### ISSUE TITLE
Memory leak on master ?

### ISSUE THREAD

**Issue by carnaval** [JuliaLang/julia#10159]
Running the test suite on current master (1 worker) makes resident memory usage go up to more than ~1GB. The live set (from the gc pov) is only a few 100s of MBs.
Without other evidence I would obviously tend to blame the gc patches, but I still see this behavior with MEMDEBUG (to avoid the pool allocator changes) and only full sweeps (to avoid generational issues).
Valgrind is not very helpful and mostly sees (small) leaks from LLVM allocations, but I'm not very familiar with the tool so it may be a chair-to-keyboard-interface error.
I will investigate the issue more in depth but if someone has an idea in the meantime ...

**Comment by timholy** [comment]
Just a thought, does the total memory usage include JITed-code, and your "live set" does not?

A quick check would be to check out a version of julia before the merger of your patches and perform the same tests.

**Comment by carnaval** [comment]
No it should not. The buffers holding machine code, as well as the whole LLVM object forest, are outside the GC's reach. Maybe we are leaking some of those ?
Running the testsuite as of commit gc_merge^ shows the same kind of memory growth (i.e., can't complete the testsuite on this "low ram" box).
Even if we end up not needing it to fix this one, I think it would be good to bite the bullet at some point and write code to generate some kind of heap summary to break down memory usage between the gc managed part, LLVM's data structures, generated machine code, shared library code, ...

**Comment by JeffBezanson** [comment]
JITed code would also be my guess. We know we don't free it, and we also know the test suite spends a lot of its time generating code. The reason is probably that the nature of tests is to loop over every combination of things, and we generate code for each combination.

It's very hard to free generated code, since if we guess wrong that something won't be needed again we'd end up re-compiling it repeatedly, which might be even worse.

**Comment by fundamental** [comment]
I have some code which has been appearing to leak quite a bit with recent versions of master. I'm hoping that I can reduce this down to a reasonably sized test case, though currently I can't load the data needed to trigger the issue without HDF5.jl which is currently broken due to the Tuple changes. Hopefully I'll be able to update this with a minimal piece of code that leaks in a few days.

**Comment by fundamental** [comment]
I'm not sure if this is the original issue is the one that I've narrowed things down to, but there certainly seems to be a leak in the handling of deprecated function. Reading through the code in base/deprecated.jl it doesn't look like this should be the case, yet running something like:

```
function make_a_leak()
    data = rand(200,2)
    y=0
    for i=1:1000
        y+=median(map(int,data))
    end
    y
end
````

seems to trigger a memory leak which can be repeated indefinitely. This may or may not be the whole of what I was experiencing, though most libraries are currently in a state where there's some deprecated API usage so they may all be leaking some from this behavior.

Version info on the image that was tested:
```
Julia Version 0.4.0-dev+4527
Commit 9ec6ae1* (2015-04-27 11:56 UTC)
Platform Info:
  System: Linux (x86_64-slackware-linux)
  CPU: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by tkelman** [comment]
I believe the depwarn leak was fixed, I had seen it too a few months back. Open a new issue if you can come up with anything that convincingly leaks.
