### ISSUE TITLE
Should we expect floating point indexing to be implemented?

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#10154]
Handling `(get/set)index(::AType, ::FloatingPoint....)` is inconsistently implemented for `AbstractArray` subtypes in base and in user defined types for many packages.  Should we expect this case be handled when defining `(get/set)index` behavior for user defined types?  This needs to be documented (or a generic fallback defined), related to #10064.

**Comment by JeffBezanson** [comment]
In more detail, we call `to_index` in operators.jl on "non obvious" index types, and it does things like convert to Int.

I've never really liked this. This is a case where the types can accurately reflect what is *actually* supported (namely, integers). I wonder how useful it is in practice to be able to index with integer-valued floats, and get an InexactError for non-integer values, which is what we do now.

**Comment by jiahao** [comment]
cc ApproxFun.jl authors @dlfivefifty @ajt60gaibb any thoughts?

**Comment by jakebolewski** [comment]
I can see how this is useful functionality for `AbstractArray` subtypes, in that floating point indexing is useful when you want a user defined type that is represented as a function but is "array like".  This is used in `Interpolations.jl` for instance.  If this is useful then we should define a generic `AbstractArray` fallback.

I don't think this is useful for general types, such as indexing into a tuple.

**Comment by jakebolewski** [comment]
However, in the continuous case `size` cannot be defined so in that sense these types cannot be thought of as `AbstractArrays`

**Comment by andreasnoack** [comment]
Has the ability to overload `call` changed the need for non-integer indexing?

**Comment by SimonDanisch** [comment]
I like that you can index textures with floats in GLSL and get interpolated values back. But it's probably not justified to put something like this in Base, as it should rather live in an interpolation package.
Which is actually a case against explicitly allowing for floats, as an interpolation package couldn't overwrite it that easily than.
I'd think, that in general something went wrong if you index an array with a float.
There are a lot of use cases, where float intermediate representations are useful, but shouldn't the caller be forced, to use a function like floor,ceil, round, etc, to convert to an Integer before indexing?!
Throwing an inexact error gives me shivers, as it can lead to subtle bugs if the float is just sometimes a little bit off.

**Comment by dlfivefifty** [comment]
In the case of ApproxFun this should be sufficient, as we have moved away from the “functions as vectors” in many other respects.

**Comment by JeffBezanson** [comment]
I agree it's typically better to handle a float index by specifying floor, ceil, etc. at the call site. Much clearer what's going on.
Types that do interpolation are clearly a separate case. It's totally fine if some AbstractArray subtypes support float indexing and others don't. #10064 is about specifying the minimal core interface.

**Comment by jakebolewski** [comment]
Is there support for deprecating this behavior for `AbstractArray`'s  and other datatypes (ex. tuples) in base?

**Comment by stevengj** [comment]
@jakebolewski, we could always just deprecate `getindex(a, i::FloatingPoint...)` without specifying the type of `a`, no?

**Comment by ViralBShah** [comment]
That seems to be a reasonable approach.

**Comment by cortner** [comment]
If I may: I think this is a bad idea. In many situations, it is very convenient to not worry about types. It is one of the reasons why switching to Julia was easy for me. I started a discussion at [Google groups](https://groups.google.com/forum/#!topic/julia-users/sEUvnjvtryI)

**Comment by SimonDanisch** [comment]
Can you give good examples, where this actually hurts?
I cried a little, when `convert(Int, FloatingPoint)` was starting to throw `InexactError()` errors. 
But it actually made my code quite a bit safer and wasn't that hard to ship around.

**Comment by nalimilan** [comment]
I had the same feeling as @cortner, but I failed to find good examples of where it's useful. I'm sure there are valid cases. (And this feature is much less dangerous than automatic rounding conversion from float to int, there is no loss of information here.)

**Comment by dlfivefifty** [comment]
This change revealed several type in-safeties in my code, where what started as an int became a float: k/2 instead of div(k,2).  So I'm in favour.

The deprecating of int() at the same time is a bit annoying, but given that it's ambiguous whether it means integer part or round, I'm ok with that.

**Comment by IainNZ** [comment]
Only time I've used this is to select percentiles lazily, e.g.

```
n = 927
x = rand(n)
sort!(x)
@show x[n/4]
@show x[3n/4]
```

but the "cure" is `div`. I think the real problem will be people not knowing about `div`.

**Comment by mbauman** [comment]
Well if folks like my proposal to refactor getindex on AbstractArrays (#10525) then one of my reasons for liking this change will go away.  As Tim noted, `Real`'s placement in the type hierarchy makes extending getindex particularly tricky and annoying (https://github.com/JuliaLang/julia/pull/10458#issuecomment-77957672).  If we only have one getindex method defined for AbstractArrays (without specializing on the indices), then that concern is no longer relevant.

I still think this is a sensible restriction to make, but I'd be open to reconsidering it now.

**Comment by jiahao** [comment]
As I had posted [on julia-users](https://groups.google.com/d/msg/julia-users/sEUvnjvtryI/vqYTsxlMX2sJ), an edge case shows up when indexing with floats in regions where epsilon > 1: 

```jl
julia> (1:10^17)[1e16:(1e16+5)] #Not the same as indexing with (10^16:10^16+5) 
5-element Array{Int64,1}: 
 10000000000000000 
 10000000000000000 
 10000000000000002 
 10000000000000004 
 10000000000000004
```

**Comment by cortner** [comment]
I think it should be easy enough to throw an exception when a conversion is not "safe".

**Comment by cortner** [comment]
Re use cases: it occurs e.g. when I compute an index using `round`, but more generally I've stumbled over it a few times. Always easy to fix, but annoying.

**Comment by cortner** [comment]
@dlfivefifty : I am not convinced about the type instability. When there is a performance issue then a programmer who actually cares will be able to find it. Julia provides very nice tools to find type instability.

**Comment by dlfivefifty** [comment]
Probably wasn't much performance impact, but it did bother me that something I called k was becoming a float...it's very unlikely I would have found this otherwise.  (More unlikely that it would ever make a difference however..)

My feeling is 99% of cases where get index is called with float are unintentional.

(I do kinda think down the line there should be a "relaxed" mode where Julia is not so picky though..)

**Comment by jiahao** [comment]
> I think it should be easy enough to throw an exception when a conversion is not "safe".

@corrner If the index doesn't round, sure. However, I don't think it is so easy to tell in the example I gave whether or not that behavior was intentional or a mistake. Maybe someone forgot to round the index set. But maybe someone genuinely intended to do precisely that. Trying to second-guess a user's intent is a dangerous rabbit hole to go down.

**Comment by jiahao** [comment]
AFAIK only Matlab/Octave and Mathematica support indexing into an array with a float. Maple, C, Python, Fortran do not.

**Comment by StefanKarpinski** [comment]
For dense arrays, this is not such a big concern since indexing into a `Float64` vector with a length of `maxintfloat()` requires 64 petabytes of data. For sparse data structures, of course, this can actually happen, although I suspect it's still rare to have integral dimensions that are that large.

**Comment by johnmyleswhite** [comment]
Once we have COO arrays, I think you should expect to see a lot of integral dimensions outside of the 2^52 range.

**Comment by cortner** [comment]
But I still argue that one can simply throw an exception when the conversion is unsafe.

**Comment by jiahao** [comment]
@cortner and my point is that you _cannot_ tell in my example whether it is "unsafe".

**Comment by cortner** [comment]
@jiahao , I think your example shows that it is unsafe to use float-indexing for numbers > 1/eps.

**Comment by jiahao** [comment]
Also, this is not just an academic counterexample when it comes to `Float32`s. `maxintfloat(Float32)` is 2^24, and there are already quite a few data sets of this size. (See the [Network Repository](http://networkrepository.com/networks.php) for some examples.)

**Comment by cortner** [comment]
For Float32, float-indexing is unsafe for indices > 1/eps(Float32)

**Comment by jiahao** [comment]
@cortner Julia allows indexing with an arbitrary index set. `x[ [10^16, 10^16+1] ]` is a valid indexing operation. It is tempting but incorrect to think that `x[ [1e16:(1e16+1.0)] ]` might do the same thing, but it doesn't. Instead, it does the same thing as  `x[ [10^16, 10^16] ]`, which is _also_ a valid indexing operation. To claim that this operation is "unsafe" is to make a subjective judgment call on user behavior  which uses valid, unambiguous (if not necessarily intuitive) semantics.

**Comment by cortner** [comment]
I understand all the arguments (to some extent anyways), all I keep saying is that you are taking the point of view of a computer scientist and not that of a numerical analyst / user. One of the nice things about Julia is that, if I don't want to, then I don't need to worry about types. But suddenly now I do.

In all honesty, it is a relatively minor issue, but many such minor issues taken together will make Julia a less attractive language for teaching, for casual programmers, and maybe even for programmers in general. I plan to collect a list of examples along the same lines and will post them at some point.

**Comment by jiahao** [comment]
If we lived in a world where all floating point numbers had epsilon <= 1 I would agree that floating point indexing is much less of a problem. However, we don't live in that world, so we have the problem of balancing the "convenience" of writing `A[1.0]` against the "problem" of indexing with large floats. All I'm cautioning against is any concessions to convenience that come at the expense of overall semantic consistency.

**Comment by SimonDanisch** [comment]
Hm you're slowly convincing me, as it now reminds me of `[a => b]` becoming `Dict(a=>b)`, which also made me quite sad...
Maybe move these kind of checks into Lint.jl, or something comparable?
So someone who wants safety, can still get it, and someone who just wants to play around doesn't have to think much about types and conversions.
This doesn't address @jiahao's concern of semantic inconsistency though....

**Comment by nalimilan** [comment]
@jiahao If floating point indexing is forbidden, then it's obviously not considered as "valid". Thus, allowing a subset of those operations gives more freedom to users, so I don't see the problem about it being a "judgement call".

FWIW, also add R to the list of software that allow indexing with floats.

**Comment by quinnj** [comment]
I think it all depends on how you look at it. There have been several
people who have posted about how they've found bugs/type issues in their
code due to this change and are grateful for this change. In a teaching
situation, we have right there some great examples to help explain why this
certain restriction was chosen; more so as an overall design decision than
a "correctness" decision and here's why.

I also don't think it's too terrible to define your own float getindex
methods if you have your own use case for them. There may be legitimate use
cases and if it really makes sense for a package, they can define their own
and use them or as a user, put it in your .juliarc file.

**Comment by jiahao** [comment]
@nalimilan I think you may be conflating "forbidden" with "not defined". If we define this method to work, it should do something reasonable for _all_ valid inputs of that given type. I'm not opposed to something like
```jl
if 0 <= floatidx < maxintfloat(typeof(floatidx))
    idx = round(Int, floatidx)
    return A[idx]
end
```

The unresolved question in my mind is what should happen otherwise. One possibility is to assert that users should never do this and raise an error. Another possibility is to assume that users know what they are doing past this point and do the same thing as in the block I wrote. If it is not clear what this method should do then the most conservative choice is to not define it in `Base`.

**Comment by tkelman** [comment]
Another good candidate definition for the MatlabCompat.jl package?

**Comment by nalimilan** [comment]
@jiahao I think the proposal is to raise an error when indexing above `maxintfloat`. People who know what they are doing can still convert manually to an integer beforehand (as currently).

@tkelman But also into RCompat.jl then. I don't really like the idea of encouraging alternative definitions for core functions like `getindex(::AbstractArray, ...)` in supplementary packages. This means `[]` won't have the same meaning depending on the background of the person who wrote the code, and contrary to a convenience function it's not easy to find out where it comes from.

**Comment by cortner** [comment]
@tkelman That is a possibility, but to be honest I would prefer to not have to rely on a package, which may or may not be updated on time with new versions of the language.

**Comment by mbauman** [comment]
@cortner Is your main objection that you are already calling `round` (or similar) and don't like the verbosity and type-fiddliness of `round(Int, …)`?

**Comment by cortner** [comment]
@mbauman the short answer is *yes*; it seems small when said like this, but it is a matter of principle. I want to have the choice to not worry about types. And it is not so much myself I am worried about, as I will get used to it, but I think these sort of design decisions will play against Matlab and R users converting to Julia.

**Comment by johnmyleswhite** [comment]
>  I want to have the choice to not worry about types.

I don't really think that's a viable choice, even though it's occasionally been claimed that you don't have to worry about types. Right now, the type inference system really only lets you ignore types if you exclusively work with `Int`, `Float64` and `Array{Float64}`. Even with that caveat, conflating `Int` and `Float64` poses serious problems for both performance and correctness. (It's not an accident that both Matlab and R made themselves more "user-friendly" by discouraging users from ever using any integers.)

As soon as you work with strings (let alone a custom type), you discover that you need to know a lot about the type system before you can write efficient code in Julia. You need to know which types are abstract, so that you can make sure that you never include those types as fields in a type; you need to know which visually similar values (e.g. `0` vs `0.0` / "foo" vs "fóo") have distinct types, so that you can avoid writing code that has variables with performance-damaging type uncertainty.

As such, I think it would be unwise for the Julia community to claim that you have a choice to not worry about types. We could only achieve that if we adopted a radically more limited type system and removed integers completely from the language.

Since that won't likely be happening, I think it's a virtue of the debated indexing change that it encourages users to make sure that they never think of integers and floating-point numbers as interchangeable, since they manifestly are not interchangeable in Julia's current state.

**Comment by dlfivefifty** [comment]
I can imagine a new user doing something like 

A=[1,2]
A[1]=2.4

where you definitely do have to worry about types.

**Comment by StefanKarpinski** [comment]
Yeah, I don't really buy the "you don't have to worry about types" thing – because that will last all of about a day – but I still think that we should in general do conversions automatically when they're safe and obvious. I'm not really convinced that the fact that you may have *previously* lost precision when computing a floating-point value is the concern of the indexing operation.

**Comment by jakebolewski** [comment]
@cortner, @StefanKarpinski  why should indexing for arrays be special cased here?  Do you think that most users define indexing for all subtypes of `Real`s for user defined types?  Almost no one does.  To index consistently across all user defined types you have to explicitly convert to an `Int` anyways.  Reasoning about `Int`s in the system is inescapable.  

In fact, indexing by floating point values is not even consistently defined in `Base`.   For example, the dense case is defined:
```julia
julia> A = randn(3,3)
3x3 Array{Float64,2}:
 -1.44595   1.07011    2.06128
 -0.46673   0.406243   3.70655
 -0.564156  0.494642  -0.936865

julia> A[1.0,1.0]
-1.4459545197847976
```

but for sparse arrays, and much of the `AbstractArray` subtypes it is not
```julia
julia> SA = sprandn(3,3,1.0)
3x3 sparse matrix with 9 Float64 entries:
	[1, 1]  =  -0.294094
	[2, 1]  =  0.00830028
	[3, 1]  =  -1.11293
	[1, 2]  =  0.304284
	[2, 2]  =  -0.786085
	[3, 2]  =  -0.591092
	[1, 3]  =  0.648532
	[2, 3]  =  1.72333
	[3, 3]  =  -0.0314884

julia> SA[1.0,1.0]
ERROR: MethodError: `getindex` has no method matching getindex(::Base.SparseMatrix.SparseMatrixCSC{Float64,Int64}, ::Float64, ::Float64)
Closest candidates are:
  getindex(::AbstractArray{T,2}, ::Any, ::Any, ::Any, ::Any...)
  getindex(::AbstractArray{T,N}, ::Real)
  getindex(::Base.SparseMatrix.SparseMatrixCSC{Tv,Ti<:Integer}, ::Integer)
  ...


julia> Diagonal(A)[1.0,1.0]
ERROR: MethodError: `getindex` has no method matching getindex(::Base.LinAlg.Diagonal{Float64}, ::Float64, ::Float64)
Closest candidates are:
  getindex(::AbstractArray{T,2}, ::Any, ::Any, ::Any, ::Any...)
  getindex(::AbstractArray{T,N}, ::Real)
  getindex(::Base.LinAlg.Diagonal{T}, ::Integer, ::Integer)
  ...
```

@mbauman work would help here for subtypes of `AbstractArray`, but that still does not address the behavior for user defined types.  We could obviously export the conversion and promote it as the way to do indexing but that would be a big change to the Julia code which is currently out in the wild.

**Comment by StefanKarpinski** [comment]
To be clear, I'm kind of ambivalent about this. It's annoying how inconsistent this is across all of Base and various packages. I don't think that indexing is an exceptional case – I want a more consistent policy. But to have such a policy, I think we need to have a reason why we draw the line where we do. Currently, it's a very wiggly line.

**Comment by johnmyleswhite** [comment]
For me, the bright line is just that indexing shouldn't use floating-point numbers in addition to allowing integers. The rationale I see is that:

* Allowing floats doesn't increase the expressive power of the language
* Allowing floats increases the amount of code that has to be written, documented, tested and maintained
* Allowing floats contributes to encouraging people to develop a bad habit of conflating integers and floating point numbers

For me, floating point indexing is almost entirely lose-lose. It's kind of cute that it works, but it's not cute enough to justify its existence in the absence of some other compelling rule that would imply it ought to exist.

**Comment by jakebolewski** [comment]
I just want some consistency in the interface as well, but I agree with @johnmyleswhite's points which is why I proposed the change.

**Comment by dlfivefifty** [comment]
I would say as someone who has not really used MATLAB/R that it wasn’t “cute” but “bizarre” to find out that float indexing works… I just checked Mathematica (which does distinguish between Ints and Floats) which turns out also supports Floats as an index..but it would be bizarre if Mathematica’s behaviour wasn’t bizarre :)

**Comment by goretkin** [comment]
In the world where floats can be an index to an array, I'm confused about whether `a[3.9]` would be an error or whether there would be rounding.

If the proponents of that world think it should be an error, then we might as well allow `a["4"]`. There are many strings that don't represent integers, just as there are many floats that don't either. It's harder for strings to arise from numerical computations than it is for floats, but I think it would be consistent with doing a best-effort interpretation of a float index, right?

I don't think that's the right way to go, but doesn't it seem like either you'd have both or none?

**Comment by nalimilan** [comment]
@goretkin Currently: 

```julia
julia> Int(3.9)
ERROR: InexactError()
 in call at base.jl:36

julia> Int(4.0)
4

julia> Int("4")
ERROR: MethodError: `convert` has no method matching convert(::Type{Int64}, ::ASCIIString)
```

So it's not like float -> int and string -> int aren't treated differently already; "both or none" doesn't sound like a sufficient rule.

**Comment by cortner** [comment]
@goretkin `"4"` is not a number but a string; `4.0` is a number.

**Comment by dlfivefifty** [comment]
If BigInt("4") works then so should Int("4")...

**Comment by cortner** [comment]
I just want to say this discussion got the attention I had hoped for and I am very happy with this, even if the developers decide to stick with integer-only indexing.

Just to reiterate, the much bigger issue for me is, that it would be great if the Julia developers could bear in mind that the majority of users and potential users (all of Matlab and R!) of the language are not and don't want to be computer scientists. Possibly I am wrong on this particular issue, but I just think decisions like having to write `i = round(Int, x)` instead of `i = round(x)` (so I can now use `i` as an index; and btw I can't write `Int(a)` if `a` is an vector, I have to write `Vector{Int}(a)`) and `Dict(a=>b)` instead of `[a=>b]` and `Float64[ f(x) for x in X]` instead of `[f(x) for x in X]` put me off just a little bit. It makes it a little less pleasant to write Julia code and having too many such cases will make teaching in Julia and conversion to Julia much harder.

**Comment by dlfivefifty** [comment]
I have to say that I agree with all your examples, other than float for getindex 😀

**Comment by nalimilan** [comment]
Related debate: array constructors that accept any real: https://github.com/JuliaLang/julia/issues/4275, https://github.com/JuliaLang/julia/pull/9776

**Comment by garborg** [comment]
@cortner I've worked mostly using Stata and R doing economics and statistics in academia and business, and I suspect I'm in the minority, R- and Matlab- user-wise, but...

I think writing `Int(a)` if `a` is a vector is the greater evil -- special casing certain operations like that both obscures what that step is doing, and is, to me, idiomatic in a bad (inconsistent) way and more to store in one's head for newcomer and old user alike. `map(Int, a)` and `Vector{Int}(a)` seem like plenty -- with the latter hinting that conversion, not construction, is happening, and the former handling other cases (or if one prioritizes brevity over giving maximal hints to readers).

I'm more on the fence about floating point indexing, but I'm mostly bugged by running into libraries implementing it inconsistency, or partially -- I've never actually missed it personally.

**Comment by dlfivefifty** [comment]
I think having one command that converts both vectors and scalar to a type is convenient for writing functions that work both on scalars and vectors.  int(a) is cleaner than isa(a,Vector)?Vector{Int}(a):Int(a)

**Comment by StefanKarpinski** [comment]
Mapping `Int` already has this property:

```
julia> map(Int,1.0)
1
```

This is an argument in favor of considering scalars to be container-like.

**Comment by garborg** [comment]
@dlfivefifty IMO those are two separate issues -- either we want that behavior for callable things, not just conversion/coercion (in which case `map` or a special syntax for mapping -- open discussion in #8450 -- is the way to go), or we decide on balance to forgo it. I'd be sad to see it special cased again.

**Comment by ScottPJones** [comment]
Interesting discussion here... but I ask, why *shouldn't* you be able to index by a floating point value (either binary or decimal)?
I've spent almost 30 years as one of the developers/architects for a language/database system where that is done all the time... it is heavily used (you're medical information is most likely stored using it,
if you live in the US, England, Sweden,  Scotland, and many other places around the world... or if you get arrested in Belgium! :grinning:)
Basically, any string can be used as an index into a multidimensional associate array, and they
are sorted (a B+tree is used for persistent variables, and a ptrie is used for in-memory variables)
using a particular collation rule, which defines the numeric collation and string collation behavior.
The rule says 1) whether you have pure string collation, or where all numbers come first, sorted by numerical value [up to around 510 digits]), and 2) if there is some country/language specific collation sequence (i.e. like Spanish or French, where you want estas and estás to sort before estandar)

The indices (subscripts) all get encoded in a wonderfully special way :grinning: so that "" sorts before everything, then all numbers (including floating point), and then all strings (unless the rule says to treat numbers as strings)... Unicode is also encoded in a very packed format, so that you normally have things sorted by the Unicode code points, but still can have collations where FOO and foo both sort before FOOBAR (case insensitive - but they are still distinct).

So, it is quite frequent to have an array with index with subscripts like "-100.234" 0.123e-6 12345.

It would be extremely limiting IMO if Julia did not allow for AbstractArrays to be able to handle this...

**Comment by timholy** [comment]
#10525 is about to change this, in a way that's easy to make systematic.

**Comment by ScottPJones** [comment]
@timholy that will be just what I need, actually, to implement associative arrays... I have to dig into this, will I be able to have an arbitrary number of dimensions? Some customers had many many dimensions (10 or more easily!)

**Comment by timholy** [comment]
Yes, you'll be able to have arbitrary dimensions. "Easy & generic" arbitrary dimensions await #10911, but you can "hand-generate" all the methods you need up to some fixed dimensionality.

**Comment by stevengj** [comment]
@ScottPJones, it sounds like you are thinking of the `Dict` type (i.e. an associative array).  `Dict` can indeed be indexed by anything you want.  If you want ordering, then you can use an `OrderedDict` or a `PriorityQueue`, depending on your needs.

**Comment by ScottPJones** [comment]
@stevengl I'd want an ordered, multi-dimensional Dict then... also, can Dict's sort numerically?  I hadn't thought so... but there is so much I don't yet know in Julia... (I also want a persistent OMD [ordered, multidimensial Dict :grinning:] I also have to look if Dict's allow any string, including "", as a key...

**Comment by stevengj** [comment]
@ScottPJones, an `OrderedDict` can sort by any comparison function that you want.   And yes, they allow any Julia object as a key, including empty strings.

**Comment by kmsquire** [comment]
Actually, an OrderedDict maintains the insertion order of elements.  A
SortedDict will maintain the sort order.

I started working on a patch to sort OrderedDicts a while ago, but never
finished it.  I guess now would be as good of a time as any...

Cheers,
   Kevin

On Sat, Apr 25, 2015 at 6:51 PM, Steven G. Johnson <notifications@github.com

**Comment by stevengj** [comment]
Thanks @kmsquire, I got the two confused.

**Comment by StefanKarpinski** [comment]
> I've spent almost 30 years as one of the developers/architects for a language/database system where that is done all the time... it is heavily used (you're medical information is most likely stored using it,
> if you live in the US, England, Sweden, Scotland, and many other places around the world... or if you get arrested in Belgium! )

@ScottPJones, Please stop giving your resume whenever you're making an argument. [Argument from authority](http://en.wikipedia.org/wiki/Argument_from_authority) is actively counter-productive in having a reasoned debate. Someone who has only been programming for a year could just as easily be right while people who have been programming for decades are wrong. If you can't make a solid argument without falling back on authority, you don't have a good case. Experience is a great resource, but it should provide good examples from which solid arguments can be made, not serve as a replacement for making a compelling case.

**Comment by ScottPJones** [comment]
@StefanKarpinski Sorry about that, I was *not* trying to make an argument from authority, I hate that myself, but rather based on my experience, of real world applications, and the rest of that comment was an attempt to give an example of just what is done where people do want to use sorted floating point keys, coexisting with sorted, collated strings.
