### ISSUE TITLE
USE_BLAS64 build warning on arm

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#10173]
I see this build warning when the sysimg is being built. However, when I actually run `check_blas()` later, everything works fine. I am wondering if some other corruption is leading to this warning.

````
Warning: error initializing module LinAlg:
ErrorException("BLAS and LAPACK are compiled with 32-bit integer support, but Julia expects 64-bit integers. Please build Julia with USE_BLAS64=0.")
````

After compilation, I do:
````
julia> Base.check_blas()

julia> (_, info) = LinAlg.LAPACK.potrf!('U', [1.0 0.0; 0.0 -1.0])
(
2x2 Array{Float64,2}:
 1.0   0.0
 0.0  -1.0,

2)

julia> Base.USE_BLAS64
false

julia> sizeof(Base.LinAlg.BlasInt)
4
````

**Comment by ViralBShah** [comment]
cc: @ihnorton

**Comment by physicsd00d** [comment]
I am getting the same error on the odroid XU3 (after commenting out three assertions in constants.jl) and the build still fails later anyways.  I don't understand why the error says "Julia expects 64-bit integers" when I'm compiling on an ARMv7 which is 32-bit.  Why does julia expect 64-bit?  Does it not realize this is a 32-bit system?

**Comment by tkelman** [comment]
Are you using system blas? We need to change the default to disable `USE_BLAS64` when using system blas.

**Comment by physicsd00d** [comment]
I don't think so.  Make.arm: override USE_BLAS64=0.  Make.inc: USE_SYSTEM_BLAS= 0.  And the error seems to indicate that it worked too, right?  Since my BLAS is apparently (correctly) in 32-bits.

**Comment by tkelman** [comment]
This could be a bug then, the conditions that the error is checking for might be returning incorrect values for some reason.

**Comment by physicsd00d** [comment]
In Make.inc, for an arm $ARCH, BINARY is never set to anything.  Adding [this rule](http://stackoverflow.com/a/25817631) to my makefile, i get
```
$ make print-BINARY
BINARY =
```
I'm not sure what that means for its usage in deps/Makefile.  I'll try forcing it to 32 on my next build attempt.

I also notice that 
```
$ make print-JCFLAGS
JCFLAGS = -std=gnu99 -pipe -fPIC -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -fsigned-char
```

I don't understand the penultimate flag but google tells me "This forces all file access calls to use the 64 bit variants".  I assume this must be a bug since I'm on a 32-bit machine.  I'll remove that flag on my next build attempt as well.

Possibly related to assertion errors involving Float64() at https://github.com/JuliaLang/julia/issues/10235#issuecomment-80518594 ?

**Comment by tkelman** [comment]
You may be on a 32 bit machine, but your filesystem is presumably larger than 32 bits in size?

**Comment by physicsd00d** [comment]
I'm not totally sure what you mean by that.  The root partition is ext4 (with 21G free) so I think it does indeed have Large File Support, but i'm seeing some other threads on the internet where people are complaining about LFS failing due to improper glibc configurations and some other people complaining about similar LFS issues on an ARM.  

As a disclaimer, this is really all mostly over my head.  I'm just poking around here because I want julia on this odroid.

**Comment by ViralBShah** [comment]
It would be nice to fix this. Doesn't seem to affect things.

**Comment by ViralBShah** [comment]
I don't see this warning anymore, and everything else appears to be ok.
