### ISSUE TITLE
travis builds libgit2, pcre unnecessarily

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#10205]
travis likely doesn't need to build libgit2 every time as part of the julia test build. perhaps there's a ppa with the right version? or maybe canonical already has it?

**Comment by tkelman** [comment]
There are a few different ppa's with at least 0.21 last I checked, I don't know whether or not the bindings in their current state can be made to work for either 0.21 or 0.22, or if we'll have to pick one and use it everywhere. At the moment it's not super important, and we can move whatever version we need into the juliadeps ppa if we need to and Elliot has time.

I may not have implemented `USE_SYSTEM_LIBGIT2` properly yet, I can't remember.

**Comment by nalimilan** [comment]
Julia builds fine with libgit2 0.21 on Fedora 21, with `USE_SYSTEM_LIBGIT2=1`.

**Comment by tkelman** [comment]
If anyone can find a way to install a binary of gfortran without sudo on Ubuntu 12.04 (Nix, Guix, or linuxbrew maybe?), we should probably play with doing our Linux Travis builds on the Docker workers where we can cache things.

**Comment by vtjnash** [comment]
How about the official distribution channel: https://gcc.gnu.org/wiki/GFortranBinaries (See link on page to gfortran.org)

**Comment by tkelman** [comment]
Good call, these might work http://gfortran.com/download/x86_64/snapshots/

**Comment by JeffBezanson** [comment]
Can we just get `USE_SYSTEM_LIBGIT2` working on travis? It'd be nice to shave a few minutes off every build. Can we also avoid building Rmath? I don't think anything in the build+tests uses it.

**Comment by JeffBezanson** [comment]
Looks like we are also building and testing PCRE. Surely that can be skipped.

**Comment by ViralBShah** [comment]
It would be nice to just move RMath build to work reliably with BinDeps and out of Base.

**Comment by tkelman** [comment]
We can't use system libgit2 or pcre on Travis yet because they're still on Ubuntu 12.04 which has old (if any) versions of these libraries. We need @staticfloat to get some time to build up-to-date versions of them in the juliadeps PPA, or find some other PPA that has the latest versions for 12.04.

**Comment by staticfloat** [comment]
I seem to remember trying to get PPAs of this on 12.04 previously, but running into lots of issues with build dependencies being very far behind.  It may be worth another look soon, to see if anything has changed.

**Comment by tkelman** [comment]
I added some detailed timing to the `make install` step on Travis in #11622. As you can see from https://travis-ci.org/JuliaLang/julia/jobs/67145335, building the docs takes about 60 seconds (we could turn that off on travis if anyone feels like figuring out the best way to do that), and compiling libgit2+pcre+openlibm+all of Julia's C code takes another 120-150 seconds. Compared to building inference taking nearly 300 seconds (150 on osx), each stage.

I don't think this issue is a big enough deal to worry about. When Elliot gets these packaged into the PPA, great, we'll use them then. In the mean time, time would be better spent trying to make codegen faster. Or we could go with @vtjnash's idea of checking in inference32.ji and inference64.ji, but I'm not sure that's a good idea since it goes against distro policies and it could end up masking failure-to-bootstrap bugs.

**Comment by staticfloat** [comment]
To give a little bit of a progress update, I've emailed the debian packager of PCRE to see when he plans on updating so I can just port his work over.
