### ISSUE TITLE
argument parsing: make `--` argument terminate parsing

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#10226]
See discussion here: https://groups.google.com/forum/#!topic/julia-users/lahbdoIImcQ

When parsing options to `julia` encountering a `--` argument should terminate option parsing and treat the rest of the arguments as simply part of `ARGS`.

**Comment by jsbee** [comment]
any update on this?

**Comment by jakebolewski** [comment]
`--` now terminates argument parsing, but the example highlighted in the google groups issue stil does not work because julia loads foo.jl with arguments bar & baz but then tries to load bar as a source file and fails because bar does not exist.  One way to fix this would be to disallow loading a script and running an additional source file at the same time.

```shell
julia -i -L foo.jl -- bar baz
```

**Comment by StefanKarpinski** [comment]
Perhaps the `-i` flag should be what forces interactive mode and thus causes arguments to be considered as arguments rather than scripts. Alternately, the `--` could signal that everything after it should go verbatim in `ARGS` – implying that they are not the names of scripts to be loaded.

**Comment by jakebolewski** [comment]
The second option will not work because `julia --longarg foo -- src.jl` is a valid way to write `julia --longarg=foo src.jl` using `getopt` style parsing.

**Comment by StefanKarpinski** [comment]
Says who? Don't we get to dictate what the `--` means for parsing options and arguments to `julia`?

**Comment by jakebolewski** [comment]
Unfortunately no if we are using the system `getopt` library (which we are currently). `julia` just see's the argument buffer that  is left over from command line parsing.

**Comment by StefanKarpinski** [comment]
Ok, that's annoying, but it also seems reasonable to me that `-i` should force arguments to go into `ARGS` instead of being used as scripts. Currently `julia script.jl` and `julia -i script.jl` behave the same way except that `isinteractive()` is false in the former and true in the latter. Might as well make the `-i` flag a little more useful than that.

**Comment by jakebolewski** [comment]
`--load` doesn't really have to exist.  Is it just to save a toplevel `require("src.jl")` call in a source file?

**Comment by tkelman** [comment]
> Might as well make the `-i` flag a little more useful than that.

While I agree that the `-i` flag currently doesn't serve a whole lot of purpose, encouraging its use more places is not necessarily a good thing... Running a script with `-i` can easily stop and block for user input, because that's an entirely reasonably thing to do in some places when `isinteractive()` is true.

**Comment by StefanKarpinski** [comment]
How about scanning the arguments for `--` *before* even passing them to `getopt`? That way we're not subject to what `getopt` thinks that `--` should mean, but we can rely on `getopt` for the rest of the option parsing.
