### ISSUE TITLE
Hash error due to overloading of == for custom types

### ISSUE THREAD

**Issue by karanveerm** [JuliaLang/julia#10267]
We have overloaded the `==` operator for custom types that we have defined. They do not return a boolean value. This hasn't been an issue so far, however with https://github.com/JuliaLang/julia/pull/10167, https://github.com/JuliaLang/julia/blob/master/base/hashing2.jl#L184 will throw an error:
```
ERROR: TypeError: non-boolean (Convex.EqConstraint) used in boolean context
 in hash at hashing2.jl:184
 in hash at hashing.jl:3
```

I know there are restrictions on which operators shouldn't be overloaded (such as `+(a::Int64, b::Int64)`), but I don't think there should be restrictions placed on operators being overloaded in arbitrary ways for custom types. Should `==`  be considered basic enough that it cannot be overloaded? Or is there some way I could avoid this error?

Ref: https://github.com/JuliaOpt/Convex.jl/issues/67

**Comment by tkelman** [comment]
You should be able to avoid the error by defining a specialized method for `hash` on your type. If the old definition of `hash` was working for you, you could just copy it but specialized for just whichever subtypes of `AbstractArray` are defined in Convex.jl.

**Comment by tkelman** [comment]
cc @IainNZ has PkgEvaluator been down for over a week? Running `Pkg.test("Convex")` on latest master should have caught this sooner...

**Comment by ivarne** [comment]
We put great effort into ensuring that all functions in Base have a documented meaning, and that all the methods of a function work in a similar way. In lots of cases we've split functions to ensure consistency, and enable generic programming. 

When code uses `==` in a generic fashion,  it expects it to take two arguments, and return true, if the arguments are equivalent,  and false, if they are not. You can define == however you want, but you will get undefined behavior when you pass the object to generic code. It might work sometimes,  but then you get an error when you exercise a different code path (eg adding more elements to a Dict,  so that it needs to be rehashed)

**Comment by IainNZ** [comment]
@tkelman it has been down, first due to GnuTLS stuff and now due to some mystery problem. I've been holding off filing issues for the most part on 0.4 unless they have a clear error message and a fairly obvious fix.

**Comment by mlubin** [comment]
@karanveerm, we're probably going to remove operator overloads for comparisons from JuMP (in favor of macros) because of this and similar reasons. I tend to agree with @ivarne that changing a comparison operator to return something other than boolean goes against the idea of generic programming.

**Comment by karanveerm** [comment]
Thanks, this makes sense. I'm closing the issue now.

**Comment by ivarne** [comment]
Note that after d61befa, you can fix this specific issue by defining `isequal` and `==` differently, but that doesn't solve the general issue of generic code that assume generic functions has a generic meaning.
