### ISSUE TITLE
Can we have print_color and println_color?

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#10327]
Title says it all really. We currently have just `print_with_color` which is verbose and almost every time I've used it I've wanted to have a new line. Hence my "request". I will even invest the 10 hours required myself to make the PR ;)

**Comment by dpsanders** [comment]
How about a color=true keyword argument for the print and println functions? Or is that a bad idea performance-wise?

**Comment by dpsanders** [comment]
Sorry, ignore my uninformed comment...

**Comment by JeffBezanson** [comment]
It seems like a perfectly reasonable comment to me! (am I missing something?)

Generally underscores are unsatisfying. `print_color` should ideally be separated into two concepts: print and color. A keyword argument would be one way to do that.

**Comment by IainNZ** [comment]
Keyword argument sounds good too. I'll make a PR in that style

**Comment by dpsanders** [comment]
Great. Rather than color=true, I guess it would be rather color=:blue

Any chance we could also allow the spelling colour...?  ;)

**Comment by ivarne** [comment]
@dpsanders What would happen if you specify both?

**Comment by TotalVerb** [comment]
`Base.println_with_color` exists and just needs to be exported. I see there is some concern with underscore names though, so perhaps this is not desired?

**Comment by TotalVerb** [comment]
I don't think that a keyword argument would be practical. Since there's no dispatch on keyword arguments, every reimplementation of `print` would need to accept this keyword argument (correct me if I'm mistaken). Also, `print` is used often in functions like `string`, where this additional complexity isn't needed at all. What about these other kinds of syntax?

```julia
println(with_color(:blue, "Hello World!))
```
(`with_color` constructs an object that overloads print)

```julia
with_color(:blue, println, "Hello World!)
```
(`with_color` calls the given IO function, consistent with `sprint` and similar)

**Comment by IainNZ** [comment]
@TotalVerb I like your thinking there! @vtjnash has been thinking about passing that type of information with higher-level `IO` types as well, I can't find the PR though

**Comment by vtjnash** [comment]
yep. this is another issue that https://github.com/JuliaLang/julia/pull/13825 would solve (and is very similar to what @TotalVerb described)

**Comment by JeffBezanson** [comment]
Now Implemented as `printstyled`.
