### ISSUE TITLE
NegatedIndex type

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#1032]
Idea spawned by [this discussion](https://groups.google.com/d/topic/julia-dev/QMSgkl-gTnM/discussion). The idea is that just as writing `v[b], v[!b]` where `b` is a logical indexing vector partitions `v` into two disjoint sets of elements, writing `v[x], x[!x]` should also partition `v` into two disjoint sets of elements when `x` is a single index or a range of indices. This requires some new `NegatedIndex` type, together with `!` methods for integers and ranges and the appropriate method for indexing arrays with `NegatedIndex` objects.

**Comment by ViralBShah** [comment]
I am closing this, since this is something that can easily live in a package. Please reopen if you think otherwise.

**Comment by nalimilan** [comment]
Well, if it was to be implemented, it would make much more sense in Base than in a package, since it would affect all indexing.

Would the recent changes in array indexing make this easier to implement efficiently for any number of dimensions? @timholy @mbauman?

**Comment by timholy** [comment]
I'd suggest putting this into SubArray as a valid index type---eventually `A[negated(1:15,3), :]` would return a SubArray anyway.

**Comment by mbauman** [comment]
Well, #10525 would allow us to define this once and transform the complement to direct indices (or potentially even doing so without any intermediates).  

One thing I realized the other day is that we *almost* have a negated index type already in base.  It's the complement IntSet.  If IntSets were not in the range 0:(typemax(Int)-1), but instead 1:typemax(Int), it'd actually simplify quite a bit of their implementation.  And it'd make `IntSet` much more useful for indexing… especially if we start using BitArrays as their bit-storage.

**Comment by nalimilan** [comment]
Cool. But AFAIK the order of elements is not defined for `IntSet`, while for indexing it really matters.

**Comment by mbauman** [comment]
It's [documented](http://docs.julialang.org/en/release-0.3/stdlib/collections/#Base.IntSet) as being sorted, which seems sensible.

**Comment by mbauman** [comment]
Ah, and yes, my changes in #10331 for indexing with `Colon` fix Jeff's concerns above.

**Comment by tpapp** [comment]
Would #13157 allow "negated" indexes for array-like constructs with named indexes? (which map keys to indexes, like `NamedArray`, which already has its `Not` construct)

**Comment by mbauman** [comment]
Not directly, no.  Both SubArray and fallback non-scalar indexing have converged to simply re-index into the stored or passed indices. The difficulty with using IntSets and complement types as indices is that they do not directly support fast indexed access. I don't want more special cases, so that means doing what we do with logical vectors: transform them to normal index vectors after checking their bounds.

Perhaps the only action item for Base is to change the `Base.to_index` API to accept the array and index dimension so there's enough context to transform a negated index. That would allow this to live in packages and work uniformly.  It still requires some funny business, though, since a NegatedIndex must be an `AbstractArray` to dispatch properly, but it'd really only implement `checkbounds` and `to_index`.
