### ISSUE TITLE
Floating points and exponentiation

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#10393]
Consider the following expressions:

```julia
julia> (1-0.8-0.2)^2
3.0814879110195774e-33
```
```julia
julia> (1-0.8-0.2)^2.5
ERROR: DomainError:

 in ^ at math.jl:258
```

The approach in MATLAB/Octave is to not fail and instead return a complex:

```MATLAB
octave> (1-0.8-0.2)^2.5
ans =  7.0291e-57 + 2.2959e-41i
```

What is the desired approach in Julia?

**Comment by johnmyleswhite** [comment]
Well, since Julia code has to return a predictable type, returning a Complex is not a real option.

**Comment by juliohm** [comment]
@johnmyleswhite, we should simply ignore such weird corner cases then? The domain error is conservative, I like it.

**Comment by nalimilan** [comment]
In Julia, you have to write `Complex(1-0.8-0.2)^2.5` or `(1-0.8-0.2+0im)^2.5` in order to allow for a complex result (not sure whether this was the meaning of your question).

**Comment by juliohm** [comment]
@nalimilan, the question was basically about the floating point issue near 0, I personally like the domain error that is emitted.

**Comment by nalimilan** [comment]
Ah, OK. I'm not sure there's much to do, that's the general issue with floating point values. The error message could be made more explicit, like for `sqrt(-1)`, so that people do realize that the value is not exactly zero as they may have expected. (As somebody who doesn't use complex numbers often, the behavior of Matlab/Octave you showed is indeed less obvious...)

**Comment by JeffBezanson** [comment]
Yes, we're not planning to change this behavior.

**Comment by jiahao** [comment]
Again, please note that issues are for bug reports, not general questions.

**Comment by juliohm** [comment]
This is not considered a bug report?

-Júlio

**Comment by JeffBezanson** [comment]
This is a legitimate topic to raise. It just happens to be something we're fairly set on and not considering changing.

**Comment by juliohm** [comment]
Thanks Jeff.

-Júlio

**Comment by tkelman** [comment]
This has been raised before, not that long ago. DomainErrors can cause issues if you're sending Julia functions as callbacks to C libraries. See https://github.com/mlubin/NaNMath.jl for the simple type-stable approach of returning NaN instead of DomainError for real-valued versions of these functions.
