### ISSUE TITLE
@parallel and zip()

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#10435]
Consider this code:

``` julia
A = eye(3)
B = {A,A,A}

for (a1,a2) in zip(B,B)
  a1+a2
end
```

It works fine. If I add `@parallel (+)` it fails with:

> exception on 1: ERROR: MethodError: `getindex` has no method matching getindex(::Base.Zip2{Array{Any,1},Array{Any,1}}, ::Int64)
>  in anonymous at no file:1471
>  in anonymous at multi.jl:1320
>  in run_work_thunk at multi.jl:617
>  in run_work_thunk at multi.jl:626
>  in anonymous at task.jl:6

**Comment by JeffBezanson** [comment]
`@parallel` only handles certain ranges that it knows how to partition.

**Comment by ivarne** [comment]
Would implementing `getindex(::Base.Zip2{Array{Any,1},Array{Any,1}}, ::Int64)` actually fix this issue (as the error message indicates), or will other problems regarding parallelism need to be solved too?

In that case, we should have a type assertion on the supported types, instead of a `MethodError`

**Comment by malmaud** [comment]
The ranges need to have `getindex(_, ::Int)` and `getindex(_, ::UnitRange{Int})` defined. I defined those for `Zip2` and got this to work. As @jakebolewski mentioned in #12712, the general solution to this problem is to do something like Chapel does. 

But in the meanwhile, we should probably either automatically call `collect` on the range or print a better error. 

I'll vote for the former: there's a risk that more memory than the user expected will be consumed, but it has to be weighed against the inconvenience that there are many finite iterators in common use which will seem to mysteriously not work in parallel loops.

**Comment by juliohm** [comment]
Is this issue relevant? What is the current status?

**Comment by malmaud** [comment]
Still relevant, no change in status

**Comment by juliohm** [comment]
It seems that `@parallel` doesn't have a great future as discussed in https://github.com/JuliaLang/julia/issues/19578. I like that proposal.

I will close this issue because it is not relevant to me anymore. Please feel free to reopen it if it is something that should receive more attention.
