### ISSUE TITLE
`Pkg.add` looks at every file in `METADATA.jl`

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#10480]
When I run `Pkg.add`, `julia` seems to unnecessarily `open` and `read` nearly every single file in `METADATA.jl`.  On a slow/busy filesystem, this can take a very long time.  Specifically, running the command

```
$ strace -e open julia -e "Pkg.add(\"DataStructures\")"
```

outputs the following (here's an excerpt):

```
open("METADATA/TrafficAssignment/versions/0.0.4/sha1", O_RDONLY) = 15
open("METADATA/TrafficAssignment/versions/0.0.4/requires", O_RDONLY) = 15
open("METADATA/Trie/versions/0.0.0/sha1", O_RDONLY) = 15
open("METADATA/Trie/versions/0.0.0/requires", O_RDONLY) = 15
open("METADATA/Twitter/versions/0.0.1/sha1", O_RDONLY) = 15
open("METADATA/Twitter/versions/0.0.1/requires", O_RDONLY) = 15
open("METADATA/Twitter/versions/0.0.2/sha1", O_RDONLY) = 15
open("METADATA/Twitter/versions/0.0.2/requires", O_RDONLY) = 15
open("METADATA/Twitter/versions/0.0.3/sha1", O_RDONLY) = 15
open("METADATA/Twitter/versions/0.0.3/requires", O_RDONLY) = 15
```

CC: @kshyatt

**Comment by ihnorton** [comment]
Right now, Pkg has to load all of METADATA into memory in order to run the
constraint solver for dependency resolution. I guess it might be possible
to lazy-load package-specific data as it is needed, which might help on NFS
(I'm guessing that's where you see an issue?) and on Windows.

Somewhat o/t to this specifically, but I do wonder how well the current
METADATA design is going to scale to (say) 20k packages in a few years. It
may be worth considering moving this to SQLite at some point.

**Comment by garrison** [comment]
I'm assuming Pkg3 will fix this.  @StefanKarpinski, is there any sense in keeping this issue open?

**Comment by StefanKarpinski** [comment]
It does. No point keeping it open.
