### ISSUE TITLE
Modifying a running program can crash it

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#10497]
I am using the lastest `julia` `master` on Debian jessie.

Consider the following program, `program.jl`:

    println("hello")
    sleep(4)
    println("goodbye")

I run it from the commandline:

    $ julia program.jl

In the four seconds in which it is sleeping, I add several newlines to the program and re-save (using emacs):

    println("hello")
    sleep(4)

    println("goodbye")

This typically causes the program to crash with a mysterious error message, in this case:

    hello
    goodbye
    ERROR: LoadError: syntax: incomplete: invalid string syntax
     in include at ./boot.jl:250
     in include_from_node1 at loading.jl:129
     in process_options at ./client.jl:318
     in _start at ./client.jl:402
    while loading /tmp/something.jl, in expression starting on line 11

**Comment by rened** [comment]
Tried to reproduce this with 0.3.6 and current master on OSX and linux, to no avail. With vim, though.
But I dont understand why Julia would care about the file at all after it read and parsed it. I even tried to delete the file while it's running, no problems.

**Comment by StefanKarpinski** [comment]
Deleting files doesn't actually delete them, it removes the reference to the file by that name; on UNIX systems, any process that already has the file open retains a reference to it. The file is only "deleted" when there are no references anywhere to it by name or open file handle. What's happening with the reported case is that the file is being read and executed as it's read. The input is buffered, so part of the rest of the file is already in a buffer; when you change it and it reads the rest and parses it, you get a nonsensical mix of the old and the new version of the code. Possible solutions include:

- reading in the whole file when running a program like this instead of evaluating while reading
- reading in source files line-buffered so that you never buffer beyond the end of a line
- nothing; don't do this.

**Comment by garrison** [comment]
My preferred solution of course is the first one: reading in the whole file at once.

In fact, in order to cope with the status quo, most of my programs look like this:

    include("mainfunctionality.jl")
    println("include complete")
    mainfunctionality()

where I put everything in a separate file, which is read all at once, and which I can modify at will while a longer computation is running.  Having a several-hour-long computation fail because I modified a file (even something as simple as fixing a typo in a comment) got frustrating after a while.

Are there any downsides to reading the whole file at once?

**Comment by rened** [comment]
Ok, that explains why this does not happen with vim - as far as i know it saves to a new file and renames, thus letting Julia read the old file undisturbed.

**Comment by garrison** [comment]
Thanks!
