### ISSUE TITLE
Vararg staged functions not re-staging for different numbers of arguments

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#10502]
I don't know how to better explain this behavior than to show it:

```julia
julia> f() = error("not called")
f (generic function with 1 method)

julia> stagedfunction f(I...)
           :($(length(I)))
       end
f (generic function with 2 methods)

julia> f(1)
1

julia> f(1,2)
1

julia> f(1.,2.)
2

julia> f(1.,2.,3.)
2
```

It only happens if there's also a normal (non-staged) method defined on the same function.  If you remove the definition for `f()` (or make it a stagedfunction as well) `f(I...)` behaves as expected.  The oldest binary I have sitting around (from 2014-12-31) predates @Jutho's stagedcache and also exhibits this bug, so it's not the cache.  I've not dug back further, but I have a hunch that this isn't a regression.

cc: @JeffBezanson

**Comment by mbauman** [comment]
Here's another breadcrumb.  The staged function stops staging after the non-staged method is defined:

```julia
julia> stagedfunction f(I...)
           :($(length(I)))
       end
f (generic function with 1 method)

julia> f(1), f(1,2), f(1,2,3)
(1,2,3)

julia> f() = error()
f (generic function with 2 methods)

julia> f(1), f(1,2), f(1,2,3), f(1,2,3,4), f(1,2,3,4,5), f(1,2,3,4,5,6)
(1,2,3,4,4,4)
```

**Comment by timholy** [comment]
The way I hacked around this in `SubArray` was to force creation of a tuple and then dispatch on the exact tuple type:
```
julia> f() = error("not called")
f (generic function with 1 method)

julia> f(I...) = ftuple(I)
f (generic function with 2 methods)

julia> stagedfunction ftuple{TT}(I::TT)
           :($length(I))
       end
ftuple (generic function with 1 method)

julia> f(1)
1

julia> f(1,2)
2

julia> f(1,2.)
2

julia> f(1.,2.)
2

julia> f(1.,2.,3.)
3
```
If you further use the [`meta` trick](https://github.com/JuliaLang/julia/blob/5195cc82f5a0256f64900367578a75e1d76d93a5/base/multidimensional.jl#L124-L126) to force inlining then I think it won't actually allocate the tuple. (I haven't done that in SubArrays because they have to allocate tuples anyway, so who cares about one more :-).)
