### ISSUE TITLE
mmap_array fails for empty file (0-length array)

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#10516]
`mmap_array(Int, (0,), open("foo", "r"))` on an empty file `"foo"` gives:
```
ERROR: SystemError: memory mapping failed: Invalid argument
 in systemerror at /Users/stevenj/Code/julia/usr/lib/julia/sys.dylib
 in mmap at mmap.jl:35
 in mmap_array at mmap.jl:108
 in mmap_array at mmap.jl:4
```
(See also JuliaLang/JSON.jl#98.)

**Comment by quinnj** [comment]
The current behavior is an explicit check that the file size is > 0 or an ArgumentError is thrown. I guess I can see the argument that we should return a 0-length array. Do people think that would generally be a better behavior?

**Comment by stevengj** [comment]
Since 0-length arrays are valid, I think it would be better to support any length `>= 0` here.  0 length will come up as a corner case in a lot of algorithms, and it's better not to force the caller to check for that.

**Comment by kcajf** [comment]
Sorry to raise an old issue. I just encountered the following:
```
julia> using Mmap

julia> x = Mmap.mmap(open("test.dat", "w+"), Array{Float64,2}, (1, 10))
1×10 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 
julia> x = Mmap.mmap(open("test.dat", "w+"), Array{Float64,2}, (0, 10))
0×0 Matrix{Float64}
```

I would expect the second call to return a `0x10 Matrix{Float64}` instead of `0x0`. I traced the cause to the line added in this issue/PR: https://github.com/JuliaLang/julia/blob/5faad5fee902b8654880d97ed0d9e533083bded2/stdlib/Mmap/src/Mmap.jl#L196

It looks like this could be an oversight, and that line could just be replaced with:
```
len == 0 && return Array{T}(undef, dims)
```
What do you think?

**Comment by stevengj** [comment]
Yes, that seems like an oversight in d208f8dcd897202cd88f84502ef0038a4f15108b, and would make a good PR.

(On an unrelated note, it seems like the `len >= 0` check should really be `all(>=(0), dims)`
