### ISSUE TITLE
Create Special.jl: A package for numerics with special functions

### ISSUE THREAD

**Issue by yosefrajwulf** [JuliaLang/julia#10565]
I think it would be very useful to have a Julia package that standardises the special functions available for numerical computations (as opposed to having several packages for different families of functions, or no packages at all). Are there any plans for this? For an idea of which special functions to include, and what other programming languages and or systems already have please see http://dlmf.nist.gov/software/.

**Comment by jiahao** [comment]
This would be an excellent package to have. We look forward to having someone like you to try implementing it!

Have a look at JuliaLang/libopenspecfun for some functions which are already implemented in Fortran and wrapped in Julia. There's also open issues about wrapping or translating the NSWC library.

**Comment by yosefrajwulf** [comment]
I am sorry but I cannot find JuliaLang/libopenspecfun. Do you mean JuliaLang/openspecfun? Also, does anyone have any idea, or pointers, on the performance of using C or Fortran functions and them calling them via a wrapper vs native Julia functions?

**Comment by yosefrajwulf** [comment]
Also, just for reference, there seems to be a discussion about including this (or not) in Base. See #8536 and #4301. Furthermore, if translating NSWC is not an option, how useful is it to do so with the GNU Scientific Library?

**Comment by jiahao** [comment]
Yes, without the lib.

At this point we believe that NSWC is public domain code and the risk to translating that code is minimal. GSL has an incompatible license.

Would you be interested to attempt a translation?

**Comment by jiahao** [comment]
The manual has a comprehensive chapter on wrapping external code.

**Comment by garrison** [comment]
> GSL has an incompatible license.

GSL is licensed under the GNU GPL.  With what would this be incompatible?

**Comment by yosefrajwulf** [comment]
I am, but I am afraid I do not know enough Julia just yet.

**Comment by johnmyleswhite** [comment]
> GSL is licensed under the GNU GPL

Most everything else in Julia. We've fought tooth and nail to keep ourselves unrestricted by the GPL.

**Comment by yosefrajwulf** [comment]
@garrison I had the same question and you beat me to it. However, since @jiahao has worked on GSL.jl I would suppose he has already had discussion with others about this.

**Comment by garrison** [comment]
@johnmyleswhite The GPL is not *incompatible* with the license of Julia; it's simply that the developers of Julia have decided to avoid linking with any GPL code.  There's a big difference.  In any event, if `Special.jl` is an external package, it should be fine to depend on GPL code if the developer of that package wishes, just as `GSL.jl` currently does.

**Comment by johnmyleswhite** [comment]
I think we're mostly talking at cross-purposes: the GPL is clearly *legally* compatible with the MIT license, but it is *philosophically* incompatible since the goal of the use of the MIT license in Julia is to ensure that businesses are not prohibited from doing things with Julia that they might want to do.

Having an external package under the GPL is clearly fine, but it's also clearly an issue that shouldn't be listed in this repo. But we have special functions in Base right now, where we don't want to add new GPL code.

**Comment by yosefrajwulf** [comment]
Indeed, a quick look at math.jl in base shows that there are already several special functions in Julia. However, several are missing, e.g.. orthogonal polynomials and hypergeometric functions just to name a couple. There is already a project on special functions for Julia JuliaLang/openspecfun but one of the issues is also the lack of more functions (JuliaLang/openspecfun#10). Also, the project does not seem to be very active at the moment.

Returning to the NSWC translation, the discussions in JuliaLang/openlibm#20 seems to suggest that it would be OK to do such a translation and not run into any licensing issues. Would anyone else be interested in moving forward with this? (either by creating Special.jl, or by working on openspecfun)

**Comment by jiahao** [comment]
I typed the previous message on the plane and was slightly hypoxic. GSL is GPL, so its license doesn't make any code translated from GSL it incompatible to _use_ with Julia. But the viral nature of GPL does limit its usefulness.

I wouldn't consider orthogonal polynomials as special functions that would be interesting to evaluate in the monomial basis. That would defeat the purpose of using orthogonal polynomials in most use cases I know. There's also infinitely many of them...

Someone on julia-users complained about the poor quality of the hypergeometric functions in GSL, but I'm not an expert on these things so I don't know if how to evaluate that claim.

We are developer time-limited here, so by far the best thing to do is try implementing something and see how far you get.

Closing, not because I think it's not worth doing, but because this is not actionable in base Julia.

**Comment by tkelman** [comment]
As you may have seen in one of the linked issues, the Amos code has been translated to Julia here - https://github.com/nolta/SpecialFunctions.jl

I'd need to check what the license is on the Amos functions, but it would be good to have someone with interest in this area pick up that effort and spruce up the package fully with testing, registering, documentation, etc. (Removing a Fortran dependency from base Julia would be great.) And add more functions as desired. Though anything GPL-licensed should be kept in separate repositories, no harm in doing this across several separate packages. GSL-derived code should probably start as contributions to GSL.jl.

**Comment by ViralBShah** [comment]
There has been a lot of discussion on the Amos license in many places. See details here:

https://github.com/JuliaLang/openspecfun/blob/master/LICENSE.md
