### ISSUE TITLE
linalg: print factorization objects as matrices?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#10586]
Currently, we print factorization objects as a bunch of fairly opaque internal data, which is pretty unhelpful and a bit awkward in demos. Since factorization objects are stand-ins for the original matrix, it might be clearer if we allowed e.g. `lufact(A)[i,j]` to work and printed `lufact(A)` as though it were a matrix.

**Comment by simonbyrne** [comment]
I don't know, that doesn't seem that useful to me (you can always get it from `full`), though I admit the current state is far from ideal. My first instinct is that we should print them as their constituent objects (i.e. L and U). But then we have things like pivoting, and packed storage of Householder reflections, so I'm not so sure.

One other problem would be for huge objects where there might be significant overhead for creating big objects. I don't ever want to be in the same situation as Matlab where my computer is unusable for several minutes because I accidentally printed the wrong object at the REPL.

**Comment by andreasnoack** [comment]
For these reasons, I changed how the `Cholesky` is printed to
```julia
julia> cholfact(A)
Base.LinAlg.Cholesky{Float64,Array{Float64,2},:U} with factor:
3x3 Base.LinAlg.UpperTriangular{Float64,Array{Float64,2}}:
 2.72405  0.504966  -2.22913 
 0.0      0.21541   -0.448631
 0.0      0.0        0.254741
```
which I think is better than `lufact`. I prefer either printing each factor or a short list of the fields.

**Comment by ViralBShah** [comment]
Completely unrelated, but perhaps we can show a spy plot of the factors in IJulia.

**Comment by andreasnoack** [comment]
We are heading in the other direction here. `BunchKaufman` now prints the factors but I've also realized that LAPACK needs to be changed before we can reconstruct the input of all factorizations. See http://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=14&t=4761. I'll suggest that we'll proceed with #12105
