### ISSUE TITLE
Move fzero to Base

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#10596]
I often find myself wanting `fzero` and it seems to be a simple and common enough function. I feel it would be really convenient for a lot of people to have it in Base.

 Of course, Roots.jl is a simple enough package to install - but I often see new users immediately wanting fzero, and Roots.jl is just a little further out of reach.

Cc: @jverzani

**Comment by vtjnash** [comment]
i think part of the problem with moving `fzero` to Base just how many ways there are of searching for them

**Comment by mlubin** [comment]
I don't think we should be moving numerical algorithms like this into base. Is it actually simple? The Roots package also depends on Polynomials and PowerSeries.

**Comment by ViralBShah** [comment]
Well - yeah, you are right. It would be nice to have, but then so would many other packages. We'll have to find a different way to provide a base level of functionality that includes more stuff than what is in base.

**Comment by jiahao** [comment]
I ***violently object*** to any more movement of things in and out of `Base` for the sake of "convenience". There have been far too many issues recently relating precisely to moving things in and out of `Base` which have caused many package developers enormous grief. Since it is much harder to take something out of `Base` once it's there, I urge everyone to think very carefully before repeating the disaster that was `Base.Graphics`. 

We we really need is a more comprehensive discussion of what belongs in `Base` and what doesn't.

**Comment by quinnj** [comment]
I think we need to revisit the discussion/idea of "Base packages". These
are stand-alone packages, yet are automatically bundled/included in some
way to the standard Julia installation; yet just as easily *excluded* with
the flip of a switch. There are several of these already living in Base and
we should find a clean way of managing the separation.

**Comment by ViralBShah** [comment]
JuliaBox comes with a set of packages, mainly due to user demand, because it is not easy to add packages in user space right now.

**Comment by tkelman** [comment]
> I think we need to revisit the discussion/idea of "Base packages".

I think everyone likes the idea, what we need is people to experiment with implementations. Where do default packages get bundled, what do we do about managing/upgrading them after they're installed, etc.

**Comment by tknopp** [comment]
@jiahao I cannot understand why removing Base.Graphics was a disaster. Its pretty clear that a restructuring cannot happen without breaking packages. That is the reason why it is done in an `unstable` master branch. Keeping all packages and master always stable will in the end lead to situations where everybody is afraid breaking something. In that case `master == stable` and we do not need releases anymore.

@tkelman: True. I think this is also on hold as long we do not have package precompilation in place. This would allow for a different implementation

**Comment by jiahao** [comment]
Removing Base.Graphics was a disaster because we did not understand the cost of doing so. It is one thing to make breaking changes; it is another to realize that it will take dozens of unbudgeted man-hours to recover from the fallout of those changes. If it were up to me I'd rather have all that time back to work on something more productive.

**Comment by StefanKarpinski** [comment]
That's not on the menu – the breakage had to happen sooner or later and sooner is better than later.

**Comment by jiahao** [comment]
Personally, working on fixing Base.Graphics was not a good use of my time. It would help if we could make these kinds of breaking changes easier to deal with. Anyone else who wants to help with that kind of thankless work is a better person than I am. And I will leave it at that.

**Comment by tkelman** [comment]
The breakage didn't have to be as bad as it was, but hindsight's 20/20. For one thing using the same name for the new package as the former base module was not a great idea.

Breaking existing packages and user code on 0.4 is inevitable, we can try to minimize it but only so much. The real nasty PITA problems start happening when the fixes to make things work again on 0.4 manage to break things that previously worked on 0.3. Otherwise people are starting to make 0.4-only packages, which is ridiculous since we're still quite a ways from an RC, and still rightfully telling non-developers to avoid 0.4.

**Comment by timholy** [comment]
@jiahao, I hear your pain. I have been dragging my feet for months on some changes I know I should make: split HDF5 and JLD into separate packages, and break Images up into at least 3 separate packages. In the short term there is absolutely nothing gained by making these changes, and they are (1) quite a lot of work, and (2) guaranteed to screw things up for somebody.

**Comment by JeffBezanson** [comment]
I think trying to find better structure and organization is more important than getting new functionality. And actually, just *moving* the Base.Graphics code out of Base is not really the desired outcome. We should take the opportunity to do more redesign where appropriate.

**Comment by catawbasam** [comment]
I'd like to second the concerns about our packages, especially under 0.3.    
While it is clear the language must continue to evolve, and that this will involve breaking changes, a healthy package ecosystem is also critical to Julia's success. 

The package ecosystem pulse at http://iainnz.github.io/packages.julialang.org/pulse.html paints a worrisome picture.  Perhaps some re-balancing in favor of package updates is warranted?

**Comment by timholy** [comment]
Can you clarify, what about the picture is worrisome? On 0.3 both the number and percentage of passing packages seems as high as ever. (There do seem to have been a number of 0.4 breakages that haven't been fixed.)

**Comment by catawbasam** [comment]
Sure.  In the 'Testing status changes' plots for 0.3, we have 'Package doesn't load' trending downward in both absolute and percentage terms between April and early October.  There are several times when multiple packages broke, but recovery was fast in every case.  

In January and February, the number and percentage of packages that do not load in 0.3 moved up.
The number and percentage of packages with failing tests has been trending up since October.

Here is a heavily rescaled clip of the 0.3 percentage chart that focuses on packages with problems:
![image](https://cloud.githubusercontent.com/assets/1277811/6807583/af8863e0-d225-11e4-8453-32f2cdf84c8f.png)

**Comment by JeffBezanson** [comment]
I can't think of a good reason more packages would start failing in 0.3. Is it because people are changing packages for 0.4 and listing incorrect version dependencies? That doesn't seem likely to me.

**Comment by StefanKarpinski** [comment]
There's no drop in packages working on 0.3 – the drop is on 0.4, which is to be expected and will bounce back given a bit of time.

**Comment by JeffBezanson** [comment]
That's what I thought, but @catawbasam said 0.3. Is that right?

**Comment by IainNZ** [comment]
Just found this issue! Sorry there are no updates on package evaluator this week, I'm travelling and it hasn't been made automatic again after a refactoring.

There has perhaps been an increase in "package doesn't load" percentage on 0.3, but it may be due to new packages wrapping binary dependencies that aren't bundled. Its a small increase regardless. "Tests pass" is pretty stable (the dip you see ~3 weeks ago was due to refactoring of how the testing is done, and it seems to be steady again now).

On 0.4, I'd say things have been surprisingly good given there is no real expectation in my mind that they should work. I don't really file issues regarding 0.4 problems unless its a very-high-use package - I will start filing them once we get a release candidate to try to crank numbers up to higher before release though.

**Comment by mbauman** [comment]
The only significant effect I see from glancing through a sampling of the test logs is that there are a good number of packages that still seem to be broken from the move to Vagrant on Feb 28 (https://groups.google.com/forum/#!searchin/julia-users/vagrant/julia-users/yQoHC8AYt2o/h3Pj0MTbyoIJ).  It looks like most of the broken packages have been that way for a very long time or never passed.

**Comment by IainNZ** [comment]
Btw if you want to look at the percentage plot, go to
http://pkg.julialang.org/test03per.svg
and use your browser to zoom

**Comment by IainNZ** [comment]
It worth noting that only 28 packages don't load on 0.3, or 5%. You can filter them using `More Options` on the main package listing. Several are abandoned, some others have binary stuff and should possibly just be excluded from the testing system (I occasionally look into these ones myself, but prefer PRs)
