### ISSUE TITLE
socket on server is still open after client closed socket

### ISSUE THREAD

**Issue by freddycct** [JuliaLang/julia#10601]
On server
```
julia> server = listen(2000)
TcpServer(active)

julia> socket = accept(server)
```
On client
```
julia> cl_socket = connect(2000)
TcpSocket(open, 0 bytes waiting)

julia> isopen(cl_socket)
true
```
On server
```
julia> isopen(socket)
true
```
On client
```
julia> close(cl_socket)

julia> isopen(cl_socket)
false
```
On server
```
julia> isopen(socket)
true
```

isopen(stream) → Bool
Determine whether a stream is open (i.e. has not been closed yet). If the connection has been closed remotely (in case of e.g. a socket), isopen will return false

**Comment by vtjnash** [comment]
this is correct. the question of whether a socket is open is a weak and generally useless statement, it may be worth considering un-exporting the `isopen` function. a better question in general is whether the stream has set `end-of-file` (whether it can be read). as a side effect, `eof` will determine set the `isopen` flag to false, so that future calls to `eof` will be able to return quickly.

```julia
julia> eof(socket)
true

julia> isopen(socket)
false

help?> isopen
search: isopen

Base.isopen(stream) -> Bool

   Determine whether a stream is open (i.e. has not been closed yet).
   If the connection has been closed remotely (in case of e.g. a
   socket), "isopen" will return "false" even though buffered data
   may still be available. Use "eof" to check if necessary.
```
