### ISSUE TITLE
Should inv of a Cholesky factor return a Cholesky factor

### ISSUE THREAD

**Issue by dmbates** [JuliaLang/julia#10611]
I may be the person responsible for the initial decision to have `inv(C)` return a matrix rather than a factorization but, if so, I have changed my mind.  If the inverse exists it will be positive definite and will have a Cholesky factor that is the inverse of the Cholesky factor of `C`.  Returning a `Cholesky` (or `CholeskyPivoted`) object from `inv(C)` will provide more information than simply returning a Matrix.  If you just want the matrix you can use `full(inv(C))`.  But having a `Cholesky` object returned will automatically give you the information that the result is positive definite.  There are occasions when you want to do things like evaluate
```julia
PDMat(inv(cholfact(X'X)))
```

which is going to form the product of the inverse factor then turn around and factorize it again.

Of course, it may be difficult to create the same behavior for `inv` of an `LU` object so this could be a bad idea in that it doesn't generalize.

**Comment by StefanKarpinski** [comment]
Makes sense to me. It seems perfectly reasonable to return a special type for inv when possible and and just compute a full inverse when it doesn't.

**Comment by andreasnoack** [comment]
I think this is a good idea and will add it to my to do.

**Comment by andreasnoack** [comment]
There is a problem here. The usual Cholesky is the _forward_ Cholesky which takes the form ◣◥ and LAPACK lets us chose if we want to store the upper or lower triangular matrix. However, the inverse takes the form ◥ ◣, i.e. the _backward_ Cholesky and we don't have a type for that version. I'm not sure it is worth the trouble to add a backward Cholesky type. This might also explain why LAPACK returns the triangle of the _full_ inverse instead of the Cholesky factor of the inverse.

**Comment by toivoh** [comment]
Would it make sense to have a general `Inverse{T}` type to wrap factorizations where both multiplication and division are fast, swapping the two?  Or would that provide too limited functionality?

**Comment by tkelman** [comment]
An `Inverse` wrapper type seems somewhat redundant with the Factorization types we have, which already support both efficient division and multiplication.

**Comment by toivoh** [comment]
My thought was that instead of having to create specialized `InverseCholesky`, `InverseQR`, `InverseLU` etc factorization types, we could get (more or less?) the same behavior with a single `Inverse` type.

**Comment by andreasnoack** [comment]
I think the positive definite case is slightly special here since I believe it is the only case where you sometimes want the actual inverse and not just the factorization, e.g. when calculate estimated variances of estimators in statistics. In that case you'd probably prefer the actual inverse instead of the factorized version. For now, I've made `inv(Cholesky)` return a `Hermitian` type.

**Comment by andreasnoack** [comment]
I'll close this. It will require a lot of new definitions to support and it's not supported in LAPACK. If a good proposal comes up later then we can reconsider.

**Comment by ViralBShah** [comment]
+1
