### ISSUE TITLE
Binary package for Julia: "target architecture mismatch"

### ISSUE THREAD

**Issue by rekado** [JuliaLang/julia#10639]
I finished packaging Julia for GNU Guix (here's the package recipe: http://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/julia.scm).  When I build it locally I can use it just fine, but when I download a binary substitute from the build farm and run it I get this error:

    rekado@node087:~$ julia
    Target architecture mismatch. Please delete or regenerate sys.{so,dll,dylib}.

Our [OpenBLAS package](http://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/maths.scm#n1020) is built with "DYNAMIC_ARCH=1".

We are not passing MARCH or ARCH as make flags when building Julia ([should](https://github.com/JuliaLang/julia/issues/8119) [we](https://github.com/JuliaLang/julia/issues/9473)?).

Here's the complete build log produced by the build farm: http://hydra.gnu.org/build/346508/log/raw

**Comment by ronisbr** [comment]
Hi @rekado,

I had the same problem in the past.
Can you please try what was proposed in issue #9473?
My problem was caused because I was not passing the MARCH flag to `make install` command.
You can also see my RPM SPEC used to build OPENSUSE packages here:
https://build.opensuse.org/package/view_file/home:Ronis_BR/julia/julia.spec?expand=1

Thanks,
Ronan

**Comment by tkelman** [comment]
Sorry, yeah, you might want to check DISTRIBUTING.md but it's also likely way out-of-date. The Fedora, Debian, openSUSE, etc packaging recipes will likely also be instructive. By default the Julia system image will get compiled using the fastest native instruction set possible on the build machine, which is not what you want for a redistributable package. You should set `MARCH` to something like `pentium4` for 32 bit or `x86-64` for 64 bit. I've been meaning to simplify these together and combine all the flags for creating portable binaries into a single setting, `JULIA_PORTABLE = 1` or something similar - #9372 just haven't gotten around to it yet.

**Comment by tkelman** [comment]
@nalimilan if you have a minute could you check over DISTRIBUTING.md and make any edits for out-of-date info there?

**Comment by nalimilan** [comment]
It's pretty up to date AFAICT. I updated it after `MARCH` was introduced. This section explains it all:
https://github.com/JuliaLang/julia/blob/master/DISTRIBUTING.md#target-architectures

I'm not sure about `make install`, but passing the variables to both steps doesn't hurt. I think nothing gets rebuilt if you first call `make all` or `make release debug` (and not only `make`), and pass all the `USE_*` variables to `make install`. This is because `make install` does not merely check that `release` and `debug` are up to date: it runs them again anyway:
```
install: $(build_bindir)/stringreplace doc/_build/html
        @$(MAKE) $(QUIET_MAKE) release
        @$(MAKE) $(QUIET_MAKE) debug
```

Any idea why we couldn't make them dependencies instead? It's unintuitive that you need to pass build flags to `make install`.

**Comment by vtjnash** [comment]
it used to be that you couldn't run release and debug in parallel, but that's (mostly) fixed now so this could indeed be changed. fwiw, though, the net result should be the same.

**Comment by rekado** [comment]
Thanks for all the comments.  I will update the package recipe to pass the `MARCH` make flag.  For x86_64 I'll pass `MARCH=core2`, for i686 I'll pass `MARCH=pentium4`.

However, I'm not sure what to pass for armhf and mips64, both of which are supported by Guix in addition to x86_64 and i686.  Suggested LLVM flags are `-march=arm -mcpu=generic -mattr=+v7,+vfp3,+d16,+thumb-mode,+thumb2` and `-march=mips -mcpu=mips3 -mattr=+n32`, respectively, but I suppose the `MARCH` flag isn't meant to hold all these feature flags.

Should I just pass `MARCH=arm` and `MARCH=mips` or is there a way to also specify a list of features?

**Comment by ihnorton** [comment]
You can use LLVM_FLAGS for the other stuff (see `Make.arm`). However, I would prefer not to distribute ARM binaries until we have a solid handle on the tests there. I don't think it is very useful to give people an easier way to run a known-broken system.

No idea about MIPS.

(Closing for now, ping the issue if this should be reopened)

**Comment by tkelman** [comment]
> I don't think it is very useful to give people an easier way to run a known-broken system.

It is useful for nightlies, since getting ahold of binaries can help people save some time who have the right hardware and would like to help debug things. It's not so useful on the release branch since major changes to accommodate arm or other platforms are much less likely there.
