### ISSUE TITLE
unintuitive type conversion in constructor with parametric type

### ISSUE THREAD

**Issue by shashi** [JuliaLang/julia#10641]
```julia
julia> immutable X
           a::Float64
           b::Float64
       end

julia> X(1, 1)
X(1.0,1.0)
```
But,
```julia
julia> immutable Y{T <: Number}
           a::T
           b::Float64
       end

julia> Y(1, 1)
ERROR: MethodError: `convert` has no method matching convert(::Type{Y{T<:Number}}, ::Int64, ::Int64)
This may have arisen from a call to the constructor Y{T<:Number}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  convert{T}(::Type{T}, ::T)
 in call at base.jl:36
```
I was expecting it to convert the second argument to a `Float64` and infer T to be `Int64`

@one-more-minute pointed out a way to make this work
```julia
julia> Y{T}(a::T, b) = Y{T}(a, b)
Y{T<:Number}

julia> Y(1,1)
Y{Int64}(1,1.0)
```

I was wondering if this is a good default behavior

**Comment by JeffBezanson** [comment]
The generated default constructor is `Y{T}(a::T, b::Float64) = Y{T}(a, b)`, so `Y(1,1.0)` works.

I believe we did this because otherwise when a new "outer" constructor is added it is too easy for it to be circular. E.g. people would write

```
Y(a, b) = Y(a, convert(Float64, b))
```

which would overwrite the default constructor and call itself.
