### ISSUE TITLE
Strange error messages for unary `\`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#10677]
Unary `\` (which is not defined) gives a strange error message when used with a number:
```
julia> \1
ERROR: syntax: extra token "1" after end of expression
```

When used with a variable, the error message is also not quite what I would expect:
```
julia> \pi
ERROR: MethodError: `*` has no method matching *(::Function, ::MathConst{:π})
Closest candidates are:
  *(::Any, ::Any, ::Any)
  *(::Any, ::Any, ::Any, ::Any...)
  *{T<:Number}(::Bool, ::T<:Number)
  ...
```

**Comment by dhoegh** [comment]
The parser expands the expression to:
```
julia> :(\pi)
:((\) * pi)
```
  Which is the reason for the strange error.

**Comment by JeffBezanson** [comment]
I have a pending fix for this, but it alters some of the cases mentioned in #8994. We used to parse `* : 2` as `Expr(:(:), :(*), 2)`, and `- : 2` as `Expr(:call, :-, Expr(:quote, 2))`, since `-` is unary and `*` is not. That's pretty wonky. With my change, the first one gives a `"*" is not unary` error, and the second one gives a `space after : used for quoting` error. If you want to write those expressions, you have to parenthesize the operator, `(*):2`. Hopefully this is ok. It seems to make the syntax much more predictable.
