### ISSUE TITLE
`isdiagonal` method?

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#10739]
I propose creating a new `isdiagonal` method, which will return `true` if the matrix is diagonal and `false` otherwise.  This will act similarly to MATLAB's `isdiag` or R's `isDiagonal`.

I'm thinking that for a scalar it should return `true`, just as `ishermitian` currently does.

Thoughts?

**Comment by garrison** [comment]
Actually, `istril` and `istriu` are already implemented, and indeed they both return true for scalars.

In fact, we could define `isdiagonal` (or `isdiag`, if we choose to follow MATLAB) as follows:

    isdiagonal(m) = istril(m) && istriu(m)

**Comment by tkelman** [comment]
Not sure this is worth adding the export for. We have a dedicated type for matrices that are structurally diagonal, it should be encouraged to use that (and flesh it out if it's missing any functionality that dense matrices have) rather than store numerically diagonal matrices in a structurally dense format.

**Comment by garrison** [comment]
If I am using the dedicated type for diagonal matrices, I already know that `isdiagonal` is true.  Here I am interested in taking a general (possibly dense) matrix and testing whether it is diagonal.  (In fact, having this could even be useful test if I e.g. want to optimize a code path so that it uses the special diagonal type if a dense but diagonal matrix is passed to it.)

Also, as a possible counter to your point, we already have `diagm` which creates a diagonal matrix in dense format.

**Comment by pao** [comment]
That's no good if your data is coming from outside the program. You may need to test it in that case (possibly as a precursor to constructing a `Diagonal()`.)

**Comment by garrison** [comment]
@pao said it better than me :)

**Comment by tkelman** [comment]
`diagm` is another one of these matlab-isms that we should probably find a way to get rid of at some point. Or put them all in MatlabCompat, or maybe as non-exported functions in `LinAlg`.

**Comment by ViralBShah** [comment]
What's wrong with `diagm`? It is a perfectly useful function. You don't always want a diagonal matrix in diagonal format, even if it is completely internal to a julia program.

I would be ok with having `isdiag`.

**Comment by tkelman** [comment]
Mostly namespace pollution. I think we should aim towards more general composable concepts rather than exporting more names for relatively simple functions just for the sake of brevity. I'm absolutely not against defining them in some module since they are certainly convenient, but they shouldn't be exported by default.

As an example all of the `sp___` names would be better-served by making the single traditional "dense" name (`ones`, `zeros`, etc) take a special matrix type as the first input. I hit this immediately as soon as I tried to write a new sparse format.

**Comment by nalimilan** [comment]
While I agree `sp*` functions would better be replaced with generic ones, I don't think `isdiag` and `diagm` fit in the same pattern: we can't make them special-cases of more generic functions. We could imagine moving all special matrix functions to a module, but moving only a few of them does not make much sense IMHO.

**Comment by ViralBShah** [comment]
I am onboard with cleaning up the sp* function names. We need a good proposal - but it would be good to do this in 0.4.
