### ISSUE TITLE
segfault in code_llvm

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#10765]
```
vavasis@vavasis-VirtualBox:~/juliahomedir$ /media/newdrive2/julia/julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+4179 (2015-04-07 06:16 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit c8c967c* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> code_llvm(lexcmp,(Array{UInt8,1},Array{UInt8,1}))

signal (11): Segmentation fault
unknown function (ip: 1667995426)
```

[pao: formatting]

**Comment by pao** [comment]
I cannot reproduce on 8fc5b4e, so this may be a recent regression due to #10747. cc @ihnorton

**Comment by ihnorton** [comment]
You can use Base.code_llvm_raw to get the previous behavior, although that
is not very useful because the function is compiled into the system
image (e.g. code_llvm shows only the declaration on 0.3). For now, if you
remove `sys.so` you can get the full IR listing.

I'll look at this tonight -- obviously it shouldn't segfault, but also to
see about making code_llvm useful with precompiled functions (probably need
to re-generate a copy).

**Comment by simonster** [comment]
Isn't this (making `code_llvm` work for precompiled functions) what #10193 is about? (cc @vtjnash)

**Comment by ihnorton** [comment]
Fixed segfault by adding a necessary safety check before trying to clone Function*.

@simonster thanks, will follow up on the saved-code issue there.
