### ISSUE TITLE
reduce machinery assumes bitwise operators are scalar

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#10838]
Here's the symptom:

```jl
julia> reduce(&,fill([true],16))
ERROR: TypeError: non-boolean (Array{Bool,1}) used in boolean context
 in mapreduce_impl at reduce.jl:316
 in _mapreduce at reduce.jl:149
 in reduce at reduce.jl:159
```

The problem was introduced in this commit: https://github.com/JuliaLang/julia/commit/5336b78819f506bdca2b68985d45557a615b3aff. The issue seems to be that this commit assumes that boolean operators like `&` and `|` can only produce `Bool` values, which is not the case, e.g. when the reduction is over arrays of booleans instead of booleans. Opening an issue since this reduce machinery is really complicated and I'm not sure what the best way to fix this is.

cc @lindahua

**Comment by lindahua** [comment]
I am looking at the issue.

**Comment by lindahua** [comment]
The issue is here: https://github.com/JuliaLang/julia/blob/master/base/reduce.jl#L313-L329

We have a specialized implementation for operator `&` and `|`, which uses an efficient short-circuit implementation, that is, for example, when the or operator is used, it returns `true` when it first time sees a `true`.

The solution is quite simple, that is, to restrict this special implementation only to `AbstractArray{Bool}` instead of generally all `AbstractArray`s.

**Comment by StefanKarpinski** [comment]
This should also be backported to 0.3

**Comment by tkelman** [comment]
Since there was a PR (#10842) for this one, makes more sense to put the backport pending label there

**Comment by mbeltagy** [comment]
In 0.3.7 reduce would work well up to point. 
For example 
```julia
reduce(|, fill(trues(5), 15))  == trues(5)
```
returns ``'true```. 

But 
```julia
reduce(|, fill(trues(5), 16))  == trues(5)
ERROR: type: non-boolean (BitArray{1}) used in boolean context
 in mapreduce_impl at reduce.jl:383
 in _mapreduce at reduce.jl:174
 in mapreduce at reduce.jl:182
 in reduce at reduce.jl:190
```
Something seems broken with the reduce machinery for BitArrays.
