### ISSUE TITLE
return type declarations

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#1090]
Provide this convenient shorthand:

```
function foo(x)::T
  ...
  return z
end
```

for this:

```
function foo(x)
  ret::T
  ...
  ret = z
  return ret
end
```

**Comment by StefanKarpinski** [comment]
My most recent thinking is that you may actually want two distinct features here:

1. return annotations on methods implicitly convert the return value to that type
2. typed generic functions, which raise errors if any method violates the asserted signature

Example of 1:

```jl
f()::Float64 = 1

julia> f()
1.0
```

Example of 2 (very hypothetical syntax):

```jl
function f::Float64 end # no methods + guaranteed return type
f() = 1

julia> f()
ERROR: TypeError: typeassert: expected Float64, got Int64
```

The reasoning is this. There are two reasons you want return-type annotations:

1. as a shortcut to make sure that every exit point of a method definition returns the same type
2. to allow type inference to reason about the return type of a generic function better (e.g. convert)

For the former, you want convert behavior, while for the latter convert behavior is bad since it introduces very non-local effects – namely that the behavior of a method can be massively and unexpected changed  by a type annotation in a totally unrelated place. Arguably, you should also only be able to put a "function type" on a generic function when it's created, not at any point in time.

See also: #210, #964, #8283.

**Comment by ScottPJones** [comment]
:+1: @StefanKarpinski I like your breakdown of the cases very much, and I want both... also I think your hypothetical syntax looks good.

**Comment by yuyichao** [comment]
@StefanKarpinski I like the idea.

I guess to handle methods with different signatures we would need to allow the extending the constraint as well just like how we extend functions now (although much more generic).

Would we create another method-definition table?

**Comment by yuyichao** [comment]
Examples of what I'm thinking about.

```julia
function convert{T}(::Type{T})::T # and somehow we need to tell the difference between this and a normal function definition. Probably by replacing the function keyword or by a macro?

function +{T<:Number}(::T...)::T
function +{T<:Number}(::AbstractArray{T}...)::AbstractArray # OK I know this example is stupid but you get the point....
```

**Comment by StefanKarpinski** [comment]
Maybe something like this:

```jl
function convert{T}::{Type{T},Any}-->T end
```

Kind of depends on how the new syntax for union all ends up looking after #8974.

**Comment by ScottPJones** [comment]
So, that means a `convert` with a Type as the first argument, any as second, must return that type?  seems pretty intuitive, and I don't think `-->` would cause any parsing ambiguities...

**Comment by mauro3** [comment]
(2) would be super cool to write performant numeric higher order functions, especially if parametric versions become available.  But even a simple non-parameteric one would be great for starters.

**Comment by evanrinehart** [comment]
One of the original reasons for return type annotations, not recently discussed here, is to easily determine from reading the signature what the return type is. Especially with a penchant for automatic conversion this can be hard to identify or verify from the body of a method, and seems like a silly thing to require reading implementation code to determine. This information, like the type of parameters in a dynamic language, could be given in a comment instead. But making it part of the language would standardize the presentation and have other uses described elsewhere. Sorry if all this is too obvious to state. Parametric return types might way beyond Julia's type system at this point and doesn't seem that crucial.

**Comment by bramtayl** [comment]
I think return types could play a very important part of any super-overloading strategy. For example, imaging a strategy which looks something like this:

```julia
type CsvFile
  file::String
end

function read(csv::CsvFile, args...)::DataFrame
  DataFrames.readtable(csv.file, args...)
end
  
function read(csv::CsvFile, args...)::AbstractArray
  readcsv(csv.file)
end
```

This kind of strategy could, hypothetically, extend IO operations like read, write, open, close, etc. to any combination of inputs and outputs

**Comment by StefanKarpinski** [comment]
@bramtayl, is that intended for return-type overloading? How would it work?

**Comment by bramtayl** [comment]
@StefanKarpinski, I'm not sure I understand your question? An important component of that particular IO system above is to classify file names into individual types: 

```julia
function classify_file_type(string)
  pieces = @> string split('.')
  extension = pieces[end]
  if extension == "csv"
    CsvFile(string)
  end
  if extension = "sqlite3"
    SQLiteFile(string)
end
```

My more general point, though, is that with coordination with package authors as well as using return type within the function overloading system, Julia could implement overloading to a much larger extent than the present.

**Comment by nalimilan** [comment]
@bramtayl I don't see how that's related to return type declarations. You can already do what you're proposing. Why do you think this would allow to " implement overloading to a much larger extent than the present"?

**Comment by bramtayl** [comment]
Maybe another example would help? Imagine that we've defined a type for a database table:

```julia
type DataBaseTable
  conn::DatabaseHandle
  name::String
end
```

Let's say that external a DataBaseTable


answer = external[[:column_1, :column_2]]::AbstractArray 
could import the the table into Julia and then find the value at index 1, 2.

But
answer = external[[:column_1, :column_2]]::DataBaseTable
wouldn't need to import anything into Julia. Instead, it could submit a select SQL command to the database to have the database create new table called answer with just columns 1 and 2, and return a DataBaseTable pointer to that object.

**Comment by nalimilan** [comment]
OK, I see. This is dispatch on return type, as mentioned above in this thread: https://github.com/JuliaLang/julia/issues/1090#issuecomment-12153946

**Comment by bramtayl** [comment]
Yup. Apparently, @johnmyleswhite arrived here first, which is surprising given his luke-warm reaction in JuliaDB/DBI.jl#8

**Comment by StefanKarpinski** [comment]
That syntax already means something – it's a type assertion that the returned value is of some type. You can accomplish the same thing, however, by making the desired type an argument of the function and dispatching on that using `::Type{T}`, e.g.: `read(DataFrame, file, args...)`.

Dispatching on return types requires expressions to have well-defined types, which makes perfect sense in statically typed languages – where every expression has a type. In a dynamic language, expression don't have types, values do. As a result, dispatch on return types doesn't make sense since it's not generally meaningful to talk about the type context in which a call occurs.

**Comment by bramtayl** [comment]
```jula
read(DataFrame, file, args...)
```
could work, but somehow the syntax seems misleading because DataFrame is not an argument, but a return type. Maybe there's a way to do this with a bit of syntactic sugar.

**Comment by dataPulvurizer** [comment]
I am new to Julia and this thread is very interesting. Is there a time scale for when return types will be implemented? I can't tell if there is consensus regarding how return types will be implemented.

**Comment by johnmyleswhite** [comment]
I think it's a safe bet to operate on the assumption that the time scale is unknown.

**Comment by dataPulvurizer** [comment]
That's unfortunate. I just listened to your presentation at juliacon 2015 https://www.youtube.com/watch?v=lf1_FhMR7xA&index=35&list=PLP8iPy9hna6Sdx4soiGrSefrmOPdUWixM were you talk about the problem with lifting for Nullable types and the need for return types. I come from the Statistics/R/C++ side and I think Nullable types are a welcome addition but I agree with the point you made about lifting. Even when declaring basic operators for example arithmetic, logical operators you certainly need to specify return types or you'll find yourself re-writing code over and over again for different cases. Otherwise you climb into some kind of rabbit hole of trying to infer types somehow fighting with inconsistent type returns and other nasties.

For Julia to be successful in the R community it definitely needs to do Nullable types simply and I think return types are important in trying to implement this.

What is the sticking point over implementing return types Julia? Is it because it is a very large effort or does it break Julia's functionality somehow? Or perhaps it is on how it should be implemented?

You mention simply tagging onto a database e.g. sqlite. What about Cassandra? It now has a C API that Julia can tag onto and its type system is sufficiently rich as to allow data to be represented however you want and of course it is a high performance big database. It may be possible to write an API that allows computation within the database itself from Julia using Julia as a command big data statistical analysis interface to Cassandra. I think I may be getting ahead of myself there.

**Comment by johnmyleswhite** [comment]
An oversimplified summary might be: you can either have a dynamically typed language or you can have static return types. Once you don't have static return types, getting the semantics right becomes much harder.

If you're interested in getting up to speed on this issue, I'd recommend going through all of the currently open issues for Julia and figuring out how they fit together. After that, you'll be in a good position to understand where things stand.

**Comment by dataPulvurizer** [comment]
Thanks for the tip

**Comment by mauro3** [comment]
Get started with Jeff's talks at JuliaCon 2014 and 2015: https://www.youtube.com/user/JuliaLanguage/playlists

**Comment by dataPulvurizer** [comment]
I am not sure if this is the right place to ask this question, but where is the "function" keyword/type implemented? I have been searching through the Julia source code and have not been able to find it.

**Comment by mauro3** [comment]
No questions go to julia-users mailing list although this one might go to julia-dev (not both though!).

**Comment by dataPulvurizer** [comment]
@mauro3 thanks Jeff's talks are very good suggestion.

**Comment by RauliRuohonen** [comment]
If this feature is implemented as originally described and one additionally defines `return_type(f, argtypes)` to return the declared return type of `f(argtypes)` if it exists and `Any` otherwise, then one could use this to define the return type of `map` more stably than with `Base.return_types` or with value-dependent computation. You could just do

    @generated function mymap(f, x)
        T = return_type(f, (eltype(x),))
        :($T[f(x[i]) for i in 1:length(x)])
    end

assuming https://github.com/JuliaLang/julia/pull/13412. Note that `return_type` only needs to work for leaf types.

This works even with functions like `exp`, which do not have a reasonable return type for the generic function more specific than `Any`. Using something like Stefan's example

>    function f::Float64 end

might seem like a reasonable restriction for `exp` initially, but then someone will want to define the exponential for BigFloats or complex numbers or matrices or some funny Lie algebras. Even for matrices you could have something like exp: SkewSymmetricMatrix -> RotationMatrix. This isn't ad hoc from the POV of Lie theory, but from the POV of the compiler's type system it definitely is. Then there's exp: Int -> Float64 and exp: BigInt -> BigFloat, which makes sense, but is also very ad hoc.

There is no hope in trying to reason about `exp` in the aggregate, but reasoning about individual methods is very doable, and seems to suffice.

**Comment by bramtayl** [comment]
Dispatching on return types could be implemented by adding a return_type keyword argument for all functions in base Julia

```{julia}
function add_together(number_1::Int, number_2::Int; return_type::Type = Number)
  if return_type <: Number
     number_1 + number_2
  else
    "$number_1$number_2" end end
```

**Comment by hayd** [comment]
Does #13412 allow a solution here? A naive idea is a return-type Function type...

**Comment by jamesdanged** [comment]
+1 to this eventually being nailed down. 
Return types would be really useful for the Atom package I just released. (Check it out!)
https://github.com/jamesdanged/Jude 
In it, I run a full syntax parse in Javascript of your Julia codebase to resolve names. It's not a huge step to do type checking. Return types would make it a lot easier to do type inference statically in a lot of situations, which could help catch a lot of errors. It would also enable better auto complete and safer refactoring capabilities. I realize that in Julia, objects are typed, not variables. But it's already good practice to write type stable code, and a lot of code actually is implicitly typed.

**Comment by stevengj** [comment]
Note that if `function foo(...)::T` is just syntactic sugar for a `convert(T, ret)::T` as @JeffBezanson indicated, it should be possible to make `T` an arbitrary expression computed from the parameters.  e.g.
```jl
function foo{A<:Number,B<:Number}(a::A, b::B)::promote_type(A,B)
    ...
end
```
This is pretty important in order have type-generic code.  We don't want to encourage a lot of hard-coded `::Float64` declarations.  (People already habitually over-type their arguments, often from the mistaken impression that it helps performance.)

However, this means that @jamesdanged won't necessarily be able to use the type declarations in any useful way from his Javascript parser.

**Comment by jamesdanged** [comment]
Though a good deal of code is generic across multiple input types
```julia
function foo{A<:Number,B<:Number}(a::A, b::B)::promote_type(A,B)
    ...
end
```

there's also plenty of code that is more simply generic that would easily benefit
```julia
function foo{T<:Number}(a::T, b::T)::T
    ...
end
```

Also, if ```promote_type(A,B)``` uses multiple dispatch
```julia
function promote_type(::Type{A}, ::Type{B})
  C
end
function promote_type(::Type{C}, ::Type{D})
  E
end
```
then tooling like Jude could probably parse this.

It's probably not possible or desirable to have everything statically typed, but I think there's definitely plenty of room to incrementally type.

**Comment by martinholters** [comment]
Maybe I'm pointing out the obvious, but if we combine expressions for the return type, individual method return type annotation, and the requirement of monotonicity, the desired behavior needs to be clarified a bit. Assume
```Julia
function foo{T}(x::T)::bar(T) ... end
```
Then monotonicity would require that for any type `T1`, `T2`, if `T1<:T2`, then `bar(T1)<:bar(T2)`. So far so obvious. Now we add
```Julia
function foo(x::Int8)::Int32 ... end
```
monotonicity would definitely require that for any `T`, if `Int8<:T` and `T!=Int8`, then `Int32<:bar(T)`. But would we also require `Int32<:bar(Int8)`? At first glance, I'd say no. In fact,
```Julia
function /{T<:Number}(x::T, y::T)::T ... end
function /{T<:Integer}(x::T, y::T)::Float64 ... end
# and probably some more cases
```
doesn't look too bad. However, picking up @yuyichao's `convert` example, here it would make sense for the general declaration to enforce the return type expression on all specialized methods. Do we need to distinguish two cases here?

**Comment by stevengj** [comment]
Frankly, I think that a monotonicity requirement is unworkable and would change the nature of the language too much.  (It's certainly not a constraint that one would want to enforce in all cases, so at the very least you'd need a way to specify which return-type declarations are supposed to be monotonic and which are not.)   @JeffBezanson's initial suggestion of return types as mere syntactic sugar seems a lot more sensible to me, and doesn't change Julia semantics.

**Comment by eschnett** [comment]
It's a bit more than syntactic sugar, isn't it? I assume you can somehow query it (`return_type`?). Here is a scenario where this would be convenient:
```
function lazy_map{T}(f, xs::Vector{T})
   R = return_type(f, T)
   rs = Vector{Future{R}}()
   for x in xs
      push!(rs, @remote_async_lazy_delayed f(x))
   end
   rs
end
```
Here I want to allocate a collection, using a specific type (here `R`) that I know only after the function `f` has finished. However, I don't want to wait until `f` has been called. I don't know how to do this without knowing (a good approximation of) `f`'s return type ahead of time.

**Comment by martinholters** [comment]
And for this, monotonicty is needed: If given a `Vector{Number}`, all individual results types should be`<:return_type(f,Number)`.

**Comment by eschnett** [comment]
If `f` is declared (or inferred) to return a type `R`, then it must do so. But that is surely a trivial statement? If `f` violates the declaration, or if type inference returns a wrong result, that would clearly a bug.

I assume you're instead speaking of different methods for the same function `f`, and want to impose certain conditions on the relation between (the return types) of different methods. For my case here, I'm only speaking of a single method `f` that might even be selected by the caller, or `f` might be a lambda expression that has only a single method.

**Comment by martinholters** [comment]
Yes, I had an `f` with different methods in mind. From your example, it is not at all clear that should not be the case. (Unless `T` is forced to be a concrete type, of course.) But even with a single method for `f`, allowing an arbitrary expression in the return type annotation, one could do crazy stuff. And yes, that probably should be considered a bug if it violates monotonicity.

Whether - or to what extent - monotonicity should be enforced by the compiler is another question, though.

**Comment by JeffBezanson** [comment]
See e.g. recent discussion in #11034. This has been discussed *a lot*.

Declaring return type `T` would cause return values to be wrapped with `convert(T, x)::T`, so you could be certain the requested type would be returned, or you'd get an error. As I see it, this really is just syntactic sugar. There is no guarantee that you can "look up" this declared type, since after all the declaration is optional. I do not acknowledge the `return_type` function.

In practice, declaring return type `T` will certainly cause the compiler to infer a type at least as specific as `T`. However making this a semantic guarantee is going too far. To the extent you can call the mythical `return_type`, you have to be prepared for it to return `Any` whenever it feels like it.

**Comment by johnmyleswhite** [comment]
> To the extent you can call the mythical `return_type`, you have to be prepared for it to return `Any` whenever it feels like it.

I still think this is worth it.

**Comment by JeffBezanson** [comment]
Fair enough --- the only question is how much people would complain when the result changes from version to version, or perhaps if you statically compile a program instead of running it with the JIT.

**Comment by toivoh** [comment]
How about a dumb implementation of `return_type` that only looks up the matching method and returns the return type that would be computed  (possibly based on abstract argument types)?
Though I guess there might not always be a matching method for abstract enough argument types (or in the case of method ambiguity, there might be several).

**Comment by JeffBezanson** [comment]
I certainly don't want to tell people to add a method to `return_type` to make the return type of their function discoverable. To me that would be far worse than the mostly-theoretical problems I described.

**Comment by martinholters** [comment]
> I certainly don't want to tell people to add a method to `return_type` to make the return type of their function discoverable.

Well, right now people have to add a method to (the somewhat misnamed) `promote_op` for that purpose. (Ok, `promote_op` is only used in a few places, but still...) Having a return type annotation automatically generate a suitable `return_type` method sounds like an improvement to me. The question is what to do about functions without return type annotation. Taking the `promote_op` way to default to `promote_type(ArgumentTypes...)` is somewhat arbitrary (but seems to be a surprisingly good heuristic), `Any` seems like a safe but potentially inefficient choice. Relying on type inference in my eyes would be way too fragile. Maybe it could even be worth to make the fact that no return type annotation is provided discoverable to switch to other heuristics then.

**Comment by iamed2** [comment]
My new package [ResultTypes](https://github.com/iamed2/ResultTypes.jl) has a really nice use case for this.

**Comment by JeffBezanson** [comment]
Ah, that is quite nice!

**Comment by StefanKarpinski** [comment]
Yes, that's really nice. On the input direction, this is similar to why I think it would be nice to do implicit conversion to the declared type of an argument, e.g.:

```jl
f(x::Nullable{Int} = 0) = x

f() # => returns Nullable(0)
```

Otherwise you have to write this as

```jl
f(x::Nullable{Int} = Nullable(0)) = x
```

which just seems obnoxiously redundant and unJulian.

**Comment by blairn** [comment]
so I'd be able to write something like...

    function groupby{A,B}(xs::Vector{A}, f::A -> B)::Dict{B, Vector{A}}
      result = Dict{B, Vector{A}}()
      for x in xs
        key = f(x)
        result[key] = push!(get(result, key, []), x)
      end
      result
    end

**Comment by mauro3** [comment]
No, this is not about function types which contain their return type.  The best you can do is:
```
function groupby{A,B}(xs::Vector{A}, f, ::B)::Dict{B, Vector{A}}
  result = Dict{B, Vector{A}}()
  for x in xs
    key = f(x)
    result[key] = push!(get(result, key, Vector{A}()), x)
  end
  result
end
```
i.e. you'd need to manually pass in an instance of B.

**Comment by blairn** [comment]
I was kinda hoping if the function knew its return type, I'd be able to use it as the key in the dictionary.

Either way, I think it is an improvement. If nothing else, it should help with the documentation.

**Comment by mauro3** [comment]
Actually, this works:
```
julia> fn(g, x)::Dict{Symbol, typeof(g(x))} = Dict{Symbol, typeof(g(x))}()
fn (generic function with 1 method)

julia> @code_warntype fn(sin, 5.6)
# ... looks good
```
Note that type-inference is fine irrespective of whether you use the return-type annotation.

**Comment by blairn** [comment]
That is pretty awesome!

I was hoping I had a way to look at a function and see what it would return for a type.
Sin returns number, but.. without handing it a number and calling it, I can't know it does that - However I'm pretty sure the compiler _does_ know.

Anyway - it is no big deal, it would make some code a bit more efficient, and make a couple of things a bit nicer. But overall? I can work around it pretty easily.

**Comment by yuyichao** [comment]
> `fn(g, x)::Dict{Symbol, typeof(g(x))} = Dict{Symbol, typeof(g(x))}()`

Not sure what this tries to achieve but FYI `g(x)` is called twice.

**Comment by mauro3** [comment]
My understanding was that the purpose is to annotate the return type.  I'm aware that this comes at the cost of two function evaluations.  Is there a way which avoids the two evaluations?  (The frowned upon) `Base.return_types` cannot do it:
```
julia> fn{X}(g, x::X)::Dict{Symbol, Base.return_types(g, Tuple{X})[1]} = Dict{Symbol, typeof(g(x))}()
fn (generic function with 1 method)

julia> @code_warntype fn(sin, 5)
# looks bad
```
But yes, probably better to leave the annotation off.

**Comment by dataPulverizer** [comment]
Hi guys, I recently came across the [Sparrow programming language](https://github.com/Sparrow-lang/sparrow) a static compiled programming language with very simple syntax, but with hper-metaprogramming capabilities, that is being able to go from runtime->compile time. I think that this is revolutionary step forward in computing and his approach would solve the challenges Julia has been facing. Since the language is static, it already has return types but it does not suffer from the problems caused by the compiler not recognising types for example the challenges with data frame (http://www.johnmyleswhite.com/notebook/2015/11/28/why-julias-dataframes-are-still-slow/).

Its something the D community has been seriously looking at (https://forum.dlang.org/thread/ne3265$uef$1@digitalmars.com). You can find the link to the creator's PhD thesis - one of the best texts I've read on programming period. I think this approach is something to be seriously considered.

**Comment by JeffBezanson** [comment]
> Since the language is static, it already has return types

I might be missing something not having read all the details, but this sounds to me like a well-understood tradeoff: yes, with a static type system you can have arrow types, and instead of performance problems from a lack of type information, you get a compile-time error.

The case of DataFrame `getindex` could be solved, for example, with something like a `@generated` function that could also see (constant) argument values.

**Comment by johnmyleswhite** [comment]
I'm hesitant to comment on an old, closed thread, but I would note that several of us have converged on translating DataFrames into row-iterators that generate rows as well-typed tuples (which is possible now that we have `Nullable` scalar objects that can handle missing values). I think it's likely that we'll simply remove `getindex` from a future variant of DataFrames rather than try to improve on it.

**Comment by dataPulverizer** [comment]
I didn't realise that the DataFrame issue was solved.  @JeffBezanson why would you get a compile-time error?

**Comment by dataPulverizer** [comment]
@johnmyleswhite does this mean that in the future DataFrames will be able to efficiently process tables with columns of arbitrary type or will the types be bound to a specific set?

**Comment by johnmyleswhite** [comment]
Let's have that conversation elsewhere and in a few months from now. :)

**Comment by dataPulverizer** [comment]
Fair enough

**Comment by JeffBezanson** [comment]
> why would you get a compile-time error?

That's generally what happens when a compiler for a statically-typed language can't figure out the type of something. Which will happen eventually. To say much more we'd have to drill down on what "approach" you're talking about more specifically. For example Sparrow supports calling functions on constants at compile time, but the name-to-type mapping in a DataFrame isn't a compile-time constant.

+1 To row iterators. I've had success using tuples and NamedTuples with that approach.

**Comment by dataPulverizer** [comment]
As far as I can see from his thesis he has developed semantics for the user to decorate what should be done in compile time and run time as well as the default state where the compiler works out what should be done depending on the nature and typing of the inputs. "If a metaprogram has bugs, it will cause the compiler to crash or behave incorrectly"  as would be the case in a run-time system. But I think he is the best person to speak about this aspect

**Comment by dataPulverizer** [comment]
I think however, it would certainly be possible to create rules that deal with this aspect as a sort of compile time exception handling

**Comment by davidanthoff** [comment]
I have a completely type stable row iterator for DataFrames in Query [here](https://github.com/davidanthoff/Query.jl/blob/master/src/sources/source_dataframe.jl). It uses [NamedTuples](https://github.com/blackrock/NamedTuples.jl) to represent rows and works great. You can write arbitrary queries against DataFrames with [Query](https://github.com/davidanthoff/Query.jl) and there are no type instability problems because that iterator essentially solves that problem

**Comment by lucteo** [comment]
@JeffBezanson one of the major points of statically-typed languages is to get errors. They show you that most probably you got something wrong. In my view, if you want efficiency, you would better be in this category of languages. Moreover, I would argue that it's really important for one to easily figure out how a particular code would be translated in the machine language (at least to some degree). If the language is allowed to do a lot of "clever" things that makes it harder for one person to actually understand the performance characteristics of the code. That inevitably leads to less efficient code. I think the example illustrated by @johnmyleswhite in http://www.johnmyleswhite.com/notebook/2015/11/28/why-julias-dataframes-are-still-slow/ is perfect here.

If, on the other hand, the language allows you to write simple code that everyone understands how it translates to machine code (again, to some degree), then, the language must make it pretty clear what run-time is. That means the language needs to create a clear distinction between run-time and compile-time. 

Yes, the distinction between run-time and compile-time can be annoying in some cases, but I would argue that those cases appear very seldom in practice. After all, we know that our programs will never be like "compiler, please solve my problem (and you should be able to infer which problem I'm referring to)"

My 2 cents,
LucTeo

**Comment by johnmyleswhite** [comment]
Let's not continue this broad design conversation on this issue as every comment sends a notification to many people.

**Comment by StefanKarpinski** [comment]
@lucteo: Julia is not currently a static language and won't become one in the future, so I'm not sure what the point of your comments is. The alleged simplicity of having semantically different compile-time and run-time phases is contradicted by the many confusions and troubles that arise from this distinction in static languages: virtual vs non-virtual methods, overloading vs dispatch, etc. – these are some of the most chronically problematic and hard-to-explain issues in static languages.

**Comment by JeffBezanson** [comment]
I'll reply on the julia-dev list.

**Comment by mauro3** [comment]
x-ref to julia-dev thread: https://groups.google.com/d/msg/julia-dev/N9mj_eI9wCE/78AwQ71YAAAJ

**Comment by gyk** [comment]
Another problem is if the argument list goes too long and you want to put the `::ReturnType` at the second line, Julia complains about invalid syntax: `"ERROR: syntax: invalid "::" syntax"`.

**Comment by yurivish** [comment]
If you put the closing `)` on the last line then it parses:
```
julia> f(a, b, c
       )::Int = 3
f (generic function with 1 method)
```

It may be more aesthetic to do it this way:
```
julia> f(
           a, b, c
       )::Int = 3
f (generic function with 1 method)
```
