### ISSUE TITLE
Windows: setting ENV changes only unicode environment variables

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#11215]
Windows does some funny things with environmental variables. There are 2 interfaces: an ASCII and a Unicode one: a problem arises in that any libraries "getting" from the ASCII one (in my case, R) won't see anything "set" by the Unicode one (which is used by Julia). 

See discussion on julia-users:
https://groups.google.com/d/msg/julia-users/hqHnMbrnHT4/qTeEkYvU5xgJ

**Comment by vtjnash** [comment]
seems like it might be more accurate to open this on the R issues tracker and ask them to be unicode compliant

**Comment by simonbyrne** [comment]
Well, yes and no: R is using the interface correctly, so while it would be nice if they would support unicode, it isn't technically a bug on their end. Also, I suspect that there are lots of other libraries that might have this problem.

What about if we defined an extra `_setenv` method for `ASCIIString`s which uses the ASCII interface? That way, the unicode interface is only used when necessary?

**Comment by ScottPJones** [comment]
I think something strange is going on here... I never saw problems like this when I ported to NT (granted, that was ages ago, back in 1992)... and we had customers all over the world, using Japanese, Chinese, etc. characters in paths, etc...
When I looked at the Windows API, it does say that when you call `_putenv`, it is duplicated both in the 8-bit (or MBCS) environment and the Unicode environment, so I'm not sure where your problem is arising.
Where is the Julia code that is setting the environment variables?

**Comment by vtjnash** [comment]
the old API wasn't always ANSI or ASCII-compatible, it might be OEM, MBCS, or locale-dependent which makes it a bad idea to try to use at all (unless you are just treating them as raw bytes and don't need to manipulate them). Julia instead currently tries to be fully unicode-compliant, including defining wmain instead of main. support for the unicode API's did not originally exist in windows 98 but was added later (http://en.wikipedia.org/wiki/Unicode_in_Microsoft_Windows)

the julia code sets the Win32 environment variables (GetEnvironmentVariable), not the posix ones (getenv). but adding support for the the posix ones is rather pointless, since they exist per msvcrt library and shared libraries on windows often load multiple msvcrt libraries these days.

**Comment by simonbyrne** [comment]
I apologise: it turns out this isn't an ANSI vs Unicode thing, but a Win32 API vs POSIX API thing: see here:
https://gist.github.com/simonbyrne/3dc6e870f7b9b9aeedae

And, if I understand their code correctly, R is using the UTF16 POSIX api:
https://github.com/wch/r-source/blob/b5a80a23b88cc29391b04231ee7fe826d5459ba7/src/main/sysutils.c#L382
(if you uncomment the `rprint` lines of the gist, they match the POSIX ones).

I don't know enough about the internals to know if this is fixable, but we probably should document it somewhere.

**Comment by simonbyrne** [comment]
And, yes, I agree that R is clearly at fault here. As per [the docs](https://msdn.microsoft.com/en-us/library/tehxacec(VS.71).aspx):

> `getenv` operates only on the data structures accessible to the run-time library and not on the environment "segment" created for the process by the operating system. Therefore, programs that use the envp argument to `main` or `wmain` may retrieve invalid information.

**Comment by ScottPJones** [comment]
I think it was always at least ASCII... (I'm not aware that it ever functioned with any character set that wasn't at least compatible with ASCII...).
I wonder it the problem with R is that R might be using the posix libraries?

**Comment by ScottPJones** [comment]
Oops - I'd made that comment last night, forgot to hit "comment"

**Comment by StefanKarpinski** [comment]
Would it make sense to set variables using both APIs and use (modified?) UTF-8 to stick Unicode strings into the old API?

**Comment by vtjnash** [comment]
> adding support for the the posix ones is rather pointless, since they exist per msvcrt library and shared libraries on windows often load multiple msvcrt libraries these days

using anything in libc on windows is actually highly problematic, since any internal state may not be common with another shared library's state. on any platform, you have to be careful with malloc/free since it is stateful. but on windows you also technically should assume that each dll may or may not have an independent mapping of file descriptors, environment variables, and signal handlers.

i'm hoping that someday microsoft will implement a real posix subsystem (for example, bsd implements linux as a compatibility layer, but without these issues), but their track record so far seems terrible.

fwiw, the wine project has effectively done almost all of the necessary work to make it possible, except for making it widely available to all of the computers that come with a windows license pre-installed.

**Comment by tkelman** [comment]
Some day midipix will be complete and we'll package it up through oneget. Until then, mind the dragons.

**Comment by simonbyrne** [comment]
I've updated the title to reflect the problem, in case this comes up again.

I don't know if it is possible, but what about a function that "updates" the msvcrt copy to reflect the system one?

**Comment by simonbyrne** [comment]
For anyone following along at home, I emailed the r-devel list [here](https://stat.ethz.ch/pipermail/r-devel/2015-May/071119.html).
