### ISSUE TITLE
About SparseVectors

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/julia#11324]
There's been a lot of debate about whether we should incorporate sparse vectors into Julia 0.4.

Here are three options:

- (A) Use ``SparseMatrixCSC`` to emulate a sparse vector. This, as many have pointed out in other issues, breaks the consistency with the dense arrays. It is also unnatural and inefficient. 

- (B) Add ``SparseVector`` to base *before* 0.4 is released.  The functionalities have been developed and tested in [SparseVectors.jl](https://github.com/JuliaSparse/SparseVectors.jl). These functionalities are relatively simple and they don't need a long time to get mature. (#8718)

- (C) Deprecate sparse vector related functions in Base, and add ``SparseVector`` to base *after* 0.4 is released. (#11323)

Personally, I don't like (A), and I am fine with either (B) or (C).

One opinion against (B) is that there can be multiple ways to represent a sparse vector. However, IMHO, the way used in [SparseVectors.jl](https://github.com/JuliaSparse/SparseVectors.jl) seems to be the most natural way, and it is consistent with both CSC and COO formats. I understand that other formats may be more suitable for certain situations. For such cases, it is not difficult to develop a new sparse vector format (using a different type name of course). 

cc: @tkelman @ViralBShah @StefanKarpinski @mlubin 

Since @ViralBShah has tagged #8718 as 0.4, and that PR was closed, I tag this as 0.4 in order to make sure that we come to a decision before 0.4 is released.

**Comment by ViralBShah** [comment]
I am in favour of (B) and to get it all right for 0.4. I don't like just removing the functionality and then adding it again later, which would break codes yet again. This will be an improvement over what already exists, IMO.

**Comment by mlubin** [comment]
Agreed that the implementation in SparseVectors.jl is an improvement over what already exists. Don't take my objection over the maturity and name too seriously if there's a consensus for option (B).

**Comment by andreasnoack** [comment]
The "inconsistency" between dense and sparse arrays doesn't go away by adding a sparse vector type. Even with a sparse vector, there is still no sparse arrays for dimensions higher than two, so I don't buy the consistency argument and therefore also not the "unnatural" argument. It might be very useful with a sparse vector type, but I think we should focus of the class of operations that could benefit from a sparse vector type and some performance measures.

**Comment by tkelman** [comment]
Here's your inconsistency argument:
```
julia> A = rand(5,5); As = sparse(A);

julia> size(A[:, 3])
(5,)

julia> size(As[:, 3])
(5,1)
```

I'm repeating myself, but I don't care that sparse doesn't generalize yet. But we're doing dimensions 1 and 2, and the operations that result in one from the other, wrong. Let's just fix that for now.

**Comment by ViralBShah** [comment]
It is these kinds of inconsistencies I don't like, which make the system feel lacking. I wish we had N-d too, but that is likely to happen in JuliaSparse rather than Base.

I also feel that a sparse vector will be useful with non-numeric data types as well.

**Comment by ScottPJones** [comment]
Although, for non-numeric data types, what is the type for fields not represented?
The types of sparse arrays and vectors I have implemented (for database use) didn't store null or undefined fields.  For Julia, I guess you'd need type Any, and Nothing.

**Comment by mlubin** [comment]
@andreasnoack, the storage for a sparse vector and a 1-column CSC matrix is essentially the same, I don't think there are any performance differences. The argument is that the current semantics are wrong.

**Comment by andreasnoack** [comment]
I still think that it would be useful to see examples application of sparse vectors. The indexing behavior of special matrix types is hard. It is a standard attack on the special matrix types and one of the reasons they might not fit well as subtypes of `AbstractArray`. I don't think indexing is the most important feature of sparse matrices or special matrices in general. They are mainly about `*` and `\`.

**Comment by johnmyleswhite** [comment]
One common sparse vector application:

* Read in a text corpus document-by-document and train a logistic regression classifier with an L1 penalty on parameters. Your parameter vector is a sparse vector and each new document (of which there should be exactly one in memory at a time) is a sparse vector. The only thing you need to do is compute dot products and update the parameter vector.

**Comment by lindahua** [comment]
The SparseVectors package was initially motivated by the need to represent sparse samples in machine learning applications (@johnmyleswhite's example is an important case). 

For sparse vectors, we often want to compute dot products, compute distances between them, etc. Matrix-vector product is also very useful.

**Comment by lindahua** [comment]
Looks like, the general opinion is towards option (B). I will make a PR later this week.

**Comment by andreasnoack** [comment]
Thanks for the examples. I think all of them could work for vectors represented by `Nx1` sparse matrices. After all, that approach works well in MATLAB, but go ahead with another type. I won't obstruct the process further.

**Comment by mbauman** [comment]
I preface this with the caveat that I do not do sparse linear algebra, but I have been playing with indexing a lot lately.  I've not tried this yet, either.

Would it be possible to add a "phony" dimensionality to the CSC type, allowing it to pretend to be one or multi-dimensional?  All indexing would be reduced or expanded to its canonical two dimensions.  This will be very inefficient for high dimensional arrays, but it should be fairly easy to make it semantically correct and consistent (especially if we get #10525).  The JuliaSparse organization can provide more specialized types that are more efficient in the non-2-dimensional cases.

**Comment by ScottPJones** [comment]
Somewhat OT: Since SparseVectors have decidedly numeric meaning in Julia (i.e. it is zero values that are removed, instead of null values), how would you name a package for storing efficiently sparse vectors of any type, where many values may be null? [think of JSON arrays, RDBMS rows, etc.]... Does something like that already exist, and I just haven't found it yet?  Thanks!

**Comment by quinnj** [comment]
Scott, check out the DataArrays.jl package.

**Comment by tkelman** [comment]
@ScottPJones Nullable types, or DataArrays potentially.

@mbauman that sounds finicky and more complicated than just adding a separate type for 1-d. If we're going to distinguish vectors from matrices within the type system for dense arrays, consistency really demands that we do the same for sparse. Faking it adds complexity to the CSC type, whose internals are already quite commonly used and relied upon not changing in packages.

I have an application where I build up a sparse CSC matrix representation column-by-column, often reordering columns but rarely changing their contents. For this, an array-of-SparseVectors is an ideal representation. Representing this as CSC adds overhead for an extra integer field and an extra 2-element integer array for the column pointers for each object, which I'd really rather avoid since my columns have very few nonzeros on average.

**Comment by mlubin** [comment]
@tkelman, I would love to be able to vcat an array of sparse vectors to get a sparse CSC matrix. I think I'm coming around on this.

**Comment by tkelman** [comment]
hcat, you mean?

**Comment by mlubin** [comment]
Yes, hcat

**Comment by tkelman** [comment]
> sparse matrices or special matrices in general [...] are mainly about * and \.

I'm going to have to disagree with you pretty strongly there. I use sparse matrices very heavily, but I do essentially zero linear algebra with them *in Julia*. Why? Because Julia's sparse matvec and matmul are still quite a bit slower than doing it in C++ or using MKL's sparse blas extensions, and the sparse factorizations available in Base aren't complete enough for my needs (SuiteSparse has no Bunch-Kaufman indefinite LDL^T).

My sparse matrices do have linear (and often custom nonlinear) algebraic meaning, but that gets sent to a compiled solver to do all the actual work. So indexing, reductions, data structure traversal and creation within Julia is really important to me on sparse and structured array types (re: #8001). I should send Jiahao an email and see about visiting MIT and working on it for a few weeks leading up to JuliaCon.

Eventually Julia will be fast enough to write the solvers themselves - if I can get diagonal-D quasidefinite factorizations from Cholmod to work properly I've been meaning to write a Mehrotra QP solver as a proof-of-concept. Will be interesting to benchmark against Ipopt.

**Comment by ViralBShah** [comment]
@jiahao is going to be travelling from now to JuliaCon. I will probably be around MIT a few days before and after JuliaCon - so would love to push on sparse matrix work in any way possible.

**Comment by ViralBShah** [comment]
@mbauman The CSC/CSR format is dense in one dimension. It doesn't generalize well to higher dimensions, where you really just want the COO format - representing indices as tuples. I have thought about faking it in CSC, but you just get extra overhead for processing vectors. I would love to make the two representations close enough, so that one can write generic code for iterating through either SparseMatrixCSC or SparseVector.

**Comment by ViralBShah** [comment]
@ScottPJones You can store anything in Julia's sparse data structures already:
````
julia> sparse([1,2], [1,2], ["hello", "world"])
2x2 sparse matrix with 2 ASCIIString entries:
	[1, 1]  =  "hello"
	[2, 2]  =  "world"
````

**Comment by ScottPJones** [comment]
@ViralBShah What about the following?
```julia
julia> z = sparse([1,2], [1,2], ["hello", 1.5])
2x2 sparse matrix with 2 Any entries:
	[1, 1]  =  "hello"
	[2, 2]  =  1.5

julia> z[1,2]
ERROR: `zero` has no method matching zero(::Type{Any})
 in getindex at sparse/sparsematrix.jl:773
```
The problem is that Julia's sparse data structures all have 0 not be represented, but for RDBMS rows, you want NULL to not be represented....

**Comment by ViralBShah** [comment]
Julia's sparse data structures although not strictly restricted to numeric values, have only been used with numeric values so far. Hence all the rough edges for non-numeric data. This discussion should really be on the mailing list and not here in this issue, where it is off-topic.

**Comment by mbauman** [comment]
> The CSC/CSR format is dense in one direction.

Yup, I'm well aware. That's why I called them phony dimensions. My point was just that it might be easiest (as a stopgap) to allow the CSC data structure to masquerade as non-matrices. But perhaps that's naive.

**Comment by lindahua** [comment]
Adding A specific class for sparse vectors is not very difficult. It is largely done in a package, I will try to find some time during the weekend to make a PR.

**Comment by StefanKarpinski** [comment]
I'm worried that we're going to go through the same process of finding that all sorts of operations are missing or unusably slow due to using generic fallbacks that went on (is going on?) with sparse matrices for so long. If @lindahua and @ViralBShah are confident that this functionality is complete, then I guess we can merge this into the standard library, but we really need very complete tests for this.

**Comment by tkelman** [comment]
We probably will. The implementation covers enough functionality to be very useful as-is. I don't think Dahua was able to figure out how to get Coveralls turned on yet (https://github.com/JuliaSparse/SparseVectors.jl/issues/2), which I have no idea how to help with.

> all sorts of operations are missing or unusably slow due to using generic fallbacks that went on (is going on?) with sparse matrices

It's getting better over time by adding new methods. My nascent idea for a proper generic solution that would be good enough to eventually close #8001 is to extend the cartesian indexing types with a sparsity-aware version, something like `eachstored`, and make the "generic" fallbacks use it where appropriate.

**Comment by lindahua** [comment]
What I can make sure is that all methods in SparseVectors.jl (or the PR that would be made later) are implemented in a reasonably efficient manner. 

However, there are many functions out there that accept ``AbstractArray`` but are implemented in a way that assumes fast random access (e.g. ``for i = 1:length(A) ... end``), these functions are doomed to work very slowly when called on sparse arrays.

**Comment by ViralBShah** [comment]
I believe this functionality is useful as is too. We will discover fallbacks to generic implementations, but we are pretty good about fixing them quickly. There is enough time in the 0.4 release cycle to get this 100% right. 

Let's at least start with a PR.

**Comment by timholy** [comment]
@tkelman, it would be pretty easy to add such an iterator for sparse matrices. If you want me to help, just holler.

**Comment by tknopp** [comment]
What about option D) move all sparse matrix/vector stuff into a package? I don't see any advantages of this being in Base despite that its there by default. I really think it would help to decouple the development of these things from Julia itself. (ref #5155)

**Comment by StefanKarpinski** [comment]
I have to say, I'm with @tknopp on this one.

**Comment by ScottPJones** [comment]
+:100: @tknopp

**Comment by tkelman** [comment]
Can we finish precompiled packages first? Then we'll talk about it. For now, let's not break every package in JuliaOpt, kay? Dense linear algebra doesn't need to be in base either.

Ignoring sparsity leads to way too much of this nonsense:

> However, there are many functions out there that accept `AbstractArray` but are implemented in a way that assumes fast random access (e.g. `for i = 1:length(A) ... end`), these functions are doomed to work very slowly when called on sparse arrays.

Pretending problem structure isn't important and every problem has all-to-all interactions leads to a crippled framework. Ever notice how there's no such thing as JuliaOpt for Torch?

**Comment by tknopp** [comment]
@tkelman: Why should that break every package in JuliaOpt? One would just have to put a `using SparseArrays` into packages that require this from 0.4 on. The reason I bring up this here is that the original suggestion of this thread is to put something from a package into base. And in my opinion this is the wrong direction. The designing of libraries should not be done in Base but outside base.

So if you are not fine with removing this stuff than let me ask: Why should SparseVectors be in base? What is the benefit of this?

**Comment by joehuchette** [comment]
I mean, it WILL break everything in JuliaOpt, which we can then work around. How much effort that takes and pain it causes is contingent on how cleanly the excision goes (which is an open question). There's also the issue of precompilation Tony mentioned; I'm not sure how much an external SparseArrays package would add to our load time. The question is whether that burden is outweighed by the potential gains of removing sparse matrices from Base for 0.4.

**Comment by tknopp** [comment]
We have various syntax changes in 0.4, why should a removal of some code matter more? This is Julia master, it should not be used for production use and thus a breakage of packages is a very natural thing during a dev cycle. The point of moving things into a package is that the maintainability is increased and further any improvement that is done is directly available to users that use stable versions of Julia. In my research lab we rely on stable Julia and thus cannot benefit from any improvement that has been made to the sparse matrix code since 0.3 has been release. If it would be in a package this unnatural coupling would be broken.

Regarding the load time I don't see why sparse matrices should be more special than other packages. Note that I do use sparse matrices in a large Julia code base, so I will be equally effected.

**Comment by tkelman** [comment]
> Why should SparseVectors be in base? What is the benefit of this?

This is a bugfix. Read the entire thread, this is fixing a semantic inconsistency in the way the current sparse matrix implementation interacts with 1-dimensional indexing.

Sparse matrices are far too large, important, and widely used to consider removing before 0.4. We're already months behind schedule, let's not make it any worse.

> How much effort that takes and pain it causes is contingent on how cleanly the excision goes (which is an open question).

Considering this has gone poorly every time we've tried it, I have serious reservations about doing this again until we work out how to do it more smoothly. For one thing I've suggested leaving functionality in base but moving it into independent modules instead of exporting it by default, which would leave the functionality still available but behind an import, and cause a much easier-to-deal-with breakage in packages.

**Comment by mlubin** [comment]
@tknopp @StefanKarpinski, I was on the fence about including sparse vectors in Base, but really this addresses a significant usability and semantics issue with the current implementation, and better yet there's already code to do so and @lindahua is willing to push through a PR.

Agreed with @tkelman. Let's make the incremental improvement now and not create a huge new time sink for everyone to deal with.

**Comment by tkelman** [comment]
Precompilation will be addressed in time, more significant is what consequences saying "sparse matrices are not important enough to worry about in base" would have to the package version of sparse matrices being able to work well at all. If base Julia ignores the existence of sparse matrices and writes all routines in a way that they can only ever be efficient for dense matrices, that will be crippling. You need to rewrite all of LinAlg, every reduction, all of broadcast, all indexing and concatenation over again for every sparse matrix type. And again, squared, for all conversions and linear algebra operations between different types. We need a better framework in base first, for which SparseMatrixCSC can be the first implementation - ideally a small, pluggable one that could live out in a package, but the framework needs to exist first.

**Comment by StefanKarpinski** [comment]
> I believe this functionality is useful as is too. We will discover fallbacks to generic implementations, but we are pretty good about fixing them quickly.

This attitude is what I object to. We had this ongoing steady stream of broken sparse matrix stuff for a long time. We are past the point where it's acceptable to have that in Base – we're trying to get rid of that kind of thing; it's certainly shouldn't be adding more of.

**Comment by tkelman** [comment]
Stefan, I don't understand why you think it's suddenly fixed. It isn't yet.

**Comment by StefanKarpinski** [comment]
It's better than it used to be and I object to introducing more half-baked functionality into base.

**Comment by mlubin** [comment]
@StefanKarpinski, I think @lindahua's proposed PR is already or can be brought to a state that's not half baked before merging.

**Comment by tkelman** [comment]
This isn't half-baked. Things have only gotten better by gradual improvement. Which this is a case of.

**Comment by tknopp** [comment]
> Sparse matrices are far too large, important, and widely used to consider removing before 0.4. We're already months behind schedule, let's not make it any worse.

Why should being to large be an argument for not moving it in a package? Importance and widely used are pretty subjective. In my subjective opinion PyPlot is a lot more important and widely used than the sparse module.

If I understand Tony correctly there will be major overhaul for the sparse module in the future (e.g. generalization to CSR matrices...) and in my opinion there is no benefit of having this development in base. It will make the development even much harder than if it would be developed in a package. Or does nobody see this point?

**Comment by mlubin** [comment]
@tknopp, I agree with you and have stated before that CSR shouldn't be developed in base, but that's not related to this PR. Sparse vectors aren't a major overhaul, they're a bugfix.

**Comment by tknopp** [comment]
@mlubin: This is not a PR yet but a question how to proceed. If you all want this than simply go ahead and do it. The reason I started this discussion is to show the advantages of this being in a package. And I still have not seen an argument why it would be a bad thing.

**Comment by tkelman** [comment]
We agree with you on everything except timeframe, and maturity of the code removal process. 0.4 shouldn't be removing any more code. 0.4 should also stop adding code that isn't fixing bugs for that matter, and try to get out the door before fall. The bug here is `As[3,:]` returns a 1-column matrix instead of a 1-d vector, if there's a way to fix that bug before 0.4 without adding a new type or introducing some ugly fragile workarounds (#11323), speak up. #8718 was on Viral's personal wishlist to get into 0.4 for some time.

There's also a non-negligible risk of the sparse code bitrotting and losing a lot of visibility if it gets moved out of base. Sparse matrices will need the right infrastructure to exist in base first (which will have to be developed here) before they can work well as a package, and just as importantly they will need enough people to maintain them or they will wither and die.

**Comment by tknopp** [comment]
> We agree with you on everything except timeframe, and maturity of the code removal process. 0.4 shouldn't be removing any more code. 0.4 should also stop adding code that isn't fixing bugs for that matter, and try to get out the door before fall. The bug here is As[3,:] returns a 1-column matrix instead of a 1-d vector, if there's a way to fix that bug before 0.4 without adding a new type or introducing some ugly fragile workarounds (#11323), speak up. #8718 was on Viral's personal wishlist to get into 0.4 for some time.

- Timeframe will always be bad
- Removing the package is an equally valid bugfix ;-)

> There's also a non-negligible risk of the sparse code bitrotting and losing a lot of visibility if it gets moved out of base. Sparse matrices will need the right infrastructure to exist in base first (which will have to be developed here) before they can work well as a package, and just as importantly they will need enough people to maintain them or they will wither and die.

This is where I object to. If there is not enough momentum to maintain this then the code is simply not important and should definitely not be in base. Visibility loss is also something which can be said about almost every package and we need other mechanisms to highlight "must have" packages.

**Comment by tkelman** [comment]
> Timeframe will always be bad

Completely wrong. The perfect time to make major, significant, breaking reorganizations and changes is early in a -dev cycle. We're not early in a -dev cycle, we're overdue for determining scope completion to close the -dev cycle to move to -pre and a release. We've blown past the 6 months for -dev then 3 months in -pre plan already.

> Removing the package is an equally valid bugfix ;-)

Not until a replacement is available, tested, and working. And Base is capable of supporting that package working at all.

> If there is not enough momentum to maintain this then the code is simply not important and should definitely not be in base.

We're way off topic, but the counterargument to that is how few commits to base are necessary to make use of this type of code once it's there and in place. Miles, Iain, etc have very few base commits, but their packages are a major driver of adoption. If Julia has a single killer app right now where it's undoubtedly better than the competition, it's OR, which you can't do at all without sparse matrices. Let's not cause major breakage there by deleting code without preparing a replacement first.

**Comment by johnmyleswhite** [comment]
> If Julia has a single killer app right now where it's undoubtedly better than the competition, it's OR, which you can't do at all without sparse matrices. 

I think this is the core point of Tony's argument and it's completely accurate from what I can see.

**Comment by tknopp** [comment]
> Completely wrong. The perfect time to make major, significant, breaking reorganizations and changes is early in a -dev cycle. We're not early in a -dev cycle, we're overdue for determining scope completion to close the -dev cycle to move to -pre and a release. We've blown past the 6 months for -dev then 3 months in -pre plan already.

Yes you are right, I agree with that

> We're way off topic

These discussions always end up with a statement that we are off topic. But where if not here should these discussions happen?

> Let's not cause major breakage there by deleting code without preparing a replacement first.

I did not say first remove it and then do the package. Of course the order is the other way around. 
But you are probably right that doing the package is a little bit more complicated due to the binary dependencies. If these were not there it would be a simple copy of the `sparse` directory into a new git repo

**Comment by tknopp** [comment]
@johnmyleswhite:
- What is OR?
- Does OR require a package? If yes where would be the issue if an additional package is loaded?

**Comment by tkelman** [comment]
OR = operations research, aka optimization, so JuMP, Convex, MathProgBase, the solver bindings, and to some extent Optim.

Yes these require an external package, and it probably wouldn't be the end of the world to add an additional dependency package to the mix, BUT, it needs to be done right. It's not yet clear to me, as things stand right now, if taking sparse matrices out of base wholesale can leave both parts working as well together as they did before moving them.

**Comment by mlubin** [comment]
We all want the same thing here, but I don't find the proposal to block a bugfix in favor of a major reorganization as we're trying to finish up 0.4 very convincing. @lindahua has put his valuable time and effort into developing sparse vectors, and we all have better things to spend our time on than dealing with the fallout of removing everything sparse from Base.

**Comment by ViralBShah** [comment]
+1

**Comment by tknopp** [comment]
Reading this thread in retrospect taking into account Virals change in the milestone hopefully shows that it could be a good move to decouple the sparse array development from Julia...

**Comment by tkelman** [comment]
@tknopp there's still no particularly clean way of both fixing the indexing inconsistency bug with SparseVectors as a package while also avoiding massive package breakage or name conflicts by trying to move sparse matrices wholesale into packages. If you would like to start doing the work to prepare package migrations for some of the functionality that's in base right now, please go ahead and start helping do some of that work.

**Comment by ViralBShah** [comment]
I request not bringing off-topic discussions into issues. I also do not see how this conclusion is drawn - but this is a discussion to be had elsewhere. If you do wish to continue this discussion, I suggest the mailing list or an appropriate issue.

**Comment by malmaud** [comment]
Can this be closed in light of https://github.com/JuliaLang/julia/pull/13440?
