### ISSUE TITLE
random indexing performance of SparseMatrixCSC is so terrible it renders sparse matrices effectively unusable

### ISSUE THREAD

**Issue by ssagaert** [JuliaLang/julia#11326]
replacing large (30000 * 30000) dense matrices with sparse ones slows down the program orders of magnitude, changing training time from  15 minutes to hours. In the end I just killed the program.

**Comment by jiahao** [comment]
Please read [How to file a bug report](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#how-to-file-a-bug-report)

In this case, it would help to show a simple code example that illustrates the speed difference.

**Comment by timholy** [comment]
It's also a valid to ask whether it's reasonable to expect anything different. Do you understand what's required for indexing a sparse matrix?

**Comment by ssagaert** [comment]
here's an extract of the relevant code:

```
function learn3(data::Data3,catalogs::Dict{(String,String),Vector{String}},classCatalogs::Dict{(String,String),Vector{String}})
    itemIndex=Dict{String,Int}()
    itemInvIndex=Array(String,length(data.items))
    itemId=1
    for sku in data.items
        itemIndex[sku]=itemId
        itemInvIndex[itemId]=sku
        itemId+=1
    end
    itemPairs=spzeros(Float32,length(data.items),length(data.items))

    classIndex=Dict{String,Int}()
    classInvIndex=Array(String,length(data.classes))
    classId=1
    for classPath in data.classes
        classIndex[classPath]=classId
        classInvIndex[classId]=classPath
        classId+=1
    end

    classPairs=spzeros(Float32,length(data.classes),length(data.classes))
    #process the transaction data
    for t in values(data.transactions)
        for itemData2 in t,itemData in t #loop first over the columns because that's faster (julia arrays are column stored)
            sku=itemData[1]
            class=itemData[2]
            sku2=itemData2[1]
            class2=itemData2[2]
            if sku2!=sku
                itemPairs[itemIndex[sku],itemIndex[sku2]]+=1
            end
            if class2!=class
               classPairs[classIndex[class],classIndex[class2]]+=1
            end
        end
    end

    #normalize matrix to joint probability
    N=length(data.transactions) #nrTransactions
    itemPairs./=N
    classPairs./=N
    #support=copy(itemPairs) #copy joint prob
    support=itemPairs #just a rename
    classSupport=classPairs

    #calculate marginal prob
    #divide by marginal probability => result=p(i,j)/p(j) = p(i|j)
    itemProb=zeros(size(itemPairs,2))
    for j=1:size(itemPairs,2)
        itemProb[j]=sum(itemPairs[:,j])
        #if itemProb[j] > 0
        #    itemPairs[:,j]./=itemProb[j]
        #end
    end

    classProb=zeros(size(classPairs,2))
    for j=1:size(classPairs,2)
        classProb[j]=sum(classPairs[:,j])
    end

    #calculate cosine measure p(i,j)/sqrt(p(i)*sqrt(p(j))
    confidence=spzeros(Float32,size(support))
    for j=1:size(confidence,2),i=1:size(confidence,1)
        if itemProb[i] > 0 && itemProb[j] > 0
            confidence[i,j]=support[i,j]/(sqrt(itemProb[i])*sqrt(itemProb[j]))
        end
    end

    #calculate cosine measure p(i,j)/sqrt(p(i)*sqrt(p(j))
    classConfidence=spzeros(Float32,size(classSupport))
    for j=1:size(classConfidence,2),i=1:size(classConfidence,1)
        if classProb[i] > 0 && classProb[j] > 0
            classConfidence[i,j]=classSupport[i,j]/(sqrt(classProb[i])*sqrt(classProb[j]))
        end
    end

end
```

**Comment by lindahua** [comment]
I think the foremost question is whether sparse matrix is suitable for your application. If your program requires extensive random indexing, then you should not use sparse matrix.

To be more specific, sparse matrix is not good for something as follows:
```julia
for j = 1:n, i = 1:m
     # do something with A[i, j]
end
```

**Comment by ViralBShah** [comment]
If you need to construct a sparse matrix, you should be using `sparse(I,J,V)`.

**Comment by lindahua** [comment]
Look at this code snippet (extracted from your example):
```julia
classConfidence=spzeros(Float32,size(classSupport))
for j=1:size(classConfidence,2),i=1:size(classConfidence,1)
    if classProb[i] > 0 && classProb[j] >  0
        classConfidence[i,j]=classSupport[i,j]/(sqrt(classProb[i])*sqrt(classProb[j]))
    end
end
```
It is obvious to me that ``classConfidence`` should be a dense matrix in the first place.

**Comment by jiahao** [comment]
Unlike ordinary dense matrices, which have O(1) indexing cost, random access on CSC matrices costs O(n) where n is the average length of each column. (Ref #10064) Therefore in this use case, we expect an O(n) slowdown, which is consistent with what is reported.

Closing as not actionable.

**Comment by ScottPJones** [comment]
@jiahao, it sounds like it must be doing a linear scan, couldn't that be brought down to O(log n), with a binary search?

**Comment by jiahao** [comment]
Oops, I left out the log factor.

**Comment by lindahua** [comment]
It is now using binary search, so it is `log(n)`.

**Comment by ScottPJones** [comment]
Even so, I think it might be possible to do better than O(log n) in many cases... I'll have to look into how sparse matrices are implemented...  Is each column the same length? (since you said, average length)  Just how sparse is each column, typically?  The columns could be subdivided by a fixed abount (say, chunks of 256 elements), and each chunk could be sparse or dense (and even for the dense ones, only store from the 1st defined element to the last defined element), and sparse chunks would really only need an array of bytes that could be scanned or binary searched to find the index into the dense representation...

**Comment by jiahao** [comment]
Actually I think in this problem the dominant cost is not random access, but rather growing the matrices as elements are set. So the actual cost of this algorithm looks something like `O(nnz^2 log(nnz)^2/log(nrows))` per matrix construction, of which `O(log(nnz)^2/log(nrows))` (amortized) pertains a single `setindex` call on a single entry.

I may yet change my mind after more caffeine.

@ScottPJones Have a look at http://netlib.org/linalg/html_templates/node92.html. I believe CSC matrices are essentially tries of depth 2 where you are allowed to drop zero entries and the underlying representation has to be sorted in lexical order.

**Comment by ssagaert** [comment]
I understand that’s it slower than a dense matrix. I expected a slowdown. The question is how much is a reasonable slowdown?






Van: Tim Holy
Verzonden: ‎maandag‎ ‎18‎ ‎mei‎ ‎2015 ‎13‎:‎21
Aan: JuliaLang/julia
CC: Steven Sagaert





It's also a valid to ask whether it's reasonable to expect anything different. Do you understand what's required for indexing a sparse matrix?

**Comment by timholy** [comment]
If julia's sparse code is implemented in a way that achieves absolute ideal performance, you expect a slowdown of `log2(30000)` which is approximately 15. Consequently, you expect your 15-minute computation to take at least 4 hours. That's consistent with the scenario you outlined at the top. Hence, it's not at all obvious that there's any kind of problem---using your experience as evidence to conclude that the performance is "terrible" ignores all the constraints of the problem.

In reality you'd expect it to be much worse than that because the CPU probably can't realistically get the same cache-efficiency, certainly is not multithreaded like BLAS, etc. I wouldn't be surprised to see a 50x slowdown, yet with almost no possibility of making things any better. (Short of explicit parallel schemes like https://github.com/madeleineudell/ParallelSparseMatMul.jl.)

**Comment by KristofferC** [comment]
@ScottPJones Each column is not the same length. Accessing a CSC matrix `A` at `[i,j]` means you have to do a search for `j` in `A.rowval` between indices `A.colptr[i]:A.colptr[i+1]`.

 `A.colptr[i+1] - A.colptr[i]` is just the number of non zero elements in column `i`

 If it is not found you return 0.

As a reference, for a typical 2D finite element problems, the sparsity is around 0.0001.

What you are talking about sounds like Blocked CRS, see: http://netlib.org/linalg/html_templates/node93.html

**Comment by ScottPJones** [comment]
@KristofferC But, the columns are conceptually the same length, correct? It is for a 2D matrix, of size M x N, right?  What I'd done in the past was for arbitrary dimensions, eliminating null fields instead of zeros, and able to store any type of data (including arrays) at each node.  Maybe closer to Tuples and Named Tuples...

**Comment by tkelman** [comment]
> the columns are conceptually the same length, correct

Not within the data structure, no. (Maybe in certain applications, but the general CSC data structure is not specialized for that.) For CSC, the storage space for an m-by-n sparse matrix with nnz nonzeros is `2 * sizeof(Int) + (n + 1 + nnz) * sizeof(Ti) + nnz * sizeof(Tv)`, where Ti is the index type and Tv is the value type. A single column could take up the entire `rowval` and `nzval` array (if it's the only column with any nonzeros in it), or none of it.

**Comment by ScottPJones** [comment]
@tkelman, I said *conceptually* it is an m-by-n matrix, even if the rows or columns are not completely stored, so that row ids must be 1..m and columns 1..n, correct?

**Comment by tkelman** [comment]
> so that row ids must be 1..m and columns 1..n, correct?

Correct.

There are already a few heuristics for switching between linear and binary search in the sparse matrix indexing, those could always be tuned or made more sophisticated over time. But the core CSC data structure needs to be left as-is for compatibility, since the representation details are standardized. Customized sparse algorithms typically need to work on the underlying data structure directly for the best performance, and I don't think arbitrary generic getindex (and especially not setindex) can be made completely competitive here.

Application-specific optimized sparse data structures are certainly called-for at times (if you know the sparsity of all columns is close to uniform, as one example), but should be worked on out in packages.

**Comment by ssagaert** [comment]
right, that makes sense. I guess out of frustration with the huge slowdown I jumped the gun on this one.


I’ll just use my own sparse data structure.






Van: Tim Holy
Verzonden: ‎maandag‎ ‎18‎ ‎mei‎ ‎2015 ‎18‎:‎10
Aan: JuliaLang/julia
CC: Steven Sagaert





If julia's sparse code is implemented in a way that achieves absolute ideal performance, you expect a slowdown of log2(30000) which is approximately 15. Consequently, you expect your 15-minute computation to take at least 4 hours. That's consistent with the scenario you outlined at the top. Hence, it's not at all obvious that there's any kind of problem---using your experience as evidence to conclude that the performance is "terrible" ignores all the constraints of the problem.

In reality you'd expect it to be much worse than that because the CPU probably can't realistically get the same cache-efficiency, certainly is not multithreaded like BLAS, etc. I wouldn't be surprised to see a 50x slowdown, yet with almost no possibility of making things any better. (Short of explicit parallel schemes like https://github.com/madeleineudell/ParallelSparseMatMul.jl.)

**Comment by KristofferC** [comment]
@tkelman  ```There are already a few heuristics for switching between linear and binary search in the sparse matrix indexing```

Are there?

https://github.com/JuliaLang/julia/blob/master/base/sparse/sparsematrix.jl#L1229

seems to always call `searchsortedfirst` which is a binary search right?

**Comment by tkelman** [comment]
@KristofferC for single scalar row and column indices you're right. The heuristics are for indexing with an AbstractVector https://github.com/JuliaLang/julia/blob/9e8badc45988f2e0cb0baad3022856b6340fe47a/base/sparse/sparsematrix.jl#L1321-L1335
