### ISSUE TITLE
Confusing lack of whitespace in ``show``ing Dict

### ISSUE THREAD

**Issue by joehuchette** [JuliaLang/julia#11394]
```jl
julia> VERSION
v"0.4.0-dev+4928"

julia> a = Dict(:(==) => 1,:<= => 2,:>= => 3);

julia> show(a)
Dict(:(==)=>1,:<==>2,:>==>3)
```

**Comment by yuyichao** [comment]
I guess this also applies to pairs

```julia
julia> :<= => 1
:<==>1
```

**Comment by yuyichao** [comment]
And the lack of parenthesis when showing pairs. (this is probably a separate issue though.)

```julia
julia> (:<= => :>=) => (:< => (:< => :<))
:<==>:>==>:<=>:<=>:<

julia> :<= => (:>= => (:< => (:< => :<)))
:<==>:>==>:<=>:<=>:<
```

**Comment by joehuchette** [comment]
Also:
```jl
julia> show(:(=>) => 1)
:(=>)=>1
```
I guess just adding parens should make this clearer.

**Comment by fcard** [comment]
The lack of parentheses also applies to `Expr`s.
```julia
julia> :((a => b) => (c => d))
:(a => b => c => d)
```

That's because `=>` is treated as an infix operator and infix operators of same precedence don't need parentheses to separate them. Should `=>` be treated as a special case and always have parentheses around it or is there a case where it shouldn't have them? (apart from being by itself)

(this is not 100% related, so should it be a separate issue...?)

**Comment by yuyichao** [comment]
@JeffBezanson Should I open a separate issue for this?

```julia
julia> 1 => (2 => 3)
1=>2=>3

julia> (1 => 2) => 3
1=>2=>3
```

**Comment by JeffBezanson** [comment]
Yes, similar to #11393 --- operator precedence/associativity printing issue.

**Comment by yuyichao** [comment]
OK. Done.
