### ISSUE TITLE
Pairs and `:=>` expressions should be printed with parenthesis

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11436]
Best shown by example:

```julia
julia> 1 => (2 => 3)
1=>2=>3

julia> (1 => 2) => 3
1=>2=>3

julia> :(1 => (2 => 3))
:(1 => 2 => 3)

julia> :((1 => 2) => 3)
:(1 => 2 => 3)
```

Similar issues: https://github.com/JuliaLang/julia/issues/11394, https://github.com/JuliaLang/julia/issues/11393

**Comment by fcard** [comment]
Do you mind if I fix this? I already have half the code done with #11427 (if that gets approved, anyway...).

**Comment by JeffBezanson** [comment]
@fcard that would be great!

**Comment by fcard** [comment]
@JeffBezanson Thanks, I will get to that then! :)

**Comment by fcard** [comment]
Hi. Due to the direction #11427 ended up going, the solution I had in mind for this introduces a lot of unnecessary parentheses, so I am not sure it's satisfactory anymore. (I had one that didn't introduce the parens, but it's overly complicated)

So unless it's okay to have parentheses even when it's not ambiguous without them, I think I am going to have to pass this along.

**Comment by kmsquire** [comment]
Perhaps you could submit thi version with too many parentheses and ask for
suggestions?

**Comment by fcard** [comment]
The change I wanted to make is now conceptually broken because I needed one variable to mean one thing and now it means another. I think submitting wouldn't have much of a point.

I actually came up with another solution based on Mr. Benzason's commit above (that I noticed just a little while ago), but I want to make sure everything is correct before even thinking about submitting. I made way too many silly mistakes already, it's starting to make me feel depressed :P

**Comment by pao** [comment]
> but I want to make sure everything is correct before even thinking about submitting

If it's a larger change--I'm not sure whether it is or not--it can make sense to get something out early, even with known issues, to make sure you're on the right path. Just make it clear that it's work in progress (we usually prepend "WIP" to the pull request title on GitHub) and that you're looking for design feedback.

We certainly appreciate what you've contributed so far, and hope you aren't too embarrassed to continue! Thanks!

**Comment by fcard** [comment]
Thanks. I am a little embarrassed to be honest, but I think I can try again. I guess I need to stop being so nervous about this. (I am still worried that the two `´` that I added in my first commit are going to cause some sort of chain reaction and break the entire language)

@mbauman that is exactly the first fix with unnecessary parens :P

**Comment by mbauman** [comment]
Hah, sorry, I should have let you take charge.  I think getting things right trumps a little verbosity here and there.
