### ISSUE TITLE
herk! should take real valued scalars

### ISSUE THREAD

**Issue by dane-unltd** [JuliaLang/julia#11469]
There seems to be an issue with the herk! BLAS wrapper.
It should take real valued scalars alpha and beta as in the original BLAS function.

**Comment by timholy** [comment]
@dane-unltd, someone else might tackle this, but a pull request would be great! See https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md.

**Comment by simonster** [comment]
It would be nice to backport this, since the behavior on 0.3 is actually incorrect, but I guess it's not really backport-able because it's a change to the signature...

**Comment by andreasnoack** [comment]
We could backport it and keep a version with the present signature where we do a conversion to reals. This will give a runtime error whenever the `α` and `β` have non-zero imaginary parts which are the only cases where the result is wrong since the imaginary part is simply ignored in the present version.

**Comment by tkelman** [comment]
Could you make a PR for that? Would also like to wait for this change to go through PkgEvaluator on master before backporting, so hopefully waiting until 0.3.10 is fine for this?
