### ISSUE TITLE
julia-mode: Code block indentation doesn't work in parenthesis

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#11498]
Code block indentation doesn't work in parenthesis.

This is what julia-mode does right now
```julia
:(function f(a)
  a
  end)
```

This is what it should do
```julia
:(function f(a)
      a
  end)
```

**Comment by justbur** [comment]
Maybe we could treat parens/brackets and block delimiters the same way instead of distinguishing between the two? This would solve this issue and implement the second suggestion in #8971, and would make for a nice simple rule about indentation. However, that would lead to this
```julia
:(function f(a)
        a
    end)
```
which could be "resolved" by doing
```julia
:(  function f(a)
        a
    end)
```
or
```julia
:(  
    function f(a)
        a
    end
 )
```

**Comment by yuyichao** [comment]
This sounds reasonable.

**Comment by yuyichao** [comment]
Covered by https://github.com/JuliaLang/julia-emacs/issues/11
