### ISSUE TITLE
Implement printf %g format specifier

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#11599]
The printf `%g` format specifier is [currently unimplemented](https://github.com/JuliaLang/julia/blob/3ff49ff39bd56a4928ae4341e60030c6b170e7a1/base/printf.jl#L647-L649).  It would be great to be able to use it in Julia code.

Is there a specification somewhere for what this *should* do?  The best I can find is [python's documentation on the subject](https://docs.python.org/3.4/library/string.html#format-specification-mini-language), which contains documentation on how `g` works there.

**Comment by elextr** [comment]
The python definition looks to be exactly the same as the C standard definition for 'g' in the `printf()` formats.

**Comment by garrison** [comment]
In that case, the C standard definition certainly seems like the best thing to base this behavior on.  [Here's a link](http://www.cplusplus.com/reference/cstdio/printf/).

**Comment by elextr** [comment]
What I meant was that the wording in the Python link appears to express the same specification/algorithm as the C standard (including things like `-4 <= exp < p`) but written in different language and layout presumably to avoid the fact that the C spec is copyright.

The description in the second link "Use the shortest representation: %e or %f" is the effect, but the Python version says precisely how to achieve that.

**Comment by garrison** [comment]
Got it, thanks!

**Comment by dfannius** [comment]
Just how closely is `@printf` supposed to map to C's `printf`? I started poking around in `printf.jl` due to this issue and immediately found a couple of places where Julia and C diverge:

If `x` is `NaN` then in Julia
`@sprintf( "%e", x ) => "NaN"`
`@sprintf( "%E", x ) => "NaN"`
while in C and C++
`printf( "%e", x ) => "nan"`
`printf( "%E", x ) => "NAN"`

Similarly, if `x` is `Inf` then in Julia
`@sprintf( "%e", x ) => "Inf"`
`@sprintf( "%E", x ) => "Inf"`
while in C and C++
`printf( "%e", x ) => "inf"`
`printf( "%E", x ) => "INF"`

The documentation for `@printf` in the manual just says "Print arg(s) using C `printf()` style format specification string."

Should either the code or the documentation should be changed, or is this below the threshold of caring? I only noticed because I wanted `%g` and `%G` to do the right thing, whatever that is. I wouldn't be surprised if "fixing" the behavior of `%e` and `%f` would cause some currently-existing code that parses Julia output to break.

(The C/C++ results are from [http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html) and clang.)

**Comment by StefanKarpinski** [comment]
I personally like the way Julia's `@printf` prints these, but then again, I wrote the code originally so that's not shocking. I would make `%g` match and then we could consider whether we need to match C or have an option to do so. I suspect it's fine. The difference, however, should be documented.

**Comment by dfannius** [comment]
Sounds good. `%g` and `%G` have to handle `NaN` and `Inf` too, so I assume that they should be consistent with Julia's `%[eEfF]` in that respect (both now and in the future if they ever change).

**Comment by ScottPJones** [comment]
I checked, and there is nothing in Base that uses `%E` or `%F`, and only one registered package that uses `%E` (`OptimPack.jl`).
I wonder if maybe then, `%E`/`%F`/`%G` could be changed to output `NAN`/`INF`, as per C/C++/etc.,
and have `%e`/`%f`/`%g` output `NaN`/`Inf`.
That would be most consistent to current behavior (and internally consistent, even if not %100 consistent with C for the lowercase versions).
Then, if you *really* want C/C++ lower case `nan`/`inf`, get that option into @tbreloff's `fmt` changes, and then people can use that.

**Comment by nalimilan** [comment]
I don't really see the point of retuning `nan`/`inf` or `NAN`/`INF`, since these appear as `NaN`/`Inf` in Julia. Making `%E`/`%F`/`%G` different would create more confusion than anything IMHO.

**Comment by ScottPJones** [comment]
OK, the C/C++ compatible forms should then be just in something like `fmt` (in `Formatting.jl`), and I think `@printf` `%g`/`%G` should also use the "Julian" forms (`Inf` and `NaN`) (I think it looks better also), and have the documentation for the `@printf` family changed.

**Comment by ScottPJones** [comment]
Maybe also just deprecate using the uppercase forms for `@printf` family, and change that one package.

**Comment by dfannius** [comment]
I started another issue for the capitalization question, so that my pull request (if eventually accepted) can completely resolve what remains of this one.

**Comment by StefanKarpinski** [comment]
+1 – that's the way to do it
