### ISSUE TITLE
memory mapping bug?

### ISSUE THREAD

**Issue by Cody-G** [JuliaLang/julia#11693]
Hi, when I assign iteratively to a large memory mapped array, memory usage quickly increases until all system memory is consumed (as shown via the "top" or "free" commands in linux).  In the example below, I would expect to see memory usage to peak at about 2% of the space occupied by the memory mapped array at any given time.  However the code below gradually consumes all system memory, and I'm not sure why.  Thanks for your help!

    p,fid = mktemp()
    a = mmap_array(Float64, (600,600,600,100), fid); #allocates about 170GB of disk space

    #fill a, about 1.7GB per iteration
    for i = 1:100
        a[:,:,:,i] = 3
    end

**Comment by vtjnash** [comment]
eventually you would have touched all of the array, so it is expected that this would eventually drive the free memory reported by top towards zero. does the system start thrashing badly at that point, or does it stablize at that point (the expected behavior)? linux won't necessarily bother swapping out these pages back to disk until you actually request more physical pages. otherwise, it is more efficient for the OS to be always running with essentially zero free pages.

if you wanted to write a file containing 170GB of the number 3, it is far more efficient to use file IO operations, because this allows the kernel to assume you are not as likely to try to go back and read a random portion of the array, and thus allows it to page the file out to disk more aggressively. (the kernel will usually try to avoid writing out "hot" memory -- e.g. memory that you have just written to will usually be the last thing the kernel wants to evict from memory)

**Comment by Cody-G** [comment]
On my system it does thrash a bit, but then it stabilizes.  I tested this by opening a second instance of julia and making another allocation while the above loop is running.  Julia opens slowly and is a bit slow to make the first allocation, but then it speeds up after that (and the memory usage of the first julia instance decreases as reported by to p).  So that solves my problem...thanks!

Also thanks for enlightening me about how the kernel works!  I'll take your advice when I'm writing 3s, and other numbers as well ;-)
