### ISSUE TITLE
add test for: Windows output redirection trouble

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#11727]
Steps to reproduce (this is in Cygwin cross-compile, I'll also check in MSYS2 to see if it's any different there):

```
$ git clone git://git.kitenet.net/moreutils
$ make clean && make testall1 | moreutils/ts -s
```

Full output is at https://gist.github.com/tkelman/4d9717ae288c637a6432 - note the `jl_uv_writecb() ERROR: invalid argument EINVAL` during the later bootstrap stages which seems to be non-fatal, but when running the tests it is fatal. `ts` is a perl script, but we have similar messages on the Windows buildbots where I think python is driving the process and logging: http://buildbot.e.ip.saba.us:8010/builders/package_win8.1-x64/builds/864/steps/make/logs/stdio

This has been happening for quite a while, I think @staticfloat and I hit this error the last time we tried to enable running the tests on the Windows buildbots so this is probably a blocker to doing that.

versioninfo:

```
Julia Version 0.4.0-dev+5413
Commit fecadcb* (2015-06-16 17:23 UTC)
Platform Info:
  System: Windows (i686-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

---

edit: minimal reproduction:

``` julia
$ (usr/bin/julia -e "println('a')" && usr/bin/julia -e "println('b')") | cat
a
bERROR: write: invalid argument (EINVAL)
 in uv_write at stream.jl:1024
...
```

**Comment by staticfloat** [comment]
Grrr, yes.  I remember this.  I'm pretty sure it has something to do with the way libuv handles cygwin pipes on windows.

**Comment by vtjnash** [comment]
is this still broken for you? i currently can't seem to reproduce it on master on my machine.

**Comment by tkelman** [comment]
Yes, at 298231e83291ad4d29be this is still happening. Cygwin64 build of win64 Julia (last month was win32 but looked the same), windows 7. I have `MARCH = x86-64` in my `Make.user` but I'd be surprised if that made any difference.

I do recall this being picky about not always happening in an incremental build, are you running the exact command verbatim including the `make clean`?

**Comment by vtjnash** [comment]
This seems to be an implementation error with the implementation of UV_HANDLE_EMULATE_IOCP in libuv commit https://github.com/libuv/libuv/commit/54982a23efc2d47333d60223f59e773dec365327 . In particular, overlapped->hEvent was not initialized prior to ReadFile / WriteFile per https://msdn.microsoft.com/en-us/library/windows/desktop/ms686358(v=vs.85).aspx, so it is still NULL when passed to RegisterWaitForSingleObject, which thus returns ERROR_INVALID_PARAMETER.

This happens here because the NamedPipe handle is getting passed to multiple libuv (Julia) processes and apparently only one process may make an IOCompletionPort for a NamedPipe (not documented, although the restrictions given are pretty troubling -- for example, the handle should not be duplicated, shared, or passed to CreateProcess: https://msdn.microsoft.com/en-us/library/windows/desktop/aa363862(v=vs.85).aspx), forcing libuv to use the fallback emulation code. (partially related, this appear to also indirectly be caused by a resource leak in the Windows kernel where the OS is failing to destroy `uv_loop.iocp` after program termination, but it is not valid for destruction prior to program termination because we can't close the stdio objects that we've associated with it).

**Comment by eschnett** [comment]
I've just encountered this error when building the Julia release-0.4 branch with Cygwin. Does this mean that building with Cygwin is currently broken? If there's no immediate prospect of having this corrected, should the build instructions be updated to warn about this?

**Comment by vtjnash** [comment]
you just can't build with output going to a pipe

**Comment by ihnorton** [comment]
Additional comments from @vtjnash about this issue:
> 1. the code to initialize `overlapped->hEvent` is missing from pipe.c
> 2. the parallel code in tty.c (from which the pipe.c code was copied) is correct

**Comment by tkelman** [comment]
^ care to comment or explain there? this needs doing to allow running windows tests on buildbot. does @ihnorton or anyone else know how?

**Comment by tkelman** [comment]
This issue is now preventing windows binaries from being built on master, ever since #18588. How hard is this to fix, can we please do so if it's possible?

> the code to initialize `overlapped->hEvent` is missing from pipe.c

What should it be initialized to?

**Comment by vtjnash** [comment]
No idea, but there's a correct implementation in `tcp.c` that should be useful as a reference. The libuv folks just forgot to copy over some code when they implemented the one in `pipe.c`.

In theory, I think the workaround should be easy by just redirecting IO through a pipe: `cat | ./julia | cat`

**Comment by tkelman** [comment]
redirecting to a pipe is what causes the problem here

**Comment by vtjnash** [comment]
redirecting to the *same* pipe causes the problem here. I don't think I've seen any issues with redirecting to a cygwin pipe.

**Comment by tkelman** [comment]
redirecting what to the same pipe?

this is an example that fails in a cygwin cross-compile build right now: `make cleanall && make -j4 install | tee install.log 2>&1`

**Comment by staticfloat** [comment]
This is happening on the new buildbots.  During `make` time, [we get a bunch of `EINVAL` error codes](https://buildog.julialang.org/#/builders/74/builds/20/steps/4/logs/stdio) from `jl_uv_writecb()`, and `make test` [fails immediately with a backtrace](https://buildog.julialang.org/#/builders/74/builds/20/steps/5/logs/stdio).

This does not happen when running from a `bash` shell, so I assume this is because the `buildbot-worker` process capturing the output of the Julia executable is causing this issue.

**Comment by staticfloat** [comment]
@tkelman can you please verify that this PR fixes the problem on windows for you: https://github.com/JuliaLang/libuv/pull/44

In my testing, it seems to have worked, but I'd like to be doubly sure. :)

**Comment by tkelman** [comment]
It can start running tests, but cmdlineargs is freezing.

**Comment by staticfloat** [comment]
Are you sure it's actually cmdlineargs and not just the Julia waiting for a
worker to join that never does?  cmdlineargs is the last test, so if we've
got some kind of join() lockup, that might be the problem.
-E

**Comment by tkelman** [comment]
it hasn't been the last test in a while afaik

**Comment by staticfloat** [comment]
Really?  Looking at the latest [linux64](https://build.julialang.org/builders/build_ubuntu14.04-x64/builds/439/steps/shell_2/logs/stdio) and [osx64](https://build.julialang.org/builders/build_osx10.9-x64/builds/516/steps/shell_2/logs/stdio) testing runs on the buildbot, it's listed as the last.

**Comment by tkelman** [comment]
run in a single worker, it definitely isn't the last to start

**Comment by staticfloat** [comment]
Ah, I see, so you're saying that running the tests in a single worker freezes on `cmdlineargs`?

**Comment by tkelman** [comment]
It's looking like it's an unrelated problem. `make testall1` finishes running `enums` but never finishes with the next test which is `cmdlineargs`. Though there was an assertion failure before that for older commits, trying to figure out what fixed that.

**Comment by tkelman** [comment]
the freeze in the cmdlineargs tests looks like it was caused by 94acb6f47dceeb2d44a4f0952cc9146723f9ec98

**Comment by vtjnash** [comment]
upstream's problem now

**Comment by tkelman** [comment]
it will regress if not tested here. come on, what is so hard about following the standard policy we've always had of adding a test when you fix a bug?
