### ISSUE TITLE
Julia Crypto

### ISSUE THREAD

**Issue by 0x75** [JuliaLang/julia#11783]
Hello dear Julia Team.

In modern times i think it is crucial to have a solid crypto implementation.
Academia has never been save and is less than ever. So having solid crypto is a must.
Since the implementation is more important and error prone than in other fields i suggest following approach:

Select a dedicated and experienced crypto core team. take a solid library like dj Bernsteins NaCL (or its followups) as reference. Implement easy to use crypto routines for files and network connections.
I have not used the network routines at all in Julia, one wants a method to very quickly establish a secure
connection from a to b without thought. like   int connection = connect(ip,port, bool encrypted) (sorry about the c).

Start introducing encrypted datatypes (open new field of research).

**Comment by jiahao** [comment]
Thanks for your interest. For broad suggestions of this form, we recommend that authors try out ideas in external packages and we can discuss whether or not the features should belong in the base library once the code is properly fleshed out.

**Comment by JeffBezanson** [comment]
We do have some things, such as https://github.com/staticfloat/Nettle.jl

**Comment by tkelman** [comment]
Also refer to #9744, and https://github.com/JuliaWeb/Roadmap/issues/5

**Comment by sbromberger** [comment]
I think we need to separate Crypto from network, at least initially. This is because there are at least two (abandoned?) efforts to implement OpenSSL - but the crypto functions, not the TLS/SSL functions. (The latter are desperately needed in Julia, I believe. It's a shame we didn't get the GSoC slot for this project.)

In any case, moving forward, I'd love to see a robust, maintained OpenSSL.jl somewhere with both crypto, randomness, and networking built in (similar to how pyOpenSSL does it).

The issue with this is that ideally, we'd replace  things like `Base.download()` with these functions, but it appears to be nontrivial to merge OpenSSL-linked code into Base given the licensing conflict (see https://github.com/JuliaLang/julia/issues/10763 and https://github.com/JuliaWeb/Roadmap/issues/5#issuecomment-84413539 for some additional background).
