### ISSUE TITLE
Restrict @doc to recognised syntaxes

### ISSUE THREAD

**Issue by one-more-minute** [JuliaLang/julia#11850]
As we get more syntax sugar for `@doc` there's more risk of confusion – if the syntax is slightly wrong you end up documenting the value of a function call (for example) which isn't all that useful. For that reason, perhaps only a clearly-specified set of syntaxes should be allowed, with everything else throwing an error.

This also makes it easier to add more syntax in future without breaking code.

**Comment by one-more-minute** [comment]
Now I think about it, there are actually decent use cases for this, e.g. documenting the values of an enum or `nothing`. Much better would be to improve the handling of documentation for variable bindings.

**Comment by StefanKarpinski** [comment]
Well, maybe we don't need the docstring syntax for that – you could explicitly stick things in the META dict. There's a legitimate danger that the expression following a doc string will not be recognized by the macro, which will therefore evaluate the expression and apply the docstring to the resulting value, which is unlikely to be what was intended.

**Comment by JeffBezanson** [comment]
This issue needs a description or an example.

**Comment by StefanKarpinski** [comment]
The expand on what I was saying, this could be an error:

```jl
"some string"
123
```

Since it's way too easy to do this:

```jl
"some string"
expression_that_returns_some_value()
```

and accidentally end up "documenting" the return value of the following expression. Instead, I would propose that only certain syntactic forms (types) and kinds of values (functions, types), be accepted by the `@doc` macro emitted for docstring syntax, and everything else would be an error. If you actually want to document a plain value like the number `0` or the value `nothing`, then you can express that more explicitly.

**Comment by one-more-minute** [comment]
Having `@doc` throw an error when it doesn't recognise the syntax – as opposed to just documenting the value of the expression – does seem like a reasonable thing to do. One can always use `doc!()` directly for documenting values, which is probably a fairly unusual case.

It might make sense to allow obvious syntaxes for value docs, e.g. a single symbol on its own, or allow certain types of value through (e.g. function, enum) because we already use these quite a lot and it's pretty convenient.
