### ISSUE TITLE
REPL OutOfMemoryError using MPFR

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaLang/julia#12049]
I am doing calculations using BigFloats, and encountered an error when taking an unsafe_view of an array of BIgFloats in the REPL.

Here is the code

```julia
using ArrayViews

set_bigfloat_precision(80)

b = rand(3,3)
b2 = Array(BigFloat, 3,3)

for i=1:9
  b2[i] = convert(BigFloat, b[i])
end

view_b2 = view(b2, :, 1)
println("created view")
unsafe_view_b2 = unsafe_view(b2, :, 1)
println("created unsafe_view")
```

The code run successfully if I do include("file.jl") in the REPL, but if I paste line 14 (second from the end) into the REPL directly, it causes an error:

```
ERROR: OutOfMemoryError()
 in string at mpfr.jl:770
 in showcompact_lim at show.jl:94
 in sprint at iostream.jl:205
 in alignment at show.jl:928
 in alignment at show.jl:956
 in print_matrix at show.jl:1031
 in print_matrix at show.jl:1023
 in anonymous at replutil.jl:23
 in with_output_limit at ./show.jl:1231
 in writemime at replutil.jl:23
 in display at REPL.jl:113
 in display at REPL.jl:116
 in display at multimedia.jl:151
 in print_response at REPL.jl:133
 in print_response at REPL.jl:120
 in anonymous at REPL.jl:599
 in anonymous at REPL.jl:805
 in anonymous at LineEdit.jl:762
 in prompt! at ./LineEdit.jl:1581
 in run_interface at ./LineEdit.jl:1549
 in run_frontend at ./REPL.jl:842
 in run_repl at ./REPL.jl:165
 in _start at ./client.jl:454
```

It looks to me like this is a REPL issue rather than an ArrayViews issue, although taking a normal view (line 12) works correctly when pasted into the REPL.

Versioninfo:

```
Julia Version 0.4.0-dev+5149
Commit 317a4d1* (2015-06-01 18:58 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU       Q 820  @ 1.73GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by simonster** [comment]
This is an ArrayViews issue. As implemented there, `getindex` for an `unsafe_view` will not work with non-`isbits` types such as BigFloats, which is why you can't display the array. Because the BigFloat returned by `getindex` is invalid, Julia thinks it needs to allocate an enormous amount of memory to display it, hence the ReadOnlyMemoryError.

This could probably be hacked to work (in ArrayViews), but you're not going to gain much by making an `unsafe_view` of BigFloats or other non-`isbits` types, since the amount of memory an ordinary view needs to allocate will be small by comparison to the allocation required for the objects themselves, or, in the BigFloat case, the allocation required to do math.

**Comment by JaredCrean2** [comment]
It might be worth making it work in ArrayViews for compatibility even if there is no performance benefit.  Being able to run a code with Float64s most of the time and check it occasionally with BigFloats would be a nice feature.

Anyways, for now I'll use an ordinary view.
