### ISSUE TITLE
pointer(x, i) should be inlined

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#12054]
I think it should actually use `getelementptr`, which would require a new intrinsic (which might conflict out #11973), but seems like the right way to do address computation. At the very least it needs some `@_inline_meta` magic. (The inliner thinks there's a branch checking `isbits(T)`, but that branch is always optimized out.) I'll handle this if someone tells me which approach to take.

**Comment by vtjnash** [comment]
i hate that function.

i propose just implementing the optimizations to make Ref equally efficient so that `pointer` can finally just go away. it should be very feasible without too much actual work.

---

also, i've declared a moratorium on any further codegen improvements until #11973 is resolved. codegen is really just too overdue for the cleanup and documentation that PR represents, and it is not practical to continue adding features to the current design.

**Comment by StefanKarpinski** [comment]
Jameson, what's your plan for replacing pointer with Ref?

**Comment by JeffBezanson** [comment]
Looks like the branch is actually in `elsize`.
