### ISSUE TITLE
Error in internal `_getindex` method?

### ISSUE THREAD

**Issue by davidagold** [JuliaLang/julia#12066]
I'm writing tests for `abstractarray.jl` and noticed a possible error in this line:
https://github.com/JuliaLang/julia/blob/918ee650539fbe3b50ea5e1efb915ebe7cbdfe31/base/abstractarray.jl#L432

In particular, `_getindex` doesn't appear to have a method for the signature on which it is called in the RHS:
```
julia> which(Base._getindex, (AbstractArray, Int))
ERROR: no method found for the specified argument types
 in which at ./reflection.jl:285
```

I imagine `getindex` was intended?

Pinging @mbauman who may be interested.

EDIT: Can also be seen on line 434.
EDIT2: Also https://github.com/JuliaLang/julia/blob/918ee650539fbe3b50ea5e1efb915ebe7cbdfe31/base/abstractarray.jl#L524 and 526.

**Comment by ScottPJones** [comment]
:+1: for adding the tests! :clap:

**Comment by tkelman** [comment]
@davidagold heads up, when you link to lines of code on github, it's a good idea to hit `y` then github will refresh the page with a commit sha in the url, so links will point to the same line of code even if master changes

**Comment by davidagold** [comment]
@tkelman Thank you for the heads up! Edit'D.

**Comment by mbauman** [comment]
Oh my, right you are.  Thank you for the catch!  I did intend to use the `_` methods there; they just need a linearindexing argument.  My reasoning at the time was that, for `LinearSlow` arrays, the linear index still needs to be resolved to the proper dimensionality, so we can just take a short-cut and stay within the internal methods without trying the real `getindex` method.  In general, the goal here is to *always* stay within the internal `_function` until we're sure we're calling the canonical user-defined method.  That doesn't always happen (it's really hard to do so for general multidimensional indexing), but it's something that I aim to fix this fall. 

But even that's not right.  We also need to be careful about the dimensionality of the LinearSlow array, since if we try to call `_getindex(LinearSlow(), A, 1)` on a "LinearSlow" vector (which is quite the misnomer) we'll get an error.

**Comment by mbauman** [comment]
Thanks again, @davidagold!  Let me know if you have any questions about the problem or the fix.

**Comment by davidagold** [comment]
@mbauman My pleasure! Glad to be able to help. I'm coming across other possible bugs. For instance, consider:

```julia
type UnimplementedFastArray{T, N} <: AbstractArray{T, N} end
Base.linearindexing(::UnimplementedFastArray) = Base.LinearFast()
Base.size(::UnimplementedFastArray) = 0
ndims{T, N}(::UnimplementedFastArray{T, N}) = N

type UnimplementedArray{T, N} <: AbstractArray{T, N} end
Base.size(::UnimplementedArray) = 0
ndims{T, N}(::UnimplementedArray{T, N}) = N
```
```
julia> U = UnimplementedFastArray{Int, 2}()
0-element UnimplementedFastArray{Int64,2}

julia> U[1]
ERROR: indexing not defined for UnimplementedFastArray{Int64,2}
 in getindex at abstractarray.jl:424

julia> U[1, 1]
ERROR: BoundsError: attempt to access 0-element UnimplementedFastArray{Int64,2}
  at index [1,1]
 in throw_boundserror at abstractarray.jl:150
 in getindex at abstractarray.jl:424

julia> V = UnimplementedArray{Int, 2}()
0-element UnimplementedArray{Int64,2}

julia> V[1]
ERROR: BoundsError: attempt to access 0-element UnimplementedArray{Int64,2}
  at index [1]
 in throw_boundserror at abstractarray.jl:150
 in getindex at abstractarray.jl:424

julia> V[1, 1]
ERROR: indexing not defined for UnimplementedArray{Int64,2}
 in getindex at abstractarray.jl:424
```
Seems like we'd want each of these to throw `ERROR: indexing not defined for ... `, right?

Should I open a separate issue for this?

**Comment by mbauman** [comment]
I think those are ok. You've defined the size to be 0, so there's no way we can safely resolve multidimensional indexes to a linear one without a bounds error. Others can chime in, but I think it'd be hard to change that error message.

**Comment by davidagold** [comment]
I defined `size` because otherwise I received this error:

```
julia> U = UnimplementedFastArray{Int, 2}()
julia> getindex(U, 1, 1)
ERROR: MethodError: `size` has no method matching size(::UnimplementedFastArray{Int64,2})
Closest candidates are:
  size{T,n}(::AbstractArray{T,n}, ::Any)
  size(::Any, ::Integer, ::Integer, ::Integer...)
 in getindex at abstractarray.jl:424
```

In any case, I suppose I just don't understand why the errors are asymmetric in the number of index arguments between `LinearSlow` and `LinearFast` array types that haven't defined a default scalar `getindex` method. That is to ask: why is there no default method to kick in to throw `ERROR: indexing not defined for UnimplementedArray{Int64,2}` for `getindex(U, 1, 1)`, but there does appear to be such a method for `getindex(V, 1, 1)`?

**Comment by mbauman** [comment]
The trouble is that when you index with a "non-canonical" number of indices (`N!=1` for LinearFast), we must compute the linear index using `sub2ind`. The way that works is to go through and multiply each index by its stride and sum them all together. The strides are defined by the size, and then it's just a matter of doing the math.  Doing this computation is inherently "unsafe" — even if the math works out such that the linear index is in-bounds, one of the indices might have been out-of-bounds (but the others compensated).  So we must check bounds before resolving the linear index.  

That's why there's an asymmetry in the error message here: there's no way we can safely compute the linear index without checking bounds.  If you instead defined `size` to be nonzero, then all in-bounds accesses will give you an unimplemented error. 

Also note that `size` needs to return a tuple `(0,)` in order to comply with the AbstractArray interface, and you shouldn't need to define `ndims`.

**Comment by davidagold** [comment]
Ah, I understand now. Thank you for taking the time to explain. =)

Actually, one more question: what is a stride?

**Comment by johnmyleswhite** [comment]
Strides come up when discussing array-like structures whose elements are evenly spaced, but potentially not contiguous. The stride is essentially the distance between sequential elements. There's some useful ideas here: http://compgroups.net/comp.lang.fortran/purpose-of-stride-in-blas/593894

**Comment by davidagold** [comment]
Thank you for the resource, John!

I think that's all from me on this and related issues for now. @mbauman I will ping you when my test PR is ready (hoping for tomorrow).
