### ISSUE TITLE
InexactError on failed spawn

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#12176]
backtrace:
```
ERROR: InexactError()
 in uv_return_spawn at process.jl:242
```

**Comment by tkelman** [comment]
I was meaning to file exactly this issue, sorry I didn't get around to it yet - one of these is `STATUS_DLL_NOT_FOUND` if you for example rename `libiconv-2.dll` then try to do ```run(`iconv --version`)```. I tried changing that line to `proc.exitcode = exit_status % Int32` but that resulted in assertion failures in libuv, arguably worse since it exits Julia. Don't think even latest libuv has the greatest of handling of these. The exit status in libuv is a 64-bit integer though, so maybe the `exitcode` field of our `Process` type should be too?
