### ISSUE TITLE
should convert(Float64, 2^53+1) be an InexactError?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#12187]
On the one hand, this seems to break the "convert only does lossless conversion" contract:

``` jl
julia> convert(Float64, 2^53+1) == 2^53+1
false
```

I've made a few false starts on changing this so that you have to write `round(Float64, 2^53+1)` instead of using `convert`. One could generically define `convert` like this for most cases:

``` jl
function convert{T<:FloatingPoint}(::Type{T}, x::Integer)
    y = round(T, x)
    z = oftype(x, y)
    x == z ? y : throw(InexactError())
end
```

This works and even generates pretty good code in most situations, but it raises some troubling issues. Going beyond integers, what about `Rational` and `Irrational` numbers? Should we write `round(Float64, π)` instead of `convert(Float64, π)`? But then expressions like `2pi` won't work since they rely on `convert` to get the arguments into a common type. Similarly for `(2//3)*x` when `x` is `Float64` for example – since you cannot represent `2//3` exactly as a `Float64` – or any other binary floating-point type – this will always be an inexact conversion.

Here are the options that occur to me:
1. Leave it as is – converting to floating-point types is implicitly lossy.
2. Draw a line between integers and rationals and irrationals. The `Rational` and `Irrational` types exist primarily to allow writing generic code that use constants with the desired precision, so being finicky about converting them defeats their primary purpose. `Integer` types, on the other hand, are very much legitimate computational types.
3. Change promotion to calling `round` instead of `convert` when converting to floating-point types.

**Comment by jiahao** [comment]
On the other hand, we have:

```jl
julia> convert(Float64, 2^53+1)/1 == (2^53+1)/1
true
```

**Comment by StefanKarpinski** [comment]
So division is not an injective operation – even division by 1. What's the relevance?

**Comment by jiahao** [comment]
Oops, I deleted the rest of that comment with a space.

What I meant to say is that this issue is really about whether constructing a floating point number must necessarily involve a rounding operation _fl()_. It's reasonable to consider `convert(Float64, x)` as equivalent to _fl(`x`)_, since we already have other functions that are implicitly defined to use _fl()_, like `/`.

If you agree with identifying `convert(Float64, x)` with _fl(`x`)_, then arguably according to IEEE 754-2008, you have to do either Option 1, unless the inexact exception is trapped, in which case, raise an `InexactError`. The standard says (p 50):

> 7.6 Inexact
> Unless stated otherwise, if the rounded result of an operation is inexact — that is, it differs from what would have been computed were both exponent range and precision unbounded — then the inexact exception shall be signaled. The rounded or overflowed result shall be delivered to the destination.

**Comment by eschnett** [comment]
My "gut feeling" tells me that floating point numbers are always lossy, thus convert shouldn't complain. I would expect such a change to break a lot of code, or require many work-arounds (calling `round` instead of `convert`?), indicating that the change is not worthwhile.

**Comment by ScottPJones** [comment]
The problem is not when people call `convert` explicitly, the problem is when Julia decides to use `convert` in situations such as storing data into a collection.
Maybe there needs to be a `safe_convert` function, which does throw the `InexactError`.
If `convert` really did have a contract that it only would do lossless conversion though, then either `convert` needs to be changed, or people warned that there is no such contract, and a function introduced that does honor that contract.
For performance, it might also be useful to have a function that would let you know if all values of type A can be converted to type B without loss of information, so that for those types, `convert` == `safe_convert`, and no run-time checking of values is needed.  For instance, `Int32` can always be safely converted to a `Float64`, but `Int64` cannot. If Julia had a `Float80`, as far as I understand the IEEE 80-bit format, that could safely store both `Int64` and `UInt64`.
Another useful thing to know might be which types a type can be converted to without loss, and a way of figuring out a "least common type" that two types can always be safely converted to, or if `Any` or a `Union` is needed.

**Comment by ScottPJones** [comment]
This is where I think the real problem may lie:
```julia
julia> promote_type(Int64, Float64)
Float64

julia> promote_type(Int128, Float64)
Float64

julia> promote_type(BigInt, Float64)
Base.MPFR.BigFloat
```
It would seem to me that `promote_type` should be returning `Base.MPFR.BigFloat` in all 4 cases,
if you don't want information loss.
The other thing that makes all of this more complicated is that integer literals all end up type `Int` or larger, instead of `Int8`, `Int16`, `Int32`, `Int64`, etc. depending on the size of the literal, so that you can't tell just by looking at the type that literals such as 0, 1, 100000 could actually be converted safely to a `Float64` on a 64-bit machine.

**Comment by simonster** [comment]
@StefanKarpinski, do you have examples of specific cases in which the current behavior is problematic?

**Comment by StefanKarpinski** [comment]
Hah. I actually just tried to concoct a problematic case with different behavior depending on whether an untyped or typed dict was being used, and got this error:

```jl
julia> d = Dict()
Dict{Any,Any} with 0 entries

julia> d[2^53] = 1
1

julia> d[2^53+1] = 2
2

julia> d
Dict{Any,Any} with 2 entries:
  9007199254740993 => 2
  9007199254740992 => 1

julia> t = Dict{Float64,Any}()
Dict{Float64,Any} with 0 entries

julia> t[2^53] = 1
1

julia> t[2^53+1] = 2
ERROR: ArgumentError: 9007199254740993 is not a valid key for type Float64
 in setindex! at dict.jl:616
```

So, that's actually already not a problem, which is pretty nice. Maybe this is fine.

**Comment by ScottPJones** [comment]
Well, that is only not a problem because whoever wrote `dict.jl` did some defensive programming in the `setindex!` method and all the `get!` methods, i.e.:
```julia
    key = convert(K,key0)
    if !isequal(key,key0)
        throw(ArgumentError("$key0 is not a valid key for type $K"))
    end
```
which means that there is an extra performance penalty.
If there were a `safe_convert` function, that could be used without the `!isequal` check (and additionally,
if the compiler determined that due to the types, it was always safe, no extra checking need be done at all).

**Comment by JeffBezanson** [comment]
To me accepting roundoff is part of working with floats, and is the expected behavior. Nobody who's serious about Float64s would want Int+Float64 = BigFloat since it's too slow to be useful. After all, floats can't even losslessly represent the results of their own computations. The entire point of floats is to offer an acceptable amount of information loss in exchange for great efficiency. If the amount of information loss is not acceptable, then the entire field of numerical analysis comes into play, or else you need to use a different type from the beginning.

**Comment by ScottPJones** [comment]
That's fine, when you explicitly want to work with floats, to me, the issue is when Julia decides to do a conversion for you (instead of using a type that can hold all values), and loses information.  For example:
```julia
julia> [0x8000000000000000, -1]
ERROR: InexactError()
 in setindex! at array.jl:304
 in hvcat_fill at abstractarray.jl:935
 in vcat at abstractarray.jl:696
 in vect at abstractarray.jl:42
julia> [0x8000000000000000, 1.0]
2-element Array{Float64,1}:
 9.22337e18
 1.0       
```
If one really wanted the information loss,  one could have written `Float64[0x8000000000000000, 1.0]`
To prevent silent information loss, all that needs to be done is have the untyped `[ ]` constructor return either a `Vector{Union{Float64,UInt64}}` or `Vector{Any}`, or have it call still return a `Vector{Float64}`, but use a `safe_convert` method that would throw an `InexactError` consistent with the `UInt64/Int64` case above.

**Comment by StefanKarpinski** [comment]
On the other hand, putting a `UInt` and a `Float64` in a homogenous array together is kind of a strange thing to do. Related thought experiment – is it problematic to have this:

```jl
julia> [1.5, 2//3, pi]
3-element Array{Float64,1}:
 1.5
 0.666667
 3.14159
```

If having `[0x8000000000000001, 1.0][1] != 0x8000000000000001` is bad but `[pi, 1.0][1] != pi` and `[2//3, 1.0][1] != 2//3` are ok, that seems like evidence that the second option is the right one: i.e. silently converting `Rational` and `Irrational` values in a lossy way is ok but silently converting `Integer` valuers isn't.

**Comment by ScottPJones** [comment]
I don't see `[2//3, 1.0]` ending up as a `Float64` automatically is good either, I think somebody should write either `Rational[2//3, 1.0]` and get back `Rational[2//3, 1//1]`, or write `Float64[2//3, 1.0]`, and get back `Float64[0.666667, 1.0]`.  Note in that *particular* case, no information is lost when converting `1.0` to a `Rational`, but it is lost when converting to a `Float64`.

I worry more though about the type of cases that @JeffBezanson pointed out in #12128,
where I'd rather never see conversions of whole collections placed into an array.

**Comment by ScottPJones** [comment]
```julia
julia> Real[2//3, 1.5, pi]
3-element Array{Real,1}:
 2//3                  
  1.5                  
 π = 3.1415926535897...
```

**Comment by mschauer** [comment]
The title reminds me that 2^53 is 0, maybe... #5573.

**Comment by nalimilan** [comment]
I'm sympathetic with option 2 based on the idea that integers are of a different nature than floats and irrationals. For example, if I attempted to store observation IDs in a `Float64`, I'd rather get an error than a silent rounding, which would merge different individuals/groups together. That said, I'm not sure how such a situation could arise. Maybe when filling an array created by importing data from a poorly-typed source, like CSV.

I think this raises the question about the "contract" a type respects. When converting `Int64` to `Int32`, we enforce the "contract" that the `Int64` will be represented exactly, or an error will be raised. Why not when converting to `FloatingPoint`? Shouldn't the "contract" only depend on the original type, and not on the destination? This would be more consistent IMHO, even if arithmetic operations aren't checked, in part for performance, in part for convenience reasons.

**Comment by StefanKarpinski** [comment]
Loading CSV data is a good example. What if you have a mix of data in a single column including the strings `1.5` and `9007199254740993`? I guess the CSV reader could be careful about making sure that it doesn't lose information in cases like this, but maybe the convert function should just do that for you.

@nalimilan, I'm not sure I follow your argument about the contract only depending on the source type. Why should that be the case?

**Comment by nalimilan** [comment]
> Loading CSV data is a good example. What if you have a mix of data in a single column including the strings 1.5 and 9007199254740993? I guess the CSV reader could be careful about making sure that it doesn't lose information in cases like this, but maybe the convert function should just do that for you.

@StefanKarpinski I don't think the conversion function can really handle this, as the issue regards choosing a correct type in the first place (more like `promote`). In the case of CSV import, I think any inexact conversion should be an error by default: it should be stricter than standard conversions where the user explicitly asked for a given destination type. Or a type that can represent all the data without loss (like a string) should be used.

> @nalimilan, I'm not sure I follow your argument about the contract only depending on the source type. Why should that be the case?

My point is that if you store numbers as integers, it means you don't consider them as continuous: losing precision is not acceptable, contrary to floats. This is typical of unique identifiers or of loop counters (you don't want `n` and `n+1` to be ever considered as equal). So whatever the type towards which the conversion is attempted, Julia should guarantee that the original number is preserved exactly, because you considered it as an essential property of your data.

**Comment by JeffBezanson** [comment]
I think we should leave this as-is.
