### ISSUE TITLE
Precompilation doesn't know about environment variables

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#12239]
```jl
module MyModule

println(ENV["MYVAR"])

end
```
and start julia with
```sh
MYVAR=5 julia
```
Saying `using MyModule` works, but `Base.compile(:MyModule)` complains about not knowing about `MYVAR`.

The most important (but not only) place I've seen this come up is when defining `JULIA_PKGDIR`. I have a server where everyone uses a set of packages stashed in `/usr/local/julia/packages`. Under such circumstances, it's not possible for folks to precompile packages with dependent packages.

Presumably it has to do with [these lines](https://github.com/JuliaLang/julia/blob/50a1068d25dd7e655c6da77c8d48ea23f21acd4f/base/loading.jl#L228-L232), but to me it's not obvious what the right solution is (I'm not clear on how `ENV` gets populated).

**Comment by JeffBezanson** [comment]
Must be because of the `detach`. I'm not sure why we would need that.

**Comment by vtjnash** [comment]
this was intentional.

https://github.com/JuliaLang/julia/blob/50a1068d25dd7e655c6da77c8d48ea23f21acd4f/base/loading.jl#L232-L240 is the environment allowed to pass to the child compile unit. `JULIA_PKGDIR` should be added to that list.

**Comment by timholy** [comment]
OK, when I get time to fix this I'll also add a keyword argument to let users add more environment variables.

**Comment by JeffBezanson** [comment]
It's not obvious to me that hiding environment variables from the child process is the right default.

**Comment by timholy** [comment]
To be honest, nor do I---it seems that by default, you'd want to replicate the same environment that `using X` sees without precompilation. @vtjnash, can you explain your thinking a bit more?

To give another example, we also define `JULIAFUNC` to point to the repository that holds the lab's own code. There are several others, too. Hence my interest in allowing customization of the environment variables, if we don't solve this simply by exposing all of them.

**Comment by vtjnash** [comment]
the problem is that "replicating the environment that will be seen by `using X`" is exactly the empty set of environment variables. adding any to that set at compile time means that the set could be different at runtime.

the basic goal here is to strongly discourage attempts to do build-time customizations that are going to get frozen into the cache (aka CPPFLAGS / aka Makefile-hell). for that same reason, `--startup-file=no` is also getting passed to the child to inhibit environment customization.

additionally, there may be interest at some future point (when doing more automatic caching) in inverting some of the cache-file location lookup logic to find the source file first, then attempt to find the exact matching cache file, before going back to load the source file.

**Comment by JeffBezanson** [comment]
I'm not sure I buy it. This is the passive-aggressive approach, where we make something mysteriously fail to punish the user for doing something they "shouldn't do". Simply leaving environment variables alone seems like a reasonable default to me. Especially since we use the `JULIA_PKGDIR` variable ourselves. People might have env vars or stuff in `.juliarc.jl` that's necessary to make julia work at all in their environment. Isn't it just as likely to get a bug from the source version of a package seeing .juliarc.jl, but the precompiled version *not* seeing it?

**Comment by ScottPJones** [comment]
Would it be possible (or necessary to get the behaviour you want) to make a hash on .juliaarc.jl, and also any environment variables that are listed (as in the above comment) as being passed in, and recompiling if that's changed?

**Comment by stevengj** [comment]
I tend to agree with @JeffBezanson that leaving the environment alone is the most sane default.  

People should be cautious about build-time dependencies on environment variables, but there are too many ways in which environment variable might be required for the build to succeed.  Particularly if a package wraps some external library which might require environment variables to function.

**Comment by timholy** [comment]
While we discuss the larger design, I pushed the most minimalistic bandaid in c3963496e4bd3adec298de88af140a041eca4779. But I also think we should leave the environment alone.

**Comment by timholy** [comment]
:+1:
