### ISSUE TITLE
module SparseMatrix should be renamed

### ISSUE THREAD

**Issue by lindahua** [JuliaLang/julia#12323]
Currently, Julia base has a submodule named `SparseMatrix`. This name is problematic in several ways:

- It violates the convention that a module name should use plural form when the name can be a name of certain type of entities.
- We are working on introducing `SparseVector` into Base (see #11424). It is really inconsistent and confusing to have a module named `SparseMatrix` while a type within that module named `SparseVector`.
- We have `StridedMatrix`, `DenseMatrix`, and `Matrix`, which are all types, while `SparseMatrix` is a module ...

I propose to rename this sub-module to `Sparse` or `SparseArrays`. (Personally, I prefer the former, which is both concise and informative).

**Comment by tkelman** [comment]
This will break package/user code and should not be done prior to 0.4. There's an unfortunately-named `CHOLMOD.Sparse` type that conflicts with this as well. The plural thing is really a guideline more than a hard rule, I don't think that matters much here. I'd prefer `SparseArrays` or similar, since `Sparse` is too short, too general, and it's an adjective.

**Comment by lindahua** [comment]
I am ok with `SparseArrays`, and also fine with doing the renaming post-`v0.4`.

**Comment by ViralBShah** [comment]
I am ok with renaming, but post 0.4.

**Comment by andreasnoack** [comment]
`CHOLMOD.Sparse` is not exported so there is not a conflict. The type names in the CHOLMOD module are chosen such that they correspond to the names of the structs in CHOLMOD. I think `SparseArrays` is fine.

**Comment by ScottPJones** [comment]
:+1: to `SparseArrays`, post `v0.4` (very good to see @lindahua having time for Julia again!)

**Comment by StefanKarpinski** [comment]
I somewhat prefer `Sparse` over `SparseArrays`. I'm trying to think of something else that `Sparse` might plausibly refer to and having a hard time coming up with anything.

**Comment by tkelman** [comment]
I've seen people use the term sparse to refer to missing-data situations, which bugs me a little because the implementations are usually quite different. Or sparse coding in the compressed sensing literature, LASSO methods etc where you end up with results that are sparse in values, but not (usually) in representation.

And it's likely confusing to have both a `sparse` function and a `Sparse` module, like we saw recently with `pipe`/`Pipe`. `CHOLMOD.Sparse` isn't exactly a conflict since it's not exported, but while working inside the cholmod-related files there's some potential ambiguity.

**Comment by johnmyleswhite** [comment]
I agree with @tkelman: the word sparse is used for a lot of things that aren't related to array storage.

**Comment by ViralBShah** [comment]
Bump. We should do this soon and early in the cycle.

**Comment by tkelman** [comment]
Closed by #13440
