### ISSUE TITLE
`merge` or `union`

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#12426]
Having recently written some `IntSet` tests, I was expecting to be able to use `union!` on dictionaries too. 
However, it turns out that for dictionaries the function is named `merge!`. 

Since this seems (to me) to be the same functionality (despite the fact that dictionaries are more complicated, since they have values and not just keys), could we pick just one of the two names and be consistent?

**Comment by kmsquire** [comment]
+1

**Comment by toivoh** [comment]
I'm not sure that they are actually the same operation. If I take the union of two dicts, I would expect it to contain all (key,value)-pairs that are in either. That's not quite possible to do with two dicts when there is a key that has different values in them. I think it could be acceptable to call the operation `union` if it gives an error in this case, but not otherwise. 

What does `merge` do when a key exists in both dicts, with different values? (And what do we want it do do?)

**Comment by dpsanders** [comment]
Good point, @toivoh. 

According to the [docs](http://julia.readthedocs.org/en/latest/stdlib/collections/): 

> If the same key is present in another collection, the value for that key will be the value it has in the last collection listed.

That's pretty arbitrary, but easy to implement.

**Comment by KristofferC** [comment]
I think `@toivoh`'s comment shows that these are different operations.
