### ISSUE TITLE
static compile part 6: automated opt-in compilation

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#12462]
Given automated recompilation (#12259, hopefully coming soon via #12458), it would be good to eliminate the manual call to `Base.compile` for most users, which is both awkward and dangerous (since users won't know whether a module is compilable).   I think we want a way for a module author to mark it as *compilable* so that `using Foo` will automatically call `Base.compile` if it has not been compiled yet.

It will be easy to implement this, once we decide on a syntax.  Some options:

* a magic comment (e.g. ~~`#@compilable`~~ `#pragma compilable`) at the top of the file.  Pro: backwards compatible with Julia 0.3, easy to check *before* parse and `eval` of the file, is per-file like compilation, simple and robust to implement (#12475).  Con: not very Julian.
* `@compilable module Foo ... end`: Pro: more Julian, can be checked after parsing but before `eval`. Con: hard to make backwards-compatible (a major problem), requires parsing (non-compiled files will be parsed twice every time they are included!), and per-module rather than per file.
* `@compilable` statement *inside* the module. Pro: can be made backward-compatible via Compat. Con: must eval the module to execute it, which means that if it is compiled too then it gets evalled twice, and the compiled version is not the one that is loaded (since it has already been imported), and is per-module whereas compilation is per-file.

*Updates:*
* via `Pkg`: e.g. a `COMPILABLE` file in the package directory would cause the package to be compiled when it is added (automated recompilation could handle the rest). Pro: backward compatible, no parse/eval.  Con: auto-compilation only available for registered packages, does not allow compilation to be disabled for a module unless `Base.compile` hooks into `Pkg`.
* `@compilable; module Foo ... end`: as `@compilable module` but per file, otherwise same pros and cons.

Any other options?  I have to admit that I lean toward the magic comment, since avoiding parse/eval is attractive enough to me to compensate for the slight syntactical ugliness.

**Comment by vtjnash** [comment]
> a magic comment (e.g. #@compilable) at the top of the file. Pro: backwards compatible with Julia 0.3, easy to check before parse and eval of the file. Con: not very Julian.

`#pragma compilable`?

> @compilable module Foo ... end: Pro: more Julian, can be checked after parsing but before eval. Con: not backwards-compatible (a major problem), requires parsing.

i did this for some time in the original #8745 PR. (at the time, I was also passing the parsed version directly to `create_expr_cache`, instead of passing a filepath). I dropped it after adding support in the deserializer to handle an arbitrary number of modules in one `.ji` file.

> Any other options?

another option is to couple this step to the Pkg manager, so that Pkg.add / Pkg.update / Pkg.checkout / etc will manage some metadata for whether to call Base.compile. Arguably, this would make `Pkg` feel much slower, but make Julia feel much faster (since the next logical command after `Pkg.add` is `using`).
-- this assumes automated recompilation (#12259, hopefully coming soon via #12458) will take over from there so that Pkg is not integrally coupled to `Base.require`.

**Comment by wildart** [comment]
As for package manager, it should be a problem to put a compilation step after package update, some were [here](https://github.com/JuliaLang/julia/blob/b92b5378ce7aca0259fb4576be7d91c61e2ec824/base/pkg/write.jl#L27).

**Comment by stevengj** [comment]
Magic comments (I like `#pragma compilable`) have the advantage of working just as well for local modules as for `Pkg` ones, although I suppose you could always call `Base.compile` manually for the former.

Yes, a `COMPILE` file in the package directory sounds like the best alternative to a magic comment.  `Pkg` would only need to call `Base.compile` on `add` and when the `COMPILE` file changes, not on every `Pkg.update()`, since automated recompilation would handle the rest.

**Comment by wildart** [comment]
Or extend a package description, #11955. I would see it as a part of requirements description in REQUIRE file rather then a separate empty file. You would need to touch `COMPILE` every time when  a new version tag is created, but with an explicit compilation requirement there is no need to timestamp check. Package manager will know better when to compile on a package version update.

**Comment by stevengj** [comment]
@wildart, I disagree with the notion of using the package manager to manage *re*compilation; I think it would be brittle and inflexible (e.g. it wouldn't recompile when a developer is hacking on the package).  But if you want to talk about recompilation strategy, please go to #12259 ... this issue is about opting in for the initial compilation.

Obviously, if the structure of the package metadata changes, where you would put the compilation opt-in would change.  But since I doubt #11955 will be resolved in time for 0.4, I would prefer not to rely on it here.

**Comment by IainNZ** [comment]
#11955 really would be great, but is definitely not 0.4

@stevengj, is there any reason you would not want to compile? Could Pkg.add not simply try to compile every package? Is there a scenario where a package is seemingly compiled, but compilation was dangerous had has negative side effects?

**Comment by wildart** [comment]
I would think of opt-out option rather then opt-in. Disabling static compilation for modules or functions looks more reasonable then any opt-in options. Don't we want to compile everything? Wouldn't a faster code loading improve user experience?
@stevengj  As you try avoid manual compilation, you should consider involving the package manager. For majority of users, the best time to do compilation is during a package installation and later on a package update. I'm less concerned about developers because they can always recompile code or #12458.

**Comment by timholy** [comment]
There are definitely packages that won't work if compiled. http://docs.julialang.org/en/latest/manual/modules/#module-initialization-and-precompilation

**Comment by timholy** [comment]
I confess I kind of like the magic comment, too. As someone who has ~100 "packages" not managed by the package manager (i.e., lab-specific code), I'm a little less excited about coupling this to the package manager (but will cope if this is the outcome).

**Comment by rened** [comment]
+1 for not tying this to the package manager. also +1 for making this opt-out: in my work on [SystemImageBuilder.jl](https://github.com/rened/SystemImageBuilder.jl) I found only few packages (of the 60+ I use) that can't be precompiled. My suggestion would be
```jl
module MyModule
  #pragma nocompile
...
```
In a concerted effort we can quickly add this to the packages which can't be precompiled (yet), and it adds an incentive to actually make those packages precompilable.

**Comment by bicycle1885** [comment]
I think most packages are compilable, so the opt-out pragma would be better.
But I love a `@nocompile` macro rather than any pragma because it's more Julian way.
Why not have both? If a package author decides to support only v0.4 or later, the `@nocompile` macro is a better choice.

**Comment by stevengj** [comment]
Julia is a safe language by default, and making this opt-out would violate that contract.   Compilation has to be for people who know what they are doing.  Otherwise this is a deathtrap for new developers.

**Comment by stevengj** [comment]
@bicycle1885, the fact that a macro requires parsing is a big disadvantage.

This is a classic use for a [pragma directive](https://en.wikipedia.org/wiki/Directive_%28programming%29), because it is effectively a compiler option rather than part of the language per se.

**Comment by stevengj** [comment]
The opt-in vs. opt-out discussion already took place in #8745.

**Comment by IainNZ** [comment]
Ah OK. Comment works for me.

**Comment by bicycle1885** [comment]
I see. Safe-default principle makes sense to me.

I think the pragma should take an argument (for example, `yes`/`no`) to make author's intuition explicit in both cases:
```julia
#pragma compile yes
#pragma compile no
```

**Comment by wildart** [comment]
Unfortunately, I missed first "opt-in vs opt-out" but I have filling that as soon as 0.4 will be released every package developer will put `@compile` macro or pragma in its package. I disagree that compilation should be a tool of skillful devs. If person is able to create package then definitely one is able to follow static compilation guidelines. I see no problem in forcing a package compilation. So I strongly encourage to develop opt-out option.

**Comment by tkelman** [comment]
Eww, -1 to significant comments. Comments are for humans, and get thrown away pretty early in the Julia parsing-to-execution pipeline.

**Comment by stevengj** [comment]
@tkelman, the whole point of a pragma is that it occurs before the parsing-to-execution pipeline, and it is not part of the language per se — it is a compiler hint.

**Comment by tkelman** [comment]
So far most of the ways of interacting with the Julia compiler have been part of the language - it feels wrong to suddenly buck that trend. And pretty much all Julia code, with the exception of comments, has usually been treated equally whether it came from a program or a file.

`@compilable module` can be worked-around in a backwards-compatible, though ugly way via conditional inclusion. This would be a poster case for #7449 - actual pragmas as part of the language, not magic comments.

**Comment by stevengj** [comment]
`@compilable module` requires the parser, and backward compatibility would involve extremely ugly code in every single module that is going to be compiled (a lot of them) for as long as 0.3 is supported.

**Comment by quinnj** [comment]
I think we either need to do #7449 or rely on Compat here. If we want #7449 to look like `#pragma [option]`, then that's fine, but I feel like I'd prefer the original #7449 syntax using `%if pragma`. I also don't think it's the end of the world to rely on Compat here and deal with the double parsing.

If we're also planning on a much shorter 0.5 release, then maybe it won't be as bad either.

**Comment by StefanKarpinski** [comment]
Would it make sense to put compilation opt-in into METADATA?

**Comment by stevengj** [comment]
@quinnj, the problem with relying on Compat is that Compat is included *inside* the module, and here we need something outside.  Also, using Compat requires actually loading the file, which is worse than just parsing it.

**Comment by stevengj** [comment]
@StefanKarpinski, then you only get auto-compilation for registered packages, which is a really problematic limitation.

Also, if you think about the implementation (compared to the really easy #12475), anything based on Pkg is vastly more complicated, and therefore more brittle, and Pkg is already complex and slow as it is.

**Comment by rened** [comment]
@StefanKarpinski please let's rather aim for a solution which works with non-registered packages as well, i.e. rather on a per-module basis than a per-package basis.

**Comment by stevengj** [comment]
I'm fine with #7449 looking like `#pragma option`, by the way.  The advantage of this is that you get backwards compatibility automatically, and you can implement the feature more incrementally.  (e.g. just via simple regex matching as in #12475, and then later integrated into the parser.)

**Comment by StefanKarpinski** [comment]
Since we didn't go ahead with reserving the `%if` syntax at the time, we can't do that without breaking everything on older versions of Julia now. Which was why I was intent on getting something like that done when we released 0.3 – by the time you really need this feature, it's too late.

**Comment by stevengj** [comment]
@StefanKarpinski, spilled milk and all that.  Besides, you are complaining that you can't use
```
%if compilable
@compilable
%endif
module Foo
```
which involves double-parsing, incorrectly implies per-module compilation semantics, requires a more complicated implementation, and is longer and uglier than
```
#pragma compile
module
```
so I'm having a hard time seeing why the latter is so awful in comparison to a syntax that seems worse in every way except that it uses `@` instead of `#`.

**Comment by bicycle1885** [comment]
I may have found a loophole for backward compatibility.
The code compiles in v0.3:

```julia
module Foo(compilable=true)
function foo()
    return "foo"
end
end

@show Foo.foo()
```

**Comment by vtjnash** [comment]
strange. apparently it's in statement position, so it's actually a variable assignment:
```
julia> module Foo(compilable=true)
       function foo()
           return "foo"
       end
       @show compilable
       end
WARNING: replacing module Foo
compilable = true
Foo
```

**Comment by nalimilan** [comment]
If the `#pragma` solution is just a temporary trick for 0.4, waiting for an opt-out solution when compilation is reliable enough, then it's easier to accept than if it's going to stay forever in the language. Is that the case?

**Comment by stevengj** [comment]
`module Foo(compilable = true)` still requires double parsing, and still incorrectly marks a module rather than a file.   Also, it is a clearly just a hack; it doesn't actually make sense in the context of Julia syntax, because it looks like an optional argument to `Foo`.  It makes me think I can do `using Foo(false)`.  See also #3894.

It seems a little silly to reject a syntax that does exactly what is needed here just because it uses `#` rather than `@`.

**Comment by tkelman** [comment]
I'm not sure making this opt-out will ever be safe. If we need real pragmas as a first-class language feature, then IMO magic-comment pragmas should be a temporary stand-in purely for compatibility reasons until there's a non-comment syntax that can be parsed for them.

I'm opposing `#` syntax because comments are non-syntax. Comments aren't a legitimate way of talking to the compiler, or conveying any programmatic meaning for that matter.

Package-manager-based solutions are clearly limiting, and module-based annotations don't quite match the current static compilation semantics as has been mentioned above. But what about talking to the compiler through an actual API? At top level, `Base.compilable(@__FILE__)` ? Could call it conditionally for backwards compatibility. That kind of information could live in your juliarc even, wouldn't have to be package-local. There's some state there that I'm not too sure about where to put, but I guess it bears some parallels to `LOAD_PATH`.

**Comment by stevengj** [comment]
@tkelman, that solution is even worse, because it requires actually `eval`ing the module, not just parsing.

Your argument seems circular: essentially "`#` is a comment, not syntax because it is a comment, not syntax".  If we define `#pragma compile` as syntax, then it is, despite its resemblance to a comment (and its treatment as a comment in other contexts is a feature, not a bug).

**Comment by vtjnash** [comment]
as I understand this, it is only about marking whether the package should initially be precompiled or not. all subsequent updates are handled by a separate mechanism (#12458).

thus, i'm generally in favor of this being part of Pkg metadata, not the source code itself. For packages that aren't managed by the package manager, it's a one-time setup to turn this on. Presumably for packages that aren't managed by any package manager, then you just started hacking on it and don't want it to be loading from a cache (yet).

for timholy's case (a lab with lots of private code), I think @StefanKarpinski has mentioned that the package manager can work with private repos. Could you indicate whether this is possible and provide a link on how to do it?

also, for the lab case, I'm imagining there may be plenty of cases where you want groups of modules packed into a single `.ji` file. (it may require some more work to expose this API rather than the direct control I use in places like https://github.com/JuliaLang/julia/issues/5155#issuecomment-128092110). @timholy, given the number of packages you work with, do you have a sense of whether such functionality would be useful or whether the single-module `.ji` file is more aligned with your usage?

**Comment by stevengj** [comment]
@vtjnash, it is also useful to *disable* compilation for modules that are not precompilable.  `#pragma compile false` can do this.  Module metadata cannot, unless you want `Base.compile` to hook into `Pkg`.

**Comment by ScottPJones** [comment]
I'm probably missing something, but why can't you just have a macro, defined in Base, called Compilable, with no arguments, that simply sets a flag (which would need to be set to false at the start of compiling each file).  (I imagine `#pragma compile true` would have to act in a similar fashion, setting some state during the compilation process).
Or is the whole file parsed before any of the code is evaluated?

Doing it that way, you would 1) not be hiding something in a macro, 2) could be handled by Compat,
3) would be part of the syntax.

Please tell me just where I've messed up here.

**Comment by stevengj** [comment]
@ScottPJones, that is (a) requires the module to be `eval`-ed, where as the decision to compile should take place *before* `eval` and (b) is per-module whereas compilation is actually per-file.

**Comment by ScottPJones** [comment]
Why does the module have to be `eval`-ed?  Why would it have to be per-module?
```julia
# Licence statement

@Compilable
# comments
@doc """
module information
""" ->
module Foo
... code ...
end
```
When something like the above is compiled, does it have to parse the whole thing before it can evaluate the `@Compilable` macro?

**Comment by ScottPJones** [comment]
@stevengj What I proposed wasn't at all like the macro you proposed, which was a macro that took an argument (a module).

**Comment by tkelman** [comment]
"`#` means comment except when spelled `#pragma`" doesn't seem like a consistent treatment or a particularly elegant design. We're in a hurry, it was easy to make work, and it doesn't break any code, but unless I'm the only one who has such an intense dislike for magic comments then those don't seem like compelling reasons to move in this direction and expect it to be a permanent design choice. Would set a messy precedent.

If there's a way for a module to ask "am I being precompiled right now," then forcibly disabling via erroring should be doable inside the module. The enabling of auto-compilation seems like it could be controlled by an external registration: one that either Pkg, or a knowledgeable user, could manually enable before attempting to first load a to-be-compiled file.

**Comment by stevengj** [comment]
Other than being per-file, `@compilable; module ...` has the same pros and cons as `@compilable module`: it requires the file to be parsed (which means double-parsing of non-compiled modules), and is hard to make backward compatible without additional `if VERSION ...` statements (because `using Compat` goes inside the module, not outside, and in any case requires `eval`).

**Comment by ScottPJones** [comment]
@tkelman I also agree completely with your dislike of magic comments, and don't think something should be rushed into the language simply because everybody wants all of precompilation working right now.

**Comment by stevengj** [comment]
`#pragma` is a comment except when deciding whether to compile a file.  Yes, this is a slighly annoying rule, but every alternative proposed so far has major *functional* shortcomings.  I'll take "slightly annoying use of `#`" to "major functional shortcoming" every time.

**Comment by tkelman** [comment]
`register_as_precompilable(foo)` - called ahead-of-time from outside of foo, rather than being marked inside of foo
`fail_if_precompiled()` - called from inside of foo

It's not perfect, it splits up the affirmative vs negative information and it's nonlocal in the enabling step, but would it work? `if VERSION` isn't too verbose as long as you aren't having to move code around into conditionally included separate files. `Pkg` would be one location, but not the only way, to call `register_as_precompilable`.

**Comment by stevengj** [comment]
We already have `register_as_precompilable(foo)`; it's spelled `Base.compile(foo)`.   But who calls this?  The end user doesn't know whether the package is precompilable.   You could put it in the Pkg metadata, but then that ties compilation to Pkg in a way that makes non-Pkg packages second-class.

I agree that we could have a `fail_if_precompiled()` function (spelling TBD) called inside the module.

**Comment by carnaval** [comment]
So if the `forbid_cache()` thing works well for opt-out, it's kinda sad that we have to go the opt-in route simply because we "promised" both 0.4 soon and this feature in 0.4.

Imminent release aside, I'd much rather go the painful-but-quick opt-out way to weed out the related bugs and improve the detection of not-cacheable behavior. I also think that things that makes a module impossible to cache should mostly be frowned upon. If someone has a good use case for one of those, we'd rather start thinking of a way to achieve the same goal in a cache-friendly fashion.

**Comment by stevengj** [comment]
@carnaval. We have to go the opt-in route for the foreseeable future, I think. The restrictions on precompilation are such that they can never be enforced automatically, and changing it to opt-out breaks the contract that Julia is a memory-safe language by default.

**Comment by ScottPJones** [comment]
@stevengj So, the whole file is always parsed, no matter what? (unless you have something added to the parser, such as detecting `#pragma`?)
From my stupid tests, I hadn't thought that to be the case.  (maybe I've got something incorrect about code when macros are expanded)

**Comment by stevengj** [comment]
@ScottPJones, detecting `#pragma` at the top of a file just needs a regex in #12475; only the first few lines are read.

**Comment by tkelman** [comment]
Joking maybe: insert a `forbid_cache` automatically in every module by default, `@compilable` turns it into a no-op. File-based behavior falls out if every module in a file succeeds?

**Comment by stevengj** [comment]
@tkelman, that would lead to a failed attempt to `Base.compile` the module *every* time it is loaded, which is horribly expensive.

**Comment by ScottPJones** [comment]
@stevengj Doesn't that make it rather fragile?   For example, if somebody puts a doc string at the top of the file?
But you didn't answer my question, when loading a file, does Julia read lines until it finishes parsing an expression, and then evaluate it, or does it read the whole file parsing a list of expressions, and then evaluating them?

**Comment by carnaval** [comment]
@stevengj sorry if I'm polluting the discussion here, I'm not very familiar with this feature yet. I'm not sure I follow the memory safety thing though : I'm reading the manual page about this, and while it's somewhat discouraging me from the opt-out choice given all the subtle gotchas, the only memory related point was the nulling of raw pointers.

I'm pretty sure that handling pointers like that is already acknowledging that you ventured in the unsafe parts of the language, and I guess that the knowledge of whether we serialized a raw pointer can be checked. Is there something I'm missing ?

Otherwise yeah, you're probably right. We need a much more restrictive toplevel and/or clearer separation between compile/runtime to make this an automatic feature without tripping people up.

**Comment by stevengj** [comment]
@ScottPJones, the documentation states that the `#pragma compile` needs to go before any other non-comment code in the file.  This is fair, I think, since it is a statement that is supposed to apply to the whole file.

**Comment by ScottPJones** [comment]
@stevengj That still doesn't answer what I think is a fairly simple question, does Julia read and evaluate an expression at a time, or read all expressions in the file, and then evaluate?

**Comment by stevengj** [comment]
@carnaval, just doing `const foo = STDOUT` is a memory-related gotcha, and the rehashing things are also memory/pointer related.  Nearly all of the restrictions are due to having a pointer somewhere under the hood.

**Comment by joehuchette** [comment]
How necessary is backwards compatibility with v0.3? Is it not tenable to just add the ``%pragma`` syntax and expect that developers opting into this behavior will ensure any code they release has ``julia 0.4`` required?

**Comment by stevengj** [comment]
@ScottPJones, `include` and similar parse and eval one expression at a time, but `module .... end` is a single expression.  (There is also the machinery to just parse one expression at a time without eval-ing, I think.)  So, if you are parsing the file to look for a `@compilable` macro at the top (wrapped with suitable `if` statements to make it backward compatible), and it is *not* compilable, then it will end up parsing the whole module.

**Comment by stevengj** [comment]
@joehuchette, so you are willing to accept a major functional shortcoming (forcing every package to fork a separate 0.4 version to be compiled) just to spell `pragma` with a `%` instead of a `#`?

**Comment by ScottPJones** [comment]
@stevengj No, the macro would set a flag *before* anything else in the file is parsed.  The flag being set would short-circuit the parsing and evaluating of the rest of the file.

**Comment by joehuchette** [comment]
It wouldn't be a fork so much as "version x.y.z is the last to support v0.3," which is how many packages (implicitly) treated the v0.2 --> v0.3 transition. Considering that 1) v0.4 offers a fair number of backwards-incompatible goodies, 2) v0.5 is promised to be a "quick" release, and 3) julia is still pre-1.0 (for whatever the last two are worth), it seems like a fair trade-off for better syntax.

Maybe my perception is skewed, but how much development against v0.3 will continue once v0.4 is out?

**Comment by stevengj** [comment]
@ScottPJones, that's only if the macro is present.  But to detect whether the macro is present, you have to parse/eval the first expression in the file … and suppose that the first expression in the file is `module Foo ... end`.

**Comment by StefanKarpinski** [comment]
I'd like to point out that using something that's valid syntax in 0.3 and something that can be found with just a regex sans parsing a file are not at odds with each other. You could, for example add a no-op vararg`@pragma` macro to `Compat` and then scan each file for the presence of `@pragma` with a regex – and handle its arguments however you want. When evaluating the file, this would be a no-op, but you can still detect it on a per file basis. Another alternative: look at a separate file for information.

**Comment by stevengj** [comment]
@StefanKarpinski, the problem is that to scan for `@pragma` anywhere *except* the beginning of the file, you pretty much need the full parser (to eliminate occurrences in strings and similar).  But you can't put `@pragma` outside the `module ... end` because `using Compat` has to go inside the module.  Furthermore, if it is a `@pragma` inside the module, you would reasonably expect that it could occur in an `included` file, but you don't get those unless you actually `eval`, and if you don't do that then it doesn't really act like a "normal" Julia macro anyway.

So, are you willing to accept those major functional shortcomings just to spell `pragma` with `@` instead of `#`?

**Comment by StefanKarpinski** [comment]
For the record, I'm not dead against `#pragma` especially since in this case it is literally meant to have no semantic effect. I'm mostly just trying to spitball some other ideas in case it leads to a better solution.

**Comment by JeffBezanson** [comment]
I dislike interpreting comments, but I admit it works well here. Maybe the syntax should just be a bit further separated from normal comments, like `#%pragma` or `#__pragma__`. You always need more underscores.

**Comment by stevengj** [comment]
You could have the following at the top of the file:
```jl
if VERSION < v"....."
    @pragma compilable
end
```
and parse for that, but again you need the full Julia parser, and even then it *looks* like ordinary Julia code but isn't because it can't go in an `include` without needing `eval`.    (Also, as boilerplate goes this is pretty ugly.)  If it is not *really* evaluated as Julia code, probably it shouldn't *look* like Julia code.

**Comment by stevengj** [comment]
@JeffBezanson, isn't "pragma" such a weird word already that `__pragma__` is overkill?

**Comment by JeffBezanson** [comment]
I'm just wondering what the standard syntax for interpreted comments will be. Will they all begin with `#pragma`? It seems possible that not all future uses will be considered pragmas, and we wouldn't want a precedent that `#word` for any word can be interpreted.

**Comment by tkelman** [comment]
I think it would need to be `include_string("@pragma compilable")` since the macro would otherwise be unconditionally parsed. Still that doesn't look that ugly to me. Less philosophically jarring than significant comments, but clearly this is a gut reaction thing that sits differently from person to person. I'm willing to accept two extra lines at each usage location, and only in packages that want to continue actively developing against 0.3, to avoid spelling pragma with `#`.

If it is such a separate thing from Julia code, perhaps it should be stored somewhere that isn't inline in the Julia code?

**Comment by ScottPJones** [comment]
@stevengj If the macro is *not* present, then it has to parse/evaluate the rest of the file anyway, because this is opt-in, not opt-out, correct?

**Comment by ScottPJones** [comment]
Maybe a silly suggestion, but, instead of having to decorate every compilable file with *something*, why couldn't compilable files simply have a different suffix? I.e. `.jlc` for compilable julia source.

**Comment by stevengj** [comment]
@ScottPJones, that's true.  It would mean that the code to check for compilability would be intermingled with the code to include in the non-compilable case. Things would be a bit uglier, and it would require the `if VERSION ... ` boilerplate in every file, but it might be made to work.

I kinda like the `Foo.jlc` idea, actually.  It could be made backward-compatible by putting a `Foo.jl` file in the same directory that `include`s the `.jlc` file, and having `.jlc` take precedence.

**Comment by JeffBezanson** [comment]
I don't think compilability is significant enough to warrant a different file extension. Unless perhaps this veers off into, say, a statically-typed variant of the language.

**Comment by stevengj** [comment]
@ScottPJones, there is still a problem with the short-circuiting `@compilable` macro, now that I think of it.  Suppose you have a non-compilable module `Foo` that includes a compilable module `Bar`.  Then the evaluation of Foo could be 90% done before it gets to the `import Bar` statement and barfs.  I guess you could avoid this by enabling the short-circuiting except at the top-level eval.  But I'm worried that this strategy is getting more and more complicated to implement (hence more fragile) the more I think about it.

**Comment by ScottPJones** [comment]
Why would it barf at the `import Bar`?  (sorry if it is a stupid question, or one from lack of sleep!)

**Comment by stevengj** [comment]
@ScottPJones, because `import Bar` includes `Bar.jl` (if Bar hasn't been compiled yet) and `Bar.jl` includes your `@compilable` macro which short-circuits parse/eval.

**Comment by ScottPJones** [comment]
but wouldn't it only short-circuit parse/eval of `Bar.jl` (and only if a cached version of Bar were found, and the timestamp/hash/whatever matched)?

**Comment by ScottPJones** [comment]
Another thing, can the Julia compiler always correctly determine if something is "compilable" or not?
(shouldn't that really be "cacheable" also)?
If so, why doesn't it always write out a `.ji` file which is just a short special header, that indicates the file is not "compilable", with the same timestamp/hash/etc. info, so that if the file later becomes "compilable",
it can be detected and cached.

**Comment by stevengj** [comment]
@ScottPJones, no, because it can't finish evaluating Foo if a module it depends on barfs on `import`.

And no, it can't determine automatically whether a module is (safely) compilable.  (It can compile anything, but modules that don't follow certain rules will get compiled to incorrect code.)  That's why it has to be a human opt-in.

**Comment by timholy** [comment]
> @timholy, given the number of packages you work with, do you have a sense of whether such functionality would be useful or whether the single-module .ji file is more aligned with your usage?

Somewhere in between, but single-module is a bit better. There's still quite a lot of mix-and-match going on.

**Comment by stevengj** [comment]
@tkelman, `include_string("@pragma compilable")` *looks* like Julia code, but it isn't if you don't actually `eval` it when you are deciding whether to compile a module.  (e.g. it can't be hidden inside another `include`).  And I'm having a hard time believing that
```
if VERSION >= xxx
      include_string("@pragma compilable")
end
```
plus magic not-quite-julia parse-without-eval interpretation at compile time is better than `#pragma compile`.

**Comment by timholy** [comment]
> Maybe the syntax should just be a bit further separated from normal comments, like #%pragma or #__pragma__. You always need more underscores.

We haven't done a sufficiently good job of emulating bash's outstanding syntax choices. So I'm all in favor of `#! /bin/compile_this_file`

**Comment by stevengj** [comment]
`#!@#$pragma!@#$ __CoMpILe__`.  Because `#pragma` is just too beautiful.

**Comment by ScottPJones** [comment]
@stevengj I guess I just don't understand.
I would think that import would:
1. Look and see if there is a .ji file for Bar
2. If so, see if it's timestamp/hash/whatever match.
    a. If match, see if it was cacheable.
        I. If cacheable, load it and return.
        II. Otherwise, parse/evaluate it and return
    b. Otherwise, act as if no .ji file found, maybe print "recompiling Bar message" if at REPL.
3. If no .ji file, parse/evaluate the file, see if it is cacheable, and save the information as a .ji file.

I also  think that compilers are much better than humans usually in determining if code is "following the rules".  Where are all the rules that need to be followed?
I'm not sure I'd trust a system that depended on people getting something like that right or else silently generated incorrect code.
If you did as I've outlined above, people could add opt-out macros or function calls at the beginning of their modules if they were sure that it was not safe to cache, and that would simply let the compiler avoid any extra overhead (is there any?) of attempting to see if the module were cacheable or not.

**Comment by stevengj** [comment]
@ScottPJones, the problem is the "parse/evaluate the file, see if it is cacheable" step.  That's what we're discussing here.  A long discussion of why compilability can't be determined automatically already occurred in #8745, and the rules are described in the "precompiling" section of the manual.

**Comment by stevengj** [comment]
Tomorrow, I'll try to put together an alternative PR based on @ScottPJones's short-circuit `@compile true` per-file macro.  I think it can be made to work without major functional shortcomings, but I need to implement it to be sure that there aren't any gotchas.

**Comment by ScottPJones** [comment]
OK, so you can still do as I've outlined above, but instead of being able to determine cacheability automatically (I had missed all of the old conversation, I'll have to read it tomorrow), it could just use
the `@Compilable` macro (wrapped in `if VERSION ...` if you need 0.3 compatibility) to decide.

What other problems do you see with that technique?  It avoids looking at the source code, even to do a regex, if the .ji file is present and valid, if it the .ji file says that it is not cacheable, it just does what it has always done, i.e. parse/eval the file.

**Comment by ScottPJones** [comment]
That would be great, thanks for having patience with a sleep deprived old PITA!

**Comment by stevengj** [comment]
@ScottPJones, it's just that the `require` code is more complicated than you think (it was more complicated than I thought) once you take into account nested and parallel imports.

**Comment by ScottPJones** [comment]
OK, I hadn't looked at the `require` code yet, and I still have to wrap my mind around the way only a single "master" node does all the compilation (if I understand that correctly).  Thanks!

**Comment by vtjnash** [comment]
i think the key is that compilation of a module always occurs in a separate process, and never as a side effect of running code in the local instance

I added a number of examples of failure cases to the end of the Modules documentation:
http://docs.julialang.org/en/latest/manual/modules/#module-initialization-and-precompilation [Other known potential failure scenarios include]

Note that `Ptr` objects turn into `C_NULL` when they hit the serializer (in most contexts), so you can use this to detect whether it has been initialized (or get a friendly SEGV instead of runtime memory corruption if you blindly attempt to use it).

Of those, I expect that #12010 may be the most serious and limiting. The others hopefully are fairly benign and expected. There are a few classes of failure scenarios that are pretty easy for the compiler to detect and complain about (and so it already does). Most of the others are broken only by determining the author's actual intent. There are many valid reasons to alter global state while compiling a module (reading files, opening libraries, creating counters, and manipulating shared structures like LOAD_PATH and ARGS), which makes it impossible for the compiler to guess at the user's intent.

For example, given the following script, what should the runtime value of `baseversion` give? (assume that `Base.VERSION` isn't defined as a constant for the purposes of this example)
```
module Z
  baseversion = Base.VERSION
end
```
There are two choices:
1) the runtime value of Base.VERSION (create a reference)
2) the compile time value of Base.VERSION (create a copy) – this is what it actually does
The problem (for the compiler), is that it isn't exactly obvious which one you intended, since there are valid use cases for both. Indeed, in the Base.GMP module, there is a test to ensure that the compile-time and runtime versions of the dynamic library are the same (so you want both!).

parsing the file is a pretty negligible cost, but if you want to avoid doing it twice, but still wanted to have the benefits of parsed code, one option is to note that `Base.compile` is calling a function called `Base.create_expr_cache`, not `create_cache_for_include_file`. This is because it is actually taking a series of serialized expression objects, not a file, and compiling the result. One of the expressions just happens to be an include statement: https://github.com/JuliaLang/julia/blob/master/base/loading.jl#L276
In past versions of the code, this function actually just took an Expr (although, to be fair, in the past versions of the code, it only accepted a `Expr(:module)`)

**Comment by stevengj** [comment]
Okay, no macro required, and no magic non-Julia syntax.  Just `compilethis()` at the top of the file, or `VERSION >= xxx && compilethis()` if you want backward compatibility.  Thanks to @ScottPJones for pointing out that this short-circuits the parser.

**Comment by ScottPJones** [comment]
Cool!  I hope this satisfies @tkelman's objections (it does mine).  Great stuff no matter what the syntax, Steve!

**Comment by carnaval** [comment]
@vtjnash It is true that the compile/run time distinction is unclear right now. To be honest, I feel that for the next release we should aim at making it more explicit. I don't think the goal should be to try to transparently cache module and pretend that `using X` is going to work the same, exactly for the reason you highlighted.

Instead, maybe we could have a `compile_time` block inside modules, so by default everything is defered to runtime (=> __init__) and you cache an empty module. This is backward compatible. Then you can selectively add some code to the compile time like method definitions and some const things/precomputation.

Something like that ?
```julia
module Foo
const runtime_v = Base.VERSION
cached
   const compiled_v = Base.VERSION
end
end
```

I didn't think this through but I believe my general point stands : we should not be scared of changing module semantic to make this feature first class, instead of this "dangerous but everyone will still use it because load times are unbearable".

As for rehashing, it may be hairy to make it work but maybe we should use the julia serializer at least for user types to let them handle this ?

**Comment by tkelman** [comment]
(another disadvantage of the `#pragma` syntax that I didn't predict in advance is it would have been more complicated to enable or disable precompilation selectively depending on platform, as in https://github.com/timholy/Images.jl/pull/338)
