### ISSUE TITLE
Type when mapping an empty array

### ISSUE THREAD

**Issue by m-legrand** [JuliaLang/julia#12513]
Poking around with Julia, here is what I found :

<img width="929" alt="capture d ecran 2015-08-07 a 18 10 44" src="https://cloud.githubusercontent.com/assets/9072763/9148428/05284d7c-3d30-11e5-9f77-714c190deab6.png">
My question is... why ?
Let's assume you have a `fun : type1 -> type2` with which you want to map an `Array{type1,dim}`, for example in a function you are writing for a general purpose. Who in this world will want an output-type depending on the size of the input, having an `Array{type1,dim}` if it is empty and an `Array{type2,dim}` if not ?
In most cases people will have to struggle a bit to find where are their issues from, then correct it with an ugly hack like `if isempty(A) ... else ... end`. And of course it can happen in any dimension...

<img width="924" alt="capture d ecran 2015-08-07 a 18 35 24" src="https://cloud.githubusercontent.com/assets/9072763/9148502/215c265a-3d33-11e5-8c18-7ee304ffc2a1.png">

**Comment by johnmyleswhite** [comment]
You should read through some of the older issues. You'll find a lot of discussion of this topic.

**Comment by m-legrand** [comment]
Well, indeed. The talks around it still don't convince me that this case is not ten times less intuitive than the opposite, though.
https://github.com/JuliaLang/julia/issues/10307

**Comment by carnaval** [comment]
Indeed. And the current behavior is arguably the worst possible since it has no justification, is surprising and might even work in some cases.

The reason why this has not changed yet is that we still have not reached consensus on the other possible behaviors. The combination of 1) julia has dynamic semantic 2) homogeneous arrays 3) resizable arrays; makes this issue surprisingly deep. Feel free to jump in the discussion :-)

**Comment by carnaval** [comment]
Ref also #7258 #11034 on the top of my mind
