### ISSUE TITLE
Performance regression in search for strings

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#12520]
In https://groups.google.com/forum/m/#!topic/julia-dev/oWHxKLQpgio Marcos noted that `split` is slower on 0.4 than 0.3.11.

```julia
julia> A = string(rand(1:10000, 1, 2500000));

# 0.4
julia> @time split(A);
  0.633825 seconds (14.72 M allocations: 295.811 MB, 37.44% gc time)

# 0.3:
julia> @time split(A);
elapsed time: 0.231212685 seconds (147109952 bytes allocated, 28.79% gc time)
```

I think this is due to a regression in the search functions for strings. Compare:

```julia
const _default_delims = [' ','\t','\n','\v','\f','\r']
@time for i in 1:10^6
    search(A, _default_delims, 10)
end

# 0.4:
0.085101 seconds (2.00 M allocations: 30.518 MB, 2.91% gc time)

# 0.3
elapsed time: 0.02674722 seconds (0 bytes allocated)
```

Note that 0.3 is allocation free, while 0.4 allocated 2 times per iteration. Walking down the call stack the problems seem to be with the `in` function used here: https://github.com/JuliaLang/julia/blob/4f52e768bd06dc2d4c78400c26ab8e5e517c3bd7/base/strings/search.jl#L13.

I am not sure exactly where the problem is but profiling seem to point to this line: https://github.com/JuliaLang/julia/blame/4f52e768bd06dc2d4c78400c26ab8e5e517c3bd7/base/reduce.jl#L360

Maybe relevant:
```julia
# 0.3 unallocating with char
@time for i = 1:10^6
    'a' in _default_delims 
end
elapsed time: 0.006235336 seconds (0 bytes allocated)

# 0.4 allocating with char
@time for i = 1:10^6
    'a' in _default_delims 
end
  0.024336 seconds (1000.00 k allocations: 15.259 MB)
```

cc @fcard 

I can do a bisect later if it would help locating the exact commit. Something tells me it might be the `any` short circuiting that was merged quite recently.

**Comment by nalimilan** [comment]
Thanks for the detailed investigation. Indeed, with an old version of master as of 2015-06-28, no allocation was visible with any of your examples.

The problem is that `'c' in ['a', 'b', 'c']` calls `any(EqX('c'), ['a', 'b', 'c'])`, which does not appear to be type-stable according to `@code_warntype`. And indeed it calls the line you mention: https://github.com/JuliaLang/julia/blame/4f52e768bd06dc2d4c78400c26ab8e5e517c3bd7/base/reduce.jl#L360 Maybe some specialization for `EqX` is needed?

**Comment by tkelman** [comment]
Or should part of 8cdb199eb9d1ed7bf67cbc640e6a30043aed0f0b be walked back, would it work to change the signature of `any(f::Predicate, itr) = mapreduce_sc_impl(f, OrFun(), itr)` to `any(f::Func{1}, itr) = mapreduce_sc_impl(f, OrFun(), itr)` ?

**Comment by fcard** [comment]
Oops, just saw this, but seems the problem is solved already, thanks for fixing it @JeffBezanson. Instead of `any(f::Predicate, itr)` I could have used `any(f::ReturnsBool, itr)`, which would've specialized `EqX` as well. The `f === identity` check seems a bit silly since if someone wanted to use `identity` they would just use the one argument version, but I was thinking of the cases where identity was used as a default value, like:
```julia
# simpler, but slower
f(A, g=identity) = any(g, A)

# more verbose, but faster
f(A, g=identity) = g === identity ? any(A) : any(g,A)
```
But I should've known not to put corner cases above the general ones, sorry about that (was that the problem or was it mostly because I forgot to make the `Predicate` type immutable? I'd like to know so that I don't make the same mistake again)
