### ISSUE TITLE
Rational{Int32}(n,d) broken where Rational{Int64}(n,d) works (v0.4)

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#12536]
```julia
julia> Rational{Int64}(1,3)
1//3
julia> Rational{Int32}(1,3)
ERROR: MethodError: `convert` has no method matching
   convert(::Type{Rational{Int32}}, ::Int64, ::Int64)
This may have arisen from a call to the constructor Rational{Int32}(...), ...
```
calling Rational{I}(n,d) with I any Int type that is not == Int generates the same error

Julia Version 0.4.0-dev+6253
Commit a97b24b* (2015-07-26 15:40 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4960X CPU @ 3.60GHz
  WORD_SIZE: 64

**Comment by KristofferC** [comment]
Adding this makes it work
```julia
call{T}(::Type{Rational{T}}, n::Integer, d::Integer) = Rational{T}(convert(T, n), convert(T, n))
```

Someone more experienced will have to say if that is a good idea.

**Comment by J-Sarnoff** [comment]
Indeed ... 
there is something that is not as it should be.

this works
```julia
immutable TypeWorks{T<:Integer} <: Real
    num::T
    den::T
end

julia> TypeWorks(Int16(1),Int16(3))
TypeWorks{Int16}(1,3)
```
this does not
```julia
immutable TypeFails{T<:Integer} <: Real
    num::T
    den::T
         
    TypeFails(num::T, den::T) = new(num,den)
end

julia> TypeFails(Int16(1),Int16(3))
ERROR: MethodError: `convert` has no method matching...
```

**Comment by KristofferC** [comment]
The difference:

```julia
julia> @which TypeWorks(Int16(1),Int16(3))
call{T<:Integer}(::Type{TypeWorks{T<:Integer}}, num::T<:Integer, den::T<:Integer)

julia> @which TypeFails(Int16(1),Int16(3))
call{T}(::Type{T}, args...)
```

**Comment by yuyichao** [comment]
AFAICT, the `TypeWorks` and `TypeFails` behavior is expected because julia will not provide default constructor if there's user provided inner constructor.

**Comment by J-Sarnoff** [comment]
I follow that and I appreciate your work helping others with Julia.

I do not understand why TypeFail fails; what about the supplied constructor is errant?

Rational defines a default constructor within the type and redefines that constructor externally.  Is that to resolve some edge case?

```julia

immutable Rational{T<:Integer} <: Real
    num::T
    den::T

    function Rational(num::T, den::T)
        num == den == zero(T) && throw(ArgumentError("invalid rational: zero($T)//zero($T)"))
        g = den < 0 ? -gcd(den, num) : gcd(den, num)
        new(div(num, g), div(den, g))
    end
end
Rational{T<:Integer}(n::T, d::T) = Rational{T}(n,d)
```

**Comment by aviks** [comment]
Here's how I try and understand this. The issue is that for a parametric type, the compiler needs to know what the type parameter is. The question then is, is there enough information to unambiguously infer a type for the parameter, given the constraints in the parent's definition and construction. 

So the first thing to realise is that for an inner constructor, the method itself is not parameterised. The parameters it uses are the parameters of the  type within which it exists. So, when you call `TypeFails(Int16(1),Int16(3))`, the compiler cannot know what `T`, the type parameter of `TypeFails{T}` is. There is nothing to say that the `T` should be the types of the arguments. 

So, to construct `TypeFails`, you need to say what `T` is in `TypeFails`

```julia
julia> TypeFails{Int16}(Int16(1),Int16(3))
TypeFails{Int16}(1,3)
```

For `TypeWorks`, and indeed `Rational`, the type parameter of the outer construction asserts the type-parameter of the type is the same as types of the arguments of the method. This means that when you say  `TypeWorks(Int16(1),Int16(3))`, the compiler knows that it should construct `TypeWorks{Int16}`. 

This knowledge can only be provide by a method definition `TypeWork{T}(x::T, y::T) = TypeWorks{T}(x,y)`. The key thing here is the parameter `T` ... every position where it exists in that definition is significant. This definition (actually its equivalent via `call`) is automatically provided by the compiler if and only if no inner constructor exists. 

For rational, since an inner constructor exists, and explicit outer constructor has to be provided for this type inference to work.

To reiterate, an inner constructor *cannot* have a type parameter on the method. It has to re-use the type parameter of the parent type... that is the sense in which it is _inner_. And without a type parameter in the method, you cannot assert that the parameter of the type you are creating is the same as the types of the arguments of the method 

Hope this helps.

**Comment by J-Sarnoff** [comment]
That clarifies much.

**Comment by JeffBezanson** [comment]
This is surprising. Usually we accept any, or almost any, arguments, and call `convert`:

```
julia> Complex{Float16}(1.0,2.0)
Float16(1.0) + Float16(2.0)im
```

I think `Rational{T}` should accept any integers, and convert them.

**Comment by J-Sarnoff** [comment]
That is exactly the surprise that led me to file this issue.  While making a table of examples using the built-in numeric types, I noticed the entries for Rational did not conform to the overall pattern.

All of these (and the [U]Int8, [U]Int128 variants) should just work, 
```julia
Rational{UInt16}(1,2), Rational{UInt32}(1,2), Rational{UInt64}(1,2)
Rational{Int16}(1,2), Rational{Int32}(1,2), Rational{Int64}(1,2)
Rational{Float16}(1,2), Rational{Float32}(1,2), Rational{Float64}(1,2)
```

**Comment by KristofferC** [comment]
I don't believe these should work:

```julia
Rational{Float16}(1,2), Rational{Float32}(1,2), Rational{Float64}(1,2)
```

**Comment by J-Sarnoff** [comment]
After a few minutes looking into Rational{FloatN}(num,den) and realizing a subtile  algorithm is needed ...

I would be happy with support for Rational{IntN}(num,den)  and Rational{UIntN}(num,den).  That would mirror how Complex accepts integer types.
