### ISSUE TITLE
Deprecate colon(::AbstractFloat, ::AbstractFloat)

### ISSUE THREAD

**Issue by joehuchette** [JuliaLang/julia#12624]
Update: See below at https://github.com/JuliaLang/julia/issues/12624#issuecomment-131477258

```jl
cnt = 0
for _ in 1:1_000_000
    if rand(0.8:1.2) != 0.8
        cnt += 1
    end
end # cnt => 0

cnt = 0
for _ in 1:1_000_000
    if rand(0.8:2.0) != 0.8
        cnt += 1
    end
end # cnt => 500034
```

**Comment by joehuchette** [comment]
```jl
cnt = 0
for _ in 1:1_000_000
           if rand(0.8:2.2) != 0.8
               cnt += 1
           end
       end # cnt => 500602
```
So maybe this is because ``1.2 - 0.8 < 1``?

**Comment by joehuchette** [comment]
Yep, guess this is just stemming from my (mis)understanding of float ranges, since
```
julia> .8 : 1.2
0.8:1.0:0.8
```

**Comment by yuyichao** [comment]
Maybe we shouldn't have a default step of `1.0` for floating point? We don't have UnitFloatRange anyway...

**Comment by joehuchette** [comment]
I'm not sure what a more sensible default would be, but I have to say that ``0.8:1.2 == 0.8:1.0:0.8`` wasn't immediately obvious to me (or else I wouldn't have opened this...)

**Comment by yuyichao** [comment]
I kind of agree. And what I meant is that simply remove this definition.

**Comment by StefanKarpinski** [comment]
What? No, that's crazy.

**Comment by tkelman** [comment]
What else would `0.8:1.2` be, an error?

**Comment by yuyichao** [comment]
> What else would `0.8:1.2` be, an error?

`MethodError` for `colon`?

I'm not saying we should definitely do this. But it does seem that many people have been confused by this (especially for `in` and `rand`). Forcing the step to be explicit with some special handling of error printing might be less confusing and not too much more inconvenient.

**Comment by ivarne** [comment]
> What else would 0.8:1.2 be, an error?

The assumption seems to be that it could be a closed `Interval` containing every value between 0.8 and 1.2, which seems like a reasonable assumption to me. `collect(0.8:1.2)` (and general iteration) would be problematic, but it would be cool to use it for `rand` and `in`. A deprecation for `colon{T<:AbstractFloat}(a::T, b::T)` would certainly be the way to prepare for the possibility of supporting such a type.

**Comment by tkelman** [comment]
How often is iterating over every possible Float64 between two values actually what you want to do? That's also slightly funky because if the start and endpoint don't have the same exponent, then the step length of "every floating-point value" is not a constant.

There are a handful of use cases where you do want to look at every floating point value for some algorithmic purpose but I don't think that needs pretty syntax, whereas iterating over a range of floats with default step of 1.0 seems like a much more common thing to want to do.

**Comment by jiahao** [comment]
I have to say that in this specific context, `rand(0.8:1.2)` really does read like "return a random number in the interval [0.8, 1.2]".

**Comment by ivarne** [comment]
> How often is iterating over every possible Float64 between two values actually what you want to do? 

Mostly for educational purposes with short intervals, but iteration over all Float64 values is not the topic. We can have Interval with or without iteration. 

> whereas iterating over a range of floats with default step of 1.0 seems like a much more common thing to want to do.

Common is a relative term, but if Interval doesn't support iteration, it's easy to inform users that they need to provide an explicit step. `step=1` seems rather arbitrary for FloatingPoint.

**Comment by tkelman** [comment]
Ah, sorry, I missed the point initially, you're suggesting that `0.8:1.2` could return an entirely different type that isn't really used the same way as normal ranges. Interesting, and I can see for `rand` or `in` it would be useful, but maybe that shouldn't be giving colon yet another meaning, and could use a different syntax instead. There are already a few packages and pieces of example code that do interval types, but I'm not sure whether they're plugged into `rand` or `in` as you suggest.

**Comment by yuyichao** [comment]
I reopened this issue and changed the title. Hopefully it's more clear what I mean.

To summary, I think having `0.8:1.2` meaning `0.8:1.0:1.2` is kind of confusing and writing out the step explicitly shouldn't be too bad if that's what you really want. Whether making it a constructor for an interval that can be used in `in` and `rand` etc is a different issue if we decide to remove it's current meaning.

**Comment by tkelman** [comment]
> remove it's current meaning.

deprecate

**Comment by yuyichao** [comment]
> deprecate

Sure

**Comment by yuyichao** [comment]
Title updated again.

**Comment by StefanKarpinski** [comment]
No, this is a terrible idea. First off, this is a completely standard thing to do in Matlab and Octave, where we got the notation from. This gratuitously breaks compatibility with them, with no benefit other than catering to people not understanding how ranges work (ranges are not intervals). It also makes it harder to write generic code without worrying about corner cases. Previously you could write `a:b` and count on it starting at `a` and doing unit increments until you reach `b`. Now you have some pointless, annoying corner case where that's true *except* if `a` or `b` are floating point values (or promote to floating point).

-100

**Comment by kmsquire** [comment]
I agree with Stefan. -1

**Comment by yuyichao** [comment]
> this is a completely standard thing to do in Matlab and Octave

Well, I always think this is mainly because the type of an integer literal in matlab is a double and something like `1:10` won't work unless float range with default interval of `1` is allowed. This shouldn't be an issue for us though (except for backward compatibility).

> with no benefit other than catering to people not understanding how ranges work

Not giving people surprise in a subtle way is a big benefit and I'm only bringing this up because people are confused by this Ref [julia-users](https://groups.google.com/forum/?fromgroups=#!searchin/julia-users/interval/julia-users/qiMsrzj2A9s/ant3ZL8IpfwJ)

> Now you have some pointless, annoying corner case where that's true except if a or b are floating point values

`a:0x1:b` should work. Also, if you want to be generic, you also have the corner case of length overflow so just writing `a:b` now is not truely generic either.

Personally for most of the case (which is admittedly not many) I encounter an `a:b` with floating point `a` or `b` I usually want something else (Interval or a UnitRange (for array indexing)). I'm interesting to see a real example of when you want a generic `a:b` to work for both integer and floating point.


I agree that the current behavior has the benefit of not breaking compatibility and compatible with matlab / octave but I think it gives surprise to new users (or anyone that do not use this function very often). TBH, I find it really tempting to think `0.8:1.2` is an interval unless I'm explicitly iterating over it.

For users of the current behavior, If you just want to get the work done, just write out the step shouldn't be too bad. If you want to write some generic code, writing `a:0x1:b` shouldn't be too bad.


I would also relate this to https://github.com/JuliaLang/julia/issues/7903 (or more discussion in https://github.com/JuliaLang/julia/issues/11769). Both of them are matlab/octave behaviors that confuses people from time to time. I agree that this one might have more users than iterating a number and that's why I'm interested to see what are the use cases.

**Comment by simonster** [comment]
-1. The current behavior is very easy to explain: if you don't specify a step, the step is 1. There's nothing inherently confusing about this. The proposed alternative is more confusing.

What is confusing is that we use `rand` with ranges when we want random integers within an interval, but the same syntax does not work for floating point. But the way to fix that is to introduce intervals and fix our examples for `rand` to use them. It's not clear to me that eliminating methods from ranges will help much.

Finally, using `a:0x1:b` for generic code kind of blows. Not only is it ugly, but it creates a `StepRange` rather than a `UnitRange` if `a` and `b` are Ints.

**Comment by joehuchette** [comment]
I also (mostly) agree with Stefan, but I think there's one point that's backwards:

> It also makes it harder to write generic code without worrying about corner cases.

Given the promotion behavior, the current behavior for ``a:b`` makes it harder to write generic code without worrying about the standard float vs. int corner cases (e.g. #12547, #7420), despite Stefans great work with ``FloatRange``s.

For a contrived example, you have something like
```jl
julia> s = 1;

julia> length(typemax(Int)-s : typemax(Int))
2

julia> s = 1.;

julia> length(typemax(Int)-s : typemax(Int))
1
```

It seems to me that in many (most?) cases people want ``a:b`` to act like ``Int(a):Int(b)`` (except in the ``rand`` case, which is why the mental model broke down), in which case it's maybe not so bad to either push people towards writing that, or explicitly opt into ``a:c:b`` syntactically.

**Comment by mbauman** [comment]
Are there other places where intervals make for a better API?  In this case, it seems like we really want to express `rand(T, Interval(lower_bound, upper_bound))`.  The `..` operator can work very nicely for this: `rand(Float64, 1.8 .. 2.2)`.  Multiple folks have created interval packages (or implementations within packages), but they're tough to generalize and fully support as a computable number.

That said, introducing complexity because the existing options were confusing is unlikely to solve the confusion… and may just make it worse.

**Comment by JeffBezanson** [comment]
I agree with Stefan et. al. Simply removing `a:b` for floats doesn't actually fix any of the mentioned problems.
