### ISSUE TITLE
c11 _Static_assert is used in c99 mode

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#12881]
The build fails when linking ``usr/bin/julia``
```
/scratch/julia/usr/lib/libjulia.so: undefined reference to `_Static_assert'
collect2: ld returned 1 exit status
make[1]: *** [/scratch/julia/usr/bin/julia] Error 1
make: *** [julia-ui-release] Error 2
```

I am on 
```
Distributor ID:	CentOS
Release:	6.6

LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
```
with 
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Stepping:              3
CPU MHz:               3301.000
BogoMIPS:              6584.39
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-3
```
```
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
ldd (GNU libc) 2.12
```

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/commit/a96afe2f1d65a4e9d20a65d8fbab20b66069495b#commitcomment-12870463

**Comment by pao** [comment]
As I also responded in the issue @yuyichao linked, GCC 4.4.x isn't currently supported; the floor is currently set at GCC 4.7.

**Comment by yuyichao** [comment]
Although GCC 4.4 is not supported, the use of c11 feature in c99 mode still breaks compilation on icc. It is pretty easy to restrict the use of `static_assert` only to `c11` or `c++11` but I'd like some input from @Keno (who originally added this assertion) before doing that.

(I also hijacked the title since this is probably a won't fix for unsupported compilers otherwise)

**Comment by pao** [comment]
No problem, that is more accurate.

**Comment by mschauer** [comment]
Wasnt it supported until recently? I mean I was compiling julia without problems on that machine 
before...

**Comment by yuyichao** [comment]
So [it turns out](https://gcc.gnu.org/wiki/C11Status) that gcc 4.7 has support for both `-std=c11` and `_Static_assert`.

[Icc also appears](https://software.intel.com/en-us/articles/c11-support-in-intel-c-compiler) to have support for `_Static_assert` in `15.0` which is also our minimum required version according to README.

For windows, I guess we are also requiring a recent enough gcc version and @tkelman's comment seems to suggest that `static_assert` works fine with MSVC.

I haven't been able to find when did clang start supporting c11 and `_Static_assert` yet although I don't imagine it to be worse than gcc.

**Comment by pao** [comment]
@mschauer since you're building from git, you may just want to locally patch that out (or revert the commit) for now.

**Comment by nalimilan** [comment]
@mschauer I think it worked in practice, as fixes have been committed some time ago to work around bugs in older gcc versions.

**Comment by pao** [comment]
I believe we've taken such patches before--it may be more of a "this doesn't get tested on" requirement.

**Comment by nalimilan** [comment]
Ah, found one of them: https://github.com/JuliaLang/julia/pull/9984 The requirement for gcc >= 4.7 was apparently based on the idea that we would need to build LLVM 3.5 or newer.

**Comment by TomekTrzeciak** [comment]
For some time now I have the following hack in my `Make.user`:
`JCFLAGS += -D'_Static_assert(...)='`
to deal with the `_Static_assert ` business and compile with gcc44.
