### ISSUE TITLE
scale!(A,b) for triangular matrices is actually scale(A,b)

### ISSUE THREAD

**Issue by mfasi** [JuliaLang/julia#12903]
For reference, the code I blame is
```javascript
for (t1, t2) in ([:UnitLowerTriangular, :LowerTriangular],
                 [:UnitUpperTriangular, :UpperTriangular])
    @eval begin
        function scale!{T,S<:Number}(A::$(t1){T}, c::S)
            D = $(t2)(Array(promote_type(T,S), size(A)...));
            scale!(D,A,c);
            return D
        end
        function scale!{T,S<:Number}(A::$(t2){T}, c::S)
            D = $(t2)(Array(promote_type(T,S), size(A)...));
            scale!(D,A,c);
            return D
        end
    end
end
```
The code does not modify the input matrix `A`, but instantiates and returns a new matrix. I think this can be solved easily for `UpperTriangular` and `LowerTriangular`, as rewriting the method to modify `A` in place and return it should be enough, but I am not sure what I should do with the `Unit` versions.
These methods cannot be removed as they are used by `scale(A,c)`, but `A` cannot be modified in place without changing type (from `UnitUpperTriangular` to `UpperTriangular` and from `UnitLowerTriangular` to `LowerTriangular`).

**Comment by stevengj** [comment]
If no in-place version is possible, (as for the `Unit` versions) then `scale!` should not be defined.

**Comment by mfasi** [comment]
Would renaming these functions `scale()` be acceptable?

**Comment by andreasnoack** [comment]
I guess ti would actually be okay to have a `scale!(A::UnitLowerTriangular) -> LowerTriangular`, i.e. it returns a `LowerTriangular` which is the same underlying memory as `A`. That would be similar to how the factorizations work.

**Comment by Jutho** [comment]
The question is, if you use an inplace method such as scale!, do you always write
```julia
A=scale!(A,scalar)
```
or just
```julia
scale!(A,scalar)
```
I know I certainly use the second form sometimes, and that would fail with the suggestion of @andreasnoack .  The first form would lead to a type instability with that same suggestion; not sure how bad that is.

**Comment by andreasnoack** [comment]
What is type instability in the first form?

**Comment by Jutho** [comment]
if `A` changes from `UnitLowerTriangular` to `LowerTriangular`. Of course you can use a new variable to avoid this, but this is already quite different from the standard `scale!` idiom, since now you are not really scaling in place: you are returning a new object corresponding to the scaled matrix, and where you have recycled some memory from the input to `scale!`, or, put differently, destroyed the input given to `scale!`. I.e. if you write `B = scale!(A,scalar)` then `A` should no longer be used afterwards, as it would still have unit diagonal but rescaled off-diagonal elements.

 There are other exclamation mark functions that use this idiom (the result is the return value, but we destroy the inputs in creating it), so it is certainly a possibility. It just seems to be quite different from how `scale!` works on normal matrices.

**Comment by andreasnoack** [comment]
I agree that it is a bit dangerous to invalidate the array as would be the consequence of defining `scale!(UnitXTriangular)` in the way described above because many people are probably now using the return value.

@mfasi Let's just remove the exclamation marks from the definitions. Would you make pr?

**Comment by tkelman** [comment]
We did @andreasnoack's suggestion recently with `tril!`. I don't see a problem with returning a different type wrapping around the same data.

**Comment by mfasi** [comment]
@andreasnoack Yes, I can do it. Actually, I'd need the true `scale!()` for `UpperTriangular`, so I'd prefer to define `scale!(T::Union{UpperTriangular,LowerTriangular},c::Number)` and `scale(T::Union{UnitUpperTriangular,UnitLowerTriangular},c::Number)`,  provided there is no problem in this approach.

**Comment by andreasnoack** [comment]
No it should be fine to define
```jl
scale!(T::Union{UpperTriangular,LowerTriangular},c::Number)=scale!(T,T,c)`
```

**Comment by nalimilan** [comment]
> We did @andreasnoack's suggestion recently with tril!. I don't see a problem with returning a different type wrapping around the same data.

@tkelman AFAICT it's going to break badly if somebody passes a `UnitLowerTriangular` to a function defined on `AbstractMatrix` that calls `scale!` without using the return value, giving the scenario that @Jutho highlighted, in code that the caller didn't write. Breaking the `AbstractMatrix` abstraction isn't acceptable IMHO.

Better require people to convert to `LowerTriangular` manually first. `scale!(::UnitLowerTriangular, c)` could print a message explaining that.
