### ISSUE TITLE
`startswith` and `endswith` look suspicous

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#12917]
The definitions for `startswith` and `endswith` for strings look suspicious (`base/string/util.jl`):
```
startswith(str::AbstractString, chars::Chars) = !isempty(str) && str[start(str)] in chars
endswith(str::AbstractString, chars::Chars) = !isempty(str) && str[end] in chars
```

1. Why `start(str)`? Isn't this always `1`?
2. Why `end`? Shouldn't this be `endof(str)` instead?

**Comment by yuyichao** [comment]
`end` is lowered to `endof`

**Comment by nalimilan** [comment]
...but indeed `1` and `start(str)` are equivalent for strings, and I think for all `AbstractArrays`. Not a big deal though.

**Comment by simonster** [comment]
If we're going for maximum generality it should be `first(str)` and `last(str)`. `start` is definitely wrong since a custom string type could have some other way of defining iteration. I also find the behavior of accepting a `Set{Char}` or `Vector{Char}` a bit questionable, since `startswith` doesn't accept a `Vector{T<:AbstractString}` or `Set{T<:AbstractString}`.

**Comment by yuyichao** [comment]
@simonster I made that mistake some time ago too. `first` and `last` returns the element not the index. `endsof` is the right way to get the last index and IIRC we don't have a generic way to get the start index and for most places we just use `1`.

**Comment by simonster** [comment]
We don't need the index here, just the first and last characters.

**Comment by yuyichao** [comment]
Ahh. That's right

**Comment by stevengj** [comment]
I agree that `first` and `last` are the right choice, although the current implementation seems to work for our current string types.
