### ISSUE TITLE
Precompilation clears ARGS

### ISSUE THREAD

**Issue by rened** [JuliaLang/julia#12958]
The following code outputs `ARGS = UTF8String[]`, ignoring any command line parameters passed:
```jl
VERSION >= v"0.4.0-dev+6521" && __precompile__()

module argscompile
@show ARGS
end
```
Commenting out the first line _and_ deleting the `.ji` file makes it work again.

**Comment by stevengj** [comment]
This is correct.  If you want `@show ARGS` to happen at run-time when the module is loaded, rather than at compile-time, you should put it into an `__init__` function.  The whole point of precompilation is to separate run-time computations from compile-time computations.

(And the compilation itself is performed in a separate Julia process, so that it is isolated from temporary runtime conditions, like `ARGS`, in the Julia process that happens to trigger compilation.)

**Comment by rened** [comment]
I see, thanks a lot for the explanation! Makes sense, of course - it's the first time I seem to need to use an `__init__` function for my modules.
