### ISSUE TITLE
sparse and transpose on sparse matrices could be faster

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#12998]
I thought this was worth a separate issue.

In #12981 @mb1234 posted a short comparison script to benchmark few methods on sparse matrices between Julia, Octave and Matlab. The script to perform the table below can be seen in https://github.com/JuliaLang/julia/issues/12981#issuecomment-138122760 except I added an explicit call to `gc()` between method invocations. The average of 5 runs is shown with the standard deviation in parenthesis.

| Func | Julia | Octave | Matlab (single thread) |
| --- | :-: | :-: | :-: |
| sparse: | 2.478101 (0.161879) | 1.233007 (0.098839) | 2.678221 (0.104867) |
| 2*A   : | 0.052062 (0.000805) | 0.120093 (0.042131) | 0.070358 (0.001547) |
| A'    : | 1.131908 (0.010331) | 0.810197 (0.075346) | 1.159815 (0.246967) |
| A+B   : | 0.246413 (0.001277) | 0.487021 (0.088988) | 0.202465 (0.000276) |
| A*x   : | 0.169672 (0.003784) | 0.340456 (0.009046) | 0.162381 (0.016590) |
| A'*x  : | 0.146576 (0.003835) | 1.191680 (0.099767) | 0.135291 (0.003267) |

In general, we are doing really well! However, we can see that for `sparse` and `transpose` we have a bit to go to match Octave. Right now, for `sparse` we are making a CSR-matrix and transposing it in the end. It should be possible to directly construct the CSC-matrix and avoid the transpose.

For `transpose` I looked at [the code](https://github.com/JuliaLang/julia/blob/f51873ab0578c7562cca9c1f84e6499b45c69201/base/sparse/csparse.jl#L135) and I am not sure what could be done. Anyone have any ideas here?

**Comment by KristofferC** [comment]
Maybe Octave doesn't sum duplicates?

**Comment by andreasnoack** [comment]
It appears that they do.
```matlab
octave:1> sparse([1,1], [1,1], [1,1])
ans = Compressed Column Sparse (rows = 1, cols = 1, nnz = 1 [100%])

  (1, 1) ->  2
```

**Comment by KristofferC** [comment]
`csparse` is GPL anyway so isn't it possible to just translate the Octave code?

**Comment by ViralBShah** [comment]
The reason for creating a csr and transposing is that we get everything in sorted order. For direct csc construction, you have to have a sorting step. Any idea what octave does? Also, maybe worth testing few different cases for the constructor.

**Comment by ViralBShah** [comment]
Related, see #13400 for a pathological case due to csr construction.

**Comment by KristofferC** [comment]
I took a stab at trying to improve our sparse but I failed. My attempt was to use a bucket for each column and sort the rows into that. I currently use a linear search through each bucket and insert the row at the proper place.

Here is my attempt: https://gist.github.com/KristofferC/554badaa7b9f494f45ee

And results:

```jl
n = 10^5
sparsity = 20 / n
accums = 5
nzs_1 = repmat(rand(1:n, Int(sparsity * n^2)), accums)
nzs_2 = repmat(rand(1:n, Int(sparsity * n^2)), accums)
vals = rand(Float64, length(nzs_1))

A2 = @time sparse2(nzs_1, nzs_2, vals)
#   5.090254 seconds (970.25 k allocations: 152.123 MB, 3.83% gc time)
A = @time sparse(nzs_1, nzs_2, vals)
#   1.284557 seconds (23 allocations: 186.918 MB, 3.46% gc time)
A == A2
# true
```

Maybe someone can find some obvious way to speed my attempt up.

**Comment by KristofferC** [comment]
For #13400 it is however much faster:

```jl
julia> @time sparse2([1;100000000], [1;1], [1;1])
  0.000008 seconds (19 allocations: 1.078 KB)
100000000x1 sparse matrix with 2 Float64 entries:
    [1        ,         1]  =  1.0
    [100000000,         1]  =  1.0

julia> @time sparse([1;100000000], [1;1], [1;1])
  4.620142 seconds (20 allocations: 2.235 GB, 3.77% gc time)
100000000x1 sparse matrix with 2 Int64 entries:
    [1        ,         1]  =  1
    [100000000,         1]  =  1
```

**Comment by ScottPJones** [comment]
If you use a O(n^2) algorithm such as an insertion sort, poor performance is to be expected.
See: http://bigocheatsheet.com/ and https://en.wikipedia.org/wiki/Sorting_algorithm
In the past, I've used a modified quicksort (to eliminated the O(n^2) worst case when already sorted),
along with a mergesort (when the things to be sorted did not fit into memory - chunks were sorted by modified quicksort, and then combined at the end by zero or more merge sort passes).
Also, instead of moving large data around, you can just use a vector that indexes your data, i.e. it starts as [1:n].  Finally, you have two vectors where you are doing insert! on, but maybe an single vector of immutable type that holds the index/value would work better (less memory shuffling if you do an in-place sort instead of using an index to the index/value pairs).  (Actually, instead of coming up with an immutable type, maybe you could just use the new Pair type).

If you are interested in this sort of performance optimizations, I'd recommend reading http://www.amazon.com/Introduction-Algorithms-Edition-Thomas-Cormen/dp/0262033844 (I had the course this was based on with Rivest and Leiserson, back in '81 or '82), also recommend Sedgewick's book (see http://algs4.cs.princeton.edu/home/, they have a free MOOC using the book).

**Comment by KristofferC** [comment]
O(n) relations are good to look at when n is large. Is n large? Most of the time in real applications, no. And in my example, also no. I don't think repeatedly quicksorting lists of length 20 will be faster than insertion sort.

**Comment by mauro3** [comment]
Here on binary search vs linear search: https://schani.wordpress.com/2010/04/30/linear-vs-binary-search/

**Comment by KristofferC** [comment]
Cool, I'll play around with some techniques there to see if I can get the search faster.

**Comment by ScottPJones** [comment]
Definitely depends on the size and sparsity - I have no idea what real applications you might be using this for, but I definitely wouldn't want an O(n^2) algorithm, with all that shuffling, if I were attempting to improve performance.
For the applications I'm used to, the sparsity could vary wildly - from totally dense to 1 in millions.
@mauro3's link is very good (although it is just about search, not sorting), and shows binary search as being about the same as linear up to around 25.

**Comment by KristofferC** [comment]
From the article:
>  If you need to search through a sorted array of integers and performance is really, really important, use linear search if your array is below around 64 elements in size, binary search if it’s above.

Anyway, let's not Scott this thread too much. If you think bisection search will be faster on my benchmark you can try it and see.

**Comment by ScottPJones** [comment]
>Anyway, let's not Scott this thread too much. If you think bisection search will be faster on my benchmark you can try it and see.

Was that meant to be a snarky comment?  Please refrain.
Also, you asked for help, and were given it.  Why should other people spend their time to try it out?

**Comment by KristofferC** [comment]
Giving a lecture about O(n) and giving a freaking wikipedia link to a page about general sorting is much more insulting than mentioning your constant derailing of Github issues.

It is good that you try to help, but try to understand the problem, play around with your suggestions and do some timings before firing of 20 lines mostly filled link to irrelevant books, wikipedia links and an obligatory life story.

> Why should other people spend their time to try it out?

Because people want fast `sparse` in Julia?? 

> Also, you asked for help, and were given it. 

I asked for suggestions about making `sparse` faster.  Not for someone to read the word "linear search" and start firing away the Wikipedia links.

**Comment by ScottPJones** [comment]
It wasn't even about linear search - that was @mauro3.  It was the *insertion sort* that I had commented on.  The books weren't at all irrelevant - have you read them?

**Comment by ScottPJones** [comment]
>Why should other people spend their time to try it out?
Because people want fast sparse in Julia??

I well understand that people want fast sparse in Julia - my question was really, why should people waste time modifying your benchmark to use binary search to try to improve the performance?

**Comment by johnmyleswhite** [comment]
FYI: I'm going to lock this issue if *even one* more comment that contains any noise goes through the issue tracker.

**Comment by KristofferC** [comment]
Fine to lock.  Already derailed.

**Comment by ViralBShah** [comment]
I really would prefer to delete off-topic comments on searching and sorting here - basically from right after @KristofferC 's attempt. This was a nice performance tracking issue that we had, and it is a shame to have to lose it to the noise.

**Comment by KristofferC** [comment]
Please do.

**Comment by ViralBShah** [comment]
I propose to delete the part of the conversation I outlined above, in about a day from now. We haven't done this kind of a thing before, but I think this is the best way of keeping this issue relevant for the purpose it was created.

Cc: @StefanKarpinski

**Comment by ScottPJones** [comment]
@viralbshaw The comment on sorting was not off-topic.  I described both how I solved the same problem (performance issue with creating a sparse structure from a set of unsorted, possibly duplicate key(s)/values), and also the sources for the algorithms I used.  The problem I solved in the past, using the techniques I described above, was actually a lot more complex, because it was multi-dimensional sparse arrays, not just 2 dimensional matrices, with keys that could be any value, not just positive integers, both for arrays that could fit in memory, and ones that could be many terabytes.

This wasn't even a good performance tracking issue, it was more the sort of thing that should have been left to a Julia-users discussion.
The benchmarking is very limited - it just tests one particular size, with no duplicates, no zero values,
with random indices, with a single level of sparsity.
It doesn't test cases like different sizes, different levels of sparsity, whether the input is already in column major sorted order, or is the reverse of that, or is in random order, whether there are duplicates, and what percentage of duplicates there are, whether there are zero values in the input, and what percentage of the input is zero values.
@KristofferC's code doesn't handle zero values nor duplicates - it has no combine function, and doesn't even perform the default behavior of adding duplicates, it also doesn't check the validity of the inputs - so comparing the performance of something that doesn't actually implement what is being tested is not very useful.

**Comment by ViralBShah** [comment]
Everyone here knows all this. @kristofferc wrote code and benchmarks. That is valuable. Please submit code, not discussion.

**Comment by Keno** [comment]
I think that's enough discussion here. Anybody who thinks they can write a faster `sparse` is welcome to submit a PR. If at that point somebody else find said implementation deficient in some way they can do the benchmarks to show that. Let's argue about code and data not hypotheticals.

**Comment by StefanKarpinski** [comment]
I have deleted @ScottPJones comments and all the back and forth waste of everyone's time (@KristofferC, primarily) and unlocked the issue so that we can make forward progress on it. @ScottPJones, you may not post here. If you do so, you will be blocked for JuliaLang for a week.

**Comment by ViralBShah** [comment]
@KristofferC I used to have the insertion sort based logic a long time back, and switched to the current one since it was faster.

**Comment by KristofferC** [comment]
We are pretty much the same as MATLAB now so dont think there is a need to keep this issue open.
