### ISSUE TITLE
Print the type's help for undocumented bindings

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#13002]
In 0.3:

```txt
julia> sparse([1,2,3]);

help?> ans

	[1, 1]  =  1
	[2, 1]  =  2
	[3, 1]  =  3 is of type
DataType   : SparseMatrixCSC{Int64,Int64} (constructor with 1 method)
  supertype: AbstractSparseArray{Int64,Int64,2}
  fields   : (:m,:n,:colptr,:rowval,:nzval)
```

Currently:

```txt
help?> ans
search: ans transpose transpose! ctranspose ctranspose! randsubseq randstring
```
This was a nice way to explore an API.  It'd be nice for an undocumented binding/object to print out its type and the type's help (which is much nicer now with #12996).

**Comment by MichaelHatherly** [comment]
Yeah, would be good to have. I didn't really like the way it echoed the object itself since sometimes that would be distracting if it's a large object.

This would probably just need some minor changes to https://github.com/JuliaLang/julia/blob/5edd47c0574762c3e4b44c8045b3263c4bbac9a4/base/docs/Docs.jl#L98-L101 I think.
