### ISSUE TITLE
`reload` prints a deprecation warning

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#13059]
It's not deprecated, so this shouldn't happen.

**Comment by JeffBezanson** [comment]
https://github.com/JuliaLang/julia/issues/13052#issuecomment-139319402

**Comment by yuyichao** [comment]
In that case, we are also missing the document for `reload` [latest doc](http://julia.readthedocs.org/en/latest/search/?q=reload&check_keywords=yes&area=default) [release-0.3 doc](http://julia.readthedocs.org/en/release-0.3/search/?q=reload&check_keywords=yes&area=default)

I caught this with script but didn't add it because I thought it was also deprecated along with `require(::AbstractString)`

**Comment by JeffBezanson** [comment]
Actually, it's worse than this. The deprecated `require` does not work at all.

**Comment by ScottPJones** [comment]
This is why I've said that deprecated functions really should have unit tests, just like any other code, and hopefully we'll get to complete coverage of them as well, like we are trying to do for the rest of base.  Just because they will go away at some point in the future, doesn't mean that people don't depend on them in the meantime.

**Comment by ssfrr** [comment]
so does that mean that `reload` doesn't work right now? I've been having trouble with it lately but I've been messing around in Atom so I figured it was due to something in there.

**Comment by JeffBezanson** [comment]
Yes, there could very well be problems with it. Post more examples of failures if you have them. `require` is in worse shape though. I'm working on a fix.

**Comment by ssfrr** [comment]
FYI with a simple module I can reproduce my issue in Atom but not in the REPL, so I think it has more to do with my understanding of how Atom.jl handles module resolution or something.

**Comment by JeffBezanson** [comment]
Also needs 615e746967de9a333cb5d43b4dc90abf207c55aa

**Comment by tkelman** [comment]
Got it in the #13107 branch
