### ISSUE TITLE
chained parsing of assignment?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#13186]
[This thread](https://groups.google.com/forum/#!topic/julia-users/r3yrLn9lZtY) is just the most recent example of people's confusion about how chained assignment works in Julia. The current behavior is that `y = x` assigns `x` to `y` and evaluates to the value of `x`, which ensures that in `z = y = x`, the value of `x` is assigned to `z` no matter what implicit conversion may happen when `y` is assigned the value of `x`. This is very important since conversions to type variables are implicit and can do completely arbitrary things. This seems to confuse people pretty often because they expect `y = x` in isolation to evaluate to whatever value `y` ends up having.

It might be less confusing if we parsed `z = y = x` as `(= z y x)` instead of `(= z (= y x))` with the behavior that it assigns `x` to `y` and then `z` but evaluates to the value of `z` rather than the value of `x`. The only practical downside I can think of is that this would make `z = (y = x)` and `z = y = x` mean different things. But I don't think I've ever seen anyone parenthesize a chained assignment that way.

**Comment by JeffBezanson** [comment]
-1

In both that thread and the linked issue where this came up before, the conclusion was "ok, that makes sense". I don't think changing this is worth the syntax churn and subtle behavior changes. How confident are we that nobody will be confused by `a = b = c` and `a = (b = c)` doing different things?

IIUC, in this proposal the leftmost argument of `=` is returned instead of the rightmost argument. I don't think that behavior is better, and it will be very difficult to fix all affected code. In the multi-argument form, we'd assign the rightmost value to every other argument like we do now, but then return the leftmost argument. So first the rightmost value is special, then the leftmost is. This strikes me as more complicated.

**Comment by StefanKarpinski** [comment]
It is more complicated, but I suspect that the `a = (b = c)` case would come up vanishingly rarely.

**Comment by ScottPJones** [comment]
I think maybe it's more of a documentation issue, something to be added to the "Noteworthy differences" sections, like the one I added for C/C++.  I'm fine with the current behavior, now that I understand it.

**Comment by ggggggggg** [comment]
I'm the one who posted the linked thread. I did try to search the documentation for a description of this behavior, and I couldn't find anything. I looked in "Variables", "Functions", and a few other places. I tried searching for "assignment", "expression", "value", "=".

It seems like it is mostly (only?) an issue when dealing with type assertions and type declarations? In that case maybe it makes sense to talk about this behavior in "Types/Type Declarations"?

**Comment by JeffBezanson** [comment]
> but I suspect that the a = (b = c) case would come up vanishingly rarely.

Whereas now it comes up exactly never, because there is no distinction.

**Comment by mbauman** [comment]
Interestingly, this also has a significant impact on field assignment and indexed assignment, but I'm not sure I've ever seen a thread complaining about its behavior in those places.  If this were to change, what would `A = Array(Int, 4); A[2:3] = 0` return?  It should probably be `A`, but that means that the rule is even more complicated than using the right-most expression for all assignments and returning the value of the left-most expression.

The current rule may not be very intuitive, but it's so stinking simple.

**Comment by JeffBezanson** [comment]
That is an interesting point. I don't recall, but it may have gone into the original thinking behind this behavior: in `A[2:3] = x` we already have `x` computed, so returning it is easy, but if we had to return the left operand we might have to separately construct `A[2:3]`.

**Comment by mbauman** [comment]
Exactly.

I wonder if part of this is because folks can't play with typed variables directly in the REPL, so the very first thing they try is an assignment in a function.

**Comment by StefanKarpinski** [comment]
Yes, but the fact that `a = b` returns `b` rather than `a` comes up a lot.

**Comment by StefanKarpinski** [comment]
I do find the indexed assignment argument pretty compelling. I vaguely recall that this may have been one of the things we were thinking about when we decided to make things work like this in the first place. It would require some signficant email excavation to figure out.

**Comment by JeffBezanson** [comment]
I think the indexed assignment case shows that returning the left argument is generally questionable, because it's an lvalue, not an rvalue. In almost all (maybe all?) languages lvalues are also valid rvalues, but this doesn't necessarily need to hold. In the case of arrays, it fails to hold with respect to performance. One could imagine crazy cases like assignment sending a value to a channel or socket, where it's not clear what it means to treat the lvalue as an rvalue.

**Comment by StefanKarpinski** [comment]
We decided on returning the RHS here. Except for `.=` which confusingly returns whatever view object the LHS assigns into, which is generally considered to be a design bug that we should not have allowed in 1.0, oops.
