### ISSUE TITLE
@code_warntype should not highlight Union{}

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#13295]
A simple example where every single type annotation is highlighted:

```jl
julia> @code_warntype error()
Variables:
  s::Tuple{}

Body:
  begin  # error.jl, line 22:
      return (Base.throw)(((top(getfield))((top(getfield))(Base.Main,:Base)::Any,:call)::Any)((top(getfield))((top(getfield))(Base.Main,:Base)::Any,:ErrorException)::Any,((top(getfield))((top(getfield))(Base.Main,:Base)::Any,:string)::Any)()::Any)::Any)::Union{}
  end::Union{}
```

The `Any`s are harmless, and `Union{}` shouldn't really be considered type unstable.

**Comment by yuyichao** [comment]
(I thought I mentioned this somewhere but couldn't find it...)

I sometimes find it useful to have `Union{}` highlighted since there might be something wrong with the code if they appear at someone you didn't expect (e.g. typo in the field name etc). They should normally appear only in the error path so it doesn't matter so much even if such path has type instability.

At the same time, I can see that having highlighted type in a function that should be type stable can be confusing, maybe we can just document this?

**Comment by timholy** [comment]
I agree, it's better to highlight `Union{}`. It's saved me several times from not realizing the function would error on me were I to actually run it with the given inputs.

**Comment by johnmyleswhite** [comment]
+1 to highlighting `Union{}`

**Comment by jiahao** [comment]
Looks like the consensus is to close in favor of #13568
