### ISSUE TITLE
`replace` doesn't convert replacement argument to string any more in 0.4

### ISSUE THREAD

**Issue by carlobaldassi** [JuliaLang/julia#13332]
I don't know if this is intentional, but I didn't see it mentioned in the NEWS or in the documentation.

In julia 0.3:

```
julia> replace("abc", 'b', 2.1)
"a2.1c"
```

whereas in 0.4:

```
julia-0.4> replace("abc", 'b', 2.1)
"aΌ͌͌\0@c"
```

This can lead to unexpected and funny results, and to silently broken code (no deprecation is provided).

**Comment by ScottPJones** [comment]
I'd very much like to know the answer to that, because I've been trying to fix some of the type-instability in replace (in particular, `UTF16String` and `UTF32String`s get returned as ASCIIStrings or UTF8Strings,
depending on what's in them, and what's been replaced.
This seems like it needs a unit test for whatever the correct behaviour should be.

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/commit/bbca721359a7c734d28ab4fbb74647c7a222098f @malmaud

**Comment by malmaud** [comment]
That change was unintentional. I'll reimplement it, and it should probably be backported.
