### ISSUE TITLE
NullSpace for BitArray and SparseBitArray

### ISSUE THREAD

**Issue by raichu** [JuliaLang/julia#13512]
An implementation of [NullSpace](https://reference.wolfram.com/language/ref/NullSpace.html) that uses [Block Lanczos algorithm](https://en.wikipedia.org/wiki/Block_Lanczos_algorithm) for yet-to-come SparseBitArray (issue #13511) is sorely needed.

(original closed issue is #8469)

**Comment by jiahao** [comment]
You still haven't explained your use case.

**Comment by raichu** [comment]
> You still haven't explained your use case.

This is like asking "what is your use case for wanting SVD for matrices". NullSpace is an elementary operation in linear algebra. My specific use case is related to a research on LDPC codes, but it doesn't matter here now, does it?

**Comment by jiahao** [comment]
> This is like asking "what is your use case for wanting SVD for matrices?".

No, it is not. SVDs are demonstrably useful. Any proposed feature to go into Base must have a reasonable use case; most features whose benefits are not known beforehand usually start out life as an external package before being incorporated into Base when there is demand for that functionality.

Rather than being antagonistic, why not be more productive and try implementing the ideas you have?

**Comment by raichu** [comment]
Yes, it is. Sorry if you missed your linear algebra classes.
It is also called [kernel](https://en.wikipedia.org/wiki/Kernel_(linear_algebra), and is very useful and elementary in linear algebra.

> Rather than being antagonistic,

That is you.

> why not be more productive and try implementing the ideas you have?

Productive means different things to you and me. Julia doesn't pay my bills. And I already became productive by switching to Mathematica.

**Comment by jiahao** [comment]
Marking as up for grabs.

**Comment by stevengj** [comment]
Given that even iterative algorithms over the real numbers are not in Base, I'm skeptical that this belongs in base rather than in a package.

Number theory is certainly an interesting and important field (no pun intended), but it's not as central to Julia's focus on scientific/technical computing as linear algebra over real and complex numbers, and so a lot of number theory algorithms probably belong in a package.

And @raichu, your dialogue is rude and often counter-productive.

**Comment by ViralBShah** [comment]
Yes, this certainly doesn't belong in base. 

@raichu The mailing list is the place to bring up such discussion, if the hope is to find help. The dialogue is clearly in violation of our [community standards](http://julialang.org/community/standards/). We would love to have you continuing Julia, but do request to keep the dialogue meaningful and constructive.

**Comment by JeffBezanson** [comment]
Yes, this should be discussed in IterativeSolvers.jl.

**Comment by StefanKarpinski** [comment]
It might make sense to have a `nullspace` function in Base.

**Comment by JeffBezanson** [comment]
There is one already.

**Comment by StefanKarpinski** [comment]
Ah, my bad. Didn't realize we had that already. Go us.
