### ISSUE TITLE
Change the name of "Julia" before 1.0?

### ISSUE THREAD

**Issue by EricForgy** [JuliaLang/julia#13531]
Is it a ridiculous idea?

The conversation [here](https://groups.google.com/forum/?fromgroups=#!topic/julia-users/qUomRDzIRus) is painful and could be avoided.

**Comment by simonster** [comment]
Personally I think it would be quite sad if a programming language cannot have a female name because this prompts a very small group of users to make inappropriate comments.

**Comment by MichaelHatherly** [comment]
The way to avoid conversations such as that one should be to follow the Community Standards. That conversation really shouldn't have needed further digressions after Stefan's initial request.

If there are parts of the JCS that aren't clear enough then PRs can be opened to fix them and additional discussion can be had over the concrete proposals rather than derailing other topics.

**Comment by jiahao** [comment]
Renaming the project entirely seems like a measure of absolute last resort. Before that, I would prefer to consider the more general issue of improving awareness and enforcement policy of Julia's Community Standards. 

Also relevant is @ihnorton's PR #13516 to reword `CONTRIBUTING.md`. The contents of this file are particularly relevant because AFAICT this is GitHub's only available mechanism for [pointing new contributors to a message we can customize](https://help.github.com/articles/setting-guidelines-for-repository-contributors/).

**Comment by lobingera** [comment]
-1

Discussions similar to the above might show up - and i'm sure the JCS will not help in all cases as the use of a programming language can not be controlled to the julia community alone - again and again, and then someone aware of the 'julia' culture should stand up and make the statement about naming and the correct use of the name and that's it.

**Comment by StefanKarpinski** [comment]
I appreciate where this is coming from, but when people behave inappropriately, the right response is to (gently) correct the behavior, not to bend over backwards to avoid situations where they might be tempted to behave inappropriately.

**Comment by ScottPJones** [comment]
@MichaelHatherly I have submitted a PR https://github.com/JuliaLang/julialang.github.com/pull/287.
As this document is considered important to the community, it might be good to have the standards on the home page of julialang.org, instead of nested two levels deep, along with all the benchmarks, etc.

**Comment by MichaelHatherly** [comment]
Thanks @ScottPJones, much appreciated.
