### ISSUE TITLE
faster rank for rectangular matrices

### ISSUE THREAD

**Issue by matthieugomez** [JuliaLang/julia#13607]
For dense matrices of size n, m with n >= m, it seems like
the function rank could be made faster by computing the cholesky decomposition

```julia
m = 10
for n in (100, 1000, 10000, 100000)
    A = rand(n, m)
    @time rank(A)
    @time rank(cholfact!(At_mul_B(A, A), :U, Val{true}))
end
 # 0.000145 seconds (21 allocations: 22.641 KB)
 # 0.000103 seconds (12 allocations: 1.609 KB)
 # 0.000224 seconds (24 allocations: 92.969 KB)
 # 0.000143 seconds (12 allocations: 1.609 KB)
 # 0.001367 seconds (24 allocations: 796.094 KB)
 # 0.000234 seconds (12 allocations: 1.609 KB)
 # 0.071097 seconds (24 allocations: 7.644 MB, 80.06% gc time)
 # 0.002141 seconds (12 allocations: 1.609 KB)
```

**Comment by matthieugomez** [comment]
Actually, the rank based on cholesky always seems to be faster than the current `rank` (based on `svdvals`)

**Comment by jiahao** [comment]
Computing the rank from the Cholesky factor of A'A may be faster, but in general it will be less accurate since you are squaring the condition number of the matrix you are working with. The SVD is slightly overkill, yes, but the right thing to do in general is a rank revealing QR, not cholfact of A'A.

For a specific problem a given user has, s/he may need only the rank to the accuracy computable from cholfact(A'A), but it is not a good idea to use this method for general purpose rank computations.

**Comment by matthieugomez** [comment]
Ok thanks for the explanation!

**Comment by matthieugomez** [comment]
What about adding a method keyword?

**Comment by jiahao** [comment]
I really don't think it's a good idea to make it easy to do numerically unstable computations. It should be safe to assume that users who know numerical linear algebra will know when it's OK to do `rank(cholfact(A'A))`, and users who don't know are better off with the slower but more accurate general purpose algorithm.

**Comment by matthieugomez** [comment]
Ok, thanks again for this.

**Comment by jiahao** [comment]
Here is a sketch of how `rank` could be improved:

- Supporting a `method` keyword as @matthieugomez suggested.The methods would be at least:
  - SVD - the current implementation
  - RRQR - rank revealing QR
  - (maybe) Cholesky - the fast but unstable way

- For RRQR, the rank can be determined from the column-pivoted QR produced by `Base.LinAlg.LAPACK.geqp3!`. The rank can be computed by counting the nonzero eigenvalues revealed along the diagonal of R.

- It's also useful to specify the tolerance for numerical zero as a parameter for rank determination, which would be used in all methods. Currently the tolerance can be specified but it is an [undocumented parameter](https://github.com/JuliaLang/julia/blob/d711b7d8a174edfd7633e0a2fa6553162e9e144b/base/linalg/generic.jl#L302-L309). 

- The Cholesky method would need to figure out which matrix to compute on - A'A or A*A', whichever is smaller, would suffice. The rank can be computed similarly as in the RRQR by counting the nonzero eigenvalues revealed along the diagonal of the Cholesky factor.

@matthieugomez this would make for a nice small side project, if you would be interested to work on implementing this functionality.

**Comment by andreasnoack** [comment]
I don't think a keyword is the right solution here. The different methods separate perfectly into different factorizations, so the right way to get a rank estimate based on the pivoted QR is to define a `rank(QRPivoted)` method. We already have the `rank(CholeskyPivoted)`. Defining `rank(QRPivoted)` is of also relevant for our solvers for under-determined systems and rank deficient least squares. Right now, we don't have generic fall backs for the rank estimation [here](https://github.com/JuliaLang/julia/blob/d711b7d8a174edfd7633e0a2fa6553162e9e144b/base/linalg/qr.jl#L367-L378)

**Comment by matthieugomez** [comment]
@andreasnoack it's a good case forhaving type for factorization rather than `cholfact, qrfact` functions, i.e.
```julia
factorization(Cholesky, A)
rank(Cholesky, A)
```

**Comment by andreasnoack** [comment]
I'm not sure. Indeed, `rank(cholfact(A, :L, Val{true}))` is too verbose, because of the way we specify pivoting, but do you think that `rank(CholeskyPivoted, A)` is better than `rank(cholfact(A))`? The problem with using the type explicitly is also that ,right now, we try to talk about the *Cholesky* factorization in some more abstract sense than the `Cholesky` type. By that I mean that `cholfact` can return three different *Cholesky* factorization types (`Cholesky`, `CholeskyPivoted` and `CHOLMOD.Factor`) depending on the input. I think it will be less userfriendly to use the types explicitly instead of the `cholfact` function.

**Comment by matthieugomez** [comment]
For rank, I was thinking of the case of a rectangular matrix
```julia
rank(Cholesky, A) = rank(cholfact!(At_mul_B(A, A), :U, Val{true}))
```

For `factorization`, I see your point (again I'm not clear on how everything works currently), but
- `Cholesky` could be an abstract type, with different instantiation dependent on the type of A
- When the user wants to impose a certain return type, `factorization(CholeskyPivoted, A)` make the relationship between function calls -> result type clearer than `cholfact(A, :U, Val{true})`.
