### ISSUE TITLE
typeinference / getfield(NTuple{N, T}) / inlining error

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#13652]
type-inference (inlining?) incorrectly expands `f(d::NTuple{N, T}...)` into `f(d[1], d[2])` in the AST:
```julia
julia> code_typed(Base.call, (Type{Base.BitArray}, Tuple{Vararg{Int64}}))
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[symbol("##946"),:dims], Any[Any[Any[:dims,NTuple{N,Int64},0]],Any[],Any[],Any[:N]], :(begin  # bitarray.jl, line 29:
        return ((top(apply_type))(Base.BitArray,N)::Type{_<:BitArray{N}})((top(getfield))(dims::NTuple{N,Int64},1)::N,(top(getfield))(dims::NTuple{N,Int64},2)::Int64)
    end))))
```

for comparison, a valid call looks like:
```julia
julia> code_typed(Base.call, (Type{Base.BitArray}, NTuple{1, Int64}))
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[symbol("##946"),:dims], Any[Any[Any[:dims,Tuple{Int64},0]],Any[],Any[],Any[:N]], :(begin  # bitarray.jl, line 29:
        return (BitArray{1})((top(getfield))(dims::Tuple{Int64},1)::Int64)::BitArray{1}
    end::BitArray{1}))))

julia> code_typed(Base.call, (Type{Base.BitArray}, NTuple{0, Int64}))
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[symbol("##946"),:dims], Any[Any[Any[:dims,Tuple{},0]],Any[],Any[],Any[:N]], :(begin  # bitarray.jl, line 29:
        return (BitArray{0})()::BitArray{0}
    end::BitArray{0}))))
```

**Comment by carnaval** [comment]
as you probably know this can be blamed on https://github.com/JuliaLang/julia/blob/3e0e063676b5c3e7c1ce71dd49099353c887415f/base/inference.jl#L2941
since `NTuple <: Tuple`

but I think that
https://github.com/JuliaLang/julia/blob/3e0e063676b5c3e7c1ce71dd49099353c887415f/base/inference.jl#L784
can probably also be incorrect in that kind of case

would it make sense to have `isvatuple` also return true for `NTuple` when the first arg is not a constant int (which never happens since we expand those eagerly) ?

**Comment by carnaval** [comment]
actually we probably want two different predicates for `isvatuple` and `isknownlength` since we don't want a NTuple as a last argument to be interpreted incorrectly
