### ISSUE TITLE
Slow JIT compilation in zip(x...) is of order O(length(x))

### ISSUE THREAD

**Issue by colinfang** [JuliaLang/julia#13722]
It takes 10+ seconds to compile `a, b = zip(A...)` in the following example, and the speed seems to be related to the length of `A`. (Julia 0.4)

```{julia}
const A = Tuple{Int, Int}[]

for i = 1:200
    push!(A, (1, 1))
end

a, b = zip(A...)
a
```

Also, the type of `zip` it returns is a bit too complicated.

```{julia}
function test()
    c = zip(A...)
    a, b = c
    a
  
end

@code_warntype test()

Variables:
  c::UNION{BASE.ZIP2{TUPLE{INT64,INT64},TUPLE{INT64,INT64}},TUPLE{INT64,INT64},ZIP{I,Z<:BASE.ABSTRACTZIPITERATOR}}
  a::ANY
  b::ANY
  #s41::ANY
```
The first run of `test()` takes `.632628 seconds (2.36 M allocations: 105.897 MB, 0.13% gc time)`, plus 10+ seconds compilation time.

Should we have a dedicated `unzip`?

**Comment by JeffBezanson** [comment]
Yes, `zip` is not really designed to zip 200 things. It's designed to run things like `for (x,y) in zip(a,b)` really fast, with no overhead compared to iterating manually over both arguments. In fact in general you need to be careful when splatting a large number of values. In part this is an unavoidable consequence of multiple dispatch, since if `a` has 1000000 elements then `f(a...)` has to perform dispatch over 1000000 types.

**Comment by StefanKarpinski** [comment]
Pretty much any time you have `f(c...)` where `c` is an arbitrary length collection, you should reconsider.
