### ISSUE TITLE
fix microbenchmarks to be more alike

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#13729]
See: https://github.com/JuliaLang/julia/pull/13673

**Comment by kshyatt** [comment]
I think this is perf related? Could we get, like, a paragraph summary of what the situation is?

**Comment by ViralBShah** [comment]
The issue is that the original benchmark is supposed to use 2d indexing in construction of the complex array in mandel. Many of the versions are hand-linearized (C, Java, Fortran, Lua, Go, etc.). 

The other issue is that some of the benchmarks are not even creating the array and just summing up values upon computation. The summing is a correctness check, but the benchmark is to compute the complex array. I notice this in at least the Java and Fortran versions.

**Comment by eschnett** [comment]
You could change the correctness check to access the array elements in an "unpredictable" order (and accessing some array elements twice, maybe not accessing all of them). This should prevent that optimization.

**Comment by KristofferC** [comment]
Moved to https://github.com/JuliaLang/Microbenchmarks/issues/23
