### ISSUE TITLE
Loosen Vector argument restrictions to StridedVector in lapack.jl

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#13737]
I don't have time to do this right now, but at some point this should be done. It requires a check of the stride for all the changed arguments.

**Comment by kshyatt** [comment]
I'm bumping this because I just went through `lapack.jl` and it seems to me almost everywhere we *can* have `StridedVecOrMat` we do. The places we don't have it, and have just `Vector`, are for things like lists of pivots or elementary reflectors. Incidentally, there *are* a few places where we accept a `StridedVector` for `tau` (elementary reflectors) despite the fact that the LAPACK function does *not* accept a stride argument for `tau`, and I think this hasn't come up because no one has tested with strided vectors. An example is in `trsen` or `ormhr`. Should we remove those `StridedVectors` in favor of `Vector`s, or am I totally off-base about this?

**Comment by andreasnoack** [comment]
Yes. I think we should.

**Comment by kshyatt** [comment]
That's a yes to remove, right?

**Comment by andreasnoack** [comment]
Yes.
