### ISSUE TITLE
ccall number of arguments message

### ISSUE THREAD

**Issue by wherrera10** [JuliaLang/julia#13769]
I have been using a third-party-written C library in Julia, but some (not all) of the calls give the error:

ERROR: LoadError: error compiling myfunc: ccall: wrong number of arguments to C function

Since some work and some do not I wonder if there is a way to find out exactly how many arguments are wanted?  Does the Julia 0.4.0 compiler get this information, so that it might be possible for the error message to include the expected number of arguments?

This is a 32-bit Windows dll with 32-bit Julia if it matters.

**Comment by stevengj** [comment]
@wherrera10, I think you are misunderstanding the error message.

Julia has no way of knowing how many arguments a C function expects in `ccall`.  It doesn't parse the header file.  It doesn't even know that the function was written in C (as opposed to Fortran or some other language with a C-like ABI).   It only knows the argument types you tell it.

Remember that the syntax for `ccall` is `ccall(function, returntype, (argtypes...), args...)`.   What is happening here is that the number of `args...` you are passing does not match the number of `argtypes...` you told it to expect.  For example:

```
julia> ccall(:sin, Cdouble, (Cdouble,), 3, 4)
ERROR: error compiling anonymous: ccall: wrong number of arguments to C function
```
gives an error because I told it there was a single `Cdouble` argument, but I passed two arguments `3, 4`.

**Comment by wherrera10** [comment]
Thanks.  I had thought that the ccall function was checking the return stack for argument count, as the Python ctypes does.  It looks like I was passing two tuples for types and values in some cases intead of a tuple followed by individual values, and that was the problem.
