### ISSUE TITLE
Libtool link error when compiling 0.4 on Ubuntu

### ISSUE THREAD

**Issue by rodonn** [JuliaLang/julia#13788]
I am getting the following error when I try to compile on Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-63-generic x86_64)

    CCLD     libuv.la
    libtool: link: require no space between `-L' and `/afs/.ir/users/r/o/rodonn/local/lib/'
    make[3]: *** [libuv.la] Error 1
    make[2]: *** [all] Error 2
    make[1]: *** [libuv/.libs/libuv.la] Error 2
    make: *** [julia-deps] Error 2

I tried
    git clone git://github.com/JuliaLang/julia.git
    git checkout release-0.4
    git reset --hard
    git clean -x -f -d
    make cleanall
    make

I was able to get things running again by downloading the .tar.gz instead of trying to compile.

If the problem is something missing in my machine's configuration, I'm sorry for wasting your time.

**Comment by tkelman** [comment]
odd. can you try building with VERBOSE=1 so we can see more of what's going on?

**Comment by vtjnash** [comment]
if you do `cd deps/libuv && make V=1`, what is getting run for the `./libtool` line? it shouldn't be getting a `-L` flag:

`/bin/bash ./libtool  --tag=CC   --mode=link gcc -m64  -g -O2     -g -O2 -no-undefined -version-info 11:0:0  -v -o libuv.la -rpath /home/jameson/julia/usr/lib src/libuv_la-fs-poll.lo src/libuv_la-inet.lo src/libuv_la-uv-common.lo src/libuv_la-version.lo  src/unix/libuv_la-async.lo src/unix/libuv_la-core.lo src/unix/libuv_la-dl.lo src/unix/libuv_la-fs.lo src/unix/libuv_la-getaddrinfo.lo src/unix/libuv_la-getnameinfo.lo src/unix/libuv_la-loop-watcher.lo src/unix/libuv_la-loop.lo src/unix/libuv_la-pipe.lo src/unix/libuv_la-poll.lo src/unix/libuv_la-process.lo src/unix/libuv_la-signal.lo src/unix/libuv_la-stream.lo src/unix/libuv_la-tcp.lo src/unix/libuv_la-thread.lo src/unix/libuv_la-threadpool.lo src/unix/libuv_la-timer.lo src/unix/libuv_la-tty.lo src/unix/libuv_la-udp.lo     src/unix/libuv_la-linux-core.lo src/unix/libuv_la-linux-inotify.lo src/unix/libuv_la-linux-syscalls.lo src/unix/libuv_la-proctitle.lo      -lrt -lpthread -lnsl -ldl`

i suspect there is some environment variable that is inserting itself here (`LDFLAGS` probably) due to the `/afs` mount shraed/cluster config.

**Comment by rodonn** [comment]
I tried running with VERBOSE=1 and got the following
```
mv -f src/unix/.deps/libuv_la-proctitle.Tpo src/unix/.deps/libuv_la-proctitle.Plo
/bin/sh ./libtool  --tag=CC   --mode=link gcc -m64  -g -O2     -g -O2 -no-undefined -version-info 11:0:0  -L ~/local/lib/ -Wl,-rpath=~/local/lib/  -v -o libuv.la -rpath /srv/zfs01/user_data/rodonn/test/julia/usr/lib src/libuv_la-fs-poll.lo src/libuv_la-inet.lo src/libuv_la-uv-common.lo src/libuv_la-version.lo  src/unix/libuv_la-async.lo src/unix/libuv_la-core.lo src/unix/libuv_la-dl.lo src/unix/libuv_la-fs.lo src/unix/libuv_la-getaddrinfo.lo src/unix/libuv_la-getnameinfo.lo src/unix/libuv_la-loop-watcher.lo src/unix/libuv_la-loop.lo src/unix/libuv_la-pipe.lo src/unix/libuv_la-poll.lo src/unix/libuv_la-process.lo src/unix/libuv_la-signal.lo src/unix/libuv_la-stream.lo src/unix/libuv_la-tcp.lo src/unix/libuv_la-thread.lo src/unix/libuv_la-threadpool.lo src/unix/libuv_la-timer.lo src/unix/libuv_la-tty.lo src/unix/libuv_la-udp.lo     src/unix/libuv_la-linux-core.lo src/unix/libuv_la-linux-inotify.lo src/unix/libuv_la-linux-syscalls.lo src/unix/libuv_la-proctitle.lo      -lrt -lpthread -lnsl -ldl
libtool: link: require no space between `-L' and `/afs/.ir/users/r/o/rodonn/local/lib/'
make[3]: *** [libuv.la] Error 1
make[3]: Leaving directory `/srv/zfs01/user_data/rodonn/test/julia/deps/libuv'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/srv/zfs01/user_data/rodonn/test/julia/deps/libuv'
make[1]: *** [libuv/.libs/libuv.la] Error 2
make[1]: Leaving directory `/srv/zfs01/user_data/rodonn/test/julia/deps'
make: *** [julia-deps] Error 2
```

I'll try `cd deps/libuv && make V=1` next.
After that I'll see if moving it off the AFS drive fixes the problem.

Thanks.

**Comment by tkelman** [comment]
Looks like it's the `-L ~/local/lib/`, so @vtjnash called it. Do you have that added to `LDFLAGS` in `~/.bashrc` or somewhere similar?

**Comment by rodonn** [comment]
Yeah it looks like I do have LDFLAGS getting set somewhere
`echo $LDFLAGS` reports `-L ~/local/lib/ -Wl,-rpath=~/local/lib/`

**Comment by rodonn** [comment]
Ok manually getting rid of my LDFLAGS fixed the problem. Thanks for your help!

**Comment by abhilashsinghimd** [comment]
> Yeah it looks like I do have LDFLAGS getting set somewhere `echo $LDFLAGS` reports `-L ~/local/lib/ -Wl,-rpath=~/local/lib/`



> Ok manually getting rid of my LDFLAGS fixed the problem. Thanks for your help!


on doing echo $LDFLAGS the ouput is:
-L /home/abhilash/openssl/lib -Wl,-rpath,/home/abhilash/openssl/lib

How did you Edited these LDFLAGS ?? like in which file i.e .bashrc or .bash_profile etc?
