### ISSUE TITLE
lufact ill condition on sparse matrix

### ISSUE THREAD

**Issue by colinfang** [JuliaLang/julia#13781]
Basically, I cannot use `lufact` on a simple sparse matrix, but the dense version works fine.

Forgive me if I missed something obvious. Is it a result of some linear algebra concept?

```{julia}
A = sparse(Int[],Int[],Float64[], 3,3)
A[1,1] = 1
A[3,1] = 1
A[3,3] = 1
A[1,3] = 1

full(A)
3x3 Array{Float64,2}:
 1.0  0.0  1.0
 0.0  0.0  0.0
 1.0  0.0  1.0

B = lufact(A)
LoadError: Base.SparseMatrix.UMFPACK.MatrixIllConditionedException("")

B = lufact(full(A))

Base.LinAlg.LU{Float64,Array{Float64,2}}(3x3 Array{Float64,2}:
 1.0  0.0  1.0
 0.0  0.0  0.0
 1.0  0.0  0.0,Int32[1,2,3],2)
```

**Comment by andreasnoack** [comment]
The matrix you are trying to factorize is singular and therefore the factorization fails. That is the case for both the sparse and the dense version. If you look at the result from the dense factorization, you'll see a `2` after the `Int32[1,2,3]` which is an error code. The factorization has failed hwne that value is larger that zero.

In the sparse case we throw an exception when the matrix is singular instead of return the failed factorization. You could argue that we are inconsistent here and maybe we should not throw an exception in the sparse case. Note, however, that you cannot do much with a failed LU factorization. The reason why we don't throw in the dense case is because we want to use the information to compute `det(A)=0`, see https://github.com/JuliaLang/julia/pull/1499, and indeed
```jl
julia> det(A)
ERROR: Base.SparseMatrix.UMFPACK.MatrixIllConditionedException("")
 in umfpack_numeric! at sparse/umfpack.jl:173
 in lufact at sparse/umfpack.jl:114
 in det at linalg/generic.jl:508
```

**Comment by colinfang** [comment]
thank you for the explanation.
