### ISSUE TITLE
UnicodeError in REPL

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#13819]
I've got the following when trying to modify a line with Unicode in the REPL history

```jl
julia> Ω = 1
1

julia> ΩWARNING: Caught an exception in the keymap:
ERROR: UnicodeError: invalid character index
ERROR: syntax: invalid character "̠"
 in eval at ./boot.jl:264
```

There's nothing fancy at the first prompt and the key sequence at the second prompt is `\Omega<tab><Ctrl-p or UpArrow><space>`.

Looking at the the backtrace in GDB, it seems like the REPL is inserting the space after the first byte instead of the first character in a `UTF8String`. Using the key sequency `\Omega<tab><Ctrl-p or UpArrow><Ctrl-f or RightArrow><Ctrl-f or RightArrow>` it can also be seen that the cursor gets "stuck" on the first character at first (supposedly when it looks for the next code point).

**Comment by yuyichao** [comment]
This also happens on my on month old `0.4.0-rc3` build.

**Comment by stevengj** [comment]
The use of `length(s.p.prompt)` rather than `sizeof` in [`edit_insert`](https://github.com/JuliaLang/julia/blob/f8a4340548e7d6be31fede13cdc4e0f5f434f33f/base/LineEdit.jl#L494) looked suspicious to me at first glance, but that doesn't fix it.  It's probably something like that (using `length` in characters rather than in bytes).
