### ISSUE TITLE
"fatal: bad revision '^origin/ JuliaLang/master'" on make

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#13881]
On the `julia.mit.edu` machine (Ubuntu 15.04) with `git 2.1.4` installed, `make` now emits two new fatal messages on master:

```
$ git pull && make
remote: Counting objects: 50, done.
...
 2 files changed, 12 insertions(+), 2 deletions(-)
fatal: bad revision '^origin/ JuliaLang/master'
fatal: Not a valid object name origin/
    PERL base/version_git.jl.phony
    JULIA usr/lib/julia/inference0.ji
...
```

The build process appears to proceed normally.

Do we need to bump the version of `git` that is officially supported?

**Comment by tkelman** [comment]
how did you clone? what are your remotes?

**Comment by jiahao** [comment]
I last cloned this repo back in the 0.1 days.

Here's a snippet of my `.git/config`.
```
[remote "origin"]
        url = https://github.com/JuliaLang/julia.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

**Comment by tkelman** [comment]
step through https://github.com/JuliaLang/julia/blob/master/base/version_git.sh and see which line is giving the message. might be harmless.

**Comment by StefanKarpinski** [comment]
I see this all the time too – for years now.

**Comment by StefanKarpinski** [comment]
```
[remote "origin"]
	url = git@github.com:JuliaLang/julia.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

**Comment by eschnett** [comment]
Using `-x` in the shell script I find:
```
++ git rev-list HEAD '^origin/master'
fatal: bad revision '^origin/master'
+ fork_master_distance=0
++++ echo origin/
+++ git merge-base HEAD origin/master
fatal: Not a valid object name origin/master
++ git show -s --format=format:%ct
```

That is, the two errors are generated by the two commands `git rev-list` and `git merge-base`.

The reported errors are correct since I call my upstream `upstream` and not `origin`; `origin` points to my fork of the Julia repository on Github. This makes it much easier to push to my fork, since many tools (e.g. `SourceTree`) want to push to `origin` by default.

The underlying cause seems to be that I originally cloned Julia without using `.git` suffix in the repository name. The mechanism to determine the name of the upstream repository then fails. Modifying the pattern to match just `julia` instead of `julia.git ` seems to do the trick.
