### ISSUE TITLE
Improve Documentation on SharedArrays

### ISSUE THREAD

**Issue by ahwillia** [JuliaLang/julia#13922]
Caveat -- I'm new to using the parallel tools in Julia, but I think this section of the documentation could use some love: http://julia.readthedocs.org/en/latest/manual/parallel-computing/#parallel-map-and-loops

In particular, it notes that the following won't work as intended:

```julia
a = zeros(10)
@parallel for i=1:10
  a[i] = i
end
```

But states that [Distributed Arrays](https://github.com/JuliaParallel/DistributedArrays.jl) can fix this. It doesn't provide any specifics though. Simply trying:

```julia
using DistributedArrays
a = dzeros(10)
@parallel for i=1:10
  a[i] = i
end
```

Doesn't produce the desired behavior either. Neither does `@everywhere using DistributedArrays`. However, using SharedArrays *does work*:

```julia
a = SharedArray(Float64,10)
@parallel for i=1:10
  a[i] = i
end
```

If there is a way to make something simple like this work with DistributedArrays, I think it would be nice to include an example.

I've also seen people use `@sync @parallel for i=1:10`... but this doesn't seem necessary to get the desired behavior. Happy to contribute to the documentation if this sounds reasonable.

**Comment by timholy** [comment]
Certainly doc improvements would be very welcome. It sounds like a minimalist improvement would be directing users to SharedArrays rather than DistributedArrays.

As for a good illustration of `DistributedArrays`, I haven't used them in ages so I can't offer any useful advice. But surely there are others who can. I trust you've check the docs at https://github.com/JuliaParallel/DistributedArrays.jl?
