### ISSUE TITLE
Directory in tarball changed from "julia-$version" to "julia"

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#13925]
In the new 0.4.1 release prepared by @tkelman, the directory inside the tarball is called `julia`, while in 0.4.0 it was called `julia-$version`. This minor point is a source of annoyance for packagers. If it's not too late, I suggest we change it before people download it.

It would make sense to change the make scripts to automate this. I can have a look.

Anyway, thanks for the great backporting work @tkelman!

**Comment by tkelman** [comment]
Man you're fast. I'm writing a script to automate most of this. Easiest thing to do is just make a new clone with the desired directory name and run `make full-source-dist light-source-dist` from there. I'd kind of rather stop making these full tarballs since I'm not sure how many people are really using them...

**Comment by tkelman** [comment]
Replaced them, should be fixed now.

**Comment by nalimilan** [comment]
Great! Looks like you're the fast one. ;-)

About the full tarballs, I'm not sure, but they don't sound too costly to create.
