### ISSUE TITLE
inconsistent deprecation of push!(A) but not push!(A, items...)

### ISSUE THREAD

**Issue by damiendr** [JuliaLang/julia#13930]
Consider the following function that uses the `push!(dest, items...)` syntax:

``` julia
function f(items)
    dest = Set()
    push!(dest, items...)
end
```

Calling `f([1, 2])` raises no warning, but whenever `items` happens to be empty the following warning is emitted:
`WARNING: push!(A) has been deprecated`

I can't think of another natural way, in the current API, to add all the elements in a generic collection to an existing Set.

**Comment by nalimilan** [comment]
Also relevant is that `append!` doesn't work on `Set`.

**Comment by yuyichao** [comment]
Another relevant note is that you shouldn't splat a vector to call a vararg function.

**Comment by damiendr** [comment]
@yuyichao What is the rationale for that? That seems like such a natural thing to do. It is even given as an example in the doc, see http://julia.readthedocs.org/en/latest/manual/functions/#varargs-functions scrolling down to where it says:
>Furthermore, the iterable object spliced into a function call need not be a tuple:

The example calls a function defined as `bar(a,b,x...) = (a,b,x)` with both `bar(1,2,x...)` and `bar(x...)`.

**Comment by yuyichao** [comment]
* It's bad for type inference (it might know which function you are calling if it can't figure out how many argument you are actually supplying).

* For large arrays, the dispatch is potentially very expensive.

* For this particular case, I believe the definition is recursive (which could be good for small and known number of arguments) so with a large collection you pay a `O(n^2)` price as you recursively all these functions with a large number of arguments.

**Comment by yuyichao** [comment]
Also for you specific case, I don't think `Set` define any fancy multi argument `push!` so you'll be better off just write a loop.

**Comment by damiendr** [comment]
@yuyichao Makes sense for type inference in hot loops. But my particular use case is for a bit of code that does not need to be fast at all, but *does* need to be extra tidy and readable, because it's hairy enough as it is ;)

Performance issues aside, remains the issue of inconsistent warnings / lack of `append!` for Sets. I think it may be worth harmonizing things either way.

**Comment by yuyichao** [comment]
Also ref https://github.com/JuliaLang/julia/issues/12919. IMHO the right fix is to deprecate the generic multi argument `push!` (and possibly define one for `AbstractArray`). Then make `append!` works for `Set` (or if there's a better function for pushing a sequence to a `Set`).

**Comment by simonster** [comment]
`union!` is the Set version of `append!`, since Sets are not ordered. I think @johnmyleswhite and I may have discussed this at some point, but it's possible we want to come up with a better name than `push!` here, since `push!`, like `append!`, seems to imply ordering of elements.

**Comment by johnmyleswhite** [comment]
Yes, I hate the name `push!` for Sets.

**Comment by damiendr** [comment]
Looks like `union!` does what I was trying to do with `push!`.

I'm not so sure about having to remember so many synonyms for the same abstract operation `add items to collection` depending on the collection type. Isn't that what multiple dispatch is for? This seems slightly pedantic at the expense of cognitive load.

BTW `push!` is also the method to add a `Pair` to a `MultiDict`, for instance.

**Comment by toivoh** [comment]
I seem to remember that once upon a time, set members were added with `add` and not `push!`. But I think that the real question is which semantics that we expect `push!` to implement, and which type can support those semantics.

**Comment by johnmyleswhite** [comment]
Yes, @toivoh is right.

The problem, for me, is that `push!` doesn't only mean "add items to collection". It has additional guarantees that got lost.

Going down this route is what makes multiple dispatch so hard to get right with a giant shared namespace: using the same word to mean different things is called punning and is something we discourage, but the meaning of words is vague enough that you don't realize things are puns immediately.

In this case, I think most people would assume that `push!` and `pop!` are inverses (and might want to check that relationship in a generic unit test), but that isn't true of sets, so the test would fail precisely because it's falsely generic. IMO, `push!` achieves generic programming by failing to offer the more specific guarantees you want to offer.

I was totally ok with using `add!` for this more generic concept, but I believe there was a concern that it was a pun with `add!`, which was being used for arrays.

I've come to think human language is a bad example here: our minds think so locally about meaning that it's easy for us to ignore the inconsistencies in our usage of a single word across many contexts. (Cf. the ubiquitous issues we've had with people want us to identity scalars with 1x1 matrices.)

**Comment by damiendr** [comment]
I think it's possible to come up with a list of aspects/interfaces that allow both genericity and specificity, eg:

- mutable
- indexable
- ordered
- associative
- etc.

So for sure there should be `union!` and `pop!` and etc., but there should also be something in the abstract `mutable` aspect that puts things into other things with no other guarantees and no questions asked.

**Comment by KristofferC** [comment]
This is now a MethodError
