### ISSUE TITLE
Precompile cache should be more robust when using multiple Julia's with the same major / minor version

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/julia#13961]
Having v0.4.1 and v0.4 on the same system is no bueno with respect to package precompilation.  I feel that having the lib cache by minor & major version would require the least amount of user intervention (instead of having to update JULIA_PKGDIR path manually).

**Comment by tkelman** [comment]
it already has major and minor. are you asking for patch too? how often are you switching back and forth between 0.4.0 and 0.4.1?

-1 on this, what's next, adding the commit too for devs working on master?

**Comment by jiahao** [comment]
I have to say that the recompilation gets me too when I switch between different builds within the same minor version. I find myself switching between release-0.4 built from source with default options, release-0.4 with the Intel toolchain, when the versions, and 0.4.x official builds, and then kicking myself when I run a test script that plots something with Gadfly and the whole universe gets recached.

I wish there were a good solution to this problem. Versioning the precompilation cache on the patch version doesn't seem like a good idea though, because many users will just build up month after month of v0.4.x folders if they update regularly.

**Comment by tkelman** [comment]
For devs who do a lot of switching back and forth, we should probably just come up with a standard snippet to put in `juliarc` that adds extra info to the default cache path.

**Comment by vchuravy** [comment]
Correct me if I am wrong put adding this to your `~/.juliarc.jl` should do exactly that.

````julia
function set_load_path()
  vers = "v$(VERSION.major).$(VERSION.minor).$(VERSION.patch)"
  Base.LOAD_CACHE_PATH[1] = abspath(Pkg.Dir._pkgroot(),"lib",vers)
end

set_load_path()
````

````
julia> using Compat
INFO: Precompiling module Compat...

$ ls .julia/lib/v0.4.0/
Compat.ji
````

**Comment by jiahao** [comment]
Is it possible to extract at run time what branch a binary was built from? If so then one possibility is to simply name the last part of the cache directory after the branch (e.g. release-0.4, master, cjh/removearpack) rather than the default v0.4 or v0.5.

**Comment by yuyichao** [comment]
`Base.GIT_VERSION_INFO.branch` (for git build)

**Comment by jiahao** [comment]
Awesome. Thanks for the input! I think we can make this a doc issue about being able to customize the precompile cache directory and resolve it as such. Meanwhile I'll give some of these ideas a spin and see how it works for me.

**Comment by vtjnash** [comment]
> Versioning the precompilation cache on the patch version doesn't seem like a good idea though

I thought about this a fair amount when implementing it, and had come up with the following solution sketch that I think could be turned into a complete solution:

Instead of versioning the files at all by various arbitrary criteria such as Julia hashes, treat the entire archive as a single unified immutable LRU cache. The file format actually already essentially supports this (given a julia environment it can tell you whether a file can be loaded into the julia session, independent of the determination of whether it is up-to-date with respect to  the source files).

Expected benefits:
It would be possible to make mixed builds with out-of-date files, potentially helping to alleviate some of the need to restart julia after Pkg.update.
It would be possible to have multiple versions of julia (even just debug/release) using the same cache location fairly seamlessly.
The cache files for unused packages and versions could be automatically gc'd over time

**Comment by jakebolewski** [comment]
Edited to reflect what I really want.  I do not buy that we should not make developers life easier here.  Anything that makes developers lives easier will also make users lives easier, and the implementation more robust.

@vtjnash that idea sounds really interesting.

**Comment by tkelman** [comment]
> Anything that makes developers lives easier will also make users lives easier

By saving one recompilation per package per month? For normal users who only run releases I don't see how this is a big deal. The fact that we never free compiled code is already a major memory hog - I don't want to start having that same level of clutter and consumption on disk to save a few lines in your juliarc.

**Comment by jakebolewski** [comment]
I'm perfectly willing to trade disk space for my time by default, but I don't really want to defend this viewpoint.  Thanks @vchuravy for the snippet, should probably go in the developer documentation.
