### ISSUE TITLE
rand!(arr::BitArray) allocates memory

### ISSUE THREAD

**Issue by jwmerrill** [JuliaLang/julia#14006]
``` julia
julia> function benchmark(n)
         arr = BitArray(10, 10)
         for i in 1:n
           rand!(arr)
         end
       end

julia> benchmark(100)

julia> @time benchmark(100)
  0.000038 seconds (407 allocations: 15.938 KB)
julia> @time benchmark(1000)
  0.000269 seconds (4.01 k allocations: 156.563 KB)
julia> @time benchmark(10000)
  0.002620 seconds (40.01 k allocations: 1.526 MB)
julia> @time benchmark(100000)
  0.027045 seconds (400.01 k allocations: 15.259 MB, 32.85% gc time)
```

Here's my versioninfo:

```
julia> versioninfo()
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by simonster** [comment]
So does `rand!(::Vector{Int64})`. The culprit is the various `pointer_to_array` calls in `random.jl`, e.g. [here](https://github.com/JuliaLang/julia/blob/ad4e97511f555085d851edc4d9fba9ec81cec9f9/base/random.jl#L426). These allocate something, but at least the amount of allocation is O(1). These allocations could probably be avoided at the cost of making the code uglier...

**Comment by jwmerrill** [comment]
That makes sense. I noticed that `rand!(::Array{Bool})` didn't do any extra allocation and was surprised by the difference.

**Comment by rfourquet** [comment]
There was this PR #9174 almost one year ago, rejected as too "ugly". I proposed a modified [version](https://github.com/JuliaLang/julia/pull/9174#issuecomment-65190888), I might as well open a new PR for it. 
For reference also, it was noted there that filling arrays of `BigInt` can be at least 3 times slower than it could be because of these `pointer_to_array` calls.
