### ISSUE TITLE
Fall back to sys.ji if sys.dll is deleted

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/julia#14019]
It would be good if Julia could automatically fall back to using sys.ji if sys.dll is deleted. Because  `build_sysimg` do not generate a new sys.dll when no linker is found. To get the code changes the sys.dll needs to be deleted and it will cause Julia to error as:
```
ERROR: system image file "C:\Users\Hoegh\Julia-0.5.0-dev\lib\julia\sys.dll" not found
```
Julia can be started using the new `sys.ji` by giving the sysimg to Julia as `julia -J ..\lib\julia\sys.ji`.

**Comment by tkelman** [comment]
By the time we switch to a newer LLVM, LLD might be mature enough that we could just ship it.

**Comment by uozden** [comment]
Dear @dhoegh @tkelman  I cannot start Julia, which gives following error. I am using Julia 0.4.3 on Windows 10.  Your kind help will be appreciated. Thank you. 
```ERROR: system image file "C:\Users\......\AppData\Local\Julia-0.4.3\bin\lib\julia\sys.dll" not found````

**Comment by tkelman** [comment]
@uozden please use the [julia-users](https://groups.google.com/forum/#!forum/julia-users) mailing list for questions.

I think the `-J` flag is the only clean way to accomplish this original issue since the path to `sys.dll` is hard-coded into the binary as `JL_SYSTEM_IMAGE_PATH`, and the only place it's used is for the default value of that option when no `-J` is given. Writing a fallback in `src/init.c` that checks if the hardcoded file is present and tries a `.ji` fallback if not would be more complicated than just using the `-J` flag.

**Comment by vtjnash** [comment]
yeah, we're not planning on reverting to this auto-detection behavior. it's going to be assumed that if you plan on building code that you can get access to the system linker. Julia's incremental linker should handle the use cases previously explored in userimg.jl

**Comment by ranieribt** [comment]
Well, at Windows 7, the error:

`ERROR: system image file "C:\Users\[login]\AppData\Local\Julia-0.4.5\bin\lib\julia\sys.dll" not found``

Occured to me after I've created the JULIA_HOME environment variable set to

`C:\Users\[login]\AppData\Local\Julia-0.4.5\bin`

When I've deleted the JULIA_HOME variable the Julia's shell was started normally.

Hope it helps =)
