### ISSUE TITLE
cholfact(Sparse matrix) ERROR: UndefVarError: commonStruct not defined

### ISSUE THREAD

**Issue by KimNganLe** [JuliaLang/julia#14023]
Hello, 
There is an error when cholfact comment is tested.

julia> A=sprand(5,5,.1)
5x5 sparse matrix with 3 Float64 entries:
        [1, 1]  =  0.0641921
        [2, 2]  =  0.803508
        [3, 5]  =  0.509073

julia> B=A'*A
5x5 sparse matrix with 3 Float64 entries:
        [1, 1]  =  0.00412063
        [2, 2]  =  0.645625
        [5, 5]  =  0.259155

julia> F=cholfact(B)
ERROR: UndefVarError: commonStruct not defined
 in allocate_sparse at sparse/cholmod.jl:433
 in convert at sparse/cholmod.jl:842
 in cholfact at sparse/cholmod.jl:1238

julia> versioninfo()
Julia Version 0.4.1
Commit cbe1bee (2015-11-08 10:33 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

Best,
KNL

**Comment by nalimilan** [comment]
This usually happens when you're using a incorrect version of SuiteSparse/libcholmod, either because it's too old, or because the version changed since you build Julia. How did you get Julia, and what's the SuiteSparse version?

(The error message should definitely be improved, cf. https://github.com/JuliaLang/julia/issues/12841)

**Comment by KimNganLe** [comment]
Thanks nalimilan. 
I have updated the version of Cholmod, then the issue is resolved now.

Best,
KNL

**Comment by nalimilan** [comment]
Good to know!
