### ISSUE TITLE
Document numeric conversions

### ISSUE THREAD

**Issue by ArchRobison** [JuliaLang/julia#14031]
It seems that the Julia documentation does not cover numeric conversions.  I think the subject deserves mention as a section of  [Mathematical Operations and Elementary Functions](http://docs.julialang.org/en/latest/manual/mathematical-operations/), with cross references between it and the [Conversion and Promotion](http://docs.julialang.org/en/latest/manual/conversion-and-promotion/) chapter.  

How many forms should it cover?  The three forms I find myself using are:
- Int(x) - checked for exactness, i.e. value preserving
- x % Int - modular, restricted to integer types
- floor( Int, x ) - checked for exactness after flooring (and is documented)

I would describe the three forms and their tradeoffs.  Any others worth documenting in said section of the manual?

**Comment by simonbyrne** [comment]
There is also `convert`, but I'm not sure what the distinction is between `T(x)` and `convert(T,x)`?

**Comment by simonbyrne** [comment]
Also, `unsafe_trunc`.

**Comment by swt30** [comment]
There's also the safe form `trunc` which checks that it's representable in the new type.

`T(x)` calls the constructor for type T with value x. If a constructor isn't defined, it falls back to `convert(T, x)` as of version 0.4, which means you can write things like `Float32(1)`, which is nice and compact. I'm not really sure what to write for custom types though (numeric or otherwise). Do I define 

- the constructor `T(x)`? 
- the function `call(::Type{T}, x)`? 
- or `convert(::Type{T}, x)`?

**Comment by simonbyrne** [comment]
The first 2 are actually the same (the `call` function was a design hack to get inability to define constructors for bits types: this may change in future).

I would suggest defining `convert`, but this is a good question.

**Comment by brenhinkeller** [comment]
Looks like the current (1.8.3) section on [Mathematical Operations and Elementary Functions](https://docs.julialang.org/en/v1/manual/mathematical-operations/) has a whole subsection on [Numerical Conversions](https://docs.julialang.org/en/v1/manual/mathematical-operations/#Numerical-Conversions), so I think we can consider this completed!
