### ISSUE TITLE
zero sparse vector error

### ISSUE THREAD

**Issue by augustinyiptong** [JuliaLang/julia#14046]
Hi,

I am getting this error with Julia Version 0.5.0-dev+1158

v = sparsevec(zeros(10))
v + v

LoadError: MethodError: `convert` has no method matching convert(::Type{SparseVector{Tv,Ti<:Integer}}, ::Type{Float64}, ::Int64)
This may have arisen from a call to the constructor SparseVector{Tv,Ti<:Integer}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{Tv,Ti}(::Type{SparseVector{Tv,Ti<:Integer}}, !Matched::SparseMatrixCSC{Tv,Ti})
  convert{Tv}(::Type{SparseVector{Tv,Ti<:Integer}}, !Matched::AbstractArray{Tv,1})
  ...
while loading In[133], in expression starting on line 2

 in _binarymap at sparse/sparsevector.jl:815
 in + at sparse/sparsevector.jl:1051
 [inlined code] from essentials.jl:114

There is no error in Julia 0.4.0

Thanks, Gus

**Comment by tkelman** [comment]
Good catch, that line isn't right at all - https://github.com/JuliaLang/julia/blob/ea2ab73bddb2071f8c8f69d5ea5a7770e53647f1/base/sparse/sparsevector.jl#L848

Though it's also an issue in the original SparseVectors.jl code, ref https://github.com/JuliaSparse/SparseVectors.jl/blob/b7217cdab8e9ba3f3a3f13beb5ed6c8e12987a25/src/math.jl#L113 and should also be raised there for anyone using this code on 0.4 and earlier.

Definitely a missing test case. Should be easy enough to fix, should be something like `SparseVector(n, Int[], R[])` instead of `SparseVector(R, 0)`.

**Comment by mbauman** [comment]
I think that line should just be removed. Changing the constructor to do what was intended means that `spzeros(5)+sprand(5, 1.0) --> spzeros(0)`, which isn't right, either.

**Comment by tkelman** [comment]
You're right, I was reading that line as if it started with `(mx == 0 && my == 0)` rather than `(mx == 0 || my == 0)`
