### ISSUE TITLE
Document capture of stdout/stderr from external command

### ISSUE THREAD

**Issue by damiendr** [JuliaLang/julia#14042]
A manual section on how to capture stdout/stderr from an external command into a string would be nice, eg. in:
http://julia.readthedocs.org/en/latest/manual/running-external-programs/

**Comment by damiendr** [comment]
Use cases:
- how do I pass stdout/stderr through to STDOUT/STDERR?
- how do I silence stdout/stderr?
- how do I capture stdout/stderr into a buffer or string?
- (for all of those) ... and write to stdin?

**Comment by josefsachsconning** [comment]
How about the return code as well (please)?

**Comment by sbromberger** [comment]
Does this help?

```
julia> origstdout = STDOUT
Base.TTY(open, 0 bytes waiting)

julia> (outread, outwrite) = redirect_stdout()
(Base.PipeEndpoint(open, 0 bytes waiting),Base.PipeEndpoint(open, 0 bytes waiting))

julia> r = `echo "foo"`
`echo foo`

julia> run(r)

julia> readline(outread)
"\e]133;C\a\e]133;C\a\e]133;C\afoo\n"

julia> redirect_stdout(origstdout)
Base.TTY(open, 0 bytes waiting)
```

**Comment by fingolfin** [comment]
It would be really good to take care of this. I know at least two ways to achieve this, but only by asking / folklore; the documentation alone would have *never* allowed me to figure this out.

Perhaps it helps, here is the code that works for me. It also grabs the exit code, which is of course yet another thing that would be nice to cover -- `ignorestatus` is not currently mentioned on  <https://docs.julialang.org/en/v1/manual/running-external-programs/>.

Method 1 works in all Julia version >= 1.0:
```
function execute(cmd::Base.Cmd)
    out = Pipe()
    err = Pipe()
    process = run(pipeline(ignorestatus(cmd), stdout = out, stderr = err))
    close(out.in)
    close(err.in)
    return (stdout = String(read(out)),
            stderr = String(read(err)),
            code = process.exitcode)
end
```

Method 2 works in Julia >= 1.0 and was suggested to me by @pfitzseb on Slack (thanks); the version of it here is due to me, so mistakes are mine
```julia
function execute(cmd::Base.Cmd)
    out = IOBuffer()
    err = IOBuffer()
    process = run(pipeline(ignorestatus(cmd), stdout=out, stderr=err))
    return (stdout = String(take!(out)),
            stderr = String(take!(err)),
            code = process.exitcode)
end
```
