### ISSUE TITLE
Builtins returning signed integers

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#14137]
I was looking into a codegen difference (ccall using `Cstring` vs `Ptr{UInt8}`, based on a comment on #14024) and one of the differences was a check + branch throwing `jl_inexact_exception` when converting the string. Turns out the underlying cause is `jl_f_sizeof` returning a signed rather than an unsigned integer.

In C, `sizeof` returns an unsigned `size_t`. I assume this makes sense in Julia as well, and it should get rid of at least some checked conversions (completely unscientific gut feeling). In case of my micro-benchmark with `Cstring`s, overhead dropped from ~10% to ~8%.

Does it make sense to explore this further, or are there existential issues I'm not seeing? An initial `testall` yielded many failures, but most were signature mismatches which should be trivial to fix. A bigger problem seems to be that `jl_datatype_t.size` is signed.

**Comment by yuyichao** [comment]
IIUC, the initial problem with unsigned integers (they make everything unsigned) might not be relavant anymore. However, changing that will cause a very big breakage and performance regressions due to type instability that is very hard to track down and fix completely. The check was in the convert to `Csize_t` and adding a `% Csize_t` in `containsnul` should get rid of the bounds check.

**Comment by maleadt** [comment]
Yeah, it seems to break quite a lot :-) Just getting rid of the signedness seemed too much like an ad-hoc fix while there might be other optimization opportunities, but you're probably right that the fallout would be massive. I'll have a look at assessing the performance gains, if any.

**Comment by stevengj** [comment]
The decision was made a long time ago in Julia to make all `length`-like quantities (`sizeof`, `size`, etcetera)` signed (`Int`) rather than unsigned (`UInt`).  The extra bit of range makes no practical difference on 64-bit architectures, and arithmetic on unsigned integers just has way too many unexpected properties.

So, I don't think this is likely to change.

**Comment by JeffBezanson** [comment]
Agreed; it's way better to have a single default integer type that is as unsurprising as possible (`Int`!).

**Comment by maleadt** [comment]
Yeah I understand. Sorry for leaving it open, I was trying to get some accurate performance numbers on how the change affects base, but that turns out to be surprisingly difficult (but that's another issue).
