### ISSUE TITLE
julia_init crash embedding app on windows and gcc tool-chain

### ISSUE THREAD

**Issue by armgong** [JuliaLang/julia#14163]
when try to slove  https://github.com/armgong/rjulia/issues/23 found some interesting things.

when use julia 0.4.1 download from julialang.org ,and compile rjulia use msys2+mingwbuild 4.92 rev3, it will crash R.

but when use julia 0.4.1 compile by myself  use msys2+mingwbuild 4.92 rev3 and rjulia , everything is ok.

the only difference maybe gcc tool-chain, 

I use mingw-build   download from sourceforge

gcc version 4.9.2 (x86_64-win32-seh-rev3, Built by MinGW-W64 project)  
Thread model: win32

but julialang.org use gcc tool-chain download from get_toolchain.sh

http://download.opensuse.org/

maybe the toolchain lead this issue? could anyone verify this issue?

@twadleigh @tkelman @waTeim @nalimilan @vtjnash

**Comment by tkelman** [comment]
The release binaries are actually cross-compiled from Cygwin. They should be ABI compatible with the opensuse toolchain, and if you'd like to build from inside MSYS2 then you should do so using the opensuse toolchain.

**Comment by armgong** [comment]
Things became more and more complicated, most R user on windows will use Rtools ,  so there will another toolchain.

**Comment by tkelman** [comment]
Yes, ABI incompatibilities are annoying. It would be worth trying to convince the Rtools maintainers to try to adjust their toolchain build configuration to try to get things to be ABI compatible with Cygwin and Linux cross-compilers. I think we might be ABI compatible with the MSYS2 toolchain on 64 bit at the moment, but I'm not positive.

**Comment by waTeim** [comment]
Oh ouch, something changed?  Ok I can work to confirm or not.  I find that julialang.dll should be ABI compatible across all of this stuff because you know it's C, not C++.  And if this succeeds or fails (depending) we can add in yet another toolchain MSVCC -- this should (has been) working all this time, so, this is worrisome.

**Comment by waTeim** [comment]
Ok a short update, which will be updated later.  I am compiling 0.5 using MSYS2, and am getting hit by #13206.  As an aside, integration between node 4.x and julia 4.x and julia 5.x works, but only on Yosemite (haven't tried El Capitan yet, but should also work), but fails on Mavericks which is unfortunate because of Travis.  I feel this has happen only lately, does @staticfloat have any info on change to maybe Xcode 7 and/or Yosemite for Julia build lately (month or so)?  On Linux everything is good.

**Comment by armgong** [comment]
unfortunately, compile rjulia use  opensuse toolchain still crash. so status is:

 julia version                                     rjulia                     result

download from julialang               mingw-builds             fail
download from julialang           opensuse toolchain       fail
download from julialang           rtools                             fail
compile with mingw-builds        mingw-builds                ok
compile with mingw-builds        opensuse toolchain      ok
compile with mingw-builds        rtools                            need to be done

when combine R and julia, Could we say mingw-builds on windows is better then cross-compile and opensuse toolchain???

**Comment by tkelman** [comment]
Try using any WinRPM package like ZMQ, Cbc, etc and I suspect it won't work with mingw-builds. We're not about to change the toolchain the binaries use.

**Comment by waTeim** [comment]
As a workaround I simply downloaded and installed Julia 0.4.1 and Julia 0.5-dev+1464, and used the build defined by [binding.gyp](https://github.com/waTeim/node-julia/blob/master/binding.gyp), which causes [node-gyp](https://github.com/nodejs/node-gyp), to invoke Visual C++ provided by [Visual Studio Community 2015](https://www.visualstudio.com/en-us/visual-studio-homepage-vs.aspx).  Some or all of these may prove relevant.  I found no errors in the build or in the subsequent tests.  However I did find a couple of interesting problems with 0.5-dev itself.  I will update this comment with those results

**Comment by tkelman** [comment]
I didn't notice your 3rd bullet about running Julia inside MSYS2. See https://groups.google.com/d/msg/julia-users/tCfrhMWBEwk/K4-nde_1BQAJ for the same issue in Cygwin. This is because we upgraded the embedded git version for 0.4.1, and git 2.x on Windows is now using a forked, incompatible version of MSYS2. You can comment out everything in `etc/julia/juliarc.jl` as a workaround for that.

**Comment by waTeim** [comment]
This looks like it fixes itto fix it

    $(VIRTUALENV_TARGET): $(VIRTUALENV_SOURCE)
            "$(shell $(SRCDIR)/find_python2)" $< $@
    ifeq ($(BUILD_OS), WINNT)
        -[ -e $@/Scripts ] && ! [ -e $@/bin ] && cmd //C mklink //J `echo $@/bin $@/Scripts | sed -e s/\\\\//\\\\\\\\/g`
    endif
            touch -c $@

**Comment by waTeim** [comment]
oops wrong issue

**Comment by tkelman** [comment]
Everything here is outdated, we've updated the toolchain versions a few times. Leave a new comment and we can reopen, or open a new issue, if there are still problems here.
