### ISSUE TITLE
Want to use `end` in `sub(...)`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14169]
As far as I can tell, `sub(...)` (which creates sub-array views) accepts a index arguments indices, ranges, and colons. It would be quite convenient if it also accepted `end`. This would allow writing e.g.
```Julia
a[1:end-1] = sub(a, 2:end)
b[2:end] = sub(b, 1:end-1)
```

If getting this to work with `end` is too complex for the parser then I wouldn't mind using a different syntax, e.g. `:end` or `:End`. Or maybe with a completely different syntax such as `SubArray[a, 2:end]`, or `@sub(a[2:end])`.

**Comment by yuyichao** [comment]
I don't think we can reasonably support this in the parser. Just use `endof`.

**Comment by eschnett** [comment]
Well, `endof` (or rather `size`) leads to length and unreadable expressions... Here's a real-world case:
```Julia
a[1, 2:end-1, 2:end-1] = sub(a, sizeof(a,1)-1, 2:sizeof(a,2)-1, 2:sizeof(a,3)-1)
```

**Comment by yuyichao** [comment]
When you have a function call rather than a indexing expression, it's not clear which argument do you want to apply `endof` to.

Treating one of the argument differently from the other ones is a really bad idea if they are otherwise identical. If the syntax to call `sub(a, ...)` is `a.sub(...)`, it would make sense to add syntax suger for applying certain functions on `a`.

**Comment by eschnett** [comment]
@yuyichao The expression `a[end]` is translated to `getindex(a, :end)`. Here, `:end` is a symbol (not a range). Apart from the problem of parsing the `end` keyword, the expression `sub(a, end)` could similarly be translated to `sub(a, :end)`.

**Comment by yuyichao** [comment]
> The expression `a[end]` is translated to `getindex(a, :end)`

No it's not.

```jl
julia> :(a[end])
:(a[end])

julia> expand(:(a[end]))
:(getindex(a,(top(endof))(a)))

julia> getindex([1, 2], :end)
ERROR: indexing Array{Int64,1} with types Tuple{Symbol} is not supported
 in getindex at ./abstractarray.jl:483
```

It's also not only about the object to be indexed, but also the dimension you want to index. I don't think there's a easy way to see which dimension each of them should correspond to.

Using a `:end` for indexing doesn't make any sense and doesn't require any special change to the parser. You can't do any arithmetics on it, can't construct a range with it. And you can get it simply using `:end`.

**Comment by yuyichao** [comment]
Just to be clear, `end` is indeed a symbol in the surface AST of `a[end]`. This is allowed in the parser because it has an unambiguous meaning (as for which object and dimension it corresponds to) and we support this usage by lowering it to a function call of `endof`.

You can already construct AST with `end` symbol in it (try `Expr(:call, :sub, :a, :end)`) but it doesn't get any special treatment in lowering and execution because there isn't a sane way to consistently interpret it.

**Comment by Rory-Finnegan** [comment]
I ran into the same issue today, so I know where you're coming from @eschnett. @yuyichao based on your comments I can understand why `end` isn't likely to be supported for `sub`, but then it seems like the reasonable solution is to remove support for `end` in `getindex` (and probably also `setindex!`) in order to make things consistent.

**Comment by eschnett** [comment]
I see. I didn't know that `end` was lowered in `expand`; I assumed that `end` was treated like `:`, which remains a symbol and needs to be handled explicitly in `getindex`. Of course, in `getindex` it's clear which array this is about, and what the value of `end` should be.

My idea was -- apart from the parsing issue -- to allow `end` (or something equivalent) generically, not only in `ref` expressions, and then handle it via the type system (in a generated function) in a simple extension to the way colon is handled.

**Comment by yuyichao** [comment]
>  the reasonable solution is to remove support for end in getindex (and probably also setindex!) in order to make things consistent.

No. There's not special support for `end` in `getindex` and `setindex!`. They are just normal functions. The special support in parsing and lowering of indexing. And it's not much more special than allowing `[]` as a syntax for indexing itself.

> to allow end (or something equivalent) generically, not only in ref expressions

You are still missing the point though. Because

> You can't do any arithmetics on it, can't construct a range with it.

is why you can't do that. If you want to have consistent support for `end` in indexing without functional regression, you will need to support using `end` in arbitrary expressions while still make sure type inference can look through the expression and figure out what you actually want to do. Not to metion it will take much longer time to compile and likely much more useless code generation. That's basically something nearly impossible to do and almost certainly not worth the effort since you could just do exactly the same now with just a little more typing.

**Comment by eschnett** [comment]
Here's an idea: The syntax
```Julia
sub(a)[2, :, 3:end-4]
```
should work fine, and address all your concerns.

**Comment by yuyichao** [comment]
That will still cause 2x allocation but sounds fine for me otherwise. Not sure how people feel about the inconsistency between `size(sub(a)[1, :])` and `size(a[1, :])` if they are both indexing.

**Comment by eschnett** [comment]
It doesn't cause a second allocation if `sub(a)` returns a new immutable type that handles the `getindex`, which then returns a `SubArray`.

I don't know what you mean by "inconsistency" -- `size(sub(a)[1, :])` === `size(sub(a, 1, :))`?

**Comment by yuyichao** [comment]
> It doesn't cause a second allocation if `sub(a)` returns a new immutable type that handles the `getindex`, which then returns a `SubArray`.

Yes, I know that's what you meant and yes it does allocate. Non-`isbits` immutable types are (currently) heap allocated.

> I don't know what you mean by "inconsistency" -- `size(sub(a)[1, :])` === `size(sub(a, 1, :))`?

AFAIK, for base types, it is always consistent whether scalar indexing drops the dimension. If we allow what you suggested here, that will not be true anymore since indexing of `a` will drop scalar dimensions while indexing of `sub(a)` will not.

**Comment by nalimilan** [comment]
@eschnett Since array views are going to be the default in 0.5, will you still need to use `sub` instead of `[]`?

**Comment by eschnett** [comment]
@nalimilan I'm looking for a simpler syntax to write `2:end-1` without making a copy. If that's available via the regular syntax I'll be quite happy. Thanks!
