### ISSUE TITLE
whos() considerably slow

### ISSUE THREAD

**Issue by hyiltiz** [JuliaLang/julia#14173]
julia> @time whos()
                          Base  24573 KB     Module : Base
                          Core   3043 KB     Module : Core
                          Main 808579 KB     Module : Main
                           ans      0 bytes  Void : nothing
                             x 781250 KB     10000x10000 Array{Float64,2} : [0.2345839889343943…
                            α̂₂      8 bytes  Int64 : 2
203.371041 seconds (1.58 G allocations: 34.022 GB, 4.22% gc time)

**Comment by andreasnoack** [comment]
That is really bad. The problem is mainly [this line](https://github.com/JuliaLang/julia/blob/1b850c7e96f49358c6c1ede257f9e8e8724c93ba/base/interactiveutil.jl#L454) which prints the object. Unfortunately, it prints all the values of the array, which takes quite long time because your array is large. It shouldn't print all the values, but instead do something like we are doing when printing an array in the REPL, but our array printing code is really convoluted, so I'm not sure there is an easy fix.

Hopefully https://github.com/JuliaLang/julia/issues/14052 will be a long term fix for easier array printing, but I'm not sure it is worth the trouble to print the objects in `whos`. It is mainly their size and type that are interesting.

**Comment by Keno** [comment]
Wouldn't replacing that line with `showcompact` be sufficient?

**Comment by hyiltiz** [comment]
I am fairly new to Julia, and am really fascinated by it. All I did was `x = rand(1000,1000)` and a call to `whos()`. But I really do not expect to wait about a minute to find out about my workspace. I am not sure what needs to be done, but definitely not trying to print implicitly or explicitly the variables in the workspace.

**Comment by andreasnoack** [comment]
Unfortunately, `showcompact` won't work. It also prints all the values of the array and I think it ends up calling the same method. The more efficient printing in the REPL completely bypasses `show` and `showcompact` using `writemime` and `showarray`. The reasons for the two different paths for array printing are a bit of a mystery because I don't think it's ever a good idea to fetch all the values of big arrays. For `DArray` this would probably make the system hang forever.

**Comment by hyiltiz** [comment]
@andreasnoack So is that a feature to come in a future release?

**Comment by andreasnoack** [comment]
@hyiltiz The fix in #14177 should be possible to backport. The more general refactoring of the printing functions is for future releases.

**Comment by hyiltiz** [comment]
I really liked the current behavior (printing head and tail of a big matrix) of the printing function. I hope #14177 does not change that. Instead, `whos()` only needs to represent properties of the variables in the namespace. So, instead of showing everything, a (maybe hardcoded) `head -n 5` could be enough as far as `whos()` functionality is concerned.

**Comment by JeffBezanson** [comment]
We should not be trying to show whole values during `whos`. We should use something like `summary`.

**Comment by andreasnoack** [comment]
@JeffBezanson That is also what I've ended up doing in #14177.
