### ISSUE TITLE
Performance improvements with text processing

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#14196]
I don't have time to make this a PR right now, so this is just a placeholder so it doesn't get lost: see https://groups.google.com/d/msg/julia-users/2uaRs3JIdfw/hMLdj6wxCwAJ. The most important change was making the string encoding a type parameter of what is effectively `EachLine`, and then using that in downstream code to prevent type instability.

Without this, on the "Hungarian Wikipedia" test data set (see https://github.com/juditacs/wordcount), some lines come back as `UTF8String` and some as `ASCIIString`. Might as well keep it consistent.

**Comment by JeffBezanson** [comment]
ref #1792

**Comment by nalimilan** [comment]
Looks like this is another issue which will get fixed by merging `ASCIIString` and `UTF8String` into a single `String` type (https://github.com/JuliaLang/julia/pull/14383), which should get rid of type instability in `EachLine`.

@timholy What other lessons to you draw from that thread regarding thread processing? I must say it's not immediately obvious to me.

**Comment by timholy** [comment]
Thanks for the reminder. I have a grant deadline of Wednesday, after which I'll try to remember to come back to this.

**Comment by nalimilan** [comment]
No worries. I was just trying to link related issues together.

**Comment by timholy** [comment]
Fixed by the strings changes.
