### ISSUE TITLE
Distributing precompiled packages

### ISSUE THREAD

**Issue by MikeInnes** [JuliaLang/julia#14193]
Right now Juno's first boot takes a _long_ time, as does compiling Gadfly etc. for the first time. It would be great if we could distribute the precompiled code along with the source in order to speed up this first run. I think when I tried this the cache was treated as stale – perhaps there's a way to work around this?

**Comment by tkelman** [comment]
Could try writing a post-install script that cheats and modifies the header of the .ji files to match the installed package source paths and modification times.

**Comment by ViralBShah** [comment]
+1

**Comment by tkelman** [comment]
And/or switch from saving a timestamp to a hash.

**Comment by wbhart** [comment]
If you switch to a hash could you please consider having the hash function ignore blank lines and comments.

Precompilation slowing our dev cycle is now by far the number one issue we are having with Julia. Ideally we'd like precompilation to only happen for the files that have changed (if that's even feasible). 14-60s recompile every time we even change a comment is just killing us.

**Comment by jakebolewski** [comment]
@wbhart you can use `--compilecache=no` to turn off precompilation.  Doesn't solve the fundamental problem you are talking about, but may be faster when developing packages.

**Comment by wbhart** [comment]
@jakebolewski We are aware of this possibility, and indeed it makes about 50% difference in the delays (with an increasing difference as our packages get larger). But clearly it's eventually going to be necessary for Julia to track dependencies in precompilation somehow.

**Comment by tkelman** [comment]
Split your code into multiple modules. A Julia-parser-aware hash seems like it would be more expensive than a standard hash of the data.

**Comment by ScottPJones** [comment]
I have a suggestion about using hashes (and it's nice that people are now coming around to the idea of using hashing instead of timestamps), that would help the issue @wbhart brought up.
Have two hashes in the header (at fixed locations in the header - maybe both 64-bit).
The first hash would be on the text of the file.  If it is identical, then accept the cached version.
If not, then the file would be parsed, to whatever the first pass is (lowered?) which should eliminate non-important differences - [might have to ignore line no. information for the hash], and that would be hashed.
If that hash matches the second stored hash, then the first hash is updated in place in the cache file, and the cached version is used.

**Comment by ScottPJones** [comment]
On second thought, the second hash might not be able to ignore line number changes, since that would mess up stack backtrace / debugging info, or the new macros that give file & line number info, but it would at least handle changes to comments.

**Comment by wbhart** [comment]
@tkelman Currently we have a submodule called Nemo.Test. Making any changes to it still triggers a recompile for everything. So it looks like submodules don't help.

Separate modules is a theoretical possibility I suppose, but ultimately we need the user to be able to do "using Nemo" and get all symbols from all the separate modules. I tried to make this work a long time ago, and I couldn't figure out how to do so.

**Comment by ScottPJones** [comment]
@wbhart We've run into that same problem, constant recompilation, even with things divvied up into many different modules, because of any change to a submodule making everything recompile. We also will need to be able to distribute precompiled packages.

**Comment by samoconnor** [comment]
+1 to @tkelman's [suggestion](https://github.com/JuliaLang/julia/issues/14193#issuecomment-160773768) of using a hash instead of (path, timestamp)

I have been working on cleaning up [AWSLambda.jl](https://github.com/samoconnor/AWSLambda.jl) so that creation of new lambda functions is done by a single lambda function call (previously there were multiple passes of creating ZIPs, deploying lambdas, executing recompilation, updating ZIPs with `.ji`s, redeploying etc).

Lambda creation now consists of:
 - Pass ZIP of Julia code and dependancies to base lambda.
 - Base lambda unzips to /tmp (everything else is read-only).
 - precompilation creates `.ji` files under /tmp.
 - A new ZIP is created combining the base lambda image and the new files under /tmp.
 - The new ZIP is passed to the Lambda CreateFunction api to create the new lambda.

When the new lambda runs it treats the `.ji` files as stale because they refer to `/tmp/var/task/ModFoo.jl` and not `/var/task/ModFoo.jl`.

My work-around is to disable the path/timestamp check:  https://github.com/samoconnor/AWSLambda.jl/commit/6e37fcbfbe4edc5dcdb2a15d1f6a21056fc5fd7c

I suggest replacing the path/time check with a fast non-cryptographic hash. e.g. https://github.com/samoconnor/FNVHash.jl

(Note that FNV is defined for 32, 64, 128, ... 1024 bits. But for this application 32-bits is should be enough.)

**Comment by ViralBShah** [comment]
The way our precompilation works, this can't be done as part of package distribution. However, since we have now moved precompilation to happen during installation, and we have PackageCompiler - this particular issue can be closed.
