### ISSUE TITLE
Should `div(typemin(Int), -1` throw `OverflowError` instead of `DivideError`?

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14273]
Currently, `div(typemin(Int), -1` throws a `DivideError`. Should it throw an `OverflowError` instead? Arguably, there's nothing wrong per se in dividing by `-1`; it's just that the type `Int` can't hold the result.

**Comment by JeffBezanson** [comment]
I suspect this came from a desire to minimize the amount of code generated for `div`. I agree an OverflowError makes more sense, but our `div` is already painfully slow so we'd have to carefully check the performance and code size impact.

**Comment by oscardssmith** [comment]
Closing as won'tfix for performance reasons.

**Comment by BioTurboNick** [comment]
Figured I'd post a response here too, from Slack - LLVM defines division by zero and typemin(Int) by -1 to be undefined behavior, so Julia couldn't just rely on an LLVM intrinsic to implement this.

That said, in implementing this for OverflowContexts.jl, the branching required doesn't seem to hit performance much because integer division is so slow anyway.

But, the existing Julia API is that division is checked by default, and there is probably code relying on this behavior, so that would be a breaking change and introduce silently wrong arithemetic into existing code if it were to be done. Very bad :-)

**Comment by thchr** [comment]
From more chatting Slack: it is in fact documented that this case will throw - and so, I suppose, technically breaking to change it: https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/#Division-errors.

On the other hand, it is odd that we use non-throwing, modular arithmetic for addition, subtraction, and multiplication of `Int`s, but not for division (aside from division by zero; that makes sense).
