### ISSUE TITLE
Collecting optional args: BREAKING changes in 0.4.2

### ISSUE THREAD

**Issue by multidis** [JuliaLang/julia#14371]
Previously (v0.3), to collect optional arguments in a dictionary, I used:

    Dict(zip(optargs...)...)

After 0.4 release, in response to this warning:

> WARNING: Dict{K,V}(ks::Tuple{Vararg{K}},vs::Tuple{Vararg{V}}) is deprecated, use Dict{K,V}(zip(ks,vs)) instead.

I started using

    Dict{Symbol,Any}(zip(opta))

which was working in 0.4.1. However, with 0.4.2, the following error happens:

    fopt(x::Float64; optargs...) = optargs
    opta = fopt(2.0, z=true)
    Dict{Symbol,Any}(zip(opta))

>ERROR: BoundsError: attempt to access ((:z,true),)
  at index [2]
 in call at dict.jl:390

**Comment by nalimilan** [comment]
Yes, that's an unfortunate side-effect of fixing https://github.com/JuliaLang/julia/issues/13979. I'm not sure what's the best solution here. Clearly, you relied on a bug introduced in 0.4.0, and fixed in 0.4.2. But fixing bugs can indeed break existing code. Maybe we shouldn't have backported it.

Anyway, the best code in all cases is to replace `Dict{Symbol,Any}(zip(opta))` with `Dict{Symbol,Any}(opta)`. I'm not sure why you called `zip` at all...

**Comment by multidis** [comment]
`Dict{Symbol,Any}(opta)` works, thanks. The reason I called `zip` to begin with was related to the warning text. No need for it in this case indeed.
