### ISSUE TITLE
StackOverflow on `@sprintf("%a", big"42")`

### ISSUE THREAD

**Issue by mason-bially** [JuliaLang/julia#14409]
While writing coverage tests for printf I encountered this bug. Only %a combined with BigInts seem to be problematic.

```julia
@sprintf("%a", big"42")
```

It seems related to `BigInt`s. I'm still new to Julia and am not quite sure how to go about fixing this error or I would do it myself. My coverage tests will include this case/issue commented out.

**Comment by ivarne** [comment]
Great to see that writing tests catches StackOverflows in Julia. What output would you expect? 

It is not obvious to me how a Hexadecimal floating point representation of a BigInt would look like, except for just doing a potentially lossy conversion to an arbitrary FloatingPoint precicion. Generally we seem to prefer having the user explicitly ask for lossy conversions. Maybe a friendly exception is the right solution?

**Comment by ScottPJones** [comment]
Even C/C++ compilers give warnings these days about mismatches between the *printf format string and the arguments.
I agree with @ivarne, a "friendly" exception would be the best way to handle this.

**Comment by simonbyrne** [comment]
Here are 3 possible options:
1. Throw an error (well, a more informative one than we do now).
2. Convert to a `BigFloat` (other integers are also converted to `float`: the problem here is that the branch to handle `BigFloat`s occurs before this conversion).
3. Actually implement this properly (for all integer types).

Option 3 is a little bit tricky, but is actually well-defined (find the leading significant bit, and go from there). Whatever we do, we should make it consistent across all integer types.

**Comment by ivarne** [comment]
With three options, it isn't an intro issue.

**Comment by ScottPJones** [comment]
Would you set the precision temporarily of the `BigFloat`, to make sure it is large enough to hold the `BigInt` without loss, for option 2?

**Comment by simonbyrne** [comment]
That's one option, but it should be possible to avoid doing that.

**Comment by mason-bially** [comment]
I was actually sort of thinking about rewriting the printf library from scratch. See #14331 .

**Comment by simonbyrne** [comment]
That would be awesome! Do ping feel free to ping me if you have any questions, I'm more than happy to help with that.

**Comment by StefanKarpinski** [comment]
I'm also more than happy to help.

**Comment by mason-bially** [comment]
My goal would probably be by the end of the year.

**Comment by StefanKarpinski** [comment]
Ditto for early design and/or code review.

**Comment by simonbyrne** [comment]
Actually, an even easier way to do this would be to print the hex integer (`"%x"`), prefixing with `0x` and suffix with `p0`. The only problem would be moving the sign to before `0x`.

**Comment by mason-bially** [comment]
Unfortunately shortly after my last comment here, the Julia community demonstrated what I had hoped would not be true after reading [this](http://danluu.com/julialang/). So I put it on pause to think and finally decided not to make it something I contribute to regularly. I'll update my pull request #14410 but other than that I can't justify contributing to a project with a community having systemic problems.

**Comment by nalimilan** [comment]
@mason-bially Could be more explicit about what happened which prompted you to stop contributing to Julia? That post by Dan Luu mentions many different issues, most of which are now solved, and has already generated a lot of heated discussions. If you want to be constructive, please explain your criticism in a detailed message rather than via short allusive comments in GitHub.

**Comment by mason-bially** [comment]
It was the updates in the Dan Luu post that concerned me the most. The specific response is that the person in the Julia community who I most identified with, agreed with, and to whom I have a similar argumentative style was banned. There is no committee or larger community guidelines for recourse, and the decision appeared arbitrary.

I think Julia appears like a great project, and I'll continue to use and evangelize it, but I cannot invest my time in a community where I could be so easily, arbitrarily banned with no recourse.

**Comment by simonbyrne** [comment]
I'm not really sure what the story with Dan is (I'm not one for seeking out drama), but I have to say my personal experience with the community could not have been more different (I did however agree with many of his technical complaints at that point in time).

As to banning, I assure you that a decision of such magnitude is not taken lightly or unilaterally: it is only done after repeated warnings, and with wide consultation and agreement within the community. That said, as the community is growing, it perhaps is time to have some sort of community moderation committee, so that such matters could be handled more transparently in future (though we've been lucky so far that this has been exceedingly rare)

**Comment by mason-bially** [comment]
I witnessed it a few days after joining the community it appeared unilateral to me, and the target was a person whom I identified and agreed with.

It's put me off to a degree that I can no longer consider being part of the community.

**Comment by tkelman** [comment]
We debated whether we should make a public statement about the issue and decided against it at the time, but despite any public appearances I can assure you it wasn't a unilateral decision, made lightly, or without privately consulting with a larger group of contributors. There's also zero connection between that blog post and the events we're referring to.

If you feel uncomfortable participating in the community that's unfortunate and we should work to make sure that doesn't happen.

**Comment by mason-bially** [comment]
I'm saying between the blog post and what I witnessed it paints a picture I don't want to participate in.

**Comment by nalimilan** [comment]
@mason-bially Really, all the fuss Dan Luu makes about the Julia community on his blog appear as an exaggeration to me. It's really unfortunate that it's one of the first posts you find when reading about Julia. We don't have access to private the conversations he talks about. But you can confront what he says about public discussions being rude with the actual contents of the threads, which sound extremely constructive to me: https://groups.google.com/d/msg/julia-users/GyH8nhExY9I/SoSKxSv6HtYJ

It's too bad that you joined the party just 6 days before Scott's banishment from GitHub. But this happened only once in several years, so I'd say it's just a bad coincidence for you. Please judge the Julia community by your actual daily experience when working with people, not from what you can hear about it. I can assure you you won't be disappointed.

**Comment by KristofferC** [comment]
>  6 days after immersing myself in the community (reviewing all github activity) I "personally" (over github) witness (what appears to be) arbitrary community banning.

Maybe you should realize that if you have been in a community for 6 days that you don't have the whole picture. This was something that developed over 6 months and the incredible patience and multiple attempts at cleanly handling the situation from the core Julia members s something that should be praised. Calling it a "personal vendetta" is completely false. 

This seem to have given you a bad impression of the way the julia community is being handled while for me it is completely the opposite. I am glad that the community managers have the guts to make the hard decisions instead of just sitting by passively.

**Comment by timholy** [comment]
@mason-bially, if I had thought about contributing to something and then immediately saw "fire," as you so aptly put it, I too would be inclined to walk away. I can't blame you a bit, and would probably have done the same myself. Definitely Julia's loss, and I hope you find other projects that make you happy.

That said, I do hope you'll take away a balanced perspective. Bad stuff happens eventually in any project that involves so many people, and for a project that regularly attracts new contributors it's a statistical certainty that **someone** will happen to be walking in the front door just at the moment when it all hits the fan. You happened to be that unlucky someone. Too bad for us, and perhaps for you. But as the others have said, it was not the sudden and arbitrary decision that it might appear to be.

From nearly 4 years in this project, my own personal experience has been one of the most congenial collective enterprises I've ever experienced. Even as you walk away (for good reasons), I hope you have at least the willingness to consider the possibility that you happened to get unlucky, and that most contributors seem to have a very positive experience.

**Comment by mason-bially** [comment]
> Please judge the Julia community by your actual daily experience when working with people

I am, I had positive interactions with him on the gitter the day he was banned. He helped me though a problem, at the time he was the only person "in the community" whom I had had any live interaction with.

> Maybe you should realize that if you have been in a community for 6 days that you don't have the whole picture. [...] Calling it a "personal vendetta" is completely false. 

I do realize that, on the other hand it completely killed my enthusiasm and excitement for the project. That may be false, but that's what it looked like when I went through the logs.

> Even as you walk away (for good reasons), I hope you have at least the willingness to consider the possibility that you happened to get unlucky, and that most contributors seem to have a very positive experience.

I'm not so sure. The thing is that if some one who helped me, who's arguments I tend to agree with, and has an argumentative style similar to my own gets banned for what looks like a supremely silly reason to me... *maybe I am not someone you want in your community*. And if that's the case I am not going to force it, I'm not going to invest my time when it seems like I'm just going to get a ban for it.

**Comment by mason-bially** [comment]
On a note of actually fixing Julia :sweat_smile: the fix posted above doesn't fix:

```
@sprintf("%A",0x002a) # "0X1.5P+4"
```
