### ISSUE TITLE
[0.4.2] 2^2^2^2^2^2 = 1

### ISSUE THREAD

**Issue by xyproto** [JuliaLang/julia#14411]
64-bit Arch Linux, Julia 0.4.2

I got a surprising result:

~~~
julia> 2
2
julia> 2^2
4
julia> 2^2^2
16
julia> 2^2^2^2
65536
julia> 2^2^2^2^2
0
julia> 2^2^2^2^2^2
1
julia> 2^2^2^2^2^2^2
2
julia> 2^2^2^2^2^2^2^2
4
julia> 2^2^2^2^2^2^2^2^2
16
~~~

What's surprising here is not that the number is overflowing, nor that the answers are wrong (in a mathematical sense), but that there are no errors, warnings or indications that an overflow is happening. Will this not lead to errors that are hard to find in larger programs?

**Comment by tkelman** [comment]
http://docs.julialang.org/en/latest/manual/integers-and-floating-point-numbers/#overflow-behavior

**Comment by nalimilan** [comment]
If it were possible to efficiently detect overflows and print a warning, we would rather make them an error. The problem is, you cannot do either without a large performance hit.

**Comment by eschnett** [comment]
Actually, integer exponentiation is already kind of expensive, compared to (say) addition or subtraction. We do check for overflow by default for multiplication and division, so we might also want to check for integer exponentiation.

**Comment by ScottPJones** [comment]
On the other hand, this is inconsistent with other similar decisions in Julia.  For example, bounds checking is done by default, that you need to turn off with `@inbounds`, and that is also a large performance hit.  Same thing with `@fastmath`.  Conversions do give an `InexactError`.

I don't think following C's 50 year old example in this (having unchecked math the default) is a good thing in Julia.  It has always seemed to me that math should be checked by default, and explicitly use a macro like `@unchecked` would be a lot cleaner and consistent with the rest of Julia.

**Comment by ScottPJones** [comment]
>We do check for overflow by default for multiplication and division, so we might also want to check for integer exponentiation.

@eschnett Where do you you see that? If I do `typemax(Int64)*typemax(Int64)` I get 1 back.

**Comment by eschnett** [comment]
@ScottPJones Sorry, I misremembered the multiplication case -- we only check for division, which is more expensive than division to begin with.

**Comment by JeffBezanson** [comment]
There is a world of difference between bounds checks and overflow checks. Out-of-bounds accesses can cause memory corruption, leaving the program in an undefined state. In contrast, overflow is perfectly well defined: operations are done mod 2^n. Sometimes the mod 2^n behavior is even desirable. I completely understand the desire for overflow checks, but the comparison to bounds checks is not the motivation.

**Comment by H-225** [comment]
@JeffBezanson 
> Sometimes the mod 2^n behavior is even desirable

I agree, but doesn't @ScottPJones' suggestion of `@unchecked`--or something similar--allow for that?

Indeed, I have also come by the fact that `2^64` => `0` in Julia... 
I'd rather have it tell me that it overflowed rather than silently assume I'm okay with it overflowing. Especially when it's a literal I'm dealing with, such as: `const LIMIT = UInt128(2^64)`, as an example.
Although in that case, I'd rather not have to say: `big(2)^64`; I'd rather `BigInt(2^64)` -- but that's getting off track for this thread.

**Comment by mason-bially** [comment]
I'd say remember to always exponent by a `BigInt` if you want safe behavior. (You also need to put the `BigInt` on the right. Consider:

* `BigInt(2)^2^2^2^2^2` is still 1
* `2^2^2^2^2^BigInt(2)` is overflow in the BigInt library.

**Comment by ScottPJones** [comment]
About overflow checks vs. bounds checks, both are situations where you can get logical corruption of your data, and get invalid results. I prefer no bounds checking, because you usually find out there is a bug in the program much sooner, maybe with a segment violation, rather than no overflow checking, where errors may be totally silent.

I think there are two totally distinct things going on here - one is the need (sometimes) for modular arithmetic, and the wish to be able to use faster, if potentially inaccurate, operations.
I was just thinking at lunch, that one way of solving this would be to add some new types to Julia, instead of using macros (which can be rather hard to deal with, and there are issues with whether things like `@inbounds` affect only the current scope, or things that are brought in by in-lining.
Something like: `CheckedInteger`, `NoCheckInteger`, `ModInteger`, and corresponding concrete types
(such as `Mod32`, `Mod64`, ... for (unsigned) modulo arithmetic)
(I'm not sure whether or not a signed version is needed for modulo arithmetic, I've never needed that).
The current types `Int64`, `Int32`, `UInt64` etc. could be aliased to either the the checked or unchecked versions, depending on the environment, just as `Int` is either `Int32` or `Int64`, depending on the environment.

Any thoughts?

**Comment by xyproto** [comment]
That is surprisingly different from mathematics.

I think x * 7 * 7 should be equal to 7 * 7 * x. Not because programming should be exactly like mathematical notation, but because I think it would be more intuitive for the target audience.

Is it not unintuitive that the ordering changes the result in such a way?

**Comment by eschnett** [comment]
The difference between checking and not is not that the result differ -- you get a correct output for the same set of inputs; it's just that errors are detected earlier (if at all) with checking. If a code runs correctly with checked integers, it will also do so with unchecked integers (for the same input), only faster. Thus using a different type doesn't cover the general use case: Enable thorough checking while debugging and testing, disable it for production runs if you are confident the code is correct.

If you want different semantics (modulo arithmetic, saturating arithmetic), then new types make sense. But not for checking.

**Comment by H-225** [comment]
ref #14415

**Comment by ScottPJones** [comment]
OK, but at least having a new type for Modulo arithmetic would make it easier to change the normal integer types from unchecked to checked by default, because the programmer can then indicate when they really do want modulo or not.  Since whether something works or not is generally going to be dependent on the input data, I don't think you can turn off checking after debugging (but then, for my use cases, it is critical that silent logical corruption doesn't occur).

**Comment by eschnett** [comment]
You can check your inputs (or the inputs to a function), and then disable checking inside the function once you are reasonably certain that the function is bug-free. It's the same case as for `@inbounds`: It's really the compiler that should disable the check if it's not needed, but in reality, it's going to be the programmer.

Yes, `ModInt` and `SatInt` make sense as type. In fact, they make much more sense than `add_mod` and `add_sat` functions.

**Comment by ScottPJones** [comment]
That sounds reasonable (checking on input), or having the checking explicitly turned on within functions that you really can't tell in advance.  Have to think about a `ModInt` PR.

**Comment by xyproto** [comment]
Just a quick update. Tried this with the latest version of Julia, in the REPL:

`2^2^2^2^2`

And the result is:

`0`

A way to enable bounds checking would be great.
