### ISSUE TITLE
read!() and readbytes!() mutate their second argument

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#14412]
I thought the convention was that in-place versions of functions mutate their first argument. It looks like we could easily change the argument order and print deprecations if we want to enforce this convention.

Though the `rand*!` family of functions also doesn't follow this rule, so maybe we should just give up on consistency.

**Comment by ivarne** [comment]
It's true that in-place functions mutate their first argument, but IO methods takes an optional `::IO` object as the first argument. The question is which convention that should win?

(The `::AbstractRNG` interfaces tries to use the same convention as `::IO`)

**Comment by ScottPJones** [comment]
I think @ivarne is correct, which convention takes precedence.
In this case, I personally would prefer to keep the IO as the first argument, even if that causes a little inconsistency with the mutating versions usually modifying the first argument.
It also makes sense if you wanted to have `read!(arr)` read from `STDIN`, for example.
(for some reason that short form doesn't seem to exist, though)

**Comment by stevengj** [comment]
I agree that `io` should continue to be the first argument.

**Comment by vtjnash** [comment]
the mutation of the first argument is common (since it often appears when used for container-semantics and oo-semantics), but I don't think it was ever intended that should be used as a rule. for example, i believe most of the linalg `!` functions mutate/assign/overwrite/destroy one or more arguments, but not necessarily the first argument. (unhelpfully, all of the IO functions actually mutate their first argument also, since IO is a form of mutation).

is there a place this needs to be documented better (e.g. when `!` is first described in the manual)?

**Comment by nalimilan** [comment]
To be honest, I haven't read this anywhere (or I don't recall it). No worries.
