### ISSUE TITLE
Negative shift counts could be handled better

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14516]
Julia allows both signed and unsigned shift counts, e.g for the operator `<<`. Signed counts are implicitly reinterpreted as unsigned counts, i.e. shifting by a negative value corresponds to shifting by a very large positive value, leaving as result either `0` or `-1` (for `>>`). This implicit conversion not ideal. It would also be very unusual to have code that finds this behaviour useful.

I can think of three possible alternatives:
- The "obvious": left-shifting by a negative amount is interpreted as a corresponding right-shift
- Explicitly convert from signed to unsigned, thus with a run-time error for negative values
- Require the shift count to be explicitly unsigned (very inconvenient, I don't really suggest this)

In many cases, the shift count is known at compile time, and I expect the compiler to produce optimal code in this case. Experiments confirm this. I thus expect performance differences (if any) only for variable shift counts.

Current CPU architectures don't have direction-agnostic instructions, so option 1 would require a case distinction in the general case. There is already a case distinctions e.g. on x86 (and probably many other architectures), since the machine shift instructions behave differently from what Julia specifies, and thus there is a branch statement or equivalent in the code. Adding one more branch for unknown, signed shifts might not be that bad.

I looked at how shifts are used in Base. In the vast majority of cases, the shift is directly known, and the compiler can generate optimal code. In a few cases, the shift is calculated, e.g. `io.jl`, line 136:
```Julia
    for n = 1:sizeof(x)
        x |= (convert(T,read(s,UInt8))<<((n-1)<<3))
    end
```
In no case there is an `if` statement to handle both shift directions (although I need this in my code, hence my suggestion).

**Comment by tkelman** [comment]
What do other languages do for negative shifts?

**Comment by eschnett** [comment]
Here's a sample from other languages:
- C, C++: undefined behaviour, even for shift counts larger than then number of bits in the shifted type
- OpenCL C: shift count is taken modulo the number of bits in the shifted type
- Perl: negative shift counts are implicitly converted to a large unsigned number
- Go: shift counts must be unsigned
- Python: negative shift counts are a run-time error
- Fortran: `ishft` intrinsic function accepts positive and negative values for left and right shifts, respectively
- Mathematica: `BitShift[Left,Right]` accept both positive and negative values
- Matlab: `bitshift` function accepts both positive and negative values

**Comment by tkelman** [comment]
Cool. I think I'm inclined to go with Fortran/Mathematica/Matlab then.

**Comment by anthonyclays** [comment]
Those functions in fortran, mathematica and matlab are generic 'bitshift' functions, not operators such as '<<' or '>>'.

If you want a function such as 'bitshift' that can handle both negative and positive shifts, you should write one explicitly - I feel like checking for negative values in bitshift _operators_ will create a minefield for performance if the additional branch can't be compiled away.

**Comment by simonster** [comment]
Yes, performance is potentially an issue here. Code that uses BitArrays is heavily reliant on shifts that aren't known at compile time, and I'm not sure LLVM is smart enough to know that these shifts will always be positive and optimize out the branch. It would be interesting to see what happens to the generated code.

**Comment by tkelman** [comment]
The branch would also happen for the runtime error check on negative shifts, which would be my second choice. I don't see how the spelling of whether these are infix changes anything about the performance concern.

**Comment by anthonyclays** [comment]
Of course the performance concern does not have anything to do with `<<` and `>>` being infix, but rather from the unpredictability inherent to adding bounds checks to those functions.

I mentally map `<<` to a single `sll`-instruction, which is why I don't feel comfortable changing the behavior of `<<` and `>>` (and `>>>`). Adding a new function `bitshift` that can handle both positive and negative values (à la Matlab-bitshift) might still be a useful addition to the standard library though.

**Comment by eschnett** [comment]
@anthonyclays If the shift count is known at compile time, then `<<` turns into a single `sll` instruction. This would continue to be the case since LLVM would optimize away the respective branch.

But already currently, when then shift count is not known at compile time, there is a branch. The `sll` machine instructions e.g. on x86 cannot handle arbitrarily large counts (or if they do, have different semantics than Julia). Thus there is a check, and if you e.g. shift an `Int` by more than 63, the result is explicitly set to zero:
```
	movb	%sil, %cl
	shlq	%cl, %rdi
	xorl	%eax, %eax
	cmpq	$63, %rsi
	cmovbeq	%rdi, %rax
```
The changes discussed above would add a second check, with a predictable branch.

**Comment by eschnett** [comment]
LLVM's shift instruction is documented as:
"The first argument to the 'shl' instruction must be an integer type. The second argument must be an 'ubyte' type."

I assume that `ubyte` means "unsigned byte". Julia's shift operators accept a signed integer as argument, reinterpret is as unsigned integer in the C++ wrappers, and then pass it to LLVM.

This looks to me as if this code was written when Julia was young, and when type conversions were not yet safe. (I believe type conversions started to check for overflow only with the 0.4 release.)

**Comment by anthonyclays** [comment]
@eschnett I see. When those branches turn into simple conditional instructions, the additional branch might not be such a bad idea. Behaviour will become very much incompatible with C though, where shifting a number will only use the rightmost few bits of the second operand (e.g. shifting a 64 bit int by `65 = 0b1000001` is equivalent to a shift by `1 = 0b0000001`).

Side-note: I like the idea of measuring the performance hit from the second branch by benchmarking BitArrays.

**Comment by El-Zurdo-Sordo** [comment]
@anthonyclays Is compatibility with C such a good thing?  I'd hoped for Julia to not copy the design decisions of C that might have been appropriate given processors back 40+ years ago, but necessarily the best decisions now.

**Comment by eschnett** [comment]
Idea: If we define both
```Julia
<<(x, count::UInt) = ...
<<(x, count::Int) = x << convert(UInt, count)
```
then all callers who care about efficiency can use the first version, which -- since the argument is unsigned -- carries no penalty for checking for negative indices. Only in cases where the argument is signed (and not known at compile time!) there is a penalty for checking for overflow.

**Comment by eschnett** [comment]
@anthonyclays No, the behaviour will remain compatible with C... In C the behaviour is undefined. Some compilers/systems will probably do what you describe, but you cannot rely on it in general.

**Comment by tkelman** [comment]
I like defining separate methods for unsigned shifts, but convert is the runtime error option, right? Hard to tell how often negative shifts might be legitimate vs a mistake in user code.

**Comment by eschnett** [comment]
@tkelman I looked at how shifts are used in Base; all negative shifts would be an error. Since the documentation also doesn't state that negative shifts are re-interpreted as large unsigned values, and since there is no agreement between different programming languages, I don't think there will be many places relying on it.

**Comment by anthonyclays** [comment]
@eschnett "... you cannot rely on it in general." True, but I challenge you to find a compiler that doesn't work that way.

Now that I've seen that UInt trick, I think everyone agrees that:
- for statically known shift counts, there is no problem (as LLVM compiles the branches away),
- for shifts where the shift count is computed at runtime _and_ performance is an important consideration (BitArrays), one should use `<<(x, count::UInt) = ...` which requires only the >63 branch (this should be documented then?),
- otherwise, the behaviour should be one of the first two possibilities @eschnett describes in the original post. As @tkelman notes, the desired behaviour in this case depends on how often a negative shift count would be a mistake by the user (-> runtime error) vs how often this would be desired (-> shift in the other direction).

The original issue post shows that there exist use cases where negative shifts are desired.
On the other hand, runtime errors might make it easier to debug mistakes (off-by-one errors come to mind) in the shift count.

**Comment by rfourquet** [comment]
I would be a user of negative shift counts, but wouldn't mind using a dedicated function (e.g. `bitshift`).
If a method `<<(x, count::UInt)` is added, removing the ">63 branch" could be considered to provide the native efficiency.

**Comment by El-Zurdo-Sordo** [comment]
>one should use <<(x, count::UInt) = ... which requires only the >63 branch (this should be documented then?),

On Intel, that's not even a (normally never taken) branch, it uses a conditional move instruction.

>The original issue post shows that there exist use cases where negative shifts are desired.
On the other hand, runtime errors might make it easier to debug mistakes (off-by-one errors come to mind) in the shift count.

I would prefer a dedicated function (`bitshift`) for treating negative shift counts as right shifts, and having the the `<<`, `>>`, and `<<<` operators use convert (and give run-time error when values not known at compile time are negative) (as well as return 0 for `<<` and `>>>` where shift > size in bits, or -1 for >> where shift of signed value > size-1 in bits, instead of C's useless "undefined" behavior).
I think that would make the intent of the programmer clearer, and brings off-by-one bugs to light.

**Comment by El-Zurdo-Sordo** [comment]
@eschnett Should those be instead, so that shifts of other `Signed` types are caught?
```julia
<<(x, count::Unsigned) = ...
<<(x, count::Signed) = x << convert(UInt, count)
```

**Comment by eschnett** [comment]
@El-Zurdo-Sordo Yes; my description was just a sketch.

I think we've reached an agreement. I will prepare a pull request

**Comment by StefanKarpinski** [comment]
I'm in favor of the Mathematica/Matlab interpretation of the shift operations, but I'm concerned about performance. Of course these operations already have lousy performance as it is.

**Comment by StefanKarpinski** [comment]
See also: https://github.com/JuliaLang/julia/issues/11592
