### ISSUE TITLE
Float type alias for Float64?

### ISSUE THREAD

**Issue by AzamatB** [JuliaLang/julia#14542]
Is it possible to create a `Float` type alias to `Float64` type in analogy to `Int` aliasing `Int64` if this will not cause any conflicts?

**Comment by johnmyleswhite** [comment]
You wouldn't want to do this because most modern 64-systems and 32-bit systems both provide efficient 64-bit floating point numbers. The `Float64` vs `Float32` distinction is fundamentally dissimilar to the `Int64` vs `Int32` distinction.

Just FYI: questions like this are better suited to StackOverflow or the julia-users mailing list.

**Comment by tkelman** [comment]
Ref. #12188. Adding a architecture-independent `Float` type that always aliased to `Float64` would be confusing given the `float` type in C and C++ is single (32 bit) precision.
