### ISSUE TITLE
Incorrect shape reported for vec*mat error

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#14679]
``` jl

julia> x = rand(4); A = rand(4, 4); x*A

ERROR: LoadError: DimensionMismatch("A has dimensions (4,1) but B has dimensions (4,4)")
 in gemm_wrapper! at linalg/matmul.jl:311
 in * at linalg/matmul.jl:88
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
```

The first argument is a vector, and so should be reported as having only a shape of (4,), not (4, 1).

**Comment by tkelman** [comment]
Need a length check [here](https://github.com/JuliaLang/julia/blob/9c08e5d9d86bc98756e7b72d146561cf3fc1c35b/base/linalg/matmul.jl#L88) before calling reshape

**Comment by andreasnoack** [comment]
I'm not sure this is wrong. If you multiply a matrix with a vector from the left then it is promoted to a matrix-matrix multiplication. If the shapes of the matrix-matrix multiplication don't fit then you get an error.

**Comment by KristofferC** [comment]
Isn't that an implementation detail?

**Comment by jiahao** [comment]
The user never sees the implicit promotion though.

**Comment by andreasnoack** [comment]
> Isn't that an implementation detail?

I'm never really sure when something is an implementation detail. It must depend on the specification of the function and there we hit #4774. If the specification of linear algebra operations ends up being something like "for `*`, all vector arguments are promoted to matrices" then I don't think it's an implementation detail.

If we "fix" this issue then we should also "fix" the issue below. I don't think we should since I prefer to throw the exception at the point some necessary requirement is not fulfilled even though it might be a little down the chain of function calls. Alternatively, we'll check the same things over and over and in a generic programming context, it can be difficult to predict the possible errors down the chain.

```jl
julia> randn(3,2)*randn(3)'
ERROR: DimensionMismatch("A has dimensions (3,2) but B has dimensions (1,3)")
 in gemm_wrapper! at linalg/matmul.jl:312
 in A_mul_Bc at operators.jl:164
```

One could also ask what the error message of `sqrt(-1)` should report as the input (type) when failing. Should it be `-1 (Int64)` or `-1.0 (Float64)`. Right now the function doesn't mention the input (type) explicitly so that would be similar dropping the explicit dimension sizes in this issues message.

**Comment by fwang88** [comment]
I think this fix is consistent with the definition of ```size()``` function in ```julia```. For example,
```
julia> size(randn(3))
(3,)
julia> size(randn(3)')
(1,3)
```
So your example here looks to be no problem. Though I'm not sure why ```randn(3)'``` is considered as a 2 dimensional array.

**Comment by carnaval** [comment]
> Though I'm not sure why randn(3)' is considered as a 2 dimensional array.

Jiahao is now fully awake

**Comment by jiahao** [comment]
> If the specification of linear algebra operations ends up being something like "for *, all vector arguments are promoted to matrices" then I don't think it's an implementation detail.

Yes, but we don't define it this way, therefore it is an error in the sense that the message does not read "A has dimensions $(size(A)) but B has dimensions $(size(B)). Let's not confuse what Julia does with what R does.

**Comment by KristofferC** [comment]
This now gives:

```jl
julia> x = rand(4); A = rand(4, 4); x*A
ERROR: DimensionMismatch("Cannot left-multiply a matrix by a vector")
```

so this issue seem obsolete.
