### ISSUE TITLE
int, Int, and box

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#1470]
I.e. write `Int(1.5)` instead of `int(1.5)`. See this thread for discussion:

https://groups.google.com/d/topic/julia-dev/gy1HlWWcxBA/discussion

**Comment by stevengj** [comment]
With the current situation, `T(x)` is (by default) equivalent to `convert(T, x)`, which expresses lossless conversion.  e.g. `Int(1.5)` throws an error.

So, we still need a separate function for coercing conversion.   I suppose we can continue to use the lower-case `t(x)` convention for this?

(Although we aren't entirely consistent: `uint(-1)` throws an `InexactError` rather than coercing.)

**Comment by johnmyleswhite** [comment]
Is `coerce` dead already? I really like the idea of a name that's so explicit.

**Comment by stevengj** [comment]
We could get rid of the lower-case versions by a variant on @StefanKarpinski's proposal early in this issue:

* `coerce(T,x)` coerces (replacing `int(x)` etc.); defaults to `convert(T,x)` but may be more forceful
* `convert(T,x)` converts, throwing an error if an exact conversion isn't possible
* `T(x) == call(T, x)` is the constructor, and defaults to `coerce(T, x)`.  (Or to `convert`?  That is the key question.)

The point is that we seem to all agree that we need three concepts: construction, conversion, and coercion, which *may* coincide (and can coincide by default) but *may* be distinct operations.  The only tricky part is the spelling, and deciding what defaults to what.

If we make `T(x)` default to `coerce(T, x)`, then this eliminates the brevity rationale for `int(x)` etcetera: `Int(x)` is just as easy.  On the other hand, this means we have no short spelling for exact conversion: you have to write out `convert`.  Also, as has been pointed out, it is slightly weird for e.g. `Int([....])` to produce an `Array{Int}` and similar "coercions" that don't produce an instance of the requested type. 

The problem I have with `coerce(T, x)` is that it is not clear what we gain compared to the `t(x)` convention.    I'm skeptical about using `coerce` in generic code (i.e. with an unknown `T`), since it is hard to use coercion effectively if you have no idea what type it will produce (`T`, `Array{T}`, ...).   Furthermore, a disadvantage of making `coerce` default to `convert` is that you can't tell by looking at the call site whether it will throw `InexactError`; in contrast, since there is no `t(x)` defined by default for a type `T`, if you see `t(x)` you can be pretty sure that someone has defined a coercion that is distinct from `T(x)`.  Finally, the lower-case versions for common types can often be abbreviated further, e.g. `float(x)` instead of `FloatingPoint(x)` or `utf16(x)` vs. `UTF16String(x)`.

**Comment by nalimilan** [comment]
From the discussion above, I got the feeling that `coerce` was not really needed. For example, people would better call `round(Int, x)` or `floor(Int, x)` to make explicit *how* coercion should happen.  Are there cases where `coerce` would be useful?

**Comment by JeffBezanson** [comment]
I agree very much with the bullet points at the end of @stevengj 's last comment. I'm skeptical of `coerce`. Ideally I'd also like to get rid of the lowercase functions, but they seem to be quite convenient and I'm not sure what to do with them (except maybe just delete them).

**Comment by stevengj** [comment]
I don't think we should get rid of coercion.   It is incredibly convenient to be able to write `float(x)` and get a floating-point version of `x`, whether `x` is an `Array{Int}` or `Complex{Int}` or whatever.

Here is another point in favor of `float(x)`: I was recently looking at decimal floating-point libraries, and for a `DecimalFloat64 <: FloatingPoint` type it will be very convenient to define:
```
float(x::DecimalFloat64) = Float64(x)
```
This way, all of the special functions would just work, because they all have fallback functions of the form `sin(x::Real) = sin(float(x))`.    (Conversion to binary float is what you want here because there is no point in preserving the decimal representation when you pass through a function yielding an irrational result.)   On the other hand, if these functions used `coerce(FloatingPoint, x)`, I could no longer do this because `DecimalFloat64 <: FloatingPoint` already.

**Comment by JeffBezanson** [comment]
Indeed, `float(x)` is especially convenient since the whole point of it is not to correspond to a particular type. This reinforces the idea that there isn't a general notion of both `Type(x)` and `type(x)` for all types. For me, functions like `int32(x)` are much closer to being on the chopping block.

**Comment by tknopp** [comment]
I agree with the usefulness of `float` but also `int`. One point is that they are so easily recognizable and I often do `int( a/b )`. This might not be the most efficient thing but for newcomers or people that do not know what the best way to write this it is convenient.

**Comment by JeffBezanson** [comment]
`int(a/b)` is a bit of a problem, to me. In that specific case I think it's much better to know what kind of integer conversion is needed.

**Comment by tknopp** [comment]
Jeff: I know that. But its was the most intuitiv way to do it when I needed to be a/b an index.

**Comment by YusufCakan** [comment]
Could this work

* T(x) is the constructor and defaults to convert
*  convert(T,x) is used to specify exact conversions, and can be accessed through the constructor syntax above, throws error if exact conversion is not available
* T!(x) is used to indicate coercing, this way we get rid of the lower case versions t(x), but use the ! to indicate that something forceful is being done here.

I just started using julia, so I don't know enough about the internals of the language to know whether the above could work from an implementation point of view.

**Comment by ivarne** [comment]
@YusufCakan I think that could work, but there are definitely a few points where it will be problematic.

* The `!` postfix for functions is currently used to indicate that the function will modify one or more of the arguments "in place". This suggestion adds a concept of coercing and will be conflicting if coercing a mutable type.
* You would not know where to add the `!` for constructors with type parameters (eg. `Array{Float64,2}!()` or `Array!{Float64,2}()`).
* It will just be a convention that you should define such a method. We will probably not be able to cleanly add some logic so that `T!(a)` falls back to `T(a)`, if the coercing version is not defined for that type.

**Comment by nalimilan** [comment]
@stevengj I fully agree these cases are useful, but I don't see the examples you gave as coercion, rather as conversion. Regarding `float(::Array{Int})`, this sounds like vectorized conversion. As for `float(::DecimalFloat64)`, it looks like what you're taking about is a special conversion that would convert to the most appropriate `FloatingPoint` subtype. Right?

@tknopp The fact that `int(a/b)` appeals to new users is the strongest argument against it. In many cases, you do that when you know `a/b` can be converted to an integer without any rounding, thus `Int(a/b)` would be correct. OTC, `int(a/b)` will happily round the value even if it doesn't match your expectations, possibly introducing bugs.

@YusufCakan `!` usually means that the argument is modified, which isn't the case as all with `T!(x) `. Not sure it's a good idea to introduce an inconsistency here.

**Comment by YusufCakan** [comment]
@ivarne agree this adds the concept of coercing to the ! postfix operator. I suppose the distinction is that this modification of the concept applies only when calling types. But agree that it does make the ! operator more subtle, which may be too much of a sacrifice in order to get rid of the lower case t(x)'s. Depends on whether the current t(x) versus T!(x) would cause more confusion.

Regarding your  second point, i think this is just a matter of establishing some conventions in the language.

finally, I don't really see much benefit in defaulting coercion back to convert. i see the coercion function as being the thing you try when there isn't a way to do an exact conversion through convert anyway, or you want to do something very specific for your type, so was not suggesting that the coercion default back to convert.  

Yes, implementing the T!(x) method would be by convention, same as using the t(x) method by convention.

**Comment by JeffBezanson** [comment]
I'm totally against adding any meanings to `!`. Naming conventions only work if you follow them really strictly, because nothing else in the language can check them for consistency.

**Comment by kmsquire** [comment]
How about having `int(x)` return an error asking the user to use `round` or` trunc`? 

This is could initially just be part if the deprecation, of course.

**Comment by StefanKarpinski** [comment]
I'm fairly convinced that generic coercion doesn't make sense. If there's only one reasonable way to go from values of type `A` to type `B` then that wouldn't be a coercion – it would just be conversion. If there is more than one way to go from values of type `A` to type `B` then you inherently need to specify which one – and what the choices are tends to depend heavily on `A` and `B`, which makes the choice inherently non-generic. For each `A` and `B` you are just arbitrarily picking one of many possible ways to coerce from `A` to `B` and then pretending that all of these arbitrarily chosen methods are somehow related.

> @stevengj: I don't think we should get rid of coercion.   It is incredibly convenient to be able to write `float(x)` and get a floating-point version of `x`, whether `x` is an `Array{Int}` or `Complex{Int}` or whatever.

I think there's a lot to be said for just spelling this out. What do you really want to do here? Take the real part and convert it to some floating-point type? Then write `FloatingPoint(real(x))`. That's not so bad. If you want to assert that all the values in `x` are real-valued and fail otherwise you can just write `FloatingPoint(x)`.

**Comment by goretkin** [comment]
perhaps @stevengj  was hoping to avoid needing to write `Complex(FloatingPoint(real(x)),FloatingPoint(imag(x)))`

**Comment by stevengj** [comment]
@goretkin, that and the fact that a lot of code will be less generic.  e.g. `sin(x::Number) = sin(float(x))` will have to be replaced by multiple methods.

**Comment by JeffBezanson** [comment]
I think one good argument is that "convert to *some* appropriate floating point type" is a sensible operation because floats have a large range and you implicitly accept roundoff error. "Convert to integer" doesn't have those properties. It also makes sense to have `float(z::Complex)::Complex`. One could argue for `integer(z::Complex)::Complex`, except that complex integers are just so rare in practice.

**Comment by quinnj** [comment]
Not sure how the change here interacts with `methods` fully, but the output for `Int64` is not very meaningful.
```julia
n  [71]: methods(Float64)

Out [71]: 4-element Array{Any,1}:
 call(::Type{Float64},x::Base.MPFR.BigFloat,r::Base.Rounding.RoundingMode{T}) at mpfr.jl:180                                              
 call{T<:Union(Float64,Float32),s}(t::Type{T<:Union(Float64,Float32)},c::MathConst{s},r::Base.Rounding.RoundingMode{T}) at constants.jl:17
 call{T<:FloatingPoint}(::Type{T<:FloatingPoint},x::Real,r::Base.Rounding.RoundingMode{T}) at rounding.jl:66                              
 call{T}(::Type{T},args...) at base.jl:35                                                                                                 

In  [72]: methods(Int64)

Out [72]: 1-element Array{Any,1}:
 call{T}(::Type{T},args...) at base.jl:35
```
I can open a separate issue if needed.

**Comment by quinnj** [comment]
Actually, I guess the above output is correct, because there are no explicit outer constructors for `Int64`, and it's created as a `bitstype`. I guess it just occurred to me that `bitstype` don't get any default constructors, though that's probably obvious since you don't inherently know anything except it's size.

**Comment by JeffBezanson** [comment]
It does look like the more generic conversion functions are more popular:

```
jeff@gurren:~/src/julia/base$ ack 'complex(32|64|128)\('|wc -l
38
jeff@gurren:~/src/julia/base$ ack 'complex\('|wc -l
78
jeff@gurren:~/src/julia/base$ ack 'float(16|32|64)\('|wc -l
128
jeff@gurren:~/src/julia/base$ ack 'float\('|wc -l
171
```

I'd like to get rid of all the lower-case conversions except `float` and `complex`. Good replacements include `Int(x)`, `map(Int, x)`, and `Array{Int}(x)`.

We should also remove `utf8`, `utf16`, and `utf32` (and `wstring`). I think the main barrier there is just the verbosity of `UTF16String(x)`. Maybe the types should be renamed to `UTF16` etc.

**Comment by ViralBShah** [comment]
+1

**Comment by garborg** [comment]
Love it.

**Comment by ivarne** [comment]
Just for comparison, searching all METADATA packages gives:

```
ivarne~/dev/allpkg$ ack 'complex(32|64|128)\('|wc -l
      15
ivarne~/dev/allpkg$ ack 'complex\('|wc -l
      91
ivarne~/dev/allpkg$ ack 'float(16|32|64)\('|wc -l
     756
ivarne~/dev/allpkg$ ack 'float\('|wc -l
     630
```

**Comment by timholy** [comment]
I'm really pleased about this change. But one practical matter: to avoid deprecation warnings, does anyone see an alternative to forking a 0.4 version of packages? The syntax `Float32(2.8)` can't work on julia 0.3.

**Comment by stevengj** [comment]
@timholy, you can use `@compat Float32(2.8)` via the `Compat` package, or `convert(Float32, 2.8)`.

**Comment by timholy** [comment]
I'd thought about the rewriting part, but missed the `@compat` method. Thanks!

**Comment by timholy** [comment]
Ah, although
```
`convert` has no method matching convert(::Type{Float32}, ::UnitRange{Int64})
```
suggests a certain amount of rewriting might be necessary anyway.

**Comment by stevengj** [comment]
For a range, you can do `convert(Vector{Float32}, r)`

**Comment by timholy** [comment]
I know. I was just hoping for something I could do via search-replace with a text editor. I have a lot of packages :-). And a lot of lab-specific code.

**Comment by ViralBShah** [comment]
While I love this change, I don't like the idea of writing `map(Int, x)` instead of `int(x)`, which is clear and concise. What about vectorized `Int(x)`?

**Comment by johnmyleswhite** [comment]
Also relevant: does `map(Int, x)` make the output array of fixed length?

**Comment by tkelman** [comment]
> What about vectorized `Int(x)`?

Calling a constructor for a scalar type on a non-scalar input and implicitly mapping seems like a bad idea to me. `map` is pretty concise too, unless you want to get into Mathematica territory of adding infix syntax like `/@` for map.

**Comment by ViralBShah** [comment]
Why is it a bad idea? Intuitively, it does not feel right, but I dislike doing a `map` even more. Doing `map` is not as clear as the original `int(x)`. I am pretty sure @alanedelman thinks so as well.

**Comment by quinnj** [comment]
I agree with @tkelman. While writing `Int(x)` may be convenient, I think it leads to the crux of the "vectorized" discussions that have been going on: namely, do we continue the use of `@vectorized_1arg` to auto-vectorize scalar functions, or arbitrarily define vectorized versions of scalar functions here and there, or enforce a convention like `map` or some kind of operator that would vectorize scalar functions over a collection. I'm highly in favor of the latter; I don't think `map(Int,x)` is terrible, but I think some kind of operator not unlike the `.+`,`.*` family would be ideal.

It makes it explicit, both when writing and reading code that the operation is vectorized, and doesn't require any macro-ing or auto-vectorizing for the developer.

**Comment by timholy** [comment]
@ViralBShah, it's the classic issue: does `exp` mean elementwise-exponential or matrix-exponential? Once functions-as-arguments have good performance, I suspect all elementwise operations will be performed using `map`.

**Comment by tkelman** [comment]
With call overloading we have construction and conversion using the same interface. A non-scalar type is not convertable to a scalar type.

Conceptually `map` makes perfect sense here. Do you dislike the concept, or the current (and some recently proposed) limitations in the way Julia implements map?

**Comment by JeffBezanson** [comment]
I agree `map(Int, x)` is not nice syntax. However we simply cannot keep adding piecemeal vectorized versions of things. From one perspective `int(x)` is clear, but it just doesn't scale. As you start working with more types, how do you use them? If you know `int(x)`, and then you learn about `Rational{Int8}`, it's not clear how to combine them. I think this is still an unsolved problem.

**Comment by ViralBShah** [comment]
I am in favour of having a generic way to vectorize things as well, and that the current method does not scale. The only issue I have with `map` is that we have just made julia a little more difficult and annoying for those used to writing vectorized codes.

Perhaps we can retain some of those old definitions and not deprecate them yet - after all, you still have `sin(x)`. Once we find nice syntax for `map`, we can remove all the vecotrized methods in one shot.

**Comment by timholy** [comment]
In my julia travels, I have found at least one case where I wonder whether vectorization is more useful than we generally credit. Say I have two images, `img1::Image{Ufixed8}` and `img2::Image{RGB{Ufixed8}}`, and I want to convert these so that the raw values are encoded as `Float32` rather than `Ufixed8`. For the purposes of this discussion, let's sometimes think of an `RGB` simply as a fixed-length 3-vector, so really what we have in one case is an array and in the other case an array-of-arrays (except that I also often think of an `RGB` as a single object). For writing generic code, `float32(img)` does have its appeal; otherwise I have to write this as:
```jl
map(Float32, img1)
map(x->map(Float32, x), img2)
```
The implication is that I have to write more versions of whatever function this conversion appears inside of.

Or maybe I'm missing a better way?

**Comment by ViralBShah** [comment]
That was exactly one of the cases that happened when I was working on a demo using Images.

**Comment by pao** [comment]
(This discussion is turning into an #8450 sequel. *Map Syntax II: APL Strikes Back*)

**Comment by timholy** [comment]
@ViralBShah, FYI, `float32` exists in Images and does what is described above. 

@pao, good point, let's not add more to this here.
