### ISSUE TITLE
Intermittent deadlock in PR merge process

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#14748]
The PR merge process seems to sometimes deadlock in cases like this:

 - Find a small bug.
 - Fix it and submit a PR.
 - PR reviewer asks for a test case.
 - Write a test case.
 - Test case finds new bugs.
 - Fix new bugs.
 - Push test and bug fixes to PR.
 - PR reviewer asks for the PR to be split so that each PR fixes only one bug.

Deadlock! Can either have first bug fix without test, or test with all bug fixes.

The perverse effect of this process is that it discourages writing good test cases.

Maybe what is needed is a way to add a failing test case without having your PR rejected.
e.g. Instead of the test system "failing CI" when a test fails it should record a list of failures. The rule could be that there are no regressions in existing tests but that it is fine (and encouraged) to add new tests that fail.

**Comment by JeffBezanson** [comment]
I don't think this is a common problem. In such cases, I would be satisfied with the explanation that the fixes are coupled. IMO, better to do 2 fixes at once than to deliberately allow failing tests onto master. Of course, writing failing tests is very helpful, but nobody can realistically predict when they might be fixed so they're best left in bug reports or PRs rather than blocking CI passing.

**Comment by StefanKarpinski** [comment]
There's also the issue that broken tests (or builds) make git bisect not work. There are two cases here:

1. The bugfixes are coupled such that they cannot be separated easily – keep them in one PR.
2. The bugfixes are not coupled and can be separated easily – split them into two PRs.

I'm guessing that part of the difficulty is that since the test for the first bug depends on the fix for the second bug, you will have to rebase the first PR on top of the second PR, which takes a little git-fu, but isn't all that hard: make the second change on a new branch `bug2`, then rebase the `bug1` change on top of `bug2` by doing `git checkout bug1 && git rebase bug2`.

**Comment by tkelman** [comment]
This has happened before, with scottpjones. Keeping PR's smaller, as repeatedly suggested- not adding new methods within the same PR as a renaming, splitting bug fixes that apply to different types, etc would ease this process. There's nothing wrong with opening new PR's that depend on an already open PR to pass, just indicate as much in the description. Leaving the already open PR small so it can be reviewed is better than adding to it so it's a moving target. If there's a clear order of dependencies then we know where to focus review effort first.

**Comment by StefanKarpinski** [comment]
As I said, it's also ok to open a new PR and rebase an older one onto it, which solves the deadlock.

**Comment by samoconnor** [comment]
My git-fu is strong enough that I grok the appropriate chicken waving enough to keep the rebasing gods pacified (mostly).
As Jeff says, explaining coupled tests is usually fine.

The thing that worried me was thinking to myself "how can I get my next PR merged more smoothly?" then thinking "If I'd just kept my head down and written a minimal test case...",
and then "So how could things be improved to encourage writing broader-than-required test cases?"

I still think there might be a place for a seperate class of "soft" or "warning" test cases that are expected to fail.
Perhaps...
```julia
@test_soft "#12345" condition == true
```
Where #12345 is the issue number that explains why this test doesn't always pass (maybe it fails intermittently, or fails on certain platforms). When the underlying problem is fixed the soft test can be promoted to a normal test.

In my recent case of testing a set of `::IO` subtypes vs a set of `read*()` functions vs a set of test data it would have been useful to be able to mark certain combinations of failure as "soft" or "warnings" rather than leave them out altogether.

I'm not super convinced that this is essential, it's just a thought...

**Comment by samoconnor** [comment]
> As I said, it's also ok to open a new PR and rebase an older one onto it, which solves the deadlock.

I think the split and rebase works in some cases but not all. If the test for fix A inadvertently finds bug B. You end up with fix A and fix B and a single test case. Whatever order the PRs are submitted or rebased you still end up having to contrive a hobbled test case to go with the first submitted PR.

This is not a big problem, as @JeffBezanson says _"In such cases, I would be satisfied with the explanation that the fixes are coupled."_.

**Comment by tkelman** [comment]
I do think expressing something like "fix pending" within the test suite would be valuable. Often when revisiting old issues we find they're no longer reproducible, but it requires bisecting to actually find out what the fix was. There's often valuable information to be had by knowing exactly when a bug gets fixed (especially if it was an unintended consequence of some other change) rather than hand-waving and saying "apparently fixed, but don't know by what."

**Comment by StefanKarpinski** [comment]
How about a file where we stick all the failing tests, which isn't run by default but can be run by `make test-failing` or something like that? Of course, that leaves the matter of how to test for that specific failure being fixed unsolved. So it seems like without better granularity for running tests this may not help. Or were you thinking of some kind of warning / failure when a test that's expected to fail starts passing?

**Comment by tkelman** [comment]
More the latter, most of the point of wanting to have something in the test suite (even if currently failing) is to have it running regularly. Adds a bit of work to go in and change its status when it gets fixed (intentionally or not), but that's kind of the point, to flag and make it obvious precisely when the status changes on a FIXME item.
