### ISSUE TITLE
Fallback `*(AbstractMatrix, AbstractMatrix)` method

### ISSUE THREAD

**Issue by rofinn** [JuliaLang/julia#14757]
Hi, I've been implementing a couple custom Array types ([PersistentArrays.jl](invenia/PersistentArrays.jl - Julia - GitHub) and [TrajectoryMatrices.jl](https://github.com/invenia/TrajectoryMatrices.jl) and I noticed that julia doesn't have a fallback for matrix multiplication. I realize that ideally you want to be using the in place BLAS methods whenever possible, but is there anything wrong with including something like this as a fallback?

```
function (*){T}(A::AbstractMatrix{T}, B::AbstractMatrix{T})
    if size(A, 2) != size(B, 1)
        throw(
            DimensionMismatch(
                "Columns in the first matrix ( $(size(A)) ) doesn't equal " *
                "the number of rows in the second ( $(size(B)) )"
            )
        )
    end

    result = Matrix{T}(size(A, 1), size(B, 2))
    for i in 1:size(A, 1)
        for j in 1:size(B, 2)
            result[i,j] = vecdot(A[i,:], B[:,j])
        end
    end

    return result
end
```

If this seems reasonable I can make a PR, but I'm not sure where it should go...

**Comment by andreasnoack** [comment]
We almost have support for this. The low level function [here](https://github.com/JuliaLang/julia/blob/8e036b445f6413386f2b1a2c747abce2df0315fa/base/linalg/matmul.jl#L454) is a generic matrix multiply and if [this](https://github.com/JuliaLang/julia/blob/8e036b445f6413386f2b1a2c747abce2df0315fa/base/linalg/matmul.jl#L129) signature was loosened the generic fallback would be called. However, the generic fallback includes two different algorithms: a fast one that assumes a specific memory layout and a simple three loop version. I think the branching condition is insufficient right now because your `TrajectoryMatrix` would probably go into the "fast" version, but it doesn't meet the memory layout requirements. The problematic condition is [here](loosened) and I think it has to check the strides as well. If you want to try out a PR it would be great.

**Comment by ViralBShah** [comment]
Does dispatch take one to the right place for generic matmul now?

**Comment by ViralBShah** [comment]
Seems to work as intended.
