### ISSUE TITLE
`make test` spawns 50 workers and breaks down

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#14828]
In one of the RPM nightlies builds, `make test` appears to have gone completely mad, and started 50 workers despite `JULIA_CPU_CORES=2`. Previous and subsequent builds under the same conditions work fine and start 2 workers as expected. This is with LLVM 3.7.1.

It also seems that the tests completely break down for some reason, probably related.

I don't dare copying the messy output here, but see the end of this log:
https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia-nightlies/fedora-23-x86_64/00156219-julia/build.log.gz

**Comment by tkelman** [comment]
The reason for the number of workers is due to all the failures, waiting to report all of them until the end, Something is fishy and intermittent with pointer conversions in many of the tests, possibly due to https://github.com/JuliaLang/julia/commit/639621859863609c5f3abbc2ed75c675695b3693 or some other recent commit. I've seen this a handful of times on travis and appveyor and locally too, but only since yesterday.

**Comment by yuyichao** [comment]
Is this still a problem and is there a back up of the log somewhere? The link above is 404 now...

**Comment by nalimilan** [comment]
I haven't seen it again, and anyway there's not much information here, so let's close. Maybe this is related to other obscure failures which you may well have fixed today.
