### ISSUE TITLE
ship with juliaX and juliaX.Y symlinks in usr/bin

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#14839]
It's often handy to ask for a particular version of Julia – e.g. 0.3 or 0.4 – without resorting to hard coding a full path. If we start making symlinks to julia0.3 or julia0.4 in usr/bin then it's easy to write scripts that use one or the other. Once we reach 1.0, it should also probably be julia1 and julia1.2 and so on.

**Comment by yuyichao** [comment]
Sould we also use version lib directory or soname at the same time?

**Comment by StefanKarpinski** [comment]
Probably.

**Comment by tkelman** [comment]
use separate build trees for this

**Comment by StefanKarpinski** [comment]
How is that helpful?

**Comment by tkelman** [comment]
Base Julia's build system should never be writing to system wide paths. You're also never building multiple versions of julia from the exact same source...

**Comment by tkelman** [comment]
Could add a makefile variable for `PROGRAM_SUFFIX` or something like that.

**Comment by StefanKarpinski** [comment]
@tkelman, you're missing the point. I don't want to build multiple julia versions in one source tree, I frequently work on systems where there are multiple installed versions of Julia and I'd like to be able to select between them in a standard way without needing to hard code paths to them. I can run `julia` if I don't care what version I get – it will be whichever one appears in my PATH first; if I want a 0.3 Julia from my PATH, I can run `julia0.3` and similarly for `julia0.4`.

**Comment by tkelman** [comment]
No, I'm just against encouraging anyone to modify their path permanently. I see two ways of going about what you want to happen here.

Option one, we create a few extra symlinks, on platforms that support them, in our makefiles - and encourage people to add the local build locations where we put these symlinks onto their path so they can type `julia-0.4` or `julia-0.5` and get different versions.

Option two, we document the one-liner to manually do `sudo ln -s /usr/local/bin/julia-$(cut -f1-2 -d. VERSION) $PWD/usr/bin/julia` and get the same result, but without any path modifications.

Either option requires one manual step for the user. I'd rather encourage the one that doesn't mess with the path.

**Comment by StefanKarpinski** [comment]
While it would be lovely if people didn't ever have to modify their paths, reality is that they often have to and do. That's how various Julia versions get found on several systems I end up working on. The combination of putting each Julia's usr/bin directory in PATH and then using `#!/usr/bin/env julia0.3` or `#!/usr/bin/env julia0.4` at the tops of scripts gets the job done. Of your two options, the first is much easier than telling people to make appropriately named symlinks themselves. But even more importantly, the first option creates a standard naming convention. Otherwise people will do the second option but they will pick their own naming scheme and this will end up being idiosyncratic and unpredictable on different systems depending on what some person decided to call the binary for various versions. I've already seen these called `julia3` and `julia4`, `julia-0.3` and `julia-0.4`, `julia0.3` and `julia0.4`, etc. A major part of the benefit of this is establishing a standard naming scheme for specific versions of the Julia executable.

**Comment by tkelman** [comment]
Well, standard naming convention among linux distributions for this kind of thing includes a dash. How is "adding to path manually" functionally any different than "make symlink/shell alias manually"? The latter is technically preferred since it doesn't also put other versions of things we also put in bin on the path. We could be breaking other software that uses llvm for example if we do that and use different versions of llvm tools. Path modification should not be our recommended solution to this problem.

**Comment by nalimilan** [comment]
The convention used by Python doesn't include a dash:
```
$ ls /bin/python*
/bin/python            /bin/python3              /bin/python3-pyinotify
/bin/python2           /bin/python3.4            /bin/python-config
/bin/python2.7         /bin/python3.4m           /bin/python-coverage
/bin/python2.7-config  /bin/python3-chardetect   /bin/pythontex
/bin/python2-config    /bin/python3-coverage
/bin/python2-coverage  /bin/python3-mako-render
```

I don't understand the debate about PATH:  if julia creates versioned symlinks in `usr/bin`, the users are free to use them how they prefer. This includes modifying their PATH to point to the Julia dir, but they may well have done that already. Or they can create symlinks using the same convention. Anyways, I see this as completely orthogonal to the present issue. Creating versioned symlinks is an improvement over the current situation, but it doesn't fix the issue of how to find the Julia executables.

**Comment by tkelman** [comment]
True. If we do this it shouldn't be in a source build though, it should be part of `make install`. Compare:
```
tkelman@ygdesk:~/Julia/julia$ ls julia-1acdfb8a56/bin
julia  julia-debug
tkelman@ygdesk:~/Julia/julia$ ls usr/bin
bugpoint             llvm-ar          llvm-link      llvm-size        pcre2grep
count                llvm-as          llvm-mc        llvm-stress      pcre2test
dnsimp               llvm-bcanalyzer  llvm-mcmarkup  llvm-symbolizer  pcre-config
fftwf-wisdom         llvm-config      llvm-nm        llvm-tblgen      pcregrep
fftw-wisdom          llvm-cov         llvm-objdump   llvm-vtabledump  pcretest
fftw-wisdom-to-conf  llvm-cxxdump     llvm-pdbdump   macho-dump       verify-uselistorder
FileCheck            llvm-diff        llvm-prof      not              yaml2obj
julia                llvm-dis         llvm-profdata  obj2yaml
llc                  llvm-dsymutil    llvm-ranlib    opt
lli                  llvm-dwarfdump   llvm-readobj   patchelf
lli-child-target     llvm-extract     llvm-rtdyld    pcre2-config
```

**Comment by StefanKarpinski** [comment]
Tony, please stop being so argumentative. Telling people to make their own symlinks doesn't address the issue establishing standard binary names. I followed the Python naming convention because it seems like the best prior art and the thing that people are most likely to be familiar with. I'm not advocating for people putting Julia's usr/bin directory in their path – I'm saying that people do this already and will continue to do so no matter what we do. I don't think this is a terribly unreasonable thing to do and we should make it work as well as possible for people who don't want to do an install that puts stuff all over their system – honestly, I hate that UNIX style approach to installing software. We should have separate bin directories that are safe to put in your path and another one where we have all the binaries that Julia itself depends on.

**Comment by tkelman** [comment]
> We should have separate bin directories that are safe to put in your path

This is exactly `bin` of a `make install` tree.

> another one where we have all the binaries that Julia itself depends on.

on unix that is `lib/julia` of an install tree and all rpaths are relative.

**Comment by ViralBShah** [comment]
I like the idea of having symlinks for julia-0.3, julia-0.4, etc. We need to start versioning libjulia as well, but that is not immediately important until other software starts depending on it, and it starts getting bundled as its own package in linux distros.

I often find myself adding multiple julia-0.x/usr/bin to my PATH, and having it be versioned is useful. Just a couple of lines to add to our make/install scripts. I would personally prefer we do this in the source build also, because that is often my primary way of working on many systems.

**Comment by tkelman** [comment]
@StefanKarpinski sorry if my disagreement is bothering you. Staying technical here - the majority of the things we put in `usr/bin` are only temporary side effects of the source build, and should not be used by anyone except for compiling and working on Julia itself. I realize this is not the case since more people are building from source than really need to, but the `make install` tree (which is local under `julia-<sha>` by default, not spread across the system unless you ask it to be) is the documented supported way in which people should be running julia for actual usage.

This is probably unrealistic to enforce or get people to change their behavior. So what I think we should do is install all the other LLVM, PCRE, FFTW and patchelf executables that are currently ending up in `usr/bin` (but only needed at build time, and should **not** be added to anyone's path) to a different location, something like `usr/tools` that is out of the way and only used at build time, to keep `usr/bin` cleaner - even though people shouldn't be using that location.

On whether or not to include a dash, gcc and llvm and quite a few other packages go with the dash convention. What should we call a versioned symlink to `julia-debug`? `julia0.4-debug`, or `julia-debug0.4`, or `julia-0.4-debug`, or `julia-debug-0.4`?

**Comment by ViralBShah** [comment]
I agree that the build time executables should be on a different path, and perhaps that should be a separate issue?

I would go with `julia-debug-0.4`.

**Comment by tkelman** [comment]
Yes I'll put together a PR. It's partially related - if we're proposing creating versioned symlinks, the only reason to put them in `usr/bin` is if we are encouraging people to use them from there. As things stand today, I don't think we should be encouraging that - or doing it ourselves for that matter. Looks like it might be a simple change to `deps/Makefile` to redirect dependency binaries somewhere other than `usr/bin` though.

**Comment by ararslan** [comment]
Something we could do is create symlinks in a separate Makefile target that isn't run by default. Something like
```
make
make symlinks LINKPATH=/magical/place
```
You can specify a path that tells `make` where to put the symlinks, with a default like `/usr/local/bin` (I'd greatly prefer local/bin to bin FWIW) or even `~/bin` (which seems to be a common place for stuff like this on Linux, though I don't use it myself).

That approach seems to me like a reasonable compromise between providing in-path symlinks with an officially vetted naming convention and not modifying outside of Julia's build directory by default.

Also FWIW I prefer a dash in the names. I currently have aliases set up as `julia-0.3`, etc.
