### ISSUE TITLE
Documentation for `tol` parameter of `eigs` confusing

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14836]
The documentation of `eigs` contains the line
```
  * ``tol``: tolerance (:math:`tol \le 0.0` defaults to ``DLAMCH('EPS')``)
```
~~~where `\le` should be `\ge` instead.~~~ which is confusing because it doesn't explain the ordinary use case of this parameter. (@jiahao - corrected)

**Comment by jiahao** [comment]
On the contrary, the documentation is correct, although arguably poorly worded in the original ARPACK documentation.

`tol` is supposed to be positive and the user is supposed to supply a positive relative tolerance.
However, if the specified tolerance is less than machine epsilon, so if you specify something smaller (like 0 or a negative value) it is capped to epsilon. The documentation is confusing since it only tells you how ARPACK handles the exceptional case.

I will edit the issue accordingly.

**Comment by jiahao** [comment]
Again my apologies to @venky18 for misunderstanding the source of his PRs.

**Comment by eschnett** [comment]
What is the default value of `tol`, if none is specified by the user?

**Comment by jiahao** [comment]
Our `eigs` wrapper specifies `tol = 0.0`, which gets passed to ARPACK's `S/NAUPD` routines depending on whether the input matrix is symmetric (S) or not (N). In both cases `tol .ne. 0.0` triggers a cap of `tol` to machine epsilon.

I'll prepare a PR fixing this issue.

**Comment by StefanKarpinski** [comment]
Since we get to see the tolerance value first, we could do something saner than what LAPACK does.
