### ISSUE TITLE
Space in array indexing causes syntax error

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#14853]
This gives the following error:

```julia
julia> A = zeros(5)
       for i in 1:3
            A[2*i -1] = 10
       end
ERROR: syntax: invalid spacing in left side of indexed assignment
 in eval at ./boot.jl:267
```

Removing the space in front of `-1` makes it work.

**Comment by simonster** [comment]
The problem is that `Int[2*i -1]` does something different from `Int[2*i-1]`, so the parser needs to parse these forms differently, and there's nothing special about `Int` vs. `A` at parse time. `x = A[2*i -1]` doesn't work either for the same reason, although perhaps that needs a better error message.

**Comment by KristofferC** [comment]
Ah, I see. Thanks! Always thought using spaces to create matrices where kinda ugly but oh well...

**Comment by StefanKarpinski** [comment]
Yes, I'd like to get rid of the space-sensitive syntax.
