### ISSUE TITLE
Operator precedence for unlisted operators & anonymous functions

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#14933]
How does precedence interact for the `operator ∘` and `operator ->`?

Looking through the [docs on operators](http://docs.julialang.org/en/release-0.4/manual/mathematical-operations/#operator-precedence), I don't see `∘` or `->` listed anywhere. Yet it seems I _am_ able to define `∘` as an operator:

``` julia
# Define a function composition operator.
julia> ∘(g,f) = x -> g(f(x))
∘ (generic function with 1 method)

# And two simple functions
julia> f(x) = x+2
f (generic function with 1 method)

julia> g(x) = x
g (generic function with 1 method)

# Composing these named functions works great.
julia> println((g∘f)(2))
4
```

But I run into trouble when using this with unnamed functions due to precedence problems:

``` julia
# This works okay.
julia> println((g ∘ x->x)(2))
2

# BUT replacing the *first* named function does not do what I expected.
julia> println((x->x ∘ g)(2))
(anonymous function)
```

This seems to be because of precedence problems:

``` julia
julia> println(((x->x) ∘ g)(2))
2
```

I have two questions:
1. What is the precedence for operators not listed on that doc page? How can we find out programmatically?
2. It seems weird that the "precedence" behavior changes depending on which side of the anonymous function declaration the `∘` is placed. Is that intended behavior? For other operators, isn't precedence commutative? Can anonymous function definitions (`operator ->`) be treated similarly?

If not, can we purposefully break the operation where the operator is before the function? i.e. make `2 * x->x` parse as `(2*x) -> x`, and fail with an error? This way, at least the behavior would be consistent, and wouldn't cause others work to figure out what's wrong with their code.

**Comment by NHDaly** [comment]
As an example of the behavior I am suggesting:

``` julia
# Allow multiplying a function's output.
julia> *(x,y::Function) = a-> x*y(a)
WARNING: module Main should explicitly import * from Base
* (generic function with 139 methods)

# This is correctly bad.
julia> (2*x) -> x
ERROR: syntax: "*(2,x)" is not a valid function argument name

# This should also be bad (since x -> x * 2 would mean something very different).
julia> 2 * x -> x
# Maybe this should throw the same error:
ERROR: syntax: "*(2,x)" is not a valid function argument name
# Instead of what it currently actually outputs:
(anonymous function)

# And only this should be okay.
julia> 2*(x -> x)
(anonymous function)
```

Thoughts? This way, `->` has consistent operator precedence as anything else.

Thanks for your time!

**Comment by stevengj** [comment]
You can find out the precedence of operators via `Base.operator_precedence(:∘)`: this returns a bigger number, and the bigger the number the higher the precedence.

In particular, you can see that `∘` has the same precedence as `*`, so `x -> x ∘ 1` is parsed as `x -> (x ∘ 1)`.

  However, if you have an expression like `g ∘ x -> x`, it will be parse as `g ∘ (x -> x)`, because parsing it as `(g ∘ x) -> x` is impossible: the left operand of `->` must be an identifier.

**Comment by JeffBezanson** [comment]
Unicode provides a large number of operators and the table in the docs could get a bit overwhelming if we listed them all. Maybe we should anyway? One can see the full list at the top of https://github.com/JuliaLang/julia/blob/c200b4cdb9620b6df369ae3c735cf3af30b6a47f/src/julia-parser.scm

It looks like we gave `∘` multiplication-like precedence. I'm not sure what its standard precedence is, or if it has one.

Yes, `->` has asymmetric precedence because it is very asymmetric: very few things can go on the left side (basically only a symbol or symbols) but any expression can go on the right side. `x->y=x` is a valid function that contains an assignment. So `->` would have to have lower precedence than `=`, but then you couldn't write `f = x->x`, you'd have to parenthesize the function every time.

**Comment by stevengj** [comment]
The precedence of Unicode operators was discussed in #6929.  I think `∘` was given multiplication precedence because [U+2218](http://www.fileformat.info/info/unicode/char/2218/index.htm) is documented as the "ring operator", which I understood as the "multiplication" operator for a generic ring.  But it is also documented as "composite function", i.e. function composition, so this could argue for `->` precedence.

It might be nice to have a list of allowed operators, sorted into groups by precedence (just copied from `julia-parser.scm`) in the docs.

**Comment by mbauman** [comment]
`->` is effectively a more restrictive right-associative assignment, isn't it?  I think the "only" breakage from removing this special case are custom infix operators that take function arguments on the RHS like `∘` above… and of course uses in macros and DSLs.  Probably not worth futzing with, but it would allow `x,y -> x+y` and even `f = x,y -> x[1] = y`.

**Comment by StefanKarpinski** [comment]
Not having to use parens on lambda arguments would be quite nice.

**Comment by JeffBezanson** [comment]
That syntax does not work terribly well inside an argument list.

**Comment by StefanKarpinski** [comment]
True, true.

**Comment by NHDaly** [comment]
> You can find out the precedence of operators via the (undocumented) function Base.operator_precedence(:∘)

@stevengj: Thanks for the tip! It would be great to put this in the documentation somewhere! Maybe [here](http://docs.julialang.org/en/release-0.4/manual/mathematical-operations/#operator-precedence)?

> It might be nice to have a list of allowed operators, sorted into groups by precedence (just copied from julia-parser.scm) in the docs.

+1 Maybe similar to [the cppreference docs](http://en.cppreference.com/w/cpp/language/operator_precedence).

**Comment by NHDaly** [comment]
I agree with everyone above, regarding `=` and `,`. Those would definitely be more confusing if `->` bound symmetrically on the right and left.

Could we still just loosen the binding a bit on the left side so that some other operations *do* bind symmetrically? We could leave the very tightly binding things such as `=` `,` and maybe `&&`/`||`, and change the rest to bind more tightly (`*`, `+`, `>`, etc.)?


I think part of the problem for me is that in a lot of other languages you need to delineate your lambda with something like braces, so it's more clear where the function definition starts and ends.

**Comment by nalimilan** [comment]
> @stevengj: Thanks for the tip! It would be great to put this in the documentation somewhere! Maybe here?

Sounds like a good idea. Could you make a PR for that?

**Comment by stevengj** [comment]
Since `operator_precedence` is not exported, I'm not convinced we should be documenting it (as opposed to just documenting the operator precedences).

**Comment by NHDaly** [comment]
Sorry I never followed up with this! Here's a small docs PR that puts this information in the documentation!

I did not make a larger, all-operators precedence table, but I think this is a good first step.
