### ISSUE TITLE
big(pi) value last 3 digits are incorrect 

### ISSUE THREAD

**Issue by haniyehia** [JuliaLang/julia#14974]
I have "pi" as a hobby and, checking the high precision value obtained with function "big", obtained

julia> big(pi)
3.141592653589793238462643383279502884197169399375105820974944592307816406286198

The last 3 digits differ from the values available in the web:
(e.g. http://oeis.org/A000796 and http://www.piday.org/million/)

3.141592653589793238462643383279502884197169399375105820974944592307816406286208

It is a small difference, but may be relevant.

**Comment by mauro3** [comment]
I think this is due to the finite precision of the floating point number and its translation to decimal:
```
julia> set_bigfloat_precision(2^8) # usual precision of big
256

julia> big(pi)
3.141592653589793238462643383279502884197169399375105820974944592307816406286198

julia> eps(big(pi))
3.454467422037777850154540745120159828446400145774512554009481388067436721264971e-77

julia> set_bigfloat_precision(2^9)
512

julia> pi256 = big"3.141592653589793238462643383279502884197169399375105820974944592307816406286198"
3.14159265358979323846264338327950288419716939937510582097494459230781640628619800000000000000000000000000000000000000000000000000000000000000000000000000014

julia> pi256_eps = big"3.454467422037777850154540745120159828446400145774512554009481388067436721264971e-77"
3.45446742203777785015454074512015982844640014577451255400948138806743672126497099999999999999999999999999999999999999999999999999999999999999999999999999982e-77

julia> pi256+pi256_eps
3.14159265358979323846264338327950288419716939937510582097494459230781640628623254467422037777850154540745120159828446400145774512554009481388067436721264985
```
This last number is now bigger than the correct pi, thus the printed one is within the eps distance.

But maybe `show`  could be improved to not print those last incorrect digits?  I think that is what's done for normal floats.

**Comment by simonbyrne** [comment]
`big(pi)` just gives the closest `BigFloat` to `pi` (using the current `BigFloat` precision).

The number of decimal digits printed is intentionally chosen such that conversion back to binary will give the exact number: see [here](http://www.exploringbinary.com/number-of-digits-required-for-round-trip-conversions/) for an explanation of how this works.

For normal floats we're slightly more clever: we instead print the shortest decimal string that will correctly round to the exact value. Unfortunately, this is much more difficult to compute, and finding efficient ways to do this is an open research problem.

**Comment by oxinabox** [comment]
For reference on anyone later reading this and thinking that pi is a Float64 (like I did).
pi is not a Float64, pi is a magically mathconst that knows how to convert itself to various different forms see #3294 (is that in docs anywhere?)

And thus this is **not** the same as the python user mistake corrected in http://stackoverflow.com/a/33818692/179081 (and no doubt  other places on the web).

(Just for reference, this doesn't change anything already said.)

**Comment by simonbyrne** [comment]
Good point @oxinabox: it doesn't appear to be documented, we should have something.

**Comment by yash14123** [comment]
I would like to take this issue.

**Comment by StefanKarpinski** [comment]
By all means, make a pull request.

**Comment by ayushi19031** [comment]
So, can I mention this in the documentation of Julia, and make a pull request? 
Because as per the above discussions, making change to the actual variable in the code might not be feasible due to the finite precision of the floating point number and its translation to decimal.

**Comment by StefanKarpinski** [comment]
The situation is that this:

- `big(pi)` produces the closest `BigFloat` to the true value of `pi`

- printing that value as a decimal is correct in the sense that the printed value parser back to BigFloat (with the same precision) will give the same value back.

The expectation that printing the decimal digits of `big(pi)` will match the decimal digits of `pi` all the way to the end of what's printed is unwarranted. Even if we had the same kind of "smart shortest decimal printing" behavior for `BigFloats` I don't think that would hold. First of all, `pi != big(pi)`: you've lost precision there already, and due to _correct_ rounding even in binary the last bit(s) of `big(pi)` may disagree with the corresponding bits of the binary expansion of `pi`. In addition, more disagreement may be introduced by printing a binary value in decimal. There are many correct decimal strings that represent the same binary value. It is, in general, hard to define a unique one to print and then computing that one is even harder. It's been thoroughly studied for fixed precision formats like Float32 and Float64 but MPFR doesn't offer anything like this—it prints a correct string but makes no guarantees about which correct string it prints.

Anyway, I'm not sure where in the manual this kind of information would go, but if you can find a good place it would be fine to add.

**Comment by StefanKarpinski** [comment]
Example of an exact rational value where rounding to the closest binary value causes all binary digits to disagree:

- `x = sum(2.0^-p for p = 1:10)` which is exactly equal to `1023//1024`
- This value has the following representation as a binary string: `0.1111111111`
- That isn't `x`'s only representation as a binary string, there's also this one: `0.1111111110111111...`
- If we round `x` to eight significant bits, then we get the exact value 1
- The typical binary printing of 1 to eight binary digits is `1.0000000`
- Which disagrees with binary string representation of the exact value `x` in *all* significant places

This happens because we round the last significant digit up since it's followed by `11` and carry all the ones. The same thing happens when convert `pi` to `BigFloat` except that there are a lot more significant digits and the bits of `pi` aren't all ones, so the bit carrying stops closer to the end, but this does already cause the last few bits of `big(pi)` to disagree with the corresponding bits of `pi` depending on where the rounding occurs based on the current precision.
