### ISSUE TITLE
Bug in simple base Dict calls results in lost keys

### ISSUE THREAD

**Issue by slundberg** [JuliaLang/julia#15077]
The example below shows a simple Julia dictionary forgetting about a key it was given. I ran across this while building millions of dictionaries from a dataset, so it is a rare case (but a very troubling one). Essentially it seems a key somehow gets added to the slots past the maxprobe length from its original hash. This causes it to be unretrievable. I am using Julia 0.4.1 (but base/dict.jl does not change for 1.4.3).

```julia
badKeys = ASCIIString["FINO_emv5.0","FINO_ema0.1","RATE_ema1.0","NIBPM_ema1.0",
    "SAO2_emv5.0","O2FLOW_ema5.0","preop_Neuro/Psych_","gender_",
    "FIO2_ema0.1","PEAK_ema5.0","preop_Reproductive_denies","O2FLOW_ema0.1",
    "preop_Endocrine_denies","preop_Respiratory_",
    "NIBPM_ema0.1","PROPOFOL_MCG/KG/MIN_decay5.0","NIBPD_ema1.0","NIBPS_ema5.0",
    "anesthesiaStartTime","NIBPS_ema1.0","RESPRATE_ema1.0","PEAK_ema0.1",
    "preop_GU_denies","preop_Cardiovascular_","PIP_ema5.0","preop_ENT_denies",
    "preop_Skin_denies","preop_Renal_denies","asaCode_IIIE","N2OFLOW_emv5.0",
    "NIBPD_emv5.0", # <--- here is the key that we later can't find
    "NIBPM_ema5.0","preop_Respiratory_complete","ETCO2_ema5.0",
    "RESPRATE_ema0.1","preop_Functional Status_<2","preop_Renal_symptoms",
    "ECGRATE_ema5.0","FIO2_emv5.0","RESPRATE_emv5.0","7wu3ty0a4fs","BVO",
    "4UrCWXUsaT"]

d = Dict{AbstractString,Float64}()
for k in badKeys
    d[k] = 1
end
problemKey = "NIBPD_emv5.0"
println("Is key in dict by looking: ", problemKey in collect(keys(d)))
println("Is key in dict with haskey(): ", haskey(d, problemKey))
println("Try and get the value for the key...")
d[problemKey]
```

produces

```
Is key in dict by looking: true
Is key in dict with haskey(): false
Try and get the value for the key...
LoadError: KeyError: NIBPD_emv5.0 not found
while loading In[133], in expression starting on line 23

 in getindex at dict.jl:718
```

**Comment by StefanKarpinski** [comment]
This is a pretty embarrassing bug – I'm very sorry about that and thank you for reporting it. Here's what I've figured out so far. This exhibits a bad hash collision situation in [`ht_keyindex`](https://github.com/JuliaLang/julia/blob/3c1f2d322c995b77778e8849be6e9fda5fabe32a/base/dict.jl#L583-L605). We have

```jl
sz = 256
maxprobe = 16
index = 58
```

Here are the keys stored in the dict, starting at index 58:

```jl
julia> keys[58:58+17]
18-element Array{AbstractString,1}:
 "NIBPM_ema5.0"
 "preop_ENT_denies"
 "preop_Skin_denies"
 "preop_Renal_denies"
 "RESPRATE_ema0.1"
 "RESPRATE_emv5.0"
 "asaCode_IIIE"
 "preop_Respiratory_complete"
 "ETCO2_ema5.0"
 "preop_Functional Status_<2"
 "preop_Renal_symptoms"
 "ECGRATE_ema5.0"
 "FIO2_emv5.0"
 "4UrCWXUsaT"
 "N2OFLOW_emv5.0"
 "7wu3ty0a4fs"
 "BVO"
 "NIBPD_emv5.0"
```

The key we're looking for occurs at the 17th slot after the initial hash index. Since `maxprobe` is 16, the function gives up before getting there and returns `false`. I'm not sure what the right solution is.

cc @JeffBezanson

**Comment by slundberg** [comment]
Thanks for looking into it. My assumption is that the hash table should get resized before anything ends up past the maxprobe length, but I couldn't figure out quickly why that was not occurring here.

**Comment by JeffBezanson** [comment]
Thanks for the high-quality bug report; it made this relatively easy to track down. I believe the problem is in `rehash!`. It assumes that growing the table will not lead to worse key-bunching than before, but this is a pathological case where that doesn't hold, and growing the table makes the crowding at index 58 even worse.

**Comment by slundberg** [comment]
Glad it was helpful. I have come to like (and hence use) Julia a lot, so it is good to see it get sorted out. thanks.

**Comment by vtjnash** [comment]
still broken it seems:
```julia
julia> type FooBar
         x
       end

julia> Base.hash(::FooBar) = 1

julia> Base.(:(==))(a::FooBar, b::FooBar) = a.x==b.x

julia> x=Dict()
Dict{Any,Any}()

julia> for i = 1:100; x[FooBar(i)] = i end

julia> FooBar(4) in keys(x)
false

julia> versioninfo()
Julia Version 0.5.0-dev+2694
Commit f8e4211* (2016-02-16 18:32 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.3.0)
  CPU: Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by kmsquire** [comment]
The fix makes the assumption that the actual hash values that map to the
same location are different. Your test violates that assumption.

The question then is, is that a reasonable assumption to make?

**Comment by vtjnash** [comment]
a hash function makes no such guarantee (that would be a perfect hash). `hash(x) = 1` is a valid hash function (since `isequal(a, b) implies hash(a) == hash(b)` but not the reverse) and its the easiest way to test for the edge case of large numbers of hash collisions (instead of trying to find these 100 hash collisions manually).

**Comment by El-Zurdo-Sordo** [comment]
@vtjnash, that is correct. I think that the probing in dict.jl shouldn't stop until it gets back to the original starting location.  There is no guarantee that a hash function will be good enough to ever fall below the "maxsprobe" value of 16.  Maybe a better heuristic for the expansion would be if the Dict is more than 60%-70% full (which is where this sort of hash table starts to perform badly).

**Comment by JeffBezanson** [comment]
But maxprobe is determined by the dictionary size; it is not fixed at 16. For any number of collisions, there is a dictionary size with a maxprobe that will work, and we will eventually grow to that size. @vtjnash That test case seems to work if you define `hash(::FooBar, ::UInt)` instead.

**Comment by vtjnash** [comment]
ah, good call. defining `Base.hash(::FooBar, ::UInt) = 1` fixes my example

**Comment by tkelman** [comment]
backport label is on the PR

**Comment by vtjnash** [comment]
https://groups.google.com/d/msg/julia-users/azdTHOMS2Dg/G3cdlvW_BAAJ

**Comment by JohnHBrock** [comment]
I'm still seeing missing keys on v0.4.5. Can the changes in 58aa57c7a69256b1b1c81e58d8dff351522f353d be backported?

**Comment by ivarne** [comment]
I'm not sure (dictionary implementation is above my skills), but I've added a ``backport pending 0.4`` label on #15176, so lets hope someone opens a PR against `release-0.4` with tests and fix.

**Comment by cbecker** [comment]
Hi, I think I stumbled upon this bug, and even with the master branch I am still getting some issues (see below).

The problem is that I cannot seem to reproduce this in a simple piece of code, as creating a raw dict and filling it in with the right values doesn't trigger it.

I have some more tricky code that populates M.valueTable below. I am still trying to get a smaller working example, but any ideas a welcomed.

```julia
julia> M.valueTable
Dict{Array{UInt8,1},Float64} with 10 entries:
  UInt8[1,1,2,0,2,0,0,0,0] => 0.0
  UInt8[2,2,1,0,1,0,1,0,0] => 1.0
  UInt8[0,0,0,0,0,0,0,0,0] => 0.0
  UInt8[1,0,0,0,0,0,2,0,0] => 0.0
  UInt8[2,0,0,0,0,0,1,1,0] => 0.0
  UInt8[1,1,1,0,0,2,2,2,0] => 1.0
  UInt8[0,0,0,0,0,0,1,0,0] => 0.0
  UInt8[2,2,0,0,0,1,1,1,0] => 0.0
  UInt8[1,0,0,0,2,0,0,0,0] => 0.0
  UInt8[0,0,0,0,1,0,0,0,0] => 0.0

julia> for k in keys(M.valueTable)
         @show M.valueTable[k]
       end
M.valueTable[k] = 0.0
M.valueTable[k] = 1.0
M.valueTable[k] = 0.0
M.valueTable[k] = 0.0
ERROR: KeyError: UInt8[2,0,0,0,0,0,1,1,0] not found
 in getindex(::Dict{Array{UInt8,1},Float64}, ::Array{UInt8,1}) at ./dict.jl:777
 [inlined code] from ./show.jl:166
 in anonymous at ./<no file>:4294967295
 in eval(::Module, ::Any) at ./boot.jl:236
```

**Comment by yuyichao** [comment]
This will happen if you mutate the key.

**Comment by cbecker** [comment]
Thanks, that seems to be the problem.
It was tricky to find, but I had to make sure I was copying the key before using it so a reference was not modified later. Sorry for the false alarm.
