### ISSUE TITLE
Relative module path inconsistency?

### ISSUE THREAD

**Issue by colinfang** [JuliaLang/julia#15134]
We have to use relative path to `using` a nested module.

```{julia}
    module Parent
        module Utils
            type B end
        end
        using .Utils  # or using Parent.Utils
    end
```

But here we cannot have leading `.` to access the internal symbols.

```{julia}
    module Parent
        module Utils
            type B end
        end
        Utils.B # or Parent.Utils.B
    end
```

The behaviour seems a bit confusing to me. What is the design purpose to have these 2 different?

**Comment by yuyichao** [comment]
The leading `.` is a special syntax for relative import and is not valid anywhere else.

When you define a module, the name is implicitly available/imported so the name is available in the outer module and you can use the module name (without fully qualifying it) directly to access the newly defined module. However, this cannot be done with relative import since you are giving the runtime a path to the module rather than an object (or an identifier/name in the current scope) and therefore a special syntax is needed for raletive import in order to distinguish a relative import from a global import.
