### ISSUE TITLE
Rational{T} constructor doesn't work when denominator is typemin{T}

### ISSUE THREAD

**Issue by pkofod** [JuliaLang/julia#15225]
Trying to work out #15215 I ran a lot of random comparisons of the old method and my new proposal. There I stumbled upon a bug. When trying to construct `Rational(rand(T), typemin(T))` I found that it fails, because `div(typemin(T), -1)` (which happens sometimes) of course overflows. 
(for `T=Int64`:
 `-1*typemin(Int64) == -1*(-9223372036854775808) > 9223372036854775807 == typemax(Int64)`
)

The problem arises because `Rational()` wants to simplify the fraction, but apart from that, I guess there is no reason for the constructor to fail. At least it should give an error saying "Can't simplify fraction when denominator is typemin(T), and gcd(num, den) == -1`.

(this really emphasizes the importance of tests covering not just all lines, but also things like `typemin` or `typemax` cases` for things like rationals, and other edge cases)

**Comment by jiahao** [comment]
Related: #5796

Maybe we need `Base.checked_div` and `Base.checked_gcd` functions

**Comment by pkofod** [comment]
I am totally sympathetic to performance wants in things like `gcd`, `abs` and so on, but in a constructor like `Rational` you might still want to be able to construct the mentioned number. I think there is a difference between very basic, performance critical functions, and then a constructor like `Rational`. The functions you propose could allow that, without perf regressions in functions using `abs`, `gcd`, ...

**Comment by eschnett** [comment]
`Base.checked_div` exists. In fact, since division is somewhat expensive, it is actually just a wrapper around `div`, which already does the checking.

That means you probably only need `Base.checked_gcd`. It seems that changing the `abs` in `gcd` to `checked_abs` should suffice. And since a checked `abs` is cheap (compared to `rem`), that could even be the default behaviour.

**Comment by pkofod** [comment]
I think the consensus (?) in the other issue was that if `-x` is not overflow checked, neither should `abs` be. I'd be willing to have a go at this, but I'm not going to spend time changing `abs` if the PR is going to loose a majority vote ;) Good to know `checked_gcd` exists. At least that could be changed right now.

**Comment by nalimilan** [comment]
The idea isn't to change `abs`, it's to change the call to `abs` in `gcd` to make it safe.

**Comment by pkofod** [comment]
>  And since a checked abs is cheap (compared to rem), that could even be the default behaviour.
That was the part I was commenting on.

**Comment by nalimilan** [comment]
I think he meant "the default behaviour for `gcd`.

**Comment by pkofod** [comment]
To be honest, `Rational` should probably just check if `gcd(den, num) == 1 && den == typemin(T)` and throw an error. Since it can't be reduced, and the setup is such that `den` is always positive, it is going to fail even if we check `abs` and `gcd`.

**Comment by eschnett** [comment]
Yes, I meant changing the call to `abs` in `gcd` to `checked_abs`. That's a small and cheap change, and will help all `gcd` callers detect these errors.

`Rational` should probably not have a check involving `typemin`, since there might be other implementations of `Integer` that don't have such a restriction, such as e.g. `BigInt`. It's much cleaner to put this check into the integer arithmetic, than teaching the rational arithmetic about all the shortcomings of all integer arithmetic implementations.

**Comment by vtjnash** [comment]
@eschnett what's left for this issue?

**Comment by pkofod** [comment]
I think what's left is that the checked gcd should be used in the `Rational` constructor, right?

**Comment by Liozou** [comment]
Fixed by #32572?

**Comment by pkofod** [comment]
Appears so. I just thing it should have said "fixes" not "fix" in the original comment of that PR.
