### ISSUE TITLE
Float16 gets promoted to Float64 when multiplied by pi

### ISSUE THREAD

**Issue by Evizero** [JuliaLang/julia#15359]
I just discovered this and found it strange enough to report. Might be related to https://github.com/JuliaLang/julia/issues/5942

Basically when multiplying a `Float16` with `pi` it results in a `Float64`, while a `Float32` multiplied by `pi` results in a `Float32`

``` julia
julia> typeof(Float16(.5) * pi)
Float64

julia> typeof(Float32(.5) * pi)
Float32

julia> typeof(Float64(.5) * pi)
Float64
```

**Comment by Synthetica9** [comment]
This behavior stems from `irrationals.jl`. At the top of this file, there are the following lines:

```julia
promote_rule{s}(::Type{Irrational{s}}, ::Type{Float32}) = Float32
promote_rule{s,t}(::Type{Irrational{s}}, ::Type{Irrational{t}}) = Float64
promote_rule{s,T<:Number}(::Type{Irrational{s}}, ::Type{T}) = promote_type(Float64,T)
```

What this means is that `Float32` with an irrational explicitly converts to `Float32`. `Float16` doesn't have this exception, so it follows the more general rule in the third line, and promotes to `Float64`. This seems to be intentional; but it might be worth changing the first line to `promote_rule{s, T<:AbstractFloat}(::Type{Irrational{s}}, ::Type{T}) = T` to fix this and other issues.

**Comment by StefanKarpinski** [comment]
This goes back to the old debate about whether Float16 is a "computational type" or just a storage type, and what those terms even mean. I think we've gone in favor of treating Float16 as computational even though its operations aren't supported directly by hardware. So by that line of reasoning yes, we should make that change.

**Comment by JeffreySarnoff** [comment]
+Float16(1.0) for the change
I compute with Float16, often using it to test floating point algorithmics when there are too many relevant Float32s for the time allotted.  Once cleared using Float16, usually it is ok to apply a narrower test to Float32|64 values.  I do not want to have to be a Float16 sheriff.
