### ISSUE TITLE
use DateTime consistently in Base for `time()` / `now()` / `stat()` / etc.

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#15405]
part of the reason DateTime was added to base is so that times could be expressed consistently as objects (locale-aware and dimension) rather than raw numbers (Float64)

**Comment by denisli** [comment]
Is this issue still open? I'm new here and would like to try this out if it is still open.

But I have trouble finding where these changes need to be made. Are you referring to the time() method which currently returns Int? I cannot find where it is implemented. Also, Dates.now() already returns DateTime. I also am not sure what stat() means. I cannot find a stat() method that relates to time.

Thanks.

**Comment by quinnj** [comment]
@denisli, yes this issue is still opening. Take a look in the Libc.jl file/module for the stat/time functions.

**Comment by lbollar** [comment]
I was also interested in contributing on this, mostly as a way to learn to contribute on something similar. 

I see the function for time() in Libc.jl module. 

Is this as simple as rewriting time to:

time() = Dates.now(Base.Dates.UTC)

or creating a default time() that uses Dates.now() and then another that takes TimeZone type for argument?

Just learning to contribute, sorry for any lack of understanding.

**Comment by tkelman** [comment]
I'm not sure if this is the best thing to do given #5155 and the desire for modularity. Wouldn't it be more idiomatic to make most of these accept an output type argument, then you could choose what output type (and module dependencies) you want? If we want to change the default to depend on Dates types, then Dates should define the version without an output type argument, rather than Base.

And what's the deprecation path here?

**Comment by JeffBezanson** [comment]
I would say

1. This might be a case where we should separate the DateTime type and basic functions from date and period math; maybe a DateMath library.
2. It seems silly for Base to export both `now` and `time` (`time` is also unrelated to `@time`, and so a bit confusing). `time` should be un-exported and possibly deprecated entirely.
3. The purpose of the Libc module is to wrap libc functions, so `Libc.time` should return the same value that the libc function returns. If that's not useful, deletion is always an option. File mtime is a borderline case; our `mtime` can probably return a DateTime if we want.

**Comment by praveshcj** [comment]
Hello. Is this issue still open? I am new to open source contributions and would like to start working with this issue.

**Comment by StefanKarpinski** [comment]
I think we're really moved in the other direction here and fortuitously ended up where we should be: Base uses UNIX timestamps for time and does not depend on the Dates package. Only if you want to work with Date and DateTime objects do you depend on Dates and you can use `now()` instead of `time()`. This seems like a good and reasonable division and allows Dates to live entirely outside of Base cleanly.
