### ISSUE TITLE
Testall fails in arrayops mdsum()

### ISSUE THREAD

**Issue by colbec** [JuliaLang/julia#15420]
In 

```
versioninfo()
Julia Version 0.5.0-dev+3071
Commit ec6f886* (2016-03-09 04:38 UTC)
Platform Info:
  System: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1
```

Seen:

```

    From worker 4:       * tuple                 in   1.18 seconds, maxrss  933.95 MB
    From worker 3:       * arrayops             Test Failed
    From worker 3:    Expression: mdsum(B) == 15
    From worker 3:     Evaluated: 5.0 == 15
```

Full output in https://gist.github.com/colbec/781cffe4b0218366a326
I am currently retesting to ensure that it will repeat.

FWIW the second and third tests ran correctly.

**Comment by tkelman** [comment]
Hey again @colbec. I've indeed seen this one on CI for a while. Possibly the same underlying cause as https://github.com/JuliaLang/julia/issues/15271 since I think they started happening around the same time, but hard to say for sure. Maybe running these using https://github.com/mozilla/rr (and their new chaos mode feature?) would be the most effective path towards isolating it.

**Comment by colbec** [comment]
FWIW the second test ran correctly. Order of reporting is the same, with `numbers` and `reduce` reporting before the happy `arrayops`. This makes sense, in the error run `arrayops` finished early. `Numbers` and `reduce` report really fast, so this indicates that `arrayops` failed early. Previously the same worker used by `arrayops` was running `staged`. If `staged` left something odd behind would this trip `arrayops` early?

**Comment by KristofferC** [comment]
Please open if this happens again.
