### ISSUE TITLE
repeat is unnecessarily slow

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#15553]
```
julia> @time n = repeat(collect(1:20000), inner=[84], outer=[1]);
  1.439516 seconds (20.03 M allocations: 523.687 MB, 4.77% gc time)
```

Writing the loops manually is 100x faster.

Unfortunately I can't think of any easy way to fix the general case that doesn't involve generated functions.

**Comment by nalimilan** [comment]
Cf. https://github.com/JuliaLang/julia/pull/14082

**Comment by JeffBezanson** [comment]
I believe we could at least do block copy operations instead of computing the position of every element individually. Instead of constructing an array of scalar indexes, construct an array of ranges for each element to handle `inner`, initially constructing only one of the `outer` copies. Then that data just needs to be copied to handle `outer`. The case of `inner` being all 1s can be optimized as well.

**Comment by stevengj** [comment]
(Benchmark added to BaseBenchmarks.)
