### ISSUE TITLE
JIT function lookup broken on LLVM svn

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#15582]
The backtrace (pc pointers) is good but the function name/info lookup for JIT functions are broken.

It seems to be broken by https://github.com/JuliaLang/julia/pull/15519 @vtjnash

**Comment by vtjnash** [comment]
it looks like llvm switched to taking a pointer to the section (https://github.com/JuliaLang/julia/pull/15567/files#diff-d4b80bf89e46982070f234dd7cc344a9R382), but in #15519, i switched to iterating over the debug object (because that's the object that gets saved and it made computation of the section `slide` a bit easier) instead of the loaded object.
