### ISSUE TITLE
run() fails for programs requiring admin access on windows

### ISSUE THREAD

**Issue by c42f** [JuliaLang/julia#15598]
Demo (windows 7, official 0.4.5 windows package)

```
julia> run(`regedit`)
ERROR: could not spawn `regedit`: unknown error (UNKNOWN)
 in _jl_spawn at process.jl:262

julia> run(`cmd /c regedit`)
# Runs fine after clicking ok to the popup box
```

The motivating use case was that I'm trying to install windows binaries for Proj4 via the Osgeo4w package manager (based on cygwin's package manager I believe), see http://download.osgeo.org/osgeo4w/setup.exe.  This setup program unfortunately requires admin access, even though the install will go into a local deps folder.  Hacking the embedded manifest to remove the permissions allows osgeo4w setup.exe to run, but other things go wrong down the line.

**Comment by vtjnash** [comment]
error message seems slightly better now:
```
julia> run(`regedit`)
ERROR: IOError: could not spawn `regedit`: permission denied (EACCES)
```

The problem is this requires a complicated RPC call which is part of the Win32 shell, not the kernel (https://learn.microsoft.com/en-us/windows/win32/shell/launch). Seems like a much better design than unix's sudo/su. But hard to see how to use it well in integration here.
