### ISSUE TITLE
bin, dec, oct, hex all fail with BigInt and padding argument 

### ISSUE THREAD

**Issue by arghhhh** [JuliaLang/julia#15601]
``` julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+3235 (2016-03-23 05:32 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit c29bff1* (0 days old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> bin( big(100) ,10)
ERROR: argument is an abstract type; size is indeterminate
 in convert(::Type{Unsigned}, ::BigInt) at ./gmp.jl:182
 in unsigned(::BigInt) at ./int.jl:78
 [inlined code] from ./gmp.jl:344
 in bin(::BigInt, ::Int64) at ./intfuncs.jl:306
 in eval(::Module, ::Any) at /Volumes/Julia-0.5.0-dev-c29bff1462/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:-1

julia> 
```

**Comment by KlausC** [comment]
I made the same observation. Julia Version 0.5.0.
Reason seems to be the functions hex(x::Integer, p::Int) etc. are calling hex(unsigned(x), p, x<0) intfuncs.jl:341. The unsigned(::BigInt) unfortunately fails because BigInt cannot be converted to Unsigned.
In order to resolve the issue, there should be implementations of hex(x::BigInt, p::Int) etc. in gmp.jl, extending the existing implementations of hex(::BigInt) etc. gmp.jl; they are all calling base(b::Int, x::BigInt).
The implementation of base() calls __gmp__get_str() in libgmp, which has no arguments to specify the padding size.

**Comment by KlausC** [comment]
proposed solution: in case padding is needed make a copy of x::BigInt and modify value in order to add one non-zero digit at the leftmost padding position. After calling get_str() replace the digit by a zero character in the output string.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/18849

**Comment by jiahao** [comment]
I don't think this issue is fully resolved yet.  [Both methods](https://github.com/JuliaLang/julia/blob/7aba3f57bcd370c7bda2a3df4ba6cecf3553df33/base/gmp.jl#L180-L200) for `convert(Unsigned, big(100))` and `convert(Signed, big(100))` would still fail on master with the "argument is an abstract type" error. Some clear options here:

1. Try to convert to `Int` or `UInt`, else throw a run time error if the `BigInt` is too big.
2. Always throw a run time error.

**Comment by yuyichao** [comment]
> I don't think this issue is fully resolved yet.

Yes it is. Both this issue and #18849 are about `bin`, `dec`, `oct`, `hex` on `BigInt` and that is indeed fixed on master.

The error thrown by `convert(Unsigned, ::BigInt)` and `convert(Signed, ::BigInt)` are not what either of the issue is about. If you think we need a better implementation / more specific error that should be a different issue.
