### ISSUE TITLE
Cannot easily configure Julia to build with gcc on OS X

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#15751]
I believe that setting `USEGCC=1` should suffice to build Julia with gcc.

However, on OS X, Julia prefers clang, and overwrites the user's settings. To build with gcc nonetheless, one has to override Julia via

```
override USEGCC=1
override USECLANG=0
override USE_LIBCPP=0
```

in `Make.user`. (The `override` is necessary to ensure that Julia's overwriting cannot happen; one has to use it for every configuration variable that Julia tries to enforce on OS X.)

Ideally, Julia should honour a `USEGCC=1` even on OS X. If that's not feasible, then the above should be documented.

Thanks to @staticfloat for finding this out; see #15647 for a related discussion.

**Comment by lbenet** [comment]
Just curiosity: do you have a preferred configuration for a Mac ? I'm having in mind performance...

**Comment by staticfloat** [comment]
In our testing we haven't found a large difference in Julia performance between `clang` and `g++`; just using the defaults should work fine.

**Comment by lbenet** [comment]
Thanks for the comment. I use the defaults as well, but was wandering if it was worth changing.

**Comment by staticfloat** [comment]
As it stands now, I cannot build openlibm with `g++` on OSX because of some problems with the old version of the assembler that `g++` uses.  See [this](https://github.com/JuliaLang/openlibm/issues/9#issuecomment-212539115) and [this](https://github.com/JuliaLang/openlibm/issues/84#issuecomment-187827298) for more detail.
