### ISSUE TITLE
OSX failing travis fairly often

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#15808]
Builds are failing with "No output has been received in the last 10m0s". The first instance seems to be here: https://travis-ci.org/JuliaLang/julia/jobs/120808578

It's possible that we're doing something that takes more than 10m while producing no output --- maybe creating sys.o?

**Comment by yuyichao** [comment]
Could be compileall?

**Comment by tkelman** [comment]
It's probably compile-all's fault, we should move that testong somewhere else. The tests should be just barely fast enough now to go back to full coverage testing instead of compile all on mac travis, but the fact that homebrew did a big repository split and travis hasn't updated their osx images means `brew update` now takes maybe 90 seconds on travis. Once travis updates the osx images with latest homebrew we can try going back to full test coverage again.
