### ISSUE TITLE
writedlm ignores delimiter

### ISSUE THREAD

**Issue by ethomag** [JuliaLang/julia#15856]
I expect a ',' (comma) between the values below and I believe I got that a few days ago on the Julia master branch. 
```
$ ./julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+3505 (2016-04-12 23:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 18a6722* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> writedlm(STDOUT, [1:4;], ',')
1
2
3
4
```

**Comment by nalimilan** [comment]
That's because `[1:4;]` is a vector, implicitly taken as a 1-column matrix, so you have only one number per line. Transpose the vector if you want a 1-row matrix: `writedlm(STDOUT, (1:4)', ',')`. Note that you can also use `join(1:4, ',')` if all you need is a string with values separated by a comma.
