### ISSUE TITLE
UnitRange Performance

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaLang/julia#16063]
I did a benchmark and found that summing a UnitRange is slower than summing the equivalent array:

``` julia
function sumit{T}(arr::AbstractArray{T})

  val = zero(T)
  for i=1:length(arr)
    val += arr[i]
  end

  return val
end

rng = 1:10000000
rng_arr = collect(rng)

@time sumit(rng)
@time sumit(rng_arr)

println("final results:")
println("sizeof(array) = ", sizeof(rng_arr))
@time sumit(rng)
@time sumit(rng_arr)
```

results:

```
$ julia4 --check-bounds=no ./tmp.jl 
  0.039517 seconds (2.28 k allocations: 118.851 KB)
  0.013272 seconds (1.98 k allocations: 100.646 KB)
final results:
sizeof(array) = 80000000
  0.036911 seconds (5 allocations: 176 bytes)  # UnitRange
  0.008454 seconds (5 allocations: 176 bytes)  # array
```

versioninfo:

```
Julia Version 0.4.4-pre+35
Commit 1a9429e* (2016-02-12 13:21 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7 CPU       Q 820  @ 1.73GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

The array is large enough that it does not fit into cache, so I would have expected the UnitRange to be faster because it uses far less memory.

**Comment by timholy** [comment]
On master, the difference is less than two fold. Add an `@inbounds` to that loop, and you get:
```jl
julia> @time sumit(rng)
  0.000005 seconds (5 allocations: 176 bytes)
50000005000000

julia> @time sumit(rng_arr)
  0.014655 seconds (5 allocations: 176 bytes)
50000005000000
```
In other words, LLVM is smart enough to realize it can compute the sum without iterating through the array.

**Comment by timholy** [comment]
(Improvements in 0.5 are largely thanks to @blakejohnson.)

**Comment by JeffBezanson** [comment]
I think this is a real issue. `getindex` and the bounds check for ranges seems to be particularly slow.

**Comment by JaredCrean2** [comment]
> Add an @inbounds to that loop
Isn't that equivalent to using `julia --check-bounds=no` ?

**Comment by ararslan** [comment]
If I'm not mistaken, if you start Julia with the `--check-bounds=no` option, no bounds checks are performed for the entirety of that session, but using `@inbounds` applies only to the block on which it's used.

**Comment by mbauman** [comment]
On 0.4, it was completely impossible to remove bounds checks from custom types unless they implemented and used the ad-hoc and private `Base.unsafe_getindex`.  So that's why 0.4 is going to be much slower here.

On 0.5, though, there's the new amazing user-extensible `@inbounds` with `@boundscheck` blocks. Custom `@boundscheck` blocks don't respect the `--check-bounds` flag yet… only `Array` currently respects that flag.

I'm actually not convinced that this is a surprising result.  Sure, the array is bigger than the cache, but the access pattern is extremely predictable… with pre-fetching I'm not sure if there'd be all that many stalls. The IR does look pretty complicated for `UnitRange`, but I think it's mostly from using checked arithmetic in determining `length`.  If I'm reading it right, there is room for improvement, though — it'd be nice if LLVM would realize the length won't change and hoist it.

**Comment by okvs** [comment]
While this does not change the indexing concern, if you do
```julia
for v in arr
    val += v
end
```
then the range is faster than the array, even on 0.4.

**Comment by timholy** [comment]
> I think this is a real issue.

Fair enough. The LLVM for `getindex` on `UnitRange` is indeed really messy, mostly for the reason that @mbauman points out. This definition:
```jl
@inline function mygetindex{T}(v::Range{T}, i::Integer)
    ret = convert(T, first(v) + i - 1)
    @boundscheck ((i > 0) & (ret <= v.stop)) || Base.throw_boundserror(v, i)
    ret
end
```
seems safe (?) and generates much cleaner LLVM, with only one branch. (One of the nice things about ranges is that we can do the bounds-check *after* we compute the element value!)

For timings, I get
```jl
julia> @time sumit1(a)
  0.019552 seconds (5 allocations: 176 bytes)
50000005000000

julia> @time sumit2(a)
  0.021075 seconds (5 allocations: 176 bytes)
50000005000000

julia> @time sumit1(rng)
  0.036140 seconds (5 allocations: 176 bytes)
50000005000000

julia> @time sumit2(rng)
  0.028725 seconds (5 allocations: 176 bytes)
50000005000000
```
where `sumit2` uses `mygetindex`. So it's better, but still not as good. That is a little puzzling. I'm not great at reading `@code_native`, but perhaps someone who is might have some clue.

I do note that with `rng = 1:10^8` and using `julia -O`, the range is as good as the array. Still, you'd think it would be even better since there are no cache misses.

**Comment by nalimilan** [comment]
> Still, you'd think it would be even better since there are no cache misses.

I'm no expert in that area, but going over memory linearly is the most predictable access pattern, so there may not be any cache misses.

**Comment by timholy** [comment]
As long as prefetch never stalls, I guess that's true.

**Comment by JeffBezanson** [comment]
@timholy That's great; I'd be glad to have any amount of improvement here.

**Comment by JaredCrean2** [comment]
> Still, you'd think it would be even better since there are no cache misses
I don't there there are for a linear memory access pattern.  The limiting factor should be memory bandwidth.

Doing a back of the envelope calculation here:
The memory bandwidth of the machine I did the original benchmark is 8.314 gigabytes per second
The size of the array is 80,000,000 bytes
So the theoretical maximum speed (if limited by memory bandwidth) is: 0.00896 seconds


If the speed of the sum was limited by the flop rate:
For a clock speed of 2.0 GHz, assuming 1 operation per clock cycle, an array with 10000000 elements would take ~0.005 seconds.  (and this is a bit conservative, because the sum of an integer array should vectorize)

So it looks like memory bandwidth is the limiting factor for the array case.
The UnitRange does 2 extra integer adds per call to `getindex`, but it doesn't have to access memory ever, so I would expect it to be roughly 3x the operation per clock cycle minimum time, 0.015 seconds.

**Comment by timholy** [comment]
Nice analysis!

But, it doesn't take bounds-checking into account, and that's what we're focusing on because it's where the performance deficit for ranges occurs. If you use `@inbounds` on julia-0.5, then for the range performance is O(1) (i.e., `sumit(1:10^15)` completes in a few microseconds), because LLVM can compute the answer without actually iterating over the loop.

As @okvs says, if you want automatic bounds-check removal, use the `for a in A` syntax. The C-inspired `for i = 1:length(A)` could not possibly be a worse construct from the compiler's standpoint of being able to guess what you actually mean.

**Comment by JaredCrean2** [comment]
Thanks.

> LLVM can compute the answer without actually iterating over the loop.

That's awesome

The actual code (for which this sum is a model problem) uses the index `i` to index several arrays of different dimensionalities,  so until the tricky iterator questions are solved, its the only way.  Automatic bounds check removal isn't that interesting to me, because for any run where I really care about performance, I will use `julia --check-bounds=no` to get rid of all bounds checking everywhere.

Between the new `getindex`, using `julia -o` and the boundscheck removal, this problem seems solved to me.

**Comment by timholy** [comment]
If you want, you can use `for (i, a) in enumerate(A)` to get both the index and the value, without bounds-checking.

**Comment by blakejohnson** [comment]
> Automatic bounds check removal isn't that interesting to me, because for any run where I really care about performance, I will use `julia --check-bounds=no` to get rid of all bounds checking everywhere.

@mbauman was right when he noted above that the `--check-bounds=no` flag does not turn off *all* bounds checking, just bounds checks of Julia's native array type. So, automatic bounds checking removal should still be of interest to you.

**Comment by JaredCrean2** [comment]
That seems like an unusual design decision.  I'll file a separate issue for it to get a discussion going.

**Comment by JaredCrean2** [comment]
> you can use for (i, a) in enumerate(A) to get both the index and the value,

I was thinking of a case like this:
```julia
  numEl = 100
  numNodesPerElement = 6
  numDofPerNode = 4
  q = Array(Float64, numDofPerNode, numNodesPerElement, numEl)
  dxidx = Array(Float64, 2, 2, numNodesPerElement, numDofPerNode)
  res = zeros(q)

  function calcResidual(q, dxidx, res)
  numDofPerNode, numNodesPerElement, numEl = size(q)
    for  k=1:numEl
      for j=1:numNodesPerElement
        # do some calculation with dxidx[:, :, j, k]
        for i=1:mesh.numDofPerNode
          res[i, j, k] = # some calculation involving q[:, j, k], dxidx[:, :, j, k]
        end
      end
    end

  return nothing
end

  calcResidual(q, dxidx, res)
```

Admittedly, this is a very difficult case for bound check removal because it is multi-dimensional and uses the same set of indices to index multiple arrays.  Even replacing the `for` loops with some kind of `idx, val = enumerate(A, dim)` would remove bounds checking from accesses of `A`, but not from the other arrays accessed using `idx` (I think?).

(is this getting too off-topic?)

**Comment by mbauman** [comment]
This is now significantly improved. With bound checks on:

```
final results:
sizeof(array) = 80000000
  0.012834 seconds (5 allocations: 176 bytes)
  0.010455 seconds (5 allocations: 176 bytes)
```

With `@inbounds` the loop for the range is completely pre-computed:

```
final results:
sizeof(array) = 80000000
  0.000004 seconds (5 allocations: 176 bytes)
  0.008710 seconds (5 allocations: 176 bytes)
```

**Comment by tkelman** [comment]
would be good to add a benchmark so this gets tracked for perf regressions

**Comment by mbauman** [comment]
This exact function is already in BaseBenchmarks as perf_sumlinear. We test it on many array types, including UnitRanges.

**Comment by tkelman** [comment]
ah great, should have followed the breadcrumbs through https://github.com/JuliaLang/julia/pull/16078
