### ISSUE TITLE
Show a git-diff of NEWS.md on update

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#16187]
Right now, there aren't a lot of ways for package maintainers to communicate breaking changes and updates with their users. Could `Pkg.update(news=true)` display the git-diff of `NEWS.md` for each updated package?

**Comment by StefanKarpinski** [comment]
I like that idea 👍.

**Comment by nalimilan** [comment]
As noted [on Discourse](https://discourse.julialang.org/t/printing-changelog-upon-package-updates/4519), it would make sense to use the GitHub release notes for this. A git log is generally hard to read even for developers, and NEWS.md files are more tedious to update (since you need to commit the changes before tagging the release).

**Comment by juliohm** [comment]
I vote for having this feature tightly integrated with attobot as proposed on Discourse. Ideally, changelogs would be extracted from GitHub releases directly without any impact on our current workflow.

**Comment by KristofferC** [comment]
More discussion at https://github.com/JuliaLang/Pkg.jl/issues/176. Discussion can continue there.
