### ISSUE TITLE
`lufact` and `lufact!` behave differently on matrices of type `Int`

### ISSUE THREAD

**Issue by gasagna** [JuliaLang/julia#16193]
Hi, 

short demo:

```julia
julia> D = [1 2; 3 4]
2x2 Array{Int64,2}:
 1  2
 3  4

julia> lufact(D)
Base.LinAlg.LU{Float64,Array{Float64,2}}(2x2 Array{Float64,2}:
 1.0   2.0
 3.0  -2.0,Int32[1,2],0)

julia> lufact!(D)
ERROR: InexactError()
 in generic_lufact! at linalg/lu.jl:53
 in lufact! at linalg/lu.jl:20
```

While I understand why this happens, I believe a more detailed error message for `lufact!` would be good to have. Furthermore, wouldn't it be better to require explicitly that the input to `lufact` is of an adequate type, rather than the implicit convert? I guess more consistency between the copying and in-place versions would make this more predictable.

Cheers

**Comment by andreasnoack** [comment]
think it would be impractical to provide a more verbose error message in situations like these. The issue is that `generic_lufact!` is generic and therefore the user is allowed to use his own element type as long as it supports `+`,`-`,`*`, and `/`. The only solution a can see is that `InexactError` provided information about the failed conversion.

Julia promotes automatically almost everywhere, e.g. you can do `1+1.0` without getting an error and this is generally considered the most user-friendly behavior. As you mention, automatic promotion is not possible for in-place functions like `lufact!`. The usual explanation we give is that the `!` versions are expert versions and if you in doubt then use the non-`!` version.

**Comment by gasagna** [comment]
Thanks Andreas. I still believe, though, that a slightly more verbose error message in the `lufact!` version would help.

**Comment by andreasnoack** [comment]
Would it help to explain the `DomainError` in the documentation for `lufact!`? I still don't see how it would be possible to get a better error message unless you wrap it in a `try`/`catch` which I don't want to.

**Comment by gasagna** [comment]
Yes, I believe that documenting that `lufact!` might raise an InexactError exception for some input types is a good step. Should I open a pull request for the docs?

**Comment by andreasnoack** [comment]
Yes. That would great.
