### ISSUE TITLE
rand(::Set)

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#16231]
As [mentioned on the mailing list](https://groups.google.com/d/msg/julia-users/UbFZIhoc5O4/N1MfnN8qCgAJ), it might be nice to have a `rand(::Set)` function.  Since this is hard to implement efficiently without access to the `Set` internals, it is something that almost has to be in Base.  Here is a sample O(1) implementation:
```jl
import Base: GLOBAL_RNG, isslotfilled, rand
function rand(r::AbstractRNG, s::Set)
    isempty(s) && throw(ArgumentError("set must be non-empty"))
    n = length(s.dict.slots)
    while true
        i = rand(r, 1:n)
        isslotfilled(s.dict, i) && return s.dict.keys[i]
    end
end
rand(s::Set) = rand(GLOBAL_RNG, s)
```
If someone wants to put together a test case and documentation, it could make a good intro PR. 

Probably also add a `rand(::Set, dims)` method (etcetera) to supplement `rand(::Array, dims)`, which could be accomplished just by converting `rand` arguments from `AbstractArray` to `Union{AbstractArray,AbstractSet}` in a few places.

**Comment by stevengj** [comment]
Note that my implementation is efficient for the usual case that the set's internal hash table is at most a few times larger than the size of the set.   You can defeat this by deleting the contents of the set and then re-inserting a much smaller number of elements.  For example, my code will be extremely inefficient for:
```jl
s = Set(1:10^7)
empty!(s)
push!(s, 1)
length(s.dict.slots) / length(s) # gives 2e6!
@time rand(s)
```
takes almost 1 second for `rand(s)`.

I suppose you could test whether `length(s.dict.slots) > 20 * length(s)` and do something different in that case.

**Comment by PythonNut** [comment]
I'd like to take a look at this, if you don't mind.

**Comment by stevengj** [comment]
@PythonNut, that would be great.

**Comment by PythonNut** [comment]
@stevengj 

> You can defeat this by deleting the contents of the set and then re-inserting a much smaller number of elements.

I'm new to the Julia scene, but this strikes me as something that has performance implications outside this issue. You mention iteration, and I wouldn't be surprised if other operations would also be impeded by large numbers of empty bins. 

I've heard that the most common solution to this problem is to have the set rehash down when `bins/nonempty_bins` gets too large. This also saves space, which is nice. Performance obviously takes a hit if you're constantly varying the size of the hash table by large factors.

Does this sound like a better path forward?

**Comment by stevengj** [comment]
I think it would be good to fix `Base.rehash!` so that it can shrink the hash table if needed.

I don't know about automating this; the need for that seems pretty rare.   Typical uses of `Set` seem to grow but almost never shrink them (except to empty and refill to about the same size).

**Comment by PythonNut** [comment]
@stevengj that sounds quite reasonable. 

I've run some [profiling](https://gist.github.com/PythonNut/911c117637947e5e8735fcc12221e0cd), the results of which are visualized here:

* `O(1)` is the algorithm you supplied
* `O(n)` is `rand(collect(s))`

# v0.4.5 Fedora x86_64 i5-2520M

This is a personal ESXi server, so nothing else was running during this test.

![set_rand_perf_100k](https://cloud.githubusercontent.com/assets/5009546/15380500/e82d3d5e-1d2b-11e6-8bb3-dfaf83f66cd9.png)
![set_rand_perf_1m](https://cloud.githubusercontent.com/assets/5009546/15380501/e98cb6a2-1d2b-11e6-8986-38f1800ec19e.png)
![set_rand_perf_10m](https://cloud.githubusercontent.com/assets/5009546/15380503/eae7534a-1d2b-11e6-9b1d-cd337450affc.png)

# v0.4.5 Fedora i386 Core2Duo T9300

![set_rand_perf_100k](https://cloud.githubusercontent.com/assets/5009546/15380660/3cebc472-1d2d-11e6-98e5-b87fd9a05fab.png)
![set_rand_perf_1m](https://cloud.githubusercontent.com/assets/5009546/15380661/3eccbbac-1d2d-11e6-9f3a-159fad1457bd.png)
![set_rand_perf_10m](https://cloud.githubusercontent.com/assets/5009546/15380663/41b54c26-1d2d-11e6-84d1-8c35dd7d408b.png)

# Conclusion

As you can see, the crossover points vary with the size of the set (in addition to the number of bins), and also vary by machine. In addition, the `O(n)` solution only beats your `O(1)

**Comment by stevengj** [comment]
@PythonNut, nice job.  In principle, one could do a bit better than `rand(collect(s))` — do `i = rand(1:length(s)); state = start(s); for k = 1:i-1; _, state = next(s, state); end; return next(s, state)[1]` — since this will avoid an allocation.

But I doubt it will change the crossover point by orders of magnitude.   With such a high crossover point, I would only bother to implement the O(1) algorithm.

**Comment by stevengj** [comment]
Note also that rather than `tic`/`toq`, you can benchmark an expression `e` with `t = @elapsed e`.

**Comment by PythonNut** [comment]
@stevengj yes, looks like the effect isn't that significant.

### v0.4.5 Arch Linux x86_64 i7-4712HQ
**Allocation avoiding technique**
![set_rand_perf_1m](https://cloud.githubusercontent.com/assets/5009546/15397680/ea52b126-1d95-11e6-83fd-e62a73df0ddf.png)

**Original technique**
![protogon_set_rand_perf_1m](https://cloud.githubusercontent.com/assets/5009546/15397685/ed11f624-1d95-11e6-9973-758d3b0ec9ce.png)

I understand that your technique has the additional advantage of short circuiting the collection once the value is found, so it performs better on average. However, they have almost identical worst-case times, which I can't explain since we should be saving a bit deal of allocation. ╮(╯_╰)╭

> Note also that rather than `tic`/`toq`, you can benchmark an expression `e` with `t = @elapsed e`.

Thanks. I was looking for something like that, but couldn't find it for some reason.

**Comment by KristofferC** [comment]
Your thoroughness is inspiring.

**Comment by PythonNut** [comment]
@stevengj would you also like a `rand(::Dict)` method?

**Comment by stevengj** [comment]
`rand(::Dict)` would return a `key => value` pair, I guess?  That might make sense, since then `rand(s::Set)` could just call `rand(s.dict)[1]` so you get two methods for the price of one.

**Comment by PythonNut** [comment]
@stevengj Yup, that's what I was thinking.

Sorry, I'm having some trouble building my development Julia since I don't have much disk space. :/ Don't worry, I'll think of something.

**Comment by PythonNut** [comment]
Sorry guys, it looks like I'll need a much bigger VM to build Julia, and I haven't got around to making it yet—my job is making it hard. 

Hopefully, I get a spare moment to build it and start work on the tests for this.
