### ISSUE TITLE
`pinv` does not accept UpperTriangular

### ISSUE THREAD

**Issue by cdipaolo** [JuliaLang/julia#16486]
Minimal example (actual error for me comes from using a Cholesky decomposition):

``` julia
> A = UpperTriangular(randn(3,3))
> pinv(A)

LoadError: MethodError: `pinv` has no method matching pinv(::UpperTriangular{Float64,Array{Float64,2}})
while loading In[59], in expression starting on line 2

> inv(A)
3x3 UpperTriangular{Float64,Array{Float64,2}}:
 -1.65633   0.0833178  -0.905621
  0.0      -0.51199     0.299859
  0.0       0.0        -1.08089 
```

I'm assuming there should be a method for finding the pseudoinverse of upper triangular matrices considering it should be much faster than regular dense matrices, right?

In the case we know `A` is invertible we should use `inv()` but nevertheless I'd think it's still applicable.

**Comment by andreasnoack** [comment]
I'm not sure that it is possible to benefit that much from the triangular shape here. The core of the computation is the SVD and it's not obvious that the computation is simplified by extra structure. I found [an algorithm](http://cpsc.yale.edu/sites/default/files/files/tr917.pdf) but it's not available in LAPACK so it would require quite a bit of work to implement in Julia and even then, I'm in doubt it's really faster. Therefore, we should probably simply have something like `pinv(T::AbstractTriangular)=pinv(full(T))`.

**Comment by andreasnoack** [comment]
@cdipaolo When reading this again it strikes me that I'm not sure that using `pinv` on a Cholesky factor will ever help you. If the Cholesky succeeds then I don't think that `inv(chol(A))` and `pinv(full(chol(A)))` would be substantially different. Do you have an example where this actually makes a difference?

We might still want to have a working `pinv` for `XTriangular` which in practice will mean a working SVD for `XTriangular` because not all triangular matrices are computed from a Cholesky.

**Comment by ViralBShah** [comment]
FWIW, works now.
