### ISSUE TITLE
readdlm confused by input with quoted newline in field

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#16599]
Shortened from a real test case I found in the wild:

```jl
shell> cat > test.tsv
a"
"b
^D
julia> readdlm("test.tsv")
ERROR: truncated column at row 2 column 1
 in dlm_parse(::String, ::Char, ::Char, ::Char, ::Char, ::Bool, ::Bool, ::Bool, ::Int64, ::Bool, ::Base.DataFmt.DLMOffsets) at ./datafmt.jl:548
 in readdlm_string(::String, ::Char, ::Type{T}, ::Char, ::Bool, ::Dict{Symbol,Union{Char,Integer,Tuple{Integer,Integer}}}) at ./datafmt.jl:271
 in #readdlm_auto#9(::Array{Any,1}, ::Function, ::String, ::Char, ::Type{T}, ::Char, ::Bool) at ./datafmt.jl:57
 in #readdlm#7(::Array{Any,1}, ::Function, ::String, ::Char, ::Char) at ./datafmt.jl:38
 in #readdlm#5(::Array{Any,1}, ::Function, ::String) at ./datafmt.jl:35
 in readdlm(::String) at ./datafmt.jl:35
 in eval(::Module, ::Any) at ./boot.jl:225
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

`CSV.csv` works fine for this case.

Can be reproduced on both master and release-0.4.

**Comment by tanmaykm** [comment]
The error message seems right. Columns that start with a quote char are treated as quoted strings. Quote character occurring inside a quoted string must be escaped, but not otherwise.

In this case, it is complaining about missing closing quote for quoted column 1 at row 2 ("b).
It read the first row as "a\"" as plain (unquoted) string, since it did not start with a quote.

**Comment by JeffBezanson** [comment]
Yes, I'm not sure this is a valid delimited file that readdlm needs to handle.

**Comment by StefanKarpinski** [comment]
Solution: delete `readdlm`.
