### ISSUE TITLE
do we need `broadcast_function`?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#16601]
I came across this looking for exports to remove. It just does `(As...) -> broadcast(f, As...)`, so I'm not sure we need an exported function for this. Is this widely used?

**Comment by StefanKarpinski** [comment]
Yeah, that seems pretty unnecessary.

**Comment by timholy** [comment]
Out of 218 installed packages on my laptop, `grep` can't find a single use.

**Comment by toivoh** [comment]
I introduced it with the original `broadcast` to allow you to get hold of the appropriate broadcasted function directly instead of having to go through a dict lookup each time you wanted to broadcast the same function. But I think it has degenerated since, and now that we have specialization on function arguments I guess it's not needed at all anymore. (Haven't looked into how the current `broadcast` implementation handles this.)
