### ISSUE TITLE
StackOverFlowError with >> on Float64

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#16700]
I did this by accident, but it seems like we probably want a no method error or something.

```julia
julia> 1.0 >> 8
ERROR: StackOverflowError:
 in >>(::Float64, ::UInt64) at ./operators.jl:196 (repeats 80000 times)
```

**Comment by stevengj** [comment]
I get a `>> not defined for Float64` error in Julia 0.4, so this happened in 0.5.

**Comment by stevengj** [comment]
Seems to have been caused by #14516.  cc @eschnett

**Comment by eschnett** [comment]
It seems some type signatures are too loose. I suggest to restrict `>>` to have `Integer` as first argument, same as e.g. `&`.

**Comment by stevengj** [comment]
This seems sensible; I'm not sure what the `<<` operation means for non-integer types.  Unless we want to generically define `<<(a,b) = a * exp2(b)`?

**Comment by eschnett** [comment]
There are types such as e.g. `BitVector` where `<<` still makes sense.

The problem here is that there is a generic fall-back function that translates e.g. `<<(x, n::Signed)` to `<<(x, n::Unsigned)` (or `>>`), depending on the sign of `n`. By restricting the signature, this fallback doesn't apply any more. However, I just see that `BitVector` doesn't use this fallback anyway, as it has a more specific signature.

**Comment by stevengj** [comment]
It makes sense to restrict type of the fallback in any case.
