### ISSUE TITLE
filter() function edge case, possible bug.

### ISSUE THREAD

**Issue by esproff** [JuliaLang/julia#16704]
Consider the code:

`filter(n -> true, collect(1:0))`

this returns a 0-element array.  However if I don't collect the iterator into an array:

`filter(n -> true, 1:0)`

I get the error 

`Error: TypeError: typeassert: expected AbstractArray{Bool, N}, got Array{Int64, 1} in filter at array.jl:923`

It seems like this should also return a 0-element array, since if the iterator is non empty, e.g.

`filter(n -> true, 1:2)`

I get the two element array `[1,2]`.

**Comment by ararslan** [comment]
I can reproduce this on 0.4.5 but on 0.5 the error is slightly different: it says `Array{Union{},1}` instead of `Array{Int64,1}`.

**Comment by berndbohmeier** [comment]
In array.jl the function filer is implemented using map
`filter(f, As::AbstractArray) = As[map(f, As)::AbstractArray{Bool}]`

but map does not change the elementtype of the AbstractArray if the AbstractArray is empty.

`map(n-> true, 1:2)` results in `Array{Bool,1}`
but
`map(n-> true, 1:0)` results in `Array{Int64,1}` , which causes the problem in filter

Is this the expected behaviour of map?
