### ISSUE TITLE
Is there some easy hackable mini-version of Julia available ?

### ISSUE THREAD

**Issue by zhmz90** [JuliaLang/julia#16798]
[Documentation of Julia’s Internals](http://docs.julialang.org/en/latest/devdocs/julia/) is wonderful. 
In my opinion, It will be much easier for others to learn Julia's internals especially those who don't have strong knowledge about compilers/interpreters/LLVM, if someone can make a minimum Julia version to illuminate how Julia is built.

**Comment by yuyichao** [comment]
I'm not sure what are you asking about here. What do you mean by `illuminate how Julia is built.`?

**Comment by vtjnash** [comment]
The early bootstrap versions of Julia aren't actually easier to work with. But, I think the problem you're describing here is real: if you want to experiment with changing some characteristic of Julia, where do you start and which file do you open? There's a lot of information out there (I've also blogged about it some too http://juliacomputing.com/blog/2016/02/09/static-julia.html), but afaik, there's no good meta resource to help interested users find the right link (although I think the creation of such a page would be an excellent way for one or a couple inexperienced users to become much more knowledgeable about it).

I'm closing this as non-actionable, since it doesn't describe a particular bug (tracking speculative improvements slows down the triaging and fixing of issues), but this is still a good topic to continue here, on the mailing list, or at JuliaCon.

**Comment by JeffBezanson** [comment]
@zhmz90 Perhaps a julia interpreter written in julia?

**Comment by ViralBShah** [comment]
Well, we already have JuliaParser.

**Comment by StefanKarpinski** [comment]
Once again, @vtjnash, the issue tracker is not just for bugs. It is also for features, speculation and documentation improvements.

**Comment by vtjnash** [comment]
@StefanKarpinski no. there's a non-zero cost in terms of bugs that won't get fixed if this issue is open. The issue tracker is not for capturing the complement set of features not implemented in Julia.

**Comment by StefanKarpinski** [comment]
There is a fairly clearly actionable documentation issue here:

> But, I think the problem you're describing here is real: if you want to experiment with changing some characteristic of Julia, where do you start and which file do you open?

> there's no good meta resource to help interested users find the right link (although I think the creation of such a page would be an excellent way for one or a couple inexperienced users to become much more knowledgeable about it).

This is what labels like "doc" and "up for grabs" are for.

**Comment by JeffBezanson** [comment]
I think the devdocs are pretty good. They can always be improved of course, which would be great, but this issue wasn't asking for that. It asked for:

> if someone can make a minimum Julia version to illuminate how Julia is built

**Comment by zhmz90** [comment]
Sorry for the late.  Maybe I should just try again to build this mini Julia myself. One of my purpose of this mini Julia is to be as a starter code base for experiment with Julia internal source code later.

@yuyichao , perhaps `illuminate` will be better replace by `illustrate`. 

@JeffBezanson ,  A julia interpreter written in julia will help. But maybe It will be more appropriate just to go toward there, if I want to be able to work with code in `Julia src`.

Thanks for so many core developers here. I am very appreciate it. I will continue it on the mailing list when I make a progress on it. Thanks again for all your time.

**Comment by yuyichao** [comment]
In my experience, a mini version isn't really a good way to peek the inside of a project. We should indeed improve the dev doc so that new people can better understand where certain features are implemented and what else needs to change if one place is changed but it's far from an actionable doc issue. (For example, when do we call the doc to be good enough?) You can certainly ask on julia-dev list if you want to know about certain features and propose improvements to corresponding dev docs.

**Comment by StefanKarpinski** [comment]
Agreed. The parts of Julia that are hard to understand are not the parts that can be removed anyway. The things that can be pared away from Julia are precisely the things that are fairly independent (like the recently-extracted prime functionality, linear algebra functionality, etc.), and as such, they are not really essential to understanding how Julia works.
