### ISSUE TITLE
Define `findfirst` for generators

### ISSUE THREAD

**Issue by malmaud** [JuliaLang/julia#16884]
Can't think of a good reason not to, since `find` is defined on them.

**Comment by ararslan** [comment]
Looks like the reason it works for `find` now is because the fallback for `find` doesn't use `getindex` so it works fine for generators. `findfirst` uses `findnext` which makes a call to `getindex`, and `getindex` doesn't have a method for generators. Would it make sense to have `getindex` for generators?

**Comment by nalimilan** [comment]
I'd rather make `findfirst` rely only on the iteration protocol. See https://github.com/JuliaLang/julia/pull/15755.

**Comment by adienes** [comment]
this works now.

**Comment by ararslan** [comment]
Thanks, looks like you're right
