### ISSUE TITLE
Unclear docstring for airyx

### ISSUE THREAD

**Issue by giordano** [JuliaLang/julia#17032]
The docstring of `airyx` function reads:

> scaled `k`-th derivative of the Airy function, return `\operatorname{Ai}(x) e^{\frac{2}{3} x \sqrt{x}}` for `k == 0 || k == 1`\ , and `\operatorname{Ai}(x) e^{- \left| \operatorname{Re} \left( \frac{2}{3} x \sqrt{x} \right) \right|}` for `k == 2 || k == 3`.

This is at best unclear, if not misleading.  `airyx(2, x)` isn't the scaled second derivative of Airy Ai function, but rather the scaled Airy Bi function, like `airyx(3, x)` isn't the scaled third derivative of Airy Ai.

In addition, how is the scaling factor computed?  For negative real values of `x` it should be complex according to the docstring (at least in the case `k == 0 || k ==1`), but `airyx(0, -1.23)` is real.  GSL [uses](https://www.gnu.org/software/gsl/manual/html_node/Airy-Functions.html#Airy-Functions) 1 as scaling factor for negative real `x`, but this isn't the case for Julia's `airyx`, because `airyx(0, -1.23) != airy(0, -1.23)`.

**Comment by tkelman** [comment]
cc @simonbyrne or @stevengj might be the most knowledgeable here

**Comment by giordano** [comment]
Actually also the docstring of `airy(k, x)` is wrong: `airy(2, x)` isn't the first and derivative of `airy(1, x)` and `airy(0, x)`, respectively, it's just the `airybi` function.  The same applies to `airy(3, x)`

**Comment by stevengj** [comment]
Yeah that looks right at first glance in the source code.   Can we rename these horrible functions?  It looks like the Fortran interface was copied a little too literally—I'd rather just define eight functions in Julia (for Ai, Ai', Bi, Bi', and the scaled versions) rather than pass these obscure integer arguments.

The scaling is defined by `kode=2` in [zairy.f](https://github.com/JuliaLang/openspecfun/blob/0615b58c019ac6803858d47cd9a06cf133de4c34/amos/zairy.f) and [zbiry.f](https://github.com/JuliaLang/openspecfun/blob/0615b58c019ac6803858d47cd9a06cf133de4c34/amos/zbiry.f), I believe.

**Comment by tkelman** [comment]
These should be moved to a special functions package where they can be named more idiomatically.

**Comment by giordano** [comment]
> These should be moved to a special functions package where they can be named more idiomatically.

Actually I like about Julia that you don't have to install and load an external package in order to use common special functions.

**Comment by tkelman** [comment]
Sorry, that's going to change, there's zero technical reason for them to be here and tied to the development schedule of the base language.
