### ISSUE TITLE
Test.atsign-inferred doesn't work on calls using kwargs...

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#17105]
...even when the kwargs do not affect the return type in any way. (It's a problem with how the macro is defined.)

```jl
function kwtest(x; str="Hello, world!")
    println(str)
    2x
end

julia> using Base.Test

julia> @inferred(kwtest(3))
Hello, world!
6

julia> @inferred(kwtest(3, str="Hi there!"))
ERROR: function tuple does not accept keyword arguments
 in kwfunc(::Any) at ./boot.jl:236
 in eval(::Module, ::Any) at ./boot.jl:234
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

**Comment by simonster** [comment]
`@inferred` should probably be changed to use [`gen_call_with_extracted_types`](https://github.com/JuliaLang/julia/blob/00ba80d22760c60bd87c12ce865ff6ace544594e/base/interactiveutil.jl#L278-L332) like `@code_typed` etc.

**Comment by jamesonquinn** [comment]
`gen_call_with_extracted_types` doesn't work for a couple of reasons:
-It gives the types, but not the values
-In its current version, it simply discards keywords

I believe the easiest solution would be through https://github.com/JuliaLang/julia/issues/17189.

**Comment by simonster** [comment]
The idea is to change [the part of `@inferred` that calls Base.return_types](https://github.com/JuliaLang/julia/blob/844f284334737c82933c7cd0af2c8e0682188113/base/test.jl#L923-L924) to do it by interpolating the result of `gen_call_with_extracted_types` into the generated AST. Those two lines are just (doing a bad job of) getting the argument types and calling `Base.return_types` with them. It doesn't matter that `gen_call_with_extracted_types` discards keywords since they aren't relevant to type inference.

**Comment by simonster** [comment]
Thinking about this more, it does matter that `gen_call_with_extracted_types` discards the keywords, since it's not actually looking at the keyword version of the function. This applies to `@code_typed` etc. as well. A case that fails:

```julia
function uninferrable_kwtest(x; y=1)
    2x+y
end
```

Type information for `y` is available if this is called as `uninferrable_kwtest(1)` but not if called as `uninferrable_kwtest(1; y=2)`.
