### ISSUE TITLE
Segmentation fault where stack overflow expected

### ISSUE THREAD

**Issue by davidagold** [JuliaLang/julia#17280]
I came across this while working on `map` for `NullableArray`s. Here's an example:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+5156 (2016-07-05 13:54 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 0b22a01* (0 days old master)
|__/                   |  x86_64-apple-darwin15.5.0

julia> immutable MyArray{T, N} <: AbstractArray{Nullable{T}, N}
           A::Array{T, N}
           B::Array{Bool, N}
       end

julia> X = nothing

julia> Base.map(f, A::MyArray; kwarg=false) =
           kwarg ? X : map(f, A)
julia> A = MyArray(collect(1:5), [true, true, true, true, false]);

julia> f(x) = 5*x
f (generic function with 1 method)

julia> map(f, A)
Segmentation fault: 11
Davids-MacBook-Pro-3:~ David$ 
```

The culprit seems to be the inclusion of a name in the second argument to `?:`; using a literal yields a stack overflow, as I would have expected the above example to:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+5156 (2016-07-05 13:54 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 0b22a01* (0 days old master)
|__/                   |  x86_64-apple-darwin15.5.0

julia> immutable MyArray{T, N} <: AbstractArray{Nullable{T}, N}
           A::Array{T, N}
           B::Array{Bool, N}
       end

julia> Base.map(f, A::MyArray; kwarg=false) =
           kwarg ? nothing : map(f, A)

julia> A = MyArray(collect(1:5), [true, true, true, true, false]);

julia> f(x) = 5*x
f (generic function with 1 method)

julia> map(f, A)
ERROR: StackOverflowError:
 in #map#1 at ./REPL[2]:0 [inlined]
 in map(::Function, ::MyArray{Int64,1}) at ./REPL[2]:1
 in #map#1 at ./REPL[2]:0 [inlined]
 in map(::Function, ::MyArray{Int64,1}) at ./REPL[2]:1
 in #map#1 at ./REPL[2]:0 [inlined]
 in map(::Function, ::MyArray{Int64,1}) at ./REPL[2]:1
...
```

**Comment by yuyichao** [comment]
Does a simpler version like the following triggers the stack overflow error correctly?

```
julia> f() = f() + f()
f (generic function with 1 method)

julia> f()
ERROR: StackOverflowError:
 in f() at ./REPL[1]:0
 in f() at ./REPL[1]:1 (repeats 79999 times)
```

**Comment by davidagold** [comment]
Yes, it does trigger the stack overflow error correctly.

**Comment by yuyichao** [comment]
If you run this in GDB, and when the segfault happens, can you set a breakpoint in `cache_exception_raise` and single step to **after** the `thread_get_state` call and check the following when you hit the breakpoint due to the segfault?

1. `p *ptls2` (if `ptls2` is optimized out, try `p *jl_all_tls_states[0]`)
2. `p exc_state.__faultvaddr`
3. `thread apply all p $rsp`
4. `thread apply all p $rbp`

**Comment by KristofferC** [comment]
Bump @davidagold, what is the status now?

**Comment by mbauman** [comment]
This shouldn't have gotten a "needs more info" label — it's a nicely self-contained reproduction.

In any case, it's resolved now.  The original case now throws a stack overflow error as expected.

**Comment by yuyichao** [comment]
I've also had a [nicely described precedure](https://github.com/JuliaLang/julia/issues/17280#issuecomment-230789807) to obtain the necessary "more info". A self contained repro that doesn't reproduce the issue everywhere isn't always all the info needed to debug an issue.

**Comment by mbauman** [comment]
You're welcome to re-open this issue if you believe it's not fully resolved.  In any case we should add regression tests for it.

I think it's fine to ask folks (particularly committers) to run stuff in GDB, but I don't think that counts as a "needs more info" tag.  In my view, that is for incomplete issues where only the OP is encountering a problem and we actually need more info from them in order to simply reproduce the issue.  But this is a great issue, and I don't think David needs to do anything further.  It's a nice minimal example.  Sure, it's platform dependent, but we support multiple platforms.

This is more of a "if you know how to run GDB and are willing to spend some time helping us debug this further, it'd be really great if you could try getting some more information for us" kind of situation.

**Comment by yuyichao** [comment]
> You're welcome to re-open this issue if you believe it's not fully resolved. In any case we should add regression tests for it.

In that case I'll close https://github.com/JuliaLang/julia/issues/21072 since so far all evidence points to that the two are the same issue.

> Sure, it's platform dependent, but we support multiple platforms.

It's more platform dependent than that. It's not even reproducible all the time on mac.

> But this is a great issue, and I don't think David needs to do anything further.

No one will ever be responsible for providing more info for any bugs, even for ones that no minimum repro was given. The tag does not mean that this is a bad issue, it just means that more info is needed before this can be debugged further. Of course anyone that can reproduce it are free to provide the info, especially anyone that want this bug to be fixed.
