### ISSUE TITLE
promote_op/broadcast should not call the function for one(T)

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#17314]
As was commented at https://github.com/JuliaLang/julia/pull/17300#issuecomment-231027267 and https://github.com/JuliaLang/julia/pull/17172#issuecomment-230975340, the `promote_op` function has a [fallback  method](https://github.com/JuliaLang/julia/blob/6ab1b197f42807362c77893ea112fbaaad510785/base/number.jl#L68) that calls `typeof(op(one(T)))`.  This is not really acceptable.

For one thing, `op(1)` may not even be valid—it may throw a `DomainError` e.g. if `op(x)=log(log(log(x)))`.   Even if `1` is a valid argument, it is unexpected and undesirable that `op` should be called without the user requesting it.  (e.g. imagine if `op` has side effects, or is simply an extremely expensive function.)

**Comment by stevengj** [comment]
cc @nalimilan, @JeffBezanson

**Comment by andreasnoack** [comment]
Maybe the guideline should be not to broadcast functions with side effects. As mentioned in #17300, using a version of `log` that doesn't throw completely fixes the issue here. It might be too hard to find that version of `log` though and we throw a lot in Base.

I'm not really concerned about the cost of a single extra call to a function you already want to broadcast. To be significant, it would require that the function is very expensive and it's broadcast over a very short range. I'm not sure that case should be given too much weight in this decision.

**Comment by nalimilan** [comment]
IIUC Jeff's concern is that the `map`/`broadcast` algorithm for guessing the type could hurt performance, in particular by preventing SIMD: https://github.com/JuliaLang/julia/pull/17172#issuecomment-230921759 To make progress on that front, we'd need to check whether that's the case or not.

**Comment by nalimilan** [comment]
I also wonder whether whether inference couldn't allow for a fast-path when the called function is type-stable for the passed input types.

**Comment by JeffBezanson** [comment]
Inference already works fine here. If we can infer the result type of the function the code is specialized down to a compact loop. Anyway I think I should just merge #16622, which provides `return_type`.

**Comment by nalimilan** [comment]
So in theory there should be no problem with removing that method?

**Comment by stevengj** [comment]
Can this be fixed now that #16622 was merged?

**Comment by pabloferz** [comment]
@stevengj See #17389

**Comment by ssfrr** [comment]
This also causes a problem in SIUnits.jl: Keno/SIUnits.jl#84.

In the issue above the error is because unit-less numbers can't be `convert`ed to unitful numbers, so it fails trying `one(typeof(Hz))`

Also if you try `collect(1:5) * (1Hz)` you get a conversion error on `setindex`. This is because `one(typeof(1Hz))` is `1` (because the multiplicative identity of a unitful number doesn't have any units).

So this is a case where `one(T)` isn't a good representative value to determine the `eltype` for the result array.

**Comment by stevengj** [comment]
As @yuyichao pointed out [on julia-users](https://groups.google.com/forum/#!topic/julia-users/nzKu4Adh0Tw), this also causes a `MethodError` for e.g. `broadcast(muladd,[1],[2],[3])`, because the `promote_op` fallback that passes `one(T)` assumes that every function accepts one or two arguments.

Marking the issue as a regression since these problems weren't present in 0.4.

**Comment by ssfrr** [comment]
Seems that the commit that closed this issue has been reverted (dbdaf72b2). Should the issue be re-opened?

**Comment by tkelman** [comment]
it was reverted on release-0.5. if it can be fixed in a way that doesn't hurt performance and doesn't break packages, we can consider re-applying along with backporting the fix
