### ISSUE TITLE
Seeded random results differ between 0.4 and 0.5

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#17426]
@ranjanan found that `randperm` returns different results given the same seed in 0.4 and 0.5.

0.4:
```julia
julia> srand(1); randperm(10)
10-element Array{Int64,1}:
  2
  9
  8
  6
  5
  4
  7
  3
 10
  1
```
Current master:
```julia
julia> srand(1); randperm(10)
10-element Array{Int64,1}:
 10
  3
  7
  8
  9
  2
  5
  6
  4
  1
```

It appears the difference was introduced in https://github.com/JuliaLang/julia/commit/fd93d4555900ecf39a75d4c02c385cacf8c942fb through the use of `rand_lt` in place of `rand`. Indeed, if I define `randperm` locally equivalent to how it was before that commit, the results match between versions.

```julia
julia> function randperm2(n::Integer)
           a = Array{typeof(n)}(n)
           n == 0 && return a
           a[1] = 1
           @inbounds for i = 2:n
               j = rand(Base.Random.GLOBAL_RNG, 1:i)
               a[i] = a[j]
               a[j] = i
           end
           return a
       end
randperm2 (generic function with 1 method)

julia> srand(1); randperm2(10)
10-element Array{Int64,1}:
  2
  9
  8
  6
  5
  4
  7
  3
 10
  1
```

This is causing some issues in the JuliaStats packages, particularly in HypothesisTests, where the computed p-value for a certain test is radically different between 0.4 and 0.5 because of `randperm`.

**Comment by tkelman** [comment]
thanks for bisecting! cc @rfourquet was the change in output intentional?

**Comment by simonbyrne** [comment]
In general, we've not preserved the behaviour of random functions and seeds between versions, but if you're getting radically different p-values then there's a problem somewhere.

**Comment by ararslan** [comment]
Ref discussion in https://github.com/JuliaStats/HypothesisTests.jl/issues/63

**Comment by lobingera** [comment]
@simonbyrne This might be a missunderstanding on my side, but did you just say that the same code with the same random seed settings will produce different output on different versions of julia? And this is the intended behaviour?

**Comment by rfourquet** [comment]
Yes this was intentional behavior, the algorithm to generate random permutations was simply far from being optimal. As I said in the PR where I made this change, this use of `rand_lt` is kind of a band-aid, and I hope that random generation for ranges can be improved and used again for `randperm` (so this would again change the output for `randperm` with the same seed).
I don't have time to investigate myself the p-value problem in the next few weeks, but if someone can detect and report that the new `randperm` implementation is buggy, I will fix it asap.
Preserving the behaviour of random functions between versions would prevent further improvements, so I think we should not have this constraint, at least not before version 1.0 of Julia.

**Comment by lobingera** [comment]
> Preserving the behaviour of random functions between versions would prevent further improvements, so I think we should not have this constraint, at least not before version 1.0 of Julia. 
But at the same time this would improve usability of julia. I'm fine with improvements if the 'old' version of behaviour is somehow available and documented. I might be biased, because i already spent some weeks worktime working around 'improvements' in the sorting algorithms in different matlab versions and similar

**Comment by tkelman** [comment]
seems it is "available" via making a local copy of the old implementation. documentation (is this mentioned in NEWS.md?) could always be clearer about this kind of change though
