### ISSUE TITLE
`cd` does not expand `~`

### ISSUE THREAD

**Issue by bastibe** [JuliaLang/julia#17477]
It would be very helpful if `cd` would expand `~`, at least on platforms where `~` has a clear meaning.

**Comment by tkelman** [comment]
see `expanduser`

**Comment by vtjnash** [comment]
dup https://github.com/JuliaLang/julia/issues/1136

**Comment by StefanKarpinski** [comment]
This isn't exactly a dup, @vtjnash – this is a much more restricted case and interactive-only.

**Comment by StefanKarpinski** [comment]
Btw, it's a little unclear if this refers to the `cd` function or `;cd dir` in shell mode: if it's the former then it's a dup (since giving `cd` special behavior that every other file system function doesn't have seems like a bad idea), but if it's just for the shell mode, then it's not a dup at all.

**Comment by TotalVerb** [comment]
`cd` *does* expand `~` in shell mode.

**Comment by yuyichao** [comment]
so this is a dup?

**Comment by TotalVerb** [comment]
Looks like it.

```sh
shell> cd ~
/home/fengyang
```

**Comment by bastibe** [comment]
Yes, I was referring to the `cd` function.

**Comment by tkelman** [comment]
See also https://github.com/rory-finnegan/FilePaths.jl
