### ISSUE TITLE
Unquoting in quote inside quote isn't affected by a macro's name mangling

### ISSUE THREAD

**Issue by fcard** [JuliaLang/julia#17588]
As seen in:

``` julia
macro m()
  quote
    x = "x"
    quote
      $x
    end
  end
end
```

```
julia> @m()
ERROR: UndefVarError: x not defined

```

Tested on today's master and `0.4.6`.

...

**Comment by ssfrr** [comment]
Just hit this again. It also occurs to me that there might be code in the wild that's depending on this behavior, e.g. 
```
julia> macro m()
         x = "outer"
         quote
           x = "inner"
           quote
             $x
           end
         end
       end
@m (macro with 1 method)

julia> @m
quote  # REPL[2], line 6:
    "outer"
end
```

whereas it should return `"inner"`. Does that escalate this to a breaking change that should go in the 0.7 milestone?

**Comment by fcard** [comment]
@ssfrr Your example doesn't work unless you make the outer `x` global, or use `$$x` instead. The latter should still work after this bug is fixed.

**Comment by ssfrr** [comment]
Oh, whoops, :flushed:  I must have had an `x="outer"` defined in my REPL. 

My point was just that someone might have wrong code that works because of this bug, though I'm having trouble constructing it so maybe it's not such a concern. There have definitely been times where I've found myself trying different combinations of `:(...)`, `esc(...)`, and `$...` to try to get something to work, and it somehow feels like subtle changes to escaping and interpolation are more likely to trip people up than non-metaprogramming stuff.

That said, there's a lot on the docket for 0.7, so I mostly just wanted to bump this and see if it's worth adding (but maybe it's not).

**Comment by vtjnash** [comment]
```
julia> @macroexpand @m
quote
    #= REPL[6]:3 =#
    var"#3#x" = "x"
    #= REPL[6]:4 =#
    Core._expr(:block, $(QuoteNode(:(#= REPL[6]:5 =#))), var"#3#x")
end
```
this was fixed
