### ISSUE TITLE
Split source file `codegen.cpp`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#17609]
When I build Julia on my Raspberry Pi, by far the longest time is spent building `codegen.cpp`. The reason is that this is a rather large file, and my Pi is running out of memory, and (obviously) swapping while compiling is rather slow.

`codegen.cpp` is much larger than any other source file; it's about three times as large both in terms of lines of source code, as well as in terms of the size of the generated object file.

I would like to split `codegen.cpp` into two or three source files. Does this make sense? Have you thought about this as well, and if so, do you have a suggestion for "natural" breaking points? Are there groups of routines that need to remain in the same source file for efficiency?

**Comment by yuyichao** [comment]
Jameson has already done a lot of works of splitting this file and I think there's probably even more coming. PR's that split this file naturally are definitely welcome but I'm not sure if there's anything useful to keep this issue open though. (For one thing, what is "enough" splitting and when do we close this.)

**Comment by JeffBezanson** [comment]
First, we could move ccall.cpp, intrinsics,cpp, and cgutils.cpp to actual separate compilation units instead of including them in codegen.cpp.

codegen.cpp could then contain just the core IR generation functions, basically those beginning with `emit_`. A lot more helper functions can be moved to cgutils, and then there are reflection, initialization, and analysis routines, and code for writing object files and coverage data that can be moved out.

**Comment by ViralBShah** [comment]
For the raspberry pi, the easy way out is to add swap space, which works reliably.
