### ISSUE TITLE
Splatted keywords take precedence

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#17785]
When combining specified keywords and splatted keywords the splatted keywords are always used. Similar to #16937.
```julia
julia> g(; a=1, b=2) = a, b
g (generic function with 1 method)

julia> opts = (:a => 3, :b => 4)
(:a=>3,:b=>4)

julia> g(; opts...)
(3,4)

julia> g(; a=5, opts...)
(3,4)

julia> g(; opts..., a=5)
(3,4)

julia> g(; a=5)
(5,2)
```
Occurs in both 0.4.6 and 0.5.

**Comment by iamed2** [comment]
On the other hand:
```julia
julia> opts = (:a=>3,:b=>4,:a=>5); g(; opts...)
(5,4)
```

This is not quite #16937 as it isn't a syntax issue and wouldn't be the same mistake. This could be the result of the `merge` call mentioned in that thread, and is probably intentional.

IMO the ideal result is that the rightmost kwarg takes precedent in all cases, whether it is part of a splat or not.

**Comment by JeffBezanson** [comment]
Yes, I think this could easily be changed to make everything left-to-right.
