### ISSUE TITLE
replace matmul with blas calls in perf.f90

### ISSUE THREAD

**Issue by alinelena** [JuliaLang/julia#17807]
the “algorithm” for random matrix multiplication is to call LAPACK(shall read BLAS), except where that’s not possible, such as in JavaScript.

the fortran perf contains matmul,transpose calls for no real reason. Irronically BLAS reference implementations are fortran.

**Comment by stevengj** [comment]
If the language provides a `matmul` routine, isn't the most natural thing to use it?  It's up to the language implementation to make `matmul` fast (e.g. by calling a fast BLAS).  In the Julia benchmark, we do `A * B` rather than calling `A_mul_B!` or `LinAlg.BLAS.gemm!`, right?

Honestly, this whole matmul benchmark is so uninteresting (because it is mostly just measuring BLAS speed) that I'm not convinced we should include it at all.   But if it has any point at all, it is to benchmark the simplest, most straightforward, most "built-in" way to multiply matrices available in the language, and to see if they did a good job in interfacing a fast BLAS.

**Comment by StefanKarpinski** [comment]
We were reluctant to even add this but people kept asking about it, so we did. The shocking thing is that there's even any variance in how long it takes to call BLAS (and of course, some variance in the speed of the BLAS libraries that different systems ship with). But yes, a very silly benchmark.
