### ISSUE TITLE
I get this error while trying to run *.jl file from Terminal  ERROR: LoadError: UndefVarError: input not defined

### ISSUE THREAD

**Issue by Rishabh-Raghunath** [JuliaLang/julia#17879]
Hello,
I am a beginner in the Julia language .. 
I get this error while I try to run ****.jl Julia program file from the terminal. However It works perfectly fine in the Juno IDE. This following is the error message I receive while trying to run the program from the Linux terminal:

ERROR: LoadError: UndefVarError: input not defined
in legacy at /home/rishabh/Desktop/ProjectJulia/juliatest.jl:120
while loading /home/rishabh/Desktop/ProjectJulia/juliatest.jl, in expression starting on line 138

How do I resolve this and run .jl file in the terminal rather than in Juno ?
Thanks In advance
![screenshot from 2016-08-07 23-56-02](https://cloud.githubusercontent.com/assets/17016085/17464477/38daf50a-5cfd-11e6-97d4-8332e95291d6.png)

**Comment by KristofferC** [comment]
Hello again Rishabh. Maybe I was not clear in the last post. The github website is for bug reports when there is likely something wrong with the Julia language itself. In this case, it seems like you need some guidance on how to use Julia since you are new to it. In that case, posts should me made to https://groups.google.com/forum/m/#!forum/julia-users.

**Comment by Rishabh-Raghunath** [comment]
I'm Sorry 
I understand now.. 
Thanks
