### ISSUE TITLE
Pkg.clone() operation slow compared to Pkg.add()

### ISSUE THREAD

**Issue by ma-laforge** [JuliaLang/julia#17907]
I am not certain if this is intrinsic to how `Pkg.clone()` is implemented, but it is significantly slower than `Pkg.add()`.  The performance difference is very noticeable on less powerful computers.

```
Pkg.clone("git://github.com/ma-laforge/NumericIO.jl")
INFO: Cloning NumericIO from git://github.com/ma-laforge/NumericIO.jl.git
INFO: Computing changes...
INFO: No packages to install, update or remove
INFO: Package database updated
```

It almost looks like Julia is running `Pkg.update()` every time you clone a package. 

If, on the other hand, you run `Pkg.add()`, the performance is better, probably because it does not "[re-c]ompute changes":

```
julia> Pkg.add("NumericIO")
INFO: Installing NumericIO v0.0.4
INFO: Package database updated
```

**Comment by tkelman** [comment]
I'm guessing, but Pkg.clone doesn't know the requirements of the package until after it's done with the clone, then it has to do a dependency resolution which can get expensive. Registered packages have their dependencies listed in METADATA so that data is known locally on your filesystem.

**Comment by andyferris** [comment]
> it has to do a dependency resolution which can get expensive

To me, this is the *real* problem. Does anyone know why this is so slow? Dependency resolution in Julia *feels* slower than package managers like apt, conda, pip, etc, all of which have more packages...

**Comment by ma-laforge** [comment]
@tkelman:

Just out of curiosity: Does Julia scan the entire code base to do dependency resolution, or does it just look at `REQUIRE`?  I ask, because the `REQUIRE` file of `NumericIO` is simply:
```
julia 0.4
```
So no real dependencies here.
...Yet the "Computing changes" operation seems to take an exhorbitant amount of time on my Celeron running Windows 10.

This gets really bad when trying to install a custom software distribution made up of multiple packages, not registered in METADATA.

**Comment by carlobaldassi** [comment]
@andyferris, @ma-laforge: on my Linux machine, `@time Pkg.resolve()` takes ~1.5 seconds. When profiling, almost all of it is fetching/analysing dependencies. More or less, one third of the time is spent doing `Read.available()` [here](https://github.com/JuliaLang/julia/blob/b378ece5705a44a28ffe4c72f07bd392a58ab6b7/base/pkg/entry.jl#L470), one third `Read.installed()` [here](https://github.com/JuliaLang/julia/blob/b378ece5705a44a28ffe4c72f07bd392a58ab6b7/base/pkg/entry.jl#L471), one third `Query.dependencies()` [here](https://github.com/JuliaLang/julia/blob/b378ece5705a44a28ffe4c72f07bd392a58ab6b7/base/pkg/entry.jl#L478).

Can you do a `@profile Pkg.resolve()` and check where the "exorbitant amount of time" is spent?

More directly related to this issue, `Pkg.add()` has a special case for when dependency resolution is unnecessary, [here](https://github.com/JuliaLang/julia/blob/b378ece5705a44a28ffe4c72f07bd392a58ab6b7/base/pkg/entry.jl#L28). This is really within the `Entry.edit` function though, and in principle this should be used by `Pkg.clone` as well, but it seems that [the check in the latter case is definitely too strict](https://github.com/JuliaLang/julia/blob/b378ece5705a44a28ffe4c72f07bd392a58ab6b7/base/pkg/entry.jl#L203-L206), since it only avoids calling `resolve()` if the `REQUIRE` file is empty.

**Comment by ma-laforge** [comment]
@carlobaldassi : `@profile` returns nothing (I will have to read how to get outputs from it), but I can show you what I get from `@time` for now:

On my celeron, I get a relatively slow time:
```
99.780262 seconds (7.56 M allocations: 333.324 MB, 0.71% gc time)
```
Even on my i3, I get a relatively slow time:
```
22.303634 seconds (7.61 M allocations: 333.447 MB, 0.90% gc time)
```

NOTE: since even my i3 needs >> 1.5 seconds to run, it might have something to do with the fact I have **many** (almost 20) `Pkg.clone()`-ed packages:
```
Pkg.clone("https://github.com/ma-laforge/CData.jl.git")
using CData
CData.install() #Will Pkg.clone() a bunch of packages
```
I don't necessarily expect you try to run this particular test yourself... but I figured I should mention it.

**Comment by carlobaldassi** [comment]
@ma-laforge: I tried that `CData.install()` command on an empty package directory. It took less than 2 minutes to clone/install/build/compile everything. Then, for me, `Pkg.resolve()` takes ~1 second.

In order to use profiling see [this](http://docs.julialang.org/en/latest/stdlib/profile/). Anyway, the easiest approach is:

1. install  the `ProfileView` package (might need to `Pkg.checkout("Gtk")` on julia 0.5 perhaps...)
2. remember to call `Profile.clear()` between tests
3. call `Pkg.resolve()` once to compile stuff, then `@profile Pkg.resolve()` (I dont' think we need to profile compilation times here)
4. call `ProfileView.view()` and inspect the results. The [package README](https://github.com/timholy/ProfileView.jl) explains what you are looking at.

**Comment by ma-laforge** [comment]
> I tried that `CData.install()` command on an empty package directory. It took less than 2 minutes to clone/install/build/compile everything. Then, for me, `Pkg.resolve()` takes ~1 second.

That's good.  It took my i5 about 11min to clone/install/build/compile everything from an empty package directory (not even counting the PyPlot/PyCall-dependant modules).  Then, for me, `Pkg.resolve()` takes about 21sec.

On a clean install with only `METADATA`, `Pkg.resolve()` takes about 4.5sec.

As an FYI: I have seen `Pkg.resolve()` take **89 seconds** (not just 21sec) on my i5.  So it seems this process can get significantly slower.


NOTE: `Pkg.resolve()` appears faster on Linux - even when performed through a VMWare session.

I tried looking at `ProfileView.view()/Profile.print(fileid)` - but I don't know much about the code.  Here is the dominant profile info:

Windows/Julia: v0.4.6 (i5: my faster computer).
```
      2491 pkg/entry.jl; resolve; line: 404
       1594 pkg/read.jl; installed; line: 143
        190 pkg/read.jl; installed_version; line: 85
         161 process.jl; readbytes; line: 514
          161 stream.jl; wait_readnb; line: 374
           161 task.jl; wait; line: 286
            161 task.jl; wait; line: 360
             161 stream.jl; process_events; line: 731
        448 pkg/read.jl; isfixed; line: 62
         307 pkg/git.jl; success; line: 30
          114 process.jl; readbytes; line: 514
           113 stream.jl; wait_readnb; line: 374
            113 task.jl; wait; line: 286
             113 task.jl; wait; line: 360
              113 stream.jl; process_events; line: 731
          150 process.jl; run; line: 531
           150 process.jl; wait; line: 655
            150 stream.jl; stream_wait; line: 60
             150 task.jl; wait; line: 286
              150 task.jl; wait; line: 360
               150 stream.jl; process_events; line: 731
         140 pkg/git.jl; success; line: 32
          127 process.jl; success; line: 545
           127 process.jl; wait; line: 655
            127 stream.jl; stream_wait; line: 60
             127 task.jl; wait; line: 286
              127 task.jl; wait; line: 360
               127 stream.jl; process_events; line: 731
        423 pkg/read.jl; isfixed; line: 63
         290 pkg/git.jl; success; line: 30
          115 process.jl; readbytes; line: 514
           115 stream.jl; wait_readnb; line: 374
            115 task.jl; wait; line: 286
             115 task.jl; wait; line: 360
              115 stream.jl; process_events; line: 731
          137 process.jl; run; line: 531
           137 process.jl; wait; line: 655
            137 stream.jl; stream_wait; line: 60
             137 task.jl; wait; line: 286
              137 task.jl; wait; line: 360
               137 stream.jl; process_events; line: 731
         131 pkg/git.jl; success; line: 32
          109 process.jl; success; line: 545
           109 process.jl; wait; line: 655
            109 stream.jl; stream_wait; line: 60
             109 task.jl; wait; line: 286
              109 task.jl; wait; line: 360
               108 stream.jl; process_events; line: 731
        382 pkg/read.jl; isfixed; line: 64
         264 pkg/git.jl; success; line: 30
          103 process.jl; readbytes; line: 514
           103 stream.jl; wait_readnb; line: 374
            103 task.jl; wait; line: 286
             103 task.jl; wait; line: 360
              103 stream.jl; process_events; line: 731
          126 process.jl; run; line: 531
           126 process.jl; wait; line: 655
            126 stream.jl; stream_wait; line: 60
             126 task.jl; wait; line: 286
              126 task.jl; wait; line: 360
               126 stream.jl; process_events; line: 731
         117 pkg/git.jl; success; line: 32
          100 process.jl; success; line: 545
           100 process.jl; wait; line: 655
            100 stream.jl; stream_wait; line: 60
             100 task.jl; wait; line: 286
              100 task.jl; wait; line: 360
               100 stream.jl; process_events; line: 731
        123 pkg/read.jl; isfixed; line: 65
         104 process.jl; readbytes; line: 514
          104 stream.jl; wait_readnb; line: 374
           104 task.jl; wait; line: 286
            104 task.jl; wait; line: 360
             104 stream.jl; process_events; line: 731
```

**Comment by ma-laforge** [comment]
Well, even if I don't know anything about the code, it seems clear that the call to `process_events` is the bottleneck - taking about 1-1.5 second each time (odd, the resolution appears to be 10ms - not 1ms).

This is the function:
```
function process_events(block::Bool)
    loop = eventloop()
    if block
        ccall(:jl_run_once,Int32,(Ptr{Void},),loop)
    else
        ccall(:jl_process_events,Int32,(Ptr{Void},),loop)
    end
end
```
And `line 731` is executed `if block`: `ccall(:jl_run_once,Int32,(Ptr{Void},),loop)`

**Comment by tkelman** [comment]
The Windows filesystem is notoriously slow, and if you're using an HDD instead of an SSD then it's going to be even worse. The way METADATA is currently designed with thousands of tiny files makes this problem even worse. We need to substantially restructure it to put information in fewer files, in some format that would be a little more expensive to parse but not as hard on the filesystem.

**Comment by wildart** [comment]
It's a known issue. Calling `Pkg.available` need to be avoided.  Instead retrieving all dependency information (by `Pkg.available`), we need recursively read only required one.

**Comment by simonbyrne** [comment]
This has changed considerably with the new Pkg. If still an issue, please open at https://github.com/JuliaLang/Pkg.jl
