### ISSUE TITLE
seeding RNG with 1:n

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#17918]
Quoting [James Douglas on julia-users](https://groups.google.com/forum/#!topic/julia-users/NHoEYB2Df8M):

> I have a question about how Julia handles the seed given to the random number generator through the function srand(seed). I am doing Monte Carlo simulations using Julia, where I have some code that depends on the output from the rand() function and then I run this code with many different initial seeds. Naively I have set the seed specifically for each run of the code as the integer corresponding to the run, i.e., I run the code starting with srand(1), srand(2), etc. up to srand(N) for N runs. My primary motivation for this is that I would like to reproduce a particular run if I see anything strange. However, I recently saw that at least in C++ (http://www.pcg-random.org/posts/cpp-seeding-surprises.html), seeding the Mersenne Twister with integers like this is a bad idea. So I would like to know if there is a problem with seeding Julia's random number generator in this way? Will it bias my sample or does Julia somehow avoid this in the way it processes the seed given to srand()? And finally, if it is a bad idea, what would be the best way to seed so that I can reproduce everything at a later stage?

We should make sure that we've addressed this issue and fix it and/or document the fix.

**Comment by rfourquet** [comment]
To answer partially, indeed the dSFMT lib processes the seed to initialize the state (with a simple random function (a kind of linear congruential generator) when the seed is a single 32 bits integer (not directly used by Julia), and a more complicated one when the seed is an array of number...) So the RNG is always initialized decently (but does not address the problem mentioned in the blogpost...), but AFAIK there is no garanty as to whether two generated sequences could "easily" overlap. E.g. the stream obtained by `srand(1)` could be the same as the one obtained by `srand(0)` after skipping only a small number of initial terms (e.g. 100000, although that's very unlikely, given the huge period of this generator). I'm far from being a specialist in this field, but I think the only way to obtain "independent" (in a controlled way) streams would be to make use of the jump ahead functionality (thanks to @wildart!).

Concerning the problem (mentioned in the blogpost) of initializing a big-state RNG with only few bits (like a 32-bit integer), which exists even with only one stream, Julia does nothing (and can't do anything). This is a problem only in some cases if used without being aware of the problem, and depends on the requirements. In the given twitter example, the fix is easy. If a bigger seed state is required, then Julia makes it easy, e.g. `srand(rand(RandomDevice(), UInt32, 624))` (I would guess the dSFMT lib makes a decent job with the initialization routine of the state, so that the function which maps the input array of `srand` to a state is "almost injective", as long as the input array has fewer bits than the state, i.e. is a good hash function).
So the fix is probably to document the problem, maybe simply by linking to the blogpost (and few comments).

**Comment by andreasnoack** [comment]
I'll add that for simulations, the issues mentioned in the blog post don't apply and I think it's very useful to be able to seed with an integer. Regarding the two points mentioned in the blog post

- It should be well known that the Mersenne Twister is not for crypto so the predictability argument is a straw man.

- The bias argument might apply. I don't know but for Monte Carlo simulations, it shouldn't matter because you'll draw a lot of numbers after the seed has been set. If this problem does apply, it shouldn't be as severe as in C++ because we use 4x32 bit integers from the random device instead of only a single.

So my conclusion is the same as @rfourquet's. I don't really think we have a problem but it's fine to keep this as a documentation issue.

**Comment by cstjean** [comment]
> the stream obtained by srand(1) could be the same as the one obtained by srand(0) 

Is `srand(n+1)` more likely to overlap/be correlated with `srand(n)` than other values of `n`?

**Comment by andreasnoack** [comment]
> Is `srand(n+1)` more likely to overlap/be correlated with `srand(n)` than other values of `n`?

I don't think so. I'm pretty sure the seed function in dSFMT tries to avoid that but I can't find the reference.

**Comment by tpapp** [comment]
For reproducible research, a `make_seed{T <: AbstractRNG}(::Type{T})` would be useful, which

1. returns a seed compatible with an RNG type,
2. makes a best effort for randomness (trying a random device, using a hash from time if that fails, etc),
3. but **doesn't change the state** of anything in Julia (of course it would change the state of the machine and this would not be purely functional etc).

This could of course be called by `srand`, factoring out the existing approach, and it would also allow existing
```julia
srand(1)
```
and similar in library tests to be replaced with
```julia
# simulating with fixed random seed for reproducibility
srand(MersenneTwister(UInt32[0xffaf5807,0x7fbcfc14,0xeda2020a,0x65d5b03f]))
```

**Comment by andreasnoack** [comment]
@tpapp If you just want to set the seed, why is `srand(1)` not sufficient for reproducibility? Do you want to be able to set the global RNG as well, e.g. to something different from our `MersenneTwister`?

**Comment by tpapp** [comment]
@andreasnoack I have similar concerns as the OP; I don't know whether seeding with small integers is sufficient, in the sense that it gives rise to random sequences that have the same properties as some best effort seeding. In particular, I would be concerned about everyone seeding their simulations with small integers in some particular field of research. I would prefer if there was a convenient way to generate a "best effort" random seed that I could save and reuse. These are, of course, minor concerns, and I can just grab `(srand(); Base.Random.GLOBAL_RNG.seed)`, but that API is not exported.

**Comment by simonbyrne** [comment]
@tpapp I think you're slightly missing the point. From the point of RNGs, any one seed is as good as any other (if it isn't, you have a bad RNG). The problem here is that when you restrict your *set* of possible seeds to a set which is much smaller than your RNG state space, you necessarily restrict the possible set of values on the first call to `rand()`.

That said, we could probably rejig the seeding interface a bit (I, for one, would like to rename `srand`).

**Comment by StefanKarpinski** [comment]
Yes, but this is true of any choice of `n` fixed seed values. The key points are:

Is `1:n` worse than any other choice of `n` fixed seed values? It seems like the answer here is no.

Can we provide a simple API for choosing a "seed seed" that lets you choose a different fixed set of seed values for each application. If choosing sequential seed values is ok, then this could be as simple as using `fixed_base_seed + 1:n` as the seed values.

**Comment by tkelman** [comment]
What is the action required here?

**Comment by StefanKarpinski** [comment]
Related:

- http://stackoverflow.com/questions/40771160/how-correlated-are-i-d-d-normal-numbers-in-julia
- http://www.stat.berkeley.edu/~kellieotto/research.html

I think there are a few things we should do here:

1. By default, hash RNG seed values with a strong cryptographic hashing algorith, like SHA3 and use the result of that to feed the underlying RNG seeding function. This will address the issue of seeding with `1:n` or any other "simple" pattern of seeds thoroughly, while remaining deterministic.

2. Once we're passing seed values to SHA3, we might as well allow passing in multiple hash values, e.g. `srand(2, 3, 1)`. That way producing independent streams in different tasks or process is simple: worker group `g` on node `n` in task `t` uses the stream seeded with `srand(g, n, t)` and those will all be independent. This is relatively easy, but the `srand` function might as well do it for you.

3. When `srand` is called, we should require passing in both an RNG *and* seed values. The point of `srand` is to fully determine a sequence of pseudorandom values – the seed is only part of what determines that, the RNG type is the other part. This is a problem for the implicit global RNG since we can't allow its type to change (currently), but we could at least check that it's the same as expected and raise an error if it's not, which allows us to change default RNGs in the future.

**Comment by StefanKarpinski** [comment]
I still think we should do 1 and 2 but 3 is kind of impractical, so we should probably just advise people that for forward compatibility they should create their RNG object and use it.

**Comment by StefanKarpinski** [comment]
The way RNG and srand works will likely have to be broken by threading as well, so we should coordinate breakages so as not to introduce two of them.

**Comment by rfourquet** [comment]
For 1.) what would be the plan to get sha2/3? import the implementation from https://github.com/staticfloat/SHA.jl ? As sha1 is available from libgit2, which is already there (will it stay?), would it be good enough? Is having multi-threaded RNG planned for 1.0?

**Comment by StefanKarpinski** [comment]
Nobody seems to care much about this who actually uses RNGs so, we can just make seeding via a strong cryptographic hash or better hashing function opt-in. We already include MurmurHash in libjulia so that would be a decent option that doesn't require any extra dependencies, but people seem to feel that this is out of scope for Base Julia.

**Comment by JeffBezanson** [comment]
This can be addressed by new RNG types (possibly in packages) that pre-process seeds or just naturally work better with 1:n seeds.

**Comment by StefanKarpinski** [comment]
Since we've resolved to [vehemently document](https://github.com/JuliaLang/julia/issues/23624) that the default RNG can change, we can also make the default RNG do something better in the future if we want to (e.g. feed through MurmurHash).
