### ISSUE TITLE
data race calling jl_gc_wb_buf

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#17971]
This global [big_objects_marked] is accessed by `gc_setmark_big`, which is called by `gc_setmark_buf`, which is called by `jl_gc_wb_buf`, which can be called concurrently by two mutator threads.

**Comment by vtjnash** [comment]
It looks like several of the code paths for jl_gc_wb_buf may be race-y. Should we just lock the whole operation?

In `gc_setmark_pool_`, I think the only critical race is on `ages`. Although some of counters such as `page->nold++;` aren't atomic either.

In `gc_setmark_big`, the call to `gc_big_object_unlink` is also race-y, since the argument (hdr) is derived from a global value.

**Comment by StefanKarpinski** [comment]
Can we start putting milestones on everything, even if they'll have to be revised later?

**Comment by yuyichao** [comment]
The unlink should be fine since this is actually only used when the buffer is just allocated by the current thread. Maybe the right solution is to queue the parent in another remset instead of marking the buffer?
