### ISSUE TITLE
build failure on Raspberry Pi 3

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#18042]
My last successful build was 0.6.0-dev.212 at b80dad4 .
```
raspberrypi% make
    CC src/sys.o
    CC src/runtime_ccall.o
    CC src/codegen.o
    LINK usr/lib/libjulia.so.0.6.0
    PERL base/version_git.jl.phony
    JULIA usr/lib/julia/inference.ji
WARNING: unable to determine host cpu name.
essentials.jl
generator.jl
reflection.jl
options.jl
promotion.jl
tuple.jl
range.jl
expr.jl
error.jl
bool.jl
number.jl
int.jl
operators.jl
pointer.jl
abstractarray.jl
array.jl
hashing.jl
nofloat_hashing.jl
reduce.jl
intset.jl
dict.jl
iterator.jl
docs/core.jl
inference.jl
LLVM ERROR: Program used external function '__sync_lock_test_and_set_4' which could not be resolved!
Makefile:215: recipe for target '/home/sachs/src/julia-master/usr/lib/julia/inference.ji' failed
make[1]: *** [/home/sachs/src/julia-master/usr/lib/julia/inference.ji] Error 1
Makefile:96: recipe for target 'julia-inference' failed
make: *** [julia-inference] Error 2
```

**Comment by yuyichao** [comment]
LLVM bug.

**Comment by yuyichao** [comment]
This is fixed on LLVM 3.9 by https://github.com/JuliaLang/julia/pull/16066 . AFAIK there's no easy way to fix this on earlier LLVM versions.

**Comment by yuyichao** [comment]
Reopen since it seems that the LLVM handling of atomics on ARM is still very buggy. I need to check if this is fixed on SVN now. This is still an upstream issue though. An easy way to workaround is to ask for a armv7 cpu target.

**Comment by josefsachsconning** [comment]
Is that done via JULIA_CPU_TARGET=cortex-a7 in Make.user?

**Comment by josefsachsconning** [comment]
Built successfully with `JULIA_CPU_TARGET=cortex-a7`.

**Comment by ViralBShah** [comment]
Will disabling threading help? I am ok to move to LLVM 3.9 on arm, but we need to wait for the release.

**Comment by yuyichao** [comment]
Disabling threading won't really now since the code path is not conditional (it could though). Looking more closely at the llvm atomic doc, it seems that llvm can still use the __sync functions and those should be stateless so it's okay to have multiple copies in the process. The two thing I need to check here are,

1. Figure out what feature flags/cpu names makes LLVM emit the instructions directly instead of a function call and if we can just require those features. We already require vfp2 which is almost armv6+. This can also potentially makes gdb less confused when no jit target is specified.
2. Provide these symbols for the JIT and sysimg. Not sure what's the best way to do this yet.

**Comment by ViralBShah** [comment]
On scaleway, `cortex-a7` did not help build master.
