### ISSUE TITLE
Static compilation doesn't use `__init__`

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#18115]
It appears that static compilation does not call the `__init__`. Take the two modules below as an example:

```julia
module StaticFail

export @process

# global ENABLED = true  # static compilation works if I uncomment out this line
function __init__()
    global ENABLED = true
end

macro process(expr)
    ENABLED && return esc(expr)
    error("ENABLED is not set")
end

end
```

```julia
module StaticFailDemo

using StaticFail
export demo
demo() = @process 1 + 1

end
```

Calling `demo()` from within the REPL works as expected with and without pre-compilation but static compilation produces the following exception:

```
...
LoadError("sysimg.jl",381,LoadError("~/Development/Julia/0.5/base/userimg.jl",1,LoadError("~/.julia/v0.5/StaticFailDemo/src/StaticFailDemo.jl",5,UndefVarError(:ENABLED))))
ERROR: LoadError: failed process: Process(`~/Development/Julia/0.5/usr/bin/julia -C native --output-ji /tmp/sys.ji --output-o /tmp/sys.o -J /tmp/inference.ji --startup-file=no sysimg.jl`, ProcessExited(1)) [1]
```

**Comment by JeffBezanson** [comment]
This is intentional; when code is only being compiled we don't consider it to be at run time. The reasoning was that `__init__` is often used by a library to discover something about its run time environment on startup, and we didn't want compiled libraries to bake-in information about the compile time environment instead.

It's also worth nothing that the same error would happen if you used `@process` within the `StaticFail` module, since macros run before the module is closed and so before `__init__` runs. So having macros depend on `__init__` is a bit dodgy in general.

**Comment by vtjnash** [comment]
Yes. I also confirmed this works with incremental compilation, as intended.

**Comment by omus** [comment]
For some reason I was under the impression that `__init__` would run at compile time as well as run time. The global I defined should actually be defined at the top level. Thanks for clearing things up.

**Comment by StefanKarpinski** [comment]
Should this be documented somewhere?

**Comment by vtjnash** [comment]
yes, it does seem like http://docs.julialang.org/en/latest/manual/modules/#module-initialization-and-precompilation may lead someone to expect otherwise

**Comment by StefanKarpinski** [comment]
Reopened as a documentation issue.
