### ISSUE TITLE
switch from GNU Make to CMake?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#1832]
I'm creating this issue to discuss the possibility of standardizing our build system on CMake, which seems to be getting significant traction as a saner, cross-platform build system than Make. If we decide to use this to build Julia, we may want to standardize on it as a standard build system for Julia packages that need to compile things too.

**Comment by vtjnash** [comment]
discussion can continue on the PR (#11754), if necessary. however, i don't think we really need to revisit this. the slow build times and msvc issues are as much a function of our dependencies (if not more), and switching julia to cmake wouldn't address that.

**Comment by tkelman** [comment]
msvc on gmake is a hack that doesn't work at all in msys2 (they broke that) so that would really be the main motivation for switching. agreed though that the deps are the messy part of this.

**Comment by lilinjn** [comment]
one small win for having a cmake build it that is some ide's have very good support for project configuration (clion and qt creator mainly, and but also in a slightly less integrated way, eclipse/xcode/visual studio (clion/qt creator make an effort at grokking cmake, and allowing users to make intelligent changes to both the source and cmake build files, the others are supported by cmake but there are limits to the scope of changes that are convenient to make in a cmake generated IDE project))    

As an example, since llvm uses cmake, a great way to start grokking how it works it to clone it, and open the CMakelists.txt in clion and start from various examples and hop "backwards" into deeper parts of the core system.  Not only do you have robust/template aware navigation within the entire code base, but you can easily run/debug examples, or just start hacking including adding new files, new libraries, etc.  The net experience is a much lower barrier to entry for new developers who want to grok the code base. (nb. clion can be slow on llvm due to its size and project complexity though I find usable on a high end workstation)

Along the same lines, aside from cmake, a minimal but useful improvement would be to make sure that the current Makefile based system generates a [compile_commands.json](http://clang.llvm.org/docs/JSONCompilationDatabase.html) file (cmake builds provide this easily, but there are many other systems (e.g.Bear) that also achieve this for other scenarios like Makefile projects).  This opens the possibility for using various clang based tools (e.g. rtags, FB's nuclide, maybe about 8 others) to help initially grokking the code base.   

Basic point it that using a main stream build system opens the possibility for new developers to use existing tools accelerate the speed at which they can grok julia internals.

Should these comments be on the PR(#11754)?

**Comment by jmigual** [comment]
So, CMake has gone a long way since this issue was opened almost 11 years ago. I think right now CMake is quite a mature setup (still with some minor quirks) that is supported in most of the IDEs. Would it make sense to reopen this discussion about problems and solutions?

**Comment by StefanKarpinski** [comment]
You can comment on a closed issue, absent evidence that there's actually a problem, we're not going to reopen. What are some actual problems that you (or anyone) has with Julia's use of make? Make is the worst build tool, except for all the others.

**Comment by jmigual** [comment]
Indeed, I am revisiting this closed issue because it was concluded 7 years ago, and I believe it's worth reevaluating in light of changes and advancements since then. I don't think it's fair to be penalized for trying to assess what has evolved and how we could improve. Here are some areas where Make falls short and where CMake could potentially offer improvements:

- **Windows Compatibility**: Currently, using Make on Windows requires installing an entire environment that emulates a Unix setup, such as Cygwin or MSYS2. This introduces an additional layer of complexity and potential sources of errors for Windows users.
- **Compiler Support**: CMake provides extensive support for a variety of compilers, including MSVC and clang-cl, offering more flexibility and options for users.
- **Existing Dependency**: It's worth noting that CMake is already a build dependency of Julia.
- **Management of External Dependencies**: CMake simplifies the management of external dependencies through features like ExternalDependency and FetchContent, making the build process more efficient and manageable.

In a properly set up CMake environment, a user unfamiliar with the project could build and install Julia as follows, with dependencies included:

```shell
git clone https://github.com/JuliaLang/julia.git
cmake -B build -S julia
cmake --build build
cmake --install build
```

I believe these points substantiate the consideration of CMake as an alternative to Make for Julia’s build system. I look forward to further discussion on this matter.

**Comment by StefanKarpinski** [comment]
> I don't think it's fair to be penalized for trying to assess what has evolved and how we could improve.

Nobody is being penalized, I just don't want to reopen an issue for no reason.

> **Windows Compatibility**: Currently, using Make on Windows requires installing an entire environment that emulates a Unix setup, such as Cygwin or MSYS2. This introduces an additional layer of complexity and potential sources of errors for Windows users.

WSL seems like a pretty good option for those who want to develop Julia on Windows systems. But sure, point taken, being able to build Julia natively without MSYS2 would be nice. That said, WSL, Cygwin and MSYS2 all exist.

> * **Compiler Support**: CMake provides extensive support for a variety of compilers, including MSVC and clang-cl, offering more flexibility and options for users.

I don't think we're interested in supporting building Julia with other compilers. We tried supporting building Julia with MSVC and it was not a success. It never worked, it was a lot of work to even try to support, and unless we waste a lot of CI resources constantly testing it, it will just bitrot.

> * **Existing Dependency**: It's worth noting that CMake is already a build dependency of Julia.

Only if you're building all dependencies from source, which there's not much reason to do.

> * **Management of External Dependencies**: CMake simplifies the management of external dependencies through features like ExternalDependency and FetchContent, making the build process more efficient and manageable.

I guess, but we have a system that works very well already and switching to this would be a bit process for little benefit. If we didn't have that system, sure, but we do.

> In a properly set up CMake environment, a user unfamiliar with the project could build and install Julia as follows, with dependencies included:
> 
> ```shell
> git clone https://github.com/JuliaLang/julia.git
> cmake -B build -S julia
> cmake --build build
> cmake --install build
> ```

Ok, but you can already build and install Julia just by doing
```shell
git clone https://github.com/JuliaLang/julia.git
make install
```

The final question of course is: Who would do this? Are you willing to spearhead changing the build system to CMake? If you want to do that and you come up with a much better build system, I don't think anyone would object, but I think that the devs are pretty ok with using `make`. This seems like a lot of work to go from having a working build system to having a (different) working build system.

**Comment by jmigual** [comment]
I see, you make a good case for the other points. So, the biggest "issue" of the current build system is the dependency on MSYS2.

> The final question of course is: Who would do this? Are you willing to spearhead changing the build system to CMake? If you want to do that and you come up with a much better build system, I don't think anyone would object, but I think that the devs are pretty ok with using make. This seems like a lot of work to go from having a working build system to having a (different) working build system. This is open source, so you can't just argue that something would be better and expect someone else to do it. Someone who really wants Julia to use CMake has to make it happen—you can't just make an argument that it would be better and expect others to do it for you because you made a good case. You have to either do it or convince someone to do it.

Regarding this, I would suggest having both build systems but keeping CMake as unofficially supported. This means that the julia developers don't work on the CMake build system, but that PRs are accepted. I've seen multiple projects go through these steps ([mixxdj](https://github.com/mixxxdj/mixxx) or [C++ boost](https://www.boost.org/) libraries being two examples). 

Right now, there's a fork that started adding CMake support (https://github.com/Neumann-A/julia/tree/add_cmake) although I was not able to build it. So, we could start from there.

**Comment by PallHaraldsson** [comment]
>I would suggest having both build systems but keeping CMake as unofficially supported.

That seems like the worst of both worlds, duplication, to have two systems, unless it's a temporary thing until you migrate, and you actually plan to do that.

I thought you meant Boost has booth, but I find no Makefile there, only CMake support. The unofficial CMake can you made to work in a fork, but I don't strictly oppose it here.

Also I have no say in this, I can sort of read Makefiles, but don't really want to edit them (here), nor need to. They are ugly and CMake seems maybe more readable, but as you wrote it doesn't (yet) work for Julia...

Would it be valuable to only make CMake for Windows work? I suppose such a file could be simpler.

**Comment by jmigual** [comment]
> That seems like the worst of both worlds, duplication, to have two systems, unless it's a temporary thing until you migrate, and you actually plan to do that.

I think that even if temporary, it can still take a very long time. While, I'm confident on CMake, I know nothing on the build requirements of julia so the build transition would require me to read and understand lots of Makefiles.

> I thought you meant Boost has booth, but I find no Makefile there, only CMake support. 

Boost always used a build system called b2 similar to autotools which was designed to build only boost. That system is still there and is the [currently officially supported system](https://www.boost.org/doc/libs/1_83_0/more/getting_started/unix-variants.html#prepare-to-use-a-boost-library-binary). They've been trying to move to CMake for more than 5 years and right now it's on a usable state. In their case, the move to CMake is more important than for Julia, as, being Boost a library, it needs to be easy to incorporate with other projects and CMake helps a lot in that sense.

> The unofficial CMake can you made to work in a fork, but I don't strictly oppose it here.

Good, even if it's on a fork, the best way would be to avoid deleting any existing build file to guarantee that the original system still works. The fork that I pointed deleted some files so it cannot be directly added to julia right now.

> Also I have no say in this, I can sort of read Makefiles, but don't really want to edit them (here), nor need to. They are ugly and CMake seems maybe more readable, but as you wrote it doesn't (yet) work for Julia...
>
> Would it be valuable to only make CMake for Windows work? I suppose such a file could be simpler. And the other Makefile could maybe refer to it for other platforms, needing both..., but not at first?

This could be a start yes. On the other side, if you write your CMake files properly from the beginning, it is quite easy to port to other platforms. The stages I see are:

1. Julia builds on Windows with CMake
2. Tests build and pass on Windows with CMake
3. Julia builds all platforms with CMake
4. Tests build and pass on all platforms with CMake

Now, a question I have is. If we had a PR adding CMake. At which stage (1-4) would we accept a PR adding it?

**Comment by vchuravy** [comment]
I once tried doing this. I didn't enjoy it... I also recommend looking how other large projects use CMake. LLVM our biggest dependency essentially has written a new CMake-dialect to support their needs.

When I have fever dreams about this I tend to want to try out meson.

> Would it be acceptable to use a package manager with the CMake build

I am very hesitant on this. We need not just provide an environment for building Julia, but make sure that all the binaries used are ABI compatible. We achieve this right now by standardizing the build and using Yggdrasil to cross-compile libraries for windows.

**Comment by vtjnash** [comment]
We have enough cmake dependencies already, that option 5 instead is probably acceptable: convert only some part, but convert it completely. An example of this might be to move the llvm.mk and libuv.mk files to be cmake subprojects of a singular cmake project in deps (with only shims remaining in the deps/Makefile)
