### ISSUE TITLE
reversed patch

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#18411]
In going from `master` to `release-0.5`, I got prompted with `Reversed (or previously applied) patch detected!  Assume -R?`. Might have been for gmp, not sure (it scrolled off too quickly).

Feel free to close if this is useless.

**Comment by tkelman** [comment]
it is gmp. due to the build system rewrites, you're better off using separate clones for master vs 0.5. the name of the patch-applied file being used there was changed so you likely need to `make -C deps distclean-gmp` to get things consistent. i don't think this hassle is worth what that rewrite may have fixed, but there you have it.
