### ISSUE TITLE
Make embedding dirt-simple

### ISSUE THREAD

**Issue by twadleigh** [JuliaLang/julia#18421]
Embedding should work uniformly across all supported platforms according to the documentation. Further, embedding Julia installed in the standard way for a platform should require no arguments to `jl_init`.

Some related issues: #6327, #8757 , #14163, #17657.

**Comment by twadleigh** [comment]
Getting `jl_init` to the point where it can be called without arguments is straightforward. Since it resides in `libjulia`, it (or some function within `libjulia` that might be in its call chain) can determine the path to the `libjulia` that is currently being called (via ). From that, `JULIA_HOME` can be inferred, as well as the paths to try for the julia executable (cf. #18437) and system image.

**Comment by StefanKarpinski** [comment]
I've marked as milestone 1.0 but this could ideally happen sooner.

**Comment by twadleigh** [comment]
I'm actively working it.

**Comment by vtjnash** [comment]
For 1.0, I think ideally `./julia` will link against `sys.so` directly and dispense with our duplication of the system linker. But since this complicates the `-J` option, we aren't quite there yet, and I'm not sure the specifics of the best way to fix that. For embedding applications though, I think that's already definitely the way to go (and jl_init just needs to be updated to accept the handles directly rather than using dlopen to look them up).

**Comment by tkelman** [comment]
can we call this fixed by https://github.com/JuliaLang/julia/pull/21299 ?

**Comment by KristofferC** [comment]
I think so, yes.
