### ISSUE TITLE
Return index vectors from unique

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#1845]
In Matlab, `unique` can return optional index vectors, such that one can construct the unique version from the input and vice versa. This is quite handy, and would be nice to have in julia.

http://www.mathworks.com/help/matlab/ref/unique.html

We would probably need the function to be called `unique_ind` or something, until we have keyword args.

**Comment by ViralBShah** [comment]
What we need is `uniqueperm` and then implement `unique` using that.

**Comment by tkelman** [comment]
Would `uniqueperm` return the second output from the Matlab version, or the third output? Both are quite useful in different applications.

Side note, one of the most aggravating things Mathworks ever did IMO was changing the default result ordering of the index outputs from `unique` from "last match" to "first match." That broke so much of my code...

**Comment by StefanKarpinski** [comment]
Unique perm wouldn't actually return a permutation, would it?

**Comment by tkelman** [comment]
ah yeah it's not really the same thing, you get a many-to-few index map and/or a few-to-many index map

**Comment by StefanKarpinski** [comment]
Let's not call it "perm" then.

**Comment by ViralBShah** [comment]
Yes, it is not strictly a permutation. Perhaps a selection or something.

**Comment by DrGar** [comment]
Hello. I am totally new to julia/GitHub, but am a lifelong matlab-er who is very impressed with the language. I needed some of this functionality for code that I am trying to port over from matlab, so I went ahead and took the open source octave code and modified it to work in julia. It probably only works for arrays, and may not have optimal speed, but it seems to be doing what I need. Maybe it (along with the original source octave file) will provide a good starting point for someone who knows what they are doing to make it work generally/correctly/well. 


<pre><code>
# This file is a modified version of unique.m from the octave language that was downloaded here:
# http://code.metager.de/source/xref/gnu/octave/scripts/set/unique.m
# It has been modified by Garrett Jenkinson to work in Julia.
# It came with the following header. 


## Copyright (C) 2000-2013 Paul Kienzle
## Copyright (C) 2008-2009 Jaroslav Hajek
##
## This file is part of Octave.
##
## Octave is free software; you can redistribute it and/or modify it
## under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or (at
## your option) any later version.
##
## Octave is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with Octave; see the file COPYING.  If not, see
## <http://www.gnu.org/licenses/>.

## -*- texinfo -*-
## @deftypefn  {Function File} {} unique (@var{x})
## @deftypefnx {Function File} {} unique (@var{x}, "rows")
## @deftypefnx {Function File} {} unique (@dots{}, "first")
## @deftypefnx {Function File} {} unique (@dots{}, "last")
## @deftypefnx {Function File} {[@var{y}, @var{i}, @var{j}] =} unique (@dots{})
## Return the unique elements of @var{x}, sorted in ascending order.
## If the input @var{x} is a vector then the output is also a vector with the
## same orientation (row or column) as the input.  For a matrix input the
## output is always a column vector.  @var{x} may also be a cell array of
## strings.
##
## If the optional argument @qcode{"rows"} is supplied, return the unique
## rows of @var{x}, sorted in ascending order.
##
## If requested, return index vectors @var{i} and @var{j} such that
## @code{x(i)==y} and @code{y(j)==x}.
##
## Additionally, if @var{i} is a requested output then one of @qcode{"first"} or
## @qcode{"last"} may be given as an input.  If @qcode{"last"} is specified,
## return the highest possible indices in @var{i}, otherwise, if @qcode{"first"}
## is specified, return the lowest.  The default is @qcode{"last"}.
## @seealso{union, intersect, setdiff, setxor, ismember}
## @end deftypefn

function uniqueOct(x)  
  n = length(x);

  y = deepcopy(x);
  ## Special cases 0 and 1
  if (n == 0)
    i = j = []
    return y, i, j
  elseif (n == 1)
    i = j = 1;
    return y, i, j
  end

  i=sortperm(y)
  sort!(y)

  match = falses(n-1)
  intMatch = zeros(Int,n-1)
  for index=1:(n-1)
    match[index] = y[index] == y[index+1]
    if match[index]
      intMatch[index]=1
    end 
  end
  idx = find(match);

  j = deepcopy(i)

  j[i] = cumsum(cat(1,1,(1-intMatch)))

  for index=length(idx):-1:1
    splice!(y,idx[index])
    splice!(i,idx[index]+1)
  end

  return y, i, j

end
</code></pre>

**Comment by johnmyleswhite** [comment]
Hi @DrGar, I'm really glad you're excited about Julia. Unfortunately, posting GPL code in a public forum puts us in legal danger, so I deleted all of the code you posted without reading it. It's a frustrating limitation, but you cannot safely post code to GitHub that you don't own the copyrights to.

**Comment by DrGar** [comment]
I'm extremely sorry about that mistake. I thought the octave code was open sourced and free to modify/redistribute. Did not realize the GPL aspect could cause you guys problems :-/

**Comment by johnmyleswhite** [comment]
Don't worry about it. I caught it fast enough that it's not an issue. I just wanted to make sure you understood why I edited your comment.

**Comment by nalimilan** [comment]
@johnmyleswhite I think your statement is a bit too strong here. Posting the GPL code in public does not create any legal danger. Please don't spread the idea that GPL is something dangerous.

The problem is only about Julia developers being suspected of having read and taken inspiration of this code when writing BSD-licensed code in Julia. (So I agree it's better remove the code from this issue.)

**Comment by johnmyleswhite** [comment]
@nalimilan: You're right. The correct summary is that posting GPL code in a public forum read by Julia developers is dangerous. Posting GPL code on the internet is harmless. It's only when you post the code somewhere that could be construed as influencing Julia's development that Julia is put in jeopardy.

**Comment by StefanKarpinski** [comment]
We probably err on the side of being more vigilant than necessary, but we really do not want to accidentally create a situation – or the perception of one – where Julia is violating the copyrights of other projects, GPL or otherwise. If our GitHub repositories are littered with GPL code and even vaguely similar code – written independently – ends up in Julia, that could cause some very unfortunate legal doubts. This is why we're very careful not to post any GPL or proprietary code around here.

**Comment by AndyGreenwell** [comment]
Please review the PR in #14142 and provide any comments related to implementation (choice of output arguments, efficiency of algorithmic choices, etc.) as well as documentation, and function name.  I do still need to add a few tests for automated testing purposes, but there are a few examples of usage in the doc string.

**Comment by ViralBShah** [comment]
This functionality was implemented in https://github.com/AndyGreenwell/GroupSlices.jl. We can decide to refactor it, or bring into base as necessary.

**Comment by tribut** [comment]
Given that the package is abandoned and unusable on current Julia, is there any interest to bringing this to Base eventually?

**Comment by kmsquire** [comment]
@tribut see https://github.com/AndyGreenwell/GroupSlices.jl/pull/9.

**Comment by ueliwechsler** [comment]
Since GroupSlices does not seem to be maintained. Maybe this functionalities, as other julia implementations of Matlab functions could be added to the package [https://github.com/ChrisRackauckas/VectorizedRoutines.jl](url).

**Comment by StefanKarpinski** [comment]
The way forward with GroupSlices (Andy seems unresponsive—he probably never looks at GitHub anymore), is to figure out if there's a clean and relatively simple API to be extracted from it that covers the common use cases and then maybe import that into Base or put it into a new package. As I recall, there was a PR to put it into Base but it was just a little too sprawling of an API to be satisfying.

**Comment by biona001** [comment]
Has anything been done to include the functionalities of GroupSlices.jl into Base?

**Comment by StefanKarpinski** [comment]
That’s what my last comment was addressing: what was attempted, why it wasn’t satisfactory, and what would need to be done to make forward progress.

**Comment by juliohm** [comment]
From the discussion in this thread it is not clear what is the current status of this more general interface (i.e. `sort/sortperm`, `unique/uniqueind`, ...). Is there a package where the ideas discussed here are being explored?

**Comment by stevengj** [comment]
Note that since `unique` nowadays accepts a function argument (#13622), you can simply implement `uniqueind` by:
```jl
uniqueind(x) = unique(i -> x[i], eachindex(x))
```
as suggested [here](https://discourse.julialang.org/t/unique-indices-method-similar-to-matlab/34446/3?u=stevengj).

Since this is a one-liner, there's not a pressing need to provide a library function for this.  On the other hand, this trick is not obvious to new users and it seems to be [requested a lot](https://discourse.julialang.org/t/is-there-a-function-similar-to-numpy-unique-with-inverse/80949/6?u=stevengj).

**Comment by stevengj** [comment]
I guess that's not quite the same thing, however, because it doesn't allow you to invert the `unique` function (you can't reconstruct the input array from `unique(a)[indices]`).
