### ISSUE TITLE
anonymous function calls have a huge overhead

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#1864]
A surprising factor of 100 slowdown in this simple example:

    julia> A = rand(100000);
    
    julia> foo(X) = for i = 1:numel(X); X[i] *= 2; end
    
    julia> bar(s) = X -> for i = 1:numel(X); X[i] *= s; end
    
    julia> @time foo(A)
    elapsed time: 0.008594989776611328 seconds
    
    julia> @time foo(A)
    elapsed time: 0.0002551078796386719 seconds
    
    julia> baz = bar(2)
    #<function>
    
    julia> @time baz(A)
    elapsed time: 0.048172950744628906 seconds
    
    julia> @time baz(A)
    elapsed time: 0.0285341739654541 seconds

I'm guessing there is some lack of JIT-ing going on?  This affects #1856.

**Comment by mauro3** [comment]
@carnaval any progress on the typed anonymous functions?  I would appreciate having those a lot! Of course, having typed generic functions will be nice too.   However, typed anonymous functions would cover 90% of my use-cases already and would be nice to have in itself.

**Comment by carnaval** [comment]
Hum. That branch must have bitrotten since then. I remember there was (unsurprisingly)  problems rebasing on top of the call overload thing. I'll try to get it back in proof-of-concept state but I won't have time to actively develop it for the coming month. Maybe opening a PR will bait someone in taking up the work :)

**Comment by JeffBezanson** [comment]
fixed by #13412.

**Comment by shashi** [comment]
:tropical_drink:

**Comment by rfourquet** [comment]
:D
