### ISSUE TITLE
nan method 

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#18676]
Add to base the following
`nan{T<:AbstractFloat}(::Type{T}) = convert(T, NaN)`
 and 
`nan(x::AbstractFloat) = oftype(x, NaN)`

Would these methods be useful in base? I have defined these methods in a pr to libm.jl  and they provide an alternative to `T(NaN)` where `T` is a type.  This mirrors `one(T)`, `zero(T)`, and for the `+-Inf` cases we already have `typemax` and `typemin`

**Comment by stevengj** [comment]
`zero` and `one` are different because they are the additive and multiplicative identities for a given type, which may not be numbers at all.  e.g. `zero(rand(10))` is very different from `oftype(rand(10), 0)`

In contrast, `NaN` only makes sense for floating-point numeric types.

**Comment by JeffBezanson** [comment]
Yes, if `T(NaN)` works acceptably I'd prefer not to add too many ways to do the same thing.

**Comment by timholy** [comment]
We used to have this, and then got rid of it. I've actually brought it back to life in ColorVectorSpace:
```jl
julia> nan(RGB{Float32})
RGB{Float32}(NaN32,NaN32,NaN32)
```
because I don't think it makes sense to support `RGB(::Number)` (you want there to be 3 numbers).

But I agree as a general thing in Base it may not make sense. The only concern might be that if different packages define it, the definitions will be incompatible. As far as I know, this has not yet been a problem in practice.

**Comment by tkelman** [comment]
> The only concern might be that if different packages define it, the definitions will be incompatible

The strategy right now for that would probably be to pick a small common dependency package that other authors can agree to import it from, and add it there. NaNMath would probably be an uncontroversial home for this one.
