### ISSUE TITLE
Julia exceptions do not seem compatible with c++ stack unwinding semantics

### ISSUE THREAD

**Issue by lilinjn** [JuliaLang/julia#18862]
From julia, if I call a native library implemented in c++,                  

- which then calls a  julia callback (wrapped via `cfunction`), 
- which then throws an exception (e.g. `error(msg)`), then

it does not seem that c++ destructors are being called (leading to leaks) as the stack is being unwound back to the original julia `ccall` (code snippet attached below). 

Does this behavior seem consistent with the internals of Julia's implementation of exception handling? 
LLVM seems to have support for emitting EH frames so, naively, it seems like codegen could actually support unwinding c++ stacks , but at this point I don't know enough of the julia internals to reason more broadly about what behavior to expect in my scenario, or if it is feasible to change julia to support c++ stack unwinding semantics.  Any further details would be greatly appreciated...

(In my particular scenario, I have enough control over the source that I can revert to C style "error code return values" to work around any issues, and I realize that ffi's rarely (never?) support exceptions traversing language boundaries, but partly for reasons of aesthetics and also just to more broadly document julia behavior, I would like to better understand the limits of what might be possible.)

````
## code sketch clarifying my scenario; nb. may have typos
## Julia side 
good() = println("good"); bad() = error("bad");
native(f) = ccall((:entry, :mylib), Void, (Ptr{Void},), cfunction(f, Void, (Void,)))

## native entry point, happens to be an "externed c" c++ function
void entry(void (*f)(void)) {
  struct sentinel {
    sentinel() { std::cout << "Now my watch beings..." << std::endl; }
    ~sentinel(){ std::cout << "My watch has ended."    << std::endl;; }
  }   sentry;  
  f();
}
````
example output: 

 ````
  julia> native(good)
  `````
  Now my watch beings...
  good
  My watch has ended.

 ````
  julia> native(bad)
  `````
  Now my watch beings...
  Error: bad
  etc. plus stack trace, but no end of watch

 ````
  julia> 
  `````

**Comment by yuyichao** [comment]
I think you need to catch the exception in cfunction and propagate it in another way. Doing this for our exception for all cases requires unwind info in all external C code (or a way to distinguish the ones that don't, which isn't really possible). Unfortunately we can't require that since there's still a lot of binary C libraries our there that does not have unwind info compiled.

**Comment by lilinjn** [comment]
Thanks -- at the risk of belaboring the issue... Just in the way recent Julia's have chosen to layout `bitstype`'s consistently with the system ABI for great benefit to users, would it not be possible for Julia's EH implementation to be consistent with the C++ ABI, which in LLVM might actually simplify implementing exception handling (because it already had to provide convenient hooks to clang)?  I could imagine either GC logic  or yield(jl_task)  are the main blocking points to this approach but I'm not positive...

**Comment by lilinjn** [comment]
Or, else shouldn't `cfunction(cb,...)` implicitly wrap the cb in a try/catch to report to the user they should not send exceptions across the ffi boundary?

**Comment by yuyichao** [comment]
> would it not be possible for Julia's EH implementation to be consistent with the C++ ABI

We do generate correct unwind info and use them.

> I could imagine either GC logic or yield(jl_task) are the main blocking points to this approach but I'm not positive... 

No those are fine. As I mentioned, the only issue is external C code that does not obey the C++ EH ABI and we do a lot of ccalls

> Or, else shouldn't cfunction(cb,...) implicitly wrap the cb in a try/catch to report to the user they should not send exceptions across the ffi boundary?

Since we can't use zero-cost eh handling, that'll be way too expensive.

**Comment by lilinjn** [comment]
Ok -- I appreciate your feedback -- I gives me a few things that I need to clarify in my own mind (I don't quite understand why external C code needs to be aware of C++ conventions for "things to work", but I think this might be a good puzzle for me think about for a while).  Best, nehal

**Comment by yuyichao** [comment]
The issue is that the C++ eh ABI on all the supported platforms (.. ok I'm not sure about windows...) requires unwinding frame by frame until you hit a catch using information stored offband that is not needed for sequential execution. It'll fail as soon as it hits a frame that does not have unwind info. OTOH, sjlj (setjmp-longjmp) exception handling (what we use now) does not have that requirement although you need to catch the exception explicitly to run destructors.

The issue with the C frame then is that we support unwinding through C functions but many C functions do not support unwinding so if we use the C++ model we cannot unwind through `[julia1] -> [C1] -> [julia2]`. It's true that we can have a "best effort" unwinding where if you have `[julia1:catch] -> [C++1] -> [julia2:throw]` we can unwind through the c++1 frame to julia1 from julia2 and run the destructors in c++1 but we won't be able to do that if you have `[julia1:catch] -> [C++1] -> [julia2] -> [C1] -> [julia3:throw]` so it's not really a satisfying API. On possibility is to not allow unwinding through C frames, which is the approach C++ itself took. However, we currently relies on that (GMP is the case I can remember off the top of my head) and it'll take some research/effort to see if those can be done differently and fix those.

**Comment by lilinjn** [comment]
awesome explanation -- thanks!
