### ISSUE TITLE
run(``): BoundsError

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#19094]
``` julia
julia> run(``)
ERROR: BoundsError: attempt to access 0-element Array{String,1} at index [1]
 in #414 at .\process.jl:478 [inlined]
 in setup_stdio(::Base.##414#415{Cmd,Ptr{Void},Base.Process}, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:466
 in #spawn#413(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}, ::Bool, ::Bool) at .\process.jl:477
 in run(::Cmd) at .\process.jl:591
```

**Comment by vtjnash** [comment]
I'm not exactly sure what you expected this to do?

**Comment by StefanKarpinski** [comment]
I guess we could give a somewhat better error message.

**Comment by musm** [comment]
Why would this error? You aren't doing anything, I'd expect it to run silently and run nothing.

**Comment by yuyichao** [comment]
Because it should represent a single command, not zero or more than one.

It also seems like one could accidentally generate an empty command and it's better to raise an error in that case instead of silently ignoring causing problems in other cases by default. If you have a use case that wants this to not error, you can easily overwrite the default behavior by checking if the command is empty.

**Comment by musm** [comment]
Fair point, I think then Stefan has a good suggestion at possibly emitting a better error message, but feel free to close.

**Comment by ararslan** [comment]
FWIW I tried this out with master, 0.5, 0.4, and 0.3 to see what the past behavior has been. As it turns out, the behavior in 0.3 was, at least IMHO, the best: It errors saying that there are too few arguments to the command. I think that's much clearer than the behavior on 0.4+.

**Comment by StefanKarpinski** [comment]
We can leave it as up for grabs. Should be as simple as checking for emptiness of a command before trying to spawn it and raising a specific error.
