### ISSUE TITLE
Build libhttp-parser as a shared library

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#19301]
It was [mentioned](https://github.com/JuliaWeb/HttpParser.jl/pull/55#issuecomment-245843662) that `libgit2` builds/ships with `libhttp-parser` library, though it's not currently being built as a shared library. Doing so would further simplify the webstack installation process by allowing any system to use the julia-shipped library. Is this still possible/doable? Happy to help test/push things along if possible.

cc: @tkelman @wildart @staticfloat

**Comment by tkelman** [comment]
This was started here https://github.com/JuliaLang/julia/pull/17246/files#diff-323df73eb70bdc334b38faaa718ff69f but as a small part of a PR that we wound up implementing differently in the end. Separating just that part, building http-parser as its own separate shared library and making libgit2 dynamically link to it instead of building its vendored copy is certainly something we can do.

**Comment by quinnj** [comment]
Hmmm...I gave this a shot, but my "make"-fu skills are lacking. I tried to take a mix of what was in the previous PR as well as a seemingly updated model from `mbedtls.mk`, but couldn't quite get the incantations right. I might try again later, but I imagine this is probably much easier for someone else.

**Comment by staticfloat** [comment]
I've got a working (tested on OSX and Linux) branch [here](https://github.com/JuliaLang/julia/tree/sf/http_parser), which causes `libgit2` to link against our custom-built `libhttp_parser`, and still pass the `libgit2` tests.  Although I don't actually know if the `libgit2` tests exercise the part of `libgit2` that requires `libhttp_parser`.

**Comment by quinnj** [comment]
I don't have a particular use for this anymore since we now have a pure-Julia port of libhttp_parser.
