### ISSUE TITLE
Kronecker Products with SparseVector

### ISSUE THREAD

**Issue by lruthotto** [JuliaLang/julia#19426]
Dear all, 
seems like there is currently no efficient implementation of Kronecker products for sparse vectors. Try, e.g., 

```
v = sparse(randn(10))
A = speye(13);
vA  = kron(v,A)
println("issparse(vA)=$(issparse(vA))")

Av  = kron(A,v)
println("issparse(Av)=$(issparse(Av))")
```
Also, looking at the output or `@which` it seems like the input are converted to dense arrays, which works here but not for bigger problems.

Is anyone working on this already?

**Comment by lruthotto** [comment]
quick update: we have fixed this in our code by converting the sparse vector into a sparse matrix. See this PR: https://github.com/JuliaInv/jInv.jl/pull/26 

Shall we adopt this change in julia base?

**Comment by Pbellive** [comment]
This seems to be a regression in 0.5 caused by the introduction of sparse vectors. It causes problems for dense vectors too. `kron(::Vector,::SparseMatrixCSC)` dispatches to the following one-liner at base/sparse/linalg.jl line 785:
```
kron(A::VecOrMat, B::SparseMatrixCSC) = kron(sparse(A), B)
```
that method converts the dense array to a sparse matrix or vector. If the dense array is 2d, the call is then dispatched to the `kron` method for two `SparseMatrixCSC` arguments. However, if the dense array is 1d it gets converted to a `SparseVector` which doesn't match the signature for the sparse `kron` method. The PR referenced by @lruthotto above seems like an acceptable fix to me.

**Comment by jebej** [comment]
done with PR #23229

**Comment by ViralBShah** [comment]
@lruthotto Would you be ale to provide this PR in stdlib?

**Comment by lruthotto** [comment]
Hi @ViralBShah . Just filed a PR for this. Hope this is okay.

**Comment by ViralBShah** [comment]
Thank you!
