### ISSUE TITLE
SortedDict tab completion

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#19441]
tab completions don't work for `SortedDict`s.  i should've added tests for that with my Dict completion PR!

trying to debug this is difficult, because when run under Gallium, it all works fine.  can anyone point me in the right direction to fix this?

here's the transcript showing it's broken for `SortedDict`s but not `Dicts`:

```
julia> using DataStructures

julia> foo=Dict("asdf"=>1, "qwer"=>2)
Dict{String,Int64} with 2 entries:
  "asdf" => 1
  "qwer" => 2

julia> bar=SortedDict(foo)
DataStructures.SortedDict{String,Int64,Base.Order.ForwardOrdering} with 2 entries:
  "asdf" => 1
  "qwer" => 2

julia> foo["a  # then TAB ENTER
1

julia> bar["a  # then TAB
WARNING: Caught an exception in the keymap:
ERROR: type SDMKeyIteration has no field dict
ERROR: syntax: incomplete: invalid string syntax
```

immediately after the above i try calling `Base.REPLCompletionscompletions()` with the appropriate inputs.  fails again for the `SortedDict`.  yet it works when prepended with `@enter`.

```
julia> using Gallium, Base.REPLCompletions

julia> stringf="foo[\"a"
"foo[\"a"

julia> stringb="bar[\"a"
"bar[\"a"

julia> pos=length(stringf)
6

julia> completions(stringf,pos)
(Any["\"asdf\"]"],5:6,true)

julia> completions(stringb,pos)
ERROR: type SDMKeyIteration has no field dict
 in completions(::String, ::Int64) at ./REPLCompletions.jl:428
 in completions(::String, ::Int64) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?

julia> @enter completions(stringb,pos)
In REPLCompletions.jl:418
417       # First parse everything up to the current position
418       partial = string[1:pos]
419       inc_tag = Base.syntax_deprecation_warnings(false) do
420           Base.incomplete_tag(parse(partial, raise=false))

About to run: (Core.Box)()
1|debug > finish

julia> 

```

all line 428 does is iterate over the keys, like so:

```
for key in keys(identifier)
    rkey = repr(key)
    startswith(rkey,partial_key) && push!(matches,rkey)
end
```

no problem doing this manually:

```
julia> for key in keys(foo)
       info(key)
       end
INFO: asdf
INFO: qwer

julia> for key in keys(bar)
       info(key)
       end
INFO: asdf
INFO: qwer
```

any ideas?  i'm drawing a blank here.  thanks.

**Comment by nalimilan** [comment]
Looks like the incorrect method for `start` is called. Indeed, `@code_warntype completions(stringb,pos)` incorrectly contains this:
```julia
SSAValue(6) = (Base.REPLCompletions.keys)(identifier::Any)::Base.KeyIterator{T<:Associative}
#temp#@_44::Any = (Base.start)((Core.getfield)(SSAValue(6),:dict)::Associative{K,V})::Any
```

And the corresponding `start` method is:
```julia
start(v::Union{KeyIterator,ValueIterator}) = start(v.dict)
```

Inference appears to be confused by the `dict_identifier_key` function, which is inherently type unstable since it calls `getfield` based on the name of the object (passed as a string).

In the end, maybe that's just another occurrence of #265: when the method is first compiled, there is only one `start` method for `Associative` objects. The one for `SortedDict` is only added when loading DataStructures. And since `completions` does not dispatch on the input dict type, it's not recompiled for `SortedDict`. A way to fix this would be to move the dict-specific code to a separate method.
