### ISSUE TITLE
`one` for AbstractString

### ISSUE THREAD

**Issue by bdeonovic** [JuliaLang/julia#19536]
I noticed you can do something like

```julia
julia> prod(["*" for k in 1:3])
"***"
```

but you might get an error if you try

```julia
julia> prod(["*" for k in 1:0])
ERROR: MethodError: no method matching one(::Type{String})
```
Why was multiplication decided to be the operator on strings which appends them together? Wouldn't addition make more sense? 

What do you guys think of introducing 

```julia
one(String) = ""
zero(String) = ""
```

since "zero" is often defined as a + 0 = a, and "one" is defined as a * 1 = 1. This zero then makes sense for the way multiplication is defined for Strings

**Comment by stevengj** [comment]
Multiplication is the string concatenation operator because concatenation is not commutative, whereas `+` usually denotes a commutative operator in mathematics.  This has been discussed many times, e.g. in #11030.

Given that, defining `one(::AbstractString) = ""` makes sense, since this is the identity element for string concatenation, and `one` is defined as the multiplicative identity.

Defining `zero` (the additive identity), however, makes no sense here since we don't define `+` for strings.

**Comment by oscardssmith** [comment]
Isn't multiplication usually commutative also?

**Comment by KristofferC** [comment]
Often not.

**Comment by bdeonovic** [comment]
> whereas + usually denotes a commutative operator in mathematics.

Addition doesn't have to be commutative either. Multiplication can be commutative. This just seems confusing to me. 


After reading through some of https://github.com/JuliaLang/julia/issues/11030 I can see arguments for not having any kind of operator that does string concatenation, but I don't see why * is chosen over +. 

But if one of these is included in the language I think there should be an appropriate `zero` and `one`.

**Comment by KristofferC** [comment]
The discussion about using `*` or `+` has already been had. For future discussion to be productive let's focus on the part:

> What do you guys think of introducing
>
>one(String) = ""
>zero(String) = ""

Thanks.

**Comment by oxinabox** [comment]
our Strings should be the  [Free Monoid](https://en.wikipedia.org/wiki/Free_monoid) over all characters.
As a Free Monoid, they should have define their identity element -- the empty string.
And since we define our monoid operation using the `*` symbol, we that identity should be called `one`.
Thus `one(String) = ""` is a good idea, and also `one(::Type{String})`

Should it further `one{S<:AbstractString}(::Type{S}) = convert(S, "")` be defined?
[Like for Numbers](https://github.com/JuliaLang/julia/blob/6a1e339ac1ca24b0d00c1721a1833fb39106c559/base/number.jl#L64)
I'm less sure on that.


------
`zero(String)` on the other hand should be left undefined.
If we went and defined something using the `+` symbol,
 then defining `zero` to be that identity would be expected.
As we are not defining such a operation, it is left free for some user (/package) to do so.
As such when they do so, they should also be defining `zero(::String)` (not `Base`)

**Comment by StefanKarpinski** [comment]
Let's go ahead and do this since we're still using `*` for string concatenation. If we move away from that, we'll naturally also move away from this at the same time – this will hardly be the most painful part of that transition.

**Comment by bdeonovic** [comment]
What is the appropriate place in Base for such a definition?

**Comment by tkelman** [comment]
This seems like a pun and more often than not sending `one` a string in generic code will be a bug rather than appropriate to return an empty string as the desired behavior. Particularly because Strings occupy a strange place where they behave sometimes like collections and sometimes like scalars. `one` strikes me as a mostly numeric concept. If we were ever to deprecate `*` for string concatenation as has been floated, this would need to be deprecated alongside it.

**Comment by StefanKarpinski** [comment]
> If we were ever to deprecate `*` for string concatenation as has been floated, this would need to be deprecated alongside it.

Right, that's my point. This makes sense as long as we're using `*` and if we deprecate that, then deprecating `one` for `String` will hardly be a big deal.

**Comment by nalimilan** [comment]
I agree this makes it even clearer that we should move away from `*` for string concatenation. But for now better be consistent and implement `one`.

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/19548

**Comment by alanedelman** [comment]
I actually had a use case just today for "one" being ""
I wanted to * reduce an array of strings, and was disappointed it would not work.

**Comment by bdeonovic** [comment]
The PR has been merged into master so if you check out master branch it should work out for you. Otherwise you'll have to wait for next release.

**Comment by KristofferC** [comment]
Writing them one by one to an IOBuffer should be much more efficient I think (although perhaps less convenient).

**Comment by stevengj** [comment]
You can just call `join` to efficiently concatenate an array of strings.
```jl
julia> a = [randstring(10) for i = 1:1000];

julia> using BenchmarkTools

julia> @benchmark join($a)
BenchmarkTools.Trial: 
  memory estimate:  13.13 kb
  allocs estimate:  16
  --------------
  minimum time:     54.150 μs (0.00% GC)
  median time:      56.809 μs (0.00% GC)
  mean time:        57.813 μs (0.28% GC)
  maximum time:     1.708 ms (94.77% GC)
  --------------
  samples:          10000
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%

julia> @benchmark prod($a)
BenchmarkTools.Trial: 
  memory estimate:  4.87 mb
  allocs estimate:  999
  --------------
  minimum time:     620.688 μs (0.00% GC)
  median time:      1.592 ms (0.00% GC)
  mean time:        1.855 ms (29.36% GC)
  maximum time:     6.105 ms (82.00% GC)
  --------------
  samples:          2684
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```
