### ISSUE TITLE
oddball corner case for parameterized typealias in new type system

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#20100]
Maybe this behavior is intentional?  Are there any other oddball corner cases?  This is from the latest master.

```julia
julia> typealias BB{T} T
Any

julia> isa(5, BB{Int})
ERROR: TypeError: Type{...} expression: expected UnionAll, got Type{Any}

julia> isa(5, BB)
true
```

**Comment by JeffBezanson** [comment]
Yes, this is intentional. It's equivalent to

```
const BB = T where T<:Any
```

and `T where T<:Any` is normalized to `Any`. This is perhaps another reason to deprecate the `typealias` keyword.

**Comment by StephenVavasis** [comment]
In this case, shouldn't `typeof(Any)==UnionAll` and shouldn't `Any{Int}==Int`?

**Comment by JeffBezanson** [comment]
In general, types can be equal even if they have different representations. For example `Union{Int, Int}` equals `Int` (we also do this normalization). `T where T<:Int` also equals `Int`.

Most contexts that use types use this notion of type equality. However, type application `A{B}` depends on the structure of `A`, not its denoted type. `(T where T) == Any`, but you can apply one and not the other (except we don't make it easy to actually construct `T where T`). Similarly, `Int` has a `size` field giving a number of bytes, but `Union{Int,Int}` would not have a size field since it's a `Union` and not a `DataType`.

**Comment by StephenVavasis** [comment]
Jeff,

Thanks very much for the explanation.  The new type system makes several aspects of Julia more straightforward, especially a typealias in which the type parameter is nested two deep.  I'm going to close this issue since there is no bug or action item.
