### ISSUE TITLE
Build error on Linux, anaconda and libgit2 in error output

### ISSUE THREAD

**Issue by nevencaplar** [JuliaLang/julia#20197]
Hi all,

I seem to be having problems with the installation of Julia. After cloning the JuliaLang and checking that I have all of the dependencies, I run "make" and get erros. The output is given here: https://gist.github.com/nevencaplar/bf8006fbdd4015f7ba4a62d2121c5d5e

I wonder if there is conflict with my anaconda installation? Note that I do not have acess to sudo on this machine so the anaconda is installed in separate directory; I wonder if the different versions of python are causing problems here? The system is Ubuntu 16.04.

Any help would be highly appreciated!

**Comment by ararslan** [comment]
What's in your Make.user, if anything? Also, what do you get for `which gcc` and `gcc --version`? I don't know much about Anaconda but it looks like it's using Anaconda's math.h for some reason.

**Comment by nevencaplar** [comment]
Thanks for your answer.  Required information is below.

1. There is no Make.user file in julia directory

2.` which gcc` outputs 
`/usr/bin/gcc`

3. `gcc --version` gives
 `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

**Comment by tkelman** [comment]
try `make -C deps distclean-libgit2 && make VERBOSE=1` and see if you get the full compiler invocation line that errored

**Comment by nevencaplar** [comment]
I did as suggested. The output is here: https://gist.github.com/nevencaplar/8d20ed1d5105b8b5d83498d1065fc1f7

At least to me, everything seems to be running smoothly before reaching pretty much the same breaking point with the same output.

**Comment by tkelman** [comment]
Right. That wasn't intended to fix anything, just tell cmake to output the entire compiler invocation command that failed:
`/usr/bin/gcc -m64 -DCLAR_FIXTURE_PATH=\"/export/data1/caplarn/Documents/Variability/Farr/julia/deps/srccache/libgit2-75db289a041b1f1084768244e167b953ac7eeaa5/tests/resources/\" -DCLAR_RESOURCES=\"\" -DCLAR_TMPDIR=\"libgit2_tests\" -DGIT_ARCH_64 -DGIT_CURL -DGIT_MBEDTLS -DGIT_SSH -DGIT_SSH_MEMORY_CREDENTIALS -DGIT_THREADS -DGIT_USE_NSEC -DGIT_USE_STAT_MTIM -DHAVE_FUTIMENS -DHAVE_QSORT_R -DMBEDTLS_SHA1 -D_FILE_OFFSET_BITS=64 -I/export/data1/caplarn/Documents/Variability/Farr/julia/deps/srccache/libgit2-75db289a041b1f1084768244e167b953ac7eeaa5/src -I/export/data1/caplarn/Documents/Variability/Farr/julia/deps/srccache/libgit2-75db289a041b1f1084768244e167b953ac7eeaa5/include -I/export/data1/caplarn/Documents/Variability/Farr/julia/usr/include -I/export/data1/caplarn/Documents/Variability/Farr/julia/deps/srccache/libgit2-75db289a041b1f1084768244e167b953ac7eeaa5/deps/http-parser -I/export/data1/caplarn/Resources/anaconda/include -I/export/data1/caplarn/Documents/Variability/Farr/julia/deps/srccache/libgit2-75db289a041b1f1084768244e167b953ac7eeaa5/tests -D_GNU_SOURCE -Wall -Wextra -fvisibility=hidden -fPIC -Wno-missing-field-initializers -Wstrict-aliasing=2 -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-function -O3 -DNDEBUG -o CMakeFiles/libgit2_clar.dir/tests/clar.c.o -c /export/data1/caplarn/Documents/Variability/Farr/julia/deps/srccache/libgit2-75db289a041b1f1084768244e167b953ac7eeaa5/tests/clar.c`

So your problem is the `-I/export/data1/caplarn/Resources/anaconda/include` that's ending up in the compiler flags, and the fact that anaconda's copy of `math.h` seems broken. It looks like libgit2 is picking up zlib from anaconda, which we probably shouldn't be letting it do. Try replacing `deps/patches/libgit2-ssh.patch` with https://gist.github.com/c573dad5f016f0b7f5c52eaec850bb43, then re-doing `make -C deps distclean-libgit2 && make -j4`, see if that gets further.

**Comment by nevencaplar** [comment]
Ok, after replacing the `deps/patches/libgit2-ssh.patch` with https://gist.github.com/c573dad5f016f0b7f5c52eaec850bb43 and then re-doing `make -C deps distclean-libgit2 && make -j4` I get different output: https://gist.github.com/nevencaplar/5f39b203800f9b4905e6fe57ec989d04

I then re-run the command again and get https://gist.github.com/nevencaplar/2db5882f2b74c865f5d88527892739f9.
After couple runs the error message stabilizes and is always https://gist.github.com/nevencaplar/37be2158fa9720b60fec02fe7c305d41.

As you can imagine I am quite confused and not sure what is happening.

**Comment by tkelman** [comment]
Does `file deps/patches/libgit2-ssh.patch` say "unified diff output"? If not, you probably saved an html file there which `patch` doesn't like. Try the raw content: https://gist.githubusercontent.com/anonymous/c573dad5f016f0b7f5c52eaec850bb43/raw/f559036d2a5aae1e55020fbfe608b13d5323c2bb/-

**Comment by nevencaplar** [comment]
Hi. Ok, in the file that you sent before I removed the header part (I am not very smart....). Anyhow with the new version  and copying the whole input, it is still complaning about finding a file to patch...

https://gist.github.com/nevencaplar/94dcae5a04fb321e9518e575c9ec2496

**Comment by tkelman** [comment]
oops sorry, I missed that patch is `-p0` unlike most of the others. I think if you delete the `a/` and the `b/` at the top of the file it should be happier.

**Comment by nevencaplar** [comment]
Hm, same error it seems. So I delete the first 7 lines (so deps/patches/libgit2-ssh.patch starts with # Optional external dependency: zlib) and get basically the same: https://gist.github.com/nevencaplar/a71c9b36481a89779d8af8d3039b18f0

**Comment by tkelman** [comment]
Sorry, this stuff is a bit confusing and non-intuitive if you don't spend all day doing it. My bad for not testing things out before sending them across for you to try. Let's do this:
```
git checkout -- deps/patches/libgit2-ssh.patch
git remote add tkelman https://github.com/tkelman/julia
git fetch tkelman
git checkout tkelman/tk/libgit2-nozlib
make -C deps distclean-libgit2
make test-libgit2 test-libgit2-online test-pkg
```

**Comment by nevencaplar** [comment]
I executed the commands and sucess! Test summary gives the pass score of 107 (out of 107). Just to be sure I also ran `make testall` and get pass score of 20828924 (out of 20829541). Thanks a lot!

**Comment by tkelman** [comment]
Good. So that confirms that we should force libgit2 to use a known-good copy of zlib instead of picking up whatever it finds on the user system. I'm not sure if there's a cleaner way of doing that than patching out the find_package. We've been disabling zlib support in several other deps libraries for this same reason, but since libgit2 vendors its own copy of the source anyway it would probably be worth just adding zlib as a new dependency to our build system that we build from source like all the others. At one point it was in deps/Makefile but not used on most systems iirc.

**Comment by KristofferC** [comment]
I think this can be closed in favor of https://github.com/JuliaLang/julia/issues/25295.
