### ISSUE TITLE
Row major reshape

### ISSUE THREAD

**Issue by kindlychung** [JuliaLang/julia#20311]
Ideally one should be able to give some params to `reshape` to achieve the following:

```julia
A = [1 2 3; 4 5 6]
B = transpose(reshape(transpose(A), 2, 3))
```

To generalize to multidimensional case, one should be able to reshape in any axis.

**Comment by timholy** [comment]
One of the contracts that our current `reshape` satisfies is that it *always* creates a *view* of the original memory, meaning that no copy is formed:
```julia
julia> A = [1 2 3; 4 5 6]
2×3 Array{Int64,2}:
 1  2  3
 4  5  6

julia> B = reshape(A, 3, 2)
3×2 Array{Int64,2}:
 1  5
 4  3
 2  6

julia> B[2,1] = -1
-1

julia> A
2×3 Array{Int64,2}:
  1  2  3
 -1  5  6
```
To satisfy that contract and provide the functionality you want in a type-stable fashion, you'd need an `AbstractArray` type for which the storage order is effectively checked at runtime. That's not a crazy thing to want, but if built-in to general arrays it would surely cause a performance hit for far too many operations. See the following blog post: http://julialang.org/blog/2013/09/fast-numeric or any reference on "cache-friendly" operations.

To me this sounds like functionality for a package; you can find examples of interesting array types at [JuliaArrays](https://github.com/JuliaArrays). As you hopefully appreciate, in Julia there is scarcely any difference between having something "built-in" to the language and having it provided in a package. I'm going to close this as non-actionable within base Julia, but if you decide to develop such a package you may find that you have many grateful users. The Base class [`PermutedDimsArray`](https://github.com/JuliaLang/julia/blob/65afe479cfd5afd6c782aafc2a18dac5a55cb4de/base/permuteddimsarray.jl) might be an excellent model for you to follow; you'd just want to store the permutation as field in the array rather than as a type parameter.
