### ISSUE TITLE
joinpath() doesn't add path separator between drive and directory 

### ISSUE THREAD

**Issue by GregPlowman** [JuliaLang/julia#20375]
On Windows, Julia v0.5.0
```
julia> joinpath("C:", "Temp")
"C:Temp"
```

**Comment by vtjnash** [comment]
That's the correct path. It's a relative path from `C:` to `Temp` via the current working directory of `C:` (which may be accessible as `ENV["=C"]`)

**Comment by nalimilan** [comment]
So what's the correct way of doing this? We should add an example to the docstring for Windows.

**Comment by musm** [comment]
There's a note explaining what
```
joinpath("C:", "Temp")
```
actually represents  in the docstring for `joinpath`

**Comment by StefanKarpinski** [comment]
> So what's the correct way of doing this?

Turning two relative paths into an absolute path just isn't something `joinpath` does. This is like asking why `joinpath("foo", "bar")` doesn't produce the absolute path `/foo/bar` and since it doesn't, how does one get `joinpath` to produce an absolute path. The answer is: you don't, you get an absolute some other way.
