### ISSUE TITLE
√.(1:5) throws ERROR: syntax: invalid identifier name "."

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#20425]
The following seems like an unnecessary restriction, though you can avoid it using `(√).(1:5)`:

```julia
julia> versioninfo()
Julia Version 0.6.0-dev.2541
Commit 2779279 (2017-02-03 01:02 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.3.0)
  CPU: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libgfortblas
  LAPACK: liblapack
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)

julia> √.(1:5)
ERROR: syntax: invalid identifier name "."
```

**Comment by StefanKarpinski** [comment]
@dlfivefifty – thanks for banging on 0.6!

**Comment by yuyichao** [comment]
The syntax for unary operator is

```julia
julia> .√(1:5)
5-element Array{Float64,1}:
 1.0    
 1.41421
 1.73205
 2.0    
 2.23607
```

**Comment by dlfivefifty** [comment]
Ah OK, thanks!

**Comment by dlfivefifty** [comment]
Though that doesn't work in 0.5.  Should I just use `(√).(1:5)` while 0.5 is supported?

**Comment by StefanKarpinski** [comment]
Although there is a legitimate issue here – this could be parsed as a dotted function call to `√ `, applied to the argument `1:5`. It doesn't, for the same reason we parse `-(x)` as the unary `-` operator applied to `x` rather than the `-` function called on `x`. Yes, this is a subtle point, but it could be changed. I don't think it's been an issue until now since for the undotted unary operators, nobody seems to care. In this case, we could just allow this syntax.

**Comment by yuyichao** [comment]
Unary operator support is merged today and generic binary operator is also only on master I believe. So yes, if you need 0.5- support you need to use the function call syntax for unary operator and possibly combine it with `@compat`.
