### ISSUE TITLE
Have a sanctioned way to modify the REPL's IOContext

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#20509]
I would like a way to modify the `IOContext` of the REPL. Right now that's a little hard because everything is buried deep in the REPL code.

Example:
```
julia> immutable Foo
       end

julia> show(io::IO, x::Foo) = print(io, get(io, :debug, false) ? "Lots of debug info" : "Foo")
show (generic function with 1 method)

julia> Foo
Foo
```

I'd like some global setting that allows me to put `debug=true` in the REPL IOContext and print "Lots of debug info" at the REPL.

**Comment by vtjnash** [comment]
+1. I suspect we just need to remove the type restrictions from the fields of `TTYTerminal`.

**Comment by KristofferC** [comment]
What's the advantage over using a global or using a proper logging tool?

**Comment by TotalVerb** [comment]
👍 for IO context configurability in REPL. Configuring the REPL's IOContext is better than using a global because it avoids interfering with any user code; it just affects how things are displayed. I'm not sure what logging has to do with this; IOContext will only affect how things are printed and has nothing to do with logging. I believe what Keno means by "debug info" are object internals.
