### ISSUE TITLE
Error in FloatRange deprecation

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#20506]
On master, I get
```julia
julia> FloatRange(10.0,1.0,11.0,10.0)
WARNING: FloatRange{T}(start::T, step, len, den) is deprecated, use Base.floatrange(T, start, step, len, den) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:62
 [2] FloatRange(::Float64, ::Float64, ::Float64, ::Float64) at ./deprecated.jl:50
 [3] eval(::Module, ::Any) at ./boot.jl:236
 [4] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 [5] macro expansion at ./REPL.jl:97 [inlined]
 [6] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
while loading no file, in expression starting on line 0
ERROR: MethodError: no method matching floatrange(::Type{Float64}, ::Float64, ::Float64, ::Float64, ::Float64)
Closest candidates are:
  floatrange(::AbstractFloat, ::AbstractFloat, ::Real, ::AbstractFloat) at twiceprecision.jl:108
  floatrange{T}(::Type{T}, ::Integer, ::Integer, ::Integer, ::Integer) at twiceprecision.jl:94
Stacktrace:
 [1] FloatRange(::Float64, ::Float64, ::Float64, ::Float64) at ./deprecated.jl:52
```
This broke `StatsBase`.

cc: @timholy

**Comment by timholy** [comment]
Yes, thanks for the independent issue.

I think the specific issue here shouldn't be too hard: just define a method for `floatrange` that takes `Real` inputs.

With regards to the idea of a binding deprecation, I think it's much riskier. Here's what I'm struggling with. Both `FloatRange` and `StepRangeLen` are objects that have 4 real-valued fields. The problem is that the interpretation of those fields is very different. Here's an illustration of the problem, using an imagined "outdated" type `Bar`,
```julia
immutable Bar
    start::Float64
    stop::Float64
end
```
and a `Foo` type that replaces it:
```julia
module Test2

immutable Foo
    start::Float64
    len::Int
end

Base.@deprecate_binding Bar Foo
Bar(x, y::AbstractFloat) = Foo(x, floor(Int, y-x))  # without the ::AbstractFloat, this never gets called

end

module Ex2

using Test2

isbar(x::Bar) = true
isbar(x) = false

x = Bar(1.2,3.1)
@show x
@show isbar(x)

y = Bar(1.2, 3)
@show y
@show isbar(y)

end
```
Omitting the deprecation warnings, this is what you get:
```julia
julia> include("testing.jl")
x = Test2.Foo(1.2, 1)
isbar(x) = true
y = Test2.Foo(1.2, 3)
isbar(y) = true
```
So the "conversion function" only runs for certain kinds of inputs.

**Comment by timholy** [comment]
Of course, I acknowledge that the other problem is also bad: any package code that has specialized implementations for `FloatRange` inputs will no longer run. Assuming the existence of a fallback `AbstractArray/AbstractVector` implementation, there won't be an error, but certain things may behave rather differently than they used to (e.g., iterate over all elements of the Range rather than having some efficient shortcut).

The reason I designed it this was is that I felt that this was the lesser of two evils. In particular, specialized `FloatRange` methods often probably dig into the internal implementation of `FloatRange`, so having a binding deprecation for the type would have ended up triggering an error, too.

I probably should have called more attention to the issues that went into my thinking in designing this deprecation plan.

**Comment by tkelman** [comment]
The problem is that this type is deprecated and will be deleted, but package authors aren't going to get warnings from their `foo(::FloatRange)` method definitions. It'll just break hard when we remove the deprecations.

**Comment by timholy** [comment]
Agreed that's a problem. Given the above, what's the solution?

**Comment by tkelman** [comment]
can we use the binding deprecation mechanism to trigger a warning but instead of suggesting a short replacement if it's not always a trivial substitution, link to a paragraph somewhere explaining how the new type should be used differently?

**Comment by timholy** [comment]
I can't figure a way. I dug into the deprecation machinery a bit more. This was the trickiest thing I could come up with, and it doesn't work:
```julia
module Test3

export Foo, Bar

immutable Foo
    x::Float64
    len::Int
end

immutable BarOld
    x::Float64
    y::Float64
    function BarOld(x, y)
        Base.depwarn("Bar is deprecated, use Foo instead", :Bar)
        Foo(x, floor(Int, y-x)+1)
    end
end

const Bar = BarOld
Base.deprecate(:Bar)

end

module Ex

using Test3

isbar(x::Bar) = true
isbar(x) = false

x = Bar(1.2,3.1)
@show x
@show isbar(x)

y = Bar(1.2, 3)
@show y
@show isbar(y)

end
```
I think I understand better now why deprecation isn't done through the parser (two types can have the same name in different modules), but this is a case where I don't currently see a way forward without support from the parser.

**Comment by timholy** [comment]
Wait, maybe there is a way: what if we duplicate *all* the old `FloatRange` code in `deprecated.jl` but place a `depwarn` in the inner constructor.

**Comment by tkelman** [comment]
The other alternative I was going to suggest would be opening an issue in every package that uses FloatRange with a heads up that it no longer exists and will be going away, but your suggestion sounds reasonable as well. We could deprecate_binding FloatRange FloatRangeDeprecated for good measure.
