### ISSUE TITLE
conv corner case

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/julia#20539]
`conv( randn(5), randn(0) )`, say
should be, i'd think, should be a vector of length 0
right now it's an error

`conv(randn(0), randn(0))` is trickier, but a vector length 0 is not unreasonable

**Comment by StefanKarpinski** [comment]
The docs for `conv` could use some improvement:

> Convolution of two vectors. Uses FFT algorithm.

Without an actual definition of what `conv` computes, it's hard to say what the corner cases should do.

**Comment by felixrehren** [comment]
Cf. https://github.com/JuliaLang/julia/pull/20761 for a doc proposal.

From the point of view of `conv` giving the coefficients of a product of polynomials, it's hard to say what polynomial is represented by `Array{T,1}()`. To me, `conv(u, []) = []` seems like an OK convention, but not a necessary one.

**Comment by StefanKarpinski** [comment]
Wouldn't `[]` be the zero polynomial?

**Comment by felixrehren** [comment]
That's what @alanedelman proposed. Since `[0,...,0], [0,0], [0]` all have the same behaviour wrt. `conv`, one could include `[]` in that family of representations of the zero polynomial. This doesn't seem to drop out of the current implementation of the algorithm?, but require extra logic. The status quo is

> julia> conv(Float64[1,2,3], Float64[])
ERROR: invalid Array dimensions

**Comment by StefanKarpinski** [comment]
Sure, makes sense.

**Comment by KristofferC** [comment]
Moved to https://github.com/JuliaDSP/DSP.jl/issues/168
