### ISSUE TITLE
`@sprintf` not rounding to nearest

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#20753]
`@sprintf`'s `%.<num>f` functionality seems to be rounding numbers exactly halfway between two representable decimals toward infinity. This is inconsistent with `round` and other functions which round to the even of two equally acceptable options.

```julia
julia> @sprintf "%.0f" 0.5
"1"

julia> round(Int, 0.5)
0
```

Furthermore, the GNU libc guarantees round to nearest for `printf` and `sprintf`, so it is unexpected that `@printf` and `@sprintf` round toward infinity.

**Comment by StefanKarpinski** [comment]
It does seem that `C` rounds to even here:

```c
#include <stdio.h>

int main()
{
    printf("%.0f\n", 0.5);
    printf("%.0f\n", 1.5);
    printf("%.0f\n", 2.5);
    printf("%.0f\n", 3.5);
    return 0;
}
```

Produces:

```
0
2
2
4
```

**Comment by tkelman** [comment]
excitingly platform-dependent though... (plain `gcc` is cygwin's here)
```
$ gcc -o testprintf testprintf.c && ./testprintf
0
2
2
4

$ i686-w64-mingw32-gcc -o testprintf testprintf.c && ./testprintf
1
2
3
4

$ x86_64-w64-mingw32-gcc -o testprintf testprintf.c && ./testprintf
1
2
3
4
```

**Comment by JeffBezanson** [comment]
Rounding to even integers always seemed weird to me. Like some sort of superstition against odd numbers :)

**Comment by StefanKarpinski** [comment]
I'd argue that for printing it's not really what you want – you want the "math textbook" behavior, which is what our printf does. The round-to-even behavior was chosen for floating-point arithmetic because it avoids certain examples of numerical instability, iirc – that argument doesn't really apply here. If some C compilers do the same as what we're doing, then I think we're in the clear.

**Comment by TotalVerb** [comment]
Very well then, but this should be documented. I found it surprising and unexpected.
