### ISSUE TITLE
Symbolic computation

### ISSUE THREAD

**Issue by Octopoda7** [JuliaLang/julia#20754]
Hello,
I am sad that Julia doesn't have symbolic computation capabilities. I know there are external packages that do provide it, but I want to have symbolic computation in the base language (the base distribution).

Thanks.

**Comment by vchuravy** [comment]
These kinds of open questions are best asked on [discourse](https://discourse.julialang.org/).
Also note that there is seldom the need for a feature to be part of Base (which aims to be a minimal set of required functionality) since all Julia code is equal and code in packages is as fast as code in Base. Additionally it is often beneficial for code to be in a package since that allows it to evolve faster and more independent to the release cycle of Julia.
