### ISSUE TITLE
function types

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#210]
Then just settle for map returning a type of the map function as the output array type.

**Comment by JeffBezanson** [comment]
Latest discussion in #10269

**Comment by vtjnash** [comment]
@JeffBezanson i think you get the honor of closing this one now

**Comment by StefanKarpinski** [comment]
@vtjnash – I think you may be misunderstanding the intended meaning of this issue. Yes, functions are types now in the Julia sense, but not in the sense that static languages generally mean it. I think the conclusion is that we cannot do this and this issue is superseded by a combination of #1090 and #7258 and `map` behaving in the same inference-independent manner as comprehensions.

**Comment by sighoya** [comment]
I'am a little bit confused about:
[210](https://github.com/JuliaLang/julia/issues/210)
[10269](https://github.com/JuliaLang/julia/pull/10269)
[1090](https://github.com/JuliaLang/julia/issues/1090)

What is the current state of typed functions?
If we had two functions

`
f(x::Int64)::Int64
`

`
g(x::T)::S where {S,T}
`
do we get by typeof(f), and (g) only the type "Function" or a more specific result like

`
typeof(f) == Function{(Int64,),Int64}
`
`
typeof(g) == Function{(T,),S}
`

The latter would be better as we can filter out functions that we do not want. 
What is the problem with the map function, do we want it to be typesafe?
A possible solution with extended syntax would be

``
map(f::Function{Tuple{S..},R},x::Tuple{T...}..)::Tuple{R...} where {R,S<:DataType, T}=...
``
I will  explain it:
x::T... means vararg x with the same parametric type T
x::T.. means vararg x with different parametric types ( x1::T1, x2::T2,x3::T3,...)
x::Tuple{T...}.. means each Tuple xi has elements of one type, but the type from tuple to tuple in the vararg list can vary ( x1::Tuple{T1...},x2::Tuple{T2...},...)
x::Tuple{S..} means x is tuple of heterogenous type (x=Tuple{T1,T2,T3,T4,...})
S<:DataType ensures that S is a higher order generic at least of rank 2, why?
Because a function f::Function{(Int64,Float64,...),R} may be applied to vararg list of tuples where the second tuple may not include elems of Type Float64. Therefore, it is better only to take polymorphic functions into the map function.
The Tuple type could of course be exchanged by a more general collection type.
My assumption of a typed map function is that each xi in x contains only members of the same type, but the type from the elems in xi-1 to xi can vary.
If also the type in each xi can vary, then the use of the standard map in Base would be more appropriate.

**Comment by yuyichao** [comment]
`do we get by typeof(f), and (g) only the type "Function" or a more specific result like`

Neither, they have their own type but they don't and can't (as it doesn't make any sense) to give you argument and return types.

**Comment by sighoya** [comment]
Does it have to do something with methods versus function, where a method has only one argument type tuple and one return type and functions multiple argument type tuples and return types?

**Comment by JeffBezanson** [comment]
That's part of the issue, yes, but it's mostly that the language is dynamically typed so functions do not have meaningful return types (other than the types of values they actually return at run time).

**Comment by sighoya** [comment]
Disregarding the multiple method problem, mabye, a special function type could be created for functions in which the types are hardcoded by the user? For instance, something like StaticFunction{Tuple{Int64,Float64},Int64}

**Comment by KristofferC** [comment]
Sounds like https://github.com/yuyichao/FunctionWrappers.jl.

**Comment by oscardssmith** [comment]
Is this still a thing? It seems closable as moot.

**Comment by oscardssmith** [comment]
Closing since we aren't going to change this.
