### ISSUE TITLE
Call for feature: JuliaPro on Fedora

### ISSUE THREAD

**Issue by bioinformatist** [JuliaLang/julia#21032]
Dear,

I'm an user of Fedora distribution and newbee to Julia.
Currently. JuliaPro can only be installed on Ubuntu/CentOS. Can you add supporting for Fedora in the future?

Thanks.

**Comment by amitmurthy** [comment]
Not sure if this is the right place for JuliaPro feature requests. Maybe contact info@juliacomputing.com ?

**Comment by ViralBShah** [comment]
Cc @nalimilan

**Comment by ViralBShah** [comment]
Oh this is about JuliaPro - yes, this is not the right place for that.

**Comment by leocomerci** [comment]
Although it might not be the correct place to ask that question, at least you could provide a link to that information anyways.

That guy is not the only one who wants to install Juliapro on Fedora, and that bureaucracyful answer only makes me think of stackoverflow. 

You could have that information put into a wiki or something, instead of having to issue an email and all that...

**Comment by vchuravy** [comment]
Hello leocomerci, GitHub is only intended as a bug tracker for Julia and JuliaPro is a different piece of software and in general we encourage question like this to be asked on discourse https://discourse.julialang.org/c/tools/juliapro
