### ISSUE TITLE
@async calls weird output printing

### ISSUE THREAD

**Issue by felipenoris** [JuliaLang/julia#21348]
Running 0.6 master:

```julia
julia> for i in 1:5
           @async info("$i")
       end
INFO: INFO: INFO: INFO: INFO: 
1
2
3
4
5
```

Running 0.5:

```julia
julia> for i in 1:5
                  @async info("$i")
              end
INFO: 1
INFO: 2
INFO: 3
INFO: 4
INFO: 5
```

**Comment by KristofferC** [comment]
Why do you consider this weird?

**Comment by felipenoris** [comment]
The debug message type (INFO) should be printed along with the debug message.

**Comment by KristofferC** [comment]
But you have 5 asynchronous tasks printing as they wish? Do you expect synchronization from the `@async` macro?

**Comment by felipenoris** [comment]
I would expect this output, without split messages:

```julia
julia> VERSION
v"0.6.0-pre.beta.91"

julia> for i in 1:5
           @async println("INFO: done $i")
       end
INFO: done 1

julia> 
INFO: done 3
INFO: done 4
INFO: done 5
```

The example above shows another weird behavior: `done 2` doesn't get printed.

**Comment by StefanKarpinski** [comment]
Since the `info` macro is likely going to be used like this, we may as well make sure that tasks don't switch in the middle of printing a message.

**Comment by amitmurthy** [comment]
One solution would be to lock the IO object during printing like `print` does - https://github.com/JuliaLang/julia/blob/d7620388ac012492b0daa7ccb19b3ca0edf356c3/base/strings/io.jl#L26-L34

Another to write into an IOBuffer and print buffer contents in a single call.

I am guessing in 0.5, `info` was implemented with a single `print` call.

**Comment by StefanKarpinski** [comment]
I guess the question is what the performance implications of locking the IO object are. If there aren't any dire performance issues with locking it, then we should probably go with that since it means that INFO messages will get priority in some sense (i.e. they get fully printed before any other output can go to the IO stream).

**Comment by amitmurthy** [comment]
> i.e. they get fully printed before any other output can go to the IO stream

Not really, since any other writes to the IO object will not synchronize on the lock. AFAICT only `print` locks the IO object, `show` and `write` do not. Using `lock` here will only synchronize between concurrent multiple `info` as well as multiple `print` calls to the same IO object.

I haven't benchmarked, but I believe writing to a temporary IOBuffer and a single libuv write will be faster than making multiple libuv write calls (plus any locking overhead which should not be much). 

There is a FAQ entry for this - https://docs.julialang.org/en/latest/manual/faq.html#Asynchronous-IO-and-concurrent-synchronous-writes-1 .

Using an IOBuffer we can be sure that `show` output is not interleaved with `info` output. I assume that the actual bytes written to the stream is not dependent on the stream type, i.e., the same bytes are written whether the write is to a TTY or a IOBuffer.
