### ISSUE TITLE
Creation of usr/include/julia on release-0.5 branch

### ISSUE THREAD

**Issue by barche** [JuliaLang/julia#21371]
It seems the `usr/include/julia` directory is not created in an out-of-source build in the release-0.5 branch. It's fine on 0.6, but comparing both Makefiles it seems the 0.6 one is completely restructured, so I'm not sure if this would be easy/worthwhile to backport.

This problem leads to difficulty finding julia.h from CxxWrap.jl: https://github.com/JuliaInterop/CxxWrap.jl/issues/37

**Comment by tkelman** [comment]
Out-of-tree builds are a bit experimental and not as thoroughly tested. Unless you can bisect and identify otherwise, I suspect this was likely fixed as part of a larger rewrite that isn't going to be backported. But if there's a small, targeted fix for just this issue in the release-0.5 makefiles, we can consider it.

**Comment by KristofferC** [comment]
Doesn't seem like anything left to do here.
