### ISSUE TITLE
Likely Pkg resolver issue reports spurious conflict

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#21430]
Ref https://github.com/JuliaLang/METADATA.jl/pull/8838

**Comment by ChrisRackauckas** [comment]
Should this be checked with https://github.com/JuliaLang/julia/pull/21485 @carlobaldassi ?

**Comment by carlobaldassi** [comment]
I have found this:

1) "CoordinateTransformation" `v"0.2.0"` can not be installed because it depends on "Rotations" either `v"0.1.0"` or `v"0.2.0"`, which have julia version upper bounds at `v"0.5"` and `v"0.6-pre.alpha"`, respectively. Since now julia is at `v"0.6-pre.beta"`, none of these are allowed. Solution would be to cap julia version in "CoordinateTransformation" `v"0.2.0"` to `v"0.6-pre.alpha"`.

2) "Geodesy" v"0.2.0" can not be installed for the same reason.

3) "EEG" `v"0.0.3"` doesn't have any problem with #21485.

So at least the first 2 are genuine METADATA issues (cc @tkelman).

**Comment by tkelman** [comment]
Would think the transitive bounds would be implicit and not cause a sanity check failure?

**Comment by tkelman** [comment]
Or if they should fail, they should have failed a while ago rather than in response to tagging a different package?

**Comment by tkelman** [comment]
Oh right, and 0.6 is still allowed to fail at the moment. Probably worth fixing and changing that now.

**Comment by tkelman** [comment]
fixed with resolver improvements and metadata bound consistency adjustments
