### ISSUE TITLE
Windows binaries missing LLVM-X.Y.lib for linking

### ISSUE THREAD

**Issue by SylvainCorlay** [JuliaLang/julia#21520]
The binaries made available on https://julialang.org/downloads/ for windows don't include the necessary `LLVM-3.7.lib`, the companion file to `LLVM-3.7.dll` necessary for linking.

This prevents people from linking with `libjulia` and using the Julia interpreter as a library in a C++ application.

**Comment by SylvainCorlay** [comment]
Cross-referencing https://discourse.julialang.org/t/embedding-windows-binaries/3352

**Comment by musm** [comment]
Is this still relevant? cc @staticfloat

**Comment by staticfloat** [comment]
We do indeed still not ship the LLVM static libraries, and I don't think we ever will, because they are just too large.  They would inflate the download size by a large amount.

My suggestion to users that want to link against the LLVM that Julia uses is to use dynamic linking, not static linking.

**Comment by vtjnash** [comment]
`.lib` (aka `.dll.a`) _is_ the dynamic linker input file for MSVC (unlike other compilers, `link.exe` can't generate this file content itself automatically from the shared library). It is a little unexpected how large this file is for LLVM however, but it appears to be correctly formed—the names for CXX functions are just very long, and so take 40MB to list (and also in a slightly inefficient format).

**Comment by staticfloat** [comment]
Since the binaries we serve are built with mingw, not MSVC, and C++ code is known to cause many problems when mixing runtimes, it is somewhere between extremely difficult and impossible to link against the mingw C++ API that our LLVM builds expose if you're using MSVC.  If you're using mingw, you shouldn't need an import library anyway, you can just link directly against the dynamic library.

This, combined with the fact that the `.dll.a` files are very large, is why we will not ship the import libraries with the standard Julia distribution.  Jameson points out some resources on generating an import library from a dynamic library: http://www.mingw.org/wiki/CreateImportLibraries and I will also point out that if you really need the `.dll.a` files that were generated from the build, you can download the appropriate version from the `LLVM_full_jll` build of your choice.  For instance, the Julia `v1.5.0` release uses [the `v9.0.1+6` release](https://github.com/JuliaBinaryWrappers/LLVM_full_jll.jl/releases/tag/LLVM_full-v9.0.1%2B6), so you can download the appropriate tarball that matches your system's configuration there, then extract the `.dll.a` file from that tarball.
