### ISSUE TITLE
Symlinked packages shouldn't be managed by Pkg

### ISSUE THREAD

**Issue by wavexx** [JuliaLang/julia#21548]
The Pkg and PkgDev modules are quite opinionated about how packages are kept locally (branching, updating and tagging strategy).

I still follow all tagging guidelines and use git for versioning, but already a while ago I stopped using PkgDev and simply symlinked ~/.julia/v[x]/package to my package directory. Since I use real "git" to manage my repository, when Pkg attempts to update my repository, it just fails with a libgit2 error. Simply speaking, when I'm developing a package, I really don't want Pkg to touch my working copy.

Pkg should detect if a package is symlinked and stop attempting to update the package, and simply consider the package as if it were "pinned" so that I can manage the versioning myself. Opinions?

Or maybe somebody could point to a better way to add unmanaged packages to Julia's search path in a way that still satisfies the REQUIRE constrains (as I develop multiple packages in parallel).

**Comment by nalimilan** [comment]
This doesn't seem specific to symlinked packages to me. You can also want to manage non-symlinked packages using git. Is the libgit2 error due to the link?

**Comment by wavexx** [comment]
On Tue, Apr 25 2017, Milan Bouchet-Valat wrote:
> This doesn't seem specific to symlinked packages to me. You can also
> want to manage non-symlinked packages using git.

Yes, I'd wish to be able to have a fine-grained control over some
packages. Especially for testing or debugging. pin() and checkout()
assume too much as well, but my main concern right now is how to manage
the packages I develop locally while still allowing Pkg.update() to do
it's job.

Without introducing extra state to maintain, checking if the package is
symlinked to mean "managed manually" seemed something I could submit a
PR for.

> Is the libgit2 error due to the link?

No, the libgit2 error in my case is because my main branch has an
unsupported remote type (I use a second url entry to push to github).

**Comment by mbauman** [comment]
Ref: https://github.com/JuliaLang/julia/pull/20819.  Seems like such a thing would be good, it just needs to be a bit more of a scalpel.

**Comment by oxinabox** [comment]
Checking if it is symlinked or not seems like the wrong tool for the job.

For example, the drive where I have `home` mounted is very small, because of how facilities management specs linux machines.
But I have a large drive in `/mnt/data` that I can use (but it has its own problems).
So I have considered several times, symlinking packages into there, particularly if they are overly large.
(Eg `Conda.jl`, `Luxor.jl`)

------

Does creating your own directory for keeping packages that you manage manually in work?
Then change your LOAD_PATH in your .juliarc.

That would be something like appending to  `~/.juliarc` (or creating if not got one already)
```julia
push!(LOAD_PATH, "~/manual_julia_pkgdir")
```

I don't think `Pkg` touches anything that is in the `LOAD_PATH` does it?
It has its own location `~/julia/vX.Y` which is compiled in, right?
That happens to always count as if it were in the `LOAD_PATH` (wether or not it is).

I could be wrong about this, it's been a while.

**Comment by wavexx** [comment]
On Wed, Apr 26 2017, Lyndon White wrote:
> For example, the drive where I have `home` mounted is very small,
> because of how facilities management specs linux machines. But I have
> a large drive in `/mnt/data` that I can use (but it has its own
> problems). So I have considered several times, symlinking packages
> into there, particularly if they are overly large. (Eg `Conda.jl`,
> `Luxor.jl`)

Would you consider linking individual packages or the entire vX.Y
hierarchy?

> Does creating your own directory for keeping packages that you manage
> manually in work? Then change your LOAD_PATH in your .juliarc.

Having a customizable load path would make a lot of sense.
Handle one directory as managed by Pkg, then leave the rest as-is.

This would also make managing packages with the system package manager
easier (just pre-set the load path for your distribution). As a debian
user/developer, I would certainly be happy about this.

**Comment by oxinabox** [comment]
> Having a customizable load path would make a lot of sense. Handle one directory as managed by Pkg, then leave the rest as-is. 

It is already a thing:
`LOAD_PATH` as I described it:
https://docs.julialang.org/en/release-0.4/manual/modules/#module-file-paths

vs  Pkg.dir(): https://docs.julialang.org/en/release-0.4/stdlib/pkg/?highlight=pkg.dir#Base.Pkg.dir

>Would you consider linking individual packages or the entire vX.Y hierarchy?
I would be (am) considering  both. 
The temptation to do just a few packages certainly exists, because in my case there are different issues with the data drive, such that I don't want too much that isn't truely data on it.

In general, I just don't expect symlinks not to work as if they were truely copies.
A symlink should be invisible to all but specialised functions that deal with symlinks.

**Comment by tkelman** [comment]
The existing Pkg doesn't play well with packages loaded from `LOAD_PATH` (https://github.com/JuliaLang/julia/issues/8679), but that's intended to be fixed with the Pkg3 rewrite. If `using` can be satisfied entirely from `LOAD_PATH` then you're probably okay, though you may have to go and fix any packages that are assuming `Pkg.dir` is the location they're getting loaded from (use `dirname(@__FILE__)` or `@__DIR__` and relative paths instead).

**Comment by lobingera** [comment]
Not exactly the same (symlink) but ...
```julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating Rsvg master...
INFO: Computing changes...
INFO: No packages to install, update or remove
ERROR: Update finished with errors.
=> Package Iplot cannot be updated.
GitError(Code:ERROR, Class:Net, Unsupported URL protocol)
```

with:
```
l1@orange4:~/.julia/v0.6/Iplot$ git config -l
...
remote.origin.url=/home/l1/.julia/v0.5/Iplot/
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
...
```
which seems to be not problem for git.

**Comment by tkelman** [comment]
Yeah, local filesystem remotes can be convenient sometimes. I'm not sure if that's a limitation in the libgit2 library or in our bindings to it.

**Comment by lobingera** [comment]
afaiu the libgit2 it supports all 4 protocols (git/ssh/https/local). At a first look at https://github.com/JuliaLang/julia/blob/master/base/libgit2/utils.jl and searching for URL_REGEX looks like it's applied. So it's rather on julia side than libgit2

**Comment by simonbyrne** [comment]
This has changed considerably with the new Pkg. If still an issue, please open at https://github.com/JuliaLang/Pkg.jl
