### ISSUE TITLE
0I should not insert zeros when catted with sparse matrices

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#21563]
```
julia> [speye(3,3) 0I]
3×6 SparseMatrixCSC{Float64,Int64} with 6 stored entries:
  [1, 1]  =  1.0
  [2, 2]  =  1.0
  [3, 3]  =  1.0
  [1, 4]  =  0.0
  [2, 5]  =  0.0
  [3, 6]  =  0.0
```

Those stored zero values shouldn't be there.

**Comment by kmsquire** [comment]
Just curious, is there any justification for (or against) this?  It's not as clear cut to me as it seems to be in the description?

**Comment by StefanKarpinski** [comment]
It's not so bad since it's just the diagonal zeros that are inserted, but it still seems like it would be better not to insert those zeros at all. Up to the sparse folks, I guess.

**Comment by tkelman** [comment]
Checking if the multiple is zero as a special case in these concatenation methods could make sense.

**Comment by stevengj** [comment]
Digging through the code, I think the check doesn't go into the concatenation methods.  There just needs to be a `diag == 0` check in the [speye_scaled function](https://github.com/JuliaLang/julia/blob/09299516b5bf91e465812b4284f49a55e1e0d432/base/sparse/sparsematrix.jl#L1431-L1438) used to convert `0I` into a sparse matrix.

Marking as an intro issue since this should be an easy PR.

**Comment by kmsquire** [comment]
I haven't careful followed the structural zeros discussion, but it seems this would be a reasonable way to define structural zeros on some diagonal of a matrix. 

I don't have a use case, so I have no idea if this would ever be desired, or if there's a better way to do it. Would it, and is there?

**Comment by iamnapo** [comment]
Aren't the zeros already there?

**Comment by tkelman** [comment]
Removing them (with `dropzeros!`) is a bit more convenient than creating them in the first place. a sparse matrix with stored zeros on the diagonal is needed once in a while, but since UniformScaling doesn't have a size it's probably not the best type to use for this. We could perhaps stop doing zero purging by default when converting Diagonal to sparse.

**Comment by kmsquire** [comment]
@iamnapo writes:
> Aren't the zeros already there?

I assume you're referring to my comment/question?  The idea of structural zeros in a sparse matrix is that, sometimes, it's useful to explicitly store zeros at a location and have it take up space, so you can change the value later without allocating.  From @tkelman's answer, it sounds like using `Diagonal` for this would be a better solution than using `0I`.
