### ISSUE TITLE
Pkg operations hang on Julia 0.5, MacOSX10.10.5

### ISSUE THREAD

**Issue by DSLituiev** [JuliaLang/julia#21658]
This issue seems to be similar to #11623 and #17142, but now on v0.5. Trying: `Pkg.add("Distributions")` and `Pkg.add("Klara")`, same story. 
```
INFO: Initializing package repository /Users/dlituiev/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
```
Let me know if I can add more specific information.

**Comment by david-varela** [comment]
I have just downloaded the most recent binaries for 64bit linux. I have the same problem, with the same ouptut as @DSLituiev  when I run `Pkg.update()`. 

Perhaps the problem is with insufficient feedback.
My output was only:
`INFO: Initializing package repository /Users/user/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl`
But I was monitoring disk usage in '~/.julia' and it was (slowly) growing. 

So maybe the process does not hang, it just does a bad job of indicating what is doing to the user.

It seems that, before installing the target package, the package manager goes through some kind of initialization where it downloads ~200MB of files to ~/.julia. As a new user, I was not aware of this and I had no feedback to show me otherwise.

After waiting a long enough time, things seem to be running smoothly. *Perhaps @DSLituiev could remove the .julia directory and run `Pkg.add` again, this time monitoring the directory space usage to see if the process is truly hanging.*

If this is the issue, more frequent feedback could stop other users from incorrectly assuming the process is hanging.

**Comment by KristofferC** [comment]
Please comment if this is still hanging. The latency in the new package manager is significantly better (regarding the second comment)
