### ISSUE TITLE
Strange behavior of Julia implicit multiplication

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#21798]
Hi guys!

I do not know if this was asked before, but I notice a very strange behavior with julia and the implicit multiplication. On the Internet, there has been a lot of conversation about the solution of the following equation:

    6/2(2+1)

A Cassio calculator often outputs 1, whether other calculators output 9. From my point of view, the convention states that between a number and a parenthesis, there is an implicit multiplication signal. Hence, we should get:

    6/2(2+1) = 6/2*(2+1) = 3*(2+1) = 3*3 = 9

However, if I type this very same equation in julia, I get:

    julia> 6/2(2+1)
    1.0

Because, as in the Cassio calculator, julia is solving 2(2+1) first as if it was a number. However, for such notation, you must always solve the left-most multiplication / division operation. Is it a real problem or am I missing something?

Notice that if I explicitly put the multiplication signal, then julia computes it fine:

    julia> 6/2*(2+1)
    9.0

Information about my system:

```
julia> versioninfo()
Julia Version 0.5.1
Commit 6445c82* (2017-03-05 13:25 UTC)
Platform Info:
  OS: Linux (x86_64-suse-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2687W 0 @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas_openmp.so.0
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, sandybridge)
```

**Comment by fredrikekre** [comment]
Note that this is only for numeric literals which IIUC basically have a higher precedence, e.g.

```julia
julia> a, b = 1, 2;

julia> a/2b
0.25

julia> expand(:(a/2b))
:(a / (2b))

julia> expand(:(a/2*b))
:((a / 2) * b)
```

**Comment by yuyichao** [comment]
Yes, this is indended and documented https://docs.julialang.org/en/latest/manual/integers-and-floating-point-numbers.html#man-numeric-literal-coefficients-1

**Comment by ronisbr** [comment]
Hi @yuyichao,

Don't we need to add more information to that page implying that it is also valid if you have only numbers and not variables? It was not clear, at least for me, why in

    6/2(2+1)

the operation `2(2+1)` took preference over `6/2`, since we do not have any variables here.

**Comment by fredrikekre** [comment]
It is pretty clear IMO:

> [...] Julia allows variables to be immediately preceded by a numeric literal, implying multiplication. [...] The precedence of numeric literal coefficients is the same as that of unary operators such as negation. [...] Numeric literals also work as coefficients to parenthesized expressions: [...]

**Comment by ronisbr** [comment]
@fredrikekre ,

Precisely, when I read, I thought "the precedence is valid when you have a literal coefficient multiplying a variable". For literals that multiplies parenthesis, it was not clear to me, since we have a very well defined convention about that in mathematics. For me, it was only saying that you can also use literals as coefficients for parenthesized expressions.

**Comment by ronisbr** [comment]
I think I will send a PR with the following text just after the example `2(x-1)^2 - 3(x-1) + 1`:

> Notice that, in this case, the precedence of numeric literal coefficient is still the same as that of the unary operators. Hence, the expression `6/2(2+1)` leads to `1` instead of the conventional result `9`.

What do you think?

**Comment by fredrikekre** [comment]
Improvements to the documentation is always good.

**Comment by ronisbr** [comment]
Done, thanks @fredrikekre and @yuyichao 👍

**Comment by stevejacobscronung** [comment]
That is some obscure convention, implicit multiplication, for some reasons some people stick to it. But I didn't find any sources of such a n exotic convention. So, the best way is to regard as bug and misleading the provided feature of higher priority of implicit multiplication and avoid it. By all accepted conventions, which are used in Wolfram, WolframAlpha, Google, there is no higher priority given for multiplication, whether it is implicit or explicit. So, the 
There is a discussion about this convention, but with no sources provided. So it mentions that such a convention is not adopted, and 
https://people.math.harvard.edu/~knill/pedagogy/ambiguity/index.html#:~:text=In%20this%20more%20sophisticated%20convention,like%20x%20*%20%2F%20or%20%C3%B7.
**In this more sophisticated convention, which is often used in
algebra, implicit multiplication is given higher priority than explicit
multiplication or explicit division,** in which those operations are written
explicitly with symbols like x * / or ÷. Under this more sophisticated
convention, the implicit multiplication in 2(2 + 2) is given higher
priority than the explicit division in 8÷2(2 + 2). In other words,
2(2+2) should be evaluated first. Doing so yields 8÷2(2 + 2) = 8÷8 =
1. By the same rule, many commenters argued that the expression 8 ÷ 2(4)
was not synonymous with 8÷2x4, because the parentheses demanded immediate
resolution, thus giving 8÷8 = 1 again.

This **convention** is very reasonable, and I agree that **the answer is 1
if we adhere to it**. But it is **not universally adopted**. The calculators
built into Google and WolframAlpha use the more elementary convention;
they make no distinction between implicit and explicit multiplication
when instructed to evaluate simple arithmetic expressions.
