### ISSUE TITLE
sincos is broken for nonstandard types

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#22095]
Due to 
https://github.com/JuliaLang/julia/blob/3e3f96630cd9ad095c0b12b604e8d3d666b3c34b/base/math.jl#L428:

```jl
 res = Base.FastMath.sincos_fast(x)
```
This breaks `sin`, `cos`, `exp` etc. for `Complex{T}` with non-standard `T` (i.e. not `Float64`, `Float32`), that previously worked fine (but apparently weren't tested).

Presumably it's sufficient to restrict the argument type of the above `sincos` definition and add a generic fallback? Should that be

```jl
sincos(x) = (sin(x), cos(x))
```
or is there a better solution?

**Comment by yuyichao** [comment]
What's an example of non-standard `T` and what's the error message?

The fallback method is defined for [`sincos_fast`](https://github.com/JuliaLang/julia/blob/3e3f96630cd9ad095c0b12b604e8d3d666b3c34b/base/fastmath.jl#L314) and I don't see why that line will cause any error.

**Comment by dpsanders** [comment]
```jl
julia> using IntervalArithmetic

julia> a = (1..1) + (2..2)*im
[1, 1] + [2, 2]*im

julia> typeof(a)
Complex{IntervalArithmetic.Interval{Float64}}

julia> sin(a)
ERROR: TypeError: sin: in typeassert, expected AbstractFloat, got IntervalArithmetic.Interval{Float64}
Stacktrace:
 [1] sincos at ./math.jl:428 [inlined]
 [2] sin(::Complex{IntervalArithmetic.Interval{Float64}}) at ./complex.jl:701
```

**Comment by yuyichao** [comment]
k. so it's throwing an error due to https://github.com/JuliaLang/julia/blob/3e3f96630cd9ad095c0b12b604e8d3d666b3c34b/base/fastmath.jl#L313 since `float` doesn't return an `AbstractFloat`. The assertion is to avoid infinite recursion so it shouldn't be removed. The alternative way I've thought about but decide not to do before seeing a `float` that triggers the assertion is

```julia
function sincos_fast(v::Real)
    vf = float(v)
    if isa(vf, AbstractFloat)
        sincos_fast(vf)
    else
        sin_fast(vf), cos_fast(vf)
    end
end
```

Another way is to restrict the input type to `Integer`
```julia
sincos_fast(v::Integer) = sincos_fast(float(v))
```

And rely on `float(::Integer)` to not return another integer type...

**Comment by dpsanders** [comment]
Ah, I see, thanks. And you can't just have two different fallbacks, one for `v::AbstractFloat` and the other for `v::Real`?

**Comment by yuyichao** [comment]
There are two fallbacks https://github.com/JuliaLang/julia/blob/3e3f96630cd9ad095c0b12b604e8d3d666b3c34b/base/fastmath.jl#L312-L314 and the `isa(vf, AbstractFloat)` method is basically implementing an fallback for `Real`.

**Comment by giordano** [comment]
There are other functions that don't work with `Complex{IntervalArithmetic.Interval{Float64}}` and aren't related with `sincos`, like 'log1p`, `exp2`, `exp10`.

**Comment by dpsanders** [comment]
Also `log`:

```jl
julia> using IntervalArithmetic

julia> z = (1.1..1.2) + (2.1..2.2)im
[1.09999, 1.20001] + [2.09999, 2.20001]*im

julia> log(z)
ERROR: StackOverflowError:
Stacktrace:
 [1] log(::Complex{IntervalArithmetic.Interval{Float64}}) at ./complex.jl:470 (repeats 80000 times)
```

**Comment by giordano** [comment]
...and also `sqrt`,  `log10`, `log2`.  And `sinpi`, `cospi`, `sinc`, `cosc`, depending on the branch they enter:
```julia
julia> sinpi((1..2) + (3..4)im)
ERROR: StackOverflowError:
Stacktrace:
 [1] sinpi(::IntervalArithmetic.Interval{Float64}) at ./special/trig.jl:220 (repeats 80000 times)

julia> cospi((1..2) + (3..4)im)
ERROR: StackOverflowError:
Stacktrace:
 [1] cospi(::IntervalArithmetic.Interval{Float64}) at ./special/trig.jl:221 (repeats 80000 times)

julia> sinc((1..2) + (3..4)im)
ERROR: StackOverflowError:
Stacktrace:
 [1] sinc(::Complex{IntervalArithmetic.Interval{Float64}}) at ./special/trig.jl:298 (repeats 80000 times)

julia> cosc((1..2) + (3..4)im)
ERROR: StackOverflowError:
Stacktrace:
 [1] cosc(::Complex{IntervalArithmetic.Interval{Float64}}) at ./special/trig.jl:310 (repeats 80000 times)
```

**Comment by dpsanders** [comment]
Thanks for the list.

**Comment by dpsanders** [comment]
@yuyichao What is special about `AbstractFloat` here?

**Comment by yuyichao** [comment]
where?

**Comment by dpsanders** [comment]
In `sincos_fast`.

**Comment by stevengj** [comment]
There are lots of cases where `float(x)` does not produce an `AbstractFloat`, e.g. `float(1+0im)`, so that assertion doesn't seem quite right to me.

One option would be to simply let it throw a `StackOverflow` error if `float(v) === v` here.

Another option would be to use something like `sincos_fast(v::Real) = sincos_fast(assert_different_types(v, float(v)))` where
```jl
assert_different_types{T}(x::T, y::T) = error("....")
assert_different_types(x, y) = y
```

**Comment by yuyichao** [comment]
> In `sincos_fast`.

https://github.com/JuliaLang/julia/issues/22095#issuecomment-304417064

> e.g. `float(1+0im)`,

This case is irrelevant since it's not `::Real`

> One option would be to simply let it throw a StackOverflow error if float(v) === v here. That seems simplest to me; it's not like you really get "infinite recursion", right?

I don't think that fixes any problem? You **will** get a infinite recursion.

> Another option would be to use something like `sincos_fast(v::Real) = sincos_fast(forcefloat(v))` where

It's basically what the current code is doing. `forcefloat` implemented this way won't actually prevent a infinite recursion.

**Comment by pkofod** [comment]
> I've thought about but decide not to do

I figure there's an obvious reason, but why?

**Comment by yuyichao** [comment]
I did not know any exception so I have no way to back it up in case anyone asks (and I'm 100% sure someone would). Especially since the infinite recursion in other functions clearly shows that it is not currently done in any other part in Base.

**Comment by giordano** [comment]
> Especially since the infinite recursion in other functions clearly shows that it is not currently done in any other part in Base.

Yes, I believe there are several places in Base where it's implicitly assumed that `float(x::Real)` returns an `AbstractFloat`.  I wouldn't say that's a too bad assumption.

**Comment by dpsanders** [comment]
My question was more along the lines of "why is `AbstractFloat` singled out?". I think the answer is simply because there are specialised versions of `sincos` defined in Base for each of the subtypes of `AbstractFloat`.

It is definitely a bug that all these complex functions that have relatively easy fallback definitions in terms of their real counterparts (ignoring subtleties of branch cuts etc) do not work for such "non-standard" complex types.

**Comment by stevengj** [comment]
@yuyichao, "infinite recursion" is not infinite because it eventually throws a StackOverflowError.  So, it's basically a choice between throwing one exception or another, no?

**Comment by stevengj** [comment]
How about
```
function sincos(x::Real)
   f = float(x)
   if typeof(f) === typeof(x)
    sincos(f)
    else (sin(f), cos(x)
    end
end
```

**Comment by yuyichao** [comment]
>  I think the answer is simply because there are specialised versions of sincos defined in Base for each of the subtypes of AbstractFloat.

No. It's because the fallback is defined for `AbstractFloat`.

> "infinite recursion" is not infinite because it eventually throws a StackOverflowError. So, it's basically a choice between throwing one exception or another, no?

..... Errr, well, StackOverflowError **IS** infinite recursion, in that real infinite recursion (without overflowing the stack) will not happen currently. If you don't like how it is described I can use "useless/unhelpful error". Note that this is also a case where if we disable certain codegen llvm options can actually infinitely recurse without raising any error.

> The point of my forcefloat approach is that it catches recursion loops, but still works for types in which float(::T) does not produce an abstractfloat as long as there is an appropriate method.

There could be cases where this is the case. Certainly not for `IntervalArithmetic`.

> How about

I personally prefer not using `typeof(before) === typeof(after)` as the check since it doesn't theoritically avoid infinite recursion (reads: StackOverflowError). Given that the intent of the `float` call is to covert to `AbstractFloat` I think the original version I proposed [above](https://github.com/JuliaLang/julia/issues/22095#issuecomment-304417064) is clearer.
