### ISSUE TITLE
Documentation for `escape_string` is inaccurate

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#22286]
```
escape_string([io,] str::AbstractString[, esc::AbstractString]) -> AbstractString
```

Note the return value. Nope:

```
julia> typeof(escape_string(IOBuffer(), "abc", "ab"))
Void
```

**Comment by KristofferC** [comment]
Also, this should work?

```
julia> escape_string("foo", "f")
ERROR: MethodError: no method matching escape_string(::String, ::String)
Closest candidates are:
  escape_string(::Any, ::AbstractString, ::AbstractString) at strings/io.jl:233
  escape_string(::AbstractString) at strings/io.jl:249
```

**Comment by crstnbr** [comment]
Similar inconsistencies with `unescape_string`.

I will try to fix those issues and make a PR as soon as possible.

**Comment by crstnbr** [comment]
Because of #16603, I will not split up the existing function into a `print_escape_string` (with return type Void) and a function `escape_string` (with return type AbstractString). Instead I will adjust the documentation to indicate that depending on wether an `io` is given the return type differs.

I will also fix the `escape_string("foo", "f")` issue by defining a corresponding variant of `escape_string`.

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/24539
