### ISSUE TITLE
Sparse solves with col-permuted matrix

### ISSUE THREAD

**Issue by HFriberg-mosek** [JuliaLang/julia#22335]
The minimal example:
```
B = speye(3)
B[:,[3,2,1]] \ [1.0; 1.0; 1.0]
```

gives
```
ERROR: ArgumentError: matrix has one or more zero pivots
 in #ldltfact!#10(::Float64, ::Function, ::Base.SparseArrays.CHOLMOD.Factor{Float64}, ::Base.SparseArrays.CHOLMOD.Sparse{Float64}) at ./sparse/cholmod.jl:1350
 in (::Base.LinAlg.#kw##ldltfact!)(::Array{Any,1}, ::Base.LinAlg.#ldltfact!, ::Base.SparseArrays.CHOLMOD.Factor{Float64}, ::Base.SparseArrays.CHOLMOD.Sparse{Float64}) at ./<missing>:0
 in #ldltfact#12(::Float64, ::Array{Int64,1}, ::Function, ::Base.SparseArrays.CHOLMOD.Sparse{Float64}) at ./sparse/cholmod.jl:1386
 in #ldltfact#13(::Array{Any,1}, ::Function, ::Hermitian{Float64,SparseMatrixCSC{Float64,Int64}}) at ./sparse/cholmod.jl:1426
 in \(::SparseMatrixCSC{Float64,Int64}, ::Array{Float64,1}) at ./sparse/linalg.jl:871
```

The expected behavior is to get the solution vector `[1.0; 1.0; 1.0]`.

**Comment by andreasnoack** [comment]
Short term, you can work around this issue by explicitly calling `lufact(B[:,[3,2,1]])\[1,1,1]`. The issue is that when the matrix is symmetric, we try to use CHOLMOD for the factorization and CHOLMOD, in contrast to UMFPACK`, doesn't use pivoting during the numerical factorization.

I think the solution to this issue is to delay the throw of the exception in `ldltfact`. Then `\` can check if the factorization failed and use `lufact` instead. We could also use `try`/`catch` it is more fine grained to just check the factorization object and it matches what we are doing for the dense factorizations.
