### ISSUE TITLE
Feature requested: dot operation for function with vector input on each row of a matrix

### ISSUE THREAD

**Issue by fufjvnvnf** [JuliaLang/julia#22492]
Essentially, I have a function with vector as input, `function s(x::Vector)...`, and I would like to feed it a matrix `x` using dot operation, i.e. `s.(x)`, and I would like `s` to take each row of `x` as input. However, `s.` is evaluated for each entry on `x` instead of each row as I expected, and thus throws `no method matching s(::Float64)`. Is there already a way to declare row-wised dot operation? If not, isn't it nice to have it as a new feature?

**Comment by Sacha0** [comment]
Hello Wilson! Have you considered collecting your `Vector`s in a `Vector`, `Tuple`, or some other container (rather than as rows in a `Matrix`)? Might do the trick for you. Best!

**Comment by fufjvnvnf** [comment]
If it were in another scenario I would do it that way, but in my particular case I'm using the `ForwardDiff` library, which accepts only functions with vector input,  to test my `Softmax` layer, which takes in matrices as input, for my NN library. I generate multi row test cases using `rand(m,n)` and feed it to both my layer and the vector function. Is there any efficient way of converting a matrix into a vector of vector?

**Comment by rdeits** [comment]
@fufjvnvnf this is probably more appropriate as a discussion on the [Julia users Discourse forum](https://discourse.julialang.org/), rather than as a Github issue (since it's not actually a bug). 

Also, you might want to check out [CatViews.jl](https://github.com/ahwillia/CatViews.jl) which is designed to let you create a collection of vectors or arrays and treat them like a single flat vector (in order to pass them to something like an optimization function that expects vector input). I haven't used it with ForwardDiff myself, but it might work nicely.

**Comment by oscardssmith** [comment]
1.1 added `eachrow` which solves this.
