### ISSUE TITLE
deprecate `readstring` to `read(io, String)`

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#22793]
This is more consistent with other `read` methods, and more easily extensible to other types of strings.

**Comment by jpfairbanks** [comment]
This sounds straightforward you just:

- [ ] remove the definition of readstring
- [ ] add the new method for read(s::IO, ::Type{String})
- [ ] @deprecate in the base/deprecated.jl
- [ ] chase down all the deprecation warnings in Base
- [ ] Update the docs

Are there any other steps?

**Comment by JeffBezanson** [comment]
Correct!

**Comment by jpfairbanks** [comment]
This example in the docs doesn't work .
```
"""
    open(f::Function, args...)

Apply the function `f` to the result of `open(args...)` and close the resulting file
descriptor upon completion.

**Example**: `open(readstring, "file.txt")`
"""
```

You could make an anonymous function. `open(f->read(f, String), "file.txt")` but that looks weird.

**Comment by jpfairbanks** [comment]
Also what do you do with this line in `precompile.jl`

`precompile(Tuple{typeof(Base.open), typeof(Base.readstring), String})`
?

**Comment by JeffBezanson** [comment]
I think `open(f->read(f, String), "file.txt")` is fine, or maybe `open(read, "file.bin")` instead.

The precompile line can just be deleted; those need to be regenerated periodically anyway.

**Comment by jpfairbanks** [comment]
Ok, I went with `f-read(f,String)` and deleted it. The PR is open and CI failed due to some documentation building stuff. I don't know what to do about the CI.

**Comment by matklad** [comment]
Low-weight opinion of a new Julia user, but I personally would appreciate if there were `Base.readstring(io) = read(io, String)` alias defined. 

`readstring(io)` is easier to type than `read(io, String)` and also is cognitively easier to understand -- I won't be thinking "cool, Julia can dispatch on types", the could would be just boring. This is a bit of a [concrete abstraction](https://matklad.github.io/2020/08/15/concrete-abstraction.html) smell, as fixing the second argument to `String` would be pretty common I guess.

**Comment by StefanKarpinski** [comment]
Personally, I miss `readall(io)` which is how this was originally spelled. Why does that spelling make sense?

1. Whereas `read` produces bytes, `readline`, `readlines`, `readuntil` and `readchomp` all produce strings, so there is strong precedent for something called `readxxx` producing a string already.

2. Calling it `readstring` is a bit ambiguous since there are many ways to read a string from an IO stream, such as all of those functions; it would also be arguable that something called `readstring` could read a NUL-terminated string from an IO stream. Julia doesn't use NUL-terminated strings, so I'm not arguing for that, but the point is that `readstring` and even `read(io, String)` are not that clear. Read a string how?

3. The key behavior of `readall` is that it reads **all** of the remaining data as a string. The fact that `readxxx` functions generally produce strings already implies that it produces a string; calling it `readall` makes that as clear as possible.

Therefore, I propose that we reinstate `readall(io)` as an alias for `read(io, String)`.

**Comment by matklad** [comment]
Huh, TIL about `readchomp`. It actually fully replaces the need for `readall` for me: https://github.com/matklad/config/commit/6634ca5bb101c20b025585ffc757d65eecf4afb1. I didn't realize that it *could* exists, I think advertising it in the docs might help: https://github.com/JuliaLang/julia/pull/37806!

**Comment by StefanKarpinski** [comment]
`readchomp` is one of my favorites 😁
