### ISSUE TITLE
Add Sys.isfreebsd()  

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#22794]
Might be useful to add `Sys.freebsd()` now that it looks like there is more support for the platform.

**Comment by tkelman** [comment]
`Sys.isbsd` exists

**Comment by musm** [comment]
Doesn't that also include, e.g. macOS.
I'm not 100 convinced this is necessarily needed, but it might be useful instead of `Sys.KERNEL === :FreeBSD`

**Comment by ararslan** [comment]
I don't think it would hurt to add it but at the same time I'm not sure there are all that many situations where it's useful. In particular, it appears there's only one place in this repo where it would even be used, and that's in the terminal tests.

The only other FreeBSD conditional code I've seen in the wild is new in BinDeps (I added it) but that's internal. Code that uses BinDeps but still conditions on `Sys.KERNEL` to detect FreeBSD really doesn't need to do the conditional because of the `os` argument to `provider`. I believe HDF5.jl does this.

Given that no one regularly tests Julia on OpenBSD, DragonFly, et al. (and last I tried I couldn't get Julia to build on OpenBSD, DragonFly, and even 32-bit FreeBSD), `Sys.isbsd() && !Sys.isapple()` is effectively FreeBSD.

**Comment by iblis17** [comment]
> (and last I tried I couldn't get Julia to build on OpenBSD, DragonFly, and even 32-bit FreeBSD)

(@ararslan There is a patch  not upsteamed for i386 FreeBSD: https://github.com/lwhsu/freebsd-ports-lang-julia/blob/master/files/extra-patch-ui_Makefile)

**Comment by ararslan** [comment]
Nice, it would be good to submit that as a PR.

**Comment by musm** [comment]
perhaps not worth it, closing
