### ISSUE TITLE
Non-intuitive matching behavior

### ISSUE THREAD

**Issue by jamesonquinn** [JuliaLang/julia#22992]
This issue has to do with the fact that, as @JeffreySarnoff on gitter says, "when you constrain a parameter directly (immediately) the parameter is interpreted as a directly subtype-constrained entity but when you constrain a parameter using the external where form, the parameter is interpreted through the type system meta accomodation methods."

Here's a simple demonstration of what I'm talking about:

```
> Type{Associative} <: Type{X<:Associative} where {X}
false
> Type{Associative} <: Type{X} where {X<:Associative}
true
> Type{Associative{K,SVT} where SVT where K} <: Type{X} where {X<:Associative{K,SVT}} where SVT where K
false
> Type{Associative{K,SVT} where SVT where K} <: Type{X} where {X<:Associative{K,SVT} where SVT where K}
true
```

Of course, when I actually ran into this issue, it was as a MethodError that I'm now having trouble stripping down to a MVE. But here's the error:

```
MethodError: no method matching myvaltype(::Type{Associative{K,SVT} where SVT<:Real where K})
Closest candidates are:
  myvaltype(::Type{X<:Associative{N,SVT<:Real}}) where {SVT<:Real, N, X<:Associative{N,SVT<:Real}} at...
```

I'm not really sure if this is something that should be fixed, or just better documented. Certainly the MethodError I was getting is pretty impenetrable. I'll continue to work on this, and see if I can clarify and report back on this bug.

**Comment by JeffreySarnoff** [comment]
+1 principle of least surprise

**Comment by yuyichao** [comment]
You are using the wrong syntax. The syntax you are using means something else.

```julia
julia> Type{X<:Associative} where {X}
Type{false}
```

**Comment by JeffreySarnoff** [comment]
would you elaborate

**Comment by yuyichao** [comment]
`Type{X<:Associative} where {X}` means the value of `Type{X<:Associative}` for all `{X}` so it is either `Type{true}` or `Type{false}`. The `<:` in the `Type{}` is an expression just like anything else on the LHS of `where` and it is **NOT** a type constraint, which is specified on the RHS of `where`. It's probably just a invalid syntax since it should in priciple give `Type{true}` when applying on an `X` where `X<:Assotiative` and `Type{false}` for other types.

**Comment by JeffBezanson** [comment]
The `<:` in `Type{X<:Associative}` should be an error, since it's calling `<:` on a type with a free type variable (`X`), which is not a well-formed query. I think we'll start being able to give an error for this pretty soon.

There is also a problem with the "closest candidates" printing. Example:

```
julia> f(x::Array{T}) where {T<:Real} = 0

julia> methods(f)
# 1 method for generic function "f":
[1] f(x::Array{T,N} where N) where T<:Real in Main at REPL[1]:1
```

That printing is correct. But here:

```
julia> f(0)
ERROR: MethodError: no method matching f(::Int64)
Closest candidates are:
  f(::Array{T<:Real,N} where N) where T<:Real at REPL[1]:1
```

`Array{T<:Real}` is printed, which is not ideal. Unfortunately this case has its own printing code to handle red highlighting. It needs to take `UnionAll` environments into account, to avoid printing the constraints on type variables in more than one place.

**Comment by StefanKarpinski** [comment]
Should this be left open to track giving the warning?
