### ISSUE TITLE
LoadError: UndefVarError: MINICONDA_VERSION not defined

### ISSUE THREAD

**Issue by fufjvnvnf** [JuliaLang/julia#23052]
Hi. I cannot install PyPlot nor PyCall, neither can I build Conda; this error message is everywhere. I searched for it online and in the github community but never see it mentioned. Any idea?

**Comment by andreasnoack** [comment]
Please ask questions on https://discourse.julialang.org/

**Comment by Keno** [comment]
Please direct this question to [the discourse forum](https://discourse.julialang.org/) for usage question, or to the appropriate package, presumably [PyCall](https://github.com/JuliaPy/PyCall.jl) or [Conda](https://github.com/JuliaPy/Conda.jl). This repository is for julia issues and has little to do with python ;).

**Comment by fufjvnvnf** [comment]
May I politely ask how do you diagonalize so quickly that this could not possibly be a potential bug?

**Comment by fufjvnvnf** [comment]
@Keno I'm trying to install these packages on julia. Are `Pkg.add("PyPlot")`, `Pkg.build("PyCall")` the right commands?

**Comment by yuyichao** [comment]
Please do no ask questions here.

> this could not possibly be a potential bug

It could, just extremely unlikely and should have the most likely causes sorted out first.

**Comment by Keno** [comment]
I understand. Those are the right commands. It is likely a bug somewhere. However, this place is the wrong place to raise this issue, as it is unlikely that the bug is related to any code in this repository (which is the base julia language, standard library, and compiler).

**Comment by StefanKarpinski** [comment]
> May I politely ask how do you diagonalize so quickly that this could not possibly be a potential bug?

`LoadError: UndefVarError: MINICONDA_VERSION not defined` means the variable `MINICONDA_VERSION` is not defined. Since `MINICONDA_VERSION` is never mentioned in this repository's code base, this problem can't really be an issue here – unless `UndefVarError` is happening erroneously because of some fundamental language breakage, which is quite unlikely compared to the possibility that some package which is supposed to define this is failing to do so. The stack trace (which you didn't post – you should generally do that when reporting bugs) should tell you where the variable usage occurred.
