### ISSUE TITLE
Add doc instructions for building Julia-compatible binaries on Windows

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#23105]
It's quite difficult to determine what one actually needs in order to build an arbitrary shared library on Windows that's compatible with Julia. To avoid confusion and headaches for package developers (and anyone else attempting to do this), I think we should add something to the documentation explaining what all is required, e.g. exception and threading models, C++ ABI, etc. There's some basic information about building Julia itself in README.Windows.md, but for compatible binaries, it's extraordinarily non-obvious.

Examples of when this would be helpful: https://github.com/JuliaLang/Rmath-julia/pull/19, https://github.com/ararslan/fftw-builder

**Comment by tkelman** [comment]
At the moment the most reliable option is "use the same compiler used to build the Julia binaries" which is the cygwin cross-compiler described in README.windows.md (currently 5.4.0, seh exceptions on 64 bit, sjlj on 32 bit, posix threading). WinRPM packages are cross-compiled from the opensuse build service, using a cross-compiler configured as seen here https://build.opensuse.org/package/view_file/windows:mingw:win64/mingw64-cross-gcc/mingw64-gcc.spec?expand=1 (or https://build.opensuse.org/package/view_file/windows:mingw:win32/mingw32-cross-gcc/mingw32-gcc.spec?expand=1 for 32 bit). This is currently 7.1.0 but otherwise the a close configuration to cygwin's cross compiler. Unfortunately there are ABI changes between 5.4.0 and 7.1.0 that are currently causing problems with WinRPM packages on 32 bit Julia, which is a problem that I don't have a good solution to at the moment other than maybe building Julia itself with opensuse's compiler. There are also configure flags on how you build the cross-compiler such as `--enable-fully-dynamic-string` that make an ABI difference and can cause problems especially on C++ libraries if you use a compiler that doesn't match. I believe a handful of Julia packages have been successfully cross-compiling binaries using Ubuntu's mingw64 package, though I don't know offhand exactly which Ubuntu version or package configuration has been used. Ubuntu doesn't have many mingw libraries packaged which is why WinRPM uses opensuse's repository. Cygwin has a fair number of mingw libraries packaged nowadays but someone would have to write a WinRPM-equivalent package to parse Cygwin's repository information to get latest versions to be able to switch for packages.

For the source configuration used to build cygwin's cross-compiler, see the cygport file in http://mirrors.mit.edu/cygwin/x86_64/release/mingw64-x86_64-gcc/mingw64-x86_64-gcc-5.4.0-3-src.tar.xz (or http://mirrors.mit.edu/cygwin/x86_64/release/mingw64-i686-gcc/mingw64-i686-gcc-5.4.0-4-src.tar.xz for 32 bit). In a BinDeps replacement we should aim to provide a pre-built gcc cross compiler (for exactly which variant of Linux as a controlled build environment is still TBD) that matches this configuration as closely as possible. Or we change to using a different compiler on our Windows buildbots.

**Comment by ararslan** [comment]
Awesome, thanks for the info. Could that be added to the devdocs or something? Or maybe to the Windows README?

**Comment by ViralBShah** [comment]
This is now considerably addressed with BB.
