### ISSUE TITLE
Documentation for isequal appears partially repeated

### ISSUE THREAD

**Issue by IlyaOrson** [JuliaLang/julia#23106]
The subsequent documentation for methods of `isequal` for [Tuple{Any,Any}](https://docs.julialang.org/en/latest/stdlib/base/#Base.isequal-Tuple{Any,Any}) and [Tuple{Nullable,Nullable}](https://docs.julialang.org/en/latest/stdlib/base/#Base.isequal-Tuple{Nullable,Nullable}) is partially repeated on latest manual.

**Comment by nalimilan** [comment]
Thanks for catching this. It looks OK at the REPL, so that's a bug in the manual or in Documenter.jl. The docstring is included via:
```
Base.isequal(::Any, ::Any)
Base.isequal(::Nullable, ::Nullable)
```

OTOH, for `isless` the docstring is not repeated. It's included via:
```
Base.isless
Base.isless(::Nullable, ::Nullable)
```

I would think both forms should work, but maybe there's a reason for the difference?

Cc: @mortenpi

**Comment by mortenpi** [comment]
Documenter groups docstrings together based on the signature (similar to multiple dispatch). In this case I think `Base.isequal(::Any, ::Any)` also includes `Base.isequal(::Nullable, ::Nullable)` because `Nullable <: Any`. It's not documented though how Documenter decides this exactly and I'm not very familiar with that part of Documenter.

I reckon Documenter's handling of this could probably be refined. It should probably be consistent with the REPL.

In this case, maybe only keep `Base.isequal(::Any, ::Any)` since it includes the docstring for the `Nullable` case?

**Comment by nalimilan** [comment]
Thanks. We should probably apply that fix.

Though that behavior doesn't sound very useful to me: when you list a signature, I'd say you usually want to include only the one that exactly matches (just like when calling `invoke`). OTOH I could understand that not giving any signature would include all docstrings an therefore create a repetition (but for some reason Documenter appears to be smart enough to avoid it).
