### ISSUE TITLE
DomainError() with no arguments throws warning

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#23132]
```julia

julia> DomainError()
WARNING: DomainError now supports arguments, use `DomainError(value)` or `DomainError(value, msg)` instead.
Stacktrace:
 [1] depwarn at .\deprecated.jl:70 [inlined]
 [2] DomainError() at .\deprecated.jl:1550
 [3] eval(::Module, ::Expr) at .\repl\REPL.jl:3
 [4] eval_user_input(::Any, ::Base.REPL.REPLBackend) at .\repl\REPL.jl:69
 [5] macro expansion at .\repl\REPL.jl:100 [inlined]
 [6] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at .\event.jl:73
while loading no file, in expression starting on line 0
DomainError(nothing, #undef)
```
 
IMO this should  not throw a warning . Was this intentional so that package authors start using the new feature?

**Comment by fredrikekre** [comment]
It is an intentional deprecation warning, see #22751

**Comment by musm** [comment]
I don't see a discussion regarding the deprecation warning in the issue?

**Comment by fredrikekre** [comment]
What do you mean? Zero-arg DomainError() was deprecated in the linked PR.
https://github.com/JuliaLang/julia/blob/83007fb8c4c748fb23d38759daafd77fa1d56c2b/base/deprecated.jl#L1544-L1548

**Comment by musm** [comment]
RIght. My point is that I think `DomainError() ` --> `DomainError(nothing)  . I.e  the previous behavior should just just correspond to what is currently `DomainError(nothing)` .

**Comment by fredrikekre** [comment]
Why? The point of #22751 was to make `DomainError` more informative; so why would you opt out of that new feature?

**Comment by musm** [comment]
The new feature is great. I have no problems with it.
Similar to `error`, you can opt out to adding a more descriptive error message  or you can decide to  leave it as `error()` .   Same thing here, perhaps you do not care to add a message then you have to use `DomainError(nothing)` instead of `DomainError()` which is what I suggest it be an alias for. 

Considering the misunderstanding, I think this should be reopened.

**Comment by musm** [comment]
@timholy : Since you implemented this feature, care to share any insight on this?

**Comment by timholy** [comment]
Perhaps unsurprisingly, I agree with @fredrikekre ---without a deprecation warning, people won't change their code, and consequently we'll still have impenetrable errors in production code. I agree that for "quick scripting" for your own personal use, there might be times when you don't want to bother being explicit about the nature of the problem, but I think that's a minor disadvantage compared to the benefits.

The only reason it wasn't worse before was that [we used to do something clever](https://github.com/JuliaLang/julia/blob/0d83de93eb208e71aa5701329551939715268658/base/replutil.jl#L234-L262) to try to be at least a bit informative, but I think that being stupid is much better than being clever when you can get away with it (and now we can).

After 1.0 comes around we could consider adding the fallback you're asking for, but because the next release would be the first (only) with a depwarn I think we have to leave it the way it is now.

**Comment by musm** [comment]
@timholy  Thanks for the clarification.  I think it would then be best to add something to Compat to allow using this feature in a backwards compatible manner with 0.6 .
 I think this issue should receive a TODO or pending label.

**Comment by timholy** [comment]
Good idea (and I should have thought of this myself). I am pretty swamped for the next couple of days, so if you're in a hurry I'd appreciate some help. But I will put this on my TODO list if no one beats me to it.
