### ISSUE TITLE
REPL improvement: Only show previous entrys once when pressing up/down

### ISSUE THREAD

**Issue by ChristianKurz** [JuliaLang/julia#23316]
Consider the following history:

```julia
julia> abc = 1
1
julia> abc = 2
2
julia> abc = 2
2
julia> xyz = 1
1
julia> abc = 3
3
julia> xyz = 1
1
julia> xyz = 2
2
```

now entering `a` and pressing `up` results in the following items displayed as expected:

```julia 
julia> a #press up
julia> abc = 3
julia> abc = 2 #abc = 2 is only shown once
julia> abc = 1
```

On the other hand, if `x` is entered and `up` is pressed

```julia #press up
julia> x
julia> xyz = 2
julia> xyz = 1
julia> xyz = 1 #xyz = 1 is shown twice
```

I think it would be better to only have `xyz = 1` be shown once.
While saving identical consecutive commands in `julia_history` was fixed earlier this year (cannot find the issue nr.), identical commands are still saved if they are not entered consecutively. 
These would need to be filtered when up/down-searching

**Comment by KristofferC** [comment]
To me it looks like https://github.com/JuliaLang/julia/blob/e6fc03d10bc12db9212d4b3734c6217d8db6d71f/stdlib/REPL/src/REPL.jl#L735 is supposed to handle it but the `|| hist.modes[idx] != LineEdit.mode(s)` is buggy and always false because `hist.modes[idx]` is a `Symbol` and `LineEdit.mode(s)` is a `REPL.LineEdit.Prompt` so they can never compare `==` and this will always be true. And indeed, when removing that line it no longer shows the `xyz = 1` twice. I'll remove it and make a test unless someone beats me to it.
