### ISSUE TITLE
Compilation fails with Intel compilers

### ISSUE THREAD

**Issue by anton-malakhov** [JuliaLang/julia#23407]
I tried to compile Julia (master and v0.6.0) with Intel compiler 2017.4.196 according to README.md file by sourcing compilervars.sh and setting Make.user as:
```
USEICC = 1
USEIFC = 1
USE_INTEL_MKL = 1
USE_INTEL_LIBM = 1
USE_OPROFILE_JITEVENTS = 1
```
First, it complained about unrecognized OpenMP pragmas, which indicates lack of `-openmp` compiler flag. Then, it failed as if `ld` was used to link objects created by Intel compiler when its own linker is needed:
```
[ 88%] Linking CXX executable ../../bin/llvm-ar
ld: ../../bin/llvm-ar: hidden symbol `__intel_cpu_feature_indicator_x' in /nfs/site/proj/openmp/compilers/intel/17.0/Linux/install/update4/compilers_and_libraries_2017.4.196/linux/compiler/lib/intel64_lin/libirc.a(cpu_feature_disp.o) is referenced by DSO
ld: final link failed: Bad value
make[4]: *** [bin/llvm-ar] Error 1
make[3]: *** [tools/llvm-ar/CMakeFiles/llvm-ar.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [llvm-3.9.1/build_Release/build-compiled] Error 2
make: *** [julia-deps] Error 2
```
Removing `USEICC = 1` makes it go well

**Comment by Keno** [comment]
Looks like this is during the LLVM build, so probably needs to addressed there (unless we're overriding some setting we shouldn't be).

**Comment by cstoudt** [comment]
Same issue.  Intel 2018.1.163 compilers running on Linux Mint 17.3 64-bit.

**Comment by yonisch** [comment]
Same here. I'm using Intel 2017.4.196 compilers on linux mint.

**Comment by UlisesRayon** [comment]
have someone already a solution for this problem?

**Comment by ViralBShah** [comment]
I do not believe this is the highest priority item. Why do you want to build with Intel compilers?

**Comment by anton-malakhov** [comment]
Well, at least, documentation/configuration are misleading as they claim support of ICC and system LLVM while in fact they do not work. I spent time on both just to figure out that it was a waste. If you do not think that you want to support either, just remove/comment out them from public config files with a note that it is not supported yet. It will save time for newbies like myself.

What I really want to get when compile Julia with Parallel Studio are Intel SVML and MKL being used by Julia,

**Comment by ViralBShah** [comment]
I believe they used to work at one point, but because of the nature of the licenses (back then), we never set up CI. I think if someone is willing to invest the time to support the Intel toolchain, and keep it going, it is worth having. Otherwise, I agree that we should remove it from the documentation.

Also, you don't necessarily need to build Julia with Intel compilers to at least use MKL and many of the parallel libraries, but I agree it would be nice to have.

**Comment by ViralBShah** [comment]
The system LLVM is provided for people to test with, or for their convenience when they know what they are doing. Nowhere in the documentation it is recommended that one should use it. In fact, the README clearly states:

```
Using an unpatched or different version of LLVM will result in errors and/or poor performance. Though Julia can be built with newer LLVM versions, support for this should be regarded as experimental and not suitable for packaging.
```
I will remove the mention of the Intel compilers until a time someone gets it working so that it does not misguide people.

**Comment by ViralBShah** [comment]
@anton-malakhov Hopefully the updated documentation in #26432 will avoid pitfalls for new contributors. I also hope someone can bring back Intel compiler support.

**Comment by UlisesRayon** [comment]
Well, the fact here is that I've been trying and trying to install Julia on
my laptop (Dell XPS M1330 Intel duo core, 32-bits) and my OS is Debian.
I'm desperate 'cause my project to obtain my grade must be written in Julia
and my MAC now is dead. For three days I've been trying to build Julia (I
cloned the git) and every time I get error. Someone can help me?

On Mar 12, 2018 3:10 PM, "Viral B. Shah" <notifications@github.com> wrote:

@anton-malakhov <https://github.com/anton-malakhov> Hopefully the updated
documentation in #26432 <https://github.com/JuliaLang/julia/pull/26432>
will avoid pitfalls for new contributors. I also hope someone can bring
back Intel compiler support.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/JuliaLang/julia/issues/23407#issuecomment-372463553>,
or mute the thread

**Comment by Keno** [comment]
You'll probably want to download the generic binaries from: https://julialang.org/downloads/

**Comment by ViralBShah** [comment]
We aren't supporting Intel compilers, but we can bring it back if someone tests them on all the platforms and submits the relevant patches.
