### ISSUE TITLE
Use ctrl-q to 'Pkg.add()' if the previous command was a failed 'using'

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaLang/julia#23463]
```
julia> using SomePkg
ERROR: ArgumentError: Module SomePkg not found in current path.
Run `Pkg.add("SomePkg")` to install the SomePkg package.
```
Most of the time when this happens I actually want to do Pkg.add("SomePkg"), but typing it is annoying. There's an extremely nice way to edit previous stacktraces with ctrl-q, would it be a good thing to generalize to other types of interaction? In this setup ctrl-q would run Pkg.add("SomePkg"), and one could imagine other types of interaction with previous commands.

**Comment by StefanKarpinski** [comment]
The plan in Pkg3 is to prompt for installation if it's not already installed. We're not adding features to the current Pkg in the meantime since only bug fixes will be released.

- design doc: https://github.com/JuliaLang/Juleps/blob/master/Pkg3.md (somewhat outdated)
- wip implementation: https://github.com/StefanKarpinski/Pkg3.jl (see sk/wip branch for latest)
