### ISSUE TITLE
Norm of 0-dimensional array missing

### ISSUE THREAD

**Issue by tribut** [JuliaLang/julia#23566]
Currently, calculating the norm of a 0-dimensional array is not possible:

~~~~julia
a = randn(())
norm(a)
ERROR: MethodError: no method matching norm(::Array{Float64,0})
~~~~

The natural behavior seems to be to calculate `norm(a[1])`.

**Comment by andreasnoack** [comment]
We generally have quite limited support for 0-dimensional arrays. This will be even more visible when automatic broadcasting behavior goes away. To support this generally, we'd need to add a lot of methods. Basically, every possible method defined should then also have a version where each argument type is wrapped in a 0-dimensional array. It is a very inefficient representation of a `Number`. What is your use case?

**Comment by tribut** [comment]
I see. My use case is a function that gets passed a vector and I want a random vector of the same dimension with norm 1, so:
~~~~julia
function foo(x)
  randomdirection = randn(size(x))
  randomdirection /= norm(randomdirection)
  ...
end
~~~~

I can of course use something like `size(x)==() ? randn() : randn(size(x))`, but that feels somewhat clumsy. I can live with it, though.

**Comment by StefanKarpinski** [comment]
I don't see why most generic n-d array implementations wouldn't work for zero-dimensional arrays. Saying that it's annoying to implement is hardly a reason not to fully support zero-dimensional arrays. Even if it's not a great implementation, not supporting them fully prevents generic code that *could* pass through a zero-d structure from working.

**Comment by jw3126** [comment]
Actually in this case it seems that the right function to call is not `norm` but `vecnorm`. The `norm` function only exists for 1d and 2d arrays:
```Julia
julia> arr0 = randn(())
0-dimensional Array{Float64,0}:
-0.9291864460209429

julia> arr3 = randn(1,1,1)
1×1×1 Array{Float64,3}:
[:, :, 1] =
 -0.5906685288681307

julia> norm(arr0)
ERROR: MethodError: no method matching norm(::Array{Float64,0})
  ...

julia> norm(arr3)
ERROR: MethodError: no method matching norm(::Array{Float64,3})
  ...

julia> vecnorm(arr0)
0.9291864460209429

julia> vecnorm(arr3)
0.5906685288681307
```

**Comment by tribut** [comment]
The problem is of course that I do not know whether the argument is an array or a number. Of course I could check, but then I can also just keep my `size(x)==() ? randn() : randn(size(x))` workaround.

**Comment by andreasnoack** [comment]
@StefanKarpinski It is not the n-d array implementations that are causing problems here. The problem is mainly functions defined for `Number`, e.g. `norm` which is not defined for all `N`, only for `Number`  and `N=1,2`. The annoying part is that **all** functions could potentially be expected to work when wrapped in a 0-dimensional array. As mentioned, the most obvious case is probably `Number` where you'd expect `Array{<:Number,0}` to work for anything that `Number` works for. That was why I mentioned broadcasting since `exp`, `sin`, etc. soon will not work for 0-dimensional arrays. However, it would also be an issue for e.g. `String` so whenever you define `split(::String)` you should also define a method `split(::AbstractArray{<:String,0})` since `Array{String,0}` is just a "scalar string". However, this is the case for any type. 0-dimensional arrays are not showing up much though. I think I've encountered this only for some cases where I ended up doing something like `view(A, i, j)`.

**Comment by StefanKarpinski** [comment]
> The annoying part is that all functions could potentially be expected to work when wrapped in a 0-dimensional array.

What? Why? Only functions that work for arrays should work for zero-dimensional arrays. Functions that take arrays and don't have other sensible definitions for scalars can reasonably be extended to scalars the way they work for zero-dimensional arrays. That is a limited amount of functionality.

**Comment by StefanKarpinski** [comment]
Sorry, @andreasnoack, looking back at the original issue, I realize it's in the opposite direction from what I thought it was. I guess we only define `norm` for scalars, vectors and matrices. Since this is an array function, it may make sense to consider scalars and zero-arrays the same, but it's unclear why. If there were a more general array definition and the zero-dimensional case agreed with the scalar case, it might make sense, but absent a more general notion, I'd be reluctant to do this.

**Comment by eveydee** [comment]
If you change it to `randn(size(x)...)` it produces a scalar for scalar `x`, so you won't ever get the 0-d array. If 0-d arrays do and should not behave like scalars, perhaps `randn(())` shouldn't produce a 0-d array?

**Comment by StefanKarpinski** [comment]
Hmm. I feel like `rand(dims...)` and `rand(dims)` should always do the same thing. On the other hand, that is the natural way to ask for a zero-dimensional array, which is sometimes useful. Tough call on what `rand(())` should do.

**Comment by andreasnoack** [comment]
Then rereading this I think that the right solution is actually described in https://github.com/JuliaLang/julia/issues/23566#issuecomment-327008563 since it appears the "vector" here could be of any dimensions. @tribut Please complain here if you disagree and we reopen if necessary.
