### ISSUE TITLE
Enhancement request: working nb_available

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#23591]
I'm afraid I have no code to show on this, but `nb_available` doesn't do what it says. That is, it is apparently entirely dependent on having completed another (blocking) function call in order to update its count; this sort of defeats the purpose of having the function (to use when you want to know whether you've got input or whether you're just going to block until something comes across the line).

Relevant SO thread: https://stackoverflow.com/questions/45756748/check-if-data-on-a-tcpsocket

**Comment by vtjnash** [comment]
dup https://github.com/JuliaLang/julia/issues/8762 (doc issue)

**Comment by sbromberger** [comment]
So, if we're treating this as a documentation issue, is there any way to check to see whether a socket read will block before actually executing the read?

**Comment by vtjnash** [comment]
`@async read(socket, expected_bytes)`

**Comment by sbromberger** [comment]
thanks :)

**Comment by tpapastylianou** [comment]
>  @async read(socket, expected_bytes)

@vtjnash to the extent that this is intended as an answer for this issue when viewed as a 'bug', at least from a user-experience perspective (even if "technically" and "pedantically speaking" this is not a bug in an "under-the-hood" sense), then this is unacceptable as a 'solution', as it consumes the stream as a side-effect, rendering the intent of such a 'check' useless. (also note that `read(socket, 0)` is ineffective in updating the count).

The closest I've come to an acceptable solution to this problem is as per [my answer to this stackoverflow question](https://stackoverflow.com/questions/44969556/how-to-read-from-socket-without-blocking) (complementing that of Seth's). It's still not ideal, since, if used in the context of a script rather than interactively in the REPL, the `@async` call to `eof` may not return by the time the next line is executed (as per some of the discussion also made in the linked 'documentation' issue here), but at least this does not consume the stream, and assuming that this is not part of some highly efficient / parallelised implementation (which presumably wouldn't be a suitable use for such an approach anyway) then it is a minor annoyance at worst, in terms of either having to loop / poll for a few milliseconds until a modest timeout has occured or something along similar lines.

It would be nice if a more reliable equivalent to the `refreshBufSize` call was available and provided by the language though, such that it was guaranteed to have updated `nb_available` by the time it returns (if the stream, for all intents and purposes, isn't blocked), even if this is internally implemented simply as a naive waiting for that async call to either finish or timeout before returning.

**Comment by samoconnor** [comment]
Related to #14624
