### ISSUE TITLE
Modules aren't visible until after __init__ finishes

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#23915]
#23579 changed how modules are loaded. I thought it best to file https://github.com/JuliaLang/julia/pull/23579#issuecomment-331708426 as an issue. The reason turned out to be that #23579 changed behavior of when the module becomes "visible": it used to be that you could refer to the module from outside code that got called via `__init__` or one of the registered `Base.package_callbacks`. Now you have to defer such references until after `__init__` finishes.

Code example at https://github.com/timholy/Revise.jl/pull/48 (only the first commit). This new behavior might be intended, in which case please close this issue.

**Comment by JeffBezanson** [comment]
The change is intentional. In the new way of doing things, top-level modules don't have `Main` as their parent module. Since `Main` is no longer special, assigning `X` to its module after `using X` in Main is the last step (the same as in all other modules).

Looking up a top-level module can be done with `Base.root_module(name)` and replacing one can be done with `Base.register_root_module(name, mod)`.

**Comment by timholy** [comment]
Thanks, now I understand #23579 a bit better. I attributed the timing issue to be separate, but now it makes much more sense.
