### ISSUE TITLE
All titles in Julia’s manual should be identified explicitly

### ISSUE THREAD

**Issue by mnru** [JuliaLang/julia#23951]
Hi,I’m a one of Japanese transrators of Julia’s manual (https://hshindo.github.io/julia-doc-ja-v0.6).
Then I have an proposal for Julia’s English Manual ver 1.0 that every title in the manual should be identified explicitly.
What it means,there are two style for reference of markdown

| Title | Reference |
| :--- | :---- |
| `### title` | `[title](@ref)` |
| `### title(@id title)` | `[title](@ref title)` |

and,their translations are,

| Title | Reference |
| :--- | :---- |
| `### タイトル` | `[タイトル](@ref)` |
| `### タイトル(@id title)` | `[タイトル](@ref title)` |

if all translations were finished,then all links would alive,
but If English and Japanese references are mixed,
above style links are broken,but below links are still alive.
so I think every references should be written in below style.

How about this proposal?

**Comment by nalimilan** [comment]
This sounds like a good idea, but maybe adding IDs only to titles to which there are references would be enough? Adding IDs to *all* titles is going to be painful (especially if we want to avoid ID conflicts).

Would you make a pull request to fix the cases you have found?

**Comment by fredrikekre** [comment]
I don't really understand the issue, presumably if the title is translated the reference ot it should have the same translation?

**Comment by inkydragon** [comment]
The examples given in the issue description are detailed enough. Let me add the scenario in which the issue arises.

When translating documents into other languages, the normal process is to follow the documents one by one. If you do not pay special attention to the links, it is easy to break the internal links in documents. This is especially true when using some tools (e.g.: transifex) and translating paragraph by paragraph.

The proposal for this issue is to manually assign `@id`s to titles that have been linked to, so that internal links are always valid throughout the translation process.

----

Python's documentation use the same anchor text for all languages.
There may be an automated process to do this.

One advantage of this is that when switching languages in a python document, you can still stay in the current section because the anchor text is the same.

e.g.: [5. Data Structures — #list-comprehensions](https://docs.python.org/3.9/tutorial/datastructures.html#list-comprehensions)

----

> use the same names that Documenter would autogenerate

Considering the need to keep existing links unbroken, I may choose not to manually specify the reference id of the title.
Just keep the status quo.

**Comment by vtjnash** [comment]
I don't fully understand that process, since I assumed the translation would have added these `@id`'s to each title as it went along to automatically preserve the link structure, rather than attempting to add them in the source document (which seems harder to keep current). But I'm happy to encourage the process anyways. Closing this simply because the work is in progress, and this issue doesn't seem to specifically track anything.
