### ISSUE TITLE
reverse iteration protocol

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#23972]
As has been mentioned a few times, e.g. in #4590, #6165, and #23969, it would be nice if there were a standard reverse iteration protocol that iterators could support (if possible).   @StefanKarpinski suggested `rstart`, `prev`, and `rdone` as not-terrible possibilities.

You could then do e.g. `for x in Reverse(itr)` and `Reverse` (unlike `reverse`) would implement non-materializing reverse iteration by calling `rstart` etc. on `itr`.

**Comment by Keno** [comment]
Why not just have `Reverse` be a wrapper type and dispatch on `start(::Reverse{...})`.

**Comment by oscardssmith** [comment]
If `Reverse` would it just error on infinite iterators?

**Comment by stevengj** [comment]
@oscardssmith, yes, you'd get an error (probably `MethodError`) for any iterator where reverse iteration is impossible/impractical/unimplemented.

**Comment by malmaud** [comment]
I favor Keno's solution, since it also scales to different kinds of iterator orders. e.g, what if an iterator has efficient support for only iterating the even elements? Do we then need `evenstart` in Base? 

Also, I don't remember the issue, but there is an attempt to remove as many of these 'combinatorial'  (in this case, 'reverse' x 'start, done') function names in Base as possible in favor of relying on dispatch.

**Comment by ararslan** [comment]
If we do this, that would likely simplify some stuff in my `RevString` excision, though we're essentially reintroducing a `RevString`-like type.

**Comment by stevengj** [comment]
@ararslan, not quite, because `Reverse` will be a subtype of `Any`.
