### ISSUE TITLE
Possible regression in printing of getfield with anonymous functions

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#24059]
I'm not sure this should be counted as a regression but the output of the following:

```
julia> f = y -> y + a
#1 (generic function with 1 method)

julia> f(3)
ERROR: UndefVarError: a not defined
Stacktrace:
 [1] (::getfield(Main, Symbol("##1#2")))(::Int64) at ./REPL[6]:1
```

looks quite a bit uglier than on 0.6:

```
Stacktrace:
 [1] (::##1#2)(::Int64) at ./REPL[1]:1
```

**Comment by nalimilan** [comment]
Unfortunately, https://github.com/JuliaLang/julia/pull/23806 doesn't change this since I haven't change the printing of functions, assuming they are less frequently printed, and that when they are printed, their parent module is an important information. We could change that, either for all functions, or only for anonymous functions. We could also just improve the way the parent module is printed for anonymous functions.

**Comment by JeffBezanson** [comment]
This is (obviously?) intentional --- the new output gives you something you can copy & paste to refer to the function type. As long as there is going to be an ugly internal name `##1#2` anyway, we might as well give you something *useful* as well as ugly.

**Comment by KristofferC** [comment]
Alright then.

**Comment by StefanKarpinski** [comment]
Just to clarify, this works:
```jl
julia> f isa getfield(Main, Symbol("##1#2"))
true
```
