### ISSUE TITLE
POSIX cygwin build of Julia

### ISSUE THREAD

**Issue by devel-chm** [JuliaLang/julia#24128]
Per discussion in issue #23953 there is currently no build support for a native cygwin version of Julia.  I would like to request this be added as a new feature.  For users needing to use or required to use the cygwin environment, a version of Julia *would* be the fastest possible implementation and it would be interoperable with the existing cygwin packages including python, matplotlib, numerous computational and algorithmic libraries...  The fact that the posix layer is needed to support IO and systems type operation that might be slower than native windows OS features doesn't mean that the computation would not be as fast as possible.

**Comment by digital-carver** [comment]
In addition to the interoperability issues mentioned (which I haven't tried), there's filesystem issues since Julia doesn't understand or use the Cygwin filesystem. There's a minor issue that inside Julia you have to switch to using Windows-style paths (instead of the `/cygdrive/` type paths we're used to under Cygwin). This applies in the `;` REPL mode too, which breaks the "shell mode" illusion. 

But the more bothersome issue I've come across is that Julia doesn't understand Cygwin-created symbolic links. It tries to read the link file itself and errors out. I got weird GitConfig error messages running `Pkg.add` (or `add` in `Pkg3`) commands for eg., which puzzled me until I remembered my `.gitconfig` file is a symlink (to a `dotfiles/` folder), and Julia was reading the symlink file itself (instead of following the link). So I now open PowerShell for running those `Pkg` related commands alone.
