### ISSUE TITLE
lu(A, Val{false}) should be lu(A, pivot=false)

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#24144]
I use the unpivoted `lu` function a lot in teaching linear algebra, because its results are more easily compared to hand calculations (where you rarely permute rows), and it is continually annoying to me that you do this by passing `Val{false}` as the second argument — I feel like I'm exposing an ugly internal.   Can't we changed this to a `pivot=false` keyword?

LU factorization is a fairly expensive operation, so I am mystified by why we would care about dispatch performance here.  Surely the cost of a runtime branch is negligible?

cc @andreasnoack

**Comment by andreasnoack** [comment]
It's for consistency with the other factorizations that support pivoting (Cholesky and QR) because they have special types and we, therefore, need compile time dispatch for type stability in those cases. I don't like `Val`s but I wouldn't like different kinds of pivoting arguments for different factorizations. I'd be happy find a prettier alternative as long as it is consistent across factorizations and doesn't sacrifice type stability.

**Comment by stevengj** [comment]
Maybe define a singleton type?   e.g. `lu(A, LinAlg.NOPIVOT)`?

**Comment by oscardssmith** [comment]
I have no idea if this is feasible, but would it be possible to combine keyword arguments and `Val`s, to make it be `pivot = Val{false}`? Alternatively, is there any reason Val is needed for dispatch on the caller side? It feels like the caller should just pass false, and then internals should be able to figure out if there are multiple methods depending on the value passed in.

**Comment by stevengj** [comment]
@oscardssmith, the whole difficulty here is that checking the *values* can only be done at runtime, not a compile time.  This is too late for type-stability if the return type depends on whether `pivot == true`.

**Comment by Sacha0** [comment]
(Closely related to #24011.)

**Comment by andreasnoack** [comment]
Ref: https://github.com/JuliaLang/julia/pull/22232

**Comment by ChrisRackauckas** [comment]
Since 1.0 will have https://github.com/JuliaLang/julia/pull/24362 , we should consider getting rid of the value-type dispatching here and simplifying the API to `true/false` which can be type-stable on literal arguments when/if it's propagated. This would be a breaking API change, so it would have to be 1.0?

**Comment by martinholters** [comment]
> This would be a breaking API change, so it would have to be 1.0?

We could still allow a `Val` to be passed, to make the change non-breaking.

**Comment by alanedelman** [comment]
I hate LU(A,Val{False})  :-(
