### ISSUE TITLE
add tuple_type to the Tuple manipulation API

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#24312]
We have `tuple_type_head` and `tuple_type_tail`, but it would be nice to have something that is just equivalent to
```julia
tuple_type(T) = (tuple_type_head(T), tuple_type_tail(T)...)
```
Currently one needs to extract `T.parameters`, convert from the `svec`, deal with `Vararg` tuples manually, etc.

**Comment by JeffBezanson** [comment]
Why is there a need to convert from `svec`? I also don't see how this would eliminate the need to handle `Vararg` tuples.

**Comment by tpapp** [comment]
For type calculations, it would be useful to have an interface which extracts `(Int, Float64, Char)` from `Tuple{Int, Float64, Char}`. Using `.parameters` always feels like I am using an internal interface.

You are right, `Vararg` is an orthogonal issue.

**Comment by cstjean** [comment]
+1. By analogy with `fieldname/fieldnames` and `fieldtype`, it could be called `fieldtypes`.

**Comment by tpapp** [comment]
```julia
fieldtypes(T::Type{<: Tuple}) = ntuple(i -> fieldtype(T, i), nfields(T))
```
does what I want.

But I am still wondering why there is no API for this: is it something I am not supposed to do, and use some kind of lispy recursion instead with the existing head/tail API?

**Comment by vtjnash** [comment]
Should be `countfields` not `nfields`, since the number may not be a known (might be Vararg), and so this might fail. But as a definition, that seems to me like a more sound definition than `tuple_type_head` / `tuple_type_tail` / `tuple_type_cons`. At lot of these usages seem to have been designed before the type system was able to express and handle many subtyping questions. c.f. https://github.com/JuliaLang/julia/issues/22051
