### ISSUE TITLE
Pkg.update fails to read index file

### ISSUE THREAD

**Issue by jhlq** [JuliaLang/julia#24369]
Hello! Was about to tag Equations for 0.5 when this happened:
```
julia> Pkg.add("PkgDev")
INFO: Updating cache of JSON...
INFO: Cloning cache of PkgDev from https://github.com/JuliaLang/PkgDev.jl.git
INFO: Updating cache of URIParser...
ERROR: GitError(Code:ERROR, Class:Invalid, Malformed remote 'origin' - missing URL)

julia> Pkg.update()
INFO: Updating METADATA...
ERROR: METADATA cannot be updated. Resolve problems manually in /home/quin/.julia/v0.5/METADATA.
GitError(Code:ERROR, Class:Index, Failed to read index: '/home/quin/.julia/v0.5/METADATA/.git/index' no longer exists)
```
The index file does exist in the specified location although it is empty. Am running a fresh install of 0.5.2 from the official Ubuntu repos, Pkg.update worked previously and other packages can still be installed. 

Thanks

**Comment by shorty66** [comment]
0.5.2 is an old version of julia. Latest stable is 0.6.1.

It is strongly recommended that the official generic linux binaries from the downloads page be used to install Julia.
You can download them [here](https://julialang.org/downloads/).

> Linux Distribution-Specific Packages
> 
> The following distribution-specific packages are community contributed. They may not use the right versions of Julia dependencies or include important patches that the official binaries ship with. In general, bug reports will only be accepted if they are reproducible on the generic linux binaries on the downloads page.

**Comment by jhlq** [comment]
Now I know Julia is in a hectic phase of development but maybe time should still be allocated to keep versions officially provided by major Linux distributions functional, the download page does state bug fixes are provided for 0.5. 

It is a major difference when recruiting new users to say "run this familiar terminal command" compared to "download a binary from that website".

**Comment by StefanKarpinski** [comment]
Having working Julia versions on major distros would be great. For the most part, the fact that we can't do that has to do with distros having fairly rigid rules about library sharing. In order for Julia to function correctly, we need many dependencies configured in certain ways or they will be broken. For example, we regularly find and patch bugs in LLVM – it's been a long time since we've been able to use an unpatched LLVM. Many distros insist that we use whatever their current LLVM version is, without patches. The same is true to a lesser extent with other key dependencies as well.

**Comment by jhlq** [comment]
Hmm, yea, human rigidity is a hard solved problem

**Comment by simonbyrne** [comment]
This has changed considerably with the new Pkg. If still an issue, please open at https://github.com/JuliaLang/Pkg.jl
