### ISSUE TITLE
Return Variable Not defined

### ISSUE THREAD

**Issue by MFaisalZaki** [JuliaLang/julia#24619]
I have this function which produces undefined variable error when calling it multiple times.
[function.txt](https://github.com/JuliaLang/julia/files/1475689/function.txt)
<img width="1071" alt="screen shot 2017-11-15 at 7 26 29 pm" src="https://user-images.githubusercontent.com/9129265/32850549-273338f6-ca3b-11e7-9e11-538c17758cc4.png">

**Comment by vtjnash** [comment]
Do you know for certain that `size(ob.path, 1) > 0`? (otherwise, an UndefVError there would be expected)

**Comment by yuyichao** [comment]
As I said last time, please provide complete context when reporting an issue. If you are not sure, asking on discourse first is a much better way to get started. Since there is obvious control flow that should give under var error I'll close as expected. Feel free to ask on discourse for further questions as mentioned above
