### ISSUE TITLE
Different type returned for `position` between IOBuffer` and `IOStream` on 32bit

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#24650]
```
julia> typeof(position(IOBuffer()))
Int64

julia> typeof(position(IOStream("")))
Int32
```

Should https://github.com/JuliaLang/julia/blob/6e4f2fa226f931b9e2691672a68855a0996ab986/base/iostream.jl#L110 be converted to `Int`?

**Comment by vtjnash** [comment]
No, this is always a 64-bit number.

**Comment by KristofferC** [comment]
To clarify, it is intended that different IO give different types as their position?

**Comment by stevengj** [comment]
I don't see the problem having the type of `position(io)` depend on the type of `io`.

I'm confused by @KristofferC's post, above, though, since

* `position(::IOBuffer)` is an index in memory, and hence `Int` is appropriate (`Int32` on a 32-bit machine)
* `position(::IOStream)` is a position in a file, hence `Int64` is appropriate.

Did you copy the types backward in your post?

**Comment by KristofferC** [comment]
Yes,  I copied it backwards... I think this will be a source of bugs where people test their functions on IOBuffer using `::Int` for the position argument which then fails on `IOStream` (e.g. https://github.com/wildart/TOML.jl/pull/6).

If this is intended then ok.
