### ISSUE TITLE
define `similar(::Number)`

### ISSUE THREAD

**Issue by gasagna** [JuliaLang/julia#24690]
In `Base`, `copy` and `deepcopy` methods are provided for number types but not for `similar`. Having this would be useful to have more generic code.

Would it be too breaking to define
```julia
similar(x::Number) = x
```
?

**Comment by stevengj** [comment]
`similar` is defined to return a mutable array, which your proposed definition would break.

**Comment by gasagna** [comment]
My understanding is that `similar` returns an object similar to its input (up to modifiers), regardless of mutability (for instance, the [docs](https://docs.julialang.org/en/stable/devdocs/offset-arrays/#Writing-custom-array-types-with-non-1-indexing-1) suggest to overload `similar` for types with custom indexing.

**Comment by stevengj** [comment]
No, the [`similar documentation](https://docs.julialang.org/en/stable/stdlib/arrays/#Base.similar-Tuple{AbstractArray}) explicitly states that the result is mutable.

That's why `similar(1:5)` returns an `Array{Int64,1}`, for example.

Various places in the standard library call [`Base.copymutable`](similar(1:5)) to get a mutable copy of an array, which calls `copy!(similar(a), a)` precisely because `similar` always returns a mutable type.

**Comment by stevengj** [comment]
If you want a new object of the same type that may be uninitialized, doesn't it pretty much have to be mutable?  Otherwise how would you use it?

For example, how would you use your proposed `similar(x::Number)` in generic code?

**Comment by laborg** [comment]
I'll close this issue:
 - @gasagna hasn't answered the last question
 -  this issue hasn't been updated for 6 years 
 -  it isn't actually clear whats the purpose of this change
