### ISSUE TITLE
Rename pwd() to cwd()

### ISSUE THREAD

**Issue by pfitzseb** [JuliaLang/julia#24815]
`pwd()` doesn't actually *print* the working directory, it returns it:
```
julia> a = pwd();

julia> a
"U:\\"
```

**Comment by pfitzseb** [comment]
This isn't a doc issue per se, since the docs are correct:
```
help?> pwd
search: pwd powermod print_with_color

  pwd() -> AbstractString

  Get the current working directory.
```
It's just unfortunate that the function is named "**print** working directory", instead of `cwd`'s "**current** working directory".

**Comment by oxinabox** [comment]
### `pwd`
 - Matlab
 - Ruby

### cwd
 - Python 
 - Perl

### Something else
 - Rust `current_dir`
 - R `getwd`

**Comment by StefanKarpinski** [comment]
This function was previously named `cwd` and was renamed as part of a [large file API rename](https://github.com/JuliaLang/julia/issues/1782). The name `pwd` was chosen because there's not a broad consensus on what to call this function (`cwd`, `pwd`, `getwd`, `getcwd`). Before that the same function [was called `getcwd`](https://github.com/JuliaLang/julia/commit/9bb5bdc53b368484533964c58090d8135ac6335b). Empirically, so far the name `pwd` seems to have generated the least confusion and complaints. It matches Ruby and Matlab which are the single largest agreeing set of languages for this function in the spreadsheet linked.

**Comment by StefanKarpinski** [comment]
I would add all UNIX shells to the `pwd` set in the above. Technically the shell prints the working directory, but that's how the shell returns things. In general, we have tried to follow the same naming as UNIX shells for file and path operations since that's the interface that by far the largest number of people are familiar with.

**Comment by oxinabox** [comment]
Ok, I am satisfied that it was well considered.
I'm just going to have to say to myself Present Working Directory
 10 times and get over it

**Comment by jiahao** [comment]
Consider that the POSIX standard is itself inconsistent in this way: it defines

1. The PWD environment variable which "shall represent an absolute pathname of the current working directory" [Reference](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html), and

2. The `pwd` utility, which "shall write to standard output an absolute pathname of the current working directory". [Reference](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/pwd.html)

**Comment by bramtayl** [comment]
I like current_dir from rust

**Comment by KristofferC** [comment]
Looks like we are happy with `pwd`
