### ISSUE TITLE
in-place assignment operator?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#249]
Examples:

- `sort!`
- `conj!`
- `transpose!` — interesting question: is the operator version `.'!`?
- `ctranspose!` — likewise: is the operator version `'!`?

Please add others as you think of them. Obviously, they need to be operations that cannot change the type of the array. @ViralBShah: are there in-place FFTW operations that we should expose?

**Comment by ViralBShah** [comment]
I think that with various packages addressing this, and the various `!` methods in Base, we can close this issue.

**Comment by kmsquire** [comment]
A little disappointed.  I kinda like Jeff's `:=` proposal (although I vaguely recall problems with it discussed in other issues?)

**Comment by JeffBezanson** [comment]
There are probably issues more worthy of closing than this one. `!` methods are not very satisfactory, and I think it's likely we should try to do something lower level about in-place-ness.

**Comment by StefanKarpinski** [comment]
Agree on keeping this open. Still prefer `.=` to `:=`.

**Comment by ViralBShah** [comment]
I guess this issue started with the `!` methods but then moved on to operators. Would be nice to have a separate issue - but perhaps it is simpler to just leave this open.

**Comment by ViralBShah** [comment]
With `.` operators meaning element-wise / broadcast operations, it seems like overloading the syntax too much to also include in-place operations.

**Comment by StefanKarpinski** [comment]
That's the point – it's an elementwise assignment.

**Comment by kmsquire** [comment]
I'm okay with `.=` as well. :-)

**Comment by Glen-O** [comment]
I may be the only one, but I feel like "`A+=B`" should inherently be in-place. That's why you'd use it over `A=A+B` - at least, until I'd recently learned about a speed issue with `.*=`, I didn't realise that it didn't default to in-place where possible.

I'm not sure I like `.=` in concept, because it feels like you should then be able to type `A+.=B` to perform matrix addition in-place, with elementwise addition being `A.+.=B`... but then it becomes confusing, with `+=`, `+.=`, `.+=`, and `.+.=`. I can see the argument for the dot meaning "elementwise", but it seems like it's a little weird as a notation.

As an alternative, how about a special notation, something like `=<`, to say "assign in place", with the operation failing and throwing an error if it the allocated space doesn't match or the variable is of an immutable type? Then all of the usual operators feel "normal" attached to it - `A+=<B` means "take A, and add B to it in place", for instance.

Not only does this make mutation more explicit, but provides a neat way to tell if there's a mistake in the code. And then `.=` could be used for actual elementwise assignment - that is, `A.=1` would construct a matrix similar to A filled with 1 (basically, `A=fill(1,size(A))`), and then `A.=<1` would be `fill!(A,1)`. And if `A` were 2x2, and you wrote `A.=[1 2]`, then you would get `A==[1 2;1 2]`, because elementwise operations broadcast.

I'd also like to support what @jiahao said about the performance hit with non-in-place operations. I found the GeneticAlgorithms package insufficient for my need, so I wrote my own GA code... and when I went through and pre-allocated all my arrays and then mutated them instead of just assigning new arrays to the same variable, it had a massive impact. Easily more than 10x speedup. But it became a bit messy because I had to explicitly go through and do a heap of switching to forms like `A[:]=B[:]` (not actually from the code). The ability to write this as `A=<B` would make this so much easier.

Incidentally, why *are* numbers immutable? Is there some performance or design issue with re-using the memory that a number variable is stored in? I'm not suggesting they should be mutable, just wanting to understand the reasoning.

**Comment by StefanKarpinski** [comment]
Think about what it would mean if you could change the value of a number.

**Comment by lucasb-eyer** [comment]
I also expected `+=` to be in-place and got bitten by it not being so. It's not just about performance, it introduced an actual bug in my code.

But if  `+=` did different things for scalars than for arrays, it'd become useless in generic code.

I think at the very least, this should be made much more explicit in the documentation, especially given that `+=` *is* in-place in numpy. The note on [this page](http://docs.julialang.org/en/release-0.3/manual/mathematical-operations/) was the only reference I found in the docs, and it's very implicit about the implications.

**Comment by KristofferC** [comment]
Doesn't this part make it clear?

`An updating operator rebinds the variable on the left-hand side.`

**Comment by Glen-O** [comment]
@StefanKarpinski - If you're answering the "why are they immutable" question, I should make more clear that I mean variables that are number types, not actual numbers. Is there a benefit to always rebinding numerical variables instead of updating them in-place?

**Comment by lucasb-eyer** [comment]
@KristofferC Technically, yes. Practically, it wasn't enough to let "`A = ones(4); B = A; B += 3` doesn't change values in `A`" sink in - for me, anyways. This is a big difference to Numpy, but also typical C++ matrix classes. Maybe adding this as a point to the [Noteworthy differences to Python](http://docs.julialang.org/en/release-0.3/manual/noteworthy-differences/#noteworthy-differences-from-python) might help mitigate this a bit.

**Comment by jiahao** [comment]
@lucasb-eyer the difference from Python is worth documenting, if you'd like to submit a PR

**Comment by johnmyleswhite** [comment]
> Is there a benefit to always rebinding numerical variables instead of updating them in-place?

@Glen-O: The fact that number r-values are immutable *is the primary reason* why you can optimize code that involves scalar computations. If that's unclear to you, you might benefit from learning more about how Julia's compiler generates machine code. Make sure you understand (1) what l-values and r-values are, (2) what stack and heap allocation are, and (3) how immutability and stack allocation are related.

**Comment by StefanKarpinski** [comment]
Bindings to numbers aren't immutable or rather const unless you declare them to be, so I'm kind of unclear on what you mean, @Glen-O.

**Comment by lucasb-eyer** [comment]
@jiahao Glad you agree, I'll prepare a PR in a few days, got a talk to prepare first :fearful:

**Comment by Glen-O** [comment]
@StefanKarpinski - I'm not referring to the bindings, but what you're binding to. Please note that I'm a mathematician, not a computer scientist. What I'm trying to understand is, in what way is it better to keep re-binding a numeric variable to a new location in order to give it a new value, rather than changing the value in-place? If you have `a=1`, and you want to increment `a` to equal 2, why is it better to create a new value of 2 in a new section of memory and then point `a` at it, rather than simply changing the value in the bit of memory that currently holds the value 1 so that it now holds the value 2? Note that I'm not specifically referring to function calls, but generally. If I run `a=1;@time for i=1:1000000 a=a+1;end` (on 0.3), it tells me that `15991840 bytes allocated`. And if I run it a few times over, it has to run gc.

I do realise that it will do much better inside a function, but I just can't see why it should ever need to allocate so much for what amounts to incrementing a value. I was hoping for a quick, lay explanation since there is clearly some reason why it was chosen to do it like that.

Mind you, it's just a sidebar, anyway - I'm far more interested in whether or not my suggestion of a dedicated "in-place assignment" operator, separate from elementwise considerations and only usable on mutable objects with constant footprint (assigning a 5x4 integer array to a variable that currently holds a 5x4 integer array, for instance - possibly also working if it's a 20x1 integer array?), is of interest.

**Comment by nalimilan** [comment]
@Glen-O This is completely unrelated to the issue at stake. The allocation happens because in the global scope a might change type during the loop (e.g. it might become an array). Always run benchmarks inside functions, as the FAQ explains.

**Comment by Glen-O** [comment]
@nalimilan - let me try asking a different way, since I think you got caught on the specific example, which I used to demonstrate that it's rebinding even though it clearly wasn't going to change type. So here's how I'll ask it - is there a reason why the "in place assignment operator" as I suggested above shouldn't be able to assign to an Int variable in-place if you're trying to give it a new Int value (that is, why shouldn't it be mutable when it remains the same type)?

Alternatively, if it's because it can't be certain that the type will remain the same, then why doesn't this fix it? `a=0;@time for i=1:1000000 a::Int=(a+1)::Int;end`. Now it has specifically been told that `a` and `a+1` are both Int type, so it should be able to safely mutate, right?

Incidentally, if this discussion should end here (I can understand if you wish to focus on the specifics of the in-place assignment operator considerations, rather than this particular detail of in-place vs immutable), I'm happy to move it to julia-users - just say the word.

**Comment by hayd** [comment]
> Now it has specifically been told that a and a+1 are both Int type, so it should be able to safely mutate, right?

Which is exactly what **the compiler** does in the function scope (but Ints are never going to be mutable in julia itself.) This would make a good Stack Overflow/julia-users question, but as mentioned above it's off topic for this issue.

**Comment by ihnorton** [comment]
>  if this discussion should end here

Yes. It is *really great* to have people trying to understand the why of these design decisions, but GitHub can't effectively facilitate those discussions or archive them usefully and searchably. Questions like this are perfect for the StackOverflow model because the answers are timeless (and relevant beyond Julia). Thanks!

**Comment by NHDaly** [comment]
The biggest thing to me is that Arrays are supposed to be mutable containers of possibly immutable values. So it feels like an element-wise operation should *mutate* the container, since you are only touching the elements.

A clarifying example:

It seems wrong that these two do different things:
``` julia
julia> x = [ 1 1 1 ]
julia> y = x        # setup x === y

julia> for i in 1:length(x)
         x[i] += 1  # x still === y
       end
julia> println("$x : $y")
[2 2 2] : [2 2 2]

julia> x .+= 1      # x now !== y
julia> println("$x : $y")
[3 3 3] : [2 2 2]
```

Because `.+=` promises to be element-wise, it really feels like it should behave the same as `x[i] += ` for each element.

As I was coding, I made the mistake of using `+= 1`, expecting it to update in-place like numpy. When it didn't I realized, oh I guess that makes sense -- it's modifying the whole Array. So I switched to `.+= 1` expecting that to fix the problem and was really surprised when it didn't.

**Comment by NHDaly** [comment]
Also this is pretty upsetting. It makes sense now that I've read this whole thread, but still pretty freaky:

``` julia
julia> tup = Any[[1 1 1], [2 2 2]]
julia> tup[1] .*= 0     # 1. Modifies tup.
julia> z = tup[2]       #    z === tup[2]
julia> z[1] *= 0        # 2. Modifies tup.
julia> z .*= 0          # 3. Doesn't modify tup.
julia> println(tup)
Any[
[0 0 0],
[0 2 2]]
```

`1.` and `3.` seem so similar: you are updating a matrix element-wise. It's confusing that only `1.` modifies the matrix in-place, especially given that `z` is just another name for `tup[2]`.

`2.` and `3.` seem similar too, (like my previous post) `3.` seems just to be a loop across all the elements, and it feels like it should do the same thing as `2.` applied to each element.

**Comment by vtjnash** [comment]
> especially given that z is just another name for tup[2]

this may be pedantic, but this is not really a correct statement. this sentence says that `z => tup[2] => #obj#`. but in actuality, the correct statement would be that "z and tup[2] were both names for the same object", or:
````
z         =>  #ob#
tup[2]  ====^ 
```
this also explains why changes to tup[2] or z have no impact on the other, while changes to the contents referenced by these names (denotated `#obj#`) are visible, regardless of the name used to reference `#obj#`

**Comment by StefanKarpinski** [comment]
@NHDaly, you're interpreting `x .+= y` as `x .(+=) y` whereas it means `x (.+)= y` i.e. `x = x .+ y`.

**Comment by NHDaly** [comment]
I see... To be honest that is terribly unclear. I think the language would
be better off if we simply removed these operators rather than have them
operate as they do now. It is not clear at all from context how they
behave. I think that is too subtle a distinction, and doesn't save much
typing.

I'm excited to see how this turns out! :)

**Comment by 315234** [comment]
This immutable/mutable stuff is just way too subtle a distinction for most people. It is not intuitive that `+=` and friends, especially operating on arrays, will create an entirely new object and destroy the old one. It is counterintuitive that doing an operation element-wise on an array (`a[:] .*= a`) has a different effect of using array expressions (`a *= a`). In a numerical language where performance is supposed to be a focus, it is almost never anyone's intention to implicitly allocate a new block of memory and throw out the old one. The end result is that Julia has array expressions but you basically can't use them without sacrificing performance.

**Comment by carnaval** [comment]
```julia
y = a
[...]
x = a
[...]
x += 1
[...]
print(y)
```
```julia
y = a
[...]
x = a
[...]
x = x+1
[...]
print(y)
```

I don't think that having those two pieces of code have different answers is at all intuitive

**Comment by StefanKarpinski** [comment]
This doesn't warrant any further discussion at this point and the mutable vs immutable distinction is completely orthogonal – the mutability of a type has no effect on the meaning of operations on it.

**Comment by JaredCrean2** [comment]
Is this a definitive decision against including an in-place assignment operator in the language? It seems like the original question got lost in the mutable vs immutable discussion.

**Comment by johnmyleswhite** [comment]
I don't think anyone has a credible proposal for what such an operator would do. Everyone agrees the situation could be improved, but no seems to know how to do it.

**Comment by JaredCrean2** [comment]
Then shouldn't the issue be left open until someone figures it out?  If the issue is closed, there is a chance no one will revisit it in the future.

**Comment by johnmyleswhite** [comment]
People can reasonably disagree about that point, but I personally think that's not an accurate assessment of how work gets done by most of the Julia developers. I prefer the open issues to be clearly actionable. But you don't need an issue to be free to work on something.

**Comment by JaredCrean2** [comment]
I guess that's reasonable.  I definitely don't want this issue to be forgotten because it would make a big difference in much of the code I write.

**Comment by StefanKarpinski** [comment]
This particular issue has gotten too long and muddle at this point. It was also originally about adding more in-place operations, which we now have lots of. The issue of in-place operation will not be forgotten, I can assure you.

**Comment by stevengj** [comment]
Fixed by #17510, although we won't get the full power of fusing in-place assignment until `.+` etcetera turn into fusing calls ala #16285.

**Comment by NHDaly** [comment]
Fascinating. Thanks for the update!

**Comment by bramtayl** [comment]
It might be useful for
`f!(args...)`
be parsed to
`inplace(x, f, args...)``
and we could talk advantage of new closure types to do:
`inplace(x, f::typeof(reduce), args...) = f_in_place(x, args...)`
where f_in_place is an internally defined in place operator.

**Comment by KristofferC** [comment]
What's the gain?

**Comment by bramtayl** [comment]
Yes, I do think you need to define both anyway. But having ! exposed to the parser would allow it to hook into any forthcoming more general loop fusion syntax (see #16285)

**Comment by KristofferC** [comment]
```
julia> const a = randn(4);

julia> @allocated a .+= 2
0
```

Maybe reading the very first section of the [performance tips](https://docs.julialang.org/en/v1/manual/performance-tips/) is too much to ask?

**Comment by GiggleLiu** [comment]
@KristofferC 
So sorry for posing such stupid benchmark. In fact, the real problem does not have such `const` concern

(I am trying to improve the performance of SparseMatrixCSC * Diagonal, which is super slow in current version of Julia)

```
using SparseArrays
using LinearAlgebra
import LinearAlgebra:rmul!, mul!, lmul!
import Base: *

function rmul!(X::SparseMatrixCSC, A::Diagonal)
    nA = size(A, 1)
    mX, nX = size(X)
    nX == nA || throw(DimensionMismatch())
    @inbounds for j = 1:nA
        X.nzval[X.colptr[j]:X.colptr[j+1]-1] .*= A.diag[j]
    end
    X
end

using BenchmarkTools
const N = 1000
const dg = Diagonal(randn(ComplexF64, 1000))
const sp = SparseMatrixCSC(dg)
@benchmark rmul!(sp, dg)
```

It has 1000 allocations, although using `code_warntype`, I will see the type is stable, however, writing the loop explicitly out, I will get 10x speed up and 0 allocation!

Could you please explain it? (I promise I have already read the performance tips many times, lol)

**Comment by StefanKarpinski** [comment]
That seems worth opening a separate specific issue about, no?

**Comment by mbauman** [comment]
This is an example of a place where call-site inlining is essential.  It felt a little wrong to always inline `copyto!` — that's where the function break is here IIRC.
