### ISSUE TITLE
Depwarns at global scope have incorrect caller

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#25130]
This will make it quite hard to identify where deprecations come from:

```julia
julia> Array(Int, 1)
W- `Array(::Type{T}, m::Int) where T` is deprecated, use `Array{T}(uninitialized, m)` instead. -Warn:Core:julia_internal.h:380
|  caller = jl_call_fptr_internal at julia_internal.h:380 [inlined]
1-element Array{Int64,1}:
 139639004667120
```

**Comment by c42f** [comment]
I think this is more a stack sanitization issue for stack frames coming from the REPL.

In normal functions, `caller` should point to the offending calling frame rather than the whole stack trace. I thought this would be much more precise and useful than spamming the user with the whole stack trace:

```julia
julia> foo() = Array(Int,1)
foo (generic function with 2 methods)

julia> foo()
W- `Array(::Type{T}, m::Int) where T` is deprecated, use `Array{T}(uninitialized, m)` instead. -Warn:Main:REPL[2]:1
|  caller = foo() at REPL[2]:1
1-element Array{Int64,1}:
 -1
```

**Comment by c42f** [comment]
An alternative to simply attaching `caller` would be to attach the whole backtrace, but somehow have a way to highlight the offending frame.

As a bit of extra context for what I've been thinking here for future functionality - the `caller` is attached partly to make a `depwarn report` possible: the idea is that you can run a big chunk of code, collect all the depwarn log events, put them into a table and filter/group/sort them by the source location which needs to change in order to silence the depwarns.  Combined with source rewriting via `Deprecations.jl`, it should even be possible to automatically rewrite the source for a good class of deprecations.

**Comment by nalimilan** [comment]
Maybe we just need a special case for calls done in the global scope?

**Comment by c42f** [comment]
Oh, I see - this issue is worse than I thought as it applies to all code at global scope, not just the REPL.

Would you mind changing the title to something like "Depwarns at global scope have incorrect caller"

I'm sure this can be fixed.  Possibly with a special case but I'll need to dig.

**Comment by stevengj** [comment]
It's not just global scope:
```
julia> f() = warn("foo")
f (generic function with 1 method)

julia> f()
W- `warn()` is deprecated, use `@warn` instead. -Warn:Core:julia_internal.h:380
|  caller = jl_call_fptr_internal at julia_internal.h:380 [inlined]
WARNING: foo
```

**Comment by c42f** [comment]
Yep, this is serious.  I think I have a simple fix, just figuring out how to test it.
