### ISSUE TITLE
julia 0.6 on windows @edit opening editor errors

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/julia#25251]
`@edit` didn't open at the corresponding line since open (default editor) doesn't support that.
thus i switched to `ENV["JULIA_EDITOR"] = "atom"` in `.juliarc.jl`.
Now i get the following errors on using the edit macro:
```julia
ERROR: could not spawn `atom 'C:\Users\necka\.julia\v0.6\Genie\src\Router.jl:186'`: no such file or directory (ENOENT)
```
when placing that in the execute window (win+r) it won't open the file but only atom itself. Once i replace `' '` with `" "` in the execute window, atom opens the file properly.

**Comment by GregPlowman** [comment]
You could try specifying the full path name to the atom executable.
In this case you'll need to enclose in escaped quotes `\"` 
``` 
ENV["JULIA_EDITOR"] = "\"C:\\Users\\Greg\\AppData\\Local\\atom\\atom.exe\""
```
Can check this is set correctly with `Base.editor()`:
```
Julia-0.6.2> Base.editor()
1-element Array{String,1}:
 "C:\\Users\\Greg\\AppData\\Local\\atom\\atom.exe"
```

I think the reason is that `JULIA_EDITOR` represents a `command` and not just a simple path.

This could be better documented.

**Comment by jebej** [comment]
In case someone stumbles on this, on Windows, the correct variable is (assuming that `atom.cmd` is on the path, which it should be by default):
```
ENV["JULIA_EDITOR"] = "atom.cmd -a"
```
