### ISSUE TITLE
`Base.summarysize` ambigious and inconsistent with `SharedArrays`

### ISSUE THREAD

**Issue by mohamed82008** [JuliaLang/julia#25367]
The following shows an unexpected behavior of `Base.summarysize` when used on a `SharedArray` on Windows with nightly. The issue first came up in [discourse](https://discourse.julialang.org/t/size-of-multi-dimensional-sharedarray/8099/9) with more tests there showing inconsistent results with different Julia versions and operating systems. If this is not surprising, perhaps documenting the behavior of the function would be useful.

```julia
julia> versioninfo()
Julia Version 0.7.0-DEV.3232
Commit 6729e4f00c* (2018-01-02 00:25 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)

julia> using SharedArrays

julia> Base.summarysize(SharedArray{Float64}(rand(1000_000)))
8000197

julia> Base.summarysize(SharedArray{Float64}(rand(1000_000,2)))
32000205
```

**Comment by StefanKarpinski** [comment]
We should probably officially document that we may need to change the algorithm for `summarysize` and that it should currently only be used for interactive usage. It's already technically non-public since it's not exported from Base, so perhaps that's sufficient. Having a way of counting the memory reachable by various objects would be useful, even if it has to be done in a way that's as expensive as doing a full garbage collection.

**Comment by mohamed82008** [comment]
Great, thanks!
