### ISSUE TITLE
Do not export promote_rule

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#25439]
Should we stop exporting `promote_rule`? Functions which only need to be overridden when implementing types are generally not exported (e.g. `Base.IndexStyle`). That would make it clearer that it should never be called directly.

**Comment by StefanKarpinski** [comment]
The unfortunate thing is that we have no way of expressing that something is public but not meant to be called directly. Short of wrapping everything in Base in an inner `Base.Implementation` module, as has been suggested to work around this problem. I still find it questionable that we recommend as solution for packages what we are not willing to do ourselves in Base. Still, that's a feature and can be worked out on the future and we have a somewhat more complex notion of "public" than other languages since there's "public to call" and "public to extend" which are quite different and not mutually exclusive.

**Comment by nalimilan** [comment]
That's indeed a general problem, but it's already the case for all traits and the `broadcast` machinery, so unexporting `promote_rule` wouldn't really make it worse.

**Comment by StefanKarpinski** [comment]
Fair enough.

**Comment by nalimilan** [comment]
More opinions?

**Comment by JeffBezanson** [comment]
Triage thinks we can just leave this.
