### ISSUE TITLE
Strange behaviour of Vararg inside tuples

### ISSUE THREAD

**Issue by rafaqz** [JuliaLang/julia#25843]
I'm not sure if this is even meant to work, but it nearly does - which is confusing!

In this example `Vararg{Symbol}` in last position in a tuple passes `Symbol` - not `(Symbol)`, although `(Symbol,Symbol)` etc work just fine. `()` is not in the main `vals` tuple at all, and require another method to catch. The runtime type checks and `tuple(Symbol)` below solves this, but is this a reliable strategy in future? 
```  
  function VarSpec(id::Int64, vals::Tuple{Float64,Vararg{Symbol}}) 
    (value, flags) = vals
    if typeof(flags) == Symbol
      flags = tuple(flags)
    end
    range = calc_range(value)
    new(id, value, range, flags)
  end

  function VarSpec(id::Int64, vals::Tuple{Float64,NTuple{2,Float64},Vararg{Symbol}})
    (value, range, flags) = vals
    if typeof(flags) == Symbol
      flags = tuple(flags)
    end
    new(id, value, range, flags)
  end

  function VarSpec(id::Int64, value::Float64)
    range = calc_range(value)
    new(id, value, range, tuple())
  end

  function VarSpec(id::Int64, vals::Tuple{Float64,NTuple{2,Float64}})
    (value, range) = vals
    new(id, value, range, tuple())
  end
```

Julia Version 0.6.2                                                
Commit d386e40 (2017-12-13 18:08 UTC)
Platform Info:                                                     
  OS: Linux (x86_64-pc-linux-gnu)                                  
  CPU: Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz                    
  WORD_SIZE: 64                                                    
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)         
  LAPACK: libopenblas
  LIBM: libm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)

**Comment by vtjnash** [comment]
Can you explain more about what you're seeing? I just get MethodErrors:
```julia
julia> VarSpec(1, (1.0, (2.0, 3.0), (:a, :b)))
ERROR: MethodError: no method matching VarSpec(::Int64, ::Tuple{Float64,Tuple{Float64,Float64},Tuple{Symbol,Symbol}})
Closest candidates are:
  VarSpec(::Int64, ::Tuple{Float64,Vararg{Symbol,N} where N}) at REPL[7]:2
  VarSpec(::Int64, ::Tuple{Float64,Tuple{Float64,Float64},Vararg{Symbol,N} where N}) at REPL[11]:2
```

**Comment by rafaqz** [comment]
Ok sorry here's the whole struct.

But the main point is that with this type signature:
 
` function VarSpec(id::Int64, vals::Tuple{Float64,Vararg{Symbol}})`
 
This check is required to make sure I have a tuple, which seems like it shouldn't be possible:
   
```
   (value, flags) = vals
    if typeof(flags) == Symbol
      flags = tuple(flags)
    end
```


```
function VarSpec(id::Int64, value::Float64)
    range = calc_range(value)
    new(id, value, range, tuple())
  end

  function VarSpec(id::Int64, vals::Tuple{Float64,NTuple{2,Float64}})
    (value, range) = vals
    new(id, value, range, tuple())
  end
```

**Comment by vtjnash** [comment]
I’m still lost - you’ve declared that flags isa Symbol. The method shouldn’t accept a Tuple ever, not should flags ever be a Tuple.

Did you mean to use NTuple instead of Varargs, or `tail` instead of Tuple-assignment unpacking?

**Comment by rafaqz** [comment]
There can be a variable number of flags, thus the Vararg.

Originally the Varargs was outside the tuple, which makes way more sense of course - but made the DSL annoying to parse, so playing with this I was surprised to find it worked - but with those strange effects.

It actually does work perfectly how it is.

**Comment by JeffBezanson** [comment]
I'm not sure I understand the issue here, but my guess is it's that in

```
function foo(x::Float64, y::Vararg{Symbol})
```

`y` will be a tuple of symbols, but in

```
function foo(t::Tuple{Float64, Vararg{Symbol}})
    x, y = t
```

`y` will be a symbol (not a tuple of symbols). Is that the problem? If so, this is expected. The syntax `x, y = t` only extracts individual elements from tuples.

In your code, the check `typeof(flags) == Symbol` is redundant; if the `vals` tuple has at least 2 elements then `flags` will certainly be a `Symbol`. If it has 1 element the assignment `(value, flags) = vals` will give an error. If it has more than 2 elements, your code is ignoring all but the first 2.

**Comment by rafaqz** [comment]
Ok I get it. I thought Varargs _always_ returned a tuple.

So if I have this correctly it's expected behaviour when declared _inside_ another tuple is to vary the length of the containing tuple, not to produce a variable length tuple as a member of the containing tuple.

That's what got me, it's not necessarily intuitive (or in the docs!)

**Comment by rafaqz** [comment]
So the behaviour I actually wanted is (mostly) given by:

`VarSpec(id::Int64, vals::Tuple{Float64,Tuple{Vararg{Symbol}}}) `

It needs a Tuple{} wrapper around Vararg{} that isn't required in a function type signature, hopefully its clear how that could be confusing.

**Comment by martinholters** [comment]
I'm not 100% sure I understand what it is that confuses you. Is it that
```julia
julia> f(x::Vararg) = typeof(x)
f (generic function with 1 method)

julia> f(1,2,3)
Tuple{Int64,Int64,Int64}
```
Here, `x` is declared as a `Vararg` in the parameter list and becomes a `Tuple` in the function, while
```julia
julia> g(x::Tuple{Vararg}) = typeof(x)
g (generic function with 1 method)

julia> g((1,2,3))
Tuple{Int64,Int64,Int64}
```
Here, `x` is declared as a `Tuple{Vararg}`, but has the same type inside the function? Yes, that might be confusing... Maybe that's why the former should rather be written `f(x...) = typeof(x)`.

**Comment by rafaqz** [comment]
Yep that's it. It seems to be the only type keyword that behaves differently depending on wether it is declared in a function or in a tuple. It variably changes it's parent types length in a tuple, but return a variable length tuple in a function.

Is there anything else with that kind of tuple/function inconsistency? 

I realised I've gotten so used to julias incredibly consistent syntax that I don't expect quirks like that at all, where I would in other languages. So that's a good thing I guess!

I can put a pull request cross linking the docs just to make sure people know that the tuple Vararg is not the same as the function Vararg if that seems useful. I never found the Vararg Tuple type section until after putting in this issue, and just assumed the functions behaviour held.

**Comment by rafaqz** [comment]
I think most succinctly I can put it now is that Vararg is an overloaded keyword for two _slightly different_ processes in the type system that involve unknown argument lengths and tuples.

But it appears to be a single, non-overloaded Type to the uninitiated.

**Comment by JeffBezanson** [comment]
`Vararg` does not mean different things in different contexts. A function's arguments have an overall type which is a Tuple type. For example in

```
function f(x::Float64, y::Vararg{Symbol})
```

the overall argument type is `Tuple{Float64, Vararg{Symbol}}` --- imagine `Tuple{   }` with the declared argument types just dropped into it. That matches the exact same values as

```
function f(t::Tuple{Float64, Vararg{Symbol}})
```

if you wrap the values in an extra level of parentheses: `f(1.0, :a, :b)` in the first case, `f((1.0, :a, :b))` in the second case. So `Vararg` means exactly the same thing in both cases.

The next, and separate, issue, is how argument names are bound to values. In the first function, we have a rule that `y` gets bound to a tuple containing the tail of the argument list from that point. As @martinholters pointed out, the friendlier syntax for `::Vararg` is `...`:

```
function f(x::Float64, y::Symbol...)
```

this would correspond to the assignment `x, y... = <argument tuple>`. However you have been comparing it to the assignment syntax `x, y = <tuple>`, which is why there appears to be a discrepancy. (In fact we don't yet allow the syntax `x, y... = ` in an assignment, but we probably will eventually.) So in summary, you have two identical tuple types but two different ways of destructuring them into variables.

**Comment by rafaqz** [comment]
Sure, I get that Varargs matches the same arguments in both functions and tuples.

It's your second point is the main difference that confused me initially - that Vararg binds to values differently in a function and a tuple -  that's what I mean by an overloaded term with two slightly different meanings. Apologies if I haven't been very clear about that.

Also I found that not allowing (x, y...) = complicates things further, as there is no simple way of getting at the variable length tuple that would be bound when Varargs is used in a function, so refactoring between say `f(a:Int, b:Float64, Vararg{Symbol})` and `f(a:Int, Tuple{Float64,Vararg{Symbol}})` is not an intuitive process.

**Comment by rafaqz** [comment]
It does make much more sense when f(x::Vararg) is written f(x...) as there is no overloaded term - you just can't do that in a tuple.

**Comment by Keno** [comment]
As discussed, this is not a bug, just an implementation detail of argument syntax.
