### ISSUE TITLE
Instructions for distro package maintainers

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#25905]
Some linux distributions provide Julia through their various package managers. Typically they make some modifications, such as using system-provided libraries where possible.

At the moment, we include this line in the README:

> Please be aware that this procedure is not officially supported, as it introduces additional variability into the installation and versioning of the dependencies, and is recommended only for system package maintainers. 

which is not all that useful, as we don't give any further advice for what package maintainers should do.

It is probably worth documenting (either in the current README, or a new one) exactly:
1. What versions of the dependencies should work (either officially, or "have been known to work")
2. Which custom patches are used, and which are necessary

See also https://github.com/JuliaNLSolvers/NLsolve.jl/issues/123#issuecomment-363229666.

**Comment by nalimilan** [comment]
Good idea. AFAIK the versions of the dependencies are listed in README.md, so that's not an issue. But custom patches should be mentioned, e.g. pointing to the relevant files in the source tree. This only applies to LLVM and libuv I think (there have been patches for other projects, but they just fixed normal bugs which hit any user of these projects and have nothing specific to Julia).

Another point which could be stressed is that distro packages should use a multithreaded OpenBLAS and LAPACK and not the reference BLAS, as users then get poor performance and don't know why. This used to be the case with the Arch package IIRC. Depending on the distributions, it may not be possible as some distros prefer allowing the user to choose BLAS for the whole system.

**Comment by simonbyrne** [comment]
It might also be a good idea to provide a list of Julia packages. Currently maintained ones I know of are:
- [Fedora](https://copr.fedorainfracloud.org/coprs/nalimilan/julia/)
- [Arch](https://www.archlinux.org/packages/community/x86_64/julia/)

Additionally, the following unmaintained packages:
- [Ubuntu](https://launchpad.net/~staticfloat/+archive/ubuntu/juliareleases) (0.5)
- [Debian](https://packages.debian.org/sid/julia) (0.4)

**Comment by simonbyrne** [comment]
From the discussion on the [Arch issue](https://bugs.archlinux.org/task/57387) it seems that we really need to emphasise the LLVM problem, so maybe something like:

> The most complicated dependency is LLVM, for which we require version 3.9 with some additional patches (note: these are backported bug fixes, _not_ Julia specific patches: all have been contributed into upstream LLVM). We recommend either adding the patches to the LLVM 3.9 package of the distribution, or bundling a Julia-only LLVM library inside the Julia package. Using an unpatched or different version of LLVM will result in errors and/or poor performance.

**Comment by omus** [comment]
Gentoo Julia package: https://packages.gentoo.org/packages/dev-lang/julia
