### ISSUE TITLE
hello I would like to collaborate in your project of translator to Spanish which is my native language

### ISSUE THREAD

**Issue by LuigiBaute** [JuliaLang/julia#26100]
If you have a question or are unsure if the behavior you're experiencing is a bug,
please search or post to our Discourse site: https://discourse.julialang.org. We use
the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including a minimal reproducible example and the output of `versioninfo()`.
If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!

**Comment by yuyichao** [comment]
I do not believe there's anything actionable in this repo. If you are not sure which repo to raise an issue to or just want to get help on how to start, please follow the issue template and ask on the discourse site.

**Comment by miguelraz** [comment]
¡Bienvenido a Julia, estimado Luigi!

@LuigiBaute : con mucho gusto puedes ayudar con el proyecto de traducción - siempre falta gente.
Sin embargo, te fuertemente recomiendo te familiarices más con las políticas y prácticas para contribuir, pues hay mucho que aprender y hay que tener en cuenta que los desarrolladores esperan que si no estés al nivel, al menos empieces a aprender por tu parte algo.

¿Por qué no consideras empezar con tutoriales de cómo usar git y github, como [ejemplo este](https://git-scm.com/book/en/v2)?

Después considera unirte al Gitter de JuliaLangEs en español,  para que contestemos tus dudas más puntuales. 

---
Luigi: You are very welcome to join the translation project, we can also use able hands. However, we strongly recommend you read our contributing guidelines and policies, since there is a lot to learn and the developers expect you to be at the level required or strongly encourage to step up to it.

Why not start with the git book to get yourself familiary with the basic git workflow?

Afterwards, consider joining us in the JuliaLangEs Gitter, so that we can give better followthrough to your questions.

Happy hacking!
