### ISSUE TITLE
Error when adding packaging on julia

### ISSUE THREAD

**Issue by nsuhaimi** [JuliaLang/julia#26167]
![capture](https://user-images.githubusercontent.com/33942953/36575744-79b52c04-1844-11e8-8457-aa0a0da8c56d.PNG)

**Comment by paschelandromeda** [comment]
Hi keep getting this error even after few times of uninstall, restart and install. Any idea how to fix this??

**Comment by zhangliye** [comment]
I encountered the same error. I have uninstalled Julia, but it is still not solved. Currently, I cannot use Julia for the work now.

**Comment by tkind** [comment]
I ran into the same problem. Executing the 'Easy fix' solved it. I hope it helps :)
https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in

**Comment by nalimilan** [comment]
Is this a new error due to Windows updates? Do you understand what is going on and what Julia should do to avoid this?

**Comment by andreasnoack** [comment]
See https://discourse.julialang.org/t/pkg-update-error-base-libgit2-test-fails/9272/11. This is because of https://githubengineering.com/crypto-removal-notice/.

**Comment by paschelandromeda** [comment]
its all good now! Thanks @andreasnoack and @tkind

**Comment by Naetmul** [comment]
New users using Windows 7 could really suffer from this issue, because they will not be able to install any packages unless they install TLS update. At least, there should be some guidelines in Julia Windows installation page about this issue if the installation exe is not modified.

**Comment by KristofferC** [comment]
Yes, we might have to release a new 0.6 to fix this... Not sure what others think. The current situation is not good, agreed.

**Comment by Naetmul** [comment]
How to install Windows 7 TLS update is here: https://github.com/JuliaLang/julia/issues/13399#issuecomment-368279399

**Comment by StefanKarpinski** [comment]
The text of the original error not as a PNG so that it's finable by search:

> ERROR: GitError(Code:ECERTIFICATE, Class:OS, user cancelled certificate check: )

**Comment by davidanthoff** [comment]
I think this warrants a 0.6.3 release...

**Comment by simonbyrne** [comment]
This also seems to be a problem with GitHub-hosted binaries (see https://github.com/JuliaStats/Rmath-julia/issues/38), which will become a bigger issue as BinaryBuilder.jl is more widely used.

**Comment by aviks** [comment]
LibGit2 PR: https://github.com/libgit2/libgit2/pull/4550

We'll need something like that

**Comment by nalimilan** [comment]
I'm inclined to take this issue as a warning that we should not rely on a third party like GitHub to provide Julia packages and binaries. Maybe they should be hosted on a dedicated server? Or at least use a URL that we control and which can be made to point at a custom server if that kind of problem happens in the future? That would be really really bad on production systems.

**Comment by StefanKarpinski** [comment]
A layer of indirection is not a bad idea. Of course we can also push out new URLs in METADATA / a registry at any point.

**Comment by aviks** [comment]
Honestly, people who have critical uptime requirements should pay someone
to guarantee it. The amount of free services github provides is huge, I
don't think we will have the resources to replicate this to that level.

**Comment by jebej** [comment]
An announcement should probably be made with the link to the Microsoft easy fix.

**Comment by programistawpf** [comment]
Summary:

  * Close Julia window
  * Go to
    https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in
  * Use the "Easy Fix"
  * Download and run
  * Now re-run Julia --> Pkg.update() works!
  *


W dniu 2018-02-26 o 20:37, Jeremy pisze:

**Comment by ebager** [comment]
I cannot stress just how much I love that "Easy Fix".. Spend 2 days being so frustrated and now it finally works again! THANK YOU :D

**Comment by programistawpf** [comment]
Unfortunatly something new :
What to do ?

 Version 0.6.2 (2017-12-13 18:08 UTC)
 Official http://julialang.org/ release
 x86_64-w64-mingw32

`julia> Pkg.build("NLopt")
INFO: Building NLopt
INFO: Attempting to create directory C:\Users\PC\.julia\v0.6\NLopt\deps\downloads
INFO: Directory C:\Users\PC\.julia\v0.6\NLopt\deps\downloads already exists
INFO: Downloading file https://github.com/stevengj/nlopt/releases/download/nlopt-2.4.2/nlopt-2.4.2-dll32.zip
Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.SecurityProtocolType" due to invalid enu
meration values. Specify one of the following enumeration values and try again. The possible enumeration values are "Ss
l3, Tls"."
At line:1 char:28
+ [Net.ServicePointManager]:: <<<< SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (new-object net.webclient).Dow
nloadFile("https://github.com/stevengj/nlopt/releases/download/nlopt-2.4.2/nlopt-2.4.2-dll32.zip", "C:\Users\PC\.julia\
v0.6\NLopt\deps\downloads\nlopt-2.4.2-dll32.zip")
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Exception calling "DownloadFile" with "2" argument(s): "Połączenie podstawowe zostało zakończone: Wystąpił nieoczekiwan
y błąd przy wysyłaniu."
At line:1 char:121
+ [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (new-object net.webclient).DownloadF
ile <<<< ("https://github.com/stevengj/nlopt/releases/download/nlopt-2.4.2/nlopt-2.4.2-dll32.zip", "C:\Users\PC\.julia\
v0.6\NLopt\deps\downloads\nlopt-2.4.2-dll32.zip")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

====================================================[ ERROR: NLopt ]====================================================


LoadError: failed process: Process(`'C:\Windows\System32\WindowsPowerShell\v1.0\powershell' -NoProfile -Command '[Net.Se
rvicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (new-object net.webclient).DownloadFile("https
://github.com/stevengj/nlopt/releases/download/nlopt-2.4.2/nlopt-2.4.2-dll32.zip", "C:\Users\PC\.julia\v0.6\NLopt\deps\d
ownloads\nlopt-2.4.2-dll32.zip")'`, ProcessExited(1)) [1]
while loading C:\Users\PC\.julia\v0.6\NLopt\deps\build.jl, in expression starting on line 56
`

**Comment by programistawpf** [comment]
And more:
`julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of IntervalSets...
INFO: Updating cache of IndirectArrays...
INFO: Updating cache of StatPlots...
INFO: Updating cache of OnlineStatsBase...
INFO: Updating cache of MbedTLS...
INFO: Updating cache of TableTraits...
INFO: Updating cache of FFTW...
INFO: Updating cache of Compat...
INFO: Updating cache of MemPool...
INFO: Updating Plots master... 7c257a09 → 047a13a8
INFO: Package PyPlot: skipping update (pinned)...
INFO: Computing changes...
INFO: Cloning cache of BinaryProvider from https://github.com/JuliaPackaging/BinaryProvider.jl.git
INFO: Upgrading AbstractFFTs: v0.3.0 => v0.3.1
INFO: Installing BinaryProvider v0.2.5
INFO: Upgrading Compat: v0.59.0 => v0.60.0
INFO: Upgrading IndirectArrays: v0.4.0 => v0.4.1
INFO: Upgrading IntervalSets: v0.1.1 => v0.2.0
INFO: Upgrading MbedTLS: v0.5.6 => v0.5.8
INFO: Upgrading MemPool: v0.0.6 => v0.0.7
INFO: Upgrading OnlineStatsBase: v0.6.0 => v0.6.1
INFO: Upgrading StatPlots: v0.7.0 => v0.7.1
INFO: Upgrading TableTraits: v0.1.0 => v0.2.0
INFO: Building MbedTLS
Info: Downloading https://github.com/quinnj/MbedTLSBuilder/releases/download/v0.6/MbedTLS.x86_64-w64-mingw32.tar.gz to
:\Users\PC\.julia\v0.6\MbedTLS\deps\usr\downloads\MbedTLS.x86_64-w64-mingw32.tar.gz...
Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.SecurityProtocolType" due to invalid en
meration values. Specify one of the following enumeration values and try again. The possible enumeration values are "S
l3, Tls"."
At line:1 char:35
+ [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Exception calling "DownloadFile" with "2" argument(s): "Po?Yczenie podstawowe zosta?o zako?one: WystYpi? nieoczekiwan
y b?Yd przy wysy?aniu."
At line:4 char:24
+ $webclient.DownloadFile <<<< ("https://github.com/quinnj/MbedTLSBuilder/releases/download/v0.6/MbedTLS.x86_64-w64-mi
gw32.tar.gz", "C:\Users\PC\.julia\v0.6\MbedTLS\deps\usr\downloads\MbedTLS.x86_64-w64-mingw32.tar.gz")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

===================================================[ ERROR: MbedTLS ]=================================================


LoadError: Could not download https://github.com/quinnj/MbedTLSBuilder/releases/download/v0.6/MbedTLS.x86_64-w64-mingw
.tar.gz to C:\Users\PC\.julia\v0.6\MbedTLS\deps\usr\downloads\MbedTLS.x86_64-w64-mingw32.tar.gz
while loading C:\Users\PC\.julia\v0.6\MbedTLS\deps\build.jl, in expression starting on line 40

======================================================================================================================

INFO: Building SpecialFunctions
INFO: Building Rmath
INFO: Building Plots

====================================================[ BUILD ERRORS ]==================================================


WARNING: MbedTLS had build errors.

 - packages with build errors remain installed in C:\Users\PC\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("MbedTLS")`
 - build a single package by running its `deps/build.jl` script

======================================================================================================================


julia>`

**Comment by PaulMatlashewski** [comment]
I'm having the same issue as @programistawpf above. I've run the Easy Fix but no luck.

**Comment by davidanthoff** [comment]
Try to install the latest version of Microsoft's windows management framework.

**Comment by priyaranjan-tokachichu** [comment]
@davidanthoff, the installation of the latest version of Microsoft's windows management framework worked for me.

**Comment by programistawpf** [comment]
On my machine WIN7-64, after reinstaling MS Net.Framewrok 4.7 is better !
Paul

**Comment by davidh0** [comment]
Hey,

Running a freshly installed Win7 Pro 64bit and i encountered the same error as posted by @programistawpf 

Installing .NET 4.7, the already mentioned Windows Update, the EasyFix, MS WMF 5.1 and all Securityupdates up to today got it working.

**Comment by programistawpf** [comment]
Unfortunatly ths ERROR  back :/
What to do ?

Win7 - 64
Version 0.6.2 (2017-12-13 18:08 UTC)
x86_64-w64-mingw32

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of Combinatorics...
...
INFO: Upgrading WinRPM: v0.3.1 => v0.3.2
INFO: Building Blosc
Info: Downloading 
https://github.com/stevengj/BloscBuilder/releases/download/v1.14.2+5/Blosc.x86_64-w64-mingw32.tar
.gz to 
C:\Users\PC\.julia\v0.6\Blosc\deps\usr\downloads\Blosc.x86_64-w64-mingw32.tar.gz...
Exception setting "SecurityProtocol": "Cannot convert null to type 
"System.Net.SecurityProtocolType" due to invali
d enumeration values. Specify one of the following enumeration values 
and try again. The possible enumeration valu
es are "Ssl3, Tls"."
At line:1 char:35
+ [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
     + FullyQualifiedErrorId : PropertyAssignmentException

Exception calling "DownloadFile" with "2" argument(s): "Po?Yczenie 
podstawowe zosta?o zako?one: WystYpi? nieocze
kiwany b?Yd przy wysy?aniu."
At line:4 char:24
+ $webclient.DownloadFile <<<< 
("https://github.com/stevengj/BloscBuilder/releases/download/v1.14.2+5/Blosc.x86_64
-w64-mingw32.tar.gz", 
"C:\Users\PC\.julia\v0.6\Blosc\deps\usr\downloads\Blosc.x86_64-w64-mingw32.tar.gz")
     + CategoryInfo          : NotSpecified: (:) [], 
MethodInvocationException
     + FullyQualifiedErrorId : DotNetMethodException

=================================================[ ERROR: Blosc 
]==================================================


LoadError: Could not download 
https://github.com/stevengj/BloscBuilder/releases/download/v1.14.2+5/Blosc.x86_64-w64
-mingw32.tar.gz to 
C:\Users\PC\.julia\v0.6\Blosc\deps\usr\downloads\Blosc.x86_64-w64-mingw32.tar.gz
while loading C:\Users\PC\.julia\v0.6\Blosc\deps\build.jl, in expression 
starting on line 30

===================================================================================================================

INFO: Building CodecZlib
Info: Downloading 
https://github.com/bicycle1885/ZlibBuilder/releases/download/v1.0.0/Zlib.x86_64-w64-mingw32.tar.g
z to 
C:\Users\PC\.julia\v0.6\CodecZlib\deps\usr\downloads\Zlib.x86_64-w64-mingw32.tar.gz...
Exception setting "SecurityProtocol": "Cannot convert null to type 
"System.Net.SecurityProtocolType" due to invali
d enumeration values. Specify one of the following enumeration values 
and try again. The possible enumeration valu
es are "Ssl3, Tls"."
At line:1 char:35
+ [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
     + FullyQualifiedErrorId : PropertyAssignmentException

Exception calling "DownloadFile" with "2" argument(s): "Po?Yczenie 
podstawowe zosta?o zako?one: WystYpi? nieocze
kiwany b?Yd przy wysy?aniu."
At line:4 char:24
+ $webclient.DownloadFile <<<< 
("https://github.com/bicycle1885/ZlibBuilder/releases/download/v1.0.0/Zlib.x86_64-w
64-mingw32.tar.gz", 
"C:\Users\PC\.julia\v0.6\CodecZlib\deps\usr\downloads\Zlib.x86_64-w64-mingw32.tar.gz")
     + CategoryInfo          : NotSpecified: (:) [], 
MethodInvocationException
     + FullyQualifiedErrorId : DotNetMethodException

===============================================[ ERROR: CodecZlib 
]================================================


LoadError: Could not download 
https://github.com/bicycle1885/ZlibBuilder/releases/download/v1.0.0/Zlib.x86_64-w64-m
ingw32.tar.gz to 
C:\Users\PC\.julia\v0.6\CodecZlib\deps\usr\downloads\Zlib.x86_64-w64-mingw32.tar.gz
while loading C:\Users\PC\.julia\v0.6\CodecZlib\deps\build.jl, in 
expression starting on line 92

===================================================================================================================

INFO: Building SpecialFunctions
INFO: Building WinRPM
INFO: Downloading 
https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openS
USE_Leap_42.2/repodata/repomd.xml
INFO: Downloading 
https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openS
USE_Leap_42.2/repodata/repomd.xml
INFO: Downloading 
https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openS
USE_Leap_42.2/repodata/85058aa8e394e5888b8e8f5597e695eef97eadb977624938bf0c0369e751c7d5-primary.xml.gz
INFO: Building FFTW

=================================================[ BUILD ERRORS 
]==================================================


WARNING: CodecZlib and Blosc had build errors.

  - packages with build errors remain installed in C:\Users\PC\.julia\v0.6
  - build the package(s) and all dependencies with 
`Pkg.build("CodecZlib", "Blosc")`
  - build a single package by running its `deps/build.jl` script

===================================================================================================================


W dniu 2018-03-28 o 19:17, Priyaranjan Tokachichu pisze:

**Comment by KristofferC** [comment]
Looks like https://github.com/JuliaLang/julia/issues/26459

**Comment by programistawpf** [comment]
I removed this issue, upadte runing, something temporary was!

**Comment by IlyaOrson** [comment]
I am hitting this with two Win 10 machines. Windows 10 already has latest WMF and TLS patch is not available. Windows updates did not help either, any ideas?

**Comment by dieris** [comment]
Same problem as @IlyaOrson on Windows 10:
```
ERROR: METADATA cannot be updated. Resolve problems manually in C:\Users\...\.julia\v0.6\METADATA.
GitError(Code:ECERTIFICATE, Class:OS, user cancelled certificate check: )
```

**Comment by programistawpf** [comment]
What to do now  ? :/  Problem back!
"Cannot convert null to type "System.Net.SecurityProtocolType" 

Version 0.6.2 (2017-12-13 18:08 UTC)
Official http://julialang.org/ release
x86_64-w64-mingw32

julia> using HDF5
INFO: Precompiling module Blosc.
ERROR: LoadError: Blosc not installed properly, run Pkg.build("Blosc"), restart Julia and try again
Stacktrace:
 [1] error(::String) at .\error.jl:21
 [2] include_from_node1(::String) at .\loading.jl:576
 [3] include(::String) at .\sysimg.jl:14
 [4] anonymous at .\<missing>:2
while loading C:\Users\PC\.julia\v0.6\Blosc\src\Blosc.jl, in expression starting on line 10
ERROR: Failed to precompile Blosc to C:\Users\PC\.julia\lib\v0.6\Blosc.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:710
 [2] _require(::Symbol) at .\loading.jl:497
 [3] require(::Symbol) at .\loading.jl:405
 [4] _include_from_serialized(::String) at .\loading.jl:157
 [5] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:200
 [6] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:236
 [7] _require(::Symbol) at .\loading.jl:441
 [8] require(::Symbol) at .\loading.jl:405

julia>  Pkg.build("Blosc")
INFO: Building Blosc
Info: Downloading https://github.com/stevengj/BloscBuilder/releases/download/v1.14.2+5/Blosc.x86_64-w64-mingw32.tar
.gz to C:\Users\PC\.julia\v0.6\Blosc\deps\usr\downloads\Blosc.x86_64-w64-mingw32.tar.gz...
Exception setting "SecurityProtocol": **"Cannot convert null to type "System.Net.SecurityProtocolType" d**ue to invali
d enumeration values. Specify one of the following enumeration values and try again. The possible enumeration valu
es are "Ssl3, Tls"."
At line:1 char:35
+ [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Exception calling "DownloadFile" with "2" argument(s): "Po?Yczenie podstawowe zosta?o zako?one: WystYpi? nieocze
kiwany b?Yd przy wysy?aniu."
At line:4 char:24
+ $webclient.DownloadFile <<<< ("https://github.com/stevengj/BloscBuilder/releases/download/v1.14.2+5/Blosc.x86_64
-w64-mingw32.tar.gz", "C:\Users\PC\.julia\v0.6\Blosc\deps\usr\downloads\Blosc.x86_64-w64-mingw32.tar.gz")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/issues/26459

**Comment by KristofferC** [comment]
You have written four times now with the exact same error message.

And you even fixed it once: https://github.com/JuliaLang/julia/issues/26167#issuecomment-376973651

**Comment by programistawpf** [comment]
Yes, but now this solution do not help.
Paul
W dniu 2018-04-27 o 14:40, Kristoffer Carlsson pisze:

**Comment by maikkirapo** [comment]
I get the same error message when I try to use Julia from Atom:

```
Press Enter to start Julia.
Starting Julia...
INFO: Precompiling module Atom.
ERROR: LoadError: MbedTLS not installed properly, run Pkg.build("MbedTLS"), restart Julia and try again
Stacktrace:
 [1] error(::String) at .\error.jl:21
 [2] include_from_node1(::String) at .\loading.jl:576
 [3] include(::String) at .\sysimg.jl:14
 [4] anonymous at .\<missing>:2
while loading C:\Users\mra136\.julia\v0.6\MbedTLS\src\MbedTLS.jl, in expression starting on line 47
```
I have installed the easy fix, but it doesn't help. When I run `Pkg.build("MbedTLS")` I get the security protocol error.

**Comment by andreasnoack** [comment]
@maikkirapo Have you tried the "easy-fix" in mentioned in https://discourse.julialang.org/t/pkg-update-error-base-libgit2-test-fails/9272/11?

**Comment by maikkirapo** [comment]
@andreasnoack Yes, I have tried the easy fix like I already mentioned in my previous comment. Now I'm updating my computer to Win10. Let's see if that fixes this problem.

**Comment by c42f** [comment]
I just came across this problem trying to support a windows 7 install of julia 0.6.2. I don't have admin access to that machine so I spent a while trying to find a non-admin workaround. I didn't find one which works with the official julia-0.6.2 release.

However, libgit2 has merged a workaround which - if julia-0.6 was rebuilt against it - shouldn't require the registry entry workaround in the "quick fix": https://github.com/libgit2/libgit2/pull/4550. I believe this should work on any up to date win7 machine.

To summarize the problem for the curious:
* `Pkg` uses `libgit2`, which in turn downloads files using the `WinHttp` library.
* The version of `libgit2` shipped with julia 0.6.2 doesn't set the TLS version, so it defaults to TLS1.0
* github disabled TLS1.0 in February, users must upgrade to TLS1.2
* `WinHttp` on Windows 7 doesn't enable TLS1.2 by default (and indeed may not support it at all unless the non-registry parts of [KB3140245](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in) are installed via windows update?)

The registry changes in KB3140245 won't work for users without admin access because the keys relevant to WinHttp defaults live in `HKEY_LOCAL_MACHINE`, rather than `HKEY_CURRENT_USER`. The only non-admin solution looks like rebuilding julia.

**Comment by kbouhi** [comment]
@c42f , but wouldn't the build also need the git connection?

**Comment by LeoGalPras** [comment]
I have tried every solution listed here I think, still geet the error, I've tried:

-  .NET 4.7
- Windows Update
- Easyfix
- Manually installing the update for enabling TLS 1.2

Nothing seems to work, the latest WMF is not available for my computer. What could I be missing???

**Comment by stevengj** [comment]
I just ran into this error with julia 0.6.4 on Windows 7 SP1, on a machine that I don't have admin access on (department laptop). 😢

**Comment by anuraglahon16** [comment]
I have done in my Windows 8 and the easy fix didn't run on my system.How can I run Julia in Jupyter notebook now?

**Comment by Thuener** [comment]
This is an important issue for companies. Many still use Windows 7 and the windows support to Easy Fix solution are no longer supported (https://support.microsoft.com/en-us/help/2970908/how-to-use-microsoft-easy-fix-solutions).

**Comment by c42f** [comment]
This should have been fixed in julia-0.7 by the addition of 0541bca5 (see #27241).

@Thuener I assume you are stuck on julia-0.6 for now? I think the registry workaround is still possible but you have to do it manually. It's just a couple of keys though so should be doable.

**Comment by CorentinJ** [comment]
On win7 x64:
I installed the easy fix.
I downloaded the most recent .net update (which I already had).
I installed Windows Management Framework 3.
I reinstalled Julia.

I still have the issue:
`Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.SecurityProtocolType" due to invalid enumeration values. Specify one of the following enumeration values and try again. The possible enume
ration values are "Ssl3, Tls"." (...)`

**Comment by CorentinJ** [comment]
On win7 x64:
I installed the easy fix.
I downloaded the most recent .net update (which I already had).
I reinstalled Julia 0.6.4 and cleared all my packages (users/[user]/.julia folder).

Nothing worked until I installed [Windows Management Framework 3](https://www.microsoft.com/en-us/download/details.aspx?id=34595) and restarted my computer after the installation. Thank you @Thuener
