### ISSUE TITLE
Unicode: Supporting middle dot & real minus

### ISSUE THREAD

**Issue by fbruetting** [JuliaLang/julia#26193]
Would be nice if you could equal `·` (`U+b7`) with the currently existing `\cdot[TAB]` (`U+22c5`), as on some keyboard layouts (like the german Neo2) you could directly produce that. You there also can produce the real minus glyph `−` (`U+2212`), which has the same width as the plus sign, but sadly isn’t supported in Julia yet, too.

**Comment by stevengj** [comment]
See #25157, which addresses U+00b7 equivalence.

I'm less sure of what the use-case is for normalizing `−` to a hyphen, since the minus glyph is pretty hard to type by accident...  See also #19464.

**Comment by fbruetting** [comment]
Ok, I see that the `U+b7` is underway, nice!

With `−` being the _real_ minus, I think it would be more than appropriate to support that. It’s not on every keyboard, that’s true. But you also get that when copying formulas, as some formula editors convert the “half em dash” to the real minus, so that it doesn’t stick out negatively as much(becaust it’s just a quarter em dash, and therefore much shorter than the plus sign).

**Comment by StefanKarpinski** [comment]
On the other hand, I can't see any reason _not_ to treat a real minus sign as a minus sign.

**Comment by stevengj** [comment]
Since `-` is both a binary and a unary operator, this would add a bunch of cases into the parser... I just don't see the need here.

As I wrote in #19464, there are zillions of equivalences that we could potentially define, since Unicode has lots of easily confusable characters.  But if we don't want to go full NFKC normalization, I think we should be conservative about adding custom normalizations: limit ourselves to confusable characters that are easy to type and hence show up frequently in practice.  I don't think U+2212 qualifies here.

**Comment by fbruetting** [comment]
When you work with TeX/LaTeX/ConTeXt or simlar systems, you’ll encounter real minuses all day long. With Julia targeting more or less exactly the same area, I can’t imagine that it should be normal practice, having to substitute real minuses by hyphens for getting a rendered formula working in Julia by pasting.

**Comment by stevengj** [comment]
@fbruetting, I'm in a math department — of course I use typeset math with real minus glyphs.  But I never *type* those glyphs, they are rendered for me.

I'm skeptical of the use-case of copying and pasting a rendered formula into code.  There aren't many occasions in which you can copy and paste a rendered formula into a text document, and in most of those cases you can just copy-and-paste from the LaTeX source (which uses hyphens) instead.

**Comment by fbruetting** [comment]
No, I haven’t searched and really need to sleep now. I also can’t estimate the effort, but it would just be a nice feature. 🙂

**Comment by stevengj** [comment]
@fbruetting, none of those links describe people using U+2212  by accident from copy-and-paste.

**Comment by mcabbott** [comment]
This bit me a few days ago, precisely by copying coefficients from a PDF while trying to make a plot. I agree that copying a formatted formula is never going to work well, but copying numbers seems like it ought to be straightforward. 

The error was initially as follows, where `− 5` was the copied coefficient (in reality with a few more decimals) which also seems odd for an illegal character:
```julia
julia> Ls = 1:10; 1 ./ (Ls .^ 2) .− 5 ./ (Ls .^ 3)
ERROR: syntax: space before "." not allowed in "(Ls .^ 2) ."
```

**Comment by stevengj** [comment]
Copying typeset numbers from a PDF does seem like a reasonable use-case.

**Comment by dpsanders** [comment]
I have had these issues copying and pasting from a PDF multiple times.

**Comment by fbruetting** [comment]
Please give the initial posts thumbs-ups, to indicate the developers how much people would profit / are interested at a glance. 😉

**Comment by milindsmart** [comment]
I am excited enough about the _real_ (unicode) operators sufficiently that I want to start using Julia for that reason (I am also academically from a scientific computation background)... Using − (U+2212)  rather than - is one of the most visually pleasing changes I can make to arithmetic expressions in code. Please don't exclude that one operator from the list. 

Treating it as a real minus sign, or allowing it as an operator with plus-like precedence, are both great options.

**Comment by StefanKarpinski** [comment]
This seems fine to me, someone just needs to make a PR.

**Comment by stevengj** [comment]
When/if #25157 (which I just updated/fixed) is merged, supporting the Unicode minus will be a trivial one-line patch to `src/flisp/julia_charmap.h`.

**Comment by epithet** [comment]
@fbruetting I think, this can be closed now. Can be verified with the latest nightly. Sorry, I properly linked the PR too late.
