### ISSUE TITLE
a, b... = [1,2,3]

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#2626]
This would be a very nice syntax for taking head and rest. Likewise `a..., b = [1,2,3]` might be good for slurping the initial elements into `a` and the tail element into `b`.

**Comment by StefanKarpinski** [comment]
I found myself wanting this syntax yet again today. I think we should consider this.

**Comment by kmsquire** [comment]
(Match.jl has this)

**Comment by StefanKarpinski** [comment]
There are some design issues here, primarily: what should the type of `b` (or `a`) be – array, tuple or iterator? Since we haven't addressed this, it seems best to bump this to 1.0.

**Comment by HarrisonGrodin** [comment]
Here's an interesting example that begins to address the issue.

```julia
julia> a, b, c = countfrom()
Base.Count{Int64}(1,1)

julia> a, b, c
(1,2,3)
```

This works as expected, but what if "splatting" was used on one of the variables?

In the case that `c` was "splatted", it would make sense to return an iterator with `start` returning the "current" iterator value and `next`/`done` matching that of the existing iterator.
However, what if `b` was "splatted"? Would the code run indefinitely? An iterator could be useful if the last variable is "splatted", but it could become more confusing otherwise.

In the case that an iterator is not the right choice, though, the question of mutability (tuple vs. array) definitely seems to be worth debating.

**Comment by StefanKarpinski** [comment]
Yes, it does seem that returning a `Rest` iterator might be necessary in the general case.

**Comment by eveydee** [comment]
This is a feature I have missed a few times. FWIW, Python seems to do the equivalent of `collect` on the splatted unpacking. I don't like this.

Could the return type be delegated to the iterator? I. e., translate
```julia
a, b, c..., d, e = f
->
a = first(f); b = second(f);
c = slurp(f, 3, end-2);
d = secondlast(f); e = last(f)
```

**Comment by StefanKarpinski** [comment]
I think the issue is for iterable things that are not infinite but have indefinite length and/or can only be iterated in order – you can't get the last item until you've collected the ones before it.

**Comment by iamed2** [comment]
Is this not a 1.x possibility? This is currently invalid syntax.

**Comment by mlhetland** [comment]
The [Python approach](https://www.python.org/dev/peps/pep-3132/) might be worth looking at, replacing `*` with `...`. (I see dalum is skeptical of the specifics – but isn't it good to be somewhat consistent with the varargs approach, where `args...` becomes a sequence of values? I might be misunderstanding.)

Anyway, Python also permits `a, *b, c = range(5)` (i.e., `a, b..., c = 0:4`). We may not want to copy that approach, though it might be worth having a look at the (reasonably short) spec, given that this is a meaning of this kind of unpacking that is already widely in use. (And, yes, this kind of unpacking is quite useful and readable, IMO.)

**Comment by StefanKarpinski** [comment]
Even reading that PEP I don’t really get what they do. The main question we have is whether this should be eager or lazy. The Python approach appears to be eager?

**Comment by yurivish** [comment]
How could it be eager in the `a, b..., c = 0:4` case? What would be the value of `c`?

**Comment by mlhetland** [comment]
Maybe it makes sense to have two distinct classes of iterables here? If we define one class for which it makes (enough) sense to be eager (certainly tuples, maybe vectors, possibly some other things, but certainly not potentially infinite sequences), we could permit `a, b..., c` – otherwise that could be an error (the default).

(Otherwise, to be lazy and still permit it, I guess we *could* use something like a `Future`, but that seems sort of excessive, and probably not a very useful use-case anyway?)

**Comment by mlhetland** [comment]
But, yeah, the [Python definition](https://docs.python.org/3/reference/simple_stmts.html#assignment-statements) does include the length of the rhs iterable (i.e., the rhs must have at least as many elements as the lhs), and though I've only looked cursorily at it, the implementation does seem eager.

**Comment by mlhetland** [comment]
@StefanKarpinski I guess that depends on what you mean by meaning. But, yeah, I think it makes sense to make this eager, myself – and have it behave “just like” varargs (which is a very close relative, after all).

**Comment by StefanKarpinski** [comment]
That does seems like the obvious version. Note, however that varargs produces tuples which is somewhat questionable for this kind of usage. We may want to collect a vector instead.

**Comment by oxinabox** [comment]
This would also let us write function signatures like:
```
julia> foo((a, bs...), c, ds...) = bs
ERROR: syntax: invalid assignment location "bs..."
```
Which would be useful for e.g. https://github.com/JuliaDiff/ChainRulesCore.jl/issues/128#issuecomment-586716291

**Comment by StefanKarpinski** [comment]
I think that leads us to an answer for how `a, bs... = <expr>` must behave (which is what had already been concluded, anyway):

* `foo(a, bs...)` already makes `bs` tuple
* `foo((a, bs...))` should behave the same way
* `(a, bs...) = <expr>` should behave the same way

**Comment by cindRoberta** [comment]
I think this would also be interesting

```julia
a, b, c[3:4] = [1, 2, 3, 4, 5];

#a= 1
#b= 2
#c= [3, 4]
```

**Comment by mlhetland** [comment]
I would have a strong expectation for that syntax to assign to a slice.

**Comment by yuyichao** [comment]
@cindRoberta See my comment in your issue. That syntax won't work sice it already has a meaning.

**Comment by StefanKarpinski** [comment]
This seems possible, however:
```jl
a, b, c[3:4]... = [1, 2, 3, 4, 5];
```

**Comment by mlhetland** [comment]
Might just be my mental model that's janky, but that seems very confusing to me. I.e., it seems like you're assigning to `c[3]` and `c[4]`, not that you're assigning `rhs[3:4]` to `c`…?

**Comment by StefanKarpinski** [comment]
I agree with you, @mlhetland, that's what I would expect it to do. Using an index on the left to indicate what value on the right to take is very unintuitive. I'm just pointing out what syntax is available.

**Comment by cindRoberta** [comment]
What if a symbol or token was used to indicate the assignment to the variable instead of the assignment to the slice?

Rust uses & to indicate the slice and assignment to the slice, which is ideal for me, in Julia it would be as follows:

to assign to the slice:
```julia
c = [1, 2, 3, 4, 5]
&c[3:4] = [6, 7]
# c = [1, 2, 6, 7, 5]
```

to assign to the variable:
```julia
c[3:4] = [1, 2, 3, 4, 5]
# c = [3, 4]
```

or using the token § (or another token)
```julia
§c[3:4] = [1, 2, 3, 4, 5]
# c = [3, 4]
```

_______________________________________________

but the closest to reality, without conflicts, is:

this already works in Julia, I know, it's a matter of preference to use &
```julia
c = [1, 2, 3, 4, 5]
c[3:4] = [6, 7]
# c = [1, 2, 6, 7, 5]
```

to slice:
```julia
§c[3:4] = [1, 2, 3, 4, 5]
# c = [3, 4]
```julia

it's a little confusing, I know, but it can't be any other way and, of course, keep the ... to assign the rest

**Comment by mlhetland** [comment]
Well, it does seem potentially useful to permit the lhs to pick apart the rhs. I guess one would also have
```
§x["foo"] = y
```
mean
```
x = y["foo"]
```
for example? Perhaps even permitting attribute lookup in the same way? (And function calls?)

Then again, if you’re going to be explicit about which parts you want, why not put that information on the rhs? The unpacking syntax is convenient when the parts are largely implicit, but I’m not sure I think, say
```
§a[1,3], §b[2,4] = c
```
is any better than
```
a, b = c[1,3], c[2,4]
```
Quite the opposite, really. Not only is it more verbose, it is, at least to me, quite confusing and contrary to how indexing works in general.

Then again, I don’t know what the desired use cases are – I’m clearly just speaking for myself.

**Comment by cindRoberta** [comment]
@mlhetland just in my ideal,

the & references a pre-declared variable

a= [1, 2, 3, 4, 5]
print(&a[3:4]) # [3, 4]

and the a[] create a sub-array of other array
a[3:4]= [1, 2, 3, 4, 5]
print(a) # [3, 4]

only that, maybe there is already a function in Julia that does this, but I don't know

**Comment by tpapp** [comment]
Sorry if I missed something, but I don't understand what the proposals with `§` have to do with this issue. In any case, I think we have perfectly good constructs for slicing up arrays in complicated ways, that fit into the semantics of the language. Introducing a DSL that does this on the LHS seems insufficiently motivated.

**Comment by mlhetland** [comment]
The splatting syntax also makes sense wrt. current syntax/semantics (like, e.g., in Python): Conceptually, you’re splatting in an as-yet-non-existent sequence/tuple in the lhs, whose elements are then defined by the assignment. There is, in a sense, only one way of interpreting what goes where.

**Comment by tpapp** [comment]
I would understand the `...` in `a, b... = ` as [slurping](https://docs.julialang.org/en/v1/manual/faq/#The-two-uses-of-the-...-operator:-slurping-and-splatting-1), not splatting (just like the original issue words it, and the same way it works for functions).

**Comment by mlhetland** [comment]
Sure. My point was that slurping is, conceptually, the splatting in of a set of target positions into the lhs. No need for a separate conceptual framework to understand it. Just “pretend” that the target sequence exists, in a sense; it is then splatted in as a sequence of targets for assignment. My main point was just that there is really no wiggle-room in what it means and how it behaves, which I think is a good thing.

**Comment by mlhetland** [comment]
This symmetry between slurping and splatting (in a sense, just removing a set of parentheses from a tuple, in either case), has at least always been my mental model (also for the equivalent stuff in Python). I almost find it more confusing to treat them as separate ideas; to my mind, it’s just a matter of lhs vs rhs (also in function arguments).

**Comment by cindRoberta** [comment]
> Sorry if I missed something, but I don't understand what the proposals with `§` have to do with this issue. In any case, I think we have perfectly good constructs for slicing up arrays in complicated ways, that fit into the semantics of the language. Introducing a DSL that does this on the LHS seems insufficiently motivated.
> 
> In contrast, the `a, b... = ` syntax would serve a common use case and mirror how function arguments work.

my proposal is simple to understand but unconventional and limited to destructuring (therefore related to this issue), just:

### the a¬[] create a sub-array of other array

```julia
a¬[3:4] = [1, 2, 3, 4, 5] # I think this is better
or ¬a[3:4] = [1, 2, 3, 4, 5]
print(a) # [3, 4]
```

___

### change slice

```julia
a = [1, 2, 3, 4, 5]
a[3:4]¬[1:2] = [6, 7, 8, 9]
or ¬(a[3:4])[1:2] = [6, 7, 8, 9]

# a = [1, 2, 6, 7, 5]
```

___

### creating a sub-array from destructuring:

```julia
a, b, c¬[3:4] = [1, 2, 3, 4, 5] # I think this is better
or a, b, ¬c[3:4] = [1, 2, 3, 4, 5]
# a = 1, b = 2
# c = [3, 4]
```

___

### change slice from destructuring

```julia
c = [6, 7, 8, 9]
a, b, c[1:2]¬[3:5] = [1, 2, 3, 4, 5]
# a = 1, b = 2
# c = [3, 4, 5, 8, 9]
```

**Comment by simeonschaub** [comment]
Should of course be taken with a large grain of salt and I'm not saying we should just follow the majority opinion here, but I was interested in what people naturally expected this to do and did a quick survey on Slack:

![Screenshot from 2020-09-11 22-34-08](https://user-images.githubusercontent.com/5220528/92970965-e1878380-f47f-11ea-884a-2ab8b1740bb9.png)

I was especially surprised that so many people considered returning a tuple for arrays the most useful of all the options, since I would have imagined that returning a vector would be generally preferred. As discussed on the triage call, throwing an error if the rhs isn't a tuple until we have made up our minds about all the other cases might also be a very viable option.

Regarding other languages, I found rust has something a bit like this, but as part of their more general match syntax. They only support slurping for arrays (no tuples, at least for now) with `[a, b @ ..] => ...`. `b` is then a "slice", which are their type for views, but slices are immutable by default, so you need to explicitly specify `mut`, if `b` should be mutated afterwards. But since pattern matching is quite different from destructuring in Julia, I don't know whether that's really comparable.

Since we currently disallow vector expressions on the lhs of assignments, a more speculative proposal would be to support that syntax for destructuring as well, with the difference that `[a, b...] = itr` always collects the rest of `itr` into a vector, whereas for `(a, b...) = itr`, `b` is always a tuple. That still doesn't work for infinite iterators, but to me it seems that they are quite rare in real code and I think it's reasonable to have to explicitly ask for the rest with `Iterators.rest` or `Iterators.drop` in those situations. @JeffBezanson, would be interested to hear your thoughts on that.

**Comment by JeffBezanson** [comment]
Interesting. I can see the case for collecting everything to tuples because that makes it as similar as possible to varargs. But I think that option is horribly NON-useful. It's giving special syntax to the operation "take the tail of this data structure and convert it to a tuple". Why would you have syntax for that? It's very slow and type-unstable for basically every case except tuples. The comparison to varargs is not as reasonable as it seems at first, because we always need to splat out function arguments into a virtual tuple first to inspect all of their types for dispatch. And indeed, splatting large collections is slow. It's a somewhat common performance trap. So trying to be like varargs here would be intentionally copying this negative aspect of the language.


> But since pattern matching is quite different from destructuring in Julia, I don't know whether that's really comparable.

I think it's nearly the same thing. Of course rust has different concerns about mutability that make it hard to copy directly though.

**Comment by simeonschaub** [comment]
Yes, given that, I think probably the best way forward here would be to go with E, i.e. throw an error for anything that's not a tuple, for 1.6, since returning a tuple here should be pretty uncontroversial and probably also the most common case people want to use this syntax for. That would enable us to revisit the other cases later on, once people have already used this syntax a bit, so perhaps we can make a better informed decision then.
The only question that would then remain would be what to lower this syntax to. We could add a method to `Base.tail` that also accepts an index to consume from, but perhaps a separate function that potentially also accepts an iteration state would be more future-proof and extensible and allow for clearer error messages. `Base.rest` may be too confusing, since we already have `Iterators.rest` and this would probably have a different API, right now I called it `Base.slurp_rest`, but I am open to suggestions for better names/APIs.

**Comment by cwindolf** [comment]
In case they're of any interest, here are some emails discussing these questions on a Python developer mailing list in 2007. Not sure how useful the Python perspective is, but thought they were interesting.
 - https://mail.python.org/pipermail/python-3000/2007-May/007378.html
 - https://mail.python.org/pipermail/python-3000/2007-May/007391.html
 - https://mail.python.org/pipermail/python-3000/2007-May/007300.html

**Comment by tpapp** [comment]
In order to pin down the semantics, it would be interesting to see what *concrete* semantics people want this to replace.

Eg I could imagine
```julia
a, b... = c
```
replacing
```julia
a, b = first(c), c[(begin+1:end)]
```
but also variations with `view`, dropping/keeping generalized indexing for `b` (eg if `c::OffsetVector`), etc.

It is not clear that any of these is preferable to the other. Because of this, I think that just using an explicit construct on the RHS is a reasonable alternative.

**Comment by simeonschaub** [comment]
Yes, I agree that finding a semantic that works well for arbitrary array types and iterators is hard, but I think it would be a real shame to give up on this nice syntax altogether. https://github.com/JuliaDiff/ChainRulesCore.jl/issues/128#issuecomment-586716291 is just one example where this would be really useful if it worked at least for tuples. If we only allowed this syntax for tuples for now, I don't see how this would be problematic semantically.

**Comment by tpapp** [comment]
Restricting to tuples would be somewhat confusing, as the `a, b, c = rhs` syntax works for all iterables.

If the user really wants tuples, why not just
```julia
f(t) = first(t), Base.tail(t) # please someone invent a snappy name for f
a, b = f(t)
```

**Comment by simeonschaub** [comment]
> Restricting to tuples would be somewhat confusing, as the a, b, c = rhs syntax works for all iterables.

It wouldn't be a syntax error, it will just error because the analog of `Base.tail` is not defined for arbitrary iterables, which seems reasonable to me, since the latter also only works for tuples.

> If the user really wants tuples, why not just
> 
> ```julia
> f(t) = first(t), Base.tail(t) # please someone invent a snappy name for f
> a, b = f(t)
> ```

Sure, but you could make exactly the same argument against pretty much any syntax feature. I think what `a, b... = t` does should be immediately obvious to anyone familiar with how splatting and slurping works for function calls. Especially in function signatures, like in @oxinabox's [example](https://github.com/JuliaLang/julia/issues/2626#issuecomment-586740630), I just find it easier to figure out what the function is doing using the slurping syntax, than using `Base.tail`. In that example, this change would really make writing `frule`s using ChainRulesCore.jl more intuitive and more consistent with `rrule` for people wanting to write new rules.

**Comment by tpapp** [comment]
>  it will just error because the analog of `Base.tail` is not defined for arbitrary iterables, which seems reasonable to me, since the latter also only works for tuples

I understand that you have a specific use case in mind, but from the discussion it seems that others have a different one (ie it should work for `AbstractVector`) and clarifying what the user expectations are would be useful.

One great feature of the current destructuring is that it just works for *anything* iterable, loosely coupling syntax and types via the iteration interface.

Introducing `a, b... = c` requires taking a stand on how `c` maps to `b`. Eg

1. Saying that only `c::Tuple` is allowed and `b = Base.tail(c)` is *one* option, it plays well with types but happens to be restrictive, especially with the original proposal in mind.

2. Making `b` equivalent to `collect(c)[2:end]` is another option, but it isn't nice for users who want to destructure tuples.

3. Asking that the invariant `(a, b...) == (c...,)` (or similar) is maintained and allowing `b` to be any iterable for which this holds is also an option, which could accomodate tuples and anything iterable. Perhaps this could be done with lowering this syntax to a function that users can define methods for (basically `f` above).

**Comment by rfourquet** [comment]
> Perhaps this could be done with lowering this syntax to a function that users can define methods for (basically f above).

A good candidate might be `peel`, an overloadable/non-lazy equivalent of `Iterators.peel`.

**Comment by simeonschaub** [comment]
> A good candidate might be peel, an overloadable/non-lazy equivalent of Iterators.peel.

`peel` is probably not the best API here, since we don't always want to take just one element from the front. I think to be most friendly to constant propagation, this function should probably accept an iteration state as well as the number of elements in front already consumed, similar to how `iterate_and_index` works. I basically implemented this in #37410 as `slurp_rest`, just with the exception that it only ever produces tuples.

**Comment by jlumpe** [comment]
Would it make sense to introduce this functionality as a `@slurp` macro in the next version and wait and see how it is received before adding the new syntax? This could generate a lot of useful feedback from users regarding the most sensible semantics before making it officially part of the syntax, which would be much more difficult to change/deprecate later.

**Comment by tpapp** [comment]
Yes, and in a package.

**Comment by dsantiago** [comment]
Slurp in the middle would be great too:
```julia
a, b..., c = 1:5
```

**Comment by Witcon** [comment]
> Slurp in the middle would be great too:
> 
> ```julia
> a, b..., c = 1:5
> ```

Yes please, equivalent to python 

```python
first, *_, last = fun()
```

**Comment by simeonschaub** [comment]
This should now work on Julia nightly
