### ISSUE TITLE
`typeof(π/Complex64(2)) == Complex128`

### ISSUE THREAD

**Issue by ettersi** [JuliaLang/julia#26324]
We currently have
```
julia> typeof(π/Complex64(2))
Complex{Float64}
```
This looks like a bug to me. Compare with
```
julia> typeof(π*Complex64(2))
Complex{Float32}

julia> typeof(π/Float32(2))
Float32
```

**Comment by stevengj** [comment]
It's due to [this promotion rule](https://github.com/JuliaLang/julia/blob/f569ebe9bcfdeeae94952d9105c33dbf6b545da7/base/irrationals.jl#L25).

We could add a promotion rule for `Complex`, or we could add a more generic rule of the form:
```jl
promote_rule(::Type{<:AbstractIrrational}, ::Type{T}) where {T<:Real} = promote_type(Float64, T)
promote_rule(::Type{S}, ::Type{T}) where {S<:AbstractIrrational,T<:Number} = promote_type(S, real(T))
```
so that non-`Real` number types use `real` to promote based on the real part.
