### ISSUE TITLE
naming: setdiff, diff, gradient

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#26361]
I think there are a couple issues with these names:

- They have a common suffix but are unrelated.
- Every other function that begins with `set` involves assigning something, e.g. setenv, setfield, setrounding

Other possible names for `setdiff`: difference, complement, without, delete, remove

Other possible names for `diff`: finitediff, differences, decumulate

**Comment by Sacha0** [comment]
Ref. https://github.com/JuliaLang/julia/issues/20041#issuecomment-355351429 and downstream discussion regarding `diff`. Best!

**Comment by stevengj** [comment]
The standard notation for this is `A \ B`, and some authors use `A - B`.  Would one of those be too confusing?

**Comment by KlausC** [comment]
`diff`: I prefer `differences` from the proposals. `decumulate` sounds more general, while I feel, it should be a kind of inverse of `cumsum`. Then also `differences(cumsum(x)) == x` or `cumsum(differences(x)) == x` should hold.

`setdiff`: I would select to `difference` and make `\` an alias for that. At the same time deprecate all set operations when applied to `Tuple{AbstractVector,AbstractVectorVector}`. See also https://en.wikipedia.org/wiki/Set_(mathematics)#Complements

**Comment by StefanKarpinski** [comment]
I’m not sure there’s another reasonable short name for the set difference operation; calling this `setdiff` is quite standard. That said, I’d like an operator for this. I’d be happy to ditch `diff` and introduce `decumulate` which is the proper inverse of `accumulate`.

**Comment by TsurHerman** [comment]
I vote strongly against `decumulate` .. for a non-english speaker this sounds like something Sheldon Cooper from big bang theory would suggest.
diff in Matlab and probably in R and probably in NumPy means finite differencing .. please don't change that name.

If you must change then I vote for `finitediff` but thats is wrong too because there isn't an infinite diff,
also there isn't any diff by factor 2 or 3, the later cases are covered by `gradient` so another option is to deprecate `diff` entirely and rely on `gradient` instead

**Comment by mbauman** [comment]
I would support a general `unaccumulate` (which I think is a slightly better word than `decumulate`, since `decumulate` still sounds like it's cumulative but just doing the inverse operation), but I'd then also want to change the definition such that:

```julia
# pseudocode for one-dimension
unaccumulate(op, A) = unaccumulate(op, A[1], A)
unaccumulate(op, v0, A) = [v0, (op(A[i], A[i-1]) for i in 2:length(A))...]
```

With this definition, `A == accumulate(op, unaccumulate(op, A)) == unaccumulate(op, accumulate(op, A))`.

I think this is a bit of a tangent, though, since, like `cumsum`, we could still provide a helper function with a nicer name.  In that vein, maybe `uncumdiff` :trollface:?

**Comment by JeffBezanson** [comment]
If the names are getting a bit long it seems fine to me to use `accum` instead of `accumulate`.

**Comment by Sacha0** [comment]
👍 for Matt's general `unaccumulate`/`decumulate` definition. Nice to mitigate the common off-by-one-errors that occur with `diff`. Best!

**Comment by stevengj** [comment]
I'm skeptical that anyone will comprehend a neologism like `unaccumulate`, and I'm skeptical of the need for something generic here when people only really seem to use this with `-`…

+1 for merging `diff` into `gradient`, with keyword arguments to specify the different possible boundary conditions and output lengths.

**Comment by bramtayl** [comment]
I think I've seen python overload arithmetic for sets. Maybe + for union, * for intersect, - for setdiff, etc?

**Comment by stevengj** [comment]
[Python uses](https://docs.python.org/2/library/sets.html) `|` for set union, `&` for set intersection, `-` for set difference, and `^` for the symmetric difference.   These are aliases for `union`, `intersection`, `difference`, and `symmetric_difference`.

Julia has synonyms for `∪` (`\cup`) for `union` and `∩` (`\cap`) for `intersect`.  The set-difference operator in Unicode is `∖` [U+2216](http://www.fileformat.info/info/unicode/char/2216/index.htm), but this is so similar to `\` (backslash) that I doubt we would want `∖` as a distinct operator.  (Currently it is unsupported by the parser, I think for this reason.)

**Comment by KlausC** [comment]
I propose to use backslash (like reverse division) and deprecate all set operations on `AbstractArray` (currently set operations with vectors are allowed).

**Comment by stevengj** [comment]
The problem with `\` is that if I see `A \ B` in Julia code I assume it is a linear solve.

Honestly, I think `setdiff` is fine.   I'm doubt that this operation is so common in Julia code that it needs a binary operator.

**Comment by oschulz** [comment]
Personally, I use things like `mean(diff(A))` a lot, especially to take a quick look at data properties, etc. It would be nice to keep this (even under a different name).

**Comment by GunnarFarneback** [comment]
Tangential, but I'm a little puzzled by the interest in `mean(diff(A))` as it can be optimized to `(A[end] - A[1]) / (length(A) - 1)` and thus only depends on the endpoints and length of `A` (or slightly more complicated if `A` is more than one-dimensional).

**Comment by oschulz** [comment]
True, but that was just an example (since @mbauman mentioned it, together with `median`). For `median(diff(A))`, `var(diff(A))`, etc., there isn't such a simple shortcut. :-)

**Comment by StefanKarpinski** [comment]
Triage decided not to do anything here.

**Comment by juliohm** [comment]
Came across this issue today while writing some set differences in some of my own packages. No chance to reconsider the `-` (minus) or `\` (backslash) notation for Set types only? I understand the possible confusion when there are both vectors (as in vector spaces) and sets in the same line of code, but does that confusion eliminate the usefulness of the notation for sets? As mentioned above, we have the nice union and intersection notation. Adding the set difference to these symbols would be great.

```julia
(A ∪ B) - (A ∩ B)
```

reads so much nicer than

```julia
setdiff(A ∪ B, A ∩ B)
```

**Comment by StefanKarpinski** [comment]
I will frequently, if I'm doing a lot of setdiff operations just locally define `const \ = setdiff` and then use backslash. This work pretty well since it's uncommon to do a lot of linear solves in the same codebase as one does lots of set diffs.

While it's somewhat tempting for the syntax, I'm pretty uncomfortable trying to actually stuff setdiff into either `-` or `\`: it's clearly not related to the `\` operation on matrices and if you have `-` for setdiff then it's so very tempting to have `+` for set unions, which is a slippery slope I really don't think we want to go down since sets form a lattice rather than an abelian group.

**Comment by StefanKarpinski** [comment]
It's rather unfortunate that the set minus symbol `∖` looks identical to backslash symbol `\` in so many fonts. If it were reliably double wide, then I think it would be fine to give it this meaning.

**Comment by juliohm** [comment]
I like the setdiff unicode. If we accept the argument that the Unicode can
be confused with backslash and therefore confuse readers of code that
contains both vectors and sets, we also have to accept the argument that
any two types defining + will be confusing in the same context. This is
argument is not very strong in my opinion. People can always type the
explicit setdiff if they think that in some contexts it could be confused
with backslash.

**Comment by StefanKarpinski** [comment]
It's quite important for generic programming to work in Julia that we are strict about generic functions having a single meaning. So far that is working remarkably well. Let's not throw it out just so that we can have a little syntactic convenience.

**Comment by juliohm** [comment]
You mean introducing the unicode syntax would restrict the meaning of setdiff? How does it restrict meaning, I don't get it, appreciate if you can clarify.

**Comment by StefanKarpinski** [comment]
There's no problem with introducing a Unicode symbol for setdiff. However, the obvious Unicode character,`∖`, looks almost identical to `\`, which could potentially lead to confusion.
