### ISSUE TITLE
Methods fail for 0x0 matrices

### ISSUE THREAD

**Issue by haampie** [JuliaLang/julia#26377]
This came up in #26375. `0x0` matrices fail in certain methods:

```
> bkfact(ones(0,0)) # after the pr is merged
ERROR: ArgumentError: requested diagonal, -1, must be at least 0 and at most 0 in an 0-by-0 matrix
> lufact(ones(0,0))
ERROR: ArgumentError: the requested diagonal, 0, must be at least -1 and at most -1 in an 0-by-0 matrix
```

In `bkfact` the  issues are related to Tridiagonal:

- `Tridiagonal(v1,v2,v3)` does not accept three empty vectors.
- `Tridiagonal(A::AbstractMatrix)` calls `diag(A, -1)` and `diag(A, 1)` which are 'outside' the matrix.

In `lufact` the issue has to do with `tril` and `triu`, which is quite confusing.

```
> tril(ones(0,0), -1)
0×0 Array{Float64,2}
> tril(ones(0,0), 0)
ERROR: ArgumentError: the requested diagonal, 0, must be at least -1 and at most -1 in an 0-by-0 matrix
> triu(ones(0,0), 1)
0×0 Array{Float64,2}
> triu(ones(0,0), 0)
ERROR: ArgumentError: the requested diagonal, 0, must be at least 1 and at most 1 in an 0-by-0 matrix
```

**Comment by andreasnoack** [comment]
For `Tridiagonal` the issue is that we require that the diagonal is one element longer than the sub- and superdiagonals. We should relax that to allow for the `0x0` case. Regarding the confusing `tril/u` error messages see https://github.com/JuliaLang/julia/pull/16959 where it was at length. The problem here would go away if we just removed those checks but that was one the proposals in the issue.

**Comment by StefanKarpinski** [comment]
100% just relax the checks to allow the 0x0 case.
