### ISSUE TITLE
call normpath on include("foo/bar.jl") paths?

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/julia#26424]
The forward slash in `abstractdataframe/iteration.jl:33` below should be a backslash.

```julia
julia> DataFrames.eachcol |> methods
# 1 method for generic function "eachcol":
[1] eachcol(df::DataFrames.AbstractDataFrame) in DataFrames at C:\Users\morten\.julia\v0.7\DataFrames\src\abstractdataframe/iteration.jl:33
```

Only appears to be affecting package files (`base` and `stdlib` seemed fine) that are within a subdirectory of `<package>/src/`.

Present on the latest Windows nightly binary, but I am also seeing it on v0.6.2.

```
Julia Version 0.7.0-DEV.4543
Commit 00ac33a3ef* (2018-03-12 04:07 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```

**Comment by mortenpi** [comment]
Yup, it appears that's where it's coming from. The path should probably be normalized?

**Comment by stevengj** [comment]
In general, you have to use `joinpath` for path separators everywhere in Julia.

There is an argument for just allowing forward slashes in all Julia paths, and automatically converting them to backslashes as needed on Windows, since `/` is not valid in Windows filenames.

The argument for doing this *only* in `include` seems much weaker to me.

**Comment by stevengj** [comment]
Moreover, as @mortenpi alludes to, the `normpath` function *already* converts forward slashes to backslashes on Windows, so if we just call `normpath` on the `include` argument that will solve the problem.

But should any *other* file functions use `normpath`?  `open` etcetera?

**Comment by stevengj** [comment]
Alternatively, since Windows path arguments are already converted to a UTF-16 copy by libuv etcetera for handling Unicode paths, we could implement this efficiently in a very low level way, converting slashes in *all* functions that explicitly use a path argument, by doing the slash conversion in-place on the UTF-16 copy.

**Comment by stevengj** [comment]
Actually, I take it back — I misunderstood what is going on here.  [Windows APIs *already* accept forward slashes in paths](https://bytes.com/topic/python/answers/23123-when-did-windows-start-accepting-forward-slash-path-separator).    Backslashes are pretty much only required in command-line applications (to distinguish path separators from `/options`).

So the question here is just whether we should call `normpath` before *displaying* paths, or should we display them as they were entered?

I now am starting to feel like 99% of the uses of `joinpath` in Julia code are useless verbosity.

**Comment by yuyichao** [comment]
Last time I argued for not using `joinpath` it seems that people just don't like the display...... https://github.com/JuliaLang/julia/pull/21395

**Comment by vtjnash** [comment]
> Backslashes are apparently only required

This is a weird part of the Windows API (well, that seems to be said a lot, but I digress). _Technically_, `\\` is the only disallowed character, and `/` is a valid filename. Practically speaking, that's almost never encountered in the wild, since such a file would be invisible to most Windows tools (you should be able to prefix any path with `\\?\` to indicate a desire to be able to access a file with a forbidden name, if necessary, although this particular name would only be valid for WSL or NFS). Hard to know if any of that matters though...

**Comment by stevengj** [comment]
@vtjnash, according to [msdn](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx), both forward and back slashes are "reserved characters" in filenames.

**Comment by vtjnash** [comment]
Yes, but note that the name of that section is "Conventions" not "Rules". Adding `\\?\` to the beginning lets you disable the conventions (although NT or NTFS still rejects most of those characters, including `/`). But at the end of the day, it's up to the file system driver to decide what file names can be represented and which can't. As one post noted though, it's also pretty trivial to alter the FAT file tables with a hex editor and put any character in there that you want, including `/` and `\\` (and also likely rendering that file inaccessible to most if not all file system drivers).
