### ISSUE TITLE
Minor: unix epoch is Float64, not Int64

### ISSUE THREAD

**Issue by iwelch** [JuliaLang/julia#26462]
very minor, but an unusual choice:

```
julia> x= Dates.datetime2unix(Dates.now())
1.521030298628e9

julia> typeof(x)
Float64
```

not sure when Float64 will no longer be able to perfectly represent the integer used most commonly elsewhere.  in any case, it seems unconventional.  just wanted to note it.

/iaw

**Comment by stevengj** [comment]
It's a `Float64` because it is in seconds, but has resolution in milliseconds or better.

Overflow does not seem to be an issue here.  `maxintfloat(Float64) / 3.154e7 ≈ 2.9e8`: the number seconds since the epoch will be represented exactly for almost 300 million years.

Note that the Python `time.time()` function (which also returns the time in seconds since the epoch) also returns a floating-point value.

**Comment by stevengj** [comment]
(You could return the time in nanoseconds as an `Int128`, but that seems harder to work with and the extra precision seems unlikely to be significant.)

**Comment by iwelch** [comment]
did not know about Python.  I was more used to Int versions in other languages.   I did not even know we had ns support in julia.  closing.
