### ISSUE TITLE
document WeakRef

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#26745]
The `WeakRef` type is exported but has no docstring and no other documentation that I can find.

**Comment by stevengj** [comment]
This API leaves something to be desired, however.   Now that we have more efficient union handling, we might revisit #5762 and replace `WeakKey` with a parameterized type `WeakKey{T}`, with the `value` field being a `Union{T,Nothing}`.

**Comment by vtjnash** [comment]
Since it is explicitly tracking an allocated object, there's no performance to be gained from parameterizing it (but some predictability to be lost)

**Comment by stevengj** [comment]
@vtjnash, could you elaborate?  If I have code that operates on a `w::WeakKey` like
```jl
x = w.value 
if x !== nothing
    somefunction(x)
end
```
then currently `somefunction(x)` has to be dispatched dynamically.  On the other hand, if we had `w::WeakKey{T}`, then in principle the compiler could dispatch `somefunction` statically.

That is, working with `WeakKey{T}` objects would have the same performance as working with a `Union{T,Nothing}` type, rather than `Any`.

**Comment by maleadt** [comment]
Ref https://github.com/JuliaLang/julia/issues/35169 for an aspect of WeakRef that should probably be included in the documentation.

**Comment by ancapdev** [comment]
Replying here, since #35169 is closed. This behavior that objects can be accessed after finalizers have run makes ```WeakRef``` much more awkward and difficult to use. It's also contratry to the documentation of ```finalizer(f, x)```:
> Register a function f(x) to be called when there are no program-accessible references to x

Since now through ```WeakRef``` we can resurrect a reference to ```x```.

As a practical example, consider a cache of memory mapped files (byte vectors), where some caching agent opens and maps files, and keeps weak references to these around for re-use within the application. At point of looking up a cached entry, there's no way to distinguish a finalized (i.e., unampped) from non-finalized mapped array. How could this be implemented, without touching ```Mmap.mmap()```? One could of course maintain a hard reference in a proxy object and orchestrate finalization with some additional state tracking to detect this situation, but is that really ideal? What's the use case for accessing objects through ```WeakRef``` post-finalization?

**Comment by tthsqe12** [comment]
It should be noted that it *appears* the undesirable behaviour of #35169 is now gone at least in version 1.6, which guarantees that WeakRef's don't reach finalized objects. It would be great to have developer confirmation here as well as some official documentation.

**Comment by tthsqe12** [comment]
Although https://github.com/JuliaLang/julia/pull/38180 made no mention of WeakRef (only WeakKey?), this is the pr that changed the behaviour of WeakRef.
