### ISSUE TITLE
Semantics of `Expr(:new)` underspecified

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#26764]
The semantics of `Expr(:new)` with missing parameters for immutables are underspecified.
In particular, we need to decide whether the value is _undefined_ or merely _possibly uninitialized_.
The primary difference between the two is how we represent this to LLVM. In particular _undefined_ values may change on every access. As an illustrative example, consider:
```
struct Foo
    x::UInt8
    Foo() = new()
    Foo(x::UInt8) = new(x)
end

function bar(i...)
    f = Foo(i...)
    y = (f.x + UInt8(128))
    if f.x >= UInt8(128)
        println("World")
    end
    if y >= UInt8(128)
        println("Hello")
    end
    return nothing
end
```
What happens when you call `bar()` depends on LLVM versions and other considerations, but on my local copy, it prints nothing. However, any actual `UInt8` value would print either "Hello" or "World". Unfortunately, there isn't really a way to say to llvm "I don't care what this value is, but it always has to be the same". If we decide we do not like the above behavior, we'll have to initialize all (stack? - will have to check what assumptions LLVM makes) allocations visible to LLVM.

**Comment by JeffBezanson** [comment]
We should move towards initializing to zero, unless the cost is prohibitive. I suspect in these cases it's not.

**Comment by StefanKarpinski** [comment]
Or just disallow incomplete construction of immutable structs.

**Comment by JeffBezanson** [comment]
It would be very difficult to define a type like `Nullable` if uninitialized fields are disallowed.

**Comment by KristofferC** [comment]
Opt in to it by forcing putting `undef` in that slot in `new` :trollface:

**Comment by vtjnash** [comment]
If only we had thought to add optimizations to make it more performant to explicitly mark undef by describing the field as having a Union of multiple possible types, rather than to define a type like `Nullable` with possibly-undef fields. And then had deprecated `Nullable` in preparation for v0.7 when that work was largely done.

**Comment by JeffBezanson** [comment]
> explicitly mark undef by describing the field as having a Union of multiple possible types

Not the same as undef, since the value can propagate.

**Comment by JeffBezanson** [comment]
We might be talking about different things. I'm talking about undefined references that throw errors on access, as opposed to `Union{T,Nothing}`, which is how I interpreted Jameson's comment.

It would be ok to have some syntax inside `new` to indicate that a field is undefined (in the current sense). But we couldn't use the first class value `undef` for that, since that means using that value itself as the value of the field. Unlike the Array constructor, where the first argument can mean whatever we want.

**Comment by StefanKarpinski** [comment]
I was talking about what @KristofferC proposed. But I actually don't like that either since if `new(undef)` means what `new()` means now, then how do you write what `new(undef)` means currently?

**Comment by KristofferC** [comment]
> then how do you write what new(undef) means currently?

You don't since that is a useless construct :). But yes, `undef` would have to be "lifted" to be something special and not just a normal singleton.

**Comment by JeffBezanson** [comment]
We could use `@undef`, expanding to a special expression that can only appear inside `new`.

**Comment by StefanKarpinski** [comment]
That would be ok, but I'd be rather worried that we have `#undef`, `undef` and `@undef`.

**Comment by StefanKarpinski** [comment]
Not to mention `Nothing`, `nothing`, `Cvoid`, `Union{}`, `Missing` and `missing`.

**Comment by vtjnash** [comment]
Related to https://github.com/JuliaLang/julia/issues/9147 xref
