### ISSUE TITLE
setrounding/round interaction

### ISSUE THREAD

**Issue by jmkuhn** [JuliaLang/julia#26801]
```
julia> setrounding(Float64, RoundUp)
0

julia> round(1.2)
2.0

julia> round(Int, 1.2)
2

julia> round(1.2, RoundNearest)
2.0

julia> round(Int, 1.2, RoundNearest)
2
```
I expect the last 2 to be `1.0`/`1`.

**Comment by StefanKarpinski** [comment]
The rounding mode affects rounding direction in case of ties. If you want to round down, use the `floor` function instead of the `round` function.

**Comment by jmkuhn** [comment]
I'm not sure what you mean by ties in this case.  We currently have
```
julia> setrounding(Float64, RoundUp)
0

julia> round(1.2)
2.0

julia> round(1.2, RoundDown)
1.0

julia> round(1.2, RoundNearest)
2.0
```
It seems inconsistent to honor `RoundDown` but not `RoundNearest` in this case.

**Comment by simonbyrne** [comment]
I know, it's annoying, but there's not much we can do.

The problem is that LLVM doesn't expose a rounding intrinsic which matches `round(x, RoundNearest)`: the closest they have is [`llvm.rint`](https://llvm.org/docs/LangRef.html#llvm-rint-intrinsic) which depends on the global rounding mode. Presumably at some point they will need one since there is a proposal to introduce `roundeven` function into C, but until that happens, this seems like the least worst option.

One option thing we may want to do is not export `setrounding`, since it is quite unreliable (as LLVM doesn't really yet support rounding mode control), and just mark it off as experimental. Also I think the whole idea for global rounding control is bad, and that we should use something like Cassette.jl, but that's a matter for another day.

**Comment by jmkuhn** [comment]
I agree that the idea for global rounding control is bad.  Since it is exported I was just tying to make it consistent, but without support from llvm I understand your choice.

**Comment by vtjnash** [comment]
> The problem is that LLVM doesn't expose a rounding intrinsic 

It was added recently (http://llvm.org/docs/LangRef.html#llvm-experimental-constrained-rint-intrinsic), although support is likely still considered experimental and limited

**Comment by simonbyrne** [comment]
Not quite: the run time behaviour still depends on the global rounding mode, it just controls the compile time behaviour.

**Comment by simonbyrne** [comment]
`setrounding` has now been deprecated: #27166
