### ISSUE TITLE
Triple-quoted strings treated an expressions in macros

### ISSUE THREAD

**Issue by dcjones** [JuliaLang/julia#2682]
```julia
macro foo(arg)
    println(typeof(arg))
end

@foo("hello")
@foo("""hello""")
```

The first call to foo is ASCIIString the second is Expr. This prevents triple-quoted strings from being used as format strings in printf, among other things.

**Comment by ivarne** [comment]
Marking this as "up for grabs", because it is a pretty annoying issue, and if we are going to fix it, we don't want people to write workaround solutions.

As far as I understand the reason for the whole `mstr` stuff for triple quoted strings is because we want some special de-indentation behaviour that we have implemented in [triplequoted() base/string.jl:1039](https://github.com/JuliaLang/julia/blob/38ef6463f65f51396f9841a531642a6a9b7648bc/base/string.jl#L1039-L1082). It was easier to just emit `@mstr("triple quoted string")` than to implement `triplequoted` in C or scheme, so the current behaviour should be considered a temporary workaround.

Is this a correct work description?
