### ISSUE TITLE
Allow tolerance for `unique`

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#26837]
When working with `Vector`s of floating-point objects, it would be useful to be able to specify a tolerance for `unique`.

**Comment by StefanKarpinski** [comment]
Allowing a tolerance naively requires an O(n^2) algorithm instead of the O(n) hash-based algorithm that `unique` uses. There may be clever ways to make it more efficient (e.g. sorting and bucketing) but I'm not sure that level of cleverness belongs in Base. There's also the issue that adding a tolerance causes the equivalence relation to cease to be an equivalence relation anymore.

**Comment by mbauman** [comment]
At some point you probably just want `hist`.  Er, `fit(Histogram, _)`.

**Comment by dpsanders** [comment]
The use case I had in mind is finding fixed points of functions, e.g. using the Newton method.
Starting from different initial conditions leads to possibly repeated or possibly different fixed points.

But I see that probably this does not belong in Base.
