### ISSUE TITLE
PCRE download link fix is not backported to latest stable release

### ISSUE THREAD

**Issue by greyspectrum** [JuliaLang/julia#26936]
Currently, the v0.6.2 release of Julia will not build successfully, since the build process attempts to download the dependency PCRE from a dead link.

This issue was already fixed in latest/unstable in PR #26757 and backported in PR #26848, but this fix is not reflected in the latest release, here: https://github.com/JuliaLang/julia/releases.

**Comment by vchuravy** [comment]
In order to avoid this problem please use the *full* tarball of the release, which has the corresponding dependencies.
https://github.com/JuliaLang/julia/releases/download/v0.6.2/julia-0.6.2-full.tar.gz

I suspect we won't be able to backport this change to a specific release tag, since that would require changing the tag which in my opinion should be avoided.

**Comment by greyspectrum** [comment]
The release you linked to appears to be unpatched, unless I'm missing something (entirely possible/likely). Specifically, line `8` of `deps/pcre.mk` still has the dead link:

`$(JLDOWNLOAD) $@ https://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-$(PCRE_VER).tar.bz2`
