### ISSUE TITLE
@less misses by one line on Windows

### ISSUE THREAD

**Issue by niclasmattsson** [JuliaLang/julia#27017]
Linux:
```julia
julia> @less 2+2
(+)(x::T, y::T) where {T<:BitInteger} = add_int(x, y)
(*)(x::T, y::T) where {T<:BitInteger} = mul_int(x, y)

inv(x::Integer) = float(one(x)) / float(x)
(/)(x::T, y::T) where {T<:Integer} = float(x) / float(y)
[SNIP]
```
Windows 10:
```julia
julia> @less 2+2
(*)(x::T, y::T) where {T<:BitInteger} = mul_int(x, y)

inv(x::Integer) = float(one(x)) / float(x)
(/)(x::T, y::T) where {T<:Integer} = float(x) / float(y)
[SNIP]
```
Same result on 0.6.2 and latest 0.7 build. Missing by one line makes the macro completely useless on Windows since you can't page backwards with `more`.

**Comment by digital-carver** [comment]
This is a general feature of `more` on Windows - the [documentation](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/more) says "+\<N\>   Displays first file beginning at the line specified by N", but it appears to be more like "Displays first file after skipping N lines in it". 

The fix is probably to change [this line](https://github.com/JuliaLang/julia/blob/master/stdlib/InteractiveUtils/src/editless.jl#L102) in editless.jl to use `$(line-1)` instead of `$(line)`. `more` is able to handle a `+0` argument without issues, so unless the user calls with a 0 or a negative line number (maybe there should be a check for that?), the change shouldn't be problematic.

**Comment by rapus95** [comment]
@digital-carver might you want to open a pull request for it? Got the same problem now

**Comment by rapus95** [comment]
done, see #33587
