### ISSUE TITLE
Add gcd and lcm for Rational

### ISSUE THREAD

**Issue by Paalon** [JuliaLang/julia#27039]
There are no functions for `Rational`.
```julia
gcd(x::Rational, y::Rational) = gcd(x.num, y.num) // lcm(x.den, y.den)
lcm(x::Rational, y::Rational) = lcm(x.num, y.num) // gcd(x.den, y.den)

gcd(a::Rational, b::Rational...) = gcd(a, gcd(b...))
lcm(a::Rational, b::Rational...) = lcm(a, lcm(b...))
```

**Comment by thofma** [comment]
Why not `gcd(x::Rational, y::Rational) = one(typeof(x))` and `gcd(x::Rational, y::Rational) = one(typeof(x))`?

**Comment by Paalon** [comment]
I can't grasp what you mean. If we define `gcd(x::Rational, y::Rational) = one(typeof(x))` then `gcd(1//3, 2//5) == 1//1` but `gcd(1//3, 2//5) == 1//15`.

https://en.wikipedia.org/wiki/Least_common_multiple#Formulas

**Comment by thofma** [comment]
Since the rationals are a field, the gcd will always 1 (we can multiply the gcd with units).

**Comment by thofma** [comment]
The Wikipedia page describes the gcd and lcm of positive rational integers. This is unrelated.

**Comment by Paalon** [comment]
OK, I understand. Julia's `Rational` is the rational field, so gcd and lcm of them are trivial but I want to denote the gcd and lcm of rationals as gcd domain (I don't know how to say).

**Comment by sostock** [comment]
FWIW, I think implementing `gcd`/`gcdx`/`lcm` like originally suggested (so that `gcd(1//3, 2//5) == 1//15`) would be worthwhile because it should lead to the correct behavior of [`intersect(::StepRange, ::StepRange)`](https://github.com/JuliaLang/julia/blob/b5a4601bbe8a6f1b8ce8f4e307543850c08adb8e/base/range.jl#L775-L818), which currently errors for `StepRange{<:Rational}`:

```julia
julia> intersect(1//3:2//3:11//3, 0//1:1//2:4//1) # should be 1//1:2//1:3//1
ERROR: MethodError: no method matching lcm(::Rational{Int64}, ::Rational{Int64})
```

However, for this to work, one would also need to implement `gcdx(::Rational, ::Rational)`, not just `gcd` and `lcm`.

**Comment by KlausC** [comment]
See this [gcd-stackexchange-2012](https://math.stackexchange.com/questions/151081/gcd-of-rationals), specially the last article about extension of `gcd` to rationals and more general.

**Comment by waldyrious** [comment]
IIUC #33910 implemented this. Can someone with the right permissions close the issue?
