### ISSUE TITLE
extra newline displaying markdown objects in REPL

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#27102]
When getting help for a function, or equivalently just displaying a Markdown object, there are now two newlines at the end of the output.

E.g. 0.6:
```
help?> Core.eval
  eval([m::Module], expr::Expr)

  Evaluate an expression in the given module and return the result. Every Module (except those defined with baremodule) has its
  own 1-argument definition of eval, which evaluates expressions in that module.

julia> 
```

and now:
```
help?> Core.eval
  eval([m::Module], expr::Expr)

  Evaluate an expression in the given module and return the result. Every Module (except those defined with baremodule) has its own
  1-argument definition of eval, which evaluates expressions in that module.


julia> 
```

**Comment by fredrikekre** [comment]
I am pretty sure this is #25067, in particular the change here https://github.com/JuliaLang/julia/commit/88cdf44996593f35672984bbd48c867ae8d950a2#diff-e7ece136e201ac8acd4899e1a4af3431R151, which makes it such that we don't sidestep the `println` here https://github.com/JuliaLang/julia/blob/1b92f51ba3544edfcdb70a2f43ac1bb3a7bb5543/stdlib/REPL/src/REPL.jl#L131 anymore (since we now dispatch to the more generic `display` function) cc @stevengj

**Comment by fredrikekre** [comment]
Basically, the `show` method here should not contain a trailing new line:
https://github.com/JuliaLang/julia/blob/1b92f51ba3544edfcdb70a2f43ac1bb3a7bb5543/stdlib/Markdown/src/render/terminal/render.jl#L163

**Comment by stevengj** [comment]
Should be fixed by my PR.
