### ISSUE TITLE
Can't assign variables in current module with the syntax "M.x=y"

### ISSUE THREAD

**Issue by azurefx** [JuliaLang/julia#27318]
```
Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```

I'm trying to assign a global variable with the same name of a keyword argument:
```
module Test
    a=1
    function f(;a=2)
        Test.a=a
    end
end
```
And an exception occurs:
```
julia> Test.f()
ERROR: cannot assign variables in other modules
Stacktrace:
 [1] #f#1 at .\REPL[1]:4 [inlined]
 [2] f() at .\REPL[1]:4
```
Is this the intended behavior? If so, how can I change the binding of global variable 'a' inside f()?
C++ provides the scope resolution operator (::) which can do this.

**Comment by JeffBezanson** [comment]
This is intended. To assign a global variable use `global a = b`. Unfortunately, `global a = ...` doesn't work if `a` is also a local variable or argument of the enclosing function. I suspect we rarely run into this since (1) updating global variables is very rare (or should be!), and (2) globals often use uppercase or some other naming convention to differentiate them from locals.
