### ISSUE TITLE
`median` handles `missing` incorrectly

### ISSUE THREAD

**Issue by traktofon** [JuliaLang/julia#27363]
The `median` function in 0.7.0-alpha handles some cases of `missing` correctly:
```julia
median([1,1,missing])
# 1.0
```
but others not:
```julia
median([1,2,missing])
# 2.0
```
Here the correct answer should IMHO be `missing`.

Another problem is
```
julia> median([1,missing])
ERROR: MethodError: no method matching middle(::Int64, ::Missing)
Closest candidates are:
  middle(::Union{Bool, Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}) at statistics.jl:89
  middle(::Real) at statistics.jl:92
  middle(::Real, ::Real) at statistics.jl:100
Stacktrace:
 [1] median!(::Array{Union{Missing, Int64},1}) at ./statistics.jl:154
 [2] _median(::Array{Union{Missing, Int64},1}, ::Colon) at ./statistics.jl:175
 [3] #median#646 at ./statistics.jl:171 [inlined]
 [4] median(::Array{Union{Missing, Int64},1}) at ./statistics.jl:171
 [5] top-level scope
```
This could be fixed by defining `middle(::T, ::Missing) where {T} = missing`.

Additionally, the help text for `median` suggests to use `skipmissing`, but
```
julia> median(skipmissing([1,2,missing]))
ERROR: MethodError: no method matching median(::Base.SkipMissing{Array{Union{Missing, Int64},1}})
Closest candidates are:
  [...]
```
and instead one must use `median(collect(skipmissing(...)))`. I think this is because `median` in general cannot work with just an iterator, but needs access to the whole array?

**Comment by nalimilan** [comment]
The behavior without `skipmissing` is expected, as `missing` is sorted last by `isless` (though `<` throws). It could be misleading though, given that we tend to throw errors in most other cases. I guess we could add a `!any(ismissing, x)` check, the compiler should be able to optimize it out for inputs which don't allow for missing values.

The error with `skipmissing` is indeed due to the lack of support for iterables. The best solution is probably to add a definition like `median(x) = median!(collect(x))`.

**Comment by nalimilan** [comment]
See https://github.com/JuliaLang/julia/pull/27515.
