### ISSUE TITLE
triple dot deprecation inconsistency

### ISSUE THREAD

**Issue by ZacLN** [JuliaLang/julia#27514]
The `(x...)` syntax for creating a tuple is being deprecated for `(x...,)`, yet when used in an anon function arg list the change is already enforced, i.e. `(x...)->x` parses the lhs as `x...` rather than `(x...,)`

**Comment by JeffBezanson** [comment]
Yeah, this is tricky. I did it this way because `(x...)->x` is not deprecated and will continue to work the same way from a user perspective, so it shouldn't have a warning. Given that there's no warning, I figured it would be better to change the parsing sooner rather than as a surprise breaking change in 1.0.
