### ISSUE TITLE
do not implicitly convert mutables?

### ISSUE THREAD

**Issue by ylxdzsw** [JuliaLang/julia#27543]
I find the current behaviour quite unintuitive 

```julia
julia> mutable struct F x::Vector{Int} end

julia> f = F([])
F(Int64[])

julia> a = f.x = []
0-element Array{Any,1}

julia> push!(a, 1)
1-element Array{Any,1}:
 1

julia> f.x
0-element Array{Int64,1}
```

This is because we [convert values before assignment](https://github.com/JuliaLang/julia/blob/master/base/sysimg.jl#L19) and [copy the whole array when converting](https://github.com/JuliaLang/julia/blob/master/base/array.jl#L463), which ends up with assigning another different array. 

However this is unintuitive since the general meaning of "assigning a mutable" is more like "alias", rather than "copy". As per [the doc](https://docs.julialang.org/en/latest/manual/types/#Mutable-Composite-Types-1), a mutable type is distinct by address. That means when I assigning a mutable, I want to assign the exact one in the RHS, rather than some other thing like it by the content, while conversions by nature return different objects. As far as I know, Julia is the only one who *implicitly copy mutables* in ordinary struct field assignments. (except for C-likes, where variables do not mean "bindings/references to a value")

Since there are no covariance and contravariance in Julia (except for primitive tuples?) and we want to store things as concretely as possible, I would suggest that we disable conversion when trying to assign mutables and simply let different types incompatible. This is consistent with function calls:

```
julia> ff(x::Vector{Int}) = 0
ff (generic function with 1 method)

julia> ff([])
ERROR: MethodError: no method matching ff(::Array{Any,1})
```

It is also consistent with other languages like Java.

**Comment by JeffBezanson** [comment]
Function calls are not really a relevant comparison. Since we pick which method to call based on the type of the argument, it would be pretty confusing if the type of the argument could also change during the process.

Covariance is also not directly relevant, since the same issue exists between `Vector{Int}` and `Vector{Float64}`, where one would never be a subtype of the other.

My policy on these sorts of aliasing issues has been pretty consistent: the code doing mutation needs to take full responsibility for what it's doing. It is not, instead, everybody else's job to arrange things for the safety and convenience of mutating code. For example, a program that doesn't use mutation should work on both mutable and immutable arrays. If we made this change, that wouldn't hold.
