### ISSUE TITLE
make `isequal(-0.0, 0.0)` true?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#27545]
One plausible and tempting upshot of the conversation at https://discourse.julialang.org/t/possible-bug-in-unique-set/5371 is that it might make sense for Julia to sort and hash -0.0 and 0.0 the same. It's a long discussion covering many topics, but it seems that other languages (numerical and otherwise) tend to consider these two values not to be distinct for sorting, uniquing and hashing purposes. This unfortunately does not remove the need for separating `==` and `isequal` but it does reduce the difference somewhat. I don't think this would break much real-world code.

**Comment by StefanKarpinski** [comment]
If there's support for this, I'm willing to do the work since I'm fairly familiar with all the tricky sorting, hashing and numerical comparison code that would have to change for this.

**Comment by chethega** [comment]
As a bonus, to repeat from the discourse: This would allow a faster branch-free (possibly vectorized) version of `min` and `max`: `min(x,y)=ifelse(x<y, x, ifelse(x>y, y, ifelse(y==y, x, y)))`. This is currently not admissible because of `isless(-0.0,0.0)==true`. This would return the second `NaN` for two `NaN`s (just like today) and the first zero for two zeros.

**Comment by stevengj** [comment]
So, for example, if you were using a dictionary to memoize the return value of `f(x)`, the way Memoize.jl does, this would break memoization for `f(x)=1/x` since `x=±0.0` give different results.

**Comment by StefanKarpinski** [comment]
Yes, that would break. OTOH, shouldn't one be using an `IdDict` for that kind of thing?

**Comment by StefanKarpinski** [comment]
I'm confused by your last comment, @stevengj—did you mean to say that it does or doesn't work when the inputs are arrays?

**Comment by stevengj** [comment]
doesn't work, sorry

**Comment by StefanKarpinski** [comment]
Triage: this is appealing but it's just a lot to change _after_ the 0.7-alpha. We've been doing it the other way for a long time now and it's been fine.

**Comment by JeffreySarnoff** [comment]
The preponderance of intent is consensus.  This is a good move -- doing it should keep complex functions working as expected with respect to branch cuts because it does not remove -0.0 from Floating Point processing; it melds the two zeros when -0.0 is hashed or sorted.  Algorithmic uses for -0.0 will still see -0.0 as it arises, so .. signbit(-1.0/Inf) continues to be true.  The assist in throughput and the conceptual clarity that obtains both encourage this.   (so if you're punting for now, consider assigning a label that says -- this is for Julia before the master release occurs.  Otherwise all the thought and working through that this has garnered would have been made not act of the Community).

**Comment by StefanKarpinski** [comment]
For a fairly huge change, this has not attracted much visible support. Based on this thread there are four people who seem to be strongly in favor of this and at least one who is vocally against it with a decent argument.

**Comment by JeffreySarnoff** [comment]
ok :footprints: (taking a stroll)

**Comment by bkamins** [comment]
> So, for example, if you were using a dictionary to memoize the return value of f(x), the way Memoize.jl does, this would break memoization for f(x)=1/x since x=±0.0 give different results.

Agreed, but currently we break it for `NaN` already. E.g.
```
julia> signbit(NaN)
false

julia> signbit(-NaN)
true
```

So for me the question is what is the frequency of the possible problem.

With `NaN` the risk is marginal (that is why no one is complaining), the only real case where this kicks in is:
```
julia> 0.0/0.0 === NaN
false

julia> 0.0/0.0 === -NaN
true
```
and now we have a somewhat surprising result:
```
julia> signbit(0.0/0.0)
true
```

How often `0.0` vs `-0.0` causes a problem - it is hard to tell. I guess, following @StefanKarpinski - given the low response it is also marginally rare.

**Comment by bkamins** [comment]
The key thing that I want to say is that with `NaN` we already have a problem that different values compare by `isequal` as `true` yet they can produce a different result when passed to a function.

To be precise the question was how often a regular users would produce `-0.0`. I think it is much more probable than creating `-NaN` because there are many more cases when this can happen. But if this breaches the "often enough" border - I frankly do not know.

Anyway - I wanted us keep `0.0/0.0===-NaN` case in mind when making a decision (I am not a core dev so probably someone else makes this decision anyway 😄).

**Comment by JeffBezanson** [comment]
We could potentially make `isequal(NaN, -NaN) === false`. As you point out, there are operations where the sign bit of NaN is used.

**Comment by stevengj** [comment]
If we do that we'd probably want to print `-NaN` as `-NaN` too.

**Comment by bkamins** [comment]
AFAIK IEEE Std 754™-2008 (Revision of IEEE Std 754-1985) distingiushes how you should handle `+NaN` and `-NaN`. If we followed the standard strictly then in section 5.10.d specifies it (I am not sure if I can copy-paste it here due to copyright, but probably it is easy to check it).

In short this would change `-NaN` to be less than any other `Float64`.

In general this proposal would mean that we would simply push the "acceptability bar" of being not consistent with IEEE to zero 😄.

**Comment by stevengj** [comment]
Section 5.10.d specifies the behavior of a `totalOrder` predicate, which should give `totalOrder(-NaN, +NaN)` true.   It's true that we don't have such a predicate in Julia.  Does any language provide this?  I'm not aware of a C99 or Fortran function for it, for example.

According to the standard, section 6.3, the only operations that depend on a NaN sign bit are copy (assignment), negate (`-x`), abs, copysign, and totalorder.  It also says:

> For all other operations, this standard does not specify the sign bit of a NaN result, even when there is only one input NaN, or when the NaN is produced from an invalid operation.

Because of this, you can't depend upon the sign bit of a NaN unless you explicitly set it yourself with `-NaN` or `abs(NaN)` or similar.

(There are rare applications that embed "hidden" data in the significand of a NaN, and such applications might conceivably use the sign bit as well.  But for such applications you basically need `===`, not `isequal`.

**Comment by bkamins** [comment]
I am aware of all this (that is why I have shown `0.0/0.0` division example which produces `-NaN` although it is a division of two numbers without sign bit set), and that is why I initially thought that:

* not distinguishing `-NaN` and `+NaN`,
* distinguishing `-0.0` and `0.0`,

was a design decision to make a balance between simplicity and risk of user visible inconsistency with IEEE standard.

In fact the current behavior of Julia in terms of `unique` or `Set` is consistent with Java if I am not mistaken (where there is only one `NaN` but if you put `-0.0` and `0.0` into a `HashSet` they are different entries). So Julia is not the only language with the user-exposed behavior we currently have (although Julia allows `-NaN` and Java does not, the end-user experience is the same now).

**Comment by StefanKarpinski** [comment]
It's a good data point that Java does this the same as us.

**Comment by bkamins** [comment]
Just to make sure how Java works exactly I have checked its source.
The precise situation is the following: you can store different `NaN` values in `double` type, but in normal usage they are masked by a single `NaN` value.
So I would say that it is pretty much the same we have in Julia (the only difference is that a normal operation transforming `NaN` to `long` in Java will produce the same result no matter what `NaN` you have and you have to use a special "raw" access mode to get the bits actually stored in `NaN`).

**Comment by JeffreySarnoff** [comment]
If you are going to allow NaN payloads to be other than zero, that there can be positive and negative payloads is useful.  It allows the adoption of a very fast two-sorted carrier of exception characterizing information.
