### ISSUE TITLE
Feature request: Implement `atan2d` (or `atand2`)

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#27615]
Hi guys,

We have `asin` and `asind`, `acos` and `acosd`, `atan` and `atand`. Hence, I think it makes sense to also have `atan2d` or `atand2`, which is the degree version of `atand`.

**Comment by GunnarFarneback** [comment]
`atan2` is now the two argument version of `atan` though, so the request should rather be for a two argument version of `atand`.

**Comment by ronisbr** [comment]
Yes, this is what I meant :)

**Comment by staticfloat** [comment]
Yes, this seems like a simple oversight, due to the fact that `atan(y, x)` is a special-case function and doesn't follow the metaprogramming pattern that the other trig functions follow in that file. (e.g. see how most of the degrees functions are defined [down at the bottom of the file](https://github.com/JuliaLang/julia/blob/91d2071f0776ceb4c53bc95277ba967aaa0a5608/base/special/trig.jl#L1085-L1094).

I think it would be just fine to open a PR adding a line below that for loop, adding an entry for `atand(y, x) = rad2deg(atan(y, x))`

**Comment by ronisbr** [comment]
I will do this! thanks

**Comment by ronisbr** [comment]
@staticfloat done! I did a little more modifications so that we have a good docstring describing that `atand` have 1 and 2 argument versions, like `asind` for example.

**Comment by Nosferican** [comment]
Out of curiosity, if the functions with a `d` at the end are just calling `rad2deg` to the output, would it be better to just use a keyword argument `rad::Bol = True` now that keywords are efficient?
