### ISSUE TITLE
[LinearAlgebra] LU-factorization failure (0.7.0-alpha.0)

### ISSUE THREAD

**Issue by cdluminate** [JuliaLang/julia#27657]
```julia
julia> A = [1 0 0; .5 1 0; 1 2 1] * [2 0 0; 0 2.5 0; 0 0 0] * [1 -.5 1.5; 0 1 -.2; 0 0 1]
3×3 Array{Float64,2}:
 2.0  -1.0  3.0
 1.0   2.0  1.0
 2.0   4.0  2.0

julia> lu(A)
Failed factorization of type LU{Float64,Array{Float64,2}}

julia> VERSION
v"0.7.0-alpha.0"
```

However Julia 0.4.7 can factorize it

```julia
julia> A = [1 0 0; .5 1 0; 1 2 1] * [2 0 0; 0 2.5 0; 0 0 0] * [1 -.5 1.5; 0 1 -.2; 0 0 1]
3x3 Array{Float64,2}:
 2.0  -1.0  3.0
 1.0   2.0  1.0
 2.0   4.0  2.0

julia> lu(A)
(
3x3 Array{Float64,2}:
 1.0  0.0  0.0
 1.0  1.0  0.0
 0.5  0.5  1.0,

3x3 Array{Float64,2}:
 2.0  -1.0   3.0
 0.0   5.0  -1.0
 0.0   0.0   0.0,

Int32[1,3,2])

julia> VERSION
v"0.4.7"
```

So does octave.

**Comment by haampie** [comment]
See: https://github.com/JuliaLang/julia/pull/27336

On master you'd do `lu(A, check = false)` which does not throw. 

Maybe `check = false` should be the default? If you only want to compute the factorization, there's probably little reason to throw?

**Comment by haampie** [comment]
But the factorization can be completed for a singular matrix. From Netlib:

```
*  INFO    (output) INTEGER
*          = 0:  successful exit
*          < 0:  if INFO = -i, the i-th argument had an illegal value
*          > 0:  if INFO = i, U(i,i) is exactly zero. The factorization
*                has been completed, but the factor U is exactly
*                singular, and division by zero will occur if it is used
*                to solve a system of equations.
```

So maybe we should throw on `info < 0`, but not on `info > 0`. We probably throw anyways in `div` functions when singular matrices are provided.

**Comment by andreasnoack** [comment]
`info < 0` won't happen since we check the arguments. Notice that the reported behavior isn't an exception being thrown so the behavior of latest master is different
```julia
julia> lu(A)
ERROR: SingularException(3)
Stacktrace:
 [1] checknonsingular at /Users/andreasnoack/julia-dev/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/factorization.jl:12 [inlined]
 [2] #lu!#91(::Bool, ::Function, ::Array{Float64,2}, ::Val{true}) at /Users/andreasnoack/julia-dev/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:30
 [3] #lu#95 at ./none:0 [inlined]
 [4] lu at /Users/andreasnoack/julia-dev/usr/share/julia/stdlib/v0.7/LinearAlgebra/src/lu.jl:131 [inlined] (repeats 2 times)
 [5] top-level scope at none:0

julia> lu(A, check = false)
Failed factorization of type LU{Float64,Array{Float64,2}}
```
I think this is reasonable but we could consider changing `Failed factorization` to `Singular factorization` in the latter case.

**Comment by simonbyrne** [comment]
I think we should still print out the object instead of `Failed factorization` since I keep thinking that is an exception.

**Comment by simonbyrne** [comment]
perhaps we should also rename `check` to `allowsingular`?

**Comment by haampie** [comment]
Concerning the `check = true` case:

Technically it is only a real exception _without_ pivoting; a naive implementation would then divide by zero at some point, so it should throw.

_With_ pivoting, the algorithm searches for the value of largest magnitude in the active part of the column, and uses that as pivot. If there's only zero's, it can just skip to the next step. This yields a valid LU decomp without ever having to throw an exception because of division by zero.

So, with `check = true` _and_ pivotting, maybe it's better not to throw at all. Without pivoting, yes, it makes sense.

**Comment by StefanKarpinski** [comment]
Isn't the factorization fine unless you try to do division?

**Comment by simonbyrne** [comment]
Sure, but why else would you compute the LU?

**Comment by StefanKarpinski** [comment]
(a) curiosity, (b) to see if it's singular, (c) because they feel like it, (d) for some other reason we haven't thought of. Who are we to tell people what are legitimate or illegitimate reasons to compute the LU factorization are? As long as they don't try to use it for division, why not let them do it. When they actually do something where a singular factorization is a problem, that is the time to throw an error.

**Comment by simonbyrne** [comment]
I guess the main reason is that people may try to use the object directly (e.g. `F.L` and `F.U`) without first checking: this was the reason we made the change for `Cholesky`, and it seemed reasonable to do it for all factorizations.

I don't think a keyword option is too onerous of a barrier for this.

**Comment by StefanKarpinski** [comment]
But isn't the factorization still valid in the singular case? I.e. aren't the `F.L` and `F.U` components still right? Is the issue that in the singular case one of the factors will be singular but the other one may not be so if someone uses only one of them, they can fail to realize that the decomposition is singular?

**Comment by haampie** [comment]
> Sure, but why else would you compute the LU?

Another use case is to do an in-place matrix-matrix product: if you wanna compute `V := V * Q` and you have `Q = L * U`, then `V := ((V * L) * U)` can be computed in-place.

**Comment by andreasnoack** [comment]
> I guess the main reason is that people may try to use the object directly (e.g. `F.L` and `F.U`)

This is exactly the reason. Previously we delayed the exception until users called `\` on the factorization but that didn't work when factors are extracted so the conservative solution was to throw by default. It might be overly cautious since the triangular solve will throw if it hits an exact zero. As @haampie points out, the factorization is only *invalid* when without pivoting. However, currently we store the pivoted and un-pivoted LU in the same struct so we don't know if the algorithm did pivoting (and the permutation just happened to end up as the identity).

It might also be worth noting that exact zeros in floating point LU are quite rare in real use cases. The smallest rounding errors will make it a non-zero
```julia
julia> A = [1 0 0; .5 1 0; 1 2 1] * [2 0 0; 0 2.5 0; 0 0 0] * [1 -.5 1.5; 0 1 -.2; 0 0 1];

julia> A[3,3] = nextfloat(A[3,3]);

julia> lu(A)
LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0  0.0  0.0
 1.0  1.0  0.0
 0.5  0.5  1.0
U factor:
3×3 Array{Float64,2}:
 2.0  -1.0   3.0
 0.0   5.0  -1.0
 0.0   0.0  -2.22045e-16
```

> Another use case is to do an in-place matrix-matrix product:

I guess this is pretty rare though.

**Comment by perrutquist** [comment]
I just ran into this issue when doing Rayleigh quotient iteration with `BigFloat`s.
I agree that It is a good thing to throw an exception rather than returning a wrong result, but in this case Julia is throwing rather than returning the *right* result. It is not a "failed factorization", the product `F.P'*F.L*F.U` is exactly equal to the original matrix! (As it happens, I am now interested in the null space of `F.U`.)

I would suggest only throwing if `lu` was called with `pivot=false` even though pivoting would be necessary to complete the factorization.

**Comment by andreasnoack** [comment]
You are right that `!issuccess` currently covers both the cases when the factorization is invalid and when it is singular and that the message printed therefore is inaccurate. That can fixed in several ways where the easiest would be to change the wording of the message as mentioned in https://github.com/JuliaLang/julia/issues/27657#issuecomment-398513557. If you don't want your LU to throw then you can set `check=false` and it could just print something like
```julia
singular or failed LU factorization. If pivoting was enabled the matrix is detected to exactly singular otherwise the matrix could be either singular or have a zero pivot.
```

> Since a correct factorization of a singular matrix is not technically a "failure", how about replacing the function issuccess by a function issingular? 

Using the LU for detecting singularity is not reliable for floating point values so I don't think it is a good idea to introduce such a function.

> The returned matrices are not even a factorization, so why not simply throw?

See https://github.com/JuliaLang/julia/issues/27657#issuecomment-398581920. It can be useful to have access to the failed factorization. I'm not aware of applications for a failed LU but it is useful for the Cholesky so it might also be for the LU.

**Comment by Eetion** [comment]
LU decomposition of singular arrays is the basic computation on which much of _topological data analysis_ is built.  Several of the most prominent libraries in this field is written in pure Julia, but they rely on very customized DIY solutions.  If there's any way to make this functionality generally available, it would be a service to the scientific community.

**Comment by andreasnoack** [comment]
@Eetion I’m not sure what exactly what you are asking for here.

**Comment by Eetion** [comment]
@andreasnoack Thanks; that note derived from a misunderstanding (now clarified).  I'll just point out what happened, in case the same occurs to someone else.  After reading this thread I ran

```
julia> A = [1 0 0; .5 1 0; 1 2 1] * [2 0 0; 0 2.5 0; 0 0 0] * [1 -.5 1.5; 0 1 -.2; 0 0 1]
3×3 Array{Float64,2}:
 2.0  -1.0  3.0
 1.0   2.0  1.0
 2.0   4.0  2.0
julia> F = lu(A, check=false)
Failed factorization of type LU{Float64,Array{Float64,2}}
```

I now know that `Failed factorization` is a noun phrase that describes the output of the `lu` function.  At the time, I thought it was a verb phrase, namely an *error message* that stated that Julia did not support this kind of factorization, even with `check=false`.  I don't know if there's a practical way to change the text, but I'd guess that other users (particularly ones who aren't familiar with Julia-style text formatting) might get confused on this same point, too.  Thanks!

**Comment by ViralBShah** [comment]
Yes, the `check` is counter-intutitive.

**Comment by ViralBShah** [comment]
Seems like you don't get a factorization either ways:

```
julia> A
3×3 Matrix{Float64}:
 2.0  -1.0  3.0
 1.0   2.0  1.0
 2.0   4.0  2.0

julia> lu(A, check=false)
Failed factorization of type LU{Float64, Matrix{Float64}, Vector{Int64}}

julia> lu(A, check=true)
ERROR: SingularException(3)
```

**Comment by perrutquist** [comment]
I would argue that you do get a factorisation in the first case:
```
julia> A
3×3 Matrix{Float64}:
 2.0  -1.0  3.0
 1.0   2.0  1.0
 2.0   4.0  2.0

julia> F = lu(A, check=false)
Failed factorization of type LU{Float64, Matrix{Float64}}

julia> F.P' * F.L * F.U == A
true
```

As stated above, It is confusing (and wrong) to display this factorisation as "failed". Imo, it should be displayed just like any other LU factorisation,  but maybe with a note that it is rank deficient next to the `U` factor.

**Comment by danielwe** [comment]
Was tripped up by this recently via Symbolics.jl, which conforms to base Julia's behavior and throws if there is a zero pivot. This is particularly unfortunate for symbolics and rational types where you get exact zeros all the time. For example, LU is a natural starting point to solve symbolically for the column space of a singular matrix.

With the current docs ("When `check = true`, an error is thrown if the decomposition fails") and printout (`Failed factorization of type LU{...}`), even a person who knows the mathematical internals of the LU decomposition would be led to believe that the returned object with `check=false` is garbage unless they dive into the actual code and compare with LAPACK documentation. https://github.com/JuliaLang/julia/issues/27657#issuecomment-1065972220 is a case in point. The docs and printout could be fixed in an upcoming point/patch release even if changing behavior or renaming keywords must be put off for backward compatibility, right?

Long-term, though, it would be great to separate the behavior with respect to actual failures, controlled by `check` (e.g., when `pivot=false` and the matrix is singular), from the behavior with respect to zero pivots in valid decompositions, controlled by a new keyword such as `allowsingular`.

**Comment by stevengj** [comment]
Since the factorization argument has an [`info` field](https://github.com/JuliaLang/julia/blob/b058146cafec8405aa07f9647642fd485ea3b5d7/stdlib/LinearAlgebra/src/lu.jl#L53), we can easily use this to distinguish between actual failures (`info < 0`) and singular factorizations (`info > 0`).

At the very least, we can change how singular factorizations (`info > 0`) are displayed, even if we don't change the `issuccess(F)` return value for backwards-compatibility reasons.
