### ISSUE TITLE
Spurious warning for "begin" in some arrays

### ISSUE THREAD

**Issue by RalphAS** [JuliaLang/julia#27690]
The parser is confused by this:
```
julia-0.7> struct Foo
           x::Vector{Expr}
           end

julia-0.7> foos = Foo[Foo([:(begin; println(); end)])]
┌ Warning: Deprecated syntax `"begin" inside indexing expression` at REPL[2]:1.
└ @ nothing REPL[2]:1
1-element Array{Foo,1}:
 Foo(Expr[quote
    #= REPL[2]:1 =#
    println()
end])
```
Oddly enough, the warning goes away if we make the compiler figure out the array type:
```
julia-0.7> foos2 = [Foo([:(begin; println(); end)])]
1-element Array{Foo,1}:
 Foo(Expr[quote
    #= REPL[3]:1 =#
    println()
end])
```
Last checked on Version 0.7.0-alpha.154

(This pattern is actually used in Plots.jl.)

**Comment by martinholters** [comment]
The idea is that you can eventually use `begin` similar to `end` in indexing expressions, like `x[begin:begin+4]` to take the first 5 elements. This is useful for e.g. an `OffsetArray` `x`, where `begin` is not just `1`. Hence, due to potential ambiguity, using `begin` inside an indexing expression is deprecated, and your first example is actually parsed as indexing into the type `Foo`. The second example is a `vect` expression, where so such ambiguity arises, so `begin` is still allowed there.

**Comment by RalphAS** [comment]
Sure, the rationale for the deprecation in similar cases makes sense.

However I thought that this:
```julia
julia-0.7> dump(:(Foo[Foo([:(begin; println(); end)])]))
┌ Warning: Deprecated syntax `"begin" inside indexing expression` at REPL[3]:1.
└ @ nothing REPL[3]:1
Expr
  head: Symbol ref
  args: Array{Any}((2,))
    1: Symbol Foo
    2: Expr
      head: Symbol call
      args: Array{Any}((2,))
        1: Symbol Foo
        2: Expr
          head: Symbol vect
          args: Array{Any}((1,))
            1: Expr
              head: Symbol quote
              args: Array{Any}((1,))
                1: Expr

```
meant that the parser eventually recurses into the embedded expression, thereby burying the "begin" so there would not be a potential ambiguity? (Since the quoted expression with `begin` is inside a subsidiary `vect`.)

**Comment by martinholters** [comment]
Ah, true, there is no reason to treat `begin` and `end` inside a quote inside an indexing expression special, I guess.
