### ISSUE TITLE
Build tarballs for all platforms

### ISSUE THREAD

**Issue by barche** [JuliaLang/julia#27740]
When using BinaryBuilder to build a package that links to libjulia itself (e.g. CxxWrap), it is currently difficult (or for 0.7 impossible) to cross-compile against the official Julia binaries, because .exe and .dmg are not easy to extract. This could be solved by providing logically-named tarballs for each platform, ideally all in the same directory and using the BinaryBuilder `$target` environment variable, so they could be downloaded in the build script using something like this:

```bash
curl -L 'https://julialang-s3.julialang.org/bin/tarballs/julia-0.6-$target.tar.gz' | tar -zx --strip-components=1
```

A detailed discussion of the kind of errors that appear with the current system is here:
https://github.com/JuliaInterop/libcxxwrap-julia/pull/5

CC @staticfloat

**Comment by staticfloat** [comment]
I have (finally) gotten around to doing this.  I triggered some builds, which have uploaded tarballs (I'm only listing mac and windows builds, since those are the only ones which tarballs aren't usually generated for):

* https://s3.amazonaws.com/julialangnightlies/pretesting/winnt/x64/1.6/julia-2f326f73cc-win64.tar.gz
* https://s3.amazonaws.com/julialangnightlies/pretesting/winnt/x86/1.6/julia-2f326f73cc-win32.tar.gz
* https://s3.amazonaws.com/julialangnightlies/pretesting/mac/x64/1.6/julia-2f326f73cc-mac64.tar.gz

These will get automatically uploaded for each commit.  Next, we just need someone to mirror these somewhere permanent (like GitHub releases), then create a JLL package with an Artifacts.toml pointing to those mirrored locations, and we're good to go.

**Comment by barche** [comment]
I was tempted to close this, but it still seems that not all tarballs are generated in a consistent way. On 1.5.0, for example, `armv7l` seems to be missing ( see https://github.com/JuliaPackaging/Yggdrasil/pull/1439 )

**Comment by brenhinkeller** [comment]
Is this fixed now?

**Comment by barche** [comment]
Yes, the libjulia JLL solves this. Ref: https://github.com/JuliaPackaging/Yggdrasil/tree/master/L/libjulia
