### ISSUE TITLE
IPv6 Socket test failures on Travis

### ISSUE THREAD

**Issue by martinholters** [JuliaLang/julia#27788]
In https://travis-ci.org/JuliaLang/julia/jobs/396261047, there are two interesting failures in the Sockets tests:
```
  Got exception UDP send failed: address not available (EADDRNOTAVAIL) outside of a @test
  UDP send failed: address not available (EADDRNOTAVAIL)
  Stacktrace:
   [1] try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at ./event.jl:196
   [2] wait() at ./event.jl:255
   [3] wait(::Condition) at ./event.jl:46
   [4] stream_wait(::Sockets.UDPSocket, ::Condition) at ./stream.jl:47
   [5] send(::Sockets.UDPSocket, ::Sockets.IPv6, ::UInt16, ::String) at /home/travis/build/JuliaLang/julia/usr/share/julia/stdlib/v0.7/Sockets/src/Sockets.jl:355
   [6] top-level scope at /tmp/julia/share/julia/stdlib/v0.7/Sockets/test/runtests.jl:237
```
and
```
  Got exception InexactError(:trunc, UInt16, 65536) outside of a @test
  InexactError: trunc(UInt16, 65536)
  Stacktrace:
   [1] throw_inexacterror(::Symbol, ::Type, ::Any) at ./boot.jl:567
   [2] checked_trunc_uint at ./boot.jl:597 [inlined]
   [3] toUInt16 at ./boot.jl:669 [inlined]
   [4] Type at ./boot.jl:720 [inlined]
   [5] convert at ./number.jl:7 [inlined]
   [6] Type at /home/travis/build/JuliaLang/julia/usr/share/julia/stdlib/v0.7/Sockets/src/IPAddr.jl:249 [inlined]
   [7] Type at /home/travis/build/JuliaLang/julia/usr/share/julia/stdlib/v0.7/Sockets/src/IPAddr.jl:253 [inlined]
   [8] listenany(::Sockets.IPv6, ::UInt16) at /home/travis/build/JuliaLang/julia/usr/share/julia/stdlib/v0.7/Sockets/src/Sockets.jl:571
```

My guess is that the `+1` on these lines may result in the invalid port 65536, causing the respective exceptions:

https://github.com/JuliaLang/julia/blob/bd13437ea7c5095cf501c68a4305e9ddb90fcf84/stdlib/Sockets/test/runtests.jl#L234-L237

https://github.com/JuliaLang/julia/blob/bd13437ea7c5095cf501c68a4305e9ddb90fcf84/stdlib/Sockets/src/Sockets.jl#L571

**Comment by StefanKarpinski** [comment]
These should both probably wrap around at `typemax(UInt16)`. cc @Keno, @vtjnash

**Comment by Keno** [comment]
> These should both probably wrap around at typemax(UInt16)

Yes, that seems right. Though with an error if it wraps all the way around and we may want to skip the privileged ports.

**Comment by Keno** [comment]
Actually @vtjnash points out that in order for to happen, literally all ports need to be taken up (since we start the listenany at a random port between 2000 and 4000). It would be good to dump to temporarily change this test to dump out `netstat -an` when this test fails so we can get an idea of why the ports are all taken).

**Comment by c42f** [comment]
Ok after some digging I think this is because GCE (and hence Travis) doesn't support ipv6. Not even on the loopback device :-(

To repro this on a linux machine, disable ipv6 

```
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
```

Then run the Sockets tests.

See also https://github.com/travis-ci/travis-ci/issues/3302 https://github.com/restify/node-restify/issues/1545#issuecomment-341360182

**Comment by c42f** [comment]
> GCE (and hence Travis) doesn't support ipv6

... It's more complicated than this as successful Travis jobs also appear to run on the same GCE infrastructure, at least on the face of it. But regardless of that the repro seems solid.

**Comment by vtjnash** [comment]
Yes, we run the inverse of that line to re-enable IPv6 support after TravisCI approximately executes the commands you gave to disable it. That's why the tests usually pass, since stock GCE in the default configuration doesn't fail these tests. It's also why we run with sudo-enabled builds (where we can undo their mistake) and are unable to run in the containerized environments.
https://github.com/JuliaLang/julia/blob/566059bf389d9d0ab886b4cbdfce5f046a040f5a/.travis.yml#L66

> this is because GCE

It's not, although it seems like something must be different about those machines. This seems to be a misinformation campaign spread by CI companies (CircleCI makes the same unnecessary claim*). The information in https://github.com/travis-ci/travis-ci/issues/3302 is pretty absurd, since they blame the cloud host, GCE, AWS, etc. for the lack of IPv6 on loopback, but the file that disables it is actually something that they inject into the machine configuration and was not present in the normal GCE environment.

\* similar discussions on CircleCI include https://discuss.circleci.com/t/ipv6-support/13571/9, https://ideas.circleci.com/ideas/CCI-I-571. Although, IIRC, we stopped using them because we couldn't run the Socket tests there.

**Comment by c42f** [comment]
Thanks Jameson. I see you added that Travis tweak in #22986. People saw similar symptoms way back in #13076.

Even with the sudo build and the line to re-enable ipv6 it looks like it's sporadically unavailable (at least, turning it off locally gives the exact same error messages which I've seen on these failed builds).

**Comment by c42f** [comment]
Well since Travis use is discontinued now, I guess we can close this :tada:
