### ISSUE TITLE
Performance of array-grow for union-arrays

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#27825]
"The performance issue is caused by O(n^2) time in memmove at array.c:844."

**Comment by quinnj** [comment]
@vtjnash, are you working on this? I actually think I have a pretty good handle on it. Instead of storing the type-tag bytes directly after the last array element, if we store them after `a->maxsize`, that should make the fast-path as fast as non-isbits Union Arrays since we can avoid the `memmove`. We just have to make sure all the `getindex`/`setindex!` code/codegen use `a->maxsize` instead of `jl_arraylen(a)`. I can probably get a PR ready by tomorrow sometime.

**Comment by vtjnash** [comment]
I haven't started work on it, no. That sounds right, but just note that `a->maxsize` only applies to `ndims == 1`, otherwise, it'll need to continue to use `jl_arraylen(a)`.

**Comment by nalimilan** [comment]
See https://github.com/JuliaLang/julia/pull/27924.
