### ISSUE TITLE
Compiler has trouble tracking extra conditionals

### ISSUE THREAD

**Issue by matthieugomez** [JuliaLang/julia#27961]
Adding an extra conditional in the iteration protocol makes it much slower.

```julia
function g(iter)
   x = iterate(iter)
   while (x !== nothing) && true
       v, state = x
       x = iterate(iter, state)
   end
end
@time g(zeros(1_000_000))
#>   0.234451 seconds (3.01 M allocations: 69.074 MiB, 2.08% gc time)

function h(iter)
   x = iterate(iter)
   while (x !== nothing)
       v, state = x
       x = iterate(iter, state)
   end
end
@time h(zeros(1_000_000))
#>   0.005008 seconds (10.46 k allocations: 8.162 MiB)
```
Reference: https://discourse.julialang.org/t/new-iteration-protocol-much-slower/12169

**Comment by vtjnash** [comment]
I've looked into this before. With the current inference design, we can only track exactly one Slot dependency (the last one before the branch, in this case `true`). Fixing this will require redesigning inference much more significantly (to permit general reverse inference, rather than just the current `Conditional` hack).

We might want to just add a special case to lowering to match this pattern and generate a nested if statement instead of actually computing the boolean condition, so that inference can see this as a sequence of branches instead of a sequence of Bool values.

**Comment by laborg** [comment]
I can't reproduce this anymore:
```
julia> x = zeros(Int,1_000_000);

julia> function g(iter)
          x = iterate(iter)
          s = 0
          while (x !== nothing) && true
              v, state = x
              s += v
              x = iterate(iter, state)
          end
          return s
          end
g (generic function with 1 method)

julia> function h(iter)
          x = iterate(iter)
          s = 0
          while (x !== nothing)
              v, state = x
              s += v
              x = iterate(iter, state)
          end
          return s
          end
h (generic function with 1 method)

julia> @btime g(x)
  824.236 μs (0 allocations: 0 bytes)
0

julia> @btime h(x)
  824.655 μs (0 allocations: 0 bytes)
0
```
Can this be closed?
