### ISSUE TITLE
mapreduce(abs, max, Int[]) returns 0

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#28028]
```julia
julia> mapreduce(abs, max, Int[])
0

julia> mapreduce(abs2, max, Int[])
0

julia> mapreduce(identity, max, Int[])
ERROR: ArgumentError: reducing over an empty collection is not allowed
```

I see the mathematical justification for these two special cases, but they seem too clever for me. They also raise several questions:
- why not add specializations for other functions which only return positive values (e.g `exp`)?
- why not return `Inf`/`-Inf` or `typemax(T)`/`typemin(T)` for all functions?

See also this discussion in Numpy: https://github.com/numpy/numpy/issues/5032

**Comment by nalimilan** [comment]
See also https://github.com/JuliaLang/julia/pull/27845.  Cc: @andreasnoack

**Comment by andreasnoack** [comment]
To handle the empty case in general, we'd probably have to be able to reason about the range of the function which isn't and probably won't ever be possible. However, the current special casing behavior isn't wrong. Maybe just not that elegant. Returning `Inf/-Inf` or `typemax(T)/typemin(T)` instead of throwing would be wrong though. It also wouldn't avoid the exception in general since e.g. `typemax(BigInt)` isn't defined.

**Comment by simonbyrne** [comment]
This is also discussed in #28535.

**Comment by vtjnash** [comment]
Triage approved and will merge this in https://github.com/JuliaLang/julia/pull/29919
