### ISSUE TITLE
we don't infer Core._apply when passed to itself

### ISSUE THREAD

**Issue by jrevels** [JuliaLang/julia#28070]
```julia
julia> g(f, args...) = f(args...)
g (generic function with 1 method)

julia> @code_typed g(Core._apply, Base.:/, (1.0, 1.0))
CodeInfo(
1 1 ─ %1 = getfield(%%args, 1)::typeof(/)        
  │   %2 = getfield(%%args, 2)::Tuple{Float64,Float64}         
  │   %3 = %%f(%1, %2)::Any                                                       
  └──      return %3                                                
) => Any
```

Something similar might also be the case for other builtins we could special-case better, like `Core.tuple`.

**Comment by martinholters** [comment]
In order to infer `_apply`, we need the argument expressions in addition to the argument types:
https://github.com/JuliaLang/julia/blob/0f4b15a59ca35c9fbf635b2747add43a34120979/base/compiler/abstractinterpretation.jl#L520-L524
However, for the function call generated by the `_apply`, we don't have the expressions, so we substitute the empty tuple:
https://github.com/JuliaLang/julia/blob/0f4b15a59ca35c9fbf635b2747add43a34120979/base/compiler/abstractinterpretation.jl#L474
It might be possible to relax the constraint that inference of `_apply` requires the argument expressions (at the cost of potentially less precise results in that case), I'll take a look.

**Comment by martinholters** [comment]
I have a reasonable patch that yields:
```julia
julia> @code_typed g(Core._apply, Base.:/, (1.0, 1.0))
CodeInfo(
1 1 ─ %1 = getfield(%%args, 1)::typeof(/)                                                                                     │
  │   %2 = getfield(%%args, 2)::Tuple{Float64,Float64}                                                                        │
  │   %3 = %%f(%1, %2)::Float64                                                                                               │
  └──      return %3                                                                                                          │
) => Float64
```
As it doesn't specialize on the type of `Base.:/`, the generated code is not pretty, but inference succeeds. Tests running locally, will open a PR once they pass.
