### ISSUE TITLE
LinearIndices behavior change

### ISSUE THREAD

**Issue by barche** [JuliaLang/julia#28503]
With PR #26775 the behavior of indexing into a `LinearIndices` object was changed when the referred range does not start at 1. Before:

```julia
LinearIndices((5:8,))[5]
```

woud return 1, now it is a boundserror. The idea of the old behavior was to have an array with linear indices that is indexed in the same way as the original array, but this is no longer the case now for non-standard indexed arrays, so index conversion first requires a manual conversion to a 1-based index now.

CC @nalimilan @mbauman

**Comment by mbauman** [comment]
That's not quite the full story here.  The crux of the issue is https://github.com/JuliaLang/julia/pull/26682#issuecomment-379990349 — that is, with the old definition we were at odds with conversions between linear/cartesian indexing of offset arrays.

The relevant commit that changed the behavior here is not #26775, but rather https://github.com/JuliaLang/julia/pull/27038.  I agree this is still much harder than is should be, but with an updated OffsetArrays things should work.  You can opt-in to the offset behavior with Base.Slice:

```julia
julia> LinearIndices((Base.Slice(5:8),))
LinearIndices{1,Tuple{Base.Slice{UnitRange{Int64}}}} with indices 5:8:
 5
 6
 7
 8

julia> LinearIndices((Base.Slice(5:8),))[5]
5
```

Could you describe a bit more of your use-case?

**Comment by barche** [comment]
Thanks, missed that discussion. I was manually constructing `LinearIndices` objects to compute local indices into a block of a distributed matrix. So `LinearIndices` are now no longer 1-based in the case of vectors?

I was able to adapt my code to the new behavior using `Base.Slice`, so as far as I'm concerned this can be closed.

**Comment by nalimilan** [comment]
> I was manually constructing LinearIndices objects to compute local indices into a block of a distributed matrix. So LinearIndices are now no longer 1-based in the case of vectors?

IIRC you just have to pass the array `x` whose indices you want to refer to, using `LinearIndices(x)`. `LinearIndices((x,))` is completely different for ranges, it allows specifying the range of indices for the first dimension.

**Comment by barche** [comment]
Closing this, since appropriately using `Slice` fixes this for me.
