### ISSUE TITLE
v.1.0.0 documentation is missing

### ISSUE THREAD

**Issue by paul-hammant** [JuliaLang/julia#28544]
1) v.1.0.0 doco isn't up on the site.
2) https://www.google.com/search?q=julialang+faq points to v0.6.2 not v0.7.0 (latest) so y'all should do that canonical-url stuff.  Ref my friend's work towards the same for his Java tech - https://publicobject.com/2017/02/14/canonical-urls-for-javadocs/
3) https://docs.julialang.org/en should redirect to latest.

**Comment by fredrikekre** [comment]
Thanks, it should now be updated: https://docs.julialang.org/en/stable/

**Comment by paul-hammant** [comment]
1. up on site, affirmative
2. Canonical URL work done? I don't think so that'd mean redeploying all the 0.6.2, 0.7.0 doco.
3. https://docs.julialang.org/en still 404's.

:-(

**Comment by fredrikekre** [comment]
@mortenpi ^

**Comment by mortenpi** [comment]
We should add a redirect to that directory too. https://docs.julialang.org/ redirects correctly. I can PR that.

**Comment by fredrikekre** [comment]
https://docs.julialang.org/en/ now redirects to https://docs.julialang.org/en/stable/

**Comment by mortenpi** [comment]
As for canonical URLs: they were introduced with the 0.6.3 docs, but the older docs (0.6.2, release-0.5, release-0.4 etc.) don't have them, which is why they show up in google.

We could probably do a string replace in all the HTML pages from e.g. `</head>` to `<link rel="canonical" href="..."></head>`, with links translated from `https://docs.julialang.org/en/vX.Y.Z/foo.html` to `https://docs.julialang.org/en/stable/foo/index.html`.

An open question is how to handle pages that do not have a corresponding page under `stable/` anymore (or the name has changed). I am not sure what the consequences of pointing to non-existing URLs is.

**Comment by o314** [comment]
Is it intended that package markdown in stdlib has en empty doc page ?

https://docs.julialang.org/en/stable/stdlib/Markdown/


Remark 2: the edit link of the doc leads to https://github.com/fredrikekre/julia/blob/master/stdlib/FileWatching/docs/src/index.md and not https://github.com/JuliaLang/julia/blob/master/stdlib/Markdown/docs/src/index.md

**Comment by mortenpi** [comment]
#27094 for the Markdown page.

The edit link is a good catch. Somehow the base URL got changed in the build.

**Comment by o314** [comment]
OK. It seems it's the only package of the stdlib without docs
