### ISSUE TITLE
make reporting of views accurate

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#28610]
Consider:
```
a = collect(1:100)
b = view(a, 3:99)
```
right now, `Base.summarysize(a)` yields `840` and `Base.summarysize(b)` yields `880`.

This seems ... wrong. I believe this is because `summarysize` (and `varinfo`) are calculating the size of the backing array accessible via `b.parent`.

Would it be possible / generally desirable to report the size of views more accurately so that we see the size of the pointer instead of the entire backing array?

**Comment by JeffBezanson** [comment]
This depends a lot on what you need the numbers for. `summarysize` is intended to tell you how much memory a certain object is actually consuming --- i.e. how much memory could potentially be freed by dropping the last reference to it. So reachable objects should be included. Otherwise you'd have to write out the recursion yourself, which is difficult.

You can get the size of just a single object using `sizeof(typeof(x))`.

**Comment by sbromberger** [comment]
Ah, I see. Thank you!
