### ISSUE TITLE
nextpow2 stopped working for negative arguments

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#28687]
Not sure if this was intended?

0.6:

```
julia> nextpow2(-5)
-8
```

0.7

```
julia> nextpow2(-5)
┌ Warning: `nextpow2(x)` is deprecated, use `nextpow(2, x)` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
ERROR: DomainError with -5:
`x` must be positive.
Stacktrace:
 [1] nextpow(::Int64, ::Int64) at ./intfuncs.jl:357
 [2] nextpow2(::Int64) at ./deprecated.jl:55
 [3] top-level scope at none:0
```

cc @keno

**Comment by Keno** [comment]
We discussed this when we did the deprecation and @JeffBezanson pointed out that `-8` is not a power of 2, so yeah, this was mostly intentional.

**Comment by KristofferC** [comment]
Alright, let's just keep it like this then.

**Comment by oscardssmith** [comment]
should it just return 1? (or arguably 0). that is the next power of 2

**Comment by StefanKarpinski** [comment]
The complicated and fully correct deprecation would be `copysign(nextpow(2, abs(x)), x)`. Not sure if it's worth fixing that on the release-0.7 branch or not in case we make a 0.7.1 release.

> should it just return 1? (or arguably 0). that is the next power of 2

A couple of reasons:
- 0 isn't a (finite) power of 2
- 0.5, 0.25, etc. are also a powers of 2
- but that would introduce a type instability
- there's no next power of two after 0 because there are an infinite number of them

So I think it's best to have this be a domain error since it requires user clarification: did they want the next non-negative power of two, the next positive power of two?
