### ISSUE TITLE
REPL bug with semicolon output suppression

### ISSUE THREAD

**Issue by iwelch** [JuliaLang/julia#28743]
```
julia> f()= 1;

julia> f()= 1; # a

julia> f()= 1; # a ; 2
f (generic function with 1 method)
```

**Comment by stevengj** [comment]
Basically the same as #6225 and JuliaLang/IJulia.jl#734. Unless we implement a full finite-state machine, or incorporate semicolon detection into the full parser, instead of a simple regex heuristic, the detection of semicolons will always be easily confused by comments and strings. In the past we decided it wasn’t worth the trouble.
