### ISSUE TITLE
inv(transpose(X)) missing a method?

### ISSUE THREAD

**Issue by mortenpi** [JuliaLang/julia#28782]
On 0.7/1.0 I am seeing the following issue:

```
julia> X = [0.707107 0.707107 0.0; 0.707107 -0.707107 0.0; 0.0 0.0 1.0];

julia> inv(Array(transpose(X))) # Works

julia> inv(transpose(X))
ERROR: LoadError: MethodError: no method matching transpose(::LinearAlgebra.LDLt{Float64,LinearAlgebra.SymTridiagonal{Float64,Array{Float64,1}}})
```

It should probably be possible to just invert this type of matrix.

**Comment by andreasnoack** [comment]
I agree that we should support this operation. We probably need to enable general testing of `Transpose` and `Adjoint` in the test suite (which unfortunately will make the linear algebra tests even slower.)

**Comment by kragol** [comment]
This is not the first case of missing methods with `Adjoint`/`Transpose` types in the `LinearAlgebra` package (see e.g. issues #28714 and #27132, the latter being fixed in PR #27916). 

As for tests to add, there seems to be quite a few. A quick `grep` indicates that the following `LinearAlgebra` test files do not even contain the word `transpose`
```
cholesky.jl
eigen.jl
hessenberg.jl
pinv.jl
special.jl
structuredbroadcast.jl
trickyarithmetic.jl
```
(They might not include tests for adjoints either but `grep` is less helpful there.) 

Could there be a way to automatically add tests for `Adjoint`/`Transpose` types whenever a test involves a matrix? Using some kind of modified `@test` macro perhaps?

**Comment by garrison** [comment]
From [Discourse](https://discourse.julialang.org/t/inv-transpose-fails-on-1x1-matrix/14660): `inv(transpose(reshape([3.0], 1, 1)))` also fails, but with `ERROR: MethodError: no method matching ldiv!(::Float64, ::Array{Float64,2})`.

**Comment by goggle** [comment]
This issue seems to be solved, right?

On Julia 1.1.1:
```julia
X = [0.707107 0.707107 0.0; 0.707107 -0.707107 0.0; 0.0 0.0 1.0];
inv(transpose(X))
```
Result:
```
3×3 LinearAlgebra.Transpose{Float64,Array{Float64,2}}:
  0.707107   0.707107  0.0
  0.707107  -0.707107  0.0
 -0.0       -0.0       1.0
```
