### ISSUE TITLE
Consider reintroducing `ind2sub` and `sub2ind` utility functions

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#28901]
I would like to humbly ask if it would be possible to reintroduce these utility functions in Base. Although many algorithms can be rewritten in the terms of `CartesianIndex` and `LinearIndex`, many other algorithms do not benefit from this new approach, which is quite memory-hungry. (e.g. operating on CartesianIndex in a 3D image leads to 3x more memory). Furthermore, many domain types doesn't fit to the concept of `CartesianIndex`.

Since the deprecation warning just mentions that we can replace `ind2sub(dims, ind)` by `CartesianIndices(dims)[ind]`, I would like to propose that we have these definitions in `Base` to avoid having them redefined repeatedly by users in their packages. I would suggest renaming them to `lin2cart` and `cart2lin` or similar name.

Please advise on how to avoid these local definitions in packages, these utilities are quite widely used in image processing and computer vision, and I am sure many people will redefine it after realizing that working with linear indices can give considerable speedup.

**Comment by jebej** [comment]
A lot of the functions that were deprecated are now hidden behind underscores: `Base._sub2ind` and `Base._ind2sub` exist and work properly.

I was thinking about opening an issue about this, in particular for all the functions that were given keyword arguments. A lot of these methods are now just wrappers over underscored methods taking positional arguments, and I wish that this was undone. I believe we could have both the keyword methods and the positional methods. This is especially important since you can't broadcast over keyword arguments, or dispatch, and so a lot of functionality was actually removed with this transition.

**Comment by timholy** [comment]
Some concrete (aka, runnable) examples of the problems with the current approach would go far in making the case.

**Comment by juliohm** [comment]
Suppose I have a 3D image, and I want to find all the locations where a given predicate holds. That is fine. Now imagine that I need to this in a loop multiple times, perform intersection on these indices with other predicates, and then after these many operations, which are not necessarily cheap operations, I re-access the original image to extract the appropriate pixels.

An implementation of this general idea is in ImageQuilting.jl where I do quite heavy searches on the image, and do all these mathematical operations very efficiently in a set of integers (linear indices). There are many places in the code that I am not planning to use `CartesianIndices` because of the memory increase.

I can try produce a MWE, but I think the general idea described above is already clear of the memory limitations associated to the new enforced approach.

**Comment by juliohm** [comment]
Besides, many of the predicates and intersections I mentioned above are readily available with simple built-in functions on a vector of Int, whereas that is not the case for `CartesianIndex` or tuples for that matter.

**Comment by nalimilan** [comment]
> There are many places in the code that I am not planning to use CartesianIndices because of the memory increase.

What memory increase?

**Comment by timholy** [comment]
I'm still struggling to evaluate this (very polite, thanks!) request. There are two aspects that get in the way:

- To be honest I am a bit skeptical about the problems you describe. In particular, I believe that our current infrastructure does allow anyone to write code that isn't memory hungry, and that does fit most applications conceptually.  Because I can't imagine what kinds of fundamental problems our current infrastructure has, I'm left wondering whether you're asking for this on the basis of what you're used to more than "pure" design merit (whatever that means).
- There are nearly an infinite number of ways to write the operations you describe above. As I'm sure you know, sometimes tiny changes can make a vast difference in performance, ease of use, etc. Without runnable code it's really hard for me to guess whether a tiny tweak to how you're using them might change your experience considerably.

To be clear, I have lots of code that uses these constructs and doesn't allocate. A runnable example that shows me the troubles you're experiencing might really do wonders for convincing me and others.

**Comment by ViralBShah** [comment]
We can continue the discussion here, but I am going to close the issue.

**Comment by ViralBShah** [comment]
Also, I think this might be a common enough pattern that we should describe how to do it in the documentation. Perhaps once the MWE is posted and the discussion concludes, we can figure out what to put in the documentation.

**Comment by juliohm** [comment]
I don't see a good replacement for `ind2sub` and `sub2ind` in some situations like the example here: https://github.com/juliohm/GeoStatsDevTools.jl/blob/master/src/neighborhoods/cube_neighborhood.jl#L32

This code is called 1000 times, and so without a quick method to convert between linear and Cartesian indices, I end up allocating an entire `CartesianIndices` matrix for each iteration of the loop when I actually just want to find out the center of the neighborhood object as a tuple of integers giving the linear index in the regular grid.

Do you have recommendations on how to solve this issue?

**Comment by nalimilan** [comment]
@juliohm Please don't post twice the same comment. I'll remove this one and keep https://github.com/JuliaLang/julia/issues/28901#issuecomment-419311879 instead.

**Comment by timholy** [comment]
https://discourse.julialang.org/t/psa-replacement-of-ind2sub-sub2ind-in-julia-0-7/14666
