### ISSUE TITLE
Allow for variable number of arguments to NamedTuple to avoid double braces

### ISSUE THREAD

**Issue by stakaz** [JuliaLang/julia#28946]
Hello, I wonder if it would be a good thing (and possible at all) to add the following syntactic suggar to NamedTuples:

Current working version:
```julia
julia> NamedTuple{(:a, :b)}((1, 2)) 
(a = 1, b = 2)
```
first idea: remove arguments double braces (accept a variable number of arguments instead of a Tuple)
```julia
NamedTuple{(:a, :b)}(1, 2) 
```
second idea: remove type double braces
```julia
NamedTuple{:a, :b}(1, 2) 
```

I do not know exactly whether it is possible but I thing that multiple dispatch could provide these simplifications...

**Comment by JeffBezanson** [comment]
I don't think this is possible. But it is possible to introduce new definitions for more convenience, e.g.:

```
ntt(syms...) = NamedTuple{syms}   # ntt(:a, :b)
ntc(syms...) = (args...)->ntt(syms...)(args)    # ntc(:a, :b)(1, 2)
```

Making the constructors take a single argument is really more flexible. For example it allows tricks like this:
```
julia> t = (a=1, b=2, c=3)
(a = 1, b = 2, c = 3)

julia> NamedTuple{(:c, :a)}(t)
(c = 3, a = 1)
```

And we can't have it both ways, since `NamedTuple{(:a,)}((1,))` would be ambiguous --- do you want the single field value to be `1` or `(1,)`?
