### ISSUE TITLE
Missing target optimum types in

### ISSUE THREAD

**Issue by ghost** [JuliaLang/julia#28958]
Please consider adding a size independent type that represents the most cpu-performant type of Int, UInt, and Float on the target machine for a given minimum size. The use cases for this arise in systems programming and visualization applications, where a smaller type is sufficient (example: 16 bit Int) but maximum cpu performance is desirable (on most ARM processors a 32 bit Int will be faster to access and process). If these are first class types the issues with C typedef and C++ alias can be avoided.

**Comment by nalimilan** [comment]
AFAIK due to SIMD smaller integer types will always be faster than larger ones, at least in situations where vectorization is enabled. So I guess you refer to a different characteristic of ARM CPUs?

**Comment by JeffBezanson** [comment]
`Int` and `UInt` are already 32 bits on 32-bit systems and 64 bits on 64-bit systems. I don't think a platform-dependent float type makes sense, since that can change results significantly. Of course, changing integer sizes can also change results (and indeed some people would rather remove any platform-dependence here entirely) but 32-bit overflow on 32-bit systems is considered rare enough to make the trade-off worthwhile.
