### ISSUE TITLE
How to use esc()?

### ISSUE THREAD

**Issue by LaszloHars** [JuliaLang/julia#29032]
In the documentation of Julia v1.0 there is almost nothing about escaping in a macro. I tried a simple debug function, which I can add to critical points of a function. It should only print an expression or variable name, and its current value. I defined a macro in a module, but I get weird messages at loading the module, and only the last value of several calls to the macro is shown in REPL. Could anyone point me to relevant information or tell, how I can write a simple macro like this?
```
macro db(x)         # only works in REPL, single call in a line, fails when loaded and used in a module
    print(x," = ")
    return :($(esc(x)))
end
```

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.

**Comment by LaszloHars** [comment]
Even though this post is formulated as a question, it is actually pointing to issues with the documentation, and deficiencies of the esc blocks. Could you respond to the post?

**Comment by KristofferC** [comment]
The problem in the post has nothing to do with escaping.

Improvements to https://docs.julialang.org/en/v1/manual/metaprogramming/#Hygiene-1 are always welcome.

**Comment by LaszloHars** [comment]
I think, the problem is, at least partially, the lack of documentation on escaping. Where can you use esc()? (Obviously, not only in a return expression, as the doc says.) What can be enclosed? When do you need to precede it with $, and why? Etc. The Hygiene section does not give clear answers for a novice user.
But I got answers to my problem in  https://discourse.julialang.org/, and people seem to agree that the documentation is insufficient.

**Comment by yuyichao** [comment]
> Where can you use esc()? 

Anywhere. It's just a function so here isn't really much to say about where you can call a function.

> not only in a return expression, as the doc says

The doc didn't say that. If you read the hygiene section, it gives multiple examples where it's not used on return values.

> What can be enclosed? 

Anything. I actually don't see this mentioned explicitly so if you want to clearify that's fine. It's pretty well implied though IMHO.

> When do you need to precede it with $, and why?

This is interpolation, it has nothing to do with `esc`. So the answer is "when you need to interpolate it" and "because you want to interpolate it".....

**Comment by LaszloHars** [comment]
The online documentation says that esc() is "Only valid in the context of an Expr returned from a macro". It is not "anywhere", is it?
Also, the suggested solution uses the construct inside an esc(): $"...". It does not look "interpolation". Again, these are very confusing for a novice user. Maybe an expert knows, what really is meant by the documentation, but they might just need a reference instead.

**Comment by yuyichao** [comment]
> It is not "anywhere", is it?

Anywhere in a macro that is. In your case it is also used in an `Expr` returned from a macro. I see that you interpreted it as the one that is returned from a macro rather than just being part of that `Expr` so feel free to improve that.

> $"...". It does not look "interpolation". 

Errr, what about it is not interpolation? Note that `$"..."` or interpolation in general has nothing to do `esc` or macro hygiene so you shouldn't expect to find anything about it in the hygiene section. (And I do kind of agree that there are a few cases including this one where interpolation is a bit confusing).

> Maybe an expert knows, what really is meant by the documentation, but they might just need a reference instead.

I agree that the document could be better. I'm only saying that most of what you are asking about aren't about hygiene or `esc` or macros at all, even though you hit the problem in your particular case when you are dealing with these. It's not really possible for the document for each function to give you a thorough walk though of everything you need to solve a problem that might need the function, that's the job for a tutorial so when using the manual, you should be prepared to look for different things in different sections (which won't be easy to start for sure).
