### ISSUE TITLE
Performance problems of Julia

### ISSUE THREAD

**Issue by AlphaFase** [JuliaLang/julia#29078]
[project: test](https://github.com/AlphaFase/julia-libs/tree/master/%E6%80%A7%E8%83%BD%E5%AF%B9%E6%AF%94/jl_py)
python:   6 sec
julia：     11 sec

Dynamic array performance is not as good as python, only using single core CPU. Does Julia also have a GIL lock?

Is there a performance analysis tool similar to Python cProfile?
Julia's performance analysis tool is either inaccessible or inhumanized.

**Comment by sairus7** [comment]
If you are using Juno IDE, then
@profile <your function here>
Juno.profiler()

**Comment by andreasnoack** [comment]
Thanks for providing the benchmarks. However, this discussion is better suited for discourse.julialang.org

**Comment by AlphaFase** [comment]
Wrong optimization
`for (k,v) in xx`

Correct optimization
```
for x in xx
   v=x[1]
   v=x[2]
```

**Comment by timholy** [comment]
The use of a non-`const` global dict seems a likely problem. But at least in earlier Julias I have also noticed that destructuring pairs isn't optimized. Likely related to #27434 and especially https://github.com/JuliaLang/julia/pull/27434#issuecomment-400335764

**Comment by KristofferC** [comment]
For this to be reopened, I think the code should at least be written with some consideration to the performance guidelines we have.
Adding a few `const` to global variables and making the main data structure, not a `Vector{Any}` cuts the time down by a factor of 3.

**Comment by timholy** [comment]
@AlphaFase, please see https://docs.julialang.org/en/v1/manual/performance-tips/ (hint: you're violating at least performance tip number 1 :smile:)

**Comment by JeffBezanson** [comment]
Destructuring does not use splatting. I'm also pretty sure `for (a, b) in c` is optimized well now.

**Comment by andreasnoack** [comment]
Might also be worth mentioning that the first Python version shared had some parts commented out that made it much faster but not comparable to the Julia version. It has since been fixed but I first benchmarked the wrong version.

I'm not sure about the rules of the game here but using typed vector of tuples instead of an Any vector of Any vectors also gave about 2x for me.

Finally, it would really be nice to have #28648 fixed for situations like these since right now it's basically impossible to use Juno's flame graphs which, I think, is normally our best profiling tool.
