### ISSUE TITLE
[Julia 1.0.0, Win 10] Windows Freeze on interruption of executing code

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/julia#29093]
I recently ran a code ( `sum((1:n).^-2)`) several times for different n's in order to test the power of my pc. at `n=1_000_000_000` it finally took too long to execute so i interrupted it by ctrl+c (in the repl) and instead of giving me an interrupted exception or similar my whole system (windows 10) froze... cursor didn't move and taskmanager didn't open... out of curiosty i killed my pc and booted again trying it again. same result/effect. It just felt like something killed/interrupted the scheduler because nothing was working anymore

**Comment by StefanKarpinski** [comment]
Allocating too much memory can make your OS do bad things depending on the OS. When I was regularly working with really large data sets, I would regularly watch the RAM usage just hoping not to see it get pegged, because once that starts, you might be able to recover with an early enough ctrl-C but most likely, you're going to be rebooting your machine. I'm not sure there's much Julia can do here.
