### ISSUE TITLE
sortperm! with bad initialization of Int32 indices segfaults

### ISSUE THREAD

**Issue by chethega** [JuliaLang/julia#29179]
```
julia> r=rand(1000); p=rand(Int64,1000);
julia> sortperm!(p, r; initialized=true)
ERROR: BoundsError: attempt to access 1000-element Array{Float64,1} at index [1165611285912797586]

julia> r=rand(1000); p=rand(Int32,1000);
julia> sortperm!(p, r; initialized=true)

signal (11): Segmentation fault
```
I have no clue why `Int64` catches the bounds-error and `Int32` segfaults.

Also, the documentation of `sortperm!` could be clearer: I managed to misinterpret the `initialized=true` option as "apply the sorting permutation to the preallocated vector" (no idea what I was thinking). Checked on 1.0.0 and 1.1.0-DEV.254, 64bit.

**Comment by jpsamaroo** [comment]
The segfault is not an error because of the `@inbounds` on line 477 of `sort.jl`, within the call to `selectpivot!`. Removing the `@inbounds` and running your example gives a `BoundsError` as you might expect. No clue why the `Int64` variation doesn't cause the segfault, but the two `sortperm!` calls seem to throw their respective `BoundsError`s along different code paths.

I'm not an expert with sorting, but I noticed that the failure is somewhere within the first `lt(o, v[mi], v[lo])` around line 482, because `v[mi]` is some large negative `Int32` like `-780846055`. I'll continue trying to figure out why this is happening, but someone more familiar with this code will probably be able to spot the issue much quicker than I :smile:

**Comment by jpsamaroo** [comment]
Oh, now I see, so if you set `initialized=true`, the assumption is that you properly initialized `p` with the values in `1:length(r)`, which was violated in this case, hence the error/segfault.

I'm not personally sure that this really warrants any change other than possibly to the docstring of `sortperm!`. However, since the docstring says "If initialized is false (the default), ix is initialized to contain the values 1:length(v).", I think it's pretty clear that if you set `initialized=true`, then `p` needs to be manually initialized to `1:length(r)` (in this specific example). Maybe a small addition could indicate that setting `initialized=true` and then not properly allocating the argument `ix` may cause julia to crash? If this is desired, I would happily create this PR.

Otherwise, trying to catch this segfault would boil down to iterating over argument `ix` to ensure that it's valid, which is clearly going to kill the performance benefit you could get from `initialized=true`.

**Comment by ViralBShah** [comment]
No more segfault.
