### ISSUE TITLE
Dynamic Format Strings in Julia's @printf macro

### ISSUE THREAD

**Issue by JimDavidson** [JuliaLang/julia#29278]
`julia> using Printf
julia> fmt = "%10d"
"%10d"
julia> @printf(fmt, 123)
ERROR: LoadError: ArgumentError: @printf: first or second argument must be a format string`

It would be nice to have dynamic format strings for the @printf macro.

**Comment by JimDavidson** [comment]
Yes, I did see that, but hoped something changed in the last 5 years or so.  It looks like this behavior is going to be baked into the language.

**Comment by lobingera** [comment]
> It would be nice to have dynamic format strings for the @printf macro.

Macros are evaluated at compile time, once a printf macro is compiled, the format string is fixed (and yes, that's baked into the language). If you need dynamic formatting goto https://github.com/JuliaIO/Formatting.jl or similar.

**Comment by stevengj** [comment]
In principle, the `@printf` macro could look at whether the first argument is a literal string (this is known at macro-expansion time since literal strings appear as `String` nodes in the AST), and if not fall back to slow dynamic code.

This would be backwards-compatible, so in principle it could be supported in 1.x.  But it would mean folding something like Formatting.jl into the standard library.

**Comment by o314** [comment]
What is a bit puzzling is that `Printf` @ stdlib does the macro impl exporting `@printf` and `@sprintf`, but `Formatting.jl` does its function part by exporting `printfmt` instead of `printf`, `sprintf` that have not been reserved by stdlib.
Not a good pattern there

**Comment by quinnj** [comment]
This is now implemented in stdlib Printf: you can create `Printf.Format` objects by calling `Printf.format"..."` or `Printf.Format(...)`, then pass a formatting object to `Printf.format(::Format, args...)` to format arguments according to the format.
