### ISSUE TITLE
Autocomplete escape sequence bug

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaLang/julia#29304]
Autocomplete in the REPL add `\` when needed to file names but julia1.0 functions do not like them

```
julia> DelimitedFiles.readdlm("a\ a.txt")
ERROR: syntax: invalid escape sequence
```

```
julia> DelimitedFiles.readdlm("a a.txt")
```
works

**Comment by krrutkow** [comment]
This bug also cripples REPL tab-completion for files with spaces in them since it completes the path string with "invalid escape sequences" which then requires the user to correct manually.

**Comment by ssfrr** [comment]
It looks like the backslashes are added by [this `replace` call](https://github.com/JuliaLang/julia/blob/2859b11a1227a40bdebe940699c2e35484e880e6/stdlib/REPL/src/REPLCompletions.jl#L262).

It seems like that's generally not what you want when returning a string that will then be used as input (because it's now an invalid string). doing a little archaeology, this line has been touched several times but was originally added in [this 2014 PR](https://github.com/JuliaLang/julia/pull/8838), AFAICT to fix a bug with paths that end in spaces.

I think that Juno and IJulia use this completion code as well, and have the same issue.

**Comment by StefanKarpinski** [comment]
It seems like autocomplete needs to have an option when completing file names for whether spaces are needed or not based on the context. In strings they're not allowed, in shell commands they're required.

**Comment by vtjnash** [comment]
`r"\s" => "\\ "` is also the wrong regex there. it could be `r"\s" => s"\\\0"`, or `" " => "\ ", "\t" => "\\t", "\r" => "\\r", etc.`

but it really should probably use the existing functions for this (e.g. `repr` and `shell_escape_posixly`)
