### ISSUE TITLE
Cclock_t ?

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#29420]
there is already `Csize_t`.  any reason not to have `Cclock_t` an `Ctime_t` as well?

**Comment by bjarthur** [comment]
ditto for intptr_t, pid_t, id_t, pthread_attr_t, sigset_t, uid_t, ct_rune_t, rune_t, dev_t, mode_t, pthread_t, ino_t, rsize_t, blkcnt_t, blksize_t, gid_t, ino64_t, off_t, useconds_t, suseconds_t, pthread_cond_t, pthread_condattr_t, pthread_mutex_t, pthread_mutexattr_t, pthread_once_t, pthread_rwlock_t, pthread_rwlockattr_t, pthread_key_t, fsblkcnt_t, fsfilcnt_t, mach_port_t, and fpos_t.

my problem is that i'm wrapping a C library with Clang.jl and all of these things are referenced.  i could dig up in my particular system what the corresponding bitstypes are and defined constants for them.  but how is one supposed to make a cross-platform wrapper?

**Comment by yuyichao** [comment]
`clock_t` and `time_t` are OK (and `time_t` is already available as `TmStruct`). The longer list is definitely too much. FWIW, many of them are not cross-platform so by definition your wrapper won't be cross platform. They are also better for a package though since the base julia won't need most of them and there's no special semantics in them that require it to be in base.

**Comment by StefanKarpinski** [comment]
We should just make `Ctime_t` an alias for `TmStruct` (and probably mark `TmStruct` for deprecation in 2.0). `Cclock_t` seems reasonable enough; I agree with @yuyichao about the long list.

**Comment by simonbyrne** [comment]
I may have changes since the last comments, but now `TmStruct` appears to be an alias for `tm` (https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/time.h.html).

Based on [these signatures](https://github.com/JuliaLang/julia/blob/b0a55b864106e6e82724e67de1b68d5db010ea4b/base/libc.jl#L180), `time_t` would match `Int`. 

Not sure about `clock_t`.

**Comment by vtjnash** [comment]
I think using Clang for your use case is probably the best option here. I don't think we'll make wrappers for most of these types, since we'd rather reimplement them in Julia.
