### ISSUE TITLE
Could not run Julia 0.6.4 

### ISSUE THREAD

**Issue by gdragotto** [JuliaLang/julia#29563]
Hello,

While installing Julia 0.6.4 I get this error on Windows 10

[...]JuliaLang\Julia-0.6.4\bin\julia 
ERROR: could not load library "D:\JuliaLang\Julia-0.6.2\lib\julia\sys.dll" 
¯8ƒåH²

**Comment by PallHaraldsson** [comment]
I can only say Windows 10 is for sure supported (I'm not running on, but know for sure others do), by Julia current and previous versions) and JuliaPro.

Questions should go to Discourse, as I'm sure you're doing something unusual.* So I assume this is not a bug and could the issue closed here.

I see 0.6.x is still maintained" (but not older) officially, but that would mean security fixes backported to it. There's no such plan for 0.7, for any fixes, as it's just a transitional release you however may want to check out.

https://julialang.org/downloads/oldreleases.html

You shouldn't need to use JuliaPro rather than Julia, but I see it's been updated to 1.0.1.1 (and there was a 0.6.x release, I assume it's still available), and you could check it out as it has some alternative installer.

The FAQ is outdated:
https://juliacomputing.com/products/faqs/juliaprofaq.html

but it seem they (by default, only option?) install to:
C:\JuliaPro-0.6.0.1

and I see you used D: drive. Maybe such unusual choice makes a difference, I guess it shouldn't nor that you need to change some environment variable.

* It's unclear if you built from source, and it's rarely needed.

I'm not sure what's the meaning of (not part of the path):
>¯8ƒåH²

**Comment by gdragotto** [comment]
Hey, 
The problem is that I am trying to run JuliaMP, which supports only the reported version.
That said, didn't do anything _unusual_: just downloaded the version and made it run from the directory _bin_ and main dir.

**Comment by gdragotto** [comment]
UPDATE: Removing JULIA_HOME from the env fixed the thing (since we had 2 different versions)
