### ISSUE TITLE
Example in Julia document "Shared Arrays" report error when running

### ISSUE THREAD

**Issue by zhaotianjing** [JuliaLang/julia#29611]
Hi,

In documentation about "[Shared Arrays](https://docs.julialang.org/en/v1/manual/parallel-computing/#man-shared-arrays-1)". The example to create share array:
![image](https://user-images.githubusercontent.com/18593116/46846035-de1a8780-cd92-11e8-88a1-7d75d1596df1.png)

when I run, I have the error msg `MethodError: no method matching setindex_shape_check(::Int64, ::Int64)`

![image](https://user-images.githubusercontent.com/18593116/46845972-9431a180-cd92-11e8-9745-f4057c8b60b0.png)

Can someone tell me what's going on?
New to Parallel Computing in Julia. Thx.

**Comment by fredrikekre** [comment]
Thanks for the report. I think that the docs should be updated to `S[localindices(S)] .= myid()` but that just results in a different error, so there is probably something else going on too.

**Comment by henry2004y** [comment]
I am using v1.1.0. This bug is still not fixed.

**Comment by benjaminwsebastian** [comment]
I am using v1.2.0 and this bug is still not fixed.

**Comment by AtsushiSakai** [comment]
I think this issue was fixed by #35616.
- [Multi\-processing and Distributed Computing · The Julia Language](https://docs.julialang.org/en/v1/manual/distributed-computing/#man-shared-arrays)
<img width="909" alt="SS 2021-06-28 at 21 15 32" src="https://user-images.githubusercontent.com/3813847/123634938-02299a00-d856-11eb-8fac-06fa1ca3c1aa.png">
