### ISSUE TITLE
confusing argument printing in InexactError 

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#29766]
```
julia> Int(1.5)
ERROR: InexactError: Int64(Int64, 1.5)
```

I believe this is due to generic code that's also used for functions like `trunc`. But in this case it should print `Int64(1.5)`.

**Comment by laborg** [comment]
Should `convert(Int, 1.5)` print
```
ERROR: InexactError: Int64(1.5)
```
or
```
ERROR: InexactError: convert(Int64, 1.5)
```
(knowing that `convert` just delegates to the type constructor)

**Comment by fredrikekre** [comment]
From the docs of `InexactError`:

>   InexactError(name::Symbol, T, val)
> 
>   Cannot exactly convert val to type T in a method of function name.

So `Int64(Int64, 1.5)` is technically correct, since the `Int64` function can not convert `1.5` to an `Int64`, but I agree it looks weird. Maybe we can add a two-argument `InexactError` for cases like this?

> Should convert(Int, 1.5) print ... or ...

I think it should print `ERROR: InexactError: Int64(1.5)` since that is where the error is thrown from, and we don't propagate the information about `convert`.

**Comment by laborg** [comment]
A quick solution would be to compare  `string(ex.name)` to `string(ex.T)` while printing. If they are equal we could omit the redundant but provided `ex.T` type information.

**Comment by JeffBezanson** [comment]
I don't see how the docs for `InexactError` make that printing technically correct. `Int64(Int64, 1.5)` is not a valid call. Perhaps `InexactError(:Int64, Int64, val)` is a valid call to the `InexactError` constructor, but that's not relevant.

**Comment by fredrikekre** [comment]
Yea, I misinterpreted it.

**Comment by kim366** [comment]
@JeffBezanson it is because of the macros, I suspect. In https://github.com/JuliaLang/julia/blob/59762368ed7b43288605466556c97b03f09e4671/base/boot.jl#L586 we also have `throw_inexacterror(:check_top_bit, typeof(1), 1)`, which produces the output 

`ERROR: InexactError: check_top_bit(Int64, 1)`

even though that's not a valid call.
