### ISSUE TITLE
Add !=(2) to parallel ==(2)

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#29886]
The `==(2)` method is a convenient replacement of `x->x==2`. Could we also have `!=(2)`?

EDIT: `isa(Vector)` and `===(2)` would be nice, too.

**Comment by ronisbr** [comment]
I suppose that we cannot define this for the other types of comparisons like `>=` or `<=` right?

**Comment by StefanKarpinski** [comment]
The convention we decided on is that we do this kind of "auto-currying" for `verb(subject, object)` functions taking two arguments and the curried form is `subject -> verb(subject, object)`. So `in(collection)` means `item -> item in collection`. By that rule `<(b)` means `a -> a < b` which makes sense since you read it as "less than `b`" which is a predicate that is true of `a` when `a < b`.

**Comment by cstjean** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/30915
