### ISSUE TITLE
put! and take! Operations on Remote Channels not atomic

### ISSUE THREAD

**Issue by rohanmclure** [JuliaLang/julia#29932]
I have been implementing a parallel version of the [Reduce kernel](https://github.com/ParRes/Kernels), implementing a tree reduce method. After processes calculate their partial sums (partial sums in this instance are vectors), they `put!` to a blocking channel to avoid overwriting the data before they communicate it to other processes. For sufficiently large vectors, it is possible for the data to be mutated before it is serialised.

This behaviour is illustrated by the following minimal example. Worker two will take a zero vector of sufficient size and add one to it at each iteration. Immediately afterwards, it will initiate a blocking communication with worker three.  Worker three will assert that the data contained within the vector at each step is equal to the iteration counter.

`put!` and `take!` operations appear to atomically serialise the vector before beginning the next iteration for smaller vectors, however this semantic is not maintained for larger vectors.

```
@fetchfrom 2 begin
    global inbox = RemoteChannel(()->Channel{Vector{Float64}}(0))
end

@fetchfrom 3 begin
    global outbox = @fetchfrom 2 inbox
end

@sync begin
    @spawnat 2 begin
        vector = zeros(8200)
        for i in 1 : 1000
            vector .+= 1.0
            put!(inbox,vector)
        end
    end

    @spawnat 3 begin
        local incoming
        output = [take!(outbox) for i in 1 : 1000]
        wrong = 0
        for (i,v) in enumerate(output)
            if v[1] != i
                wrong += 1
            end
        end
        println("$wrong failed")
    end
end
```

```
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, sandybridge)
```

**Comment by amitmurthy** [comment]
I think I have located the issue.

- The backing store for the `RemoteChannel` is a `Channel{Vector{Float64}}(0)` on process 2
- A `put!` into this from process 2 does not involve serialization as it is local to the process.
- The `put!` call on pid 2 results in the vector `vector` stored in the channel. There is no serialization or data copying taking place. It is the same object as passed from the `put!` invocation to `inbox`.
- A `take!` executed from process 3, results in a `take!` on the backing store on pid 2 and then serialized back to pid 3
- This serialization from 2 to 3 involves https://github.com/JuliaLang/julia/blob/58fea96a5ceb95940da3fb42a1e26d0a4d864c09/base/stream.jl#L824-L846
- The optimized send in the above block of code kicks in only if bitstype data exceeds 64K . Hence this issue cropping up only for larger arrays
- Specifically what I think is happening on pid 2 is that:
  - there are 2 tasks active, one the `put!` into the backing channel and the second the `take!` on behalf of pid 3.
  - The call to `put!` in the putting task goes through and the scheduler switches to the `take!` task
  - In the taking task, vector `vector` is successfully taken from the backing channel and serialization to 3 invoked.
  - However, the call to `flush`, https://github.com/JuliaLang/julia/blob/58fea96a5ceb95940da3fb42a1e26d0a4d864c09/base/stream.jl#L838 results in this task yielding back to the putting task. 
  - In the putting task, data in vector `vector` is overwritten and the same object pushed once again into the backing channel. 
  - When control returns back to the taking task, the overwritten data is being serialized to 3
- This is seen in the following modified version of the code above.
```
julia> @sync begin
           @spawnat 2 begin
               vector = zeros(8200)
               for i in 1 : 10
                   vector .+= 1.0 ; println("putting $i")
                   put!(inbox,vector)
               end;
           end

           @spawnat 3 begin
               local incoming;
               output = [(x=take!(outbox);println("got $(x[1])");x) for i in 1 : 10]
               wrong = []
               for (i,v) in enumerate(output)
                   if v[1] != i
                       push!(wrong, [i,v[1]]) # [expected, got]
                   end
               end
               println(wrong)
           end
       end
      From worker 2:	putting 1
      From worker 2:	putting 2
      From worker 3:	got 2.0
      From worker 2:	putting 3
      From worker 3:	got 3.0
      From worker 2:	putting 4
      From worker 3:	got 4.0
      From worker 2:	putting 5
      From worker 3:	got 5.0
      From worker 2:	putting 6
      From worker 3:	got 6.0
      From worker 2:	putting 7
      From worker 3:	got 7.0
      From worker 2:	putting 8
      From worker 3:	got 8.0
      From worker 2:	putting 9
      From worker 3:	got 9.0
      From worker 2:	putting 10
      From worker 3:	got 10.0
      From worker 3:	got 10.0
      From worker 3:	Any[[1.0, 2.0], [2.0, 3.0], [3.0, 4.0], [4.0, 5.0], [5.0, 6.0], [6.0, 7.0], [7.0, 8.0], [8.0, 9.0], [9.0, 10.0]]
Future(3, 1, 132, nothing)
```

A workaround for this bug is to `put!` a deepcopy of vector `vector`, i.e., `put!(inbox,deepcopy(vector))`.

A solution to this will require some more thought - I don't have one offhand. The bug arises due to the different code paths traversed when putting to a local object verses a remote object. The `put!` in the MWE does not involve serialization at all.

**Comment by amitmurthy** [comment]
After thinking a bit, I am not sure we need to treat this particular case as a bug.

Consider a simplified example of two tasks "putting" and "taking" the same object (the vector `vector` in the above MWE) in a preemptively scheduled environment on a single process. In such a scenario we wouldn't provide any guarantees on the order of task execution and therefore the contents of `vector` in the "taking" task.

I propose clarifying this behavior and the reasons for it in the documentation.

**Comment by vtjnash** [comment]
What you previously proposed is also valid. We currently delay serializing the object until being about ready to send it over the wire. We could instead redefine this object to simply contain a PipeBuffer instead of a Vector. That might also make RemoteChannel and Channel more distinct, while generally making RemoteChannel work consistently between the local and remote cases.

**Comment by JeffBezanson** [comment]
If we want to avoid copying the data, it seems to me the only options are (1) do nothing and document this, or (2) block the calling task until the whole array has been sent. That's no guarantee of course, since another task could overwrite the data, but would at least handle simple cases like this.

**Comment by rohanmclure** [comment]
Perhaps I'm not seeing the full generality of this issue, but while I don't necessarily expect mutual exclusion for the array that I'm sending, I do expect that the putting task will be blocked until the message has fully sent.

**Comment by StefanKarpinski** [comment]
Blocking here seems reasonable to me.

**Comment by amitmurthy** [comment]
The issue here is a bit more subtle and unrelated to blocking. Fundamentally, the issue arises because a `put!` on a `RemoteChannel` owned by the local process does not involve a serialization-deserialization of the object.  It is not being "sent" anywhere. The `put!` in the MWE above is a local operation because the `RemoteChannel` exists on the same process (both are on pid 2).

Elaborating by means of an example. Consider a `RemoteChannel`, `rc` owned by pid 2. If a task on pid 2 puts a vector `v` into `rc`, and this vector is taken by another task on pid 2, then the second task receives same object `v` as both the tasks and `rc` are local to pid 2. There is no serialization of `v` happening here. However if the taking task is on a different process 3, then obviously the object `v` read on 3 is a copy as it has been serialized and deserialized across process boundaries.

We need to keep the behavior of a `put!` on a RemoteChannel the same for both cases - i.e., when the `RemoteChannel` is owned by the local process and also when it is owned by a remote process.

So, the solution would be implement the workaround suggested transparently, i.e. a `put!` to a `RemoteChannel` owned by the local process will internally execute a deepcopy of the object - this has the same effect as serializing/deserializing.  

It will be understood that a `take!` from a `RemoteChannel` will always return a copy of the object under all circumstances.
