### ISSUE TITLE
something like c++ "#pragma once" 

### ISSUE THREAD

**Issue by Orbots** [JuliaLang/julia#29966]
Assume a single package with modules A,B,C and D.  Currently if I have a module "D" that is included more than once I'll get a load error.  If B and C depend on D via "using ..D", I need to move include("D.jl") to a point before B or C are included.  A would include D, B, C, in that order.  It would be more natural for B and C to include("D.jl"), since A should not necessarily need to know that D exists at all.

In C++ you would use #pragma once or include guards.

I made a macro that works for me but feels a little unjulian since I need to include stuff outside of the module scope for it to work.  Would be nice if Julia had a more official mechanism for this.

    macro once(exp)
        if exp.head == :module
          if !isdefined(__module__, exp.args[2])
            esc(Expr(:toplevel,exp)) 
          end
        end
    end

Then for module D I can include it twice with no trouble, assuming A includes B and C.

A.jl

    module A  # my application/library level module so include() stuff inside module
       include("B.jl")
       include("C.jl")
    end

D.jl

    @once module D   # will be included more than once
        ....
      end

B.jl

    include("D.jl")   # include's outside module so it's plopped into A
    module B
      do some stuff with D
    end

C.jl

    include("D.jl")  # include outside module
    module C
      do some stuff with D
    end

Apologies if this is already covered in another issue.

**Comment by yuyichao** [comment]
Having this won't really help much when you make changes since you still can't move `D.jl` into a different module.

You can implement this in a package (and since it could, it should not be in base) by doing exactly the same thing as `C` with a unique global variable definition. That's also the recommanded way to do it in `C` since `#pragma once` is basically deprecated.

**Comment by JeffBezanson** [comment]
#4600 might be what's needed here. It also sounds like `D` could just be a separate package.

**Comment by Orbots** [comment]
Not sure I understand what you mean about moving D.jl into a different module?  I'm assuming here that, much like in C++ everything is brought into the same source blob (contained in module A in my case ) via include.  Which is why include("D.jl") appears before module declaration.

You are talking about include guards.  I see this as more akin to include guards than pragma once.  I guess I would use gensym() for the global variable and maintain a map of some sort.  Using the module name as the unique id seems simpler.

**Comment by yuyichao** [comment]
Yes #4600 is a better solution and it won't have the issue of module parent.

> what you mean about moving D.jl into a different module?

`include("D.jl")` cannot be moved into `module B`. You worked around it now by putting it outside but that's not always possible, e.g. when you have `module A; module B; include("C.jl"); end; end` and want to use `D` in `C.jl`. #4600 won't have this problem.

> I'm assuming here that, much like in C++ everything is brought into the same source blob 

This is totally different from C++ since there's no distinction between headers and sources. C++ headers and namespaces forms two completely different dependency and nesting structure which doesn't exist in julia (I'm not saying that it can't be added but this is certainly way too weak a reason for such a fundamental change). You don't have the problem I mentioned above in C++ since you never need to (and basically never should) include a header in a namespace. This is not the case in julia, the include structure has to follow the module structure.

> You are talking about include guards. I see this as more akin to include guards than pragma once. I guess I would use gensym() for the global variable and maintain a map of some sort. Using the module name as the unique id seems simpler.

Yes. The only way this can be implemented in base is using include guard anyway. You shouldn't use `gensym` since that's unstable. You should just use a mangled name computed from the module name, assuming the module name is what you want to guard against.

Here's an 5-min implementation for you if you want to put it in a package.

```julia
julia> macro once(m)
           @assert m.head === :module
           name = m.args[2]
           gvname = Symbol("#@once#gv#for#$name")
           quote
               if !isdefined($__module__, $(QuoteNode(gvname)))
                   global $gvname = 1
                   eval($(QuoteNode(m)))
               end
               nothing
           end
       end
@once (macro with 1 method)
```

Closing since I think a package is the right place to do exactly what this is asking for and we already have #4600 for the more general soluteion.

**Comment by Orbots** [comment]
Ok, thanks.  Looks like 4600 is the right way to go.   The once macro you provided has some issues.  
julia> using MyPackage
[ Info: Precompiling MyPackage [90ed3394-e3a0-11e8-12b1-2da6013e8dc0]
WARNING: eval from module Once to MyPackage:                         
Expr(:module, true, :OncedModule ...

The one I wrote has less issues but generally works ( breaks the documentation pass ).  I'll make a package with that.

**Comment by yuyichao** [comment]
Just replace the `eval(...)` with `eval($__module__, ...)`. Anyway, it's impossible to be fully generic so whatever works with you is fine.
