### ISSUE TITLE
don't show display for (nothing, nothing...)

### ISSUE THREAD

**Issue by phlavenk** [JuliaLang/julia#30258]
Would be consistent to ignore printing result tuple `(nothing, nothing,...)` the same way the result `nothing` is not written to the REPL. Occurs always when broadcasting to functions returning nothing.
If you give me hint which of `show` or `display` should be specialized for NTuple{Nothing}, I'll fill a PR.
MWE:
```julia
foo(x) = println("foo $x");nothing
bar(a...) = foo.(a)
bar(1,2,3,4)

foo 1
foo 2
foo 3
foo 4
(nothing, nothing, nothing, nothing)

foo(1)
foo 1
```

**Comment by KristofferC** [comment]
The singleton `nothing` is special because it is what is returned when a function doesn't return "anything" (like `print`) so it would be a bit spammy to always show it in the REPL (but it has been considered: https://github.com/JuliaLang/julia/pull/26209). In my opinion, doing the same for a tuple of noting seems taking it a bit too far. If you want to broadcast on something that returns `nothing` for its side effect it is typically better to use `foreach` or something since then you don't have to form any result at all.

**Comment by StefanKarpinski** [comment]
Not to be brusque, but we're not doing this.
