### ISSUE TITLE
Rename occursin to something more reasonable 

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#30368]
Everytime I encounter this function I visually parse it as `occur_sin`, and personally find it ugly. 
From slack there seems to be  a lot of people that share this sentiment.  It might be good to rename this function.

I tried searching for other programming languages that use the name `occursin`. I  found some usages where it was spelled as  `occursIn` in Java, which would more closely translate to  `occurs_in` in Julia (however I'm not a fan of the underscore and this is something that Base Julia tries to avoid in general). 

Stefan threw out the following in the thread: 
> `matches` would still be reasonable, or even `search` 

and later on threw out:   `ismatch`

**Comment by mbauman** [comment]
History:

* Initially had both `ismatch` and `contains`, but the two meant the same thing and were thus unified.  #19250, #24673.
* That wasn't liked very much, because `contains` swaps the argument orderings — and is in general opposite of our predicate tests.  #26211.
* One possible spitball to resolve the issue was to use `isfound` to support the opposite argument order. https://github.com/JuliaLang/julia/pull/26211#issuecomment-369718247
* We finally settled on using the name `occursin` to swap the argument orders. #26283

**Comment by StefanKarpinski** [comment]
Thought: Perl and Ruby use `~=` for matching. Not sure this is worth that bit of ASCII real estate, but I thought I'd mention it.

**Comment by ararslan** [comment]
That looks like it should be an updating `~`, i.e. `x ~= y` would be `x = x ~ y`.

**Comment by cormullion** [comment]
at least `within` is a real word... 😂

**Comment by KristofferC** [comment]
We put back `contains`.

**Comment by o314** [comment]
`ismatch` may has been a better choice to reach / provide some unary tester for `filter`, `find` api, eg.

```jl
ismatch(r::Regex) = (s) -> match(r, string(s)) !== nothing # could go in Base

using Test
@test filter(ismatch(r"[c-e]"), 'a':'z') == ['c','d','e']
```

Works not so well with `contains`
