### ISSUE TITLE
openblas segmentation fault

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaLang/julia#30725]
using julia 1.0.3, i get regularly:
```
OpenBLAS : Program will terminate because you tried to start too many threads.
Segmentation fault: 11
```
After that julia REPL quits.

**Comment by StefanKarpinski** [comment]
How many threads did you try to start?

**Comment by brianborchers** [comment]
This typically happens when the code that is calling an OpenBLAS routine is itself multithreaded.  Each invocation of OpenBLAS will itself start as many threads as you have processor cores, and then you'll end up trying to start n^2 threads where n is the number of cores.  Ideally, codes should be aware of how many threads they're using and  be able to control the number of threads used by subroutines called from the BLAS library.  One common strategy is to use multithreading at the higher level and then use only single threaded BLAS calls.  

Older versions of OpenBLAS had a fixed size buffer that would overflow (leading to this error message) if you tried to call BLAS routines from a bunch of different threads.  I believe that the most recent development version makes this unlimited.  However, you'd still have a very significant performance problem if you tried to run n^2 threads on n cores.  

There is no general solution to this problem- sometimes it's best to make the higher level code single threaded and let the BLAS routines run multithreaded, while other times it is better to run the higher level code multithreaded and run the BLAS routines single threaded.  Ideally, there would be some way for the programmer to control this at the higher level and tune the code for best performance.  

There's no easy way to control this the number of threads a subroutine is allowed to use if you're using pthreads multithreading.  With OpenMP multithreading, it should in theory be possible for OpenBLAS to be built using OpenMP in such a way that it respects OpenMP's methods for controlling the number of threads used by called routines but I'm not sure that this is working correctly (This is properly implemented in MKL.)  Of course, Julia would also have to use OpenMP to make this work.  

It's unlikely that you'll get a very quick solution to this problem. In the short term, there's a good chance that your code will work (and probably work most efficiently) if you simply call the BLAS routines only from single threaded portions of your code.  OpenBLAS should generally make good use of the available cores.   In the medium term (weeks to months), you'll probably see a version of Julia that works (because the limit on the number of threads has been eliminated)  but ends up oversubscribing your cores with n^2 threads running on n cores and doesn't perform well.  In that case you'll probably find that the code performs better if it only calls BLAS routines from within single threaded Julia code.

**Comment by brianborchers** [comment]
I believe that this is working with 0.6.4 is using an older version of OpenBLAS that doesn't have a particular bug that was introduced in an attempt to improve the code.  My comments above deal with some broader issues that don't appear to be the particular problem here.

**Comment by StefanKarpinski** [comment]
Sigh. This seems to be an upstream issue that we may not be able to do much about until OpenBLAS fixes it. Any thoughts on how to work around the underlying OpenBLAS issue?

**Comment by montyvesselinov** [comment]
I will try to design a reproducer. At the moment occurs after several executes. What is the magic number i do not know yet.

I did not specify explicitly anything about the number of workers or threads in the code. 

```
julia> Threads.nthreads()
1

julia> Base.Sys.CPU_THREADS
12
```

From the past, my experience was that JULIA_NUM_THREADS does not help here. But i will try to with 1 and see what happens.

**Comment by ImreSamu** [comment]
@montyvesselinov : 

Lot of `thread` related fixes in the https://github.com/xianyi/OpenBLAS/releases 
so please test with  Julia `v1.1.0-rc2` and julia `nightly`

Julia     |    OpenBlas
------     | -----------
V0.6.4     | v0.3.0
v1.0.3     | v0.3.2
[V1.1.0-rc2](https://julialang.org/downloads/)  | v0.3.3
[master/nightlies](https://julialang.org/downloads/nightlies.html )    | v0.3.5

**Comment by montyvesselinov** [comment]
`JULIA_NUM_THREADS=1` in the startup file did not help

**Comment by montyvesselinov** [comment]
will test Julia v1.1.0-rc2 and julia nightly

**Comment by montyvesselinov** [comment]
Tested extensively with Julia v1.1.0-rc2. OpenBlas segfault does not appear here. Now it all works. Thank you very much!
