### ISSUE TITLE
Julia 1.1.0 in MacOS: Segmentation fault when calling Dims on large array. 

### ISSUE THREAD

**Issue by galanakis** [JuliaLang/julia#30892]
The following code causes a segmentation fault in a freshly started REPL session.

```
julia> R=Array{Int64}(undef,32745673)
julia> Dims(R)
```

The crash output is

    signal (11): Segmentation fault: 11
    in expression starting at no file:0
    unknown function (ip: 0x108b56e62)
    jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1864
    eval_user_input at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/REPL /src/REPL.jl:89
    macro expansion at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/REPL    /src/REPL.jl:117 [inlined]
    #26 at ./task.jl:259
    jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1571 [inlined]
    start_task at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:572
   Allocations: 1091465 (Pool: 1091121; Big: 344); GC: 7

**Comment by Keno** [comment]
We should be able to do better, here, but worth pointing out that this is just because this is trying to create a very large tuple, which is not generally something that tuples are designed for, i.e.

```
R=Array{Int64}(undef,32745673)
tuple(R...)

Segmentation fault: 11
```

In particular, it tries to allocate a tuple of that size and then runs into a stack overflow that we don't detect because it skips more than one page. We'll need to add stack probing here.

**Comment by Keno** [comment]
I.e. the action item here is https://github.com/JuliaLang/julia/issues/25523
