### ISSUE TITLE
String interpolation should call `string` on each argument

### ISSUE THREAD

**Issue by christopher-dG** [JuliaLang/julia#30916]
```julia
julia> struct Foo end

julia> Base.string(::Foo) = "FOO"

julia> "$(Foo())"
"FOO"

julia> "...$(Foo())..."
"...Foo()..."
```

I would expect both `Foo`s to look the same. The cause is that `string(x, y)` is not necessarily the same as `string(x) * string(y)` or `string(string(x), string(y))`. 

So this is equivalent to the above example: 

```julia
julia> string(Foo())
"FOO"

julia> string("...", Foo(), "...")
"...Foo()..."

**Comment by StefanKarpinski** [comment]
Would be nice to allow overriding interpolation behavior through 1-arg `string` instead of having to do something hackier. Should be a viable minor change:

* it changes lowering but that's not guaranteed to be stable
* once `string` has been called on a value, calling `string` again should be safe

But technically breaking since some lunatic _could_ have defined 1-arg `string` to return something weird instead of a string.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/21982

**Comment by yuyichao** [comment]
For the current implementation, the reason is that you are overloading the wrong function. The doc should certainly be more clear on that (see linked issue).

That is not to say the behavior can never be changed but since a correct way to do what you want actually exist the case you gave isn't a good reason for the behavior change. If you have any other doubt of the doc and or the design, feel free to comment in the other issue.

**Comment by christopher-dG** [comment]
Thanks for linking that issue, I hadn't thought to overload the two-argument method. I do think that the existence of that distinction makes things extremely confusing to someone without knowledge of the internals (me, twenty minutes ago), so I'd still vouch for the behaviour being made consistent.

**Comment by yuyichao** [comment]
> I do think that the existence of that distinction makes things extremely confusing to someone without knowledge of the internals

Not sure about "extreme" but I agree there's something you need to get used to here. I looked for my old post on a similar issue but couldn't find it so I'll just post a summary.

In general, we have some functions that are meant to be overloaded directly and some other function that are meant to be used as wrapper around the overloadable functions. Even when it's not for efficiency, this is actually needed to maintain consistency across different functions. (i.e. if you overload `show` in this case, `string`, `print`, and `show` will all behave exactly the same way)

I don't think we can ever get rid of functions that are not meant to be directly overloaded. (Since that basically means letting everyone implement everything), the only thing we can do here in general is to make it more clear what you are allowed to overload and/or what is the correct way to customize a function.

**Comment by christopher-dG** [comment]
Updated my comment to be less dramatic, thanks for the info!
