### ISSUE TITLE
CI: UDP is broken on Travis Linux

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#31040]
Example: https://travis-ci.org/JuliaLang/julia/builds/491470105.

**Comment by c42f** [comment]
Dup of https://github.com/JuliaLang/julia/issues/27788.

I've been seeing on and off for the last few months. I believe it's due to IPv6 being sporadically unavailable on Travis (despite @vtjnash's best efforts to re-enable it on the loopback device in .travis.yml, which usually works... but not always).
