### ISSUE TITLE
textwidth returns wrong width for some unicode strings

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#31075]
Here is the repo:
```julia
julia> s = "\u644\u623"               
"لأ"                                  
                                      
julia> textwidth(s)                   
2                                     
                                      
julia> println("123"); println(s, "X")
123                                   
لأX                                   
```
I can reproduce this on Windows and Mac.

`textwidth` here tells me that this will take two columns, but when I `println` the string, it only takes one column.

**Comment by Keno** [comment]
These kinds of things depend on the terminal emulator unfortunately, and there isn't a good way to know what it'll do (e.g. it's correct on iTerm2):
<img width="283" alt="screen shot 2019-02-14 at 6 12 59 pm" src="https://user-images.githubusercontent.com/1291671/52823798-397fbd80-3084-11e9-96fc-0408c3ee945a.png">

The textwidth function is a bit best effort.

**Comment by davidanthoff** [comment]
Just for completeness, this is what I get on a standard Ubuntu install:

![image](https://user-images.githubusercontent.com/1036561/52826124-72b03180-3074-11e9-9a50-447cb825d347.png)

Is this the terminal emulator, or just the font that is used? This all looks like ligature issues, right? In particular, Windows and Mac seem to apply a ligature here that I think is probably correct (Word also applies it), whereas iTerm2 and Ubuntu don't. But I guess if this is happening at the font/presentation level, there is really no way to come up with a proper width... That is kind of frustrating. The issue shows up for any table type that has strings like that in it, then all the nice grid printing on the REPL is messed up. Is there potentially a way to use terminal escape sequences to position the cursor for the printing of say the vertical lines between columns, and thus work around this issue?

**Comment by mgkuhn** [comment]
The old Japanese EUC character encoding had a well established practice of which characters occupied a single VT100-style "monospaced" font cell, and which were double-width characters that occupied two cells: characters from 8-bit encodings were single-width and characters from 16-bit encodings were double-width. However, that convention (e.g., Cyrillic characters being displayed double-width) didn't really make sense in practice. The Single Unix Specification has C library functions wcwidth() and wcswidth() that determine how many such character cells a character or string occupy, but these functions made only sense with the old CJK/EUC encodings, where that width was de-facto implied by the encoding. With Unicode there was never any such well-established unambiguous convention of how many character cells a particular Unicode character should occupy on a terminal. I did propose a standard convention more than 20 years ago in the form of [wcwidth.c](https://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c), and some VT100 terminal emulators (e.g., xterm) that switch between two fonts do still use some variant of that function, but many other terminal emulators just specify a priority list of fonts to pick glyphs from, and leave it to the font designer which character appears how wide in which font. Therefore, there is no way that a library function that doesn't know what terminal emulator and what font priority scheme is used can predict how wide a string will appear on the terminal. To get any certainty on that matter, the application has to select the font to be used for each character.

**Comment by JeffBezanson** [comment]
I'm going to close this since unicode character widths are not canonical. Please reopen if anybody thinks something can be done though.

**Comment by mnemnion** [comment]
I assume some permission I don't have is needed to reopen an issue (fine by me), but I propose this one be reopened.  It would take extraordinary effort, involving user-specified manual exceptions, to get perfect behavior out of `textwidth`, but the perfect shouldn't be the enemy of the good. 

Let me show some motivating examples of the fix I'll be proposing.

```julia 
julia> textwidth("🫶🏼")
4

julia> textwidth("👨🏻‍🌾")
6

julia> textwidth("🏳️‍🌈")
3
```
Since the REPL uses textwidth (I assume from the results), this makes the cursor do strange things as well. 

But consider:

```julia
julia> textwidth("🫶🏼"[1])
2

julia> textwidth("👨🏻‍🌾"[1])
2

julia> textwidth("🏳️‍🌈"[1])
1

julia> length(graphemes("🫶🏼"))
1

julia> length(graphemes("👨🏻‍🌾"))
1

julia> length(graphemes("🏳️‍🌈"))
1
```

So `textwidth` could use `isgraphemebreak!` to find grapheme boundaries, and take the width of the first character of a grapheme.  That doesn't work for 🏳️‍🌈, which is actually why I included it, the first character is "🏳️", which `textwidth` reports as single-width, prints as single width for my particular set of fonts in the terminal, and which, given the fonts I have installed for the browser, prints as double-width here.

So no, Unicode characters don't have canonical values, and the problem can't be solved in the general case.  But this change would improve the the defaults for most combined emoji, all of which get a bad width reading from current `textwidth`, and I haven't found a counterexample where "take grapheme, return width of first Char" gives a worse result than `textwidth` does currently, and this is unlikely, because `textwidth` works a Char at a time, with no memory. So when it recognizes zero width, which it often can:

```julia
julia> textwidth("ă̷̢̨̧̢̧̧͉̞̬͓͉̯̥̘̭̘̪̣̺̻̫̣͉͔̦̪̟̪̞̩̺̬̜̘̞͈͕̭̞̟͉̯̠̺̲̠̘̔̈́̓̀̅͗͛͜͜͜͝ͅ")
1

julia> length(graphemes("ă̷̢̨̧̢̧̧͉̞̬͓͉̯̥̘̭̘̪̣̺̻̫̣͉͔̦̪̟̪̞̩̺̬̜̘̞͈͕̭̞̟͉̯̠̺̲̠̘̔̈́̓̀̅͗͛͜͜͜͝ͅ"))
1

julia> "ă̷̢̨̧̢̧̧͉̞̬͓͉̯̥̘̭̘̪̣̺̻̫̣͉͔̦̪̟̪̞̩̺̬̜̘̞͈͕̭̞̟͉̯̠̺̲̠̘̔̈́̓̀̅͗͛͜͜͜͝ͅ"[1]
'ă': Unicode U+0103 (category Ll: Letter, lowercase)

julia> textwidth("ă̷̢̨̧̢̧̧͉̞̬͓͉̯̥̘̭̘̪̣̺̻̫̣͉͔̦̪̟̪̞̩̺̬̜̘̞͈͕̭̞̟͉̯̠̺̲̠̘̔̈́̓̀̅͗͛͜͜͜͝ͅ"[1])
1
```
This would give the same result, and would fix spurious reports of extra width for combined emoji graphemes. 

Of course, an error-free `textwidth` would need to know intricacies of the terminal, fonts, and text rendering software, this is entirely impractical, besides which, `textwidth` is available in any Julia program, not just at the REPL. 

What is possible, and worth considering, would be an `ENV` variable like `"TEXTWIDTH_CUSTOM_WIDTHS"`, which could be set to a `Dict{Char,Int}` which `textwidth` would handle as directed.   That would let users correct the width of characters when they notice that `textwidth` is wrong for their local setup. If I'm a representative sample, people tend to use a subset of Unicode, and if the width of one of those is off, it's an immediate annoyance because of the effect on terminal editing. An affordance like this would make it tractable to customize that behavior for the characters someone actually uses. 

It would make `textwidth` slower by a constant factor, but my impression is that code which uses `textwidth` is basically never performance-sensitive. The grapheme patch I describe above would have negligible performance impact. 

I'd like to attach a PR for this issue, unfortunately I'm still not able to build Julia locally, for obscure reasons.
