### ISSUE TITLE
`redirect_stdout` documentation is out of date

### ISSUE THREAD

**Issue by rdeits** [JuliaLang/julia#31145]
The documentation for the second method of `redirect_stdout` is: 

```julia
  redirect_stdout(f::Function, stream)

  Run the function f while redirecting stdout to stream. Upon completion, stdout is restored to its prior setting.

  │ Note
  │
  │  stream must be a TTY, a Pipe, or a socket.
```

but passing a `Pipe` doesn't actually work: 

```julia
julia> pipe = Pipe()
Pipe(RawFD(0xffffffff) init => RawFD(0xffffffff) init, 0 bytes waiting)

julia> redirect_stdout(pipe) do
         println("hello world")
       end
ERROR: MethodError: no method matching redirect_stdout(::Pipe)
Closest candidates are:
  redirect_stdout() at stream.jl:1001
  redirect_stdout(::Union{IOStream, LibuvStream}) at stream.jl:995
  redirect_stdout(::Function, ::Any) at stream.jl:1051
Stacktrace:
 [1] redirect_stdout(::getfield(Main, Symbol("##3#4")), ::Pipe) at ./stream.jl:1053
 [2] top-level scope at none:0
```

What types are actually supported for redirection like this?

**Comment by tlienart** [comment]
I'd be happy to suggest a PR here but would need to check that I'm understanding the code right,

1. The functions `redirect_*(f::Function, stream)` are defined at https://github.com/JuliaLang/julia/blob/master/base/stream.jl#L1079-L1091
2. in there, there's a call `$F(stream)`; these functions are defined on 
https://github.com/JuliaLang/julia/blob/master/base/stream.jl#L1006-L1037
3. these lines define among other things `_redirect_*(stream)` (the `($_f)(stream)`) and `redirect_*(handle::Union{LibuvStream, IOStream})` (the `($f)(handle::...)`) which  itself calls `_redirect_*`

I'm not sure what's the semantic difference between a `handle` and a `stream` but would I be right to assume that the 3d point is the one we care about and so that the redirect works for any `x` that verifies `x isa Union{LibuvStream, IOStream}`? i.e. `IOStream` and the subtypes of `LibuvStream`: `Base.BufferStream`, `Base.PipeEndpoint`, `Base.TTY`, ...

Indeed IOStream works fine:

```julia
foo() = println("hello")
open("test.test", "w") do outf
    redirect_stdout(outf) do
        foo()
    end
end
```

So should the doc just be updated to specify that the stream must be ` <: Union{Base.LibuvStream, IOStream}` and maybe add an example like the one above?

**Comment by vtjnash** [comment]
we should support `Pipe`

**Comment by laborg** [comment]
Pipe is supported since https://github.com/JuliaLang/julia/pull/39132 landed
