### ISSUE TITLE
Can't connect Julia to Jupyter Notebook

### ISSUE THREAD

**Issue by Theqbat** [JuliaLang/julia#31307]
Hello, 
I'm having issues with connecting Julia to Jupyter Notebook. I've been following [this guide](https://www.youtube.com/watch?v=uRIQXJXRtqg) but a problem occurs at the point where I have to type Pkg.add("IJulia") or when pressing ] first and then typing add IJulia. 
A progress bar appears saying "Fetching", goes from 0 to 100%, nothing happens for about 40-50 seconds and then [this SystemError appears](https://pastebin.com/qsW8y99e)

To even begin with writing Pkg.add("IJulia") I had to first write import Pkg otherwise it'd say the following:

julia> Pkg.add("IJulia")
ERROR: UndefVarError: Pkg not defined
Stacktrace:
[1] top-level scope at none:0

I'm relatively new to programming, completely new when it comes to Julia, and definitely clueless when it comes to troubleshooting. I haven't found any way to solve this issue, haven't found any similiar problems in google, nor do I understand what the problem exactly is. 

Does anyone have an idea about what could I do about this?
Thanks for your help,
kind regards

**Comment by Keno** [comment]
Hi there, we generally try to keep the issue tracker for issues that are immediately actionable in the code base. In this case, I think some initial troubleshooting will be necessary. I'd recommend you head over to the Julia Discourse at https://discourse.julialang.org/ and ask for troubleshooting help there. Ideally include how you installed julia and anything else that may contribute (e.g. did you previously interrupt the registry cloning process, or did something else go wrong a previous time). Then if it turns out there's an actionable issue, you'll be directed to the appropriate issue tracker.
