### ISSUE TITLE
`joinpath` able to handle output of `splitpath`

### ISSUE THREAD

**Issue by jullit31** [JuliaLang/julia#31368]
It would be very handy if `joinpath` could "undo" `splitpath`, i.e.
```julia
joinpath(splitpath("/path/to/somewhere"))
```
should work and return `"/path/to/somewhere"`.

**Comment by Keno** [comment]
You can just splat the result into joinpath:
```
julia> joinpath(splitpath("/path/to/somewhere")...)
"/path/to/somewhere"
```

**Comment by StefanKarpinski** [comment]
We could also just allow `joinpath` to work on a collection of paths. In fact, that should be the core method which the varargs method calls.

**Comment by jullit31** [comment]
@Keno Thanks! That's a lot better than the workaround I came up with.
However, I still think it would be more intuitive if what I suggested worked. (Unless, of course, there is a reason for it not to work.)

**Comment by StefanKarpinski** [comment]
The only issue would be a dispatch conflict between the varargs and container version but that would only occur in the case of a single string argument which is ok. In general since we tell people not to use splatting for this kind of thing we should be consistent and provide a non-splatting API here as well.
