### ISSUE TITLE
ERROR: type Schur has no field T

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#31477]
```
julia> using DoubleFloats, LinearAlgebra

julia> df = reshape(rand(Double32, 5*5), 5, 5)
5×5 Array{DoubleFloat{Float32},2}:
 0.60097873  0.9829146   0.5978393   0.12267983  0.9307427 
 0.08192396  0.80205476  0.64310557  0.9944741   0.9047501 
 0.8361933   0.4409654   0.7816784   0.32059634  0.55601054
 0.22082317  0.80192906  0.9319419   0.64971256  0.5946293 
 0.46893406  0.21984947  0.37794232  0.09353495  0.324728  

julia> sqrt(df)
ERROR: type Schur has no field T
Stacktrace:
 [1] getproperty(::Any, ::Symbol) at ./sysimg.jl:18
 [2] sqrt(::Array{DoubleFloat{Float32},2}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/dense.jl:704
 [3] top-level scope at none:0
```

**Comment by tkluck** [comment]
As far as I can tell, this is because [GenericLinearAlgebra.jl](https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl) has [its own data structure for representing the Schur decomposition](https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/blob/master/src/eigenGeneral.jl#L62) and [hijacks the built-in `schur!` method](https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/blob/master/src/eigenGeneral.jl#L165). You got affected by this because `GenericLinearAlgebra` is a dependency of `DoubleFloats`.

It's not a Julia issue, so this report should probably be closed. The best place to report it, is here: https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/issues/new

**Comment by JeffreySarnoff** [comment]
Thank you for the insight.
