### ISSUE TITLE
startup.jl is executed before REPL is started

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#31566]
... and it causes a problem with the ordering of `Base.Multimedia.displays`.

specifically, if my startup.jl is empty, and i manually `using Gadfly` at the REPL, `GadflyDisplay` is appended as the last entry, and plots automatically appear in the default browser.  but if i put the `using` in `startup.jl`, the last entry is `REPLDisplay`, and nothing gets plotted.

seems to me that adding stuff to `startup.jl` should behave *exactly* as if the user cut&paste it into the REPL as the very first thing they did when they started julia.

this is for julia 1.1 btw;  apologies if this behavior has changed in 1.2.

**Comment by KristofferC** [comment]
This seems to be a bit of an X-Y problem. You want to be able to more flexibly handle the `Display` stack but the issue is about the order of things getting loaded. `startup.jl` need to be loaded before the REPL because it can also provide different initialization callbacks for the REPL (see `atreplinit`).

For the `Display` stack issue, see https://github.com/JuliaLang/julia/pull/30922.

**Comment by bjarthur** [comment]
thanks for the link, and for suggesting `atreplinit`.  the latter is a good workaround.
