### ISSUE TITLE
apply_any gets specialized despite annotations to the contrary

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#31565]
After running the JuliaInterpreter tests, I get this:
```julia
julia> m = first(methods(Base.append_any))
append_any(xs...) in Base at essentials.jl:663

julia> m.specializations.func
MethodInstance for append_any(::Vararg{Any,N} where N)

julia> m.specializations.next.func
MethodInstance for append_any(::Tuple{Any}, ::Vararg{Any,N} where N)

julia> m.specializations.next.next.func
MethodInstance for append_any(::Any, ::Vararg{Any,N} where N)
```
This is despite the intention to avoid specialization: https://github.com/JuliaLang/julia/blob/b073bb5ba693565859b8e9b4179c2d8402289c1c/base/essentials.jl#L662-L663 Unfortunately, this isn't fixed by changing the declaration to
```julia
function append_any(@nospecialize xs...)
```

**Comment by JeffBezanson** [comment]
`nospecialize` means that separate code will not be generated for different signatures, but the function can still be inferred on different argument types, which is probably what we're seeing here. A `noinfer` would be more dangerous, since it would have nonlocal effects, injecting worse type info into callers that might need the performance.
