### ISSUE TITLE
pkg.julialang.org website js file Compression

### ISSUE THREAD

**Issue by zxj5470** [JuliaLang/julia#31622]
I notice that this site use Vue with webpack. Though it is very nice，But a file with 1.5MB is still too large. 
![image](https://user-images.githubusercontent.com/20026798/55614994-e4794180-57c0-11e9-84a1-ea5e636f4920.png)

Here's my suggestion: Use CompressionPlugin in webpack. Then make it become just 300KB

Just need to add   `  "compression-webpack-plugin": "^2.0.0",` into `"devDependencies","package.json"
and add this plugin into `webpack.config.js`

```javascript
const CompressionPlugin = require("compression-webpack-plugin");
module.exports = {
//...
plugins: [
//...
new CompressionPlugin({
            algorithm: 'gzip',
            test: new RegExp(
                '\\.(js|css)$'
            ),
            threshold: 10240,// gt 10 KB
            minRatio: 0.8
        })
]
}
```

My website

![image](https://user-images.githubusercontent.com/20026798/55614586-eb538480-57bf-11e9-9980-43d418ea7560.png)

![image](https://user-images.githubusercontent.com/20026798/55614854-906e5d00-57c0-11e9-9442-10d5ebb82da5.png)

![image](https://user-images.githubusercontent.com/20026798/55614826-7896d900-57c0-11e9-8712-d4505d1b9499.png)

**Comment by pfitzseb** [comment]
This issue is more appropriate for [here](https://github.com/JuliaDocs/DocumentationGenerator.jl/issues) (since that is where the website is generated).

So far there has been approximately zero effort invested into making the site actually performant -- the reason why we're shipping such a large blob is that *all* package data is shipped on page load. We should definitely not do that long term and instead load that data from the server incrementally.

In the meantime this is still a great idea, so we'll of course go with it. Thanks!
