### ISSUE TITLE
Add docs for JULIA_DEBUG

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#31741]
Add JULIA_DEBUG to docs and also the 
JULIA_DEBUG environment variable section should be expanded to explain how to turn on the debug message in the REPL as well (cf https://docs.julialang.org/en/v1/stdlib/Logging/#Environment-variables-1)

**Comment by c42f** [comment]
In my opinion `JULIA_DEBUG` is kind of a non-composable hack (a very useful one, I'll admit).

But with this in mind, I'd prefer if we work toward replacing it with something more composable and future proof rather than documenting it as the preferred way to do filtering.

See for example, the package `LoggingExtras`
