### ISSUE TITLE
sort tuples

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#31818]
Why `sort` cannot handle `Tuple`s? `sort((3,2,4,1))` is an error.
I think it should simply return the sorted tuple, in cases where `<` can be applied to any pair of elements in the tuple.

**Comment by StefanKarpinski** [comment]
That's a pretty odd use case. Pretty much all sorting algorithms rely on being able to swap elements in the collection being sorted, which you can't do with a tuple since it's immutable. It also suggests that you're using a tuple as a container when you should probably be using a real container like an array. What is the use case for this?

**Comment by cossio** [comment]
> Pretty much all sorting algorithms rely on being able to swap elements

That's true. I was just surprised at first that this didn't work.

**Comment by ericphanson** [comment]
In case you still do want to sort tuples, [TupleTools.jl](https://github.com/Jutho/TupleTools.jl) provides a function to do so without allocations.

**Comment by StefanKarpinski** [comment]
Cool! I didn't know about TupleTools. Some of those methods could probably go in Base.

**Comment by ericphanson** [comment]
I've been using it to sort static vectors, via
```julia
using StaticArrays, TupleTools
import Base.sort
sort(p::SVector{d,T}; rev::Bool = false) where {d,T} = SVector{d,T}(TupleTools.sort(Tuple(p); rev=rev))
```
It would be nice if `TupleTools.sort` made it into Base, since then `StaticArrays.jl` could use it for sorting without taking on a dependency on `TupleTools`. It might be slow for long tuples, but since there's no method at all now, it wouldn't be a regression or anything.

**Comment by gasagna** [comment]
@StefanKarpinski Should this issue be reopened and then closed agains when some of `TupleTools` finally comes to Base?

**Comment by KristofferC** [comment]
> It would be nice if TupleTools.sort made it into Base, since then StaticArrays.jl could use it for sorting without taking on a dependency on TupleTools

Instead, in effect, the whole world takes on a dependency on TupleTools?

Sorting tuples makes sense for StaticArrays but there is no need to add stuff for Base to it.

**Comment by Roger-luo** [comment]
I think one problem is the type piracy. TupleTools defines its own functions for `Tuple` in order to avoid type piracy, however these functions have the exact same interface with Base. Which means if I define a generic function `foo` which takes a list-like thing which can be tuple or Vector in, e.g

```jl
function foo(x)
    sort(x)
    # blabla
end
```

in order to make it work for tuple, I have to define an intermediate method `_sort` which re-dispatch things to `TupleTools.sort`, which can be annoying and not necessary. 

I'm willing to open this PR, if people think it is welcome to Base.

**Comment by KristofferC** [comment]
As been said, sorting "naked" tuples is often not needed. StaticArrays could easily do

```
Base.sort(S::StaticArray, ...)
    StaticArray(tuple_sort(S.data))
end
```

This is the same as e.g. `+`. We don't need `+` on tuples to be defined in Base so you can do `+` on two StaticArrays.

**Comment by Roger-luo** [comment]
I'm not saying just `sort`, there are a bunch of them (also like `diff`), and that is why I was contributing to `TupleTools`, as a very very basic data type, you can't just assume this is rare and kick it out of `Base`, even it is one line, it is convenient, and both the type and function are defined in `Base`, or how can one implement these without making type piracy.

At least I have a use case for `diff`: https://github.com/QuantumBFS/YaoBase.jl/blob/master/src/compat.jl and I really have no idea what's the point to force people write this kind of code for compatibility.

**Comment by goretkin** [comment]
What of defining `sort(x::NTuple{2}) = minmax(x...)`? `min`/`max` promote their arguments, whereas `sort` does not promote all of the elements:

```julia
julia> sort(Any[2.0, 1])
2-element Vector{Any}:
 1
 2.0
```

hence the definition on `NTuple{2}` and not `Tuple{A, B}`.
