### ISSUE TITLE
Writing a macro generates code utilizing NamedTuple whose value is calculated

### ISSUE THREAD

**Issue by runapp** [JuliaLang/julia#32121]
I'm writing a macro tha packs it's parameter and @__FILE__ into a NamedTuple and push it into a Vector, like this:

```julia
testvec=Vector{NamedTuple{(:f,:s),Tuple{Int,String}}}()
# push!(testvec,(f=0,s="abc"))
macro testm(a)
    return quote
        b=a+1
        push!(testvec,$(esc(
            (f=b,s=@__FILE__)
        )))
    end
end
@testm 2
```

My think is to try avoiding other ways than esc to prevent `f` and `s` from being renamed, or to make b work in escaped environment. However I tried `$(esc(b))=a+1` and other escape forms, with none of them succeeded.

Any suggestions?

**Comment by KristofferC** [comment]
Please use https://discourse.julialang.org/ for general Julia questions.

**Comment by runapp** [comment]
Forget about it.
Finally got `$(esc(begin b=a+1 end))` to work.
I post it here rather than asking on discourse or StackOverflow only to see if anybody wants some new syntax to make it more elegent, such as makes `global` accept symbols.

**Comment by JeffBezanson** [comment]
I think there is also a hygiene bug here though:
```
julia> macro id(x)
       x
       end
@id (macro with 1 method)

julia> @id (a=1,)
(#12#a = 1,)
```

**Comment by tkluck** [comment]
@KristofferC I'm seeing this behaviour on Julia master, also related to named tuple hygiene:
```
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.0-DEV.189 (2019-09-21)
 _/ |\__'_|_|_|\__'_|  |  Commit 36220ed9c7* (3 days old master)
|__/                   |

julia> macro named_tuple_hygiene(key, value); return :( (a=1, $key => $value) ); end
@named_tuple_hygiene (macro with 1 method)

julia> @named_tuple_hygiene(:b, 2)
ERROR: syntax: invalid named tuple element "Main.=>(:b, 2)"
Stacktrace:
 [1] top-level scope at REPL[2]:1

```

I think the root cause is that named tuple syntax [Angers The Lisp Gods](https://github.com/JuliaLang/julia/pull/24990#issuecomment-478197476): within a `Expr(:tuple, ...)`, the expression `Expr(:call, :(=>), key, value)` has a meaning different from "call `=>` on `key` and `value`".

One proper fix would be to parse it differently: e.g. we should have `(a = b, c => d)` parse to something like
```
Expr(:tuple, Expr(:(=), a, b), Expr(:(=>), c, d))
```
An alternative fix is to allow pair-valued expressions as elements of named tuples (currently a syntax error), e.g.

```
julia> keyval = :b => 2
:b => 2

julia> (a=1, keyval)
ERROR: syntax: invalid named tuple element "keyval"
Stacktrace:
 [1] top-level scope at REPL[4]:1
```

But given that you've worked on this recently, maybe we can come up with a solution that only touches the macro hygiene logic. What do you think?

**Comment by KristofferC** [comment]
I'm not sure why I was pinged here?

**Comment by tkluck** [comment]
I pinged you because of this:
![afbeelding](https://user-images.githubusercontent.com/2110529/65600124-ce924f80-df9f-11e9-822a-07914cd0cc5b.png)
Is there someone else who is in a better position to check it out?

**Comment by KristofferC** [comment]
Oh, that's just cause I backported that commit to some release. https://github.com/JuliaLang/julia/pull/32464 is the original PR.

**Comment by tkluck** [comment]
Ah that makes sense, sorry for the noise! Added a comment there as well.
