### ISSUE TITLE
Inconsistency in constructing Dict and Array

### ISSUE THREAD

**Issue by ingmarschuster** [JuliaLang/julia#3214]
Both Dict and Array are parametric types. Constructing a Dict and an Array of variable size differs markedly, though:
    * `Dict{TypeA,TypeB}()`
    * `Array(Type)` while `Array{Type}()` doesn't work
This creates some confusion for people new to the language – also I think its inconsistent design.

**Comment by nalimilan** [comment]
Anyway it doesn't make much sense to try converting a `Number` to an `Array`, so assuming a single `Number` represents the size of the first dimension sounds fine. As regards tuples (cf. https://github.com/JuliaLang/julia/issues/9370#issuecomment-67075089), we can require splatting, so that you'd need to write `Array{Int}((2, 2, 2)...))` if `(2, 2, 2)` is the size of the new array.
