### ISSUE TITLE
sum(::Diagonal) visits zero elements

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#32178]
```
julia> C = Diagonal(1:10000);

julia> @time sum(C);
  0.173762 seconds (14 allocations: 528 bytes)

julia> @time sum(C.diag);
  0.000008 seconds (6 allocations: 208 bytes)
```

Perhaps there should be a specialized method that only visits the diagonal elements?

**Comment by cossio** [comment]
An easy solution is to define `sum(A::Diagonal) = sum(A.diag)`?

**Comment by mfalt** [comment]
It seems like there is a general problem with `sum(C, dims=1), sum(C, dims=2), sum(b, dims=(1,2))` (and `mapreduce`) for diagonal, and maybe similar matrices.

The first is regarding using a `SparseArray` as output. 
If `b::Diagonal` then we get a `SparseArray` result because of the generic `mapreduce` where we in https://github.com/JuliaLang/julia/blob/9a3e1c79caa530d0c2ee98c8e92dd4eb2e3607dc/base/reducedim.jl#L108
get calls to
`c = similar(b, Float64,  Base.reduced_indices(b, 1))` and
`c = similar(b, Float64,  Base.reduced_indices(b, 2))`
which are `SparseArrays`

The second problem is that we seem to visit all zero elements in the call to https://github.com/JuliaLang/julia/blob/96008dcd462735218d219ccd504da7c6d5298d1f/base/reducedim.jl#L236
`_mapreducedim!(identity, Base.add_sum, c, b)`
for both sparse and dense `c` when `b::Diagonal`.

I am not sure where the best place is to catch these behaviors.

**Comment by mfalt** [comment]
@andreasnoak Should I open a new issue for my comment?
