### ISSUE TITLE
LU and Cholesky -- Type of matrices output differ

### ISSUE THREAD

**Issue by hochB** [JuliaLang/julia#32302]
LU decomposition in linear algebra decomposes a matrix in an upper triangular matrix and a lower triangular matrix.
Cholesky too.

Julia does this correctly, but I noticed LU returns 2 matrices of type `Array` with zeros where needed to make it triangular. OTOH Cholesky returns matrices that are of type `UpperTriangular` and `LowerTriangular`.

Any reason for LU not using explicitly the types?
Or the other way around?
Could there be any benefit?

**Comment by andreasnoack** [comment]
Good question (but please ask questions in Discourse). The reason is that the factors in `Cholesky` will always be square whereas that is not the case for `LU`. We restrict the triangular types to be square. It could be changed if we decided it would be beneficial but it would complicate code that uses triangular matrices.
