### ISSUE TITLE
Allocation-heavy code is slower with Threads than Distributed

### ISSUE THREAD

**Issue by robsmith11** [JuliaLang/julia#32304]
As a follow-up to https://github.com/JuliaLang/julia/issues/31923, I was testing the same example with the current master and see that while memory usage is now fixed, it's still running nearly 40% slower with Threads vs Distributed:

```julia
julia> @btime Threads.@threads for _ in 1:10^4
       collect(1:10^6)
       end
  6.930 s (20032 allocations: 74.51 GiB)

julia> addprocs(4, restrict=true, exeflags=`--optimize=3 --inline=yes --check-bounds=no --math-mode=fast`, topology=:master_worker)
4-element Array{Int64,1}:
 2
 3
 4
 5

julia> @btime @sync @distributed for _ in 1:10^4
       collect(1:10^6)
       end
  5.024 s (616 allocations: 23.23 KiB)
Task (done) @0x00007efed2a8a980

julia> versioninfo()
Julia Version 1.3.0-DEV.395
Commit b7774095f6 (2019-06-11 21:06 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.0 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

EDIT:  IDK if relevent: if I bump the number of threads to 8 (to match the number of hyperthreads), the Threads performance matches the Distributed performance with 4 workers.  Distributed performance is unchanged when increasing workers from 4 to 8.

**Comment by JeffBezanson** [comment]
I'm not sure this is entirely surprising; if the iterations/threads don't share any state at all then there is no benefit to using shared memory. Then there will be some slowdown probably from stop-the-world GC. What is the % GC time?

**Comment by robsmith11** [comment]
```
julia> @benchmark Threads.@threads for _ in 1:10^4
       collect(1:10^6)
       end
BenchmarkTools.Trial:
  memory estimate:  74.51 GiB
  allocs estimate:  20034
  --------------
  minimum time:     7.138 s (15.14% GC)
  median time:      7.138 s (15.14% GC)
  mean time:        7.138 s (15.14% GC)
  maximum time:     7.138 s (15.14% GC)
  --------------
  samples:          1
  evals/sample:     1
```

I see.. so when a lot of GC is needed, then multiple processes are more efficient than multiple threads on a single process because the stop-the-world GC interupts all threads on the single process, whereas with separate processes, the GC can run in parallel without interupting the other threads?

I had expected threads to generally be more efficient because of the lack of IPC overhead, but I guess the GC can be a bigger factor.

**Comment by robsmith11** [comment]
Using one of my actual projects, which shouldn't require much GC, the difference between 8 workers and 8 threads is much greater (timings are consistent after multiple runs):

```julia
julia> @time @sync @distributed for _ in 1:8; Sim3.run(1, 10^5, 0.1); end
 10.178123 seconds (167.71 k allocations: 8.227 MiB)
Task (done) @0x00007f11e204a4a0

julia> @time Threads.@threads for _ in 1:8; Sim3.run(1, 10^5, 0.1); end
 41.318770 seconds (54.79 k allocations: 179.964 MiB, 0.18% gc time)
```

**Comment by StefanKarpinski** [comment]
There's very little IPC here: you're just sending a range of integers to each worker. The work here also consists almost exclusively of repeated allocation of memory which is then immediately released, so this is a strange use case which is pessimal for shared memory GC.

**Comment by robsmith11** [comment]
It is an extreme example.  I guess my expectations were from using languages like Rust without GC where it pretty much always made sense to use threads rather than multiple processes when wanting to run something in parallel on a single machine.
Thanks for the explanations :)

**Comment by 0** [comment]
Thank you for fixing the recent memory issue and/or race condition! I've also been testing a minimal example using a recent commit (c630477), and while it makes sense to see some overhead, I was surprised to find linear scaling with the number of threads.

Specifically, I'm testing by running
```julia
@time Threads.@threads for _ in 1:Threads.nthreads()
    zeros(10^8)
end
```
inside my shell's `time` command with various values of `JULIA_NUM_THREADS`. My naive expectation was to see linear memory usage, but roughly constant time, since this looks like an embarrassingly parallel task. Instead, I get the following:

![memtest](https://user-images.githubusercontent.com/140823/59533434-71273680-8eb9-11e9-9407-e99a0d1a9ada.png)

For comparison, the dotted curves are from the same loop (with the same numbers of iterations) but run serially in a single thread.

I'm bothered by two things in particular. The first is that while I see about a 1/3 decrease in runtime at 32 threads compared to the serial case (5 s instead of 8 s), the average CPU usage goes up to 2200% from 100%, so the actual amount of work done changes from 8 core-seconds to 110 core-seconds, and that's a lot of overhead. The other is that the total amount of space allocated should match between the serial and threaded runs, but it looks like `@time` is losing track of a substantial portion in the threaded case.

**Comment by StefanKarpinski** [comment]
Seems like all the work is GC which is not concurrent, so that seems to be working as one would expect. Allocation is generally pretty fast, it's garbage collection that's slow. (This is also true of `malloc` and `free`—it's the `free` that's expensive). You may want to try doing something non-trivial in each thread. Allocating in parallel and then doing no computation is not going to scale without a concurrent GC, which we don't have.

**Comment by 0** [comment]
That makes sense, but `@time` reports that only about 15% of the time is spent doing GC. Am I interpreting that incorrectly?

I think I was confused by https://github.com/JuliaLang/julia/issues/31923#issuecomment-489681463, which said

> [...] the GC does not wait for the end of `@threads` to run. It can run during the loop and is fully multi-threaded.

That got me thinking that the GC is concurrent.

**Comment by JeffBezanson** [comment]
> That got me thinking that the GC is concurrent.

That's fair, but the very next sentence explicitly says it's not concurrent.

**Comment by JeffBezanson** [comment]
I can't reproduce the short allocation count with threads. Maybe double check that your build includes commit 5335a94b2e18c3f752b4abb343a12403b09de2cb?

**Comment by 0** [comment]
I can't reproduce it either anymore. Must've switched to the wrong binary at some point while testing. Sorry for wasting your time!
