### ISSUE TITLE
Base.runtests("REPL") fails, but not when run together with some other testset

### ISSUE THREAD

**Issue by sostock** [JuliaLang/julia#32377]
`Base.runtests("REPL")` (or `Base.runtests(["REPL"])`) fails, but running another testset together with it does not:

```julia
julia> Base.runtests(["REPL"])
[...]
Test Summary: | Pass  Fail  Broken  Total
  Overall     | 1007     1       5   1013
    REPL      | 1007     1       5   1013
    FAILURE

The global RNG seed was 0x975ed040f99437173b72ce7bc2fec875.

Error in testset REPL:
Test Failed at /home/sebastian/Development/julia/usr/share/julia/stdlib/v1.3/REPL/test/replcompletions.jl:107
  Expression: count(isequal("REPL"), c) == 1
   Evaluated: 2 == 1
[...]

julia> Base.runtests(["REPL", "cartesian"])
[...]
Test Summary: | Pass  Broken  Total
  Overall     | 1029       5   1034
    SUCCESS
```

This hapens on Julia 1.0.4, 1.1.1, 1.2.0-rc1, and master.

**Comment by tgflynn** [comment]
This seems to be related to the way runtests uses worker threads.

If you do:

```
export JULIA_CPU_THREADS=1
./julia
Base.runtests(["REPL", "cartesian"])
```
The tests still fail, like in the single test case.

**Comment by tgflynn** [comment]
Also of note:

```
include("stdlib/REPL/test/runtests.jl")
``` succeeds

but

```
using REPL
include("stdlib/REPL/test/runtests.jl")
```
fails.

**Comment by twhitehead** [comment]
I believe the issue is that the test system doesn't truly isolate tests. Specifically, the Main module space is shared by the test running system and the tests themselves. This has bad effects in the REPL module which has several implicit and explicit references to Main.

What is screwing up this particular test is that test/runtests.jl imports REPL to get REPL.Terminal. This adds the module REPL to the Main namespace and causes the using REP completion test in stdlib/REPL/test/replcompletions.jl to return the module REPL brought into scope by the test runner in addition to the expected package REPL.

I tried to see if this issue could be worked around by wrapping replcompletions.jl in a module Main statement to hide the global one. While it did resolve this issue, it causes a few of the other later tests to stop working for reasons I haven't fully figured out. My wild guess would be that it might have to do with my Main not having the magic global Main export everything automatically property.

A horrible hack to resolve the issue is to just change import REPL in test/runtests.jl to import REPL.Terminal and all REPL.Terminal. call prefixes to just Terminal. I only mention this to prove the point though, not to suggest it be done.
