### ISSUE TITLE
Slow File IO on CSV

### ISSUE THREAD

**Issue by esaliya** [JuliaLang/julia#32479]
I am trying to read a 33GB CSV file that contains just two integers on each row separated by ",".  There are 2967542280 (~3 billion) lines in the file. 

I tried to first read just 100 lines to assess the performance first.

I tried both the CSV package and just pure file IO but both appear to be much slower (~40x) than a Python counterpart. It's even worse with the CSV package (~20000x). Here are the three code samples (Julia and Python) and their times.

## Julia code `test.jl`
```
function fileio()
    mycsv=open("k10.overlaps.txt","r")

    limit = 100
    i = 1
    while(!eof(mycsv))            # <-- loop through each line of the file
       row = readline(mycsv)
       i+=1
       if (i == limit)
           break
       end
    end
end
```

```
@time fileio() # Output: 0.014108 seconds (5.88 k allocations: 310.827 KiB)
```

## Julia CSV code `test.jl`

```
function csvread()
    file = "k10.overlaps.txt"
    for row in CSV.File(file; header=["col_id", "row_id"], datarow=1, limit=100, use_mmap=true)
        x = 1
    end
end
```

```
@time csvread() # 6.144095 seconds (16.74 M allocations: 794.268 MiB, 6.12% gc time)
```

## Python code `test.py`

```
import csv
import time

overlaps_fname = 'k10.overlaps.txt'
t = time.process_time()

limit = 100
with open(overlaps_fname, 'r') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for g_col, g_row in csv_reader:
        if line_count == limit:
            break
        line_count += 1
print("Total time: ", (time.process_time() - t), "s")
```

```
python test.py # output: Total time:  0.00030068700000000087 s
```

I am using Julia version `1.1.1` and Python `3.7.2`. This was run on an Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz  processor with ~500GB RAM. The OS is SUSE Linux Enterprise Server 12 SP3.

Any help on this?

**Comment by jsulmont** [comment]
Hi @esaliya -- maybe try first taking this issue to the maintainers of [CSV.jl](https://github.com/JuliaData/CSV.jl)

**Comment by quinnj** [comment]
Yeah, this is more appropriate as an issue to the CSV.jl package. In general, it's a common issue with benchmarking to actually compare like operations, which often involves digging into code a bit to better understand what's really going on under the hood.
1. In this case, you're calling `readline(mycsv)` on each iteration, which in turn calls down to `readuntil` which is allocating a fresh Array, then `readline` calls `resize!`, and then calls `String` on the result, which does another copy of the data (hence the 5.88 k allocations in your timing).
2. When using `CSV.File`, not being built into the core language, has to dynamically compile when it's called the first time, hence the 6.1 seconds. If called again, you'll see dramatically improved results, since the same code has already been compiled, and will be reused. Also note that the use of `CSV.Rows` may be more appropriate for your use-case, which provides a very low-overhead iterator over rows of a csv file (you can even call `CSV.Rows(file; reusebuffer=true)` to re-use a single buffer while iterating over an entire file).
3. In this case, though I haven't checked specifically, I imagine that `csv.reader` is doing something similar to `CSV.Rows` where it's lazily loading csv rows when values are accessed. So since you don't actually access any values while iterating over the csv file, you're just benchmarking iterating over the file rows.

Feel free to check out the excellent [Performance Tips](https://docs.julialang.org/en/latest/manual/performance-tips/) section of the Julia manual as well for more tips.

**Comment by JeffBezanson** [comment]
> 2\. has to dynamically compile when it's called the first time, hence the 6.1 seconds. If called again, you'll see dramatically improved results

Yes, I suspect this is all compilation overhead.

**Comment by JeffBezanson** [comment]
For example:
```
julia> @time fileio()
  0.027838 seconds (4.77 k allocations: 247.610 KiB)

julia> @time fileio()
  0.000274 seconds (112 allocations: 3.859 KiB)
```

**Comment by JeffBezanson** [comment]
```
julia> @time csvread()
  7.217129 seconds (14.81 M allocations: 717.256 MiB, 5.99% gc time)

julia> @time csvread()
  0.000441 seconds (64 allocations: 6.281 KiB)
```
