### ISSUE TITLE
implement efficient tensor contraction operations

### ISSUE THREAD

**Issue by lsorber** [JuliaLang/julia#3250]
was: "Add tensor-matrix multiplication to *"

*Related julia-dev discussion: https://groups.google.com/d/msg/julia-dev/GAdcYzmibyo/iOLpyVQc8YIJ*

If A and B are two matrices of the proper dimensions, then `A*B` and and `B*A` are well-defined. Now let B be a tensor (say, three-dimensional), then these two operations are still defined in the multilinear algebra sense, but not yet in Julia. For the former, the effect is that each column vector `B[:,j,k]` of B is mapped to `C[:,j,k] = A*B[:,j,k]`. For the latter, each row vector `B[i,:,k]` of B is mapped to `C[i,:,k] = B[i,:,k]*A`. As you can see, this is a straightforward generalization of the matrix-matrix multiplication to tensor-matrix multiplication.

This would certainly be a very useful improvement to *, and should not take long to implement. In general, a tensor can be multiplied along all its dimensions (not just from the left and right as the * operator allows). It would also be nice to have a `tmmul`/`tmprod`/`tenmatmul`/... function that allows the user to multiply a tensor by a set of matrices from the left, right, front, etc. It might look something like this:
```julia
T = randn(5,6,7)
A = randn(10,5); B = randn(11,6); C = randn(12,7)

A*T == tenmatmul(T,A,1)            # is true
A*T == tenmatmul(T,{A,[],[]})      # is true
T*B.' == tenmatmul(T,B,2)          # is true
T*B.' == tenmatmul(T,{[],B,[]})    # is true

size(tenmatmul(T,{A,B,C},[1 2 3])) # is (10,11,12)
size(tenmatmul(T,{A,B,C},1,2,3))   # is (10,11,12)
size(tenmatmul(T,{A,B,C}))         # is (10,11,12)
size(tenmatmul(T,{A,[],C}))        # is (10,6,12)
```

**Comment by ettersi** [comment]
Despite the title, the discussion in this issue revolves mostly around syntax. Here is my proposition of what a handy way of expressing tensor operations would be: https://github.com/ettersi/Tensors.jl

**Comment by stevengj** [comment]
@ettersi, it seems like it would be much less awkward to use a macro like `@contract A[i,:,j] B[:,j,i]` where the repeated indices `i` and `j` are contracted.

**Comment by ettersi** [comment]
In what sense is your syntax less awkward than `A*B`? My notation does of course take some more characters to define `A` and `B`, but I assume you transform tensors more often than you create them. 

Also, the Einstein notation works only well as long as you know the dimensions of `A` and `B` and the indices to contract at the time of *writing* the code. What if I want to express "contract the `k`th index of `A` with the `l`th index of `B`" where `k` and `l` are only known at runtime? In this case, you would have to use the `contract` function mentioned above, but this quickly becomes a pain in the ass because you need to figure out the positions in which the uncontracted indices ended up in. For example, the position of the `ll`th index of `B` (`ll != l`) in `contract(A,k,B,l)` is `2 + (ll < l ? ll : ll -1`. That's already quite a nuisance, and this tracking of indices definitely becomes hard once you further allow contraction over sets of indices.

**Comment by stevengj** [comment]
@ettersi, you may contract the same tensors with different sets of indices at different times, in which case it is easier to specify the indices to contract at the point where they are contracted.

I'm not sure that cases where you have lots of contractions but the ranks are unknown is common...

**Comment by Jutho** [comment]
I have recently updated http://github.com/Jutho/TensorOperations.jl to work with julia v0.4.0 though these efforts are still living under the branch `staged` (because I started working on this when `@generated` functions where still called staged functions). The only thing that remains to be done is updating the documentation, but I unfortunately have no time for this currently.

Basically, the design has changed significantly. There is a macro approach towards tensor contractions (and related operations such as partial trace and permutations) which just accepts Einstein summation convention. This very close to the suggestion of @stevengj, though I find it favourable to also being able to specify the order of dimensions in the resulting array. It simply looks as:
```julia
@tensor D[d,f,h] := A[a,c,f,a,e,b,b,g]*B[c,h,g,e,d]+0.5*C[d,h,f]
```
Here `a` etc are just interpreted as labels and not valid julia variables, though you can also use e.g. integers or chars as labels. Note that this uses the assignment operator `:=` for defining a new array `D`; this is valid syntax but unused/undefined in Julia base. Writing just `=` will store the result of this operation in a preallocated array.

There are also normal method calls to tensor operations which are more suited if you would be in a situation where indeed the specification of the contraction is a dynamic thing. However, I agree with @stevengj that I fail to see where that would be a common operation. The advantage of the macro, if you do know how the contraction pattern at compile time, is that this can also be analysed and transformed into a more efficient/machine-friendly specification of the contraction at compile time.

Since macro's are so powerful, I have even considered just using latex expressions to specify tensor operations, e.g.
```julia
@tensor D_{d,f,h} := A_{a,c,f,a,e,b,b,g}*B_{c,h,g,e,d}+0.5*C_{d,h,f}
```
though I thought that that would be one bridge too far. I hope to find some time to finish the documentation in the next one or two weeks and be able to release the new version, and then gradually add more features over time.

Ideas like multidimensional `qr` and `svd` factorisations have certainly been on the back of my mind (and were in fact implemented in my unfinished and now mostly neglected `TensorToolbox.jl` package)

@ettersi, note that there is a similar unregistered package also called Tensors.jl by @andyferris (http://github.com/andyferris/Tensors.jl).

**Comment by parpwhick** [comment]
It is really awkward for a spectator like me to see the 3rd or 4th independent attempt at a tensor library in Julia, with the outstanding differences being the syntax for the contractions. Matlab libraries like the TT-toolbox are still very much ahead in terms of functionality, while having a much uglier interface and maybe performance!

That being said, I'm not contributing to any of the projects above due to lack of time, so shame on me.

**Comment by johnmyleswhite** [comment]
I'd like to make a radical proposal to close this issue. Heretical though it may be, I think Base Julia doesn't need to be concerned with tensor contractions.

**Comment by StefanKarpinski** [comment]
Agreed. The lack of any kind of consensus here strongly indicates that this is not ready for the base language.

**Comment by Jutho** [comment]
+1. My posts were never intended as suggestions for something that should be included in Base but rather as information for people interested in tensor contractions. But I fully agree that this belongs in a package.
