### ISSUE TITLE
Markdown Links in Docstrings are broken in the REPL

### ISSUE THREAD

**Issue by jiegillet** [JuliaLang/julia#32562]
The markdown links in docstrings are not formatted well in the REPL.

Minimal working example

```julia
julia> """Foo: [link to something](https://julialang.org)""" foo() = 42

help?> foo

Foo: link to something (https://julialang.org)
```

It's not that bad since you can still click on the link, unfortunately what it links to is `https://julialang.org)` which has an extra parenthesis.

**Comment by sostock** [comment]
I cannot reproduce this (for me, the link correctly leads to `https://julialang.org` without the extra parenthesis). I think the ability to click on the link is a feature of the terminal emulator and has nothing to do with Julia.

Does the link work correctly if you just type `echo "link to something (https://julialang.org)"` into your terminal? If it does, this might actually related to the REPL. Otherwise, you might want to open an issue for whatever terminal emulator you are using.

**Comment by jiegillet** [comment]
Right, it's probably the terminal then. 
That was using Juno on Mac. I tried what you suggested and it was still the wrong link. I tried in the normal terminal and it's not clickable at all. 
I'll close the issue, thanks.
