### ISSUE TITLE
Error Handling in Tasks

### ISSUE THREAD

**Issue by rohanmclure** [JuliaLang/julia#32677]
Not sure if this is an extension of #10405 or a novel issue, but the following example provides two tasks, one of which will throw an error, the other is blocking. This makes async code difficult to debug.

```julia
c = Channel(0)
@sync begin
       @async begin
               put!(c, nothing)
       end
       @async begin
               this_is_not_defined_and_will_error()
               take!(c)
       end
end
```
Interestingly, reversing the @async blocks will cause the error to propagate properly.

I've verified this is the case in 1.1.0 and 1.3.0-alpha

**Comment by vchuravy** [comment]
This is likely due to the fact that we wait in order on the tasks, instead of peeking if one has errored.

**Comment by c42f** [comment]
go `ErrorGroup` seems about right — it wraps each function so that a failure will cancel the whole group:

https://github.com/golang/sync/blob/112230192c580c3556b8cee6403af37a4fc5f28c/errgroup/errgroup.go#L54

That seems like a better default behavior for `@sync`. Maybe we could have some syntax in `@sync` to set a cancellation policy

```julia
@sync cancellation=foo begin
    @async f1()
    @async f2()
end
```

though I'm not sure what kind of thing `foo` should be.

**Comment by StefanKarpinski** [comment]
cc @tkf who has looked into cancellation and Trio-style structured I/O a bit already.

**Comment by tkf** [comment]
It looks like the problem here is that the code in the OP is mixing two synchronization paradigms (structured concurrency (`@sync`-`@async`) and CSP (unbuffered `Channel`)) that are not aware of each other.  I think this can be solved by attaching `Channel`s (and maybe any kind of synchronization mechanisms) to the `@sync` block.  For example, a very simple minded solution would be to `close` all `Channel`s attached to a `@sync` block at the end of it.  So you would write something like

```julia
@sync begin
    c = @Channel(0)
    ...do stuff...
end
```

which is expanded to

```julia
let channels = [],
    ... and other preamble things...

    c = Channel(0)
    push!(channels, c)

    ...do stuff...

    foreach(close, channels)
    ... and other things...
end
```

(Or maybe use `task_local_storage` instead of `let`?  This way, `Channel` does not have to be a macro.)

Of course, `close` is not ideal because it makes error handling hard; you have to distinguish errors due to the automatic `close` in `@sync` with other ones.  It would be nice if there are variants of `take!`/`put!` like

```julia
maybe_take!(c::Channel{T}) :: Union{Some{T}, Cancelled}
maybe_put!(c::Channel) :: Union{Nothing, Cancelled}
```

where `close` makes `maybe_*!(c)` return a `Cancelled` immediately.  This way, I can write a helper macro (say) `@await` such that

```julia
y = @await maybe_take!(c)
```

expands to

```julia
x = maybe_take!(c)
x isa Cancelled && return x
x = something(y)
```

This way, you can create a convention that `@await`-able functions are the ones which return `Union{T, Cancelled}`.  Furthermore, the `@await`-able functions that check the cancellation tokens associated with a `@sync` block would be the cancellable functions.  This solves my concern in https://github.com/JuliaLang/julia/issues/6283#issuecomment-519365625 about making functions cancellable.

(A more sophisticated version of `@await` can be based on [`ResultTypes.jl`](https://github.com/iamed2/ResultTypes.jl).)

**Comment by tro3** [comment]
Is this issue on the drawing board for 1.6 or further in the future?  I'd be happy to help here over the holidays, if needed.

**Comment by StefanKarpinski** [comment]
The 1.6 release is branching right about now so no more features. If you want to work on this for 1.7 though, that would be great.

**Comment by tro3** [comment]
Okay, I've fixed the issue with ThreadPools, and it was not related to this after all.  But had to keep looking here...

The issue above is due to a lockup with intertwined Task/Channel Conditions.  In the code below, four tasks are generated: A (the REPL), B (unknown but unimportant), C (the first async task), and D (the second async task).  The C-level selector links the task rotation in order: A->B->C->D->A->...  The issue occurs when A is waiting on C, C is waiting on a _channel_ that is waiting on D, but D throws an exception.  The selector then moves from D to A, where we lock, presumably bouncing between A and C, waiting on a message from D that will never arrive.  To prove that it just doesn't sit on A indefinitely, I also ran a version that guarantees a closing of the channel, and the dependencies do unwind properly.  Lastly, it works when the two async tasks are reversed in order because the exception is thrown in Task (in this case) C, before Task D has had a chance to wait on the Channel.

The preferred behavior (I think) would have been to immediately propagate the unhandled exception in D upwards to A somehow.  I'll start taking a look at that unless someone feels another path makes more sense.  Not sure how to get there yet, because when D throws, nothing is actually waiting on it.  A at that time is just holding on C.donenotify.

--------------------------------

The code below is running on Julia with monkey-patched `Base.task_done_hook`, `Base._wait`, and `Base.try_yieldto`.  `safeprint` is an attempt to get a low-level stdout, as the Julia println statement generates its own async tasks.


### Functioning case:
```julia
safeprint(x::String) = ccall(:jl_safe_printf, Cvoid, (Ptr{UInt8}, Int32...), "$x\n")

c = Channel(0)
ct = current_task()
safeprint("Master task: $ct")                    # Task A
safeprint("Workqueue: $([x for x in Base.Workqueues[Threads.threadid()].queue])")
@sync begin
    @async begin                                 # Task C
        safeprint("Workqueue: $([x for x in Base.Workqueues[Threads.threadid()].queue])")
        ct = current_task()
        safeprint("        First Task: $ct")
        take!(c)
    end
    @async begin                                 # Task D
        safeprint("Workqueue: $([x for x in Base.Workqueues[Threads.threadid()].queue])")
        ct = current_task()
        safeprint("        Second Task: $ct")
        #undefined()
        put!(c, nothing)
    end
    safeprint("Workqueue: $([x for x in Base.Workqueues[Threads.threadid()].queue])")
end
```

Result, with Task locations mapped to letters:
```
Master task: Task (runnable) A
Workqueue: Task[Task (runnable) B]
Workqueue: Task[Task (runnable) B, Task (runnable) C, Task (runnable) D]
  _waiting for Task (runnable) C on Task (runnable) A
      try_yieldto from Task (runnable) A
      try_yieldto from Task (runnable) B
Workqueue: Task[Task (runnable) D]
        First Task: Task (runnable) C
      try_yieldto from Task (runnable) C
Workqueue: Task[]
        Second Task: Task (runnable) D
      try_yieldto from Task (runnable) D
      try_yieldto returned to Task (runnable) C
    prepping notify Task (done) C
    notified Task (done) C
    notify done Task (done) C
    final wait Task (done) C
      try_yieldto from Task (done) C
      try_yieldto returned to Task (runnable) D
    prepping notify Task (done) D
    notify done Task (done) D
    final wait Task (done) D
      try_yieldto from Task (done) D
      try_yieldto returned to Task (runnable) A
  _waiting done Task (done) C
  _waiting for Task (done) D on Task (runnable) A
  _waiting done Task (done) D
```

### Exception case:
```julia
c = Channel(0)
ct = current_task()
safeprint("Master task: $ct")                    # Task A
safeprint("Workqueue: $([x for x in Base.Workqueues[Threads.threadid()].queue])")
@sync begin
    @async begin                                 # Task C
        safeprint("Workqueue: $([x for x in Base.Workqueues[Threads.threadid()].queue])")
        ct = current_task()
        safeprint("        First Task: $ct")
        take!(c)
    end
    @async begin                                 # Task D
        safeprint("Workqueue: $([x for x in Base.Workqueues[Threads.threadid()].queue])")
        ct = current_task()
        safeprint("        Second Task: $ct")
        undefined()                              # Throws exception before put!
        put!(c, nothing)
    end
    safeprint("Workqueue: $([x for x in Base.Workqueues[Threads.threadid()].queue])")
end
```

Result:
```
Master task: Task (runnable) A
Workqueue: Task[Task (runnable) B]
Workqueue: Task[Task (runnable) B, Task (runnable) C, Task (runnable) D]
  _waiting for Task (runnable) C on Task (runnable) A
      try_yieldto from Task (runnable) A
      try_yieldto from Task (runnable) B
Workqueue: Task[Task (runnable) D]
        First Task: Task (runnable) C
      try_yieldto from Task (runnable) C
Workqueue: Task[]
        Second Task: Task (runnable) D
    prepping notify Task (failed) D
    notify done Task (failed) D
    final wait Task (failed) D            # Lockup occurs here - Ctrl-C in REPL to get the rest
      try_yieldto from Task (failed) D
      try_yieldto returned to Task (runnable) A
      try_yieldto error in InterruptException() Task (runnable) A
```


### Exception case:
```julia
c = Channel(0)
ct = current_task()
safeprint("Master task: $ct")                    # Task A
safeprint("Workqueue: $([x for x in Base.Workqueues[Threads.threadid()].queue])")
@sync begin
    @async begin                                 # Task C
        safeprint("Workqueue: $([x for x in Base.Workqueues[Threads.threadid()].queue])")
        ct = current_task()
        safeprint("        First Task: $ct")
        take!(c)
    end
    @async begin                                 # Task D
        safeprint("Workqueue: $([x for x in Base.Workqueues[Threads.threadid()].queue])")
        ct = current_task()
        safeprint("        Second Task: $ct")
        try
            undefined()
            put!(c, nothing)
        finally
            close(c)
        end
    end
    safeprint("Workqueue: $([x for x in Base.Workqueues[Threads.threadid()].queue])")
end
```

Result:
```
Master task: Task (runnable) A
Workqueue: Task[Task (runnable) B]
Workqueue: Task[Task (runnable) B, Task (runnable) C, Task (runnable) D]
  _waiting for Task (runnable) C on Task (runnable) A
      try_yieldto from Task (runnable) A
      try_yieldto from Task (runnable) B
Workqueue: Task[Task (runnable) D]
        First Task: Task (runnable) C
      try_yieldto from Task (runnable) C
Workqueue: Task[]
        Second Task: Task (runnable) D
    prepping notify Task (failed) D
    notify done Task (failed) D
    final wait Task (failed) D
      try_yieldto from Task (failed) D
      try_yieldto returned to Task (runnable) C
      try_yieldto error in InvalidStateException("Channel is closed.", :closed) Task (runnable) C
    prepping notify Task (failed) C
    notified Task (failed) C
    notify done Task (failed) C
    final wait Task (failed) C
      try_yieldto from Task (failed) C
      try_yieldto returned to Task (runnable) A
  _waiting done Task (failed) C
  _waiting for Task (failed) D on Task (runnable) A
  _waiting done Task (failed) D
```

**Comment by tro3** [comment]
Looking back through the history, all of the above is exactly as @tkf says - just the details of what the lockup looks like.  I agree that the best solution is a `sync_end` that cycles through Tasks (and Channels if needed, but I'll try Tasks alone first) and throws an Exception if any Tasks do.

**Comment by tro3** [comment]
Okay, I have a solution to the above that has a reasonable story, but I am leery of corner cases I don't have visibility into.  The basic idea is to take each asynchronous task and wrap it so that the main Task gets rescheduled before any exceptions are thrown.  (The core problem in the issue here is that exceptions can be thrown and Tasks killed without the managing task being notified.)  This structure guarantees that any exception will "bubble up".  In the code below, `main()` hangs with `@sync`/`@async`, but properly reports an `UndefVarError` with `@sync2`/`@async2`.

Feedback welcome.  What I don't have visibility into is what other use cases are running around for the macros.  If it is only "`@async`'s inside a single `@sync`" then this path may cover it.  But I feel like I've seen other interactions (with threads, for example), that I have not tested against.  If you all think this path has merit, I can start trying to set up for a PR, though that might be a challenge coming from PC land.

Just let me know.

--------
```julia
macro sync2(block)
    var = esc(Base.sync_varname)
    quote
        let $var = Function[]             # Uses simple array rather than channel
            v = $(esc(block))
            sync2_end($var)
            v
        end
    end
end

macro async2(expr)
    letargs = Base._lift_one_interp!(expr)

    thunk = esc(:(()->($expr)))
    var = esc(Base.sync_varname)
    quote
        let $(letargs...)
            if $(Expr(:islocal, var))
                push!($var, $thunk)       # Storing thunks, not Tasks
            end
            nothing                       # Returns nothing instead of Task. Issue?
        end
    end
end

function sync2_end(fs::Vector{Function})
    local c_ex, ts, ct, fn
    ts = Task[]
    ct = current_task()
    for f in fs                           # Wrap each thunk in a Task that checks for 
        function fn()                     # errors and reschedules the main Task before
            ex = nothing                  # rethrowing any exceptions
            try
                f()
            catch e
                ex = e
            end
            isnothing(ct.queue) && schedule(ct)
            isnothing(ex) || throw(ex)
        end
        push!(ts, Task(fn))
    end
    map(schedule, ts)                     # Launch the tasks
    while true
        wait()                            # Will return on Task schedule
        if any(istaskfailed, ts)          # Throw exception on first occurence
            c_ex = CompositeException()
            for r in ts
                istaskfailed(r) && push!(c_ex, TaskFailedException(r))
            end
            throw(c_ex)
        elseif all(istaskdone, ts)        # Exit when all tasks complete
            break
        end
    end
    nothing
end

function main()
    c = Channel(0)
    ct = current_task()
    @sync2 begin
        @async2 begin
            ct = current_task()
            safeprint("        First Task:  $ct")
            take!(c)
        end
        @async2 begin
            ct = current_task()
            safeprint("        Second Task: $ct")
            undefined()
            put!(c, nothing)
        end
    end
end
```

**Comment by tro3** [comment]
Okay, I ran against the test suite, and it did find some corner cases with the above.  So I've submitted an improved implementation at #38857 that passes the 1.5.3 test suite.  Here, the `Task` creation wraps the incoming thunks directly, and `sync_end` sticks to a Channel - emptying it of pending tasks, waiting for them all in parallel, and repeating until nothing is left.

**Comment by tro3** [comment]
@StefanKarpinski - so I have a fix for this (way simplified from the above), based on parallelizing `sync_end`.  It does not address the larger concurrency issues, though.  It just prevents the task-order-based lockup.  I've tested against the full suites in the 1.5-release and 1.6-release branches.

Would it make more sense to issue a PR into Experimental, or directly into task.jl?  Or is this considered too delicate a PR for a non-core developer (I won't take offense)?

**Comment by StefanKarpinski** [comment]
I'm not sure about that. @vtjnash or @keno would have to offer an opinion on the technical aspect.

**Comment by tro3** [comment]
So after wandering down a few different paths and getting feedback on #38916 and #38992, I came to the conclusion that the solution to this problem was (an inferior implementation of) what is already in `Experimental.sync_end`.  So I'm just going to point to that in my `startup.jl` until it moves to Base, which IMO it should do.  Happy to do the PR for this and add a lockup test suite if needed.

**Comment by vtjnash** [comment]
Seems this is now `Experimental.sync_end`, which we should move to `Future.sync_end`, and eventually `Base.sync_end`
