### ISSUE TITLE
Ctrl + backspace deletes too much

### ISSUE THREAD

**Issue by innerlee** [JuliaLang/julia#32783]
Say you entered the following line in the terminal, where `|` indicates cursor position.

```julia
julia> f(a, |
```
when you press `ctrl+backspace` trying to delete `a,`,
you fail because it deletes the whole line.

It would be great if the `ctrl+backspace` could delete to a position similar to `ctrl+leftarrow`, who position the cursor between `(` and `a`.

```julia
julia> f(|a,
```

```julia
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
```

**Comment by rfourquet** [comment]
I can't reproduce. BTW, only "Meta + Backspace" is documented, is your "Meta" key bound to "Ctrl"?

**Comment by innerlee** [comment]
I'm not sure how to check "bound". (And no experience in Mac..)

**Comment by rfourquet** [comment]
> I'm not sure how to check "bound"

I guess it's not because "Ctrl" should be different from "Meta". Then why do you expect that "Ctrl + backspace" should delete the last word? Can you try again to reproduce the problem but with starting Julia with the command "julia --startup-file=no" ? Does "Meta + Backspace" do what you want ? (I guess that on Mac, "Meta" is "Command" key or "Alt").

You can also look at the key-bindings table at https://docs.julialang.org/en/v1/stdlib/REPL/, and try "Ctrl", "Alt" or "Command" in place of "Meta" and see what works as advertised.

**Comment by innerlee** [comment]
`Alt` works as expected. Thanks!

Since `ctrl+backspace` is not documented (and supported), I will close this.

btw, the `ctrl+backspace` intuition comes from vscode.
