### ISSUE TITLE
special function sin

### ISSUE THREAD

**Issue by tvrtadx** [JuliaLang/julia#32889]
![001](https://user-images.githubusercontent.com/42902536/63015630-0cda2080-bec4-11e9-9f92-bbf3ecb0b7f0.png)
why DS1 is not equal to 1/3! ?
![002](https://user-images.githubusercontent.com/42902536/63015816-9689ee00-bec4-11e9-8bf4-896c98cb663c.png)

**Comment by yuyichao** [comment]
Please use text instead of pictures.

Do you see a problem in the results? If not, please use discourse to ask questions instead.

I believe the optimum coefficients is not the closest approximation to the Taylor coefficients since we care about the maximum (absolute/relative) deviation over a particular interval. The Taylor series gives you minimum deviation near 0 and the error goes up quickly for larger values.
