### ISSUE TITLE
CI errors on master in LinearAlgebra.mul!

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#32924]
Probably from the `mul!` PR, cc @tkf 
```
Error in testset LinearAlgebra/addmul:
Test Failed at /buildworker/worker/tester_linux32/build/share/julia/stdlib/v1.3/LinearAlgebra/test/addmul.jl:178
  Expression: ���(collect(returned_mat), collect(�� * A * B + �� * Cc), rtol=rtol)
   Evaluated: [0.6384605169296265] ��� [0.5298598366189116] (rtol=0.0003452669770922512) 
```

See e.g. https://build.julialang.org/#/builders/13/builds/4527

**Comment by tkf** [comment]
There are some bug fixes in #32901.

By the way, I realized that the test log is not very helpful since `@testset` titles are not rendered in the CI. Is there a way to get a similar output as in `Pkg.test`?

**Comment by JeffBezanson** [comment]
Hopefully fixed by #32901; can reopen if not.

**Comment by vtjnash** [comment]
Still seems to be happening (or at least, I assume related), e.g. https://build.julialang.org/#/builders/29/builds/5947/steps/2/logs/stdio

**Comment by tkf** [comment]
This is probably due to #33743. cc @dkarrasch

Just FYI, to debug this locally (without #32938), comment out this line

https://github.com/JuliaLang/julia/blob/6eebbbe2d205f8116330a77ca5e15f4a356232db/stdlib/LinearAlgebra/test/addmul.jl#L121

and run the file. IIRC, it takes some hours to finish with `--compile=min` if there is no failure.
