### ISSUE TITLE
sparse \ polyalgorithm

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#3295]
We need a polyalgorithm for sparse \.

This is the discussion from the mailing list.
https://groups.google.com/forum/?fromgroups#!topic/julia-users/FagaqWVkBGU

We may need enhancements to the dense \ as well.

Cc: @dmbates, @andreasnoackjensen

**Comment by jiahao** [comment]
A quick skim of the cited paper turns up Section 3.2 (digital page 15), which can be translated into code of this form:

```jl
function factorize{T}(A::SparseAbstractArray{T,2})
    n, m = size(A)
    if n != m #A is rectangular
    	#Compute QR factorization of A
        #TODO return qrfact of A or A', whichever is tall and thin.
    	return qrfact(A) #( n>m ? A, A') 
    end

    #At this point A is square
	if issym(A) #A is symmetric
		if all(diag(A).!= 0) && all(imag(diag(A)).== 0)
			#A has all-real nonzero diagonal
			try
				return cholfact(A)
			catch e
				isa(e, PosDefError) || raise(e)
			end
		end

		# cholfact failed or condition on the diagonal does 
		# not hold; do LDLt

		try
			return ldltfact(A)
		#catch some specific failure?
		end
	end

	#Above conditions do not hold or chol and ldl failed
	return lufact(A)
end
```

The specific implementations of `qrfact`, `cholfact`, `ldltfact` and `lufact` required are summarized in Table III, digital page 12:

![screen shot 2015-01-05 at 3 50 26 pm](https://cloud.githubusercontent.com/assets/1732/5619728/b818c56a-94f2-11e4-9290-2507fe170c3b.png)

**Comment by andreasnoack** [comment]
It is a good idea to follow Tim Davis' for the `factorize(Sparse)` methods, but I'm not sure it is a good idea to use `factorize` for `Sparse\VecOrMat`. We are not using it for `Dense\VecOrMat` for two reasons

1. The complete check is too expensive when the right hand side is only used once
2. `factorize` is not type stable (for concrete types)

Actually, I'm not sure why `factorize` is used in `Sparse\VecOrMat` right now. Going through the git history, I can see that I introduced the inferior `factorize(Sparse)` method to make our ARPACK wrapper able to efficiently factorize pd matrices. It used to `lufact` all matrices. However, `Sparse\VecOrMat` must have had a kind of polyalgorithm before I added `factorize(Sparse)` and I didn't touch any `\`s at that commit.

**Comment by jiahao** [comment]
Here is our current status:

- `lufact(::Sparse)` is defined and the computation uses UMFPACK, but the documentation of the factors `F[:L]*F[:U] == F[:Rs] .* A[F[:p], F[:q]]` is no longer correct since `.*` is now broken (Ref #9664; it was  correct as of v0.2),
- `cholfact(::Sparse)` computes either the LL' or LDL' form of Cholesky as determined by Cholmod, but `F = cholfact(A); F[:L]` does not work,
- `ldltfact(::Sparse)` is not defined. The _diagonal_ LDL' is sometimes returned by Cholmod. As @tkelman wrote [on julia-users](https://groups.google.com/d/msg/julia-users/FagaqWVkBGU/WJwnKMAQs98J), we do not have the Bunch-Kaufman form (where D is block-diagonal) that is useful for symmetric indefinite matrices.
- `qrfact(::Sparse)` is not defined.

**Comment by ViralBShah** [comment]
`qrfact` still remains, but could be a separate issue.

**Comment by andreasnoack** [comment]
I'm on that. Actually, I've already wrapped SPQR, but I have to write tests.

**Comment by ViralBShah** [comment]
Wow, you are amazing!
