### ISSUE TITLE
Julia 1.3 runs my script at least 10x slower than Julia 1.1 does on my computer

### ISSUE THREAD

**Issue by jdjohnston** [JuliaLang/julia#33014]
Please see the fuller [discourse post](https://discourse.julialang.org/t/julia-v1-3-runs-this-script-at-least-10x-slower-than-julia-v1-1-on-my-computer/27815?u=jdjohnston).

Summary: On my computer, Julia 1.3 (from about DEV.308 through current) runs the posted script at least 10x slower than Julia 1.1.1 and even Julia 1.3-DEV through about DEV.164.

My best guess is that, in mid-May, there was a deliberate design decision to be less aggressive in the use of garbage collection. I can see how that would be useful on systems with *much* RAM, but on my laptop (1879MiB, per lshw) it's not helpful. Probably true for others with limited RAM, including embedded systems. If my guess is correct, would it be reasonable to have a command-line option so the user can tune gc aggressiveness, somewhat like the existing `--optimize` option?

I've attached the script in question as a text file:
[peuler92.jl.txt](https://github.com/JuliaLang/julia/files/3527462/peuler92.jl.txt)

**Comment by StefanKarpinski** [comment]
I can reproduce this and it's also slow on release-1.2. If was fast on ce17e0529e which is 787 commits before release-1.2 so it happened somewhere in there if someone wants to bisect.

**Comment by jdjohnston** [comment]
@StefanKarpinski, thanks for looking at this. For _me_ the performance of Julia 1.2.0 is comparable to 1.3-DEV.164, i.e. as fast as 1.1.1 and maybe a little faster.

**Comment by goggle** [comment]
@c42f pointed out, that https://github.com/julialang/julia/pull/31722 might have caused this issue.

**Comment by c42f** [comment]
To repeat a probable MWE from the discourse post:

```julia
sumsqdig(n::Int) = sum(i*i for i in digits(n))
```

```julia
julia> VERSION
v"1.3.0-alpha.156"

julia> @btime sumsqdig(5000_000)
  661.931 ns (4 allocations: 192 bytes)
```

```julia
julia> VERSION
v"1.1.0"

julia> @btime sumsqdig(5000_000)
  91.624 ns (3 allocations: 176 bytes)
```


If this is due to the code in `digits` becoming very slightly more complex (#31722) and interacting badly with inlining, that's neither a regression in the compiler nor the API, just an unfortunate interaction. So it might be tricky to fix with a small tweak.

A good fix would remove the allocation from `digits` by making it return some immutable `AbstractVector` of digits (perhaps using one of the ideas from https://github.com/JuliaLang/julia/pull/31722#issuecomment-523789842). That's technically a breaking change though so I'm not sure how best to proceed.

**Comment by jdjohnston** [comment]
Somewhere between Julia 1.3.1 & Julia 1.4.1 there's been a dramatic improvement in performance for this problem (on my  laptop, at least). And, yes, it continues on through Julia 1.5.1 :). For myself, I would consider this particular issue closed.
