### ISSUE TITLE
gc-debug: scrub segfaults

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#33045]
on 1.2.0:

```
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.2.0 (2019-08-20)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |


Thread 1 "julia" received signal SIGSEGV, Segmentation fault.
0x00007ffff789795f in gc_scrub_range (low=0x7fffd71bd000 "", high=0x7fffd75bd000 "") at /home/tim/Julia/julia-1.2/src/gc-debug.c:553
553             char *p = *stack_p;
(gdb) p stack_p
$4 = (char **) 0x7fffd71c4ff8
(gdb) p *stack_p
$5 = 0x0
```

**Comment by yuyichao** [comment]
Hmmm that seems totally fine, why is that crashing? Is that a unreadable pointer? (Clearly the debugger has no problem running that line.)

**Comment by maleadt** [comment]
Yeah it's strange, but I'm debugging another issue so didn't have to look into it right now (I figured that a NULL there could still be the source of a segfault, and gdb just didn't pinpoint the line correctly). I have been using the GC debug mode for all my debug sessions for a while now and don't remember seeing this in the scrub functionality, but I'll have a closer look.

**Comment by yuyichao** [comment]
The value of `p` here is completely arbitrary. The user of this value is responsible to check if it is in the known range. A value of `NULL` is the simplest case here....

If you see it again, the useful information to collect would be,

* Is that pointer unreadable? (if you have doubt on the line number, check the asm to see which address it's trying to read)
* What's the caller
* From the previous one, which/what kind of stack it is scanning
* Did we land in the protection page? (the lower bound on the input suggests that we are pretty far still....)
* If it is, are we getting the wrong bound and could we fix it?
* If we can't fix it or if it's due to some other unpreventable issues, it shouldn't be a problem and you can just continue since we should be catching the segfault anyway.

In general, the load here isn't expected to work all the time and the safe_restore should make this not an issue. If you only see this in the debugger then it's a non-issue. If you see this without running the debugger (i.e. the segfault didn't get caught) then it's a real issue.

**Comment by maleadt** [comment]
Sorry, seems like I was a little eager filing a bug. Thanks for explaining, I didn't realize we also used safe_restore for the GC debug functionality. I only saw this in the debugger so this is probably completely benign.
