### ISSUE TITLE
reshape and push! inconsistent behavior

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#33143]
Consider the following example:

```julia
xmat = randn(5,5)
xvec = reshape(xmat, 25)
push!(xvec, 3)
xvec[1] = 0.0
xmat[1] # not zero
```

Here `push!` has decoupled `xmat` and `xvec`, though one would expect that a reshaped array always point to the same memory as the original array. I think the `push!` here should raise an error.

Contrast the example above with the following (source: https://discourse.julialang.org/t/puzzling-reshape-and-push/28326/2):

```julia
xvec = rand(4)
xmat = reshape(xvec, 2, 2)
push!(xvec, 1.0)  # ERROR: cannot resize array with shared data
```

To be consistent it seems to me that my first example above should also be an error.

**Comment by yuyichao** [comment]
This is an intentional hehavior. Changing this would be a breaking change.

Even though the implementation is different, just like subarray and reinterpreted arrays, you can't expect the original array and the new array to be completely symmetric so "consistency" isn't really an argument here. The real question then is which one is a better behavior.

In fact, both can be implemented from the other (the push does a copy implicitly) so the two behavior are basically equivalent. Having a more explicit error could be a good thing since aliasing issue are a bit hard to debug so a change in 2.0 would probably be fine.

**Comment by KristofferC** [comment]
> This is an intentional behavior.

According to what? This really feels like implementation detail leaking out and should be fair game to change. E.g. `push!` doesn't document that is unshares data when the buffer is owned by another array.

**Comment by yuyichao** [comment]
> According to what?

According to this being explicitly implemented in the code. It's not a property of a naive implementation that didn't take this into account and it's definitely not a leak of implementation detail.

> should be fair game to change.

No. This behavior is something someone can depend on. Failure to mention in the doc is just an argument to fix the doc. Raising an error in a case that previous doesn't is not going to be a minor change for sure.

**Comment by yuyichao** [comment]
Also, similar to many other aliasing issues, there are difference between users that care and users that doesn't. A user that just want to create an interpreted array before using it as a normal one is not going to care if the alias breaks or not and should be allowed to resize the new array. If the error is raised on the new array for resizing, there should be a way to support resizing a possibly shared array without making unnecessary copy when the array isn't shared.

**Comment by StefanKarpinski** [comment]
We can and do make technically breaking changes in minor releases so long as they are 1) undocumented, 2) unlikely to be relied upon on real code, 3) not actually relied upon in any packages according to PkgEval. This seems likely to qualify on all three counts.

**Comment by yuyichao** [comment]
> Especially since any code that relies on this is either broken already

Why? Not everyone cares about the old array after the new array is created.

> or will break with a fairly clear error message.

But doesn't necessarily have an easy fix. See my comment above.

**Comment by yuyichao** [comment]
And FWIW, this is tested.

**Comment by StefanKarpinski** [comment]
If you want to join the triage call and discuss it, it’s on Thursday at 2:15 pm Eastern. It’s hard to come up with a legitimate use case for this “feature”.

**Comment by yuyichao** [comment]
Discussion on github is way better logged.

It's hard to come up with any use case for many features. FWIW, it's hard for me to come up with a case that I want to resize to a vector either (edit: actually just remembered one from what I'm doding now, see below). However, this is all about combining usage of independent code. As long as you have a usecase that require you to create a vector, there should be cases you want to feed that vector to code that will resize that vector.

Things that are closely related to what I'm doing atm will be loading experiemental data from an external file. The loader of the file may return a matrix (since that's how the matlab code that produces it saves it in the MAT file) and it's possible that I want to use it as a vector. (and I do have reshaping code to do this sort of things). I also do mutate/combine/append these data before processing them together so even though I'm not 100% sure if I'm relying on this now, I can easily see a case where I am. In this case I obvously also want to decouple the loading code from the processing code since there are many different ways to load and process data.

Note that the property in this case that makes this a legitimate usecase is that I don't care about the old data. I need the new data to be in the format that I can process, the old data is essentially garbage once the new one is there.

**Comment by yuyichao** [comment]
Oh, and another case that I've done before. When creating a vector that is a flattened out matrix, I would create the matrix and then reshape so that I can push to the vector later. I'm 99% sure this comes from a case where I'm doing something related to density matrix (and treating the density matrix as vector to do operation on it) while also need to append a few extra dimentions to take care of other part of the system.

Again, I'm not saying such thing couldn't be don't with the new behavior. However,

1. It's wrong to say that such usecase must not exist since one can't come up with one.
2. It's particularly bad in this case since the fix could be no where near the error. The error will be raised when one try to push to the vector but the correct fix would be copying the initial array rather than doing anything with the `push!`.

The current behavior is also essentially a COW (of array metadata) so erroring in all cases will cause unecessary copies unless a new function is added to do the COW explicitly. Even then, in order to support any input, generic code will be required to always call that function before resizing an array which is even worse than doing that automatically as what we do now.

**Comment by StefanKarpinski** [comment]
Triage discussion with @vtjnash favors what @JeffBezanson said.

**Comment by StefanKarpinski** [comment]
Someone ought to fix this issue if they're interested. Triage has already decided.

**Comment by expnn** [comment]
Sometimes it is weired to raise an exception when pushing an array. It prevents the users from pushing new elements into an array after calling a function that performs some shared data operations, like `reshape`. 
The following snippet is an example. It show that the array `v` is marked shared after calling a function, even though the sharing data array (i.e., the local `x` in `func`) can be safely  garbage collected after the calling of `func`. 
It seems there is no way to unmark an array that it is not shared any more. After explicitly calling the gc(), the `push!` is still forbided.

```julia 
function func(a)
    x = reshape(a, 2, 2)
    z = x * x
    return z
 end

v = rand(4)
y = func(v)
push!(v, 1.0)  # ERROR: cannot resize array with shared data

GC.gc()
push!(v, 1.0)  # ERROR: cannot resize array with shared data
```

**Comment by bkamins** [comment]
Are there any plans to fix the issue raised by @expnn. If not I would recommend to add an appropriate comment in `reshape` docstrings as this pitfall is really hard to debug and users stumble upon it.

CC @pdimens

**Comment by robsmith11** [comment]
I ran into a similar issue:
https://discourse.julialang.org/t/how-to-unshare-an-array/66441

Is there a workaround or proposed solution to this issue?   I see a pull request was closed about unsharing on push, but don't see any further proposals.

**Comment by bkamins** [comment]
I recommend DataFrames.jl users (as this happens from time to time) to always `copy` what they pass to `reshape` unless they really know what they are doing.

The problem is, unfortunately, that if you write:
```
x = some_vector
y = reshape(x, ...)
```
then most likely `x` is a long term storage, while `y` is a short term storage and even GCing `y` does not allow to resize `x` (which in DataFrames.jl is one of the fundamental usage patterns)

As most DataFrames.jl users are just regular data scientists (and not super advanced computer scientists) I therefore recommend them to do the following as a standard pattern:
```
x = some_vector
y = reshape(copy(x), ...)
```
although it is suboptimal.

**Comment by ChrisRackauckas** [comment]
A pretty nasty case that runs into this is if you use the 3 argument `ldiv!`. The reason is because:

```julia
function ldiv!(Y::AbstractVecOrMat, A::Factorization, B::AbstractVecOrMat)
    require_one_based_indexing(Y, B)
    m, n = size(A, 1), size(A, 2)
    if m > n
        Bc = copy(B)
        ldiv!(A, Bc)
        return copyto!(Y, view(Bc, 1:n, :))
    else
        return ldiv!(A, copyto!(Y, view(B, 1:m, :)))
    end
end
```

that definition has a view, so if you ever use the vector in a 3 argument `ldiv!` you cannot reshape it afterwards and you will get this error. The workaround is just to `copyto!` manually and call the 2 argument `ldiv!` to avoid the view construction. This of course won't help lead to a solution of this issue, but hopefully if someone runs into this it'll help them figure out what's going on quicker than it took me 😅

**Comment by simonbyrne** [comment]
@ChrisRackauckas I don't quite understand the problem: can you give a short minimal example?

**Comment by ChrisRackauckas** [comment]
```julia
using LinearAlgebra
u = rand(2)
A = rand(2,2)
b = rand(2)

push!(b,3.0) # works
u = rand(3)
A = rand(3,3)
ldiv!(u,lu(A),b)

push!(b,4.0) # Error: cannot resize array with shared data
```

**Comment by simonbyrne** [comment]
This probably deserves it's own issue, as it could be addressed separately.

**Comment by mbauman** [comment]
No, the core challenge remains — that resizing vectors may (or may not) silently decouple intentional (reshaped) aliasing against other arrays.  The error prior to v1.11 was trying to just avoid one specific case of that, but it missed many others.

In other contexts (e.g., [views](https://docs.julialang.org/en/v1/base/arrays/#Base.view)) we explicitly call out resizes as being problematic and unsupported.

**Comment by mbauman** [comment]
Did this get documented in the process? Should it be?

This differs from the generic `ReshapedArray` equivalent, for which it needs to be explicitly prohibited akin to views.
