### ISSUE TITLE
move `first`, `last` to Iterators.jl?

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaLang/julia#33156]
Just from a code organization perspective - no outwardly visible changes - since they work for any collection but currently live in the abstractarray.jl file

Mentioned at https://github.com/JuliaLang/julia/pull/33129#issuecomment-527847809

**Comment by stevengj** [comment]
There are lots of things which work for any collection which are exported in Base, e.g. `collect`, `sum`, `isempty`, … I think the `Iterators` module is not "all things related to iterators" but rather specifically functions that take an iterator and transform it to another iterator.  `first` and `last` don't fall in that category and are pretty generally useful, so I would leave them as-is.

(Anyway, we couldn't move them to Iterators until Julia 2.0 due to backwards compatibility.)

**Comment by nickrobinson251** [comment]
Thanks - in which case I think I'll move the `only` function (in the linked PR)  :)
