### ISSUE TITLE
Curried versions of endswith and startswith

### ISSUE THREAD

**Issue by crstnbr** [JuliaLang/julia#33193]
In the spirit of https://github.com/JuliaLang/julia/pull/30915 I was wondering whether a PR for adding single-argument versions of `endswith`, `startswith`, and `occursin` that can be used as follows in functions like `filter` would be appreciated.

`filter(endswith(".jl"), readdir())`

I feel that I have definitely typed `x->endswith(x, ".jl")` far too often :)

**Comment by KristofferC** [comment]
Having a long list of functions where the first argument is considered special seems bad to me. Instead, just like with vectorized function we should IMO focus on syntax that tries to handle all of this in one fell swoop (https://github.com/JuliaLang/julia/pull/24990). Anything else will just be a neverending debate of what functions should implement this special handling and since Base code is not special, this will also seep out to the package system. We should learn from the `f(::Missing) = missing` story that is currently experiencing the same thing.

**Comment by StefanKarpinski** [comment]
The criteria we agreed to when starting with that currying was:

1. Two-argument function where the subject is the first argument: `verb(subject, object)`.
2. Currying on the second argument, so `verb(object) = subject -> verb(subject, object)`.
3. Linguistically, `verb(object)` reads naturally as a predicate.

These criteria are clearly met by `endswith` and `startswith`:

* `endswith(".jl")` is a predicate for strings that end with `.jl`
* `startswith("/")` is a predicate for strings for start with `/`.

For `occursin` it's more borderline since by these rules, `occursin(object)` is a predicate that applies to patterns (`subject`) to test whether they occur within a fixed collection or string (`object`). That's probably not what you had in mind. If we had the `ismatch(string, pattern)` predicate of yore, then `ismatch(pattern)` would do what you want.

**Comment by o314** [comment]
#24990 is very high-level and new feature oriented. Not quite done yet.

One could simply generate a lot of those binding (currently defined in https://github.com/JuliaLang/julia/blob/v1.2.0/base/operators.jl with a `for` loop doing `@eval` over a preset array of function names. Rather simple.

There will be however some corner cases with builtins functions such as

```julia
@test_throws ErrorException Base.:(===)(t) = Base.Fix2(:(===),t)
@test_throws ErrorException Base.:(!==)(t) = Base.Fix2(:(===),t)
@test_throws ErrorException Base.isa(t) = Base.Fix2(isa,t)
@test_throws ErrorException Base.:(<:)(t) = Base.Fix2(:(<:),t)
```

**Comment by oxinabox** [comment]
If we did https://github.com/JuliaLang/julia/issues/35031
And add `contains` as a Arg order flipped version of `occursin` 
Then `contains` would have same pattern as needed.

**Comment by KristofferC** [comment]
I retract my comment at https://github.com/JuliaLang/julia/issues/33193#issuecomment-529205329, these specific set of functions do seem to fit the pattern where this would make sense.

**Comment by StefanKarpinski** [comment]
This seems decided: `startswith` & `endswith` are ok, `occursin` is not ok. Just needs a PR.

**Comment by crstnbr** [comment]
> Just needs a PR.

Will create one.

**Comment by ptoche** [comment]
I know this issue is closed and I don't mean to reopen it, but just a quick comment:

Works:

    filter(f -> endswith(f, ".jl") && startswith(f, "test_"), readdir())

Doesn't:

    filter(endswith(".jl") && startswith("test_"), readdir())
    ERROR: LoadError: TypeError: non-boolean (Base.Fix2{typeof(endswith), String}) used in boolean context

Is it because it violates the criteria for currying in this case?

**Comment by crstnbr** [comment]
It doesn't work because you're trying to logically connect (`&&`) two objects of type `Base.Fix2`, which isn't defined.

**Comment by ptoche** [comment]
I see. Thanks! Is there another operator, like a pipe, to connect two objects of type ``Base.Fix2``?
