### ISSUE TITLE
Sum of sparse and diagonal matrix should be sparse

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#33276]
I notice that the sum of a sparse and a diagonal matrix give a dense matrix:
```Julia
julia> using LinearAlgebra
julia> using SparseArrays
julia> sparse([1], [1], [1.0]) + diagm([1])
1×1 Array{Float64,2}:
 2.0
```
It would make sense if this was a sparse matrix again.

**Comment by dkarrasch** [comment]
`diagm` creates a dense matrix with entries on the diagonal (actually, on any diagonal as specified by the arguments), see the docstring of `diagm`. That's why the result is dense. In the docstring, it is also recommended to use `Diagonal` and friends to generate storage-efficient versions. In your example, I think you get what you expected when calling
```julia
sparse([1], [1], [1.0]) + Diagonal(diagm([1]))
```
If you don't need/have data on shifted diagonals, it is much more efficient to use the `Diagonal` constructor right away, as in `Diagonal(rand(10))`.
