### ISSUE TITLE
watch_folder timeout failure on Windows

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#33311]
See https://build.julialang.org/#/builders/65/builds/4473 (from #33291):
```
Error in testset FileWatching:
Test Failed at C:\cygwin\home\Administrator\buildbot\worker-tabularasa\tester_win32\build\share\julia\stdlib\v1.4\FileWatching\test\runtests.jl:388
  Expression: #= C:\cygwin\home\Administrator\buildbot\worker-tabularasa\tester_win32\build\share\julia\stdlib\v1.4\FileWatching\test\runtests.jl:388 =# @elapsed(c = watch_folder(dir, timeout)) < 0.5
   Evaluated: 0.86873192 < 0.5
```
from [this test](https://github.com/JuliaLang/julia/blob/da86a22bb315bc73ed03c8da83e4fe6634dcc805/stdlib/FileWatching/test/runtests.jl#L388).

This hard-coded timeout was already increased once by @staticfloat in #27707, maybe it has to be increased again?  Or is there a deeper problem?

**Comment by JeffBezanson** [comment]
I've seen the value get as high as 10 seconds. Maybe all we can do for now is bump it up a little more.

**Comment by staticfloat** [comment]
The real problem is the absolutely ABYSMAL disk performance we get on windows on openstack.  To give an idea, the Pkg tests running on this machine takes over 12 hours, instead of the 10 minutes that it takes on my laptop.  It's a real problem, and the only reason our CI infrastructure works at all on that platform is because the entire build tree can fit into the filesystem cache.
