### ISSUE TITLE
Performance regression in skipchars

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#33335]
`skipchars` took a 5x preformance hit (for the benchmark we have in BaseBenchmarks) presumably after the introduction of locks on the `write` calls.

Perhaps we can lock outside of the loop and write without a lock and finally unlock it when we are done?

**Comment by StefanKarpinski** [comment]
cc @vtjnash

**Comment by vtjnash** [comment]
Duplicate of https://github.com/JuliaLang/julia/issues/34195 / addressed in https://github.com/JuliaLang/julia/pull/35426. We might be able to do some more automatic compiler optimization of this in the future, instead of the optimization provided there, though it breaks some forward-progress guarantees required by that code pattern in general, so remains to be investigated.
