### ISSUE TITLE
Julia crashes when I define large matrices

### ISSUE THREAD

**Issue by KA1988** [JuliaLang/julia#33543]
Hello, when I define a large matrix, I get a pop up window "Editor not responding" and my Julia crashes. I use juliapro. For example:

test1= zeros(70,30,5,5,2,5,10,4,2) or 
test1= zeros(70,30,5,5,2,5,10,12,2) 

I need to define matrices at this size, can someone help please ?
---------------- Thanks in advance

Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 2
  JULIA_PKG_SERVER = https://pkg.juliacomputing.com/
  JULIA_PKG_TOKEN_PATH = /Users/--/.juliapro/token.toml

**Comment by Keno** [comment]
Hi @KA1988, The size of that array is roughly 8GB. Given that you have a mobile CPU, I would guess you're using a MacBook, so that matrix would generally fill at least half the memory. You should consider whether you actually need a dense matrix of that size. If not, you may want to look into using a sparse representation. If so, I'd recommend a machine with more memory. Your favorite cloud provider will happily rent you a machine with several hundred GB. Also FWIW, I verified that the command works fine on a machine with sufficient memory. Closing as this does not seem to be a Julia bug. The https://discourse.julialang.org/ forum may be helpful for further usage questions.
