### ISSUE TITLE
end keyword in creating CartesianIndex 

### ISSUE THREAD

**Issue by aminya** [JuliaLang/julia#33608]
It is not possible to create a `CartesianIndex` object using `end` keyword.

This following code does not work in Julia:
```julia
CartesianIndex(end,1)
```

In Python, this is possible using `-1` indexing:
```python
import numpy
arr= numpy.array([[4, 2, 3], [2, 5, 4]])
ind=(-1,1)    # similar to CartesianIndex
arr[ind]
```

This is useful for creating algorithms that are independent of the array, such as for https://github.com/JuliaLang/julia/issues/16273

**Comment by yuyichao** [comment]
It is not expected to and cannot work.

If you want to compare to python, then the `-1` index does not support arbitrary arithmetics, e.g. `a[end ÷ 2]`.

**Comment by aminya** [comment]
@yuyichao It may be possible to make it work. In the current situation, the `end` keyword only exists in the context of a defined array. While some algorithms just use indices.

**Comment by Keno** [comment]
You can definitely create a type that behaves like this, it just doesn't have the same semantics as `end` which is defined to looks for the innermost enclosing array (so it does do what you want if you construct the Cartesian index inside the array access). Closing, since this conflicts with `end`s semantics, but I would encourage you to try writing the type that behaves like this yourself. It shouldn't be more than 15 lines of code. If you need help, Fe free to open a thread on discourse.
