### ISSUE TITLE
sort! does not work for subarray obtained with view when UInt indexed

### ISSUE THREAD

**Issue by pedrozudo** [JuliaLang/julia#33611]
When obtaining a subarray with `view` and using, for example, a UInt64 number, the `sort!` function does not work any more, even though the `sort` function still works.  I tracked down the reason for this to Julia changing the type of the axes from Int64 to UInt64. This does not happen when indexing the array with a UInt64.

2 Questions:
1) Is this behavior intended?
2) Is it a bug that the `sort!` function does not work any more but the `sort` function does? 

Below a code snippet that reproduces the the claim above. The last line is commented out as it throws an error. In the last two prints the UInt64 type will pop up.

```julia
a = [1,2,3,5,6]
Uindex = convert(UInt64, 5)
aUindex = a[1:Uindex]


v_a = view(a,1:5)
v_aUindex = view(aUindex, 1:5)
vUindex_a = view(a,1:Uindex)
vUindex_aUindex = view(aUindex, 1:Uindex)

@printf("%-15s %s\n","a",string(typeof(Base.axes(a,1))))
@printf("%-15s %s\n","aUindex",string(typeof(Base.axes(aUindex,1))))
println("")
@printf("%-15s %s\n","v_a",string(typeof(Base.axes(v_a,1))))
@printf("%-15s %s\n","v_aUindex",string(typeof(Base.axes(v_aUindex,1))))
println("")
@printf("%-15s %s\n","vUindex_a",string(typeof(Base.axes(vUindex_a,1))))
@printf("%-15s %s\n","vUindex_aUindex",string(typeof(Base.axes(vUindex_aUindex,1))))


sort(a)
sort!(v_a)
sort(vUindex_a)
# sort!(vUindex_a)
```

Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)

**Comment by mbauman** [comment]
Yes, this behavior is expected; the axes of the result from an indexing expression come from the axes of the indices used.  And the axes of `UInt(1):UInt(5)` are in unsigned integers so they can always represent the axes — even for absurdly large ranges.  This is most important for things like OffsetArrays, but it means that views just pass those axes along.  When you do normal allocating indexing, the result is a plain-old `Array` (which has `Int` axes) simply because we don't have a builtin storage array with support for custom axes.  

The internals of `sort!` assume that axes are always `Int`s.  It just happens that `sort` does not make this assumption.

In general I'd highly recommend using unsigned integers sparingly — and just using `Int`s for your indices.  We'll keep squashing these bugs but assumptions like this are not terribly uncommon.
