### ISSUE TITLE
`eof(stdin)` causes stdout to not flush properly

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#33628]
When writing an input loop, it's often desirable to check to see if the user is frustrated and tries to `^D` out of there.  In attempting to do so, I have found that `stdout` no longer flushes properly.  Whimsical Example:

```julia
ins = stdin
outs = stdout
username = nothing
while username === nothing #&& !eof(ins)
    msg = """
    Welcome to EvilCorp.  Remember, Big Brother is always watching.
    Please enter your username:
    """
    print(outs, msg, "\n> ")
    flush(outs)

    new_username = strip(readline(ins))
    println(outs)

    if new_username != "GaryHost"
        printstyled(outs, "Invalid Username!\n"; color=:red, bold=true)
        continue
    else
        global username = new_username
    end
end

if username === nothing
    printstyled(outs, "Goodbye."; bold=true)
else
    printstyled(outs, "Access Granted. :)\n"; color=:green)
end
```

With the `eof(ins)` commented, this works as expected (except that typing `^D` causes the `while` loop to spin infinitely).  Adding the `eof()`, however, causes the `flush(outs)` to do nothing, so the initial welcome message is not displayed.

**Comment by ben-schulz** [comment]
apologies if i've missed some context, but: is this really an improper behavior? if i understood it correctly as an exercise of `eof()` and `stdout`, then the code snippet above can be boiled down to:

```julia
ins = stdin
outs = stdout

msg = """
this should print
for each pass
where there is input
not end-of-file.
"""

while !eof(ins)

  print(outs, msg)
  flush(outs)

  readline(ins)
end
```

as far as i can tell, this code executes exactly as expected: the message is printed for every line of input. if the input stream immediately ends (i.e. `eof(ins)` evaluates `true` on the first pass), then it prints zero times, because `print` never executes.

suppose, in the original snippet, that we do uncomment `!eof(ins)` in the loop condition. if the first entry on `stdin` is `^D`, then the loop condition should evaluate `false`, which means that none of the `print` statements in the loop should ever execute. under these conditions, the expected behavior would be to omit the welcome message.

if, on the other hand, the first entry on `stdin` is not `^D`, the message displays as expected. (at least, it did for me.)

am i missing something in the original code? or is there a different example that exhibits the problem behavior?

**Comment by staticfloat** [comment]
Coming back to this; my understanding of the timing of things was off; the issue is that `eof(stdin)` is line-buffered; it waits until a line has been entered before returning, whereas I expected it to simply check that there was not a `^D` ready to be read next.  Because `eof()` is line-buffered, it blocked and caused the initial welcome message to not be printed until _after_ a line had been entered.

I have found that using `isopen(ins)` gives the desired result, as opposed to `!eof(ins)`.
