### ISSUE TITLE
`Base.unsafe_convert`, but with a second meaning

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#33763]
In the context of https://github.com/oxfordcontrol/OSQP.jl/blob/45a436fa128f4421719dd297b693c7bafeeb1fab/src/types.jl#L11-L55, `cs = Ccsc(ManagedCcsc(s))` is code for converting a julia `SparseMatrixCSC` into some `Ccsc`, made from pointers.

I wanted to define an `unsafe_convert(SparseMatrixCSC, cs)` to "undo" this conversion. It would carry the `unsafe` designation since it must do `unsafe_load`s of pointers.

However the function `unsafe_convert` has a different meaning already, and it's `unsafe` because it produces objects with pointers to memory managed by the Julia GC, without maintaining a reference to that memory, so the user needs to be careful the GC doesn't free the memory too early.

Is there a separate function, in `Base`, that has the first meaning?

**Comment by yuyichao** [comment]
Unsafe wrap?

**Comment by goretkin** [comment]
Sorry, I meant to also mention, this would make a copy of the data (though I'm not sure what the `*convert` functions promise), so it would not be an `unsafe_wrap`. The returned object would be "safe" to use once the function exits.

both `Base.unsafe_wrap` and `Base.unsafe_convert` produce an "unsafe" object. My "unsafe_convert" is more in the spirit of `unsafe_load`.

**Comment by yuyichao** [comment]
If it has similar properties as unsafe load and the type isn't a pointer then overloading that function is fine. In fact, among all the functions you mentioned anything is fine except `unsafe_convert`.

I don't really think there's anything for base to do here. The base is not going to provide a function for every single thing someone might want to do, safe or not.... If you are just asking a question, this should go to discourse instead.

Also, for this specific case, you should generally not expose unsafe types as API unless your users have to do c interop themselves and for some reasons a safe type can't be used for that. For internal types you can just pick whatever name you want for the internal functions. In the few cases where you really need an unsafe API, it's also not going to be some generic API and just pick whatever name you want is also fine (you don't need to pick a base function so that your user could write generic code that works on different types)

**Comment by goretkin** [comment]
All I'm hoping for is a generic name for an analog of  `T(x)` and/or `convert(T, x)`, but where the construction/conversion does "unsafe" things. My first guess at a name was `unsafe_convert`, but that has a different meaning (converts _to_ an unsafe thing, not _from_ an unsafe thing).

Your suggestion to have a type-specific name for this function is reasonable, but where it's possible to use multiple dispatch, instead of encoding types in the names of function, I would prefer to use multiple dispatch.

I thought there would be a lot of examples of that in Base, but the only one I found is `unsafe_string`. If instead of `unsafe_string(x)`, it were spelled `unsafe_convert2(String, x)`, then I would use `unsafe_convert2(SparseMatrixCSC, x)` in my code.

**Comment by JeffBezanson** [comment]
Just speculating, it seems to me this operation is possibly just not very generic. While many things can be funneled into a C pointer, for the inverse operation it seems you need to know what you're constructing. Hence the type-specific names like `unsafe_string`. Can anybody think of a case where a caller of this would naturally be polymorphic?

**Comment by goretkin** [comment]
> it seems you need to know what you're constructing.

Yeah, I think that's true. I'm just saying that you can pass in `String` instead of calling the function `foo_string`.

I haven't encountered a situation where the caller needs to be polymorphic, which would certainly motivate this generic function. But it's my sense that a generic function can also be motivated by orthogonality (in the sense of an [orthogonal instruction set](https://en.wikipedia.org/wiki/Orthogonal_instruction_set). Said another way, encoding a type in a function name seems like a missed opportunity to use dispatch.

So instead of having `unsafe_string(x)` and `unsafe_sparsematrixcsc(x)` (code below), you would have `unsafe_bar(String, x)` and `unsafe_bar(SparseMatrixCSC, x)`. 

This snippet is related to the example in my original message, for context.
```julia
function unsafe_sparsematrixcsc(c::OSQP.Ccsc)
  m = c.m
  n = c.n
  nzmax = c.nzmax
  nzval = [unsafe_load(c.x, i) for i=1:nzmax]
  rowval = [unsafe_load(c.i, i) for i=1:nzmax] .+ 1
  colptr = [unsafe_load(c.p, i) for i=1:(n+1)] .+ 1
  SparseMatrixCSC(m, n, colptr, rowval, nzval)
end
```

**Comment by vtjnash** [comment]
Seems to be a feature though, and doesn't seem to have anything exactly actionable
