### ISSUE TITLE
Windows buildbots failing due to "hard kill repl test""

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#33787]
I've seen this error now in two of my PRs 
e.g.: https://build.julialang.org/#/builders/32/builds/5930/steps/2/logs/stdio 

```
Error in testset REPL:
Error During Test at D:\buildbot\worker-tabularasa\tester_win64\build\share\julia\test\testdefs.jl:22
  Got exception outside of a @test
  LoadError: LoadError: "hard kill repl test"
```

**Comment by vtjnash** [comment]
It feels like it started about 3 days ago with https://build.julialang.org/#/builders/65/builds/5581 / https://build.julialang.org/#/builders/32/builds/5890 and is now affecting many builds?

Seeing as how that is a build of a PR that changed the line of code being tested here, it seems probably related.

**Comment by musm** [comment]
@rfourquet maybe you have some ideas why we are seeing this ?

**Comment by rfourquet** [comment]
I have no idea but will have a look...

**Comment by rfourquet** [comment]
I stil don't understand the error (I don't know where the "hard kill repl test" comes from), but I would be surprised if the problem comes from #33770: all the tests were passing in this PR before merging, and as an experiment, I reverted it in #33805 (on top of an unrelated PR), and there the tests still don't pass (and not only on windows by the way, e.g. https://build.julialang.org/#/builders/22/builds/6746).

**Comment by musm** [comment]
Thanks for taking a look. 
https://github.com/JuliaLang/julia/blob/master/stdlib/REPL/test/repl.jl#L20 
https://github.com/JuliaLang/julia/blob/master/stdlib/REPL/test/repl.jl#L32
it looks like a 'kill_timer" issue in one of the tests calling the function

**Comment by musm** [comment]
I'm not seeing this anymore
