### ISSUE TITLE
Host a central JSON file somewhere with info on all published julia versions

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#33817]
@staticfloat, @SaschaMann and I discussed this over in https://github.com/julia-actions/setup-julia/pull/4. Such a file would be super useful for various CI tools and other stuff.

@staticfloat suggested the following format initially:
```
{
  "1.0": {
    "i686-w64-mingw32": {
      "sha256": "sha256 hash of .exe",
      "url": "url to .exe"
    },
    "x86_64-linux-gnu": {
      "asc": "GPG signature",
      "sha256": "sha256 hash of tarball",
      "url": "url to .tar.gz"
    }
  },
  "1.1": {
    "aarch64-linux-gnu": {
      "asc": "GPG signature",
      "sha256": "sha256 hash of tarball",
      "url": "url to .tar.gz"
    },
    "i686-linux-musl": {
      "asc": "GPG siganture",
      "sha256": "sha256 hash of tarball",
      "url": "url to .tar.gz"
    },
    "x86_64-apple-darwin14": {
      "sha256": "sha256 hash of .dmg",
      "url": "usl to .dmg"
    }
  }
}
```
A couple of thoughts:
- I think we should record things for all patch versions that exist, and then tools can figure out themselves how they want to resolve shorter version numbers. So, for example, I think the file should include no entry for `1.0`, but should include entries for `1.0.0`, `1.0.1`, `1.0.2` etc. Tools can then figure out themselves how they want to resolve something like `1.0` to a full version specifier.
- Should we maybe think about a future world where potentially there might be say a setup installer and a tar ball for the same version?

**Comment by SaschaMann** [comment]
Some additional thoughts of mine:

> Can you open an issue on the main Julia Lang tracker with the basic pieces of information you would want in the JSON file? 

The bare minimum to solve the problem we're having in https://github.com/julia-actions/setup-julia/pull/4 would be just a list of available versions (basically the list of tags in this repo). Ideally in a way that it could be extended later on without breaking the format.

More data would make the action more robust because download URLs wouldn't have to be inferred etc, so here are some things that would be really nice to have:

- Hashes & Signatures
- Download URL
- A signature for the file itself

Potentially useful but far less important than the info above:
- State of support (not the Support Tiers but whether a given version still receives updates)
- URL to the latest nightly build
  - perhaps with a `commit` field that lists which commit it was built from

I fully agree with @davidanthoff's thought to list all versions, including patches and release candidates. There are situations in which you want to test a specific patch version in your CI or benchmarking, or you want to test against release candidates.

**Comment by davidanthoff** [comment]
I think the more this could be like an immutable information, the better. I think that would be pretty easy for released versions, less clear to me about pre-release binaries. Do we host old nightly builds, or are these overwritten whenever a new build is released? If they stay around, then it might even be nice to list them all?

**Comment by staticfloat** [comment]
I don't think this JSON file is going to be updated that often; I think this is going to be updated as part of the "release checklist" that we run through every time we make an RC/new release of Julia.  So from that perspective it can have a link to the `-latest` versions of Julia (including nightlies) but I don't think it will have information such as the commit of the latest nightly baked into it.  To do that, we'd more likely need to have a little webservice that keeps track of these things and can generate the `.json` file on the fly.  I used to run one, but it fell into disrepair, and honestly most people don't need to know the latest julia version before downloading it.

Nightly builds are kept for 30 days then deleted.

**Comment by davidanthoff** [comment]
Yep, that sounds good.

**Comment by SaschaMann** [comment]
Perhaps this is helpful, here's how Go does it: https://golang.org/dl/?mode=json&include=all

**Comment by davidanthoff** [comment]
That looks very nice!

**Comment by staticfloat** [comment]
I liked that Go template, so here's one heavily based off of it: https://julialang-s3.julialang.org/bin/versions.json

I haven't taken _that_ close of a look at it, there's probably issues with it.  Let me know if you find anything wrong with it.  This is generated by [this script](https://github.com/staticfloat/WebCacheUtilities.jl/blob/master/bin/build_json_map.jl), which downloads an amusingly large  27GB of Julia archives over the course of its lifetime.

**Comment by SaschaMann** [comment]
Thanks! That will help the Actions CI a lot :)

---

>  Let me know if you find anything wrong with it

On first glance, I think the windows exe files should be installers, not archives? (Irrelevant to our use case, just noticed it)

**Comment by staticfloat** [comment]
Hmmm, yeah, you're right, we should probably call those installers.  I've changed that.

**Comment by davidanthoff** [comment]
This is awesome!

**Comment by ninjin** [comment]
Seconding the request to have the state of support baked in. I think this can be immutable as the maintenance status can be derived programmatically, we only ever have one LTS, correct? As for the nightlies, I would be thankful if there was a separate listing of them as I suspect it would encourage more users to kick the tires. However, I think I can work around it as long as the web server handles the `Last-Modified` header correctly.

**Comment by SaschaMann** [comment]
> So from that perspective it can have a link to the -latest versions of Julia (including nightlies) but I don't think it will have information such as the commit of the latest nightly baked into it.

This would be quite nice, so that I can get rid of the file name guessing for nightlies, too.

Perhaps like this:

```json
"latest": {
    "files": [
      {
        "triplet": "x86_64-linux-gnu",
        "kind": "archive",
        "arch": "x86_64",
        "version": "latest",
        "os": "linux",
        "url": "https://julialangnightlies-s3.julialang.org/bin/linux/x64/julia-latest-linux64.tar.gz"
      },
      ...
  ]
```

---

Will this file be regularly updated in the future? Right now it's missing the latest versions, e.g. `1.4.0-rc1`

**Comment by staticfloat** [comment]
Clearly this is a popular idea!  If someone wants to help hook this up to a GitHub Action so that it runs automatically on Julia having a new version released, that would be much appreciated.  The script that generates the `.json` file is here: https://github.com/staticfloat/WebCacheUtilities.jl/blob/master/bin/build_json_map.jl

It doesn't need to be in that package; it's not really using anything significant from the package, just some downloading/caching functions that make subsequent runs faster.

**Comment by SaschaMann** [comment]
> If someone wants to help hook this up to a GitHub Action so that it runs automatically on Julia having a new version released, that would be much appreciated.

I'll take a look.

**Comment by SaschaMann** [comment]
@staticfloat Are the binaries already available when the release is tagged? I vaguely remember that I got a notification for a pushed release once but the binaries weren't available yet but I might be mixing up things.

If they're not available, we can't run the script on `release` events and would have to run the action on a schedule. This would work, but it might be easier to run it on a server outside of GitHub to avoid the secret/permission management as well as not sending a notification to everyone with access to the repo in case the action fails randomly (which happens more often than one would expect...).

**Comment by ninjin** [comment]
A lot of thanks for getting the hacking going on this. I now have a prototype of my little pet project version manager running and here are some desiderata and motivations:

1. Long Term Support marking: It is likely that we have a number of users that want to stay on the LTS and the only source of this information that I am currently aware of is the Julia downloads page. We can have this and still have the JSON be “immutable” as it is easy to infer what the latest release is from the version number.

2. Nightlies with dates marked: This may be slightly more controversial, but I would like to be able to support for example `juliav install nightly-2020-02-09` as I can see it being useful to bust both package and Julia bugs without having to compile Julia from scratch. As well as allowing users to pin a specific nightly release before a breaking change was introduced. It would also be useful to keep nightlies around for slightly longer in this regard, perhaps for as long as three or six months, but I do recognise the storage space issues. Do tell me if my thinking is flawed here.

Given the above, I think everything else can be derived programmatically from the JSON itself.

**Comment by staticfloat** [comment]
> Nightlies with dates marked

Note that our nightlies are actually as-fast-as-we-can-build-them-lies; we may have 5-10 builds within a single day, so it's not quite so easy to choose which one should be _the_ one for a particular day.  We therefore identify them by git hash, rather than by date.  The downside to this is, of course, that it's difficult to say "give me a nightly from five days ago" which I think is really what Pontus is asking for.  In order to do that, we need a datastructure somewhere that tracks the last N nightlies that are available and allows you to perform queries like that.  This probably would not be a JSON file, as we'd need to change it a bunch; it could be a small webservice sitting somewhere (we used to have one at `status.julialang.org`, but I stopped maintaining that because it was a pain and few people other than myself used it).

**Comment by ninjin** [comment]
Thank you for filling me in on the “nightlies”, given this, allow me to reformulate as I really do not think we need a canonical nightly. Having the hash and time of build (start and/or completion) would be perfectly sufficient for any needs on my end. But why would could one not just to dump a JSON into a directory when you copy the resulting binary to the web server? Am I missing something?

**Comment by DilumAluthge** [comment]
Bump. Any update on this? Now that we are going to have Julia installed by default in GitHub Actions, this will be very useful to determine the latest version of Julia.

**Comment by ninjin** [comment]
All right, I have taken a stab at a new proposal in a [messy WIP branch](https://github.com/ninjin/WebCacheUtilities.jl/blob/json_map/bin/build_json_map.jl) (A big thank you to @staticfloat for his script pointing me in the direction of `Pkg.BinaryPlatforms`, it was a good read). Key changes, additions, and RFCs will follow.

Added a version to the format itself to make it easier to detect potentially breaking changes downstream:

```
{
  …
  "version": "0.1.0-DEV",
  …
```

Added URLs to nightlies to spare anyone downstream from hardcoding or scraping HTML:

```
{
  "nightlies": {
    "files": [
      {
        "triplet": "x86_64-linux-gnu",
        "kind": "archive",
        "arch": "x86_64",
        "libc": "glibc",
        "url": "https://julialangnightlies-s3.julialang.org/bin/linux/x64/julia-latest-linux64.tar.gz",
        "os": "linux",
        "path": "linux/x64/julia-latest-linux64.tar.gz"
      },
  …
```

Moved the current `files` into `releases` to separate them from the nightlies:

```
  "releases": {
    "1.5.0-rc1": {
      "lts": false,
      "files": [
        {
          "triplet": "x86_64-linux-gnu",
          "path": "linux/x64/1.5/julia-1.5.0-rc1-linux-x86_64.tar.gz",
          "asc": "-----BEGIN PGP SIGNATURE-----\n\niQJLBAABCgA1FiEENnPfUp2QSUd/drN1ZuPH3APW5JUFAl72g/0XHGJ1aWxkYm90\nQGp1bGlhbGFuZy5vcmcACgkQZuPH3APW5JW/FRAAvrDgAXP8AiUw01ZYKWyCOjIa
\nbwxYI4kbZF0pxoiFt5Zmf4AIymdYs9yoKXG2awgA8o//k8mVe2HJgORZK0IjEl9N\nXbC+pCGbOoLCTBadxjwYiZgbuzUQ3KjdSkVB1F95L9j22tBi1uBKXVAcq0X8rDnd\nM2yAYfe9g7wCZX/MxOJoP6tcc9WPEMumLB8t4bh6nOXsQz9
hifOPsxhw41Gy1F1H\nDtloCeQGmmNKXZOn0iOmJIQxzyVTrNfHNoqR9xqYEMU8mFMu09yxkBWmRywlFGaq\ne0TC1CedFEYkatyuYrLOmzTIKbtZPaacPiPQWhujoAw/9OUPShSgE8uN0KSnEM4X\nRtGHKF6R3u85TYpSeSJgJrd8TNY53M
Bs0R+6AW0lM9DZQnh0z0Np+DMRj3cjzb3R\n6b7hZXRCZK4dcD8z9jxmJ/EpTSvznZQU8g19zPPtbt1KYkLwa61/ve5H6LFBt98r\nIpsrUWyAShicQISkdZiAU9dRAxwlUM45RehaCnQNBqjvi7XGr/CKhrYqsGqjO9Ee\nyHzgPuDTcSD99
BxjPZLy0D2/fwvOoSah4zzlMlYYQlAfeLNnLFk5SS47hwVOxfd/\nPbMeVJJmp0qp3X9MCSe/qiILrqXvrNpBoR9ehlPvtMtcMJzqfUwqv1BqMPs8v0eM\npeDHvZTzpFNESdq+MnY=\n=7kMF\n-----END PGP SIGNATURE-----\n",
          "arch": "x86_64",
          "sha256": "a4ea36aa86269116992393067e5afc182707cb4f26eac9fddda08e04a9c7b94d",
          "version": "1.5.0-rc1",
          "size": 105329069,
          "url": "https://julialang-s3.julialang.org/bin/linux/x64/1.5/julia-1.5.0-rc1-linux-x86_64.tar.gz",
          "kind": "archive",
          "libc": "glibc",
          "os": "linux"
        },
        …
        {
          "version": "1.5.0-rc1",
          "triplet": "x86_64-apple-darwin14",
          "kind": "archive",
          "arch": "x86_64",
          "sha256": "ef193bad5c458083eb84cde1a486ef34c79b00f6192e0303e51f4396f311b379",
          "size": 101290262,
          "url": "https://julialang-s3.julialang.org/bin/mac/x64/1.5/julia-1.5.0-rc1-mac64.dmg",
          "os": "mac",
          "path": "mac/x64/1.5/julia-1.5.0-rc1-mac64.dmg"
        },
  …
```

In addition, I added marking of LTS releases and added `libc` (necessary now that we support musl, unless you want to parse the triplet… Yuck!) and `path` to the “file dictionary” – as can be seen above. More on `path` shortly, but it should be noted that `libc` is only present for Linux.

Lastly, I added `mirrors` for nightlies and releases:

```
{
  "mirrors": {
    "releases": [
      "https://julialang-s3.julialang.org/bin"
    ],
    "nightlies": [
      "https://julialangnightlies-s3.julialang.org/bin"
    ]
  },
  …
```

Now that I am typing this, maybe they should be added individually to releases and nightlies, but that is easy enough to handle later. The thought is that it has come to my attention that we have several unofficial mirrors in the PRC and I can imagine companies wanting internal mirrors as well for that matter. With `mirrors` and `path` it becomes trivial to programmatically create and keep a mirror up to date.

There are some outstanding thoughts in the comment at the top of the messy patched file to generate it, but these are the big changes really. Thoughts?

**Comment by johnnychen94** [comment]
I think mirrors should not be considered permanent and trustworthy. Also, not all mirrors are public. It would be more convenient to deal with this in an extension package.

Another concern about advertising mirrors is that it will be harder to collect user statistics.

**Comment by ninjin** [comment]
> I think mirrors should not be considered permanent and trustworthy. Also, not all mirrors are public. It would be more convenient to deal with this in an extension package.
> 
> Another concern about advertising mirrors is that it will be harder to collect user statistics.

All fair points that I agree with, but I am not sure how it relates to having the official mirrors in the official JSON.

**Comment by johnnychen94** [comment]
The official JSON could serve as a template. We can introduce an extension tool to regex and replace URLs, and dynamically generate a new JSON for mirrors. I did this in my [jill.py project](https://github.com/johnnychen94/jill.py/tree/master/jill/config) and I find it rather flexible to [make modifications](https://github.com/johnnychen94/jill.py/pull/31/files).

**Comment by johnnychen94** [comment]
It would be a common case that mirrors also provide pkg servers as well as these Julia downloads; these can be both handled in a mirror registry.

CRef: https://github.com/JuliaPackaging/PkgServer.jl/pull/59#issuecomment-657263902

**Comment by ninjin** [comment]
I think there is some confusion here in terms of what I meant by “mirror”, most likely due to my own usage. I am not proposing that we list every official and unofficial mirror. Rather, I firstly wanted to account for the fact that there may be more than one official URL for each file (see for example at what Go does in their JSON. They do not list URLs but rather filenames.). Secondly, as an additional benefit I saw that it became easier to set up a mirror programmatically that would have the same structure as the official ones.

Lastly, I think any URL templating is overkill and should not be a feature of the JSON itself. If possible, I want to keep it as “dumb” and static as one can possibly make it. Heck, “mirrors” may be overkill, but it is hard for me to know since my understanding of what constitutes “content delivery” is probably 15 years out of date.

**Comment by johnnychen94** [comment]
Oh yes, we are talking about two types of mirrors; the mirrors I'm talking about are unofficial servers.

For official resources, it can be more convenient and reliable to serve them via a CDN network and users of this JSON file don't need to know what's actually serving `julialang-s3.julialang.org`.

For example, we can redirect `https://julialang-s3.julialang.org/$path` to `https://mirror.<code>.pkg.julialang.org/julialang2/$path` where `code` can be `kr`, `eu`, `us-east`, etc. (I'm not sure if this is already the case)

The mirrors feature, IMO, should leave to cases when multiple authorities are involved.

**Comment by ninjin** [comment]
Good, let us leave the unofficial mirrors by the wayside for now. I am content that they can be created from the file, but that is it really. If some downstream mirror wants a different URL scheme, etc. They are free to deal with that complexity on their own.

As for the CDN, this I think is exactly what I would love feedback on. Does it make sense to use `mirror` concatenated with `path` or just stay with `url`? The former only makes sense if there is some case for multiple CDN base URLs (No idea if this makes sense, but perhaps there is a case to use multiple providers? Maybe one with better reach for PRC than AWS at some point?). The latter is certainly simpler, but forces us to commit to a single URL per file – unless we want to go with `urls`?

**Comment by staticfloat** [comment]
I'm a little lost, but it is the case right now that every Pkg server can serve as a caching proxy for the official binaries S3 bucket.

So something hosted at `https://julialang-s3.julialang.org/$path` will be available at `https://mirror.$region.pkg.julialang.org/julialang2/$path`.  The `julialang2` is an S3 bucket name, you can use `julialangnightlies` to get nightlies as well.  This works right now, and is beneficial for users who want to download from somewhere that is very close to them.  So most mirrors will be accessible by modifying some prefix of the URL, making that easy is fine, but TBH I think it's simple enough to just `s/julialang-s3.julialang.org/mirror.us-west.pkg.julialang.org\/julialang2/`, and `s/julialangnightlies-s3.julialang.org/mirror.us-west.pkg.julialang.org\/julialangnightlies/`.

**Comment by ninjin** [comment]
My apologies to the both of you regarding the confusion, I do think the blame falls largely on me for not speaking the “CDN language” and yet attempting to implement something that is closely linked to it. In all honesty, `mirrors` is really the proposed addition I care the least about and I am more than happy to rip it out, but I will make one more attempt to explain the use case I had in mind.

`versions.json` is likely to be consumed by some downstream tool like JILL that is primarily interested in installing Julia versions to the end user. Currently, if there are issues with for example the delivery speed (PRC for example, but I am sure the topology of the Internet allows for more corner cases) or for some god forsaken reason there is a DNS issue/block in regards to the two official buckets it ends up being the downstream tool that will have to do its best to accommodate for this by either modifying the URLs or employ some sort of mirror specification of their own to incorporate official and unofficial mirrors. My thinking was that it was easier to provide mirrors (the official ones, for unofficial ones I would love for them to just host their own conforming `versions.json` that one could point to) centrally as we can then introduce/retire regions and providers as we see fit, rather than leaving it to those that are downstream to keep track of the upstream infrastructure. I do not know if this is what Go in some way does, but it is interesting that they lack a URL and only list the filenames. Is this sensible? Too complex? Unnecessary and/or flawed? I am more than happy to accept arguments for either of these conclusions as I feel like a caveman in this conversation.

Regarding the other additions:

1. `version` marking
2. `lts` marking
3. URLs to nightlies
4. `libc` introduction for files

Are these uncontroversial as “sensible” or is it that `mirrors` is just a big enough eyesore to distract from them?

**Comment by johnnychen94** [comment]
* `version` marking: this is a breaking change and could possibly break any workflow based on `versions.json`. Given that this file doesn't get updated for months and nobody complains about it, I see this an acceptable change to make parsing easier.
* `lts` marking and URLs to nightlies :+1: as it provides more information to downstream users without breaking anything.
* `libc` introduction for files: unsure what's the usage of this and I don't have a comment for it.

**Comment by staticfloat** [comment]
Yeah, that all seems totally sensible to me.  If you want to make a list of mirrors so that it's easy for downstream tools to do the substitution, then I suggest dynamically making the list from the [siblings endpoint](https://us-west.pkg.julialang.org/meta/siblings) on any pkg server.  You can take each element in that list, and transform it from `https://$region.pkg.julialang.org` to `https://mirror.$region.pkg.julialang.org/$bucketname`, and that should allow you to fill up your mirrors list easily.

**Comment by ninjin** [comment]
Super! Thank you for the sibling endpoints link and both of you for the mirrors feedback, this is exactly why I do not feel comfortable making calls like this on my own and I can now rip out the mirrors from the format. I will try to steal a few minutes to clean up my branch and split the commits to get a PR going, possibly tonight.

Some minor outstanding questions/tasks on my part:

1. I think it makes sense to include the sources (with and without dependencies), thoughts?
2. I will need to check that the heuristic captures older releases as well, perhaps by looking at the unmaintained releases page and comparing it to the resulting JSON or is there some S3 magic to get a list of everything under `bin`?
3. I need to dig up what “portable” means in the context of Windows.

That should be it.

@staticfloat there is a slight oddity with the naming of the Linux AArch64 nightlies that I [worked around](https://github.com/ninjin/WebCacheUtilities.jl/blob/2d469241d3f9fbc0bdc2f538c8d0f66cf0a18b15/bin/build_json_map.jl#L114-L116). I am fine with keeping the hack in there for the PR, but I do feel that I should tell you. My “one pint-bet” would be a regexp somewhere that matches but does not re-insert the dash.

**Comment by staticfloat** [comment]
I think the only reason you think `aarch64` is strange is because it's the only non-intel arch that has nightlies right now.  ;)

The nightlies all follow the pattern of `linux$(processor_name)` but the intel ones are the strange ones, because for a long time we only had intel processor support, so we just named things by their wordsize.  That of course doesn't work once you have other processors, but we didn't want to change things to break CI unnecessarily, so we just made all non-intel processors use the more descriptive name.

Now we did actually overhaul the official downloads a while back, and I think we should just bite the bullet and change the nightlies to upload to identical names.  So the nightlies should be things like `linux-x86_64.tar.gz` instead of `linux64.tar.gz`.

**Comment by SaschaMann** [comment]
Took me a while to get back to it, sorry.

I wrapped it in a workflow: https://github.com/SaschaMann/versions.json-testing

build_json_map.jl is based on Elliot's version with the addition of an `rm` call to delete the downloaded file because the GHA environment has limited storage space, and reading the path to the output file from `ARGS[1]`. The script can be swapped out for whatever version, or it can pull it from WebCacheUtilities.jl. I committed it to the repo for testing purposes.

Currently, it's triggered manually by pressing a button in the actions tab or with a [repository dispatch event](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#manual-events).

Here's an example build: https://github.com/SaschaMann/versions.json-testing/runs/1282040279?check_suite_focus=true

So far I've only tested it on GH without uploading it to S3 because I don't have an AWS account to test it easily. The commented out steps to upload it to S3 could be a starting point to upload it to there. They use official AWS actions. More info here: https://github.com/aws-actions/configure-aws-credentials#usage

---

The issue I mentioned above about when to run these builds still needs to be solved: https://github.com/JuliaLang/julia/issues/33817#issuecomment-583724863

There are a few ways to automate this:

- It could be run on a `release` event but that would require the new binaries to all be available when a release is tagged. IIRC this is not always the case. But please correct me if I'm wrong!
- Manually as part of the release process via the `workflow_dispatch`.
- If there's some kind of release script, it could send a `repository_dispatch` event to automatically trigger a build once all binaries are uploaded.
- On a schedule, but given that the build takes ~25 minutes, there should be some kind of check that there was a recent release. This has the same issue that the `release` event has. One potential fix could be a check that the versions.json builds once a day the first X days after a release has been tagged.

Further, you may not want to run this in julialang/julia since all people with write access would gain access to the S3 creds. I don't know if that is a problem or not, just something to be aware of.

@staticfloat Do you have an idea/preference?

**Comment by fredrikekre** [comment]
Why not jus host it on julialang.org? We update that for releases anyway so could just rerun the script there.

**Comment by staticfloat** [comment]
Yeah, let's run it in a context with smaller scope in terms of who can see the credentials.

As far as when to run it; I think an easy way to do it would be to run it once per day, but early-exit if a release hasn't been tagged within the last week.  We usually have some amount of binary shuffling (macos binaries that get notarized, armv7l binaries that need to be manually massaged a bit) but it usually doesn't take us more than 2-3 days after tagging.  I'd like to make these things more automatic as much as possible, to reduce the load on our release managers.

**Comment by SaschaMann** [comment]
> As far as when to run it; I think an easy way to do it would be to run it once per day, but early-exit if a release hasn't been tagged within the last week. 

Sounds good, I'll add that to the workflow

**Comment by SaschaMann** [comment]
Done, now it runs on a schedule and aborts if the last release on GitHub is older than a week using [the rebuild_check.jl script](https://github.com/SaschaMann/versions.json-testing/blob/main/rebuild_check.jl)

The manual trigger will always run, this would allow you to trigger it in case some binary needs to be fixed later on or something goes wrong. Takes ~1-1:30 min to run the check. Most of that is spent on installing dependencies.

To configure the AWS deploy, you'll have to change [these environment variables](https://github.com/SaschaMann/versions.json-testing/blob/main/.github/workflows/build-versions-file.yml#L8-L10), uncomment the [steps at the bottom](https://github.com/SaschaMann/versions.json-testing/blob/main/.github/workflows/build-versions-file.yml#L39-L50) and set the `AWS_DEPLOY_ACCESS_KEY_ID` and `AWS_DEPLOY_SECRET_ACCESS_KEY` secrets in the repo.

I've not tested the upload myself but I asked @iHiD, who's familiar with deploying to S3 from GHA, to check it and he said it should work. :D 

The rebuild_check and normal build work in my tests. There are some example builds in the Actions tab of the repo.

Since I don't know how familiar with GHA you are: you can trigger a build manually if you navigate to the workflow in the Actions tab of the repo. This is restricted to people with write access to the repo.

> Yeah, let's run it in a context with smaller scope in terms of who can see the credentials.

There's no reference to the repo that contains the workflow/scripts, so you should be able to clone it to a new repo that only the release managers have access. I'll watch it and am happy to PR fixes/updates to it if necessary.

**Comment by fredrikekre** [comment]
> To configure the AWS deploy, you'll have to change these environment variables, uncomment the steps at the bottom and set the AWS_DEPLOY_ACCESS_KEY_ID and AWS_DEPLOY_SECRET_ACCESS_KEY secrets in the repo.

Could it not just be pushed to `gh-pages` for https://github.com/JuliaLang/www.julialang.org? That is what I meant with https://github.com/JuliaLang/julia/issues/33817#issuecomment-713010563 but perhaps we wan't to host it on AWS too.

**Comment by SaschaMann** [comment]
Ah sorry, I misunderstood you. I thought you meant we should use that as release trigger, my bad.

We could push it to gh-pages too but I feel like there's some advantage to have that file separate from GH's infrastructure like the rest of the downloads.

**Comment by staticfloat** [comment]
@SaschaMann since it sounds like you are quite adept at this, and since you are offering to maintain it..... would you like to just create a repository, invite me to it as well, and I'll get you the S3 creds you need to upload it.  I too like it living in S3.

**Comment by SaschaMann** [comment]
Sure, works for me. I've invited you to the repo: https://github.com/SaschaMann/versions.json-testing/invitations

I'm happy to move this to an org too if you prefer.

**Comment by staticfloat** [comment]
It looks like it works!  The current `versions.json` was uploaded by Sascha's github action, so I'm going to consider this closed.
