### ISSUE TITLE
Range acts differently in 1.3.0 and 1.0.5, not reflected in docs

### ISSUE THREAD

**Issue by fpmenninger** [JuliaLang/julia#34215]
Version 1.3.0
```
julia> range(1, 5, step=1)
1:1:5
```

Version 1.0.5
```
julia> range(1, 5, step=1)
ERROR: MethodError: no method matching range(::Int64, ::Int64; step=1)
Closest candidates are:
  range(::Any; length, stop, step) at range.jl:76
Stacktrace:
 [1] top-level scope at none:0
```

**Comment by ericphanson** [comment]
It’s described in the green box: https://docs.julialang.org/en/v1/base/math/#Base.range

**Comment by fpmenninger** [comment]
Not "stop", but "step"... which is not mentioned in the green box.  
If step also requires at least Julia 1.1, that should be added to the green box.

**Comment by ericphanson** [comment]
The error you see is because you must specify either length or stop as a keyword argument for Julia 1.0 in order to construct a range. The new feature of Julia 1.1 is that you can instead specify stop as a positional argument.

You’re using two positional arguments, which doesn’t have a method on Julia 1.0, but one was added in Julia 1.1.
