### ISSUE TITLE
Pkg update problem for Julia on Windows

### ISSUE THREAD

**Issue by azev77** [JuliaLang/julia#34221]
In REPL I wrote 
` ] add FixedEffectModels#Master`

however the code ran the same as before. 
Next I manually deleted files from 
`C:\Users\azevelev\.julia\packages`

then I reinstalled in REPL and it worked. 

I encountered this problem twice this week, first w/ [MLJ](https://github.com/alan-turing-institute/MLJ.jl) and today with [FixedEffectModels](https://github.com/FixedEffects/FixedEffectModels.jl).

**Comment by azev77** [comment]
Related problems updating packages are discussed here:
https://discourse.julialang.org/t/package-stuck-at-old-version/32924

**Comment by StefanKarpinski** [comment]
In normal usage, once you've loaded a package, it is loaded. Changes to the code or the environment will not have any effect on the running code. You have to restart Julia and reload the code in order to get a different version of the package. The [Revise](https://github.com/timholy/Revise.jl) package can detect code changes and reload packages for you, but you must be using Revise.

**Comment by azev77** [comment]
Thank you Stefan. 
I did restart Julia & reloaded the code a few times. It didn't work. 
This is why I manually deleted those files.

**Comment by StefanKarpinski** [comment]
The issue described in that discourse post sounds different—the installed version does not update in certain circumstances; this has been changed in newer Julia versions. You'll have to describe your issue in more detail.
