### ISSUE TITLE
permutedims of Diagonal returns sparse matrix

### ISSUE THREAD

**Issue by amiragha** [JuliaLang/julia#34256]
Not sure if this is expected behavior, but the `permutedims(Diagonal([1,2,3]), [2,1])` returns a sparse matrix instead of an instance of `Diagonal`!

**Comment by dkarrasch** [comment]
`permutedims` is used in a data storage context, see the docstring. In the linear algebra context, where you care about the optimal matrix type for further manipulation/multiplication/solving/etc., one should use `transpose` or `adjoint`.

**Comment by ViralBShah** [comment]
But isn't it confusing that it returns a sparse matrix?

**Comment by dkarrasch** [comment]
> But isn't it confusing that it returns a sparse matrix?

Yes, could be, but it is ubiquitous.

```julia
julia> permutedims(UpperTriangular(rand(3,3)))
3×3 Array{Float64,2}:
 0.281075  0.0       0.0     
 0.288408  0.191988  0.0     
 0.169203  0.15291   0.403274
```
It's due to calling `dest = similar(A, genperm(axes(A), perm))`, and it's not easy to find which method eventually decides to create a sparse array.

**Comment by amiragha** [comment]
How about just return `transpose` for `permutedims` of matrix-like objects (if the perm is `[2,1]`) other wise just the matrix itself? 

I was just writing a generic code with array of rank N, that I found this issue. I am sure not a lot of people would use `permutedims` on an object they know is a matrix. However, it is nice to have `permutedims` return the same type. Even more so when it actually calls `similar`

**Comment by dkarrasch** [comment]
The crucial line is https://github.com/JuliaLang/julia/blob/18783434e9c0e48152b99d5e3717deb8711f492b/stdlib/SparseArrays/src/SparseArrays.jl#L51

Clearly, calling `similar` does not guarantee to get back the same type, and this looks intentional.

> How about just return `transpose` for `permutedims` of matrix-like objects (if the perm is `[2,1]`) other wise just the matrix itself?

First, this sounds like a type instability, second (as the docstring says) `permutedims` does not act recursively in contrast to `transpose` (think of arrays of arrays). Moreover, `permutedims` returns (except for vectors) copies of the array that are unaliased to the input, and people may rely on that behavior.

I continue to have a hard time imagining your application case. Having generic code for arbitrary ranked arrays sounds like you're working with arrays as containers of something, and these containers may happen to be two-dimensional, okay. This sounds to me like being independent from `LinearAlgebra` actually. Now, why do you care about linear algebra types in the two-dimensional case so much?

**Comment by amiragha** [comment]
Thanks, I think I get the point. It indeed doesn't make sense to return `transpose` for `permutedims`.

As for my use case, I was trying implementing some form of tensors (multi-linear maps) and was using instances of Diagonal to represent singular values of those object resulting from a `svd` function. so it was at least conceptually LinearAlgebra related. I was regarding `permutedims` as some generalization of `transpose` for mutli-linear algebra, which is clearly not the case here.

I close the issue then.
