### ISSUE TITLE
Threaded RNG should use same stream at different locations not different streams

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#34386]
The new, thread-safe RNG (PR #32407) uses separate RNG streams  ([link to code](https://github.com/JuliaLang/julia/blob/6144a5d7117f9e407bca2e8d7476cce3d586e858/stdlib/Random/src/RNGs.jl#L297)) instead of using the "trick" advocated in the [docs](https://github.com/JuliaLang/julia/blob/7afbb05384186457cedd321071fde137880bfaa5/doc/src/manual/parallel-computing.md#side-effects-and-mutable-function-arguments) of using just one chain but sampling from different locations (implemented using `Future.randjump`).

[Wikipedia](https://en.wikipedia.org/wiki/Mersenne_Twister#Disadvantages) (fourth bullet) suggests that at least for Monte-Carlo the randjump strategy should be used.  Or are the seeds of the separate streams chosen such that inter-stream numbers are non-correlated too?  This [line](https://github.com/JuliaLang/julia/blob/53ba0cc3c7313a66e781e18088379b75f395e0ce/stdlib/Random/src/RNGs.jl#L288) suggest that no such approach is taken.

Is the randjump the right way to go about this? If so, I could do a PR.

X-refs:
- https://discourse.julialang.org/t/parallel-mersenne-twister/27567
- https://discourse.julialang.org/t/is-rand-threadsafe/4683/3
- https://github.com/JuliaLang/julia/issues/94#issuecomment-515806131

Cc: @rfourquet

**Comment by rfourquet** [comment]
I was just wondering what exactly should be done. Shall `randjump` be used automatically only on creation (when retrieving `default_rng()` on a specific thread for the first time)? In this case, some details need to be sorted out, like which RNG to use as a reference? (given that we don't know which ones exist yet). Then, if the user calls e.g. `seed!(0)` in thread 1, before the creation of the global RNG `rng2` in thread 2, does she expect `rng2` to also be seeded (predictible) ?

Should `randjump` be used also with `seed!` (in which case `seed!` shouldn't be called from within every thread) ?

It seems to me that using `randjump` automatically forces to have either all thread rngs seeded or all not seeded. I migth be a bit confused here, but the it shows at least that the details need to be explicited :)

**Comment by vtjnash** [comment]
> Wikipedia (fourth bullet) suggests that at least for Monte-Carlo the randjump strategy should be used. Or are the seeds of the separate streams chosen such that inter-stream numbers are non-correlated too? This line suggest that no such approach is taken.

If you look at the citation there, it actually says care must be taken that they are not initialized from a linear recurrence. Yes, one method is call randjump, which is what got published in that paper. I'm not a cryptography, but my interpretation of that information is that also just not using a linear recurrence for initialization should be statistically acceptable. Our implementation therefore lacks the provable guarantee for the other approaches (and corresponding robustness against bad seed design), but I'm thinking it must be statistically immensely improbable for two unrelated seeds to be correlated (the state space of MT is huge). But, to reveal my trick, some care must be taken in my use of the world "unrelated". Simply feeding in sequential numbers, such as you might get from another standard PRNG (including MT) does not give unrelated seeds. But we don't do that. If the current mechanism of using the kernel's randomness is discovered to be insufficient, we might be able to use a secure hash of the seed, such as `AES`, to improve the quality of the input. Though my real suggestion in that case might be to get a better kernel which provides a true [CSPRNG](https://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator), since that CS stands for cryptographically secure, and its commitment to not being a linear relation is the foundational aspect of system security for nearly everything.

This was discussed during the implementation of the current work, though I'm not sure any one source covers the entirety of the design rationale. And I've done a bit of hand-waving in my analysis based on what I'm assuming are reasonable assumptions about statistics, but am no expert, or even that well-read of an amateur.

**Comment by peteroupc** [comment]
For your information.

Perhaps you should consider alternatives to Mersenne Twister for the parallel PRNG, especially because it uses such a big state.

- Here, I define [high-quality PRNGs](https://github.com/peteroupc/peteroupc.github.io/blob/master/random.md#high-quality-rngs-requirements).
- Here, I list examples of [high-quality PRNGs](https://github.com/peteroupc/peteroupc.github.io/blob/master/random.md#high-quality-prng-examples).
- Here, I mention how [multiple processes](https://github.com/peteroupc/peteroupc.github.io/blob/master/random.md#seeding-multiple-processes) can be initialized based on a common seed.  Note that besides the jumping strategy, some PRNGs, notably so-called _counter-based_ PRNGs, implement streams by giving each seed its own independent random number sequence (and providing a _counter_ to index into that sequence).

**Comment by vtjnash** [comment]
Yes, as described there, we use option 3 by default and assume that you don't normally want reproducible randomness. For the MT we use, the probability this results in the same seed on two threads is indistinguishable from zero (which might actually be too low, since any two true RNG should have a small chance of appearing to be correlated). I think we have other existing issues proposing changing from MT. The "big" state is tiny relative to the rest of the machine, so it's not really a convincing factor. But there may be other better PRNGs now that would be good to look into switching to, if someone provided an implementation of it.

**Comment by tkf** [comment]
Quoting what I mentioned in [the discourse thread](https://discourse.julialang.org/t/brew-a-parallel-rng/30286/5):

> I fond what Guy Steele mentioned in the last half of this talk interesting:
>
> https://www.youtube.com/watch?v=0hlBkQ5DjaY
>
> IIRC there is a type of PRNG that can be split in such a way that the distribution of resulting streams combined is equivalent to the original stream (or something like that). It would be nice to look into (probably some follow up studies of):
>
> * http://supertech.lcs.mit.edu/papers/dprng.pdf Deterministic Parallel Random-Number Generation for Dynamic-Multithreading Platforms
> * https://ieeexplore.ieee.org/abstract/document/6114424 Parallel random numbers: As easy as 1, 2, 3
>
> which were mentioned in the talk.

There is a Julia implementation of counter-based PRNG: https://github.com/sunoru/Random123.jl

**Comment by vtjnash** [comment]
Just to say it clearly, I think those researches are generally talking about _reproducable_ (seeded) streams. We want something a bit different (unpredictablity) as the default. So these are not contradictory, just different needs.

**Comment by peteroupc** [comment]
In my opinion, if unpredictability of random numbers (or information security in general) is a goal, then only a [cryptographic RNG](https://github.com/peteroupc/peteroupc.github.io/blob/master/random.md#Cryptographic_RNGs) is appropriate and an application should have only one thread-safe instance of the cryptographic RNG for the whole application to access.  If reproducibility is important, the API can provide a separate (perhaps parallel) PRNG for that purpose, where the user can supply a seed (see "[Implementing New RNG APIs](https://github.com/peteroupc/peteroupc.github.io/blob/master/random.md#implementing-new-rng-apis)").

**Comment by tkf** [comment]
My bad. This issue is not about reproducibility. My comment was off-topic.

> We want something a bit different (unpredictablity) as the default.

Isn't this issue about making sure Julia has "independent" streams across threads?  IIUC you don't need "unpredictability" in the sense of CSPRNG _within_ a single thread.  You just need that different threads produce independent random numbers.  (Or maybe my understanding of the word "unpredictability" is not accurate.)

**Comment by vtjnash** [comment]
That was a good comment, I was replying as much for my own benefit as others to clarify why I don’t think that research is applicable to the default (non-seeded) case. Thus, I don’t know what this issue is about—I think it’s about asking your question to request more documentation maybe. It might be just about independence, but it seems to be mistaking independence for “unpredictability”. And yes, I deliberately picked an ambiguous word here to try to separate it from the usual statistical vocabulary and focus instead of the usage. A CSPRNG is not required within an application for statistical purposes (it is required for cryptography of course), but the CSPRGN is necessary to create seeds for the PRGN (else the values on one thread may be statistically predictable from the values seen on another thread). The independence is only broken if you use a flawed seeding approach, such as using sequentially generated numbers, such as 1,2,3 or rand(),rand(),rand(). Using either randjump or a cryptographic seed should be equally safe for the purposes of splitting a stream into uncorrelated streams. The randjump approach is fraught with complexities and difficulties, while using different cryptographic seeds is trivial. (Actually, I think the cryptographic seed is probably actually more “safe” by simple argument that it seems it would severely compromised the integrity of MT if two completely unrelated machines were more likely to be correlated than two threads on one machine).

**Comment by vtjnash** [comment]
Note that the CSPRNG in that case may be initialized from the PRNG, or even from known sequential numbers, so the question regarding the use of a CSPRNG for cryptographic security is fully orthogonal to the question of setting a seed for reproducibility.

**Comment by mauro3** [comment]
Ok, so reading through this thread, my original question:

>  Or are the seeds of the separate streams chosen such that inter-stream numbers are non-correlated too? 

can be answered with "yes".  I wasn't aware that using different (truly) random numbers as seeds will guarantee uncorrelated streams.

Documentation is needed though on how to seed threaded RNGs such that the streams are uncorrelated.

**Comment by mauro3** [comment]
Although, from a UI point of view, it would be nice if only one seed would need to be set and that all the thread-local seeds would be updated consistently (and predictably).

**Comment by oscardssmith** [comment]
@mauro3 the chance of coprime numbers approaches pi^2/6

**Comment by tkf** [comment]
> Although, from a UI point of view, it would be nice if only one seed would need to be set and that all the thread-local seeds would be updated consistently (and predictably).

This is related to my first comment. Reproducible computation using thread-local RNG is not possible in general with dynamic scheduling.  Since there is no reliable way to turn-off dynamic scheduling, I don't think consistent seeding across threads has to get a high priority.

**Comment by stephenll** [comment]
At my company, financial/insurance simulations, we typically break up the simulations into predefined fixed "chunks", and assign a seed to each chunk.  Then let the dynamic scheduler do its thing.  For the most part this makes our simulations repeatable no matter the machine or number of cores. We have been doing this in c# with success.

I ported our engine to Julia hoping to get the same type of repeatability, and I did,  but the randjump calc is slower than the time it takes to simulate a "chunk".  Depending on the size of the model it makes sense to either not use threading at all, or now create a chunk size that is dependent on model size just so the randjump makes threading improve the run time.

Just sharing some recent observations.

**Comment by StefanKarpinski** [comment]
Thank you for the feedback, @stephenll. That's very helpful!

**Comment by peteroupc** [comment]
> I ported our engine to Julia hoping to get the same type of repeatability, and I did, but the randjump calc is slower than the time it takes to simulate a "chunk". 

Maybe that lies in the fact that Mersenne Twister (MT19937) has a big state compared to other modern PRNGs (about 2500 bytes compared to 16 or 32 bytes), so that jumpahead is less trivial?  (By the way, different PRNGs support different strategies to support "streams" of numbers that behave like independent random numbers.  For linear PRNGs, that is jumpahead.  For counter-based PRNGs, that's the use of "nearby" seeds.)

**Comment by stephenll** [comment]
I should of mentioned that the single threaded Julia runs about the same speed as the multithreaded on 4 cores c# code I converted from.  So huge win using Julia even without the threading. Less more readable code. I don’t need to rely on the c# devs to experiment or research.  Can’t wait to see how the experimental threading develops.

**Comment by mbauman** [comment]
If I understand correctly, this is fixed/superseded by #40546.
