### ISSUE TITLE
ccall() with parametric type passing junk values

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#34779]
If I define a function parameterized on a type, then use `ccall()` with that type bare, as in the following example:

```julia
# test.jl
function foo(N::T) where T
    ccall((:foo, "./libfoo.so"), Cvoid, (T,), T(10))
end

foo(Int64(10))
```

It seems that `ccall()` will somehow generate bad code and pass garbage values in for that parameter.  Example:

```c
// foo.c
#include <stdint.h>
#include <stdio.h>

void foo(const int64_t nz) {
    printf("foo(): %lu\n", nz);
}
```

```
$ gcc -shared -o libfoo.so foo.c
$ julia test.jl 
foo(): 140437311111840
```

Whereas, if I replace the `(T,)` with `(Int64,)`, it works.  The `@code_native` of `foo()` for the working, then broken cases is interesting:

```
# working
julia> @code_native foo(Int64(10))
        .text
; ┌ @ test.jl:4 within `foo'
        pushq   %rax
        movabsq $foo, %rax
        movl    $10, %edi
        callq   *%rax
        popq    %rax
        retq
        nopw    %cs:(%rax,%rax)
; └
```

```
# broken
julia> @code_native foo(Int64(10))
        .text
; ┌ @ test.jl:4 within `foo'
        pushq   %rax
        movabsq $140430885606048, %rdi  # imm = 0x7FB89D0D52A0
        movabsq $foo, %rax
        callq   *%rax
        popq    %rax
        retq
        nopl    (%rax)
; └
```

**Comment by yuyichao** [comment]
I thought Jameson made that an error....

**Comment by staticfloat** [comment]
Jameson just said to me on slack:

> It’s supposed to reject that function definition, but the verifier doesn’t always run when it’s supposed to
> (rejected because C, and thus llvm, have no equivalent receiver)

I'm not sure what that means, can you unpack that for me a bit?

**Comment by yuyichao** [comment]
I believe it is forbidden because such code is not precompilable. You can still do it though, you just need a generated function where all of the other non precompilable cases lives. I was promised that if the abi (i.e. type layout) can be deduced without the type parameters it should still work. This include `Ptr` and `Ref`.

I never looked into who is responsible for rejecting such code. I assume he meant that the compiler just assume such case are not supported and always does a best effort compiling it. The code that actually check for these cases might not be enabled by default.

**Comment by vtjnash** [comment]
This correctly errors now when you attempt to define the method `foo`
```
julia> # test.jl
       function foo(N::T) where T
           ccall((:foo, "./libfoo.so"), Cvoid, (T,), T(10))
       end
ERROR: TypeError: in ccall method definition, expected Type, got a value of type TypeVar
Stacktrace:
 [1] top-level scope
   @ REPL[19]:2
```
