### ISSUE TITLE
NTuple requires the first type parameter to be Int64

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#34977]
Is there any reason why it's restricted to Int64 ?  

I.e.
```julia
julia> NTuple{Int32(3),Float32}
ERROR: TypeError: in Vararg, in count, expected Int64, got Int32
```

**Comment by timholy** [comment]
Types don't have "sizes," only values have sizes (when you do `sizeof(NTuple{N,Float32})` it reports the size of the corresponding value). So there's no advantage in supporting it, and to the contrary supporting only `Int` avoids nasty "how come these look exactly the same but aren't the same type?!?" train wrecks.

What are you trying to do? Let me guess: this comes up in supporting data types saved via HDF5/JLD/JLD2 on machines with different word sizes? It would be best to normalize the reconstructed types so that `N` is always `Int`.

**Comment by musm** [comment]
Thanks for the reply. Makes sense and yes that was how this came up.
