### ISSUE TITLE
Shouldn't the compiler infer the vector type in list comprehensions?

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#35089]
Regarding the example:

```Julia
julia> v = [:a=>Float64, :n=>String]
2-element Array{Pair{Symbol,DataType},1}:
 :a => Float64
 :n => String 
julia> a = [s=>Vector{T}() for (s, T) in v]
2-element Array{Pair{Symbol,B} where B,1}:
 :a => Float64[]
 :n => String[] 
julia> eltype(a)
Pair{Symbol,B} where B
```

Shouldn't the compiler be able to pick up `Pair{Symbol,Array{T,1} where {T}}` instead of the generic `Pair{Symbol,B} where B`?

**Comment by thofma** [comment]
Because it would be a wrong result:
```julia
julia> Pair{Symbol, Vector{Int}} <: Pair{Symbol, Vector{T} where {T}}
false

julia> Pair{Symbol, Vector{Int}} <: Pair{Symbol, T} where {T}
true
```

**Comment by jakobnissen** [comment]
Right, but surely it would be possible to infer it to `Pair{Symbol, T} where T<:Vector`?

**Comment by thofma** [comment]
It comes from `promote_type`:
```julia
julia> promote_type(Pair{Symbol, Vector{Float64}}, Pair{Symbol, Vector{String}})
Pair{Symbol,Array{T,1} where T}
```
Not sure if there is some action to take? Lot's of things are possible when the compiler is allowed to do more work. One can always ask for more narrow types for [insert favorite construct here]. For what it is worth, you can narrow it down using the following trick (which I learned from @KristofferC):
```julia
julia> identity.(a)
2-element Array{Pair{Symbol,B} where B,1}:
 :a => Float64[]
 :n => String[] 
```

**Comment by martinholters** [comment]
Just to have that clear: the type is determined by promotion based on the actual values and has nothing to do with inference.

**Comment by JeffBezanson** [comment]
Correct, this type is not picked by the compiler, but by `promote_typejoin`. There are two possible strategies for promoting within a heterogeneous array:
1. Widen the array element type and leave the elements alone.
2. Pick a "bigger" concrete type (according to `promote_type`) and convert all the elements to that type.

Comprehensions use (1):
```
julia> [x for x in (1,1.0)]
2-element Array{Real,1}:
 1
 1.0
```

Array literals and concatenation (and lots of other things) use (2).

In general (1) is better, since it avoids converting (and therefore possibly copying) all the elements (in case they are e.g. arrays), and it also preserves more information since you're guaranteed to get out the exact values the comprehension expression generated. In any case, we're not changing this.
