### ISSUE TITLE
regression printing unusual Exprs inside nested quote

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#35134]
Reported on slack. Caused by part of #32423; we will probably have to revert that bit.

```
julia> ex = Expr(:quote, Expr(:quote, Expr(:foo)))
:(:(:($(Expr(:foo)))))

julia> eval(Meta.parse(repr(ex))) == ex
false
```

**Comment by simeonschaub** [comment]
Its quite unfortunate that we will always have to print nested quote expressions the verbose way, otherwise we would have to traverse the whole expression tree to make sure there aren't any unusual expressions in there. I'm currently working on a PR to print unusual expressions without the `:($(...))` around them if they are not inside another expressions, but turns out, printing expressions in an intuitive way is quite a deep rabbit hole.:grin:
