### ISSUE TITLE
"Constructors" section should be a sub section of a larger Objects section

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia#35152]
Why is there a "constructors" section but not one about Objects in the docs? https://docs.julialang.org/en/v1/manual/constructors/#man-constructors-1

The way I was taught, and this could be the wrong way, was that constructors are what is used to create objects, but the higher-level piece is the object itself. We did not start by learning about constructors and then move into learning what an object (in the programming sense) was. 

I'm interested to hear thoughts as to why we should have a constructors sections but not a objects or structs section in the core manual. In my opinion, and I could be approaching this from the wrong angle, when newcomers start using Julia, they may be looking for the OOP equivalent to what they did in their previous language and we might be doing them a disservice by not addressing this clearly in the docs.

**Comment by fredrikekre** [comment]
There is https://docs.julialang.org/en/v1/manual/types/ which is just before?

**Comment by logankilpatrick** [comment]
When I think of types, I think of int, float, string, char, etc. and not of structs/objects but this could just be my own bad practices

**Comment by KristofferC** [comment]
Yeah, that seems like a bad practice.

See e.g. https://docs.julialang.org/en/v1/manual/types/#Composite-Types-1.

I am also a bit confused about this issue because there is extensive documentation about different types/objects before the constructors so not sure what is to be done here.

**Comment by StefanKarpinski** [comment]
To explain the thinking when I organized the sections this way. In order to understand constructors, you need to know about types—since that's what constructors construct—and methods—since constructors are a special kind of method. You also need to know about types in order to understand methods since you need types types to express method dispatch. That leaves only one possible order for the sections: types, methods, constructors. Each one is a pretty substantial chunk of material even when I wrote the original manual, let alone now, so I don't think any of these can be reasonably combined. They are heavily cross-linked so that if you're reading any one, you know that that's important related material in the other sections.

**Comment by KristofferC** [comment]
Closing since this seems to just have been a misunderstanding of what a type is.

**Comment by StefanKarpinski** [comment]
@logankilpatrick, perhaps an FAQ entry about objects would be helpful? All values in Julia are objects, every value has a type, and all types can have methods defined for them, which apply to objects of that type. It's hard to contrast this in a meaningful way with a generic notion of object orientation because the latter is so ill-defined, but it could be contrasted with specific OOP languages that people may be familiar with (Python, C++, Java).

**Comment by logankilpatrick** [comment]
Yeah that would probably due the trick! Something related to OOP such that if someone comes over to Julia from an OOP language and searches OOP or the like they will find an entry about it in the docs
