### ISSUE TITLE
Diagonal(Symmetric(Diagonal(v))) converts to sparse vector

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#35314]
```
julia> v = randn(5);

julia> m = Diagonal(Symmetric(Diagonal(v)));

julia> m.diag
5-element SparseArrays.SparseVector{Float64,Int64} with 5 stored entries:
  [1]  =  0.385226
  [2]  =  0.204826
  [3]  =  -0.595964
  [4]  =  0.0489207
  [5]  =  -1.37892
```

What happened here? It seems to me that `m.diag` should be able to just reuse the original `v`, right?

**Comment by dkarrasch** [comment]
I think the `Symmetric(Diagonal(v))` should simply return the `Diagonal(v)`, because `issymmetric(Diagonal(v)) == true`.

**Comment by cossio** [comment]
> I think the Symmetric(Diagonal(v)) should simply return the Diagonal(v), because issymmetric(Diagonal(v)) == true.

I think this would be problematic, because `Diagonal <: Symmetric` is not true. Therefore if you define a method taking symmetric matrices, it won't be able to handle `Symmetric(Diagonal(v))` if it just returns `Diagonal(v)`.

**Comment by dkarrasch** [comment]
True. I think I wanted to avoid writing overly specialized-looking methods like
```julia
Diagonal(S::Symmetric{<:Any,<:Diagonal}) = Diagonal(S.data.diag)
```
because then we would need that for every non-trivial wrapper of `Diagonal`.

**Comment by cossio** [comment]
> ```julia
> Diagonal(S::Symmetric{<:Any,<:Diagonal}) = Diagonal(S.data.diag)
> ```

This is the only solution I see.

**Comment by cossio** [comment]
By the way, same thing happens with `Hermitian`,

```
julia> m = Diagonal(Hermitian(Diagonal(v)))
# 5×5 Diagonal{Float64,SparseArrays.SparseVector{Float64,Int64}}
```

However `Diagonal(Bidiagonal(Diagonal(v)))` works (it just returns the `Diagonal(v)`). It has a special-cased constructor implemented. Whereas for `Symmetric` and `Hermitian` in the examples above, it is falling back to a generic constructor `Diagonal(A::AbstractMatrix) = Diagonal(diag(A))`.

**Comment by fredrikekre** [comment]
> m = Diagonal(Symmetric(Diagonal(v)));

Why not just use `m = Diagonal(v)` here? I don't think a good approach is to play the whack-a-mole game and add methods like that, there is a combinatorial explosion of methods we have to add in that case.

**Comment by andreasnoack** [comment]
Before just adding these very special methods, I think we should look into why the result is sparse in the first place. So `diag` is just https://github.com/JuliaLang/julia/blob/105ed11b305b3208e37cf48f21812ef1e187d6f5/stdlib/LinearAlgebra/src/dense.jl#L246

where `diagind` returns a `StepRange`. The index operation ends up calling `similar(::Symmetric, (Base.OneTo(n),))` which recurs to https://github.com/JuliaLang/julia/blob/105ed11b305b3208e37cf48f21812ef1e187d6f5/stdlib/SparseArrays/src/SparseArrays.jl#L51 which returns a `SparseVector`.

Maybe we want to reconsider some of these methods. Maybe the easiest fix is just to define
```julia
diag(A::Symmetric) = diag(parent(A))
```
because there already is a `diag(::Diagonal)` method.
