### ISSUE TITLE
rooting of negative number

### ISSUE THREAD

**Issue by AsForMe** [JuliaLang/julia#35358]
Errors happen when try rooting of negative number

julia> (-3)^(1/3)
ERROR: DomainError with -3.0:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
Stacktrace:
 [1] throw_exp_domainerror(::Float64) at .\math.jl:36
 [2] ^ at .\math.jl:849 [inlined]
 [3] ^(::Int64, ::Float64) at .\promotion.jl:343
 [4] top-level scope at REPL[13]:1

Although functions can be written to fix it, like
julia> Rooting(x,t) = sign(x)*abs(x)^t
Rooting (generic function with 1 method)

julia> Rooting(-2,1/3)
-1.2599210498948732

can it be fixed?

**Comment by yuyichao** [comment]
`Rooting` is not the correct definition so this cannot be fixed. You can find the correct result by following the error message. This particular case is also partially because the result if `1/3` isn't mathematically exact, you can get the real one with `cbrt`

Please ask any further question on discourse.
