### ISSUE TITLE
should define`NamedTuple{(),Tuple{}}()` so it === `NamedTuple()`

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#35411]
I expected `NamedTuple{(),Tuple{}}()` to be a (verbose) way to construct an empty `NamedTuple`.

```julia

julia> NamedTuple()
NamedTuple()

julia> typeof(NamedTuple())
NamedTuple{(),Tuple{}}

julia> NamedTuple{(),Tuple{}}
NamedTuple{(),Tuple{}}

julia> NamedTuple{(),Tuple{}}()
ERROR: MethodError: no method matching NamedTuple{(),Tuple{}}()
Closest candidates are:
  NamedTuple{(),Tuple{}}(::T) where {names, T<:Tuple} at boot.jl:550
  NamedTuple{(),Tuple{}}(::Tuple) where {names, T<:Tuple} at namedtuple.jl:67
  NamedTuple{(),Tuple{}}(::Any) where {names, T<:Tuple} at namedtuple.jl:85
Stacktrace:
 [1] top-level scope at REPL[5]:1

julia> NamedTuple{(),Tuple{}}(:bogus)
NamedTuple()
```

**Comment by Jollywatt** [comment]
Note that if you pass any iterable as an argument, this does work as expected.
```
julia> NamedTuple{(),Tuple{}}([])
NamedTuple()
```
This is consistent with `NamedTuple`s of more than zero length:
```
julia> NamedTuple{(:a,:b),Tuple{Char,Bool}}(['a', true])
(a = 'a', b = true)
```

**Comment by JeffBezanson** [comment]
Correct; there is supposed to be one iterable argument to the constructor. Before `(;)` created an empty named tuple, we added this definition:
```
NamedTuple() = NamedTuple{(),Tuple{}}(())
```
just for convenience since otherwise the syntax is absurd. We don't really need it anymore I suppose.

`NamedTuple{(),Tuple{}}(:bogus)` unfortunately works since we don't have a way to restrict the argument to iterables, and it doesn't try to take any values. `Tuple{}(:x)` also works for the same reason.
I'm not sure there's anything to do here.
