### ISSUE TITLE
Enhancement request: isempty(::Nothing) = true

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#35438]
What breaks if we implement `isempty` for `Nothing`?

(Does it make sense to implement `iterate` for `Nothing`?)

```

julia> a = nothing
julia> isempty(a)
ERROR: MethodError: no method matching iterate(::Nothing)
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:600
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:600
  iterate(::ExponentialBackOff) at error.jl:218
  ...
Stacktrace:
 [1] isempty(::Nothing) at ./essentials.jl:736
 [2] top-level scope at REPL[2]:1
```

**Comment by KristofferC** [comment]
What's the justification? To me, this looks like a random type and a random function with a random return value. Asking "what breaks" isn't really useful because it means that pretty anything that used to be an error can be made to have an arbitrary implementation.

**Comment by sbromberger** [comment]
We've run into a situation where we can expect a union of `{Vector{Int}, Nothing}` and it would be nicer to be able to check whether any data is returned in one go. `length()` and `isempty` aren't defined for `Nothing`. We've defined `isempty` for scalars (`= false`) so I don't think it's too outlandish a request and it makes testing unions of collections and `Nothing`, which seem to be increasingly common, easier.

**Comment by KristofferC** [comment]
> able to check whether any data is returned in one go

So just do it? `x === nothing ? false : isempty(x)`? Just because you have a case where `nothing` means that there is no data doesn't mean that is the same in other peoples code. You can't really standardize your particular choice of what `nothing` means in your codebase for a function in general. It's just a choice.

> We've defined isempty for scalars (= false) so I don't think it's too outlandish a request and it makes testing unions of collections and Nothing, which seem to be increasingly common, easier.

This is a consequence of numbers being iterable which there has been a lot of discussion about (https://github.com/JuliaLang/julia/issues/7903). 

> We've run into a situation where we can expect one of {Vector{Int}, Nothing} and it would be nicer to be able to check whether any data is returned in one go

But you can have a `Union{T, Nothing}` for any `T` so with a similar argument it would be nicer to be able to call any function on `Nothing` and get something (what?) back.
The reason you tend to use a union with `Nothing` is because the `nothing` means something different than the value. But what it means is just a convention where it is used needs to be explicitly coded at the point where it is used.

**Comment by sbromberger** [comment]
The convention surrounding `nothing` [is explicit](https://docs.julialang.org/en/v1/base/constants/#Core.nothing), though. I would argue that that convention implies that `isempty(nothing)` should be `true`.

**Comment by jakobnissen** [comment]
I must echo Kristoffer in that this seems like an implementation detail of your particular system that you advocate leak into `Base`. The *meaning* of `isempty` is to test whether a collection of items is empty, and `nothing` is not a collection of items. I think it makes no sense.

If you interpret `nothing` to semantically mean something like the empty set, then this opens a Pandora's box of what `nothing` actually is. For example, does it make sense to define `Base.:+(x, ::Nothing) = x`?
 
Furthermore, in your case, the alternative (namely `x === nothing ? true : isempty(x)`) is a simple one-liner, and is optimally efficient.

**Comment by sbromberger** [comment]
I guess since there's a reasonable way to do this it doesn't merit further discussion. Thanks for the input.

**Comment by fredrikekre** [comment]
ref #26350

**Comment by KristofferC** [comment]
(that's `Missing` though)
