### ISSUE TITLE
Spurious `failed to compute relocation: R_PPC64_REL64` in `jl_DI_for_fptr`

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#35460]
Reproducer: https://gist.github.com/vchuravy/1e7b4d9fcca2f5faa0e1cd28480f6e54

Manifests itself as a scary:

```
  | | |_| | | | (_| |  |  Version 1.5.0-DEV.622 (2020-04-13)
 _/ |\__'_|_|_|\__'_|  |  vc/ppc_llvm9/88c5699df8 (fork: 1 commits, 0 days)
|__/                   |

julia> error()
ERROR: error: failed to compute relocation: R_PPC64_REL64, Invalid data was encountered while parsing the file
error: failed to compute relocation: R_PPC64_REL64, Invalid data was encountered while parsing the file
error: failed to compute relocation: R_PPC64_REL64, Invalid data was encountered while parsing the file
```

I think those were introduced in 4363c55052e (cc: @vtjnash)  since they are originating from https://github.com/llvm/llvm-project/blob/bb0e6cc1dd13997e59f3178e27b57f54c11f7f89/llvm/lib/DebugInfo/DWARF/DWARFContext.cpp#L1798-L1804

x-ref: https://github.com/llvm/llvm-project/blob/e0fd87cc64d5102f20219b6bad0e337dc4e6b2d2/llvm/lib/Object/RelocationResolver.cpp#L130-L138

cc: @shirodkara

**Comment by vtjnash** [comment]
Like the commit message said, I had to change that because LLVM added assertions to prevent us from using the better fast path.

**Comment by yuyichao** [comment]
https://reviews.llvm.org/D83800 (I'll leave the honor of carrying this patch to someone else since I'm too lazy to track down all the places that needs to be updated, outside this repo...)

So after spending an hour trying to come up with a test case I realized that this case is not actually used in llvm-dwarfdump and seems also not in any other cli tools... So it would have been find if llvm was lazier......

**Comment by vchuravy** [comment]
Yeah I can add it to https://github.com/JuliaPackaging/Yggdrasil/pull/1301

**Comment by yuyichao** [comment]
I can confirm that the issue on aarch64 is fixed for me with the patch.

**Comment by MaskRay** [comment]
You may need https://github.com/llvm/llvm-project/commit/e0fd87cc64d5102f20219b6bad0e337dc4e6b2d2

https://github.com/llvm/llvm-project/commit/b922004ea29d54534c4f09b9cfa655bf5f3360f0 added support for R_PPC_REL32 & R_PPC64_REL{32,64}

A larger issue is that llvm-dwarfdump on an object file does not do some linker job so that reasonable addresses are reported.

**Comment by vchuravy** [comment]
Thanks @MaskRay!
