### ISSUE TITLE
Scoping inside struct definition

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/julia#35498]
As mentioned on Slack, I think, it would be nice if the following worked:
```julia-repl
julia> struct A
           x
           unsafe_a(x) = new(x)
       end

julia> unsafe_a(8)
ERROR: UndefVarError: unsafe_a not defined
Stacktrace:
 [1] top-level scope at REPL[4]:1
```

It currently works like this, so I think the issue is that `unsafe_a` is defined only inside the scope of the struct expression:
```julia-repl
julia> function unsafe_a end
unsafe_a (generic function with 0 methods)

julia> struct A
           x
           Main.unsafe_a(x) = new(x)
       end

julia> unsafe_a(1)
A(1)
```
Is there a reason for this current behavior, or is this more of an oversight?

**Comment by JeffBezanson** [comment]
This is definitely intentional and documented.. Note you can also use `global unsafe_a(x) = new(x)` to define a global function within the block.

It's good for things to be local scopes in general. As it is, you try this and it doesn't work, so you add `global` and then it works. If we removed the local scope, but you mistakenly thought there was one, you would silently leak definitions without realizing it. It can also be useful for constructors to have local helper functions.
