### ISSUE TITLE
Missing BigInt functions

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/julia#3560]
Here's a quick list of some missing `BigInt` functionality:
- [x] `count_ones` (#3559)
- [ ] ~~`leading_ones`~~ (see #8256)
- [x] `base`, `bin`, `hex`, `dec`, `oct`
- [ ] ~~`bits`~~ (see #8256)

**Comment by RatanRSur** [comment]
Hi all, looking to contribute so I'm checking out the intro issues.

@daviddelaat , is `flipsign` still not implemented? Also, when I read `flipsign`, I understood it as a negation operation, but I'd be surprised if that wasn't already implemented. Is that what it is or am I misunderstanding?

**Comment by jakebolewski** [comment]
@RatanRSur a better place to start would be to make `BigInt <: Signed` (instead of `<: Integer`).  This will cause problems but `BigInt` should be able to work with `Signed` methods.  The next step would be to define the methods to fix the breakage this would cause.  I suspect almost all the missing methods would be addressed with this change.

**Comment by kshyatt** [comment]
`leading_ones` and `bits` are still missing.

**Comment by rfourquet** [comment]
cf. #8256 for some discussion on those.

**Comment by RatanRSur** [comment]
So, looking at that discussion, it seems like the consensus is that these don't make sense for BigInts?

**Comment by rfourquet** [comment]
`leading_ones` and `leading_zero` won't make sense for `BigInt`, and `flipsign` is implemented, so closing as no items remains.
