### ISSUE TITLE
sparse matrix vector product using much more memory than expected

### ISSUE THREAD

**Issue by lesshaste** [JuliaLang/julia#35931]
Consider the following test code:

```
using BitIntegers
using SparseArrays
using Random
Random.seed!(0)
function computeresults(M, iternum)
           v = ones(UInt256, size(M)[1])
           for i in 1:iternum
               v = M'*v
               println(v[1])
           end
       end
n=10^7
M = convert(SparseMatrixCSC{UInt32, UInt32}, round.(10*sprand( n, n,  4*1/n)))
computeresults(M, 10)
```

v uses 320MB of RAM and M uses 344MB according to Base.summarysize. However the peak RAM usage is over 3GB. E.g.

```
/usr/bin/time -f '%M' julia test.jl
[...]
3271812
```

Is Julia converting the entirety of M to UInt256? If so, is there some way to avoid this?  The alternative would be to convert on the fly which would use much less RAM.

**Comment by lesshaste** [comment]
A simpler test case:

```
using BitIntegers
using SparseArrays
using Random
Random.seed!(0)
n=10^7
M = convert(SparseMatrixCSC{UInt32, UInt32}, round.(10*sprand( n, n,  4*1/n)))
v = ones(UInt256, size(M)[1])
v = M*v
```

This gives a similar RAM usage figure.

```
/usr/bin/time -f '%M' julia test.jl
3188192
```

I tried  @code_warn v = M*v which gives:

```
@code_warntype M*v
Variables
  #self#::Core.Compiler.Const(*, false)
  A::SparseMatrixCSC{UInt32,UInt32}
  x::Array{UInt256,1}
  T::Type{UInt256}

Body::Array{UInt256,1}
1 ─      (T = SparseArrays.promote_op(SparseArrays.matprod, $(Expr(:static_parameter, 1)), $(Expr(:static_parameter, 2))))
│   %2 = T::Core.Compiler.Const(UInt256, false)::Core.Compiler.Const(UInt256, false)
│   %3 = SparseArrays.size(A, 1)::Int64
│   %4 = SparseArrays.similar(x, %2, %3)::Array{UInt256,1}
│   %5 = SparseArrays.mul!(%4, A, x, true, false)::Array{UInt256,1}
└──      return %5
```

**Comment by dkarrasch** [comment]
According to `@which M*v` this method gets called
```julia
.../v1.4/SparseArrays/src/linalg.jl:29
```
There, you find that the `UInt256` "conversion" is done only for the output vector of `mul!`. Neither `M` nor `v` are implicitly converted. Benchmarking suggests that there is allocation of
```julia
julia> @btime $M * $v;
  1.999 s (2 allocations: 305.18 MiB)
```
Could it be that you're measuring some compilation overhead?

**Comment by lesshaste** [comment]
I thought of that but it seems not to be the case. Try changing n = 10^7 to n=10^6. I get:

> 493864 kilobytes

instead of over 3GB for n = 10^7. There is some huge overhead associated with the size of the matrix which I don't understand.

**Comment by dkarrasch** [comment]
I'm not sure I can follow. What are you measuring? The allocations of the entire script? For `n=10^6`, I get
```julia
julia> @btime $M * $v;
  107.518 ms (2 allocations: 30.52 MiB)
```
so one tenth of the allocations for `n=10^7`, as expected. Note that `v = M*v` is not in-place of `v`.

**Comment by lesshaste** [comment]
My main motivation is simply to be able to do a matrix vector product with larger matrices that look like they should fit in memory. I find that I can't currently as they die with an out of memory error.  

I am measuring the "Maximum resident set size of the process during its lifetime, in Kilobytes.". This includes all the overheads of running Julia.  However these overheads are actually not very large as we can see by reducing the value of `n`.  You can also see how much RAM is being used by just running top and it broadly agrees with /usr/bin/time -f.

**Comment by dkarrasch** [comment]
Ok, I'm not familiar with these types of memory usage measurements. What happens if, in your script, you do the compilation with much smaller, dummy matrices, and only then do the computation on the larger ones?

**Comment by lesshaste** [comment]
> Ok, I'm not familiar with these types of memory usage measurements. What happens if, in your script, you do the compilation with much smaller, dummy matrices, and only then do the computation on the larger ones?

That sound interesting. How can I do that? 

As an experiment I just tried it with n = 10^8 on my 8GB machine. It should fit I believe but it kills the computer.

**Comment by dkarrasch** [comment]
> That sound interesting. How can I do that?

I'd suggest to first run the relevant lines with a small `n`, like
```julia
n = 10
M = convert(SparseMatrixCSC{UInt32, UInt32}, round.(10*sprand( n, n,  4*1/n)))
v = ones(UInt256, size(M)[1])
M*v
n = 10^8
M = convert(SparseMatrixCSC{UInt32, UInt32}, round.(10*sprand( n, n,  4*1/n)))
v = ones(UInt256, size(M)[1])
v = M*v
```
In your OP, this would mean calling `computeresults` with the small `M`. The rhs in the last line allocates a new vector, to which `v` then is redirected. Since you're working in a script, the "old" `v` is presumably not garbage collected, so you will have at least the old `v`, the new `v` and `M` in memory.

**Comment by lesshaste** [comment]
Hmm.. well I just did this:

```
n=10^7
@time M = convert(SparseMatrixCSC{UInt32, UInt32}, round.(10*sprand( n, n,  4*1/n)))
```

I get:

>  4.136528 seconds (1.34 M allocations: 2.398 GiB, 5.78% gc time)


That seems to be the problem on its own without the product.

**Comment by dkarrasch** [comment]
Likely. Now that you point to it. First, `sprand( n, n,  4*1/n)` is allocating a sparse, `Float64`-valued matrix. Then, `10*...` allocates yet another one, because you don't multiply in-place. I guess `round.(...)` actually operates in-place, so doesn't allocate. But then, the `convert(SparseMatrixCSC{UInt32, UInt32}, ...)` allocates another vector of non-zero values *and* another vector of rowvalues, because you convert both to the new type `UInt32`.

I guess this is not a multiplication issue then?

**Comment by mbauman** [comment]
Your final output is a sparse array with 38 million `UInt32` entries.  Alone, it will take:

* 38*4 = 150MB for the values
* 38*4 = 150MB for the row indices
* 10*4 = 40MB for the column indices
* total = 340MB.

BUT: that's not all you have here.  To create that array you first create a sparse matrix with Float64 values and Int64 indices (with `sprand`) — so that'll take 2x as much space.  There's your first 680MB.  You then multiply that matrix by 10.  There's another 680MB.  You then round it.  There's another 680MB.  You then convert it to `UInt32`.  There's the final 340MB.

3*680+340 = 2.38GB.

**Comment by mbauman** [comment]
This is totally fixable, but the discussion would be best continued at https://discourse.julialang.org

**Comment by lesshaste** [comment]
Thank you. I had expected all of these things to be in-place.
