### ISSUE TITLE
iterate is inconsistent with Int and Float64 ranges

### ISSUE THREAD

**Issue by rafaqz** [JuliaLang/julia#35951]
This seems strange:

```julia

julia> iterate(5:1:15, 3)
(4, 4)

julia> iterate(5.0:1.0:15.0, 3)
(7.0, 4)
```

On Julia 1.4.1

**Comment by jakobnissen** [comment]
As far as I know, an iterator's state is considered an implementation detail, and not part of the API as such.

You are of course right that it would be *nicer* if the internal implementations were also the same. As far as I can tell, there are good reasons for the different implementations here:

* Having the state be the actual output number (minus one) for an `OrdinalRange` makes it optimally efficient, since each iteration only has to compute `next = state + step(it)`
* This iterative computation would accumulate floating point errors for float ranges, so therefore each element should be obtained using `getindex` instead. This is less efficient, but keeps float errors to around one machine epsilon, and so is preferred for float values.

**Comment by rafaqz** [comment]
That sounds right, thanks for the explanation.
