### ISSUE TITLE
pop! is not defined for Iterators.Pairs

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#35985]
Please see [this discourse post
](https://discourse.julialang.org/t/pop-doesnt-work-with-iterator-pairs/39786)

The issue may be condensed to 

```julia
julia> f(;kwargs...) = kwargs
f (generic function with 1 method)

julia> y = f(x=3)
pairs(::NamedTuple) with 1 entry:
  :x => 3

julia> pop!(y, :x, nothing)
ERROR: MethodError: no method matching pop!(::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:x,),Tuple{Int64}}}, ::Symbol, ::Nothing)
Closest candidates are:
  pop!(::IdDict{K,V}, ::Any, ::Any) where {K, V} at abstractdict.jl:608
  pop!(::Base.IdSet, ::Any, ::Any) at abstractdict.jl:694
  pop!(::Dict, ::Any, ::Any) at dict.jl:608
  ...
Stacktrace:
 [1] top-level scope at REPL[7]:1
```

`Iterators.Pairs` is a subtype of `AbstractDict` so one might expect to be able to `pop!` keys from it. A current workaround is to convert the `Pairs` to a `Dict` before applying `pop!` to it.

**Comment by mbaz** [comment]
I'll add that `get!` and `delete!` are not implemented either.

**Comment by JeffBezanson** [comment]
`kwargs` is immutable.

**Comment by vtjnash** [comment]
And we have defined `Base.tail`

**Comment by mbaz** [comment]
@JeffBezanson Fair enough. Even though it seems unnecessarily restrictive from my perspective, I assume there are good reasons for making it so. I have submitted a pull request to document this.

**Comment by StefanKarpinski** [comment]
The bang at the end of `pop!` implies mutation but since kwargs is immutable, you can't pop it. Or are you talking about it being unnecessarily restrictive that kwargs is immutable in the first place?

**Comment by JeffBezanson** [comment]
Yes there are good reasons for it. Mostly performance; because of that keyword arguments often have zero overhead. It is pretty easy to construct a new named tuple that has an element added, changed, or removed, so mutation wouldn't add much. We could add a non-mutating `pop` that returns the removed element and a new named tuple though.

**Comment by mbaz** [comment]
@StefanKarpinski The bang didn't help me, because I didn't know that `kwargs` is immutable (I submitted a PR with that tidbit of information here https://github.com/JuliaLang/julia/pull/35998)

What I meant is that I thought `kwargs` being immutable was unnecessarily restrictive. However, @JeffBezanson has kindly explained the reasons why, which make a lot of sense (of course).

My solution, which is to do `x = Dict(kwargs)`, is simple enough. I don't think a non-mutating `pop` is necessary.
