### ISSUE TITLE
Type is not equal to itself

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#36100]
On 1.5

```
julia> NamedTuple{(:a, :b), Tuple{Missing, Union{}}} == 
       NamedTuple{(:a, :b), Tuple{Missing, Union{}}}
false
```

(works in 1.4). From test failure in PkgEval (https://github.com/JuliaCI/NanosoldierReports/blob/90885ffd4005a91d0dc4150b8c1453f2f5948eb0/pkgeval/by_hash/194ddda_vs_b5f13c3/logs/FunctionalTables/1.5.0-DEV-f11a73bd9c.log).

**Comment by JeffBezanson** [comment]
Bisect says c958b2ca77f9bd800073db22c97b946930e724b4

**Comment by vtjnash** [comment]
Curious. The hash computation seems to be working, so I'm not quite sure why we're failing to normalize this:
```julia
julia> A = Val{Tuple{Missing, Union{}}}
Val{Tuple{Missing,Union{}}}

julia> B = Val{Tuple{Missing, Union{}}}
Val{Tuple{Missing,Union{}}}

julia> A === B
false

julia> Tuple{Missing, Union{}}.hash
-302523448
```

**Comment by martinholters** [comment]
`Tuple{Union{}}` is not cached:
```julia
julia> T1 = Tuple{Union{}}
Tuple{Union{}}

julia> T2 = Tuple{Union{}}
Tuple{Union{}}

julia> pointer_from_objref(T1)
Ptr{Nothing} @0x00007fb946a38850

julia> pointer_from_objref(T2)
Ptr{Nothing} @0x00007fb946e66a10
```
But
```julia
julia> T1.isconcretetype
true
```
so
https://github.com/JuliaLang/julia/blob/f65561f88386a691da11b3c53d25f8cf7a6a248c/src/jltypes.c#L566-L567
triggers and declares `Tuple{Union{}}` not equal to the parameter of `Val{Tuple{Union{}}} `. I think this not the only place where we assume that a type is cached iff it is concrete, so I guess the problem is that `Tuple{Union{}}` is not cached? Or should `isconcretetype` by `false` here? After all, `Tuple{Union{}}` cannot have instances. Or should the condition here exclude `Tuple`s with `Union{}` elements explicitly as an exception to the rule?

**Comment by martinholters** [comment]
This fixes it:
```diff
diff --git a/src/jltypes.c b/src/jltypes.c
index 845936ed10..f0b6fc17a3 100644
--- a/src/jltypes.c
+++ b/src/jltypes.c
@@ -1492,7 +1492,7 @@ static jl_tupletype_t *jl_apply_tuple_type_v_(jl_value_t **p, size_t np, jl_svec
     int cacheable = 1;
     for (size_t i = 0; i < np; i++) {
         assert(p[i]);
-        if (!jl_is_concrete_type(p[i]))
+        if (!jl_is_concrete_type(p[i]) && p[i] != jl_bottom_type)
             cacheable = 0;
     }
     return (jl_datatype_t*)inst_datatype_inner(jl_anytuple_type, params, p, np, cacheable, NULL, NULL);
```
Does that make sense, @vtjnash? Then I can open a PR.

**Comment by vtjnash** [comment]
> After all, Tuple{Union{}} cannot have instances.

Neither can `Some{Union{}}`, but they're also concrete for the same reason that `Some{T} where T<:Union{}` becomes concrete, because that TypeVar became degenerate

**Comment by JeffBezanson** [comment]
Yes, PR it. :heart:
