### ISSUE TITLE
x86_64 binaries for Linux are not compatible with old Intel CPU

### ISSUE THREAD

**Issue by xianwenchen** [JuliaLang/julia#36306]
The x86_64 binaries for Linux are probably built with march that is not x86-64. As a consequence, CPU instructions that are not supported by old Intel x86_64 CPUs are produced.

The binaries are not able to run on an x86-64 Linux system with an Intel Pentium 4 Prescott HT630 CPU, for example. The GCC march for that CPU is nocona. Could you double check what march is set to compile LLVM and consequently Julia, which produced the x86_64 binaries for Linux?

This bug also affects packages that download libraries (such as gdal), when these libraries are compiled with an march setting that is not x86-64.

I have been able to produce a working x86_64 binary of Julia by compiling Julia using march=x86-64 on the old Intel CPU. However, I do not know how to fix the ready compiled libraries that are downloaded from servers when adding packages.

**Comment by yuyichao** [comment]
Dup of https://github.com/JuliaLang/julia/issues/35215. Your analysis of the scope of the issue appears correct (that it affects other binary downloads). See also https://github.com/JuliaLang/julia/issues/34570#issuecomment-639273444 and I've been waiting for @staticfloat or other people that maintains the infrastructure to select and implement one of the many existing ways to fix this.

**Comment by xianwenchen** [comment]
Thank you.

This issue contained two part. The first part is a duplication of #35215.  

The second part regarding packages that use additional libraries, where the libraries' binaries are compiled with CPU flags that are not supported by old x86-64 CPUs. Is there an equivalent setting of USE_BINARYBUILDER=0 when adding packages to Julia?

**Comment by staticfloat** [comment]
No, there is not.  But once we get the right infrastructure in place to build packages with multiple microarchitectures, those packages will be usable from Julia 1.4 and 1.5.

**Comment by yuyichao** [comment]
> The second part regarding packages that use additional libraries, where the libraries' binaries are compiled with CPU flags that are not supported by old x86-64 CPUs. Is there an equivalent setting of USE_BINARYBUILDER=0 when adding packages to Julia?

Right, that's a different issue and in fact that's not even an julia issue, but an issue for packages that uses the binary builder compiled binaries (which are mostly jll packages I hope). (FWIW, that's why I don't like the JLL packages but since they are prpredictable enough, for my purpose, I simply override them...). The option has to be one for the package (since the package fully controls where it get its code from) and some package do allow you do use external/user-compiled binaries. If there's a single place to request such feature to be added it'll be the jll package generator.

**Comment by xianwenchen** [comment]
Thank you.

Then I shall wait to use the packages that are affected by this.

How would I know in the future when a newer version of Julia 1.4 or 1.5 is shipped with packages that are built with multiple microarchitectures? I didn't find information like what's new on https://julialang.org/downloads/

**Comment by yuyichao** [comment]
Julia does not ship with packages..... Maybe JuliaPro does? but that'll be a question for juliliacomputing.

**Comment by xianwenchen** [comment]
Maybe I am using wrong terminologies.

When installing a package on Julia on Linux, say GDAL, libraries that depend on GDAL are downloaded to ~/.julia/artifacts/. These libraries are precompiled with specific CPU flags. Some of the CPU flags are not supported by old CPUs. 

I wonder if there is a way to ask Julia to compile these libraries, so that CPU flags that fit the computer's CPU will be used. This will be a setting that is similar to USE_BINARYBUILDER=0, but for the libraries that a Julia package requires.

Does what I say make sense?

**Comment by yuyichao** [comment]
That's exactly what I was answering above.

It's not something under julia control (julia doesn't ship with GDAL or the artifacts that it uses). It's entirely up to the julia package to provide a similar option to disable binary builder usage and there's nothing that can be done in julia (this repo) to enforce that as long as we still support an arbitrary `deps/build.jl`. I do like a uniform option, but it's simply impossible.

Now if the package use a JLL package which was auto generated from a single source, you can file an issue to the script that generates the JLL package for such an option. Otherwise, again, it's every's package's own job. There are already packages that has such capability, e.g. HDF5.jl and more traditionally PyCall.jl and IJulia.jl, which never uses BinDeps.jl and never (needs to) migrated to the new system.

And the of course you specific issue can be fixed when the problematic changes on the binary builder is fixed and further change could improve on the pre-regression status. But requiring the user to download binaries is likely never going to be a full solution unless the maintainer of the julia package cares about as many set up as the maintainer of the corresponding binary libray.

**Comment by xianwenchen** [comment]
Thank you very much for your help! I will contact package maintainers!
