### ISSUE TITLE
PDF of the manual on master is not being updated

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#36363]
The PDF on docs.julialang.org is not being updated for the master branch. The html documentation is in in sync, but the PDF is from a few weeks back.

**Comment by ViralBShah** [comment]
It seems like the CI should be doing the right thing, but I can't quite figure out why it doesn't have the right thing:

https://travis-ci.org/github/JuliaLang/docs.julialang.org/jobs/700118166

**Comment by ViralBShah** [comment]
It seems that pushing the PDFs to the git repo has made that repo quite large. Should we instead put the generated PDF files to S3? The repo is now 1.1G.

**Comment by ViralBShah** [comment]
I think we need @staticfloat 's help here.

**Comment by mortenpi** [comment]
> It seems that pushing the PDFs to the git repo has made the docs.julialang.org repo quite large.

I am not 100% sure, but I think that's actually due to the HTML docs. If I remember correctly, when we moved the the `gh-pages` away from this repo, it was already nearing something like 300-500MiB, just due to all the history of the HTML docs.

With the PDFs we actually explicitly avoid storing the history in the repository. The `make.jl` script there always force-pushes to the `assets/` branch so it always just contains a single commit with just the latest PDFs. Theoretically, this should avoid the repository size blowing up due to the PDFs.

**Comment by ViralBShah** [comment]
We could also upload the PDF to S3

**Comment by mortenpi** [comment]
> We could also upload the PDF to S3

Did you mean the HTML?

Would it actually give us anything though? The `docs.julialang.org` repository is not really meant to be cloned, so its size shouldn't really bother anyone. And it has the added bonus that you can easily access the "filesystem" (i.e. `gh-pages` and `assets` branches) for debugging.

**Comment by ViralBShah** [comment]
Fair enough.

**Comment by mortenpi** [comment]
This should be fixed by JuliaLang/docs.julialang.org#19, so could be closed.

The 1.6-DEV has updated itself: https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.6.0-DEV.pdf
