### ISSUE TITLE
Start Julia with 2 threads by default

### ISSUE THREAD

**Issue by tknopp** [JuliaLang/julia#36457]
I am coming from #16134, which would be the ultimate solution (i.e. allow package authors to add threads, if they are required for a program to not deadlock).

In the meantime I would like a propose a quick workaround: We could by default startup Julia with 2 threads. I do not really see a disadvantage to this, since we use multiple threads for BLAS anyway. So there is currently no guarantee to use a single thread anyway.

**Comment by vchuravy** [comment]
> allow package authors to add threads, if they are required for a program to not deadlock

That should never be allowed to happen. A program should be executable with how ever many threads are available. This is the reason why tasks are the programming abstractions and not threads.

**Comment by tknopp** [comment]
Then please explain to me, how to solve the following: I write a UI with Gtk, where a callback is called when a certain button is clicked. The callback performs an SVD that lasts 5 minutes. How can I prevent freezing the UI on a single thread with the task abstraction?

**Comment by vchuravy** [comment]
That is not a deadlock.

I understand the issue, and I know that it is frustrating, In a non-preemptive task parallel system you can easily end up with unfair scheduling, but just increasing the number of worker threads does not solve this issue, since as soon as your SVD implementation actually uses Julia task system it can easily oversubscribe the system again and you will see the same stuttering.

An answer to this problem right now (and it is not ideal) is to separate the program into two processes that communicate with RPCs. The operating system can implement a roughly fair scheduling, and arbitrary code will not cause hangs in your UI.

**Comment by tknopp** [comment]
My example was of course a little bit simplified. My application is much larger and there is communication between the background thread and the foreground thread. In that case it is indeed possible that the program can deadlock. My aim here really is to keep the first thread clean from any computation. And currently I cannot do this on a package level.

**Comment by tknopp** [comment]
And maybe another example. The package `ThreadPools` allows to keep the first thread free from computation. Lets see what happens if that packages is run with julia by default:
```
julia> using ThreadPools

julia> @bthreads for i=1:1; @show Threads.threadid() end
Threads.threadid() = 1
```
Currently the package can either do this or give an error. If we increase the number of threads to two, the default experience for that package is significantly improved. Ideally #16134 is implemented and `ThreadPools` has control about the thread pool size. In the mean time it could enhance the threading experience while the implementation of the present issue should be pretty straight forward.

**Comment by vtjnash** [comment]
We should add the ability to add threads, but, as Valentin points out, this issue proposal wouldn't solve anything.
