### ISSUE TITLE
range(π, stop = π, length = 1) cannot be collected

### ISSUE THREAD

**Issue by pablosanjose** [JuliaLang/julia#36695]
```
julia> collect(range(π, stop=π, length=1))
ERROR: MethodError: no method matching Irrational{:π}(::Float64)
...
```

The problem seems to be that `range(π, stop=π, length=1) isa LinRange{Irrational{:π}}`, which, when `iterate`d, causes a call to `T(::Float64)` with `T===Irrational{:π}` in `unsage_getindex` here:
https://github.com/JuliaLang/julia/blob/353e1296ae3927eef07a5476554fb641dd1a287c/base/range.jl#L689

Not sure what the correct fix would be

**Comment by JeffBezanson** [comment]
I'm not sure this needs to work.

**Comment by pablosanjose** [comment]
Care to elaborate? `collect(range(π, stop=2π, length=2))` and `collect(range(1, stop=1, length=1))` do work. Isn't the current behavior surprising?

**Comment by JeffBezanson** [comment]
`2π` is a Float64, not an Irrational. `Irrational` can't support all operations, and that's just a tradeoff we have accepted. I guess we could special-case the first element to return the start point instead of doing arithmetic, but it doesn't seem worth it just to allow 1-element ranges of Irrationals.

**Comment by pablosanjose** [comment]
I see, thanks for the explanation! There seems to be a powerful consensus here, so closing.

**Comment by thchr** [comment]
I hit this just now and found this issue. I wanted to note that it's not just that 1-element ranges of irrationals are problematic - it's problematic for ranges of any length with start & end point equal to the *same* irrational.
So, this doesn't work:
```jl
range(π, π, length=10)
```
but any of these seemingly similar constructions *do* work:
```jl
range(π, ℯ, length=10)
range(0, π, length=10)
```
The error message is also not particularly clear I'd say:
```jl
ERROR: MethodError: no method matching Irrational{:π}(::Float64)
```
The fix is of course simple (just wrap any of the `Irrational`s in a `float(...)` call) but still a bit of a trip-up for newcomers I'd imagine.
