### ISSUE TITLE
Make @ccall documentation appear in manual.

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/julia#36775]
@ninjaaron added `@ccall` in PR #32748, including documentation for it in the form of docstrings.

However, searching for `@ccall` on https://docs.julialang.org/en/v1.6-dev/ does not produce any useful hits. I also tried finding it in there by browsing, but failed to find it. Perhaps something needs to be tweaked to actually make `@ccall` appear in the manual?

**Comment by ninjaaron** [comment]
I've been thinking about this also. There was some talk that `@ccall` should be considered the "default" approach (or maybe that was just my delusion; can't remember), which would involve some pretty thoroughgoing rewrites, which is why I didn't make a PR about. However, maybe I should put some minimal documentation in the manual so there is *something* there and to get the discussion going about how much the existing documentation using `ccall` should be rewritten, if indeed it should be at all.

**Comment by rfourquet** [comment]
As version 1.5 will be released very soon, before we have a chance to update thoroughly the manual, I think it would be good to have at least the docstring of the macro included somewhere in the manual for 1.5. I will tentatively add the 1.5 milestone to this issue.

**Comment by ninjaaron** [comment]
There's actually an error in the docstring as well! I noticed it yesterday as I was finishing up my lighting talk on the macro! (the example with `sprintf` doesn't have an initial `char *` argument, which is the buffer where the formatted string is supposed to go!). This could be fixed by simply changing it to `printf`.

**Comment by JeffBezanson** [comment]
This should be listed in doc/src/base/c.md.
