### ISSUE TITLE
Allow custom return type for `tryparse`

### ISSUE THREAD

**Issue by pdeffebach** [JuliaLang/julia#37162]
Being able to return something specific after `tryparse` might be useful. See [this discource pose](https://discourse.julialang.org/t/dealing-with-missing-values-in-dataframe-again/45373) for motivation. 

currently you can do 

```
something(tryparse(Float64, "BBB"), missing)
```

Would be nice if you could do 

```
tryparse(Float64, "BBB", missing)
```

However this would be a feature unique to Julia, I think. R, at least does not allow this for either `as.numeric` or `readr::parse_number`.

**Comment by fredrikekre** [comment]
I don't like this API. Quite a number of functions return `nothing` and leaves it to the caller to handle that case, for example the `find*`-family of functions. Should every such function support a different sentinel value?
Also, from the example in #37162: `tryparse(Float64, "BBB", missing)` is barely shorter than `something(tryparse(Float64, "BBB"), missing)`. And IMO the `something(...)` way is more clear since  `tryparse(Float64, "1.0", missing)` could potentially be interpreted as returning `(1.0, nothing)`.

**Comment by mkitti** [comment]
Per https://github.com/JuliaLang/julia/pull/37170#issuecomment-961367313 , just use `something(tryparse(...), ...)`.
