### ISSUE TITLE
Julia doesn't like Pizza

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#3721]
```
julia> x = '\U1f355'
'\U1f355'

julia> charwidth(x)
0
```

**Comment by stevengj** [comment]
utf8proc now includes an up-to-date `utf8proc_charwidth` function based on @jiahao's analysis (JuliaLang/utf8proc#27), so we can fix this issue by upgrading to the latest utf8proc and using this function instead of `wcwidth`.

**Comment by tkelman** [comment]
We should probably turn the name back to utf8proc here. I'd also slightly prefer going back to using a tarball for it (once 1.2.0 is tagged) rather than a submodule.

**Comment by nalimilan** [comment]
+1

**Comment by stevengj** [comment]
I slightly prefer submodule, since the tarballs tend to leave a bunch of old versions littering the `deps/` directory when the version is upgraded.  Submodules are also somewhat more flexible, since we can link a pre-release version if there is an urgent need (e.g. a bugfix).

**Comment by tkelman** [comment]
Submodules tend to confuse newcomers when versions are upgraded, introducing confusing diffs after they `git pull` when we change the submodule. It's also a bit messier for packagers who want to use system versions. It should be possible to set `UTF8PROC_VERSION` to a non-release sha for testing, and github should just make the right tarball for us. Either way though.

**Comment by jakebolewski** [comment]
This is not quite fixed, the display of `charwidth == 2` characters is still off.
![screen shot 2015-03-30 at 9 31 29 pm](https://cloud.githubusercontent.com/assets/1157798/6910674/5576497c-d724-11e4-853f-b9c1cb99e7df.png)

**Comment by jakebolewski** [comment]
Unicode tab completion also is still a bit wonky, this is what it looks like for me entering theta (which is `charwidth == 1`.

![screen shot 2015-03-30 at 9 35 31 pm](https://cloud.githubusercontent.com/assets/1157798/6910729/0364679e-d725-11e4-8190-f9807eaeb900.png)

![screen shot 2015-03-30 at 9 35 44 pm](https://cloud.githubusercontent.com/assets/1157798/6910730/06c93e96-d725-11e4-8462-1554f4521dfb.png)

![screen shot 2015-03-30 at 9 35 59 pm](https://cloud.githubusercontent.com/assets/1157798/6910732/0a0193ec-d725-11e4-956e-3e11c8f8d60c.png)

![screen shot 2015-03-30 at 9 36 12 pm](https://cloud.githubusercontent.com/assets/1157798/6910733/0d6d309a-d725-11e4-87c1-63602eb9464c.png)

**Comment by stevengj** [comment]
It looks like there is something in the `LineEdit` code that is using the length in codepoints rather than the `strwidth`.   For example, `strwidth("🐨") == 2` ([U+1f428](http://www.fileformat.info/info/unicode/char/1f428/index.htm)), but if I type `🐨 abcd` and then hit Ctrl-A to go back to the beginning of the line, then the formatting suddenly shifts to squish the koala under the `a`.

**Comment by JeffBezanson** [comment]
I'm not sure we/LineEdit can do anything about this --- if the terminal or some other system component had incorrect character widths, wouldn't these kinds of problems persist? We don't control the actual display.

**Comment by stevengj** [comment]
Aren't we telling the OS what cells to print each character in?

**Comment by stevengj** [comment]
The logic in `refresh_multi_line` of `LineEdit.jl` looks very suspicious to me.  `line_pos` is used alternately as a byte index (e.g. `l[1:line_pos]`) and a character index (e.g. when comparing it to `slength`).

**Comment by jakebolewski** [comment]
It looks like an ITerm bug actually, changing to the default OSX terminal results in correct behavior.  All fonts in ITerm that I have tried have the same problem.

**Comment by stevengj** [comment]
I suppose that, in theory, we could print `charwidth - wcwidth` spaces or something to compensate for a buggy wcwidth?

**Comment by JeffBezanson** [comment]
Yes, we could print spaces to compensate. I feel like it's not worth the effort though, since there is unlimited scope for downstream display bugs.

**Comment by Keno** [comment]
If you believe there is an iTerm bug, that should be filed upstream. They are usually very responsive.

**Comment by jakebolewski** [comment]
@Keno ended up not being a bug in ITerm.  You need to turn off "treat ambiguous-width characters as double width" in the Text section under preferences.

**Comment by stevengj** [comment]
I'm using Terminal, not ITerm.  What confuses me is that `🐨 abcd` looks fine when I first type it, and is only wonky when I hit ctrl-a ... this makes me think it might be a bug in `LineEdit.refresh_line`.

**Comment by Keno** [comment]
Can you screenshot what you see? I don't quite understand and I suspect terminal differences might make it hard to discuss with out.

**Comment by stevengj** [comment]
Procedure: type `🐨`, then type `abcd`.  Then type ctrl-a.  Screenshots before ctrl-a:
![image](https://cloud.githubusercontent.com/assets/2913679/6927839/1858627e-d7be-11e4-9f94-43d433903238.png)
and after ctrl-a:
![image](https://cloud.githubusercontent.com/assets/2913679/6927848/22abc90a-d7be-11e4-8584-f5e22ff69c66.png)

**Comment by JeffBezanson** [comment]
I have a sudden urge to reprogram a key on my keyboard to type a koala. Or do I use the snowman more often?

**Comment by jakebolewski** [comment]
We need tab completion for emoji's `\:koala:`

**Comment by stevengj** [comment]
I have `Base.REPLCompletions.latex_symbols["\\koala"] = "\U1f428"` in my `.juliarc`.

**Comment by stevengj** [comment]
(On a more serious note, I see exactly the same behavior for `\Longrightarrow` = `⟹` = [U+27f9](http://www.fileformat.info/info/unicode/char/27f9/index.htm).)

**Comment by Keno** [comment]
Ok, thanks. I can reproduce and take a look.

**Comment by Keno** [comment]
I suspect what might be happening here is that on input the terminal properly moves the cursor by two spaces but on output it does not.

**Comment by stevengj** [comment]
Blech, I suppose there's not much we can do about it.  But iTerm2 seems to have the same behavior, and maybe they can fix it on their end.

**Comment by Keno** [comment]
Well, maybe @gnachman can shed some light on whether that's the intended behavior:
![screen shot 2015-03-31 at 4 51 46 pm](https://cloud.githubusercontent.com/assets/1291671/6929180/dd9178d4-d7c6-11e4-8e82-ddb183627696.png)
(i.e. the double width write only taking up a single cell). It might also be of course that iTerm's unicode tables are out of date. If the behavior is by design I suspect we can just print spaces to make up for it (though we might run into trouble with the space overdrawing the character - can we do a cursor move instead of printing a space?).

**Comment by stevengj** [comment]
I think it's out-of-date/inaccurate Unicode tables.  If I use 䍒 = [U+4352](http://www.fileformat.info/info/unicode/char/4352/index.htm), which has `wcwidth==charwidth==2`, then `"a\u4352b"` prints correctly with a double-width `䍒` between the `a` and `b`, without overwriting, in both Terminal and iTerm2.   Maybe iTerm2 can just use utf8proc...

But I still don't understand why it works okay for input.

**Comment by JeffBezanson** [comment]
I'm against trying to work around it with hacks like spaces or extra cursor moves. The cost is (1) complexity and maintainability, (2) incompleteness (we can't reasonably intercept `write` data), (3) I can imagine it making matters worse in other, unforeseen circumstances.

**Comment by Keno** [comment]
I think we can probably work around it by doing a cursor move (writing spaces is problematic, because iTerm's redraw code would draw the space on top of the koala), but it just seems like such an ugly solution. I am entirely fine with telling people to use a terminal with proper unicode tables if there is any chance this can be fixed there.

**Comment by gnachman** [comment]
I can't find the implementation of utf8_charwidth. According to Unicode 7.0's EastAsianWidth.txt, u+1f355 is narrow.

http://www.unicode.org/Public/7.0.0/ucd/EastAsianWidth.txt

Is there some other spec I should be looking at? This is a problem with many Emojis.

**Comment by stevengj** [comment]
@gnachman, unfortunately I think there are conflicting goals in Julia and iTerm here.

In Julia, we need a portable `wcwidth` replacement because (a) we want consistent cross-platform results for Unicode processing, (b) the Windows `wcwidth` is broken (16-bit `wchar_t`), and (c) `wcwidth` is clearly out-of-date on most other systems.   There isn't any clear standard to follow, but the procedure involving Unifont etcetera, after an [exhaustive analysis](http://nbviewer.ipython.org/gist/jiahao/07e8b08bf6d8671e9734) by @jiahao, seemed to be the most reliable practicable approach.

iTerm, however, only has to work on MacOS, and has to work with lots of programs that rely on MacOS's buggy `wcwidth` (which reports e.g. that pizza is narrow), so it makes a certain amount of sense for it to adopt whatever width the system `wcwidth` reports, no matter how crappy it looks.

**Comment by gnachman** [comment]
@stevengj  iTerm2 does need to interoperate with anything you can ssh, telnet, etc. to, not to mention Julia, so I'm open to giving users a way to opt in to more a sensible wcwidth(). I don't use wcwidth() on the client so I *could* use utf8proc_charwidth in the right circumstances. Since AFAIK only Julia departs from the standard, there'd need to be a new escape sequence to tell the terminal emulator to switch character-width lookup tables.

OTOH, since Julia is the black sheep in this regard, it probably makes the most sense for Julia to print a space after characters that it treats as wide but wcwidth does not. And deal with cursor movement across them correctly, etc. That'll work with every terminal out there. If a window gets resized it won't wrap correctly, though. Terminal and iTerm2 will both refuse to "break" a fullwidth character into two half-width pieces, choosing instead to move the whole thing to the start of the next line, but that's a small price to pay.

**Comment by Keno** [comment]
@gnachman If I print a space next to a character, is there a chance the space will get drawn on top of it during a redraw? I think I've seen that behavior in my experiments.

**Comment by gnachman** [comment]
@Keno Yes, that can happen. I'm working on a fix to that issue in my refactor_drawing branch. Feel free to try it if you're feeling brave :). I expect to merge it into master in a week or two.

**Comment by JeffBezanson** [comment]
It's not our preference to depart from standards here. Just looking at that glyph, clearly somebody thinks it is double-width. As @stevengj said there is no clear standard.

**Comment by stevengj** [comment]
`wcwidth` is only "standard" in the sense that it is used by many programs; it is not consistent even between MacOS versions, much less across operating systems, and is often out of date.

Note that [UAX#11](http://www.unicode.org/reports/tr11/tr11-28.html) provides a clear standard for a subset of Unicode, and `wcwidth` as of MacOS 10.10.2 does not conform to Unicode 7 in the sense that it reports `-1` (not printable / not recognized) for many of the characters listed in UAX#11 as having width 1 or 2.

**Comment by jiahao** [comment]
@gnachman I have to disagree emphatically with the characterization that anything I did to compute the character widths was "rickety". The rationale and details of the analyses used to justify Julia's implementation are explained in JuliaLang/utf8proc#2 and JuliaLang/utf8proc#27 and in [this notebook](http://nbviewer.ipython.org/gist/jiahao/07e8b08bf6d8671e9734), which amongst other things details the exact discrepancies between my system `wcwidth` and the analysis. In all the cases I examined, I could not find a reason to justify the system answer over the analysis outlined in the issues and notebook.

As @JeffBezanson and @stevengj have already stated, there is _no_ standard governing character widths, and so it is not possible to characterize Julia as "departing from the standard".  On the contrary, it appears that not enough thought has gone into any other implementation for the purpose of determining character widths.

To illustrate our reasoning, consider the pizza character U+1F355. The relevant entry in `EastAsianWidths.txt` is:

`1F330..1F37D;N   # So    [78] CHESTNUT..FORK AND KNIFE WITH PLATE`

which assigns it the "neutral" category (not "narrow", which is coded as "Na"). Thus it falls into the nebulous category where UAX 11 has essentially nothing to say because the character doesn't exist in legacy East Asian encodings. (UAX 11 even says in its Scope not to consider it an authoritative source on character widths, but rather that
> The East_Asian_Width is an informative property... the guidelines on use of this property should be considered recommendations based on a particular legacy practice that may be overridden by implementations as necessary.

)

In the absence of a clear standard, the best I could come up with is to look at a font that actually bothered to provide a glyph for that code point, hence settling on Unifont, which provides this glyph:

![uni01f3](https://cloud.githubusercontent.com/assets/1732/6957689/f8a352c6-d8cc-11e4-86f0-8ee58d3afa3f.png)

Note that the character width assigned by inspecting the advance width from Unifont agrees with the eyeball comparison of the reference glyph in the  chart [(pdf)](http://www.unicode.org/charts/PDF/U1F300.pdf).

![screen shot 2015-04-01 at 11 39 54 pm](https://cloud.githubusercontent.com/assets/1732/6957619/abeb06aa-d8cb-11e4-9ba5-0b9add456c0c.png)

Superimposed for reference is a square box. I do not see any reason why this should be 'narrow' instead of 'fullwidth'.

**Comment by gnachman** [comment]
@jiahao, I wasn't criticizing your work. The informal agreement between client and server, which as you note is underspecified, is what is rickety. Your work is really valuable--I wish it (or something like it) were widely adopted.

I had believed that EastAsianWidth.txt was "the standard", but I'm persuaded that there isn't really one at all. AFAIK most apps treat N as narrow, but it leads to the problems described in this bug.

**Comment by timholy** [comment]
It sounds like this should be reported upstream/more widely, if it hasn't been already.

**Comment by stevengj** [comment]
Unfortunately, it seems like the only upstream that can really fix this is libc, in order to fix `wcwidth`.  I don't know where to file this kind of low-level bug reports with Apple (??), and Microsoft is hopeless because of the `wchar_t` size, but it would be worthwhile for someone to check utf8proc against the latest GNU libc and file a bug report for discrepancies where libc is clearly wrong.

**Comment by jiahao** [comment]
[glibc#4335](https://sourceware.org/bugzilla/show_bug.cgi?id=4335)

**Comment by vtjnash** [comment]
Julia has the right (most updated) char widths, so it's up to the user to demand their terminal emulators are displaying properly. most likely, that'll happen gradually with various companies (#7267) lagging behind more or less from the standards committee.

**Comment by Keno** [comment]
Britain may be leaving the EU, but Unicode 9 came out and fixed this issue for us, so overall it's a pretty good day:
<img width="170" alt="screen shot 2016-06-24 at 12 29 30 am" src="https://cloud.githubusercontent.com/assets/1291671/16327946/d784de56-39a2-11e6-8e27-454951e624e9.png">

**Comment by Keno** [comment]
iTerm2 PR: https://github.com/gnachman/iTerm2/pull/294
