### ISSUE TITLE
upstream dSFMT patches

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#37325]
https://github.com/JuliaLang/julia/blob/master/deps/patches/dSFMT.h.patch
https://github.com/JuliaLang/julia/blob/master/deps/patches/dSFMT.c.patch

These should be upstreamed at https://github.com/MersenneTwister-Lab/dSFMT

**Comment by ViralBShah** [comment]
I doubt they want these upstream, since they really expect you to statically link dsfmt into your application. Obviously, we can't do that. I am guessing (based on no interaction with upstream) that in order to upstream, we'd want to integrate this into the Makefiles.

If they tag releases upstream there, it would be nice for us to pull from github instead of the tarballs we download from their webserver which has at times been a bit flaky.

**Comment by StefanKarpinski** [comment]
Maybe we can just delete dSFMT as a dependency once we make xoshiro the default RNG?

**Comment by ViralBShah** [comment]
Yes, we can then move it out into a package.

**Comment by ViralBShah** [comment]
Upstream will accept the patch:
https://github.com/MersenneTwister-Lab/dSFMT/issues/2

They also tagged the release of dsfmt upstream so that we can pull from github instead of the webserver (which used to fail once in a while):
https://github.com/MersenneTwister-Lab/dSFMT/issues/1#event-3722420383

It would be great if someone wants to prepare this PR for dsfmt.

**Comment by ViralBShah** [comment]
Upstream PR created: https://github.com/MersenneTwister-Lab/dSFMT/pull/4

**Comment by ViralBShah** [comment]
Incorporated into Yggdrasil: https://github.com/JuliaPackaging/Yggdrasil/pull/1952

**Comment by ViralBShah** [comment]
I guess we need to also update the build in julia deps.
