### ISSUE TITLE
upstream p7zip FreeBSD build fix patch

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#37332]
https://github.com/JuliaLang/julia/blob/master/deps/patches/p7zip-Windows_ErrorMsg.patch

This patch should be upstreamed at https://sourceforge.net/projects/p7zip/

**Comment by ararslan** [comment]
That file actually comes from the FreeBSD Ports Tree, and the patch was submitted there by @rakuco. Sorry to bother you, Raphael, but do you know whether there are existing plans to upstream this (or other) changes? If not, I can look into it.

**Comment by rakuco** [comment]
Hi there. Please feel free to try to upstream those changes -- the biggest problem is that p7zip as a project has barely had any activity in the past few years: the latest release is from 2016, and there isn't much going on in the bug/patch tracker. [This bug report](https://sourceforge.net/p/p7zip/bugs/226/), for example, seems to be about the same issue that patch I landed fixes, and it's been ignored since last December.

**Comment by inkydragon** [comment]
This is fixed by: https://github.com/jinfeihan57/p7zip/commit/1b7d2c73f01b2d2b6a3d2d16840e96e92afdcd61
