### ISSUE TITLE
Inconsistent mpfr ccall on linuxaarch64

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#37387]
On linuxaarch64 buildbot:
```julia
julia> @ccall "libmpfr".mpfr_snprintf(C_NULL::Ptr{UInt8}, 0::Csize_t, "$((() -> "%.6g")())"::Ptr{UInt8}; big"12345678."::Ref{BigFloat})::Cint
12

julia> @ccall "libmpfr".mpfr_snprintf(C_NULL::Ptr{UInt8}, 0::Csize_t, "$((() -> "%.6g")())"::Ptr{UInt8}; big"12345678."::Ref{BigFloat})::Cint
1

julia> @ccall "libmpfr".mpfr_snprintf(C_NULL::Ptr{UInt8}, 0::Csize_t, "$((() -> "%.6g")())"::Ptr{UInt8}; big"12345678."::Ref{BigFloat})::Cint
1

julia> @ccall "libmpfr".mpfr_snprintf(C_NULL::Ptr{UInt8}, 0::Csize_t, "$((() -> "%.6g")())"::Ptr{UInt8}; big"12345678."::Ref{BigFloat})::Cint
1
```

On OSX:
```julia
julia> @ccall "libmpfr".mpfr_snprintf(C_NULL::Ptr{UInt8}, 0::Csize_t, "$((() -> "%.6g")())"::Ptr{UInt8}; big"12345678."::Ref{BigFloat})::Cint
11

julia> @ccall "libmpfr".mpfr_snprintf(C_NULL::Ptr{UInt8}, 0::Csize_t, "$((() -> "%.6g")())"::Ptr{UInt8}; big"12345678."::Ref{BigFloat})::Cint
11

julia> @ccall "libmpfr".mpfr_snprintf(C_NULL::Ptr{UInt8}, 0::Csize_t, "$((() -> "%.6g")())"::Ptr{UInt8}; big"12345678."::Ref{BigFloat})::Cint
11

julia> @ccall "libmpfr".mpfr_snprintf(C_NULL::Ptr{UInt8}, 0::Csize_t, "$((() -> "%.6g")())"::Ptr{UInt8}; big"12345678."::Ref{BigFloat})::Cint
11

julia> @ccall "libmpfr".mpfr_snprintf(C_NULL::Ptr{UInt8}, 0::Csize_t, "$((() -> "%.6g")())"::Ptr{UInt8}; big"12345678."::Ref{BigFloat})::Cint
11
```

Note the weirdness in doing `"$((() -> "%.6g")())"`; if you have a string literal for the format (i.e. `"%.6g"`), then the `ccall` returns the correct length consistently. So there's something weird with a non-const string that seems to affect things here.

**Comment by yuyichao** [comment]
The format string is wrong. `%.6g` is for passing a machine size floating point argument, not for passing a `mpfr_t`. The correct format string in this case I believe is `%.6Rg` instead.

As for the result, on aarch64, the vararg floating point arguments are passed the same as normal ones so you are just reading whatever left in the `d0` register at the time of the function call. On x86, the number of floating point arguments passed in is passed in via `rax` so the callee should be fully aware that you are lying to it (since `rax` is 0 and you are asking it to read one). I didn't check what exactly the code do but the result is definately garbage (probably some random stuff from the stack).

It's a miracle that on x86 you get the correct result..... If you pass in an actual buffer instead of `C_NULL` you'll see that the return value is some random number which just happens to be 11 digit on x86.................. Passing in the correct format string makes the return value as well as the buffer content consistent and correct.
