### ISSUE TITLE
Docs for the `for outer`

### ISSUE THREAD

**Issue by Moelf** [JuliaLang/julia#37492]
As title says, should at least show up in:
1. https://docs.julialang.org/en/v1.6-dev/manual/control-flow/#man-loops
2. `?outer`

**Comment by simeonschaub** [comment]
Yeah, definitely! Just recently learned about this. Should probably also be in the REPL help for `?for`.

**Comment by Moelf** [comment]
still don't have this
```julia

help?> outer
search: count_zeros RoundToZero OutOfMemoryError ConcurrencyViolationError countlines count_ones

Couldn't find outer
Perhaps you meant one, ones, open, operm, pointer, quote, tune!, entr, @enter, Timer, filter, put! or step
  No documentation found.

  Binding outer does not exist.
```

**Comment by skleinbo** [comment]
I can't even find it in the manual.

I'm working on a PR if that's okay.

**Comment by skleinbo** [comment]
Related: https://github.com/JuliaLang/julia/issues/40841 and https://github.com/JuliaLang/julia/pull/37471#issuecomment-689563861. 

The discussion in the latter makes wonder if it's appropriate to add a docstring, but e.g. `where` also has one. Guess that makes it okay.

**Comment by tpapp** [comment]
I think that

1. the docstring of `for` should have an *example* with `outer` and *explain* what it does,

2. the docstring of `while` should *mention* outer and direct the user to `for` for an explanation and an example,

3. the *Control flow* section of the manual should *mention* outer when discussing `for` and `while` and refer to the relevant *Scope of variables* section for details.

This would ensure that users encountering `outer` in code could find it eventually, since it is always near a `for` or `while`.

**Comment by skleinbo** [comment]
1. The PR extends the docstring of `for` by an explanation of `outer`. I didn't provide an example to avoid duplication. Those are found in the docstring of `outer`. But I can see that that would be useful.
2. Having `while` reference `for` is certainly a good idea. But I'm not sure mentioning `outer` in that context is necessary. It's only a modifier for `for` after all.
3. Absolutely. I'll include that in the PR.

**Comment by tpapp** [comment]
Sorry, I was thinking of something else, I realize that my comment about `while` makes no sense for `outer`.
