### ISSUE TITLE
Deprecate Grisu?

### ISSUE THREAD

**Issue by jw3126** [JuliaLang/julia#37506]
Can we have a depwarn for `Grisu` instead of removing it straight? I assumed it was part of the public API, since it is documented? 
```julia
help?> Base.Grisu.grisu
  (len, point, neg) = Grisu.grisu(v::AbstractFloat, mode, requested_digits, [buffer], [bignums])

...
```
It is a dependency of [Showoff](https://github.com/JuliaGraphics/Showoff.jl/issues/24), which breaks plotting on master for me.

**Comment by KristofferC** [comment]
> I assumed it was part of the public API, since it is documented?

Where was it documented?

**Comment by DilumAluthge** [comment]
The docstring is here: https://github.com/JuliaLang/julia/blob/10f5a05c21af3ca66c05654e738d0dbfc482c5fb/base/grisu/grisu.jl#L40

The tricky part is: I didn't think that something is part of the public API just because it's documented? I thought something is part of the public API if at least one of the following criteria is satisfied:
1. It is `export`ed from `Base`
2. The docstring explicitly says that it is part of the public API.

**Comment by KristofferC** [comment]
> I thought something is part of the public API only if at least one of the following criteria is satisfied:

Rather, if it is in the manual or exported.

But yeah, internal docstrings are not considered public API.

**Comment by jw3126** [comment]
Ok got it, it is not part of the stable API, so its lawful to just remove it. Can we still have a depwarn, it is de facto used by people? Also the files are still present in the repo just not included? https://github.com/JuliaLang/julia/tree/master/base/grisu

**Comment by KristofferC** [comment]
That's one file and looks like it was just forgotten to be deleted.

**Comment by quinnj** [comment]
I commented on the Showoff issue that it should be much easier to do what they were trying there by "dynamically" formatting float values; there's a new `Printf.format(fmt::Printf.Format, args...)` function that allows constructing/passing in a `Printf.Format` object and formatting the result as a string (or passing an `io` as the 1st argument will print the result directly).
