### ISSUE TITLE
Possible bug in Dates.Time parsing

### ISSUE THREAD

**Issue by mkborregaard** [JuliaLang/julia#37514]
I think this might be a bug:
```julia
julia> using Dates
julia> Time("12.2", "HH.MM")
12:02:00
```
I'd expect this to give 12:20:00.

I've encountered this in the wild - when saving csv files containing time-formatted cells from Excel, the common inbuilt format is `12.20`. Parsing that with a CSV reader (or back into excel) will parse it as the floating point number `12.2`, leading to hard-to-notice silent errors in time representation. 

I don't believe, on the other hand, that there is any legal representation of `12.02` that would be shown as `12.2` (the current default).

**Comment by jmkuhn** [comment]
The current behavior is what I would expect.  What would you expect for `Time("2.2", "HH.MM")`?

**Comment by truedichotomy** [comment]
This would give the response you anticipated:
```
julia> Time("12.20","HH.MM")
12:20:00
```
where as: 
```
julia> Time("12.02","HH.MM")
12:02:00

julia> Time("12.2","HH.MM")
12:02:00
```

Not sure if it is tended this way or not.

**Comment by quinnj** [comment]
Yes, this is working as intended; data formatting is just a messy business, but with parsing, we have delimiters, and in between delimiters we parse whatever is there as a number. If it's `2`, then it has to just be `2`; it's too dangerous to start assuming, based on a specific period type that maybe it was _meant_ to be `20`.

**Comment by mkborregaard** [comment]
I still disagree. "12.20" works because it's a string, but it will parse to 12.2 when recognized as a number, which will then become 12:02. On the other hand, you would never encounter 12.2 when it is actually meant to be 12.02.

Is this a matter of opinion, in which case I'd request reopening for discussion - I hadn't seen the discussion before?

**Comment by mkborregaard** [comment]
I think at the very least `Time("12.2","HH.MM")` could error noisily

**Comment by quinnj** [comment]
But that's never been part of the parsing strategy in Dates parsing code; if you have a fixed width date string, then you use a fixed width string with no delimiters, but otherwise, it's just plain delimited parsing, meaning anything between two delimiters is what is parsed as the "number" for that slot. In no way does the parsing code every see "12.2" as a single entity; it knows to look for digits until a `.` character, and that's the `HH` period. Then anything that comes after `.` is the `MM` period.

**Comment by truedichotomy** [comment]
Seeing the explanation behind Dates implementation, I agree with @quinnj. The role of delimiters should strictly be delimiters, '.' in this case could very well be ":" or something else, in which case, "02" and "2" would be interpreted to be the same number, while "20" would be a different number. Should not mix decimal with delimiter.

**Comment by mkborregaard** [comment]
I do understand the logic about that implementation - but I still think we're missing the key point here, from my first message: 

> leading to hard-to-notice silent errors in time representation

No matter the internal logic it seems very unfortunate to me that, using all standard settings, if you have date-times in an Excel sheet, save it as CSV, then read the CSV, all occurrences of "12.20" will be replaced by "12.02". This introduces silent errors that can wreck analyses and is bound to bite people.

I really don't think Julia potentially introducing a problem of this kind can be dismissed with "that's not the parsing strategy". I realize that Excel's hopeless default delimiter for times is the real culprit here - on the other hand I'm definitely not the only person in the world using Excel.

**Comment by nalimilan** [comment]
I agree that's it's weird that `MM` accepts a single digit without a warning. What's the point of using two `M` if the number of digits doesn't matter?

**Comment by quinnj** [comment]
> What's the point of using two M if the number of digits doesn't matter?

Consider the alternative; you either have to specify a single `M` or double `MM`, but what if your data has both single and double digits? This was a conscious decision since the beginning of datetime parsing that it doesn't matter how many format characters you use in a row, it's still looking for a single number between delimiters (unless you're doing fixed-width parsing, obviously).

@mkborregaard, I can understand the frustration. Perhaps we need a different way to specify an exact number of digits for format character specifiers so people can be more strict in their code. Then you would at least get the "noisy error" you're after for `12.2`

**Comment by nalimilan** [comment]
I guess something like passing `strict=true` could work?

**Comment by mkborregaard** [comment]
I think having a keyword would also go very far in terms of documenting this possible footgun.

**Comment by mkborregaard** [comment]
Does this not mean we should at least reopen the issue?
