### ISSUE TITLE
julia/usr/include/uv.h:1797:23: error: expected ';' before 'typedef'  1797 | UV_IDLE_PRIVATE_FIELDS

### ISSUE THREAD

**Issue by 62f** [JuliaLang/julia#37561]
I cannot reproduce. I cloned a fresh copy of julia and ran `make -j1 VERBOSE=1` and it completed just fine. If you did something other than that, please include it in a self-contained issue.

_Originally posted by @StefanKarpinski in https://github.com/JuliaLang/julia/issues/37537#issuecomment-691738374_

I don’t understand the term ‘self-contained’, so I guess and give each error message its own number.

**Comment by yuyichao** [comment]
No this is not what self contained means. That's not a particular useful thing in this case since self contained here basically means you whole file system. You don't have to keep opening new issues. It's fine to talk about a new issue in an old one if the two always happen at the same time and if the first one haven't be fixed yet (i.e. closing https://github.com/JuliaLang/julia/issues/37475 is correct closing https://github.com/JuliaLang/julia/issues/37483 was unnecessary, starting this one is bad...). The discussion is very hard to track because of the large number of issues.

**Comment by yuyichao** [comment]
If it's unclear, you can ask and you'll usually be told to start a new one when it's clear that there are more then one independent issues.
