### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by m-brandl** [JuliaLang/julia#38181]
In the documentation to [Mathematical Operations and Elementary Functions: Operator Precedence and Associativity](https://docs.julialang.org/en/v1/manual/mathematical-operations/#Operator-Precedence-and-Associativity), there is the following sentence:

> Numeric literal coefficients, e.g. 2x, are treated as multiplications with higher precedence than any other binary operation, and also have higher precedence than ^.

But wouldn't this mean that

```
x = 3
2x^2
```

should evaluate to 36, and not 18? Getting 18 is probably what most people would expect from the expression without reading the docs, so: Is this a mistake in the documentation?

**Comment by StefanKarpinski** [comment]
It would seem that sentence in the documentation is incorrect. It seems to be written with `x^2y` in mind, but not `2x^y` in mind. The reality is that numeric literals parse as unary operators, so compare with `x^-y` and `-x^y` which parses in the same way. Definitely worth fixing that incorrect sentence though. The trouble is that the docs were once written by @JeffBezanson who wrote the parser and described this correctly but tersely, and have since been modified by others who want to elaborate on some of the cases but and up elaborating in ways that are not entirely accurate. It's hard for us to keep an eye on all of the docs being completely accurate.
