### ISSUE TITLE
hessenberg function -- types of outputs

### ISSUE THREAD

**Issue by RJDennis** [JuliaLang/julia#38441]
Most standard linear algebra operations can be performed on the outputs of the hessenberg function, but not all.  For example, take:
```
c = randn(3,3)
(v,s} = hessenberg(c)
```

One can do:
```
rv = rank(v)
```
but not:
```
rs = rank(s)
```
and the following also are not possible:
```
vi = inv(v)
vs = inv(s)
```
Instead v and s have to be converted to matrices beforehand:
```
vm = Matrix(v)
vs = Matrix(s)
```
This conversion is relatively painless, but it does allocate and seems unnecessary.  Can methods be defined so that the linear algebra functions that can currently be applied to Matrices can also be applied to the types of v and s?  Or can the types of v and s be made subtypes of Array?

**Comment by stevengj** [comment]
More operations can certainly be added to the Hessenberg-factorization types in the future.

However, the whole point of doing this factorization is to take advantage of the special structure of these matrices, so it is more worth the effort to implement opeations that are useful in this context.

For example, `inv` is probably not a good idea.  For the Q matrix (your `v`), since it is unitary there is not much point — you should be using `Q'b` or `Q \ b` to solve systems with `Q`—but I suppose it would be harmless to add `inv(Q::HessenbergQ) = Q'`.   For the H matrix (your `s`), computing an inverse is positively harmful, since the inverse loses the upper-Hessenberg structure.   It is *much* faster to solve `Hx=b` systems using `x = H \ b` than using `inv(H) * b`.     ("Don't compute matrix inverses" is one of the first rules of thumb to learn in numerical linear algebra.)

**Comment by stevengj** [comment]
> Or can the types of v and s be made subtypes of Array?

They already are:
```jl
julia> A = rand(5,5); Q,H = hessenberg(A);

julia> Q isa AbstractMatrix
true

julia> H isa AbstractMatrix
true
```
but that doesn't mean that arbitrary linear-algebra functions work for them — there are many special matrix types that don't support arbitrary linear-algebra operations efficiently.

**Comment by RJDennis** [comment]
I realized as I posted that my example involving the inv() function was a poor one, but throught that the general point would still be understood.  One generally expects to be able to do linear algebria operations on things that look like matrices even if they have special (and sometimes exploitable) structure.

Here is an example (that I encountered when implementing a Sylvester equation solver):
```
g = complex(randn(2,2))
h = randn(2,2)
(v,s) = hessenberg(h)
v*g
```
The above fails.  I need to convert v to a matrix
```
m = Matrix(v)
v*g
```

**Comment by stevengj** [comment]
The point is that it is not feasible to implement *every* possible matrix operation for special matrix types like this.  You should file issues for specific missing operations.   Or file a single issue that contains a list of several specific operations.

I agree that mixed real-complex matrix multiplication should ideally be implemented.  Maybe file an issue for that.

(The reason it is not implemented is that there is a special LAPACK function for multiplying by the Hessenberg Q matrix in packed format, but it doesn't support all combinations of operands.   So we'll have to implement a separate fallback routine to support other operands, e.g. mixed precision or mixed real/complex.)
