### ISSUE TITLE
SymTridiagonal MethodError

### ISSUE THREAD

**Issue by julien-blanchon** [JuliaLang/julia#38565]
`SymTridiagonal` from LinearAlgebra.jl seems broke.
I could not reproduce this command of the documentation:
```julia> A = SymTridiagonal(fill([1 2; 3 4], 3), fill([1 2; 3 4], 2));
MethodError: no method matching zero(::Type{Array{Int64,2}})```

julia version 1.5.3

**Comment by dkarrasch** [comment]
So what exactly is broken? Can you please give a function call that produces the error?

**Comment by julien-blanchon** [comment]
Oups sorry: ```A = SymTridiagonal(fill([1 2; 3 4], 3), fill([1 2; 3 4], 2));```

**Comment by stevengj** [comment]
Note that this error only occurs for display, not for construction:
```
A = SymTridiagonal(fill([1 2; 3 4], 3), fill([1 2; 3 4], 2));
```
gives no error (using the `;` to suppress output), only `display(A)` throws.  It boils down to this line in `getindex`: https://github.com/JuliaLang/julia/blob/6614645892f03915e4f10b051df9a228c980abc8/stdlib/LinearAlgebra/src/tridiag.jl#L455

The problem here is that the return value cannot be determined from the type alone — for off-diagonal elements, it must return a zero value of *some* kind of `Matrix{Int}`, but it doesn't know the *size* (since the size is not part of the type).  The only way to determine the type would be to look at *all* of the elements, which would make `getindex` O(n) instead of O(1).

One thing you might consider here is to use StaticArrays:
```jl
julia> A = SymTridiagonal(fill(@SMatrix[1 2; 3 4], 3), fill(@SMatrix[1 2; 3 4], 2))
3×3 SymTridiagonal{SArray{Tuple{2,2},Int64,2,4},Array{SArray{Tuple{2,2},Int64,2,4},1}}:
 [1 2; 2 4]  [1 2; 3 4]      ⋅     
 [1 3; 2 4]  [1 2; 2 4]  [1 2; 3 4]
     ⋅       [1 3; 2 4]  [1 2; 2 4]
```
This works because an `SMatrix` encodes the *size* of the arrays in the type.  It is also vastly more efficient than `Array` for working with lots of 2x2 matrices.

**Comment by stevengj** [comment]
I guess the correct thing here would be to determine the size of the `i,j` zero element by looking at `size(A[i,i],1), size(A[j,j],1)`.
