### ISSUE TITLE
Splatted array of arrays produce unexpected results with hvcat syntax

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#38844]
I found that splatting an array of arrays in an hvcat produces unexpected output. (Julia 1.5.3 and 1.6.0-DEV.1275)

```
b = [1; 2; 3]
a = [[b] [2b]; [3b] [4b]; [5b] [6b]; [7b] [8b]]

[a[1:2]... a[3:4]... ; a[5:6]... a[7:8]...]
#=
Performs the equivalent of [a[1] a[2] ; a[3] a[4]], dropping others.

6×2 Matrix{Int64}:
  1   3
  2   6
  3   9
  5   7
 10  14
 15  21
=#
```

To understand what might be expected, here are how the hcat and vcat behave:

```
[a[1:2]... a[3:4]...]
#=
Performs hcat of all elements

3×4 Matrix{Int64}:
 1  3   5   7
 2  6  10  14
 3  9  15  21
=#

[a[1:2]... ; a[3:4]...]
#=
Performs vcat of all elements

12-element Vector{Int64}:
  1
  2
  3
  3
  6
  9
  5
 10
 15
  7
 14
 21
=#
```

So I would think the first operation should be equivalent to:
```
[[a[1:2]... a[3:4]...] ; [a[5:6]... a[7:8]...]]

6×4 Matrix{Int64}:
 1   3   5   7
 2   6  10  14
 3   9  15  21
 2   4   6   8
 4   8  12  16
 6  12  18  24
```

Fixing this will have an implication for my PR #33697 , if accepted, so hopefully the solution can be made to work with it too.

**Comment by simeonschaub** [comment]
If we look at what this is lowered to, it becomes clear what is going on here:
```julia

julia> Meta.@lower [a[1:2]... a[3:4]... ; a[5:6]... a[7:8]]
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope'
1 ─ %1  = Core.tuple(2, 2)
│   %2  = Core.tuple(%1)
│   %3  = 1:2
│   %4  = Base.getindex(a, %3)
│   %5  = 3:4
│   %6  = Base.getindex(a, %5)
│   %7  = 5:6
│   %8  = Base.getindex(a, %7)
│   %9  = 7:8
│   %10 = Base.getindex(a, %9)
│   %11 = Core.tuple(%10)
│   %12 = Core._apply_iterate(Base.iterate, Base.hvcat, %2, %4, %6, %8, %11)
└──       return %12
))))
```
So the problem is that the number of horizontal concatenations always get hardcoded. The easiest solution here might be to make the first argument `(length(%4) + length(%6), length(%8) + length(%10))`, but that wouldn't work for iterators that don't define `length`. To fix that in the general case, we would most likely have to change the API of `hvcat` and I don't know whether that's possible in a non-breaking way. Until we have a proper solution here, it would probably make sense to have this throw an error during lowering instead.
