### ISSUE TITLE
Point source code on local file system

### ISSUE THREAD

**Issue by dcand** [JuliaLang/julia#38854]
The html documentation provided as part of binary distribution contains URL to source code which points to Github thus requires internet connection to view.

**Comment by StefanKarpinski** [comment]
The docs are source files and are not meant to be read as markdown files in-place. They can be built in various ways using the makefile in the `doc` directory, including as a PDF or local HTML files. You can ask any further questions you might have about how to do this on the [Julia discourse](https://discourse.julialang.org/c/user) discussion forums.

**Comment by dcand** [comment]
@StefanKarpinsk You didn't understand what I said. The HTML documentation file provide as part of the binary distributions contains URLs to base and stdlib's Julia source files which points to Github. I asked to point those to local file system.

**Comment by StefanKarpinski** [comment]
How would one link to files that can be in different locations on each system?

**Comment by dcand** [comment]
This should have been thought before.

**Comment by StefanKarpinski** [comment]
There is no such thing as a relative `file://` URL, so it is impossible to replace the URLs in the documentation with static URLs that would work on each install, which means that in order to accomplish what you're requesting, there would have to be a build step that replaces each URL with a non-static URL that matches the source location on your specific system. This is entirely possible but would require someone to implement such a build target for the documentation. If you're interested in doing that, a pull-request would be welcomed. It would seem to require:

1. Figuring out where the `src_root` of Julia's source code is for your installation
2. Replacing `https://github.com/JuliaLang/julia/blob/master` in the docs with `file://$src_root`

If you're interested in adding such a build option for the docs, that would be a good contribution.
