### ISSUE TITLE
Presence of :() makes previous code slow

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/julia#38880]
Julia 1.5.3

I found this confusing MWE while trying to debug performance issues in Pluto's struct viewer:

Script one:
```julia
struct A x end
struct B x end

for m in 1:1
    @time repr(A(1))
    @time repr(B(1))

    if false
        # this code is never run
        asdfasdf(:())
    end
end
```
result:
```
fons@woof:~/disorganised-mess$ julia exprmakesmeslow.jl 
  0.036861 seconds (29.76 k allocations: 1.675 MiB)
  0.028280 seconds (27.19 k allocations: 1.447 MiB)
```

Script two: _the line with `:()` is commented out_
```julia
struct A x end
struct B x end

for m in 1:1
    @time repr(A(1))
    @time repr(B(1))

    if false
        # this code is never run
        # asdfasdf(:())
    end
end
```
the result is decreased allocs and runtime: 
```
fons@woof:~/disorganised-mess$ julia exprmakesmeslow.jl 
  0.015973 seconds (10.60 k allocations: 573.326 KiB)
  0.011359 seconds (8.04 k allocations: 416.161 KiB)
```
In one case the difference was 14s vs 1s.

The MWE uses `:()`, but any quoted expression gives this behaviour.

I'm submitting this as an 'issue', but mostly I would love to understand this situation better 🙂, I think that it is linked to Pluto's performance issue

**Comment by fonsp** [comment]
For a more dramatic example: replacing 
```julia
@time repr(A(1))
@time repr(B(1))
```
with
```julia
@time repr([[[[[A(1)]]]]])
@time repr([[[[[B(1)]]]]])
```

gives `1M allocs` with the `:()` and `20k allocs` without.

**Comment by JeffBezanson** [comment]
This is due to our heuristics for when to compile top-level expressions. Generally, it's important to avoid compiling top-level expressions because compilation slows down loading a lot, and most top-level expressions only run once and don't do much.

If an expression contains a quoted expression, we assume it's being used for code generation and so is not performance-sensitive, so we don't compile it. That means we don't compile `repr` until we get inside the call to it. So adding `:()` causes the compilation overhead to get moved inside the `@time` block. Otherwise it's compiled along with the top-level block itself, hiding the compilation overhead from `@time`.

**Comment by fonsp** [comment]
Thank you!

To confirm, running `time julia script.jl` shows no difference in total runtime between the two cases.
