### ISSUE TITLE
printing for subtypes of Function could be more informative

### ISSUE THREAD

**Issue by navidcy** [JuliaLang/julia#39172]
The summary of a function is not very informative.

```Julia
julia> f(x) = x^2
f (generic function with 1 method)

julia> summary(f)
"typeof(f)"
```

```
julia> versioninfo()
Julia Version 1.6.0-beta1
Commit b84990e1ac* (2021-01-08 12:42 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 12```

**Comment by simeonschaub** [comment]
This printing of function types is definitely intentional, since `Function` is not a concrete type, so `typeof(f)` is actually a unique type. I proposed printing `typeof(f)` as `typeof(f) (singleton type of function f, subtype of Function)` in the REPL before, which seemed to be well received, but that will need to hook into the existing `show(io, ::Type)`, which is a bit non-trivial.
