### ISSUE TITLE
`norm` of a number always converts to float

### ISSUE THREAD

**Issue by plut** [JuliaLang/julia#39224]
```julia
    using LinearAlgebra, FixedPointNumbers; F = Fixed{Int64,16}
    norm(F(1))
```
Returns `1.0`, where I would expect a fixed-point value. This can even be generalized without loss of precision to any numeric type, since the norm is just the absolute value. (This could be fixed in either `FixedPointNumbers` or `LinearAlgebra`, but the most generic fix would be removing the superfluous `float()` conversion in `generic.jl`).

*Edit: canceling the paragraph below; I misread the (undocumented) function and believed that it returned the *squared* norm:*

~~Also, while investigating this, I discovered that there is a perfectly good `norm2` function in LinearAlgebra (which, as expected, is the square of Euclidean norm), but it is undocumented (although `BLAS.nrm2` is documented). Since `norm2` is in practice at least as useful as `norm(...,2)` (and faster), this function deserves a small docstring.~~

**Comment by simeonschaub** [comment]
The conversion to a floating point value is needed for integers or rationals. I think in this case, it would probably be better to fix this on FixedPointNumbers' side.

> Since norm2 is in practice at least as useful as norm(...,2) (and faster), this function deserves a small docstring.

I don't really understand how this is an improvement over `norm`. Since the 2 here is a constant, the extra `if` check inside `norm` should be able to be eliminated in almost all cases. Even if it wasn't, I don't see how this could lead to any non-negligible overhead in real-world use. `norm2` is just an implementation detail and exporting it could also lead to confusion, since we already have a function called `abs2` which calculates the absolute value squared and `norm2` does not square the output. I don't think this is related to this issue though.

**Comment by plut** [comment]
> The conversion to a floating point value is needed

Why? Is there really any code works with a float but not with an integer (or rational)?

> I don't really understand how this is an improvement over norm. Since the 2 here is a constant, the extra if check inside norm should be able to be eliminated in almost all cases.

Indeed I misread the code (and this is a separate issue); I believed that `norm2` returned the *squared* L^2-norm.

**Comment by simeonschaub** [comment]
> Why? Is there really any code works with a float but not with an integer (or rational)?

Yes, the 2-norm cannot generally be represented by a rational/integer. We also don't really want to use integers/rational for the accumulation step in between, as those will overflow fairly quickly, since they have a much lower range than floats.

**Comment by plut** [comment]
This method is about the *p*-norm of a single `Number` (not even a length-1 vector). Since this is equal to its absolute value, it can absolutely be, in general, be represented by the same type as its input (the only possible exception being `norm(typemin(T::Signed))`, which is even ignored by the current implementation of `abs`).

I don't know what “accumulation step” you mean: since this is a scalar, there is no such step in this function. There might be some cases however where this function is called in a loop, but then these calls are the place which might overflow and are where the norm could be wrapped in a `float()`. I looked rapidly in the `LinearAlgebra` sources and indeed found

 - some calls by `norm(itr, p::Real = 2)` to the scalar `norm(::Number)`, which are already wrapped in `float()`;
 - some calls by `opnorm1(::AbstractMatrix)` and its dual `opnormInf`, which are not wrapped in `float()` (and very unlikely to overflow, as it's only additions).

So my expanded suggestion would now be: remove `float()` in `norm(::Number)`, and insert it where needed in `opnorm1` and `opnormInf`.

**Comment by mcabbott** [comment]
Why not call `abs` if this is what you want? 

It doesn't seem crazy that `norm(::Number)` should behave exactly as `norm(::Vector)` does. I think we (or at least I) mis-read your initial question, by assuming that you really had vectors, and had just minimised the example down to a one number, on the assumption that these would behave similarly.

The reason `norm([1,2,3], 1)` isn't an integer is type-stability, since `norm([1,2,3], 2)` etc. are not integers. But `sum(abs, [1,2,3])` is of course an integer.

**Comment by jmichel7** [comment]
For me, the interesting part of the proposition of plut is the possibility of some programs in `linearalgebra` working in a larger context. For someone wanting to use linear algebra in modular arithmetic of finite fields, some of the basic routine (like matrix inversion) but very few other (already `\` does not work and it is currently impossible to make an alternative using multiple dispatch since the signatures are too broad). Another example is that the `rank` of a rational matrix make no effort to be exact.
It would be very useful to go over all `linearalgebra` and remove needless assumptions of floating-point whenever possible.

**Comment by stevengj** [comment]
> It would be very useful to go over all LinearAlgebra and remove needless assumptions of floating-point whenever possible.

Trying to perform exact integer and rational operations, e.g. exact integer determinants, often requires *very* different  algorithms than for the floating-point case, with very different computational complexity.   Whenever this has come up in the past, my recollection is that the consensus was that it belongs in a separate package, e.g. an ExactLinearAlgebra package, with its own definitions of `det` etcetera.

**Comment by stevengj** [comment]
With regards to `norm(x::Number)`, I don't have strong feelings about it; my vague recollection is that it was initially defined as `abs(x)` but was then converted to floating point because of things like `norm(typemin(Int))` —I agree that this is not a strong argument.

**Comment by ViralBShah** [comment]
Close?
