### ISSUE TITLE
About the element-wise operation

### ISSUE THREAD

**Issue by TZTsai** [JuliaLang/julia#39269]
In Julia, element-wise operations can be realized by the dot symbol ".". However, for arithmetic operations like "+", "-", "*", "/", etc., the dot is put before the operation symbol, e.g. ".+", ".-", while for functions the dot is put after the function name. Since these operation symbols are also generic functions in Julia (we can write `+(1, 2)` as an equivalent of `1+2`), would it be more consistent if the dot is put after the function for both symbolic operations and named functions? For example, `1+.x` instead of `1 .+ x`.

**Comment by dkarrasch** [comment]
That inconsistency seems to only affect operators for which there is an in-fix notation available. When using pre-fix notation, the same rule applies as for every other function:
```julia
julia> x = (1,2)
(1, 2)

julia> (+).(1, x)
(2, 3)
```
Since in-fix notation is special ("inconsistent") compared to the usual function notation, I'd argue that the inconsistency about the broadcasting dot is consistent. 😄

**Comment by fredrikekre** [comment]
xref https://github.com/JuliaLang/julia/issues/8450, https://github.com/JuliaLang/julia/pull/20249#issuecomment-275797612, https://github.com/JuliaLang/julia/pull/20540

**Comment by StefanKarpinski** [comment]
The other way to look at this is that in `f.(x)` the dot is in front of the `(` just as it is in front of the `+` in `a .+ b`.
