### ISSUE TITLE
GitError that only occurs in 1.6/nightly

### ISSUE THREAD

**Issue by Moelf** [JuliaLang/julia#39289]
The PkgServer problem may be network but the GitError is real since `git clone ...` from shell works just fine.

```
(@v1.7) pkg> add PyCall
    Updating registry at `~/.julia/registries/General`
┌ Warning: could not download https://pkg.julialang.org/registries
│   exception = Error reading ca cert file /etc/ssl/certs/ca-certificates.crt - mbedTLS: (-0x2180) X509 - The CRT/CRL/CSR format is invalid, e.g. different type expected while requesting https://pkg.julialang.org/registries
└ @ Pkg.Registry /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Pkg/src/Registry/Registry.jl:81
   Resolving package versions...
     Cloning [438e738f-606a-5dbb-bf0a-cddfbfd45ab0] PyCall from https://github.com/JuliaPy/PyCall.jl.git
ERROR: failed to clone from https://github.com/JuliaPy/PyCall.jl.git, error: GitError(Code:ERROR, Class:SSL, failed to load CA certificates: 0xffffde80 - X509 - The CRT/CRL/CSR format is invalid, e.g. different type expected)
```

```
(@v1.5) pkg> add ClusterManagers
 Installing known registries into `~/.julia`
######################################################################## 100.0%
      Added registry `General` to `~/.julia/registries/General`
  Resolving package versions...
  Installed ClusterManagers ─ v0.4.0
Updating `~/.julia/environments/v1.5/Project.toml`
  [34f1f09b] + ClusterManagers v0.4.0
```

**Comment by Moelf** [comment]
```
using NetworkOptions

julia> ca_roots()
"/etc/ssl/certs/ca-certificates.crt"
```
cantent:
http://sprunge.us/N16Bzf

**Comment by StefanKarpinski** [comment]
I can reproduce this and the same error occurs for when using LibGit2 and Downloads: it seems that MbedTLS does not like the format of something in this certs file. Is this the standard file that ships with your distro? If so, what distro is it? OpenSSL's `keytool` also fails to parse it:
```sh
$ keytool -printcert -file tmp/broken_certs.pem
keytool error: java.lang.Exception: Failed to parse input
```
So it seems likely that this is just a messed up certificates file since both OpenSSL and MbedTLS choke on it.

**Comment by Moelf** [comment]
that's interesting. I'm on a login node of a cluster, I will ask an IT if I can find one and get back.

**Comment by Moelf** [comment]
@StefanKarpinski reply from IT suggests they are using newer SSL certs for login nodes and whatever library (OpenSSL) we're using is too old/not patched? They tested with an older cert and it worked.

**Comment by StefanKarpinski** [comment]
> I wonder why 1.5.3 didn't complain

In previous Julia versions, we always used a bundled set of CA root certs. That's bad on systems where people have added their own CA root certs in order to securely access self-signed servers or to allow man-in-the-middle firewalls, which is a common setup in corporate environments. As of Julia 1.6, we preferentially use system certificates.

If you put the following in your startup file, you can use the bundled CA root certs instead:
```jl
@eval Module() begin
    import NetworkOptions
    ENV["JULIA_SSL_CA_ROOTS_PATH"] = NetworkOptions.bundled_ca_roots()
end
```

> reply from IT suggests they are using newer SSL certs for login nodes and whatever library (OpenSSL) we're using is too old/not patched? They tested with an older cert and it worked.

I did a bit of poking around and the certs in PEM files that MbedTLS accepts are delimited with `BEGIN CERTIFICATE` whereas the ones in the file your IT department generated that are delimited with `BEGIN TRUSTED CERTIFICATE`. As is explained in [this .NET issue](https://github.com/dotnet/docs/issues/17775) where they document the deprecation of support for the latter on Linux:

> Root certificates on Linux (and other Unix-like systems, not including macOS) can be presented in two forms: the standard "BEGIN CERTIFICATE" PEM header, and the OpenSSL-specific "BEGIN TRUSTED CERTIFICATE" PEM header.

Given that this format is OpenSSL-specific and cannot be read by Java, .NET or MbedTLS, it seems reasonable to request that IT provide CA root certificates with standard PEM format.

**Comment by StefanKarpinski** [comment]
Oh, I also tried just replacing `BEGIN TRUSTED CERTIFICATE` with `BEGIN CERTIFICATE` and that doesn't work, so something a bit more clever needs to be done. I believe that the `openssl` tool can be used to convert though.

**Comment by Moelf** [comment]
I can't find something *also* broken on the login node, for example, python works even when I point the `crt` : 
```
>>> requests.get('https://github.com', verify='/etc/ssl/certs/ca-certificates.crt')
<Response [200]>
```

**Comment by StefanKarpinski** [comment]
Python may be using OpenSSL which can presumably read its own custom format. You may want to try Java or .NET since that issue is about .NET deprecating support fo this and they cite the fact that Java doesn't support it.
