### ISSUE TITLE
@everywhere is slow on HPC with multi-node environment

### ISSUE THREAD

**Issue by algorithmx** [JuliaLang/julia#39291]
https://github.com/JuliaLang/julia/blob/7647ab574fba6460877d0c1c571a86fdf18b5d31/stdlib/Distributed/src/macros.jl#L207

Please check here for descriptions of the problem by three Julia users:

https://discourse.julialang.org/t/everywhere-takes-a-very-long-time-when-using-a-cluster/35724

I have tested `@everywhere` and `pmap()` on an HPC. Test code and result available here
https://github.com/algorithmx/nodeba

Basically I just put timestamps between the lines. You can see in t*.log files that the largest gap is the one between timestamp 3 and 4. More interestingly, I found that increasing nworkers() causes the gap to increase linearly. I believe that this gap represents the execution time of the macro `@everywhere`, seen from master.

The vesion info is :
````
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c7 (2020-11-09 13:37 UTC)
Platform Info:
OS: Linux (x86_64-pc-linux-gnu)
CPU: AMD EPYC 7452 32-Core Processor
WORD_SIZE: 64
LIBM: libopenlibm
LLVM: libLLVM-9.0.1 (ORCJIT, znver2)
Environment:
JULIA_PKG_SERVER = https://mirrors.tuna.tsinghua.edu.cn/julia
````

**Comment by algorithmx** [comment]
test code and result available here
https://github.com/algorithmx/nodeba

**Comment by algorithmx** [comment]
You can see in t*.log files that the gap between timestamp #3 and #4 
---------------------------------------------------------
***** Time now 3 **  8325076078178054
***** Time now 4 **  8325121455392544
---------------------------------------------------------
is the largest. Between them, is the @everywhere macro.
This gap seems to increase linearly w.r.t. nworkers()

**Comment by algorithmx** [comment]
_
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.3 (2020-11-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD EPYC 7452 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver2)
Environment:
  JULIA_PKG_SERVER = https://mirrors.tuna.tsinghua.edu.cn/julia

julia>

**Comment by algorithmx** [comment]
related issue 
https://github.com/JuliaLang/julia/issues/28966

**Comment by arnauqb** [comment]
Hey @algorithmx I'm facing exactly the same issue you describe, have you found any workaround yet?

**Comment by algorithmx** [comment]
> Hey @algorithmx I'm facing exactly the same issue you describe, have you found any workaround yet?
> 
> Could it be realted to this? [JuliaLang/Pkg.jl#1219](https://github.com/JuliaLang/Pkg.jl/issues/1219)

not yet :-(

**Comment by arnauqb** [comment]
So I have been able to reduce the delay quite significantly by using the latest Julia 1.6 release (seems that the faster compilation speed helps), and also changing the ``Base.DEPOT_PATH``.

```julia
using Distributed, ClusterManagers
pids = addprocs_slurm(...)
@everywhere pushfirst!(Base.DEPOT_PATH, "/tmp/julia.cache")
```

**Comment by moble** [comment]
[I've also run into](https://discourse.julialang.org/t/can-julia-be-used-with-a-large-number-of-processes/66041) this problem, and traced it back to just using `@everywhere` with basically any simple statement — even
```julia
@everywhere 1+2
```
This is a real killer for my use case, which involves scaling up to thousands of processors, which will waste (and has wasted) thousands of cpu-hours just running that first `@everywhere` statement.

**Comment by moble** [comment]
Also note that @affans [reported](https://discourse.julialang.org/t/everywhere-takes-a-very-long-time-when-using-a-cluster/35724) that this was a _regression_, with julia 1.0.5 running very quickly, and 1.3 very slowly.

**Comment by KristofferC** [comment]
If possible, it would be good to run a bisect between julia 1.0 and 1.3 to find out if there was a specific commit that caused the regression.

**Comment by LarkAnspach** [comment]
Yes

**Comment by vancleve** [comment]
I've also noticed this on Julia 1.6.2 and it's not just multi-node environments. When I am on a 128 core AMD machine and perform `@everywhere using pkgs`, I notice on using `top` that quickly only a handful of julia processes are using any CPU at once at 10% or so and only one of the processes is running. Which process is running changes until finally the `@everywhere using` completes. This happen on multi-node systems too except its one node at a time with a handful of processes at low CPU and one process running.

I have a video of what this looks like here:
[](https://drive.google.com/open?id=1uTffNoS5HyiAXgFFlSHaNqG8xNrTfO2O&authuser=jeremy.vancleve%40gmail.com&usp=drive_fs)

**Comment by moble** [comment]
Workaround described [here](https://discourse.julialang.org/t/why-does-julia-use-thousands-of-cpu-hours-to-compute-1-2/66041/3?u=moble).  Basically, you have to precompile the code that lets processes talk to each other.

**Comment by vancleve** [comment]
thanks @moble! I guess what I wonder is why is seems like precompilation problem is worse with many more processors? In other words, why aren't they all just precompiling simultaneously (the video makes it look like they're doing it one by one almost)?

**Comment by moble** [comment]
I don't actually know how things work under the hood, but I have tested it and found that the timing increases linearly with the number of processes.  So my mental model is that `@everywhere` involves the primary process sending the instruction to workers and waiting for some type of confirmation that the instruction was received — or at least that sending has started.  (I don't know it's an actual receipt confirmation, or opening of the socket, or creation of that worker's log, or the beginning of deserialization...)

But the primary must do this *in serial* to some extent, meaning it doesn't start sending the instruction to the next worker until it has whatever confirmation it needs.  Normally this wouldn't be a problem, because confirmation is presumably almost instantaneous the great majority of the time.  But *compiling the code required to confirm* takes ~1 second.  And that's the part that has to happen on each worker in serial.  That 1 second is not used in compiling the statement itself (which I know because I've tried statements that take much longer to compile); it must be just some piece of code required to let the primary know it got the message.

By precompiling something as simple as `@everywhere 1+1`, each worker can skip that step of compiling the confirming function, so the primary can move on to the next worker more quickly.  And that's exactly what KristofferC has added/re-enabled in #42156.

**Comment by vancleve** [comment]
maybe the precompilation in #42156 didn't fix this issue?

https://github.com/JuliaLang/julia/pull/42156#issuecomment-920547584

maybe there is some other code that's needs to be precompiled on the worker end that isn't precompiled by just calling `@everywhere 1+1` or the other lines in `generate_precompile.jl`?

**Comment by moble** [comment]
Maybe.  I don't know how julia's own build process works; maybe the image you used isn't being built with multiple processes.

Also, I'll point out that in the workaround I linked above, I actually used the `--trace-compile` flag on both the primary julia process *and* the worker process, then combined the outputs in case the worker's output wasn't a subset of the primary's.  (I didn't actually check whether it was or not.)  I don't know whether or not julia does this when building itself.

**Comment by carlocastoldi** [comment]
Is it possible that his bug also affects [`MPI.jl`](https://github.com/JuliaParallel/MPI.jl)?
I have built a framework that revolves around MPI calls to synchronize I/O operations over all HPC nodes. With few nodes (e.g. 4) it works like charm, but as soon I go up to 50/100 nodes it just becomes unbearable.

`@everywhere` calls doesn't seem to be the cause this time since I'm using @moble 's trick, but I'm now starting to think it's the MPI calls' fault.
I tried to add to the precompilation the `MPI` calls i'm using, but it doesn't seem to work.
I did it by adding `:MPI` in `create_sysimage()` call in `precompile.jl`. Then in `precompile_everywhere.jl` I wrote the calls i use:
```julia
# all precompile(...) calls
function main()
    MPI.Initialized()
    MPI.Init(threadlevel=:multiple)
    base_comm = MPI.COMM_WORLD
    print(" comm size: $(MPI.Comm_size(base_comm)) ---")
    base_grp = MPI.Comm_group(base_comm)
    id_group = MPI.Group_incl(base_grp, Int32[0])
    comm = MPI.Comm_create_group(base_comm, id_group, 42)
    MPI.Barrier(base_comm)
    fh = MPI.File.open(comm, "path/to/file/foo.bar"; append=true, write=true, create=true)
    MPI.File.seek_shared(fh, 0)
    MPI.File.write_ordered(fh, Int32[42,420])
    MPI.File.write_at_all(fh, 1, Int32[69])
    MPI.File.write_at(fh, 0, Int32[1])
    close(fh)
end

main()
```

And I then just execute `julia precompile.jl precompile`.
Do you have any idea? It seems like even doing `MPI.Init()` on 100 nodes takes ~1 hour....

**Comment by giordano** [comment]
> Is it possible that his bug also affects MPI.jl?

Unlikely, since `MPI.jl` has nothing to do with the `Distributed` standard library.  You may want to report the issue to the `MPI.jl` repository, but you have to provide more details about your system.

**Comment by carlocastoldi** [comment]
> Unlikely, since MPI.jl has nothing to do with the Distributed standard library. You may want to report the issue to the MPI.jl repository, but you have to provide more details about your system.

Sure, thank you. I'm now trying investigating on it so that i have more informations about it
