### ISSUE TITLE
zero-argument getindex method in Base incorrectly assumes 1-based indexing

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#39379]
It seems that the bounds check used in `Base` for zero-dimensional indexing hardcodes a comparison to `1`, assuming one-based indexing.

This means that an array with nonstandard axes can successfully pass the bounds check and then access out-of-bounds memory when indexing. I encountered this in an [issue](https://github.com/JuliaArrays/OffsetArrays.jl/issues/194) on OffsetArrays and @jishnub tracked it down to this line in `Base`:

https://github.com/JuliaLang/julia/blob/69d24532980bda6db510b6d4b71f66e7ffff2e81/base/abstractarray.jl#L642

**Comment by jishnub** [comment]
The issue here is that `A[]` gets mapped to `A[1]`, and linear indexing for `AbstractVector`s should use their axes to obtain bounds on permissible indices. A 1-element `OffsetVector`s may have an axis `n:n` for an arbitrary `n`, in which case `1` is not a valid index. Perhaps the best solution is to add a special method `checkbounds_indices(::Type{Bool}, IA::Tuple{Any}, ::Tuple{})` that ensures that `IA[1]` begins at 1? This is the solution chosen in [the fix in `OffsetArrays`](https://github.com/JuliaArrays/OffsetArrays.jl/pull/195).

**Comment by mbauman** [comment]
No, that's working correctly.  That method gets hit if you index into a non-zero-dimensional array with zero indices.  It asserts that all axes have **length** 1.

The problem is not in the bounds checking, but rather in the `getindex`.

**Comment by mbauman** [comment]
Here's the root problem:

https://github.com/JuliaLang/julia/blob/69d24532980bda6db510b6d4b71f66e7ffff2e81/base/abstractarray.jl#L1196

**Comment by yurivish** [comment]
Thanks for debugging this further @mbauman. I think my original issue title is incorrect; I've changed it to what I think is an appropriate description; feel free to change if there's a better or more correct title.

**Comment by jishnub** [comment]
This is great! I wonder if a similar fix might be applied to #37274?
