### ISSUE TITLE
Unable to download any files using Julia 1.6 beta

### ISSUE THREAD

**Issue by haozhangphd** [JuliaLang/julia#39430]
```
julia> versioninfo()
Julia Version 1.6.0-beta1.0
Commit b84990e1ac (2021-01-08 12:42 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) CPU i7-6700 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```
when I try to download any files using `Base.download` or `Downloads.download`, I always get the following error message
```
julia> Base.download("https://github.com")
ERROR: HTTP/1.1 200 Connection Established (schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.) while requesting https://github.com
Stacktrace:
  [1] (::Downloads.var"#9#17"{IOStream, Base.DevNull, Nothing, Vector{Pair{String, String}}, Float64, Nothing, Bool, Bool, String, Int64, Bool, Bool})(easy::Downloads.Curl.Easy)
    @ Downloads C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Downloads\src\Downloads.jl:348
  [2] with_handle(f::Downloads.var"#9#17"{IOStream, Base.DevNull, Nothing, Vector{Pair{String, String}}, Float64, Nothing, Bool, Bool, String, Int64, Bool, Bool}, handle::Downloads.Curl.Easy)
    @ Downloads.Curl C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Downloads\src\Curl\Curl.jl:54
  [3] #8
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Downloads\src\Downloads.jl:298 [inlined]
  [4] arg_write(f::Downloads.var"#8#16"{Base.DevNull, Nothing, Vector{Pair{String, String}}, Float64, Nothing, Bool, Bool, String, Int64, Bool, Bool}, arg::IOStream)
    @ ArgTools C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\ArgTools\src\ArgTools.jl:112
  [5] #7
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Downloads\src\Downloads.jl:297 [inlined]
  [6] arg_read
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\ArgTools\src\ArgTools.jl:61 [inlined]
  [7] request(url::String; input::Nothing, output::IOStream, method::Nothing, headers::Vector{Pair{String, String}}, timeout::Float64, progress::Nothing, verbose::Bool, throw::Bool, downloader::Nothing)
    @ Downloads C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Downloads\src\Downloads.jl:296
  [8] (::Downloads.var"#3#4"{Nothing, Vector{Pair{String, String}}, Float64, Nothing, Bool, Nothing, String})(output::IOStream)
    @ Downloads C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Downloads\src\Downloads.jl:209
  [9] arg_write(f::Downloads.var"#3#4"{Nothing, Vector{Pair{String, String}}, Float64, Nothing, Bool, Nothing, String}, arg::Nothing)
    @ ArgTools C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\ArgTools\src\ArgTools.jl:101
[10] #download#2
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Downloads\src\Downloads.jl:208 [inlined]
[11] download(url::String, output::Nothing)
    @ Downloads C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Downloads\src\Downloads.jl:208
[12] #invokelatest#2
    @ .\essentials.jl:707 [inlined]
[13] invokelatest
    @ .\essentials.jl:706 [inlined]
[14] do_download
    @ .\download.jl:33 [inlined]
[15] download(url::String)
    @ Base .\download.jl:29
[16] top-level scope
    @ REPL[33]:1
```
As a result, I am not able to install any new packages that need to download artifact files.  **I have no issue with downloading files or installing packages when using Julia 1.5.3.**

Also it's worth noting that I am behind a corporate proxy.

**Comment by KristofferC** [comment]
The tests for Pkg also has problems on nightly julia: https://github.com/JuliaLang/Pkg.jl/pull/2354. cc @StefanKarpinski

**Comment by Rudi79** [comment]
Same for me on a Linux machine:
```
Julia Version 1.6.0-beta1
Commit b84990e1ac (2021-01-08 12:42 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, westmere)
```
```julia
julia> Base.download("https://github.com")
┌ Error: curl_easy_getinfo: 48
└ @ Downloads.Curl /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
ERROR: MethodError: no method matching status_ok(::Nothing, ::Int64)
Closest candidates are:
  status_ok(::AbstractString, ::Integer) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/Easy.jl:209
Stacktrace:
 [1] (::Downloads.var"#3#4"{Nothing, Vector{Pair{String, String}}, Float64, Nothing, Bool, Nothing, String})(output::IOStream)
   @ Downloads /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:219
 [2] arg_write(f::Downloads.var"#3#4"{Nothing, Vector{Pair{String, String}}, Float64, Nothing, Bool, Nothing, String}, arg::Nothing)
   @ ArgTools /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/ArgTools/src/ArgTools.jl:101
 [3] #download#2
   @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:208 [inlined]
 [4] download(url::String, output::Nothing)
   @ Downloads /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:208
 [5] #invokelatest#2
   @ ./essentials.jl:707 [inlined]
 [6] invokelatest
   @ ./essentials.jl:706 [inlined]
 [7] do_download
   @ ./download.jl:33 [inlined]
 [8] download(url::String)
   @ Base ./download.jl:29
 [9] top-level scope
   @ REPL[1]:1
```

**Comment by KristofferC** [comment]
@StefanKarpinski do you know if this is fixed on the backport branch/master? The comment above looks like an unhandled case in Downloads.jl.

**Comment by StefanKarpinski** [comment]
These are clearly different issues. The former looks like Windows having problems with certificate verification for some reason (possibly related to the corporate proxy). The latter may be a Downloads bug.

**Comment by StefanKarpinski** [comment]
The Linux issue is strange: there's a missing method for `status_ok(nothing, ::Integer)` but it shouldn't be possible to get to that point in the first place since that means that libcurl accepted the URL as something it could download but then later claimed that it has no idea what the protocol for that URL is. @Rudi79, have you built Julia with a system libcurl and if so, what version?

**Comment by StefanKarpinski** [comment]
Regarding the originally posted issue, it's the same issue as these StackOverflow questions:

- https://stackoverflow.com/questions/45556189/git-the-revocation-function-was-unable-to-check-revocation-for-the-certificate
- https://stackoverflow.com/questions/54938026/curl-unknown-error-0x80092012-the-revocation-function-was-unable-to-check-r/56486639

Basically, your corporate firewall is blocking Windows attempts to check for revoked certificates. Hopefully your firewall checks certificates for outgoing connections, including checking for revoked certificates. The firewall should ideally be configure to allow certificate revocation checks to work.

Since the certificates you're seeing are phony anyway, you can safely turn of host verification for connections to external hosts. This can be done by setting the following environment variables:
```sh
export JULIA_SSL_NO_VERIFY_HOSTS="**"
export JULIA_ALWAYS_VERIFY_HOSTS="**.company.com"
```
where `company.com` is replaced with the internal domain for your company. If that also causes problems — Windows may still try to check for certificate revocation and fail — you can probably omit the second line and just skip TLS host verification for all domains since it's unlikely that someone (besides your company's firewall) is trying to man-in-the-middle your internal HTTPS requests.

**Comment by StefanKarpinski** [comment]
The original issue here is addressed, but I'll leave this open to wait for answers from @haozhangphd and @Rudi79.

**Comment by StefanKarpinski** [comment]
Since it may not be clear, the reason that certificate revocation was not previously an issue was that in Julia ≤ 1.5 we were using MbedTLS for all HTTPS connections and MbedTLS does not support certificate revocation checking. That is a security problem (although a surprisingly widespread one), so for better security in 1.6 we have switched to using system TLS engines on macOS and Windows, which do implement certificate revocation checking.

**Comment by haozhangphd** [comment]
Thanks! That solves the issue. I was actually looking for such an environment variable to turn off certificate verification.

**Comment by StefanKarpinski** [comment]
https://github.com/JuliaLang/Downloads.jl/pull/90 fixes the method error on Linux and may give a better error message if the error is what I suspect it is.
