### ISSUE TITLE
scanf according to printf

### ISSUE THREAD

**Issue by jarau-de** [JuliaLang/julia#39440]
It would be a fundamental step ahead if Julia would support string line parsing like scanf of C. Julia claims to be a scientific programming language with features borrowed from Matlab and Python. In science one has to deal very often with ASCII files containing irregular data structures with a fixed format. Examples are GPS RINEX files and orbital data of SP3 files. That means there are no delimiters or table like structures so readdlm or dataframe are useless in these cases. It is rather easy to read such data with C or FORTRAN and it would be very nice to have these opportunities in Julia too.

**Comment by mgkuhn** [comment]
For some previous discussion on reading floating-point numbers from an IO buffer, as found in such ad-hoc ASCII data file formats, one at a time, see https://github.com/JuliaIO/Formatting.jl/issues/21 and [Extracting a float from a string](https://discourse.julialang.org/t/extracting-a-float-from-a-string/43126/8).

I'd agree this is a fairly common requirement, also when receiving ASCII serial-port data from instruments, where there may be a wide range of terminating/separating characters in use.

It would be nice if the user didn't always have to manually perform the steps of
* separating the data fields into individual strings
* feeding them into `parse`

but if there were instead a scanf-like convenience function that could do both in one go, controlled by a single format string. Also for parsing dates and times, where there is [Dates.DateFormat](https://docs.julialang.org/en/v1/stdlib/Dates/#Dates.DateFormat), but probably no function to parse one directly from an `IO` stream.

I wonder if one underlying problem is that there isn't at the moment yet a clearly defined [interface](https://docs.julialang.org/en/v1/manual/interfaces/) for `IO` streams, and in particular that `IO` implementations are not yet all required to implement a method to allow parsers to look ahead a bit of what comes next, along the lines of [peek](https://docs.julialang.org/en/v1/base/io-network/#Base.peek) or C's `ungetc()`, without actually consuming these bytes.

**Comment by StefanKarpinski** [comment]
No reason this can't be implemented in an external package. If not for history, `Printf` would be external also.

**Comment by KlausC** [comment]
Coming soon: [Scanf](https://github.com/KlausC/Scanf.jl)

**Comment by KlausC** [comment]
Scanf v0.2.0 is registered and ready to be tested by the community
