### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by mkschulze** [JuliaLang/julia#39526]
Just leaving this feature request here to raise some awareness and maybe get some feedback if this could be officially implemented in Julia to serve general purposes and lift the baseline for other community projects using such a standard.

GOlang also has this in their [stdtlib](https://pkg.go.dev/golang.org/x/net/http2).

**Comment by jpsamaroo** [comment]
This is not something that needs to be in Base Julia or a stdlib, this should go in HTTP.jl or another such third-party library.

**Comment by mkschulze** [comment]
But isn’t it also a stream I/O object along with socket etc?

**Comment by DilumAluthge** [comment]
There are two different discussions to have here:
1. HTTP/2 support in Julia standard libraries, such as the `Downloads` stdlib and the `LibCURL` stdlib.
2. HTTP/2 support in external packages, such as the [HTTP.jl](https://github.com/JuliaWeb/HTTP.jl) package.

For the latter, I recommend opening an issue on the relevant external packages.

For the former, maybe @StefanKarpinski or @staticfloat can give a brief summary of the current level of HTTP/2 support in the stdlibs that ship with Julia (`LibCURL_jll`, `LibCURL`, `Downloads`, etc.).

**Comment by DilumAluthge** [comment]
Possibly related: https://github.com/JuliaLang/NetworkOptions.jl/issues/15

**Comment by mkschulze** [comment]
Just on a sidenote, it looks like HTTP/2 would be a prerequisite for a gRPC library for example and it would be great to have a reliable solution for this. If @StefanKarpinski or @staticfloat could maybe find a word about the possibility to use `LibCurl` or the `Downloads` stlib in that context that would help a lot. If this is too specific for this issue, then I apologise and will request in a different channel. Thx

**Comment by staticfloat** [comment]
So `LibCURL.jl` (and hence `Downloads`, which uses `LibCURL.jl` internally) supports HTTP/2.  If you connect to a server that supports HTTP/2, your normal connections will be automatically upgraded to HTTP/2:

```julia
julia> Downloads.download("https://google.com", devnull; verbose=true);
* 17 bytes stray data read before trying h2 connection
* 17 bytes stray data read before trying h2 connection
* Found bundle for host google.com: 0x55fd70b65230 [can multiplex]
* Re-using existing connection! (#0) with host google.com
* Connected to google.com (172.217.14.238) port 443 (#0)
* Using Stream ID: 3 (easy handle 0x55fd70e61100)
> GET / HTTP/2
Host: google.com
accept: */*
user-agent: curl/7.73.0 julia/1.6

< HTTP/2 301 
< location: https://www.google.com/
< content-type: text/html; charset=UTF-8
< date: Fri, 05 Feb 2021 18:15:24 GMT
< expires: Sun, 07 Mar 2021 18:15:24 GMT
< cache-control: public, max-age=2592000
< server: gws
< content-length: 220
< x-xss-protection: 0
< x-frame-options: SAMEORIGIN
< alt-svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
< 
* Ignoring the response-body
* Connection #0 to host google.com left intact
* Issue another request to this URL: 'https://www.google.com/'
* Found bundle for host www.google.com: 0x55fd70bae570 [can multiplex]
* Re-using existing connection! (#1) with host www.google.com
* Connected to www.google.com (142.250.69.196) port 443 (#1)
* Using Stream ID: 3 (easy handle 0x55fd70e61100)
> GET / HTTP/2
Host: www.google.com
accept: */*
user-agent: curl/7.73.0 julia/1.6

< HTTP/2 200 
< date: Fri, 05 Feb 2021 18:15:24 GMT
< expires: -1
< cache-control: private, max-age=0
< content-type: text/html; charset=ISO-8859-1
< p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
< server: gws
< x-xss-protection: 0
< x-frame-options: SAMEORIGIN
< set-cookie: 1P_JAR=2021-02-05-18; expires=Sun, 07-Mar-2021 18:15:24 GMT; path=/; domain=.google.com; Secure
< set-cookie: NID=208=nEo8bUj0k8F4Sm9VKDlnIxwc-FNmeVlAVcwzCwE2EJ1y706EKd8lLA4pWDTnoT34uwLsmFwTaX9uOHgSqou3y26ury6_0xCSEFsUPfbRyyJT4bhSbLiNZgno9MjZ7l6Fuw2TPu9fIJj9eBRcizEJacydL3bXKEm_K2CcnicjsRE; expires=Sat, 07-Aug-2021 18:15:24 GMT; path=/; domain=.google.com; HttpOnly
< alt-svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
< accept-ranges: none
< vary: Accept-Encoding
< 
* Connection #1 to host www.google.com left intact
```

[`LibCURL.jl`](https://github.com/JuliaWeb/LibCURL.jl) has some pretty fine-grained levers that you can pull to control how downloads are working if you're into that, but if all you want is a way to easily download things and take advantage of HTTP/2 when it is available, just using [`Downloads.jl`](https://github.com/JuliaLang/Downloads.jl/) should be more than enough for your needs.

If you want to write an HTTP/2 server, you'll need `HTTP.jl` support, and I don't know what the status of that is.  Since HTTP/2 is (with very few exceptions) encrypted over TLS, I would suggest using an HTTPS terminator (e.g. `nginx`) instead of trying to do the whole thing in Julia, and just speaking `HTTP/1.1` between the terminator and the server, then speaking `HTTP/2` between the terminator and the client.  This is, for instance, [how the Pkg servers](https://github.com/JuliaPackaging/PkgServer.jl/blob/master/deployment/conf/pkgserver.nginx.conf) are architected.

**Comment by mkschulze** [comment]
We want to connect to a gRPC server with a client library. So the server is already in place, we just need to make it talk to our Julia code. Thanks for the reply!

**Comment by DilumAluthge** [comment]
Since we already have HTTP/2 support, I'll close this issue.
