### ISSUE TITLE
Integrate Julia with Windows Terminal

### ISSUE THREAD

**Issue by scls19fr** [JuliaLang/julia#39535]
Hello,

Windows now have a better terminal named "Windows Terminal"
It's mentionned at https://julialang.org/downloads/platform/#windows
and it have been discussed at https://discourse.julialang.org/t/new-windows-terminal/23968 and https://discourse.julialang.org/t/windows-terminal-announcement/23929/8

This terminal can be found at
https://aka.ms/terminal

Unfortunately integrating julia with this terminal needs some manual tweaking such as editing `settings.json` file.

```json
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    // ...

    "profiles":
    {

        // ...

        "list":
        [

            // ...

            {
                "guid": "{e6986b05-9131-4eea-857a-d8e1e1e45c34}",
                "name": "Julia 1.5.3",
                "icon": "%USERPROFILE%\\AppData\\Local\\Programs\\Julia 1.5.3\\share\\icons\\julia.ico",
                "commandline": "%USERPROFILE%\\AppData\\Local\\Programs\\Julia 1.5.3\\bin\\julia.exe",
                "hidden": false
            }
        ]
    },

    // ...

}
```

And copying `julia.ico` ([from here](https://github.com/JuliaLang/julia/blob/master/contrib/windows/julia.ico)) into appropriate directory.

Maybe this could be done automatically by Julia Windows installer.

An other part of this integration job of Julia with Windows Terminal could be to have Julia application directly run Windows Terminal (instead of the old `cmd` terminal)

Kind regards

**Comment by stevengj** [comment]
> An other part of this integration job of Julia with Windows Terminal could be to have Julia application directly run Windows Terminal (instead of the old cmd terminal)

Since Windows Terminal is not installed by default, we can't assume it is present in our installer.  See also #7267.

**Comment by jebej** [comment]
If Windows Terminal is detected to be installed, how hard would it be to have `julia.exe` use it automatically?

**Comment by davidanthoff** [comment]
I think the proper way to do this is via the upcoming proto extension support in Windows Terminal, see [here](https://github.com/microsoft/terminal/blob/64666b22fba7584158cd1029d47083d5b59a212b/doc/specs/Proto%20extensions-spec.md). My understanding is that this has been merged, but not entirely clear whether this is shipping already or not.

I'm having another go at finishing https://github.com/JuliaLang/julia/issues/36672, and I think if I can bring that over the finishing line it would make most sense to do this things as part of that because I think it will be easier to distribute these proto extensions via the store.

**Comment by davidanthoff** [comment]
Actually, they only merged the spec, not the implementation :) But https://github.com/microsoft/terminal/pull/7632 is the PR that would merge this into Windows Terminal, and it seems pretty active and close to being merged.

**Comment by davidanthoff** [comment]
I believe the proto extension stuff is now shipping in Windows Terminal Preview 1.7, and with their normal release timing I would expect that to ship to everyone in about a month.

The documentation for it is [here](https://docs.microsoft.com/en-us/windows/terminal/json-fragment-extensions).  I think essentially the installer would need to place a file at `C:\Users\<user>\AppData\Local\Microsoft\Windows Terminal\Fragments\{app-name}` for user installs (I think that is the only option we support in any case) or `C:\ProgramData\Microsoft\Windows Terminal\Fragments\{app-name}` for system installs. The instructions are to create those folders if they don't yet exist, so I think with this we wouldn't need a check whether Windows Terminal is already installed or not.

One important thing would probably be to make sure we name these files (and also the name of the profile) with the full version number of Julia, say `Julia 1.5.3`, so that this creates a separate entry for every Julia version one has installed at the same time. Just for users like me who have every version of Julia since, well, way back, installed :)

**Comment by davidanthoff** [comment]
Just a quick FYI: I managed to publish my MSIX installer in the Windows Store now, and it automatically adds a profile for Julia to Windows Terminal via this fragment stuff.

The store version of Julia is not yet listed (too WIP at the moment) but you can get a direct link to the store listing at https://github.com/davidanthoff/winjulia.

**Comment by ViralBShah** [comment]
It seems that nowadays there are plenty of options for people to pick better terminals in windows, and I usually just use VS Code there. Do we still want to leave this issue open?

**Comment by davidanthoff** [comment]
Yes, I think this can be closed. Two things: a) on Windows 11 one can configure a default terminal, including the new Windows Terminal. If done, just clicking the Julia icon in the start menu launches it in the Windows terminal. b) The windows store distribution of Julia automatically adds a Julia profile to Windows Terminal.

I think beyond that there aren't really any further useful integration points.
