### ISSUE TITLE
[aarch64] 1.6.0-rc1 binary is built against glibc 2.18 instead of 2.17

### ISSUE THREAD

**Issue by samhatfield** [JuliaLang/julia#39675]
I seem to have a similar issue to #39178 but with aarch64:
```
$ ./julia-1.6.0-rc1/bin/julia
ERROR: Unable to load dependent library <redacted>/julia-1.6.0-rc1/bin/../lib/julia/libjulia-internal.so.1
Message: <redacted>/julia-1.6.0-rc1/bin/../lib/julia/libstdc++.so.6: symbol __cxa_thread_atexit_impl, version GLIBC_2.18 not defined in file libc.so.6 with link time reference
```
The message isn't the same but I think the cause is: I only have glibc 2.17 installed. I'm using CentOS:

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (AltArch)"
...
```
glibc version 2.17 is indeed installed:
```
$ rpm -qi glibc
Name        : glibc
Version     : 2.17
Release     : 260.el7
Architecture: aarch64
...
```

Could I ask for this to be looked into again? Presumably the suggested change in #39178, to use CentOS 7 as the base image for the build bots, would fix it. But I guess that wasn't done in rc1.

Thanks.

**Comment by staticfloat** [comment]
Unfortunately, the issue here is more complex than #39178.  While I did just look into how hard it will be to move the buildbots back to CentOS 7, the problem runs deeper; all of the binaries we ship as part of JLLs are built against glibc 2.19, because that was the earliest version our build team could get reliably cross-compiling on Linux targeting aarch64.  It's possible that there are now widespread patches that we could borrow to improve the situation, but as it stands, this is definitely too much effort to fix for 1.6, and unless someone is willing to help out with adjusting [the GCC compiler shard configuration in BinaryBuilder](https://github.com/JuliaPackaging/Yggdrasil/blob/master/0_RootFS/gcc_common.jl#L202-L206), I don't think we are going to fix this for 1.7 either.

**Comment by samhatfield** [comment]
No problem - thanks for looking into it already. I guess manual compilation is the way forward for me.

Incidentally, the ARM system I'm working on is Fugaku, so there is certainly interest in running Julia on the #1 machine.

**Comment by Keno** [comment]
I followed up with RIKEN on this and they told me the glibc version was supposed to be 2.28. Could you elaborate what you're trying here. I personally don't currently have access, so I'm just playing soundpipe here ;).

**Comment by samhatfield** [comment]
Yeah I should have clarified: the login nodes (x86_64) use glibc 2.28, but the compute nodes (aarch64) use glibc 2.17, as far as I can tell. That's where I'm trying to run Julia from.
