### ISSUE TITLE
Incosistent output in single precision

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#39732]
I expected a more consistent output, can it be fixed?

```julia
julia> t = (1.0f0, 1.0f0)
(1.0f0, 1.0f0)

julia> println(stdout, t)
(1.0f0, 1.0f0)

julia> println(stdout, t[1])
1.0
```

Either by eliminating the `f0` suffix from the tuple or adding it to the single float.

I am on Julia v1.6-beta1

**Comment by KristofferC** [comment]
> Define print if your type has a separate "plain" representation.

Floats do have a special plain representation while tuples do not. I don't really understand the problem here.

**Comment by juliohm** [comment]
I don't know, maybe the tuple could print exactly the same output one would get from printing each entry individually?

I have types for example like a Ball(center, radius) where center is a tuple and radius is a float, when I print it I get this strange output:

```julia
Ball((0.0f0, 0.0f0), 1.0)
```

Someone reading this may think the radius and center coordinates have different type due to a bug in the type constructor.

**Comment by simeonschaub** [comment]
You should probably use `show` instead of `print` for showing objects like this.

**Comment by juliohm** [comment]
Can you advise on how to rewrite this method for example?

```julia
function Base.show(io::IO, b::Ball{Dim,T}) where {Dim,T}
  c, r = b.center, b.radius
  print(io, "Ball{$Dim,$T}($c, $r))")
end
```

**Comment by simeonschaub** [comment]
Use

```julia
print​(io, ​"​Ball{​$Dim​,​$T​}(")
show(​io, c​)
print(io, ",  ")
show(io, r​)
print(io, ")​"​)
```

Please ask further questions on discourse though.

**Comment by juliohm** [comment]
So this issue shouldn't be fixed?

**Comment by juliohm** [comment]
Isn't the behavior cumbersome? Don't you feel that this print method you wrote above is too verbose? Imagine a more complicated data structure...

**Comment by simeonschaub** [comment]
I am not sure what you are proposing, like Kristoffer explained above, `print` and `show` both have a different purpose. It would of course be possible to write a custom string macro which always uses `show` for interpolation, if you really want that syntax, but I don't see a very strong reason for this to be in Base. It probably doesn't matter much most of the time, but note that using interpolation here is also less efficient, since it allocates a new string. Perhaps we could document the differences between `print` and `show` a bit better though.

**Comment by JeffBezanson** [comment]
Usually you should not even write `show` methods like that, since the default ought to work fine. The code is a bit cumbersome because wanting to print in julia syntax, but not the default format, is a marginal use case --- most of the time it's best to either use the default, or else define a more user-friendly, non-julia-syntax output format.

**Comment by JeffBezanson** [comment]
Also note that `print(io, "$object")` is a bit of an anti-pattern, since the stringification of `object` can't see the output settings inside `io`. Doing that will generally give objects that misbehave in printing.
