### ISSUE TITLE
printf output - change from 1.5.3 to 1.6.0-rc1

### ISSUE THREAD

**Issue by GregPlowman** [JuliaLang/julia#39748]
I have been using the following code to verify that I can "roundtrip" `Float64` values.
This succeeds on Julia `v1.5.3` but fails on `v1.6.0-rc1`:
```
using Printf
x = 194.4778127560983
@assert parse(Float64, @sprintf("%20.17g", x)) == x
```

|  | Julia v1.5.3 | Julia v1.6.0-rc1 |
| -- | -- | -- |
| `@printf("%20.16g", x)` | `194.4778127560983` |  `194.4778127560983` |
| `@printf("%20.17g", x)` | `194.4778127560983` | `194.47781275609833` |
| `@printf("%20.18g", x)` | `194.477812756098302` | `194.4778127560983` |

Is there a way to print a `Float64` value that guarantees the same value when parsed back?
I thought `@sprintf("%20.17g", x)` worked on previous Julia versions, but I might have just been very lucky.

EDIT:
Oh, `string(x)` would be what I'm after.
In particular, `@sprintf("%20s", string(x))`

I guess `printf` changing between Julia versions is not a problem?

**Comment by GregPlowman** [comment]
But I'd like values to be printed using decimal notation (rather than exponential notation):
```
using Printf
x = 408689256889.24097
@sprintf("%20s", string(x)) # "4.0868925688924097e11"
@sprintf("%20.17g", x)      # "  408689256889.24097"
```

Is there a way to print `Float64` values in decimal notation so that they can be parsed back as the same value?

**Comment by quinnj** [comment]
It seems like just `@printf("%g", x)` is what you're after, which by definition is: "Use the shortest representation: %e or %f", but is used to allow round-tripping/parsing back as the same value. When you start specifying precision/scale numbers, there are probably algorithmic corner cases between previous Julia versions and current (current should have _better_ coverage of corner cases), which try to force a specified length and such.

What is the decimal notation requirement? Just personal preference? If you need to avoid exponential notation, then it's harder because you have cases like:
```julia
(str="1.00000000000000011102230246251565404236316680908203125", x=1.0, code=(OK | EOF), len=0, tot=0),
    # # Slightly lower; still round down.
    (str="1.00000000000000011102230246251565404236316680908203124", x=1.0, code=(OK | EOF), len=0, tot=0),
    # # Slightly higher; round up.
    (str="1.00000000000000011102230246251565404236316680908203126", x=1.0000000000000002, code=(OK | EOF), len=0, tot=0),
```
where you need, what, like precision of 50 or so in order to capture the slight rounding difference. 

But I feel like I'm not totally understanding the full context of the use-case here.

**Comment by JeffBezanson** [comment]
It looks like the last digit of the `%20.17g` output is incorrect though?

**Comment by GregPlowman** [comment]
I guess there are two distinct questions here (my apologies for conflating the two):

1. Is the output of `@printf("%.17g")` correct according to definition of this format?
2. What are the options for round-tripping (and is there an option to round-trip using decimal notation)

Regarding question 1, I think the output of `%.17g` looks incorrect. It seems to have an extra digit. It's also different from the seemingly correct output from `Julia v1.5.3`.

> It seems like just @printf("%g", x) is what you're after

this seems to print 6 significant digits? 
```
Julia-1.6.0-rc1> @printf("%g", 194.4778127560983)
194.478
Julia-1.6.0-rc1> @printf("%g", 1944.778127560983)
1944.78
```

**Comment by quinnj** [comment]
It looks like in this specific case, our use of `round(x, sigdigits=prec)` is producing the extra `'3'` digit:
```julia
julia> round(194.4778127560983, sigdigits=17)
194.47781275609833
```
@simonbyrne, any insight into what's going on here? I know the old grisu code didn't rely on rounding at all; are we asking for bugs by using `round` before we [send the float to Ryu](https://github.com/JuliaLang/julia/blob/f2b5b6e3d45fb12369336814b6be08a035c07b7c/stdlib/Printf/src/Printf.jl#L426) to be formatted?

**Comment by simonbyrne** [comment]
> are we asking for bugs by using round before we send the float to Ryu to be formatted?

Yes, since we can't represent the round with digits/sigdigits exactly, it is probably not a good idea.

There is a disclaimer in the docs, but it's a little unclear: https://docs.julialang.org/en/v1/base/math/#Base.round-Tuple%7BType,Any%7D

**Comment by simonbyrne** [comment]
Another problem with the current approach is that it doesn't handle excess precision correctly, i.e. in Julia 1.5:
```
julia> @printf("%.23g\n", x)
194.47781275609830231588
```
in 1.6 beta:
```
julia> @printf("%.23g\n", x)
194.47781275609827
```

In the 2011 C standard it is defined as:
> A double argument representing a floating-point number is converted in style f or e (or in style F or E in the case of a G conversion specifier), depending on the value converted and the precision. Let P equal the precision if nonzero, 6 if the precision is omitted, or 1 if the precision is zero. Then, if a conversion with style E would have an exponent of X :
— if P > X ≥ −4, the conversion is with style f (or F) and precision P − (X + 1).
— otherwise, the conversion is with style e (or E) and precision P − 1.
Finally, unless the # flag is used, any trailing zeros are removed from the fractional portion of the result and the decimal-point character is removed if there is no fractional portion remaining.

**Comment by simonbyrne** [comment]
I think the easiest way forward would be to modify `writeexp` to handle this: it already has a `trimtrailingzeros` option, the main change it would need is to detect when the exponent is in the relevant range and print it in fixed format.

**Comment by bicycle1885** [comment]
Yet another problem of `round`ing a float before formatting is that it cannot correctly format values larger than the largest normal number:

```
julia> x = prevfloat(typemax(Float64))
1.7976931348623157e308

julia> @sprintf "%.1g" x  # expected: "2e+308"
"0"

julia> @sprintf "%.2g" x  # expected: "1.8e+308"
"0"
```
