### ISSUE TITLE
header=true, skips 2 lines

### ISSUE THREAD

**Issue by joseph-pollacco** [JuliaLang/julia#39831]
When I use

`Data, Header=  DelimtedFiles.readdlm(path,',',header=true)`

In the data it skips 2 lines instead of 1.

**Comment by stillyslalom** [comment]
Without a full example, this is hard to diagnose - can you provide a small example CSV file that reproduces this behavior?

**Comment by stillyslalom** [comment]
Did you figure this out? If so, can you close the issue?

**Comment by jishnub** [comment]
This issue was discussed and resolved on discourse. The issue was not that 2 lines were being skipped, it was that the numbers were being read in as `Float64` and therefore the values on the first line were being rounded, so they seemed equal to those on the second line. The solution was to either read them in as `Int`s or `Any` in `readdlm` or to use CSV.jl.
