### ISSUE TITLE
What is the proper way to use include and using statements

### ISSUE THREAD

**Issue by pjuangph** [JuliaLang/julia#39958]
This is not very helpful. Coming from python, Julia's using, import, include statements are confusing. In my GitHub example, it isn't clear what the proper way to reference types in other files is. 

"Yes, you are including `DataTestTypes.jl` both in `Connectivity.jl` and `run_me.jl`, which creates separate modules with two different structs called `Block`. This is the expected behavior for `include`." 

https://github.com/JuliaLang/julia/issues/39957#issuecomment-793200170 

_Originally posted by @simeonschaub in https://github.com/JuliaLang/julia/issues/39957#issuecomment-793203092_

**Comment by sostock** [comment]
See the links in [this Discourse post](https://discourse.julialang.org/t/modules-and-namespaces/45027/5) for some threads on how to avoid `include`ing the same file multiple times. For the future, it’s recommended to ask such questions about using Julia on Discourse instead of opening an issue.

> Coming from python, Julia's using, import, include statements are confusing.

FYI, `using` and `import` are quite different from `include`. The former two make code from a module available in the current namespace, while `include` (which is just an ordinary function) evaluates code from a file. The `include`d file does not have to contain any modules. Generally, there is no correspondence between *modules* and *files* in Julia: you can include files that do not contain modules, you can have modules that are spread across several files, and you can define several modules in a single file.
