### ISSUE TITLE
New Julia installation overwrites Windows uninstall entry

### ISSUE THREAD

**Issue by jebej** [JuliaLang/julia#40004]
I installed Julia 1.5.4 and 1.6.0-rc2 one after the other, and the entry in the "Programs and Features" / "Apps and feature" menus for 1.5.4 was removed and replaced by the one for 1.6.0-rc2.

I assume this is probably caused by some registry key being overwritten.

**Comment by jaakkor2** [comment]
Inno Setup `AppId` is defined here for v1.6.0-rc3 https://github.com/JuliaLang/julia/blob/v1.6.0-rc3/contrib/windows/build-installer.iss#L5-L7
```
#ifndef AppId
#define AppId "{{054B4BC6-BD30-45C8-A623-8F5BA6EBD55D}"
#endif
```
and here for v1.5.4 https://github.com/JuliaLang/julia/blob/v1.5.4/contrib/windows/build-installer.iss#L48
```
AppId={{054B4BC6-BD30-45C8-A623-8F5BA6EBD55D}
```
The `AppId` is the same.  Docs say https://jrsoftware.org/ishelp/index.php?topic=setup_appid
> AppId also determines the actual name of the Uninstall registry key, to which Inno Setup tacks on "_is1" at the end.

Julia v1.6.0 has the possibility to pass the `AppId` from the Makefile, but that option is not used
https://github.com/JuliaLang/julia/blob/v1.6.0-rc3/Makefile#L429-L432
```
exe:
	# run Inno Setup to compile installer
	$(call spawn,$(JULIAHOME)/dist-extras/inno/iscc.exe /DAppVersion=$(JULIA_VERSION) /DSourceDir="$(call cygpath_w,$(BUILDROOT)/julia-$(JULIA_COMMIT))" /DRepoDir="$(call cygpath_w,$(JULIAHOME))" /F"$(JULIA_BINARYDIST_FILENAME)" /O"$(call cygpath_w,$(BUILDROOT))" $(INNO_ARGS) $(call cygpath_w,$(JULIAHOME)/contrib/windows/build-installer.iss))
	chmod a+x "$(BUILDROOT)/$(JULIA_BINARYDIST_FILENAME).exe"
```
Indeed, my Windows registry has a key
`Computer\HKEY_USERS\...\Software\Microsoft\Windows\CurrentVersion\Uninstall\{054B4BC6-BD30-45C8-A623-8F5BA6EBD55D}_is1`
and Julia versions using the same uninstall key _is_ the issue here.

If I understood correctly, Inno Setup `AppId` does not have to look like GUID/uuid4, but can be plain text, so maybe `AppId` could be `AppNameLong` to prevent the issue?

CC'ing @musm and @staticfloat as they have written or edited the lines in question.

**Comment by strickek** [comment]
Dup of #36933?

**Comment by musm** [comment]
yep closed as dupe
