### ISSUE TITLE
Shell Issue!

### ISSUE THREAD

**Issue by osdenprog** [JuliaLang/julia#40016]
I want report an error issue of the **Julia REPL-shell** that still exiting.

Kindly refer to the screenshots attached about this error.

I use always the latest stable Julia version and at the moment it’s _v.1.5.4_ on _**(windows terminal)**_ but the same issue exists too on _**(Julia REPL-shell)**_ and on _**(Windows command line)**_ and in _**(Powershell)**_ too.

**The issue:**
When I enter to Julia REPL I use **( ; )** to enter to the shell inside Julia then if I run the command _(clear)_ as example, it appears the strange **[system escape character]** instead of clearing the screen. The same problem happening if I hit _(Ctrl+L)_ or any other system command into the Julia-shell.  

![1e](https://user-images.githubusercontent.com/62112113/111063949-18376880-84ba-11eb-9f01-891387507b2d.png)
![2e](https://user-images.githubusercontent.com/62112113/111063950-1a99c280-84ba-11eb-99af-d2ca90871efb.png)

**Comment by mgkuhn** [comment]
I can't reproduce this with Julia 1.6.1 on Windows 10 Version 21H1. When I type `;clear` into the Julia REPL there, I get
```
ERROR: IOError: could not spawn `clear`: no such file or directory (ENOENT)
```
This is as I would expect, because there isn't any `clear.exe` program shipping with Windows 10. There are built-in `cls`, `clear` and `clear-host` commands in CMD.EXE and PowerShell, respectively, but the Julia 1.6 REPL shell mode does not pass on strings to any such shell. It instead merely runs programs in a way similar to how a POSIX shell would do it. You therefore can't use built-in CMD.EXE or PowerShell commands directly from within Julia 1.6, unless you explicitly invoke such a shell and pass the shell-command command to it, e.g. with
```
shell> powershell -Command clear
```
which works fine for me (i.e., clears the screen without messing up ESC sequence interpretation).

Do you have some 3rd-party tool called `clear.exe` installed in your path?
What does `(get-command clear).path` show in PowerShell?

Is it possible that such a 3rd-party tool disables the [`ENABLE_VIRTUAL_TERMINAL_PROCESSING`](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) flag at the end (rather than restoring it to its initial value), and therefore tells Windows Terminal that it should become more like MS-DOS and not interpret VT100 ESC sequences? I suspect this is what might be happening here. If so, I would suggest you file a bug report with the author of your `clear` program, or simply stop calling it from within the Julia REPL.

(As a workaround, I guess the Julia REPL could call `SetConsoleMode` each time before it displays a prompt to re-enable the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag, just in case someone else has messed with it.)

**Comment by ViralBShah** [comment]
Dup of #23597
