### ISSUE TITLE
Proposal: Do not specialize functions and types in kwsorter

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#40167]
This issue was raised on Slack by Elias Börjesson (@lijas), with the following example:

```
struct Foo
    x::Function
    Foo(; x::Function) = new(x)
end

@time Foo(x=n -> n + 1)
@time Foo(x=n -> n + 1)
```
Even at the second (and third, and fourth etc) timing, `Foo(x=n -> n + 1)` will re-compile. This does not happen if the constructor uses positional arguments, not keyword arguments.

I think what happens is that the kwsorter function specializes on its keywords. Presumably, this happens because [new functions and types by default do not incur recompilation unless used in in functions](https://docs.julialang.org/en/v1/manual/performance-tips/#Be-aware-of-when-Julia-avoids-specializing).

I suggest extending this non-specialization to the kwsorter function. Although I don't know to which extent this would make keyword arguments slow. If it makes the kwsorter function slower when the keywords are statically known, it's not worth it.

**Comment by JeffBezanson** [comment]
Right, this is tricky because we create a new type of NamedTuple to hold the arguments before calling the sorter. As you guessed, we need to specialize on that type in general to optimize keyword sorting. In theory we could specialize that slot on `@NamedTuple{x::T} where T<:Function`; maybe that could be hacked in just for keyword sorters, but it's pretty fancy. Especially if we want to restrict it to cases where the user declares `x::Function`. That's hard because we have to somehow plumb in information from a totally separate method. But if we don't restrict it, some cases will get slower. So this ends up being a significant headache to avoid a pretty small amount of compilation.

**Comment by jakobnissen** [comment]
Right, that doesn't make a lot of sense, and the gain would be too minor to special-case it.
