### ISSUE TITLE
Behavior of BroadcastFunction is inconsistent for ranges

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#40309]
The docstring for `Base.BroadcastFunction` says that it

> Represents the "dotted" version of an operator, which broadcasts the operator over its arguments, so BroadcastFunction(op) is functionally equivalent to (x...) -> (op).(x...).

Except for ranges

```julia
julia> f = +
+ (generic function with 190 methods)

julia> Broadcast.BroadcastFunction(f)(2:3, 2:3)
2-element Vector{Int64}:
 4
 6

julia> f.(2:3, 2:3)
4:2:6
```

The values are still equal, as we may check with 

```julia
julia> Base.BroadcastFunction(+)(2:3, 2:3) == (2:3) .+ (2:3)
true
```

however the types are different. The `BroadcastFunction(+)` version also allocates whereas the `.+` version doesn't.

**Comment by simeonschaub** [comment]
Ah, the problem is that `Base.broadcasted_kwsyntax` replaces `+` with a closure, so because ranges only intercept `Base.broadcasted(+, ...)`, `.+(...; kwargs...)`, which is what `BroadcastFunction` actually calls, doesn't get intercepted: 
https://github.com/JuliaLang/julia/blob/878e1cd52ebf14e8666d8d54a54a95ccee4405d3/base/broadcast.jl#L1303
We could just special-case `isempty(kwargs)` here, which would be a simple enough fix. Alternatively, we can also just remove support for `kwargs` from `BroadcastFunction`.

**Comment by jishnub** [comment]
Perhaps removing support for `kwargs` would be the right move, as there won't be such surprises with other operators as well. One may construct the closure and pass it to `BroadcastFunction` if the parent function needs `kwargs`

**Comment by simeonschaub** [comment]
I mean, with kwargs, `.+(a, b; c=3)` would be consistent with `BroadcastFunction` again.
