### ISSUE TITLE
opnorm fails on an 1 x 0 matrix

### ISSUE THREAD

**Issue by andreasvarga** [JuliaLang/julia#40370]
The following computation leads to an error:
```
julia> a = rand(1,1)
1×1 Matrix{Float64}:
 0.86747552215521

julia> t = a[:,2:1]
1×0 Matrix{Float64}

julia> opnorm(t)
ERROR: TypeError: in typeassert, expected Tuple, got a value of type Nothing
Stacktrace:
 [1] generic_normInf
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\generic.jl:465 [inlined]
 [2] normInf
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\generic.jl:556 [inlined]
 [3] generic_norm2(x::Matrix{Float64})
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\generic.jl:497
 [4] norm2(x::Matrix{Float64})
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\dense.jl:105
 [5] opnorm2
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\generic.jl:705 [inlined]
 [6] opnorm(A::Matrix{Float64}, p::Int64)
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\generic.jl:767
 [7] opnorm(A::Matrix{Float64})
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\generic.jl:766
 [8] top-level scope
   @ REPL[192]:1
```

But, there is no error if the matrix has a slightly different shape:
```
julia> a = rand(2,1);

julia> t = a[:,2:1]
2×0 Matrix{Float64}

julia> opnorm(t)
0.0
```

**Comment by stevengj** [comment]
I'm not entirely clear about the definition of the operator norm in this case.  Normally it is defined as:
![image](https://user-images.githubusercontent.com/2913679/113883894-8f47e000-978c-11eb-9f46-e5e634e31410.png)
but if `A` is a `1x0` matrix then it seems like the denominator `‖x‖` is zero, and the result is not defined.

(On the other hand, it seems like `‖A‖` should be defined and give zero for a 0x1 matrix.)

**Comment by simeonschaub** [comment]
I think I did see the operator norm of `A` defined as the smallest value `c`, such that `c * norm(x) >= norm(A * x)` holds for all `x` before. Since `norm(x)` and `norm(A * x)` will always be zero if `A` is a 1x0 matrix, this trivially holds for all `c`. The opnorm can't be negative, so I don't think zero would be an unreasonable choice for the operator norm here.

**Comment by andreasvarga** [comment]
Just for comparison: in Matlab

```
>> norm(rand(1,0))

ans =

     0
```

**Comment by dagbr** [comment]
@stevengj  This definition works in this case, too. Let `A` be a `m x 0` matrix. The linear map associated with `A` has zero-dimensional source containing only the zero vector. The supremum is taken over non-zero vectors, that is, the empty set, so the norm is zero because the supremum is taken inside non-negative reals as in @simeonschaub 's explanation.
