### ISSUE TITLE
Display of parametric type in v1.6 breaks tests

### ISSUE THREAD

**Issue by goualard-f** [JuliaLang/julia#40511]
Contrary to the previous versions, Julia 1.6 adds a space after the comma when displaying a parametric type with to parameters, which seems to break unit testing with Documenter. Consider:

In Julia 1.5:
```julia
julia> struct Foo{T1,T2}
       end

julia> Foo{Int,Int}
Foo{Int64,Int64}
```

In Julia 1.6:
```julia
julia> struct Foo{T1,T2}
       end

julia> Foo{Int,Int}
Foo{Int64, Int64}
```

**Comment by simeonschaub** [comment]
This was an intentional change, because it was inconsistent with how comma-separated values were printed everywhere else. You can interpolate `Tuple{Int, Int}` into the docstring directly to make them version independent, but we generally don't make any guarantees about printing across minor versions.

**Comment by goualard-f** [comment]
Ok. Thanks for the quick answer. I guess the same is true with the way v1.6 displays arrays with one dimension (Vector{T}) vs v1.5 (Array{T,1}, then.
