### ISSUE TITLE
Issue with "check_top_bit"

### ISSUE THREAD

**Issue by M-Agent** [JuliaLang/julia#40580]
I try to solve a diff.eq. problem with the solution is N-dimensional Array,
and I want to place each solution in side by side using `CairoMakie.jl`.
But the beginning, using 1st row(`sol[:,:]` → `sol[1,:]` )
But the code below doesn't work, especially at `ay, ly`.
I got this error
`LoadError: InexactError: check_top_bit(UInt64, -9223372036854775481)`
```
FigA = Figure(resolution=(1000, 700),
            backgroundcolor = RGBf0(1, 1, 1))
ax, lx = lines(FigA[1,1],sol.t,solX[1,:],
            linewidth=2,
            axis=(title="Solution of X-axis",))
ay, ly = lines(FigA[2,1],sol.t,solY[1,:],
            linewidth=2,
            axis=(title="Solution of Y-axis",))
FigA
```

If only use `ax, lx` or replace `solY[1,:]` to `solX[1,:]`, works fine.
```
sol.t
 101-element Array{Float64,1}

solX
 17×101 Array{Float64,2}
solY
 17×101 Array{Float64,2}
```
```
solX[1,:]
 101-element Array{Float64,1}
solY[1,:]
 101-element Array{Float64,1}
```
Would you mind helping me?
Please.

**Comment by simeonschaub** [comment]
Welcome, thanks for the report! This repo is for tracking issues with base Julia and standard libraries, but this seems to be an issue with CairoMakie.jl. In particular, it looks like this issue is coming from https://github.com/JuliaGraphics/Showoff.jl, could you post a full example with your issue there?
