### ISSUE TITLE
"Add Julia to PATH" checkbox on Windows Installer should remove older Julia versions from path

### ISSUE THREAD

**Issue by PGS62** [JuliaLang/julia#40598]
The Julia Windows installer has an "Add Julia to PATH" checkbox. If I check that then the "being installed" version of Julia is indeed added to the path, but after any other Julia versions already present. That serves no purpose as far as I can tell, and is presumably not the user's intention.

**Comment by musm** [comment]
You'll need to manually uninstall the older versions, to have then remove from path.

**Comment by PGS62** [comment]
That's certainly true. I was thinking of the situation where I install a new version of Julia, but don't yet want to uninstall an older version. In that case a dialog "You checked 'Add Julia to PATH', to add Julia 1.6.1 to the path, but Julia 1.5.0 is already on the path, would you like to amend the path to include 1.6.1 instead of 1.5.0, or leave the path unchanged?" might be helpful...

I _think_ that would be a helpful (though small) change, but I don't know whether it would be easy to implement. What I do in practice is edit the path manually using "Control Panel" --> "System Properties" --> "Environment Variables".

An argument against my suggestion is it's often best to keep things simple, and "treating each Julia version like an independent program" is nice and simple.

**Comment by davidanthoff** [comment]
I should say that the MSIX installer I've been working on (see https://github.com/JuliaLang/julia/issues/36672) solves this problem of having multiple versions of Julia installed at the same time and what `julia` means in terms of `PATH`. I'm waiting for some help from Julia Computing to get the Windows Store story sorted out, but I have not given up on that whole project :)

**Comment by musm** [comment]
> An argument against my suggestion is it's often best to keep things simple, and "treating each Julia version like an independent program" is nice and simple.

I totally agree that this feature is needed for smooth upgrades.  When I was working on the installer, this was basically the conclusion I came to.  I tried and tested various more complex 'auto-updating' strategies with a custom auto-installer, but was never satisfied, since they often had some special cases where things could go awry. I can try to revisit the issue, but I think the MSIX installer is likely the better option going forward.

**Comment by musm** [comment]
@davidanthoff  I think it would simply be easier to create an account on behalf of the Julia Lang org and have that sanctioned (you would maintain it along with other committers, instead of using Julia Computing (I don't get why we would use that for the installer anways, the Julia Language is its own org).

**Comment by StefanKarpinski** [comment]
Is this mostly obviated by the existence of `juliaup` and moving to that as the standard install method for Windows?

**Comment by davidanthoff** [comment]
Yes, I think so.
