### ISSUE TITLE
macOS: running `make` gives "WARNING: using mismatched version for..."

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#40854]
```
WARNING: using mismatched version for SuiteSparse-9cfdbbd33d2d52b83b2459f670162244cc95460c symlink-uninstaller /Users/dilum/dev/repos/JuliaLang/julia/usr/share/julia/stdlib/v1.7:
  want SuiteSparse.v5.8.1+2.x86_64-apple-darwin bb-uninstaller
  To resolve this warning, you could try either of the following suggestions:
  1. Run the following command: make -C deps uninstall
  2. Remove the following directory: /Users/dilum/dev/repos/JuliaLang/julia/usr
```

Per the discussion on Slack, the cause is a file uppercase/lowercase issue on macOS.

Specifically, on macOS, you see this (note that only `suitesparse` is present):
```bash
~/julia/usr/manifest$ ls
ArgTools       Statistics     dsfmt          libwhich       nghttp2        pcre
Downloads      Tar            gmp            llvm           objconv        suitesparse
LibCURL        blastrampoline libgit2        llvmunwind     openblas       utf8proc
NetworkOptions csl            libssh2        mbedtls        openlibm       zlib
Pkg            curl           libuv          mpfr           p7zip
```

But on a different system, you see this (note that both `suitesparse` and `SuiteSparse` are present):
```julia
~/julia/usr/manifest$ ls
ArgTools        curl       gmp      libssh2   llvm     NetworkOptions  openlibm  pcre        suitesparse  unwind
blastrampoline  Downloads  LibCURL  libuv     mbedtls  nghttp2         p7zip     Pkg         SuiteSparse  utf8proc
csl             dsfmt      libgit2  libwhich  mpfr     openblas        patchelf  Statistics  Tar          zlib
```

**Comment by staticfloat** [comment]
So the issue is that now that SuiteSparse is an external stdlib, it needs to be tracked for uninstall (hence the entry in `usr/manifests/`.  But we already have a manifest for something that needs to be tracked for uninstall; the actual binary files for suitesparse.

So the `suitesparse` entry is for the files in `deps/suitesparse.mk` and the `SuiteSparse` entry is for the files in `stdlib/Makefile` for `SuiteSparse.jl`.  This explains the error message:]

```
using mismatched version for SuiteSparse-9cfdbbd33d2d52b83b2459f670162244cc95460c symlink-uninstaller /Users/dilum/dev/repos/JuliaLang/julia/usr/share/julia/stdlib/v1.7:
  want SuiteSparse.v5.8.1+2.x86_64-apple-darwin bb-uninstaller
```

`SuiteSparse-9cfdbbd33d2d52b83b2459f670162244cc95460c` is the directory name for the `SuiteSparse.jl` version, and `SuiteSparse.v5.8.1+2.x86_64-apple-darwin` is the directory name for the JLL we downloaded.

I think the proper fix to this is to change the name of one of these; most likely to change the `deps/suitesparse.mk` to instead call everything `libsuitesparse`.
