### ISSUE TITLE
Replit support

### ISSUE THREAD

**Issue by Time-dragon** [JuliaLang/julia#40994]
This allows repl.it users to use Julia.

**Comment by Keno** [comment]
replit supports julia fine: https://replit.com/languages/julia

**Comment by mgkuhn** [comment]
[Repl.it](https://replit.com/) [announced Julia support](https://replit.com/talk/announcements/Introducing-Julia-support/11469) two years ago.

Having just given it a try, there are signs it hasn't been updated recently: the console prompt claims it uses Julia 1.3.1, but `VERSION` returns 1.4.1. [Now reported.](https://replit.canny.io/general-feedback/p/julia-version-mismatch-and-update)

Is there anything you think the Julia project could do to make its use in environments like repl.it more practical?

Otherwise, https://replit.canny.io/ is available to provide feedback to the repl.it project.
