### ISSUE TITLE
Add support for BFloat16

### ISSUE THREAD

**Issue by DhairyaLGandhi** [JuliaLang/julia#41075]
This came up on the ML call today. BFloat16 has basically taken over Float16 as a low precision floating point representation and is now used in accelerating a number of ML ops to use lower precision element types. LLVM has also introduced the BFloat16 primitive. @keno mentioned adding this support in the language generically would be possible and useful. Opening this here for folks to chime in with what needs to happen for this to come to fruition. BFloat16s.jl is already quite old at this point too.

Also cc @maleadt for his thoughts.

**Comment by Keno** [comment]
Since LLVM has support now, we need to figure out how to make the `BFloat16` type (https://github.com/JuliaMath/BFloat16s.jl/blob/master/src/bfloat16.jl#L8) properly map to its LLVM equivalent. We could either add it to Base and hack something in, or add some generic mechanism for primitive types to declare their LLVM mapping. That said, there should be nothing preventing us from at least hooking up CuDNN and similar libraries using the existing BFloat16s package, so I think for the ML use case, that might not be required.

**Comment by maleadt** [comment]
CUDA.jl's CUBLAS-based GEMM already works with BFloat16s like that, https://github.com/JuliaGPU/CUDA.jl/blob/f9f21dd3f80be936c30c44b051ffaaf599eac87e/lib/cublas/wrappers.jl#L868-L874.

**Comment by maleadt** [comment]
That would first require a way to target LLVM's `bfloat` type, as Keno mentioned above. That work hasn't happened yet.
