### ISSUE TITLE
missing lu(::SparseMatrixCSC, ::Val{true}; ...) method

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#41154]
From [discourse](https://discourse.julialang.org/t/sparse-linear-alegbra-question-lu-sparsematrixcsc/62625):
```jl
using LinearAlgebra, SparseArrays
M = sprand(10,10,0.5)
lu(M')
```
gives
```jl
ERROR: MethodError: no method matching lu!(::SparseMatrixCSC{Float64, Int64}, ::Val{true}; check=true)
Closest candidates are:
  lu!(::StridedMatrix{T}, ::Union{Val{false}, Val{true}}; check) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/lu.jl:79
  lu!(::Union{Hermitian{T, S}, Symmetric{T, S}} where {T, S}, ::Union{Val{false}, Val{true}}; check) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/lu.jl:88
  lu!(::StridedMatrix{T} where T, ::Union{Val{false}, Val{true}}; check) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/lu.jl:130
```
Seems like we should just define:
```jl
lu!(M::AbstractSparseMatrix, pivot::Val{true}; kws...) = lu!(M; kws...)
```

**Comment by dkarrasch** [comment]
1. This issue should go to the new `SuiteSparse.jl` repo, but I don't know how to move issues.
2. There is no in-place `lu!` for regular sparse matrices. There is only a `lu!` for `UmfpackLU` types, which assumes that the matrix to be LU decomposed has the exact same pattern of nonzeros for which the `UmfpackLU` object was created in the first place.
3. I see two options to solve the issue: we define `lu(adjA::Adjoint{<:UMFVTypes,<:SparseMatrixCSC}) = lu(SparseMatrixCSC(adjA))` (and similarly for `Transpose`), i.e., silently materialize the adjoint/transpose; or throw an error with a hint to take the adjoint of the `UmfpackLU` object rather than the matrix (as suggested on discourse), because there are specialized solve methods for that.

**Comment by stevengj** [comment]
Closing in favor of https://github.com/JuliaLang/SuiteSparse.jl/issues/35
