### ISSUE TITLE
`deleteat!` by `CartesianIndex`

### ISSUE THREAD

**Issue by wangl-cc** [JuliaLang/julia#41170]
I try to remove the item of vector at a `CartesianIndex`, like
```
julia> deleteat!([1, 2], CartesianIndex(1))
ERROR: iteration is deliberately unsupported for CartesianIndex. Use `I` rather than `I...`, or use `Tuple(I)...`
```

It seems that a `CartesianIndex` is treated as an iterator of indices instead of an index, and there is not a method like `deleteat!(a::Vector, ind:: CartesianIndex)`.
 Is it possible to add a method `deleteat!(a::Vector, ind:: CartesianIndex)`?

**Comment by johnnychen94** [comment]
This might not be as useful as you thought it be. Although there're some intersections, `deletat!` is a method for list-like objects while `CartesianIndex` is mostly for multi-dimensional arrays. Only specializing `deletat!(a::Vector, ind::CartesianIndex{1})` doesn't sound a good change to me.

**Comment by wangl-cc** [comment]
@johnnychen94 Thanks for your reply. Specializing `deleteat!(a::Vector, ind:: CartesianIndex)` doesn't sound good, but the error message is quite confusing. Especially, delete by a vector of `CartesianIndex`:
```
julia> deleteat!([1, 2], [CartesianIndex(1), CartesianIndex(2)])
ERROR: MethodError: no method matching +(::CartesianIndex{1}, ::Int64)
```
I think that `deleteat!` convert the `CartesianIndex` to integer index or just throw an `ArgumentError` may be better.

**Comment by johnnychen94** [comment]
By saying `deleteat!` is a method for list-like objects, I was saying that this is expected to only work on linear indices. So my two cents is, if we don't plan to support `deleteat!` for multi-dimensional array `a::Array`, we don't need to support `inds::CartesianIndex`. Clearly that we don't plan to support it because the only way to do it is vectorizing it, e.g., `vec(a)`.

A similar case to this is https://github.com/JuliaArrays/OffsetArrays.jl/pull/137.

> I think that deleteat! convert the CartesianIndex to integer index or just throw an ArgumentError may be better.

Both of these are doable, one could convert a CartesianIndex into a LinearIndex, e.g., by calling `deleteat!(x, LinearIndices(x)[inds])`) or even do some lazy conversions. But as I just said, I don't think we need to add this specialization; it might be convenient or even more consistent at first sight, but IMO it eventually adds confusion because `CartesianIndex` is not designed for the vector method.

It's just my two cents and people may disagree, though.

**Comment by wangl-cc** [comment]
@johnnychen94 Thanks for your patience. Maybe you're right.
