### ISSUE TITLE
Padded and union atomic fields

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#41218]
The current API by design [^1] seems to have an issue lowering CAS with a padded field:

```julia
mutable struct A
    @atomic x::Tuple{UInt8,UInt8,UInt8}
    y::Int
end

a::A
old = @atomic a.x
if need_update(old)
    new = UInt8.((1, 2, 3))
    @atomicreplace(a.x, old => new)  # may fail due to some unknown bits before `y`
end
```

A similar problem arise with union field like `@atomic x::Union{Nothing,Float32,UInt8}`.

There is a relevant paragraph in [The manifest](https://hackmd.io/s/SyFljvtdO):

> At the implementation level, one subtle point to be aware of is that the replace may spuriously fail due to padding bits or other ways of getting an egal object with a different representation. This (and for other similar reasons) means that the operator in modifyfield! might get called multiple times. It also implies that some seemingly trivial cases (such as a field typed as Any), actually require a loop around the replace, until the representation converges to a stable value, or until the old value is not egal to the expected value.

It describes the problem but it'd be great if there is a solution before the API is stabilized. It may be a nitpick, bu I find it misleading relating CAS failures due to "dirty" padding with spurious failure. The current implementation does not provide a mechanism for strong CAS [^2] since the user does not have access to the bytes stored in the padding. This is not enough for situations that CAS must succeed given known old value to guarantee the correctness (safety and/or liveness) of the algorithm; e.g., tail pointer fixup in Michael & Scott's lock-free queue. Reliable CAS of padded struct arose in a lock-free linear proving hash table ([Maier, Sanders and Dementiev (2019)](https://doi.org/10.1145/3309206); my implementation in Julia: [ConcurrentCollections.jl](https://github.com/tkf/ConcurrentCollections.jl)) since key and/or value may be smaller than the size supported by CAS.

[^1]: Current _implementation_ seem to fail to compile this. But I think that's an issue separated from the design.

[^2]: That is to say, IIUC, current API cannot provide (even obstruction-free) progress guarantee if a user tries to implement "strong CAS" by treating `@atomicreplace` as a weak CAS.

### Possible solutions

If the current API is fixed, I think possible solutions are (1) always zero-initizlie the padded `@atomic` fields or (2) use non-hardware CAS (i.e., using "equality" ignoring the padding) when there is a padding.

If we can add another API, this can be solved efficiently by (3) introducing an API that pairs the Julia value of a field and the byte-representation of it

```julia
struct Loaded{T,B}
    value::T
    bytes::B
end

Base.getindex(ld::Loaded) = ld.value
```

where `.bytes` field contain equivalent `Unsigned` integer. A field can be loaded into `Loaded` which can be used for strong CAS:

```julia
ld = @Loaded a.x
old = ld[]
ld::Loaded{T}
old::T
if need_update(old)
    new = UInt8.((1, 2, 3))
    @atomicreplace(a.x, ld => new)
end
```

**Comment by vtjnash** [comment]
This is a long message, and seems to be confusing "at the implementation level" (which that paragraph in the manifesto describes) with details exposed to the user. It had seemed unnecessary to state "this is defined to work in all cases, including ones that are broken in other languages." Much of the text here seems to cover a problem observed in most language's implementations of CAS, but does not exist in Julia as currently implemented.

I'm tempted to split off the actual bug here, which is an alignment case that I forgot to handle in my attempts to shrink-wrap copies efficiently, and that triggers an assertion I had also added. I had previously written tests that exercised internal padding, but I forgotten that padding may also exist between fields.

The idea to demand zero-init for these fields is interesting, as it may allow us to finish the CAS loop quicker in certain cases. I think it would make the logic more complicated however, so I am not sure the gain is worthwhile right now. But that is indeed a partial implementation option for the detail mentioned in the manifesto. It should have no user-visible behavior change as well, so that experiment can happen later at any time.

**Comment by vtjnash** [comment]
> [^2]: `@atomicreplace` as a weak CAS.

It is a strong CAS, so you can treat it as a weak CAS too and still be correct. However, the implementation tries to return the actual old value (including padding bits), so theoretically you could attempt to build a reliable strong CAS even on a buggy implementation of it. However, it is very hard to ensure that the old value does not discarding padding when you work with it, so our best bet is just not to have a buggy implementation though.

**Comment by tkf** [comment]
Fair enough. I guess I can also manually pad the fields.
