### ISSUE TITLE
Should `\U` always require 8 hex digits? Or up to 6?

### ISSUE THREAD

**Issue by KlausC** [JuliaLang/julia#41365]
While the first string is as expected, the second one fails.
Probably more than 6 digits are used to calculate the code point.

```
julia> "\U100000g"
"\U100000g"

julia> "\U100000f"
ERROR: syntax: invalid escape sequence
Stacktrace:
 [1] top-level scope
   @ none:1
```

**Comment by mbauman** [comment]
That is an invalid escape sequence.  You want `"\U00100000f"`. `"\U100000g"` is two chars long since `g` isn't a hex digit, but `\U100000f` is attempting to make a single char outside of the valid code points.  Note how Julia prints this:

```
julia> char = '\U100000'
'\U100000': Unicode U+100000 (category Co: Other, private use)

julia> string(char, 'f')
"\U00100000f"

julia> string(char, 'g')
"\U100000g"
```

Most programming languages require _exactly_ 8 hex digits.  Julia allows you to omit the leading zeros.  If we change anything here (1) it'd be breaking and (2) if anything I'd say we should be more strict and just require 8 digits all the time.

**Comment by KlausC** [comment]
Why 8 and not 6? as all valid unicode codepoints are `< 0x10ffff`

**Comment by mbauman** [comment]
Sorry, my title edit was a little too opinionated.  8 is just what others do; it seems necessary to [support that](https://juliahub.com/ui/Search?q=%5C%5CU%5B%5Cda-f%5D%7B7%7D&type=code&r=true).  I suppose you could do something real fancy like look for 8 digits in the case of `\U00`, up to 7 digits in the case of `\U0_` and 6 in the case of `\U_` where the `_` represents a nonzero hex digit.

**Comment by KlausC** [comment]
Would the change you proposed be acceptable (non-breaking)?

**Comment by KlausC** [comment]
Change in documentation:

"A U-escape sequence is `\U` followed by 1 to 8 hexadecimal digits, where at most the last six of which may be non-zero."

**Comment by mgkuhn** [comment]
Related idea: one could also make `\u` or `\U` variable-length if followed by `{`, as in `"\U{20ac}1000" == "€1000"`? Similar to what Perl does:
```
$ perl -C -e 'print "\x{20ac}1000"'
€1000
```

**Comment by StefanKarpinski** [comment]
What we implemented here is [exactly what C supports](https://en.wikipedia.org/wiki/Escape_sequences_in_C). Now, that may not be the best design, but it is pretty much the closest thing that exists to a universal standard for string escaping and the `\U` escape form is followed by eight hex digits even though the maximum Unicode code point only requires six hex digits.

Historically, I suspect that the `\u` form was introduced in the UCS-2 era when people still believe that two bytes would be enough for a universal character set with code points specified by four hex digits. Later, UCS-4 slash UTF-32 were introduced along with the possibility of code points up to eight hex digits, which is when I suspect the `\U` escape form with eight hex digits was introduced. However, there was already a legacy of UCS-2 around so UCS-2 was modified to get UTF-16, whose single-code-point encodings coincide with those of UCS-2 but the at-that-point-still-unused surrogate pair code units were conscripted to encode additional code points beyond `U+FFFF`. And UTF-16 is where the maximum code point limit of `U+10FFFF` comes from since that's the highest value that can be encoded with surrogate pairs (`U+DBFF` + `U+DFFF` = `U+10FFFF`).

Anyway, history aside, it may have been better to do string escaping differently from C, but the worst possible choice would have been to do string escaping *almost* the same way as C but deviate in some minor detail like changing the `\U` escape form so that it consumes only six hex digits instead of eight. Currently we have the benefit that if you copy a string literal from a C program it will produce the same string in Julia.

There's a different conversation to be had about introducing other escape and interpolation syntaxes, but that should probably have it's own issue and include a survey of what other languages have done since once you leave the realm of classic C-style escapes, it's pretty much the wild west.

**Comment by KlausC** [comment]
>  but it is pretty much the closest thing that exists to a universal standard for string escaping and the \U escape in C is followed by eight hex digits even though the maximum Unicode code point only requires six hex digits.

I don't totally agree to your argumentation. The C-standards allow escape sequences of the for `\UXXXXXXXX`, that means always exactly 8 hexadecimal digits. That is different from what Julia allows, namely to provide less that 8 digits and terminate the sequence by any character, that is not a hexadecimal digit. That leads to the ambiguity, and bad readability, which I am criticising.

**Comment by KlausC** [comment]
> If we changed \U to consume only six hex digits, ...

But we currently allow 6 or even less characters, and are are not C-compatible this way. So "\U41X" is valid Julia for "AX" but by multiple reasons rejected by C. 

The proposal in PR #41367 tries to improve the situation a little bit without breaking too much.
The better solution would be to allow "\U00XXXXXX" like C and additionally "\UXXXXXX", where X is any hex digit, but forbid other abbreviated versions, which we allow now.

BTW, the gnu C compiler issues a warning,  if `0xXXXXXX > 0x10ffff`.

**Comment by StefanKarpinski** [comment]
> The C-standards allow escape sequences of the for `\UXXXXXXXX`, that means always exactly 8 hexadecimal digits. That is different from what Julia allows, namely to provide less that 8 digits and terminate the sequence by any character, that is not a hexadecimal digit. That leads to the ambiguity, and bad readability, which I am criticising.

Well, I'll be damned. I thought C allowed _up to_ four/eight hex digits for these escapes, but it does, as you say, require exactly four/eight hex digits. Anyway, I think the ship has sailed on this until 2.0, at which point I'd prefer just rethinking the unicode escaping entirely.

**Comment by KlausC** [comment]
My proposal for v2.0 would be to support the following escape sequences, with exact number of hex digits X.

\xXX
\uXXXX
\UXXXXXX
\U00XXXXXX

**Comment by StefanKarpinski** [comment]
I'd much prefer making it variable length and using `\u{...}` for all code points.

**Comment by KlausC** [comment]
That is v e r y much breaking. And has many advantages: easy to recognize optically, no ambiguities.
Ok, seems a question of taste and agreement. I sticked to the old forms because of inertia, and anticipated conservativism.
