### ISSUE TITLE
DOC: language specification

### ISSUE THREAD

**Issue by fhs** [JuliaLang/julia#4144]
Julia needs a language specification detailing its grammar. For couple of reasons:
1. It'll serve as a documentation for users of the language. I don't think the manual documents everything.
2. People can write compatible parsers for the language.

**Comment by cossio** [comment]
Python documentation (https://docs.python.org/3/index.html) offers an accessible Tutorial, but also has a terser [Language Reference](https://docs.python.org/3/reference/index.html) section which ends with a formal [grammar specification](https://docs.python.org/3/reference/grammar.html) of the language.

Sometimes reading a terse and precise description of an aspect of the language can be more clarifying than an informal tutorial-like exposition, which seems to be the tone of most of the documentation at the moment.

Now that Julia v1.0 is out and the language promises maintain a stable API, perhaps the idea of having a more formal description of the language can be revisited?

**Comment by cossio** [comment]
Would it make sense to revisit the idea of having a more formal specification of the language now that 1.0 is out? Sometimes reading a terse and precise description of an aspect of the language can be more enlightening than an informal description, which seems to be the tone of most of the documentation at the moment.

For example, I really like the organization of Python docs. You have a very accessible [Tutorial](https://docs.python.org/3/tutorial/index.html). Then there is the [Language Reference](https://docs.python.org/3/reference/index.html), which contains the formal grammar of every element of the language as well as some explanation in prose.

**Comment by cossio** [comment]
Reopen?

**Comment by slavchev** [comment]
Came here for the same reason. Are there any other resources besides the following two (though they seem enough)?

https://github.com/JuliaLang/julia/blob/v1.0.0/src/julia-syntax.scm
https://github.com/JuliaLang/julia/blob/v1.0.0/src/julia-parser.scm

**Comment by mwette** [comment]
Is the conditional-evaluation construct a statement or an expression?
I had to run the program to find out.   (Maybe it is in the doc's but I didn't find it there.)

The grammar would be useful for generating {octave,matlab,r} to julia translators.

**Comment by StefanKarpinski** [comment]
Everything is an expression.

**Comment by qlcom** [comment]
Having something like what Go has https://golang.org/ref/spec will be very useful

**Comment by qlcom** [comment]
why do you guys fear to write a specification?

**Comment by StefanKarpinski** [comment]
What would the benefit be?

**Comment by qlcom** [comment]
Have you read the Go language's spec? It is readable, detailed and not very long.

Having a spec mean we can have multiple implementation made by different independent groups.

**Comment by KristofferC** [comment]
What would the benefit be?

**Comment by StefanKarpinski** [comment]
> having a spec means we can have multiple implementations made by different independent groups.

I'm actively against this: there should be one really excellent open source implementation, not many half-assed implementations.

> Have you read the Go language's spec? It is readable, detailed and not very long.

Yes, a mere 30,000 word document. That should be easy enough to produce and keep up-to-date.

That said, as I stated when this was originally requested, I would be fine with there existing a spec if someone wants to write one, I will read it and give feedback. If Julia devs approve it, we can make it official. Hopefully they would also be willing to keep it up-to-date. Otherwise we can make it official only for one release of the language and then if someone else wants and up-to-date version for a newer version of the language, they can update it.

**Comment by slavchev** [comment]
> I'm actively against this: there should be one really excellent open source implementation, not many half-assed implementations.

You are a co-creator of Julia and it is good to hear your opinion. That being said, a good healthy competition might be good for the project. Anyway, it doesn’t seem that there is a major effort in creating other implementations and if I am wrong then may the best one win.

It was a while ago when I was interested in creating some tooling and a language service for Julia so having an official lang spec would make things easier. Accidentally my GitHub notification were set on so I get notifications for these recent comments. Maybe after a month or two I will try to spend some time on revisiting my previous ideas.

**Comment by StefanKarpinski** [comment]
The problem here is that other people are volunteering us to do work that we think is a waste of time: I don't think a spec is a good way to spend my very limited time and energy. The Go folks felt that it was a good way to spend their time and energy, which is their call. If someone else wants to write a spec for Julia, they are welcome to do so, and as I said, I would certainly be willing to review it (but not to keep it up to date, that's on them).

Likewise, I believe that having multiple implementations of Julia is a waste of time and energy—mine or anyone else's. If there are people out there who are willing and able to create an implementation of Julia that is so good that it "competes with" the main one, then why the hell aren't they contributing to the main one instead of doing all that pointless work? I'd be legitimately pissed if that happened. Not because of competition but because there's so much work that needs to be done and instead of helping with it, these people are reimplementing what's already been implemented? Why? Julia is already open source and has the most liberal possible license, so there can't possibly be any legal issue. We're also not like CPython which rejects using new compiler technology to make things better or faster. If someone has crazy new compiler ideas to make Julia faster, that's great! Try it out here—we'll help.

**Comment by PallHaraldsson** [comment]
>it doesn’t seem that there is a major effort in creating other implementations

well it seems like a LOT of work to me.

There were two other implementations, even only forks of Julia, and those are not maintained:

Julia "lite":
https://github.com/ScottPJones/julia/tree/spj/lite

And Intel's Julia2C was in some sense and implementation (fork), and this:
https://discourse.julialang.org/t/status-of-and-need-for-parallelaccelerator/19277

**Comment by slavchev** [comment]
Firstly, I apologise if I disturbed anyone with my previous comment. I write this for my sake, as I said I haven't used Julia for a long time (maybe 2 years) and I don't speak for the other participants in this thread. From the response I get the impression that the team is really busy and it is natural to get frustrated when a perceived pressure is added from the community. I did OSS and I know it. The resources are never enough.

Also, I really like the project. I've always liked passioned teams. Let me remind you one [post](https://julialang.org/blog/2012/02/why-we-created-julia/) I really like.

>Why We Created Julia
>In short, because we are greedy.

This is the passion I talk about. You wanted to create Julia, so you created it. So if there are other people passioned about creating alternative implementation, so be it. They want it and they will create it. Don't feel obliged to be part of it. They ask for a lang spec and they will create one if they want it. You proposed a generous offer the review the spec and I am sure they will appreciate it.

>>it doesn’t seem that there is a major effort in creating other implementations

>well it seems like a LOT of work to me.

I expressed it poorly (I am not a native speaker). What I meant is that it doesn't seem that there are people putting a lot of effort in creating alternative implementations. And to be more precise even if they put a lot of effort it doesn't seem the projects are doing well, at least not being popular. I didn't even know about the "lite" project until you brought it out. And as you said these projects are not maintained and so to speak you validate my intended point.

Finally, although I don't use Julia right now let me thank you and all involved for all hard work.

**Comment by qlcom** [comment]
ok, i understand that julia team has a different approch for documenting the language.

**Comment by KristofferC** [comment]
> Julia "lite" (I still like to have this, and maybe easy to resurrect):

This is definitely not "another implementation" of Julia. It's just Julia with certain parts removed. Doing this does not require a language spec.

**Comment by xwaeaewcrhomesysplug** [comment]
Why not just take a older version and then create a language specifications.
It is still hard but will not affect newer version.

For test implementations wise,the specifications will generally have examples right?
Then can take the example include it into the specifications testing.
So those who really desperate for specifications can see it,even self verify.
Does not actually need other party to test.

It is also like the free pascal or c in the olden days.

Specifications generally have examples,and theory.
It however very exhausting to write something like that without financial investment and some assistance.

So if someone were to be rich and kind enough.They may actually help create language specification on at least a specific version.
But,honestly....I bet there are plenty companies using it..just......

like yeah golang have it probably because...(for any other reply with golang example)

Just going around finding language with good specifications.Found this thread.
Hope this info and insights helped a bit.

**Comment by ron-wolf** [comment]
> Sure, now would be a good time for someone to work on it if they’re interested. It’s a bit hard to validate that a grammar is correct without it generating a parser (even a slow one) so it might make sense to figure out a way to write a grammar that can actually be used to parse Julia code and check that it works.

I am currently taking a course in this and would love to take it on in the near future. I believe generating a parser for verification might be doable using, e.g., Haskell parsing libraries. [Megaparsec](/mrkkrp/megaparsec#documentation) seems to have good support for many different grammars, which it seems would be necessary for Julia, since I’m not sure if Julia even has a context-free grammar.

**Comment by ron-wolf** [comment]
Actually, come to think of it that would basically just be a second implementation. Could I get a tip on what kind of parser Julia uses currently, to see if there’s a formal language specification tool that would make a good fit?

**Comment by KristofferC** [comment]
> Could I get a tip on what kind of parser Julia uses currently

You can find it here: https://github.com/JuliaLang/julia/blob/master/src/julia-parser.scm

**Comment by mwette** [comment]
I did a little work a few years ago to get started on a Julia parser, using my (Guile) Scheme-based parser generator.   When I generate parsers, I also generate pretty-printers.  The intermediate representation is in SXML (XML using S-expressions).  I also have a "mlang" (aka MATLAB, Octave) parser.   My goal for the Julia parser was to flush out the pretty-printer in order to  generate a MATLAB-to-Julia translator.   Check out julia and mlang under https://git.savannah.nongnu.org/cgit/nyacc.git/tree/examples/nyacc/lang.

**Comment by dcand** [comment]
This doesn't make any sense. You people should learn from New Jersey style. How can you make your language so complicated  that you forgot to even write a specification.

**Comment by pxeger** [comment]
I think this issue needs to distinguish from either:
- standardising the whole language, like Go, JavaScript, C, C++, etc. are
- just providing a formal grammar specification for parsing

This seems to be the source of some of the confusion here

**Comment by dsaw** [comment]
Adding a grammar specification would make it convenient for anyone to feed it into a parser generator of the language of their choice, so that the AST/IR representation can be directly used in that particular library of their language. For example, a parser in Python would be excellent for conversion of symbolic computational expressions from Julia to Python, where there are powerful libraries like Sympy for algebra.

**Comment by ViralBShah** [comment]
Worth mentioning https://github.com/julia-vscode/CSTParser.jl to people who end up here.

**Comment by ShalokShalom** [comment]
@ViralBShah And is there also a formal syntax, that describes the [concrete syntax](https://github.com/antlr/grammars-v4/issues/2076#issuecomment-1729397137)?
