### ISSUE TITLE
`t <: Vararg` now throws

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#41446]
1.7:
```jl
julia> Int <: Vararg
ERROR: TypeError: in <:, expected Type, got Vararg
```

1.6:
```jl
julia> Int <: Vararg
false
```

Is this considered breaking? These packages fail on 1.7 due to it:

-    Adapode
-    AdaptiveDistanceFields
-    DobotMagician
-    TensorValues
-    Ghost
-    Yota
-    InteractiveCodeSearch

**Comment by simeonschaub** [comment]
IIUC, this was an intentional change, since `Vararg` is not actually a real type, so asking whether `T <: Vararg` is likely a potential bug.

**Comment by vtjnash** [comment]
Adapode (actually AbstractTensors failure) -- broken anyways
AdaptiveDistanceFields -- due to StaticArrays getting somehow installed with a broken version
DobotMagician -- broken anyways
TensorValues -- (explicitly unmaintained) also due to a broken version of StaticArrays being installed
Ghost -- seems to be an incomplete reimplementation of `Base.morespecific`, perhaps needs to switch to that?
Yota -- transitive failure (via Ghost)
InteractiveCodeSearch -- amusingly, this was indeed trying to filter out Vararg from Type (referencing ~#29645~), and that workaround is now broken. Though the correct test for this would have always been `Base.isvarargtype` instead.

**Comment by Keno** [comment]
Yes, this was an intentional breaking change. I updated most widely used packages at the time. From @vtjnash's list looks like most packages are just accidentally stuck on bad dependency versions.

**Comment by vtjnash** [comment]
Right, some seem to be Pkg General choosing installation of a known bad release and could be fixed there. The others perhaps could have an issue opened in their repos to note the fail?
