### ISSUE TITLE
1.7-beta2: type instability for matrix multiplication

### ISSUE THREAD

**Issue by j-fu** [JuliaLang/julia#41489]
Hi, I encountered a type instability in matrix multiplication

```
julia> A=Rational[1 1 1; 2 2 2; 3 3 3]
3×3 Matrix{Rational}:
 1//1  1//1  1//1
 2//1  2//1  2//1
 3//1  3//1  3//1
```

On 1.7-beta2:
```
julia> A*A
3×3 Matrix{Any}:
  6//1   6//1   6//1
 12//1  12//1  12//1
 18//1  18//1  18//1
```

On 1.6.1:
```
julia> A*A
3×3 Matrix{Rational}:
  6//1   6//1   6//1
 12//1  12//1  12//1
 18//1  18//1  18//1
```

**Comment by simeonschaub** [comment]
Note that in general, return type calculations with non-concrete types are always very fragile, because intermediary calls often have quite a few matching methods, so those calls will infer to `Any`, which in many cases means the overall result will also infer to `Any`. The reason this used to work is probably more by accident due to how `+(::Rational, Rational)` was implemented. It is easy enough to fix in this case though, so I will make a PR.

**Comment by j-fu** [comment]
Ah ok, so to be on the safe side one should start with a concrete type in the first place.

**Comment by simeonschaub** [comment]
Yeah, that's always better when you have the choice.
