### ISSUE TITLE
Order of declaration bug?

### ISSUE THREAD

**Issue by mzgubic** [JuliaLang/julia#41481]
I can't seem to be able to figure out an MWE for this behaviour. It was found in [this PR](https://github.com/JuliaDiff/ChainRules.jl/pull/459/files), but I don't think the context matters too much.

Essentially, this order of definitions works
```julia
(::ProjectTo{T})(dx::AbstractArray) where {T<:StaticArray} = T(dx)
 ProjectTo(x::T) where {T<:StaticArray} = ProjectTo{T}()
```
while the opposite order
```julia
ProjectTo(x::T) where {T<:StaticArray} = ProjectTo{T}()
(::ProjectTo{T})(dx::AbstractArray) where {T<:StaticArray} = T(dx)
```
gives the following error:
```julia
ERROR: LoadError: TypeError: in Type{...} expression, expected UnionAll, got a value of type typeof(ChainRules.ProjectTo)
```

<details>
<summary>full error</summary>
<p>

```julia

(ChainRules) pkg> precompile
Precompiling project...
  ✗ ChainRules
  0 dependencies successfully precompiled in 2 seconds (9 already precompiled)

ERROR: The following 1 direct dependency failed to precompile:

ChainRules [082447d4-558c-5d27-93f4-14fc19e9eca2]

ERROR: LoadError: TypeError: in Type{...} expression, expected UnionAll, got a value of type typeof(ChainRules.ProjectTo)
Stacktrace:
 [1] top-level scope
   @ ~/JuliaEnvs/project/ChainRules.jl/src/ChainRules.jl:28
 [2] include
   @ ./Base.jl:386 [inlined]
 [3] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1213
 [4] top-level scope
   @ none:1
 [5] eval
   @ ./boot.jl:360 [inlined]
 [6] eval(x::Expr)
   @ Base.MainInclude ./client.jl:446
 [7] top-level scope
   @ none:1
in expression starting at /Users/mzgubic/JuliaEnvs/project/ChainRules.jl/src/ChainRules.jl:1
```
</p>
</details>

**Comment by JeffBezanson** [comment]
With the syntax `f(x) = ...`, if `f` does not yet exist we create a new global variable `f` in the current module and bind it to a new function. So in the second case, `ProjectTo` is not being imported from `ChainRules` but is instead a new function, which then cannot accept a type parameter. In the first case, we need to evaluate `ProjectTo`, so we search `using` modules and bring it in from ChainRules.

It's a bit like the distinction between
```
a = 1  # new local variable
```
and
```
a.x = 1  # `a` must already exist, and is evaluated
```

So the solution here is to explicitly `import ChainRules.ProjectTo`. Many find this behavior of `using` confusing, which is why some style guides strongly encourage `import` instead.
