### ISSUE TITLE
slowdown in `methods(hvcat)`

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#41518]
After #41394, the call `methods(hvcat, (Tuple{Int,Int},Any,Any,Any,Any,Any,Any,Int,Int))` takes over 50 seconds instead of less than 1 second. Most likely due to subtyping of lots of unions and long argument lists.

**Comment by dkarrasch** [comment]
Is this improved/resolved by #41511? Probably not.

**Comment by JeffBezanson** [comment]
I checked; unfortunately not.

**Comment by dkarrasch** [comment]
That reminds me of a massive observed slowdown when I was extending concatenation of `LinearMaps` toward `AbstractMatrix`, https://github.com/Jutho/LinearMaps.jl/pull/71. Unfortunately, I forgot how it got resolved eventually, probably by pure luck, because I didn't know how to inspect the problem more thoroughly.
