### ISSUE TITLE
Add atomicity keyword arg to `mv`

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#41584]
`mv` is often specified to be atomic on file systems, i.e. programs opening
a file will either get a handle to the old file or the new file, but never see an
incomplete file in the middle. This is highly useful for live replacing configuration
files, etc. Our `mv` is best-effort atomic, but if the files to be moved are on
different file systems, this can have problematic consequences. For example,
if the destination filesystem is full, it is possible for the destination file to
get truncated at arbitrary points. It would be better to have an option for
`mv` to automatically fail if atomicity cannot be guaranteed (maybe that
should even be the default).

**Comment by vtjnash** [comment]
I am not sure what you expected from this, since the target application intentionally set `force=true`, which disables the normally atomic features. Perhaps that should be better documented? There is also the inner function `Base.Filesystem.rename` (required by posix, but not supported on Windows, IIRC) which gives somewhat stronger guarantees also, and needs docs.

**Comment by Keno** [comment]
Isn't the `force` keyword for overwrite? I just want an atomic replace.

**Comment by vtjnash** [comment]
`force` means to move even if it might fail atomically

**Comment by stevengj** [comment]
Apparently on Windows 10 there is a POSIX-like atomic rename?  https://stackoverflow.com/questions/167414/is-an-atomic-file-rename-with-overwrite-possible-on-windows
