### ISSUE TITLE
Improvement: Why not making the same syntax than python ?

### ISSUE THREAD

**Issue by arita37** [JuliaLang/julia#41668]
Instead of

Function f(x,y)
   x+ y

why nor

def f(x,y):
  return x+y

**Comment by JeffBezanson** [comment]
We are not making changes of this kind at this stage. The debate on whitespace-sensitivity etc. has also gone on in many place over time, and we don't need to repeat it here.

**Comment by StefanKarpinski** [comment]
https://discourse.julialang.org/t/psa-julia-is-not-at-that-stage-of-development-anymore/44872

**Comment by arita37** [comment]
Because of this error design,
it will take many years before catching
with python user base and library richness…

Why introducing next syntax ?
There is no benefit in it…

**Comment by simeonschaub** [comment]
> There is no benefit in it…

There definitely are lots of reasons to deviate from Python's semantics. If you just want a faster Python, there are lots of accelerators like Numba or PyPy already.  https://docs.julialang.org/en/v1/manual/faq/#Why-don't-you-compile-Matlab/Python/R/%E2%80%A6-code-to-Julia? does a pretty good job of explaining why Julia is different.

**Comment by arita37** [comment]
So, there is no benefits of having
a syntax easier to use 
(no need of typing “;”)

Discussion is not about
the intrinseque performance,
but just the syntax parser.

Is there any blocking point
of having a syntax parser which
can parse “python like syntax code” ?

**Comment by arita37** [comment]
Sorry,
You mentioned this is because
of typing process in python ?

**Comment by simeonschaub** [comment]
There could be a more Python-like surface syntax for Julia, but I don't really see the benefit, since the semantics will still be different, so the similarity might be more misleading than beneficial. I also think many people here would strongly disagree that Python has the best syntax for numerical computing. Anyways, I think such a discussion would be much better suited to Discourse, since this is certainly not going to change in Base.

**Comment by KristofferC** [comment]
This is not a productive place to have this type of discussion. Please use the discourse forum instead.
