### ISSUE TITLE
Misleading error message for run "command not found"

### ISSUE THREAD

**Issue by bobcassels** [JuliaLang/julia#41716]
From a terminal:
```
bobcassels$ foo
-bash: foo: command not found
```

In Julia 1.6.2:
```
julia> run(`foo`)
ERROR: IOError: could not spawn `foo`: no such file or directory (ENOENT)
```

My original command was more complicated, and the ENOENT message misled me to waste a bunch of time. It would have saved me a lot of time if `run` had told me something more like "command not found".
```
julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 

```

**Comment by mefalsely** [comment]
Try your best

**Comment by HurtGub** [comment]
Lol

**Comment by Seelengrab** [comment]
A shell like `bash` typically has certain builtin commands, e.g. `which`. When you enter `foo` in your shell, it generally checks your PATH variable for any executable files with the name `foo` and afterwards it checks for a command named `foo` (or the other way around, depending on your shell). If it can't find either an executable file or a command, it'll error, in this case with `command not found` since that's what it checked last (though this again is shell specific).

When julia executes a CMD literal with `run` it calls into LibUV's [`uv_spawn`](https://docs.libuv.org/en/v1.x/process.html#c.uv_spawn). Per their [documentation](https://docs.libuv.org/en/v1.x/guide/processes.html?highlight=uv_spawn#spawning-child-processes), this ends up calling `execvp`, which errors with `ENOENT` because the file does not exist. From julia's point of view, there simply is no more information to be displayed here - it can't magically know that there only was a typo here. 

I agree that it's unfortunate that shell behavior and kernel error behavior is different here, but since julia doesn't have a concept of "builtin commands" like a shell does, printing a different error message seems very misleading to me.

**Comment by bobcassels** [comment]
@Seelengrab — thanks so much! This is really helpful. I have been thinking of Julia's `run` as spawning a sub-shell. You tell me it is running a LibUV "child process". So I need to think about `run` in those terms. To start, I need to understand how LibUV thinks about child processes, and how Julia `run` interacts with LibUV.

I will investigate further. I expect I will come back with a suggested change to Julia documentation about `run`. But maybe a PR for LibUV or for Julia.

I will close this issue, though. Thanks again!
