### ISSUE TITLE
Macros @test and @testset abort execution

### ISSUE THREAD

**Issue by aloispichler** [JuliaLang/julia#41736]
I understand that it is intended behavior that

`@assert 2 == 3`
`   println("never")`

terminates execution.
But a simple test as

`@test 2 == 3`
`   println("never")`

aborts execution as well and never prints "never".
The following testset:

`@testset begin`
`@test 2 == 3`
`   println("never1")`
`end`
`println("never2")`

never prints "never" neither, which is probably unintended.
This discussion here: https://discourse.julialang.org/t/test-macro/65531/10
reveals even more buggy behavior of the `@test` macro, which seems to have been introduced by #37809.
Thank you.

**Comment by KristofferC** [comment]
All of this seems to be consistent with how the test macros are intended to function. Did you read something in the documentation that made you think otherwise?

**Comment by Seelengrab** [comment]
The issue is that `never2` from the `@testset` version also never runs and isn't ever printed.

Additionally, the error that's being from results in `@test` not returning an appropriate value (as indicated by the [documentation of `@test`](https://docs.julialang.org/en/v1/stdlib/Test/#Test.@test)):

```
julia> using Test                       
                                        
julia> res = @test 2 == 3               
Test Failed at REPL[2]:1                
  Expression: 2 == 3                    
   Evaluated: 2 == 3                    
ERROR: There was an error during testing
                                        
julia> res                              
ERROR: UndefVarError: res not defined   
```

So at some point the intended behavior _was_ that code outside of `@test` or `@testset` still runs and can deal/work with failed test results directly.

---

@aloispichler you can use multiline code blocks by using triple backticks (```).

**Comment by KristofferC** [comment]
> The issue is that never2 from the @testset version also never runs and isn't ever printed.

Yes, a `@testset` throws an exception if a test within it fails. From the docs:

>   If no custom testset type is given it defaults to creating a DefaultTestSet. DefaultTestSet records all the results and, if there are any Fails or Errors, throws an exception at the
  end of the top-level (non-nested) test set, along with a summary of the test results.

**Comment by Seelengrab** [comment]
Ah, I missed that. Seems like a top-level `@testset` can't return its result because if throws and `@test` has the same (though in this case undocumented) behavior.

**Comment by KristofferC** [comment]
![tenor](https://user-images.githubusercontent.com/1282691/127701160-b87287a0-3c29-4fd2-9dc4-47f0a1315e21.gif)

**Comment by Seelengrab** [comment]
Thanks for the snarky gif, I guess, but please do point out to me what exactly I'm missing here:

![image](https://user-images.githubusercontent.com/11753998/127709219-33cbf7f1-bbba-4184-b274-93465b940ce2.png)

If you're talking about the section below the docstrings (though I'd argue it should be mentioned in the docstring, since that's the most convenient and first place to check anything when developing) where the error throwing is shown,

![image](https://user-images.githubusercontent.com/11753998/127709843-5949ca03-8aa0-44b5-9ac4-a071719540b0.png)

 it's still not true that a `Fail` result ist "returned", it's only printed to the console as I can't actually assign the result to a variable, as I've shown above. The assignment only works inside of a `@testset`, since the throwing is deferred until the enclosing `@testset` is done and not thrown immediately. Clearly, either the behavior or the wording in the docs is wrong here.

---

In general, it feels very weird that the behavior is different depending on whether or not either a `@test` or `@testset` is on the top level or not. It's also pretty hard to deduce this from the existing documentation.

**Comment by KristofferC** [comment]
I meant that the docs for `@test` is lying. Not you.
