### ISSUE TITLE
include() under @spawn

### ISSUE THREAD

**Issue by jtrakk** [JuliaLang/julia#41894]
```jl
# ./subdir/spawn.jl
Threads.@spawn include("file.jl")

# ./subdir/normal.jl
include("file.jl")

# ./subdir/file.jl
println(123)
```

`include("subdir/normal.jl")` prints 123. `include("subdir/spawn.jl")` fails with "no such file file.jl", presumably because it's interpreting `include` with respect to the CWD rather than `subdir/`. 

Why do the normal and spawn versions behave differently?

**Comment by Seelengrab** [comment]
`include` runs in the directory julia is running in, not the directory the file containing `include` is in.

**Comment by jtrakk** [comment]
That doesn't explain why the results differ when run under spawn.

**Comment by Seelengrab** [comment]
Why not? Spawned tasks inherit the working directory of their parent task. If the parent task is running in `"."`, the child task is too, making it unable to find `"./file.jl"`.

**Comment by jtrakk** [comment]
If the child task is unable to find "file.jl", why can the parent task find it, even though they have the same CWD?

**Comment by bicycle1885** [comment]
Anyway, calling `include` should not be called in parallel:
> Avoid running top-level operations, e.g. include, or eval of type, method, and module definitions in parallel.
> --https://docs.julialang.org/en/v1/manual/multi-threading/#Caveats

**Comment by jtrakk** [comment]
The example is not calling `include` multiple times in parallel, just once in a thread.

**Comment by tkf** [comment]
This is not going work (at least for now) since: (1) the information of the "current file" is propagated using the task local storage and (2) the task local storage is not inherited by the child tasks (both `@async` and `@spawn`). We'd need an alternative mechanism like https://github.com/JuliaLang/julia/pull/35833 for supporting this. If you definitely need to do this, you can use `Threads.@spawn include(joinpath(@__DIR__, "file.jl"))` instead.

But, As @bicycle1885 said, it is discouraged to use `include` inside tasks. Even if you can make `include` work, you can't use code defined in the included file anyway:

```julia
shell> cat f.jl
f() = 1

julia> @sync @async begin
           include("f.jl")
           f()
       end
ERROR: TaskFailedException

    nested task error: MethodError: no method matching f()
    The applicable method may be too new: running in world age 29610, while current world is 29611.
    Closest candidates are:
      f() at /home/arakaki/f.jl:1 (method too new to be called from this world context.)
    Stacktrace:
     [1] macro expansion
       @ ./REPL[4]:3 [inlined]
     [2] (::var"#1#2")()
       @ Main ./task.jl:406
Stacktrace:
 [1] sync_end(c::Channel{Any})
   @ Base ./task.jl:364
 [2] top-level scope
   @ task.jl:383
```

It is highly recommended to organize your code in such a way that all files are included before the execution starts (unless you are writing, e.g., some kind of editor/IDE backend). For further questions, I think it would be easier to get an answer if you post it on places like Discourse, Slack, and Zulip.
