### ISSUE TITLE
printf prints typemin(<:Signed) incorrectly

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#41971]
```jl
julia> using Printf

julia> @sprintf "%4d" typemin(Int8)
"-/.("

julia> @sprintf "%4d" typemin(Int16)
"--.)*("

julia> @sprintf "%4d" typemin(Int32)
"-./,),(-*,("

julia> @sprintf "%4d" typemin(Int64)
"-'..--).0-*(+,))+(0("

julia> @sprintf "%4d" typemin(Int128)
"-/)0/,//(-,*0,*'.-/)-/*()-0-)/+((,/0+).("```

**Comment by Seelengrab** [comment]
https://github.com/JuliaLang/julia/blob/9cad1e0af8716270a3c0bcd5c70457596fe6c2e2/stdlib/Printf/src/Printf.jl#L295

doesn't work for `typemin`s:

```
julia> typemin(Int8)     
-128                     
                         
julia> -typemin(Int8)    
-128                     
                         
julia> abs(typemin(Int8))
-128                     
```

That line in Printf.jl should only be hit by integer types and floating point is handled somewhere else, right? If so, passing `x` through `unsigned` unconditionally should work, as `x` is assumed positive after this check anyway.

So maybe something as simple as this:

```
neg = arg2 < 0
x = unsigned(x)
```

since 

```
julia> unsigned(typemin(Int8)) == 128
true
```

**Comment by bramtayl** [comment]
That's just the cool way of writing it
