### ISSUE TITLE
Docstring for isapprox: significand should read significant

### ISSUE THREAD

**Issue by PGS62** [JuliaLang/julia#41984]
see issue title!

**Comment by vtjnash** [comment]
If we are going by the wikipedia definition, the first sentence reads "The significand ... is its significant digits," so it would be absurd to claim that these numbers do not have significant digits, since that would make the definition of significand inconsistent. But, on the other hand, the doc string currently includes integers and complex numbers, which do not have a defined significand, so the doc string itself is inconsistent currently.
