### ISSUE TITLE
Warning on OrdinaryDiffEq call

### ISSUE THREAD

**Issue by Peter-Jolly** [JuliaLang/julia#42043]
I recently in installed Julia and VScode on a new machine. All went well although I now find when running one of my programs, which uses the OrdinaryDiffEq package (see below), I continually get a warning (possible call error) as follows. The warning is non-fatal:
Packages used.
# import Pkg
# Pkg.add("CSV")
# Pkg.add("DataFrames")
# Pkg.add("DelimitedFiles")
# Pkg.add("Parameters")
# Pkg.add("OrdinaryDiffEq")
# Pkg.add("BenchmarkTools")
# Pkg.add("Plots")
# Pkg.add("JuMP")
# Pkg.add("Ipopt")
# Pkg.add("Test")

````
Poss{
	"resource": "/c:/Users/peter/Documents/Julia_Code/MPC_Development/Main.jl",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 2,
	"message": "Possible method call error.",
	"source": "Julia",
	"startLineNumber": 572,
	"startColumn": 21,
	"endLineNumber": 572,
	"endColumn": 132
}ible method call error.
````
This refers to the following line:
```
            ##   Call Solver
            prob = ODEProblem(rhs, ystart, (0.0, dT_Control * 60.), p)
            # https://diffeq.sciml.ai/stable/basics/integrator/#integrator
            # default error 10^-6
            # Tsit5() - 5th order Runge Kutta
            # Non adaptive works for both RadauIIA5 and Tsit5.
            # Adaptive step size only works for Tsit5
            integ = init(prob, Tsit5(); save_everystep = false, save_start = false, save_end = false, adaptive = true, dt = dT_Min) 
```
The last line above is line 572. Hope someone can help. Thanks Peter

**Comment by Seelengrab** [comment]
Looks like a problem with OrdinaryDiffEq and/or your `Main.jl` script instead of julia itself, especially if it isn't fatal to the process.
The error message "Possible method call error." also doesn't seem to be generated by julia (at least I can't find it in the julia source code itself), which further suggests a problem with either OrdinaryDiffEq or your code and how you use OrdinaryDiffEq.

This issue tracker is for problems with julia itself - for general debugging help/investigation, please refer to [discourse.julialang.org](https://discourse.julialang.org/) and provide a small example showing the problem such that it's reproducible for anyone willing to help out.

**Comment by Peter-Jolly** [comment]
Ok. But what is very strange is the program has not been changed from my old machine, with no error,  to my new machine. Old machine Intel core new machine AMD. I will persist. Thanks

**Comment by Seelengrab** [comment]
Perhaps a different version of the packages or a new julia version? Hard to investigate without that information. Please also include it in a future discourse post.

**Comment by Peter-Jolly** [comment]
I will persist to locate the reason. I work on the principle, if I am having a problem someone else will as well. Will keep the group informed. Peter

**Comment by Peter-Jolly** [comment]
I found the problem went away when I reinstalled VScode. I think the problem is to do with the limitations of the linter in VScode. I lost a couple of days, but I guess that is par for course when dealing with software still under development.
