### ISSUE TITLE
dmg alternatives  for mac

### ISSUE THREAD

**Issue by pojos** [JuliaLang/julia#42071]
Corp firewall has started blocking all .dmg installs, plus they always blocked brew.
Are there any other alternative install formats for mac?

**Comment by PallHaraldsson** [comment]
.dmg seems like the only official way to distribute Julia (or build from source).

Such questions likely belong on discourse.julialang.org. Please close (at least if this answers).

There's also official Julia docker images (just not sure who's behind them), but while docker works on macOS, the Julia docker seems to be for Windows and Linux (you could fix that?).

Vagrant is or was supported, I'm not up-to-speed on it, never used that nor docker.

https://discourse.julialang.org/t/loaderror-with-packagecompiler-with-docker-on-macos-works-in-docker-on-windows-docker-on-linux-and-in-native-macos/39921/6

https://github.com/staticfloat/julia-vagrant

I wouldn't recommend JuliaPro. I believe it's being phased out (and is behind), and it should have all the same issues if it actually supported macOS.

There might be ways around the firewall... I can't recommend that as it's there for a reason(?), I would ask for an exception/mirror Julia in-house (you can since it's free software). Accessing the Julia General repository is maybe also a problem through the firewall (you can have a local repo).

**Comment by PallHaraldsson** [comment]
I wasn't expecting snap[craft] to work on macOS but it does: https://snapcraft.io/docs/installing-snapcraft

snap is for Linux, and there's a Julia snap (that I don't recommend), and a better unofficial Julia snap. It's unclear to me if those would work on macOS, likely only built for a specific CPU/OS config, but the tech might work to make one for macOS.

**Comment by DilumAluthge** [comment]
If the only issue is the `.dmg` file format, we also distribute the same macOS binaries in `.tar.gz` files.

So e.g. if you want to download this file: https://julialang-s3.julialang.org/bin/mac/x64/1.6/julia-1.6.2-mac64.dmg

You can try this instead: https://julialang-s3.julialang.org/bin/mac/x64/1.6/julia-1.6.2-mac64.tar.gz

**Comment by DilumAluthge** [comment]
Also, I agree that this question is better suited to be asked on https://discourse.julialang.org/

**Comment by PallHaraldsson** [comment]
If you just want to use Julia (at least to learn), you need not install it (while this is for older Julia 1.3.1 currently):

https://replit.com/languages/julia

https://replit.com/talk/announcements/Introducing-Julia-support/11469
>"it's the third-most requested language on Repl.it. That's why today we're excited to announce Julia support."

See also: https://juliahub.com/lp/

**Comment by PallHaraldsson** [comment]
One more way that has macOS support to install Julia: https://github.com/johnnychen94/jill.py Newer Juliaup is similar, originally for Windows only, maybe also macOS now, and it likely will take over to install Julia.

**Comment by staticfloat** [comment]
Those install methods will be downloading the `.dmg` and `.tar.gz` files though, so if those are blocked, it likely won't help much.  :/
