### ISSUE TITLE
reshape should be consistent re copying or sharing data

### ISSUE THREAD

**Issue by dmbates** [JuliaLang/julia#4211]
Currently the documentation for `reshape` states:
```
julia> help(reshape)
Loading help data...
Base.reshape(A, dims)

   Create an array with the same data as the given array, but with
   different dimensions. An implementation for a particular type of
   array may choose whether the data is copied or shared.
```
Copying or sharing should be consistent across array types.  Perhaps use `reshape!` for a version that shares storage and save `reshape` for a version that copies the array's contents.

**Comment by JeffBezanson** [comment]
I do think we should make `reshape` always share data. The first change for that is easy: remove the copying fallback. The harder case is, you guessed it, sparse matrices. The sparse method is the only type-specific one in Base that copies data. Should we deprecate that to a combination of `copy!` and `similar`? cc @ViralBShah @StefanKarpinski

**Comment by tkelman** [comment]
An extension of the generic lazy view could maybe be made to work with a different output size? The copying reshape on sparse matrices could be useful in a few places but for consistency it makes sense to give that a different name.

**Comment by timholy** [comment]
> The sparse method is the only type-specific one in Base that copies data.

Yes, but we have
```jl
julia> A = rand(10,10);

julia> B = sub(A, 1:8, 2:7);

julia> @which reshape(B, (48,))
reshape(a::AbstractArray{T<:Any,N<:Any}, dims::Tuple{Vararg{Int64}}) at abstractarray.jl:202
```
which points to the copy version.

Ref #10507.

**Comment by JeffBezanson** [comment]
Yes, we would need to remove that copy implementation, so reshaping SubArrays becomes an error because it doesn't obey the contract. Then we'd need #10507 to get the function back.

**Comment by StefanKarpinski** [comment]
I wonder if we shouldn't rethink the whole reshape API more radically. After all, this is really the problem child here. Without it, everything else composes fairly nicely.

**Comment by timholy** [comment]
@JeffBezanson, I see, I hadn't thought about forcing the user do an explicit `copy` during an intermediate phase.

For writing generic code, it seems possible people will define a `myreshape` which doesn't copy for Arrays and does for everything else, but perhaps that's still progress.

**Comment by JeffBezanson** [comment]
One use case I see a lot is `reshape(1:n, i, j)`. Clearly that doesn't need to be a reshape, but we should really have an array constructor that directly accepts an iterator of values and a shape. Hard to believe we don't have that already --- do we?

**Comment by timholy** [comment]
Not that I'm aware of.

Over at #15449, `reshape(1:n, i, j)` is working as a 2D view of the range. If the user never tries writing to it, it's actually nicer than using an array; the performance is very good (`1:n` is `LinearFast`, so you're OK), and you never get cache misses during usage.

However, as soon as you try writing, you're hosed. Unless you first say `copy(reshape(1:n, i, j))`.

**Comment by timholy** [comment]
Worth pointing out that this construct is more common in test code than anywhere else.

**Comment by JeffBezanson** [comment]
That sounds great, and a good example of why this issue is needed. We can
fully separate a no-copy reshape of a range from making a dense mutable
range.

**Comment by JeffBezanson** [comment]
Here's an idea: we could give `collect` the same arguments as `similar`, and allow it to accept an element type and shape. We have `collect(T, itr)`, but that would be deprecated to `collect(itr, T)`.

**Comment by timholy** [comment]
:+1: Do you throw an error if `prod(sz) != length(iter)`? Or does it truncate if shorter, and error only if longer?

Since you're thinking about this, another thought: should we consider operators and symmetry? In operations like `A+B`, allocating the output with `similar(A, ...)` is obviously asymmetric. We try to handle that now by letting the element type take account of features of both `A` and `B`, often making use of `promote_op`.

However, the "right" type to allocate may depend on both `A` and `B` in ways that the element type doesn't capture. For example, for `::Tridiagaonal + ::Tridiagonal`, the right type to allocate is `Trididagonal`, but for `::Tridiagonal * ::Tridiagonal` the right type is `BandedDiagonal`. This is not a distinction that can be conveyed by an operation on the element type.

A potential API (which could be parallel to the existing API) is `similar(op, (A, B), sz)`. The advantage of this API is that one can provide specialized methods. The harder part is knowing how to come up with reasonable fallbacks. Presumably, falling back to `Array` would be the best choice, esp. if any of the inputs are `Array`s.

**Comment by andreasnoack** [comment]
Way too late here but after having had some fights with `ReshapedArray`s wrapping `SparseMatrixCSC` and `DArray` lately, I really don't think it it is reasonable to have memory sharing to be part of the `AbstractArray` contract. It's basically to expect that all array types are like `Array`. `ReshapedArray` masks the layout of the underlying array and makes it hard to benefit from specialized methods so in generic code you'd basically would have to `copy` whenever you have done a `reshape`, `dropdims`, `vec` etc.
