### ISSUE TITLE
document translation stages

### ISSUE THREAD

**Issue by bsilbaugh** [JuliaLang/julia#4218]
When reasoning about code performance, it is often helpful to have some kind of mental model (outline) of how code is processed by the compiler/interpretor, and some of the kinds of optimizations (code transformations) that are available. This model is, of course, dependent the particular compiler/interpretor being used. In the case of Julia, a model for the julia program (the official Julia JIT compiler and REPL) should be available to the user community (perhaps as a chapter or section in the Julia manual).

In the case of a dynamic language like Julia, it may be helpful to clearly distinguish between the various phases of source compilation and execution. For example, in LISP, "read", "eval", and "print" are clearly defined phases of program execution. In C++, the notions of "compile time" and "run time" are well defined (which facilitate the definition of static and dynamic/late binding, as well as understanding their significance).

Defining a code processing model for the julia program would also aid the discussion in the user manual on macros and how they can be used to boost performance. At the time of posting, the user manual mentions macros as being expanding during "compilation", which is somewhat ambiguous given the dynamic nature in which Julia code is processed. (Perhaps describing macros as being expanding during "read time" might be clearer?)

I am willing to contribute to the documentation. However, in this case, I can only offer an educated guess as to how julia actually works.

**Comment by ViralBShah** [comment]
Closing as dup of #4800, which is about documenting julia internals.

**Comment by Ismael-VC** [comment]
+1 for this, could we also add some diagrams somewhere? 

The manual is just text and code, not even one image, I also think we could very well use a glossary in the manual to explain this concepts, Julia is the very first language in which I've had to look out for so many references to so many other languages in order to learn the language. Most other languages have a part in which they explain differences and similarities with other languages, but after that it's just language specific, and in the way the docs are currently written, I've had to look out for Fortran, C, Lisp, etc. all the time, I think the manual assumes way to much about the reader background.
