### ISSUE TITLE
Coherent behavior between `sum(x)` and `sum(f, x)` (same for `prod`)

### ISSUE THREAD

**Issue by nandoconde** [JuliaLang/julia#42275]
This does not error:
```julia
sum(Int64[ ]) # 0
```
But this does:
```julia
sum((x) -> (x), Int64[ ]) # Error
```

However, neither do any of these:
```julia
sum(identity, Int64[ ]) # 0
sum((x) -> (x), Int64[ ]; init = 0) # 0
```

Is this intended behavior, or just missing corner cases?

**Comment by KristofferC** [comment]
`mapreduce` (which is what `sum` ends up calling) is special-cased for `identity` since the behavior of that function is known:

https://github.com/JuliaLang/julia/blob/5a1b8be01bdd3f604c95c449acbfc1ea74f2af20/base/reduce.jl#L354-L356

For an arbitrary predicate, it is unclear what the zero-element is, so it errors. Also when an explicit `init` is given, that can also be used. So the issue here is that there just isn't a good value to return in the case that you mentioned errors.

**Comment by nandoconde** [comment]
I guess there is no possible way to know ahead of time what type of `init` is to be used unless the function provided is explicitly compiled and typed.

The only case I can think of where the Type is totally known beforehand would e something like this:
```julia
function fun(x)::Float64
    return x
end

sum(fun, Float64[ ]) # Error too
```

**Comment by KristofferC** [comment]
> The only case I can think of where the Type is totally known beforehand would be something like this:

There isn't really a good "Julian" way of getting this information though. You need to start invoking inference and doing that explicitly at runtime has drawbacks so it has in general been avoided.

**Comment by nandoconde** [comment]
Perfect. Thanks for explaining! I close the issue :)
