### ISSUE TITLE
ERROR: syntax: invalid named tuple element

### ISSUE THREAD

**Issue by sprmnt21** [JuliaLang/julia#42360]
I would have expected the same result from the following expressions.
Is it a parsing error or is it a choice that depends on other reasons? 

```
(;(:a,1)) #RROR: syntax: invalid named tuple element "(:a, 1)"

(;[(:a,1)]...) #(a = 1,)


(;((:a,1),)...) #(a = 1,)
```

**Comment by JeffBezanson** [comment]
Yes this was intentional. Named argument context uses non-standard evaluation that only supports certain specific syntax forms. For example, even `(; x)` has a special meaning (equivalent to `(; x = x)`), so we can't allow arbitrary expressions that might evaluate to pairs/tuples. We could support the tuple syntax mentioned here, making `(; (a,b))` equivalent to `(; a=>b)`, but I'm not sure that's worthwhile, since it just allows spurious syntax variations.

**Comment by vtjnash** [comment]
same as this:
```
julia> f(; (:x, 1))
ERROR: syntax: invalid keyword argument syntax "(:x, 1)" around REPL[3]:1
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```
