### ISSUE TITLE
Make documentation clear about handling of `local` in global scope

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#42664]
Following https://stackoverflow.com/questions/69587809/how-to-think-of-begin-block-in-julia and discussion on Slack it would be ideal to make a clear explanation in the Julia manual how the following code blocks:
```
x = 1
local x = 0
@show x
```
and
```
x = 1
begin
    local x = 0
    @show x
    x += 1
end
@show x
```
and
```
x = 1
if true
    local x = 0
    @show x
    x += 1
end
@show x
```
are handled if they are in global scope in two modes:
1. run in REPL
2. run from script

CC @JeffBezanson

**Comment by JeffBezanson** [comment]
See #10472

The answer is that each top-level expression has an invisible scope block around it that `local` uses. I'm pretty sure you can only detect the presence of this invisible scope with `local` declarations; otherwise it shouldn't affect anything. This should be the same in a script and the REPL.

Historically, this was useful for hygienic macros, which can freely add new `local` variables without either (1) introducing an explicit scope block like a `let` or (2) leaking variables into the global namespace, when used at the top level.

**Comment by tomtuamnuq** [comment]
We could add something at the end of [Global-Scope Docs](https://docs.julialang.org/en/v1/manual/variables-and-scoping/#Global-Scope) to describe the behavior of `local `keyword in global scope. 
The [docs](https://docs.julialang.org/en/v1/manual/variables-and-scoping/#man-scope-table) explicitly state "Notably missing from this table are begin blocks and if blocks which do not introduce new scopes. " For me this causes some confusion.
I would therefore add a sentence to the description of global scope to state that begin and if blocks end the local scope after using local, because "if a top-level expression contains `local x = ...`, then that expression has its own local scope" ( as @JeffBezanson stated in [10472](https://github.com/JuliaLang/julia/issues/10472#issuecomment-321584501) )

I have tested the code blocks in interactive mode and from script and it is the same. Since the docs already state
 "Note that the interactive prompt (aka REPL) is in the global scope of the module Main." for me it seems clear.

**Comment by KristofferC** [comment]
We typically don't assign issues to persons unless there is a strong reason to do so (e.g if the person is the original author of the code that needs fixing). If you want to work on this, you can just open a PR, no need to get assigned.
