### ISSUE TITLE
Maybe deprecate BigFloat(f::FloatingPoint) constructor

### ISSUE THREAD

**Issue by ivarne** [JuliaLang/julia#4278]
There has been a [long of discussion](https://groups.google.com/forum/#!topic/julia-users/fVqGvMIOmDY) in the julia-users group that started with a user that used the `BigFloat(2.1)` constructor and expected to get the same result as `BigFloat("2.1")`. The problem arrises because most floating point types in computers are stored as base2 fractions, but a programmer works in base10. A lot of base10 fractions can not be represented as a finite binary fraction, just like `one third = 0.1(base3) = 0.33333333333333...(base10)`. When programmers forget this property of computers they get unexpected results.

As the current solution is confusing (for newcomers) and leads to very hard to find bugs, I want to propose some solutions and have it open for discussion on github (where it might be easier to find in the future than the High traffic julia-users list).
1. Change BigFloat(f::FloatingPoint) so that it gives the shortest base10 fraction that would convert back to the same f value. Easy implemented as `BigFloat(f::Union(Float64,Float32,Float16)) = BigFloat(string(f))`. This approach might be unexpected by experienced MPFR users and also lets programmers write `BigFloat(2.1^256)` which obviously will not give the desired result. See: https://github.com/JuliaLang/julia/pull/1015
2. Deprecate BigFloat(f::FloatingPoint) constructor so that it gives an error explaining floating point precision and suggest initialization by string. For those who needs the floating point constructor, and understand, it could be renamed to something somewhat scary so that it has a better chance of not being used wrong. (eg. `BigFloatFromFloat64()`, or `convert(BigFloat, 2.1)`)
3. Somehow change how Julia treats numeric constants so that the BigFloat constructor can access the raw base10 representation.
4. Add syntax for construction of BigFloats and other special numbers. `big"2.1"` and or `2.1b0`
5. Use the existing api and let those who won't read the documentation have programs that contains errors they tried hard to avoid by using `BigFloat`.
6. Add a (mandatory?) second parameter, ´BigFloat(f::Float64, signif::Int)´, where `signif <= 0` gives the current behavior. Deprecation can be done by giving `signif` a magical negative value that triggers a deprecation warning. This approach could also be used for `big`.

**Comment by jirkadanek** [comment]
@nalimilan I believe it could be made practical. Go has arbitrary precision compile time constants that get converted to Int or Float if they are used in a non-compile-constant context. I want to propose doing something similar.

> Constant expressions are always evaluated exactly; intermediate values and the constants themselves may require precision significantly larger than supported by any predeclared type in the language. The following are legal declarations […] —https://golang.org/ref/spec#Constant_expressions

If a function is called with a FloatLiteral argument at position where it explicitly declares a FloatLiteral argument, it will get FloatLiteral, if it does not declare any type or declares a Float64 type, it will get Float64.

In line with this, I suggest making FloatLiteral a second-class citizen. It cannot be assigned into a variable (that would convert it into Float64), it is converted to Float64 before being used in a non-literal expression (0.5*0.6 is still FloatLiteral, 0.5*a for some variable a first converts 0.5 to Float64). It can pretty much be only passed as an argument to a function (BigFloat constructor). One trick pony.

**Comment by nalimilan** [comment]
Sounds interesting. The problem is that in Julia the distinction compile time vs. run time isn't as clear as in Go, so you'll necessarily expose that `FloatLiteral` type outside of the compiler, and currently there's no mechanism to make objects of this type "disappear" as soon as you touch it. Maybe something like that ("automatic conversion"?) would also be useful for `MathConst`.

**Comment by StefanKarpinski** [comment]
I don't think that introducing second-class, compile-time-only types is a satisfactory solution – it just complicated matters further. In Go, for example, you get completely different behavior if you operate on a literal than if you assign that literal to a variable and do the same operation on it, which, of course, confuses people. Instead of just explaining to people that computers binary instead of decimal – which is something they're going to need to know about to do numerical computing effectively – you *also* have to explain that there's this subtle difference between literal numbers runtime numbers. So now people have two confusing things to learn about instead of just one.

**Comment by jirkadanek** [comment]
I am using Julia only as "faster Octave", so I surely don't see all the consequences for the language. I just realized my example with 0.5 * 0.6 staying a FloatLiteral is very problematic because the programmer might want to redefine operators (something that Go does not allow, and for good reasons, while Julia wants that, and for good reasons too).

If a FloatLiteral would always collapse into a Float64 every time it is touched except when it is passed as a function parameter or treated as a string, the whole thing provides only syntactic convenience over passing in strings. Then it is probably not worth having. On the other hand, it does not create the semantic difficulties as in Go (because then it has no semantics).

What about attaching a string property to every Float64 that would contain the token in the source code that led to creation of that number? Possibly keeping the property around only "for a short time" (the same lifetime as my version of FloatLiteral was supposed to have)? Or storing it only if the string cannot be "losslessly" recovered from the binary representation of the number, otherwise computing it when needed? (suggestion # 3)

I like suggestion #6 the most, it would IMO work well and it does not require wild changes like # 3.

**Comment by simonbyrne** [comment]
I originally thought a float literal type could be a good idea, but I have come to change my mind: it would be really confusing to have
```
x = 0.1; y = BigFloat(x)
y = BigFloat(0.1)
```
do different things.

I think this problem could be alleviated somewhat by having a separate syntax for nonstandard numeric literals: I think postfix underscores could be nice:
```
y = 0.1_BigFloat
```

**Comment by simonbyrne** [comment]
On a related note, one thing I would like to have is a `print_full` which displays the full decimal expansion of a floating point number, e.g.
```
julia> print_full(0.1)
0.1000000000000000055511151231257827021181583404541015625
```
At the very least, it would be great for teaching floating point....

**Comment by StefanKarpinski** [comment]
I'm starting to feel like we should ditch numeric literal juxtaposition and use `<number><identifier>` more generally for different kinds of number inputs. If this invoked a macro in the general case, then we could continue to have `im` and unit input syntax work with the appropriate macro definitions. What we would give up generally is using that syntax for random local variables, but we would retain that kind of syntax for globally defined syntaxes. I also think it would be nice to allow spaces: `<number> <identifier>`.

**Comment by simonbyrne** [comment]
> I'm starting to feel like we should ditch numeric literal juxtaposition and use <number><identifier> more generally for different kinds of number inputs. 

I, for one, would be willing to sacrifice implicit multiplication for this.

**Comment by johnmyleswhite** [comment]
+1 to that. I never use implicit multiplication in practice.

**Comment by Mike43110** [comment]
On implicit multiplication, isn't `number.variable` close enough? Though it currently only works with integers. Not sure how difficult it would be to extend that to other numerical types.

**Comment by jiahao** [comment]
@Mike43110 "4.x" is parsed as "4.0 * x" and does not always preserve the semantics of integer operations. A simple counterexample:

```jl
julia> x=1
1

julia> 10_000_000_000_000_001x == 10_000_000_000_000_000x #integer arithmetic
false

julia> 10_000_000_000_000_001.x == 10_000_000_000_000_000.x #floating point arithmetic
true
```

**Comment by oscardssmith** [comment]
Bump with new idea: What would happen if we just deprecated creating BigFloats from floats? If we forced them to be made from int's, rationals, or other more exact types, we would get rid of all cases with unexpected behavior. This does seem fairly radical, but I'm not sure it's a bad idea.

**Comment by simonbyrne** [comment]
I frequently create bigfloats from floats, for checking the precision loss of computations. In fact that's the main thing I use them for.

**Comment by oscardssmith** [comment]
Could there at least be a warning? It seems like a lot of hard to catch errors could result form expressions like `BigFloat(1/3)`, which really look like construction of a value rather than a conversion.

**Comment by stevengj** [comment]
It seems like this issue could be closed?  It seems like the clear consensus here is that the current 
 behavior of `BigFloat(::AbstractFloat)` is correct and desirable.

As I commented on [discourse](https://discourse.julialang.org/t/sum-of-float64-vector-gives-slightly-incorrect-answer/8577/20?u=stevengj), my `@changeprecision BigFloat` macro already basically does what people want here — it allows you to write ordinary floating-point literals and change them *en masse* in a large code block to the desired `BigFloat` value, thanks to the grisu algorithm which allows us to recover the "exact" form in which the literal was entered.

In principle, we could use the grisu trick in the `BigFloat(::AbstractFloat)` constructor as well:
```jl
julia> mybig(x::AbstractFloat) = parse(BigFloat, string(x))
mybig (generic function with 1 method)

julia> mybig(2.1) == big"2.1"
true
```
though this is somewhat expensive.

**Comment by StefanKarpinski** [comment]
Even if people find it confusing, I don't think having `BigFloat(x::Float64)` do the equivalent of `parse(BigFloat, string(x))` is really appropriate since converting a float value to `BigFloat` has a correct and precise meaning which is what we're doing now.
