### ISSUE TITLE
Warnings when working with singular matrices

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaLang/julia#4286]
Consider the following example taken from http://www.walkingrandomly.com/?p=5092:

```
A = [1 2 3;
     4 5 6;
     7 8 9];

b = [15, 15, 15]

x = A \ b
```

On my OS X build of master, this produces the solution: 

```
3-element Array{Float64,1}:
 -39.0
  63.0
 -24.0
```

which is valid, but could potentially have been quite inaccurate. As the linked blog post notes, Matlab offers a warning in this case that the condition number of `A` is very high and that the result may be inaccurate.

Julia should probably also raise warnings when solve operations are likely to produce inaccurate solutions.

**Comment by andreasnoack** [comment]
Continuing the discussion from https://github.com/JuliaLang/julia/commit/4bf31d868ce1a93b921dbb21032c3fff272a0ece#commitcomment-9597896 here since this issue is about exactly the topic of the discussion.

@jakebolewski, @jiahao and I talked about some options this afternoon. The conclusion so far is that it would be useful to be able to either turn off the warning or catch them as with exceptions, but at the same time allow a default behavior with warning because they can be vary useful. In particular for non-experts of numerical linear algebra.

A problem is that `\` is very restricted in terms of possible arguments: because it is infix, it can really only take two arguments and it should return a matrix or vector of the result, e.g. a tuple with condition number or other auxiliary output would be very inconvenient.

One solution that we thought could accomplish this is that `\`, which we consider the default for use in the REPL or simple scripts, always warns when the condition number is above some threshold, but that `A_ldiv_B!` gets extended. Then `A_ldiv_B!` would serve as the "export" method where more control is provided. It already has this kind of interpretation because it works on a preallocated output array.

Since `A_ldiv_B!` writes the solution to one of it's arguments and isn't an infix operator, it can be much more flexible. It could therefore take an argument that controls the behavior when the problem matrix is ill conditioned, e.g. you could choose between something `:ignore`, `:warn` and `:throw`. The method is also free to return all kinds of information if we want it to do so. We could consider an option of error bounds of the solution or other auxiliary output.

**Comment by tkelman** [comment]
I don't know if this will necessarily have to be in `A_ldiv_B!` since the computational complexity of determining whether or not to warn (or calculate the quantity that the warning decision would need to be made from) could vary widely depending on the types of the arguments. I'm not sure if this can be done generically, it might be more appropriate to handle at an expert-driver lapack wrapper level.

**Comment by andreasnoack** [comment]
Some options might not be very generic, and are therefore better handled at the individual solver level, but I think the decision of whether to warn, throw or to remain silent could be considered generic.

**Comment by tkelman** [comment]
Sure, but it feels like `A_ldiv_B!` (or just `ldiv!` if we can simplify it down to that via transpose types) is maybe not the right API for adding this to. Particularly when you start getting into error bounds and other outputs.

**Comment by tkelman** [comment]
Bump. The logic on master is still wrong here and needs to be fixed while we determine a better API. `isinteractive` is the wrong thing to use for deciding whether or not to print warnings.

**Comment by Sacha0** [comment]
Unlikely to receive attention prior to 0.6. Best!

**Comment by c42f** [comment]
Now that #24490 is merged, we have some more expressive options for generating warnings and capturing them.  Also for possibly turning them into exceptions with the right Logger installed, though I'm not yet sure that's a pattern which should be encouraged.

**Comment by inkydragon** [comment]
In Julia 1.6.3/1.7.0-rc1 `A \ b` just throw an error, and `ldiv!` gives a right answer. 
Can this issue be closed now?

```julia
julia> A = [1 2 3; 4 5 6; 7 8 9];

julia> b = [15, 15, 15.0];

julia> x = A \ b
ERROR: LinearAlgebra.SingularException(3)
Stacktrace:
 [1] checknonsingular
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\LinearAlgebra\src\factorization.jl:19 [inlined]
 [2] checknonsingular
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\LinearAlgebra\src\factorization.jl:21 [inlined]
 [3] #lu!#146
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\LinearAlgebra\src\lu.jl:82 [inlined]
 [4] #lu#153
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\LinearAlgebra\src\lu.jl:279 [inlined]
 [5] lu (repeats 2 times)
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\LinearAlgebra\src\lu.jl:278 [inlined]
 [6] \(A::Matrix{Int64}, B::Vector{Int64})
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\LinearAlgebra\src\generic.jl:1142
 [7] top-level scope
   @ REPL[3]:1

julia>

julia> using LinearAlgebra

julia> x = copy(b);

julia> ldiv!(qr(A), x)
3-element Vector{Float64}:
   3.0000000000000244
 -21.00000000000002
  18.0

julia> A * x
3-element Vector{Float64}:
 14.999999999999979
 14.999999999999986
 15.0

julia> A * x ≈ b
true
```

**Comment by andreasnoack** [comment]
Nothing here has changed except maybe the instructions sets used for running the examples. If the LU factorization hits an exact zero then an exception is thrown but we otherwise don't do anything about nearly singular matrices. E.g.

```julia
julia> A = [1.0 2 3; 4 5 6; 7 8 9];

julia> A[3,3] -= eps(9.0);

julia> A\b
3-element Vector{Float64}:
 -18.0
  21.0
  -3.0
```

I'm not sure we should, be this we should keep this issue open until we decide what to do.

**Comment by ViralBShah** [comment]
We now give a singluar exception. 

```
julia> A = [1 2 3;
            4 5 6;
            7 8 9];

julia> b = [15, 15, 15]
3-element Vector{Int64}:
 15
 15
 15

julia> x = A \ b
ERROR: SingularException(3)
Stacktrace:
 [1] SingularException
   @ ~/julia/usr/share/julia/stdlib/v1.9/LinearAlgebra/src/exceptions.jl:21 [inlined]
 [2] checknonsingular
   @ ~/julia/usr/share/julia/stdlib/v1.9/LinearAlgebra/src/factorization.jl:19 [inlined]
```
