### ISSUE TITLE
MD5 and GPG files can not be downloaded (Access Denied)

### ISSUE THREAD

**Issue by ptrktn** [JuliaLang/julia#42967]
`curl https://julialang-s3.julialang.org/bin/linux/x64/1.6/julia-1.6.3-linux-x86_64.tar.gz.asc`
`curl https://julialang-s3.julialang.org/bin/checksums/julia-1.6.3.md5`

The result for both is an XML document indicating 'Access Denied'.

**Comment by ararslan** [comment]
Apparently the checksums for all Julia versions back to 0.3, as well as all(?) of the GPG signatures, were reuploaded to our S3 bucket with incorrect permissions today at 3:20pm Pacific. I've fixed the permissions for the checksums manually since those are easy. The GPG ones are more annoying though; going through all of them manually isn't really feasible (at least for me at the moment). @staticfloat, any idea what could have happened here?

**Comment by staticfloat** [comment]
Sorry, this looks to be a bug in `s3cmd` that flipped a bunch of permissions while I was trying to get it to set a different metadata field.  I've fixed it, I believe, please try again and let us know if anything still gives you a 403 error.

**Comment by ptrktn** [comment]
Confirmed the links are working and expected content is returned, closing this issue.

**Comment by inkydragon** [comment]
@staticfloat 1.7.0-rc3 AccessDenied
https://julialang-s3.julialang.org/bin/checksums/julia-1.7.0-rc3.sha256
https://julialang-s3.julialang.org/bin/checksums/julia-1.7.0-rc3.md5

**Comment by ararslan** [comment]
I've fixed those.

**Comment by taoky** [comment]
@ararslan The following links seem to be set with wrong permission since 5/28/2022:

- https://julialang-s3.julialang.org/bin/mac/aarch64/1.8/julia-1.8.0-rc1-macaarch64.tar.gz.asc
- https://julialang-s3.julialang.org/bin/musl/x64/1.8/julia-1.8-latest-musl-x86_64.tar.gz
- https://julialang-s3.julialang.org/bin/musl/x64/1.8/julia-1.8-latest-musl-x86_64.tar.gz.asc

Thanks in advance for looking into this issue.

**Comment by ararslan** [comment]
Thanks @taoky, those should now be fixed.

**Comment by taoky** [comment]
The file https://julialang-s3.julialang.org/bin/winnt/x86/1.9/julia-1.9.0-beta1-win32.tar.gz seems to be set with incorrect permission (since 12/28/2022?)
