### ISSUE TITLE
`InteractiveUtils` methods show incorrect method for negative powers

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#43337]
```julia
julia> @code_typed true ^ -1
CodeInfo(
1 ─ %1 = Base.slt_int(p, 0)::Bool
└──      goto #5 if not %1
2 ─ %3 = Base.not_int(x)::Bool
└──      goto #4 if not %3
3 ─      invoke Base.throw_domerr_powbysq(_2::Bool, _3::Int64)::Union{}
└──      unreachable
4 ─      nothing::Nothing
5 ┄ %8 = (p === 0)::Bool
│   %9 = Base.or_int(%8, x)::Bool
└──      goto #6
6 ─      return %9
) => Bool

# as expected
julia> a = true ^ 1; println(a, " ", typeof(a))
true Bool

# ???
julia> a = true ^ -1; println(a, " ", typeof(a))
1.0 Float64

# strangely, these forms work
julia> a = true ^ Int64(-1); println(a, " ", typeof(a))
true Bool
julia> a = true ^ -Int64(1); println(a, " ", typeof(a))
true Bool
```

**Comment by Seelengrab** [comment]
I think the difference to `true ^ Int(1)` is due to literal integer powers being handled specially during parsing - it's the only time we truly know what function to apply and since `true isa Number`, it gets promoted and computed as `1 / 1`, which is `1.0`. Exponentiation with literals being quasi type unstable is known.

**Comment by BioTurboNick** [comment]
Ahh interesting. Okay. Why are they handled specially?

**Comment by BioTurboNick** [comment]
Oh, so is the issue just that `inv(x::Bool) = x` should be defined?

**Comment by BioTurboNick** [comment]
Although, I guess that leaves the question of why InteractiveUtils doesn't show the correct method lowering.

**Comment by BioTurboNick** [comment]
I guess this is a duplicate of #21014.

**Comment by Seelengrab** [comment]
It's handled specially because we can, at parse time, figure out that the exponent is negative (it's a literal after all, the type can't magically change) and thus the result will be a `Float64`. This makes it stable by not going through the regular `^`. `x^(-y)` will after all always be `1/(x^y)`, with some edge case caveats.
