### ISSUE TITLE
TTFP for Set of NTuple with large N is long.

### ISSUE THREAD

**Issue by jwkvam** [JuliaLang/julia#43343]
I was using NTuple{N, Int64} for the type of a set. I increased N to 1024 and discovered that creating the empty set was taking a long time. I'm using Julia 1.7.0. I have since changed to a different type to avoid this.

```
time julia -e 'x = Set{NTuple{1024, Int64}}(); @show x'
```
Executed in 77.37 secs

I tried some other values of N to see how it changes.

|N | Time|
| -----|------|
|128 | 5.25s|
|256 | 8.73s|
|512 | 20.94s|

It took 23.5s with Julia 1.6.4. I did not try other versions.

```
julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, sandybridge)
```

**Comment by oscardssmith** [comment]
I think this is a known problem, but I'm having trouble finding the dup.

**Comment by mikmoore** [comment]
Someone else can give a more thorough and motivated response, and probably link many relevant existing discussions and issues, but I'll relay what knowledge I've learned from these discussions in the past:

A `Tuple` is not intended to be used as a large collection. The compiler does not (currently) handle large tuples gracefully. The compiler essentially writes code for every single element, which means tuples have roughly zero runtime overhead (even when inhomogeneous). However, the cost of this is compiler work for every single element in the NTuple. Further, this large amount of work results in a large amount of compiled code which can also have runtime detriments.

Personally, `x = ntuple(identity,Val(2^14))` is enough to cause my session to eat more than 4GB of memory before finally throwing a very long and angry error.

This could presumably be improved by allowing large homogeneous tuples to be handled differently than they currently are (like statically-allocated arrays in C, I think?), but this has been an extremely low priority because an `Array` tends to have similar runtime performance -- and no compile slowdowns like you're seeing here -- to `NTuple` once they reach a hundred elements or so.

I would recommend an `Array{T,1}` instead of a `NTuple{N,T}` once `N` starts getting on the order of 20 or 50. Even if there are eventual improvements to the handling of large `NTuple`, there is likely to be minimal performance improvement over `Array` at significant sizes.

**Comment by oscardssmith** [comment]
Yeah. Ideally, we would be able to do this automatically in the compiler. In an ideal world, the compiler would be able to perform inference for all N at the same time so the functions were type stable, generate specialized code for small `N`, and generate generic code for large N. Doing this in practice, however is probably really hard.

**Comment by jwkvam** [comment]
Thanks for the explanations! I did move to an Array type. I was using Tuples for their immutability but I can live without it.

**Comment by PallHaraldsson** [comment]
In case helpful, it's also a (larger) regression from at least 1.3.1 (a random version I checked):

```
$ time ~/julia-1.3.1/bin/julia -e 'x = Set{NTuple{128, Int64}}(); @show x'
x = Set(NTuple{128,Int64}[])

real	0m1,782s

$ time ~/julia-1.7.0/bin/julia -e 'x = Set{NTuple{128, Int64}}(); @show x'
x = Set{NTuple{128, Int64}}()

real	0m5,528s

$ time ~/julia-1.6.0/bin/julia -e 'x = Set{NTuple{128, Int64}}(); @show x'
x = Set{NTuple{128, Int64}}()

real	0m3,840s


$ time ~/julia-1.3.1/bin/julia -e 'x = Set{NTuple{1024, Int64}}(); @show x'
x = Set(NTuple{1024,Int64}[])

real	0m41,343s

$ time ~/julia-1.7.0/bin/julia -e 'x = Set{NTuple{1024, Int64}}(); @show x'
x = Set{NTuple{1024, Int64}}()

real	1m42,155s
```

**Comment by ViralBShah** [comment]
```

julia> 
➜  ~ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.2 (2023-07-05)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time x = Set{NTuple{1024, Int64}}(); @show x
  0.000007 seconds (7 allocations: 128.328 KiB)
x = Set{NTuple{1024, Int64}}()
Set{NTuple{1024, Int64}}()
```
