### ISSUE TITLE
Docs: Recommend `read(filename, String)` and `write(filename, contents)` instead of `open`

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/julia#43428]
Julia has two super easy to use functions:
```julia
julia> write("hello.txt", "world")
5

julia> read("hello.txt", String)
"world"
```

That should cover file I/O needs in most cases, without having to deal with file handlers! 🎉 I think this is really useful for many (beginner) users, but not visible enough. Whenever I give this tip to a new Julia user, they react along the lines of: *"If only I knew this earlier!"*

**We should recommend this in our docs.** My suggestions:
1. Right now, our [manual entry on "Working with files"](https://docs.julialang.org/en/v1/manual/networking-and-streams/#Working-with-Files) uses `open(filename::String, mode::String)` to create a file handler (the first handler is even left open!). Instead, this first example could use my above snippet. (Also, *Working with Files* could be its own chapter in the manual?) https://github.com/JuliaLang/julia/pull/49834
2. [`write`](https://docs.julialang.org/en/v1/base/io-network/#Base.write) should have a short, simple docstring for just the `write(filename::String, x)` method. https://github.com/JuliaLang/julia/pull/49835 and https://github.com/JuliaLang/julia/pull/49836
3. The docstrings for `read(filename::String, args...)` and `write(filename::String, x)` should appear more prominently in the page [IO and Network](https://docs.julialang.org/en/v1/base/io-network), before the `open` function. Simple `filename` methods should appear before `IO` methods. https://github.com/JuliaLang/julia/pull/49837
4. [`isfile`](https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.isfile) could use the direct `read` and `write` methods. https://github.com/JuliaLang/julia/pull/45261
5. We could add links to `read` and `write` from the [Filesystem](https://docs.julialang.org/en/v1/base/file/) chapter. https://github.com/JuliaLang/julia/pull/49838

I would be happy to write this PR myself, let me know which of these points (1-5) are welcome!

**Comment by AUSt-in** [comment]
can I work on this issue please

**Comment by oscardssmith** [comment]
you don't need to ask. Just make a PR.

**Comment by Ellipse0934** [comment]
The manual entry [you've linked](https://docs.julialang.org/en/v1/manual/networking-and-streams/#Working-with-Files) is inside the `Networking and Streams` category which makes it fine imo. 

However, I would like to suggest a new section `Working with files` in the manual section itself instead of `Manual > Networking and Streams > Working with Files`with the following contents
1) `pwd(), isfile(), readdir()` to check for files and traverse the filesystem tree.
2) Simple `read(filename, String)` & `write(filename, str)` as Fons as suggested.
3) Pointer to [FileWatching stdlib](https://docs.julialang.org/en/v1/stdlib/FileWatching/).
3) Pointer to the `Networking & Streams > Files` section to work with OS file descriptor friendly code.
4) Pointer to [delimited files stdlib](https://docs.julialang.org/en/v1/stdlib/DelimitedFiles/) and [mmap files](https://docs.julialang.org/en/v1/stdlib/Mmap/).

When I say pointer I mean a short example and write up followed by a link to the section with docstrings.

**Comment by fonsp** [comment]
I made a bunch of PRs!

https://github.com/JuliaLang/julia/pull/49834
https://github.com/JuliaLang/julia/pull/49835
https://github.com/JuliaLang/julia/pull/49836
https://github.com/JuliaLang/julia/pull/49837
https://github.com/JuliaLang/julia/pull/49838
