### ISSUE TITLE
using/importall: clashing names should be dropped

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#4345]
I think this is the only safe behavior: if you do `using Foo` and `using Bar` and both export a `frizz` function, then neither should show up – otherwise you're depending on some arbitrary ordering of `using` statements. This also means that a new export can only cause programs to break in the obvious manner of a name that used to be accessible becoming inaccessible, rather than the meaning of a function changing. Having neither export show up also follows the dynamic language tradition of not causing any problems as long as you don't use the problematic thing – so name clashes only affect you if you actually need to use the name that clashes.

**Comment by mauro3** [comment]
For posterity, there was quite a bit discussion about this issue here:
https://groups.google.com/d/msg/julia-users/p5-lVNlDC8U/6PYcvvsg29UJ

**Comment by greenflash1357** [comment]
My apologize for picking this up again, but I don't understand why merging exported functions with the same name (unless there are no conflicting methods) is off the table.
This seems to be the most natural and universal thing for me.

**Comment by mauro3** [comment]
Have you seen https://github.com/davidagold/MetaMerge.jl? If there is a package which does it there is  little reason to force this upon all of us.

**Comment by timholy** [comment]
Make yourself a nice cup of tea and then start reading at https://groups.google.com/d/msg/julia-users/sk8Gxq7ws3w/rs-Ej4oUSuwJ. There are also several other relevant threads.

**Comment by greenflash1357** [comment]
After reading through [the thread](https://groups.google.com/d/msg/julia-users/sk8Gxq7ws3w/rs-Ej4oUSuwJ) and also [this one](https://groups.google.com/forum/#!msg/julia-users/p5-lVNlDC8U/6PYcvvsg29UJ), I (still) share the opinion of Petr Krysl.

Yet, there are two main arguments against what we desire:
 1. Automatic merging of generic functions can mix up different concepts under the same identifier
 2. Automatic merging of generic functions can silently change the behavior of existing methods for super types

Before I try to weaken these arguments, I'd like to recall the current possibly approaches to tackle the name clash issue:
 1. Use fully qualified names
 2. Wait for a name clash, then import the existing function and manually extend it with your methods

The drawbacks of both solutions are obvious: Additional effort in both cases and in addition all the disadvantages of extending generic functions in the second case.

To reduce the effort, I again propose automatic merging of generic functions! Why? Because...
 1. Different concepts might have the same name, but still can be distinct easily by context. To stick to the widely used example: "Whats color of a bark of a birch?" and "Bello, stop barking!" won't be misinterpreted in most cases. That's the inherent nature of multiple dispatch. The arguments decide what we want to do, not the name. 
 2. Merging conflicts can be extended to not occur when the parameter lists are exactly the same, but also when any parameter is a sub/super type of the respective other parameter. This will allow for automatic merging in some cases and prevent monkey patching in the other cases. 

Remaining conflicts will then be a hint that someone might already have implemented the same concept. 
When will ::Tree and ::Dog be related anyway? Most likely only via ::Any. And using ::Any as parameter type might either be bad practice or because of the fact that you have the most general method implementing the most general concept.
