### ISSUE TITLE
Documentation should emphasise severe type system issues

### ISSUE THREAD

**Issue by yadayadaydadaa** [JuliaLang/julia#43514]
Continuation from https://github.com/JuliaLang/julia/issues/43512#event-5801793716 that another hostile person locked. 

Sure the const trick helps, but your documentation doesn't mention that it is also needed for type aliases. Explicit type aliasing instead of treating types as variables would thus seem to make the type system much more usable. Going back to https://github.com/JuliaLang/julia/issues/43492#issuecomment-998051341 probably some similar problem is going on in the core as well, Int and Float being treated completely differently. It does not compute.

**Comment by Moelf** [comment]
as mentioned in # 43492:
>Boxes for integers up to a certain number are preallocated.

so yes, this is by design, not some "problem" going on in Core.
- - -
const is covered by: https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-global-variables because there's nothing special about something being a type or not:
```julia
julia> a = Int64
Int64

julia> a = Float64
Float64
```
you can re-bind it as long as it's not `const`

**Comment by fredrikekre** [comment]
Please ask questions on https://discourse.julialang.org/.

**Comment by oscardssmith** [comment]
StackOverflow would be another acceptable venue.
