### ISSUE TITLE
Parsing empty string to date

### ISSUE THREAD

**Issue by adkabo** [JuliaLang/julia#43883]
I expected an exception but got a Date:

```jl
julia> parse(Date, "")
0001-01-01
```

**Comment by elextr** [comment]
Explicitly documented to behave this way in https://docs.julialang.org/en/v1/stdlib/Dates/

**Comment by adkabo** [comment]
It looks like the reason this happens is to allow parsing incomplete date strings.

```jl
julia> parse(Date, "2000-03")
2000-03-01
```

There may be use cases for a function like that. In the case where an explicit date format is provided, it's rather unexpected.

```jl
julia> parse(Date, "", dateformat"yyyy-mm-dd")
0001-01-01
```

I often encounter missing data in the form of an empty string, and having it parse to 0001-01-01 instead of failing is very error-prone for my use cases. 

Two ideas:
- Change `parse(Date, s, fmt)` so it throws an error if `s` doesn't match `fmt` exactly. This would break backward compatibility. If desired, introduce a `PartialDateFormat` that supports partial matches.
- Retain the current behavior and introduce a `CompleteDateFormat` created with `completedateformat"yyyy-mm-dd"` that would throw an exception here.

**Comment by elextr** [comment]
Perhaps you need [tryparse](https://docs.julialang.org/en/v1/base/numbers/#Base.tryparse)

**Comment by nalimilan** [comment]
I agree this is quite dangerous. At least it would make sense to reject empty strings, as then you don't extract any information from the string so it's absolutely useless. But changing it would be breaking so it cannot happen before 2.0.

Rather than introducing a `CompleteDateFormat` type, maybe we could use non-standard string literal flags like in regexes? For example, `dateformat"yyyy-mm-dd"c` would require a **c**omplete string but `dateformat"yyyy-mm-dd"p` would allow **p**artial matching?

Another option would be to add an argument to `parse`.

**Comment by PallHaraldsson** [comment]
Can this be considered a bug and changed in 1.x?

Despite "Explicitly documented", does anyone rely on (the very unhelpful, and illegal date, the docs can be changed, and non-default option to allow old way):
```
julia> parse(Date, "")
0001-01-01
```

https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Dates_and_numbers#Dates,_months,_and_years
>Use yyyy-mm-dd format only with [Gregorian](https://en.wikipedia.org/wiki/Gregorian_calendar) dates from 1583 onward
All-numeric yyyy-mm-dd dates might be assumed to follow the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) standard, which mandates the Gregorian calendar.

**Comment by anowacki** [comment]
I certainly would prefer `""` to throw an error, even though it was me that wrote the documentation.  I can't think of any circumstances in which `""` should correctly parse in reality, and I think the current behaviour is really just a side-effect of the way in which the parsing is implemented, rather than being intended.

That said, I think Julia should be strict about honouring SemVer so I'm uneasy about calling this a bug and changing the default behaviour.  Perhaps running PkgEval on a PR for this, and seeing if anything has tests which check for this behaviour, would help?  Given this is a parsing issue, I suspect tests will not necessarily catch all the cases where this crops up, even though I also suspect most things which 'work' with the current 'feature' are actually themselves bugs!

**Comment by oscardssmith** [comment]
I've added a triage tag. To me it seem reasonable that we should match incomplete non-empty dates, but throw on empty dates. I fairly strongly doubt that anyone actually wanted the current behavior.

**Comment by anowacki** [comment]
I have submitted #47117, which makes parsing empty strings throw an error.  I thought it may be useful to help decide whether to go ahead with the change in a minor version bump.

**Comment by JeffBezanson** [comment]
Triage agrees empty string should be an error. Dropping the partial format parsing might also be good, but that's a separate issue.
