### ISSUE TITLE
Precompilation-related segfault

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaLang/julia#43926]
`]dev DFTK`
Add this to the end of src/DFTK.jl:
```
# very simple example to exercise precompilation
begin
    using DFTK
    a = 10.26  # Silicon lattice constant in Bohr
    lattice = a / 2 * [[0 1 1.];
                       [1 0 1.];
                       [1 1 0.]]
    Si = ElementPsp(:Si, psp=load_psp("hgh/lda/Si-q4"))
    atoms = [Si => [ones(3)/8, -ones(3)/8]]
    
    model = model_atomic(lattice, atoms)
    basis = PlaneWaveBasis(model; Ecut=5, kgrid=[1, 1, 1])
    
    scfres = self_consistent_field(basis, tol=1e-0, callback=info -> nothing)
end
```
precompile, then run examples/silicon.jl. I get a segfault related to deserialization. This is on 1.7 as well as on nightly. The segfault goes away if I put the above snippet inside the DFTK module instead of at the end of the file.

**Comment by PallHaraldsson** [comment]
I could use you package as is, but I couldn't "dev" it, and anyway I think you're going about things the wrong way, so possibly this issue should be closed.

```
julia> @time using DFTK
 13.740627 seconds (23.32 M allocations: 1.526 GiB, 3.38% gc time, 49.96% compilation time)
```

You can look into:
https://timholy.github.io/SnoopCompile.jl/stable/

What I tend to do is run as (maybe it's old-fashioned advice, or you don't need it as tools do for you indirectly):
```
$ ~/julia-1.7.0/bin/julia --trace-compile=stderr

it's understandable you wouldn't know of it since it's documented with:
$ ~/julia-1.7.0/bin/julia --help-hidden
```

Your code above takes a lot of time, but did work, after `using DFTK` and with the above you see lots of precompiles, and that's the code I tend to try to add to the main source file (or some of it, usually not all work).

I never add `using <package_itself>` to the file, very possibly it's the reason for the segfault. It doesn't seem to belong there, you're trying to use the package you're in the middle of precompiling.

For some reason I get (and not sure how to resolve):
```
(@v1.7) pkg> dev DFTK

   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Libxc [66e17ffc]:
 Libxc [66e17ffc] log:
 ├─possible versions are: 0.1.0-0.3.6 or uninstalled
 └─restricted to versions 0.3.8-0.3 by DFTK [acf6eb54] — no versions left
   └─DFTK [acf6eb54] log:
     ├─possible versions are: 0.4.4 or uninstalled
     └─DFTK [acf6eb54] is fixed to version 0.4.4
```

**Comment by PallHaraldsson** [comment]
I can replicate the segfault (now that I could "dev") even with:
```
$ ~/julia-1.7.0/bin/julia --check-bounds=yes
```

But as I explained in the previous comment, I think you're doing something wrong/unreasonable. With the right way you likely do not get a segfault. Still, it may not be reasonable for people to know this is unreasonable code (an exception to the rule, Julia should never segfault?), so possibly the segfault could and should be fixed. Then hopefully with a more helpful replacement error message. I let the Julia devs consider this, so don't close the issue prematurely.

┌ Warning: Package Base does not have DFTK in its dependencies:
│ - If you have Base checked out for development and have
│   added DFTK as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Base
└ Loading DFTK into Base from project dependency, future warnings for Base are suppressed.

signal (11): Segmentation fault
in expression starting at REPL[5]:1
[..]
```

**Comment by antoine-levitt** [comment]
> I never add using <package_itself> to the file, very possibly it's the reason for the segfault. It doesn't seem to belong there, you're trying to use the package you're in the middle of precompiling.

That's possible, but I can't remove it or I won't be able to use the module. Apparently the right solution is to put the code inside the module, so I'll do that; still, julia probably shouldn't segfault. Sorry about the libxc issue, did you Pkg.update()? Otherwise it's possible we bumped the requirements too soon, it should be fixed soon.

**Comment by ViralBShah** [comment]
Please reopen if still an issue.

**Comment by antoine-levitt** [comment]
Looks like it's fixed, yes, I now get `ERROR: LoadError: ArgumentError: Package Base does not have DFTK in its dependencies:`, which I'm not sure I understand, but at least it doesn't segfault anymore.
