### ISSUE TITLE
Pair destructuring

### ISSUE THREAD

**Issue by tecosaur** [JuliaLang/julia#44392]
Currently, Julia has pretty good support for `Tuple` restructuring: in function arguments, and assignments.

```julia
f((a, b), c) = a*b + c

h = (1, 2)
(a, b) = h
```

It would be quite nice if `Pair`s could be similarly destructured, i.e.
```julia
f(a => b, c) = a*b + c

h = 1 => 2
a => b = h
```

I find the benefit particularly apparent in function calls. For example, should one want to create an inverse function to `countmap` (from `StatsBase`):
```julia
mapcount(counts::Dict{<:Any, Int}) =
  Iterators.flatten(counts |> collect .|> (val => freq) -> repeat([val], freq)) |> collect
```

Instead, one currently has to use the following syntax:
```julia
mapcount(counts::Dict{<:Any, Int}) =
  Iterators.flatten(counts |> collect .|> valfreq -> repeat([first(valfreq)], last(valfreq))) |> collect
```

I consider `valfreq -> repeat([first(valfreq)], last(valfreq)))` materially worse than `(val => freq) -> repeat([val], freq)`. It's simply less clear.

Beyond the convenience of this, since Pairs are essentially syntax sugar over 2-tuples and tuple destructuring already works, I think this makes a lot of sense in that respect also.

**Comment by fredrikekre** [comment]
```
julia> h = 1 => 2;

julia> f((a, b), c) = a * b + c;

julia> f(h, 3)
5

julia> a, b = h;

julia> a
1

julia> b
2
```

**Comment by tecosaur** [comment]
Well, that's interesting, I wouldn't have guessed to try that. Are pairs lowered to tuples at some point or something?

**Comment by jakobnissen** [comment]
Regular destructuring works by calling `iterate`, and pairs are iterable.

**Comment by tecosaur** [comment]
I see, thanks for the explanation.

**Comment by timholy** [comment]
Can this be closed or is there more to do?

**Comment by tecosaur** [comment]
If this is possible with minor effort, I'd still like to advocate for this as a "nice to have".

If this is a more major undertaking, tuple destructuring works and I'd just close the issue.

**Comment by fredrikekre** [comment]
Doesn't seem to add something you can't already do, or?

**Comment by tecosaur** [comment]
The one thing which comes to mind that isn't possible with tuple destructuring is when you want to require a pair, and only a pair, to be passed. E.g. with a function like `replace`.

Other than that, I'd say it's a matter of discoverability. I knew that tuple destructuring worked, and I thought to try pair destructuring, but not to try tuple destructuring a pair. I feel like I wouldn't be the only one.

**Comment by fredrikekre** [comment]
> The one thing which comes to mind that isn't possible with tuple destructuring is when you want to require a pair, and only a pair, to be passed.

That's what you use type restrictions for:
```julia
julia> f((a, b)::Pair) = a * b;

julia> f(2 => 3)
6

julia> f((2,3))
ERROR: MethodError: no method matching f(::Tuple{Int64, Int64})
Closest candidates are:
  f(::Pair) at REPL[2]:1
```

Note that tuple-destructuring is not pattern-matching on tuples -- it works with any iterable.

**Comment by tecosaur** [comment]
Another thing I wasn't aware of. Thanks for that.

In that case, the only remaining argument for this is discoverability.

**Comment by fredrikekre** [comment]
It should be clarified in the manual then with some exampels. I believe there is a section about destructuring (and perhaps it should be called "destructuring" or "argument destructuring" instead of "tuple destructuring" (if that isn't already the case)).

**Comment by tecosaur** [comment]
I think an example of argument destructuring a non-tuple, and argument destructuring with a type restriction would be good additions.

**Comment by tecosaur** [comment]
Oh, a little tangent from your type restriction comment (not worth creating a new issue for I think): Would it be syntactically possible/sensible for `(a::Int, b::String)` to be equivalent to `(a, b)::Tuple{Int, String}`?

**Comment by JeffBezanson** [comment]
I don't think I would want `f((a, b))` and `f(a => b)` to be synonyms; that would just be kind of spurious. But we could make `f(a => b)` mean `f((a, b)::(=>))`. The main question is how useful is it to require an argument to be a Pair?

> Would it be syntactically possible/sensible for `(a::Int, b::String)` to be equivalent to `(a, b)::Tuple{Int, String}`?

That could be implemented, but the problem is that `(a, b)` currently matches any argument so it's a bit surprising for `(a::Int, b)` to also imply the whole thing has to be a tuple.

**Comment by danielwe** [comment]
+1 for type declarations inside argument destructuring. I don't think it should imply that the iterable must be a tuple, though. Argument destructuring appears to me to be equivalent to splatting, so I'd expect the same behavior in the following two cases:

```julia
f(x::Foo, x) = [...]
f(iterable...)

g((x::Foo, y)) = [...]
g(iterable)
```

Maybe this deserves a separate issue after all?

**Comment by tecosaur** [comment]
Hmm, maybe I should make an issue for types within the destructuring. It also seems syntactically nice in combination with pair destructuring, should that be enabled — e.g. `f(a::Int => b::String)`.

**Comment by simeonschaub** [comment]
> I'd expect the same behavior in the following two cases:
> 
> ```julia
> f(x::Foo, y) = [...]
> f(iterable...)
> 
> g((x::Foo, y)) = [...]
> g(iterable)
> ```

That's already not the case with regular destructuring, since for example destructuring allows arbitrarily many trailing elements whereas dispatch will just throw an error. I also don't see any way we could actually allow dispatch on the type of the first element of an arbitrary collection without massive changes to our function call semantics, since in general that's not a static property of the collection type.

**Comment by danielwe** [comment]
I was going to explain how I envisioned dispatch inside destructuring would work in an unambiguous and non-breaking way (if at all interested, see slack thread https://julialang.slack.com/archives/C67910KEH/p1646772924251429?thread_ts=1646629190.350919&cid=C67910KEH).

Then I had a facepalm moment:

```julia
g(p) = f(p...)
```

Carry on, everyone

**Comment by simeonschaub** [comment]
I just don't think using `=>` for pair destructuring is consistent. `a => b` is just a regular call expression and we have the rule that call expression on the lhs of assignments define a new function. This is especially bad since we already allow `a => b = ...` outside of function arguments, where it is actually a function definition.

**Comment by danielwe** [comment]
> The main problem is that `f((a, b))` is different from `f((a::Any, b::Any))`, which is a bit odd but maybe not the end of the world.

My humble suggestion would be to instead update the docs around argument destructuring to include the suggestion that if you find yourself wanting to do

```
f((a::Foo,))
```

the solution is to use a function barrier

```
f((a,)) = _f(a::Foo)
```

This accomplishes the objective without syntax inconsistencies and surprises.

(I guess the pair destructuring case is different. If `f(a => b)` already maps to `f((a, b)::(=>))` (which I have no opinion about) then there's no harm or surprise in having `f(a::Int => b::String)` map to `f((a, b)::(=>){Int, String})` since the iterable type is already restricted.)

**Comment by JeffBezanson** [comment]
This doesn't seem particularly important to add.
