### ISSUE TITLE
tuple_tfunc bug handling of `Union` containing `Type{...}`

### ISSUE THREAD

**Issue by aviatesk** [JuliaLang/julia#44705]
I guess this issue should be raised before, but I couldn't find an issue that discusses this.
When working on #44512 (in particularity [this](https://github.com/JuliaLang/julia/pull/44512#issuecomment-1075345754) issue), I found the following `isa` check doesn't work as I expected:
```julia
julia> Type{Int} <: DataType
true

julia> Int isa Type{Int}
true

julia> (Int,) isa Tuple{DataType} # expected
true

julia> (Int,) isa Tuple{Type{Int}} # I expected this to return `true`
false
```

So in essence `Tuple`-type whose parameter contains `Type`-type doesn't seem to follow the covariant rule.

This issue leads to the `ERROR: fatal error in type inference (type bound)` error in #44512 when we try to union-split `Base.indexed_iterate(::Union{Tuple{Nothing, Nothing, Nothing}, Tuple{Any, Union{Type{AbstractContinuousSystem}, Type{AbstractDiscreteSystem}}, Any}}, ...)` callsite.

**Comment by vtjnash** [comment]
That is an odd looking signature type, since we should be unable to ever select that part of the union. There do not exist any values which satisfy isa `Tuple{Type{Int}}`, since Type{Int} is a subtype of DataType, which is the concrete type of this value. In particular, and for Tuples only, we can have subtypes of concrete types (but not concrete subtypes of concrete subtypes), which can lead to some confusion over the dispatch behavior if one is not careful about reflecting this fact in the algorithms.

**Comment by vtjnash** [comment]
incorrect:
```
julia> Core.Compiler.tuple_tfunc(Any[Union{Type{Int32}, Type{Int64}}])
Tuple{Union{Type{Int32}, Type{Int64}}}
```
correct:
```
julia> Core.Compiler.tmerge(Core.Compiler.tuple_tfunc(Any[Type{Int32}]), Core.Compiler.tuple_tfunc(Any[Type{Int64}]))
Tuple{DataType}
```
