### ISSUE TITLE
rpad throws DivideError when using zero-width padding

### ISSUE THREAD

**Issue by canders-rf** [JuliaLang/julia#45339]
After installing  julia version 1.7.2, I get a DivideError whenever I attempt to use rpad with an escaped character.  This error does not happen in julia 1.6.6

This function call should pad the string "foo" with null chars
```rpad("foo", 16, '\0')```

However, I get this error instead:
```
ERROR: DivideError: integer division error
Stacktrace:
 [1] div
   @ ./int.jl:284 [inlined]
 [2] divrem
   @ ./div.jl:162 [inlined]
 [3] divrem
   @ ./div.jl:158 [inlined]
 [4] rpad(s::String, n::Int64, p::Char)
   @ Base ./strings/util.jl:382
 [5] top-level scope
   @ REPL[31]:1
```

With Julia 1.6.6 the string is padded, as expected :
```"foo\0\0\0\0\0\0\0\0\0\0\0\0\0"```

**Comment by oscardssmith** [comment]
In Julia 1.7, `rpad` function was changed to use `textwidth` rather than a raw character (codepoint) count.

**Comment by canders-rf** [comment]
Can you explain how throwing a DivideError is the result of this change?  I Julia really goin

**Comment by oscardssmith** [comment]
are you trying to pad to a specific number of bytes or a specific number of codepoints?

**Comment by oscardssmith** [comment]
the reason it has a divide by zero error is that a null byte has zero width, so when it tried to figure out how many null bytes to add, it divides by zero

**Comment by StefanKarpinski** [comment]
There's three possible things that this can do:

1. Pad by bytes
2. Pad by characters
3. Pad by text width

I believe we used to do 2, we switched to 3 because that's what you actually want when you're using `rpad` or `lpad` for text alignment. This usage actually wants 1, which we never did, but which happens to work because `"foo"` is ASCII and `\0` is a single-byte character. We can try out Julia 1.6 and see how even the old behavior was potentially wrong if you want to pad to 16 bytes:
```jl
# julia 1.6

julia> rpad("foo", 16, '\0')
"foo\0\0\0\0\0\0\0\0\0\0\0\0\0"

julia> ncodeunits(ans)
16

julia> rpad("𝔣𝔬𝔬", 16, '\0')
"𝔣𝔬𝔬\0\0\0\0\0\0\0\0\0\0\0\0\0"

julia> ncodeunits(ans)
25
```
An option would be to introduce keywords for the padding count: `bytes` for bytes, `chars` for characters, `width` for text width. The old API which doesn't specify could do something automagic as previously proposed by @stevengj: https://github.com/JuliaLang/julia/pull/41133. However, that automagic behavior there switches to character-based padding, which is also not really correct in this usage or the usage in Tar.jl, which was also padding zero NUL bytes.

**Comment by canders-rf** [comment]
Thank you for this explanation.  I realize now that my use of rpad was off target from its intended use - for text alignment.  The text width change makes sense to me.  I was using rpad to send a small ascii text string across a network to a service that expected a null terminated string.  I'll change my code to use a byte array.

**Comment by stevengj** [comment]
Maybe we should:

1. Implement something like `rpad(a::AbstractVector, n::Integer, p)` method to pad arbitrary 1d arrays, which is a generically useful operation analogous to `fill`.
2. When calling `rpad(s::String, n, p)` with `p='\0'`, throw an error suggesting calling `rpad(codeunits(s), n), 0x00)` instead (instead of `DivideError`).

**Comment by stevengj** [comment]
Note that this is slightly breaking, because for some reason our current `lpad(s,n)` and `rpad(s,n)` arguments accept *any* argument `s` and convert it to `string(s)`:
```jl
julia> rpad([1,3,4], 20, 'x')
"[1, 3, 4]xxxxxxxxxxx"
```
However, this seems like a misfeature which is unlikely to break real code — I'm in favor of removing that method regardless.

**Comment by stevengj** [comment]
Interestingly enough, digging through the history of this function, it seems that it *originally* used a character count, then @StefanKarpinski changed it to use `textwidth` in https://github.com/JuliaLang/julia/commit/8be4acc0190ead6b512253460f3e6b17f1e3d796, then @StefanKarpinski changed it *back* to use a character count in https://github.com/JuliaLang/julia/pull/25069, then it was changed *back* to use `textwidth` in https://github.com/JuliaLang/julia/pull/39044.

The `lpad(string(s), n)` method was added by @StefanKarpinski in 2010: https://github.com/JuliaLang/julia/commit/b7faaf9628e939c6e75365918dfb6130ebf5d9ed

**Comment by stevengj** [comment]
Alternatively, we can go with a version of my original suggestion and pad by bytes if `p` is a zero-width ASCII character (or maybe just if `p == '\0'`).

**Comment by david-macmahon** [comment]
Padding with any character `c` for which `textwidth(c) == 0` will lead to the `DivideError`.  Interestingly, this includes the tab character `'\t'`, which is not a great choice for a padding character generally speaking, but certainly has non-zero width much of the time.

I like the idea of falling back to padding by bytes if the `textwidth` of the given padding character is 0.

If that's not acceptable then It would be nice if the exception were a little more helpful (i.e. not a `DivideError`).  Something along the lines of `ArgumentError("cannot pad using a character with zero textwidth")` would be much more helpful/informative IMHO.

**Comment by johnomotani** [comment]
Strongly agree with @david-macmahon - I just ran into this and found the error very unhelpful.

**Comment by stevengj** [comment]
In the short term, we could throw a more informative error message, e.g. suggesting `str * padchar^max(0, pad - ncodeunits(str))` if you want to pad by code-units/bytes.
