### ISSUE TITLE
Changing eltype of Array and safety

### ISSUE THREAD

**Issue by Wimmerer** [JuliaLang/julia#45684]
@Moelf has this interesting bit of code I'd like to use: https://github.com/JuliaHEP/UnROOT.jl/pull/147/files#diff-8f77b10faceb9973209e8273433768762ea7801479889abdcc355be1491872ebR27

I'd like to convert some `Vector{UInt8}`s to the desired data types directly, without a `ReinterpretArray` wrapper. I should be (within reason, a user could reference it if they forced the issue of course) the sole owner of the original `Vector{UInt8}` and it won't outlive the scope of the conversion (it may be long-lived _before_ conversion).

My questions are:
1. Is this safe within reason? 
2. Can `jl_reshape_array` be modified to allow this explicitly?  There's an assert right now that prevents this AFAICT. Or can a similar function which directly modifies the type tag for the vector be created? 

I'm sure that's there for a very good reason this is currently banned, however this would be quite valuable for me. I believe Jameson had very significant reservations about it.

**Comment by Keno** [comment]
There is no way for the user to write this safely, because the compiler would be allowed to retain references and make assumptions (even if you don't think that'll happen, imagine running the code in a debugger). However, the compiler is allowed to make this transformation if it can prove that it is safe to do by eliding a semantic copy. The immutable arrays code has some initial support for things like this for turning mutable arrays immutable and back, but it's non-trivial to do.
