### ISSUE TITLE
Wrong UNIXEPOCH

### ISSUE THREAD

**Issue by vjache** [JuliaLang/julia#45868]
`julia> Dates.epochms2datetime(Dates.UNIXEPOCH)
1969-01-01T00:00:00

julia> VERSION
v"1.7.3"
`

**Comment by quinnj** [comment]
It can be helpful for maintainers when you open an issue to be as descriptive as possible: what are you looking for? What isn't seeming to work as you expected? What were the steps you took in the process that led you to believe something is wrong?

In this case, we can try to guess what is happening, but I'll try to just explain some of the things you shared. `Dates.UNIXEPOCH` is not really meant as a user-facing value; it's an internal value that is equivalent to `Dates.value(DateTime(1970))`, which corresponds to the [rata die](https://en.wikipedia.org/wiki/Rata_Die) milliseconds of the unix epoch of 1970-01-01:00:00:00. It's used when converting to/from unix timestamps via `Dates.unix2datetime` and `Dates.datetime2unix`.

`Dates.epochms2datetime` has docs that read `Take the number of milliseconds since the rounding epoch (0000-01-01T00:00:00) and return the corresponding DateTime.`, which might make one think: "oh, so it takes # of rata die milliseconds and converts to DateTime", but not quite! The different here is is that rata die milliseconds basis is:
```julia
julia> Dates.DateTime(0, 12, 31)
0000-12-31T00:00:00
julia> Dates.value(ans)
0
```
whereas the the epochs used for date rounding are based ISO 8601's "year zero" notation, which is:
```julia
julia> Dates.DateTime(0)
0000-01-01T00:00:00
julia> Dates.value(ans)
-31536000000
```
So you can see the difference is almost a year.

Hope that helps!
