### ISSUE TITLE
`UndefVarError: .+ not defined` on `@code_lowered 1 .+ 1`

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#45889]
```julia
julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = vscode

julia> @code_lowered sin.(3)
CodeInfo(
1 ─ %1 = Base.broadcasted(Main.sin, x1)
│   %2 = Base.materialize(%1)
└──      return %2
)

julia> @code_lowered 1 .+ 1
ERROR: UndefVarError: .+ not defined
Stacktrace:
 [1] top-level scope
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/InteractiveUtils/src/macros.jl:230
```

It also happens on Julia v1.6

By the way, 

```julia
julia> @macroexpand (@code_lowered 1 .+ 1)
quote
    #= /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/InteractiveUtils/src/macros.jl:230 =#
    local var"#30#results" = InteractiveUtils.code_lowered(.+, (Base.typesof)(1, 1))
    #= /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/InteractiveUtils/src/macros.jl:231 =#
    if InteractiveUtils.length(var"#30#results") == 1
        var"#30#results"[1]
    else
        var"#30#results"
    end
end
```

I don't understand how the error arises. `InteractiveUtils.code_lowered(.+, (Base.typesof)(1, 1))` evaluates correctly in the scope of the macro invocation.

**Comment by Liozou** [comment]
Sorry about that, it was overlooked in #35522 because the issue only occurs when using a dot symbol on arguments that are not lowered to `Expr`, which I did not think of. Fix is up at #45894.

The reason why the error arises while the explicit call works is that, in the macro, `.+` is lowered to a symbol, _i.e._ `Symbol(".+")` while in the explicit call you tried, it is transformed into `Expr(:., :+)`. You can see it by comparing `dump(@macroexpand @code_warntype 1 .+ 3)` to `dump(:(InteractiveUtils.code_warntype(.+, (Base.typesof)(1, 3))))`.
