### ISSUE TITLE
shell mode in repl can't ls windows files from wsl

### ISSUE THREAD

**Issue by hros** [JuliaLang/julia#46154]
Julia version 1.7.3
running in WSL (Ubuntu 22.04) in Windows 11
in shell mode in the repl (press `;`) can ls a windows directory which is automatically mounted from wsl
however can't ls a pattern, e.g. `ls *txt` , returns the error:
```julia
shell> ls *txt
ls: cannot access '*txt': No such file or directory
```

the same ls command works from the shell (not running in Julia)

**Comment by giordano** [comment]
That's expected: the shell mode doesn't do [globbing](https://en.wikipedia.org/wiki/Glob_(programming)), which is a feature of the external shell, and the shell mode purposefully doesn't rely on them, because they aren't portable.  You may want to look at [`Glob.jl`](https://github.com/vtjnash/Glob.jl) instead.
