### ISSUE TITLE
Anonymous functions in the REPL force repeated compilation

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#46232]
```julia
julia> m = [1;;]
1×1 Matrix{Int64}:
 1

julia> @time sortslices(m; dims=2, by=x->x[1]);
  0.288263 seconds (439.98 k allocations: 23.219 MiB, 99.47% compilation time)

julia> @time sortslices(m; dims=2, by=x->x[1]);
  0.276815 seconds (439.98 k allocations: 23.218 MiB, 99.55% compilation time)

julia> @time sortslices(m; dims=2, by=x->x[1]);
  0.296135 seconds (439.98 k allocations: 23.218 MiB, 5.68% gc time, 98.84% compilation time)

julia> @time sortslices(m; dims=2, by=x->x[1]);
  0.265986 seconds (439.99 k allocations: 23.241 MiB, 98.17% compilation time)
```
This is because `x->x[1]` is a different function each time.

**Comment by Seelengrab** [comment]
I think that's expected, you're defining a new anonymous function with each `@time` after all. You're not saving the anonymous function in a variable and reusing it.

**Comment by LilithHafner** [comment]
I agree. I view this as expected and unfortunate (.3 seconds is noticeably laggy for what should be a simple function). I don't see a great solution, but changes to specialization or compilation heuristics could fix this.

**Comment by Moelf** [comment]
it is not guaranteed that these anonymous functions are identical, because they technically have names:
```julia
julia> X = x->x[1]
#1 (generic function with 1 method)

julia> X(12)
12

julia> (::var"#1#2")(x) = 3;
WARNING: Method definition #1(Any) in module Main at REPL[1]:1 overwritten at REPL[3]:1.

julia> X(12)
3
```

**Comment by KristofferC** [comment]
You get one compile function per function you "type" so this is indeed expected.

**Comment by Seelengrab** [comment]
> it is not guaranteed that these anonymous functions are identical because they technically have names

To clarify, in terms of behavior they are `==`, but the functions themselves are not `===`. This is not something that can be fixed by method specialization, as each new function has its own new type. What you're asking for is more or less making two different pieces of code that both read `x -> x[1]` to be lowered to the exact same function (which may get tricky with captured variables..).

**Comment by LilithHafner** [comment]
What I'm asking for is for that command to run faster the second time.

Compiling a `::Function` method for REPL defined anonymous functions would allow the method to be reused but come with unfortunate runtime costs. I don't have a great solution.

**Comment by simeonschaub** [comment]
Anonymous functions still contain `LineNumberNode`s that are different for each REPL cell:

```
julia> Meta.@dump f(x->x)
Expr
  head: Symbol call
  args: Array{Any}((2,))
    1: Symbol f
    2: Expr
      head: Symbol ->
      args: Array{Any}((2,))
        1: Symbol x
        2: Expr
          head: Symbol block
          args: Array{Any}((2,))
            1: LineNumberNode
              line: Int64 1
              file: Symbol REPL[1]
            2: Symbol x
```

So if we were to reuse previous compilation results we would get wrong stacktraces

**Comment by rafaqz** [comment]
I'm hitting this overhead to for functions with high compilation cost it that you use a lot in the REPL. 

When an anonymous function is in vscode even the LineNumberNode should be the same. But swapping out the line numbers of an identical anonymous function should be possible anyway?

I was imagining in that case we could swap out all the gensyms to the new function where that is cached. Maybe that's hard. But it would be a major responsiveness improvement in the REPL.

Otherwise we should start advising against using anonymous functions in interactive code in favour of e.g. Fix2s.
