### ISSUE TITLE
Permission denied when loading Makie in macOS 

### ISSUE THREAD

**Issue by michaelschwob** [JuliaLang/julia#46254]
Was directed to post here from Makie's GitHub page:

I installed Makie, GLMakie, and CairoMakie. When I have using Makie, CairoMakie, I get the following error: ERROR: LoadError: InitError: IOError: stat("/Users/schwob/.config/makie/theme.jl"): permission denied (EACCES) Stacktrace: [1] uv_error @ ./libuv.jl:97 [inlined] [2] stat(path::String) @ Base.Filesystem ./stat.jl:152 [3] isfile @ ./stat.jl:456 [inlined] [4] __init__() @ Makie ~/.julia/packages/Makie/Ppzqh/src/Makie.jl:302 [5] _include_from_serialized(path::String, depmods::Vector{Any}) @ Base ./loading.jl:768 [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String) @ Base ./loading.jl:854 [7] _require(pkg::Base.PkgId) @ Base ./loading.jl:1097 [8] require(uuidkey::Base.PkgId) @ Base ./loading.jl:1013 [9] require(into::Module, mod::Symbol) @ Base ./loading.jl:997 during initialization of module Makie in expression starting at /Users/schwob/Desktop/GitHub/folder/file.jl:10

I thought I gave Julia complete permission to my full disk, but I am still getting this error. Thank you.

**Comment by mgkuhn** [comment]
What does the command
```
$ ls -l /Users/schwob/.config/makie/theme.jl
```
output?

**Comment by michaelschwob** [comment]
Here's my output: `ls: /Users/schwob/.config/makie/theme.jl: Permission denied`

**Comment by mgkuhn** [comment]
And check the entire path with
```
$ ls -ld / /Users /Users/schwob /Users/schwob/.config /Users/schwob/.config/makie
```

**Comment by michaelschwob** [comment]
Corresponding output:
```
ls: /Users/schwob/.config/makie: Permission denied
drwxr-xr-x  20 root    wheel  640 Jul 14 03:48 /
drwxr-xr-x   5 root    admin  160 Jul 14 03:48 /Users
drwxr-x---+ 28 schwob  staff  896 Aug  4 16:36 /Users/schwob
drwx------   3 root    staff   96 Aug  3 19:22 /Users/schwob/.config
```

**Comment by mgkuhn** [comment]
> `drwx------   3 root    staff   96 Aug  3 19:22 /Users/schwob/.config`

It appears that you accidentally ran whatever program first created the folder `/Users/schwob/.config` as the superuser `root`, and not as your normal user `schwob`. Since then no other program running as user `schwob` had any ability to create a file in there, or even test for the presence of files in there because that folder ended up not belonging to you.

Solution: change the ownership of that folder and its contents, e.g. with
```
$ sudo chown -R schwob /Users/schwob/.config
```

This is not a Julia issue. Julia should normally never be run as `root`. Julia may not even have been the first program trying to access `/Users/schwob/.config`. This is just a problem in your particular home directory on that machine.

Generally, all files and folders under `/Users/schwob` should be owned by user `schob`. You may want to check if there are other things in there besides `/Users/schwob/.config` that you don't actually own, e.g. with
```
$ find ~ -user root -print
```
and then `chown` them as well.
