### ISSUE TITLE
ubuntu deployment of up to date version

### ISSUE THREAD

**Issue by eoli3n** [JuliaLang/julia#46529]
I need to automate deployment of julia for 800 hosts for a University.
On latest Ubuntu LTS, when I ``apt install julia`` it tells me to ``snap install julia``.

On snapcraft, julia package seems to be official but it is in a 2019 version : 1.0.4
https://snapcraft.io/julia

That's strange because the package is marked as official, so why isn't it up to date ?
From the website : Current stable release: v1.8.0 (August 17, 2022)

**Comment by DilumAluthge** [comment]
This is probably better suited for Discourse: https://discourse.julialang.org/

**Comment by eoli3n** [comment]
Created the same post on discourse, waiting for mod approval

**Comment by KristofferC** [comment]
Closing this here since we don't really have any control over how distros package julia.

However, instead of using `apt install` you can also just download the tarball from the Julia download page https://julialang.org/downloads/. All you need to do is extract it somewhere and make sure that `bin/julia` is available on the `PATH` of the user.

**Comment by eoli3n** [comment]
> Closing this here since we don't really have any control over how distros package julia.
> 
> However, instead of using `apt install` you can also just download the tarball from the Julia download page https://julialang.org/downloads/. All you need to do is extract it somewhere and make sure that `bin/julia` is available on the `PATH` of the user.

> I need to automate deployment of julia for 800 hosts for a University.

**Comment by KristofferC** [comment]
> Another thing, is that if the package is marked as official, it means that this is julialang members, which packaged it as snap.

Okay, I think https://github.com/JuliaCI/julia-snap is where the changes has to be made then?

> Deployment and upgrades

Perhaps look at juliaup. I understand that `apt` is convenient, the reason why I am mentioning alternatives is that distros tend to be both slow with providing new Julia releases, and they many times release bugged versions because they e.g. do not use our patched version of LLVM.

**Comment by eoli3n** [comment]
@KristofferC 

> Perhaps look at juliaup. 

I will take a look

> distros tend to be both slow with providing new Julia releases

I deployed 0.6 for a really long time, easiest way is the best to me
