### ISSUE TITLE
Julia 1.8.1 pdf docs link broken

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#46704]
https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.8.1.pdf is broken.

**Comment by ViralBShah** [comment]
Presumably this is the failing build: https://github.com/JuliaLang/docs.julialang.org/runs/8288418072?check_suite_focus=true#step:6:558

**Comment by DilumAluthge** [comment]
There are several different things going on.

The first issue is that the PDF docs build is broken, and has been for a little while. We don't know which Julia commit broke the build.

The second issue is that we don't currently build the PDF docs as part of normal CI, which is why these breakages happen without us noticing. The fix for this issue is to build the PDF docs on every PR and every commit to master: https://github.com/JuliaCI/julia-buildkite/issues/198

**Comment by mortenpi** [comment]
It's there now, fixed by https://github.com/JuliaLang/docs.julialang.org/commit/16a515e71f2ea6bb2b18a68eb510ab453db35f32
