### ISSUE TITLE
CI: No rr trace upload on failure to exit

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#46859]
E.g. in https://buildkite.com/julialang/julia-master/builds/16038#0183612c-70a0-4364-85ef-5f8fadca4f35

**Comment by DilumAluthge** [comment]
The situation here is that the parent process is the Julia process running the https://github.com/JuliaCI/julia-buildkite/blob/main/utilities/timeout.jl script, and the child process is the Julia processing running the https://github.com/JuliaCI/julia-buildkite/blob/dpa/print-after-killing/utilities/rr/rr_capture.jl script. The child (`rr_capture.jl`) has exceeded the timeout (5 hours), so the parent (`timeout.jl`) sends SIGTERM (15) to the child.

I think that this is the problem here: when the parent (`timeout.jl`) sends SIGTERM to the child (`rr_capture.jl`), instead of the child (`rr_capture.jl`) dying, what we want to do is to "forward" that SIGTERM to the `rr` process. The `rr` process is the child of `rr_capture.jl` and thus is the grandchild of `timeout.jl `

@staticfloat Do I have this all correct? If so, how do we get `rr_capture.jl` to "forward" the SIGTERM to the `rr` process?





@staticfloat This is the issue where we hypothesized that the wrong process was being killed, right? I.e. the timer has run out, so our script tries to kill the rr process, but for some reason, instead of killing the rr process, the parent Julia process dies instead.

But looking at the PIDs:



The parent process is the Julia process running https://github.com/JuliaCI/julia-buildkite/blob/main/utilities/timeout.jl, and the child proc

**Comment by vtjnash** [comment]
Can we do a pgid kill instead? (with the negative pid range or killpg, controlled by setsid, aka `detached`, during process spawn)

**Comment by DilumAluthge** [comment]
Another log BTW: https://buildkite.com/julialang/julia-master-scheduled/builds/88#01836671-8f1c-44e3-8157-49220c9a6aba

**Comment by DilumAluthge** [comment]
> Can we do a pgid kill instead? (with the negative pid range or killpg, controlled by setsid, aka `detached`, during process spawn)

Which process should be detached? Should timeout.jl do `detach` when it spawns the rr_capture.jl process? Or should rr_capture.jl do `detach` when it spawns the rr process?

**Comment by DilumAluthge** [comment]
@staticfloat I think this first started happening after timeout.jl and rr_capture.jl were split into two files during a refactoring.

Before the refactoring, Buildkite ran rr_capture.jl which spawned the rr process.

After the refactoring, Buildkite runs timeout.jl which spawns rr_capture.jl which spawns the rr process.

**Comment by staticfloat** [comment]
Yeah, I think actually we don't want to invoke `timeout.jl` on `rr_capture.jl`, but instead use the functions defined within it inside of `rr_capture.jl`.

**Comment by staticfloat** [comment]
Ah, we're using `timeout.jl` twice.  :)

**Comment by staticfloat** [comment]
https://github.com/JuliaCI/julia-buildkite/pull/204

**Comment by DilumAluthge** [comment]
I'm going to close this as fixed by https://github.com/JuliaCI/julia-buildkite/pull/204, but if you see this happen again, please re-open the issue.
