### ISSUE TITLE
Julia Snap Package Error: `GLIBC_ABI_DT_RELR' not found

### ISSUE THREAD

**Issue by eldaragalarov** [JuliaLang/julia#46886]
Cannot add additional packages using Julia 1.8.1 that was installed as a snap package from snapcraft.io:

```
using Pkg
Pkg.add("Plots")
```

Outputs following error:
```
Failed to precompile Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80] to /home/eldar/.julia/compiled/v1.8/Plots/jl_jQD2Fj.
ERROR: LoadError: InitError: could not load library "/home/eldar/.julia/artifacts/b069ad81d556658ea64a543367e128e535fab269/lib/libgio-2.0.so"
/snap/core18/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /lib/x86_64-linux-gnu/libresolv.so.2)
```

Julia v1.8.1
Ubuntu 22.10

**Comment by giordano** [comment]
My hunch is that this issue is totally unrelated to Julia and what's happening is that you're somehow mixing up libraries from different versions of glibc, some coming from your system (path starting with `/lib/x86_64-linux-gnu`) and others coming from snap (path starting with `/snap/core18/current/lib/x86_64-linux-gnu`).  I have no clue how this came about because I'm not familiar with snap, but there is likely nothing we can do about that here.

**Comment by pabloferz** [comment]
There was actually a way to fix this. It should be solved now (you should update or reinstall the snap to get the fix).

**Comment by eldaragalarov** [comment]
@giordano This bug was related to Snap packaging, not with glibc library mixing.
@pabloferz Now all working al expected. Thank you for your fix!

**Comment by giordano** [comment]
> This bug was related to Snap packaging, not with glibc library mixing.

The snap package (which is not maintained here) ***was*** mixing up different glibc libraries.  Which was fixed by Pablo by not making the Snap package not mess with RPATHs
