### ISSUE TITLE
`Iterators.partition(1:0, 0)` errors

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaLang/julia#46972]
For parallelizing an operation on an array of size N, I use
```
chunk_length = cld(N, Threads.nthreads())
@sync for (ichunk, chunk) in enumerate(Iterators.partition(1:N, chunk_length))
```
(suggested by @tkf sometime ago).
This errors when N==0, which results in extra code to handle the special case. It would be convenient if `Iterators.partition(1:0, 0)` just returned an empty iterator.

**Comment by jakobnissen** [comment]
What if the iterator it partitions is not empty (or doesn't have a known length?) Wouldn't it be highly bug-prone in this case to return an empty iterator?

Suppose a user has an iterator `itr` with an unknown length. They then use `Iterators.partition(itr, n)`, and it's empty. How can they tell if that's because `itr` had zero elements, or if `n` was zero? It seems much easier to just check if `n` is zero.
That is, it may be convenient in your case, but it enables bugs that are way way harder to track down and handle, compared to a simple check against zero

**Comment by antoine-levitt** [comment]
I was thinking one could just check if the iterator length was zero and return an empty iterator in this case, but I didn't think about iterators with unknown length... Point also well-taken on div(x, 0). Looks like I'll just have to bite the bullet. Thanks!
