### ISSUE TITLE
Function for restricting array type

### ISSUE THREAD

**Issue by pddshk** [JuliaLang/julia#47236]
Assuming I have a vector of type `Vector{Any}` but it contains values of concrete type only. This is common practice when obtaining matrices from files and databases. So there should be a function that would try to promote types of all elements and then converts `Vector{Any}` to `Vector{T}` where `T` is calculated type.

Possible solution:

```julia
function restricttype(v::Vector{T1}) where T1
    T2 = mapreduce(typeof, promote_type, v)
    T1 == T2 ? v : convert.(T2, v)
end
```

**Comment by bramtayl** [comment]
`collect` should probably work for this. But I think the right answer is not to create the `Vector{Any}` anyway?

**Comment by andrewjradcliffe** [comment]
The general solution to instability arising from text files is to either inform the parser as to the type (if it can even be type stable), and/or use a function barrier which type-asserts about the eltype (and perhaps also the dimensionality).

From databases, most of the Julia interfaces should be able to confer type stability; you may need a function barrier if the database has bad set up (e.g. induces type instability via SQL NULL, or, just mixes data types for whatever nonsensical reason).

In both cases, just function barrier that mess and call it a day. Nothing that can be added to `Base` (or any package) can possibly anticipate all the weird, curious and plainly wrong ways that humans will mix data in text files, databases, etc...

A contrived example (we know the type that we intend to read in, so we could have passed `Int64` instead of `Any` to `readdlm`):
```julia
using DelimitedFiles
x = collect(reshape(1:15, 5, 3))
open("test.csv", "w") do io
    writedlm(io, x, ',')
end

function mybarrier(::Type{T}, io::AbstractString)::Matrix{T} where {T}
    # A = f(io) # do your here, e.g. below
    A = readdlm(io, ',', Any, '\n', header=false)
    convert(Matrix{T}, A)
end

@code_warntype mybarrier(Int64, "test.csv")
```

**Comment by Seelengrab** [comment]
`map(identity, v)` also works, while keeping the shape, at the cost of an allocation:

```
julia> x = Any[1 2;
               3.0 4.0]
2×2 Matrix{Any}:
 1    2
 3.0  4.0

julia> map(identity, x)
2×2 Matrix{Real}:
 1    2
 3.0  4.0
```

**Comment by KristofferC** [comment]
> map(identity, v) also works

Or `identity.(v)`.

**Comment by pddshk** [comment]
> A contrived example (we know the type that we intend to read in, so we could have passed `Int64` instead of `Any` to `readdlm`):
> ```julia
> using DelimitedFiles
> x = collect(reshape(1:15, 5, 3))
> open("test.csv", "w") do io
>     writedlm(io, x, ',')
> end
> 
> function mybarrier(::Type{T}, io::AbstractString)::Matrix{T} where {T}
>     # A = f(io) # do your here, e.g. below
>     A = readdlm(io, ',', Any, '\n', header=false)
>     convert(Matrix{T}, A)
> end
> 
> @code_warntype mybarrier(Int64, "test.csv")
> ```

Assume we have `Matrix{Any}` with type-stable columns. I need to convert it into series of strictly typed columns.

**Comment by Seelengrab** [comment]
> Assume we have Matrix{Any} with type-stable columns. I need to convert it into series of strictly typed columns.

A `Matrix`, by design, does not have different types per column, it's one uniform type. It sounds like you're looking for a [DataFrame](https://github.com/JuliaData/DataFrames.jl).

**Comment by pddshk** [comment]
Found better way to implement this

```julia
function restricttype(v::Vector{T1,N}) where {T1,N}
    T2 = mapreduce(typeof, (x,y) -> Union{x,y}, v)
     isconcretetype(T2) || @warn "restricttype deduced $T2 which is not concrete type"
     T1 == T2 ? v : convert(Array{T2,N}, v)
end
```

**Comment by Seelengrab** [comment]
Ok, then that sounds more like a feature request for `DataFrames` instead of core julia? Especially since we've already given existing solutions doing exactly that, without requiring a new function.

**Comment by pddshk** [comment]
> > It could be, but it also could be useful function in Base (arrays like those could arise when interact with other programs)
> 
> Sure, but again, arrays by their very nature do not have a distinct type for each column. They only have a single type for all elements of the array, which will in the general case have to fall back to `Any`. Arrays just aren't the right datatype for column-wise typed collections.

And this is why when you extract columns it's type is `Vector{Any}`, and you need `restricttype` function to automatically detect eltype and perform conversion!

**Comment by Seelengrab** [comment]
> And this is why when you extract columns it's type is Vector{Any}, and you need restricttype function to automatically detect eltype and perform conversion!

Yes, but if you want to have distinct `Vector`s for each column, you won't get around allocating them (and the container holding those arrays) either way. So something like

```
julia> x = Any[1 2.0;
               3 4.0]
2×2 Matrix{Any}:
 1  2.0
 3  4.0

julia> map.(identity, eachcol(x))
2-element Vector{Vector}:
 [1, 3]
 [2.0, 4.0]

julia> typeof.(ans)
2-element Vector{DataType}:
 Vector{Int64} (alias for Array{Int64, 1})
 Vector{Float64} (alias for Array{Float64, 1})
```

is already pretty much optimal, if a package doesn't provide a way to use a `DataFrame` as a datasink directly. I don't see the advantage of having a bespoke function :shrug:

**Comment by pddshk** [comment]
> ```julia
> julia> x = Any[1 2.0;
>                3 4.0]
> 2×2 Matrix{Any}:
>  1  2.0
>  3  4.0
> 
> julia> map.(identity, eachcol(x))
> 2-element Vector{Vector}:
>  [1, 3]
>  [2.0, 4.0]
> 
> julia> typeof.(ans)
> 2-element Vector{DataType}:
>  Vector{Int64} (alias for Array{Int64, 1})
>  Vector{Float64} (alias for Array{Float64, 1})
> ```

This solution is very non-obvious. Broadcast mapping identity function over columns sounds like doing nothing, why does this even work?

**Comment by bramtayl** [comment]
I think `collect.(eachcol(x))` is a bit clearer. Collect allocates a new vector and looks for the smallest available eltype for a collection (with some limitations for performance). `map` and `broadcast` both do something similar.

**Comment by mcabbott** [comment]
What's an example where that works? `x = Any[true 2f0; false 4f0]; map(collect, eachcol(x))` produces `Vector{Vector{Any}}`. 

Acting on an iterator is different, `collect(x for x in Any[true,2,3.0]) isa Vector{Real}`. Possibly `collect(Any[true,2,3.0])` ought to change to match that.

**Comment by Seelengrab** [comment]
> This solution is very non-obvious. Broadcast mapping identity function over columns sounds like doing nothing,

`map(identity vec)` or `identity.(vec)` is often recommended for tightening the element type of vectors - broadcasting the `map` over `eachcol` is a natural extension of that.

> why does this even work?

Since `map` and broadcasting have to handle arbitrary functions that can return arbitrary values, be type unstable and lots of other kinds of nastiness, they try to find the tightest element type they can already.

But again, having to do this in the first place sounds like a design/architectural issue of the library that just spit out a `Matrix{Any}` in the first place, without either giving an option to specify expected element types, using a `DataFrame` as a datasink or other solution to not give `Any`. I think it should be encouraged to be as strict as possible as soon as possible, instead of trying to refine types after the fact at runtime, which cannot (in general) lead to optimal performance (while probably also preventing static compilation further down the road).

**Comment by JeffBezanson** [comment]
I think we already have enough ways to do this that adding a function might be actively confusing. Plus, not every case wants the same type promotion rule. For example, if you have numbers, do you want to convert them all to Float64, or something else, or use an abstract element type like `Vector{Real}`? If the columns are homogeneous, a manual approach like this is straightforward enough:
```
julia> map(col->Vector{typeof(first(col))}(col), eachcol(x))
2-element Vector{Vector}:
 Bool[1, 0]
 Float32[2.0, 4.0]
```
