### ISSUE TITLE
ijl_svec: the function name may called `jl_svec`

### ISSUE THREAD

**Issue by awfeequdng** [JuliaLang/julia#47265]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/8253416/197093278-31da90fe-9fae-4ae0-a56c-3aad6129cc82.png">

The function in simplevector.c `JL_DLLEXPORT jl_svec_t *(ijl_svec)(size_t n, ...)` might be `JL_DLLEXPORT jl_svec_t *(jl_svec)(size_t n, ...)`

**Comment by awfeequdng** [comment]
When I compile the project using clang，the function `jl_svec` is not defined

**Comment by Keno** [comment]
The true symbol name is `ijl_svec`, same as for all the other internal functions. Usually these get renamed by preprocessor macro. I assume this is done this way, because `jl_svec` is already a preprocessor macro that does the extra argument checking, so that conflicts with the renaming. In either case, I don't think it's a bug. If there's a compilation error in a supported configuration, please file an issue with that error.

**Comment by vtjnash** [comment]
it works for me in a quick check that `jl_svec` is defined:
```
(gdb) p (jl_value_t*) jl_svec(2, jl_nothing, jl_nothing)
$2 = (jl_value_t *) 0x7fffee1a6bb0
(gdb) p jl_($2)
svec(nothing, nothing)
$3 = void
```
