### ISSUE TITLE
Julia Crash

### ISSUE THREAD

**Issue by rossati** [JuliaLang/julia#47281]
Hi
This issue is about a crash on Julia.
the attached file contains:
- crash.txt
- sandbox.jl
- formgen.jl
## versioninfo()
Julia Version 1.8.1
Commit afb6c60d69 (2022-09-06 15:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 4 × 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, tigerlake)
  Threads: 1 on 4 virtual cores
 ## Minimum reproducible example
**Julia> include("sandbox.jl")**
This creates a form. 
- Choose from the menu **Examples**  **Events**.
- It appears a second form, choose an Author, for example Alan Perlis.
- The crash appens when the **Reset** button is clicked.

The statement in the 229 line of formgen.jl generates the crash:
```set_gtk_property!(wdgHandles[key],:active,indx)```

Best regards
Giovanni Rossati

[scripts.zip](https://github.com/JuliaLang/julia/files/9842006/scripts.zip)

**Comment by giordano** [comment]
When I click Examples -> Events I get this windows:
![image](https://user-images.githubusercontent.com/765740/197289360-b80beaae-69ff-40b1-bd5c-b2cdb26d3666.png)
I believe you missed to include the file `quotes.txt`.  Also, note that you should build paths with [`joinpath`](https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.joinpath) (e.g. `joinpath(dir, "quotes.txt")`) instead of manually writing out a string with hardcoded backslash as path separator which would work only on Windows (e.g. `"$dir\\quotes.txt"`).

Besides, this looks either a problem in [`Gtk.jl`](https://github.com/JuliaGraphics/Gtk.jl) or in how you pass some functions to `Gtk.jl`, I haven't looked carefully at your code.  I'm going to close this ticket because I don't see an evidence this is a Julia issue.  If you need help please either use the [Discourse webforum](https://discourse.julialang.org/), if instead you believe this is a bug in `Gtk.jl` [open an issue](https://github.com/JuliaGraphics/Gtk.jl/issues/new) there.  Should there be clear evidences (at the moment missing from what I can tell) that this is a bug in Julia itself please report it back and we can reopen this ticket.
