### ISSUE TITLE
incorrect inference of `NamedTuple{(), <:Any}`

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#47481]
See https://github.com/JuliaLang/julia/pull/47059/files/b8a6b104b224da3efc9a85c975feeffc86681bd9#r1006058629
```
julia> (()->NamedTuple{(), <:Any})()
NamedTuple{(), Tuple{}}
```

**Comment by aviatesk** [comment]
I may be making a serious misunderstanding. My understanding is that `NamedTuple{(), <:Any}` can only represent `NamedTuple{(), Tuple{}}` (since `NamedTuple{(), T}` raises an error when `T` isn't `Tuple{}` making it valid for inference to assume `NamedTuple{(), T}` to be `NamedTuple{(), Tuple{}}` always.

**Comment by martinholters** [comment]
```julia
julia> NamedTuple{(), <:Any}
NamedTuple{(), <:Any}

julia> (() -> NamedTuple{(), <:Any})()
NamedTuple{(), Tuple{}}
```
We cannot create instances of `NamedTuple{(), <:Any}`, but we can still create the type.

**Comment by KristofferC** [comment]
@aviatesk, any thoughts about what progress could be made here?

**Comment by KristofferC** [comment]
I've reverted https://github.com/JuliaLang/julia/pull/47059 on 1.9 so moving the milestone.

**Comment by vtjnash** [comment]
It should probably be reverted on master too then, since the commit itself is faulty (closing this issue)
