### ISSUE TITLE
Containers of abstract type performance (feature request)

### ISSUE THREAD

**Issue by Ha5hBr0wn** [JuliaLang/julia#47551]
Hi, 

I have been using Julia for just a few months and I generally really like the language. 

There is one aspect of it that has been bothering me however, and that is designing my code to not use containers with abstract type parameters (one of the performance tips). 

All the other performance tips have been easy for me to follow except that one. I have found myself trying to hack my way through with tuples and metaprogramming to maintain type stability. Something that requires more effort than I would like. 

I don't know if it is even possible given the design of the language, but is there any feasible way to speed up containers with abstract type parameters. Or are they already as optimized as can be? 

If there is no feasible performance boost what are some design work arounds that the community have been using? Perhaps some discussion on that will enlighten me on how to avoid having to use such containers in the first place.

**Comment by jakobnissen** [comment]
It is fundamentally not possible to compile efficient code that makes use of abstractly typed containers. This is common across programming languages.The fundamental problem is that if a type contains an abstractly typed field, the compiler cannot predict the type obtained when the field is loaded. Without type information, the compiler needs to emit a lot of runtime checks, and needs to use runtime dispatch.

Hence, I don't think this issue is tractable. Not that there aren't any possible optimisations for abstractly typed fields to allieviate some of the performance impact, but rather that these optimisations would require more concrete proposals.

In Julia, we get around it by using parametric type. That is, if you're tempted to write this:
```julia
struct Foo
    x::Integer
    v::Vector{Any}
end
```
You can instead write
```julia
struct Foo{I <: Integer, T}
    x::I
    v::Vector{T}
```
Any particular concrete subtype of `Foo`, e.g. `Foo{Int32, String}` - would not use abstractly typed fields.
For more details, ask on the Julia discourse, or on Slack, where people are normally happy to help with this kind of questions.

**Comment by vtjnash** [comment]
Do you have some example code? There might be applicable internal optimizations, but there would need to be a use case demonstration to know what they are.

**Comment by vtjnash** [comment]
There are many layers of caching already. That is why I asked for an example of what code pattern you encountered, as it helps substantially to refer to a specific examples and measurements, and not just speculate about a feeling.

**Comment by brenhinkeller** [comment]
One thing that hasn't been mentioned yet -- in some cases it could also be useful to use a container whose element type is a small union of concrete types, i.e. (as a toy example):
```
julia> a = ones(Union{Int64, Float64}, 5)
5-element Vector{Union{Float64, Int64}}:
 1
 1
 1
 1
 1

julia> a[2] = 1.0
1.0

julia> a
5-element Vector{Union{Float64, Int64}}:
 1
 1.0
 1
 1
 1
```
This could be quite a bit faster than using an array with an abstract `eltype`, especially if your concrete types are the same size as each other, and should benefit from some performance optimizations if there are fewer than (?)4-ish types in the union.

It may also be worth considering more broadly if there are any ways you can refactor your problems in a more dispatch-oriented way such that the types can be inferred; to me it really is a different programming paradigm, and not one most people  dispatch-oriented programming style since it's really not common unless you're
