### ISSUE TITLE
Sys.free_memory wrong on Apple ARM

### ISSUE THREAD

**Issue by fonsp** [JuliaLang/julia#47684]
On Julia 1.8.3, ARM build, and x86 build with Rosetta, `Sys.free_memory()` returns around 50MB, while my activity monitor shows that 2.5GB is free. `Sys.total_memory()` is correct. Note the `Memory:` line in the screenshot below:

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/6933510/203627139-a3a38145-61f8-46b3-912b-de223d8bf890.png">

The result of `Sys.free_memory()` is not fixed, but it is always too low:

```julia
julia> Sys.free_memory() / 1e9
0.086638592

julia> Sys.free_memory() / 1e9
0.076365824

julia> Sys.free_memory() / 1e9
0.089423872
```

**Comment by vtjnash** [comment]
Might need to file this upstream with libuv too, if the issue is accurate. Maybe we should try using `host_statistics64` for this API? FWIW, on my Intel machine with 16 GB ram and 12 GB "used" I get:
```
julia> Sys.free_memory() /1024/1024
143.796875

julia> Sys.free_physical_memory() /1024/1024
187.02734375

julia> Sys.MACHINE
"x86_64-apple-darwin21.6.0"
```
due to `host_statistics(HOST_VM_INFO)` reporting:
```
(vm_statistics_data_t) $0 = {
  free_count = 18330
  active_count = 1389516
  inactive_count = 1380917
  wire_count = 786126
  zero_fill_count = 479466944
  reactivations = 18148299
  pageins = 17841460
  pageouts = 247405
  faults = 878748845
  cow_faults = 11088343
  lookups = 0
  hits = 0
  purgeable_count = 184555
  purges = 9635737
  speculative_count = 12151
}
```

It is also thus likely that this value is correct, and that there are various file caches occupying the difference in space. Which is both "free" (in the sense that it can be dropped without writing to cache) and used (in the sense that it currently is allocated to hold something)

htop reports
```
  Mem[7.91G/16.0G] Swp[2.53G/4.00G] 
```
top reports
```
MemRegions: 164057 total, 5193M resident, 157M private, 1315M shared.
PhysMem: 15G used (3112M wired), 823M unused.
```

**Comment by vtjnash** [comment]
It looks like this value is correct (as reported by the kernel). It may not be useful to you, but then, this function probably isn't useful.
