### ISSUE TITLE
Allocation regression when iterating over Adjoint of Matrix

### ISSUE THREAD

**Issue by pablosanjose** [JuliaLang/julia#47703]
Ref: https://discourse.julialang.org/t/allocations-again/90780/13

António Araújo noted the following, which started happening sometime between v1.8.1 and v1.8.3

```julia
using BenchmarkTools

function test(x, Y)
    sum!(x, Y')
    return nothing
end

x = rand(Float64, 100)
Y = rand(Float64, 1, 100)
```
```julia
julia> @btime(test($x, $Y))
  301.619 ns (2 allocations: 96 bytes)
```
In v1.8.0 and v1.8.1 we have instead
```julia
julia> @btime(test($x, $Y))
  68.719 ns (0 allocations: 0 bytes)
```

**Comment by jishnub** [comment]
Can confirm allocations on `v1.8.2`
```julia
julia> @btime test($x, $Y);
  490.247 ns (2 allocations: 96 bytes)

julia> VERSION
v"1.8.2"
```

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/compare/v1.8.1...v1.8.2 are the commits between 1.8.1 and 1.8.2

**Comment by fredrikekre** [comment]
https://github.com/JuliaLang/julia/pull/46605 then probably.

**Comment by N5N3** [comment]
Some of regression comes from the the allocation caused by
```julia
switch_dim12(B::AbstractVector) = permutedims(B)
```
We can ignore it by define `switch_dim12(B::AbstractVector{<:Number}) = transpose(B)`.
Then we'll find the root cause
```julia
f(x, Y) = Base.mapreducedim!(identity, Base.add_sum, x, Y')
f2(x, Y) = (g(x, y) = Base.add_sum(x, y); Base.mapreducedim!(identity, g, x, Y'))

@btime f2($x, $Y); # simulated 1.8.0: 27.008 ns (0 allocations: 0 bytes) 
@btime f($x, $Y);  #          master: 112.000 ns (0 allocations: 0 bytes)
```
This is not suppressing as our `mapreducedim!` is not optimized for this case (dim1 reduction with small size)
If we increase the size of `Y` to 100x100 than `f` is about 2.5x faster than `f2`. So It might be hard to make all cases faster.
