### ISSUE TITLE
Request: `@test` should use `all` when it receives a vector

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaLang/julia#47885]
It'd be nice to be able to do something like this:
```
@test mean(rand(10, 10); dims=1) .≈ .5
```
And then have it work out so the test tells me whether all the tests passed (i.e. whether this returns a vector of `true`).

**Comment by jakobnissen** [comment]
Why not just add the `all` yourself?

**Comment by fredrikekre** [comment]
I like the simplicity of `@test` and that `true` is the only value that is interpreted as truthiness. I think it would be bad to suddenly try to interpret other things as true. It is better to be explicit.

**Comment by ParadaCarleton** [comment]
> I like the simplicity of `@test` and that `true` is the only value that is interpreted as truthiness. I think it would be bad to suddenly try to interpret other things as true. It is better to be explicit.

Maybe a macro `@test_all` that calls `all` as well, then?

> Why not just add the `all` yourself?

`all` can make things harder to read when too many layers are nested. The other problem is it messes with passing keyword arguments to `≈`.

**Comment by StefanKarpinski** [comment]
I would point out that `@test_all expr` is only one character shorter than `@test all(expr)`.

**Comment by StefanKarpinski** [comment]
Here are the current alternatives:
```jl
# 1 — give up on infix with keyword
@test all((≈).(mean(rand(10, 1000); dims=2), 0.5, atol=0.05))

# 2 — give up on it being a one-liner
v = mean(rand(10, 1000); dims=2)
for x in v
    @test x ≈ 0.5 atol=0.05
end

# 3 — abuse a comprehension
[(@test x ≈ 0.5 atol=0.05) for x in mean(rand(10, 1000); dims=2)]
```
Those are all a bit awkward, I have to admit.

Thinking this through a bit, if we were to add `@test_all`, how would you translate something like this?
```jl
@test_all mean(rand(10, 1000); dims=2) .≈ 0.5 atol=0.05
```
I guess it would be something like this:
```jl
@test all((.≈)(mean(rand(10, 1000); dims=2), 0.5, atol=0.05))
```
Maybe it's less bad than I thought since broadcasting infix operators seem to be lowered the same way as normal operators. It's a little weird that this wouldn't work for non-infix broadcast calls though, like
```jl
@test_all isapprox.(mean(rand(10, 1000); dims=2), 0.5) atol=0.05
```
This version would need special handling, but arguably that should be written with the keyword in the normal place. It would just be odd for that not to work when this does work:
```jl
@test isapprox(mean(rand(1000)), 0.5) atol=0.05
```
Maybe not a big deal though.
