### ISSUE TITLE
Excision: LazyArtifacts

### ISSUE THREAD

**Issue by 2005m** [JuliaLang/julia#47922]
Hi,

Should the LazyArtifacts package rely in the following repo:

https://github.com/JuliaPackaging/LazyArtifacts.jl

and be removed from the Julia repo?
(A bit like the package Pkg.jl is?)

If the answer is yes, I am happy to submit a PR.

Thank you
Kind regards

**Comment by 2005m** [comment]
Hi @DilumAluthge , I thought I'll ping you as you seem to be looking at this things. If you look at the following branch, you can see the changes I am talking about:
https://github.com/2005m/julia/tree/Excision
Thank you

**Comment by giordano** [comment]
https://github.com/JuliaPackaging/LazyArtifacts.jl contains the code for a non-stdlib package which is meant to be used for compatibility with previous Julia versions, so that you're proposed change is simply wrong.

It's unlikely LazyArtifacts.jl will undergo massive development at least in the near future, excising it would be more work than not touching it at all, for no gain.

**Comment by 2005m** [comment]
Your explanation make little sense to me. Maybe it is the way it is written or formulate.
If LazyArtifacts is a non-stdlib not sure what it is doing in the Julia source code. It should stay outside or maybe I am missing something?
Have the code in both a seperate repo and the Julia source code seems to me like duplicating the work. But fine by me if you think it is wrong...

**Comment by giordano** [comment]
> If LazyArtifacts is a non-stdlib not sure what it is doing in the Julia source code.

[stdlib/LazyArtifacts](https://github.com/JuliaLang/julia/tree/master/stdlib/LazyArtifacts) _is_ a standard library, which has been introduced only recently (I don't remember exactly, maybe Julia v1.5 or v1.6?).  As also explained in its [README.md](https://github.com/JuliaPackaging/LazyArtifacts.jl/blob/c1c1c7a90f66c64a42a6338032b816788a6d2011/README.md) file, https://github.com/JuliaPackaging/LazyArtifacts.jl is a third-party package which lives in its own repository and provides similar functionalities as the standard library with the same name for older versions of Julia where the standard library didn't exist in the first place.  You're proposing to mix them up.

Is this any clearer now?

**Comment by 2005m** [comment]
No I am not suggesting to mix them. I am suggesting to keep the external one and pull it when Julia is built the same way Pkg is pulled. As you said the functionalities are similar and looking at the code ...it is similar so not sure why one should have duplicated code....

**Comment by giordano** [comment]
> No I am not suggesting to mix them.

Yes, you are.  https://github.com/JuliaPackaging/LazyArtifacts.jl is meant to be used for versions of Julia where the standard library doesn't exist.

> As you said the functionalities are similar and looking at the code ...it is similar

They're _similar_ but not identical because they ***are*** different things.

> so not sure why one should have duplicated code....

They target different versions of Julia which provide different functionalities.

**Comment by 2005m** [comment]
How are the changes that I am suggesting preventing previous version or Julia of using the external packages?
Indeed similar but not identical. Are you suggesting that one cannot target different versions of Julia directly in the code?

**Comment by giordano** [comment]
> How are the changes that I am suggesting preventing previous version of Julia of using the external package? Indeed similar but not identical.

You're pulling https://github.com/JuliaPackaging/LazyArtifacts.jl as-is, which is not correct because, as you're finally acknowledging, it's not exactly what the standard library does right now.

> Are you suggesting that one cannot target different versions of Julia directly in the code?

Not without a bunch of `if VERSION ...` guards.

I'm spending more time in this discussion that I ever spent in https://github.com/JuliaPackaging/LazyArtifacts.jl or how much time will be devoted by anyone to the corresponding standard library in the near future.  What I'm trying to say is that it'd make sense to move the standard library to an external repository if it were going to be further actively developed, but doing it just for the sake of doing it looks to me a waste of everybody's time for exactly zero reasons.
