### ISSUE TITLE
isassigned: incorrect bounds check for ndims > 1

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#47942]
This looks like a long-buried bug, recently [identified on discourse](https://discourse.julialang.org/t/how-do-i-use-isassigned-with-a-matrix/91913/):
```jl
julia> isassigned(zeros(161,517), 500, 514) # should be false
true
```
The problem is that the [`isassigned` code](https://github.com/JuliaLang/julia/blob/8cdb17b48a005a97889f07593c4a619add46ea76/base/array.jl#L219) is checking only the *linear* index and not the multidimensional index, which is sufficient to prevent a crash but insufficient to check bounds for multidimensional indices.

cc @timholy, since this code originated in #11167, and @yuyichao who optimized this code (but did not change the semantics) in #20890.

**Comment by shlemas** [comment]
I'm the OP from that thread. I started looking at this on a whim, learning a bit about Julia dev if nothing else.

I have a naive fix here: https://github.com/JuliaLang/julia/compare/master...shlemas:julia:isassigned-multidim

It's so simple that I feel like it must be non-ideal. For example, `isassigned` was doing its own simple bounds check instead of calling `checkbounds`. I see other versions doing the same. I don't know if there is an intent behind that (e.g. optimization) or if it's because the check is so trivial that the author just wrote it out. Interested to know either way.

**Comment by oscardssmith** [comment]
Looks good to me, can you make a pull request out of the branch? (press green button "Create pull request"). The only comment I have is that I think the second `checkbounds` isn't needed.

**Comment by shlemas** [comment]
Done. I removed the second `checkbounds`, tests were still good.
