### ISSUE TITLE
Rational constructor doesn't work on inputs of a^-b

### ISSUE THREAD

**Issue by thomastjdavis** [JuliaLang/julia#47964]
![image](https://user-images.githubusercontent.com/67081709/209125470-a8fa658c-a129-4603-a560-035199ddd576.png)
This rational constructor doesn't work as expected. Some other values of a,b that this doesn't work include:

![image](https://user-images.githubusercontent.com/67081709/209125830-c28d9f7c-a22c-4946-9beb-4a578b9221e7.png)

Interestingly, some values of a,b work fine, so this behavior is unexpected and strange.

**Comment by giordano** [comment]
Are you missing that [floating point numbers](https://en.wikipedia.org/wiki/Floating-point_arithmetic) are only an approximation of real numbers?

**Comment by Seelengrab** [comment]
To expand on that - before the `Rational` constructor is called, e.g. `1/(6^3)` is calculated as a floating point number first, which cannot represent all real numbers correctly. This is then converted to a `Rational`, but since the initial calculation already lost precision, `Rational` cannot recover that. If you want to construct rational numbers, I'd recommend using the `//` operator:

```
julia> 1//(6^3)
1//216
```
