### ISSUE TITLE
Complex division:when divisor is 0+0im

### ISSUE THREAD

**Issue by wang-zh** [JuliaLang/julia#47999]
why (3+0im)/(0+0im) is equal to NaN + NaN*im   Instead of  Inf+0im
![image](https://user-images.githubusercontent.com/39694902/209539012-347b506e-8acc-44fe-b645-5b7801bbbaef.png)

**Comment by KristofferC** [comment]
Ref https://github.com/JuliaLang/julia/issues/5234

**Comment by brenhinkeller** [comment]
Looks like this can be closed as duplicate if no objections

**Comment by hyrodium** [comment]
>why (3+0im)/(0+0im) is equal to NaN + NaN*im Instead of Inf+0im

This is because the limit does not exist.
```math
\begin{aligned}
\frac{1}{a+bi} &= \frac{a}{a^2+b^2} + i \frac{-b}{a^2+b^2} \\
\lim_{a \to +0}\lim_{b \to +0}\frac{a}{a^2+b^2} &= +\infty \\
\lim_{b \to +0}\lim_{a \to +0}\frac{a}{a^2+b^2} &= 0 \\
\lim_{a \to +0}\lim_{b \to +0}\frac{-b}{a^2+b^2} &= 0 \\
\lim_{b \to +0}\lim_{a \to +0}\frac{-b}{a^2+b^2} &= -\infty
\end{aligned}
```
Related:
* https://github.com/JuliaLang/julia/issues/22983
* https://discourse.julialang.org/t/why-inv-complex-0-0-0-0-returns-complex-nan-nan/92694/2
* https://github.com/scheinerman/RiemannComplexNumbers.jl
* https://hyrodium.github.io/RiemannSphereOperations.jl/dev/
