### ISSUE TITLE
Regression in PowerSystemsUnits in julia 1.9.0-beta2 vs 1.9.0-alpha1

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#48078]
Repro:

```julia
julia> using PowerSystemsUnits, Unitful

julia> 1u"USDPerMWh" == 1u"USD/(MW*hr)"
ERROR: KeyError: key :Currency not found
Stacktrace:
  [1] getindex(h::Dict{Symbol, Unitful.Unit}, key::Symbol)
    @ Base ./dict.jl:484
  [2] (::Unitful.var"#95#96")(z::Unitful.Dimension{:Currency})
    @ Unitful ./none:0
  [3] iterate(::Base.Generator{Tuple{Unitful.Dimension{:Currency}, Unitful.Dimension{:Length}, Unitful.Dimension{:Mass}, Unitful.Dimension{:Time}}, Unitful.var"#95#96"})
    @ Base ./generator.jl:47
  [4] #s76#94
    @ ~/.julia/packages/Unitful/JwSBO/src/units.jl:305 [inlined]
  [5] var"#s76#94"(D::Any, ::Any, x::Any)
    @ Unitful ./none:0
  [6] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any})
    @ Core ./boot.jl:602
  [7] _promote_unit
    @ ~/.julia/packages/Unitful/JwSBO/src/promotion.jl:25 [inlined]
  [8] promote_unit
    @ ~/.julia/packages/Unitful/JwSBO/src/promotion.jl:18 [inlined]
  [9] promote_rule(#unused#::Type{Quantity{Int64, Money 𝐓² 𝐋⁻² 𝐌⁻¹, Unitful.FreeUnits{(USDPerMWh,), Money 𝐓² 𝐋⁻² 𝐌⁻¹, nothing}}}, #unused#::Type{Quantity{Int64, Money 𝐓² 𝐋⁻² 𝐌⁻¹, Unitful.FreeUnits{(USD, hr⁻¹, MW⁻¹), Money 𝐓² 𝐋⁻² 𝐌⁻¹, nothing}}})
    @ Unitful ~/.julia/packages/Unitful/JwSBO/src/promotion.jl:71
 [10] promote_type
    @ ./promotion.jl:307 [inlined]
 [11] _promote
    @ ./promotion.jl:357 [inlined]
 [12] promote
    @ ./promotion.jl:381 [inlined]
 [13] ==(x::Quantity{Int64, Money 𝐓² 𝐋⁻² 𝐌⁻¹, Unitful.FreeUnits{(USDPerMWh,), Money 𝐓² 𝐋⁻² 𝐌⁻¹, nothing}}, y::Quantity{Int64, Money 𝐓² 𝐋⁻² 𝐌⁻¹, Unitful.FreeUnits{(USD, hr⁻¹, MW⁻¹), Money 𝐓² 𝐋⁻² 𝐌⁻¹, nothing}})
    @ Unitful ~/.julia/packages/Unitful/JwSBO/src/quantities.jl:316
 [14] top-level scope
    @ REPL[4]:1
```

On julia-1.9.0-alpha1:

```julia
julia> 1u"USDPerMWh" == 1u"USD/(MW*hr)"
true
```

Have not yet looked into this further

**Comment by gbaraldi** [comment]
Bisected to https://github.com/JuliaLang/julia/commit/d561447cfcee9bf11148d50c6e7c099c3f6fded0

**Comment by KristofferC** [comment]
The MWE is:

`A.jl`:

```julia
module A
const d = Dict()
end
```

`B.jl`:

```julia
module B

using A
A.d["x"]  = "y"
b = A.d

function __init__()
    @assert haskey(b, "x")
end

end
```

This asserts on 1.9 but passes on 1.8.

This comes up from Unitful.jl because in https://painterqubits.github.io/Unitful.jl/stable/extending/#Precompilation they tell people to do


```julia
const localpromotion = Unitful.promotion
function __init__()
    merge!(Unitful.promotion, localpromotion)
end
```

where they have modified `Unitful.promotion` earlier via a macro.

A workaround is to instead to `const localpromotion = copy(Unitful.promotion)` which breaks the aliasing.

Not sure, but this might just have to be fixed in the packages.

**Comment by vchuravy** [comment]
Thanks for the debugging! As far as I can tell this worked accidentally previously. So yes the right fix is to make a `copy` instead of relying on serialization to make a copy of the new binding.

**Comment by KristofferC** [comment]
https://github.com/PainterQubits/Unitful.jl/pull/600,
https://github.com/haberdashPI/CorticalSpectralTemporalResponses/pull/31,
https://github.com/haberdashPI/SignalBase.jl/pull/5,
https://github.com/rmsrosa/UnitfulAssets.jl/pull/2

was the affected cases of this that I could find on JuliaHub.

**Comment by sostock** [comment]
There might be more packages that are affected, e.g. [DimensionfulAngles.jl](https://github.com/cmichelenstrofer/DimensionfulAngles.jl/blob/c7e87ccbb0d22b30cd6f8f63aba0ceda8db88fcd/src/DimensionfulAngles.jl#L145).

**Comment by KristofferC** [comment]
Thanks, I opened a PR there too.

**Comment by sostock** [comment]
Two more packages that might be affected:
[AdditionalUnits.jl](https://github.com/timmyfaraday/AdditionalUnits.jl/blob/731b341c5d4aef11e6fccc432f10427a523734fa/src/AdditionalUnits.jl#L25)
[UnitfulCurrency.jl](https://github.com/bhgomes/UnitfulCurrency.jl/blob/44e007eb22678a4d70c116524250d1c5b69bd53f/src/UnitfulCurrency.jl#L22) (repo is archived)

**Comment by KristofferC** [comment]
https://github.com/search?q=+merge%21%28Unitful.basefactors%2C++language%3AJulia&type=code&l=Julia

might be more there.

**Comment by sostock** [comment]
I’m looking into it. All those `merge!(Unitful.basefactors, localunits)` aren’t necessary anymore, because `Unitful.register` now takes care of that (where "now" means "since Unitful v0.17", see https://github.com/PainterQubits/Unitful.jl/pull/251). This means that we might have to fix `Unitful.register`.

Maybe we can avoid changing all those packages which do `merge!(Unitful.basefactors, localunits)`: We could rename `Unitful.basefactors` to something else (and fix `Unitful.register` to use the new one) and provide a dummy `Unitful.basefactors` with a custom `merge!` method so that the `merge!(Unitful.basefactors, localunits)` becomes a no-op.

**Comment by vtjnash** [comment]
This Dict also appears to be getting accessed from a generated function (instead of correctly using dispatch to define these behaviors), which is undefined behavior and thus relatively risky to be doing in a package. It violates the principle that the functions must be pure and are therefore forbidden from accessing mutable state: https://docs.julialang.org/en/v1/manual/metaprogramming/#Generated-functions

**Comment by sostock** [comment]
`Unitful.basefactors` doesn’t seem to cause any problems (at least I didn’t find any). I nevertheless tried to replace it using dispatch (so that every new unit would add a method to a function, instead of adding a new key–value pair to the dict), but ran into world age errors that I couldn’t fix.

I wonder if we can copy the `Unitful.basefactors` approach to fix the issue with `Unitful.promotion`. I haven’t yet tested whether that would work. A problem with that might be that the values in `Unitful.promotion` are supposed to be mutable (as opposed to `Unitful.basefactors`, where only new key–value pairs are added), but that doesn’t work as intended anyway (https://github.com/PainterQubits/Unitful.jl/issues/545).
