### ISSUE TITLE
GAP.jl errors on 1.9.0-beta2 vs 1.9.0-alpha1

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#48080]
```
ERROR: LoadError: InitError: invalid redefinition of constant GapObj
Stacktrace:
 [1] initialize(argv::Vector{String})
   @ GAP ~/.julia/compiled/v1.9/GAP/YqHod_YLFNV.dylib:-1
 [2] withenv
   @ ~/.julia/compiled/v1.9/GAP/YqHod_YLFNV.dylib:-1
 [3] __init__()
   @ GAP ~/.julia/compiled/v1.9/GAP/YqHod_YLFNV.dylib:-1
during initialization of module GAP
in expression starting at /Users/kristoffercarlsson/.julia/packages/GAP/p0xxt/test/runtests.jl:1
```

PkgEval log https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/05c8182_vs_258fa32/GAP.primary.log

cc @fingolfin

**Comment by fingolfin** [comment]
Yes, I am aware. This is due to Julia 1.9.0-beta2 breaking its ABI (I really hope this will stop after 1.9.0 is out...). To fix this I have to rebuild GAP_jll against Julia 1.9.0-beta. But to do that, we need a new libjulia_jll, and [we are stuck on that](https://github.com/JuliaPackaging/Yggdrasil/pull/6042) right now, due to what seems to be a problem with getting the package manager to install specific versions of stdlib JLLs... If anyone can help with that, we'd appreciate it (we are discussing this on slack in the binarybuilder channel, too).

**Comment by KristofferC** [comment]
Okay, then it doesn't seem worthwhile to have this specific issue open.

**Comment by fingolfin** [comment]
Nevertheless, thank you for bringing it to my attention (I might have very well missed it over the holidays). And thank you more for joining the discussion on Slack and helping there with a way forward :-)
