### ISSUE TITLE
Precompilation task-wait does not display warning in parallel precompile

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#48371]
#46571 seems to have caused a few packages to fail to precompile. So far, in one diagnosed case this triggered discovery of opportunity for improving the package (https://github.com/JuliaGizmos/GtkObservables.jl/pull/46), while in another this new behavior just feels "picky" (https://github.com/JuliaDebug/Cthulhu.jl/pull/343).

However, the biggest issue is that the nice warning (xref https://github.com/JuliaDebug/Cthulhu.jl/issues/342) gets displayed only with `using PkgX`: it does not get displayed with `pkg> precompile`. This is true even though warnings (printed to `stderr`) now get printed thanks to https://github.com/JuliaLang/Pkg.jl/pull/3319. Thus it seems possible that a simple fix will be to direct these warnings to `stderr`.

Another possible improvement would be to mention "precompile" somewhere in the warning. `[pid 430] waiting for IO to finish:` is fairly cryptic, maybe even just inserting "precompilation" as in `[pid 430] precompilation waiting for IO to finish:` would help?

**Comment by IanButterworth** [comment]
If the precompile process just hangs until interrupt in the example you linked to, then `Pkg.precompile` will currently not show the stderr output during or after being interrupted, as `Pkg.precompile` exits rapidly on interrupt without going via the summary prints.

It could be changed to exit via the summaries though?

**Comment by vtjnash** [comment]
> [pid 430] waiting for IO to finish

Yeah, that sounds probably helpful. I think you should be able to derive the output file name and defined modules names too for further help in narrowing the source down for the user.

**Comment by IanButterworth** [comment]
I'm not sure how to fix this in Pkg.precompile.

There are two issues:
1) The parallel nature doesn't lend itself well to just forwarding stderr from the compilecache subprocesses in real time
2) Interrupting Pkg.precompile because it appears to be hanging (without any output explaining why) will most likely interrupt the print loop and orphan the child compilecache processes, meaning their output cannot be collected and displayed via the new stderr printer https://github.com/JuliaLang/Pkg.jl/pull/3319 because the tasks haven't finished before Pkg.precompile exits.

An easy fix would be if interrupting the print loop could then interrupt the async tasks running compilecache, but I don't believe that's possible?

Alternatively `compilecache` could be reworked to not wait on `success(p)` but check with a timed loop and check for an interrupt event?

Perhaps you can see a good architecture here @vtjnash ?

**Comment by IanButterworth** [comment]
What about only allowing a certain time for trailing processes to exit, then timeout and throw an error?

**Comment by vtjnash** [comment]
Packages already take between seconds to hours to compile, so a timeout would be terrible for the user experience.

Pkg can re-buffer things to stderr, similar to Distributed, which has always had the identical issue.

**Comment by IanButterworth** [comment]
Closed by https://github.com/JuliaLang/Pkg.jl/pull/3358 and https://github.com/JuliaLang/Pkg.jl/pull/3370
