### ISSUE TITLE
Possibly unintended behavior of `zero(Time)`

### ISSUE THREAD

**Issue by vitornesello** [JuliaLang/julia#48452]
I would expect `zero(Time)` to return an object of type `Time`. Instead it returns a `Nanosecond`. See the minimal working example below, where I compare it with `typemin`:

```
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, westmere)
  Threads: 1 on 10 virtual cores
Environment:
  LD_LIBRARY_PATH = :/Library/gurobi910/mac64//lib:/Library/gurobi910/mac64//lib

julia> using Dates

julia> zero(Time)
0 nanoseconds

julia> typemin(Time)
00:00:00

julia> typemin(Time) == zero(Time)
false

julia> typemin(Time) === zero(Time)
false

julia> typeof(zero(Time))
Nanosecond

julia> typeof(typemin(Time))
Time

julia> Nanosecond <: Time
false
```

**Comment by Naunet** [comment]
An additional test I think is interesting, Time can be created from Nanoseconds:
```julia
julia> Time(zero(Time)) == typemin(Time)
true
```

**Comment by barucden** [comment]
`zero(x)` returns the additive identity for `x`. So `x + zero(x) == x` should hold, and it does for a `Time`:
```julia
julia> t = Time("12:34pm", "HH:MMp")
12:34:00

julia> t + zero(t) == t
true
```

The [definition](https://github.com/JuliaLang/julia/blob/master/stdlib/Dates/src/types.jl#L437-L441) of `Base.zero(::Type{Time})` contains the comment "zero returns dt::T - dt::T". The difference of `t - t`, where `t` is a `Time`, really returns a `Nanosecond`:
```julia
julia> t - t
0 nanoseconds

julia> typeof(t - t)
Nanosecond
```
`Time` "represents a specific moment in a 24-hour day", whereas `Nanosecond` is a time period. Adding a time period to a time results in a time again. Overall, it seems that this is intentional.

**Comment by vitornesello** [comment]
Thanks for the explanations! I will close thee issue
