### ISSUE TITLE
Bad performance getting R factor from QR

### ISSUE THREAD

**Issue by fmariofilho** [JuliaLang/julia#48880]
Since the library uses `getproperty` to make and return the `R` factor of a QR factorization (when you write `fac.R`), it keeps recomputing the factor, which leads for very bad performance.  For instance, the following code is very slow:

```
A = # some matrix
fac = qr(A)
diag = [ fac.R[i, i] for i = 1:size(fac.R, 1) ]
```
It would be better to cache the result or, instead of using getproperty, make a function to return the `R` factor.

**Comment by barucden** [comment]
The factors are not recomputed to be precise. They are extracted to newly allocated matrices when the property is requested.

Do you think it would be sufficient to advice the user to cache the factors in the documentation, instead of introducing a new functions for that? Note that the following is already possible so maybe it should also be more advertised:
```julia
julia> A = [3.0 -6.0; 4.0 -8.0; 0.0 1.0]
3×2 Matrix{Float64}:
 3.0  -6.0
 4.0  -8.0
 0.0   1.0

julia> Q, R = qr(A)
LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.6   0.0   0.8
 -0.8   0.0  -0.6
  0.0  -1.0   0.0
R factor:
2×2 Matrix{Float64}:
 -5.0  10.0
```

**Comment by fmariofilho** [comment]
Yes, I meant the factor is not recomputed from scratch, but extracted from somewhere.  Telling the user explicitly is better than nothing.

As a user, I tend to assume that property access like in `fac.R` is simple data access, and that no expensive computation is involved, because this is how things work in Julia and other languages usually.

Is there a problem with caching the result?  For instance, if the user does `fac.R` once, then the matrix is extracted and stored, and the stored one is used in subsequent calls.  Are you worried about the extra memory this would take?

**Comment by dkarrasch** [comment]
That's what `Q, R = qr(A)` does: it caches the `R` factor and then you use it subsequently, instead of `fac.R`. This is advisable in any case, since in (the copy of) `A`, most of the QR decomposition is stored, so accessing `fac.R` cannot be "simple data access". For instance, `R` doesn't need to be square, so we can't simply return `UpperTriangular(F.factors)`. It really requires a matrix that has zeros underneath the diagonal. For your specific example, use

```julia
julia> using LinearAlgebra

julia> F = qr(rand(3,3))
LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
3×3 Matrix{Float64}:
 -0.905348  -0.454075  -0.503822
  0.0        0.392048   0.267522
  0.0        0.0       -0.402202

julia> diag(getfield(F, :factors))
3-element Vector{Float64}:
 -0.9053476175333158
  0.3920484662428043
 -0.4022021773088482
```

to avoid allocating `F.R` in between, which would be a waste indeed. Do you want to take a stab at improving the docs of `qr`?

**Comment by fmariofilho** [comment]
Thanks!

I still think the behavior is counterintuitive, but maybe it is a big hassle to change it now.  I will try to improve the docs when I get some time.
