### ISSUE TITLE
Better error reporting for `stack overflow in type inference`: Line number of the function being inferred / call site

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#49237]
We've seen many errors in prod of the "stack overflow in type inference" variety, and one of the issues is that it's currently not actionable enough.

For example, we recently saw this error:
```julia
Internal error: stack overflow in type inference of iterate(Base.Iterators.ProductIterator{Tuple{Base.Set{...}, Base.Set{...}, ...}}
This might be caused by recursion over very long tuples or argument lists.
```
I truncated the message, but that `Tuple{}` goes on for a _very long time._

However, we currently can't figure out where in our code that is coming from!
It would be helpful to also report two locations, I think:
1. The source location (file:line) of the dynamic dispatch that caused this type inference invocation
2. The source location (file:line) of the method being inferred.

In this case, the function being inferred (2.) would be in `Base` somewhere, so not all that helpful. But maybe sometimes it would be.
But (1.) would be _extremely_ useful, so that we could figure out where this was coming from!

In fact, even better would be to actually dump the stack trace... if that was possible it would be a huge improvement. Thanks!

The exception is reported here:
https://github.com/JuliaLang/julia/blob/f32a5c6ea6e32333c31542eee1d67d5cd219da9c/src/gf.c#L324-L327

------

Other examples of this exception reported in julia, here:
- https://github.com/JuliaLang/julia/issues/48813
- https://github.com/JuliaLang/julia/issues/45286

**Comment by Yasser-Brh** [comment]
Subject: Stack Overflow in Type Inference with Julia 1.10.3 - Seeking Solutions

Hello,

I'm currently experiencing a problem with Julia version 1.10.3 on Linux (x86_64). I have encountered an internal error related to stack overflow during type inference. The error message suggests that it might be related to recursion involving very long tuples or argument lists. Here's the specific error:
**********************
Internal error: stack overflow in type inference of shouldlog(Logging.ConsoleLogger, Base.CoreLogging.LogLevel, Module, Symbol, Symbol).
This might be caused by recursion over very long tuples or argument lists.
Internal error: encountered unexpected error during compilation of shouldlog:
**********************

Although my code does involve some recursion, it is not extensive. I'm wondering if anyone else has experienced similar issues or has insights into potential solutions for this type of problem. Any suggestions on how to handle or debug this error would be greatly appreciated.

Here are some details about my system and Julia installation:

OS: Linux (x86_64-linux-gnu)
CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
Julia Version: 1.10.3
LLVM version: libLLVM-15.0.7

Thank you in advance for any help or guidance you can provide!

**Comment by nsajko** [comment]
@Yasser-Brh ask on the [Julia Discourse](https://discourse.julialang.org). Prepare a self-contained reproducing example beforehand.

**Comment by nsajko** [comment]
As far as I understand/hope `stack overflow in type inference` is a thing of the past now after #55575.
