### ISSUE TITLE
`@simd` enables unexpected fastmath optimizations

### ISSUE THREAD

**Issue by mikmoore** [JuliaLang/julia#49387]
`@simd` results in `@fastmath` being applied. This is undocumented behavior (except for re-association of reduction variables). The behavior needs to be documented or the `@fastmath` needs to not occur.

Reduced example derived from an effort to write a faster `norm(x, 2)`:
```julia
# Julia v1.8.0

function test(x)
	scale = exp2(768)
	s1 = 0.0
	s2 = 0.0
	@simd for z in x
		s1 += abs2(z)
		s2 += abs2(z*scale)
	end
	s = s2==Inf ? s1 : s2
	return s,s1,s2
end

test(1:3)
# (Inf, 14.0, Inf)
```

Inspecting the `@code_llvm` shows many `@fastmath` operations and the `@code_native` shows unauthorized `fma` instructions. The result should be `s == s1 == 14.0`, but instead we get `s == s2 == Inf` because the `s2==Inf` check is replaced by `false` by the "noinf" property inherited from `@fastmath`.

**Comment by giordano** [comment]
I don't think "`@simd` invokes `@fastmath`" is an accurate description because as far as I know `@simd` never invokes the `@fastmath` macro, but the code it generates enables LLVM fast-math flags under certain conditions, I presume around https://github.com/JuliaLang/julia/blob/c6ed7d7c54a501090019e2f509935f6f21bdf9af/src/llvm-simdloop.cpp#L67-L131 probably https://github.com/JuliaLang/julia/blob/c6ed7d7c54a501090019e2f509935f6f21bdf9af/src/llvm-simdloop.cpp#L126 in particular

**Comment by vchuravy** [comment]
```
help?> @simd
  @simd

    •  Floating-point operations on reduction variables can be reordered,
       possibly causing different results than without @simd.
```

There is an argument to only enable `reassoc`/`contract`.

**Comment by mikmoore** [comment]
I would argue that "contract" is also not permitted under the current language (it's more than just reordering as it eliminates otherwise-unavoidable rounding steps). But the language can certainly be amended.
