### ISSUE TITLE
The rounding of Float16 subnormals

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#49698]
The rounding of `Float16` subnormals seems to be inconsistent from the same operation in a native floating-point type.

The following example does the same thing for both `Float16` and `Float32`: construct an FP number with an odd mantissa, then halve it until it turns subnormal. Because the mantissa is odd, a rounding has to happen when the number turns subnormal. The rounding is away from zero for `Float16`, but towards zero for `Float32`. I haven't read the IEEE 754 spec, but it seems vastly more likely that `Float32` is correctly implemented and `Float16` is the buggy one.

```julia-repl
julia> versioninfo()
Julia Version 1.10.0-DEV.1221
Commit 9201414b3d8 (2023-05-05 17:36 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver2)
  Threads: 1 on 8 virtual cores

julia> m32 = 16777213
16777213

julia> m16 = 1543
1543

julia> ndigits(m32, base = 2) == precision(Float32)
true

julia> ndigits(m16, base = 2) == precision(Float16)
true

julia> e32 = 150
150

julia> e16 = 25
25

julia> issubnormal(ldexp(Float32(m32), -e32))
true

julia> issubnormal(ldexp(Float32(m32), -e32) * 2)
false

julia> issubnormal(ldexp(Float16(m16), -e16))
true

julia> issubnormal(ldexp(Float16(m16), -e16) * 2)
false

julia> Int(ldexp(ldexp(Float32(m32), -e32), e32))  # Rounded towards zero
16777212

julia> Int(ldexp(ldexp(Float16(m16), -e16), e16))  # Rounded from zero
1544

julia> # It's the same Without `ldexp`

julia> x32 = Float32(2)^Int(e32/5)
1.0737418f9

julia> x16 = Float16(2)^Int(e16/5)
Float16(32.0)

julia> Int(Float32(m32) / x32 / x32 / x32 / x32 / x32 * x32 * x32 * x32 * x32 * x32)
16777212

julia> Int(Float16(m16) / x16 / x16 / x16 / x16 / x16 * x16 * x16 * x16 * x16 * x16)
1544
```

**Comment by nsajko** [comment]
The reason I stumbled upon this is that it prevents "round to odd" rounding from working. Round to odd is a (nonstandard) rounding mode that prevents double rounding errors when used before round to nearest. The rounding mode consists of simply setting the least significant bit of the mantissa when the result is not exact, see, for example: https://hal-ens-lyon.archives-ouvertes.fr/inria-00080427v2

**Comment by gbaraldi** [comment]
Would also be interesting to check the behaviour with C on the same machine.

**Comment by nsajko** [comment]
In some cases the `Float16` subnormal is rounded *towards* zero, instead of away from zero like in the example above:
```julia-repl
julia> m16 = 1543  # same as in example above
1543

julia> e16 = 25
25

julia> x = ldexp(Float16(m16), -e16 + 1)
Float16(9.197e-5)

julia> issubnormal(x)
false

julia> issubnormal(x / 2)
true

julia> Int(ldexp(x/2, e16))
1544

julia> abs(x/2.0 - x/2) == abs(x/2.0 - prevfloat(x/2))  # tie
true

julia> m = 1537
1537

julia> y = ldexp(Float16(m), -e16 + 1)
Float16(9.16e-5)

julia> issubnormal(y)
false

julia> issubnormal(y / 2)
true

julia> Int(ldexp(y/2, e16))
1536

julia> abs(y/2.0 - y/2) == abs(y/2.0 - nextfloat(y/2))  # tie
true
```

It would be interesting to see how gradual underflow is specified by IEEE.

**Comment by milankl** [comment]
I thought that since v1.6 we use LLVM's half type, so rounding doesn't actually happen inside Julia anymore (it did before though!) so I'm suspecting that the behaviour of tie breaks is specified therein

**Comment by milankl** [comment]
I don't think this is a bug, maybe there's a misunderstanding of how IEEE specifies tie to even?

I just checked your two examples from above
```julia
x1 = Float16(9.197e-5)
x2 = Float16(9.16e-5)
```
(apologies if I have misunderstood some of your steps, I think in bits). 

1. `Float16(9.197e-5)/2`
```julia
julia> using BitInformation     # has bitstring(::AbstractFloat,:split) which visually separates sign, exp, mantissa bits
julia> bitstring(x1,:split)
"0 00001 1000000111"
```
and so in [floatmin,2floatmin) or $[2^{-14},2^{-13})$ (in fact just larger than midway of this range). When halving `x1` this becomes a subnormal in [floatmin/2,floatmin) where eps (distance between representable numbers) halfs too, so you have to apply rounding, as you say. Because the subnormals don't have the hidden bit, this operation is equivalent to a bitshift to the right, i.e. your exact result would be
```
0 00001 1000000111 >> 1
0 00000 1100000011|1
```
I've added the `|` to mark the 10 mantissa bits and denote what needs rounding afterwards. `1|1` is a tie between `1|0` (round down) and `10|0` (round up), so tie to even is applied meaning we need to round up. `011|1` therefore becomes `100|0` with carry which is exactly the result we get
```julia
julia> bitstring(x1/2,:split)
"0 00000 1100000100"
```

2. `Float16(9.16e-5)/2`
```julia
julia> bitstring(x2,:split)
"0 00001 1000000001"
```
So a very similar situation to before, meaning
```
0 00001 1000000001 >> 1
0 00000 1100000000|1
```
However, this time the tie break will round down so `0|1` is rounded down to `0|0` not up to `1|0` which would be the odd float. Which is again exactly what we get
```julia
julia> bitstring(x2/2,:split)
"0 00000 1100000000"
```
3. Like `x1` but for Float32

Let's create the same situation for Float32
```julia
julia> x3 = reinterpret(Float32,0x00c0_0007)
1.7632425f-38

julia> bitstring(x3,:split)
"0 00000001 10000000000000000000111"

julia> bitstring(x3/2,:split)
"0 00000000 11000000000000000000100"
```
which is exactly as above, just with more zero mantissa bits in between.

4. Like `x2` but for Float32

Same here
```julia
julia> x4 = reinterpret(Float32,0x00c0_0001)
1.7632417f-38

julia> bitstring(x4,:split)
"0 00000001 10000000000000000000001"

julia> bitstring(x4/2,:split)
"0 00000000 11000000000000000000000"
```

**Comment by milankl** [comment]
Rereading your original post

> The following example does the same thing for both `Float16` and `Float32`: construct an FP number with an odd mantissa, then halve it until it turns subnormal. Because the mantissa is odd, a rounding has to happen when the number turns subnormal. The rounding is away from zero for `Float16`, but towards zero for `Float32`.

I feel there is a misunderstanding here: IEEE specifies tie to even, which can be either round to zero or away from zero in the situation described here. In fact it depends on the 2nd last bit: The halving in subnormals is equivalent to `>>1` and so the last bits `xyz` are rounded as: `xyz >> 1 = xy|z`, now for `z=1` we have a tie and the `y` bit determines round to or away from zero. For `y=0` it's to zero, for `y=1` it's away from zero.
