### ISSUE TITLE
type inference regression in 1.9 due to semi-concrete interpretation

### ISSUE THREAD

**Issue by ojwoodford** [JuliaLang/julia#50037]
On upgrading to Julia from 1.8.5. to 1.9.0 I noticed code in one of my packages slow down significantly. It has taken me a long time to get down to the simplest code which replicates the problem, but I have it now. After upgrading, the following code has become type unstable, and 1000x slower as a result:

```julia
using StaticArrays, BenchmarkTools

@inline function countvars(bitflags, var)
    return bitflags >> 0
end

function myfunc(::Val{bitflags}, var) where bitflags
    N = countvars(bitflags, var)
    return zeros(SVector{N, Float64})
end

struct A
    data::Float64
end
a = A(0.)

@btime myfunc(Val(1), $a);
@code_warntype myfunc(Val(1), a);
```

Moreover, this effect is very unstable - seemingly insignificant changes to the code result in the type stability disappearing. For example:

* Removing `data`  from struct `A`
* Moving the code from `countvars` directly into `myfunc`
* Removing the redundant `var` from the inputs to `countvars`
* Changing the `>>` in line 4 to something like `&` or `+`

```
julia> versioninfo()
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_NUM_THREADS = 8
  JULIA_EDITOR = code
```

**Comment by oscardssmith** [comment]
Reduced slightly to
```
countvars(bitflags, var) = return bitflags >> 0

function myfunc(::Val{bitflags}, var) where bitflags
    N = countvars(bitflags, var)
    return Array{Float64, N}
end

struct A
    data::Float64
end
@code_warntype myfunc(Val(1), A(0));
```
The problem appears to be that `myfunc` isn't being constant folded even though the compiler knows that it could be. It is inferring correct effects for `countvars` and then not using that information. I think part of the problem is that it is evaluating `bitflags` as `::Type{1}` rather than `::Core.Const(1)`

**Comment by aviatesk** [comment]
've verified that this issue is replicable on the master branch. This problem resembles what we're attempting to address with [this PR](https://github.com/JuliaLang/julia/pull/47994). However, as @vtjnash highlighted, the PR has some performance-related issues, so we may need to explore alternative solutions. This means that we may need to make adjustments to the semi-concrete interpretation algorithm.

**Comment by oscardssmith** [comment]
Why are we using semi-concrete eval at all here? We know the inputs to the function, so we should be able to use concrete eval, right?

**Comment by aviatesk** [comment]
`var` is not compile-time constant.

**Comment by ojwoodford** [comment]
> Why are we using semi-concrete eval at all here? We know the inputs to the function, so we should be able to use concrete eval, right?

In my actual use case, the type of var is used to return a type-dependent value, i.e. constant for each type, but different between types.

**Comment by aviatesk** [comment]
Reduced this MRE yet further:
```julia
julia> @inline countvars(bitflags, var) = bitflags >> 0
countvars (generic function with 1 method)

julia> Base.return_types((Int,)) do x
           Val(countvars(1, x))
       end |> only
Val
```
We can get the optimal result (`Val{1}`) if we turn off the semi-concrete interpretation.
