### ISSUE TITLE
Should we add a keyword to sort missing values as small  `sort!(v, missingssmallest=true)`?

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#50288]
Right now, missing values are always sorted as the largest value. By default, this puts them at the end, just past the highest non-missing value. When sorting with `rev=true`, this puts them at the beginning, just before the highest non-missing value. Do we want a way to order them just past the smallest value?

_originally posted by @chris-b1 in https://github.com/JuliaData/DataFrames.jl/issues/2267_

Adding a subtype of `Ordering` that accomplishes this can be done in a package. Adding a keyword to conveniently construct those orderings in general would need to be implemented in Base (and therefore all the machinery would need to be in Base).

**Comment by jariji** [comment]
A naming question:

[In SQL](https://www.postgresql.org/docs/15/queries-order.html), this is written

```sql
ORDER BY colname [ASC | DESC] [NULLS { FIRST | LAST }]
```
eg

```sql
ORDER BY age DESC NULLS FIRST
ORDER BY age DESC NULLS LAST
```

which is isomorphic but different to the spelling proposed in the OP. In particular, should the position of the missings be specified in terms of

- smallness, i.e. in terms of the comparison
- first/last, i.e. in terms of the output order

These options will interact differently with `rev=true`.

**Comment by nalimilan** [comment]
As discussed at https://github.com/JuliaData/DataFrames.jl/issues/2267 and https://github.com/JuliaData/Missings.jl/issues/142, I don't think we need a specific keyword argument for this, as a syntax like `lt=missingisless` is convenient enough. But I'm not sure whether it would be possible to implement efficient algorithms for this custom ordering from outside Base given that `missing` and `isless` are special-cased in a few places.

**Comment by LilithHafner** [comment]
I believe that it is possible to implement efficient algorithms outside Base.

**Comment by adienes** [comment]
rather than think of `missing` as a largest value, I prefer to think of them as the "excluded middle." that is, `isless(missing, 1)` does not return `false` because `missing > 1`, but because NOT `missing < 1`.

when `rev=true`, this just returns "the reverse of what original sort would do" and hence places `missing` first, but this does not make them greater. I think at some level the "right" way to sort in descending order would to be to use an `isgreater` similar to `isless`, which would also return `false` for missing values, and still place them last.

**Comment by mikmoore** [comment]
I'll agree with/rephrase/expand on some of the above comments:

It seems that a more general solution might be desirable. What if I want to control the placement of `NaN` values as well? What about user-defined special values or types?

Our current (or recent, at least -- I haven't checked lately) float sorting places `NaN` in block 3, negatives in block 1, and positives in block 2. It leaves block 3 untouched, but sorts block 1 by reversed integer-cast and block 2 by forward integer-cast. Could we make a front-end where such a thing could be specified manually? That would make it possible for the user to relocate the `NaN` block or insert a `missing` block, for example. Is there a way this could be expanded to permit the user to specify blocks for other types/values (e.g., `missing`) via predicates for blocking and a `Base.Order.Ordering`s for each block?

Could such a generalization still be made efficient? It seems unlikely, at least for `eltype() isa Union` arrays, due to potential type instability that may persist even after partitioning (our built-in schemes produce homogeneous blocks so can mitigate this, conceivably). And perhaps this is all too ambitious. Personally, I almost never use `missing` (much less other sentinels) so I don't have a horse in this race.

---

If we go for something like the original suggestion in this thread, there's matter of wording. For example, `missingsmallest` vs `missingatfront` -- should we say where a special value should go as a value or as a location? `missingsmallest` would place `missing` at the front for forward sorting and the back for reverse, whereas `missingatfront` would always place it at the front.

**Comment by LilithHafner** [comment]
Yeah, that seems good enough, a package can define a more efficient system if folks want one.
