### ISSUE TITLE
DateTime parsing is too opinionated

### ISSUE THREAD

**Issue by robsmith11** [JuliaLang/julia#50330]
I realize that the most recent ISO standard requires a `T` separator between the date and time, but the reality is most timestamps in the wild still are using a space as the separator, so I think that Julia should be able to handle it by default.

```
julia> parse(Dates.DateTime,"2023-06-05 16:52:17.531")
ERROR: ArgumentError: Invalid DateTime string
```

**Comment by giordano** [comment]
```julia
julia> parse(DateTime, "2023-06-05 16:52:17.531", dateformat"YYYY-mm-dd HH:MM:SS.sss")
2023-06-05T16:52:17.531
```

**Comment by timholy** [comment]
It might be nice to have a mode that "tries hard" using several different formats---while the mode we have now is fantastic if you have to parse a bunch of dates, for a one-off there's a certain amount of effort to craft the `dateformat` string and that's a little annoying. (Maybe it exists, but if so I don't know it.)

**Comment by PallHaraldsson** [comment]
>It might be nice to have a mode that "tries hard" using several different formats

It's a question, which important other date formats should also be supported. I think we could be opinionated and adding only that one exception (since/if it's common, and supported by other software), but only for parsing (we should just output the one T format; strict on output, liberal on input). Some more to consider would be official extensions:

[Since Julia is for science, and those below seem relevent, something to look into supporting]

https://www.loc.gov/standards/datetime/

Compliance
Three conformance levels are defined: level 0, level 1, and level 2. Level 0 specifies features of ISO 8601-1; Levels 1 and 2 specify features described ISO 8601-2.

An implementation must support all of the features listed for Level 0. The vendor must state one of the following levels of support:

Level 0 is supported.
Level 0 is supported, and in addition the following features of levels 1 and 2 are supported (list features).
Level 1 is supported.
Level 1 is supported, and in addition the following features of level 2 are supported (list features).
Level 2 is supported.
Two communication parties that agree to operate according to this specification must suppress, during their communication, any features of ISO 8601-1 that are not included in level 0.
[..]

Level 1
Level 1 of this specification requires support for Level 0 as well as the following features:

Letter-prefixed calendar year
'Y' may be used at the beginning of the date string to signify that the date is a year, when (and only when) the year exceeds four digits, i.e. for years later than 9999 or earlier than -9999.

Example 1             'Y170000002' is the year 170000002
Example 2             'Y-170000002' is the year -170000002

Seasons
The values 21, 22, 23, 24 may be used used to signify ' Spring', 'Summer', 'Autumn', 'Winter', respectively, in place of a month value (01 through 12) for a year-and-month format string.

Example                   2001-21     Spring, 2001
[..]
Negative calendar year
Example 1       ‘-1985’
Note: ISO 8601 Part 1 does not support negative year.

Level 2
Level 2 requires support for Level 1 as well as the following features:

Exponential year
'Y' at the beginning of the string (which indicates "year", as in level 1) may be followed by an integer, followed by 'E' followed by a positive integer. This signifies "times 10 to the power of". Thus 17E8 means "17 times 10 to the eighth power".

Example        ‘Y-17E7’
the calendar year -17*10 to the seventh power= -170000000
[..]
Sub-year groupings
Level 2 extends the season feature of Level 1 to include the following sub-year groupings.

21     Spring (independent of location)
22     Summer (independent of location)
23     Autumn (independent of location)
24     Winter (independent of location)
25     Spring - Northern Hemisphere
26     Summer - Northern Hemisphere
27     Autumn - Northern Hemisphere
28     Winter - Northern Hemisphere
29     Spring - Southern Hemisphere
30     Summer - Southern Hemisphere
31     Autumn - Southern Hemisphere
32     Winter - Southern Hemisphere
33     Quarter 1 (3 months in duration)
34     Quarter 2 (3 months in duration)
35     Quarter 3 (3 months in duration)
36     Quarter 4 (3 months in duration)
37     Quadrimester 1 (4 months in duration)
38     Quadrimester 2 (4 months in duration)
39     Quadrimester 3 (4 months in duration)
40     Semestral 1 (6 months in duration)
41     Semestral 2 (6 months in duration)

**Comment by quinnj** [comment]
"automatic" is an interesting way to phrase it; in Julia, you can define "default" arguments, and that's the case here. If you don't provide a default, we use the 8460 format by default.

I know in data wrangling tools, it's common to have this kind of "automatic" format detection, but that feels like the kind of problem that isn't well-defined enough to live in the Dates stdlib (as opposed to, say, the CSV.jl package having a bunch of auto-detect logic for this).

**Comment by robsmith11** [comment]
I suppose that's fair to keep the base library explicit and strict.

I've been meaning to write my own UInt64-backed datetime library that supports microseconds, so that will be a better place for convenience functions and more flexible parsing.
