### ISSUE TITLE
gcext test is often failing

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#50434]
The gcext test is failing. A quick fix would be to change the `length(errlines) == 0` check to use `isempty(errlines)` instead, which has special printing in Test and would likely quickly reveal the issue.
example: https://buildkite.com/julialang/julia-master/builds/25595#01892862-243e-4599-b390-cf005b815ea4

**Comment by vchuravy** [comment]
Looked briefly into this, definitely a release blocker.
Diogo surmised that we likely broke conservative GC support with the page table changes

**Comment by d-netto** [comment]
5939e2d (from https://github.com/JuliaLang/julia/pull/50137) is the first commit in which gcext is failing.

**Comment by fingolfin** [comment]
I just stumbled over this issue. Yes we noticed in GAP.jl resp Oscar.jl new crashes related to our gcext code, see https://github.com/oscar-system/Oscar.jl/issues/2543

I don't know yet if these are related or a separate issue (nor do
i exclude a possible bug i our code -- although nothing there has changed recently).

CC @benlorenz

**Comment by d-netto** [comment]
Is this reproducible on the latest master?

**Comment by fingolfin** [comment]
I am not sure, the problem with these issues is that we in general have a hard time reproducing them outside of CI (the CI runners have comparatively low memory compared to our dev machines, and exhibit the problems much more frequently).


The last one I am explicitly aware of was 5 days ago, the same day PR #50533 was merged, so *perhaps* that resolved it?

In general it would be great to get a ping when you observe gcext failures, because they almost always affect us, and then we can coordinate testing. If you wish I'll be happy to do the reverse (so we far we usually try to first figure out more about the problem in case it is on our side; but with the recent fast pace of GC changes, maybe it'd be better to notify you immediately? But we don't want to bother you guys unduly...)
