### ISSUE TITLE
Matrix-Vector multiplication in Float16 returns incorrect result if NCOLS>2048

### ISSUE THREAD

**Issue by svilupp** [JuliaLang/julia#50580]
## Summary

I found an issue with matrix-vector multiplication when both are in Float16.
Specifically, if the number of columns exceeds 2048 in a matrix-vector multiplication with `Float16` inputs, it results in incorrect output. Calculation returns at most 2048.

## Steps to Reproduce

You can replicate the issue with the following code:

```julia
N = 2050
# matrix of size (10,N) times vector of size (N)
output = ones(Float16, 10, N) * ones(Float16, N)

# output should be equal to N
exp_output = ones(Float16, 10)*N
exp_output == output # fails!

output[1] |> Float64 # 2048
exp_output[1] |> Float64 # 2050
```

If you run it with N=5000, you'll still get `output[1]==2048`, not 5000.

You can try with smaller numbers or random matrices as well. It will not be truncated to 2048, but it will be more incorrect than eps(Float16) would suggest.
```
N = 2050
r1 = rand(Float16, 10, N)
r2 = rand(Float16, N)
output = r1 * r2
exp_output = sum(r1[1, :] .* r2)
exp_output == output[1]
output[1] |> Float64
exp_output[1] |> Float64
```

## Version Info
> Julia Version 1.11.0-DEV.111
Commit 5eddb816b3 (2023-07-17 18:58 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.5.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 on 6 virtual cores
Environment:
  JULIA_EDITOR = code

## Additional Information

There are no error messages or segfaults associated with this bug. The issue is not related to a specific package.
I've tried on 1.9, 1.10 and master, all give the same result.

## Potential causes

Could it be because of some rounding in the accumulation? `eps(Float16)*2050 ~ 2` 
But that would only explain an imprecise result, not the truncation to 2048 under all circumstances

**Comment by Keno** [comment]
There's nothing matrix multiplication specific here. As you point out, the issue is just that
```
julia> eps(Float16(2048))
Float16(2.0)
```

e.g.
```
julia> x = Float16(1.)
Float16(1.0)

julia> for i = 1:5000
       x += Float16(1.)
       end

julia> x
Float16(2.048e3)
```

`Float16` is not a particularly good computational format for this reason. In general to get Float16 to actually work, you need to perform the intermediate arithmetic in a higher precision format and be careful about the places where you cast back to low precision.

**Comment by stevengj** [comment]
The `sum` function is more accurate here because of [pairwise summation](https://en.wikipedia.org/wiki/Pairwise_summation):
```jl
julia> foldl(+, fill(Float16(1), 5000))
Float16(2.048e3)

julia> sum(fill(Float16(1), 5000))
Float16(5.0e3)
```
In principle, we could change the matmul routines to use pairwise summation for `Float16`, but this would come at a performance cost and of course would not solve all problems with `Float16` inaccuracy.

**Comment by mikmoore** [comment]
I imagine that our `Float16` functions use native Julia implementations? Are those implementations block-based? It wouldn't fully resolve the underflow issue here, but intermediate accumulations of the blocks to local variables (i.e., stack or register locations) and only accumulating them into the output memory after computing the block might slightly reduce the propensity for this particular phenomenon. Or, rather, push the limit a little further at least.

For example, I notice that despite only having 24 bits of mantissa, this problem does not manifest for `Float32` until accumulating 2^29 elements:
```julia
julia> eps(2f0^24)
2.0f0

julia> n = 2^27; only(ones(Float32, 1, n) * ones(Float32, n)) - n
-16.0f0

julia> n = 2^28; only(ones(Float32, 1, n) * ones(Float32, n)) - n
-32.0f0

julia> n = 2^29; only(ones(Float32, 1, n) * ones(Float32, n)) - n
-1.3421773f8
```

But, fundamentally, any scheme will run into precision issues in certain situations.

**Comment by stevengj** [comment]
> For example, I notice that despite only having 24 bits of mantissa, this problem does not manifest for Float32 until accumulating 2^29 elements:

That's just due to the blocking of `Float32` matmuls in optimized BLAS libraries like OpenBLAS, and isn't true in general:
```jl
julia> foldl(+, fill(Float32(1), 2^24))
1.6777216f7

julia> foldl(+, fill(Float32(1), 2^25))
1.6777216f7

julia> foldl(+, fill(Float32(1), 2^26))
1.6777216f7

julia> foldl(+, fill(Float32(1), 2^27))
1.6777216f7
```

**Comment by ctkelley** [comment]
Fixing half precision internally is not, IMHOP, a good idea. You make the operations at least 2x slower and make it hard for those of us who study low-precision arithmetic to get reliable timings and results.

People who play with Float16 need to be warned that things can fail and need to think about how little half precision can resolve. Fixing matmul to do single behind the curtain is not a good solution.

**Comment by giordano** [comment]
I'm missing what's concretely the bug here. Are you just facing the matter of fact that Float16 has low precision or are you observing divergence from IEEE 754 semantics of this number format? Only the latter would be a bug, the former is just how Float16 works and isn't specific to the Julia language. When you work with low precision numbers it's your duty to scale down your problem to remain in a meaningful dynamic range, and again this has nothing to do with julia.

Side note, one way to recover accuracy with low precision floating point numbers is to use stochastic rounding. This can be done with software emulation, which adds some overhead, there's a package doing this in julia, [`StochasticRounding.jl`](https://github.com/milankl/StochasticRounding.jl), or if you can use a processing unit which can do this on hardware you have no performance penalty. I showed such an example at https://discourse.julialang.org/t/fp16-16-and-fp32-16-float-type-in-julia-and-stochastic-rounding/83638/3. Stochastic rounding is a game changer because it makes low precision formats much more useful, if you can still afford some small errors.

**Comment by stevengj** [comment]
I think the question is whether we want to make low-precision computations more accurate, and hence more useful by doing some of the accumulations in a higher precision by default for some common operations (e.g. matmul/matvec, norm, …).  

* Pro: This is relatively easy for us, and incurs almost no computational cost, while it is not easy for end users without rewriting matmul etc.  It extends the range of operations for which you can use `Float16`.
* Con: Adds a little more complexity into Base.  (e.g. we'd add a function like `sumzero(T)`, defaulting to `zero(T)`, to return a zero of the type used for accumulation.)   Might not be clear to users when they can rely on this.

PS. Stochastic rounding won't help in this particular case, because the summation loop is eventually adding values `< eps(sum_so_far)`.

**Comment by giordano** [comment]
> PS. Stochastic rounding won't help in this particular case, because the summation loop is eventually adding values < eps(sum_so_far).

I don't think that's true:

![newplot-1](https://github.com/JuliaLang/julia/assets/765740/477636a5-b533-4ca5-9465-fce4ffd7e985)
```julia
julia> eps(Float16(2000))
Float16(1.0)

julia> eps(Float16(4000))
Float16(2.0)

julia> sum(Float16(0.9) for _ in 1:5000)
Float16(2.048e3)

julia> mean(Float64.(sums_sr))
4499.828

julia> median(sums_sr)
Float16(4.5e3)
```

**Comment by stevengj** [comment]
> We don't do anything to try to "fix" `(1e20 + 1e0) - 1e20` even though the issue is the same.

The issue is not the same there because that sum is ill-conditioned, whereas summing 1's is not.

And for well-conditioned sums the `sum` algorithm *does* try to fix problems with the naive algorithm, by using pairwise summation.

There are lots of other examples of algorithms where we bend over backwards to try to avoid losing precision in intermediate calculations, e.g. `norm` and `hypot`.

And there are *lots* of `Float16` functions that are computed by promoting to `Float32`, doing the calculation, and rounding the result back to `Float16`.  For example, [`hypot`](https://github.com/JuliaLang/julia/blob/0f56da8988366dd60e170932eefca4adb890acff/base/math.jl#L840-L846), [`ldexp`](https://github.com/JuliaLang/julia/blob/0f56da8988366dd60e170932eefca4adb890acff/base/math.jl#L979), [`x^y`](https://github.com/JuliaLang/julia/blob/0f56da8988366dd60e170932eefca4adb890acff/base/math.jl#L1283), [`rem2pi`](https://github.com/JuliaLang/julia/blob/0f56da8988366dd60e170932eefca4adb890acff/base/math.jl#L1464), and [many others](https://github.com/JuliaLang/julia/blob/0f56da8988366dd60e170932eefca4adb890acff/base/math.jl#L1555-L1561).   Just because the user passes `Float16` inputs doesn't mean that we promise to do the calculation inaccurately internally.

If the user passes a `Float16` array, I think we should generally avoid allocating `Float32` arrays of the same size.   But I don't see a problem with doing some scalar intermediate calculations in `Float32` or `Float64`.

**Comment by adienes** [comment]
> There are lots of Float16 functions that are computed by promoting to Float32

I did not know about this. that is really unfortunate....
if a user asks for `Float16`, shouldn't she get `Float16` ?

**Comment by ctkelley** [comment]
Are we promoting to Float32 on Apple M* machines where Float16 has working hardware/software support? That seems very strange.

**Comment by giordano** [comment]
> I did not know about this. that is really unfortunate....

Well, the same happens for Float32 and Float64 in a few other functions: all trigonometric functions are internally implemented by computing kernels in higher precision and then truncating the result back to the desired precision. This technique of doing intermediate operations in higher precision is again not specific to the Julia language.

**Comment by stevengj** [comment]
> I can see the reasoning, but does it still feel like an appropriate choice for something so primitive as `x^y`?

How do you think `x^y` is computed for other floating-point types?  It is *not* by repeated multiplication, or even by repeated squaring, in general.  For example, see that you get different results even in `Float64` from:
```jl
julia> (x, y) = (1.2948417091804099, 12)
(1.2948417091804099, 12)

julia> x^y
22.212639298758184

julia> foldl(*, repeat([x], y), init=1.0)
22.212639298758177

julia> Base.power_by_squaring(x, y)
22.21263929875817
```
The algorithm that Julia uses internally is often not what users naively expect (for good reasons), and may produce different roundoff errors than the procedure the user imagines.

**Comment by stevengj** [comment]
If your argument is that doing the accumulation in `Float32` will be vastly slower than doing it in `Float16`, at least on systems with hardware `Float16` support, I'd like to see benchmark data for that.  Doing a single (non-SIMD) accumulation in a higher precision is usually not a significant performance hit, for example:
```jl
julia> @btime sum($x, init=0.0f0); # accumulate in Float32
  1.142 μs (0 allocations: 0 bytes)

julia> @btime sum($x, init=0.0); # accumulate in Float64
  1.161 μs (0 allocations: 0 bytes)
```

**Comment by stevengj** [comment]
> Here's a better benchmark:

The problem is that `sum(f, x)` uses SIMD, which is why you're getting the 2x slowdown for `Float64`.   That's why I used `init`.  You can see the same thing with `mapfoldl`:
```jl
julia> @btime mapfoldl(Float32, +, $x);
  1.141 μs (0 allocations: 0 bytes)

julia> @btime mapfoldl(Float64, +, $x);
  1.195 μs (0 allocations: 0 bytes)
```
That's why I specified that there isn't a significant slowdown for scalar **non-SIMD** accumulation.

**Comment by giordano** [comment]
> If your argument is that doing the matmul accumulation in Float32 will be vastly slower than doing it in Float16, at least on systems with hardware Float16 support, that would be a persuasive point — but I'd like to see benchmark data for that. 

The IPU has native support only for half and single precision floating point numbers, while double precision is implemented in software and is horribly slow, so these intermediate operations in higher precision _are_ a significant performance hit for Float32 (we're speaking of orders of magnitude, if functions don't crash completely because of missing implementations of f64 intrinsics) 🥲 But at least when targeting this processor we can override methods in Base with llvm intrinsics, this is for example what I'm doing for the trigonometric functions. I think also GPUs typically have similar limitations? For more general-purpose CPUs this is usually not a concern, as shown by your benchmark.

**Comment by svilupp** [comment]
Thank you for your comments. 
I'll close the issue, as this is clearly not a bug, merely a lack of knowledge on my part.

I was aware of the lack of precision of F16 and how it's implemented in bits, but haven't grasped its implications. I always assumed that the gap to the following "representable" number is constant at `eps(Float16)`. The above "bug" was shocking because of the truncation to half the value (ie, N=5000 giving 2048.0)

Now, I appreciate that the gap depends on the number itself `eps(Float16(2048))=2.0`, so when we reach `Float16(2048)`, we cannot effectively increment by anything smaller than 1.0 (ie, half of `eps(Float16(2048))`

***
Given that Float16 is becoming increasingly popular with LLMs and it was even called out in the official Julia 1.9 highlights blog (native support), should the above pitfall be explicitly called out in the docs?

Would it make sense to add a column "Next representable number after 10000" in the [table of primitive types](https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/). That would make it super practical and easy to understand.

**Comment by oscardssmith** [comment]
I think we should probably add 2 columns for floating point numbers: maximal value and maximum consecutive integer.
