### ISSUE TITLE
Feature request: Computation of complex numbers by default

### ISSUE THREAD

**Issue by ay111** [JuliaLang/julia#50664]
Julia returns domain error if a computation result is a complex number. For instance (-1)^0.5 returns domain error instead of complex number. Please enable complex number computation by default. Some of my codes cannot run in Julia but working smoothly and faster on Matlab because they have some complex numbers and require many iterations

**Comment by oscardssmith** [comment]
Julia is not at this stage of development.

**Comment by timholy** [comment]
Just use `(-1+0im)^0.5`

**Comment by oscardssmith** [comment]
(or better would be `sqrt(-1+0im)`

**Comment by ay111** [comment]
Ok. That means for now Julia is not suitable for some computations.

Thanks.
Regards.

**Comment by jakobnissen** [comment]
@ay111 To expand a little more on why it is not a good idea to do this, consider: What is the return type of `^(::Int, ::Float64)`? Currently, it's always just `Float64`, but with your proposal it would be `Union{Float64, Complex{Float64}}`. If the downstream result needs a `Float64`, the compiler would now have to start checking after every single `^` computation if the result is a `Float64` or not. This would slow down all code that uses exponentiation.

Furthermore, it's pretty easy to make your code work anyway. Instead of `a^b`, you could do `complex(a)^b` so that the result is always `Complex{Float64}`. If you don't mind the result being a `Union` type, you could use the following function instead of `^`:
```julia
my_sqrt(a, b::Real) = b < zero(b) ? complex(a)^b : a^b
```

**Comment by timholy** [comment]
> That means for now Julia is not suitable for some computations.

No. It means that unlike some other languages, you have complete control over what outcome you want.

**Comment by ay111** [comment]
Thanks. I have found a way around it with SymPy.jl. For example,
using SymPy
a = Sym(-1)
sqrt(a) gives the complex root of (-1) as desired.
