### ISSUE TITLE
@threadcall adopts the libuv threads

### ISSUE THREAD

**Issue by gbaraldi** [JuliaLang/julia#50782]
This seems like a bad idea and is also what causes the ccall tests to fail.

**Comment by vchuravy** [comment]
Actually I don't it is all that bad of an ideal I was toying with it actually xD

**Comment by gbaraldi** [comment]
This thread never enters a safepoint 😄

**Comment by gbaraldi** [comment]
@vtjnash suggested to me that we should reinplement `@threadcall` with `@spawn`, which would then actually have correct behaviour. It wouldn't be multithreaded if the user didn't start julia with threads, which is a slight change of behaviour.

**Comment by vchuravy** [comment]
The thread should transition to GC safe, after executing the cfunction?

The reason why one would use `@threadcall` is to not pick Julia's worker threads. So implementing it with `@spawn` seems to be to big of a semantics divergence. We could manage the threadpool ourselves instead of using libuv pool.
