### ISSUE TITLE
searchsorted has an errant `@inbounds`

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#51176]
This should error:
```julia
julia> searchsorted([1,2], 2, 1, 10, Base.Order.ForwardOrdering())
2:3
```
When we run Julia with `check-bounds = yes` we get correct behaviour:
```julia
julia> searchsorted([1,2], 2, 1, 10, Base.Order.ForwardOrdering())
ERROR: BoundsError: attempt to access 2-element Vector{Int64} at index [5]
Stacktrace:
 [1] getindex
   @ ./essentials.jl:13 [inlined]
 [2] searchsorted(v::Vector{Int64}, x::Int64, ilo::Int64, ihi::Int64, o::Base.Order.ForwardOrdering)
   @ Base.Sort ./sort.jl:207
 [3] top-level scope
   @ REPL[1]:1
```
The problem applies to other searchsorted variants.

There should probably be a check on whether `hi` exceeds the length of a vector in

https://github.com/JuliaLang/julia/blob/8e14322b5aa344639dd86bf9eabb84afe831fcba/base/sort.jl#L195

**Comment by LilithHafner** [comment]
This is expected behavior. `searchsorted([1,2], 2, 1, 10, Base.Order.ForwardOrdering())` is not part of the public API (because it is not mentioned in the documentation). You have called an internal method which assumes its arguments have already been boundschecked. It's unfortunate that this internal method shares the same function as the public `searchsorted([1,2], 2)`.

**Comment by jishnub** [comment]
> This is expected behavior

Ideally, this shouldn't be the expected behavior, and the compiler, being able to prove that the indices are within bounds, should use inbounds without an explicit annotation
