### ISSUE TITLE
Tab expansion of NamedTuple fails on 1.10.0-beta2

### ISSUE THREAD

**Issue by jaakkor2** [JuliaLang/julia#51194]
This worked on 1.9, does not on 1.10.0-beta2.

`A = (; foo=2, bar=3)`, and then type `A.foo + A.b<TAB>`.  `bar` does not get expanded.

**Comment by oscardssmith** [comment]
Interestingly for regular structs (e.g. complex numbers) this still works.

**Comment by oscardssmith** [comment]
Pretty sure the bisect will find https://github.com/JuliaLang/julia/pull/49206/ but would be good to be sure.

**Comment by Liozou** [comment]
Fix is up at https://github.com/JuliaLang/julia/pull/51366. The symptoms are a bit misleading but this issue actually has nothing to do with `NamedTuple` vs regular structs, it is only due to the completion of arguments of infix operator (the `+` here) which has been buggy since https://github.com/JuliaLang/julia/pull/49294.
