### ISSUE TITLE
Avoid `count(itr)` confusion

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#51212]
```jl
  count([f=identity,] itr; init=0) -> Integer
```

C++ has a lengthlike function `count` for getting the length of iterators and another function `count_if` that takes a predicate. 

In Julia, `count(itr)` looks like it counts the values in `itr`, but it actually only counts the `true` ones. Having the default `f` be `identity` rather than `Returns(true)` means `count(itr)` does the nonobvious thing. 

I propose deprecating `count(itr)` (without `f`) to avoid confusion.

**Comment by barucden** [comment]
I see your example from C++, but don't you think that Julia is pretty consistent in using `length` for getting the length of an object? Or do you see people making the mistake of using `count` instead of `length` to get the number of elements?

I think it is useful to have a function that counts the number of `true` elements in a collection.

**Comment by JeffBezanson** [comment]
I don't think it is worth a deprecation for this. Doing an O(n) length computation only makes sense for iterators with fixed (but unknown) length that are also restartable, or in cases where you only need the length of an iterator and nothing else. I think that's rare enough that I'm not too worried about it. To be clear this suggestion is reasonable I just don't think it's worth deprecating at this stage.
