### ISSUE TITLE
Pkg/REPL excision causes precompilation when using custom DEPOT_PATH

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#51439]
MWE:

```
❯ wget https://julialangnightlies-s3.julialang.org/bin/linux/x86_64/julia-latest-linux-x86_64.tar.gz
❯ tar -xvf julia-latest-linux-x86_64.tar.gz
❯ cd julia-*
❯ export JULIA_DEPOT_PATH=$(mktemp -d)

❯ ./bin/julia
┌ Info: Precompiling InteractiveUtils [b77e0a4c-d291-57a0-90e8-8db25a27a240]
└ @ Base loading.jl:2351
┌ Info: Precompiling REPL [3fa0cd96-eef1-5676-8a61-b3b8758bbffb]
└ @ Base loading.jl:2351
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-DEV.542 (2023-09-23)
 _/ |\__'_|_|_|\__'_|  |  Commit 3c0d4802fad (1 day old master)
|__/                   |

julia> using Pkg
┌ Info: Precompiling Pkg [44cfe95a-1eb2-52ea-b672-e2afdf69b78f]
└ @ Base loading.jl:2351
[ Info: We haven't cleaned this depot up for a bit, running Pkg.gc()...
```

~This is probably the reason PkgEval times have regressed from 12h -> 15h -> 20h (presumably first from the REPL removal, then the Pkg removal).~

cc @vchuravy

**Comment by maleadt** [comment]
After some discussion with @KristofferC, I'd argue that setting `JULIA_DEPOT_PATH` should still result in the bundled depot being searched. Although it could be argued you need to use `JULIA_DEPOT_PATH=/foo::` for that, I think that's unexpected, and it also results in the default environment still being used (which is often what you want to avoid by setting the depot path).

**Comment by vchuravy** [comment]
> and it also results in the default environment still being used

Sounds like you want to set `JULIA_LOAD_PATH` instead? But the default environment should only be reachable in interactive mode (iirc).

But yeah our documentation on this isn't the best but `JULIA_DEPOT_PATH=/foo:` is needed, or you inserting the stdlib depot. The issue is that we also need a way to remove the stdlib depot from the search path.

**Comment by maleadt** [comment]
Hm, looks like this was the case already on 1.10 too, with e.g. the Test stdlib.

I wonder if we should change the semantics of `JULIA_DEPOT_PATH` to always include the bundled depot? Would there be any reason not to use those?

**Comment by DilumAluthge** [comment]
By "bundled depot", you mean the place where stdlibs live?

Personally, in my opinion, if I set e.g. `JULIA_DEPOT_PATH="/foo"`, I would only want `/foo` to be used.

IMO it seems very reasonable to require people to set `JULIA_DEPOT_PATH=/foo:` instead.

It sounds like the issue here is that `JULIA_DEPOT_PATH=/foo:` will include not only the bundled depot but also `~/.julia`, right? So what if we introduce a depot alias `@stdlib` (analogous to how we do for the load path)?

So then the user can do `JULIA_DEPOT_PATH=/foo:@stdlib`, and this will use `/foo` and the bundled depot, but it will NOT use `~/.julia`.

**Comment by maleadt** [comment]
> Personally, in my opinion, if I set e.g. `JULIA_DEPOT_PATH="/foo"`, I would only want `/foo` to be used.

What would be the use case for that? We always use the bundled source of the stdlibs anyways, so it seems sensible to use the bundled cache as well.
