### ISSUE TITLE
docs for `sort` refer to `Base.copymutable`, but the latter is not in the manual

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#51932]
> Uses `Base.copymutable` to support immutable collections and iterables.

If `Base.copymutable` is an internal function, why does the `sort` doc refer to it? Should `Base.copymutable` be made public?

**Comment by nsajko** [comment]
FTR, if it does get made public, it probably needs a better doc string, because I'm not sure how is one supposed to use it and/or overload it by reading the doc string.

Also, FWIW, `Base.copymutable` is used already in StaticArrays.

**Comment by LilithHafner** [comment]
In 1.9 the docstring for `sort` said

> Variant of `sort!` that returns a sorted copy of `v` leaving `v` itself unmodified.

So it's not too late to keep `copymutable` internal. That said, it seems like sensible functionality to make public.

Also, the new docstring for `sort!` is objectively false for tuples because `copymutable` returns a Vector when passed a tuple and `sort(::NTuple)` returns an `NTuple`.
