### ISSUE TITLE
Julia 1.11.0-DEV (`Memory` PR) breaks SymbolServer precompilation

### ISSUE THREAD

**Issue by George9000** [JuliaLang/julia#52021]
[SymbolServer.jl](https://github.com/julia-vscode/SymbolServer.jl) precompilation broke on master. Error [output](https://gist.github.com/George9000/bcca45f45b4a779bca8a876d1d102b11). Issue bisected down to 909bceae.

<details>
<summary>versioninfo</summary>

```
julia> versioninfo()
Julia Version 1.11.0-DEV.753
Commit 909bceae8a (2023-10-27 14:41 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.6.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 5 on 8 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_EDITOR = Emacs
  JULIA_PKG_DEVDIR = /Users/foo/Documents/julia/dev
```
  
</details>

**Comment by oscardssmith** [comment]
That's a very ugly error message. I believe the problem comes from the fact that you are trying to do things with the core `array` intrinsics (see https://github.com/julia-vscode/SymbolServer.jl/blob/f39b9d26352f2e1149180061dad231232f8d02a7/src/symbols.jl#L527) and those mostly no longer exist. What is this code actually trying to do?

**Comment by George9000** [comment]
I will loop in the SymbolServer developers. I use emacs as my IDE for Julia and use the [julia tree sitter mode](https://github.com/ronisbr/julia-ts-mode). That requires [lsp-julia](https://github.com/gdkrmr/lsp-julia) which needs the SymbolServer and LanguageServer packages.

**Comment by Liozou** [comment]
The issue stemming from the `Memory` PR was already fixed downstream at https://github.com/julia-vscode/SymbolServer.jl/pull/276 (it just needs a new release) but as you show in your second stacktrace, what is currently broken on SymbolServer#master is due to https://github.com/JuliaLang/julia/pull/51878#issuecomment-1784769226 so let's make this particular issue track that problem instead.
