### ISSUE TITLE
kwarg with a UInt type signature causes a "MethodError"

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#52179]
Julia Version 1.10.0-rc1

```
julia> f(x; i::Int=0) = i
f (generic function with 1 method)

julia> f(1)
0

julia> f(x; i::UInt=0) = i
f (generic function with 1 method)

julia> f(1)
ERROR: MethodError: no method matching var"#f#5"(::Int64, ::typeof(f), ::Int64)

Closest candidates are:
  var"#f#5"(::UInt64, ::typeof(f), ::Any)
   @ Main REPL[26]:1

Stacktrace:
 [1] f(x::Int64)
   @ Main .\REPL[26]:1
 [2] top-level scope
   @ REPL[27]:1
```

**Comment by oscardssmith** [comment]
This isn't a bug. julia doesn't dispatch on kwargs.

**Comment by joa-quim** [comment]
How come it's not a bug? I'm not expecting it to dispatch on kwargs, just to limit what's possible to pass.
```
julia> f(x; i::UInt=0) = x
f (generic function with 1 method)

julia> f(1)
ERROR: MethodError: no method matching var"#f#6"(::Int64, ::typeof(f), ::Int64)

Closest candidates are:
  var"#f#6"(::UInt64, ::typeof(f), ::Any)
   @ Main REPL[29]:1
```

**Comment by joa-quim** [comment]
OK, in the message I got by mail this part was not in `The problem is that 0 is not a UInt. f(x; i::UInt=UInt(0)) = i works.`
Still find this behavior very contra-intuitive and very difficult to debug.

**Comment by oscardssmith** [comment]
it's slightly unintuitive and possibly should give a better error message, but this is intended behavior. The root of the issue can be seen with `f(i::UInt=0) = i` and is that default arguments are not converted before being passed into functions. This is an intentional decision (because if you have multiple methods, which convert should you use), and it would be fairly weird to make kwargs or default args be an exception to the rule here.
