### ISSUE TITLE
incremental precompile warning turned into error: breaking?

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#52213]
Tried out 1.10rc for a bit recently, and got this error a few times:
`ERROR: LoadError: Method overwriting is not permitted during Module precompile.`
As I understand, this error was added deliberately, which really surprised me: it's basically the definition of a breaking change, explicitly making code that worked fine before to error now.

In previous versions, this was a warning that only appeared during precompilation (so users rarely even saw it), and it didn't really indicate that the code uses some internals and could break after updating Julia:
```
│  WARNING: Method definition <...> overwritten in module <...>.
│    ** incremental compilation may be fatally broken for this module **
```
I even found a discourse thread (https://discourse.julialang.org/t/what-is-incremental-compilation-and-what-does-it-mean-for-it-to-be-broken/100956) where Tim Holy directly states that everything is supposed to work with this warning, just with slower compilation/loading/invalidations.

So, should this breaking change be reverted?
And, probably, the warning text made cleaner: I saw it several times, but never had an idea what "incremental compilation" means and why would I be worried about it. Looking at discussions, I'm not alone in this.

See a recent slack thread https://julialang.slack.com/archives/C67910KEH/p1699434379137429 for more discussion and examples.

**Comment by PallHaraldsson** [comment]
>where Tim Holy directly states that everything is supposed to work with this warning

Does he? It seems to me he's saying something is actually "fatally broken"? I.e. not good for the ecosystem if you change a method from another package (maybe not fatal in itself, until the ecosystem grow more, or more packages composed), but depending on the order of how you do it, for different packages trying to modify the same, is "broken".

I suppose if you do redefine in a certain order it COULD be ok, if you're ok with that, and the order is correct, something you're ok with. And changing this to an ERROR is then a breaking change. But I'm not sure most users are ok with this, or know the issue? E.g. in his example if only B or C is used, then ok, but would users for sure test the ecosystem for B AND C, or the other order C AND B, and would be ok with both the different conclusion? Must not either be wrong, and you might even have a combinatorial explosion of possible orders, and only 1 (or few?) ok. I suppose it best to let this error.

It seems to me the WARNING SHOULD have been a sign you or the ecosystem needed to change, and now the ERROR is forcing it. You always have the option of using the older Julia version where this "worked" in some sense, maybe with wrong answer?! or I mean at least not what you though would happen?

**Comment by vtjnash** [comment]
Warnings are printed when something should not be relied upon working, as it is known to be broken. Ignoring warnings is buyer-beware. But it was pointed out that this lacks a NEWS entry, since changing warning to error usually doesn't seem to merit one, but it might in this case

Also worth pointing out in that NEWS that this is only a problem if you want to incrementally compile code. If you avoid using `module` & the precompilation system (e.g. `__precompile__(false)`), then this is not a problem.

**Comment by PallHaraldsson** [comment]
He does write:
>You can only overwrite a method if you’re committing type piracy [..]. Hence this warning only happens if you’re committing type piracy.

So if you don't, nor your packages, then you're ok... yes, it's not unheard of in the ecosystem, but it IS bad?!

He's saying any order will compile to something, but not the same thing. So it's deterministic, and COULD be allowed. I'm just not sure most users realize. When I have e.g. a Python package, implemented in C, I think I can import them in any order, and all will work the same, since there's no possibility of the C code being changed after/when importing.

For Python code, or the wrapper code of that C code, that might actually not be true, since Python is very dynamic. Though I'm not sure.

Is there some good non-breaking way out of this? I'm also thinking, one package may need a certain version, e.g. latest, and another might not be able to use that version, so preventing installing two packages at the same time. Might we want to allow that different packages can depend on the same package, just different versions? If we allow that, then we make this headache even more complex, OS should people be able to change and get new versions, and all valid? It might still be a warning if you do something such unusual...

**Comment by vtjnash** [comment]
>  Does this mean that deprecated functions can just be removed in the next minor Julia version

If warnings have been present in all minor releases, yes, since there hasn't been a version in which it was part of the API. Otherwise, semver says it would be a major version change.

The workaround is `__precompile__(false)`

**Comment by BioTurboNick** [comment]
I concur with @aplavin - it may make sense to prevent a package developer from doing this going forward, but it doesn't make sense to prevent an end user from relying on an already existing package/version from being able to use that package going forward.

From both perspectives, I never knew what the error actually *meant*, what impact I was really being warned about. Everything seemed to work fine. What specifically was broken that I might care about? I couldn't tell you.

I would highly recommend first making the _meaning_ of the warning more clear before taking a further step. And when that next step is taken, it should make sure that older packages don't need to be updated to continue to be used on future Julia versions. Maybe it's just added as a check for new General registrations. Maybe there's a switch for an end user to turn off.

**Comment by vtjnash** [comment]
What might happen is that it might segfault occasionally, which is what it started doing very often when we decided to change the warning to an error

**Comment by PallHaraldsson** [comment]
We shouldn't warn (or error) where there's no actual problem.

It seems to me (incremental) compilation is a red herring. It's the redefinition that's the problem?! This would also be a problem with the interpreter, or without precompilation? At some point you must compile (or interpret) and if you precompile, then potentially you recompile. The only way out of that is not allowing redefinition, i.e. type piracy? But it's also very useful in an interactive system if you know what you're doing... or annoying if you couldn't redefine e.g. functions or structs... It seems there will always be a tension, and that for packages you may want to disallow more changes.

> I typically don't care how the code is compiled. So, how to tell Julia that I don't explicitly want "incremental" compilation for installed packages that throw this error?

You mean get similar to what C packages in Python give you? They are not generic. I think we could disallow recompilation for existing types (like there), but allow adding new types, and they would work with those packages, note that's addition (and implied compiled code), not a change, thus not type piracy, still more compilation. Recompilation would be the wrong word for that.

**Comment by KristofferC** [comment]
You can do the method overwrite in `__init__`. Doing it at precompilation time doesn't make sense I think.

**Comment by KristofferC** [comment]
> The incremental compilation one doesn't appear in earlier 1.x versions:

I think that is because `Pkg.precompile` swallowed some output here. If you precompile it with `using` it should be visible.

**Comment by KristofferC** [comment]
> I'm not arguing with this at all, just please let me know if there's any workaround on the user side (without changing package code). 

I think `--compiled-modules=no` would work around it.
