### ISSUE TITLE
Replace && and || with and and or

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaLang/julia#5238]
As discussed at length in #5187, many of us would prefer that `&&` be written as `and` and `||` be written as `or`.

**Comment by jakebolewski** [comment]
@johnmyleswhite this issue be closed?  I think the ship has sailed on this one.

**Comment by johnmyleswhite** [comment]
:(

**Comment by jakebolewski** [comment]
short circuit that frowny face

**Comment by StefanKarpinski** [comment]
I think we should still consider this. A lot of people seem to dislike using `&&` and `||` the way we're using them and would prefer `and` and `or`. There's also the issue of precedence, which makes `&&` and `||` somewhat awkward. We could move to a future where `&&` and `||` require both operands to be boolean and `and` and `or` do what `&&` and `||` currently do but with lower precedence so that you can write `x == nothing and x = 0` and such. Either that or introduce a different one-line conditional syntax like `x = 0 if x == nothing`.

**Comment by ScottPJones** [comment]
The last syntax `x = 0 if x == nothing` has some of the problems IMO that the suggestion in https://groups.google.com/forum/#!topic/julia-dev/cnmLcNg8h0Q does.
Are the two following options so horrible that Julia needs post-conditionals?
```julia
    if x == nothing ; x = 0 ; end
```
or
```julia
   x == nothing && (x = 0)
```
That said, just as I wouldn't mind seeing a `repeat ; expr(s) ; until cond` construct in Julia (but can live without it), I don't see anything wrong with having `and` and `or` added to Julia.
They do seem to fit in better with julia syntax than using the borrowed from C `&&` and `||`.

**Comment by Sacha0** [comment]
> I think we should still consider this.

+1

**Comment by jpiitula** [comment]
I was surprised by assignment being lower precedence than `||`, so I came in search of previous discussion and found this issue. It's not a big deal, but those parentheses do look out of place to me. It took me a while (several seconds, I think, and a test in REPL) to find out which assignment location was invalid. - The error message indicated the line past the end of the function definition.
```julia
isempty(o) || (m.over[s][NULL] = o)
```
In contrast, the parentheses in `cond = (f() && g())` look all right to me. I think I would use them anyway.

For what it's worth, I would also prefer `and` and `or`.

**Comment by p-i-** [comment]
+1 from me too.  

Response is almost unanimously positive in favour of `and` etc.  I count two opinions against, one indifferent, a couple unspecified and everyone else (15 or more) in favour.

One argument against (more difficult to read) I think is incorrect. The argument is that `foo and bar` it Is more difficult to read than `foo && bar` on account of 3 words vs word SYMBOL word. However everyone is using syntax highlighting, and in this case the reverse happens.  `and` is coloured as a keyword, so `a<1 and b>3` will actually colour in favour of visually splitting up the left and right subexpressions, whereas `a<1 && b>3` all three operators will be the same colour, cue potential operator-precedence-head-scratching.

An argument _for_ that hasn't yet been presented is that there is an elegant consistency to boolean operators being words, as the result of the operation is either `true` or `false`, i.e. also a word.  So it's very easy for a beginner to memorise `&` vs `and` for bitwise versus logical. It's much more difficult to memorise `&` vs `&&`, as it appears an arbitrary assignation. Guaranteed beginners will be using `&` incorrectly, as `&` conveys the word `and` in English. This might cause precedence bugs(?).

Another possible argument _for_ would be that the brain naturally parses {BUNCH OF SYMBOLS} word {BUNCH OF SYMBOLS}.

Why not just switch? Now is always the best time to do it, it is never going to be easier than now.  It's not exactly difficult to fix code that currently uses &&.

Have `and` `or` `not` `xor` maybe `nand` just for completeness??  I don't mind the idea of keeping `!`. Let the programmer choose when to use which. Nothing wrong with that!  Having said, `!` already has a use in `foo!` style functions, so there is some "minimise symbol reuse" argument.

**Comment by Ismael-VC** [comment]
@StefanKarpinski there seems to be consensus in favor dating back from 2013, I could try to implement this, but I'm worried if this will be considered at all, since this issue hasn't been closed I would assume this is still open for discussion? Using this words instead of symbols will go nicely with `isa` being an infix operator also, same as with `true`, `false`, `end`, etc. It seems more consistent and readable this way.

**Comment by nickeubank** [comment]
+1

**Comment by femtotrader** [comment]
Supporting `not` keyword could also improve code readability.

**Comment by martinholters** [comment]
Should we deprecate/forbid use of `and` and `or` (and possibly `not`) in 0.7/1.0, respectively, to be able to add these later on in case we decide to indeed like them?

**Comment by StefanKarpinski** [comment]
I'd be ok with that. I bet @JeffBezanson is against, but we if we disallow now we can always change our minds later and allow it, whereas we can't go in the other direction. It might also be helpful to be able to give a simple "Use `&&` instead of `and`" error message to users who try Python-style operators.

**Comment by nickeubank** [comment]
I think that'd be great!

**Comment by martinholters** [comment]
Reopening and adding to milestone to make sure we don't forget.

**Comment by Ismael-VC** [comment]
I don't understand the intent of the milestone, we are going to add `and` and `or`? we are reconsidering it? looking for another use of this? Or you mean you are going to add deprecation like warnings, so people coming from Python know to use `&&` instead of `and`?

I had https://github.com/JuliaLang/julia/pull/19788 in which they were aliases, but I can change that to replace them.

**Comment by martinholters** [comment]
The milestone should mean: Reach a decision. Or, if we cannot reach a decision in time, deprecate any use of `and` and `or` so that we can postpone the decision without risking to break anyones code later on.

**Comment by nickeubank** [comment]
I understand that given aspiration to freeze code in a few weeks it may be to late to re-open this can of worms now (and I appreciate the idea of adding depreciations to leave door open for the future), but one thought:

When this first came up for discussion (2013), I think the Julia community was primarily developers -- people with strong CS backgrounds who were more than used to using `&&` and `||`. I _suspect_ that the people who might appreciate `and` and `or` most are applied users who aren't as comfortable with ascii salads and who have yet to spend enough time in older languages to become entirely used to `&&` and `||`. It might be interested to see how people felt about this if we polled current Julia users (especially if we brought it up on discourse where more non-developers are likely to see it).

**Comment by StefanKarpinski** [comment]
What's been proposed is reserving the `and`, `or` and `not` syntax. If we do that, we can add these as operators at any point in the 1.x timeline. No further discussion is required for now.

**Comment by ararslan** [comment]
I'd be fine with parsing these as permanent syntax errors, as we do with `**`. But I'm still very, *very* against giving them any kind of meaning otherwise.

**Comment by StefanKarpinski** [comment]
To be clear: this gets done if someone does it.

**Comment by Ismael-VC** [comment]
Thanks for the clarification! :D

**Comment by TotalVerb** [comment]
It seems very silly to me to bother parsing them and prohibiting other use, and nevertheless make it a syntax error. I think most people would rather not have situation where `and` and `or` are reserved words (i.e. not usable in contexts like `@stackeval 1 0 and 1 or`) yet do nothing useful.

**Comment by ararslan** [comment]
We've already decided not to parse them as aliases, that's why the PR was closed. So +1 for not parsing them at all.

At the risk of rehashing this discussion which has been had ad nauseum, I'll note that regarding C and Ruby, using `and` and `or` in C is very uncommon in my experience, and the most common Ruby style guides require `&&` and `||` instead of `and` and `or`.

**Comment by nickeubank** [comment]
IMHO: seems like the original debates were rather divided, and adding this protection simply leaves space for the community to revisit it in the future it they'd like.

**Comment by JeffBezanson** [comment]
I don't have any idea why this was reopened.

**Comment by Ismael-VC** [comment]
A Julia dialect with syntactic features like this one could be done using JuliaParser.jl easily, once the internal and meta-programming APIs stabilize.

**Comment by martinholters** [comment]
For those coming to this issue without having followed what has happened: Although the idea of using `and` and `or` gathered a fair amount of support *), the first PR to approach the issue - #19788 - mainly led to an inconclusive discussion of whether `and` and `or` should be direct replacements for `&&` and `||` or should have slightly different semantics, e.g. with regards to precedence, but just making them aliases was deemed unwanted. PR #24965 would have reserved the keywords (along with `not`), to allow giving them a meaning during the 1.x cycle. However, discussion during a triage call resulted in disapproval, so the earliest point at which this could be reconsidered is for 2.0. (And one would probably need to make a really compelling case for the change to happen then.)

*) It seems as if the proposed change is less popular with more influential/"core" developers, so just looking at the number of 👍s may be misleading, though.

I hope I didn't over-simplify and got things decently right. Apologies if I didn't.

**Comment by ararslan** [comment]
> so the earliest point at which this could be reconsidered is for 2.0. (And one would probably need to make a really compelling case for the change to happen then.)

I don't see why it would ever happen if we've decided multiple times now not to do it. I hope we can avoid digging this issue up again for every major release.

**Comment by holocronweaver** [comment]
If Julia sticks around long enough to compete with Python, I can guarantee this will come up more and more. Many Python users don't want to return to C syntax. It's one of the many reasons Python is so popular: easy to learn, addicting to use, you won't want to go back the old way of doing things.

New language designers often claim they want user-friendly syntax, yet they tend to get lost in fancy features only a tiny subset of users will ever want or use, while overlooking simple tweaks that could drive adoption.

Case in point: [bizarre Unicode operators are supported]( https://github.com/JuliaLang/julia/pull/24404), but not natural language `and` and `or`.

**Comment by nickeubank** [comment]
I recognize this probably a dead issue, but in reply to @TomKellyGenetics, I would suggest that IMHO many of us would argue R qualifies as "older" and it not particularly user friendly... And while I agree that with beginners, `&&` operators is  "not what they struggled with", I do think most student's I've taught find english language operators (`and`, `or`) more familiar and readable whether they are Python users or not.

**Comment by ararslan** [comment]
This issue has been resolved; `and` and `or` are allowed as operators and we will continue to use `&&` and `||` for control flow. I'm not sure why this is still being discussed.

**Comment by JeffBezanson** [comment]
There is a tendency to over-rate the importance of superficial syntax issues, since they are highly visible, easy to discuss, and their implications are usually clear. In another sphere, a language is considered unusable unless code blocks are surrounded by curly braces, in which case both julia and python are beyond the pale.

I think it's debatable whether `a and b` is indeed more readable than `a && b`. `&&` stands out more. The fact that `||` and `&&` are the same length can also lead to nicer formatting. One of the reasons operator symbols like `a = b` and `a + b` work so well is that they add visual structure over something like `set a to b`. `a[i]` or `element i of a`?

> you won't want to go back the old way of doing things.

To me, the old way of doing things is manual memory management and weak support for polymorphism, not the spelling of `&&`.

**Comment by martinholters** [comment]
#24965 ?

**Comment by holocronweaver** [comment]
Ah, missed that, thanks! I guess not reserving keywords doesn't prevent supporting these keywords in the future.

**Comment by vlad1777d** [comment]
Sorry, read all discussion, but still didn't got it, how can I use `and`, `or` in Julia now ?
