### ISSUE TITLE
Pair to Tuple conversion is unstable

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#52636]
Converting a `Pair` to a `Tuple` should fundamentally be type-stable, but for some reason it isn't:
```julia
julia> Tuple(1=>"2")
(1, "2")

julia> @code_warntype Tuple(1=>"2")
MethodInstance for Tuple(::Pair{Int64, String})
  from (::Type{T})(itr) where T<:Tuple @ Base tuple.jl:369
Static Parameters
  T = Tuple
Arguments
  #self#::Type{Tuple}
  itr::Pair{Int64, String}
Body::Tuple{Vararg{Union{Int64, String}}}
1 ─ %1 = Base._totuple($(Expr(:static_parameter, 1)), itr)::Tuple{Vararg{Union{Int64, String}}}
└──      return %1
```
The tuple conversion machinery is quite involved, so I don't readily see where the issue lies exactly.

This is the same for all julia versions, and for both homogeneous and heterogeneous pairs.

**Comment by KristofferC** [comment]
Maybe easiest to just add a constructor for `Pair` explicitly?

**Comment by jakobnissen** [comment]
`Tuple(x)` is implemented recursively with `to_tuple`. There is a comment that the recursion can cause inference to give up.
I don't know how, but since the length of `Pair` is compile-time constant, it should be achievable to make it infer. Actually, it should be possible to make `Tuple(x)` infer for any compile-time known length iterator.
That could be a useful PR to make.

**Comment by nsajko** [comment]
> `Tuple(x)` is implemented recursively with `to_tuple`.

Actually, no: the recursion is only for (small-enough) concrete `<:Tuple` types, the UnionAll `Tuple` itself is implemented with `collect`, except for certain special cases. The new PR just adds a `Pair` method to these special cases.
