### ISSUE TITLE
Source button of SparseArrays docstrings redirects to a 404 page not found.

### ISSUE THREAD

**Issue by jam-khan** [JuliaLang/julia#52891]
https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.qr

Under Linear Algebra.qr **Examples,** there is a **source** button and it redirects to a 404 page not found.

**Comment by giordano** [comment]
More generally, that's the case for all docstrings of the SparseArrays.jl stdlib: https://docs.julialang.org/en/v1.10.0/stdlib/SparseArrays/ because that's maintained in a different repository: https://github.com/JuliaSparse/SparseArrays.jl

**Comment by jam-khan** [comment]
In that case, I am thinking of fixing it by adding hard links to the corresponding JuliaSparse Repo code, but I am not sure if it is the best solution. Is there a better way to solve this?

**Comment by inkydragon** [comment]
> Is there a better way to solve this?

Maybe just add a line of regular expression to replace the URL here.

https://github.com/JuliaLang/julia/blob/4d670fbd8bf6d85ced39fb549c199b58d482c6bd/doc/make.jl#L386-L410

**Comment by LilithHafner** [comment]
Duplicate of https://github.com/JuliaLang/julia/issues/50035, fixed by https://github.com/JuliaLang/julia/pull/51375 though @mortenpi seems to have a better long term solution by fixing this at the Documenter.jl level.

**Comment by giordano** [comment]
@LilithHafner I don't think this was fixed by  #51375, I don't see any changes about SparseArrays.jl there and links in https://docs.julialang.org/en/v1.11-dev/stdlib/SparseArrays/ look still wrong to me. Last commit on https://github.com/JuliaLang/docs.julialang.org/tree/gh-pages is based on https://github.com/JuliaLang/julia/commit/b4f7263bcef14bd2de17fe04bc0f2b0f027ec0b1, which is after the merge of your PR, so it should include your fix, if it did something for SparseArrays.jl

**Comment by jam-khan** [comment]
In that case, I plan to solve the issue using suggestions from @inkydragon.

**Comment by LilithHafner** [comment]
I agree that this is not fixed by #51375. My mistake. However, it is still definitely a special case of #50035 (duplicate). It should be hopefully fixed by https://github.com/JuliaSparse/SparseArrays.jl/pull/442

**Comment by nsajko** [comment]
dups #50035
