### ISSUE TITLE
the covariance subtyping property fails to hold for types involving a parameter bounded from above with Bottom

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#53067]
```julia-repl
julia> expected_property(A, B) = (A <: B) == (Tuple{A} <: Tuple{B})
expected_property (generic function with 1 method)

julia> expected_property(Tuple{Vararg{X}} where X<:Union{}, Tuple{})
false

julia> versioninfo()
Julia Version 1.11.0-DEV.1382
Commit 5cf10211fe9 (2024-01-26 02:37 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × AMD Ryzen 3 5300U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, znver2)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```

Given that the counterexample features a type parameter bounded from both above and below with the bottom type, I guess this is somewhat related: #52385

**Comment by vtjnash** [comment]
This is not an expected property. The `apply_type` operation is not required to preserve subtyping, as `apply_type` is not a subtyping query. The confusion can occur since the written syntax `A{T}` can mean both the expression of the apply type operation and the result formed by the operation. The expression `f(::A{T}) where {T} = A{T}` <==> `A{T} === f(A{T})` however should be true, so the transforms applied are observed to be idempotent.
