### ISSUE TITLE
relocatedepot tests are flaky.

### ISSUE THREAD

**Issue by gbaraldi** [JuliaLang/julia#53103]
The relocatedepot tests fail sometimes, it doesn't seem to be specific to a platform since it happens in macos https://buildkite.com/julialang/julia-master/builds/32827#018d545b-d100-456d-9457-abdffcb752be/778-1617 and in windows https://buildkite.com/julialang/julia-master/builds/32787#018d5202-e985-42d8-b62f-e76ddcb7ad52/26541-26929

**Comment by staticfloat** [comment]
`#ci-dev` discussed this and thinks it's highly likely that the issue is that a previously-loaded `Foo` package is interfering with `Base.require()` and we should instead use `Base.compilecache()` to force compilation.  (Also perhaps avoid using the `Foo` name, and embed an issue number into the name to disambiguate.)
