### ISSUE TITLE
the GenericMemory doc string isn't included in the docs

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#53854]
`GenericMemory` is referred to in three places in the in-development docs, but not documented itself. It's public and has a doc string, though, although the doc string doesn't describe the `kind` and `addrspace` type parameters.

**Comment by nsajko** [comment]
`GenericMemoryRef` is likewise public and not documented, but it doesn't have a doc string, either.

**Comment by oscardssmith** [comment]
I think this was somewhat intentional. We know that regular `Memory` has the interface we want, but I think we wanted a release or two and a few examples using the addrspace and kind before we actually decide that the `GenericMemory` doesn't have any design defects that would require breaking changes if it was part of the interface.

**Comment by nsajko** [comment]
If `GenericMemory` or `GenericMemoryRef` aren't part of Julia's API, probably they:

1. shouldn't be *public*/*exported* (currently we have `Base.ispublic(Core, :GenericMemory) == Base.ispublic(Core, :GenericMemoryRef) == true` and they're exported into `Main`)

2. shouldn't be referred to from anywhere in the documentation

**Comment by LilithHafner** [comment]
@oscardssmith, would you be willing to put a note in the docstring describing what is and isn't guaranteed to remain stable?

e.g. should package authors define `f(::Memory{T}) where T` or `f(::GenericMemory{IDK, T}) where {IDK, T}`. Lacking this I think it's all going to end up semi-public upon the release of 1.11 at the very least.
