### ISSUE TITLE
BUG: `clamp(typemax(UInt64), Int64)` errors

### ISSUE THREAD

**Issue by KlausC** [JuliaLang/julia#54022]
The call `clamp(typemax(UInt64), Int64)` should return `typemax(Int64)` but throws `InexactError`.

```
julia> clamp(typemax(UInt64), Int64)
ERROR: InexactError: check_top_bit(UInt64, -9223372036854775808)
Stacktrace:
 [1] throw_inexacterror(f::Symbol, ::Type{UInt64}, val::Int64)
   @ Core ./boot.jl:634
 [2] check_top_bit
   @ ./boot.jl:648 [inlined]
 [3] toUInt64
   @ ./boot.jl:759 [inlined]
 [4] UInt64
   @ ./boot.jl:789 [inlined]
 [5] convert
   @ ./number.jl:7 [inlined]
 [6] clamp
   @ ./math.jl:98 [inlined]
 [7] clamp(x::UInt64, ::Type{Int64})
   @ Base.Math ./math.jl:123
 [8] top-level scope
   @ REPL[1]:1
```

**Comment by KlausC** [comment]
The same happens for bit sizes 8, 16, 32, 64, 128.

**Comment by barucden** [comment]
It's due to `ifelse` being used in https://github.com/JuliaLang/julia/blob/e9a24d4cee4153023a7841a75fc4285229f26720/base/math.jl#L99-L102

Since `ifelse` is a function, all arguments are evaluated. That is
```julia
convert(UInt64, typemax(Int64))
convert(UInt64, typemin(Int64))
convert(UInt64, typemax(UInt64))
```
with the second one throwing the reported error since `typemin(Int64)` is negative. We might replace `ifelse` with the ternary conditional operator, but I am not sure whether it has some performance consequences.

**Comment by vtjnash** [comment]
Ternary is nearly always faster and usually generates better code

**Comment by KlausC** [comment]
See my comment in #54038.
Additionally something like `clamp(x::Int64, UInt64) = UInt64(max(x, 0))` for all bit sizes would solve the issue, probably.
