### ISSUE TITLE
switch expression

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#5410]
It would be nice to have a `switch`-like statement, exploiting LLVM's built-in [switch instruction](http://llvm.org/docs/LangRef.html#switch-instruction), since this can greatly enhance performance of look-up tables (which are not uncommon in inner loops), compared to chains of `if-else` statements (or a `Dict` of functions).

I feel like I've mentioned this to @JeffBezanson, before, but can't find an issue for it.

**Comment by simonbyrne** [comment]
I just tried @simonster's above example on the current master (with both LLVM 3.3 and 3.5), and I get a chain  of `cmp`/`jne` statements. Has something changed since?

**Comment by simonster** [comment]
It doesn't work for me anymore either. It looks like it did in Julia 0.2.1 but doesn't in 0.3.

**Comment by richardreeve** [comment]
I see this thread has been dormant for a while. Although certain chains of ifelse statements may once have been optimisable to computed gotos, they are nonetheless deeply inelegant and error-prone (and I understand they don't currently optimise correctly). The introduction of some kind of switch statement, whether based on Match.jl, Lazy.jl or some other mechanism, would improve code readability, thereby likely reduce inadvertent errors, and add a useful and commonly used tool into the language, as well as speeding up code if they used LLVM's built in computed goto functionality.

**Comment by quinnj** [comment]
@richardreeve, do checkout the [Switch.jl](https://github.com/dcjones/Switch.jl) package.

**Comment by stevengj** [comment]
@quinnj, that package is just syntactic sugar for a bunch of `if val == label` statements, and doesn't address the low-level issue of interfacing LLVM's computed-goto or [switch instruction](http://llvm.org/docs/LangRef.html#switch-instruction) functionality.

**Comment by richardreeve** [comment]
Thanks for the suggestion, @quinnj - that's obviously a possibility. I guess my feeling is that if switch remained as several(!) add-in packages, it will never be optimised and continue instead to be translated into a series of ifelse statements as @stevengj points out.

**Comment by yuyichao** [comment]
Reply to https://github.com/JuliaLang/julia/issues/18285#issuecomment-243469083

> Some of these are difficult to implement via macros.

I don't think so

> often more concise than an elseif sequence

    Can be handled with macro

> can ensure there are no duplicates, or no overlapping ranges

    Can also be handled with macro. Having a syntax doesn't help. Will likely have runtime overhead unless we restrict the condition to constant. And this behavior may not be wanted.

> can ensure all cases are handled, in particular for enums

    Can be hanled with macro.

> can implicitly produce an error if a case isn't handled, without having to explicitly call throw

    Can be handled with macro.

> can be extended to handle types, not just integer-like values; type inference can be taught about this

    Lowering to `elseif` in a macro can trivially handle this. Type inference doesn't need to know anything special about it.

**Comment by bpr** [comment]
# Proposal
This is a Julep suggested by @StefanKarpinski during this [julia-users group discussion](https://groups.google.com/forum/#!topic/julia-users/7IqQROx_zIo). Originally posted at [#18285](https://github.com/JuliaLang/julia/issues/18285), moved here at @yuyichao's suggestion

Julia lacks a C-style [switch](http://en.wikipedia.org/wiki/Switch_statement) statement. This issue has [come up](https://github.com/JuliaLang/julia/issues/5410) [before](https://groups.google.com/forum/#!topic/julia-users/pnEqF5w4GJY/discussion) on various fora. Unsurprisingly, Julia also lacks [pattern matching](https://en.wikipedia.org/wiki/Pattern_matching), a useful generalization of case and switch, which has been implemented as a [macro](https://github.com/kmsquire/Match.jl) for Julia.

This proposal is concerned with using switch statements over integral (isbits) types  to exploit the ability of LLVM's [switch instruction](http://llvm.org/docs/LangRef.html#switch-instruction) to provide a [branch table](https://en.wikipedia.org/wiki/Branch_table) implementation of switch, which is more performant than a sequence of `if-else` conditionals. It should be amenable to supporting extended switch and pattern capabilities in the future; for that reason I'll suggest using adding the `case` keyword to introduce the form. If it's desired that the statement only be used as a C style switch and that pattern matching be introduced separately, perhaps `switch` is the better choice.

I'll skip the arguments in around whether to include such a feature at all; interested readers can review some of those arguments in the context of [Python](http://www.python.org/dev/peps/pep-3103/) or [Lua](http://lua-users.org/wiki/SwitchStatement), as the arguments on both sides would be similar for Julia.

# Syntax

If we'd like to subsume this in a future pattern matching Julia extension, I suggest a syntax influenced by the [Match.jl](https://github.com/kmsquire/Match.jl) macro, replacing `@match` with the keyword `case`, and adding a new keyword `of` to use instead of `begin`. I chose `of` because that's used in many other languages that use `case`, and because Julia constructs like `if/for/while` don't require a `begin` for their `end`.

```Erlang
case case_expr of
    case0 => expr0
    case1 => expr1
    .
    .
    .
    caseNMinusOne => exprNMinusOne
    else => exprN
end
```

The optional `else` at the end could be replaced by `_` or even `otherwise` or `default`, at the cost of using more keywords.

Each case above could be preceded by an `of` if that syntax is preferable. It strikes me as a little wordy but it's a syntax used in other languages and perhaps people find it more readable.

```Erlang
case case_expr
    of case0 => expr0
    of case1 => expr1
    .
    .
    .
    of caseNMinusOne => exprNMinusOne
    else => exprN
end
```


# Examples
```Erlang
n = rand(0:32)
function print_if_lt_3(n)
    case n of
        0 => println("zero")
        1 => println("one")
        2 => println("two")
        else => println("too big")
    end
end
```

Should be semantically equivalent to

```Julia
n = rand(0:32)
function print_if_lt_3(n)
    if n == 0 
        println("zero")
    elseif n == 1
        println("one")
    elseif n == 2
        println("two")
    else
        println("too big")
    end
end
```

An example with enums

```Erlang
@enum Dir north northeast east southeast south southwest west northwest
function degree_of_dir(d)
    case d of
        north => 90
        northeast => 45
        east => 0
        southeast => 315
        south => 270
        southwest => 225
        west => 180
        northwest => 135
    end
end
```

The intent is that `@enum` should work well with this `case` statement, which means that the conversion to the enum's Int value should be implicit, as above.

**Comment by bpr** [comment]
Having done some experiments with clang++, I'm less convinced that there is a performance argument for the inclusion of a switch statement that maps to LLVM's switch. At least in C++ on OS-X , I'm not seeing better performance. I ran with -emit-llvm and confirmed (I'm not an LLVM IR expert, but I can fake my way through and I saw switch where I expected it) that switch was being generated, but I hardly saw any difference at all in a CPU bound (all compute was switching too) benchmark.

I still like switch and pattern matching, but the argument in theory for better performance of switch doesn't appear in practice. Anyone have benchmarks showing switch is O(1) vs O(n)?

**Comment by richardreeve** [comment]
@yuyichao I'm not quite sure why this was closed. While there may not be major performance enhancements (and as far as I'm aware, we're not sure about this), introducing a switch statement into core Julia still seems like a hugely desirable thing to do, as it is a very common pattern, and will reduce errors in coding multiple if-else statements.

**Comment by yuyichao** [comment]
Because of https://github.com/JuliaLang/julia/issues/18285

**Comment by richardreeve** [comment]
Ah, okay, I thought you'd closed that one instead.
