### ISSUE TITLE
Most packages with artifacts are not relocatable

### ISSUE THREAD

**Issue by jonathan-conder-sm** [JuliaLang/julia#54398]
Would anything break if I added `track_content = true` to this line?
https://github.com/JuliaLang/julia/blob/999dde7339787a0efac5b874b6ccf14b7dace8e8/stdlib/Artifacts/src/Artifacts.jl#L696

Related: https://github.com/JuliaLang/julia/pull/53906 and/or https://github.com/JuliaLang/julia/pull/51798

**Comment by KristofferC** [comment]
I don't see why anything should break.

**Comment by vchuravy** [comment]
@jonathan-conder-sm do you want to open that PR?

**Comment by jonathan-conder-sm** [comment]
Sure, sorry I've been busy and forgot about this. See https://github.com/JuliaLang/julia/pull/54426

I'm curious, if this is unlikely to break anything then why is `track_content` not the default?

**Comment by fatteneder** [comment]
The default `track_content = false` was initially chosen, because that's how it used to work before. In particular, some folks on discourse, and I think also Oscar.jl, relied on the mtime check to trigger recompilation.

But I agree that not many pkgs will notice the change, because its seldomly used.
