### ISSUE TITLE
Support guards/filters in comprehensions

### ISSUE THREAD

**Issue by pao** [JuliaLang/julia#550]
Quoting @rtzui in #547:
On the other hand more powerful:

```
x=[1,2,3,4,510,1,2,3,1,9]
y=[sqrt(a) | a ∈ x, x%2==0]
```

(Discussion from @pao)
There is an open syntactic question. The Haskell syntax (shown above) has guards as boolean expressions separated by commas and interspersed with membership assertions, which works as long as you can tell the difference between an expression evaluating to a boolean and a loop assignment statement. Python uses the keyword "if" to precede each guard. I'm sure there are other approaches as well.

(From @JeffBezanson)
It's maybe not ideal, but you can accomplish this as:

```
x=[1,2,3,4,510,1,2,3,1,9]
y=[sqrt(a) | a in x[x%2==0] ]
```

**Comment by chriscoey** [comment]
I like Raul's idea for syntax.

Any updates on this? I would help if I wasn't such a noob! It would make Julia more attractive I think... I used list comprehensions with guards all the time in Python and they saved a lot of time/space.

**Comment by FGFW** [comment]
S[S.> 0]

**Comment by diegozea** [comment]
What is the future/present of this now that generators exist?

**Comment by quinnj** [comment]
I know there's been a lot of discussion around final 0.5 feature triage, but I think this would be a great candidate. I'd hate for us to release 0.5 with generators only to have python-users everywhere wonder why this didn't come with it. From the discussion in https://github.com/JuliaLang/julia/pull/15023, it sounds like a pretty straightforward parsing re-write, which does limit the number of devs who'd feel comfortable making the change, but I think it'd be well worth it.

**Comment by kmsquire** [comment]
:+1:

**Comment by ararslan** [comment]
I think @StefanKarpinski's proposed placement of `if` in #16389 is cleaner than Raul's trailing `if`, i.e.
```julia
x^2 if x % 3 == 0 for x = 1:100 # versus
x^2 for x = 1:100 if x % 3 == 0
```

**Comment by jamesonquinn** [comment]
Note that the infix macros from #16985 could enable a decent band-aid for this issue. If `a @m c`=>`@m a c`, then you could write a "filteredby" macro such that:

`[x^2 for x in 1:100] @filteredby x % 3 == 0` 

=>

`[x^2 for x in filter(x->x%3==0,1:100)]`

I'm not saying that the above should be the long-term answer in this case, but it is a good demonstration of the power of infix macros for easily prototyping language features.

(The same hypothetical macro could of course be used in prefix position, but that seems to me uglier, because it leaves a naked space separation between two things that are treated very differently. YMMV.)

**Comment by StefanKarpinski** [comment]
Omg, man – stop with the infix syntax stuff.
