### ISSUE TITLE
Base.tail Function Redeclaration Causes Julia to Crash

### ISSUE THREAD

**Issue by kylincaster** [JuliaLang/julia#55057]
Hello,

I encountered a crash in Julia (v1.10.4 in win10) when using the following function declaration:

```julia
@inline Base.tail(x::NTuple{N, Any}) where {N} = nothing
```

This crash seems to be related to a conflict with the definition of `Any32{N}` in `base/tuple.jl` at line 361.

Could you please investigate this issue?

Thank you in advance.

**Comment by sgaure** [comment]
This is documented.

> "Type piracy" refers to the practice of extending or redefining methods in Base or other packages on types that you have not defined. In extreme cases, you can crash Julia
(https://docs.julialang.org/en/v1/manual/style-guide/#Avoid-type-piracy)

**Comment by Seelengrab** [comment]
As mentioned above, this is expected behavior. See also [this comment](https://github.com/JuliaLang/julia/pull/54099/files#r1567788049) in a PR about adding docs for UB, which IMO covers this particular case. `Base.tail` on tuples is something pretty much the whole stack relies on, so rewriting it to something different is bound to lead to incorrigible issues.
