### ISSUE TITLE
[LinearAlgebra] Wrong positive definite check when performing Cholesky decomposition

### ISSUE THREAD

**Issue by narger-ef** [JuliaLang/julia#55126]
Hello,

I am trying to do the Cholesky decomposition of the following Gram matrix:

$$
G = U^TU
$$

where:
 
$$
U = \begin{pmatrix}
64337 & 17852\\
8480 & 2353
\end{pmatrix}
$$

$G$ is positive definite by Gram matrix definition.

## How to reproduce

```
using LinearAlgebra

U = stack([[64337, 8480], [17852, 2353]])

cholesky(U' * U)
``` 

It return a `PosDefExecption` exception:
```
PosDefException: matrix is not positive definite; Cholesky factorization failed.
```

I think is related to numerical issues, since the eigenvalues of the matrix $G$ are:

$$
(2.1233931835062947\text{e-8}, 4.535390482\text{e9})
$$

So very close to 0.

Info:

Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 8 default, 0 interactive, 4 GC (on 8 virtual cores)

**Comment by giordano** [comment]
> I think is related to numerical issues

```julia-repl
julia> using LinearAlgebra

julia> U = BigInt[64337 17852; 8480 2353]
2×2 Matrix{BigInt}:
 64337  17852
  8480   2353

julia> G = U' * U
2×2 Matrix{BigInt}:
 4211159969  1168497564
 1168497564   324230513

julia> isposdef(G)
true

julia> cholesky(G)
Cholesky{BigFloat, Matrix{BigFloat}}
U factor:
2×2 UpperTriangular{BigFloat, Matrix{BigFloat}}:
 64893.5  18006.4
      ⋅       1.54099e-05
```

**Comment by mikmoore** [comment]
As remarked above, the issue is that the matrix is very ill-conditioned. There isn't a lot that can be done, in general, to address this, short of using more precision (like `BigFloat` in the above suggestion)

If you truly have the $G = U^\top U$ construction in your situation, consider using the QR decomposition `Q,R = qr(U)`, which will yield $G = R^\top Q^\top Q R = R^\top R = L L^\top$. You might need to flip the sign of some rows of $R$ to make the diagonal positive like in a proper Cholesky decomposition (e.g., `R = sign.(Diagonal(R)) * R`)

**Comment by narger-ef** [comment]
Thank you both, I did not think about the BigFloat type. My bad.
