### ISSUE TITLE
`no method round(MathConst{:π})`

### ISSUE THREAD

**Issue by ihnorton** [JuliaLang/julia#5561]
```
julia> round(pi)
ERROR: no method round(MathConst{:π})
```

reported [here](https://news.ycombinator.com/item?id=7127023)

**Comment by NHDaly** [comment]
This issue is marked as [up for grabs](https://github.com/JuliaLang/julia/labels/up%20for%20grabs) and [intro issue](https://github.com/JuliaLang/julia/labels/intro%20issue), but in light of https://github.com/JuliaLang/julia/issues/21535, this seems like more of a [decision](https://github.com/JuliaLang/julia/labels/decision)?

**Comment by tpapp** [comment]
Would the missing method
```julia
julia> round(Int, pi)
ERROR: MethodError: no method matching round(::Type{Int64}, ::Irrational{:π})
Closest candidates are:
  round(::Type{T<:Integer}, ::Integer) where T<:Integer at int.jl:524
  round(::Type{T<:Integer}, ::Float16) where T<:Integer at float.jl:356
  round(::Type{T<:Union{Signed, Unsigned}}, ::BigFloat) where T<:Union{Signed, Unsigned} at mpfr.jl:229
  ...

julia> VERSION
v"0.7.0-DEV.3507"
```
fall under this issue? Asking because so much of the interface changed since it was opened. 

`round(pi, [digits])` works.

**Comment by KristofferC** [comment]
`round(pi)` now works. For adding additional methods, closing based on https://github.com/JuliaLang/julia/issues/5561#issuecomment-33335174.
