### ISSUE TITLE
Names of startup packages that are being precompiled are not being printed anymore 

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#55653]
Currently, on launching julia nightly, the output in the REPL is
```julia
$ julia +nightly
  6 dependencies successfully precompiled in 32 seconds. 16 already precompiled.
  8 dependencies successfully precompiled in 54 seconds. 12 already precompiled.
  4 dependencies successfully precompiled in 18 seconds. 10 already precompiled.
```
Previously, this used to print the names of the packages as well.
```julia
julia> versioninfo()
Julia Version 1.12.0-DEV.1127
Commit ca72e28f26b (2024-08-31 11:47 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Environment:
  JULIA_EDITOR = subl
```

**Comment by IanButterworth** [comment]
This is a regression caused by https://github.com/JuliaLang/julia/pull/55588 because of two reasons:
1) the progress bar no longer mentions the package name if it's being called on a package that is being loaded (rather than a project, like Pkg does)
2) the progress bar is being cleared after finishing

![Screenshot 2024-08-31 at 2 28 05 PM](https://github.com/user-attachments/assets/7ecd52fc-4ada-4bf2-9b78-f9f516d62f7a)

![Screenshot 2024-08-31 at 2 28 51 PM](https://github.com/user-attachments/assets/e87e4aa7-d835-4fe4-a227-d891fa4dc3f0)

The simplest option would be to modify the report that does print to list what was being precompiled (project/package(s)) and do it in the standard styling.

cc. @KristofferC
