### ISSUE TITLE
REPL precompile script not caching methods from runtime dispatch

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/julia#55778]
See https://github.com/JuliaLang/julia/pull/55759#issuecomment-2349038978

<del> 
It seems difficult to precompile TTY methods directly without either being noisy or crafting `precompile`s manually.

What about adding a mechanism to also compile methods if they change after they've gone through a registered transform?
Something like
```julia-repl
julia> register_pair_compile_transform!(Base.DevNull => Base.TTY)

julia> print(devnull, 1)
precompile(Tuple{typeof(Base.print), Base.DevNull, Int64})
precompile(Tuple{typeof(Base.print), Base.TTY, Int64})

julia> deregister_pair_compile_transform!(Base.DevNull => Base.TTY)
```
Perhaps insert the check for registered transforms [here](https://github.com/JuliaLang/julia/blob/4633607ce9b9f077f32f89f09a136e04389bbac2/src/gf.c#L3088)?
</del>

**Comment by IanButterworth** [comment]
Actually.. 
If I precompile REPL with
```
% ./julia --start=no -e 'Base.PRECOMPILE_TRACE_COMPILE[] = "stderr"; using REPL'
```
then put all the precompiles into `REPL/src/precompile.jl` manually then I get great coverage, low latency.
Note that those precompiles do include the TTY methods..

So it seems the issue is more that something about the way the script is run is causing compiled methods to not be included.
Could it be because the repl is run on another task?

**Comment by IanButterworth** [comment]
> Could it be because the repl is run on another task?

I tried putting the `precompile`s in a separate task and waiting for it to finish but that was still effective.

btw, even though I had a `wait(t)` right at the end I was getting a crash with `task cannot be serialized` unless I `t=nothing` and `GC.gc()`'d. Seems like a bug.

**Comment by IanButterworth** [comment]
With the precompiles the dylib is 29 MB. Without 20 MB. So it seems to be a saving rather than loading issue.

**Comment by IanButterworth** [comment]
It looks like all the methods that aren't sticking are Base methods, so external to REPL. Could it be related to this check, which if I add an else for, is hit twice for `m == Base` at the end of the REPL precompilation. 
https://github.com/JuliaLang/julia/blob/4633607ce9b9f077f32f89f09a136e04389bbac2/src/staticdata.c#L2645

**Comment by timholy** [comment]
> Could it be related to this check

To explain what's going on there (since you work in this space a lot!), that block of code is targeted at discovering "external extending methods," i.e., if `REPL` defines `Base.show(io::IO, c::Completion) = ...`: `Base` owns `show`, and yet `REPL` (external to `Base`) has defined a method that extends `show`. The issue is that such methods can only be found by traversing the module that owns the function, not the module that defined the method:

```julia
julia> module Foo
       struct F end
       Base.show(io::IO, f::F) = print(io, 'F')
       end
Main.Foo

julia> names(Foo; all=true, imported=true)
6-element Vector{Symbol}:
 Symbol("#eval")
 Symbol("#include")
 :F
 :Foo
 :eval
 :include 
 ```
So to discover (and thus cache) this new `show` method, you have to (1) realize that `Foo` depends on `Base` (implicitly, it's not a `baremodule`), and then (2) traverse `Base` in its entirety and look for methods that are owned by `Foo`. (So, that check you highlighted is just a check that we don't repeat work by always starting at the top.)

But presumably that's not what is happening here: presumably it's the standard thing, of REPL's workload forcing compilation `CodeInstances` of Base methods that had not been created at the time that `Base` was cached. Presumably all the missing `CodeInstance`s are "hidden" behind a runtime dispatch, which is why Julia doesn't realize that `REPL` needs them when it saves the cache for REPL. This is the fundamental problem that PrecompileTools solves, as it turns on snooping on inference to tag `CodeInstance`s that get compiled while running the workload, even (especially) when they are hidden behind a runtime dispatch.

The best approach is to fix inference in the callers of these methods, as any inferable calls get added to the cache. I did a ton of this work in REPL for Julia 1.6, but I'd guess it's not been looked at systematically in a while. You could use https://aviatesk.github.io/JET.jl/dev/tutorial/#Analyze-packages-using-a-representative-workload (JET + MethodAnalysis to start from concrete MethodInstances) if you wanted to tackle this. It's not a small project but it is the most wide-ranging in impact.

Alternatively, PrecompileTools is not a huge package, the essentials are probably a couple dozen lines. So if there's no better alternative, you could effectively vendor it into REPL.

**Comment by KristofferC** [comment]
> Presumably all the missing CodeInstances are "hidden" behind a runtime dispatch, which is why Julia doesn't realize that REPL needs them when it saves the cache for REPL.

So running a workload with `--trace-compile` and putting the emitted signatures into the package getting precompiled is "better" than just running the workload itself during precompilation? Because that is what seems to be the case here.

**Comment by timholy** [comment]
Yes, because #43990 added a `precompiled` field to `MethodInstance` which allows you to flag it as "include this is in the cache even if you can't prove it's needed." Calling `precompile` sets this flag (this, plus snooping on inference, is how [PrecompileTools works](https://github.com/JuliaLang/PrecompileTools.jl/blob/a99446373f9a4a46d62a2889b7efb242b4ad7471/src/PrecompileTools.jl#L13)):

```julia
julia> fieldnames(Core.MethodInstance)
(:def, :specTypes, :sparam_vals, :uninferred, :backedges, :callbacks, :cache, :inInference, :cache_with_orig, :precompiled)

julia> using MethodAnalysis

julia> foo(x) = 2x
foo (generic function with 1 method)

julia> foo(3)
6

julia> only(methodinstances(foo)).precompiled
false

julia> precompile(foo, (Int,))
true

julia> only(methodinstances(foo)).precompiled
true
```

Using explicit lists of `precompile` directives is pretty horrible because of differences in platforms (32-bit vs 64-bit, OS, etc) and, for packages, differences in Julia (or other dependencies) versions. But for something like REPL it's something we could conceivably maintain. But really, PrecompileTools for workloads boils down to just a few lines:
- https://github.com/JuliaLang/PrecompileTools.jl/blob/a99446373f9a4a46d62a2889b7efb242b4ad7471/src/workloads.jl#L32-L38 (`check_edges` isn't needed in >95% of cases)
-  https://github.com/JuliaLang/PrecompileTools.jl/blob/a99446373f9a4a46d62a2889b7efb242b4ad7471/src/workloads.jl#L90-L98

And that's pretty much it. So, about 15 lines of code.

**Comment by KristofferC** [comment]
> Using explicit lists of precompile directives is pretty horrible because of differences in platforms (32-bit vs 64-bit, OS, etc) and, for packages, differences in Julia (or other dependencies) versions.

The way things used to work for the REPL precompilation is that we spawned a separate process which we recorded things (with `--trace-compile`) and then imported them into the main process. So there wasn't an explicit list per say. However, now we just run the workload directly which thus explains why things are worse now.

**Comment by IanButterworth** [comment]
Thanks @timholy very helpful!

Couldn't the grabbing of all methods compiled during the process be done by looking at world age?

**Comment by IanButterworth** [comment]
Also

> The best approach is to fix inference in the callers of these methods, as any inferable calls get added to the cache.

The way the script works is a predetermined [string list](https://github.com/JuliaLang/julia/blob/4633607ce9b9f077f32f89f09a136e04389bbac2/stdlib/REPL/src/precompile.jl#L42) of things to run in the REPL, which I guess requires runtime dispatch? That seems like a nonstarter for that strategy?

**Comment by timholy** [comment]
> Couldn't the grabbing of all methods compiled during the process be done by looking at world age?

Yes, but then you'd end up with bloated files. You don't actually need to cache, say, all the things that were needed to implement the macros (because you cache just the result), nor the things needed to generate data for your compile workloads (the idea behind `@setup_workload`). I tested this and the effect was much larger than I naively anticipated, it led to quite huge files. But that was a while ago that I looked.

> which I guess requires runtime dispatch

Runtime dispatch isn't a problem for things that are owned by the module you're precompiling: we cache all module-owned CodeInstances. The CodeInstances that get "lost," if they're hidden behind runtime dispatch, are those that don't belong to module(s) you're caching. So if your script "gets into the REPL" quickly, relying on runtime dispatch at top level is a non-issue. It's really whether the internals in REPL are calling methods in Base or other dependencies via runtime dispatch.
