### ISSUE TITLE
Application reaches a deadlock if an adopted thread outlives the runtime thread

### ISSUE THREAD

**Issue by Taaitaaiger** [JuliaLang/julia#56016]
Reproducer:

```C
#include <julia.h>
#include <pthread.h>
#include <stdatomic.h>

JULIA_DEFINE_FAST_TLS

static _Atomic(int) init = 0;
static _Atomic(int) active = 0;

void *func(void *arg) {
    jl_init();
    atomic_store(&init, 1);
    while (atomic_load(&active) == 0) {}
    jl_atexit_hook(0);
    return NULL;
}

int main(int argc, char *argv[])
{
    pthread_t thread;
    pthread_create(&thread, NULL, func, NULL);

    while (atomic_load(&init) == 0) {}

    jl_adopt_thread();

    atomic_store(&active, 1);

    void *result;
    pthread_join(thread, &result);

    return 0;
}
```

This might be by design, but I 'm not sure. I haven't done a bisection, but I think #55105 might have introduced this  problem because the code gets stuck [here](https://github.com/JuliaLang/julia/blob/7cc195cf19a317e633a9ea575c842396a2fa70a8/src/safepoint.c#L271)

**Comment by vtjnash** [comment]
It is likely intentional there. There are a lot of concurrency issues with the sample code you posted anyways, and one intent of https://github.com/JuliaLang/julia/pull/55105 is to make those more visible to the user. I don't have time to post an entirely fixed version, but once you adopt a thread, that thread is then required to explicitly exit the safe region (using cfunction instead of jl_adopt_thread would have handled this for you) and/or check the workqueue that it is handling all events. Often pthread_join is not allowed anymore on that thread after being adopted, since it only synchronizes with some of the C runtime, and does not correctly synchronize with the julia runtime.

**Comment by Taaitaaiger** [comment]
Thanks for the info, I appreciate it! With exiting safe region, do you mean the leaving the GC-unsafe region?

In any case, I'm closing this issue because it's a design choice.
