### ISSUE TITLE
Bug, where? In Base.power_by_squaring?

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#56176]
```
julia> randn(2,2)^5250  # I think must be a bug.
2×2 Matrix{Float64}:
 NaN  NaN
 NaN  NaN


julia> randn(2,2)^4250  # not bug, expected
2×2 Matrix{Float64}:
 Inf  Inf
 Inf  Inf

julia> randn(2,2)^2250  # neither a bug
2×2 Matrix{Float64}:
  0.0   0.0
 -0.0  -0.0

This works:
julia> floatmin(Float64)*floatmax(Float64)
3.9999999999999996
```

Could it be about subnormals? Are they generated by randn, and is that wanted? They could be generated by simply multiplying, and is a NaN then maybe expected with further processing?

**Comment by adienes** [comment]
```
julia> x
2×2 Matrix{Float64}:
 -5.56712e174  1.10344e176
 -1.51232e177  2.99752e178

julia> x * x
2×2 Matrix{Float64}:
 NaN  NaN
 NaN  NaN
```

**Comment by mikmoore** [comment]
As pointed out above, your use of `randn` is confusing things here. It's not the powers that cause the problem (except that they are large), but the matrices themselves.

If a matrix has all positive entries, then it will power to some combination of `0` and `Inf`. Otherwise, it will usually end up with some combination of `0` and `Inf-Inf == NaN`.
