### ISSUE TITLE
Julia on servers without IPv4

### ISSUE THREAD

**Issue by tk3369** [JuliaLang/julia#56520]
I am trying to build julia 1.11.1 on a server that only has IPv6 interfaces. I was able to build the julia binary but the networking related tests were skipped. And, they were skipped because `getipaddr()` throws an exception:

```julia
julia> getipaddr()
ERROR: No networking interface available
```

This is where it's invoked from the test:
https://github.com/JuliaLang/julia/blob/8f5b7ca12ad48c6d740e058312fc8cf2bbe67848/test/choosetests.jl#L188-L202

I do have IPv6 addresses:
```
julia> getipaddrs()
3-element Vector{IPAddr}:
...
```

The documentation suggest that it should return an IP address, just having a preference of IPv4 over IPv6. 
```julia
help?> getipaddr
search: getipaddr getipaddrs getpid getindex getalladdrinfo

  getipaddr() -> IPAddr

  Get an IP address of the local machine, preferring IPv4 over IPv6. Throws if no addresses are available.

  getipaddr(addr_type::Type{T}) where T<:IPAddr -> T

  Get an IP address of the local machine of the specified type. Throws if no addresses of the specified type are available.

  This function is a backwards-compatibility wrapper around getipaddrs. New applications should use getipaddrs instead.

  Examples
  ≡≡≡≡≡≡≡≡

  julia> getipaddr()
  ip"192.168.1.28"
  
  julia> getipaddr(IPv6)
  ip"fe80::9731:35af:e1c5:6e49"

  See also getipaddrs.
```

So, why doesn't getipaddr() return IPv6 address instead? Do you consider this a bug or an error in documentation? I feel that it's the former.

**Comment by barucden** [comment]
Both `getipaddr()` and `getipaddr(::Type{<:IPAddr})` are confusing to me.

`getipaddr(T)` should return an address of type `T`. We already request a list of addresses of that type on line 284:
https://github.com/JuliaLang/julia/blob/afdba951b36e65cd8b728e460160d8765aae321f/stdlib/Sockets/src/addrinfo.jl#L283-L293
So if, `T` is IPv4, all addresses in `addrs` should be IPv4 addresses, and then we don't need to `findfirst` (on line 291) address of type IPv4 – the first one will be an IPv4 address. On the other hand, if `T` is IPv6, then none of `addrs` will be IPv4 and (even if some would) the method should return an IPv6 address because that was requested.

The single-argument method should not "prefer" one address type over another, because the address type is given by the argument. 

The method without any argument should prefer IPv4 as per documentation and it does not do that now. It either returns IPv4 or nothing. 

We should change the methods to something like
```julia
function getipaddr(addr_type::Type{T}) where T<:IPAddr
    addrs = getipaddrs(addr_type)
    if length(addrs) == 0
        error("No networking interface available")
    end
    return first(addrs)
end
function getipaddr()
    ipv4addrs = getipaddrs(IPv4)
    isempty(ipv4addrs) || return first(ipv4addrs)
    return getipaddr(IPv6)
end
```
