### ISSUE TITLE
breaking out of parallel for loops

### ISSUE THREAD

**Issue by thearn** [JuliaLang/julia#5826]
Hi, new to Julia (and like what I'm seeing so far!)
I just tried to construct this parallel for loop, which I would like to break out of based on a conditional:
```julia
import pe

s = @parallel (+) for i in 1:1000
    f = pe.fib(i)
    if f > 4000000
        break
    end
    f % 2 == 0 ? f : 0
end
println(s)
```
This code fails with the error:

```
ERROR: syntax: break or continue outside loop
```
I'm not sure if this is a bug or not.
If not, is there currently a supported way to break out of a `@parallel` for loop, based on a conditional? I didn't find anything obvious in the docs.

edit : thanks for the tip on avoiding accidental notifications!

**Comment by malmaud** [comment]
I am tempted to say this shouldn't be implemented exactly because there is no unambiguous  meaning for `break` in this setting . Matlab's `parfor` loops don't support any control instructions, nor does openmp, nor any other parfor-like construct in other languages I'm aware of. I'll close this in a few days if there isn't any opposition.

**Comment by malmaud** [comment]
I'm going to close for now. @thearn, feel free to leave a comment to reopen if you want to discuss a concrete notion of what `break` should do in this situation.
