### ISSUE TITLE
GC behavior when memory is almost full

### ISSUE THREAD

**Issue by danielcdcj** [JuliaLang/julia#6103]
Refer to this example
https://groups.google.com/forum/#!topic/julia-users/eYCwT6o4UlM

A = a big matrix. After A is defined, there would be 1.1 GB free memory left
B = a random matrix of 500 MB

C = a random matrix of 500 MB
so now there's only 100 MB free on the memory

C = 0
still 100MB free.... Julia not cleaning up Memory. MATLAB would free the memory at this point

B = a random matrix of 500 MB
run out of RAM, now stuff get written to disk

This example was ran in Julia v0.2.1 on Mac OS 10.8.5.

**Comment by PallHaraldsson** [comment]
This issue was last updated long before v0.4.0-rc2. Is it still an issue after many changes, e.g. to an incremental GC?

Yes, RAM can of course still get full.. but was this about accumulated garbage? [I only scanned thread.. Will not look into much if you think someone just forgot to close the issue.]

@vtjnash: "Good garbage collection is a tradeoff of time and memory allocation. I recommend you save time and buy enough memory to contain your data."

[Yes and no, garbage be allowed to accumulate to much for cache reasons, and you can't buy that easily, but it's a different issue to memory running out.] In the case stated, the memory didn't really run out.

Does Julia ever return memory to the OS? Maybe allocated garbage memory, not used, isn't too big of a problem.. for the current process or for all combined, so I'm not too worried, on Android without VM, it would however be more of an issue.

**Comment by yuyichao** [comment]
Close as dup of https://github.com/JuliaLang/julia/issues/17987. (Really the other way around but it's better to discuss there.)
