### ISSUE TITLE
more specific location for syntax errors

### ISSUE THREAD

**Issue by maximsch2** [JuliaLang/julia#6179]
test.jl:

```
function test(a, b)
  c = 0
  d = 3
  d = d + a(b, d]
end
```

`julia test.jl`:

`ERROR: syntax: unexpected "]" in argument list
 in include_from_node1 at loading.jl:120
while loading test.jl, in expression starting on line 1`

It would be better if the error will be point out more precisely (instead of just pointing at the beginning of the function).

**Comment by oscardssmith** [comment]
I just ran into this. I'm definitely not the most experienced Julian, but we have to be able to do better than
```
ERROR: syntax: missing comma or ) in argument list
Stacktrace:
 [1] top-level scope at none:1
```
for 
```
function foo()
           x=1
           bar(a b)
end
```
If you're typing it in line by line, the experience is fine since the error comes right after you hit the offending line, but if you're copy-pasting code in, not having any indication what line was the problem is really annoying.

**Comment by vtjnash** [comment]
```
julia> function foo()
                  x=1
                  bar(a b)
       end

ERROR: ParseError:
# Error @ REPL[1]:3:18
           x=1
           bar(a b)
#                ╙ ── Expected `)`
```
