### ISSUE TITLE
convert(Float64, ::BigInt) – rounding and corner cases

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#6365]
See https://github.com/JuliaLang/julia/commit/f04aa6fc16177b01975a3af40c1747718e1db8c8 and https://gmplib.org/manual/Converting-Integers.html#Converting-Integers.

**Comment by jiahao** [comment]
In principle @simonbyrne's recent work on incorporating `RoundingModes` into `Float64` constructors offers a simple resolution: simply define only `Float64(::BigInt, RoundToZero)` to work.

However, this issue is somewhat mind-bending: the edge cases here are when a `BigInt` is converted to `Float64` where the granularity of `Float64` is > 1.0 (the magnitude of the number must be ~1e16 or greater). I'm not sure if all the usual notions of rounding modes apply. What does "resolve ties to even" mean when `eps(x) = 16384.0` ?

**Comment by simonbyrne** [comment]
Ties to even is still well-defined: the even one is the number with the zero in last place of the significand (`bits(x)[end]`).

We could probably do this ourselves via an explicit branch if the returned value is greater than `maxintfloat`?

**Comment by jiahao** [comment]
That makes sense. (I didn't know `maxintfloat` existed!)
