### ISSUE TITLE
make `write(io, Any[...])` an error

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#6466]
I noticed this with IOBuffer, but it looks like IOStream, AsyncStream, and File all have the same issue.  In each of their `read!{T,N}(::IO, a::Array{T,N})` methods, they assume that the number of bytes to read is `length(a)*sizeof(T)`.  This is not true for `Char`:

```
julia> buf = IOBuffer("abcdefghijklmnop");

julia> read(buf, Char)
'a'

julia> read(buf, Char, 2) # dispatches to read!(IOBuffer, Array{Char,1})
2-element Array{Char,1}:
 '\U65646362'
 '\U69686766'
```

For IOBuffer, I think the specialization could simply be removed (albeit perhaps at a small performance loss).  The others, however, are trickier — File performance is much more critical and the Async/IOStream ones need to know how many bytes to wait for.

**Comment by kshyatt** [comment]
This is reproducible on today's `master`.

**Comment by JeffBezanson** [comment]
This has gotten slightly better since we changed `read(io, Char, 2)` to `read!(io, Vector{Char}(2))`, which makes it clear you're reading an Array, and that `Array` determines the representation.

One question is what `read(io, Char)` should do. Currently it's UTF-8; is that the right thing to do?

Another issue is writing non-isbits arrays, or `Any` arrays. Currently we handle these by calling `write` in a loop, but this is a strange thing to do since you'll end up with a basically unusable binary representation. Arguably you should have to write the loop yourself if you really want this. Triage thinks we should make this case an error.

**Comment by StefanKarpinski** [comment]
Shouldn't it be an error to serialize any pointer array?

**Comment by JeffBezanson** [comment]
Yes, I was using `Any` as a shorthand for that.
