### ISSUE TITLE
On-demand loading of support for file formats?

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#7299]
@mbauman had an interesting idea he proposed in https://github.com/timholy/HDF5.jl/pull/101 that may be worth discussing. He pointed out that there are conflicts for functions named `save` and `load`. He suggested that one way to solve this is based on file extension, e.g., `save("mydata.jld", ...)` would invoke the HDF5/JLD code, whereas `save("mydata.df", ...)` might invoke DataFrames routines, etc. (I don't know whether there's a standard extension for DataFrames, I just made that up.) This is especially important when the same datatype could be stored using two different on-disk formats.

Images already has something that's a little bit like this, a framework for registering support for file formats based on extension and/or magic bytes, https://github.com/timholy/Images.jl/blob/master/doc/extendingIO.md#contributing-a-file-format-to-images. Should this registration framework be generalized and added to Julia proper? The idea is that all the support code would still live in packages, but that those packages would be loaded automatically depending on extension and/or magic bytes.

**Comment by SimonDanisch** [comment]
By the way, advanced my approach a little in FileIO. 
I want to use it soon for all my FileIO.
I took the feedback from FileIO and stole a little from Images.jl and that's what came out of it:
https://gist.github.com/SimonDanisch/feea8f9afb0fe8a109e3#file-fileio_mime-jl
Would be nice to get some feedback =)
I ditched the parameter in File{ending} as this turned out to be pretty annoying for arrays.
I still like it, so maybe it would be nice to get better support for phantom parameters, which don't influence the underlying memory representation!?
Caching and where the mimes live is still an open question.
I also don't have a clear picture of how to handle streams vs paths vs data.
Maybe have the  parameter of File tell if its a stream or just a path to a file.

**Comment by SimonDanisch** [comment]
I haven't really showed how loading should work.
I think the function should specialize to the unique_identifier, e.g. ascii_ply.
It could look like this:
```Julia
load(::File, Mime{UniqueIdentifier})
safe(::T, Mime{UniqueIdentifier})
```

**Comment by timholy** [comment]
OK, I finally found time to deliver some "feedback": https://github.com/JuliaIO/FileIO.jl/pull/15

My sense is that this doesn't need to live in base julia; every package that wants to use `load` or `save` should be `using FileIO`. If others agree, I think we can close this.

**Comment by SimonDanisch** [comment]
I agree!  Would be odd to have a hook to every io package in Base, while
`using FileIO` is completely acceptable!
Thanks a lot for this, I will have a look at it tomorrow!
