### ISSUE TITLE
syntax of `const` with multiple variables

### ISSUE THREAD

**Issue by berceanu** [JuliaLang/julia#7314]
While `global const a=1, b=2` works as expected,

`const a=1, b=2`
`syntax: invalid assignment location "1"`

obviously doesn't.  Instead one has to use `const a, b = 1, 2`.
This looks quite inconsistent to me.

**Comment by mindbound** [comment]
The same situation is with using `local` and `global` in typed variable declarations: http://stackoverflow.com/questions/39733365/multiple-typed-variables-in-one-line-in-julia

**Comment by JeffBezanson** [comment]
Now that I'm looking into this, I wonder which syntax should actually be deprecated.

Normally, `a, b = 1, 2` is a valid assignment. However, in a few specific cases we give comma *lower* precedence than `=`, such as `for i=1:n, j=1:m`, and also `let` variables. We also do that for `global` and `local`, but not `const` (this issue). I'm kind of inclined to drop the special parsing for `global` and `local`, and use normal assignment syntax more often.

As an example, the dates code currently contains

```
const Mon,Tue,Wed,Thu,Fri,Sat,Sun = 1,2,3,4,5,6,7
```

Do we prefer that, or

```
const Mon=1, Tue=2, Wed=3, Thu=4, Fri=5, Sat=6, Sun=7
```

I'm leaning towards the first one, since the syntax can be the same with or without the `const` in front.

**Comment by stevengj** [comment]
I'd prefer the first one.  It's important to support `const a,b = foo()`, where `foo()` returns a tuple, since otherwise you'd have to do `const ab = foo(); const a = ab[1]; const b = ab[2]`.

**Comment by omus** [comment]
I would prefer if we stick to normal assignment syntax rather than having special parsing for `global` and `local`.

I noticed that assignment is allowed in arrays (`[a=1, b=2]`) so if we want to support both forms we could have:
```
const Mon,Tue,Wed,Thu,Fri,Sat,Sun = 1,2,3,4,5,6,7
const [Mon=1, Tue=2, Wed=3, Thu=4, Fri=5, Sat=6, Sun=7]
```

**Comment by JeffBezanson** [comment]
Deprecation for this is in. Moving to 1.0, where we can change the parsing and remove the warning.

**Comment by maleadt** [comment]
The deprecation from #19905 seems confused by `local`:

```julia
julia> function foo()
         x = 0
         y = 0
         for i = 1:2
           local x=1, y=1
         end
         (x,y)
       end

WARNING: deprecated syntax "local x=1, y=1" at REPL[1]:6.
Use "local x, y = 1, 1" instead.
foo (generic function with 1 method)

julia> foo()
(0,0)
```

So far so good, however using this suggested syntax a) seems invalid, and b) triggers a nonsensical deprecation warning:

```julia
julia> function bar()
         x = 0
         y = 0
         for i = 1:2
           local x, y = 1, 1
         end
         (x,y)
       end

WARNING: deprecated syntax "local x, y=1, 1" at REPL[2]:6.
Use "local x; local y=1; local 1" instead.
ERROR: syntax: invalid syntax in "local" declaration
```

**Comment by JeffBezanson** [comment]
Yes, looks like I need to require parentheses there.

**Comment by tkelman** [comment]
That cleanup should be made before we put out an alpha that we tell people to test against, right?
