### ISSUE TITLE
iswritable(::FileName) is useless and broken

### ISSUE THREAD

**Issue by gasagna** [JuliaLang/julia#7385]
There is probably a bug is the `iswritable` function. Watch this:

````julia
julia> iswritable("/")
true

shell> touch /new
touch: cannot touch '/new': Permission denied

````
All this is run from the REPL, with julia launched as normal user, so there is no write permission at all in the root folder /. I would expect `iswritable` to return false in this case.

Running Julia v"0.3.0-prerelease+3461" on Ubuntu 14.04.

**Comment by vtjnash** [comment]
PR was https://github.com/JuliaLang/julia/pull/7418 for Isiah's attempt (since github only seems to have linked the commit sha1 from here)

I think we should just delete this functions. Since, as the man page says: "Warning: Using access() to check if a user is authorized to, for example, open a file before actually doing so using open(2) creates a security hole, because the user might exploit the short time interval between checking and opening the file to manipulate it"
