### ISSUE TITLE
Error in A_ldiv_B! with sparse matrix 

### ISSUE THREAD

**Issue by CodeLenz** [JuliaLang/julia#7488]
Hi.

I just found a bug in A_ldiv_B! when used with a sparse matrix
factored with lufact! 

The error is trigered with 

````
A = spzeros(3,3)
A[1,1] = 1
A[2,2] = 1
A[3,3] = 1
b = ones(3)

lufact!(A)

A\b  --> trigs the error.
````

 ERROR: BoundsError()
 in istriu at sparse/sparsematrix.jl:1748
 in unsafe_copy! at array.jl:41
 in A_ldiv_B! at linalg/sparse.jl:209

julia> versioninfo()
Julia Version 0.3.0-prerelease+3952
Commit b2fd3af (2014-06-30 01:39 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY)
  LAPACK: libopenblas
  LIBM: libopenlibm

It was working with the previous versions.

Sincerely yours,
Eduardo.

**Comment by ViralBShah** [comment]
We have now removed `!` methods for sparse factorizations.

**Comment by ViralBShah** [comment]
@andreasnoack Should we disallow `cholfact!` too? It gives a `DomainError` currently:

````
julia> cholfact!(sparse(rand(5,5)))


ERROR: DomainError:

 in chol! at linalg/cholesky.jl:133
 in chol! at linalg/cholesky.jl:71
 in cholfact! at linalg/cholesky.jl:98
````

**Comment by ViralBShah** [comment]
I see that it has a fallback to the generic implementation. Perhaps we need an explicit method to disallow it for sparse?

**Comment by andreasnoack** [comment]
I think it is safe to restrict that method to `StridedMatrix`. That should fix the issue, so I'll do that.

**Comment by andreasnoack** [comment]
Fixed in 9c72dec5f191de11f86687afdad158ef2250fdc3

**Comment by tkelman** [comment]
> Removing the `!` methods also breaks generic code that can work with both dense and sparse matrices.

This is still a potential concern. But I don't think our current `cholfact!` API is really generic enough to cover sparse effectively in its current form. What would probably be better for dense-sparse generality is deciding on (then implementing, testing, and documenting it properly) a good medium-level API for reusable sparse factorizations, something like `symfact` and `numfact!`. Dense can be expressed as the special-case performance optimization here, within a framework that's generic enough to do sparse correctly. `symfact` for dense just happens to be a no-op (or identity, returning the same array space).

**Comment by andreasnoack** [comment]
I agree. The generic `cholfact!` computes the factorization correctly, but is not useful for sparse matrices. It could be interesting to experiment with sparse factorizations in Julia, but we should probably do the experiments outside base.

**Comment by ViralBShah** [comment]
In case you did not already know, see: https://github.com/JuliaSparse/MultiFrontalCholesky.jl

**Comment by tkelman** [comment]
That's great to see a start for a pure-Julia sparse solver implementation. So far that's working at a pretty low level though, the API refinement will need to happen somewhat separately from and in parallel with the pure-Julia solver implementations. Ideally we want a design somewhat like MathProgBase where different low-level solvers (some in Julia, some in C or C++ or Fortran) can plug into a uniform set of interfaces, to present the same API to consumers (whether users directly working with sparse linear algebra, or higher-level libraries like optimization solvers).

This probably should happen outside of base to start with. Though to truly resolve #8001 and make sparse matrices first-class citizens, the way base Julia deals with dense matrices will eventually have to adapt in order to generically handle either dense or sparse matrices for all operations.
