### ISSUE TITLE
WIP: Total size of Julia objects

### ISSUE THREAD

**Issue by avitale** [JuliaLang/julia#7603]
Hi, I couldn't find any function to calculate the total size of an object (ie including size of its elements), so I wrote one 

https://gist.github.com/avitale/0070b629b89350b39c21#file-totalsize-jl

is there any interest in including it in base?

**Comment by pagnani** [comment]
I would find quite useful a ``totalsizeof(T)`` function, and also an improved ``whos()`` showing total size of desktop. I came across this thread and I tried using the above mentioned gist. There must be some error in the implementation since on a rank four tensor does not seem to return the same size

```
julia> totalsizeof(rand(21,21,53,53))
18953024

julia> totalsizeof(rand(21,21,53,53))
18884112
```

Also smaller size tensor show the same behaviour although with this size the inconsistency is systematic, at least on my laptop 

```
julia> versioninfo()
Julia Version 0.3.5-pre+25
Commit 4f74d19 (2015-01-03 10:35 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by LilithHafner** [comment]
For folks who are still looking for this feature, we have `Base.summarysize`

```
help?> Base.summarysize
  Base.summarysize(obj; exclude=Union{...}, chargeall=Union{...}) -> Int

  Compute the amount of memory, in bytes, used by all unique objects reachable from the argument.

  Keyword Arguments
  ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡

    •  exclude: specifies the types of objects to exclude from the traversal.

    •  chargeall: specifies the types of objects to always charge the size of all of their fields, even if those fields would normally be excluded.
```
