### ISSUE TITLE
Matrix factorizations with unitful elements fail

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#7623]
A simple example:
```julia
julia> using SIUnits; A=randn(1,1)Second
1x1 Array{SIQuantity{Float64,m,kg,s,A,K,mol,cd},2}:
 -1.0710545530502584 s 

julia> lufact(A)
ERROR: `convert` has no method matching convert(::Type{Float64}, ::SIQuantity{Float64,0,0,1,0,0,0,0})
 in copy! at abstractarray.jl:149
 in convert at abstractarray.jl:303
 in lufact at linalg/lu.jl:65
```

The error arises here because `lufact` dispatches on [this method](https://github.com/JuliaLang/julia/blob/master/base/linalg/lu.jl#L65) which computes `T=eltype(A); S=one(T)/one(T)` and converts the matrix to an `AbstractMatrix{S}`. In this case `S == Float64` drops the SIQuantity annotation, which causes the error.

cc: @Keno @andreasnoack

**Comment by andreasnoack** [comment]
I believe this is now just an `SIUnits` issue. It has
```jl
julia> A = eye(2)Second                                           
2x2 Array{SIUnits.SIQuantity{Float64,m,kg,s,A,K,mol,cd,rad,sr},2}:
 1.0 s  0.0 s                                                     
 0.0 s  1.0 s                                                     
                                                                  
julia> typeof(one(A[1]))
Float64                                                           
```
but
```jl
julia> typeof(one(eltype(A)))                
SIUnits.SIQuantity{Float64,0,0,0,0,0,0,0,0,0}
```
because it falls back on the `Number` fallback. It's a instance of a type for which the right thing is `typeof(x) != typeof(one(x))`. `Char` is similar but for `zero` since
```jl
julia> 'a' == 'a' + 0
true
```
(but we don't define `zero(Char)`).

Right now, `qrfact` doesn't work, but that is because of a missing `abs2` in `SIUinits`.

cc: @Keno
