### ISSUE TITLE
Pkg.rm sometimes has to be run twice

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#7757]
I can't quite pin down why this happens, but I see this quite often:

``` julia
julia> Pkg.rm("React")
INFO: No packages to install, update or remove
INFO: Package database updated

julia> Pkg.rm("React")
INFO: Removing React (unregistered)
```

**Comment by tkelman** [comment]
I just re-discovered this while working on doing something about #7054. @StefanKarpinski what's the desired behavior here? We have:
```
function rm(pkg::AbstractString)
    edit(Reqs.rm,pkg) && return
    ispath(pkg) || return info("Nothing to be done")
    info("Removing $pkg (unregistered)")
    Write.remove(pkg)
end
```

The first time you run `Pkg.rm` on a package that's a dependency of some other installed package, the `edit` takes that package out of `REQUIRE` but otherwise doesn't do anything, but returns true so `rm` finishes there. The second time, `edit` returns false so it goes on and thinks the package is unregistered and moves it to `.trash`. Seems like a bug?
