### ISSUE TITLE
Exposing UVError doesn't seem right

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/julia#7841]
```
julia> try
         run(`false`)
       catch err
         dump(err)
       end
ErrorException
  msg: ASCIIString "failed process: Process(`false`, ProcessExited(1)) [1]"

julia> try
         run(`foobar`)
       catch err
         dump(err)
       end
UVError
  prefix: ASCIIString "could not spawn `foobar`"
  code: Int32 -2
```

I feel like `UVError` isn't something that should be escaping the Julia internals. For one thing, I doubt anyone not involved with Julia development knows or wants to know what the `UV` refers to. Having different exception types thrown from the same method (from the users perspective) feels odd to me, although I think thats a much more debatable point.

It bit me recently (I had code like `println(fp, err.msg)`, which threw an error in the error handler...) and I just saw https://github.com/JuliaLang/julia/pull/7822 which made me think of it again.

**Comment by samoconnor** [comment]
#15879

**Comment by IainNZ** [comment]
I think this is still relevant (the original example still works). UVError is not exported from Base, so is it correct that its OK to put this off past 1.0?

**Comment by JeffBezanson** [comment]
Agree this should be replaced with SystemError, IOError, etc.

**Comment by StefanKarpinski** [comment]
Shouldn't this be on the 0.7 milestone rather than 1.0?

**Comment by JeffBezanson** [comment]
Yes I think this could be on the 0.7 milestone, but it's fairly minor since code probably doesn't reference UVError too often.

**Comment by samoconnor** [comment]
In #15879 a subset of `UVError` was replaced by `DNSError`. A quick scan of the [possible  `UV_` error codes](http://docs.libuv.org/en/v1.x/errors.html) suggests that there is scope to continue this pattern and split out more specific error types in future (`IOPermissionError`?, `IOBusyError`?, `HostUnreacableError`?).

However, I'm concerned that baking `IOError` into 1.0 with its current meaning would preclude splitting out more fine-grained error types.

e.g if the code below was written for Julia 1.0, it would stop working if `IOPermissionError` was later added as a fine-grained error type for `UV_EACCES`.
```julia
catch e
    if e isa IOError && e.code == UV_EACCES
        bar()
    else
        rethrow(e)
    end
end
```

It might be better for `IOError` to be an abstract type so that a future `IOPermissionError` could be `<: IOError`. Then code like the following would continue to work as fine-grained error types are added:

```julia
catch e
    if e isa AbstractIOError && errorcode(e) == UV_EACCES
        bar()
    else
        rethrow(e)
    end
end
```

**Comment by StefanKarpinski** [comment]
Technically making `IOError` abstract in the future is not a breaking change. Dispatch on it and fields that use it would continue to work as expected. Only code that was written to the new subtypes would see any difference and that's not breaking.

**Comment by samoconnor** [comment]
Then perhaps the `IOError.code` field should be renamed to `uvcode` (`syscode`? `internalcode`?). Otherwise future `IOError` subtypes can't use the field name `code`.
e.g. if `HTTPError <: IOError` then `.code` would be `404` not a `UV_` code.

**Comment by JeffBezanson** [comment]
The `code` field is implementation-defined anyway; it's pretty hard to commit to a meaning for all of its possible values. `HTTPError` would specify that `.code` is an HTTP error code, but `IOError` says the code is implementation-defined and you don't really know what it is.
