### ISSUE TITLE
Better error for accidently shadowing functions with local variables

### ISSUE THREAD

**Issue by ivarne** [JuliaLang/julia#7862]
Currently you get a quite incomprehensible error when you shadow a variable with a local variable.

This has been a problem (eg [here](https://groups.google.com/forum/?fromgroups=#!topic/julia-users/TiaMeTAxfCw)).

``` jlcon
julia> yticks([0.0, 1.0, 2.0]) 
type: apply: expected Function, got Array{Float64,1}
Use square brackets [] for indexing.
while loading In[21], in expression starting on line 8
 in getindex at C:\Users\zahir\.julia\v0.3\PyCall\src\PyCall.jl:625
 in pysequence_query at C:\Users\zahir\.julia\v0.3\PyCall\src\conversions.jl:741
 in pysequence_query at C:\Users\zahir\.julia\v0.3\PyCall\src\conversions.jl:740
```

Is this a better error message?

``` jlcon
julia> yticks([0.0, 1.0, 2.0])
Array{Float64,1} is not a callable function
Use square brackets [] for indexing.
You might also have a local variable that shadows the function you intended to call.
while loading .....
```

In the REPL, one might easily use function names as variables and forget about it later.

Would it be possible to make such assignment trigger a warning?

**Comment by brenhinkeller** [comment]
So it looks like the current (1.8.2) error message is actually quite a bit better than the one reported above for Julia 0.(?3)
```
julia> yticks = ([1, 2, 3])
3-element Vector{Int64}:
 1
 2
 3

julia> yticks([1,2,3])
ERROR: MethodError: objects of type Vector{Int64} are not callable
Use square brackets [] for indexing an Array.
Stacktrace:
 [1] top-level scope
   @ REPL[10]:1
```
in particular the `ERROR: MethodError: objects of type Vector{Int64} are not callable` is actually quite close to the requested  `Array{Float64,1} is not a callable function`, and makes it clear that `yticks` is a `Vector{Int64}` and not a function. 

Attempting to shadow any function you have previously used will also now error (rather than merely warn), as will attempting to shadow a function defined in the current module.

I suspect this is about as good a solution as is possible, so will suggest closing this as completed if no objections
