### ISSUE TITLE
should min(0.0, NaN) be NaN?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#7866]
I know this has come up before and we opted to go with Matlab's behavior, but it strikes me that NaN poisoning really might be safer. After all a NaN could be larger or smaller than any value.

**Comment by StefanKarpinski** [comment]
I say we go ahead with this in 0.6.

**Comment by simonbyrne** [comment]
We should probably have a function that gives the old behaviour for standards-junkies. numpy and matlab use `nanmin`.

**Comment by StefanKarpinski** [comment]
Eh, let's wait and see how much complaining there is first.

**Comment by StefanKarpinski** [comment]
E.g. https://github.com/mlubin/NaNMath.jl

**Comment by AgnerF** [comment]
FYI, this question is also discussed here: [https://stackoverflow.com/questions/49011370/nan-propagation-and-ieee-754-standard/49040225]. 
I agree that a global state does not work well with parallel processing. Now that more and more platforms support vector processing, it is better to rely on NAN propagation than fault trapping because you can have multiple faults simultaneously in one vector. In my opinion, min and max should propagate NAN always.

**Comment by StefanKarpinski** [comment]
That's good to hear 👍 – that is what Julia does these days.
