### ISSUE TITLE
export keyword in front of functions / types

### ISSUE THREAD

**Issue by tknopp** [JuliaLang/julia#8005]
This came up on the mailing list and having worked on Gtk.jl (see https://github.com/JuliaLang/Gtk.jl/blob/master/src/long_exports.jl) I think it would be a good thing to allow writing

```
export type MyType
    x::Int
end

export myfunc(m::MyType) = m.x
```

Don't know if it causes issues that `export` operates on methods rather than functions.

**Comment by davidmanzanares** [comment]
+1 to this idea. This would make it closer to ES6 modules (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export) and it would reduce the number of lines avoiding noise in my opinion.

Regarding the utility of having a single place to look upon the exposed functions, I think this is useful when the exported functions are the API of a library, but I think that for application code the proposal is more convenient.

**Comment by tk3369** [comment]
I love this idea too. 

Is it possible to export only the specific functions that are marked export, taking into account the complete signature?  That would solve the include/exclude-all issue above.

**Comment by StefanKarpinski** [comment]
All that's required to make this happen is someone hacking the parser to make it happen.

**Comment by dalum** [comment]
If anyone is interested, I made a small package that provides an `@export` macro here: https://github.com/dalum/InlineExports.jl

**Comment by c42f** [comment]
For what it's worth I'm not really in favor of this; it seems a little frivolous as surface syntax when a macro achieves the same thing with one extra character to be typed.

If people do really want the functionality, why not just add `@export` to the standard library rather than the parser? That should be strictly more conservative than adding it as actual language syntax.

(I also happen to like the up-front export list which has become the convention in package source and it can be a nice opportunity to group the package's public API in a meaningful way for people who will be working on the code.)

It's worth also considering Jeff's points here: https://github.com/JuliaLang/julia/pull/36474#issuecomment-651380656

One final point — I feel like exports are kind of a big deal and should deserve some careful thinking by package authors. So it might be ok to not have the utmost convenience in their syntax :-)

**Comment by tknopp** [comment]
I don't buy that argument. If `export` is a special keyword, it is an additional thing to remember whether an `@` in-front of it and sometimes not. I favor consistency here.

**Comment by StefanKarpinski** [comment]
True, but one doesn't _need_ the ability to export functions by doing `export function` instead of separately. If that was clearly a desirable feature, then sure, we should do this instead of `InlineExports` but I think the deeper question is whether it's desirable or not in the first place.

**Comment by tknopp** [comment]
yep, that was kind of my point. Either this is a feature we want, then please let's use consistent naming. Or don't implement it at all. 

Nowadays I am not so certain anymore. When reorganizing code and removing functions it happens regularly that I miss also to remove the export. But on the other hand this feature is not so important to be personally that I would dependent on another package just to have it.

**Comment by DavidSagan** [comment]
+1 to this idea.

**Comment by LilithHafner** [comment]
Triage agrees with @c42f https://github.com/JuliaLang/julia/issues/8005#issuecomment-660077430
