### ISSUE TITLE
Rename abstract numeric types like FloatingPoint and Complex?

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#8142]
We've seen empirical evidence that new users sometimes use abstract numeric types like `FloatingPoint` or `Complex` in lieu of concrete types like `Float64` and `Complex128`. The result is that users end up with slow code or even wrong code due to operations over variables with types like `Array{Complex,2}` or `Vector{FloatingPoint}`. (For example: [this comment](https://github.com/JuliaLang/julia/issues/4796#issuecomment-28459235) in #4796)

The unintentional use of abstract numeric types seems especially prevalent with `FloatingPoint` or `Complex` which share common prefixes with concrete types. Other abstract numeric types like `Signed` or `Real` do not seem prone to accidental misuse to the same extent.

Suggestions for new names? I'd propose something like `FloatingPointAbstract` or `AbstractFloatingPoint` to emphasize the abstract nature of the type. And perhaps something like `ComplexCartesian` instead of `Complex` to emphasize the canonical (real, imaginary) representation and to distinguish it from polar forms or other more esoteric representations.

**Comment by Sisyphuss** [comment]
Since in Julia, only leaf nodes are concrete types, presenting the type tree to users will largely solve the problem. (In fact, I just wanted to say that I want this type tree, but cannot find it.)

**Comment by lostanlen** [comment]
@Sisyphuss here you go:
```
include(replace(JULIA_HOME, joinpath("usr","bin"), joinpath("examples","typetree.jl")))
TypeTrees.print_tree(TypeTrees.types_tree)
``

**Comment by Sisyphuss** [comment]
@lostanlen Thanks for your humor! I think that users would prefer a concise, portable and visible typetree that could be used as a reference card.

**Comment by nstiurca** [comment]
I came late to the party, so several comments and thoughts:

I would like to have `Real <: AbstractComplex` despite @JeffBezanson's protests. After all, any function that wants a complex should work given a real input, just as a function that wants a `Real` is perfectly happy with an `Int` even though as Jeff would put it "Ints are not Reals, they are just embedded in them". Why should we separate complex values from the rest of the `Number` type hierarchy?

Regarding the abstract-ness of `Complex` (and `Array`, etc) and how many Julia users don't realize the type is abstract, how about requiring a trailing pair of braces to be explicit about the fact that the type is parametric? For example, instead of being able to simply type `Complex`, require `Complex{}`, or maybe even `Complex{?}` to be even more explicit that the parameter(s) is/are unknown. This would be a pretty far reaching change throughout the language, and maybe deserving of its own issue. I haven't even slept on it yet, so it's a very premature thought on how to solve this problem.

I think the `Abstract` prefix is fine despite the verbosity and I think it was a good change in v0.4. (If anyone is really offended by the extra keystrokes, they are free to `typealias` to something shorter in their own codebase.)

For what it's worth, I find `Integer` and `Int` as defined to be both useful and sometimes confusing. :-S

**Comment by nstiurca** [comment]
Also, +1 for having `AbstractComplex` and `PolarComplex`.

**Comment by toivoh** [comment]
Sure, a function that takes a complex value can always take a real value instead, but what if you have a function that accepts an `Array{T}` where `T <: AbstractComplex` and writes to it?

I think it does make sense to be able to talk about the set of types that do not only represent complex numbers, but are able to represent more or less any complex number (up to precision).

**Comment by nstiurca** [comment]
Then you get `InexactError`, which is business as usual. We already have something like this within the `Real` type tree.

    bar!{T<:Real}(a::Array{T}) = copy!(a, rand(Float64, size(a)...))  # copy some none-integers into a
    fArr = Array(Float32, 3,4); bar!(tArr)                                            # OK: double -> float conversion
    rArr = Array(Rational, 3,4); bar(rArr)                                           # OK: rational approximation
    iArr = Array(Int, 3,4); bar!(iArr)                                                    # InexactError()

**Comment by Ismael-VC** [comment]
@Sisyphuss [here](http://es.scribd.com/doc/271871142/Julia-Type-Hierarchy) is a GraphViz based plot of v0.3.10 by @jbn, [here](http://git.io/vRQ1V) is the code he used, it would be nice if we could automatically provide similar plots updated and linked in the documentation.

**Comment by Sisyphuss** [comment]
@Ismael-VC it seems to me that he used Julia to write a Graph data object (a sort of metaprogramming). IMHO, his code can be directly used in a v0.4 kernel and produce a correspondent v0.4 type graph.

**Comment by Ismael-VC** [comment]
@Sisyphuss it's done with Graphviz, but I don't know much dot foo, this: [julia_0.4.1_type_hierarchy.pdf](https://github.com/JuliaLang/julia/files/57463/julia_0.4.1_type_hierarchy.pdf) graph looks too crowded, I'll try to make it better. Acrobat reader doesn't render this file for me (too big I guess?), but Chrome does! If this can be prettyfied, I'd like to add them to the documentation somewhere.

**Comment by Sisyphuss** [comment]
@Ismael-VC it can be opened by other application such as *evince*. To make it pretty, maybe it will help to divide the tree to subtrees at the first level.

**Comment by iagoba** [comment]
I vote +1 for `A` prefix. It stands for `Abstract` as well as for "a" the indefinite article. They could be easy to read as "a complex" or as "a real". And `A` is short enough to implement.

This lead me to think on "an integer". Should it be `AnInteger` the abstract type for integers? I don't know what to think about this. It could be good for new people to find abstract types like...
```
AComplex
AFloat
AnArray
AMatrix
AnInteger
```
Don't know... You can skip this idea ;-p

Definitely to stress the fact they are abstract is a huge improvement

**Comment by quinnj** [comment]
Should we close this? We made the change to `AbstractFloat` and I think the consensus was everything else could stay the same.
