### ISSUE TITLE
ARM nightlies

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#8359]
It would be nice to have ARM nightlies for Ubuntu in the julianightlies PPA, if such a thing is possible. For people running on underpowered boards, this should be an easy way to get Julia rather than building it for hours.

Cc: @staticfloat

**Comment by ViralBShah** [comment]
@staticfloat Is this the right place to see what's happening with the arm builds?

https://launchpadlibrarian.net/200186425/buildlog_ubuntu-precise-armhf.julia_0.4.0-1956~ubuntu12.04.1_BUILDING.txt.gz

**Comment by staticfloat** [comment]
Yep!  That's the place.  Looks like I've got some tweaking to do still.
-E

**Comment by staticfloat** [comment]
Okay, I've made [some tweaks](https://github.com/staticfloat/julia-debian/commit/783d4bdbc524ad458e3015756a847c200a44463f) to the debian packaging rules, we'll see if we get past the dependency verification point now.

**Comment by ViralBShah** [comment]
It is now dying on the Rmath dependency. Best to let it just build that if possible. Looks like the amd64 build is also failing.

Also, you have to include ARM.inc in the Make.user for things to build. Perhaps we should completely integrate the ARM build in the Makefile as there are enough people trying things out.

**Comment by ViralBShah** [comment]
With #12310 it is now possible to do `make binary-dist` on arm. In earlier trials of mine, the resulting tarball was unusable as julia would segfault (although I had not had a chance to figure out why). Now, I can use the resulting tarballs on other paths on the same machine, and I feel that we may just have enough things in place to start doing ARM nightlies.

Would the simplest thing to do for now be to just build them on my computer and upload them to s3? Perhaps a cross-compiled one may be the better way to go.

**Comment by staticfloat** [comment]
@ViralBShah we could try that.  Launchpad is trying to build them, but as usual, there are little problems with the build system that cause them to fail.  For instance, now that we're trying to build LLVM 3.6.1 on ARM (which isn't bundled with the typical source upload package) it [tries to download](https://launchpadlibrarian.net/212149319/buildlog_ubuntu-vivid-armhf.julia_0.4.0-2515~ubuntu15.04.1_BUILDING.txt.gz) them and fails.  If you want to experiment with doing our own arm builds, I'm totally okay with that.

**Comment by ViralBShah** [comment]
I can set up a crontab on my chromebook to upload binaries nightly - not very reliable, but will at least get us going. What should I do to upload?

**Comment by staticfloat** [comment]
You should install the [`aws` command line utility](http://timkay.com/aws/), putting your AWS credentials into `~/.awssecret`, as appropriate so you can login.  Then, go ahead and run something like:

```
aws put --fail --public julianightlies/bin/linux/armhf/<major_version>/julia-<version>-<shortcommit>-linux_armhf.tar.gz <localfile>
```

Where the parameters can be found inside Julia as:
```
major_version = "$(Base.VERSION.major).$(Base.VERSION.minor)"
version = "$(Base.VERSION)"
shortcommit = "$(Base.GIT_VERSION_INFO.commit_short)"
```

These should result in URLs that look similar to:
```
https://s3.amazonaws.com/julianightlies/bin/linux/x64/0.4/julia-0.4.0-9b789b8c9a-linux64.tar.gz
```

All this assuming that the architecture is actually `armhf`, that is.

**Comment by ViralBShah** [comment]
I will try set this up next week.

**Comment by PallHaraldsson** [comment]
I see all arm builds have failed here:

https://launchpad.net/~staticfloat/+archive/ubuntu/julianightlies/+packages

is it (still) because of a time limit? Is there a link to a binary (any one, could be not brand new) that I've not found) or would I have too look into "the aws command line utility" (or compile myself..)?

**Comment by staticfloat** [comment]
It's because the ARM build requires a different version of LLVM than the normal ones, and that version of LLVM isn't being bundled in the source tarball properly right now.

**Comment by staticfloat** [comment]
I've attempted a fix here: https://github.com/staticfloat/julia-buildbot/commit/efe9f8b76be046c508a3d98e5cc98921d5af95fd

**Comment by staticfloat** [comment]
I will note that we've got some ARM builds that have made it much farther than any previous attempt right now; but they've been going for 6+ hours and aren't even done compiling LLVM.  I fully expect Canonical to tell me to knock it off, especially if we attempt to build these ARM binaries with the same frequency as the non-ARM binaries (e.g. every day).  It may be the case that we really do just need to make `armhf` tarballs instead of trying to have a PPA.

**Comment by nalimilan** [comment]
@staticfloat Couldn't you build LLVM as a separate package so that you don't need to do that everyday?

**Comment by ViralBShah** [comment]
Tarballs are always preferable. Also, you could try using the stock llvm 3.6.1 binaries if they have those for the ppa.

**Comment by ViralBShah** [comment]
I am wondering if we should bother with PPAs in general, given that they always end up using dependent libraries that have known bugs, which are fixed in the tarballs.

**Comment by nalimilan** [comment]
Well, packages are the way Linux users expect to get their software, and they offer automated updates which would be relatively painful to do manually when you don't follow Julia's development very closely. (Though this doesn't really apply to ARM at this point, given that it's not completely stabilized.)

**Comment by staticfloat** [comment]
Welp, it doesn't matter either way, since building LLVM currently fails with:
```
/«PKGBUILDDIR»/deps/llvm-3.6.1/lib/Target/ARM/Disassembler/ARMDisassembler.cpp:11:45: fatal error: MCTargetDesc/ARMAddressingModes.h: No such file or directory
 #include "MCTargetDesc/ARMAddressingModes.h"
                                             ^
compilation terminated.
```

But in general, I agree with @nalimilan that distribution packages are a nice way to make Julia available.  Currently, we are dodging the "old library" issue by bundling a bunch of .tar.gz files in the source .tar.gz that we upload to Canonical's buildd servers.  That's not a great solution, global warming-wise, since that means we do things like build LLVM every day.  If we were the ones actually building the `.deb`'s, we could build them the exact same way that we build any other binary, which (if we end up needing to build our own `armhf` binaries) is probably what we'll have to transition towards.

**Comment by tkelman** [comment]
We have them now: https://status.julialang.org/download/linux-arm

**Comment by nalimilan** [comment]
Cool. Should they be listed at http://julialang.org/downloads/?

**Comment by ViralBShah** [comment]
+1

**Comment by ViralBShah** [comment]
Added to the website in the nightlies section. Perhaps we should have a separate arm section altogether, but for now, it's linked.
