### ISSUE TITLE
integer arithmetic overflow

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#855]
To deal with integer arithmetic overflow we do the following:
1. add checked integer arithmetic intrinsics named `checked_add`, `checked_mul`, etc.
2. have a compiler switch that uses these everywhere.
3. write a `@check_overflow` macro that transforms an expression to turn `*` into `checked_mul` and `+` into `checked_add`, etc., but only in the expression — called functions are on their own.

**Comment by StefanKarpinski** [comment]
```jl
julia> sqr(x) = x^2
sqr (generic function with 1 method)

julia> @code_native sqr(123)
	.section	__TEXT,__text,regular,pure_instructions
Filename: none
Source line: 1
	pushq	%rbp
	movq	%rsp, %rbp
Source line: 1
	imulq	%rdi, %rdi
	movq	%rdi, %rax
	popq	%rbp
	ret

julia> checked_sqr(x) = checked_mul(x,x)
checked_sqr (generic function with 1 method)

julia> @code_native checked_sqr(123)
	.section	__TEXT,__text,regular,pure_instructions
Filename: none
Source line: 1
	pushq	%rbp
	movq	%rsp, %rbp
	pushq	%r15
	pushq	%r14
	pushq	%rbx
	subq	$40, %rsp
	movq	%rdi, %r14
	movq	$6, -64(%rbp)
Source line: 1
	movabsq	$jl_pgcstack, %rax
	movq	(%rax), %rcx
	movq	%rcx, -56(%rbp)
	leaq	-64(%rbp), %rcx
	movq	%rcx, (%rax)
	xorps	%xmm0, %xmm0
	movups	%xmm0, -48(%rbp)
	movq	$0, -32(%rbp)
	movabsq	$4619782280, %rax       ## imm = 0x1135C4888
Source line: 1
	movq	(%rax), %rbx
	testq	%rbx, %rbx
	je	L218
	movq	%rbx, -48(%rbp)
	movabsq	$jl_box_int64, %r15
	movq	%r14, %rdi
	callq	*%r15
	movq	%rax, -40(%rbp)
	movq	%r14, %rdi
	callq	*%r15
	movq	%rax, -32(%rbp)
	movq	-8(%rbx), %rax
	shrq	$2, %rax
	cmpq	$1141923900, %rax       ## imm = 0x4410603C
	je	L176
Source line: 1
	leaq	-48(%rbp), %rsi
Source line: 1
	movabsq	$jl_apply_generic, %rax
	movabsq	$4591455440, %rdi       ## imm = 0x111AC0CD0
	movl	$3, %edx
	callq	*%rax
	jmpq	L190
L176:	leaq	-40(%rbp), %rsi
	movq	%rbx, %rdi
	movl	$2, %edx
	callq	*(%rbx)
L190:	movq	-56(%rbp), %rcx
	movabsq	$jl_pgcstack, %rdx
	movq	%rcx, (%rdx)
	addq	$40, %rsp
	popq	%rbx
	popq	%r14
	popq	%r15
	popq	%rbp
	ret
L218:	movabsq	$jl_undefined_var_error, %rax
	movabsq	$13174591616, %rdi      ## imm = 0x311445080
	callq	*%rax
```

While it's possible we could do a better job with the checked version, you'll note that throwing errors on really basic integer operations is a performance trap, even for things like `^`. People write `x^2` all the time, expecting it to be equivalent to writing `x*x`.

**Comment by ScottPJones** [comment]
@keno Where does that `checked_mul` live?
I'm interested in using a checked version of the arithmetic, because for certain financial and medical applications, I think doing unchecked arithmetic can be legally dangerous.  That's also where decimal arithmetic is frequently necessary... correctness is much more important than raw speed.
(round(.70*.05*100) shows a very simple case where binary arithmetic can get you in trouble with the tax man...)

**Comment by PallHaraldsson** [comment]
@ScottPJones "I'm interested in using a checked version of the arithmetic, because for certain financial and medical applications, I think doing unchecked arithmetic can be legally dangerous."

This issue is only about integer overflows. Should be easy enough to do as a separate type (BigInt is also an option), that could be built out of regular integers (or even from below or binary floating point..):

See also:

https://github.com/stevengj/DecFP.jl

[Seems you have to call xchk to check for overflow to get it thrown. [I'm not sure, I think ordinary binary floating point may be similar.]]

This one is arbitrary precision.. so you wouldn't get overflows.. only possibly out-of-memory errors:
https://github.com/tinybike/Decimals.jl/blob/master/README.md

**Comment by johnmyleswhite** [comment]
@PallHaraldsson: Please do not comment on issues like this to offer your two cents. You are e-mailing dozens of people unnecessarily.

**Comment by eschnett** [comment]
I recently got bitten several times by accidental integer overflow. I implemented `@fastmath` in the past, and my first idea for implementing `@checked` would be along the same lines, throwing `InexactError` if things go wrong. Is this still a good idea?

My motivation is:
- Do something now, without waiting for efficient LLVM intrinsics
- Safety first, I'm willing to pay a speed penalty for this
- By default, don't change the current behaviour
- I don't want to rewrite code, so `SafeInt` etc. wouldn't work for me

**Comment by StefanKarpinski** [comment]
@eschnett, are you saying you want something dynamically scoped? I don't think we can do that right now because there are legitimate usages of overflow, e.g. the [classic `>>>` midpoint trick](https://github.com/JuliaLang/julia/blob/master/base/sort.jl#L97) see also http://googleresearch.blogspot.com/2006/06/extra-extra-read-all-about-it-nearly.html. Arguably, addition with intentional overflow should be a separate operator so that we can distinguish these cases.

**Comment by eschnett** [comment]
@StefanKarpinski No, I'm thinking of static scoping. The `@checked` macro would convert operations in its argument e.g. from `*` to `checked_mul`. This is how `@fastmath` is implemented -- I think that's different from `@inbounds` which sets a global codegen flag.

Over time, I can also imagine explicitly annotating all places where overflow is expected and harmless; this would then allow using a command-line option to switch over all of Julia.

**Comment by JeffBezanson** [comment]
What, if anything, should we do for 1.0 here? Seems like it can be moved out of the milestone.

**Comment by timholy** [comment]
Seems like some folks want a way to turn this on for all arithmetic operations, which formerly might have meant a new startup flag `julia --check-overflow`. But now that #265 is fixed, it theoretically seems like this could be solved which a package (and thus removed from the 1.0 milestone), though I note that
```julia
eval(Base, quote
     (+)(x::T, y::T) where {T<:BitInteger} = checked_add(x, y)
     end)
```
results in a StackOverflow due to the use of an increment in tuple iteration/destructuring. I suspect it could be resolved by having tuple iteration call an intrinsic directly, but that's just a guess. Clearly the package would have to be structured with care.

**Comment by StefanKarpinski** [comment]
What you really need to support this is a way to express that you really *want* to do overflowing arithmetic, e.g. in the classic `(lo + hi) >>> 1` computation in binary search or quicksort. However, that seems like a feature that can be added post 1.0 as can a hypothetical `--arithmetic-overflow=[wrap|error]` option (or a package). It might be a good idea to turn checking on by default during testing like Rust does; that would entail carefully going through Base Julia and using intentionally wrapping overflow in the places where we mean it, of course.

**Comment by JeffBezanson** [comment]
Seems like we're unlikely to change the default behavior, and the rest of the ideas here can be new features, even in packages --- a `@check_overflow` macro, a wrapper type that provides checked arithmetic, a way to annotate operations expected to overflow, together with options for enabling checking everywhere else for testing.

**Comment by ronisbr** [comment]
Just one question:

How difficult / feasible / sensible is to implement the following:

Add a macro so that every integer operation that will overflow has their arguments promoted to a Integer representation with a higher bit number before execution?

So, if I am using in my code things like:

```julia
f = C1*Δt^2 + C2*Δt^3
``` 

where the user can pass a very big integer number to `Δt`, then I can add this safe measurement to avoid incorrect computations.

**Comment by StefanKarpinski** [comment]
It's easy but all your code will be very slow.

**Comment by mbauman** [comment]
There's a package that does this — [SaferIntegers.jl](https://github.com/JeffreySarnoff/SaferIntegers.jl).  It also has a macro (`@safeints`) — but its docstring is a little confusing since it hasn't been totally updated (it may be helpful to know that it is a modified version of https://github.com/stevengj/ChangePrecision.jl, so that's why there's stuff about floating point there).

**Comment by oscardssmith** [comment]
This seems closable.
