### ISSUE TITLE
functions multiply like constants

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#8763]
I'm not sure how to label this issue, but you can use a function as a multiplier just like a constant:

```
julia> sqrt(16)2
8.0
julia> sqrt(16)sqrt(4)
8.0
```

Is this purposeful?  This seems strange.

**Comment by JeffBezanson** [comment]
I've fixed `x 'y` and `x' y` to both give errors.

I also disallowed `sqrt(16)2`, since it would be overly obscure to write that instead of `2sqrt(16)`. However `sqrt(2)im` is still allowed. I'm inclined to leave things this way, since that syntax is pretty compelling and I suspect it could break a lot of things to remove it.
