### ISSUE TITLE
formatting conventions for function documentation

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#8966]
Right now, the `@doc` help suggests;
```
  @doc """
    # The Foo Function
    `foo(x)`: Foo the living hell out of `x`.
  """ ->
  function foo() ...
```

In method documentation, wouldn't it be much more satisfactory () for the `help` command to automatically prepend the signature for `foo` before the documentation output as needed?

In generic-function documentation (e.g. documentation for `sum` in all its forms), obviously this is not possible (since there will in general be multiple possible signatures).   However, we should establish some convention for what the documentation should look like.

**Comment by jiahao** [comment]
In #9447 @MichaelHatherly @one-more-minute @hayd very kindly humored me as I ranted about the features I wanted in documentation.

I have just reformatted in [IterativeSolvers: rlinalg.jl](https://github.com/JuliaLang/IterativeSolvers.jl/blob/master/src/rlinalg.jl) and [rsvd.jl](https://github.com/JuliaLang/IterativeSolvers.jl/blob/master/src/rsvd.jl) the documentation of `rsvd`, `rnorm`, `reigmax`, `reigmin`, `rcond`, `IterativeSolvers.rrange`, `IterativeSolvers.rrange_si`, `IterativeSolvers.rrange_adaptive`, and other functions comply with the new `@doc doc "" ->` format.

It's really nice to see help for functions I wrote!

I hope my usage here helps clarify why I would like inline cross-references, equation rendering and bibliographies.

**Comment by hayd** [comment]
I was having a play trying to put together a MetaDoc type a'la @stevengj in https://github.com/JuliaLang/julia/issues/8514#issuecomment-57331690 and https://github.com/JuliaLang/julia/pull/8588#issuecomment-60244983, it doesn't seem to play well with `@doc` I think this is since you can't override mdify (but no doubt I'm missing something)....

Anyways a gist is here: https://gist.github.com/hayd/bdddb51dc7df89b9a24e

*Thinking about it may be that you could just extract sections from the text i.e. lower @jiahao's docstrings into MetaDoc... (kind of [docopt](http://docopt.org/)-style).*

There's some discussion about Returns section (and how you could use this) in PR to prepend signature info to the help message: https://github.com/JuliaLang/julia/pull/9838.

**Comment by hayd** [comment]
I hadn't realised that Docile has a [meta object](http://michaelhatherly.github.io/Docile.jl/api/docile/), but that didn't make it to base.

@MichaelHatherly IMO Docile.meta ought to be in base, having two levels of documentation (one in Base and one in Docile) seems strange. getting it in base would help flesh out what meta is and get it working (e.g. it doesn't work with help for me in 0.4 - following the examples in the readme :( ). Pretty please can we have meta!

**Comment by MichaelHatherly** [comment]
@hayd, I think I might have added `meta` some time after the @one-more-minute's initial docs pr, so that's probably why it got missed.

From the looks of your gist that's basically all there. Not sure about the rendering trouble you're having; @one-more-minute is the best person to ask about that. Some differences I can see: naming (I can easily change names in Docile if we settle on `MetaDoc` rather than `meta`), the meta entries are stored as a `Dict{Symbol, Any}` rather than `Vector{Pair}` in Docile. I think the `=>` syntax is 0.4 only if I'm not mistaken, in which case I can't really support it in Docile.

**Comment by hayd** [comment]
@MichaelHatherly You may be able to use the [compat module](https://github.com/JuliaLang/Compat.jl) to support 0.4 syntax on 0.3.... ?

TBH I'm not sure what syntax is best here going forward anyway, perhaps others have some ideas, but :100: to getting meta in. :)

**Comment by one-more-minute** [comment]
I want to point out that extensions, like `meta`, can both live in external packages *and* be first-class parts of the doc system. In fact, this was a key design goal; I don't want to mandate how documentation is done so much as allow people to do whatever they might need. There are other advantages to keeping the non-core functionality in packages, too, like the fact that you can release updates whenever.

So once 0.4 is out there's really no reason Docile.jl can't be compatible with it. I'm sort of hoping it will live on as a way to have all of the great "advanced-mode" doc features that it currently supports.

**Comment by prcastro** [comment]
I've been writing some docs with this system and, alongside metadata, I would find very useful to have a way to insert the function's signature into the docs automatically. Actually, the same for constants (insert their types into docs), types (insert their supertypes), macros and generated functions, etc. Maybe something like:

```julia
@doc """
$signature$

Foo the living hell out of an Int
""" -> function foo(x::Int)
```

So that:

```
julia> ?foo(10)
foo(Int)

Foo the living hell out of an Int
```

Also, I really believe metadata for docs should be on Base. This would incentive developers to write richer documentation from start, while guaranteeing good documentation on how to do this, and a single stardard way to do it.

**Comment by hayd** [comment]
There;s been some major changes to Docile of late, which parses

```
"docstring with *markdown*"
function f(); end
```
*even* if there's no `using Docile` in the package/file. It can even do this on base! see https://github.com/MichaelHatherly/Docile.jl/issues/56#issuecomment-108759557

I think there is an issue about signature (and I had a PR rejected), IMO it should __always__ be shown. `$ wouldn't work as it's already used for latex, but there may be some other options for similar things...

I think the metadata will work itself out, now that Docile doesn't need `using`... most packages use `### Arguments` or `#### Returns`, so these could be silently extracted into metadata (if there was some benefit to do that). When base moves to markdown this convention should be followed.

**Comment by ScottPJones** [comment]
Well, why not just use the javadoc/doxygen/etc. tags (they are pretty standard), instead of coming up with something julia specific?

```julia
##\brief Brief description here
#
# detailed description
# \param[in]    str::AbstractString  String to be munged
# \param[out]  buf::Vector{UInt8}  Output buffer
#
# \returns        Bool   if string was valid or not
# \throws         ArgumentError  (if str is empty)
```

Doxygen supports Markdown, and the comments can be easily filtered to remove the `\` and colorize the param, etc. tags, and remove totally the `\brief` tag...

I think this would be better than everybody coming up with their own incompatible style, which is what is going on now...

**Comment by prcastro** [comment]
Parsing markdown to extract metadata sounds awesome. We could parse anything before an (sub)title as a overview end xtract other section based on title names. For parameters, I believe we should have a standard way to do it, maybe a markdown list of parameters and their types/descriptions:

```
### Parameters
* x: A number to be fooed
* `y`: Simply *anything*
```

Would get us something like:
```julia
:parameters => [:x => "A number to be fooed", y: => "Simply *anything*" ]
```

We could also, later, use the upcoming Ordered Dicts to make an order about these parameters. An IDE could, then, use this info (alongside function's signature) to provide tooltips for each parameter as we type them (like their types and descriptions).

**Comment by ScottPJones** [comment]
Yes, but just using the \param tag, with the optional [in], [out], [in,out] attributes, makes it really easy to pull out all of that and create the metadata, for \returns and \throws as well.

**Comment by ScottPJones** [comment]
Instead of an OrderedDict, what about the NamedTuples that I've heard about?

**Comment by prcastro** [comment]
This may work, but I'd prefer not to add new syntax just to obtain metadata.

**Comment by one-more-minute** [comment]
@prcastro Yes, something like this would work well. The more I think about it the more I dislike the idea of specialised syntax like doxygen/javadoc.

I mean, I get it – we're programmers, and making things precise enough that computers can parse and manipulate them just Feels Right. But doc strings *have* to be designed for humans first – and humans, particularly ones new to programming, are a lot more comfortable with paragraphs of text than noisy syntax trees.

On top of that, we already have two syntaxes – Julia and Markdown – and we should be able to use them to specify anything we want (in the limiting case, splicing a metadata dict into the docstring, for example). As long as structured data is a nice-to-have rather than a make-or-break, there's no way to justify adding a third syntax for people to learn on top of that.

**Comment by prcastro** [comment]
Exactly, things become even more difficult to the enduser when you add more syntax. Afterall, people searching for that kind of power could find it on Docile. Base should have just a simple metadata system, that is as natural and as unobtrusive as possible to newcomers.

Would the overhead of parsing markdown to obtain metadata be a problem?

**Comment by one-more-minute** [comment]
I don't think so – we already parse markdown to display it so it's just a case of looking over the structure for patterns. Should be pretty easy, really.

I should clarify also that what Base does doesn't prevent anyone using doxygen or whatever if they really want. You can just use your own string macro:
```
dox"..."
foo ...
```

**Comment by ScottPJones** [comment]
@one-more-minute Ha!  I already have a dox"..." macro!  Might I say, "great minds think alike"? :grinning:

@prcastro You'd still have to come up with some new syntax to say if something is a parameter, a return value, or what errors are thrown... my point is simply, there is *already* a syntax that is pretty much a de facto standard, why not use that?  I think a lot of people would probably be at least familiar with it.

I guess, if you actually do make sure that everything is correctly parsed, and you can produce the metadata for: brief description, full description, parameters, return value(s), and errors thrown,
then to support doxygen (or any other documentation tool), you could just output the metadata converted to the doxygen rules... (along with all the other information it needs, like what line the method is on, the method signature, what functions it calls, etc).
I'd drop my push for doxygen specifically, *if* somebody does get a standard for at least those "tags" in place, *and* is able to show a working parser that collects all of the metadata.
Finally, what were you thinking for type or enum fields?  That's handled by doxygen (and for me, is the second best benefit of using the tool... you simply put `##<` instead of `#`, or """<...""".
I suppose dox"..." would be enough to indicate it needs to be passed to doxygen, as long as it can pick up the context (i.e. that it is in a type, immutable, or enumeration declaration, the name of the field, the name of the type, and the file name and line number)

**Comment by StefanKarpinski** [comment]
For what it's worth, I'm 100% with @one-more-minute on this – adding doxygen syntax to the mix is causes more problems than it solves – and we want to support people before machines. The issue with generic documentation systems like doxygen is that they never *quite* do what you need, so you end up in this close-but-no-cigar situation until you throw in the towel and build/design something custom that's really tailored to your specific needs. Julia is unusual enough as a language that the chances of something "standard" like doxygen working really well for it seems negligible.

**Comment by ScottPJones** [comment]
You maybe missed my comment elsewhere, I am also now 100% behind @one_more_minute's excellent idea of parsing the meta data out of the doc strings, from which I could generate a file in a form doxygen could understand, to get all the x-references out of the code, even x-referencing with the C source files in julia/src

**Comment by StefanKarpinski** [comment]
I wasn't addressing you specifically.

**Comment by hayd** [comment]
Extracting metadata from markdown has the benefit of a graceful failure. Also checkout https://github.com/MichaelHatherly/Lexicon.jl ...perhaps we can use that to build the docs in the future (*without* migrating it to base!!)

**Comment by JeffreySarnoff** [comment]
@alanedelman wrote 
"I've always wished one could click somewhere and find out about numerical notes"

Last night I put an http link inside of @doc inline function documentation. It half worked.
I was not able to use the usual markdown way [Read and Click This](http://to.go.here).
Writing the http address inside of the square brackets worked as a link, when I right 
clicked on it, a small menu popped up, "connect to  the site" was a choice and it did that.

**Comment by hayd** [comment]
@JeffreySarnoff  they're called autolinks. I did a PR for that a while ago. There's a way to go for full commonmark compat.

**Comment by JeffreySarnoff** [comment]
@hayd clearly appropriate

There is a watershed of benefit to Julia when, as one designs, experiments, codes, and dreams there are  co-available threads of insight to push and enagement to pull.  Soon there are others pulling and pushing through shared threads.  This self-magnifies, setting a place for Julia in many, many places.
