### ISSUE TITLE
slow searchsorted due to keyword argument

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#8991]
The [keyword argument](https://github.com/JuliaLang/julia/blob/d0a951ccb3a7ebae7909665f4445a019f2ee54a1/base/sort.jl#L219-L221) in `searchsortedfirst`/`searchsortedlast` causes a performance hit when used repeatedly, even when no keyword argument is used in calling:

``` julia
julia> X = randn(10_000_000);

julia> f(X)=Int[searchsortedfirst(-5.0:5.0,x,Base.Order.Forward) for x in X]
f (generic function with 1 method)

julia> g(X)=Int[searchsortedfirst(-5.0:5.0,x) for x in X]
g (generic function with 1 method)

julia> @time f(X);
elapsed time: 1.461309065 seconds (80144356 bytes allocated)

julia> @time g(X);
elapsed time: 2.445579336 seconds (640000128 bytes allocated, 12.64% gc time)
```

cf: #8952

**Comment by JeffBezanson** [comment]
Keyword arguments are no longer the problem here, but this has indeed gotten much slower.
v0.5: ~1.5 sec
v0.6: ~3.0 sec
v0.7: ~3.9 sec

**Comment by ViralBShah** [comment]
I now note with 0.7-alpha, that we are slightly better than 0.6.

**Comment by JeffBezanson** [comment]
Almost all of the time here is in constructing the range, probably because ranges have gotten much more sophisticated. In the case of 2-argument `:`, a lot of time is wasted computing `rat` and twice-precision division for a step of `1`. It might be worth special-casing that value in 3-argument colon.

I'll close this and open a new issue, since the part specific to searchsorted is fixed.
