### ISSUE TITLE
randbool() API 

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#9105]
Given that we have `rand(Bool)`, which is fully general, we can deprecate `randbool()`. Any reasons to keep it? Performance wise, there doesn't seem to be any difference either.

Cc: @rfourquet

**Comment by ViralBShah** [comment]
I like that too. Basically this now boils down to deprecating `trues`, `falses` and `randbool`, and doing nothing further. Will do so in the next few days, unless someone beats me to it.

@StefanKarpinski @JeffBezanson Thoughts?

**Comment by carlobaldassi** [comment]
I vote against removing the functions and forcing the usage of more general but verbose methods. I'm likely biased since I use these methods all the time, but I really don't see what's to be gained by removing them, at the cost of reduced code readability. I'd much prefer renaming them instead. The original `bitrand`, `bitones` and `bitzeros` which @ViralBShah suggested seem fine to me, even though the latter two used to make more sense when BitArrays were a parametric type. `bittrues` and `bitfalses` would also be ok. To be honest, the current `trues` and `falses` are also more or less ok in my opinion, but prefixing everything with `bit-` seems more consistent and explicit.

I'm not convinced by the argument for plain removal by @garborg:

>That sounds like maybe the nicest option for right now -- my hesitation is that as soon as there's one more container type that wants these functionalities, the export new names route will be a worse, less consistent option than just using `rand!(Container(dims))`, `fill!(Container(dims), false)`, etc., consistently for non-Array containers.

My objection is that BitArrays are, in the current state of affairs, one of the core types in Julia, since they are returned as the result of all element-wise comparisons, and thus are not like any other specialized container. So it doesn't seem unjustified to have specialized methods for constructing some common special cases. One more objection is that I don't expect to see many new array-like container kinds added to Base, while most new containers of such kind would added in packages, where it is perfectly reasonable to add specialized constructors for common cases (for example, if BitArrays were not in Base and I wanted to write a package to add them, I'd surely add those constructors - the fact of not having those methods *because* the container is in Base seems silly to me). Consider also that `spones` and `spzeros` also exist.

Finally, there are currently the functions `bitbroadcast`, `bitpack` and `bitunpack`. I don't see what's the problem in having 3 more `bit-` functions.

**Comment by ViralBShah** [comment]
I am ok with having many `bit*` methods. I just don't like the inconsistency of `true` being a `Bool`, but `trues` producing `BitArrays`, and `randbool` producing a BitArray instead of an array of Bools. 

I agree that it is unlikely we will add more containers to base.

**Comment by nalimilan** [comment]
I guess it would be OK to have both `bit*` methods (for the common cases), and the more general `rand!(Container(dims))` and `fill!(Container(dims), value)`.

**Comment by johnmyleswhite** [comment]
I think it's not a great idea to keep things like `bitones` and `spones` around when there's clearly a more consistent abstraction to be used instead. As one obvious example, we eventually need to support more kinds of sparse arrays in Base. By using `spones` to generate CSC format, we bless a certain format and thereby disincentivize using the other formats.

**Comment by carlobaldassi** [comment]
Probably `spones` is not the best parallel to make, and it also works somehow differently.

I think my argument boils down to this: `bitones` is useful for exactly the same reason for which `ones` is useful. I don't see any advantage in removing either, only (mild) annoyances.

**Comment by ViralBShah** [comment]
I don't see why `spones` can only generate the CSC format. It can easily take an optional argument to create other formats.

**Comment by garborg** [comment]
But at that point, wouldn't it be better to just make `ones` take that optional argument, and for `BitArray` as well?

**Comment by tkelman** [comment]
@garborg as was mentioned, `spones` is actually a bad example (and one of those annoyingly inconsistent Matlab-heritage names) in that it doesn't really do the same thing as `ones` - making a full matrix in sparse format is a pretty terrible idea and almost never a thing you want to do. `spones(A)` is more like `B=copy(A); fill!(B.nzval, 1.0); return B`.

**Comment by garborg** [comment]
Oops, thanks.

**Comment by ViralBShah** [comment]
Spones  is also used to make a sparse matrix of the same structure as another matrix in Matlab. I would be open to getting rid of it, of it can be merged into ones() and have a compact invocation.

**Comment by tkelman** [comment]
`spones` is getting off-topic for this issue, but I would avoid trying to cram it in to an optional API of `ones()` since it is not the same meaning. I do use `spones` somewhat often when I'm doing structure-only operations, `spones(spones(A)*spones(B))` is the most concise way I've found of getting the nonzero structure of a sparse matrix product without having to worry about possible cancellation. What would make more sense to me for structure-only operations is a sparse matrix type that is inherently structure-only, a graph of where the nonzero elements are but without any values associated with them (implicitly boolean).

**Comment by ViralBShah** [comment]
We do have `similar`, which is a much better name than `spones`. I agree that it is off-topic here. 

@carlobaldassi What about @rfourquet 's suggestion of having a type named `Bit`, that can be used as `ones(Bit, dims...)`. I would actually love that, compared to `bitones`, and it would be just as compact.

**Comment by rfourquet** [comment]
I wanted today to implement the `Bit` solution to have a better feel of it, so your message encouraged me to do so, cf https://github.com/JuliaLang/julia/compare/rf/Bit. I find it elegant that by only defining `Array(::Type{Bit}, dims)` and `zero(Bit)/one(Bit)`, you automatically get `rand(Bit, dims)`, `zeros(Bit, dims)` and `ones(Bit, dims)`. I think that this is my prefered solution. Instead of having those 3 specific methods (`randbool`, `trues`, `falses`), the specificity is factored out in one special type, and this sound better when writing generic code.

Moreover, I personally think that it's actually a good thing that the special treatment of `BitArray` is removed (I see no reason to favor `BitArray` over `Array{Bool}`, on the contrary). It is a little bit more verbose, but the user has to do a conscious choice (`ones(Bool, n)` or `ones(Bit, n)`?), instead of using the more concise `trues(n)` (the existence of `trues` gives the impression that this is the "prefered" way of getting a collection of `true`s). I guess this will lead to using `Array{Bool}` by default, as `Bool` is a more familiar type than `Bit`.

The `Bit` type should encapsulate a `Bool` if we wanted something like `fill(Bit(true), n)` to work, which may be useful in generic code, but seemed to me rare enough that more verbose alternatives (`fill!(Array(BitOrBool, n), true)`) are OK for when this occurs.

**Comment by carlobaldassi** [comment]
I'm sorry to be that guy, but I still don't understand what's the issue here:

1. Everybody agrees to remove `trues` and `falses`, for clarity. So that's a non-issue at this point; nobody's actually arguing for favoring `BitArray` over `Array{Bool}` (even though it is the de facto situation right now, since when element-wise comparisons are performed the result is a `BitArray`).
2. The `Bit` type is very weird to me, as it represents neither the element type nor the container type. It may be an elegant implementation, but I think it would be very confusing to explain. Basically, it's like adding a flag `container=BitArray` in the call to `ones` and similar functions, except that it's done in this strange way to work around type inference issues, conflating the element type and the container type. But the very possibility of conflating the two types is a peculiarity of the `BitArray` container, I think, so this does not seem like an extensible approach to me at all. It's also not really needed for writing generic code, since the `fill!` and `rand!` methods are available for that purpose; on the other hand, `ones` and similar functions are only relevant for convenience purposes.
3. I still don't get what's wrong with adding (or rather, keeping) three specialized convenience methods for a very specialized container, provided that their names make this fact clear.

Having said all this, it seems like I'm in the minority (probably since I'm a heavy `BitArray` user). So to conclude, I still favour renaming, followed by removing the functions (in which case I'll just write my own package with 3 `bit-` functions, and possibly blackjack and hookers...), and I'm very much against the introduction of the `Bit` type (unless convinced otherwise).

**Comment by StefanKarpinski** [comment]
I agree with @carlobaldassi. I'm not terribly bothered by the current API – BitArray is a special type and having special constructors for it seems reasonable to me.

**Comment by garborg** [comment]
It's more likely I'm in the minority and spoke too loudly, especially given the added exports tradeoff seems ambiguous to me with the current set of containers, so I won't push any more discussion. (Other than for what seems to be in agreement: no name `randbool(...)::BitArray`, `rand(Bool, ...)` returns `Array{Bool}`, no `bitrand()::Bool`).)

**Comment by ViralBShah** [comment]
I am ok with the special constructors for BitArray as well, but with more consistency that have a clear distinction from the Bool types.

**Comment by rfourquet** [comment]
The `Bit` type represents the type that `BitArray`'s elements would be if a one-bit size was possible. It can maybe feel a bit weird at first, but in usage it it's no more difficult to write `ones(Bit, n)` and `rand(Bit, n)` than `bitones(n)` and `bitrand(n)`. It's a "special" type, but which is handled essentialy in  `Array(Bit, n)` producing a `BitArray(n)`, which I find acceptable.

That it could be "elegant" is not important, but the useful thing in it is that it's less methods/implementations to maintain.
On the genericity, I meant for example that if I'm not sure what to choose between `BitArray` or `Array{Bool}`, I can have a method taking `Bit` or `Bool` as a parameter, and the all the underlying implementation is switched very easily. If I have to use `fill!/rand!` instead of `ones/rand` to generically test both alternatives, it's more work.
But I don't have a strong opinion on this, so won't try to push the `Bit` type more than that.

**Comment by ViralBShah** [comment]
I momentarily felt the temptation for the `Bit` type, but being neither the element type or container type as @carlobaldassi pointed out will create trouble later on.

For now, I am restricting my attention to my original goal - fixing the randbool API, which I have a PR for now.

**Comment by ViralBShah** [comment]
I am closing this with the randbool deprecation, which was the original topic of this issue.
