### ISSUE TITLE
Parallel Computing Planning Issue

### ISSUE THREAD

**Issue by alanedelman** [JuliaLang/julia#9167]
As we talk about parallel computing in various contexts, it might be handy to keep in mind
all the high level moving parts.   Here are some that come to mind, just to get the ball rolling.

Hardware
- [ ]   Shared Memory Machines (Threads: See #1790,  #1802)
- [ ]   Distributed Memory (especially networks of shared memory) (spawns, MPI?, migrating threads?)
- [ ]  GPUs? (we do/don't believe these are here to stay)

Tools
- [ ]  Nice Graphical Performance Tools and Instrumentation (My first wish: just
      have Green (working) / Red (idle) on every processor easily every time I do parallel julia)

Programming Models 
- [ ] Persistent Data as in Global Array Syntax  Darrays (Star-P and others)
- [ ] CILK/Spawns
- [ ] Map/reduce etc.

Communication Layers
- [ ] ZMQ, MPI, sockets

Schedulers
- [ ]  ??
- [ ] Does one master know all state?  
- [ ] Can our serial model be in conflict with various parallel models?

Libraries
- [ ] Scalapack, parallel FFTW?, sparse matrices, PETSc , (star-p like to compare
      with more pure julia  methods?)

**Comment by ChrislS** [comment]
Hi everybody!
As Julia is making great progress, it's becoming really interesting for the image processing. (Local) threading is really important here, though. I dug through the various discussions and found this discussion and the "threads" branch.

Apparently, the implementation in that branch is working. The basic tests are passing, though one test relying on the "Images" module currently doesn't work (since the Images module requires functionality available only in the latest Julia version, and I didn't go through a merge since it couldn't be done automatically). What are the plans regarding local parallelism? Are there any plans to merge the "threads" branch? It looks promising!

**Comment by timholy** [comment]
Other than a few experiments back in the very earliest days, I have not been involved in the threads branch at all. So take this with a big grain of salt.

I think it's fair to say that there certainly are plans to merge the branch. Guessing here, but presumably what it needs is (1) some free time for its principal developers (including one who needs to defend his thesis) to finish not-yet-implemented features or bug fixes, and (2) people kicking the tires. There's a chance you might be able to help the process along by doing that merge you described above and submitting a PR against the threads branch. If you are brave and willing to start using it in regular work, continued PRs against the threads branch would surely go a long ways to speeding the merger.

**Comment by StefanKarpinski** [comment]
The plan is to merge the threading work into master soon, but leave it off by default since it's still quite experimental. The main purpose of merging is to avoid continually rebasing when people make changes to the internals on master that break the threading functionality. That should make it easier for people to try out threading functionality even though it will still be experimental during the 0.4 cycle.

**Comment by ChrislS** [comment]
That sounds very good! I had a quick look on what the main merge problems were. A critical part of changes concerns the garbage collection, which is at the very heart of Julia and cannot be merged without quite some reading/knowledge of the internals.

**Comment by StefanKarpinski** [comment]
Yes, it's a pretty non-trivial merge.

**Comment by ViralBShah** [comment]
The GC patch was ready and tested, and merging it first meant that work remains to make it thread safe. As said before, we expect to have this in 0.4, even if disabled by default.

There is a `threading` branch that is more recent than the `threads` branch, which is updated to just before the GC merge. Cc: @kpamnany

**Comment by jakebolewski** [comment]
Does the `threading` branch work on OSX / Window's or is it Linux only for the time being?

**Comment by ViralBShah** [comment]
I don't think anyone has tried it on OS X. I wouldn't even dare try windows. I personally have only tried it on Linux, and I also see a few segfaults.

**Comment by kpamnany** [comment]
Haven't tried OS X or Windows, but the former shouldn't be too hard to get running. The threading infrastructure mostly needs only pthreads and atomics. There's an LLVM dependency, for thread-locals, but @Keno has a functional hack in an llvm-svn branch (I don't know if this is Linux-specific though). Getting this functionality into LLVM is another dependency.

Reentrancy in the runtime (specifically in the new GC) is the main block right now. And there are, of course, lots of functions in the standard library that need to be made thread-safe, or thread-safe versions added. Most crashes you'll find in the threading branch relate to such problems.

Lots more functionality to add, but it mostly works, and scales quite nicely. :-) See `test/perf/threads/laplace3d`.

**Comment by Keno** [comment]
The LLVM patch is Linux-only at this point, but give me a week or two.

**Comment by ChrislS** [comment]
Yes, the scaling is near perfect and the functionality looks very promising and impressive!

Do you have plans already for the variable sharing policy? I.e., what variables will be treated thread-local and when are variables syncronized between threads.

**Comment by skariel** [comment]
please consider [nanomsg](http://nanomsg.org/) it is by the same author and supercedes zeroMQ

**Comment by pao** [comment]
Julia already supports ZMQ--it's needed to communicate with IPython (Jupyter), so it's sensible to pursue. I think the transports are supposed to be pluggable, so if you're interested in a nanomsg transport, you're welcome to build it!

**Comment by garborg** [comment]
@skariel A sensible place to start: https://github.com/quinnj/Nanomsg.jl

**Comment by ChrisRackauckas** [comment]
What's missing is stupid easy parallelization of linear algebra. Almost every problem gets translated down to linear algebra, and even though Julia is fast, code is still faster in MATLAB simply because there are three lines that's required to make all matrix operations parallel on a 64 core node. Sure, I can play around with sending processes around and fetching and all that in Julia, but it's so much easier just to write the matrix operations, plop a code down that now runs all linear algebra operations in parallel, and have good enough MATLAB. I know that if Julia ever implements this, it will kill MATLAB in efficiency, I just hope it gets done sooner rather than later.

**Comment by IainNZ** [comment]
@ChrisRackauckas do you mean fusing multiple linear algebra operations? Because aren't all the basic linear algebra operations parallel already? As for for loops, we have `@parallel` already but soon enough we'll have `@threads` too.

**Comment by ChrisRackauckas** [comment]
Wow, turns out I was just wrong. When I last used Julia I don't remember this, but I just ran a simple test with multiplying two random matrices of size 10,000 x 10,000 and it did max all my cores. I think that it should be noted in the documentation (what other functions are parallel?).

Also, did not know about @parallel.

FYI, hearing this (and noticing that MATLAB's native parallelization doesn't come close to using the full power of my machine...) finally makes me a convert.

**Comment by IainNZ** [comment]
Not sure which operations exactly, but basically "linear algebra on Float64s" for sure. Definitely check out the manual, it covers the parallel computing functionality of Julia pretty well - PRs welcome for improvements as well. CUDA support isn't a base Julia issue (IMO) given its dependent on an external closed source library, but there is [JuliaGPU/CUBLAS.jl](https://github.com/JuliaGPU/CUBLAS.jl) which is getting there for higher level abstractions: (also contributions welcome there, I'm sure)
```julia
    A = rand(elty,m,n)
    d_A = CudaArray(A)
    # test y = alpha*(A*x)
    x = rand(elty,n)
    d_x = CudaArray(x)
    y1 = alpha*(A*x)
    y2 = A*x
    d_y1 = CUBLAS.gemv('N',alpha,d_A,d_x)
    d_y2 = CUBLAS.gemv('N',d_A,d_x)
    h_y1 = to_host(d_y1)
    h_y2 = to_host(d_y2)
    @test_approx_eq(y1,h_y1)
    @test_approx_eq(y2,h_y2)
```

**Comment by ChrisRackauckas** [comment]
The only mention I could find of that functionality is hinted at in the peakflops function on this page: http://julia.readthedocs.org/en/latest/stdlib/linalg/. There is no mention in the parallel computing page http://julia.readthedocs.org/en/latest/manual/parallel-computing/ or the linear algebra page http://julia.readthedocs.org/en/latest/manual/linear-algebra/.

**Comment by johnmyleswhite** [comment]
Arguably this isn't something that should be documented as Julia's behavior since it's really the behavior of OpenBLAS.

**Comment by StefanKarpinski** [comment]
@ChrisRackauckas, where did the impression that Julia was not maxing out a system's cores when doing things like matmul come from? Doing so is a matter of using a well-tuned multithreaded BLAS – which we always have, albeit a different one from Matlab (OpenBLAS vs. MKL). There are other vectorized operations where Matlab has hand-coded implementations in C that use multiple cores, while Julia's implementation, being written in Julia, uses a single core. Often that deficit can be compensated for by devectorizing the code and improving the serial performance. In the future, Julia will support threading natively, and that issue will go away too. The distributed computing issue is largely orthogonal to all of this, but it also important if one wants to do HPC-style work.

**Comment by ViralBShah** [comment]
Once we have multi-threaded Julia, it won't be only hand coded internal functions in C that will be multi-threaded, but the entire Julia Base library. So while we have some distance to cover, we will have something great in the 0.5 timeframe.

**Comment by ChrisRackauckas** [comment]
Thank you for the explanation, that clears it up. I look forward to multi-threaded Julia.

**Comment by ViralBShah** [comment]
This planning issue seems too broad. Does it break into smaller tasks that can have their own issues? I am tempted to close this, and have specific issues dealing with specific problems.

**Comment by ViralBShah** [comment]
I am closing this as very generic. A bunch of specific things are being done already.

**Comment by ChrislS** [comment]
Where will the status of the threading branch be tracked? And what is its current status? That one was very promising! :)

**Comment by ViralBShah** [comment]
#1790
