### ISSUE TITLE
Dummy variable _

### ISSUE THREAD

**Issue by RauliRuohonen** [JuliaLang/julia#9343]
It'd be convenient to have a designated dummy variable `_` (actually keyword), which would simply ignore everything stored into it. For example, you often want to deconstruct tuples like so

```
a, _, b, _, c = f()
```

where the `_` values are uninteresting. Likewise, one may want to ignore function arguments, like so

```
function foo(a, _, b, _, c)
    return (a, b, c)
end
```

This is actually a syntax error right now, because two arguments have the same name, which makes sense if you actually want to read their values. The idea here is to instead discard them, and reading the value of `_` would be a syntax error.

In theory, this is purely about code readability: when one sees `_`, one knows that the value is not used and thus won't need to be thought about any further; OTOH if one sees something else, then the value is probably going to be used further down the line and needs to be kept track of. One also won't need to behold the unsightly output of wetware gensym() implementations in unused function argument names. In practice though, there is also a performance difference with the current compiler:

```
function f1(x1, x2, x3, x4, x5)
    a, _, b, _, c = x1, x2, x3, x4, x5
    return (a, b, c)
end

function f2(x1, x2, x3, x4, x5)
    return (x1, x3, x5)
end

code_native(f1, (Int, String, Int, Int, Int))
code_native(f2, (Int, String, Int, Int, Int))
```

The assembly for f2 is significantly shorter.

**Comment by jakebolewski** [comment]
Closing as this is better handled by forms of static analysis, not syntax.

**Comment by kmsquire** [comment]
@jakebolewski, is there another issue which tracks the static analysis improvements needed for this?  Or would it be better to reopen and change the title (or open another issue)?

**Comment by StefanKarpinski** [comment]
Here's one situation where it could be nice to have an explicitly ignored identifier name:

```jl
julia> foo() do _, _
           println("ignores arguments")
       end
ERROR: syntax: function argument names not unique
```

**Comment by JeffBezanson** [comment]
I'm reopening this, as I've encountered more and more cases where it would be convenient for the front end to be able to emit a pseudo-name for a value that gets ignored.

Example 1: The syntax `f(::T) = ...` is pretty widely used, but internally all function arguments need names. We currently use gensyms for this, but that's wasteful --- the symbols have to be stored, and information about them is tracked even though the names are ultimately never used. Unused variables can only be fully optimized out rather late, and until then we're carrying around baggage.

Example 2: On the jb/functions branch all functions are generic functions, so I want to normalize the syntaxes `f(x)=x` and `x->x` to the same thing as early as possible. It would be convenient to convert the arrow form to `_(x)=x`. If there are many closures in a function they wouldn't conflict, since `_` never actually gets assigned.

There are a few ways in which the full version of this feature is nicer than relying on optimizations:

1. As already pointed out, you could have multiple function argument names called `_` without an error.
2. When debugging you would not see `_` spuriously listed among local variables.
3. Removing stuff as early as possible makes the compiler more efficient.

**Comment by yuyichao** [comment]
This also sounds like a better and more general solution to https://github.com/JuliaLang/julia/issues/12474

**Comment by StefanKarpinski** [comment]
I'm on board. I guess this would conflict with potentially using `_` for [terser lambdas](https://github.com/JuliaLang/julia/issues/5571), although this is always used in lvalue position, whereas that's always in rvalue position.

**Comment by JeffBezanson** [comment]
That would be a bit confusing. It would be nice to be able to give "error: _ used in value position" errors.

**Comment by StefanKarpinski** [comment]
If we allow that, it effectively reserves value position usage of `_`, so that's ok either way.

**Comment by Ismael-VC** [comment]
I was thinking the other day to port a PHP MIT licensed version of gettext to Julia, gettext use `_` (as seen [here](https://en.wikipedia.org/wiki/Gettext#Programming)) instead of `gettext` as a short hand, I would love to have support for something like this in Base (and beyond?) by default allowing Julia to be multilang and also users to be able to make multilang packages. 

I don't know what do you think about this? I haven't mentioned anywhere because I haven't even started implemented it yet, but it's one step in my efforts to explore multilang Julia [here](https://groups.google.com/forum/#!topic/julia-dev/Vu6zyCPkkFs).

I'm just way too slow, wish I had more time.

**Comment by nalimilan** [comment]
+1 for gettext integration, but `_` should probably not be defined by default, as it is currently used for values you don't care about. As regards licensing issues, porting the MIT PHP gettext (I guess you mean [this one](https://github.com/oscarotero/Gettext/tree/master/src)?) will take a lot of work and be a maintenance burden in the future. I'd rather see how far we can get using [NetBSD's libintl](https://wiki.netbsd.org/projects/project/libintl/), which should work except for the most recent gettext features.

**Comment by Ismael-VC** [comment]
@nalimilan yes I was talking about that PHP implementation, it's the only MIT licensed one I found which looked self contained. I'll experiment with `libintl`. I'm not an expert in this so I would really appreciate a lot if you could drop by anytime you want at [Julia-i18n](https://gitter.im/JuliaLangEs/julia-i18n) chat room if you like and share more of your thoughts.

Thanks for your advice!

**Comment by Ismael-VC** [comment]
Actually `Gettext` uses `@__str` macro!

```
using Gettext

bindtextdomain("sample", "po/")
textdomain("sample")

println(_"Hello, world!")
```

I wonder about it's performance.

**Comment by nalimilan** [comment]
The non-standard string literall `_""` sounds like a good solution. I don't have much more advice to give, as I don't know libintl at all. I'd simply try to wrap it and see whether you can replicate enough of the features offered by Gettext.jl.

**Comment by Ismael-VC** [comment]
Thank you, I'll try to do that.

**Comment by vtjnash** [comment]
it seems most of the goals of https://github.com/JuliaLang/julia/issues/9343#issuecomment-163031697 were implemented (via the hidden symbol '#unused#') in jb/functions (and improved upon in jb/linear3)

**Comment by SrAceves** [comment]
Following on @vtjnash's comment, for `f -> x, y, z` des this work? `##, ##, z = f() '. Also, why not index the function's output, say ` z = f()[3]`?

**Comment by StefanKarpinski** [comment]
If we're going to do this then perhaps using `_` as an r-value should become a syntax error?

**Comment by Keno** [comment]
yes

**Comment by mauro3** [comment]
(remove "won't fix" label?)

**Comment by StefanKarpinski** [comment]
Then the first steps for 0.6 are:

- deprecate using `_` as an r-value
- allow using `_` multiple without warning (i.e. implement #18251)

This allows people to start using `_` as a dummy variable in 0.6. It will still hold a value, which means that code using it won't break – it will just cause a warning (unless deprecations are off). Then in 1.0 it can be changed to discard assigned values entirely and using it as an r-value will be an error.

**Comment by Keno** [comment]
Do we really need to go through that kind of deprecation cycle for this? I suspect very few people are using `_` in a way that would be incompatible with this change and for those that are, there is a few clear change that can be made to fix it.

**Comment by StefanKarpinski** [comment]
Sure, we could skip the deprecation cycle and just make it an error right away.

**Comment by stevengj** [comment]
As mentioned in #20446, another possible use of `_` would be as a wildcard in things like `Array{_,3}`

**Comment by quinnj** [comment]
It'd be nice for `f(a, _, c)` `_` function arguments, to actually lower to `@nospecialize(_)`.
