### ISSUE TITLE
Parsing of multi-line comment gives error if `"#="` is inside the comment block

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/julia#9517]
This gives a syntax error
```julia
#=
"#="
=#
```
and also this:
```
#=
#=
=#
```
It seems that the parser parses recursive with `#=` even though it is the enclosing that should determine the comment block.

**Comment by elextr** [comment]
@Ismael-VC just to support @JeffBezanson 'won't fix', note that the "unterminated" comment will almost certainly not be anywhere near the problem, it will always be the outermost opening comment, which is probably the one you put in to comment out the block of code.  Same problem occurs with mismatched {} in C like languages.

**Comment by Ismael-VC** [comment]
@elextr I see, that indeed does make sense, thanks for the explanation!

**Comment by timholy** [comment]
Given that many seem not to like multiline comments (I'm in that camp, too), is there any realistic path to removing them? Or are we basically stuck with them?

**Comment by Ismael-VC** [comment]
@elextr  I see what you mean:

> Disabling of blocks of code can always be fooled.

I've just tested in Java and other languages that support multi-line comments:

```java
public class HelloWorld{
     public static void main(String []args){
        /*
        System.out.println("Hello */ World");
        */
     }
}
```
```julia
julia> #=
       println("Hello =# World")
       =#

ERROR: syntax: incomplete: invalid string syntax
```

On the other side, while I've seen many newbie errors, I've never ever seen this error in Java in the wild. It's true that the Julia example breaks, but programmers just have to know why it's breaking and could avoid using `=#` inside a Julia string. 

@timholy

> Given that many seem not to like multi-line comments (I'm in that camp, too), is there any realistic path to removing them? Or are we basically stuck with them?

How many are you assuming are *many*? Just those among the developers?, Why not make a poll to the community for things like this? It's not like you have to do what the majority wants, but at least you'll have a better idea of it.

Just as an example: http://quorumlanguage.com/evidence.php

Before considering removing them, could you first consider what would be a Julian alternative for disabling (large) blocks of code (and document it), `#` in front of every line?  (with editor support that is easy, but that's assuming you have it already configured, or have the time to do it (I'm thinking in the situation when one has to use a borrowed computer or has to use a public one.)

This perhaps:

```julia
if false
    # lots of code
    println("Hello world")
    # lots of code
end
```

I don't like that option. Which was the consideration to add this feature to the language in the first place?

I mention this because I feel that in Julia we also care about the human factor, not just in the machine and performance. Devs don't forget about us mere mortals! :P

**Comment by dhoegh** [comment]
@Ismael-VC does it also gets folled with this?
```
public class HelloWorld{
     public static void main(String []args){
        /*
        System.out.println("Hello /* World");
        */
     }
}
```
Since it is a begin comment I have in the original example.

**Comment by timholy** [comment]
No one is forgetting "mortals" (we are all mortal), but I guess I'm assuming that editor support is a given. For the history, you can search closed issues and pull requests for multiline comments; you can see it was a hard call.

Regarding the poll, that's interesting, but there is no reason to conduct such a poll if there isn't a reasonably "safe" way to remove them (i.e., with deprecation warnings, etc) and enough motivation by someone who will do the work (I won't, I'm not a parser guy).

**Comment by ul** [comment]
Actually, fixing this issue would enable very nice pattern:

```julia
#=
the block is commented
=#
```

```julia
#=
the block is uncommented
#=#
```

As you can see, it allows to comment/uncomment arbitrary large block by changing only one symbol! Haskell supports similar trick, but by changing opening:

```haskell
{--
commented
--}
```

```haskell
--{--
uncommented
--}
```
