### ISSUE TITLE
better warning for commands instead of strings

### ISSUE THREAD

**Issue by iwelch** [JuliaLang/julia#9660]
if someone uses

   open("cat file.csv")

that is, a filename that contains a space and that has resulted in a file-not-found error, and thus looks like a possible attempt at a command, could the error message ask

    "did you mean to use backquotes for a command instead of string quotes for a filename?"

regards,

/iaw

**Comment by elextr** [comment]
You would only want such a message if the argument to the `open()` call was a literal string.  It would not make sense if the argument is a variable containing a string.  But (as far as I know) there is no way for open to detect that the argument is a literal or not.

**Comment by iwelch** [comment]
novice question---why?

if we are already in an error situation, adding a hint for a common mistake
after the first error wouldn't be so bad (assuming the internal coding in
iostream.jl:122 makes this easy).

x="echo hi"
open(x)

regards,

/iaw


----
Ivo Welch (ivo.welch@gmail.com)
http://www.ivo-welch.info/
J. Fred Weston Professor of Finance
Anderson School at UCLA, C519
Director, UCLA Anderson Fink Center for Finance and Investments
Free Finance Textbook, http://book.ivo-welch.info/
Editor, Critical Finance Review, http://www.critical-finance-review.org/

**Comment by elextr** [comment]
[Warning: pet hate triggered :) ]

Because it includes a message about a theoretical programmer error (possibly meaning to use backslashes) in a message about a user error (wrong filename).  Users should not be bothered by irrelevant messages.

A common use of open is where the filename string is passed to a function:

    function do_stuff_to_file(f::string)
        do_stuff(open(f))
    end
    do_stuff_to_file("my misytped Julia data filename with spaces")

This is likely to be far more common than meaning to run a command and forgetting to use backquotes since opening files is very common.  There is no way the function user could use a command, so why spam them with irrelevant messages.

The reason I might allow it if its a literal string is that in this case the filename is fixed and programmer specified.  So the fact that it can't be opened is more likely to be a programmer error.  But as I said I don't know if it is possible to distinguish.

**Comment by JeffBezanson** [comment]
If you look at `base/replutil.jl`, there are many cases where people have hacked in helpful suggestions to go with various errors. We will accept pull requests there if people generally agree they are helpful.

However I think this particular case is a bit marginal; trying to guess that somebody meant to do something different because a file wasn't found is not too compelling to me.

**Comment by ivarne** [comment]
There is nothing that prevents you from only issuing the help if if the filename begins with `cat `, or another common Unix utility followed by a space. If you think such a change is worth your time, it should be easy for us to review and merge a PR.

**Comment by iwelch** [comment]
that's a good idea, but I am completely overwhelmed this quarter.  so I
don't have the time to learn this right now.  maybe next quarter.  regards,
/iaw


----
Ivo Welch (ivo.welch@gmail.com)
http://www.ivo-welch.info/
J. Fred Weston Professor of Finance
Anderson School at UCLA, C519
Director, UCLA Anderson Fink Center for Finance and Investments
Free Finance Textbook, http://book.ivo-welch.info/
Editor, Critical Finance Review, http://www.critical-finance-review.org/
