### ISSUE TITLE
test_throws message confuses me

### ISSUE THREAD

**Issue by matrixmorpheus** [JuliaLang/julia#9686]
There’s nothing I can say that will explain it for you. See for yourself.

julia> @test_throws DomainError throw(DomainError)
ERROR: test failed: DomainError was thrown instead of DomainError
 in expression: throw(DomainError)
 in error at error.jl:21
 in default_handler at test.jl:27
 in do_test_throws at test.jl:69

**Comment by ihnorton** [comment]
The issue is that `run_test_throws` checks `isa` not `is` -- it only checks whether the thrown error is an instance of the given type, but not the type itself. This works:

`@test_throws DomainError throw(DomainError())`

It's an easy chage, but I'm not really sure if there might be some other implication.

**Comment by ivarne** [comment]
That message is really confusing. It should be pretty simple to check `is` when `isa` is false and instruct the caller to throw an instance instead of  a type.

@StefanKarpinski is it considered valid to `throw` a type?

**Comment by JeffBezanson** [comment]
Julia makes it too easy to define

```
error{E<:Exception}(::Type{E}) = throw(E())
```

and so in some places the idiom `error(DomainError)` is used. I've never liked this however.

**Comment by ivarne** [comment]
See also https://github.com/JuliaLang/julia/pull/9690
