### ISSUE TITLE
Question: function parameters with static multiple types? (or partial dynamic types)

### ISSUE THREAD

**Issue by ifmihai** [JuliaLang/julia#9730]
First, I'm a newbie, python average programmer.

What I want to ask, I better give an example, as I don't know names for key terms:

in julia we have:

```julia
function myinc(x::Int)
  x + 1
end
``` 

Would it be advantageous to have the following?

```julia
function myinc(x::[Int, Float64])
 return x + 1
end
```

Because usually, in my user cases in python, I always have at most 3 types possible.
Static typing being the most restrictive.
Dynamic typing giving too much freedom.
And I was wondering about a middle area between these two.

I'm curious at least about opinions of julia's devs, how you see this idea

**Comment by JeffBezanson** [comment]
We have `function myinc(x::Union(Int,Float64))`, if you want the argument to be either an Int or Float64. But I would encourage using the biggest type that makes sense, e.g. `function myinc(x::Number)`.

**Comment by JeffBezanson** [comment]
I'm going to close this issue, since this is more of a question that would be appropriate for the mailing lists, and not really an issue report.

**Comment by quinnj** [comment]
Just to add one more comment:

In Julia, specialized methods will be compiled for each concrete type that a function sees. In your case,
```julia
function myinc(x)
    x + 1
end
```
given the above function definition (with no restriction on the type of `x`, or even using `Number` as suggested by Jeff), separate methods will be compiled for
```julia
myinc(1)
```
and
```julia
myinc(1.0)
```
as can be seen from the output of `@code_llvm`, which shows the LLVM IR code compiled for a method invocation
```julia
julia> @code_llvm myinc(1)

define i64 @julia_myinc_22188(i64) {
top:
  %1 = add i64 %0, 1, !dbg !363
  ret i64 %1, !dbg !363
}

julia> @code_llvm myinc(1.0)

define double @julia_myinc_22226(double) {
top:
  %1 = fadd double %0, 1.000000e+00, !dbg !363
  ret double %1, !dbg !363
}
```
The first method compiles code specifically for an `Int64` concrete input type (since my system is 64-bit), while the 2nd method is compiled specifically for `Float64`.

Anyway, hopefully that helps provide a little insight on what Julia's actually doing with function declarations.
