### ISSUE TITLE
Antivirus complains about julia/contrib/windows/7zS.sfx

### ISSUE THREAD

**Issue by n-riesco** [JuliaLang/julia#9845]
ClamAV and McAfee-GW-Edition  complain about julia/contrib/windows/7zS.sfx

See the following analysis in VirusTotal 

https://www.virustotal.com/en/file/ec2094909fbf6040c450488cb403d822f8ee867becfd9d319094313f0e022fa3/analysis/

**Comment by tkelman** [comment]
That's annoying. cc @ihnorton is the only person to have touched that file. Apparently it required some modifications relative to the upstream version?

**Comment by ihnorton** [comment]
Damned if you do, damned if you don't. I modified this file to avoid the Program Compatibility Assistant warnings, see explanation [here](https://github.com/JuliaLang/julia/commit/2f26857aad8fdb9483c3f1babbb5b8b6a4b0ea55).

You can compare  the hex yourself with the upstream to verify that is the only modification - I don't remember the exact details but it is one or two fields in the PE header. See the link to MSDN from the commit message above.

Does the original 7zS.sfx trigger the warning as well? I wouldn't be surprised if it does, because that self-extractor is probably used by many low-rent viruses. Either way, I don't think there is anything we can do about this, so I am going to close this issue. I would suggest to add it to the exclusion list if you are satisfied with the explanation.

**Comment by ViralBShah** [comment]
The Julia virus. All your cycles are belong to us!

**Comment by n-riesco** [comment]
Just for the record: I've checked and the previous commit gets 6 antivirus complaints:

https://www.virustotal.com/en/file/acc12db90679f52aaef5cea2cd6c29f60cbe74de2521a10263f919a16f6103e0/analysis/1421742419/
