### ISSUE TITLE
Floating point bitwise operations

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#9868]
(from discussion on [julia-dev](https://groups.google.com/d/topic/julia-dev/5y1y6Uj8T1A/discussion))

In certain algorithms (particularly double-double style arithmetic) it is necessary to and/or individual bits of a floating point number. At the moment, the easiest way to do this in Julia is something like:

``` julia
bittrunc(x::Float64) = reinterpret(Float64,reinterpret(UInt64,x) & 0xffff_ffff_0000_0000)
```

 The `code_native` of this seems to indicate that this is basically what the compiler ends up doing as well.

However x86 offers native bitwise instructions for floats (ANDPD, etc.): it would be useful to have someway to use these via Julia. Ideally, the above code would automatically do this, but at the moment LLVM doesn't seem to be able to manage it. 

LLVM seems to make these operations available via `FAND`, `FOR`, etc for the X86 backend:
http://llvm.org/docs/doxygen/html/namespacellvm_1_1X86ISD.html#ab81d298b0f48499395110a6055048b28aed927d0ca1203766de671e7437d658b2

One option suggested by @eschnett is to overload `&` and `|` for floats.

**Comment by ArchRobison** [comment]
I'm against overloading `&` and `|` to do this since their use with floating-point is for specialists, and it will make accidental use by everyone else harder to track down.

The `reinterpret`-style code seems like the right direction.  We just have to get the X86 backend to recognize the pattern.  I'm not an expert on the LLVM backend technology, but it seems to be designed to recognize LLVM IR instruction patterns in a basic block, so this ought to be doable in a straightforward way.

**Comment by nalimilan** [comment]
> I'm against overloading & and | to do this since their use with floating-point is for specialists, and it will make accidental use by everyone else harder to track down.

There have been discussions of changing the bitwise operators to something else: https://github.com/JuliaLang/julia/issues/9711#issuecomment-69484081 (I can't find the other references). This would have the advantage of also protecting most users from these functions when using integers. After all, there's no reason only floats should be safe from unexpectedly using bitwise operations.

**Comment by StefanKarpinski** [comment]
I don't know about this. I agree that bitwise operations are not a great use of ASCII characters, but what else are we going to use them for? The only thing that comes to mind is using `|` and `&` for commands and piping like we used to.

**Comment by jakebolewski** [comment]
`|` could be used for piping commands, `&` could be used as sugar for `Ref` or `Box` as @vtjnash outlined here https://gist.github.com/vtjnash/7296634.

**Comment by StefanKarpinski** [comment]
@ArchRobison, the problem with the reinterpret approach is that LLVM isn't currently smart enough to replace type casts + integer bitwise operations with floating-point bitwise operations. If it were, this wouldn't be an issue in the first place. Ideally that would be the better way to handle this and we wouldn't have to do anything at all on the Julia side. I'm not sure what the harm of supporting bitwise operations on floating-point values is though. It saves a bunch of annoying reinterpreting back and forth. I really don't feel like accidentally anding or oring floats is a big problem – especially since if someone does write that, this would do exactly what they probably want to do anyway.

**Comment by nalimilan** [comment]
> I don't know about this. I agree that bitwise operations are not a great use of ASCII characters, but what else are we going to use them for? The only thing that comes to mind is using | and & for commands and piping like we used to.

@StefanKarpinski Element-wise operations, as currently. That's what @elextr suggested in the thread I referred to. One of the reasons for this idea is that operator precedence is not ideal for this case ATM (https://github.com/JuliaLang/julia/issues/5187).

**Comment by StefanKarpinski** [comment]
We could just change the precedence and leave the meaning as is.

**Comment by nalimilan** [comment]
> We could just change the precedence and leave the meaning as is.

Sure.

But I know that for many people with a background in stats and not in CS, `1 & 3 == 1` is quite puzzling, when all they use `&` for is element-wise boolean operations. Bitwise operations on floats will increase the surprise a bit more. But they can certainly live with that, it just makes teaching a bit harder.

**Comment by ArchRobison** [comment]
I was too brief in my comment about fixing the LLVM pattern matcher.   `FAND` and `FOR` are not part of the LLVM IR and there are currently no LLVM operations or intrinsics (as far as I can tell) for directly accessing them.  They are currently used only for lowering of fabs and fneg(fabs(...)).  To get to them more generally would require us to either introduce new LLVM intrinsics or extend the pattern matching in the backend.  The LLVM community resists adding intrinsics when there is a short basic-block sequence that can do the same, since the pattern-matching stuff in the backend is built to recognize such sequences.

I'll check with some of our LLVM experts.  Maybe there's a gotcha that makes compiling the pattern difficult.

**Comment by StefanKarpinski** [comment]
Thanks for the explanation, @ArchRobison. Given that situation, adding more pattern matching to the backend is clearly the better way to go.

**Comment by vtjnash** [comment]
OT: In that julep, I'm eliminating the need for special syntax. I'm not looking to add it back

**Comment by simonbyrne** [comment]
Thanks @ArchRobison. I think we should avoid bitwise float operations if we can.

**Comment by ArchRobison** [comment]
I'm probably not going to have time to look at this much further.  Here's "pirate map" for anyone trying to do it.

It turns out that it's easy to modify the X86 backend (see `PerformAndCombine` in `X86ISelLowering.cpp`) to make LLVM to emit `ANDPS` when both arguments to `and` are `bitcast`     The gotcha is dealing with the case where an operand is a constant, which is exactly the case that we are  interested in.  The IA-32 instruction `ANDPS` does not have a form that takes an immediate operand, so the constant has to be loaded from memory.   Depending on how instructions are scheduled, that load may make the use of `ANDPS` instead of `AND` a wash.

There's logic in `lib/Transforms/Scalar/ConstantHoisting.cpp` for hoisting expensive integer constants, but I don't understand if it has the context-sensitivity required for the `and` example..

**Comment by eschnett** [comment]
The bitwise floating-point operations can easily be accessed from `C` via the intrinsics defined in `emmintrin.h`. The intrinsics defined there include `_mm_add_sd`, `_mm_add_pd`, and `_mm_and_pd`. Note there is no `_mm_and_pd`, i.e. the only intrinsic available needs to work on a vector type.

The `_mm_and_pd` intrinsic is defined as follows:
```
static __inline__ __m128d __attribute__((__always_inline__, __nodebug__))
_mm_and_pd(__m128d __a, __m128d __b)
{
  return (__m128d)((__v4si)__a & (__v4si)__b);
}
```
That is, the implementation is straightforward -- it just relies on the built-in `&` operator, with the arguments reinterpreted as 4-element vector of integers.

We could thus implement bitwise floating-point operations by expanding the scalar operands to vectors, and extracting the scalar result afterwards. We can extend the mask to either leave the other vector elements unchanged, or to ensure they are zero.

In fact, I observe that vectorized loops (`@simd`) already use the bitwise floating-point instructions just fine.

**Comment by StefanKarpinski** [comment]
@eschnett, are you suggesting going through C to use these instructions? If so, that would not be a win for performance.

**Comment by eschnett** [comment]
@StefanKarpinski No, I am suggesting to use the same mechanism that is used in these intrinsics. That is, instead of emitting a scalar `&`, we emit a conversion scalar->vector, a vector `&`, and then extract the result from the vector. This doesn't require looking too deep into LLVM, as it requires only standard LLVM bitcode instructions.

**Comment by ArchRobison** [comment]
Nice!  It didn't cross my mind that LLVM recognized the vector version of the pattern, but it makes sense in retrospect since there is no scalar version of the SSE `ANDPD`.  This was so cool I had to try it :smile: :
```
$ cat fand.ll
define double @foo(double %a, double %b) {
  %av = insertelement<2 x double> undef, double %a, i32 0
  %bv = insertelement<2 x double> undef, double %b, i32 0
  %ai = bitcast <2 x double> %av to <2 x i64>
  %bi = bitcast <2 x double> %bv to <2 x i64>
  %and.i = and <2 x i64> %ai, %bi
  %cf = bitcast <2 x i64> %and.i to <2 x double>
  %cfe = extractelement<2 x double> %cf, i32 0
  ret double %cfe
}

$ llc -O3 fand.ll
$ cat fand.s
        .text
        .file   "fand.ll"
        .globl  foo
        .align  16, 0x90
        .type   foo,@function
foo:                                    # @foo
        .cfi_startproc
# BB#0:
        andps   %xmm1, %xmm0
        retq
.Ltmp0:
        .size   foo, .Ltmp0-foo
        .cfi_endproc


        .section        ".note.GNU-stack","",@progbits
```

**Comment by ArchRobison** [comment]
On the subject of naming, `and_float`, `or_float`, and `xor_float` would be consistent with  the names `and_int`, `or_int`, and `and_int` in `base/boot.jl`.  Though the ...`_int` functions are intrinsics not seen by users.  I see the names `and`, `ior`, and `xor` in `base/gmp.jl`.  [Note the i in ior].

Using `&`, `|`, and `^` still bothers me.  I can explain to high school students what bitwise ops do to binary integers, e.g. x&1 checks if x is odd. and x$-1 is equivalent to -1-x.  But bitwise ops on floating point numbers is a much trickier -- source code should be clear that tricky stuff is going on.   

I can't imagine a practical generic function that would use bitwise ops on both int and float arguments, because int is 2's-complement, but float is sign-magnitude.

**Comment by StefanKarpinski** [comment]
> I can't imagine a practical generic function that would use bitwise ops on both int and float arguments, because int is 2's-complement, but float is sign-magnitude.

This is a good point. Let's leave that out for now and just add the intrinsics.

**Comment by simonbyrne** [comment]
Nice! We can even implement this all using `llvmcall`
```julia
function and_float(x::Float64,y::Float64)
       Base.llvmcall("""%av = insertelement<2 x double> undef, double %0, i32 0
         %bv = insertelement<2 x double> undef, double %1, i32 0
         %ai = bitcast <2 x double> %av to <2 x i64>
         %bi = bitcast <2 x double> %bv to <2 x i64>
         %and.i = and <2 x i64> %ai, %bi
         %cf = bitcast <2 x i64> %and.i to <2 x double>
         %cfe = extractelement<2 x double> %cf, i32 0
         ret double %cfe""",Float64,(Float64,Float64),x,y)
end
```

Are there any architectures we target for which this would be problematic?

**Comment by eschnett** [comment]
I'm afraid that this may make things slower if moving data between scalar and vector FPU registers is slow, or if the CPU does not have vector instructions, or if this prevents LLVM from vectorizing code. These may be all architectures that are not Intel, pre-SSE Intel architectures, as well as Intel architectures when `@simd` is used...

Intel is special in that a vector-and is faster than a scalar-and, while LLVM does not know how to generate this (it should). If vector-and is slower than a scalar-and, then either LLVM needs to undo the transformation above, or the code will be slower. Also, if one uses vector instructions in a loop, it is likely that LLVM won't vectorize the loop (we should check this).

It may be that using 4-element vectors is significantly faster than using 2-element vectors when the Intel CPU has AVX instructions. We'd need to test this as well.

**Comment by simonbyrne** [comment]
Well, it does seem to give a fairly good speed boost:
https://gist.github.com/simonbyrne/62f25608aaf831de5996

It's tough to compare such basic operations, but it seems to be at least 30-40% faster than using the integer ops.

**Comment by eschnett** [comment]
That's a nice speed-up. I looked at `code_native`, and the generated code is good.

The code here is not vectorizable, so we don't know yet whether this trick inhibits vectorization.

**Comment by ArchRobison** [comment]
I tried vectorizing it: https://gist.github.com/ArchRobison/cb1aab380905fdc1255f
Alas the trick in `t4` thwarts vectorization that otherwise happens (very nicely) with `t3`.

**Comment by simonbyrne** [comment]
That's a pity, but I guess this is something that really should be handled by LLVM anyway.

**Comment by eschnett** [comment]
Julia could make this transformation using a heuristic: Apply the transformation if
- the CPU is Intel
- the CPU has SSE instructions
- the code does not appear inside an `@simd` block

This may still destroy some vectorization opportunities where LLVM would vectorize even without `@simd` present.

Is there an LLVM performance bug report open for this?

**Comment by eschnett** [comment]
I have opened <http://llvm.org/bugs/show_bug.cgi?id=22428> for this.

**Comment by simonbyrne** [comment]
Thanks @eschnett

**Comment by simonbyrne** [comment]
Based on the upstream bug report, this hopefully should have been fixed on the LLVM development branch, though not on 3.7.1.

**Comment by tkelman** [comment]
Will there be a way to unit test this or will it only show up in benchmark results?

**Comment by KristofferC** [comment]
`andpd` is now being generated.
