### ISSUE TITLE
Index conversion of multidimensional arrays

### ISSUE THREAD

**Issue by hofmannmartin** [JuliaLang/julia#9919]
A couple of days ago I had an issue, where I wanted to find the position of a maximum in a multidimensional array. However the function indmax returns the flattened index. So I was wondering if there is a function converting to a multidim index?

Something like:
```julia
function index_to_multiindex(index::Integer,A::AbstractArray)
  idx = zeros(typeof(index),ndims(A))
  stridesA = strides(A)
  for i=ndims(A):-1:1
    idx[i] = div(index-1,stridesA[i])+1
    index += -(idx[i]-1)*stridesA[i]
  end
  return idx
end
```

However, i still would something like A[index_to_multiindex(i,A)] to work. Instead I have to do getindex(A,index_to_multiindex(i,A)...). Any suggestions?

**Comment by tknopp** [comment]
- There is ind2sub which does basically what `index_to_multiindex` does (but its tuple based)

- if you have an array A of dim 2, `A[index]` will do linear indexing so you can directly use the index from `maximum` without the need to convert to a multiindex

- Instead of `getindex(A,index_to_multiindex(i,A)...)` you can use `A[index_to_multiindex(i,A)...]`. The splatting of the array/tuple is required however.

**Comment by hofmannmartin** [comment]
* Thanks for the answer. I was not aware of `ind2sub`, but of linear indexing.

* I just thought, that `A[ind2sub(size(A),i)]` should return `A[i]`. But i expect this would be in conflict with the current behaviour.
