### ISSUE TITLE
Tail recursion memory error

### ISSUE THREAD

**Issue by melvin0008** [JuliaLang/julia#9920]
The below function causes my ubuntu to crash at factorial of 75000
```
function fact(acc::BigInt,n)
    (n == 0) ? acc : fact(acc*n,n-1)
end
```
The same function in Haskell works really well . Takes 7.78 seconds on the same machine for factorial of 1,00,000 
```
factorial :: (Integral a)=> (a,a) -> a
factorial (0 , acc)= acc
factorial (n , acc) = factorial (n-1,acc * n)
```

Any idea why?

**Comment by ivarne** [comment]
Dup of https://github.com/JuliaLang/julia/issues/4964. You currently need to write a loop in Julia for such deep recursions.

**Comment by melvin0008** [comment]
Thanks.

**Comment by xanderdunn** [comment]
You can work around this and maintain a recursive style using the `@rec` from [Lazy.jl]():

foobar.jl
```julia
module foobar

using Base
import Base: range
import Lazy: @rec

@rec recursive_factorial(n::Real, a::Real) = (n == 0) ? a : recursive_factorial(n-1, a*n)

function iterative_factorial(n::Real)
    result = BigInt(1)
    for i in range(1, n)
        result *= i
    end
    result
end

end # module
```

runtests.jl
```julia
using foobar
import foobar: recursive_factorial, iterative_factorial
using Base.Test

# write your own tests here
@test 1 == 1

x = BigInt(1000000)

base_time = @timed factorial(x)
println("Base = $(base_time[2])")

recursive_time = @timed recursive_factorial(x, 1)
println("Recursive = $(recursive_time[2])")

iterative_time = @timed iterative_factorial(x)
println("Iterative = $(iterative_time[2])")

@test base_time[1] == recursive_time[1] == iterative_time[1]
```

Output:
```
Base = 0.477305071
Recursive = 517.544341882
Iterative = 491.569636915
```

So, the recursive factorial function is slightly slower than the iterative function.  These two hand crafted functions are both much slower than the built-in `factorial` because [Base uses some lookup table magics](https://github.com/JuliaLang/julia/blob/85482e59234936884b2b55b6efb4a731629fd939/base/combinatorics.jl).
